### PR TITLE
udevadm: return earlier when non-root users invoke trigger command

### PR DESCRIPTION
**Pull request by yuwata**
After commits 569ad251adde02dc0915758fe027e0346e50738a and 67acde4869a9505f9721e31fa5167c82445e0e12, -EACCES errors are ignored, and thus 'udevadm trigger' succeeds even when it is invoked by non-root users. Moreover, on -EACCES error, log messages are shown in debug level, so usually we see no message, and users are easily confused why uevents for devices are not triggered.

### CODE REVIEW

**Comment by keszybz** [comment]
The commit message clearly shows that the problem is with logic that doesn't emit proper error messages in certain cases. Even if running as root, permission might be denied by mac. So we need to have proper error messages in that path too. And if that is fixed, the issue for non-root users goes away.

**Comment by yuwata** [comment]
@keszybz Thank you for the comment. Updated. Now only -ENOENT is logged in debug level, and if we get -EACCES, -ENODEV, or -EROFS, then consequent devices are skipped and return earlier. PTAL.

**Comment by keszybz** [comment]
Hmm, looking at this again, I think 67acde4869a9505f9721e31fa5167c82445e0e12 is wrong. I know I merged it, but in retrospect it seems to lead us down a path where we can't do the right thing. A user says `udevadm trigger` and now we try to guess whether to ignore failure or not. If the user is actually depending on the trigger happening, they will be rightfully unhappy. There is simply no way we can get this game of guesswork right. Instead, the *caller* must ignore the result if they are in a scenario where they are not sure if they have privileges to emit the call and want to ignore the result if not. The caller knows whether the call is just "best effort" or something that matters.

#13652 was reported because in an lxc container, `/sys` is not set up properly. Either that should be fixed or Ubuntu should adjust `systemd-udev-triger.service` so that it doesn't fire under lxc.

(Also note that in Fedora, all package scriptlets are supposed to ignore failure and suppress errors for such cases where operations are expected to fail in certain setups. The same should be done in Ubuntu, which would fix the original issue independently.)

/cc @ddstreet

**Comment by yuwata** [comment]
@keszybz and @ddstreet Another version is pushed to #17192. PTAL.

**Comment by keszybz** [comment]
Obsoleted by #17192.

**Pull request closed without merging**
