### PR TITLE
test: support QEMU on other architectures

### PR DESCRIPTION
**Pull request by mrc0mmand**
Let's continue with the efforts attempted in #12884 regarding running QEMU on s390x and aarch64 in Ubuntu CI. As the QEMU is completely broken on s390x there, and probably misconfigured on aarch64, it's going to need some tweaking from the Ubuntu side as well.

[s390x:](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/s390x/s/systemd-upstream/20190701_195118_baadc@/log.gz)

```
TEST RUN: test migrating state directory from DynamicUser=1 to DynamicUser=0 and back
+ /usr/bin/qemu-system-s390x -smp 1 -net none -m 512M -nographic -kernel /boot/vmlinuz-4.15.0-54-generic -drive format=raw,cache=unsafe,file=/var/tmp/systemd-test.oAVz6V/rootdisk.img -initrd /boot/initrd.img-4.15.0-54-generic -append 'ro root=/dev/sda1 raid=noautodetect loglevel=2 init=/lib/systemd/systemd console=ttyS0 selinux=0 printk.devkmsg=on   '
The Linux kernel requires more recent processor hardware
Detected machine-type number: 2064
Missing facilities: 18,21,25,27,32,33,34,35,45,49,52
See Principles of Operations for facility bits
ls: cannot access '/var/tmp/systemd-test.oAVz6V/journal/*/*.journal': No such file or directory
Makefile:4: recipe for target 'run' failed
make: Leaving directory '/tmp/autopkgtest.9epIvk/build.vSC/systemd/test/TEST-34-DYNAMICUSERMIGRATE'

...

+ /usr/bin/qemu-system-s390x -smp 1 -net none -m 512M -nographic -kernel /boot/vmlinuz-4.15.0-54-generic -drive format=raw,cache=unsafe,file=/var/tmp/systemd-test.QFcdlH/rootdisk.img -numa node,nodeid=0 -initrd /boot/initrd.img-4.15.0-54-generic -append 'ro root=/dev/sda1 raid=noautodetect loglevel=2 init=/lib/systemd/systemd console=ttyS0 selinux=0 printk.devkmsg=on   '
..//test-functions: line 117: 13931 Segmentation fault      (core dumped) $QEMU_BIN $QEMU_OPTIONS -append "$KERNEL_APPEND"
E: QEMU failed with exit code 139
ls: cannot access '/var/tmp/systemd-test.QFcdlH/journal/*/*.journal': No such file or directory
Makefile:4: recipe for target 'run' failed
make: Leaving directory '/tmp/autopkgtest.9epIvk/build.vSC/systemd/test/TEST-35-NUMAPOLICY'
make: *** [run] Error 1

FAILED TESTS:  test/TEST-01-BASIC test/TEST-04-JOURNAL test/TEST-05-RLIMITS test/TEST-08-ISSUE-2730 test/TEST-09-ISSUE-2691 test/TEST-11-ISSUE-3166 test/TEST-14-MACHINE-ID test/TEST-18-FAILUREACTION test/TEST-19-DELEGATE test/TEST-20-MAINPIDGAMES test/TEST-23-TYPE-EXEC test/TEST-24-UNIT-TESTS test/TEST-25-IMPORT test/TEST-26-SETENV test/TEST-27-STDOUTFILE test/TEST-28-PERCENTJ-WANTEDBY test/TEST-29-UDEV-ID_RENAMING test/TEST-30-ONCLOCKCHANGE test/TEST-31-DEVICE-ENUMERATION test/TEST-32-OOMPOLICY test/TEST-34-DYNAMICUSERMIGRATE test/TEST-35-NUMAPOLICY

```

[aarch64:](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/arm64/s/systemd-upstream/20190701_220418_baadc@/log.gz)
```
+ timeout --foreground 180 /usr/bin/qemu-system-aarch64 -smp 1 -net none -m 512M -nographic -kernel /boot/vmlinuz-4.15.0-54-generic -drive format=raw,cache=unsafe,file=/var/tmp/systemd-test.M5PUC0/rootdisk.img -initrd /boot/initrd.img-4.15.0-54-generic -append 'ro root=/dev/sda1 raid=noautodetect loglevel=2 init=/lib/systemd/systemd console=ttyS0 selinux=0 printk.devkmsg=on   '
qemu-system-aarch64: -nographic: No machine specified, and there is no default
Use -machine help to list supported machines
```

cc @ddstreet @evverx

### CODE REVIEW

**Comment by cpaelzer** [comment]
I think you are running s390x in emulation (not full HW virt) and in there the max supported machine level IIRC was z900 (really old).

But the Ubuntu kernel is built with minimal arch level set of zEC12 which needs a few more chip features.

```
grep -e '^C.*MARCH' /boot/config-4.15.0-53-generic
CONFIG_HAVE_MARCH_Z900_FEATURES=y
CONFIG_HAVE_MARCH_Z990_FEATURES=y
CONFIG_HAVE_MARCH_Z9_109_FEATURES=y
CONFIG_HAVE_MARCH_Z10_FEATURES=y
CONFIG_HAVE_MARCH_Z196_FEATURES=y
CONFIG_HAVE_MARCH_ZEC12_FEATURES=y
CONFIG_MARCH_ZEC12=y
CONFIG_MARCH_ZEC12_TUNE=y
```

 OTOH newer qemu might be able to run [more emulated facilities and newer chips](https://wiki.qemu.org/Documentation/Platforms/S390X), I haven't checked that in detail for a while.

I was able to reproduce it on s390x when not using -enable-kvm
```
sudo /usr/bin/qemu-system-s390x -smp 1 -net none -m 512M -nographic -kernel /boot/vmlinuz-4.15.0-54-generic 
[sudo] password for ubuntu: 
The Linux kernel requires more recent processor hardware
Detected machine-type number: 2064
Missing facilities: 18,21,25,27,32,33,34,35,45,49,52
See Principles of Operations for facility bits
```

And if you set a newer cpu (you can probe with -cpu help) TCG will tell you it can't

```
sudo /usr/bin/qemu-system-s390x -smp 1 -net none -m 512M -nographic -kernel /boot/vmlinuz-4.15.0-54-generic  -cpu zEC12-base
qemu-system-s390x: Selected CPU generation is too new. Maximum supported model in the configuration: 'z900'
```


I think the options are either:
* use -enable-kvm on an s390x-host
* build an Ubuntu kernel with a lower level set (all but z900 disabled).

There is work going on at low prio, if there are tweaks to that David or Christian might know. I'll send them a mail with a link to this issue.

**Comment by evverx** [comment]
@cpaelzer thank you for taking a look!

> use -enable-kvm on an s390x-host

If I recall correctly, [`--enable-kvm` has been off everywhere just in case since 2018](https://github.com/systemd/systemd/pull/8701#issuecomment-380213302) because of https://bugs.launchpad.net/ubuntu/+source/linux-lts-xenial/+bug/1682077. I'm wondering if it's safe to turn it on on s390x on Ubuntu CI.

> build an Ubuntu kernel with a lower level set (all but z900 disabled).

Unfortunately, we don't have any control over the infrastructure where the tests are run so it doesn't seem to be an option (at least we can't do that on the systemd side). cc @iainlane.

**Comment by evverx** [comment]
Generally I think the PR is a step in the right direction (because it makes those issues visible, which, in turn, should help to get them fixed eventually). So as not to destroy Ubuntu CI upstream completely I think something like `if [ $LOOKS_LIKE_UBUNTU ==  yes && $TEST_UPSTREAM == 1 ]` could be added to `test-functions`.

**Comment by iainlane** [comment]
> Unfortunately, we don't have any control over the infrastructure where the tests are run so it doesn't seem to be an option (at least we can't do that on the systemd side). cc @iainlane.

No sorry, that's not really going to be feasible. We run the standard Ubuntu kernels (which is actually the right thing to do if you think about it). @cpaelzer is in a good position to get any required changes to the stock kernels or qemu made though, so I will leave it in his hands. (Internal note for Christian: you can get your hands on the same VMs we use in production in `canonistack-bos01` these days.)

**Comment by evverx** [comment]
> We run the standard Ubuntu kernels (which is actually the right thing to do if you think about it)

@iainlane can't argue with that. Though, the script is supposed to work not only on Ubuntu CI but everywhere else and it's possible to point it to any kernel via `KERNEL_BIN`. That's why I generally have no problem with rolling out this PR with some kludges to keep Ubuntu CI afloat upstream.

**Comment by ddstreet** [comment]
> + timeout --foreground 180 /usr/bin/qemu-system-aarch64 -smp 1 -net none -m 512M -nographic -kernel /boot/vmlinuz-4.15.0-54-generic -drive format=raw,cache=unsafe,file=/var/tmp/systemd-test.M5PUC0/rootdisk.img -initrd /boot/initrd.img-4.15.0-54-generic -append 'ro root=/dev/sda1 raid=noautodetect loglevel=2 init=/lib/systemd/systemd console=ttyS0 selinux=0 printk.devkmsg=on   '
> qemu-system-aarch64: -nographic: No machine specified, and there is no default
> Use -machine help to list supported machines
> ```

Try adding '-machine virt'.  For full reference, here's what is currently available from the qemu-system-aarch64 on bionic:

ubuntu@systemd-upstream-arm64:~$ qemu-system-aarch64 -machine ?
Supported machines are:
akita                Sharp SL-C1000 (Akita) PDA (PXA270)
ast2500-evb          Aspeed AST2500 EVB (ARM1176)
borzoi               Sharp SL-C3100 (Borzoi) PDA (PXA270)
canon-a1100          Canon PowerShot A1100 IS
cheetah              Palm Tungsten|E aka. Cheetah PDA (OMAP310)
collie               Sharp SL-5500 (Collie) PDA (SA-1110)
connex               Gumstix Connex (PXA255)
cubieboard           cubietech cubieboard
emcraft-sf2          SmartFusion2 SOM kit from Emcraft (M2S010)
highbank             Calxeda Highbank (ECX-1000)
imx25-pdk            ARM i.MX25 PDK board (ARM926)
integratorcp         ARM Integrator/CP (ARM926EJ-S)
kzm                  ARM KZM Emulation Baseboard (ARM1136)
lm3s6965evb          Stellaris LM3S6965EVB
lm3s811evb           Stellaris LM3S811EVB
mainstone            Mainstone II (PXA27x)
midway               Calxeda Midway (ECX-2000)
mps2-an385           ARM MPS2 with AN385 FPGA image for Cortex-M3
mps2-an511           ARM MPS2 with AN511 DesignStart FPGA image for Cortex-M3
musicpal             Marvell 88w8618 / MusicPal (ARM926EJ-S)
n800                 Nokia N800 tablet aka. RX-34 (OMAP2420)
n810                 Nokia N810 tablet aka. RX-44 (OMAP2420)
netduino2            Netduino 2 Machine
none                 empty machine
nuri                 Samsung NURI board (Exynos4210)
palmetto-bmc         OpenPOWER Palmetto BMC (ARM926EJ-S)
raspi2               Raspberry Pi 2
realview-eb          ARM RealView Emulation Baseboard (ARM926EJ-S)
realview-eb-mpcore   ARM RealView Emulation Baseboard (ARM11MPCore)
realview-pb-a8       ARM RealView Platform Baseboard for Cortex-A8
realview-pbx-a9      ARM RealView Platform Baseboard Explore for Cortex-A9
romulus-bmc          OpenPOWER Romulus BMC (ARM1176)
sabrelite            Freescale i.MX6 Quad SABRE Lite Board (Cortex A9)
smdkc210             Samsung SMDKC210 board (Exynos4210)
spitz                Sharp SL-C3000 (Spitz) PDA (PXA270)
sx1                  Siemens SX1 (OMAP310) V2
sx1-v1               Siemens SX1 (OMAP310) V1
terrier              Sharp SL-C3200 (Terrier) PDA (PXA270)
tosa                 Sharp SL-6000 (Tosa) PDA (PXA255)
verdex               Gumstix Verdex (PXA270)
versatileab          ARM Versatile/AB (ARM926EJ-S)
versatilepb          ARM Versatile/PB (ARM926EJ-S)
vexpress-a15         ARM Versatile Express for Cortex-A15
vexpress-a9          ARM Versatile Express for Cortex-A9
virt-2.10            QEMU 2.10 ARM Virtual Machine
virt                 QEMU 2.11 ARM Virtual Machine (alias of virt-2.11)
virt-2.11            QEMU 2.11 ARM Virtual Machine
virt-2.6             QEMU 2.6 ARM Virtual Machine
virt-2.7             QEMU 2.7 ARM Virtual Machine
virt-2.8             QEMU 2.8 ARM Virtual Machine
virt-2.9             QEMU 2.9 ARM Virtual Machine
xilinx-zynq-a9       Xilinx Zynq Platform Baseboard for Cortex-A9
xlnx-ep108           Xilinx ZynqMP EP108 board (Deprecated, please use xlnx-zcu102)
xlnx-zcu102          Xilinx ZynqMP ZCU102 board with 4xA53s and 2xR5s based on the value of smp
z2                   Zipit Z2 (PXA27x)

**Comment by cpaelzer** [comment]
> > use -enable-kvm on an s390x-host
> 
> If I recall correctly, [`--enable-kvm` has been off everywhere just in case since 2018](https://github.com/systemd/systemd/pull/8701#issuecomment-380213302) because of https://bugs.launchpad.net/ubuntu/+source/linux-lts-xenial/+bug/1682077. I'm wondering if it's safe to turn it on on s390x on Ubuntu CI.

Well you should check /dev/kvm to exist and /sys/module/kvm/parameters/nested to be one before using it. But then something like `-machine accel=kvm -enable-kvm` will get you out of the current issues. Will it always work perfectly, I don't know. But it will work more than the TCG emulation which as we see in the discussion is stopped by providing a too old cpu.


> > build an Ubuntu kernel with a lower level set (all but z900 disabled).
> 
> Unfortunately, we don't have any control over the infrastructure where the tests are run

Yeah I assumed that, but I had to mention it to be complete in my answer.

**Comment by evverx** [comment]
I passed `-machine accel=kvm -enable-kvm` to `qemu` and it failed on `s390x` with
```sh
TEST RUN: test migrating state directory from DynamicUser=1 to DynamicUser=0 and back
+ /usr/bin/qemu-system-s390x -smp 1 -net none -m 512M -machine accel=kvm -enable-kvm -nographic -kernel /boot/vmlinuz-4.15.0-54-generic -drive format=raw,cache=unsafe,file=/var/tmp/systemd-test.5JZtI5/roo
tdisk.img -initrd /boot/initrd.img-4.15.0-54-generic -append 'ro root=/dev/sda1 raid=noautodetect loglevel=2 init=/lib/systemd/systemd console=ttyS0 selinux=0 printk.devkmsg=on   '
Could not access KVM kernel module: No such file or directory
qemu-system-s390x: failed to initialize KVM: No such file or directory
E: QEMU failed with exit code 1
```

Anyway, this PR isn't about making it work on Ubuntu CI so I think it would make sense to simply skip that part upstream and wait for the PR to make it downstream where it can be decided what options should be used or whether the test should be run there at all or https://salsa.debian.org/systemd-team/systemd/commit/7c79f66f8f07b3ae1f should be reverted.

**Comment by davidhildenbrand** [comment]
Upstream QEMU in TCG mode should be able to boot upstream Linux kernel + user space compiled for z13. For example, RHEL 8 kernel and user space works just fine.

Older kernels require CPU facilities (although they are not really needed) we don't support in QEMU TCG yet. Also, we did some major improvements on the QEMU TCG side during the latest releases (and especially will have vector instruction support in the next QEMU release).

E.g., under upstream QEMU TCG:

[root@rhel8 ~]# cat /proc/cpuinfo 
vendor_id       : IBM/S390
# processors    : 4
bogomips per cpu: 13370.00
max thread id   : 0
features        : esan3 zarch stfle msa ldisp eimm etf3eh highgprs vx 
facilities      : 0 1 2 3 4 7 9 16 17 18 19 21 22 24 25 27 30 31 32 33 34 35 37 40 41 45 49 51 52 53 69 71 72 76 77 129 138
processor 0: version = 00,  identification = 000000,  machine = 2964
processor 1: version = 00,  identification = 400000,  machine = 2964
processor 2: version = 00,  identification = 800000,  machine = 2964
processor 3: version = 00,  identification = C00000,  machine = 2964

IOW, the QEMU version @cpaelzer is using is just too old.

**Comment by ddstreet** [comment]
While this PR is not specifically about Ubuntu CI, I believe that's the only place that currently runs the tests on s390x or arm64 hardware.  For those cases, the testbed is currently configured to use Ubuntu Bionic, which is the latest LTS release, but which was released 2018-04, so the qemu provided there is obviously older.  Since the Ubuntu CI tests use a specific ppa to test, it's possible to include a newer qemu there that would only be used by the systemd-upstream Ubuntu CI tests, although I haven't looked at doing that yet.

I am testing a patch that combines updates to the upstream systemd code, with updates to the debian/ubuntu-specific test controls:
https://git.launchpad.net/~ddstreet/ubuntu/+source/systemd/commit/?id=255a318f7b8509665a61bede0e3b12a0cb97e3e7

That changes the upstream systemd code to try to use whatever qemu is appropriate for the arch, but also allows the debian test file to disable qemu use, or tweak the qemu options, so it can be adjusted to work on the Ubuntu testbeds separately from any other non-Ubuntu CI testing.

I think it's probably also appropriate to add some basic qemu sanity test into find_qemu_bin() to detect the case of qemu not working at all (e.g. the current case with qemu on s390x in the Ubuntu CI testbeds) and fallback to not using qemu, instead of failing the test...

**Comment by ddstreet** [comment]
FYI - I verified that the qemu from the Ubuntu devel release (Eoan, 19.10) does appear to work fine, so the choices for getting it working with Ubuntu CI are either 1) backport all needed changes in qemu to the Ubuntu Bionic release, or 2) drop a working qemu version into the Ubuntu CI ppa, for use only by systemd-upstream CI builds.

**Comment by evverx** [comment]
> Since the Ubuntu CI tests use a specific ppa to test, it's possible to include a newer qemu there that would only be used by the systemd-upstream Ubuntu CI tests, although I haven't looked at doing that yet.

I completely forgot about the ppa. On Travis CI we simply stopped using it and on Semaphore 0d427d377a09b316fe was added to make `add-apt-repository` work somewhat reliably. On Ubuntu CI it's probably the best way to get packages installed. Though I'm not sure how actively it's maintained.

> I am testing a patch that combines updates to the upstream systemd code, with updates to the debian/ubuntu-specific test controls:
https://git.launchpad.net/~ddstreet/ubuntu/+source/systemd/commit/?id=255a318f7b8509665a61bede0e3b12a0cb97e3e7

I think `TEST_NO_QEMU` (from `test-functions`) can be used to skip the tests in QEMU (instead of `QEMU_NONE`). More generally, I think it would be better to add code like that upstream so that we could, for example, turn off `-machine accel=kvm -enable-kvm` right here without waiting for a month for 1-line change to make it to the Debian package.

> I think it's probably also appropriate to add some basic qemu sanity test into find_qemu_bin() to detect the case of qemu not working at all (e.g. the current case with qemu on s390x in the Ubuntu CI testbeds) and fallback to not using qemu, instead of failing the test

In general it depends but I think the tests should fail if QEMU is broken to make it easier to figure out what's going on.

**Comment by ddstreet** [comment]
> > Since the Ubuntu CI tests use a specific ppa to test, it's possible to include a newer qemu there that would only be used by the systemd-upstream Ubuntu CI tests, although I haven't looked at doing that yet.
> 
> I completely forgot about the ppa. On Travis CI we simply stopped using it and on Semaphore [0d427d3](https://github.com/systemd/systemd/commit/0d427d377a09b316fe9f291de08c18d3ef51d70d) was added to make `add-apt-repository` work somewhat reliably.

As a side note re: add-apt-repository, I updated (i.e. rewrote) it to add private ppa support, but a side effect of the rewrite is it no longer needs to query any keyserver to get the gpg key for a ppa; it gets that directly from api.launchpad.net.  Not sure if that would help but thought I would mention it.  For details see
https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/645404
and test builds are in
https://launchpad.net/~ddstreet/+archive/ubuntu/lp645404
It's still waiting on review, so not in any Ubuntu repo yet.

> On Ubuntu CI it's probably the best way to get packages installed. Though I'm not sure how actively it's maintained.

The only members are @martinpitt @xnox and @mbiebl 
https://launchpad.net/~upstream-systemd-ci/+archive/ubuntu/systemd-ci
The only relevant package (all Ubuntu CI is run, currently, on the Bionic release) in the ppa is a newer version of meson, which is needed to build upstream systemd (the version in bionic is too old).  So I assume one of the members would need to approve/perform any qemu upload, if we decided that is the right way to handle running qemu-system-s390x in Ubuntu CI.

> 
> > I am testing a patch that combines updates to the upstream systemd code, with updates to the debian/ubuntu-specific test controls:
> > https://git.launchpad.net/~ddstreet/ubuntu/+source/systemd/commit/?id=255a318f7b8509665a61bede0e3b12a0cb97e3e7
> 
> I think `TEST_NO_QEMU` (from `test-functions`) can be used to skip the tests in QEMU (instead of `QEMU_NONE`). 

Ah!  perfect, thnx

> More generally, I think it would be better to add code like that upstream so that we could, for example, turn off `-machine accel=kvm -enable-kvm` right here without waiting for a month for 1-line change to make it to the Debian package.

That works, but the difficulty there is getting the settings right for 1) Ubuntu CI testbeds, 2) CentOS CI testbeds, and 3) local user's test systems

> 
> > I think it's probably also appropriate to add some basic qemu sanity test into find_qemu_bin() to detect the case of qemu not working at all (e.g. the current case with qemu on s390x in the Ubuntu CI testbeds) and fallback to not using qemu, instead of failing the test
> 
> In general it depends but I think the tests should fail if QEMU is broken to make it easier to figure out what's going on.

ack; that makes sense.  just have to make sure the qemu params are set correctly for all testbeds.

**Comment by ddstreet** [comment]
> but a side effect of the rewrite is it no longer needs to query any keyserver to get the gpg key for a ppa

sorry, just to clarify this, the devel version for Eoan (Ubuntu 19.10) removes any need for a keyserver, but the smaller backport to SRU releases in my PPA only changes that for private ppas; public ppas still need to query a keyserver.

**Comment by evverx** [comment]
> So I assume one of the members would need to approve/perform any qemu upload, if we decided that is the right way to handle running qemu-system-s390x in Ubuntu CI.

Given that it's one of the moving parts making Ubuntu CI work I think it would be great if you had access to that PPA and could do whatever you needed there. I generally have no say in the decisions made there but I hope it can be arranged.

Plus, I think it would make sense to invite you to the systemd organization on GitHub so that you could have access to the webhooks, which I think would be useful when something like https://github.com/systemd/systemd/pull/12980#issuecomment-509014105 happens. @poettering @keszybz @yuwata @mrc0mmand what do you think? It seems weird to me that @ddstreet (a maintainer of Ubuntu CI) can't, for example, look at what's going on with the requests GitHub sends to Ubuntu CI.

> the difficulty there is getting the settings right for 1) Ubuntu CI testbeds, 2) CentOS CI testbeds, and 3) local user's test systems

That's true but I was thinking about adding a kludge that could help to detect Ubuntu CI if a patch isn't applicable in general.

**Comment by mrc0mmand** [comment]
> > So I assume one of the members would need to approve/perform any qemu upload, if we decided that is the right way to handle running qemu-system-s390x in Ubuntu CI.
> 
> Given that it's one of the moving parts making Ubuntu CI work I think it would be great if you had access to that PPA and could do whatever you needed there. I generally have no say in the decisions made there but I hope it can be arranged.

That would definitely make sense. We do a pretty much similar thing in CentOS CI with several dependencies[[0]](https://copr.fedorainfracloud.org/coprs/mrc0mmand/systemd-centos-ci/).

> 
> Plus, I think it would make sense to invite you to the systemd organization on GitHub so that you could have access to the webhooks, which I think would be useful when something like [#12980 (comment)](https://github.com/systemd/systemd/pull/12980#issuecomment-509014105) happens. @poettering @keszybz @yuwata @mrc0mmand what do you think? It seems weird to me that @ddstreet (a maintainer of Ubuntu CI) can't, for example, look at what's going on with the requests GitHub sends to Ubuntu CI.

Having an access to the webhook configuration is indeed tremendously helpful when trying to debug a CI, so it would only make sense.

> 
> > the difficulty there is getting the settings right for 1) Ubuntu CI testbeds, 2) CentOS CI testbeds, and 3) local user's test systems
> 
> That's true but I was thinking about adding a kludge that could help to detect Ubuntu CI if a patch isn't applicable in general.

**Comment by cpaelzer** [comment]
FYI I checked qemu 4.0 as it is in Ubuntu 19.10 and TCG would work there to boot Ubuntu guests.
Thanks @davidhildenbrand for the hint.

**Comment by ddstreet** [comment]
@martinpitt could you add me to the upstream-systemd-ci lp team, or could you copy my qemu build:
https://launchpad.net/~ddstreet/+archive/ubuntu/systemd-upstream
into the ci ppa?

That's the current 19.04 qemu, with smartcard and capstone disabled (won't build in 18.04 with those enabled, I didn't look deeper into why since they aren't needed for our testing purposes), built for 18.04.  With that package, qemu can at least successfully start up on s390x, arm64, and ppc64el (and of course amd64/i386).

I have a bit of other tweaking to the qemu params that the systemd tests use, but I'll open a PR for those once the working qemu is available for the Ubuntu CI runs.

**Comment by ddstreet** [comment]
> @martinpitt could you add me to the upstream-systemd-ci lp team, or could you copy my qemu build:
> https://launchpad.net/~ddstreet/+archive/ubuntu/systemd-upstream
> into the ci ppa?

@martinpitt sorry to bug you again, but I think you're the only admin for the upstream-systemd-ci launchpad team:
https://launchpad.net/~upstream-systemd-ci
so I don't think @mbiebl or @xnox can add me to that team.  It would be great if I could join it so I could upload my qemu there so upstream systemd testing can run tests under qemu on non-intel archs.

**Comment by ddstreet** [comment]
@mrc0mmand @evverx and anyone interested in Ubuntu CI, I'm attempting to get the tests run on a larger testbed, mostly to avoid test timeouts after un-blacklisting all the tests and enabling testing under qemu, but also to try to speed up the Ubuntu CI test runs a bit.  @iainlane suggested that I make you all aware of the request as it might also require limiting the number of concurrent PR test runs; see this MP for more details and please feel free to comment there:
https://code.launchpad.net/~ddstreet/autopkgtest-cloud/+git/autopkgtest-cloud/+merge/369620

**Comment by mrc0mmand** [comment]
> @iainlane suggested that I make you all aware of the request as it might also require limiting the number of concurrent PR test runs

This might not be as *bad* as it sounds, as the hard limit for concurrent jobs should be (at least partially) countered by the tests running much faster (especially if you tweak certain aspects of the tests themselves, like setting `QEMU_SMP=$(nproc)` on multi-core machines, etc.). I'm not familiar with the exact (or at least average) runtime of Ubuntu CI jobs, so knowing this *variable* as well might make the decision easier.

Also, skipping CI completely for certain changes (like man-only PRs, translations, Travis/Semaphore/Azure CI configuration fixes, etc), should help as well (as we already do at least in the CentOS CI).

**Comment by mbiebl** [comment]
@ddstreet uploaded your qemu and device-tree-compiler packages

**Comment by ddstreet** [comment]
> @ddstreet uploaded your qemu and device-tree-compiler packages

Thanks @mbiebl!   However the qemu will need rebuilding, as it needs the updated device-tree-compiler to compile correctly.

Also, it seems the PPA is enabled only for amd64 and i386, so the PPA will need to have (at least) ppc64el, s390x, and arm64 enabled.  You should be able to enable alternate archs from the ppa page by clicking 'Change details' at the top right, then selecting the arch checkboxes.

I think that once additional archs are enabled for a PPA, packages have to be deleted and re-uploaded (or just re-uploaded with bumped version numbers) to build for the newly enabled archs.  I'm not aware of any way to build existing packages for newly enabled archs, although there might be some way I just don't know about.

@martinpitt if you could add me to the team for that ppa, I'd be happy to maintain qemu there.

**Comment by martinpitt** [comment]
@ddstreet : Sorry for the lag, I was (and still am) on holidays. I added you to https://launchpad.net/~upstream-systemd-ci , made @mbiebl an administrator, and added the three architectures. I didn't (re)upload any packages to trigger new builds there.

**Comment by ddstreet** [comment]
Thanks!  The qemu in the ppa is built for all archs being tested now.  I'll open a PR with a few patches I have to start using qemu for non-intel archs; I don't think that I can add onto this pull request, can I?

**Comment by mrc0mmand** [comment]
> Thanks! The qemu in the ppa is built for all archs being tested now. I'll open a PR with a few patches I have to start using qemu for non-intel archs; I don't think that I can add onto this pull request, can I?

@ddstreet feel free to edit this PR to your needs! :-)

**Comment by evverx** [comment]
> @iainlane suggested that I make you all aware of the request as it might also require limiting the number of concurrent PR test runs;

As far as I can tell, Ubuntu CI doesn't cancel jobs when PRs are updated, which, in turn, leads to a lot of jobs piling up there. In https://github.com/systemd/systemd/pull/13399#issuecomment-524517732 I attached a couple of screenshots to show what it looked like. In https://github.com/systemd/systemd/pull/13407 about 20 minutes ago 14 jobs were running at the same time (instead of 4). Until this is fixed somehow, I don't think the number of runs should be limited.

I'll take a look at the MR on launchpad later this week.

**Comment by iainlane** [comment]
On Mon, Aug 26, 2019 at 05:32:10PM -0700, Dan Streetman wrote:
> > > @iainlane suggested that I make you all aware of the request as it might also require limiting the number of concurrent PR test runs;
> > 
> > As far as I can tell, Ubuntu CI doesn't cancel jobs when PRs are updated, which, in turn, leads to a lot of jobs piling up there.
> 
> That's my understanding as well; once a job is submitted, it runs until completion (or timeout), with no way to stop it, nor any logic to detect when a job should be aborted due to external changes (like an updated PR).

Correct. It's possible to imagine how this might be done, but it's not
there now. If someone wants to help with that, please get in touch and
we can provide mentoring and reviews.

Cheers,

-- 
Iain Lane                                  [ iain@orangesquash.org.uk ]
Debian Developer                                   [ laney@debian.org ]
Ubuntu Developer                                   [ laney@ubuntu.com ]

**Comment by evverx** [comment]
> If someone wants to help with that, please get in touch and
we can provide mentoring and reviews.

If hypothetically I got in touch, would you give me access to the Canonical infrastructure? Or is it just another way of saying that nobody is going to do anything about it? :-)

**Comment by iainlane** [comment]
On Tue, Aug 27, 2019 at 01:54:12AM -0700, Evgeny Vereshchagin wrote:
> > If someone wants to help with that, please get in touch and
> we can provide mentoring and reviews.
> 
> If hypothetically I got in touch, would you give me access to the Canonical infrastructure? Or is it just another way of saying that nobody is going to do anything about it? :-)

I'm afraid that this message comes across as a bit rude, but I'll still
respond to you.

I can't give you access to the machines in the data centre, no. I can
explain how the system works. We can brainstorm solutions together and I
can deploy code to test it out. If you wait long enough then one of us
at Canonical might implement it. If you want it done on your own
timescale, you are welcome to work on it and I made an offer to make my
own time available to assist you. If you have access to an Openstack
cloud you can run the infrastructure yourself (that is a high bar, I
know) so you'll require less back and forth.

Cheers,

-- 
Iain Lane                                  [ iain@orangesquash.org.uk ]
Debian Developer                                   [ laney@debian.org ]
Ubuntu Developer                                   [ laney@ubuntu.com ]

**Comment by evverx** [comment]
> I can't give you access to the machines in the data centre, no. I can
explain how the system works. We can brainstorm solutions together and I
can deploy code to test it out.

I'm afraid I don't think that it can lead anywhere.

>  If you wait long enough then one of us
at Canonical might implement it.

I doubt it but if we're talking about feature requests I'd like to draw attention to https://github.com/systemd/systemd/issues/11195, which, in my opinion, is much more important than canceling jobs.

> If you want it done on your own
timescale, you are welcome to work on it and I made an offer to make my
own time available to assist you.

Thank you for the offer but I'm going to pass.

> If you have access to an Openstack
cloud you can run the infrastructure yourself (that is a high bar, I
know) so you'll require less back and forth.

It's not a high bar but I'm not sure why you think I would spend my time setting up Ubuntu specific infrastructure.

> I'm afraid that this message comes across as a bit rude

I didn't mean to upset or offend anyone. I apologize.

**Comment by evverx** [comment]
@ddstreet since you started to maintain Ubuntu CI, it's been relatively stable and I really appreciate what you've been doing there. But as we discussed somewhere on launchpad, for a long time it was completely abandoned and at some point it started to look like the whole thing was offloaded onto volunteers. So those kind "offers" to help with setting up a local instance of Ubuntu CI and "mentoring" to get the basic feature any webhook should provide still surprise me to say the least. I agree that message might have not been addressed to me or that I might have misunderstood it but given it's not the first time people from Canonical subtly (or sometimes directly) have told me to basically go and fix their stuff for them I kind of got frustrated.

**Comment by iainlane** [comment]
You can feel free to stop tagging me on bugs. It's clear there is a communication problem and I'm not interested in making that worse. I can talk to Dan just fine so please go through him.

**Comment by evverx** [comment]
> You can feel free to stop tagging me on bugs.

I wouldn't have tagged you if there had been anyone from Canonical keeping track of what is going on on Ubuntu CI. The fact that you still expect me to monitor Ubuntu CI and contact @ddstreet is just another example of what I was talking about.

> It's clear there is a communication problem and I'm not interested in making that worse.

Sure.

**Comment by keszybz** [comment]
The original patch looked like a nice cleanup. @mrc0mmand is this something we still want to pursue?

**Comment by keszybz** [comment]
Oh, there's #13409. Let's close this one then.

**Pull request closed without merging**
