### PR TITLE
hwdb: Logitech M305 Wireless Optical Mouse dpi data

### LINKED ISSUE #8208: Logitech M305 missing from udev hwdb
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 229

### Used distribution

> Ubuntu 16.04

The Logitech M305 mouse is missing from udev hwdb. I've checked the specs using mouse-dpi-tool. The following lines should be added to `70-mouse.hwdb`:

```
# Logitech M305 Wireless Optical Mouse
mouse:usb:v046dpc52f:name:Logitech USB Receiver:
 MOUSE_DPI=1000@170
```

### PR DESCRIPTION
**Pull request by danmou**

### CODE REVIEW

**Comment by poettering** [comment]
@whot ptal!

**Comment by poettering** [comment]
@Danmou semaphore CI doesn't like your patch. Could you please look into that and make sure that "meson test" passes?

**Comment by keszybz** [comment]
@Danmou You need an empty line above the new block, that is the reason for CI failure. Please also change the title of your patch to the same title that is now set for the PR.

**Comment by Danmou** [comment]
> Please also change the title of your patch to the same title that is now set for the PR.
Not sure what that means. Do you mean I should rename the branch?

**Comment by keszybz** [comment]
@Danmou we usually ask contributors to do amend any commits and use `git push --force` to replace any existing commits in the PR. But in this case we can fix that on our side when we squash your two commits into one when applying the PR. So you don't need to do anything else, but let's wait for the CI.

**Pull request merged**
