### PR TITLE
build-sys: revert dbus >= 1.9.18 requirement

### PR DESCRIPTION
**Pull request by floppym**
Instead, document the necessary step to utilize older dbus versions.

### CODE REVIEW

**Comment by mbiebl** [comment]
I think it would be nicer if we add a AC_WARNING if dbuspolicydir is not set. and dbus < 1.9.18.

**Comment by poettering** [comment]
The centos CI issue is unrelated. Fixing.

(@mbiebl: patch for such a warning would be very welcome!)

**Comment by poettering** [comment]
@floppym, @mbiebl  btw, a patch for NEWS explaining the situation would be very welcome too!

**Comment by mbiebl** [comment]
Not sure if this was discussed or not.
We could test for the dbus version and set dbuspolicydir depending on which version is found (unless explicitly set via --with-dbuspolicydir, of course)

**Comment by poettering** [comment]
I'd very much prefer a warning over an automatism. People should stop using the old version. If they want to anyway, they can do the work themselves, we shouldn't make that automatic. 

Hence: warning yes please! automatism no thanks!

**Comment by mbiebl** [comment]
alright, understood.

**Pull request merged**
