### PR TITLE
 test-network: check whether ethtool support driver field for dummy interfaces

### LINKED ISSUE #11758: test-network: NetworkdNetDevTests.test_dropin fails in CIs
e.g. https://ci.centos.org/job/systemd-pr-build/4844/artifact/systemd-centos-ci/artifacts_TnaGSl/testsuite-logs.UvK/systemd-networkd-tests.py_FAIL.log
```
======================================================================
FAIL: test_dropin (__main__.NetworkdNetDevTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 292, in test_dropin
    self.assertRegex(output, 'Driver: dummy')
AssertionError: Regex didn't match: 'Driver: dummy' not found in '● 29: dropin-test\n       Link File: /usr/lib/systemd/network/99-default.link\n    Network File: n/a\n            Type: ether\n           State: off (unmanaged)\n      HW Address: 00:50:56:c0:00:28 (VMware, Inc.)'

----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #11758.

### CODE REVIEW

**Comment by ssahani** [comment]
@yuwata it seems it failing only on vmware. virtualbox I tested it works ok. 
```
$ systemd-detect-virt 
oracle
$ networkctl status dummy1
● 5: dummy1
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: n/a
            Type: ether
           State: n/a (unmanaged)
          Driver: dummy
      HW Address: 92:0c:a3:ef:a6:1e
         Address: fe80::900c:a3ff:feef:a61e

```

We should only disable on vmware I think.

**Comment by yuwata** [comment]
Thanks!!!

**Comment by yuwata** [comment]
Hmm? But CentOS CI uses vmware? I am not sure, but I do not think so...

**Comment by yuwata** [comment]
CentOS CI seems to use qemu.

**Comment by yuwata** [comment]
Anyway, let's wait for that CentOS CI finishes.

**Comment by yuwata** [comment]
Hmm... Still failed....

**Comment by yuwata** [comment]
`systemd-detect-virt` returns `none`... 
@mrc0mmand The test is running on bare system? Does the system use `udevd` built from git? I am very confused...

**Comment by ssahani** [comment]
> Hmm? But CentOS CI uses vmware? I am not sure, but I do not think so...

From the log it says vmware . it's the manufacturer ID matching interface from interface HW address.. ooops . sry.

**Comment by mrc0mmand** [comment]
> `systemd-detect-virt` returns `none`...
> @mrc0mmand The test is running on bare system? Does the system use `udevd` built from git? I am very confused...

All CentOS CI machines are baremetal. The integration tests are run under both `nspawn` and `qemu`, however, the `systemd-networkd-tests.py` is run directly on the machine without any virtualization. Also, `udevd` is compiled along `systemd` directly from git (see https://github.com/systemd/systemd-centos-ci/blob/master/agent/bootstrap.sh#L84).

**Comment by mrc0mmand** [comment]
@yuwata also, this might help you as well: https://wiki.centos.org/QaWiki/PubHardware

**Comment by yuwata** [comment]
@mrc0mmand and @ssahani Thank you for comments. Finally, I found the root of the issue. PTAL.

**Comment by mrc0mmand** [comment]
LGTM, thank you!

**Comment by ssahani** [comment]
Wow thanks

**Pull request merged**
