### PR TITLE
cifuzz: fuzz the master branch on push

### PR DESCRIPTION
**Pull request by mrc0mmand**
Apart from running CIFuzz for each relevant PR, let's run it
unconditionally for each push to master to detect possible issues
(caused by ignored PRs, etc.).

Followup to 94f660a8fe6144b9153c8acaf9e6bb9e47e14b97.

/cc @evverx

### CODE REVIEW

**Comment by evverx** [comment]
I'll go ahead and merge it. Though given https://github.com/google/oss-fuzz/issues/3731#issuecomment-621279832 I'm not sure how exactly CIFuzz reacts to push events. Let's find out :-)

**Comment by mrc0mmand** [comment]
Looks like the GH gods have been merciful and the fuzzers built successfully, at least in this case. Hopefully it's going to stay that way :-)

**Comment by evverx** [comment]
To judge from
Screenshot 2020-05-08 at 21 33 57

workflow runs aren't cancelled when PRs are updated. I might have to read https://github.community/t5/GitHub-Actions/Is-it-possible-to-cancel-previous-jobs-automatically-when-the/td-p/37139 :-)

**Comment by mrc0mmand** [comment]
Ouch, that's unfortunate. I naively hoped this is (finally) handled automagically.

**Pull request merged**
