### PR TITLE
systemd-timedated: allow setting timezone when wierd permissions on /etc

### PR DESCRIPTION
**Pull request by shawnl**
root@desktop:~# timedatectl set-timezone UTC
Failed to set time zone: Access denied

### CODE REVIEW

**Comment by shawnl** [comment]
this fixes a regression

**Comment by boucman** [comment]
CI failure is a KVM machine error, seems unrelated...

**Comment by shawnl** [comment]
Ahh, it appears it only happens which in systemd-nspawn containers, so something having to do with UID namespaces.

**Comment by evverx** [comment]
`systemd-nspawn` normally `chown`s everything when [`-U`](https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html#-U) or [`--private-users=pick`](https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html#--private-users=) is used. If you passed one of this options and didn't manually change the owner of the top-level directory, then in theory `/etc` should have had the right permissions. If it didn't, then something possibly went wrong and it might be a bug elsewhere.

**Pull request closed without merging**
