### PR TITLE
core: several follow-ups for timeout PR #11211

### PR DESCRIPTION
**Pull request by yuwata**
Follow-ups for dc653bf487bae9d1ddf794442bf4176fee173b41 (#11211).

### CODE REVIEW

**Comment by benjarobin** [comment]
@yuwata I did not create a MR immediately, in order to give a change for @jkloetzke to fix it, with all others @poettering remarks. But since you already started, you may want to take into account all poettering remarks in this MR.

**Comment by yuwata** [comment]
Ah, I did not follow the comments by @poettering. I will address them in this PR. Thank you.

**Comment by yuwata** [comment]
@benjarobin and @poettering I hope all comments in #11211 are addressed.

**Comment by jkloetzke** [comment]
@benjarobin Good catch. @yuwata Looks good to me. Thanks for taking care of all of the remaining issues...

**Pull request merged**
