### PR TITLE
just the recvmsg_safe() stuff from #15457

### PR DESCRIPTION
**Pull request by poettering**
Split out of #15457, in an attempt to track down those Ci failures.

### CODE REVIEW

**Comment by keszybz** [comment]
It's failing in the same way as the other one.

**Comment by keszybz** [comment]
This happens a few times:
`[[0;1;31mFAILED[0m] Failed to start [0;1;39mNetwork Service[0m.`
So it would look like something related to systemd-networkd, but I don't see the error.

**Comment by poettering** [comment]
it looks like we end up with truncated cmsg on some of our uses unconditionally. which is actually great, given that this PR is precisely about finding such previously silent errors...

**Comment by poettering** [comment]
I force pushed a new version now. I dropped the conversion in the DHCP + netlink code. Maybe this makes things work. If it does, we should probably merge it, and then do the DHCP/netlink conversion later, since apparently something needs some fixing there with the sizing of the control buffers.

If this also doesn't work I guess we have to do the conversions one by one, or bisecting it...

**Comment by poettering** [comment]
@mrc0mmand hmm, the travis failure, what's going in there? i don't see anything actually failing in the log dump?

**Comment by mrc0mmand** [comment]
> @mrc0mmand hmm, the travis failure, what's going in there? i don't see anything actually failing in the log dump?

That's just a flake, something which I need to take a look at as well. Rescheduled.

**Comment by poettering** [comment]
so the ubuntu CIs passed this time (except for the i386 one, which timeout due to ttyS0 not popping up, which i guess is an unrelated issue).

let's merge this now (@keszybz already gave it a green flag after all, over in #15457). Let's then figure out what to do with the remaining bits from the other PR, and what issue they actually are triggered by.

**Pull request merged**
