### PR TITLE
nspawn: Open-code changing selinux exec context

### PR DESCRIPTION
**Pull request by richardmaw-codethink**
This is the local patch I have for issue #475. This is mostly submitted for completeness, as ideally glibc or libselinux would be fixed.

### CODE REVIEW

**Comment by poettering** [comment]
Well, let's see what @rhatdan has to say before we merge anything like this.

However, should we want to merge a patch like this, it should really use write_string_file_no_create() to write the string. It makes it shorter and more robust.

**Comment by richardmaw-codethink** [comment]
> However, should we want to merge a patch like this, it should really use write_string_file_no_create() to write the string. It makes it shorter and more robust.

@poettering I tried that first, `write_string_file_no_create()` always puts a trailing \n on the file.
The result is a short write if the string already ends with a \n (see [selinux/hooks.c](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/security/selinux/hooks.c?id=1dc51b8288007753ad7cd7d08bb8fa930fc8bb10#n5596)), but the follow-up `fputc('\n', f)` always results in an invalid write.
So while the context is changed, the error result is indistinguishable from being given a garbage label.

If you think this is an appropriate change after speaking with @rhatdan, then I'm happy to rework the fileio helpers to add support for a variant of `write_string_file()` that doesn't force the newline.

**Comment by poettering** [comment]
What a stupid API the selinux /proc stuff is. Yuck!

Anyway, I figure we should probably do some clean-up work here, and merge write_string_file(), write_string_file_no_create() and write_string_file_atomic() into a single call, which takes a new flags argument:

```
WRITE_STRING_FILE_CREATE = 1
WRITE_STRING_FILE_ATOMIC = 2
WRITE_STRING_FILE_AVOID_NEWLINE = 4
```

flags=0 would then be identical to the the current write_string_file_no_create().

Would that make sense?

Still would like to know @rhatdan's opinion on all of this.

**Comment by zonque** [comment]
This is now implemented in #500, please review!

**Comment by rhatdan** [comment]
My understanding is the caching was added to help performance for systemd on boot.  @eparis added this, I have little problem with this patch or adding a call to libselinux to invalidate the cache.  Or to remove the cache altogether, if we feel it is not worth the hassle.

**Comment by richardmaw-codethink** [comment]
From my understanding of the code in question, all the caching becomes unnecessary on recent enough kernels as you can write to `/proc/thread-self/attr/exec`.
If it were me I'd use a raw `getpid()` syscall in the fallback, or see if it were suitable to put `getpid()` into the vdso, as I understand the caching of gettime was moved in there for similar reasons.

**Comment by eparis** [comment]
The cache is supposed to be avoided entirely if the pid has changed.

https://github.com/SELinuxProject/selinux/blob/master/libselinux/src/procattr.c#L92

I'm not sure I understand how you got into a situation where there is a problem.

**Comment by richardmaw-codethink** [comment]
@eparis That's because of a problem with glibc.

It caches the result of `getpid()` and invalidates it when calling a `fork()` or `clone()`.

Unfortunately the interface glibc exposes for `clone()` is not low-level enough for systemd, so it never invalidates the `getpid()` cache, so after the fork the result of `getpid()` does not change, so libselinux doesn't know that it can't use its cache.

**Comment by eparis** [comment]
Where is the glibc bug filed?

**Comment by richardmaw-codethink** [comment]
https://sourceware.org/bugzilla/show_bug.cgi?id=17214 looks close.

**Comment by poettering** [comment]
This appears to be fixed in libselinux now, see comments in #475. Closing this now.

**Pull request closed without merging**
