### PR TITLE
nspawn: allow multiple uid maps with private-users

### PR DESCRIPTION
**Pull request by sqwishy**
I'm not sure if this a super great way to introduce this feature but it seemed mostly harmless and I want feedback. This is in regards to issue #12864.

The `--private-users=HOST` option allows specifying a host uid to map to the container's uid 0 with range 0x10000 or `--private-users=HOST:RANGE` to specify the size of the mapping.

This change allows `--private-users=HOST:CONTAINER:RANGE` to add a mapping for some other uid in the container other than zero.

---

Something I noticed while doing this was that the `uid_shift` setting seems to be somewhat important. Specifically, I think it's used for chowning a bunch of things. So that is still there and `uid_shift` and `uid_range` essentially mean what they used to: The mapping for the uid zero in the container.

Also:

- This still doesn't let you have a separate uid/gid map.
- There isn't really any validation. (Overlapping values or overflows.) If you don't specify any mapping to uid zero in the namespace, it acts a little weird. So eventually it tries to write the mapping and fails because linux is like "what is this garbage you're giving me?" but nspawn could certainly figure out and tell the user ahead of time if something looks broken.
- This doesn't touch any of the OCI stuff.
- I didn't change the documentation or anything.

I didn't want do too much in case this whole approach is dumb or something and also I want feedback from the CI at least.

### CODE REVIEW

**Comment by poettering** [comment]
what's the usecase for this precisely?

**Comment by sqwishy** [comment]
I had a use case where a number of namespaces would share the same mapping for their uid zero but different mappings for uid 1000. But I don't think that was a good idea, so I'm not using this feature anymore.

But it was originally brought up in issue #12864. I figured at the time, based on the RFE tag, that the usecase in that issue was sound. So I'd defer to that rather than defend whatever pathology I'm trying to use uid maps for.

**Comment by NightTsarina** [comment]
This feature seems to me like the missing piece to have containers with private users, except for the user(s) running the container, so home directories can be shared seamlessly. Up to now, I have not been able to find a way to do that short of adding some FUSE middleware to translate the UIDs for the bind mount.

**Comment by bluca** [comment]
There's a new feature being worked on in the kernel, close to being ready, which allows remapping IDs on mounts: https://lore.kernel.org/selinux/20201203235736.3528991-1-christian.brauner@ubuntu.com/T/#m056cb868e035965c82abfc18cea52fd29fe23cac

IMHO we should wait for that to be available and then leverage it, as it should simplify things greatly.

**Comment by poettering** [comment]
Let's close this. #19555 has been merged in the meantime, and I think that solves the usecase mentioned here in a much nicer and more comprehensive way.

**Pull request closed without merging**
