### PR TITLE
meson: create unit symlinks in the vendor directory

### LINKED ISSUE #12767: `systemctl preset-all` makes cross-compilation hard
I'm using current master (`v242-851-g9a31142997`) within Buildroot, a framework for building embedded Linux images.

The instructions now suggest to run `systemctl --root=/path/to/it preset-all` in order to enable services such as `systemd-networkd` or `systemd-resolved`. This makes the installation process more painful than it used to be because:

- I'm typically building on amd64, targetting ARM, meaning that I cannot use my just-built `systemctl` to set up stuff automatically.
- Even if my build environment has `systemctl` available, it is completely different than what I've just built. I do not think I want to use `systemctl` from RHEL7 to bootstrap a new system image.
- I could build systemd twice, once just to get a working `systemctl`, and the second time targetting my final target arch. That sounds like a waste of resources for creating a bunch of symlinks.
- I'm aware of hacks such as registering QEMU as a binfmt-misc for running alien binaries. That's just too fragile (and won't work in least-privileged build containers, anyway).

I might be missing the whole picture, but can you please ensure that these symlinks are created during the build?

### PR DESCRIPTION
**Pull request by jktjkt**
During the v242 cycle, a [change was merged](https://github.com/systemd/systemd/commit/01d2041e41f4886a6dff16a53a950ae8d5b66bc7) which stopped creating enablement symlinks for various services, including systemd-networkd. The main reason described in the commit message was that this auto-provisioning undoes configuration for those end users who chose to disable some of these services on their systems. For them, running `ninja install` caused these services to become enabled again, which was not expected. Running `systemctl preset-all` is documented to be a recommended step prior to the first boot.

This change has implications for cross-compilations. A build machine cannot execute binaries (such as `sysrepoctl`) which were just built for the target. There are workarounds for this, including QEMU, but they are needlesly complex. Creating these symlinks by hand works, but it's yet another manual step which can get out of sync from the actual code.

Systemd has a concept of vendor presets, bits which are intended to represent default configuration "from the factory". These settings are in no way affected by the end-user configuration. This patch simply takes all services which were, prior to 01d2041e41, enabled by symlinks in `/etc/systemd/system/`, and puts these into an appropriate `*.wants` below the `/lib/systemd/system/`.  This means that the usual way of overriding and masking stuff via `/etc` is available to express a user's configuration. As before, stuff below `/lib` represents the default system state, and people are free to override this "policy" via a configuration below `/etc`.

There's one change for people who already grew accustomed to the v242's behavior. They will now have to mask each corresponding unit (because this "enablement" is not an "enablement" as in `systemctl is-enabled`).

Closes #12767, #12769

Signed-off-by: Jan Kundrát <jan.kundrat@cesnet.cz>

### CODE REVIEW

**Comment by floppym** [comment]
> There's one change for people who already grew accustomed to the v242's behavior. They will now have to mask each corresponding unit (because this "enablement" is not an "enablement" as in systemctl is-enabled).

This PR is a bad idea, for exactly this reason. This will confuse users, just to make life a little easier for people cross-compiling systemd.

**Comment by arvidjaar** [comment]
> puts these into an appropriate `*.wants` below the `/lib/systemd/system/`. This means that the usual way of overriding and masking stuff via `/etc` is available to express a user's configuration

There is no way to override `.wants` links in `/lib` via `/etc`; there was long discussion on this that withered away without any solution. And masking is wrong tool to override vendor defaults.

**Comment by keszybz** [comment]
>> There's one change for people who already grew accustomed to the v242's behavior. They will now have to mask each corresponding unit (because this "enablement" is not an "enablement" as in systemctl is-enabled).

> This PR is a bad idea, for exactly this reason. This will confuse users, just to make life a little easier for people cross-compiling systemd.

Yep, there is no way this can go in. Masking units provides a bad user experience.

> There is no way to override .wants links in /lib via /etc; there was long discussion on this that withered away without any solution.

The idea was to allow /dev/null links that would mask individual .wants symlinks in directories with lower priority. This would allow us to keep vendor enablement symlinks in /usr/lib, but still allow the user to call `systemctl disable` that would only touch `/etc`. If this was implemented, we could reconsider creating symlinks by default again.

**Comment by poettering** [comment]
yeah, we shouldn't do this unless there's a way to mask symlinks again. happy to review a patch for that.

**Pull request closed without merging**
