### PR TITLE
run: check if the specified realtime timer is not in the past

### LINKED ISSUE #12253: onCalendar in the past doesn't error
**systemd version the issue has been seen with**
> systemd 241 (241.67-1-arch)

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > Some type of error or warning message, and a non-zero return

**Unexpected behaviour you saw**
 > Time looked like it was set even though it's impossible. Command returned success.

```
Running timer as unit: run-r57dda746e0e7452cbdba3c3b215d90c0.timer                     
Will run service as unit: run-r57dda746e0e7452cbdba3c3b215d90c0.service
```

**Steps to reproduce the problem**

 * `systemd-run --user --on-calendar '2018-01-01 12:00' echo "ABC"`

### PR DESCRIPTION
**Pull request by mrc0mmand**
Let's make sure the calendar event expression specified by
--on-calendar runs at some point in the future.

Fixes #12253.

```
$ date +"%Y-%m-%d %H:%M"
2019-04-12 12:03
$ build/systemd-run --user --on-calendar "2019-04-12 9:03" echo "ABC" 
The calendar event must be in the future
$ build/systemd-run --user --on-calendar "2019-04-12 13:03" echo "ABC" 
Running timer as unit: run-raab906dcb7b0428398533b75b06cbf60.timer
Will run service as unit: run-raab906dcb7b0428398533b75b06cbf60.service
$ build/systemd-run --user --on-calendar "now" echo "ABC" 
Failed to parse calendar event specification
$ build/systemd-run --user --on-calendar "hourly" echo "ABC" 
Running timer as unit: run-r1010d782e0584d489ae62b2995432377.timer
Will run service as unit: run-r1010d782e0584d489ae62b2995432377.service
```

### CODE REVIEW

**Comment by keszybz** [comment]
Shouldn't we instead print a warning and make the calendar run "now"?

**Comment by keszybz** [comment]
@mrc0mmand ?

**Comment by mrc0mmand** [comment]
Hm, I'd stick with the error here, as it's somewhat expected by supplying an *invalid* argument (i.e. a date in the past). However, I'm open to both approaches, as I don't have any real-world use case for such scenarios.

Maybe the author of the issue, @kenmacd, can give us some insight?

**Comment by keszybz** [comment]
I was considering a case where a time close in the future is calculated, e.g. "start of operation + 1 minute", and then some more operations are done, and by the time we get to requesting the timer, one minute has already passed and we get an error. I guess this could happen in scripts, but maybe it's not something to worry about.

**Comment by KenMacD** [comment]
Personally when I ran in to this I'd typoed the date, so my preference would have been for an error message and the command to have not been run. It wasn't meant to be run at that time time of day, even if the date had been right.

This seems like the least surprising behaviour to me, and generally matches the real work in that if you order a cake for last week they're not going to immediately make it.

I understand @keszybz's point that this could causes issues with near-now times, especially with DST or timezone changes. If the solution ends up being that it's run immediately I'd understand and just request that there's a warning message generated so I can fix it.

**Comment by poettering** [comment]
Hmm, I think this should be a warning, not be fatal. Otherwise this will always be racy... Let's say you calculate some time to run in 5sec time, and then for some time your scripts takes  abit of time to reach the systemd-run line, and suddenly the call fails even though everything should be OK, and it should be OK to run the job right-away...

Moreover, I think scheduling a calendar timer with an expression such as "2019-*-* 12:00" today would make a lot of sense event though strictly speaking it would first elapse 4 months ago...

Hence: warning is good I think, but it shouldn't be fatal.

**Comment by evverx** [comment]
This pull request **introduces 1 alert** when merging 83a212e3b3b216173897d0b331d4971d9686281e into aba5472979168a47e426b06e720a4b0d50a56bfa - [view on LGTM.com](https://lgtm.com/projects/g/systemd/systemd/rev/pr-3ad48817af1ef51dfcce669e1f846bf83fd6b583)

**new alerts:**

* 1 for Dead code due to goto or break statement

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by mrc0mmand** [comment]
> Hmm, I think this should be a warning, not be fatal. Otherwise this will always be racy... Let's say you calculate some time to run in 5sec time, and then for some time your scripts takes abit of time to reach the systemd-run line, and suddenly the call fails even though everything should be OK, and it should be OK to run the job right-away...

Good point. I tweaked the patch so now the `OnCalendar` property won't be added to the newly created unit if the calendar event is in the past, thus executing it immediately (with an appropriate warning).

```
$ build/systemd-run --user --on-calendar "2019-04-12 9:03" echo "ABC" 
Specified calendar event is in the past, executing immediately
Running as unit: run-r3ac95bc0cb034febba35c5e649704938.service
$ journalctl --user --unit run-r3ac95bc0cb034febba35c5e649704938.service
-- Logs begin at Wed 2019-04-24 04:35:26 PDT, end at Wed 2019-04-24 04:57:55 PDT. --
Apr 24 04:57:42 arch.localdomain systemd[562]: Started /usr/bin/echo ABC.
Apr 24 04:57:42 arch.localdomain echo[883]: ABC
Apr 24 04:57:42 arch.localdomain systemd[562]: run-r3ac95bc0cb034febba35c5e649704938.service: Succeeded.

```

> 
> Moreover, I think scheduling a calendar timer with an expression such as `2019-*-* 12:00` today would make a lot of sense event though strictly speaking it would first elapse 4 months ago...
> 

This wouldn't be an issue even with the previous version of this patch, as it checks for a next invocation time relative to the current time (i.e. delta from `now(CLOCK_REALTIME)`), which is always in the future for such events. That said, no warning is emitted for following example:

```
$ build/systemd-run --user --on-calendar "2019-*-* 12:00" echo "ABC" 
Running timer as unit: run-r6342de5786bc4e3888cca9990d373bc7.timer
Will run service as unit: run-r6342de5786bc4e3888cca9990d373bc7.service
$ systemctl --user  cat run-r6342de5786bc4e3888cca9990d373bc7.timer
# /run/user/1000/systemd/transient/run-r6342de5786bc4e3888cca9990d373bc7.timer
# This is a transient unit file, created programmatically via the systemd API. Do not edit.
[Unit]
Description=/usr/bin/echo ABC

[Timer]
OnCalendar=2019-*-* 12:00
RemainAfterElapse=no
```

**Pull request merged**
