### PR TITLE
hwdb: add axis range corrections for Dell Latitude E7470

### PR DESCRIPTION
**Pull request by pakdel**
Followed https://wayland.freedesktop.org/libinput/doc/1.7.3//absolute_coordinate_ranges.html

### CODE REVIEW

**Comment by macrothian** [comment]
These ranges broke the edge scrolling on my E7470 as the edge was suddenly further right than possible. 
Please see https://github.com/systemd/systemd/issues/7252 that has ranges touchpad-edge-detector suggested (and worked).

**Comment by whot** [comment]
@pakdel please re-measure your touchpad, the range we merged in commit 9f14144 looks a bit unusual. thanks

**Comment by pakdel** [comment]
@whot Here is what I got:

```
[root@RP-YUL-L1319 ~]# touchpad-edge-detector 98x52 /dev/input/event20
Touchpad AlpsPS/2 ALPS DualPoint TouchPad on /dev/input/event20
Move one finger around the touchpad to detect the actual edges
Kernel says:    x [39..5856], y [10..1532]
Touchpad sends: x [21..2937], y [45..1535] -|-^C

Touchpad size as listed by the kernel: 98x52mm
User-specified touchpad size: 98x52mm
Calculated ranges: 2916/1490

Suggested udev rule:
# <Laptop model description goes here>
evdev:name:AlpsPS/2 ALPS DualPoint TouchPad:dmi:bvnDellInc.:bvr1.17.5:bd07/11/2017:svnDellInc.:pnLatitudeE7470:pvr:rvnDellInc.:rn0T6HHJ:rvrA00:cvnDellInc.:ct9:cvr:*
 EVDEV_ABS_00=21:2937:30
 EVDEV_ABS_01=45:1535:29
 EVDEV_ABS_35=21:2937:30
 EVDEV_ABS_36=45:1535:29
```

**Comment by whot** [comment]
ok, looks like the one we merged was a typo 5->2 would make the range more sensible. We'll fix this as part of #7252 then, thanks.

**Comment by pakdel** [comment]
Sorry for the typo.
Thanks!

**Pull request merged**
