### PR TITLE
lgtm: complain about ftok() use

### PR DESCRIPTION
**Pull request by poettering**
Similar to the existing fgets() thing. Prompted by #11555 

/cc @evverx

### CODE REVIEW

**Comment by poettering** [comment]
(note, I don't fully grok what precisely I added there, the whole patch is kinda copy/paste)

**Comment by evverx** [comment]
I took a look at #11555 and it seems to me that the query was supposed to be about `strtok` (`ftok` would most likely look suspicious too and probably shouldn't be used either, though :-))

**Comment by evverx** [comment]
It would probably be better to borrow [PotentiallyDangerousFunction](https://github.com/Semmle/ql/blob/master/cpp/ql/src/Security/CWE/CWE-676/PotentiallyDangerousFunction.ql) from https://github.com/Semmle/ql so as not to add a new file every time we want to look for potentially dangerous (or otherwise problematic) functions but I think it can be done later.

**Comment by evverx** [comment]
@mbiebl looks like https://salsa.debian.org/systemd-team/systemd/commit/8d810fda9a640a932d6e7b32afd958fe75e36f5b broke Ubuntu CI. Could you take a look?

**Comment by mbiebl** [comment]
@martinpitt can we provide a backport of dpkg in the PPA?

**Comment by mbiebl** [comment]
@martinpitt, @iainlane, @xnox hm, we could change that dependency to `dpkg (>= 1.9.3) | systemd-sysv`. After all, we don't need the SysV init script under a systemd managed system. Not entirely sure if that would have any undesired side-effects though...

**Comment by evverx** [comment]
It seems that it won't be fixed anytime soon. @mbiebl could you revert that commit and reopen #908796?

**Comment by evverx** [comment]
I reported it in https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1819589.

**Comment by martinpitt** [comment]
@mbiebl: We could (I suppose it doesn't use too many other dependencies), but this will also break Debian backports. Thus I actually prefer the `| systemd-sysv` alternative dependency. I [committed](https://salsa.debian.org/systemd-team/systemd/commit/bd89a706b18) that, and will now retry the  recent PRs.

**Comment by evverx** [comment]
@martinpitt thank you! Could you also restart it in https://github.com/systemd/systemd/pull/11915 and https://github.com/systemd/systemd/pull/11602? Those PRs were updated relatively recently and seem to have hit the same issue.

**Comment by poettering** [comment]
Ouch, I am an idiot... To my defense though: ftok() is also stupid, but probably nothing to worry about. ;-)

Anyway, thanks for prepping #11965. Let's close this one.

**Comment by martinpitt** [comment]
@evverx : Done

**Pull request closed without merging**
