### PR TITLE
some assorted fixes and additions, in particular a way to turn off "nobody" synthesizing on a specific system

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by boucman** [comment]
this could maybe have a bit more documentation than juste the comment ? maybe in DISTRO_PORTING

**Comment by poettering** [comment]
> this could maybe have a bit more documentation than juste the comment ? maybe in DISTRO_PORTING

this will get coverage in NEWS as we do a release, but usually we write that up only on release time. But I think it fits better there than in DISTRO_PORTING.

**Comment by boucman** [comment]
hmm, I tend to think that NEWS is mainly for people looking for new features, whereas PORTING is how to integrate in a distro and workaround the various quirks, but that makes sense too...

**Comment by keszybz** [comment]
OK, let's merge. Further tweaks might be necessary, but I think the gist is OK.

**Comment by keszybz** [comment]
Semaphore CI should be fixed in master now, so hopefully the merge result will build.

**Pull request merged**
