### PR TITLE
ethtool: Fix Duplex, half or full.

### PR DESCRIPTION
**Pull request by ssahani**
Fix values for duplex.
```
/* Duplex, half or full. */
#define DUPLEX_HALF             0x00
#define DUPLEX_FULL             0x01
#define DUPLEX_UNKNOWN          0xff
```

### CODE REVIEW

**Comment by keszybz** [comment]
What is the effect of this? Does this fix a bug, or is this just a cleanup?

**Comment by ssahani** [comment]
yes it's a bug. The ethtool value 
~~~
#define DUPLEX_HALF             0x00
#define DUPLEX_FULL             0x01
#define DUPLEX_UNKNOWN          0xff
~~~

Where we were 
~~~
   DUP_FULL that is 0                                                                                                                                                                              
    DUP_HALF and this one
~~~

had a effect on ethtool_set_glinksettings       
                                                                
~~~                                                                                                                        
        if (link->duplex != _DUP_INVALID)                                                                                                                                                      
                u->base.duplex = link->duplex; 
~~~

**Comment by keszybz** [comment]
Well, I know that the values are different. But what the effect of them being wrong? Did we set the duplex configuration wrong in the kernel? Please describe that in the commit message. If there's a bug open, link to it.

**Comment by ssahani** [comment]
>But what the effect of them being wrong? 

I actually do not understand this

**Comment by keszybz** [comment]
>> But what the effect of them being wrong?

> I actually do not understand this

I'm asking if this was causing actual problems, visible to the user.

**Comment by ssahani** [comment]
Yes I saw this while testing the port conf. We are setting the wrong value. Hence need to be corrected. Will add in the commit message

**Comment by keszybz** [comment]
This fails tests. Just drop DUP_UNKNOWN from the enum definition, it is not used for anything.

**Comment by ssahani** [comment]
pushed a new version . oh yes the Build passed. Thanks :)

**Pull request merged**
