### PR TITLE
Systemctl add log-level, log-target, service-watchdogs commands

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
Still not liking this very much. So, what about this idea: let's maybe just implement "systemd-analyze verify" in the main systemd binary, maybe behind some switch that is generally not documented, but just an implementation detail. Then systemd-analyze would forward its invocation there, so that the interface remains systemd-analyze but the internal implementation is actually in the PID 1 binary, where it exists anyway.

Pros: systemd-analyze would be substantially smaller. Hopefully small enough that people just can ship it anyway and don't need to split it up. Not interface borkage, no user facing redundancy.

Cons: the PID 1 binary will grow a tiny bit most likely.

(We have something like this anyway btw, in the "telinit" handling where the PID 1 binary operates very differently in a very specific case)

**Comment by keszybz** [comment]
This move was motivated by the desire to split systemd-verify out, but it's not the only reason. I think the change is warranted on its own. It simply is the right place to have those commands.

**Comment by msekletar** [comment]
I agree with @keszybz. Setting the log level is basic functionality and should be exposed via `systemctl`.

**Comment by keszybz** [comment]
qemu-system-ppc64: terminating on signal 15 from pid 13488 (timeout)
bionic-amd64: test-journal-send (code: 134)
both unrelated

**Comment by keszybz** [comment]
I'll rebase.

**Comment by poettering** [comment]
setting the log level to debug (and that's the only thing that the command is good for primarily and almost exclusively) is a debugging feature, as the word "debug" suggests. I don't think we should have debugging features in our primary tool. And the service watchdog stuff even more so. I mean for the log level stuff one could maybe construct a synthetic usecase that people might want to set the log level to LOG_NOTICE instead of LOG_INFO, but for the watchdog stuff? why would anyone ever use that except for debugging?

I mean, we have to draw the boundary between these tools somewhere, and I think the line must be drawn between "useful in clean codepaths" and "useful only for debugging". The three commands clearly are on the right side of this device to me.

And even if this wasn't as clear cut as I think it is, if there's doubt we should think twice before changing interfaces (or making redundant interfaces) like this, i.e. if there story isn't clear then it's not really worth breaking documented interface to me.

I mean, let's be constructive, if we implemented my proposal, then this should probably be sufficient to just leave systemd-analyze in the main RPM of systemd without paying substantial disk space. i.e. we'd keep the full feature set of the tool available even on very minimal systems.

**Comment by keszybz** [comment]
I don't think the division into "clean" and "unclean" code paths is useful. This is totally vague and we'll never agree on what it means. For me, a much more useful split is between things that modify what pid1 is doing, and things that "analyze", and "system-control" should be the tool that "controls" the behaviour.

One of the arguments used against having 'set-log-level' in systemctl was that it is too confusing to have many verbs. I don't think this is a valid argument. As long as options are clearly named it is OK to have many verbs. Things become confusing when verbs have conflicting or unclear names, on when things are located in an unexpected place.

> if there story isn't clear then it's not really worth breaking documented interface to me.

Nothing is broken as the change is fully backwards compatible.

> I mean, let's be constructive, if we implemented my proposal, then this should probably be sufficient to just leave systemd-analyze in the main RPM of systemd without paying substantial disk space. i.e. we'd keep the full feature set of the tool available even on very minimal systems.

I don't think it'll work out like this. If we make it clear that "systemd-analyze" is for "advanced debugging, introspection, and linting", than poeple will want to leave it out of various installations no matter what size the binary is. Even if the binary is small, than keeping the number of executables down is worthwhile to some poeple. It might be useful to pursue different compilation arrangements, but I think that is orthogonal to the change at hand.

**Comment by poettering** [comment]
> > 
> 
> I don't think it'll work out like this. If we make it clear that "systemd-analyze" is for "advanced debugging, introspection, and linting", than poeple will want to leave it out of various installations no matter what size the binary is. Even if the binary is small, than keeping the number of executables down is worthwhile to some poeple. It might be useful to pursue different compilation arrangements, but I think that is orthogonal to the change at hand.

Well, so far neither Debian nor Fedora split out the binary, things can't be bad...

But anyway, I think this is a bad idea, but I am not going to block this.

**Comment by keszybz** [comment]
bionic-ppc64el failed with "FAILED TESTS:  TEST-08-ISSUE-2730", looks unrelated.

**Pull request merged**
