### PR TITLE
Remove the old version of the lz4 stream compressor

### PR DESCRIPTION
**Pull request by keszybz**
This should be merged after systemd 228.

### CODE REVIEW

**Comment by keszybz** [comment]
Interesting... github shows the commits in different order than they are in in the repo. Commit 50e1cf7 is the last and is not part of the other pull request #1606.

**Comment by poettering** [comment]
Yeah, github is sometimes pretty confused.

**Comment by poettering** [comment]
Hmm, what happened to semaphore on this one?

**Comment by zonque** [comment]
Hmm, dunno. Maybe push a new version, and let's see what happens.

**Comment by poettering** [comment]
I figure one of the patches was already included in another PR, and that confused semaphore...

**Comment by keszybz** [comment]
OK, rebased not to include commits from the other pr.

**Pull request merged**
