### PR TITLE
units: drop full paths for utilities in $PATH

### PR DESCRIPTION
**Pull request by keszybz**
This makes things a bit simpler and the build a bit faster, because we don't
have to rewrite files to do the trivial substitution. @rootbindir@ is always in
our internal $PATH that we use for non-absolute paths, so there should be no
functional change.

### CODE REVIEW

**Comment by keszybz** [comment]
Oh, I submitted the same patch also in #14378. Let's close this one.

**Comment by keszybz** [comment]
CI passes, except for travis which failed when downloading packages. Setting flag.

**Comment by keszybz** [comment]
> not a fan of this commit. it just makes things less deterministic, since we are subject to searching rather than fixed paths. Can we keep this independent of the other parts of the PR? the searching of executables stuff is problematic enough, I am not convinced at this point that we should make use of that for our own binaries too, needlessly...

The fact that we call `/usr/bin/systemctl` and not just plain `systemctl` makes very little difference. We have a fixed search path, so the only difference would be if somebody put a different `systemctl` binary earlier in the path than our own. If they do that, they get to keep the pieces. The reason is that not only systemd calls systemctl internally, but many of the things we invoke might call our utilities in turn (`systemctl` and others), and if "compromised" versions are available in the search path, things will go south. The fact that systemd uses a fixed path is not enough.

There was a similar discussion in rpm packaging. Back in the day people used macros like `%__make` to call `/usr/bin/make` and `%__mkdir_p` to call `mkdir -p` and `%__ln` and `%__ar` and … The idea was (I think) to guard against "rogue" utilities inserted somewhere in $PATH. But this completely ignores that fact that e.g. make will read the Makefile and in turn invoke various utilities, so fixing just the first call is a waste of time. This use of macros is now discouraged, but peple cargo-cult their usage to this day.

**Comment by keszybz** [comment]
I still think the reasoning behind this commit is solid ;) PTAL.

**Comment by poettering** [comment]
So my reservations about this is that searching for executables sounds so unnecessary and error prone. We know exactly what we want to invoke, so why search for it? I mean, we install the files, we *know* the path, hence why then search for it when executing?

I mean, the build being faster isn't convincing to me. I mean, it's great if it becomes faster, but it's a relatively low priority goal, in particular in light of the fact that one can argue that in return this makes runtime slower since we now need to search for the binaries. 

It's not about security and rogue binaries for me btw. This code runs under a controlled $PATH and if people manage to change that, then by all means we should call their redirected binaries. It's more about being deterministic here and having a consistant installation where the various components we install actually reference precisely and accurately our own binaries, because that's why we do this stuff.

Besides being faster to build, is there any actual benefit from searching $PATH here?

(also needs rebase)

**Comment by keszybz** [comment]
I see the following benefits:
- the file in git is more like the real file, in most case we avoid having to do any translation, so things are just ... simpler,
- files look exactly the same on all distributions, and it's possible to copy and paste them without issue,
- for our own files, we "know" where they are installed, but this is not true of other projects, and by not using the full path we encourage other projects to do the same and make it more likely that people write portable files.
- and finally, the executable search path is an absolutely core concept of unix, and I don't see a good reason to deviate from it in just this one particular instance.

**Comment by mrc0mmand** [comment]
Hmm, this seems to break the *logic* in `test/test-functions`

```
# make -C test/TEST-01-BASIC clean setup run debug=1
+ for _x in inst_symlink inst_script inst_binary inst_simple
+ inst_binary plymouth
+ local _bin _target
+ [[ 1 -eq 1 ]]
+ [[ -e /var/tmp/systemd-test.YjBUdr/root/plymouth ]]
++ find_binary plymouth
++ [[ -z plymouth ]]
++ type -P plymouth
+ _bin=
+ return 1
+ for _x in inst_symlink inst_script inst_binary inst_simple
+ inst_simple plymouth
+ [[ -f plymouth ]]
+ return 1
+ return 1
+ '[' plymouth '!=' plymouth ']'
+ '[' plymouth '!=' plymouth ']'
+ '[' /bin/plymouth == plymouth ']'
make: *** [Makefile:4: setup] Error 1
make: Leaving directory '/build/test/TEST-01-BASIC'
```

**Comment by keszybz** [comment]
"logic" is to nice of a word. I would say the "duct tape contraption" instead ;)

**Comment by poettering** [comment]
not a fan still, but ok

**Comment by flokli** [comment]
While working on bumping systemd for NixOS, I stumbled into this commit - discovering binaries at runtime causes serious headaches here.

We currently set `DEFAULT_PATH` to a nonexistent location and require all paths in `ExecStart` etc. to be absolute.

Can we revert this? Having the build a bit simpler and faster doesn't really seem to kick as an argument. We trade this with a lot of runtime complexity and impurity.

**Comment by keszybz** [comment]
Nah. Making the build faster is the most minor of reasons. The most important is having the unit files portable between distributions. Having the same file work on many different systems is great, and the pointless path differences were often the only thing preventing that. If NixOS makes design choices that change the layout from what everybody else has, then you'll just need to adjust the ExecStart= lines.

**Comment by flokli** [comment]
Well, The PR description says "makes things a bit simpler and the build a bit faster", not "makes the unit file portable between distributions". The part about being able to share across distros comes later.

I can understand this is desirable for distro packagers, for other applications (like nginx people being able to ship a distro-agnostic unit in their source code) -  but not for systemd-provided units itself.

They inherently depend on the systemd version being used. If we look at the `git log` of the `units` folder, these do change over systemd version, so I don't see the point of sharing them across distros.

Also, 58 of the 83 `.service` files in there are still generated depending on some meson-specifics (58 `.service.in` vs 25 `.service` files), so again, most of these files still depend on how systemd is configured, and is not distro-agnostic.

We could of course configure/patch systemd to have (only) `@rootbindir@` inside its internal `$PATH` (instead of a non-existent path as we usually do) to avoid having to maintain a revert of this - But I don't really see the advantage of omitting `@rootbindir@` here - doing this causes us more work in other areas, to check the underlying binaries are different.

**Comment by keszybz** [comment]
What we do internally in systemd is used as an example by other people. If we write ExecStart=/usr/bin/sh everywhere, that's what people will see and what they will write in their own files. Full paths were originally added with some bogus justification about selinux requiring them, and we've been carrying them ever since. For me, everything that is present in the unit file should have justification, and finding the path to a program in path is something that the program is very good at doing by itself. The burden of the proof would be to show why it *should* be there, rather than why not.

>  58 of the 83 `.service` files in there are still generated depending on some meson-specifics

Those are for programs not in the search path. This is the same as calling a program on the command line — there you too have to specify a full path to binary. It happens that most of our binaries are not in in the search path, and that is OK.

**Pull request merged**
