### PR TITLE
selinux: use *_raw API from libselinux

### PR DESCRIPTION
**Pull request by evverx**
This is a follow-up to 5c5433a

### CODE REVIEW

**Comment by evverx** [comment]
Ok:)

BTW:
There are four non-raw calls:
- [`setexeccon`](https://github.com/systemd/systemd/blob/7f508f2c7468a6469c4db92bb3b9f0e799246eb8/src/core/execute.c#L1925) (raw variant breaks [SELinuxContext=](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#SELinuxContext=))
- [`selinux_check_access`](https://github.com/systemd/systemd/blob/6344f3e28dd6ae341015d62163437f6cb1add749/src/core/selinux-access.c#L254) (~~there is no "raw"-variant. see https://github.com/keszybz/systemd/commit/5c5433ad32c3d911f0c66cc124d190d40a2b5f5b#commitcomment-16491265~~ @bachradsusi has prepared a patch: see https://github.com/keszybz/systemd/commit/5c5433ad32c3d911f0c66cc124d190d40a2b5f5b#commitcomment-16497590)
- [`mac_selinux_apply`](https://github.com/systemd/systemd/blob/6344f3e28dd6ae341015d62163437f6cb1add749/src/basic/selinux-util.c#L182) (raw call may break something)
- [`mac_selinux_create_socket_prepare`](https://github.com/systemd/systemd/blob/6344f3e28dd6ae341015d62163437f6cb1add749/src/basic/selinux-util.c#L380) (raw call may break something)

**Comment by zonque** [comment]
@keszybz so this is good to merge you say?

**Comment by keszybz** [comment]
I don't understand the implications of this patch. I wanted to read the selinux code to have an informed opinion, but didn't find the time to do it yet. I don't think this is critical — things mostly seem to work now, so if we could wait a few more days, I'll try to make a proper review during the weekend.

**Comment by bachradsusi** [comment]
@keszybz  Generally SELinux contexts follows `user:role:type:level` syntax. In the most case, the level looks like `s0-s0:c0.c1023`, which is the raw variant. However, on MLS enabled systems with mcstransd runnning, the level is/can be translated to human readable form like `SystemLow-SystemHigh`.

systemd already uses _raw variants to get a process contexts, file contexts and so on. Therefore there's no need to use non-raw variant which first check if `mcstransd` running and tries to translate the context first and then runs _raw variant with the translated context.

**Comment by keszybz** [comment]
@evverx, @bachradsusi IIUC, SELinuxContext= can be affected if MLS is used. Do we need to add some NEWS entry?

**Comment by evverx** [comment]
> SELinuxContext= can be affected if MLS is used.

We still use [`setexeccon`](https://github.com/systemd/systemd/blob/master/src/core/execute.c#L1925) for `SELinuxContext=`-setting. So, `SELinuxContext` understands non-raw (and raw) contexts.

> Do we need to add some NEWS entry?

I think we needn't.

**Comment by keszybz** [comment]
We call `setexeccon` from the chlid process. So calling the non-raw version should be OK.

But we call `mac_selinux_apply` and `mac_selinux_create_socket_prepare` and `selinux_check_access` from PID 1. Shouldn't we use _raw calls for them too?

**Comment by evverx** [comment]
Yes, we should use `_raw` calls whenever possible.

We can implement `selinux_check_access_raw` manually (https://github.com/keszybz/systemd/commit/5c5433ad32c3d911f0c66cc124d190d40a2b5f5b#commitcomment-16497590)

We can change `mac_selinux_create_socket_prepare` (we always pass a `raw` labels to `socket_address_listen`)

I'm not sure about `mac_selinux_apply`.

**Comment by keszybz** [comment]
Non-raw calls might return different result in early boot and different after mcstransd is started. So we should avoid them even if only for that reason.

**Comment by evverx** [comment]
I agree.
Updated TODO: https://github.com/systemd/systemd/pull/2881

**Pull request merged**
