### PR TITLE
battery-check: rework unit

### PR DESCRIPTION
**Pull request by poettering**
Let's rename the unit to systemd-battery-check.service. We usually want to name our own unit files like our tools they wrap, in particular if they are entirely defined by us (i.e. not just wrappers of foreign concepts)

While we are at it, also hook this in from initrd.target, and order it against initrd-root-device.target so that it runs before the root device is possibly written to (i.e. mounted or fsck'ed).

This is heavily inspired by @aafeijoo-suse's PR #28208, but quite different ;-)

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by fbuihuu** [comment]
> While we are at it, also hook this in from initrd.target, and order it against initrd-root-device.target so that it runs before the root device is possibly written to (i.e. mounted or fsck'ed).

It seems that this service can be useful even if `ENABLE_INITRD=false`, no ?

**Comment by YHNdnzj** [comment]
> It seems that this service can be useful even if ENABLE_INITRD=false, no ?

If you want to check the result of `battery_is_discharging_and_low()`, `systemd-ac-power --low` can be used. The `systemd-battery-check` does some extra stuff such as sending plymouth messages, and shall generally be used for early-userspace battery check only IMO.

**Review by yuwata — APPROVED** [review]

**Comment by fbuihuu** [comment]
> > While we are at it, also hook this in from initrd.target, and order it against initrd-root-device.target so that it runs before the root device is possibly written to (i.e. mounted or fsck'ed).
> 
> It seems that this service can be useful even if `ENABLE_INITRD=false`, no ?

@poettering can you please provide some insight ?

And according to the reason you provided for renaming the service into `systemd-check-battery.service` and although this service is initrd specific, `initrd-udevadm-cleanup-db.service` should also be renamed the same way.

**Comment by poettering** [comment]
> It seems that this service can be useful even if `ENABLE_INITRD=false`, no ?

Hmm? I am pretty sure a tool like this should not run after the rootfs is already mounted. after all on linux even if you mount an fs ro it will replay its journal and thus make changes to the backing store. And we shouldn't power off the machine in the middle of that. The only safe place to do this thing is *before* we mount the rootfs. Hence initrd is should be.

Also, initrd-less systems are mostly theory, or at least special purpose (i.e. systems that run on very very specific environment only, i.e. VM-only OSes), I doubt in such scenarios you really want the battery checker thingy. or to say this differently: only devices having immediate user access (i.e. PCs, tablets, cell phones, …) should need this, but they'll have initrd too.

**Comment by poettering** [comment]
> And according to the reason you provided for renaming the service into `systemd-check-battery.service` and although this service is initrd specific, `initrd-udevadm-cleanup-db.service` should also be renamed the same way.

Yeah, true. Renaming things sucks though for long established stuff. For entirely new stuff like this battery checker it's super easy though to just get the naming right before the first release

**Comment by fbuihuu** [comment]
> Also, initrd-less systems are mostly theory, or at least special purpose (i.e. systems that run on very very specific environment only, i.e. VM-only OSes), I doubt in such scenarios you really want the battery checker thingy. or to say this differently: only devices having immediate user access (i.e. PCs, tablets, cell phones, …) should need this, but they'll have initrd too.

ok I thought that initrd-less systems were quite common in the embedded world.

**Pull request merged**
