### PR TITLE
test: avoid asserts for calls with side-effects

### PR DESCRIPTION
**Pull request by bluca**
CID#1542972
CID#1542973
CID#1542974

Follow-up for 5152b8459afc6570efa537605d3bbf47c067661e

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
These seem like false positives. These are just macros that expand to regular code, they won't get optimized out.

**Comment by DaanDeMeyer** [comment]
If it's too much work we can also just rename all these to `CHECK_XXX`

**Comment by mrc0mmand** [comment]
> If it's too much work we can also just rename all these to `CHECK_XXX`

That's certainly a solution, but I really hate the idea of bending source code to accommodate tooling. I'll play with this a bit more, but I'll have to spin up an internal Coverity instance first (since the OSS one has a _very_ limited number of builds per week).

**Comment by mrc0mmand** [comment]
I spent a couple of hours trying to reproduce the three specific ASSERT_SIDE_EFFECT defects in a local Coverity instance and just couldn't no matter how hard I tried (with the same version of Coverity, too). And this morning the three defects were marked as "eliminated" in Coverity. _What._

**Comment by bluca** [comment]
self-correcting bugs - what's not to like!

**Pull request closed without merging**
