### PR TITLE
.travis.yml: bump the ubuntu version from bionic to focal

### PR DESCRIPTION
**Pull request by szb512**
*im too lazy to edit the branch name, it calls it a patch by default*
The title pretty much explains itself.

### CODE REVIEW

**Comment by szb512** [comment]
The only thing i want to see pass is travis. I got my eyes peeled on that test.

**Comment by szb512** [comment]
Travis errored with this:
Package docker-ce is not available, but is referred to by another package.

This may mean that the package is missing, has been obsoleted, or

is only available from another source

E: Package 'docker-ce' has no installation candidate

**Comment by bluca** [comment]
Thanks for the PR, but please note that work is in progress to move away from Travis and use Github Actions: https://github.com/systemd/systemd/pull/18128

**Comment by szb512** [comment]
Closing in favor of  #18128.

**Pull request closed without merging**
