### PR TITLE
systemd-hwdb: fix unsigned and signed comparison problem

### PR DESCRIPTION
**Pull request by huyubiao**
issue: https://github.com/systemd/systemd/issues/29320

### CODE REVIEW

**Review by DaanDeMeyer — COMMENTED** [review]
I'm not sure I get this fix? Shouldn't `c` in `trie_insert()` be changed into `char` instead to fix this issue?

**Comment by huyubiao** [comment]
> I'm not sure I get this fix? Shouldn't `c` in `trie_insert()` be changed into `char` instead to fix this issue?
I've modified.
I think either unsigned char or char can be done.

**Comment by huyubiao** [comment]
> Please move the description of the issue to the commit message.



> commit message

I have added the description to the commit message

**Comment by huyubiao** [comment]
> Please move the description of the issue to the commit message.
I have added the problem description to the commit message.

**Review by DaanDeMeyer — APPROVED** [review]

**Review by bluca — APPROVED** [review]

**Pull request merged**
