### PR TITLE
network: read sysctl value only once

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for bafa9641446852f7fa15ca12d08a223d345c78ea.

### CODE REVIEW

**Comment by floppym** [comment]
How long does this cached value persist? I'm wondering what happens if the sysadmin changes the sysctl value outside of networkd.

**Comment by yuwata** [comment]
When the value is changed, networkd needs to be restarted.

**Comment by ssahani** [comment]
May we we can have a watch on that file and do the needful when that changes rather than restarting manually as we already doing similar thing .

**Comment by keszybz** [comment]
Nah, I don't this we need to go to all that trouble, unless people request this. If IPv6 is switched on or off, this usually means network is being reconfigured, and I think it should be OK to require a restart of networkd in that case.

**Pull request merged**
