### PR TITLE
journald compression bug fix

### PR DESCRIPTION
**Pull request by vcaputo**

### CODE REVIEW

**Comment by vcaputo** [comment]
additional context: https://github.com/coreos/bugs/issues/322

**Comment by poettering** [comment]
Hmm, so, our general rule is to always return kernel-style negative errno errors from functions, and normal exits are indicated by a zero or positive return value. Hence, compress_blob() should really work the same here, hence it's OK the way the function is defined, but the user of it in journal_file_append_data() is borked, it should check for >= 0 really...

Now, looking at the code, it appears there are actually more bugs with the lz4 handling here:
- There's no le64toh used when ORing in the compression mask into the object flags field
- The whole if check checks for f->compress_xz, but should actually alternatively check for f->compress_lz4 too, here. 

I am a bit puzzled this was not noticed earlier, I figure the only reason is that lz4 support was so far never on in any of the big distros.

@keszybz any idea on this?

**Comment by poettering** [comment]
Ah, the flags issue is not an issue, the flags field of objects is actually just one byte, ignore that...

**Comment by vcaputo** [comment]
updated to reflect upstream preferences

**Comment by poettering** [comment]
A bummer, we worked on the same issue at the same time... See #1663...

**Comment by poettering** [comment]
I guess the patches in #1662 and #1663 are mostly the same now, except that #1663 also fixes the compress bool check...

Anyway, @keszybz would prefer a comment from you on the bool thing...

**Comment by poettering** [comment]
Still puzzled why the xz can't compress 512 byte blocks though. @vcaputo any idea why that fails? Are you saying it fails for all 512 byte blocks? Or just for specific ones?

Or is this simply triggered by an uncompressable block, i.e. where the compressed result is larger than the input?

**Comment by vcaputo** [comment]
To address your earlier statements re: lz4, we're using xz in coreos, not lz4.

After poking at liblzma's lzma_stream_buffer_bound(), it appears to return 656 on an input size of 512, and COMPRESSION_SIZE_THRESHOLD is defined as 512.

So apparently we're observing this bug triggering @ 512 because of the value defined as COMPRESSION_SIZE_THRESHOLD, and perhaps that define should be changed to 656 (or something else) on HAVE_XZ.

Though with the bug fixed I guess it doesn't make much difference.

**Comment by vcaputo** [comment]
@poettering out of curiosity, why the src_size - 1 for dest_len? @ https://github.com/systemd/systemd/blob/master/src/journal/compress.c#L80  isn't the payload allocated to accommodate src_size?

**Comment by poettering** [comment]
@vcaputo ah, if that's a block that got increased 512 →656 through compression, then yeah, it's one of those uncompressable ones, and compress_blob_xz() already returns ENOBUFS in such a case. So I think the logic in that place is working correctly.

The src_size - 1 as dest_len is because we want the call to generate an error if the result has the same size as the input or is larger. Hence we provide only enough space as the input size, minus 1 byte. That way we know it will generate an error when the compression doesn't have any beneficial effect, so that save the data uncompressed in that case.

**Comment by vcaputo** [comment]
Makes sense.

**Pull request closed without merging**
