### PR TITLE
network: accept colons in network interface names

### LINKED ISSUE #4057: systemd-networkd: ifname_valid too strict (at least for use in config_parse_label)
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> > = 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Gentoo
### In case of bug report: Expected behaviour you didn't see

> Address labels are useful to allow explicit association of names with additional IP addresses on a network device.  A name such as "eth0:alias" (i.e. a colon separator with the actual device name first and the alias after) is _required_ in order to allow tools like ifconfig (or, specifically for us, Lustre's lnet_ipaddr_enumerate()) to identify these as valid, distinct devices.  config_parse_label should not be rejecting names with a colon, I believe.  Perhaps ifname_valid can be stricter in other cases, but not for address labels (kernel's dev_valid_name does reject the colon, so must not be in the path for alias assignment). 
### In case of bug report: Unexpected behaviour you saw

> A systemd.network [ADDRESS] section should allow a "Label=" entry to contain colons.
### In case of bug report: Steps to reproduce the problem

> Assign a name with a colon to a network interface via systemd.network specification.  Start systemd-networkd and observe the error message, e.g.: "Interface label is not valid or too long, ignoring assignment: ethX:label".  Alternatively, assign a label without a colon (i.e. something that would pass ifname_valid), and try enumerating interfaces with ifconfig.  The expected additional "alias" device will not correctly display, instead erroring with "error fetching interface information: Device not found" (at least with net-tools 1.60)

### PR DESCRIPTION
**Pull request by peoro**
Fix for #4057

### CODE REVIEW

**Comment by peoro** [comment]
Here an example of the patch in action to create an alias interface (credits @zukka77)

[asciicast](https://asciinema.org/a/7dhtjmpxeuvbbn0uoc4llf5gi)

**Comment by floppym** [comment]
The character `:` is a colon, not a semicolon (`;`).

**Comment by peoro** [comment]
...Whoops!

**Comment by keszybz** [comment]
So we have two pull requests (#5116 is the other), purporting to make the same change, but with completely different implementation. Interesting.

**Comment by keszybz** [comment]
OK, this one looks better. From you explanation, it seems that the check that @ssahani added to make sure that the label is numerical is not needed.

**Pull request merged**
