### PR TITLE
mkosi: build for the host distro by default

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by bluca** [comment]
For some reason my comment on the commit is not visible here: https://github.com/keszybz/systemd/commit/fce4052022c8d89be6b8d549b3c8b4e4c23a9bd9#r55880237

**Comment by keszybz** [comment]
> For some reason my comment on the commit is not visible here: [keszybz@fce4052#r55880237](https://github.com/keszybz/systemd/commit/fce4052022c8d89be6b8d549b3c8b4e4c23a9bd9#r55880237)

I saw the comment (got a notification by mail).

> I think the idea here is to have dev environment specific config that don't get committed? This is how I use it for   
example

Hmm, OK. So what files do you have there?

**Comment by keszybz** [comment]
I don't think ignoring all files is the correct approach. We could either have some specific pattern, e.g. `/mkosi.default.d/*local*`, or users should add their files to `.git/info/exclude`.

**Comment by keszybz** [comment]
I updated that one commit to keep ignoring files matching `*local*.conf`. PTaL.

**Comment by bluca** [comment]
> > For some reason my comment on the commit is not visible here: [keszybz@fce4052#r55880237](https://github.com/keszybz/systemd/commit/fce4052022c8d89be6b8d549b3c8b4e4c23a9bd9#r55880237)
> 
> I saw the comment (got a notification by mail).
> 
> > I think the idea here is to have dev environment specific config that don't get committed? This is how I use it for
> > example
> 
> Hmm, OK. So what files do you have there?

I've got stuff to make my normal cmdline shorter:

```
[Packages]
Packages=
        libc6-dbg
        gdbserver
        openssh-server

[Content]
        Password=
        WithTests=false
```

But the approach with .local works just fine for me.

**Comment by bluca** [comment]
CI's unhappy tho:

```
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'mkosi.default.d/.gitignore', line: 2
'/*local*.conf\n'
```

**Comment by DaanDeMeyer** [comment]
This should also update the docs in the HACKING doc to remove the symlinking stuff since stuff will work by default now. Maybe add a comment that if users want a different distro, they can just write a mkosi.default file that sets their preferred mkosi distro and mkosi will pick up the rest of the config automatically.

**Comment by keszybz** [comment]
Updated:
- the gitignore patterns are moved one directory up to avoid the CI failure.
- HACKING.md is updated.

**Review by bluca — APPROVED** [review]
lgtm

**Review by yuwata — APPROVED** [review]
LGTM too.

**Comment by keszybz** [comment]
focal-amd64 timed out in "upstream" tests.

**Pull request merged**
