### PR TITLE
ukify: don't attempt to print emoji

### LINKED ISSUE #35784: ukify should check whether emojis are available akin to emoji_enabled()
### systemd version the issue has been seen with

257.1

### Used distribution

Arch Linux

### Linux kernel version used

6.12.7-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Expected program output:
```
Kernel version not specified, starting autodetection.
```

### Unexpected behaviour you saw

Actual program output:
```
Kernel version not specified, starting autodetection ▯.
```
System tools should not use emojis and shoul not rely on specific fonts availability.

### Steps to reproduce the problem

```
ukify build --linux=/boot/vmlinuz --output /tmp/linux-signed.efi
```

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by dimich-dmb**
Fixes #35784

### CODE REVIEW

**Comment by bluca** [comment]
Why remove this? Sounds like a utf issue in your terminal?

**Comment by dimich-dmb** [comment]
> Why remove this? Sounds like a utf issue in your terminal?

In my terminal I can see all UTF characters I need: Cyrillic, Greek, math, pseudograpic, etc because I have installed corresponding fonts. To see emoji I need to find and install more fonts. I won't.
Moreover, Linux virtual console, for example, supports no more than 512 glyphs and they are limited in size.  
Moreover, not all terminals are unicode-capable.

Unprintable characters in system utility output are confusing: it's hard to understand whether it is an important warning failed to print or just someone's joke.

**Comment by YHNdnzj** [comment]
Sorry, but we generally assume emojis just work if not on Linux VT and locale is in UTF-8 (see `emoji_enabled()`), hence dropping this wholly is not desirable. However, I think it's acceptable to teach `ukify` to honor `$SYSTEMD_EMOJI` like our C tools.

**Comment by dimich-dmb** [comment]
> Sorry, but we generally assume emojis just work if not on Linux VT and locale is in UTF-8 (see `emoji_enabled()`)

Sorry, but this is wrong assumption. Charmap "UTF-8" in locale doesn't mean that terminal is able to display any arbitrary unicode character.

> However, I think it's acceptable to teach `ukify` to honor `$SYSTEMD_EMOJI` like our C tools.

I don't care how the issue will be fixed. I just proposed the simplest, and in my opinion, the most optimal solution.

**Comment by dimich-dmb** [comment]
Ah, I looked into C code and got your point now. I couldn't even imagine it has special code to display emojis 🤦 Fortunately I've never seen them in output of other utilites. Of course, in this case removing garbage from warning message doesn't fit into overall style of this software. The PR can be closed.
However, the issue #35784 is still relevant: ukify displays `▯`.

**Pull request closed without merging**
