### PR TITLE
hwdb: let's no abbreviate HORIZONTAL as HORIZ

### PR DESCRIPTION
**Pull request by poettering**
I think I am developing OCD... Let's fix this before this actually gets used in
the wild.

A follow-up for #3986 (5fc9e4abb41e7f58f6c308f54881c596713fba75).

### CODE REVIEW

**Comment by poettering** [comment]
Merging, since CI passed and it has the good-to-merge label.

**Comment by keszybz** [comment]
So, I was too slow to comment: I think "horizontal" is not better. We have EVDEV_ABS, and also POINTINGSTICK_CONST_ACCEL. Abbreviating the long adjectives at the end was kind of consistent.

**Comment by poettering** [comment]
i see your point... what shall we do now? @whot, please make an executive decision whether to revert this PR or not. I am fine with either.

**Comment by whot** [comment]
I couldn't care less and if HORIZONTAL means I don't have Lennart's OCD coming after me that's fine with me :) there's nothing yet that relies on it anyway, so changing it is easy.

fwiw, EVDEV_ABS is a direct directive from the EV_ABS constants in the kernel, so it has a different history and isn't an abbreviation as such. CONST_ACCEL sticks out but I'm fine with having a generic "no abbreviations" rule

**Pull request merged**
