### PR TITLE
man: do not install sd-boot man pages when -Dgnu-efi=false is set

### PR DESCRIPTION
**Pull request by davide125**
https://github.com/systemd/systemd/commit/34357545590d4791d1acbbeb07ae8f7636e187cb gated sd-boot on `-Dgnu-efi=false`, but right now the manpages are still installed when that is set, even though the corresponding binaries are not. Update the gating to solve this.

Related: https://bugzilla.redhat.com/show_bug.cgi?id=2031426

### CODE REVIEW

**Comment by yuwata** [comment]
I guess you manually edit the file. Please do not, but update the header of corresponding man pages.

**Comment by davide125** [comment]
Oh I completely missed the comment on the top -- thanks, will fix this.

**Comment by davide125** [comment]
Updated and ran `ninja -C build update-man-rules` to ensure the rules were regenerated correctly.

**Review by yuwata — APPROVED** [review]
LGTM.

**Review by bluca — APPROVED** [review]

**Pull request merged**
