### PR TITLE
Provide unit name and operation in manage-units polkit checks

### PR DESCRIPTION
**Pull request by AnchorCat**
This patch series provides polkit action details when verifying the `org.freedesktop.systemd1.manage-units` authorization. Custom policy can be written to grant access to individual units, or particular operations on particular units, to non-administrator users.

The following details are passed:
- `unit`: the primary name of the unit upon which the action was invoked (i.e. after resolving any aliases);
- `verb`: one of `start`, `stop`, `reload`, `restart`, `try-restart`, `reload-or-restart`, `reload-or-try-restart`, `kill`, `reset-failed`, or `set-property`, corresponding to the systemctl verb used to invoke the action.

Typical use of these details in a policy rule might be:

```
// Allow alice to manage example.service;
// fall back to implicit authorization otherwise.
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.systemd1.manage-units" &&
        action.lookup("unit") == "example.service" &&
        subject.user == "alice") {
        return polkit.Result.YES;
    }
});
```

We also supply a custom pokit message that includes the unit's name and the requested operation.

Some further notes:
- A few place where `manage-units` is verified are not covered by this patch series, including:
  - starting a transient unit;
  - clearing all pending jobs;
  - creating a snapshot;
  - resetting the "failed" state on all units;
  - abandoning a scope.
- I chose to use `set-property`, not `set-properties`, as the verb for the `SetProperties` bus call, since that's how it's exposed via systemctl.
- I am in two minds whether to include the custom polkit messages. I think it provides a clearer message to the user, but it does obscure the fact that the authorization may be applied to subsequent authorization checks for some time. I can drop the custom messages if you think that's a problem.
  
  An alternative option might be to introduce a new, non-interactive PK action (`perform-unit-action` perhaps?), check this new action first and only fall back to `manage-units` if that doesn't grant authorization.

### CODE REVIEW

**Comment by poettering** [comment]
Otherwise looks good to me.

**Comment by AnchorCat** [comment]
The N_() macro marks the string for translation (which is why I added the file to po/POTFILES.in), but simply expands to the original string. systemd doesn't apply the translation; instead that's done by polkit when displaying it to the user.

As for the keys, I don't think programs are expected to prefix them with anything special. polkit reserves the "polkit." namespace. For further reference I looked at pkexec (which defines "program" and "command_line" keys), and udisks (which uses "device", "drive", etc.; see http://udisks.freedesktop.org/docs/latest/udisks-polkit-actions.html).

Do you have any problems with the concerns I raised in my final point? To reiterate, I was worried that a user might see "Authentication is required to start 'example.service'" and not realise that they're really being granted access for _any_ operation on any unit (until polkit expires the authorization). I don't think it matters too much though.

**Comment by poettering** [comment]
I thinkt the approach you took is good. We should probably introduce a new PK action for creating transient units though...

But the patch looks good AFAICS, but I would prefer to use a non-dynamically allocated array for the one case, as I pointed out.

**Comment by AnchorCat** [comment]
OK, I've just opened a new PR with these changes: #1159

**Pull request closed without merging**
