### PR TITLE
networkd: When link gets dirty mark manager dirty too.

### PR DESCRIPTION
**Pull request by ssahani**
If we not marking manager dirty when link is dirty then
the state file is not updated. This is a side effect of
issue #2850
setting CriticalConnection=yes

timesyncd NTP servers given by DHCP server are ignored.

### CODE REVIEW

**Comment by poettering** [comment]
@ssahani are you saying this fixes #2850?

**Comment by poettering** [comment]
@yuwata any chance you can check if this fixes your prob?

**Comment by ssahani** [comment]
Yes.

**Comment by poettering** [comment]
(@ssahani btw, in cases where your patch fixes a github issue, please always add a line "Fixes: #2850" or suchlike to the commit msg. Github recognizes that, and will close the issue automatically, when the PR is merged.)

**Comment by ssahani** [comment]
OK thanks for the tip .

**Comment by yuwata** [comment]
Thank you. I confirm that #2850 is fixed now. Sorry for late reply.

**Pull request merged**
