### PR TITLE
various fixes, for various things

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by keszybz** [comment]
All look good, though 2929897843a61b09469c0e7ff46ac8c0aea7ddcb is rather long. Maybe adding something like `_cleanup_strv_free_erase_` would help?

**Comment by poettering** [comment]
I thought about that, but for the cases where this would simplify things we'd need both a ptr and a size to be able to memset it, but that would mean introducing some struct there, since the cleanup stuff of course works only with single variables. And then I figured the "goto finish" thing is nicer and simpler...

**Comment by keszybz** [comment]
But it should work for strv: keszybz@9b605c7b2c374b4b3dd191f8e159b22599b42433

**Comment by poettering** [comment]
@keszybz ok, i took your patch, updated it, and added it to the PR. I think it's OK to leave this as two separate commits. Please merge, if it looks good to you now!

**Comment by keszybz** [comment]
For the record: lgtm.

**Pull request merged**
