### PR TITLE
clock-util: read timestamp from /usr/lib/clock-epoch

### PR DESCRIPTION
**Pull request by zonque**
On systems without an RTC, systemd currently sets the clock to a
compile-time epoch value, derived from the NEWS file in the
repository. This is not ideal as the initial clock hence depends
on the last time systemd was built, not when the image was compiled.

Let's provide a different way here and look at `/usr/lib/clock-epoch`.
If that file exists, its timestamp for the last modification will be
used instead of the compile-time default.

### CODE REVIEW

**Comment by poettering** [comment]
lgtm

**Comment by boucman** [comment]
This really needs to be documented somewhere...

**Comment by mbiebl** [comment]
Couldn't we just use /etc/machine-id?

**Comment by zonque** [comment]
> This really needs to be documented somewhere...

I agree. What would be a good place for that, @poettering ?

**Comment by zonque** [comment]
> Couldn't we just use /etc/machine-id?

On stateless systems with a r/o rootfs, `/etc/machine-id` is auto-generated on early boot, so it has the timestamp pid1 had at the time of creation. It's a chicken-egg problem, hence I opted for the idea of a new file that only exists for the purpose of setting the clock to something static if all other methods fail.

**Comment by poettering** [comment]
> Couldn't we just use /etc/machine-id?

That one is generated at first-boot-time. The file this PR adds is supposed to be created at build-time.

**Comment by poettering** [comment]
> I agree. What would be a good place for that, @poettering ?

Well, good question. One of those days we should probably have some markdown doc, similar to what we have for the random seed but for the clock, there's just so much details to document what people should do on RTC-less systems.

i.e. something like this:

https://systemd.io/RANDOM_SEEDS

but about the clock, timezone shifts, RTC-in-UTC vs. local-RTC and so on.

I didn't wnat to put the burden on you to put that together. But of course, you'd be very welcome to start a doc, just explain the basics of what you added in this PR, and we can fill in the rest.

**Pull request merged**
