### PR TITLE
network: rename UseFQDN= -> UseHostname=

### PR DESCRIPTION
**Pull request by yuwata**
Prompted by https://github.com/systemd/systemd/pull/18543#issuecomment-780798451.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @flo-wer.

**Comment by bluca** [comment]
Matching the RFC would be nice - maybe they could be aliases?

**Comment by yuwata** [comment]
@poettering suggests this, but @bluca dislikes this. I do not have any strong opinion about this. So,,, what should we do?

> maybe they could be aliases?

Hmm, we should not introduce any aliases for new option...

**Comment by bluca** [comment]
> @poettering suggests this, but @bluca dislikes this. I do not have any strong opinion about this. So,,, what should we do?
> 
> > maybe they could be aliases?
> 
> Hmm, we should not introduce any aliases for new option...

It was just a thought, no hard preference from me.

**Review by bluca — APPROVED** [review]

**Pull request merged**
