### PR TITLE
exec-invoke: properly look up home dir for user

### PR DESCRIPTION
**Pull request by ZLima12**
## Issue
Previously `get_home_dir` was used in `acquire_home`; this provides the home directory of the current user. However, in this case, that is the user running the service manager, not the user which will be running the unit.

The issue was masked because `get_home_dir` would not be reached most of the time; `acquire_home` returns early if home was already acquired from `get_fixed_user`. However, this may not happen if, for example, the user in question's home directory is root, since that will be suppressed to `NULL`.

## Reproducible example
- Create a user named `testuser`, with its home directory set to `/`
- Create the following service and start it:
```
[Unit]
Description=Print working directory as testuser

[Service]
Type=oneshot
User=testuser
WorkingDirectory=~
ExecStart=pwd
```

The service will fail with `Changing to the requested working directory failed: Permission denied`; it's not clear from the logs, but this is because we attempted to chdir to `/root`.

## Solution
I decided to add a `_for_uid` version for both `get_home_dir` and `get_shell`, since they were so similar. `get_shell_for_uid` is currently unused, but I plan to take a look at the various calls to both functions to make sure that they really want the info for the current user. For example, it seems like `run0` currently uses the shell of the original user, instead of the target user.

### CODE REVIEW

**Review by yuwata — CHANGES_REQUESTED** [review]
LGTM. But, could you add test case for the issue?

**Comment by poettering** [comment]
lgtm, test case would be good though

**Review by YHNdnzj — CHANGES_REQUESTED** [review]
Hm, is this really the right fix? This would also set `$HOME` and/or `$SHELL` to values that we previously suppress on purpose (see get_fixed_user()).

I figure get_fixed_user() should always return the target user's home, and store whether to set the vars in a bool separately, which would be passed to build_environment.

**Comment by YHNdnzj** [comment]
> Well, get_fixed_user can remove USER_CREDS_CLEAN from its call to get_user_creds, which would then not suppress values of either $HOME or $SHELL.

That's where the later half comes into play. Instead of suppressing those in get_user_creds, the final decision should be passed as a separate bool to build_environment.

**Comment by YHNdnzj** [comment]
> `get_fixed_user` will only be run before `acquire_home` and `build_environment` if `!(context->dynamic_user && runtime && runtime->dynamic_creds) && context->user`. If this condition isn't met, `acquire_home` will continue on to the `get_home_dir` call, so I think that should still be changed to `get_home_dir_for_uid`.

I doubt there's actually the need. If neither DynamicUser= nor User= is set, uid of the process will not be changed. So `acquire_home` doesn't need to be changed in my eyes...

**Comment by yuwata** [comment]
Pleaes add test cases...

**Comment by YHNdnzj** [comment]
> If we really don't want to make this modification, I would wish for the function to be renamed or at the very least have comments added around the call, to make clear that it will not look at the uid in the context.

I think this is a better approach really. Duplicating the logic would only make things harder to track.

**Pull request closed without merging**
