### PR TITLE
ci: turn off Azure Pipelines

### PR DESCRIPTION
**Pull request by evverx**

### CODE REVIEW

**Comment by bluca** [comment]
Any particular reason to remove it?

**Comment by evverx** [comment]
It's linked to my account there (which I stopped using last year and no longer have access to, as far as I know). Apart from that, I don't think it makes much sense to keep running that script there because the fuzzers are covered by CIFuzz.

**Comment by bluca** [comment]
> It's linked to my account there (which I stopped using last year and no longer have access to, as far as I know). Apart from that, I don't think it makes much sense to keep running that script there because the fuzzers are covered by CIFuzz.

If it's just a matter of accounting, I can probably procure one with all the credits we need (next week, as I'm still on holiday right now).

Is the fuzzing engine the same? If there's any difference, and costs are covered, IMHO it's good to have larger coverage. But if the tests are identical or without meaningful differences, then it's a different matter of course.

**Comment by szb512** [comment]
travis failure appears to be unrelated

toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

The command "$CI_MANAGERS/debian.sh SETUP" failed and exited with 1 during .

Your build has been stopped.

**Comment by evverx** [comment]
>  I can probably procure one with all the credits we need

Thanks but I don't think it's worth it.

> Is the fuzzing engine the same? If there's any difference, and costs are covered, IMHO it's good to have larger coverage. But if the tests are identical or without meaningful differences, then it's a different matter of course.

The fuzzing engine is the same. The only difference is that the script tries to make sure the fuzz targets can be built in "local" mode with all the dependencies enabled (as opposed to CIFuzz where they're skipped by default to avoid building and linking them statically). It doesn't cover anything.

Anyway, the pipeline isn't run on Azure any more so at least the badge should be removed from README.

**Comment by bluca** [comment]
> > I can probably procure one with all the credits we need
> 
> Thanks but I don't think it's worth it.
> 
> > Is the fuzzing engine the same? If there's any difference, and costs are covered, IMHO it's good to have larger coverage. But if the tests are identical or without meaningful differences, then it's a different matter of course.
> 
> The fuzzing engine is the same. The only difference is that the script tries to make sure the fuzz targets can be built in "local" mode with all the dependencies enabled (as opposed to CIFuzz where they're skipped by default to avoid building and linking them statically). It doesn't cover anything.
> 
> Anyway, the pipeline isn't run on Azure any more so at least the badge should be removed from README.

Thank you for confirming. @mrc0mmand is of the same opinion, so let's go ahead and merge this.

**Pull request merged**
