### PR TITLE
man: document that start limiting of GC'ed units doesn't work

### PR DESCRIPTION
**Pull request by poettering**
Fixes: #7139

### CODE REVIEW

**Comment by fbuihuu** [comment]
As I wrote already, the only cases where StartLimitBurst seems to be useful is when a service is restarted via `systemctl restart` or via `Restart=` option. Other cases like I described in issue #7139 make the mechanism unpredictable for the users hence shouldn't be handled.

**Comment by martinpitt** [comment]
@kesbyz: So on Ubuntu 16.04 (xenial) with latest meson 0.42 the build still fails on this `msgfmt: cannot locate ITS rules for ../src/login/org.freedesktop.login1.policy.in` issue. Not sure exactly where that came from, but apparently the build in 17.10 (artful) worked fine. Trying an amd64 build as well now. If that works, we can switch CI to 17.10 in general to get it back to green, and get newer build dependencies.

**Comment by poettering** [comment]
@fbuihuu well, I disagree. The GC logic is not really unpredictable, though it is definitely not the most obvious of concepts. To make this less surprising PR #7314 actually contains some man page additions that explain the GC logic in more detail.

Either way, this PR is primarily about documenting the logic that is in place right now.

**Comment by fbuihuu** [comment]
> @fbuihuu well, I disagree. The GC logic is not really unpredictable,

For regular users I would disagree.

How can one figure out that hte start limit will never be reached (given that `systemct restart` is supposed to be equivalent to `systemct start && systemctl stop`) when doing the following:

 `while :; do systemctl start foo.service && systemct stop foo.service; done`

whereas doing:

 `while :; do sudo <whatever command>; done`

can trigger the start limit (of the user instance service) ?

**Comment by fbuihuu** [comment]
@poettering, again why not limiting StartLimit to units that are:

1. restarted via `systemct restart`
2. restarted via `Restart=` option

That would limit the option to the cases where it can be useful and leave the cases where it can be triggered (or not) unexpectedly.

**Comment by poettering** [comment]
> @poettering, again why not limiting StartLimit to units that are:
> 
>     restarted via systemct restart
>     restarted via Restart= option
> 
> That would limit the option to the cases where it can be useful and leave the cases where it can be triggered (or not) unexpectedly.

It used to be a restartlimit actually, a long time ago. I generalized it to be a startlimit, to cover units that are triggered repeatedly and fail right-away. Think a socket-activated service which fails starting up. We need a way to make sure the service doesn't get triggered in a busy loop. And in that case it's entirely safe too, as the socket activated service remains referenced by the socket unit.

**Comment by poettering** [comment]
> How can one figure out that hte start limit will never be reached (given that systemct restart is supposed to be equivalent to systemct start && systemctl stop) when doing the following:
> 
> while :; do systemctl start foo.service && systemct stop foo.service; done

this won't trigger the limit only if the unit is GC'ed between the start/stop. For most units that are installed on systems this probably not even the case, as they are enabled, and thus hooked into multi-user.target or something like that, and hence remain constantly referenced.

**Pull request merged**
