### PR TITLE
scope: on unified, make sure to unwatch all PIDs once they've been mo…

### PR DESCRIPTION
**Pull request by fbuihuu**
…ved to the cgroup scope

Commit 428a9f6f1d0396b9eacde2b38d667cbe3f15eb55 freed u->pids which is
problematic since the references to this unit in m->watch_pids were not more
removed when the unit was freed.

This patch makes sure to clean all this refs up before freeing u->pids by
calling unit_unwatch_all_pids().

### CODE REVIEW

**Comment by mbiebl** [comment]
hi @fbuihuu, I guess this PR is supposed to fix #17768 ?

**Comment by fbuihuu** [comment]
@mbiebl yes but someone needs to double check as I missed something pretty obvious the first time :(

I'm wondering how CI didn't catch this regression...

**Comment by mbiebl** [comment]
> I'm wondering how CI didn't catch this regression...

Is there supposed to be a test for this?

**Comment by mbiebl** [comment]
@fbuihuu If we find a better reproducer then https://github.com/systemd/systemd/issues/17768#issuecomment-735248193 then it would imho definitely make sense to make a test for it.

**Comment by keszybz** [comment]
Let's merge this. I test would be nice, but we don't have a clear reproducer so I don't think it makes sense to block.

**Comment by fbuihuu** [comment]
@mbiebl the simplest reproducer I found was:

1. log in via a tty
2. systemctl daemon-reload
3. reboot or `systemctl stop session-<xxx>.scope`

where `<xxx>` is the session num created by 1.

**Comment by keszybz** [comment]
> @mbiebl the simplest reproducer I found was:

Thanks, this works here too (without the patch). With the patch, everything seems OK. I'll push the patch to v247-stable.

**Comment by mbiebl** [comment]
thanks @fbuihuu

**Pull request merged**
