### PR TITLE
network: rename eui64 to static

### PR DESCRIPTION
**Pull request by yuwata**
See RFC 4291.

Follow-up for 5f506a55606fed9fd74b851a18f15a9835a26d08.

cc @kpfleming, @ssahani and @keszybz.

### CODE REVIEW

**Comment by keszybz** [comment]
I misunderstood what the options were supposed to mean. Let's wait for @kpfleming's review who seems to understand this better.

**Comment by evverx** [comment]
@yuwata I think to make sure https://github.com/systemd/systemd/issues/14811 is gone, "eui64" should be replaced with "static" in `test/fuzz/fuzz-network-parser/oss-fuzz-20548` as well.

**Comment by yuwata** [comment]
@evverx Updated.

**Comment by kpfleming** [comment]
This is very promising! Thanks for the quick response.

In 'eui64' mode should the user still be allowed to specify an address? It seems like that is unnecessary, as the user has explicitly requested automatic generation of the IID using the EUI-64 method.

I'm also still happy to improve the documentation before this is merged; I can send a PR to @yuwata's branch if that's the simplest way to get that done.

**Comment by yuwata** [comment]
Thanks. Improvement is always welcome.

**Comment by keszybz** [comment]
Let's merge this since it fixes a crash. @kpfleming we still have a few days before the next release to fix any outstanding issues.

**Pull request merged**
