### PR TITLE
hwdb: fix microphone shortcut on HP EliteBook 840 G1

### PR DESCRIPTION
**Pull request by mrc0mmand**
Fixes: #15774

@ThesimpleMachine could you give this one a try if it fixes your issue?

### CODE REVIEW

**Comment by TheSimpleMachine** [comment]
> Fixes: #15774
> 
> @TheSimpleMachine could you give this one a try if it fixes your issue?

@mrc0mmand The solution I posted had worked on my laptop. I can disable that solution to test what you posted. However, I am do not know how to test what you posted above. Could you provide the necessary steps please?

**Comment by mrc0mmand** [comment]
> Do I replace the code I used:
> evdev:atkbd:dmi:bvn*:bvr*:bd*:svnHewlett-Packard*:pnEliteBook:pvr*
> KEYBOARD_KEY_81=f20 # Fn+F8 on Elitebook, map to F20
> 
> ...with the following code for testing:
> evdev:atkbd:dmi:bvn*:bvr*:bd*:svnHewlett-Packard*:pnHPEliteBook840G1:pvr*
> KEYBOARD_KEY_81=f20 # Fn+F8 on Elitebook, map to F20

Yup, that should do the trick, just to see if the modalias string is correct.

**Comment by TheSimpleMachine** [comment]
> > Do I replace the code I used:
> > evdev:atkbd:dmi:bvn*:bvr*:bd*:svnHewlett-Packard*:pnEliteBook:pvr*
> > KEYBOARD_KEY_81=f20 # Fn+F8 on Elitebook, map to F20
> > ...with the following code for testing:
> > evdev:atkbd:dmi:bvn*:bvr*:bd*:svnHewlett-Packard*:pnHPEliteBook840G1:pvr*
> > KEYBOARD_KEY_81=f20 # Fn+F8 on Elitebook, map to F20
> 
> Yup, that should do the trick, just to see if the modalias string is correct.

@mrc0mmand Thanks. Just tested. I can confirm that this works with the new line.
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnHewlett-Packard*:pnHPEliteBook840G1:pvr*

Just out of curiosity how does this change make it to various linux distributions?Specifically, when and how would it make it to ubuntu and would it cause problems with the manual workaround I have currently?

**Comment by keszybz** [comment]
>  how does this change make it to various linux distributions?

It'll be picked up along with the systemd release at some point. The details ar e up to each distro.

**Comment by TheSimpleMachine** [comment]
@keszybz Many thanks for this. Super excited that I have contributed to the community, even if in a small way.

**Pull request merged**
