### PR TITLE
missing: re-add mistakenly dropped entries

### LINKED ISSUE #11036: systemd seems to be failing to compile on CentOS
```
[148/1733] Compiling C object 'src/libsystemd/src@libsystemd@@systemd_static@sta/sd-netlink_netlink-types.c.o'.
FAILED: src/libsystemd/src@libsystemd@@systemd_static@sta/sd-netlink_netlink-types.c.o
cc -Isrc/libsystemd/src@libsystemd@@systemd_static@sta -Isrc/libsystemd -I../src/libsystemd -Isrc/basic -I../src/basic -Isrc/shared -I../src/shared -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/udev -I../src/udev -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I../ -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-error=nonnull -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -fPIE -Werror=shadow -include config.h -g -O0 -ftrapv -fPIC -pthread -fvisibility=default  -MD -MQ 'src/libsystemd/src@libsystemd@@systemd_static@sta/sd-netlink_netlink-types.c.o' -MF 'src/libsystemd/src@libsystemd@@systemd_static@sta/sd-netlink_netlink-types.c.o.d' -o 'src/libsystemd/src@libsystemd@@systemd_static@sta/sd-netlink_netlink-types.c.o' -c ../src/libsystemd/sd-netlink/netlink-types.c
../src/libsystemd/sd-netlink/netlink-types.c:636:10: error: ‘FRA_SUPPRESS_IFGROUP’ undeclared here (not in a function)
         [FRA_SUPPRESS_IFGROUP]    = { .type = NETLINK_TYPE_U32 },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:636:9: error: array index in initializer not of integer type
         [FRA_SUPPRESS_IFGROUP]    = { .type = NETLINK_TYPE_U32 },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:636:9: error: (near initialization for ‘rtnl_routing_policy_rule_types’)
../src/libsystemd/sd-netlink/netlink-types.c:637:10: error: ‘FRA_SUPPRESS_PREFIXLEN’ undeclared here (not in a function)
         [FRA_SUPPRESS_PREFIXLEN]  = { .type = NETLINK_TYPE_U32 },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:637:9: error: array index in initializer not of integer type
         [FRA_SUPPRESS_PREFIXLEN]  = { .type = NETLINK_TYPE_U32 },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:637:9: error: (near initialization for ‘rtnl_routing_policy_rule_types’)
[149/1733] Compiling C object 'src/libsystemd/src@libsystemd@@systemd_static@sta/sd-netlink_netlink-util.c.o'.
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #11036.

cc @evverx.

### CODE REVIEW

**Comment by evverx** [comment]
@yuwata thank you! I'll launch a CentOS VM shortly and report back how it goes

**Comment by evverx** [comment]
Now it's complaining about `IPVLAN_F_PRIVATE`:
```
[459/1733] Compiling C object 'src/network/src@network@@networkd-core@sta/meson-generated_.._netdev-gperf.c.o'.
FAILED: src/network/src@network@@networkd-core@sta/meson-generated_.._netdev-gperf.c.o
cc -Isrc/network/src@network@@networkd-core@sta -Isrc/network -I../src/network -Isrc/basic -I../src/basic -Isrc/shared -I../src/shared -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/udev -I../src/udev -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I../ -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-error=nonnull -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -fPIE -Werror=shadow -include config.h -g -O0 -ftrapv -fPIC  -MD -MQ 'src/network/src@network@@networkd-core@sta/meson-generated_.._netdev-gperf.c.o' -MF 'src/network/src@network@@networkd-core@sta/meson-generated_.._netdev-gperf.c.o.d' -o 'src/network/src@network@@networkd-core@sta/meson-generated_.._netdev-gperf.c.o' -c src/network/netdev-gperf.c
In file included from ../src/network/netdev/netdev-gperf.gperf:11:0:
../src/network/netdev/ipvlan.h:19:39: error: ‘IPVLAN_F_PRIVATE’ undeclared here (not in a function)
         NETDEV_IPVLAN_FLAGS_PRIVATE = IPVLAN_F_PRIVATE,
                                       ^
../src/network/netdev/ipvlan.h:20:36: error: ‘IPVLAN_F_VEPA’ undeclared here (not in a function)
         NETDEV_IPVLAN_FLAGS_VEPA = IPVLAN_F_VEPA,
                                    ^
[460/1733] Compiling C object 'src/network/src@network@@networkd-core@sta/meson-generated_.._networkd-network-gperf.c.o'.
ninja: build stopped: subcommand failed.
```

**Comment by yuwata** [comment]
@evverx Please test this again. If still fails, could you give me the rpm of kernel-headers you use.

**Comment by evverx** [comment]
@yuwata I was a little bit frustrated and destroyed the VM :-) Now that I've cooled down I'll spin it up again. Basically I use the scripts from systemd-centos-ci, which turns CentOS into something completely different, so let's cc @mrc0mmand just in case.

**Comment by evverx** [comment]
Now the script is installing systemd which means that it was built successfully. I'll run `systemd-networkd-test.py` while I'm at it. In the meantime, we should probably wait for Ubuntu CI to finish.

**Comment by yuwata** [comment]
Have you disabled firewalld? Anyway, please file the failure at #10908 or as a new issue.

**Comment by evverx** [comment]
Yes, the firewall is turned off and I'll paste the output of the test later. @yuwata just to be clear it was my idea to disable the test there altogether and I still think it was the right thing to do.

**Pull request merged**
