### PR TITLE
various cgroup fixes

### PR DESCRIPTION
**Pull request by poettering**
Mostly to get cgroupsv2 into shape.

### CODE REVIEW

**Comment by yuwata** [comment]
The commit 'tests: make "test-execute" work in "sudo ninja -C build test"' is already merged by #7463.

**Comment by keszybz** [comment]
Please rebase.

**Comment by poettering** [comment]
rebased!

**Comment by keszybz** [comment]
Fedora CI is failing on memfd_create, already fixed elsewhere.

**Pull request merged**
