### PR TITLE
nspawn: unref the notify event source

### LINKED ISSUE #4934: nspawn: 2,404 (648 direct, 1,756 indirect) bytes in 1 blocks are definitely lost
```
$ sudo ./libtool --mode=execute valgrind --leak-check=full ./systemd-nspawn -D CONT --register=no -b
...
==8861==
==8861== HEAP SUMMARY:
==8861==     in use at exit: 6,652 bytes in 14 blocks
==8861==   total heap usage: 46 allocs, 32 frees, 51,623 bytes allocated
==8861==
==8861== 2,404 (648 direct, 1,756 indirect) bytes in 1 blocks are definitely lost in loss record 13 of 14
==8861==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==8861==    by 0x1E600C: sd_event_new (sd-event.c:431)
==8861==    by 0x12B609: main (nspawn.c:4027)
==8861==
==8861== LEAK SUMMARY:
==8861==    definitely lost: 648 bytes in 1 blocks
==8861==    indirectly lost: 1,756 bytes in 11 blocks
==8861==      possibly lost: 0 bytes in 0 blocks
==8861==    still reachable: 4,248 bytes in 2 blocks
==8861==         suppressed: 0 bytes in 0 blocks
```
Regression introduced in https://github.com/systemd/systemd/pull/3474

cc @alepuccetti , @alban

### PR DESCRIPTION
**Pull request by evverx**
Fixes:
```
sudo ./libtool --mode=execute valgrind --leak-check=full ./systemd-nspawn -D ./CONT/ -b
...
==21224== 2,444 (656 direct, 1,788 indirect) bytes in 1 blocks are definitely lost in loss record 13 of 15
==21224==    at 0x4C2FA50: calloc (vg_replace_malloc.c:711)
==21224==    by 0x4F6F565: sd_event_new (sd-event.c:431)
==21224==    by 0x1210BE: run (nspawn.c:3351)
==21224==    by 0x123908: main (nspawn.c:3826)
==21224==
==21224== LEAK SUMMARY:
==21224==    definitely lost: 656 bytes in 1 blocks
==21224==    indirectly lost: 1,788 bytes in 11 blocks
==21224==      possibly lost: 0 bytes in 0 blocks
==21224==    still reachable: 8,344 bytes in 3 blocks
==21224==         suppressed: 0 bytes in 0 blocks
```
Closes #4934

### CODE REVIEW

**Comment by evverx** [comment]
Hm,
```
FAIL: test_no_failed (__main__.ServicesTest)
No failed units
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.Za8o4J/build.8Sz/debian/debian/tests/boot-and-services", line 60, in test_no_failed
    self.assertEqual(failed, [])
AssertionError: Lists differ: ['ifup@ens2.service loaded failed failed ifup for ens2'] != []
```
> -- Logs begin at Wed 2016-12-21 15:47:57 UTC, end at Wed 2016-12-21 15:48:16 UTC. --
Dec 21 15:47:58 autopkgtest systemd[1]: Started ifup for ens2.
Dec 21 15:47:58 autopkgtest systemd[1]: ifup@ens2.service: Unit is bound to inactive unit sys-subsystem-net-devices-ens2.device. Stopping, too.
Dec 21 15:47:58 autopkgtest systemd[1]: Stopping ifup for ens2...

This is https://github.com/systemd/systemd/issues/4725
Is there https://anonscm.debian.org/cgit/collab-maint/ifupdown.git/commit/?id=3dfd3590?
@martinpitt ?

**Comment by martinpitt** [comment]
@evverx : yes, I backported that commit  to the overlay PPA ages ago: https://launchpadlibrarian.net/294934561/ifupdown_0.8.10ubuntu1_0.8.10ubuntu1.1pitti1.diff.gz

**Comment by evverx** [comment]
@martinpitt , seems like `After=` didn't fix #4725 
Should we reopen #4725?

**Comment by martinpitt** [comment]
@evverx : sorry, that was it after all -- the PPA version got shadowed by a stable release update in Ubuntu xenial proper. I merged that and uploaded a newer version to the PPA again. Once that is published (in about 30 mins) we can retry PR #4949 and other affected ones.

**Pull request merged**
