### PR TITLE
Enable TasksMax by default for all units

### PR DESCRIPTION
**Pull request by poettering**
with this change we'll se TasksMax=512 for all units by default, with the exception of per-user slices which default to TasksMax=4096 and nspawn containers which defaul to 8192.

Also contains a bunch of unrelated fixes.

### CODE REVIEW

**Comment by evverx** [comment]
original thread: http://lists.freedesktop.org/archives/systemd-devel/2015-November/035006.html

**Comment by poettering** [comment]
Thanks for the review, will force push a fixed set shortly!

**Comment by poettering** [comment]
ok, should be all fixed now.

**Comment by evverx** [comment]
Yeah, test passes, thanks!
But I don't understand why [old build](https://semaphoreci.com/systemd/systemd/branches/pull-request-1886/builds/1) passed.

**Comment by poettering** [comment]
@evverx my guess is that the semaphore machines lack the pids controller or so, and hence the code was not actually tested there...

**Comment by poettering** [comment]
@keszybz fixed now, thanks!

**Pull request merged**
