### PR TITLE
Allow overriding pkgconfig prefixes

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by martinpitt** [comment]
This causes a regression in the unit-config test, as shown by the bionic-i386 test here: 
`pkg-config --variable=systemdsystemunitdir systemd` now starts with two slashes.

**Comment by keszybz** [comment]
> pkg-config --variable=systemdsystemunitdir systemd now starts with two slashes

Is this a real problem, or just ugly?

**Comment by martinpitt** [comment]
We can certainly adjust the unit-config test to get along with it. At first sight it's just ugly, but of course it might cause other weird effects in projects that use `systemdsystemunitdir` (there's a lot of them).

**Comment by martinpitt** [comment]
I adjusted the test to tolerate such duplicate slashes: https://salsa.debian.org/systemd-team/systemd/commit/3da52a0fab3cfaf0

**Comment by michaelolbrich** [comment]
@keszybz at least the chromium build system interprets paths that start with `//` as relative to the top-level source directory. I've looked at this more closely but I'm guessing that this is a `gn` feature.
I don't think tat chromium uses `systemdsystemunitdir` but other `gn` users might.

**Comment by keszybz** [comment]
Well, that'd be completely insane. You might just as well declare that paths ending in "/" signify optional dependencies.

I'm not happy about the double slash, 'cause its ugly, and might fail in literal comparison, but seriously, if you somebody decides to reinterpret filesystem paths in some completely incompatible fashion, then they get to keep the pieces.

**Pull request merged**
