### PR TITLE
Added support for 3D printers to uaccess (ID_3DPRINTER)

### PR DESCRIPTION
**Pull request by yarda**
This will allow classification of peripherals as 3D printers and will allow finer grain access control. We are ready to use this (or similar) tag/env in our 3D printers rules.

### CODE REVIEW

**Comment by teg** [comment]
Sounds fine, but are you sure you don't want something slightly more generic? I mean there could be a many similar tools to 3D printers that are not 3D printers CNC router, laser cutter, or any other kind of "maker tool"?

**Comment by hroncok** [comment]
Or a 3D scanner.

**Comment by yarda** [comment]
@teg: Thanks for looking at it.

I was focusing only on 3D printers (as widespread low cost HW). I am not against anything more generic, but I have no idea how it should be named (e.g. ID_3D_MODELAR? just guessing). Also I am not sure what's better approach:
- to have one ID for CNC/3D printer class of devices or 
- separate IDs for 3D printer, CNC, ..., to distinguish

Any ideas?

**Comment by teg** [comment]
We'd prefer to have only one ID for a class of devices, rather than being too specific (or we will have an explosion of tags pretty soon), so if you manage to come up with some name that is as generic as possible, but still useful for what you need that would be great. If there are no better suggestions, I suppose going with the specific one would be ok.

**Comment by yarda** [comment]
@hroncok: any idea for generic ID?

**Comment by hroncok** [comment]
ID_MAKERTOOL

**Comment by yarda** [comment]
Ok no problem with ID_MAKERTOOL, if nobody is against I will update the PR.

**Comment by keszybz** [comment]
MAKERTOOL is fine, but please spell it `ID_MAKER_TOOL`. Other tags are spelled with underscores between words.

Alternatively, what about `ID_3D_TOOL`? I think it's more intuitive.

**Comment by hroncok** [comment]
ID_3D_TOOL dosn't work with laster cutters, etc.

**Comment by keszybz** [comment]
I think a laser cutter still operates on 3D objects... but that's bikeshedding.

**Comment by hroncok** [comment]
I'd prefer ID_MAKER_TOOL but I'm not strongly against ID_3D_TOOL

**Comment by yarda** [comment]
Of course I will add comment near the ID stating that it's targeted to 3D printers, CNC, laser cutters, etc., so it should be easy to find by e.g. full text search.

**Comment by keszybz** [comment]
`ID_MAKER_TOOL` is fine. Can you squash the two commits and force push?

**Comment by yarda** [comment]
Push forced updated version.

**Comment by keszybz** [comment]
Thanks.

**Pull request merged**
