### PR TITLE
export sd_bus_object_added() / _removed()

### LINKED ISSUE #306: missing exports: sd_bus_emit_object_*
The following two methods are defined in sd-bus.h but are not marked as public nor exported via libsystemd.sym:
- `sd_bus_emit_object_added()`
- `sd_bus_emit_object_removed()`

I assume these are public and that they are missing exports (or are these erroneous declarations in sd-bus.h?)

### PR DESCRIPTION
**Pull request by geertj**
Fixes #306.

### CODE REVIEW

**Comment by crrodriguez** [comment]
Nope, new symbols exported have to go in a new release and therefore in a
new symbol versioning section..

**Comment by geertj** [comment]
@crrodriguez Nope what (not right solution or doesn't fix problem)?

It is easy to add this to LIBSYSTEMD_222. But I'm not sure if that is what you want.

Currently a user who use this symbol from sd-bus.h will be able to compile his program, but not run it as the symbol is missing from the shared library.

This is not a "hey I need this symbol to be public" request. This is a bugreport of a mismatch between sd-bus.h and libsystemd.sym.

**Comment by keszybz** [comment]
Yeah, this should go in a new release. A certain .so version .X.Y is a promise that a certain set of symbols is available. If we add a new symbol without bumping Y, somebody could compile a program linking to libsystemd on an updated system, and copy it to an un-updated system, and it will crash there. The header file is not authoritative, the .sym file is.

**Comment by dvdhrm** [comment]
Yes, as @keszybz explained, can you resubmit your patch and put the symbols into 222 section?

**Comment by geertj** [comment]
@dvdhrm @keszybz new patch, putting the newly exported symbols in LIBSYSTEMD_222

**Pull request merged**
