### PR TITLE
keymap: Add Samsung NP350V and NP670Z

### PR DESCRIPTION
**Pull request by dslul**

### CODE REVIEW

**Comment by martinpitt** [comment]
As said on the previous PR, please `rebase -i` the commits to one clean one and `push -f`. We don't want to retain the intermediate "bad" one. Thanks!

**Comment by dslul** [comment]
Sorry, now it should be OK.

**Comment by poettering** [comment]
@martinpitt We so far asked people to do new PRs instead of force pushing... I am  not a fan of force pushing I must say and losing the comments and reviews of the original submission.

**Comment by martinpitt** [comment]
@mezcalero yes, that's what I did -- PR #123 was the original PR with my review comments, and I asked to open a new one. But I did that to avoid having broken commits with followup fixes, I want one "good" commit in trunk.

**Comment by martinpitt** [comment]
Thanks @dslul, looks good now!

**Comment by martinpitt** [comment]
@dslul: Sorry, missed that originally: Can you please `git commit --amend` and change the title to "keymap: Add Samsung NP350V and NP670Z"? We usually prefix commits with the "subsystem". Thanks!

**Pull request closed without merging**
