### PR TITLE
hashmap: add a flag to control hashmap uses mempool or not

### PR DESCRIPTION
**Pull request by yuwata**
Replaces #10021.

~~Not tested. I will test this later.~~

### CODE REVIEW

**Comment by yuwata** [comment]
Seems works fine. With this lightdm (Xorg+libinput) works fine.

**Comment by fbuihuu** [comment]
Hello @yuwata, couldn't the flag be used with `use_pool()` instead ?

That would limit the size of the changes at least.

**Comment by yuwata** [comment]
@fbuihuu Hmm, if it is possible, then it is better. But I do not have any idea how to implement that now...

**Comment by fbuihuu** [comment]
forget about it, after a second glance, your patch seems the only way to do that. Sorry for the noise.

**Comment by yuwata** [comment]
No problem. Thanks.

**Comment by poettering** [comment]
i prepped #10286, which implements my idea with duplicate compilation

**Comment by yuwata** [comment]
Close this in favor of #10286.

**Pull request closed without merging**
