### PR TITLE
fix: Unknown variable "efi_arch"

### LINKED ISSUE #21258: Unknown variable "efi_arch" with -Defi=false
**systemd version the issue has been seen with**
 > current `main`

**Used distribution**
 > ArchLinux

**Linux kernel version used** (`uname -a`)

 > `N/A`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > systemd should build with `-Defi=false`

**Unexpected behaviour you saw**
 > meson configure fails

**Steps to reproduce the problem**
 > try to configure systemd with `-Defi=false`

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
systemd/src/boot/efi/meson.build:48:3: ERROR: Unknown variable "efi_arch".
```

### PR DESCRIPTION
**Pull request by yurikoles**
Closes #21258

Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

### CODE REVIEW

**Comment by medhefgo** [comment]
Ooops, mea culpa.

If it can wait till tomorrow, I have an idea to rework the efi meson.build to make things much nicer and will fix this alongside.

**Comment by keszybz** [comment]
@medhefgo ?

**Comment by yuwata** [comment]
The first commit in #21264 should replace this PR.

**Comment by medhefgo** [comment]
I moved that commit out into #21278.

**Pull request closed without merging**
