### PR TITLE
documentation: proper English

### PR DESCRIPTION
**Pull request by shawnl**
"ellipsize" is a neologism, the proper word is "elide"

This made-up word is all over the code,
but don't let it get into the documentation.

https://www.merriam-webster.com/dictionary/elide

### CODE REVIEW

**Comment by shawnl** [comment]
> [We might also choose to use proper ellipsation here](https://github.com/systemd/systemd/pull/4540/commits/3394af85d3d6f646669d33e69749ea65ff548700) -Lennart

We might also choose to elide here

As Harold Evans says in _Why Writing Well Matters_ when commenting on Google's mis-use of the word [deprecate](https://www.merriam-webster.com/dictionary/deprecate):
> We are deprecating the classic Google Admin console...

[N]ouns and verbs aren't bits of silicon you can dope with chemicals (boron, phosphorus, and arsenic), drop into a kiln at 2,000 degrees Fahrenheit, and slice and dice.

**Comment by evverx** [comment]
@shawnl, thank you for spotting this. As a non-native English speaker, I think that something like "leave out" or "omit" would be much easier to understand. But I'll leave it to someone else who knows English better to decide what to use :-)

Some other dictionaries have already been updated, so the wrong meaning of "deprecate" is not as incorrect as it used to be:
* https://ahdictionary.com/word/search.html?q=deprecate
* https://www.macmillandictionary.com/dictionary/american/deprecate
* https://www.oxfordlearnersdictionaries.com/definition/english/deprecate?q=deprecate

:-)

**Comment by shawnl** [comment]
"omit" is a great word

**Comment by shawnl** [comment]
@evverx How about this, with truncate. Not sure about provide the synonym where the difference really matters to the documentation.

**Comment by evverx** [comment]
@shawnl I think that "truncate" is better than "ellipsize" probably because I'm used to it. Another word I've just found in the man page for `less` is "chopped" (`less` even has the option `--chop-long-lines`).

I'm afraid I can't help with a proper synonym for "elide". To be honest, If I wrote something like this, I would simply use "omit such-and-such from so-and-so".

**Comment by shawnl** [comment]
I like chop. (_I am going to chop up some carrots for dinner._) It is a common non-technical non-jargon word and gets the idea across.

**Comment by keszybz** [comment]
Sorry, but no. We have gone over this before, and formal grammatical correctness aside, when I say "This text contains ellipsized lines", or even "This text has been ellipsized", there is no ambiguity. When I say "this text contains elided lines" or "... contains lines that have been elided" (or whatever the correct form is, it's not too easy to phrase properly), my meaning is ambiguous. The primary issue is that "elide" can mean skipping both of entire lines and of words within a line, and those operations have very different meanings for the user. So yeah, "ellipsize" is a neologism, but it has a very clear meaning in this context, so we're keeping it.

(Generally, I think we should accept neologisms once they gain a meaning that is not covered by an existing word. This is especially true for technical documents, where we generate new meanings all the time, so we need new words too.)

**Comment by poettering** [comment]
Well, it doesn't matter whether something is a neologism or a word from the middle ages. It matters that it it is an established, precise term. And it is, we didn't come up with it. See for example:

https://developer.gnome.org/gtk3/stable/GtkLabel.html#gtk-label-set-ellipsize
https://developer.android.com/reference/android/widget/TextView.html#attr_android:ellipsize

And yes, this has been discussed before:

https://lists.freedesktop.org/archives/systemd-devel/2014-February/thread.html#16656

I think if Android and Gtk use the term that should definitely be good with us, too.

**Comment by evverx** [comment]
Thank you. I didn't know that it had been discussed before. It would be interesting to find out why this word bothers people so much :-)

> when I say "This text contains ellipsized lines", or even "This text has been ellipsized", there is no ambiguity

I read a book the other day in which the authors have trouble defining the meaning of "ellipsis". @keszybz, just out of curiosity, when you say "ellipsized line" do you mean that something has just been left out or that something has been left out and replaced with an ellipsis?

**Comment by keszybz** [comment]
> @keszybz, just out of curiosity, when you say "ellipsized line" do you mean that something has just been left out or that something has been left out and replaced with an ellipsis?

Left out and replaced with an ellipsis.

**Pull request closed without merging**
