### PR TITLE
A variety of man page fixes

### PR DESCRIPTION
**Pull request by poettering**
Let's close some bugs…

If you find typos or would like to reword things, please send another PR. As long as this patch doesn't break the build (which is unlikely) I'd rather see this go in quickly, instead of staying for longer in review cycles...

### CODE REVIEW

**Comment by zonque** [comment]
Except for the minor details I commented on, this lgtm.

**Comment by poettering** [comment]
tsss. I asked to just merge the PR and push another PR with typo fixes ;-)

**Comment by poettering** [comment]
anyway, will update and force push

**Comment by poettering** [comment]
force pushed the fix now. please apply!

**Pull request merged**
