### PR TITLE
fix bash shebangs

### PR DESCRIPTION
**Pull request by Mic92**
Similar to: 

https://github.com/systemd/systemd/pull/15014
https://github.com/systemd/systemd/pull/7701
https://github.com/systemd/systemd/pull/5816

### CODE REVIEW

**Comment by keszybz** [comment]
In for a penny, in for a pound.

**Comment by bluca** [comment]
Mmh I don't see how it's related, but the bionic tests are failing with:

```
unit-tests           FAIL non-zero exit status 1
autopkgtest [19:24:49]: test unit-tests:  - - - - - - - - - - stderr - - - - - - - - - -
Traceback (most recent call last):
  File "test/run-unit-tests.py", line 4, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
```

`dataclasses` is part of the Python standard library, so it's unlikely to be a missing dependency of some sort... what's going on?

**Comment by bluca** [comment]
Ah never mind, it's failing in another new PR as well

**Comment by Mic92** [comment]
> Mmh I don't see how it's related, but the bionic tests are failing with:
> 
> ```
> unit-tests           FAIL non-zero exit status 1
> autopkgtest [19:24:49]: test unit-tests:  - - - - - - - - - - stderr - - - - - - - - - -
> Traceback (most recent call last):
>   File "test/run-unit-tests.py", line 4, in <module>
>     import dataclasses
> ModuleNotFoundError: No module named 'dataclasses'
> ```
> 
> `dataclasses` is part of the Python standard library, so it's unlikely to be a missing dependency of some sort... what's going on?

My guess is that the python version is too old? dataclasses was introduced in 3.7 or 3.8. It should be in the standard lib in any case.

**Comment by yuwata** [comment]
It is not related. See #19640.

**Pull request merged**
