### PR TITLE
core, job: fix breakage of ordering dependencies by systemctl reload command

### PR DESCRIPTION
**Pull request by d-hatayama**

### CODE REVIEW

**Comment by d-hatayama** [comment]
I want to fix something to remove the label ci-fails/needs-rework, but I don't know what causes the label. There are many things that fail, I think some of them are not due to the patch set. Maybe, is it enough to failures on unit tests regarding job handling?

**Comment by anitazha** [comment]
@d-hatayama You can click on "Details" below to see logs from the failed CI. I looked at a couple of the failing CIs and it is for unit tests. So if you fix the unit tests like you said it should be fine.

**Comment by d-hatayama** [comment]
Thanks, @anitazha . It looks to me that the problematic patch is the 2nd one only, but this is actually not related to Issue #10464. I'll re-post the 2nd patch as another PR.

**Comment by d-hatayama** [comment]
I removed the 2nd patch, which I'll request another PR later. I also modified the patch description of the 1st patch.

**Pull request merged**
