### PR TITLE
Skip mkosi runs on docs-only changes and some small cleanups

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
```
2022-11-10 14:22:52 [ERROR]   Found errors in [actionlint] linter!
2022-11-10 14:22:52 [ERROR]   Error code: 1. Command output:
------
.github/workflows/mkosi.yml:23:5: both "paths" and "paths-ignore" filters cannot be used for the same event "push". note: use '!' to negate patterns [events]
   |
23 |     paths:
   |     ^~~~~~
.github/workflows/mkosi.yml:41:5: both "paths" and "paths-ignore" filters cannot be used for the same event "pull_request". note: use '!' to negate patterns [events]
   |
41 |     paths:
   |     ^~~~~~
```

**Review by mrc0mmand — APPROVED** [review]

**Comment by mrc0mmand** [comment]
So, with this PR all mkosi tests end up in an emergency mode when booting the built VM:

```
Activating default unit: mkosi-check-and-shutdown.service
mkosi-check-and-shutdown.service: Failed to load configuration: No such file or directory
Unit mkosi-check-and-shutdown.service not found.
Falling back to rescue.target.
```

I'm not sure, yet, what's going on.

**Comment by mrc0mmand** [comment]
Ah, I see, it seems like mkosi ignores the `mkosi.config` file?

Because with this PR:

```
       CleanPackageMetadata: auto
              Build Script: /home/runner/work/systemd/systemd/mkosi.build
        Script Environment: ASAN_OPTIONS=verify_asan_link_order=false
                 Run tests: yes
```

but checking a build outside of this PR (with `mkosi.default`) yields:
```
CleanPackageMetadata: auto
        Build Script: /home/runner/work/systemd/systemd/mkosi.build
  Script Environment: CI_BUILD=1
                      ASAN_OPTIONS=verify_asan_link_order=false
           Run tests: yes
```

(and the `CI_BUILD=1` variable here is what makes `mkosi.build` to install the test service)

**Comment by keszybz** [comment]
I dropped the change of suffix from .default to .config. Let's see what happens now.

**Review by mrc0mmand — APPROVED** [review]

**Pull request merged**
