### PR TITLE
Use SET_FLAG in more places

### PR DESCRIPTION
**Pull request by keszybz**
This pattern repeats occasionally, let's add a helper for it.

There's a bunch of more occurrences in #5598.

### CODE REVIEW

**Comment by poettering** [comment]
We already have a macro for this, and it's called SET_FLAG (i.e. just uppercase)

**Comment by keszybz** [comment]
Yikes!

**Comment by keszybz** [comment]
Updated.

**Comment by poettering** [comment]
(it might make sense to add a coccinelle script for this..)

**Pull request merged**
