### PR TITLE
cgroup2: use new fstype for unified hierarchy

### PR DESCRIPTION
**Pull request by alban**
Since Linux v4.4-rc1, __DEVEL__sane_behavior does not exist anymore and
is replaced by a new fstype "cgroup2".

https://github.com/torvalds/linux/commit/67e9c74b8a873408c27ac9a8e4c1d1c8d72c93ff

---

Question: should systemd support unified hierarchy both before and after 
Linux v4.4-rc1? If so, systemd needs to support both 
__DEVEL__sane_behavior and cgroup2.

By the way, systemd-cgls is broken with the unified hierarchy.

### CODE REVIEW

**Comment by alban** [comment]
More commits added in this branch implementing cgroup namespaces (CLONE_NEWCGROUP).

**Comment by poettering** [comment]
I figure we should drop the old __DEVEL__sane_behaviour as soon as 4.4 is out, and probably merge this patch only then too.

**Comment by poettering** [comment]
I added the "postponed" label, to indicate that this should wait until 4.4 is released.

**Comment by poettering** [comment]
Hmm I don't see how cgroupns could even work in the legacy hierarchy, as the top-level dir in cgroupfs was always special in the legacy hierarchy, and hat a couple of settings the others didn't have, such as notifier support.

Anyway, happy to see cgroups2 and cgroupsns supported, but if both of these only apply to the unified hiearchy anyway, then i'd prefer if we'd just make use of them unconditionally, after all the stuff is in flux anyway, and the fewer options the better.

**Comment by zonque** [comment]
Replaced by #2332

**Comment by poettering** [comment]
@zonque I think you closed the wrong bug here...

**Comment by zonque** [comment]
Oh, sorry. Indeed.

**Comment by poettering** [comment]
I guess #2271 replaces this one.

**Comment by alban** [comment]
For the record, the status of this branch:

> commit 4a8d16c932e6bfb5e2545195cb6cf787afc39b7a
>     nspawn: implement cgroup namespaces

Not merged. TODO.

> commit a35b159b2ae40d545a0cda373d3bf56cb06421c3
>     nspawn: userns and cgroup2: chown cgroup.events

Replaced by ab2c3861dcbece00d1c03357556faced6e048de0

> commit 69395c2ac29c099d636ca12f75ab5d4badc025ef
>     nspawn: refuse to start a container out of it cgroup namespace root

Not merged. TODO.

> commit d8c6e5fd883bb0f8c3d1d732234b2c820678b78b
>     cgroup2: use new fstype for unified hierarchy

Merged as 099619957a0d9ae0e6e5e221493e40fb8fc2cd81

**Comment by keszybz** [comment]
> commit 4a8d16c
> nspawn: implement cgroup namespaces

Can we make this the default when we switch to unified hierarchy?

**Comment by alban** [comment]
> Can we make this the default when we switch to unified hierarchy?

Yes we could. We should however make sure the kernel supports cgroupns by [checking /proc/self/ns/cgroup](https://lkml.org/lkml/2016/2/26/1044), and just not use cgroupns if not supported. The commit above does not do this.

**Pull request closed without merging**
