### PR TITLE
tests: skip tests when cg_pid_get_path fails

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
lgtm

**Comment by poettering** [comment]
Looks good to me, but CI failed, it shows some format string type issues. WHich isn't surprising as the type is basically randomly defined on the various archs. See the definition of out `statfs_f_type_t` after all...

To print it I figure the best way is to cast it to (unsigned long) or so, explicitly

**Comment by keszybz** [comment]
Updated.

**Comment by poettering** [comment]
excellent, lgtm

**Comment by keszybz** [comment]
xenial-i386 fails in boot-and-services. Looks unrelated.

**Comment by keszybz** [comment]
`xenial-i386` is the same, seems unrelated. I'll just merge this, since the code changes are in tests, apart from one trivial snippet.

**Pull request merged**
