### PR TITLE
core/cgroup: add a helper macro for a common pattern

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
the concept looks good, but I am not sure I like the name `xyz_FLAG()` for it. To me "flags" suggests a bitfield, but this isn't really one. maybe call this UNIT_CGROUP_FEATURE()? or UNIT_CGROUP_HAS()? or UNIT_CGROUP_BOOL()? or so?

**Comment by poettering** [comment]
lgtm

**Comment by keszybz** [comment]
`test-execute` fails in `xenial-390x`, but I don't see why:
```
exec-read-only-path-succeed.service: Child 1657 belongs to exec-read-only-path-succeed.service
exec-read-only-path-succeed.service: Main process exited, code=exited, status=0/SUCCESS
exec-read-only-path-succeed.service: Running next main command for state start.
exec-read-only-path-succeed.service: Passing 0 fds to service
exec-read-only-path-succeed.service: About to execute: /bin/sh -x -c '! /bin/touch /tmp/thisisasimpletest'
exec-read-only-path-succeed.service: Forked /bin/sh as 1658
Followed symlinks /tmp → /tmp.
Applying namespace mount on /tmp
Successfully mounted /tmp to /tmp
Remounted /tmp read-only.
exec-read-only-path-succeed.service: Executing: /bin/sh -x -c '! /bin/touch /tmp/thisisasimpletest'
+ /bin/touch /tmp/thisisasimpletest
/bin/touch: cannot touch '/tmp/thisisasimpletest': Read-only file system
Received SIGCHLD from PID 1658 (sh).
Child 1658 (sh) died (code=exited, status=0/SUCCESS)
exec-read-only-path-succeed.service: Child 1658 belongs to exec-read-only-path-succeed.service
exec-read-only-path-succeed.service: Main process exited, code=exited, status=0/SUCCESS
exec-read-only-path-succeed.service: Running next main command for state start.
exec-read-only-path-succeed.service: Passing 0 fds to service
exec-read-only-path-succeed.service: About to execute: /bin/rm /tmp/thisisasimpletest
exec-read-only-path-succeed.service: Forked /bin/rm as 1660
exec-read-only-path-succeed.service: Executing: /bin/rm /tmp/thisisasimpletest
DirectoryPreserve: no
	RuntimeDirectoryMode: 0755
	StateDirectoryMode: 0755
	CacheDirectoryMode: 0755
	LogsDirectoryMode: 0755
	ConfigurationDirectoryMode: 0755
	StandardInput: null
	StandardOutput: inherit
	StandardError: inherit
	DynamicUser: no
	ReadOnlyPaths: /tmp
	LockPersonality: no
FAIL: test-execute (code: 1)
```
I doubt it's related though.

**Comment by poettering** [comment]
ok, let's merge this then.

**Pull request merged**
