### PR TITLE
network: cleanups for creating or enslaving netdevs

### PR DESCRIPTION
**Pull request by yuwata**
Fixes the order of processing requests.

Split out of #21648.

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

**Comment by yuwata** [comment]
`test_macvtap` failed with timeout. Hmm? Requesting master interface index takes 16 seconds?? There should be no netlink handling after the previous log line.
```
Dec 07 09:20:24 n59.crusty.ci.centos.org systemd-networkd[243523]: macvtap99: Requested to set interface group
Dec 07 09:20:40 n59.crusty.ci.centos.org systemd-networkd[243523]: macvtap99: Requested to set master interface
```
@mrc0mmand Were there any issue on CI environment? Could you restart the failed CentOS CI?

**Comment by mrc0mmand** [comment]
> `test_macvtap` failed with timeout. Hmm? Requesting master interface index takes 16 seconds?? There should be no netlink handling after the previous log line.
> 
> ```
> Dec 07 09:20:24 n59.crusty.ci.centos.org systemd-networkd[243523]: macvtap99: Requested to set interface group
> Dec 07 09:20:40 n59.crusty.ci.centos.org systemd-networkd[243523]: macvtap99: Requested to set master interface
> ```
> 
> @mrc0mmand Were there any issues on CI environment? Could you restart the failed CentOS CI?

Yup, looks like it was indeed a machine hiccup, everything is green now \o/

**Comment by yuwata** [comment]
> > `test_macvtap` failed with timeout. Hmm? Requesting master interface index takes 16 seconds?? There should be no netlink handling after the previous log line.
> > ```
> > Dec 07 09:20:24 n59.crusty.ci.centos.org systemd-networkd[243523]: macvtap99: Requested to set interface group
> > Dec 07 09:20:40 n59.crusty.ci.centos.org systemd-networkd[243523]: macvtap99: Requested to set master interface
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @mrc0mmand Were there any issues on CI environment? Could you restart the failed CentOS CI?
> 
> Yup, looks like it was indeed a machine hiccup, everything is green now \o/

Thank you!

**Pull request merged**
