### PR TITLE
virt: detect bhyve hypervisor

### PR DESCRIPTION
**Pull request by lbschenkel**

### CODE REVIEW

**Comment by keszybz** [comment]
Looks nice, but we need an update for the man page too, see man/systemd-detect-virt.xml.

While at it, please add a symlink to bhyve upstream page like we have for "microsoft hv". Bhyve is easy to google, but not everybody knows what it is.

**Comment by lbschenkel** [comment]
Yes, I overlooked the man page. I have amended the commit. Unfortunately the bhyve documentation is really sparse and as far as I could see the CPUID and DMI vendor values are not formally documented. The best I could do is to put a comment referring to the FreeBSD wiki.

**Comment by martinpitt** [comment]
```
parser error : Opening and ending tag mismatch: row line 136 and tbody
```

You are missing a `</row>` there. Please test-build locally :-)

**Comment by lbschenkel** [comment]
Damn, shouldn't work on PRs while commuting. Sorry about the stupid mistake, I have fixed it. Built locally and checked the tool and man page.

**Comment by poettering** [comment]
lgtm.

**Pull request merged**
