### PR TITLE
tests: ignore EPERM and EACCESS returned by mount in test-process-util

### PR DESCRIPTION
**Pull request by evverx**
That call to mount was added as a safeguard against a kernel bug which was fixed in
torvalds/linux@bbd5192.

In principle, the error could be ignored because

* normally everything mounted on /proc/PID should disappear as soon as the PID has gone away
* test-mount-util that had been confused by those phantom entries in /proc/self/mountinfo was
  taught to ignore them in 112cc3b.

Closes https://github.com/systemd/systemd/issues/9649.

### CODE REVIEW

**Comment by evverx** [comment]
That's true. On the other hand, the test had always worked this way and nobody seems to have complained :-) Seriously though, it should normally happen inside containers where everything is usually hidden from the host. That is, container runtimes do `unshare -m; mount(NULL, "/", NULL, MS_PRIVATE|MS_REC, NULL)` for us.

**Comment by poettering** [comment]
Hmm, then at least we should umount() our bind mount as last step, so that at least during clean operation we leave no traces...

Also I think MS_SHARED is actually better than MS_PRIVATE here, otherwise we pin temporary mounts from the host needlessly long, as unmount events won't be propagate to us anymore

**Comment by evverx** [comment]
Ubuntu CI failed because of https://github.com/systemd/systemd/issues/8880. @mbiebl if you happen to give this PR a try, could you also take a look at that issue? I guess it affects Debian CI as well.

**Comment by evverx** [comment]
I think I know why I didn't use `MS_SHARED` originally. It's because in most cases `MS_SHARED` will lead to entries like
```sh
159 20 8:1 /tmp/test-cmdlineF3Xqdb /proc/19975/cmdline rw,relatime shared:1 - ext4 /dev/sda1 rw,seclabel
```
appearing in `/proc/self/mountinfo` in the global namespace. Due to the kernel bug I pointed out earlier those entries will stay there until the next reboot. So if I changed `MS_PRIVATE` to `MS_SHARED`, it would make the call to `mount` virtually pointless, so I'd prefer not to do it. I hope it makes sense.

**Comment by poettering** [comment]
> The kernel will take care of the bind-mounts automatically immediately after the test stops (that's exactly what was fixed in torvalds/linux@bbd5192).

Oh, you mean because /proc/$PID will go away because the process $PID dies the kernel will unmount all mounts below /proc/$PID, too?

That makes sense, but I think this deserves a comment next to the bind mount, explaining this, as it's not obvious why the mount() isn't paired with an umount() even though we allow the MS_PRIVATE remount fail.

**Comment by poettering** [comment]
> It just occurred to me that if the first call to mount fails, then the second one is extremely unlikely to succeed, so I can just put return right after assert_se, thus avoiding the problem with those potentially visible bind-mounts altogether. @poettering what do you think?

I don't know what that apparmor rule refuses: all kinds of mounts or just changing of mount propagation?

In general though, in general if we people use crazy policies it's on them to deal with the fallout. I sympathize with a policy of disallowing all mounts. However a policy that prohibits just changing mount propagation sounds strange to me. Hence I actually sympathize with your idea: it's OK to skip testing of these things if we detect mount() to fail...

**Comment by poettering** [comment]
> I think I know why I didn't use MS_SHARED originally. It's because in most cases MS_SHARED will lead to entries like
> 
> 159 20 8:1 /tmp/test-cmdlineF3Xqdb /proc/19975/cmdline rw,relatime shared:1 - ext4 /dev/sda1 rw,seclabel
> 
> appearing in /proc/self/mountinfo in the global namespace

Ooops, sorry, I meant MS_SLAVE, not MS_SHARED. Yes, MS_SHARED is explicitly *not* what we want here, we want no propagation from our own namespace to the host's. But MS_SLAVE appears much more suitable to me, as it means that we'll still get umounts propagated from the host, and thus won't pin mounts forever that the host already long got rid off.

**Comment by evverx** [comment]
With `MS_SLAVE` addressed in https://github.com/systemd/systemd/pull/9670, I just need to add a comment expanding on why `umount` isn't used and also place a call to `return` after `assert_se`. I'll do it as soon as I have my laptop close at hand.

**Comment by evverx** [comment]
@poettering I've just updated the PR. Could you take another look?

**Pull request merged**
