### PR TITLE
core: don't load dropin data multiple times for the same unit

### PR DESCRIPTION
**Pull request by fbuihuu**
When an alias is loaded, we resolve this alias to its final unit first to load
the dropin data.

However if the final unit was already loaded, there's no point in reloading the
dropin data a second time.

This patch optimizes this case.

Also this allows the dropin loading code to assume that only units not yet
loaded are passed down. This assumption is not yet used but might be in the
future.

### CODE REVIEW

**Comment by keszybz** [comment]
I force-pushed a trivial change (revert the condition in the `if`s, it feels more natural this way), to force rebuild.

**Comment by fbuihuu** [comment]
On 01/24/2017 04:03 AM, Zbigniew Jędrzejewski-Szmek wrote:
> I force-pushed a trivial change (revert the condition in the |if|s, it
> feels more natural this way), to force rebuild.
> 

Your change looks good, however I'm not sure to understand how you did force push in
the branch that belongs to *my* own repo...

**Comment by fsateler** [comment]
@fbuihuu You allowed that when filing the PR: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by keszybz** [comment]
I wanted to say that I hacked github, but @fsateler beat me to it ;)

Now it's all green, so I'll push the button.

**Comment by poettering** [comment]
@fbuihuu @keszybz this one really doesn't look right. i mean this way we stop reading the drop-ins of the alias name, don't we?

**Pull request merged**
