### PR TITLE
travis: add aarch64, s390x, and ppc64le jobs

### PR DESCRIPTION
**Pull request by mrc0mmand**
*TBD*

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Looks like running a privileged Docker container under LXD is not supported yet, according to [this issue](https://travis-ci.community/t/debugging-docker-run-issue-on-arm64/5491) and respective [section in the documentation](https://docs.travis-ci.com/user/multi-cpu-architectures#security-and-lxd-container).

Currently the aarch64 jobs die with:
```
Successfully tagged debian-with-systemd/latest:latest
Starting container systemd-debian-testing
4e999cb1d94e01436d392957170405a7af11f393293a4ef57989707a6740147e
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:70: creating device nodes caused \\\"open /var/lib/docker/overlay2/7f2d2ca9b079b3c3011c5d31066b6fcc24462cb3f71bfd497fdd1e25de21900d/merged/dev/tty: no such device or address\\\"\"": unknown.
The command "$CI_MANAGERS/debian.sh SETUP" failed and exited with 125 during .
```

**Comment by evverx** [comment]
@mrc0mmand as far as I can remember, docker was introduced to make it possible to build systemd on Fedora using Ubuntu Xenial. Fedora is long gone there (except for the coverity scan job) so in theory it should be possible to avoid using docker (at least when systemd is built on arm64) by building and running the tests directly on Ubuntu (which as far as I know can be updated to bionic if necessary to get more or less new tools). Though I have no idea how it's going to interact with ASan (which is supposed to be run in privileged containers) :-)

**Comment by evverx** [comment]
Having said that, it would probably be easier to somehow make Ubuntu CI also build systemd with clang and run the unit tests under ASan+UBsan. cc @ddstreet.

**Comment by mrc0mmand** [comment]
> @mrc0mmand as far as I can remember, docker was introduced to make it possible to build systemd on Fedora using Ubuntu Xenial. Fedora is long gone there (except for the coverity scan job) so in theory it should be possible to avoid using docker (at least when systemd is built on arm64) by building and running the tests directly on Ubuntu (which as far as I know can be updated to bionic if necessary to get more or less new tools). 

That's what I though of as well. Basically replicate what I did in the [libbpf PR](https://github.com/libbpf/libbpf/pull/86). I'll just *abuse* the Xenial script you moved to Azure Pipelines for that :-)

> Though I have no idea how it's going to interact with ASan (which is supposed to be run in privileged containers) :-)

I think using ASan/UBSan directly in the LXD aarch64 container *shouldn't* be an issue (or at least I think, as it doesn't touch any privileged paths, from what I remember). I guess we could even stick with the Docker containers, if we didn't need to boot systemd there.

**Comment by mrc0mmand** [comment]
Looks like the aarch64 job is finally working, apart from the three failing test cases (two SIGIOTs/SIGABRTs and one timeout). I wonder if it's somewhat related to the security restrictions of LXD.

**Comment by mrc0mmand** [comment]
A quick summary:

 * `test-libmount` and `test-umount` will need to be disabled, as the memory leaks there are not systemd-related
 * `test-xattr-util`, `test-fd-util`, `test-fs-util`, and `test-process-util` all seem to keep aborting due to a stale file handle:

`test-xattr-util`
```
--- stderr ---
Found container virtualization lxc.
btime: Stale file handle
Assertion 'fd_getcrtime(fd, &usec) >= 0' failed at src/test/test-xattr-util.c:75, function void test_getcrtime(void)(). Aborting.
```

`test-fs-util`
```
/* test_unlinkat_deallocate */
Assertion 'st.st_blocks == 0' failed at src/test/test-fs-util.c:678, function void test_unlinkat_deallocate(void)(). Aborting.
```

`test-fd-util` (strace)
```
24450 write(4, "\376\377\2\0\0\0\0\0\377\377\2\0\0\0\0\0", 16 <unfinished ...>
24452 <... exit_group resumed>)         = ?
24450 <... write resumed> )             = 16
24450 read(3, "", 16384)                = 0
24450 openat(AT_FDCWD, "/proc/self/fd/4", O_RDONLY|O_CLOEXEC) = -1 ESTALE (Stale file handle)
24452 +++ exited with 0 +++
24450 close(4)                          = 0
24450 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=24452, si_uid=0, si_status=0, si_utime=30, si_stime=594} ---
24450 close(5)                          = 0
24450 writev(2, [{iov_base="Assertion 'fd2 >= 0' failed at src/test/test-fd-util.c:306, function void test_fd_duplicate_data_fd(void)(). Aborting.", iov_len=118}, {iov_base="\n", iov_len=1}], 2) = 119
```

`test-process-util` (strace)
```
[pid 24442] waitid(P_PID, 24446,  <unfinished ...>
[pid 24446] set_robust_list(0xffff8cb4de50, 24) = 0
[pid 24446] unshare(CLONE_NEWNS)        = 0
[pid 24446] mount(NULL, "/", NULL, MS_REC|MS_SLAVE, NULL) = 0
[pid 24446] openat(AT_FDCWD, "/tmp/test-cmdlineguQEq2", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0600) = 3
[pid 24446] mount("/tmp/test-cmdlineguQEq2", "/proc/self/cmdline", 0x5312e0, MS_BIND, NULL) = 0
[pid 24446] unlinkat(AT_FDCWD, "/tmp/test-cmdlineguQEq2", 0) = 0
[pid 24446] prctl(PR_SET_NAME, "testa") = 0
[pid 24446] prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
[pid 24446] openat(AT_FDCWD, "/proc/24446/cmdline", O_RDONLY|O_CLOEXEC) = -1 ESTALE (Stale file handle)
[pid 24446] writev(2, [{iov_base="get_process_cmd() returned -116: Stale file handle", iov_len=50}, {iov_base="\n", iov_len=1}], 2get_process_cmd() returned -116: Stale file handle
) = 51
[pid 24446] writev(2, [{iov_base="cmdline: (null)", iov_len=15}, {iov_base="\n", iov_len=1}], 2cmdline: (null)
) = 16
[pid 24446] prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
[pid 24446] openat(AT_FDCWD, "/proc/24446/cmdline", O_RDONLY|O_CLOEXEC) = -1 ESTALE (Stale file handle)
[pid 24446] writev(2, [{iov_base="Assertion 'get_process_cmdline(getpid_cached(), SIZE_MAX, 0, &line) == -ENOENT' failed at src/test/test-process-util.c:248, function void test_get_process_cmdline_harder(void)(). Aborting.", iov_len=188}, {iov_base="\n", iov_len=1}], 2Assertion 'get_process_cmdline(getpid_cached(), SIZE_MAX, 0, &line) == -ENOENT' failed at src/test/test-process-util.c:248, function void test_get_process_cmdline_harder(void)(). Aborting.
) = 189
```

I suspect it's caused by some LXC/LXD setting in Travis[0] but I haven't managed to reproduce it locally (albeit only on `x86_64`). Also, my LX* knowledge is pretty limited.

@evverx have you, by any chance, seen something like this during your CI adventures?


[0] https://docs.travis-ci.com/user/multi-cpu-architectures/#security-and-lxd-container

**Comment by evverx** [comment]
I'm not sure why the tests wouldn't have access to `/proc/*` on Travis CI on `arm`, `s390x` and `ppc64le`. @brauner  I'm wondering if you could point us in the right direction?

**Comment by brauner** [comment]
Looking at this trying to understand what's going on.

**Comment by evverx** [comment]
Thank you!

I'm not sure why wrote the tests didn't have access to `/proc/*` though. Judging by
```
24450 openat(AT_FDCWD, "/proc/self/fd/4", O_RDONLY|O_CLOEXEC) = -1 ESTALE (Stale file handle)
```
it seems to be something else.

@mrc0mmand as far as I can see, you pasted the output of `strace`. Where can the full log be found?

**Comment by brauner** [comment]
> Thank you!
> 
> I'm not sure why I wrote the tests didn't have access to `/proc/*` though. Judging by
> 
> ```
> 24450 openat(AT_FDCWD, "/proc/self/fd/4", O_RDONLY|O_CLOEXEC) = -1 ESTALE (Stale file handle)
> ```
> 
> it seems to be something else.
> 
> @mrc0mmand as far as I can see, you pasted the output of `strace`. Where can the full log be found?

I mean ESTALE is usually something I expect from NFS where server and client are out of sync...

**Comment by evverx** [comment]
I'm wondering why that would happen in lxc containers on Travis CI everywhere except for amd64. Since it's `/proc` I didn't think of `NFS` :-) It looked like a seccomp filter of some kind at first glance.

**Comment by evverx** [comment]
Just to clarify, we're trying to utilize the "multi-arch" feature announced in https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support. As far as I understand, everything is run with LXC/LXD there and for some reason it only works on amd64.

**Comment by evverx** [comment]
I'm not sure if it helps, but to judge from https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/arm64/s/systemd-upstream/20200209_195524_8a42f@/log.gz those tests pass on "bare metal" machines on arm64 so it seems something causing `/proc/self/fd/4` to fail with "ESTALE" happens within LXD containers on Travis CI.

**Comment by evverx** [comment]
I "fixed" three tests by mounting "tmpfs" onto "/tmp" effectively replacing `shiftfs` used there by default. It looks like `shiftfs` doesn't support O_TMPFILE (though it doesn't fail when something like `open(directory, flags|O_TMPFILE|O_EXCL, S_IRUSR|S_IWUSR)` is called.

**Comment by evverx** [comment]
The last test was "fixed" by mounting "tmpfs" onto "/var/tmp" (`fd_duplicate_data_fd` falls back to "/var/tmp" when files are relatively large by its standards). The command I used to run the tests in https://travis-ci.org/systemd/systemd/builds/649140700?utm_medium=notification&utm_source=github_status was
```sh
unshare -m bash -x -c "
mount -t tmpfs tmpfs /tmp/
mount -t tmpfs tmpfs /var/tmp/

meson --werror \
      --optimization=0 \
      --buildtype=debug \
      -Dc_args='-fno-omit-frame-pointer -ftrapv' \
      -Dtests=unsafe \
      -Dsplit-usr=true \
      -Dman=true \
      build
ninja -v -C build
meson test -C build --print-errorlogs --timeout-multiplier=4"
```

I'm not exactly sure what `shiftfs` is so I don't know how to fix it properly without kludges :-)

**Comment by mrc0mmand** [comment]
@evverx here are the test logs, not sure how useful they're going to be, since running strace in Travis is a bit complicated due to log size limits:

 * `test-fd-util`: https://travis-ci.org/systemd/systemd/jobs/648053015#L3431
 * `test-fs-util`: https://travis-ci.org/systemd/systemd/jobs/648047140#L3431
 * `test-process-util`: https://travis-ci.org/systemd/systemd/jobs/648037914#L3431
 * `test-xattr-util`: haven't run this one under strace, yet

**Comment by evverx** [comment]
I opened https://github.com/systemd/systemd/issues/14861 to keep discussing the shiftfs issues. It appears it boils down to a file descriptor we get after calling `unlinkat` (which according to `unlinkat(2)` shouldn't be stale as long as we keep using it):
```sh
openat(AT_FDCWD, "/tmp", O_RDWR|O_EXCL|O_TMPFILE, 0600) = -1 EOPNOTSUPP (Operation not supported)
umask(077)                              = 022
getpid()                                = 29361
openat(AT_FDCWD, "/tmp/systemd-tmp-7950fL", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0600) = 3</tmp/systemd-tmp-7950fL>
umask(022)                              = 077
unlinkat(AT_FDCWD, "/tmp/systemd-tmp-7950fL", 0) = 0
statx(3</tmp/systemd-tmp-7950fL (deleted)>, "", AT_STATX_DONT_SYNC|AT_EMPTY_PATH, STATX_BTIME, 0xffffdba7c2e8) = -1 ESTALE (Stale file handle)
getxattr("/proc/self/fd/3", "user.crtime_usec", 0xffffdba7c2c0, 8) = -1 ESTALE (Stale file handle)
fsetxattr(3</tmp/systemd-tmp-7950fL (deleted)>, "user.crtime_usec", "\200\307.0\243e\5", 8, 0) = 0
statx(3</tmp/systemd-tmp-7950fL (deleted)>, "", AT_STATX_DONT_SYNC|AT_EMPTY_PATH, STATX_BTIME, 0xffffdba7c2e8) = -1 ESTALE (Stale file handle)
getxattr("/proc/self/fd/3", "user.crtime_usec", 0xffffdba7c2c0, 8) = -1 ESTALE (Stale file handle)
writev(2<pipe:[241902836]>, [{iov_base="Assertion 'fd_getcrtime(fd, &usec) >= 0' failed at src/test/test-xattr-util.c:40, function test_getcrtime(). Aborting.", iov_len=118}, {iov_base="\n", iov_len=1}], 2Assertion 'fd_getcrtime(fd, &usec) >= 0' failed at src/test/test-xattr-util.c:40, function test_getcrtime(). Aborting.
) = 119
```

**Comment by brauner** [comment]
> I opened #14861 to keep discussing the shiftfs issues. It appears it boils down to a file descriptor we get after calling `unlinkat` (which according to `unlinkat(2)` shouldn't be stale as long as we keep using it):
> 
> ```shell
> openat(AT_FDCWD, "/tmp", O_RDWR|O_EXCL|O_TMPFILE, 0600) = -1 EOPNOTSUPP (Operation not supported)
> umask(077)                              = 022
> getpid()                                = 29361
> openat(AT_FDCWD, "/tmp/systemd-tmp-7950fL", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0600) = 3</tmp/systemd-tmp-7950fL>
> umask(022)                              = 077
> unlinkat(AT_FDCWD, "/tmp/systemd-tmp-7950fL", 0) = 0
> statx(3</tmp/systemd-tmp-7950fL (deleted)>, "", AT_STATX_DONT_SYNC|AT_EMPTY_PATH, STATX_BTIME, 0xffffdba7c2e8) = -1 ESTALE (Stale file handle)
> getxattr("/proc/self/fd/3", "user.crtime_usec", 0xffffdba7c2c0, 8) = -1 ESTALE (Stale file handle)
> fsetxattr(3</tmp/systemd-tmp-7950fL (deleted)>, "user.crtime_usec", "\200\307.0\243e\5", 8, 0) = 0
> statx(3</tmp/systemd-tmp-7950fL (deleted)>, "", AT_STATX_DONT_SYNC|AT_EMPTY_PATH, STATX_BTIME, 0xffffdba7c2e8) = -1 ESTALE (Stale file handle)
> getxattr("/proc/self/fd/3", "user.crtime_usec", 0xffffdba7c2c0, 8) = -1 ESTALE (Stale file handle)
> writev(2<pipe:[241902836]>, [{iov_base="Assertion 'fd_getcrtime(fd, &usec) >= 0' failed at src/test/test-xattr-util.c:40, function test_getcrtime(). Aborting.", iov_len=118}, {iov_base="\n", iov_len=1}], 2Assertion 'fd_getcrtime(fd, &usec) >= 0' failed at src/test/test-xattr-util.c:40, function test_getcrtime(). Aborting.
> ) = 119
> ```

Is there any chance I can get the exact kernel version that is used on this system? Including the package version?

**Comment by evverx** [comment]
@brauner to judge from https://api.travis-ci.org/v3/job/649362680/log.txt, the runtime kernel version is 5.3.0-19-generic. Though at some point it says there that it's
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
[34m[1mLinux Version[0m
5.0.0-23-generic
```
Regarding the packages, I think I can find out what versions would be installed within containers but the underlying host is a mystery. Though they provide a link to https://github.com/travis-ci/worker/tree/6d3048d96b26562be21fa1a8b8144f4c4cecd083 (which I suspect in theory somehow should help to figure out what's going on).

**Comment by brauner** [comment]
> @brauner to judge from https://api.travis-ci.org/v3/job/649362680/log.txt, the runtime kernel version is 5.3.0-19-generic. Though at some point it says there that it's
> 
> ```
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.3 LTS
> Release:	18.04
> Codename:	bionic
> �[34m�[1mLinux Version�[0m
> 5.0.0-23-generic
> ```
> 
> Regarding the packages, I think I can find out what versions would be installed within containers but the underlying host is a mystery. Though they provide a link to https://github.com/travis-ci/worker/tree/6d3048d96b26562be21fa1a8b8144f4c4cecd083 (which I suspect in theory somehow should help to figure out what's going on).

So I think this might be fixed by https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1860041 but a kernel with that fix hasn't been released yet. I think that should fix it.

**Comment by evverx** [comment]
Regarding the memory leaks, to judge from https://github.com/systemd/systemd/pull/12252#issuecomment-482804040, I'm pretty sure they were fixed almost a year ago. It appears the fixes haven't made it into the util-linux package on Ubuntu Bionic. I wouldn't turn the tests off. Could you try https://clang.llvm.org/docs/SanitizerSpecialCaseList.html instead?

**Comment by mrc0mmand** [comment]
> Regarding the memory leaks, to judge from [#12252 (comment)](https://github.com/systemd/systemd/pull/12252#issuecomment-482804040), I'm pretty sure they were fixed almost a year ago. It appears the fixes haven't made it into the util-linux package on Ubuntu Bionic. I wouldn't turn the tests off. Could you try https://clang.llvm.org/docs/SanitizerSpecialCaseList.html instead?

Hah, didn't know about this feature, I'll definitely give it a try, thanks!

**Comment by mrc0mmand** [comment]
@evverx I had to resort back to using a suppression file for LSan, as the blacklist (at least from what I've understood) won't work for functions not defined by us (at least it didn't when I was playing around with it). Using LSan's suppression file seems to work as expected.

Also, the `tmpfs` workaround works as well except for one thing: `src/test/test-systemd-tmpfiles.py` gets stuck when run with the workaround on aarch64 and under sanitizers. I tried to debug it a little bit more in my several (vain) attempts, but unsuccessfully so far, will try again tomorrow.

**Comment by mrc0mmand** [comment]
Sorry for the radio silence, but I got really overwhelmed by downstream. Anyway, the current issue can be summarized as follows:

 - test: `src/test/test-systemd-tmpfiles.py`
 - it happens only on `aarch64/arm64`
 - it happens only under ASan with `ASAN_OPTIONS=detect_leaks=1`
 - the test is *incredibly* slow compared to other architectures

Basically, after 2 minutes it got to `Running /home/travis/build/systemd/systemd/build/systemd-tmpfiles --user on 's'` which is not even a 1/4 of the test itself. For example, here are times of the same test under the same conditions (ASan + UBsan with LSan enabled) on other archs:
 - s390x:  `234/488 test-systemd-tmpfiles                   OK       1.42 s`
 - ppc6le: `234/488 test-systemd-tmpfiles                   OK       4.49 s `
 - x86_64: `234/488 test-systemd-tmpfiles                   OK       4.39 s `

After wrapping it in `python3 -u -m trace -t` it clearly shows that it progresses, but slowly. Not sure if it's fault of something in systemd or the stuff around it, but it's hard to debug it properly, since I can't run it under `strace` (as LSan uses `ptrace()`).
 
@evverx any ideas?

(note for my future self: run the python test with `-u` for unbuffered stdout, otherwise it won't have any output if it gets killed prematurely)

**Comment by mrc0mmand** [comment]
Not sure why it didn't work before, but after running the offending test manually without timeout it takes over 4 minutes to complete, so there's definitely something fishy going on:

```
+ python3 -u /home/travis/build/systemd/systemd/src/test/test-systemd-tmpfiles.py /home/travis/build/systemd/systemd/build/systemd-tmpfiles
...
real	4m20.732s
user	4m16.194s
sys	0m3.869s
```

**Comment by mrc0mmand** [comment]
It looks like the LSan overhead on `aarch64` is simply costlier than on other architectures:

`ppc64le`
```
+ export SYSTEMD_LOG_LEVEL=debug
+ SYSTEMD_LOG_LEVEL=debug
+ echo 'f++ /too/many/plusses'
+ unbuffer /home/travis/build/systemd/systemd/build/systemd-tmpfiles --create /home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf
Looking for configuration files in (higher priority first):
	/etc/tmpfiles.d
	/run/tmpfiles.d
	/usr/local/lib/tmpfiles.d
	/usr/lib/tmpfiles.d
	/lib/tmpfiles.d
Reading config file "/home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf"…
[/home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf:1] Unknown modifiers in command 'f++'
real	0m0.049s
user	0m0.024s
sys	0m0.023s
```

`aarch64`
```
+ export SYSTEMD_LOG_LEVEL=debug
+ SYSTEMD_LOG_LEVEL=debug
+ echo 'f++ /too/many/plusses'
+ unbuffer /home/travis/build/systemd/systemd/build/systemd-tmpfiles --create /home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf
Looking for configuration files in (higher priority first):
	/etc/tmpfiles.d
	/run/tmpfiles.d
	/usr/local/lib/tmpfiles.d
	/usr/lib/tmpfiles.d
	/lib/tmpfiles.d
Reading config file "/home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf"…
[/home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf:1] Unknown modifiers in command 'f++'
real	0m3.456s
user	0m3.323s
sys	0m0.133s
```

I'm not sure if there's a way I could dig into this deeper, since I can't use `strace` and similar tools.

**Comment by mrc0mmand** [comment]
Last attempt in getting something useful of it, by appending `debug=true:atexit=true:print_stats=true` to `ASAN_OPTIONS=`:

`ppc64le`
```
+ export SYSTEMD_LOG_LEVEL=debug
+ SYSTEMD_LOG_LEVEL=debug
+ export ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:debug=true:atexit=true:print_stats=true
+ ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:debug=true:atexit=true:print_stats=true
+ echo 'f++ /too/many/plusses'
+ unbuffer /home/travis/build/systemd/systemd/build/systemd-tmpfiles --create /home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf
Looking for configuration files in (higher priority first):
	/etc/tmpfiles.d
	/run/tmpfiles.d
	/usr/local/lib/tmpfiles.d
	/usr/lib/tmpfiles.d
	/lib/tmpfiles.d
Reading config file "/home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf"…
[/home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf:1] Unknown modifiers in command 'f++'
AddressSanitizer exit stats:
Stats: 0M malloced (0M for red zones) by 31 calls
Stats: 0M realloced by 8 calls
Stats: 0M freed by 28 calls
Stats: 0M really freed by 0 calls
Stats: 1M (1M-0M) mmaped; 29 maps, 0 unmaps
  mallocs by size class: 2:4; 3:4; 4:1; 6:7; 8:2; 11:2; 12:1; 13:1; 18:1; 21:1; 22:4; 25:2; 49:1; 
Stats: malloc large: 0
Stats: StackDepot: 294 ids; 0M allocated
Stats: SizeClassAllocator64: 0M mapped (0M rss) in 1399 allocations; remains 1399
  02 (    32): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks    1920 avail:   2048 rss:     64K releases:      0 last released:      0K region: 0xa1000000000
  03 (    48): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks    1237 avail:   1365 rss:     64K releases:      0 last released:      0K region: 0xa1800000000
  04 (    64): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     896 avail:   1024 rss:     64K releases:      0 last released:      0K region: 0xa2000000000
  06 (    96): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     554 avail:    682 rss:     64K releases:      0 last released:      0K region: 0xa3000000000
  08 (   128): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     384 avail:    512 rss:     64K releases:      0 last released:      0K region: 0xa4000000000
  11 (   176): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     244 avail:    372 rss:     64K releases:      0 last released:      0K region: 0xa5800000000
  12 (   192): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     213 avail:    341 rss:     64K releases:      0 last released:      0K region: 0xa6000000000
  13 (   208): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     187 avail:    315 rss:     64K releases:      0 last released:      0K region: 0xa6800000000
  18 (   384): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks      42 avail:    170 rss:     64K releases:      0 last released:      0K region: 0xa9000000000
  21 (   640): mapped:     64K allocs:     102 frees:       0 inuse:    102 num_freed_chunks       0 avail:    102 rss:     64K releases:      0 last released:      0K region: 0xaa800000000
  22 (   768): mapped:     64K allocs:      85 frees:       0 inuse:     85 num_freed_chunks       0 avail:     85 rss:     64K releases:      0 last released:      0K region: 0xab000000000
  25 (  1280): mapped:     64K allocs:      51 frees:       0 inuse:     51 num_freed_chunks       0 avail:     51 rss:     64K releases:      0 last released:      0K region: 0xac800000000
  36 (  8192): mapped:     64K allocs:       8 frees:       0 inuse:      8 num_freed_chunks       0 avail:      8 rss:     64K releases:      0 last released:      0K region: 0xb2000000000
  49 ( 81920): mapped:    128K allocs:       1 frees:       0 inuse:      1 num_freed_chunks       0 avail:      1 rss:     64K releases:      0 last released:      0K region: 0xb8800000000
Stats: LargeMmapAllocator: allocated 0 times, remains 0 (0 K) max 0 M; by size logs: 
Quarantine limits: global: 256Mb; thread local: 1024Kb
Global quarantine stats: batches: 0; bytes: 0 (user: 0); chunks: 0 (capacity: 0); 0% chunks used; 0% memory overhead
real	0m0.060s
user	0m0.024s
sys	0m0.036s
```

`s390x`
```
+ export SYSTEMD_LOG_LEVEL=debug
+ SYSTEMD_LOG_LEVEL=debug
+ export ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:debug=true:atexit=true:print_stats=true
+ ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:debug=true:atexit=true:print_stats=true
+ echo 'f++ /too/many/plusses'
+ unbuffer /home/travis/build/systemd/systemd/build/systemd-tmpfiles --create /home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf
Looking for configuration files in (higher priority first):
	/etc/tmpfiles.d
	/run/tmpfiles.d
	/usr/local/lib/tmpfiles.d
	/usr/lib/tmpfiles.d
	/lib/tmpfiles.d
Reading config file "/home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf"…
[/home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf:1] Unknown modifiers in command 'f++'
AddressSanitizer exit stats:
Stats: 0M malloced (0M for red zones) by 31 calls
Stats: 0M realloced by 8 calls
Stats: 0M freed by 28 calls
Stats: 0M really freed by 0 calls
Stats: 1M (1M-0M) mmaped; 29 maps, 0 unmaps
  mallocs by size class: 2:4; 3:4; 4:1; 6:7; 8:2; 11:2; 12:1; 13:1; 18:1; 21:1; 22:4; 25:2; 33:1; 
Stats: malloc large: 0
Stats: StackDepot: 282 ids; 0M allocated
Stats: SizeClassAllocator64: 0M mapped (0M rss) in 1410 allocations; remains 1410
  02 (    32): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks    1920 avail:   2048 rss:      4K releases:      0 last released:      0K region: 0x602000000000
  03 (    48): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks    1237 avail:   1365 rss:      4K releases:      0 last released:      0K region: 0x603000000000
  04 (    64): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     896 avail:   1024 rss:      4K releases:      0 last released:      0K region: 0x604000000000
  06 (    96): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     554 avail:    682 rss:      4K releases:      0 last released:      0K region: 0x606000000000
  08 (   128): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     384 avail:    512 rss:      4K releases:      0 last released:      0K region: 0x608000000000
  11 (   176): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     244 avail:    372 rss:      4K releases:      0 last released:      0K region: 0x60b000000000
  12 (   192): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     213 avail:    341 rss:      4K releases:      0 last released:      0K region: 0x60c000000000
  13 (   208): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks     187 avail:    315 rss:      4K releases:      0 last released:      0K region: 0x60d000000000
  18 (   384): mapped:     64K allocs:     128 frees:       0 inuse:    128 num_freed_chunks      42 avail:    170 rss:      4K releases:      0 last released:      0K region: 0x612000000000
  21 (   640): mapped:     64K allocs:     102 frees:       0 inuse:    102 num_freed_chunks       0 avail:    102 rss:      4K releases:      0 last released:      0K region: 0x615000000000
  22 (   768): mapped:     64K allocs:      85 frees:       0 inuse:     85 num_freed_chunks       0 avail:     85 rss:      4K releases:      0 last released:      0K region: 0x616000000000
  25 (  1280): mapped:     64K allocs:      51 frees:       0 inuse:     51 num_freed_chunks       0 avail:     51 rss:      4K releases:      0 last released:      0K region: 0x619000000000
  33 (  5120): mapped:     64K allocs:      12 frees:       0 inuse:     12 num_freed_chunks       0 avail:     12 rss:      8K releases:      0 last released:      0K region: 0x621000000000
  36 (  8192): mapped:     64K allocs:       8 frees:       0 inuse:      8 num_freed_chunks       0 avail:      8 rss:      4K releases:      0 last released:      0K region: 0x624000000000
Stats: LargeMmapAllocator: allocated 0 times, remains 0 (0 K) max 0 M; by size logs: 
Quarantine limits: global: 256Mb; thread local: 1024Kb
Global quarantine stats: batches: 0; bytes: 0 (user: 0); chunks: 0 (capacity: 0); 0% chunks used; 0% memory overhead
real	0m0.092s
user	0m0.016s
sys	0m0.057s
```

`aarch64`
```
+ export SYSTEMD_LOG_LEVEL=debug
+ SYSTEMD_LOG_LEVEL=debug
+ export ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:debug=true:atexit=true:print_stats=true
+ ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:debug=true:atexit=true:print_stats=true
+ echo 'f++ /too/many/plusses'
+ unbuffer /home/travis/build/systemd/systemd/build/systemd-tmpfiles --create /home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf
Looking for configuration files in (higher priority first):
	/etc/tmpfiles.d
	/run/tmpfiles.d
	/usr/local/lib/tmpfiles.d
	/usr/lib/tmpfiles.d
	/lib/tmpfiles.d
Reading config file "/home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf"…
[/home/travis/build/systemd/systemd/systemd-tmpfiles-test.conf:1] Unknown modifiers in command 'f++'
AddressSanitizer exit stats:
Stats: 0M malloced (0M for red zones) by 31 calls
Stats: 0M realloced by 8 calls
Stats: 0M freed by 28 calls
Stats: 0M really freed by 0 calls
Stats: 15M (15M-0M) mmaped; 15 maps, 0 unmaps
  mallocs by size class: 2:4; 3:4; 4:1; 6:7; 8:2; 11:2; 12:1; 13:1; 18:1; 21:1; 22:4; 25:2; 33:1; 
Stats: malloc large: 0
Stats: StackDepot: 294 ids; 0M allocated
Stats: LargeMmapAllocator: allocated 0 times, remains 0 (0 K) max 0 M; by size logs: 
Quarantine limits: global: 256Mb; thread local: 1024Kb
Global quarantine stats: batches: 0; bytes: 0 (user: 0); chunks: 0 (capacity: 0); 0% chunks used; 0% memory overhead
real	0m3.515s
user	0m3.404s
sys	0m0.117s
```

Frankly, I'm still not sure if the different behavior on `aarch64` is expected or not :-)

**Pull request closed without merging**
