### PR TITLE
debug

### LINKED ISSUE #21390: test-json fails on ppc64el
```
/* test_float */
Assertion 'json_variant_is_real(json_variant_by_index(v, 7)) && json_variant_is_integer(json_variant_by_index(v, 7)) && json_variant_integer(json_variant_by_index(v, 7)) == 10' failed at src/test/test-json.c:540, function test_float_match(). Aborting.
```
cc @poettering

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by poettering** [comment]
hmm, wa? i wasn't aware 10 could not be expressed in "long double" safely. I am puzzled by this.

**Comment by poettering** [comment]
still fails on ppc64el

**Comment by yuwata** [comment]
Oh,
```
/* test_float */
Assertion 'json_variant_is_integer(json_variant_by_index(v, 7))' failed at src/test/test-json.c:541, function test_float_match(). Aborting.
```

**Comment by yuwata** [comment]
> hmm, wa? i wasn't aware 10 could not be expressed in "long double" safely. I am puzzled by this.

Actually, that's strange. I am also confused...

**Comment by bluca** [comment]
https://github.com/systemd/systemd/pull/21424 fixes the issue, shall we close this?

**Comment by yuwata** [comment]
Yeah, let's close this.

**Pull request closed without merging**
