### PR TITLE
ci: test ubuntu switch from bionic to focal

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by bluca** [comment]
@ddstreet i386 is failing to install:

```
The following packages have unmet dependencies:
 builddeps:/tmp/autopkgtest.BUS69V/build.Yze/systemd:i386 : Depends: python3-jinja2:i386 but it is not installable
                                                            Depends: python3-pyparsing:i386 but it is not installable
                                                            Depends: python3-evdev:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Wasn't i386 dropped as a full architecture at some point in Ubuntu?

**Comment by ddstreet** [comment]
> Wasn't i386 dropped as a full architecture at some point in Ubuntu?

yes sorry, I should have mentioned to disable i386; it was dropped starting in Focal.

**Comment by bluca** [comment]
> > Wasn't i386 dropped as a full architecture at some point in Ubuntu?
> 
> yes sorry, I should have mentioned to disable i386; it was dropped starting in Focal.

Do you think there's any value in keeping bionic-i386 around?

**Comment by ddstreet** [comment]
> > > Wasn't i386 dropped as a full architecture at some point in Ubuntu?
> > 
> > 
> > yes sorry, I should have mentioned to disable i386; it was dropped starting in Focal.
> 
> Do you think there's any value in keeping bionic-i386 around?

i feel like it would probably just result in more false-negatives, but we could keep it around to see if it's helpful, or not? It can be disabled later if it's failing incorrectly too often. Also there may be a point where it gets too old for some new dependency that isn't backportable into bionic in the test ppa.

**Comment by bluca** [comment]
> > > > Wasn't i386 dropped as a full architecture at some point in Ubuntu?
> > > 
> > > 
> > > yes sorry, I should have mentioned to disable i386; it was dropped starting in Focal.
> > 
> > 
> > Do you think there's any value in keeping bionic-i386 around?
> 
> i feel like it would probably just result in more false-negatives, but we could keep it around to see if it's helpful, or not? It can be disabled later if it's failing incorrectly too often. Also there may be a point where it gets too old for some new dependency that isn't backportable into bionic in the test ppa.

Yeah it will bitrot. We got a build-test already for i386 for fedora rawhide, so that should be enough. Thanks!

**Pull request closed without merging**
