### PR TITLE
test: several fixlets for test-sd-device

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes https://github.com/systemd/systemd/commit/93e04eb43bed6cd1cea344f8fb1002b62155fae2#commitcomment-70387367.

### CODE REVIEW

**Comment by yuwata** [comment]
@mbiebl Could you check if this PR fixes your issue?

**Comment by mbiebl** [comment]
```
>>> MALLOC_PERTURB_=194 PATH='/build/systemd-251~rc1/build-deb:/usr/sbin:/usr/bin:/sbin:/bin' SYSTEMD_LANGUAGE_FALLBACK_MAP='/build/systemd-251~rc1/src/locale/language-fallback-map' '/build/systemd-251~rc1/build-deb/test-sd-device'
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stderr:
/* test_sd_device_new_from_nulstr */
lo: setting devlink: /dev/disk/by-partuuid/1290d63a-42cc-4c71-b87c-xxxxxxxxxxxx
lo: setting devlink: /dev/disk/by-path/pci-0000:00:0f.0-scsi-0:0:0:0-part3
lo: setting devlink: /dev/disk/by-label/Arch\x20Linux
lo: setting devlink: /dev/disk/by-uuid/a07b87e5-4af5-4a59-bde9-yyyyyyyyyyyy
lo: setting devlink: /dev/disk/by-partlabel/Arch\x20Linux
lo: checking devlink: /dev/disk/by-partuuid/1290d63a-42cc-4c71-b87c-xxxxxxxxxxxx
lo: checking devlink: /dev/disk/by-path/pci-0000:00:0f.0-scsi-0:0:0:0-part3
lo: checking devlink: /dev/disk/by-label/Arch\x20Linux
lo: checking devlink: /dev/disk/by-uuid/a07b87e5-4af5-4a59-bde9-yyyyyyyyyyyy
lo: checking devlink: /dev/disk/by-partlabel/Arch\x20Linux
/* test_sd_device_enumerator_filter_subsystem */
/* test_sd_device_enumerator_subsystems */
/* test_sd_device_enumerator_devices */
Assertion 'sd_device_new_from_device_id(&dev, id) >= 0' failed at src/libsystemd/sd-device/test-sd-device.c:57, function test_sd_device_one(). Aborting.
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```
This is from a test-build

**Comment by mbiebl** [comment]
Fwiw, this is run in a pbuilder build chroot.

**Comment by mbiebl** [comment]
```
>>> MALLOC_PERTURB_=136 PATH='/build/systemd-251~rc1/build-deb:/usr/sbin:/usr/bin:/sbin:/bin' SYSTEMD_LANGUAGE_FALLBACK_MAP='/build/systemd-251~rc1/src/locale/language-fallback-map' '/build/systemd-251~rc1/build-deb/test-sd-device'
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
Listing only the last 100 lines from a long log.
test_sd_device_one(/sys/module/xt_tcpudp)
test_sd_device_one(/sys/module/xz_dec)
test_sd_device_one(/sys/module/zswap)
/* test_sd_device_enumerator_devices */
test_sd_device_one(/sys/devices/LNXSYSTM:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXPWRBN:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXPWRBN:00/input/input4)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXPWRBN:00/input/input4/event3)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXPWRBN:00/wakeup/wakeup19)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0010:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0010:00/LNXCPU:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0010:00/LNXCPU:01)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0010:00/LNXCPU:02)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0010:00/LNXCPU:03)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/PNP0A06:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/PNP0A06:01)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/PNP0A06:02)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/QEMU0002:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/QEMU0002:00/wakeup/wakeup24)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/PNP0303:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/PNP0501:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/PNP0B00:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/PNP0F13:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/wakeup/wakeup10)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:01)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:01/wakeup/wakeup11)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:02)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:02/wakeup/wakeup0)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:03)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:03/wakeup/wakeup1)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:04)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:04/device:05)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:04/device:05/wakeup/wakeup12)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:04/wakeup/wakeup2)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/device:07)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/device:07/wakeup/wakeup13)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:06/wakeup/wakeup3)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:08)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:08/device:09)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:08/device:09/wakeup/wakeup14)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:08/wakeup/wakeup4)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0a)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0a/device:0b)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0a/device:0b/wakeup/wakeup15)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0a/wakeup/wakeup5)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0c)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0c/device:0d)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0c/device:0d/wakeup/wakeup16)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0c/wakeup/wakeup6)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0e)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0e/device:0f)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0e/device:0f/wakeup/wakeup17)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:0e/wakeup/wakeup7)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:10)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:10/device:11)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:10/wakeup/wakeup8)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:12)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:12/wakeup/wakeup9)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/wakeup/wakeup18)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C01:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:01)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:02)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:03)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:04)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:05)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:06)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:07)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:08)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:09)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:0a)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:0b)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:0c)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:0d)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:0e)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0F:0f)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXSYBUS:01)
test_sd_device_one(/sys/devices/breakpoint)
test_sd_device_one(/sys/devices/kprobe)
test_sd_device_one(/sys/devices/msr)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:00.0)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:01.0)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:01.0/drm/card0)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:01.0/drm/card0/card0-Virtual-1)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:01.0/drm/card0/card0-Virtual-2)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:01.0/drm/card0/card0-Virtual-3)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:01.0/drm/card0/card0-Virtual-4)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:01.0/graphics/fb0)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:02.0)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:02.0/0000:00:02.0:pcie001)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:02.0/0000:00:02.0:pcie002)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:02.0/0000:00:02.0:pcie010)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:02.0/0000:01:00.0)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:02.0/0000:01:00.0/virtio0)
test_sd_device_one(/sys/devices/pci0000:00/0000:00:02.0/0000:01:00.0/virtio0/net/enp1s0)
Assertion 'sd_device_new_from_device_id(&dev, id) >= 0' failed at src/libsystemd/sd-device/test-sd-device.c:57, function test_sd_device_one(). Aborting.
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

**Comment by yuwata** [comment]
@mbiebl Thanks. Could you test again?

**Comment by mbiebl** [comment]
```
>>> SYSTEMD_LANGUAGE_FALLBACK_MAP='/build/systemd-251~rc1/src/locale/language-fallback-map' PATH='/build/systemd-251~rc1/build-deb:/usr/sbin:/usr/bin:/sbin:/bin' MALLOC_PERTURB_=228 '/build/systemd-251~rc1/build-deb/test-sd-device'
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
Listing only the last 100 lines from a long log.
test_sd_device_one(/sys/module/joydev)
test_sd_device_one(/sys/module/kernel)
test_sd_device_one(/sys/module/keyboard)
test_sd_device_one(/sys/module/kvm)
test_sd_device_one(/sys/module/kvm_intel)
test_sd_device_one(/sys/module/l2tp_core)
test_sd_device_one(/sys/module/l2tp_netlink)
test_sd_device_one(/sys/module/ledtrig_audio)
test_sd_device_one(/sys/module/libahci)
test_sd_device_one(/sys/module/libata)
test_sd_device_one(/sys/module/lpc_ich)
test_sd_device_one(/sys/module/macsec)
test_sd_device_one(/sys/module/mbcache)
test_sd_device_one(/sys/module/memory_hotplug)
test_sd_device_one(/sys/module/module)
test_sd_device_one(/sys/module/mousedev)
test_sd_device_one(/sys/module/net_failover)
test_sd_device_one(/sys/module/netpoll)
test_sd_device_one(/sys/module/nmi_backtrace)
test_sd_device_one(/sys/module/page_alloc)
test_sd_device_one(/sys/module/page_reporting)
test_sd_device_one(/sys/module/pci_hotplug)
test_sd_device_one(/sys/module/pcie_aspm)
test_sd_device_one(/sys/module/pciehp)
test_sd_device_one(/sys/module/pcspkr)
test_sd_device_one(/sys/module/printk)
test_sd_device_one(/sys/module/processor)
test_sd_device_one(/sys/module/psmouse)
test_sd_device_one(/sys/module/pstore)
test_sd_device_one(/sys/module/qemu_fw_cfg)
test_sd_device_one(/sys/module/qxl)
test_sd_device_one(/sys/module/random)
test_sd_device_one(/sys/module/rapl)
test_sd_device_one(/sys/module/rc_core)
test_sd_device_one(/sys/module/rcupdate)
test_sd_device_one(/sys/module/rcutree)
test_sd_device_one(/sys/module/rfkill)
test_sd_device_one(/sys/module/rng_core)
test_sd_device_one(/sys/module/rtc_cmos)
test_sd_device_one(/sys/module/scsi_common)
test_sd_device_one(/sys/module/scsi_mod)
test_sd_device_one(/sys/module/secretmem)
test_sd_device_one(/sys/module/serio_raw)
test_sd_device_one(/sys/module/sg)
test_sd_device_one(/sys/module/shpchp)
test_sd_device_one(/sys/module/snd)
test_sd_device_one(/sys/module/snd_hda_codec)
test_sd_device_one(/sys/module/snd_hda_codec_generic)
test_sd_device_one(/sys/module/snd_hda_core)
test_sd_device_one(/sys/module/snd_hda_intel)
test_sd_device_one(/sys/module/snd_hwdep)
test_sd_device_one(/sys/module/snd_intel_dspcfg)
test_sd_device_one(/sys/module/snd_intel_sdw_acpi)
test_sd_device_one(/sys/module/snd_pcm)
test_sd_device_one(/sys/module/snd_timer)
test_sd_device_one(/sys/module/soundcore)
test_sd_device_one(/sys/module/spidev)
test_sd_device_one(/sys/module/spurious)
test_sd_device_one(/sys/module/sr_mod)
test_sd_device_one(/sys/module/srcutree)
test_sd_device_one(/sys/module/suspend)
test_sd_device_one(/sys/module/syscall)
test_sd_device_one(/sys/module/sysrq)
test_sd_device_one(/sys/module/tcp_cubic)
test_sd_device_one(/sys/module/thermal)
test_sd_device_one(/sys/module/tpm)
test_sd_device_one(/sys/module/tpm_crb)
test_sd_device_one(/sys/module/tpm_tis)
test_sd_device_one(/sys/module/tpm_tis_core)
test_sd_device_one(/sys/module/ttm)
test_sd_device_one(/sys/module/udp_tunnel)
test_sd_device_one(/sys/module/usb_common)
test_sd_device_one(/sys/module/usbcore)
test_sd_device_one(/sys/module/usbhid)
test_sd_device_one(/sys/module/virtio)
test_sd_device_one(/sys/module/virtio_balloon)
test_sd_device_one(/sys/module/virtio_blk)
test_sd_device_one(/sys/module/virtio_console)
test_sd_device_one(/sys/module/virtio_net)
test_sd_device_one(/sys/module/virtio_pci)
test_sd_device_one(/sys/module/virtio_pci_legacy_dev)
test_sd_device_one(/sys/module/virtio_pci_modern_dev)
test_sd_device_one(/sys/module/virtio_ring)
test_sd_device_one(/sys/module/virtio_rng)
test_sd_device_one(/sys/module/vt)
test_sd_device_one(/sys/module/watchdog)
test_sd_device_one(/sys/module/workqueue)
test_sd_device_one(/sys/module/x_tables)
test_sd_device_one(/sys/module/xen)
test_sd_device_one(/sys/module/xen_kbdfront)
test_sd_device_one(/sys/module/xhci_hcd)
test_sd_device_one(/sys/module/xhci_pci)
test_sd_device_one(/sys/module/xz_dec)
test_sd_device_one(/sys/module/zswap)
/* test_sd_device_enumerator_devices */
test_sd_device_one(/sys/devices/LNXSYSTM:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXPWRBN:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXPWRBN:00/input/input4)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXPWRBN:00/input/input4/event3)
Assertion 'ERRNO_IS_PRIVILEGE(r)' failed at src/libsystemd/sd-device/test-sd-device.c:86, function test_sd_device_one(). Aborting.
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

**Comment by yuwata** [comment]
@mbiebl Thank you for testing this PR many times. One more time please!

**Comment by mbiebl** [comment]
```
>>> SYSTEMD_LANGUAGE_FALLBACK_MAP='/build/systemd-251~rc1/src/locale/language-fallback-map' MALLOC_PERTURB_=142 PATH='/build/systemd-251~rc1/build-deb:/usr/sbin:/usr/bin:/sbin:/bin' '/build/systemd-251~rc1/build-deb/test-sd-device'
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
Listing only the last 100 lines from a long log.
test_sd_device_one(/sys/module/joydev)
test_sd_device_one(/sys/module/kernel)
test_sd_device_one(/sys/module/keyboard)
test_sd_device_one(/sys/module/kvm)
test_sd_device_one(/sys/module/kvm_intel)
test_sd_device_one(/sys/module/l2tp_core)
test_sd_device_one(/sys/module/l2tp_netlink)
test_sd_device_one(/sys/module/ledtrig_audio)
test_sd_device_one(/sys/module/libahci)
test_sd_device_one(/sys/module/libata)
test_sd_device_one(/sys/module/lpc_ich)
test_sd_device_one(/sys/module/macsec)
test_sd_device_one(/sys/module/mbcache)
test_sd_device_one(/sys/module/memory_hotplug)
test_sd_device_one(/sys/module/module)
test_sd_device_one(/sys/module/mousedev)
test_sd_device_one(/sys/module/net_failover)
test_sd_device_one(/sys/module/netpoll)
test_sd_device_one(/sys/module/nmi_backtrace)
test_sd_device_one(/sys/module/page_alloc)
test_sd_device_one(/sys/module/page_reporting)
test_sd_device_one(/sys/module/pci_hotplug)
test_sd_device_one(/sys/module/pcie_aspm)
test_sd_device_one(/sys/module/pciehp)
test_sd_device_one(/sys/module/pcspkr)
test_sd_device_one(/sys/module/printk)
test_sd_device_one(/sys/module/processor)
test_sd_device_one(/sys/module/psmouse)
test_sd_device_one(/sys/module/pstore)
test_sd_device_one(/sys/module/qemu_fw_cfg)
test_sd_device_one(/sys/module/qxl)
test_sd_device_one(/sys/module/random)
test_sd_device_one(/sys/module/rapl)
test_sd_device_one(/sys/module/rc_core)
test_sd_device_one(/sys/module/rcupdate)
test_sd_device_one(/sys/module/rcutree)
test_sd_device_one(/sys/module/rfkill)
test_sd_device_one(/sys/module/rng_core)
test_sd_device_one(/sys/module/rtc_cmos)
test_sd_device_one(/sys/module/scsi_common)
test_sd_device_one(/sys/module/scsi_mod)
test_sd_device_one(/sys/module/secretmem)
test_sd_device_one(/sys/module/serio_raw)
test_sd_device_one(/sys/module/sg)
test_sd_device_one(/sys/module/shpchp)
test_sd_device_one(/sys/module/snd)
test_sd_device_one(/sys/module/snd_hda_codec)
test_sd_device_one(/sys/module/snd_hda_codec_generic)
test_sd_device_one(/sys/module/snd_hda_core)
test_sd_device_one(/sys/module/snd_hda_intel)
test_sd_device_one(/sys/module/snd_hwdep)
test_sd_device_one(/sys/module/snd_intel_dspcfg)
test_sd_device_one(/sys/module/snd_intel_sdw_acpi)
test_sd_device_one(/sys/module/snd_pcm)
test_sd_device_one(/sys/module/snd_timer)
test_sd_device_one(/sys/module/soundcore)
test_sd_device_one(/sys/module/spidev)
test_sd_device_one(/sys/module/spurious)
test_sd_device_one(/sys/module/sr_mod)
test_sd_device_one(/sys/module/srcutree)
test_sd_device_one(/sys/module/suspend)
test_sd_device_one(/sys/module/syscall)
test_sd_device_one(/sys/module/sysrq)
test_sd_device_one(/sys/module/tcp_cubic)
test_sd_device_one(/sys/module/thermal)
test_sd_device_one(/sys/module/tpm)
test_sd_device_one(/sys/module/tpm_crb)
test_sd_device_one(/sys/module/tpm_tis)
test_sd_device_one(/sys/module/tpm_tis_core)
test_sd_device_one(/sys/module/ttm)
test_sd_device_one(/sys/module/udp_tunnel)
test_sd_device_one(/sys/module/usb_common)
test_sd_device_one(/sys/module/usbcore)
test_sd_device_one(/sys/module/usbhid)
test_sd_device_one(/sys/module/virtio)
test_sd_device_one(/sys/module/virtio_balloon)
test_sd_device_one(/sys/module/virtio_blk)
test_sd_device_one(/sys/module/virtio_console)
test_sd_device_one(/sys/module/virtio_net)
test_sd_device_one(/sys/module/virtio_pci)
test_sd_device_one(/sys/module/virtio_pci_legacy_dev)
test_sd_device_one(/sys/module/virtio_pci_modern_dev)
test_sd_device_one(/sys/module/virtio_ring)
test_sd_device_one(/sys/module/virtio_rng)
test_sd_device_one(/sys/module/vt)
test_sd_device_one(/sys/module/watchdog)
test_sd_device_one(/sys/module/workqueue)
test_sd_device_one(/sys/module/x_tables)
test_sd_device_one(/sys/module/xen)
test_sd_device_one(/sys/module/xen_kbdfront)
test_sd_device_one(/sys/module/xhci_hcd)
test_sd_device_one(/sys/module/xhci_pci)
test_sd_device_one(/sys/module/xz_dec)
test_sd_device_one(/sys/module/zswap)
/* test_sd_device_enumerator_devices */
test_sd_device_one(/sys/devices/LNXSYSTM:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXPWRBN:00)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXPWRBN:00/input/input4)
test_sd_device_one(/sys/devices/LNXSYSTM:00/LNXPWRBN:00/input/input4/event3)
Assertion 'ERRNO_IS_PRIVILEGE(r)' failed at src/libsystemd/sd-device/test-sd-device.c:87, function test_sd_device_one(). Aborting.
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

**Comment by yuwata** [comment]
@mbiebl Ugh... One more please.

**Comment by mbiebl** [comment]
```
Ok:                 940 
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            40  
Timeout:            0   
```

**Comment by keszybz** [comment]
Looks reasonable.

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
@mbiebl Thank you!

**Pull request merged**
