### PR TITLE
preparation for v234

### PR DESCRIPTION
**Pull request by poettering**
As usualy, please submit follow-up PRs if you find an error in NEWS. or in other words: please fix the types yourselves, don#t let me jump through loops ;-)

### CODE REVIEW

**Comment by keszybz** [comment]
No typos? I'm disappointed.

**Comment by poettering** [comment]
there are plenty in the issue cover letter ;-)

**Comment by marcosfrm** [comment]
A note in NEWS about logind accepting restarts (7e867138f586a7113f43cc6d42f6ce9720489e67) would be nice. Maybe warn about xserver's commit dc48bd6 too?

**Comment by gdamjan** [comment]
what's going on with ` xenial-amd64 — autopkgtest finished (failure) `

**Comment by martinpitt** [comment]
@gdamian: Supposedly the nspawn TEST-01-BASIC hang (`Failed to allocate manager object: Read-only file system`) is a race condition; I doubt that the changes in this PR (which are mostly documentary) affect this in any way. That said, it certainly looks like a real bug, but it shouldn't block this PR. I retried the test for now.

**Comment by gdamjan** [comment]
@martinpitt it seems to block the other PRs too

**Comment by martinpitt** [comment]
That said, no - this now happens on every PR, so someone let a PR through with this regression :-(

I filed issue #6253 about it. Unless someone understands what's going on, this might need some bisecting.

**Comment by poettering** [comment]
I will take @keszybz's additions as a blessing of the rest, and merge this now. It's docs and hence unlikely to break anything...

**Pull request merged**
