### PR TITLE
mkfs-util: Remove user namespace owner => root mapping

### PR DESCRIPTION
**Pull request by daandemeyer**
This isn't actually thorough. An OS tree that we're packing up with repart can contain files belonging to any number of users. If we only remap the owner of the OS tree root directory to root in the userns, all the other files in the OS tree not owned by the owner will end up owned by "nobody" in the final filesystem. This issue can only be solved at a higher level (image builder), so let's drop the logic from repart completely.

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

I'm not going to sweat the review: you are reverting your own patches, and the author is usually the most qualified to know when their patch is not useful.

**Comment by keszybz** [comment]
CentOS CI (Arch Linux + sanitizers)
TEST-58-repart fails:
`15:27:43 [   10.602364] testsuite-58.sh[552]: Failed to copy '/tmp/test-repart.le9pdg2uVf' to '/var/tmp/repart-vthKo1/def': Operation not permitted`

**Comment by poettering** [comment]
lgtm

**Comment by keszybz** [comment]
jammy-ppc64el:
TEST-50-DISSECT:                    FAIL     (149 s)
[   96.723276] systemd-udevd[331]: pci: Worker [366] processing SEQNUM=1664 is taking a long time

I guess it's some transient kernel issue.

jammy-s390x: testbed failure

**Pull request merged**
