### PR TITLE
rc-local: drop generator and hook up units statically instead

### PR DESCRIPTION
**Pull request by mbiebl**
The only job of the rc-local generator is to check, if
RC_LOCAL_SCRIPT_PATH_START or RC_LOCAL_SCRIPT_PATH_STOP are executable
and if so, hook up rc-local.service in multi-user.target.wants and
halt-local.service in final.target.wants dynamically.

It's much simpler (and faster) to hook up the units statically and rely
on ConditionFileIsExecutable=.

### CODE REVIEW

**Comment by poettering** [comment]
It used to be that way, but we dropped that, since they are a synchronization point iirc

**Comment by mbiebl** [comment]
@poettering I don't quite understand your reply. Can you elaborate?

**Comment by poettering** [comment]
See the git log of the file. Specifically: 156730831730701cada2750e826abbf7b113861f

**Comment by mbiebl** [comment]
I would assume, a legacy free system doesn't install rc-local.service at all?

That said, is there a more detailed discussion what issue specifically was solved by this generator?

**Comment by poettering** [comment]
@mbiebl well, depends on what you mean by "legacy-free". 

legacy-free could mean: os supports legacy, but nothing uses it. Which is what we heading for with Fedora, and which is nicely supported with the generator.

legacy-free could also mean: os doesn't even support legacy. In that case you wouldn#t ship the generator (and it is turned off if you disable sysv compat support).

I am not aware of a longer discussion about this besides the patch commit msg.

**Comment by martinpitt** [comment]
The "If/when we rewrite SysV compatibility into a generator, this one can become a part of it." comment is interesting -- that did happen a while ago, so if we wanted to, `systemd-sysv-generator` could create a unit if `rc.local` is executable?

**Comment by poettering** [comment]
well, what's precisely gained by merging the two generators? I mean, the generators are run in parallel anyway...

**Pull request closed without merging**
