### PR TITLE
sysusers: also create root group

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by bluca** [comment]
@poettering was saying that there could be issues in fixing the problem line this, although i did not fully understand how

**Comment by yuwata** [comment]
> @poettering was saying that there could be issues in fixing the problem line this, although i did not fully understand how

Me neither. @poettering Could you comment on this?

**Review by bluca — APPROVED** [review]
I checked what the systemd-sysusers behaviour was on 252 and it's identical to the new one. If you have `u root 0` then the gid is created for you, and if you have `u root 0:0` it is not, in which case you need `g root 0` before, so i don't see any regressions here, unless I am missing something. Hence I am pretty sure we can merge this.

**Comment by poettering** [comment]
lgtm. (sorry i mistook this was fixing a different thing. ignore my noise)

**Pull request merged**
