### PR TITLE
iovec-util: add iovw_isempty() helper

### PR DESCRIPTION
**Pull request by poettering**
Follow-up for: 3746131aac4798cacf67b60cfc4e2e1c80ec4efb

### CODE REVIEW

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by bluca** [comment]
Coverity is also upset about that iow change:

```
*** CID 1518433:    (USE_AFTER_FREE)
/src/coredump/coredump.c: 1313 in gather_pid_metadata_from_procfs()
1307                     (void) iovw_put_string_field_free(iovw, "COREDUMP_CMDLINE=", t);
1308     
1309             if (cg_pid_get_path_shifted(pid, NULL, &t) >= 0)
1310                     (void) iovw_put_string_field_free(iovw, "COREDUMP_CGROUP=", t);
1311     
1312             if (compose_open_fds(pid, &t) >= 0)
>>>     CID 1518433:    (USE_AFTER_FREE)
>>>     Calling "iovw_put_string_field_free" frees pointer "t" which has already been freed.
1313                     (void) iovw_put_string_field_free(iovw, "COREDUMP_OPEN_FDS=", t);
1314     
1315             p = procfs_file_alloca(pid, "status");
1316             if (read_full_virtual_file(p, &t, NULL) >= 0)
1317                     (void) iovw_put_string_field_free(iovw, "COREDUMP_PROC_STATUS=", t);
1318     
/src/coredump/coredump.c: 1284 in gather_pid_metadata_from_procfs()
1278             if (r < 0)
1279                     return r;
1280     
1281             /* The following are optional, but we use them if present. */
1282             r = get_process_exe(pid, &t);
1283             if (r >= 0)
>>>     CID 1518433:    (USE_AFTER_FREE)
>>>     Calling "iovw_put_string_field_free" frees pointer "t" which has already been freed.
1284                     r = iovw_put_string_field_free(iovw, "COREDUMP_EXE=", t);
1285             if (r < 0)
1286                     log_warning_errno(r, "Failed to get EXE, ignoring: %m");
1287     
1288             if (cg_pid_get_unit(pid, &t) >= 0)
1289                     (void) iovw_put_string_field_free(iovw, "COREDUMP_UNIT=", t);
```

Would you mind fixing that too please, while you are there?

**Comment by bluca** [comment]
And the CI is also upset about this one:

```
../src/basic/io-util.c: In function ‘iovw_append’:
../src/basic/io-util.c:385:26: error: passing argument 1 of ‘iovw_isempty’ discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  385 |         if (iovw_isempty(source))
      |                          ^~~~~~
In file included from ../src/basic/io-util.c:8:
../src/basic/io-util.h:113:55: note: expected ‘struct iovec_wrapper *’ but argument is of type ‘const struct iovec_wrapper *’
  113 | static inline bool iovw_isempty(struct iovec_wrapper *iovw) {
```

Is this the start of the machine uprising?

**Review by yuwata — APPROVED** [review]

**Comment by poettering** [comment]
> Would you mind fixing that too please, while you are there?

i don#t really know how?

**Comment by poettering** [comment]
> i don#t really know how?

i'd just click them away in coverity, it's confused...

**Comment by poettering** [comment]
fixed the const thing

**Pull request merged**
