### PR TITLE
analyze: add "alias" handling to dot subcommand

### PR DESCRIPTION
**Pull request by evverx**
There is a problem: `systemd-analyze dot` doesn't work with aliases.

``` bash
$ ls -l /etc/systemd/system/default.target
lrwxrwxrwx 1 root root 37 Sep  5 02:43 /etc/systemd/system/default.target -> /lib/systemd/system/multi-user.target

$ systemd-analyze dot default.target
digraph systemd {
}

$ ls -l /etc/systemd/system/sshd.service
lrwxrwxrwx 1 root root 31 Aug 20 10:19 /etc/systemd/system/sshd.service -> /lib/systemd/system/ssh.service

$ systemd-analyze dot sshd.service
digraph systemd {
}

```

### CODE REVIEW

**Comment by evverx** [comment]
Fixed:
-  `sd_bus_get_property_string()` (see [comment](https://github.com/evverx/systemd/commit/0b5e1de9526d8d60a0dcacac7af825760104b681#commitcomment-13084075))
- `expand_patterns` logs all errors (see [comment](https://github.com/evverx/systemd/commit/0b5e1de9526d8d60a0dcacac7af825760104b681#commitcomment-13084074))
- Invert the `string_is_glob` check to keep indentation minimal (see [comment](https://github.com/evverx/systemd/commit/0b5e1de9526d8d60a0dcacac7af825760104b681#commitcomment-13084079))

Remained:
- `strv_extend` (see [comment](https://github.com/evverx/systemd/commit/0b5e1de9526d8d60a0dcacac7af825760104b681#commitcomment-13084072))

**Comment by poettering** [comment]
Looks much nicer already. 

Regarding the allocation strategy (i.e. the strv_extend() thing). Maybe we shouldn't use an strv here at all actually, but a Hashmap. Then add everything to the hashmap, thus filtering out duplicates, and leaving allocation strategy to the hashmap. And finally use hashmap_get_strv() to convert the hashmap into an strv.

**Comment by poettering** [comment]
Ah, forget what I wrote, I didn't read your earlier comment, but you are right, the array won't actually grow that large. Looks good to merge then! Sorry for the confusion!

**Comment by evverx** [comment]
@poettering , thanks for the hints.
I forgot about `--from-pattern` and `--to-pattern`.
Fixed:  #1180

**Pull request merged**
