### PR TITLE
po: add basic fedora.zanata.org configuration

### PR DESCRIPTION
**Pull request by keszybz**
This is in response to https://bugzilla.redhat.com/show_bug.cgi?id=1320812.
There is a chance that we will get additional translations through
zanata, so let's try that. To upload .pot and current translations:

$ ninja -C build systemd-pot
$ zanata-cli push
$ zanata-cli push  --push-type trans --trans-dir po

### CODE REVIEW

**Comment by poettering** [comment]
how does the workflow work there? do we get proper commits out of this, with correct attribution and history?

**Comment by keszybz** [comment]
I don't know. But that might not matter, since even if zanata doesn't provide this natively, we can just force whatever authorship in the commit when we apply the patch. I hope. I mean that if people who work on translations think this works for them, let's provide the hook-up for them to use this.

**Comment by poettering** [comment]
> I don't know. But that might not matter, since even if zanata doesn't provide this natively, we can just force whatever authorship in the commit when we apply the patch. I hope. I mean that if people who work on translations think this works for them, let's provide the hook-up for them to use this.

well, if translator folks have a laissez-faire approach to copyright I am not sure this is something we should accept for stuff that is merged into our tree... I mean, if the major jurisdictions all say that translations aren't copyrightable, then sure I'd be fine with merging translations without proper attributions, but otherwise I am not sure we should have that in our repo...

I appear to be missing something completely there. I mean, I understand why Transifex doesn't hand out properly attributed commits: they are a business, and want to be the primary source of truth. That makes it incompatible with our goals but OK. But for Zenata, why this all? They aren't a business, they are just some RH tool, so why don't they hand out properly attributed history upstreams can merge into their git trees? and why am I apparently the only one who is weirded out by this disinterest in the most basic copyright hygiene on these things?

**Comment by poettering** [comment]
I mean, I am just afraid of sending the signal to translators that we now accept translations this way, but then we actually either are in serious trouble merging it back, because there appears to be no sensible tool for doing so and we need to do it manually, or we won't do it at all, which then sucks for everybody, because people think they are contributing, but effectively it's never reaches us upstream...

**Comment by keszybz** [comment]
I **assumed** that the way this works is that people type in some translations in the web service, and then then pull out the .po files and overwrite those in the tree, and the diff is what it is, and the copyright is assigned to that patch. I mean, how can this work otherwise?

**Comment by poettering** [comment]
> I assumed that the way this works is that people type in some translations in the web service, and then then pull out the .po files and overwrite those in the tree, and the diff is what it is, and the copyright is assigned to that patch. I mean, how can this work otherwise?

My understanding is that whenever you think it's time you pull the current version from zanata using some zanata-specific tool. And what you get then you commit as a new commit to git. Typically you'd do this pull shortly before each release. The resulting commit would hence consist of all translations changes made on zanata since the last pull, all squashed into one humungous big change without any attribution except "this is an import from zanata". Yes, the individual .po files might contain an author's name in the metadata section at the top, but this never worked for .c files (and I figure sooner or later we'll drop the whole copyright blurb from our .c files altogether even, making git metadata the primary source of copyright ownership info), and there's little reason to believe it works any better for .po files... 

I don't know, I am not a translations guy, I don't really grok their workflow, but from all I am seeing it's like what I describe above, and that's just weird...

**Comment by poettering** [comment]
That new commit is attributed to you, but that's because you did the import, no? Hence if we do "git shortlog -s" we'll always see you as the contributor then, but that's not a good thing… And "git blame" will show you as contributor for most lines too very soon...

**Comment by keszybz** [comment]
So I made a test translation, and it seems OK. See the description in the second commit message. This means that attributions *can* be done correctly, even if the default zanata workflow does not do that (I'm not saying that it doesn't, I just did the most obvious thing for me and it seemed to work).

Anyway, I think if multiple people work on the translations, I think it's OK to not bother with proper authorshiop assignment for each line. Even in systemd, we generally don't bother putting copyright lines on each file, except if somebody largely rewrites some source file or makes a new one.

> That new commit is attributed to you, but that's because you did the import, no? Hence if we do "git shortlog -s" we'll always see you as the contributor then, but that's not a good thing… And "git blame" will show you as contributor for most lines too very soon...

Well, no. Only for the lines I changed. My patch has a lot of churn because the line number comment formatting changes (which actually is caused by my other patch to fix `systemd-pot`, and not by zanata), but apart from that and a few superficial formatting changes, only new strings and the new translation are "new". For translations patches that we got before, there was always the problem that when different translators used different software, a lot of churn was generated by formatting changes. I guess it's something that we have to live with because the .po format is not too precisely defined.

And if there were multiple people working on a single translation, then one will have to picked to be the author of the patch. I think that's the same as with any other git patch, since git does not allow multiple authors on a patch.

**Comment by poettering** [comment]
> And if there were multiple people working on a single translation, then one will have to picked to be the author of the patch. I think that's the same as with any other git patch, since git does not allow multiple authors on a patch.

well, let's say we do one release per month, hence import the data from zanata once per month, then this would mean that all contributions to the l10n for one specific language would be merged into one commit and it would be attributed to whoever is the one importing this from zanata, right? Or if the one importer it is nice and uses git's `--author=` switch, then it would be attributed to whoever the importer chooses from the list of actual contributors, right? There's quite a disconnect there: on one hand we want that git history reflects the list of contributors correctly and fully. And on the other hand zanata will munge contributions into one for each language over each of our release cycles.

**Comment by keszybz** [comment]
First of all, that's now how things work so far: with some rare exceptions, we have just one person who takes our .pot file and either completely translates it to a new language, or updates an existing translation to contain all the latest strings. So your concern is mostly theoretical, since we don't really have multiple contributors to translations for a single language.

But second, even if there *were* multiple translators, they can do the export multiple times and submit a PR with multiple commits. Also, I haven't checked that, but I hope that zanata will include multiple names in the author section in the translation file.

All in all, I feel that we could use more translations, and it's possible that translators might find it easier to go through zanata (the interface is certainly nice, and I found it obvious and pleasant, despite never having used it before), and we're blocking on some concerns that are a) not really our concerns, b) don't really apply to our case, at least from what we have seen until now, c) can be easily surmounted with some manual git commands.

**Comment by poettering** [comment]
Hmm, OK, but please, let's be super careful with importing stuff from zanata.

I think SPDX and git give us the opportunity to properly track licenses and attributions of contributions in a more systematic, machine-readable, fine-grained way. It'd be sad if we can't really rely on that because we connect our stuff to remote tooling that duplicates contribution attribution in its own database and only provides us with a mangled, squashed set – within the files themselves rather than in proper git metadata.

**Comment by keszybz** [comment]
Ack.

**Comment by piotrdrag** [comment]
I added systemd to the [upstream](https://fedora.zanata.org/version-group/view/upstream) group on Zanata and added a note on the [GNOME](https://l10n.gnome.org/module/systemd/) project page to direct translators to it.

**Pull request merged**
