### PR TITLE
macro.h: improve IN_SET helper macro

### PR DESCRIPTION
**Pull request by zonque**
Make `IN_SET()` generate switch-case statements rather than a list walker.

/cc @dvdhrm

### CODE REVIEW

**Comment by michich** [comment]
Wow, I did not know this macro trick.
OK, I see how it works :-)

Quoting myself from commit 77247cba3e8 "basic: more optimizable IN_SET macro":

> IN_SET still results in worse generated code than using
> "x == FOO || x == BAR || ...". I don't think we'll be able to match
> that with the C preprocessor.

It sound like you've found a way to do it. Excellent!

**Comment by dvdhrm** [comment]
Hm, there was a temporary `#pragma` error in semaphore. No idea where it came from, but it seems to be resolved.

The series looks good to me. As I said, the `__VA_ARGS__` trick requires a maximum argument level. There are ways to bump it to `2^32` easily, but at the cost of crazy code and crazy compile-times. Even `boost-cpp` limits itself to 64 in nearly all its APIs.

Long story short: I like it!

**Comment by zonque** [comment]
> Hm, there was a temporary #pragma error in semaphore. No idea where it came from, but it seems to be resolved.

That was caused by an earlier version that used `assert_cc()` instead of the dummy array allocation that the patch now has. The problem is that `assert_cc()` doesn't work when the entire construct is used in a ternary expression.

**Comment by zonque** [comment]
> The series looks good to me. As I said, the **VA_ARGS** trick requires a maximum argument level. There are ways to bump it to 2^32 easily, but at the cost of crazy code and crazy compile-times. Even boost-cpp limits itself to 64 in nearly all its APIs.

If people use that many arguments to `IN_SET()`, I'd argue there is a nicer way to handle the case on the call site :)

**Comment by poettering** [comment]
I like!

**Pull request merged**
