### PR TITLE
Update Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by rffontenelle**

### CODE REVIEW

**Comment by mbiebl** [comment]
@martinpitt you speak Portuguese? Impressive :-)

**Comment by martinpitt** [comment]
I deliberately said "reasonable", not "correct" -- Portugese is close enough to German, French, and some tiny bits of Italian that I know that I can say whether unfuzzed translations make sense in general :-)

**Comment by rffontenelle** [comment]
I'm sorry: I just found a single typo in the translation. Could you replace "uma contêiner" with "um contêiner" (just remove the "a") in this file?

**Comment by martinpitt** [comment]
@rffontenelle: Done in https://github.com/systemd/systemd/commit/91dacd445

**Comment by rffontenelle** [comment]
Thanks!

**Pull request merged**
