### PR TITLE
[RFC] journal: mlock keep_always and in-context windows

### PR DESCRIPTION
**Pull request by vcaputo**
When the system is under memory pressure, page reclaim can cause
journald to thrash resulting in significant latency spikes and reduced
logging throughput.

The journal header is accessed by most operations and mapped with the
keep_always flag set to true, by locking keep_always pages we pin the
header's backing memory ensuring the its members may be accessed without
unnecessary page faults.

This commit also locks non-keep_always windows while they are referenced
in the context cache, for the same reasons.

It has shown to make a small improvement in journald performance under
memory pressure:

```
w/mlock:
 [ 2310.908835] iterations: 0 0 0 0 16 0 0  0  1 0 0 0 0 0 1 0 25 10 0 1
 [ 2315.928947] iterations: 0 0 0 1 13 1 1  3  0 1 0 1 2 0 2 0 19 15 0 0
 [ 2321.049267] iterations: 0 0 0 0 11 2 1  1  1 0 0 0 0 0 0 0 4  23 0 1
 [ 2326.186509] iterations: 0 0 0 0 10 4 1  1  1 0 0 0 0 0 0 0 1  25 1 0
 [ 2331.355932] iterations: 0 0 0 0 14 2 0  0  1 0 0 0 0 0 1 0 21 17 0 0
 [ 2336.875003] iterations: 0 0 0 0 14 2 1  0  0 1 0 0 0 0 0 0 10 21 0 1
 [ 2341.887096] iterations: 0 0 0 0 12 1 1  0  0 1 0 0 0 0 0 0 0  26 1 0
 [ 2346.997502] iterations: 0 0 1 0 14 1 2  0  1 0 0 0 2 2 0 0 8  20 0 1
 [ 2352.128118] iterations: 0 0 0 0 12 4 0  1  1 0 0 0 0 0 0 0 6  23 1 0
 [ 2357.342909] iterations: 0 0 0 0 15 0 0  0  0 1 0 0 0 0 1 0 0  27 2 0
 [ 2362.442891] iterations: 0 0 0 0 12 1 0  2  2 0 0 0 0 0 0 0 0  27 1 0
 [ 2367.542129] iterations: 0 0 0 0 15 0 1  2  0 0 0 0 0 0 0 1 12 22 0 0
 [ 2372.624936] iterations: 0 0 0 0 15 1 1  1  0 1 0 1 5 6 0 0 13 17 2 0
 [ 2377.710251] iterations: 0 0 1 0 14 0 3  0  0 1 0 0 0 0 1 0 10 21 0 0
 [ 2382.801476] iterations: 0 0 0 0 14 0 0  1  0 1 0 0 0 0 0 0 4  26 0 0

unmodified:
 [ 1820.136485] iterations: 0 0 0 0 1  1 11 6  0 0 0 0 0 0 0 0 2  29 2 0
 [ 1825.182421] iterations: 0 0 0 0 0  1 5  7  2 0 0 0 0 0 0 0 0  22 3 0
 [ 1830.236331] iterations: 0 0 0 0 1  0 8  8  1 0 0 0 0 0 1 0 0  34 0 0
 [ 1835.430928] iterations: 0 0 0 0 1  0 7  7  2 0 0 0 0 0 0 0 0  15 5 1
 [ 1840.466423] iterations: 0 0 1 0 8  1 6  0  0 1 0 0 0 0 1 0 0  26 1 0
 [ 1845.589526] iterations: 0 0 0 0 14 2 1  1  2 0 0 0 0 0 0 0 0  32 1 0
 [ 1850.596734] iterations: 0 0 0 0 15 0 0  1  1 0 0 0 0 0 0 0 0  31 0 0
 [ 1855.705874] iterations: 0 0 0 0 11 1 2  3  2 0 0 0 0 0 0 0 0  25 3 0
 [ 1860.878891] iterations: 0 0 0 0 6  0 4  4  1 0 0 0 0 0 0 0 0  18 3 0
 [ 1865.954972] iterations: 0 0 0 0 9  1 2  2  0 1 0 0 0 0 0 1 0  18 2 0
 [ 1871.090451] iterations: 0 0 0 1 12 1 4  1  2 0 0 0 0 0 0 0 0  27 2 0
 [ 1876.178701] iterations: 0 0 0 0 16 0 0  1  1 0 0 0 0 0 1 0 0  33 0 0
 [ 1881.227717] iterations: 0 0 0 0 15 2 0  2  1 0 0 0 0 0 0 0 0  33 0 0
 [ 1886.348814] iterations: 0 0 0 0 15 1 1  1  1 0 0 0 0 0 0 0 0  35 0 0
 [ 1891.450513] iterations: 0 0 0 0 14 1 0  2  1 0 0 0 0 0 0 0 1  26 2 0
```

### CODE REVIEW

**Comment by vcaputo** [comment]
Just throwing this up here to start the conversation, these changes make a small improvement but it's nothing to write home about still.

**Comment by poettering** [comment]
mlock appears a bit strong, no? But i figure there's no weaker api...

could we at least add some limit or so to this? i.e. that we don't end up locking too much memory? otherwise looks OK I think.

**Comment by vcaputo** [comment]
Well, I'm not aware of any alternative to mlock.

I force-pushed a changed version where it only mlocks windows <= WINDOW_SIZE.

**Comment by poettering** [comment]
Oh, I meant a global counter, not just a window size threshold. i.e. in MmapCache maintain a counter that accumulates how many locked pages we keep, and as soon as that goes beyond some threshold we should not lock more pages. Basically I am just afraid about locking too much memory, if this is done without bounds. (yes, we put a limit on the number of windows anyway, hence if we put a limit on the locked windows size we indirectly also lock the whole amount, but I'd really prefer if this was explicit a per-MMapCache limit that accounts for the whole locked memory).

Also, I'd really like to see some comments placed next to one of the mlock()s to explain why we are doing this. This is otherwise really hard to grasp when looking at jut the code... Just add a small comment about performace (linking to this PR might even make sense...)

**Comment by vcaputo** [comment]
I'm just not sure what would make for a good magic number to restrict these locked pages to.

It's making me lean towards only locking the keep_always=true windows which would keep the headers pinned and bring some benefit, without us having to worry about pinning "too much" (and thus avoid defining what "too much" is).

**Comment by poettering** [comment]
@vcaputo well, picking limits is always difficult. I'd just take some somewhat sensible but mostly random value (let's say 64MiB or so) as a start, verify that it has a positive effect, ship it in a released version and see if it triggers any complaints by users...

**Comment by martinpitt** [comment]
This PR is almost year old and thus stale, and got rejected in its present form. Hence I am closing it now. If this is still relevant, please fix and rebase to current master, and either reopen this PR or open a new one. Thank you for understanding!

**Pull request closed without merging**
