### PR TITLE
NEWS: fix several typos

### PR DESCRIPTION
**Pull request by mrc0mmand**

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
LGTM. I don't think we have to wait for CI for this one.

**Comment by evverx** [comment]
@DaanDeMeyer welcome to the systemd team on GitHub!

Could you press the "rebase" button when merging one-commit PRs going forward? According to https://github.com/systemd/systemd/issues/8665#issuecomment-387967612:
> ... So the new rules are:
> - single commit → rebase
> - a bunch of fixup commits that should be one → squash
> - more than one commit → merge

**Comment by evverx** [comment]
@DaanDeMeyer I forgot to say that if you'd be interested in receiving and viewing OSS-Fuzz bug reports I could add your gmail address to https://github.com/google/oss-fuzz/blob/master/projects/systemd/project.yaml. If you don't have access to [Coverity](https://scan.coverity.com/projects/350) yet I can add you to the systemd organization there as well.

**Comment by DaanDeMeyer** [comment]
@evverx That'd be great. Thanks!

**Pull request merged**
