### PR TITLE
Eliminate an unnecessary VLA

### PR DESCRIPTION
**Pull request by vcaputo**
gettyname_malloc() grows the path on the stack, it's probably fine but seems potentially dangerous.  To preserve the exponential growth a non-greedy realloc variant LAZY_REALLOC has been introduced as well.

### CODE REVIEW

**Comment by vcaputo** [comment]
This has not been compiled or tested.  The meson_options.txt appears to no longer be compatible with the version of meson available on debian stable, so I didn't build and figured the CI can test it.  My bandwidth is too limited right now to spin up a newer container with a toolchain etc.

**Comment by keszybz** [comment]
I pushed #12044 as a suggestion of a simpler solution.

**Comment by vcaputo** [comment]
@keszybz I just blindly preserved the existing robustness while eliminating the ostensibly potentially unbounded stack allocation, assuming the robustness was there for good reason.

I just took a look at some glibc source I have laying around and the linux `ttyname()` implementation uses malloc and enlarges the global buffer similarly to GREEDY_REALLOC but with free/malloc - it's not explicitly bound to `PATH_MAX` there.  But looking at what is being put into the buffer, it looks like its length would be bound to a "/dev/pts/" prefix plus NAME_MAX.  In that particularly glibc version at least.

But it's gross to be relying on such assumptions in userspace, it's not like the ttyname_r() man page makes any commitments as to the maximum length; its API accomodates any length.

Isn't it entirely plausible that we'd start having tty paths attached anywhere in the filesystem?  Would there ever be a scenario where a host needs to get the ttyname of a tty inside a container, with the path from the host perspective?  I.e.  `/var/lib/machines/foo/dev/pts/10` ?  If that sort of thing is in our future, then the robustness becomes important.

It's up to you guys.

**Comment by keszybz** [comment]
But the path like that cannot be open()ed or anything. I think it's not worth worrying about a theoretical case.

**Comment by poettering** [comment]
Hmm, so I don't like this patch because it actually makes use of realloc() for something where realloc() doesn't need to be used. It's most noble property after all is that it copies the memory to the new memory block if it allocates a new one. But we don't need that here, we request the full thing from the kernel after all, each time.

realloc() loops are great if we need to retain the data from the previous loops. But if we don't, i think it's better to just free() and malloc(), as this allows memory management to just place the newly allocated data wherever it wants without copying stuff around.

Anyway, I prepped an alternative (3rd) fix for this in #12076, ptal.

**Comment by vcaputo** [comment]
Closing in favor of the proposed alternatives...

**Pull request closed without merging**
