### PR TITLE
udev,systemctl: fix memleak caused by wrong cleanup function

### LINKED ISSUE #13764: Possible memory leak in `udev_rule_line_apply_static_dev_perms()` (udev/udev-rules.c)
**systemd version the issue has been seen with**
> latest master

**Used distribution**
 > Arch Linux

```
[   85.185177] systemd-udevd[340]: =================================================================
[   85.208065] systemd-udevd[340]: ==340==ERROR: LeakSanitizer: detected memory leaks
[   85.240686] systemd-udevd[340]: Direct leak of 8 byte(s) in 1 object(s) allocated from:
[   85.260204] systemd-udevd[340]:     #0 0x7ff3addb78d6 in __interceptor_strdup /build/gcc/src/gcc/libsanitizer/asan/asan_interceptors.cc:445
[   85.282955] systemd-udevd[340]:     #1 0x7ff3ad2d7b47 in strv_extend ../src/basic/strv.c:509
[   85.305865] systemd-udevd[340]:     #2 0x55c40068da2f in udev_rule_line_apply_static_dev_perms ../src/udev/udev-rules.c:2347
[   85.328606] systemd-udevd[340]:     #3 0x55c40068da2f in udev_rules_apply_static_dev_perms ../src/udev/udev-rules.c:2368
[   85.350934] systemd-udevd[340]:     #4 0x55c40064af9f in main_loop ../src/udev/udevd.c:1707
[   85.371191] systemd-udevd[340]:     #5 0x55c40064af9f in run ../src/udev/udevd.c:1838
[   85.391155] systemd-udevd[340]:     #6 0x55c40064af9f in main ../src/udev/udevd.c:1841
[   85.411539] systemd-udevd[340]:     #7 0x7ff3abc3f152 in __libc_start_main (/usr/lib/libc.so.6+0x27152)
[   85.432790] systemd-udevd[340]: SUMMARY: AddressSanitizer: 8 byte(s) leaked in 1 allocation(s).
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #13764.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
@yuwata could you give this one a force-push to re-trigger the rest of the CentOS CI jobs?

**Comment by mrc0mmand** [comment]
Jjust a note why this issue wasn't detected automagically: it's reproducible only with gcc and its version of libasan, the LLVM one doesn't detect it. And since we had to disable the gcc sanitizers job, the checks remained green.

**Comment by yuwata** [comment]
Let's merge this.

**Comment by mrc0mmand** [comment]
Triggered a manual build of the cron job and it finally passes: https://ci.centos.org/view/systemd/job/systemd-cron-build/

**Comment by yuwata** [comment]
Thank you!

**Pull request merged**
