### PR TITLE
mkosi.build: Silence "Entering directory" message from ninja

### PR DESCRIPTION
**Pull request by daandemeyer**
When using `ninja -C "$BUILDDIR"`, ninja prints an annoying log
message about entering the directory that cannot be silenced. To
circumvent this, we use pushd/popd which we can actually silence
instead.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Added an extra commit to silence errors when groups already exist as well

**Comment by bluca** [comment]
Uh, wut?

```
/root/mkosi.build: 90: pushd: not found
```

**Comment by bluca** [comment]
> Uh, wut?
> 
> ```
> /root/mkosi.build: 90: pushd: not found
> ```

It's not a missing directory, or it would be:

```
$ pushd wut
bash: pushd: wut: No such file or directory
```

**Comment by DaanDeMeyer** [comment]
pushd is bash only, switched to simple cd instead.

**Comment by DaanDeMeyer** [comment]
Changes only touch mkosi and those CIs are all green to taking the liberty to merge.

**Comment by bluca** [comment]
> pushd is bash only, switched to simple cd instead.

Oh I see, I tought these images ran with bash so I was a bit confused

**Pull request merged**
