### PR TITLE
networkd: fix overflow check

### PR DESCRIPTION
**Pull request by poettering**
Fixes: #9591

### CODE REVIEW

**Comment by poettering** [comment]
cc @pfl

**Comment by gdamjan** [comment]
What's the use of `uint64_t n = n_used` on line 184 actually? it's not modified anywhere I can see.

**Comment by poettering** [comment]
@gdamjan ah, right, that code makes no sense. @pfl ?

**Comment by pfl** [comment]
> @gdamjan ah, right, that code makes no sense. @pfl ?

Yeah, if it is not used, feel free to drop it. Otherwise the patch looks fine, I'll take a look at what happens with the left-over subnets, the code looks a bit lame there too.

**Pull request merged**
