### PR TITLE
core: map io.bfq.weight to 1..1000

### PR DESCRIPTION
**Pull request by keszybz**
Aaargh. See the comment in the code.

Apparently the range is like that:
$ sudo bash -c 'echo "default 1001" >/sys/fs/cgroup/user.slice/io.bfq.weight'
bash: line 0: echo: write error: Numerical result out of range

$ uname -r
5.11.0-0.rc4.129.fc34.x86_64

/cc @paolo-github

### CODE REVIEW

**Review by bluca — APPROVED** [review]
An... interesting interface. LGTM.

**Comment by keszybz** [comment]
bionic-i386: FAILED TESTS:  TEST-30-ONCLOCKCHANGE TEST-55-UDEV-TAGS
bionic-amd64: FAILED TESTS:  TEST-17-UDEV-WANTS TEST-55-UDEV-TAGS

This looks unrelated to this PR, but maybe something changed recently to make those tests more flaky?

**Comment by bluca** [comment]
> bionic-i386: FAILED TESTS: TEST-30-ONCLOCKCHANGE TEST-55-UDEV-TAGS
> bionic-amd64: FAILED TESTS: TEST-17-UDEV-WANTS TEST-55-UDEV-TAGS
> 
> This looks unrelated to this PR, but maybe something changed recently to make those tests more flaky?

mmh TEST-55 does sometimes fail, but I cannot recall ever seeing TEST-30 fail before?

**Comment by keszybz** [comment]
https://github.com/systemd/systemd/issues/12268

**Comment by bluca** [comment]
> #12268

mmh looks like it was blocked for a while, but it is not currently? Only TEST-25 has a deny-list-ubuntu-ci

**Comment by poettering** [comment]
still tempted to just drop bfq support. kernel people should figure out their api mess...

**Comment by poettering** [comment]
lgtm though

**Comment by paolo-github** [comment]
As you can see from linux-block ml, I've done my best to clear this interface mess, at no avail. I'm sorry for the community, and for the scheduler, whose quality and benefits have not to do with this problem.

**Comment by poettering** [comment]
if kernel peeps can't figure out their mess I am not sure we should accept the bill for it though.

**Pull request merged**
