### PR TITLE
network: do not request dynamic addressing protocols finished when at…

### LINKED ISSUE #27779: systemd-networkd-wait-online service wait for IPv6 network discovery after static IPv4 is configured
### systemd version the issue has been seen with

252

### Used distribution

custome/yocto

### Linux kernel version used

5.10.154.10

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd-wait-online

### Expected behaviour you didn't see

The network configuration is static IPv4 support, and the systemd-networkd-wait-online service is expected to report link is configured and network is online as long as the static IPv4 address is configured, skipping IPv6 network discovery configuration, which delayed wait-online service time. We want network online to be faster.

### Unexpected behaviour you saw

From test, the systemd-networkd-wait-online service took 2 seconds, which includes more than 1.2 seconds on IPv6 network discovery configuration. From the systemd-netword source code, it seems that systemd-networkd-wait-online service needs to 
wait both static IPv4 address and IPv6 network discovery to be configured before it announces the link is configured and network
is online. The wait-online service is thus delayed by the IPv6 network discovery configuration.

### Steps to reproduce the problem

Here is the network configuration to check the issue:

[Network]
DHCP=No
Address=<PREFIX>.138.15/25
Gateway=<PREFIX>.138.1
DNS=<PREFIX>.99.167...

[IPv6AcceptRA]
DHCPv6Client=no
     

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
...
[    1.171503] (t-on[429]: systemd-networkd-wait-online.service: Executing: /usr/lib/systemd/systemd-networkd-wait-online
[    1.174346] systemd-networkd-wait-online[429]: Found link 1
[    1.174871] systemd-networkd-wait-online[429]: lo: link is ignored
...
[    1.603098] systemd-networkd[391]: enP8p1s0f0np0: link_check_ready(): static addresses are not configured.
...
[    1.608904] systemd-networkd[391]: enP8p1s0f0np0: Addresses set
...
[    1.609824] systemd-networkd[391]: enP8p1s0f0np0: Routes set
...
[    3.070317] systemd-networkd[391]: enP8p1s0f0np0: NDISC: Sent Router Solicitation, next solicitation in 3s
[    3.072865] systemd-networkd[391]: enP8p1s0f0np0: NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 1800 sec
...
[    3.074386] systemd-networkd[391]: enP8p1s0f0np0: SLAAC addresses and routes set.
[    3.074465] systemd-networkd[391]: enP8p1s0f0np0: link_check_ready(): IPv4LL:no DHCPv4:no DHCPv6:no DHCP-PD:no NDisc:yes
...
[    3.074582] systemd-networkd[391]: enP8p1s0f0np0: State changed: configuring -> configured
[    3.075692] systemd-networkd-wait-online[429]: enP8p1s0f0np0: link is configured by networkd and online.
...
```

### PR DESCRIPTION
**Pull request by yuwata**
… least one static address is configured

The setting IPv6AcceptRA= is defaults to yes, hence, even if a .network file for an interface has static IP address configuration, it may takes few seconds for the interface being configured state, as NDisc for the interface needs to be finished. That makes wait-online.service needlessly slow. Typically, such delay is not necessary for statically configured networks.

Let's make the required condition slightly relaxed; if a .network file has static IP address configurations, then let's make the matching interface enter the 'configured' state soon after the static addresses configured on the interface.

Note, this does not change the default for IPv6AcceptRA=, hence, NDisc still runs on interfaces by default. So, addresses, routes, DNS servers, and so on based on RA will be assigned on interfaces later.

Strictly speaking, this breaks backward compatibility, but the previous behavior is not clearly documented. If a user requested both static IPv4 address and IPv6 SLAAC address configured before an interface being entered to the 'configured' state, then '--ipv6' for wait-online can be used. So, the behavior change should not cause severe regression.

Closes #27779.

### CODE REVIEW

**Comment by bluca** [comment]
So the same thing could be achieved, without changes, with --ipv4 on the command line? I see that the af options are not documented in the manpage. Perhaps it would be better to instead enhance the manpage, fully list these new options, and show detailed examples of all the supported combinations? There are quite a few switches now, and it is unclear how they behave when they are combined.

**Comment by yuwata** [comment]
> So the same thing could be achieved, without changes, with --ipv4 on the command line?

Unfortunately, no. --ipv4 (or --ipv6) works only when an interface is in the 'configured' state.
If IPv6AcceptRA=yes, the interface never enters the configured state until NDisc timeouts or finishes to process the initial RA.

**Comment by yuwata** [comment]
> I see that the af options are not documented in the manpage. Perhaps it would be better to instead enhance the manpage, fully list these new options, and show detailed examples of all the supported combinations? There are quite a few switches now, and it is unclear how they behave when they are combined.

It is documented. But, yeah, we should extend the man page about the combination of options.

**Review by bluca — APPROVED** [review]
Could you please update the manpage to document the static v4 + --ipv6 wait and so on?

**Comment by yuwata** [comment]
> Could you please update the manpage to document the static v4 + --ipv6 wait and so on?

Sure, will do, but in another PR.

**Pull request merged**
