### PR TITLE
networkctl: display address labels

### PR DESCRIPTION
**Pull request by ssahani**
```
 ./networkctl label

    Prefix/Prefixlen                          Label
        ::/0                                  1
    fc00::/7                                  5
    fec0::/10                                11
    2002::/16                                 2
    3ffe::/16                                12
 2001:10::/28                                 7
    2001::/32                                 6
::ffff:0.0.0.0/96                                 4
        ::/96                                 3
       ::1/128                                0

```

### CODE REVIEW

**Comment by keszybz** [comment]
Hm, can you provide a bit more explanation what exactly those labels are and what this is useful for?

**Comment by ssahani** [comment]
Actually we already have them in networkd. https://github.com/systemd/systemd/blob/master/man/systemd.network.xml#L805
IPv6 address labels are used for address selection. https://www.ietf.org/rfc/rfc3484.txt explains in details.

**Comment by keszybz** [comment]
This needs an addition in networkctl.xml.

This output is the same as `ip addrlabel`, except in reverse order. Please mention that in the man page description.

The sd-netlink part looks OK. But the networkctl part needs some work. Just duplicating the functionality of `ip` doesn't seem useful if it doesn't provide anything extra. `networkctl list/lldp` print nice tables, and this command should do the same.

Also, shouldn't networkctl status include this information in the address listing? Or is that too much information?

**Comment by ssahani** [comment]
>networkctl list/lldp print nice tables, and this command should do the same.

 Yes will change it.

>Also, shouldn't networkctl status include this information in the address listing? Or is that too much information?

Yes  it would look rather polluted there.

**Comment by ssahani** [comment]
updated

**Comment by keszybz** [comment]
I added the man page and shell completions additions.

**Comment by ssahani** [comment]
Nice thanks :+1:

**Comment by keszybz** [comment]
Right now it's basically equivalent to `ip addrlabel`, but I hope we can build on this to provide more functionality in the future.

**Pull request merged**
