### PR TITLE
test: use the new `udevadm wait` verb to wait for the loop device

### PR DESCRIPTION
**Pull request by mrc0mmand**
The original workaround didn't work, as `systemd-repart` kept failing
even when the `/dev/loopX` device was present:

```
[   13.959419] H testsuite-58.sh[280]: + LOOP=/dev/loop1
[   13.959636] H testsuite-58.sh[280]: + :
[   13.959764] H testsuite-58.sh[280]: + test -e /dev/loop1
[   13.959895] H testsuite-58.sh[280]: + break
[   13.960023] H testsuite-58.sh[280]: + systemd-repart --pretty=yes --definitions=/tmp/testsuite-58-sector/ --seed=750b6cd5c4ae4012a15e7be3c29e6a47 --empty=require --dry-run=no /dev/loop1
[   13.970538] H testsuite-58.sh[363]: Device '/dev/loop1' has no dm-crypt/dm-verity device, no need to look for underlying block device.
[   13.970538] H testsuite-58.sh[363]: Failed to determine canonical path for '/dev/loop1': No such file or directory
[   13.970538] H testsuite-58.sh[363]: Failed to open file or determine backing device of /dev/loop1: No such file or directory
```

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
Could you also update test-repart.sh?

**Comment by mrc0mmand** [comment]
> Could you also update test-repart.sh?

Sure! Done.

**Review by yuwata — APPROVED** [review]
Thanks. LGTM.

**Comment by mrc0mmand** [comment]
`test-repart.sh` needed a bit more work to make it work properly, so dropping the green label for another round of reviews

**Review by yuwata — APPROVED** [review]

**Pull request merged**
