### PR TITLE
RFC Group user slices 

### PR DESCRIPTION
**Pull request by Werkov**
The structure of slices related to systemd-logind is currently hardcoded, having individual user slices under one common `user.slice`. It is not possible to share a resource within a group of users. This series introduces a new [systemd-logind configuration directive](https://lists.freedesktop.org/archives/systemd-devel/2018-February/040356.html) that specifies how the slice hierarchy is being built and it implements one new policy that is based on the primary group of the user.

The user session scopes and `user@.service` are started under the new slice, the latter is patched by systemd-logind, breaking some assumptions introduced in #7599. This changes also help with #12989.

### CODE REVIEW

**Comment by poettering** [comment]
What's the usecase for this?

**Comment by Werkov** [comment]
The use case is joint resource control/accounting for groups of users, also detailed in #12989.

Recently, I've learnt about pam_data and per session scope resource limits, so alternative approach would be setting the session's slice with a PAM module. (Again, `user@.service` would need special handling as in the posted patches.)

**Comment by johannbg** [comment]
This wont work in practice since users can be in multiple groups and will just lead to inherit administrators mess if based on end users group(s) and before you know it suddenly you have individual higher up hierarchy( a team leader, a manager etc ) which wants or should get more resources based on his or her "status" within that group ( there are few pykota war story's in the wild ). So first providing the means to assign resources to individual users. Once that has been achieved those users could be put into some form of resource scope outside their end users group(s) (  which most likely ends up being a company --> departments -- staff or school --> department --> staff --> students but sometimes staff works in more than one department and students can also be staff so before you know it it's just as messy as allocate resources to group(s) so meh it's probably best just to stick with individual users )

**Comment by Werkov** [comment]
Thanks for your input. Note that control over individual user slices is retained. Surely, it requires conscientious admin to design groups properly (note the aggregation per primary user group is a just a natural proposal).

The complementary POV is that the goal is to make `user.slice` more fine grained or give more freedom in structuring the hierarchy (as we already have with service/scope `Slice=` directive).

**Comment by poettering** [comment]
Hmm, so, I wonder, the stuff in #14375, wouldn't that cover your usecase too? i.e. with that you could set resource settings for individual users by providing a per-user json record.

i.e. do you actually need to group users? or is simple per-user resource mgmt enough for your usecase?

If you actually want to group users, then wouldn't it be nicer if we built that on top of #14375 by addinga "slice" json field or so that allows admins to explicitly assign users a specific slice. That way we wouldn't plug the concept of unix groups in between...

Does this make any sense?

**Comment by Werkov** [comment]
On Fri, Jan 03, 2020 at 05:53:41AM -0800, Lennart Poettering <notifications@github.com> wrote:
> i.e. do you actually need to group users? or is simple per-user
> resource mgmt enough for your usecase?
Sharing resource within a group is desired. And more generally
configuring user slices subtree,...

> If you actually want to group users, then wouldn't it be nicer if we
> built that on top of #14375 by addinga "slice" json field 
...which a configurable slice attribute would achieve quite cleanly.
Alas, it'd be usable only for homed users, wouldn't it?
It could compose as another policy for `UserSliceParent=` though.

Meanwhile, I started pondering an alternative idea of (ab)using PAM data
(as we do for per-session limits) to specify slice for session scopes.
The reason why I abstain from it is that it excludes `user@.service`.

**Comment by poettering** [comment]
> On Fri, Jan 03, 2020 at 05:53:41AM -0800, Lennart Poettering ***@***.***> wrote: i.e. do you actually need to group users? or is simple per-user resource mgmt enough for your usecase?
> Sharing resource within a group is desired. And more generally configuring user slices subtree,...
> If you actually want to group users, then wouldn't it be nicer if we built that on top of #14375 by addinga "slice" json field
> ...which a configurable slice attribute would achieve quite cleanly. Alas, it'd be usable only for homed users, wouldn't it? It could compose as another policy for `UserSliceParent=` though. Meanwhile, I started pondering an alternative idea of (ab)using PAM data (as we do for per-session limits) to specify slice for session scopes. The reason why I abstain from it is that it excludes `user@.service`.

the userdb stuff is separate from homed to some degree. Anyone can provide JSON user records easily. It's a matter of hacking up a trivial varlink/json service that provides them on request. homed is one provider, but this is intentionally designed to be open to other providers, including for example ldap solutions that generate such json user records from ldap info.

PAM is inherently per-session. And I am pretty sure resource management should be per-user. Hence I think that doing resource mgmt via more pam props is not really going to deliver what is needed in the long run. the userdb json stuff inhrently puts metadata in the *user* record, and that's what makes it so useful. the data is directly associated with the entity it should be associated with: the user...

**Comment by Werkov** [comment]
> the userdb stuff is separate from homed to some degree.
I see (my previous statement was caused by lack of familiarity), userdb
is the API,...
mean it'd need to pass the information through userdb API.

> It's a matter of hacking up a trivial varlink/json service that
> provides them on request.
... so for plain files backed database, there'd troubles storing the
slice information. Hence I think there is a merit to primary GID based
policy. (And I'm positive about having Slice= available through userdb
API.)

> PAM is inherently per-session. And I am pretty sure resource
> management should be per-user.
Would anything break if session granularity was allowed (I thought of
`loginctl terminate-user` but that's based on sessions anyway)?
(Certainly, admin should be aware how they configure session
distributions of a single user.)

**Comment by poettering** [comment]
>  the userdb stuff is separate from homed to some degree.
> I see (my previous statement was caused by lack of familiarity), userdb is the API,... mean it'd need to pass the information through userdb API.

Correct. But that's dead-easy. Bind a socket in /run/systemd/userdb, and reply to two varlink requests with a simple json object.

> > It's a matter of hacking up a trivial varlink/json service that provides them on request.
> ... so for plain files backed database, there'd troubles storing the slice information. Hence I think there is a merit to primary GID based policy. (And I'm positive about having Slice= available through userdb API.)

It's a just a few lines in python to write a service that responds to requests via the varlink iface and serves json files stored in /var/lib/jsonuserdb/$uid.json as user records.

> PAM is inherently per-session. And I am pretty sure resource management should be per-user.
> Would anything break if session granularity was allowed (I thought of `loginctl terminate-user` but that's based on sessions anyway)? (Certainly, admin should be aware how they configure session distributions of a single user.)

Well, it already is allowed, for example via pam module parameters, but I am not convinced the usecase is particularly strong for that. I mean, the trust boundary is the UID, and it shouldn't matter how the user internally distributes its resources, what matters that the user as a whole gets only a certain amount of resources...

**Pull request closed without merging**
