### PR TITLE
shutdown: don't try to unmount NFS mount points

### PR DESCRIPTION
**Pull request by d-hatayama**
We should not call mount() and umount() to NFS mount points in this phase
because it could result in system hang during shutdown when the NFS server
doesn't respond.

Here is a log in the situation where system hang occurred during umount():

    [  OK  ] Stopped target Remote File Systems.
             Unmounting /mnt...
    [  *** ] A stop job is running for /mnt (3min 17s / 4min 30s)[  283.978108] nfs: server 192.168.122.1 not responding, timed out
    [    **] A stop job is running for /mnt (6min 18s / 7min 30s)[  464.459012] nfs: server 192.168.122.1 not responding, timed out
    [   ***] A stop job is running for /mnt (6min 24s / 7min 30s)[  469.835026] nfs: server 192.168.122.1 not responding, timed out
    [   ***] A stop job is running for /mnt (9min 19s / 10min 31s)[  644.939855] nfs: server 192.168.122.1 not responding, timed out
    [**    ] A stop job is running for /mnt (9min 24s / 10min 31s)[  650.059766] nfs: server 192.168.122.1 not responding, timed out
    [***   ] A stop job is running for /mnt (9min 29s / 10min 31s)[  655.691913] nfs: server 192.168.122.1 not responding, timed out
    [***   ] A stop job is running for /mnt (12min 19s / 13min 31s)[  825.420713] nfs: server 192.168.122.1 not responding, timed out
    [   ***] A stop job is running for /mnt (12min 30s / 13min 31s)[  835.916823] nfs: server 192.168.122.1 not responding, timed out
    [    **] A stop job is running for /mnt (12min 35s / 13min 31s)[  841.548795] nfs: server 192.168.122.1 not responding, timed out
    [**    ] A stop job is running for /mnt (15min 20s / 16min 32s)[ 1005.901645] nfs: server 192.168.122.1 not responding, timed out
    [   ***] A stop job is running for /mnt (15min 25s / 16min 32s)[ 1011.021714] nfs: server 192.168.122.1 not responding, timed out
    [***   ] A stop job is running for /mnt (15min 35s / 16min 32s)[ 1021.773581] nfs: server 192.168.122.1 not responding, timed out
    [*     ] A stop job is running for /mnt (15min 41s / 16min 32s)[ 1027.405678] nfs: server 192.168.122.1 not responding, timed out
    [  *** ] A stop job is running for /mnt (18min 20s / 19min 32s)[ 1186.574393] nfs: server 192.168.122.1 not responding, timed out
    [    **] A stop job is running for /mnt (18min 32s / 19min 32s)[ 1198.606480] nfs: server 192.168.122.1 not responding, timed out
    [***   ] A stop job is running for /mnt (18min 44s / 19min 32s)[ 1210.638687] nfs: server 192.168.122.1 not responding, timed out
    [     *] A stop job is running for /mnt (21min 21s / 22min 33s)[ 1367.055361] nfs: server 192.168.122.1 not responding, timed out
    [   ***] A stop job is running for /mnt (21min 36s / 22min 33s)[ 1382.287429] nfs: server 192.168.122.1 not responding, timed out
    [ 1382.288342] nfs: server 192.168.122.1 not responding, timed out
    [  *** ] A stop job is running for /mnt (24min 21s / 25min 33s)[ 1547.600168] nfs: server 192.168.122.1 not responding, timed out
    [ 1547.601206] nfs: server 192.168.122.1 not responding, timed out
    [    **] A stop job is running for /mnt (25min 33s / 25min 33s)[ 1619.792522] nfs: server 192.168.122.1 not responding, timed out
    [ 1619.801782] nfs: server 192.168.122.1 not responding, timed out
    [     *] A stop job is running for /mnt (27min 25s / 28min 34s)[ 1731.153062] nfs: server 192.168.122.1 not responding, timed out
    [    **] A stop job is running for /mnt (28min 34s / 30min 4s)[ 1800.337312] nfs: server 192.168.122.1 not responding, timed out
    [***   ] A stop job is running for /mnt (28min 46s / 30min 4s)[ 1812.369591] nfs: server 192.168.122.1 not responding, timed out
    [ TIME ] Timed out starting Reboot.
    [ !!  ] Forcibly rebooting as result of failure.
    [ 1886.116465] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
    [ 1886.123469] systemd-journald[663]: Received SIGTERM from PID 1 (systemd-shutdow).
    [ 1886.146434] kauditd_printk_skb: 174 callbacks suppressed
    [ 1886.149205] audit: type=1305 audit(1491141220.732:181): audit_pid=0 old=864 auid=4294967295 ses=4294967295 subj=system_u:system_r:auditd_t:s0 res=1
    [ 1976.133673] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
    [ 1976.140952] systemd-shutdown[1]: Process 2800 (plymouthd) has been marked to be excluded from killing. It is running from the root file system, and thus likely to block re-mounting of the root file system to read-only. Please consider moving it into an initrd file system instead.
    [ 1976.151666] systemd-shutdown[1]: Sending SIGKILL to PID 2893 (umount).
    [ 1976.155682] systemd-shutdown[1]: Unmounting file systems.
    [ 1976.160518] systemd-shutdown[1]: Remounting '/mnt' read-only with options 'vers=4.2,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.122.22,local_lock=none,addr=192.168.122.1'.
    [ 1976.168503] systemd-shutdown[1]: Unmounting /mnt.
    [ 1980.818269] nfs: server 192.168.122.1 not responding, timed out
    [ 1980.821576] nfs: server 192.168.122.1 not responding, timed out
    [ 2005.074542] nfs: server 192.168.122.1 not responding, timed out

Unlike the expectation by the commit 0c08f5cde749bd2818475e487109cd0d413452df,
this would unfortunately mean that there's no reliability of NFS returning
EBUSY to umount() in this case.

Although there's no log left, I saw system hang during
mount(MS_REMOUNT|MS_RDONLY), too.

### CODE REVIEW

**Comment by poettering** [comment]
I am not convinced this is a good idea. An NFS mount might obstruct a non-NFS mount, hence we really need to unmount the NFS mount first, to get all file systems we possibly can get into a clean state into a clean state. 

I think it would be better to introduce a form of "mount() with a time boundary", i.e. a bit of code that forks of a tiny thread that invokes mount() on behalf of the caller, but is killed after a specific timeout (or, if the kill doesn't work is left hanging detached). Then, let's invoke mount() in the shutdown logic this way, in all cases (not just for NFS) and specify a short timeout (let's say 30s or so).

**Comment by d-hatayama** [comment]
But the "umount() with a time boundary" has already been done in normal shutdown sequence when stopping the corresponding mount units. I think that the fact that the mount points still being left in this phase indicates that umount() didn't work well. Do you think doing the same thing in this phase again still makes sense?

**Comment by d-hatayama** [comment]
I think I understand. I overlooked you want to deal with not only NFS mount points but also any other types of mount points.

**Comment by poettering** [comment]
> But the "umount() with a time boundary" has already been done in normal shutdown sequence when stopping the corresponding mount units. I think that the fact that the mount points still being left in this phase indicates that umount() didn't work well. Do you think doing the same thing in this phase again still makes sense?

Well, it's not really the same thing. It's the safety-net, the cleaning up the left-overs of the first phase, in a more "brutal" way. If you so will it is in its entirety the same thing it already did before. But that's how it is with "cleaning up" after a non-effective first attempt: it might run into the same pitfalls again.

That said, the timeouts can definitely be shorter than in the first attempt. There's no point in waiting for so long again.

I think the code could be really simple for doing such a time-bounded mount. Something like this: 

```c
struct mount_params {
        const char *source;
        const char *target;
        const char *fstype;
        unsigned long flags;
        const void *data;
        int done_fd;
};

static void *mount_thread(void *p) {
        const struct mount_params *mp = p;
        struct mount_params copy;

        /* Copy all parameters, so that we don't reference our caller's stack anymore */
        copy.source = strdupa(mp->source);
        copy.target = strdupa(mp->target);
        copy.fstype = strdupa(mp->fstype);
        copy.flags = mp->flags;
        copy.data = strdupa(mp->data);

        /* Signal that we copied the structure */
        safe_close(mp->done_fd);

        /* And now, simply invoke the syscall */
        if (mount(copy.source, copy.target, copy.fstype, copy.flags, copy.data) < 0)
                return INT_TO_PTR(errno);

        return NULL;
}

static int async_mount(const char *source, const char *target, const char *fstype, unsigned long flags, const void *data, usec_t timeout) {
        struct mount_params mp = {
                .source = source,
                .target = target,
                .fstype = fstype,
                .flags = flags,
                .data = data,
        };
        struct pipe_fd[2] = { -1, -1};
        pthread_t t;
        struct timespec ts;
        uint8_t x;

        if (pipe2(pipe_fd, O_CLOEXEC) < 0)
                return -errno;

        mp.done_fd = pipe_fd[1];

        r = pthread_create(&t, NULL, async_mount, &mp);
        if (r != 0) {
                safe_close_pair(pipe_fd);
                return -r;
        }

        /* Wait until the thread let us know it successfully copied the structure's data. It will close its side of the pipe in that case, which signals us an EOF, which means read() returns 0 */
        if (read(pipe_fd[0], &x, &sizeof(x)) < 0) {
                r = -errno;
                safe_close(pipe_fd[0]);
                (void) pthread_join(t); 
                return r;
         }

         safe_close(pipe_fd[0]);

         timespec_store(&ts, timeout);
         r = pthread_timedjoin_np(t, &ret, &ts);
         if (r != 0) {
                 (void) pthread_detach(t);
                 return -r;
          }

         return -PTR_TO_INT(ret);
}
```

Or someting like that. (The complexity of the pipe is only necessary, so that the thread can let the caller know when it copied all data it needs from the callers stack. If we wouldn't do that, and for some reason the thread doesn't manage to copy things before the parent's timeout runs out, then it might end up accessing invalidated memory. It's a racy, a tiny one, but still a race we can fix via this pipe).

Hope that makes sense?

**Comment by Werkov** [comment]
I have a concrete example when the second phase (systemd-shutdown) hangs, so IIUC this async wrapper would need to be called also there, right?

Precond: A manual loop mount of a file from NFS share.

Shutdown sequence:

- `loop.mount` is transitively `Before=nfs.mount` (if the manual loop mount was done with `_netdev`, they would only be concurrent),
- `nfs.mount` unmount fails because it's busy (with the `loop.mount`),
- network goes down,
- `loop.mount` unmount hangs (here 83897d5470190a9818df50026cf38cd97114f77d should help),
- systemd-shutdown fails to RO remount the lingering `nfs.mount`

> Sending SIGTERM to remaining processes...
Sending SIGKILL to remaining processes...
Sending SIGKILL to PID 2840 (umount).
Unmounting file systems.
Remounting '/nfs' read-only with options 'vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.112.61,mountvers=3,mountport=20048,mountproto=udp,local_lock=none,addr=10.100.112.61'.

CC: @neilbrown

**Comment by neilbrown** [comment]
making systemd-shutdown more robust  would certainly be a good idea - possubly by using MNT_DETACH, then sync() in a child. But I think this particular problem should be addressed by teaching systemd about some implicit dependencies.
When a loop device appears, it needs to create an implicit RequiresMountsFor for the backing file.  This should ensure that the loop-mounted filesystem will be unmounted before the nfs filesystem.
I hope to  turn this idea into a patch soon.

**Comment by poettering** [comment]
Let's close this PR here. There's now #6598 which implements some of the ideas proposed here, with the same goal as this PR, hence I figure we can close this one.

**Pull request closed without merging**
