### PR TITLE
meson: bump minimum required version to 0.44

### PR DESCRIPTION
**Pull request by yuwata**
This is a subset of #8876.

Below is the current meson version of each distribution.
\===============
Ubuntu artful (EOL date: July 2018): [0.42.1](https://packages.ubuntu.com/artful/meson)
Ubuntu bionic (EOL date: April 2023): [0.45.1](https://packages.ubuntu.com/bionic/meson)
Ubuntu cosmic: [0.46.0](https://packages.ubuntu.com/cosmic/meson)

Fedora 27,28,rawhide: [0.46.0](https://koji.fedoraproject.org/koji/packageinfo?packageID=19835)

RHEL 7 (EOL: Q4 of 2019): [0.44.0 (backported package)](https://github.com/facebookincubator/rpm-backports/tree/master/rpms/meson)

Debian stretch-backports: [0.45.1](https://packages.debian.org/source/stretch-backports/meson)
Debian buster: [0.45.1](https://packages.debian.org/buster/meson)
Debian sid: [0.46.0](https://packages.debian.org/sid/meson)

### CODE REVIEW

**Comment by yuwata** [comment]
@davide125 This does not request python-3.5. So, I hope this works fine on RHEL7.

**Comment by keszybz** [comment]
I'd prefer to wait with this until artful is EOL.

**Comment by davide125** [comment]
Thanks @yuwata, this should be fine. We're actually [using 0.44 already](https://github.com/facebookincubator/rpm-backports/tree/master/rpms/meson) for our CentOS 7 backport builds.

**Comment by mbiebl** [comment]
Fwiw, no objections from the Debian side to bump the b-dep to 0.44. We have a fairly recent version of meson in stretch-backports (0.45.1 atm): https://packages.debian.org/source/stretch-backports/meson

**Comment by yuwata** [comment]
@davide125 and @mbiebl Thank you for the comments. I've removed 'postponed' tag.

**Comment by martinpitt** [comment]
Actually no, semaphore pulls ninja and meson from upstream. I bumped the `pip` install from 0.42.1 to 0.46.0 and restarted the semaphore test, let's see how that goes.

**Comment by martinpitt** [comment]
I lowered meson back to 0.44.0, as 0.46.0 requires Python 3.5 which isn't available on 14.04 yet. This passed now. :smile:

**Comment by martinpitt** [comment]
Two [s390x test](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/s390x/s/systemd-upstream/20180514_091950_ea53d@/log.gz) failed:

```
======================================================================
FAIL: test_no_failed (__main__.ServicesTest)
No failed units
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.vrqB6n/build.R4T/debian/debian/tests/boot-and-services", line 60, in test_no_failed
    self.assertEqual(failed, [])
AssertionError: Lists differ: ['cpi.service loaded failed failed Apply Control Program Identification (CPI)'] != []
```

This smells like an actual bug in bionic, something for @xnox ? I pushed a [patch](https://salsa.debian.org/systemd-team/systemd/commit/50e860fd3e54bf823b57f4b88aeffb7362212152) to blacklist this for now.

The other failure is
```
autopkgtest [09:19:20]: test boot-smoke: [-----------------------
reboot #0
bash: line 1: 27513 Killed                  /tmp/autopkgtest.vrqB6n/build.R4T/debian/debian/tests/boot-smoke 2> >(tee -a /tmp/autopkgtest.vrqB6n/boot-smoke-stderr >&2) > >(tee -a /tmp/autopkgtest.vrqB6n/boot-smoke-stdout)
autopkgtest [09:19:21]: test process requested reboot with marker 1
Connection to 10.44.45.227 closed by remote host.
checking for failed unmounts for user systemd
checking for connection timeouts
May 14 09:17:26 autopkgtest systemd-udevd[1220]: Error resolving group 'render': Connection timed out
May 14 09:17:51 autopkgtest systemd-udevd[1220]: Error resolving group 'kvm': Connection timed out
```

This is either a bad error message, or libnss-systemd trying to talk to the dynamic resolver and timing out? I'll re-run the test to get a second log for comparison.

i386 succeeded, so I updated that webhook to move to bionic. amd64 is still running.

**Comment by martinpitt** [comment]
[amd64 test](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/amd64/s/systemd-upstream/20180514_094621_ea53d@/log.gz) failed in the upstream tests (`TEST-16-EXTEND-TIMEOUT`):
```
[[0;32m  OK  [0m] Started Testsuite: Success Stop (EX…OG_USEC however < TimeoutStopSec).
[[0;1;31mFAILED[0m] Failed to start Testsuite: Success …G_USEC however < TimeoutStartSec).
See 'systemctl status testsuite-success-start.service' for details.
[[0;32m  OK  [0m] Started Testsuite: EXTEND_TIMEOUT_U… - extend timeout on all services.
[[0;1;31mFAILED[0m] Failed to start Testsuite: Fail Sta…ient time after TimeoutStartSec.).
See 'systemctl status testsuite-fail-start.service' for details.

May 14 09:36:48 systemd-testsuite systemd[1]: testsuite-success-start.service: Start operation timed out. Terminating.
May 14 09:36:48 systemd-testsuite systemd[1]: testsuite-success-start.service: Failed with result 'timeout'.
May 14 09:36:49 systemd-testsuite systemd[1]: Failed to start Testsuite: Success Start (EXTEND_TIMEOUT_USEC > WATCHDOG_USEC however < TimeoutStartSec).
May 14 09:36:49 systemd-testsuite systemd[1]: testsuite-fail-start.service: Start operation timed out. Terminating.
May 14 09:36:50 systemd-testsuite systemd[1]: testsuite-fail-start.service: Failed with result 'timeout'.
May 14 09:36:50 systemd-testsuite systemd[1]: Failed to start Testsuite: Fail Start (EXTEND_TIMEOUT_USEC Didn't occur in sufficient time after TimeoutStartSec.).
May 14 09:36:57 systemd-testsuite systemd[1]: testsuite-fail-runtime.service: Service reached runtime time limit. Stopping.
May 14 09:36:57 systemd-testsuite systemd[1]: testsuite-fail-stop.service: State 'stop-sigterm' timed out. Killing.
May 14 09:36:57 systemd-testsuite systemd[1]: testsuite-fail-stop.service: Main process exited, code=killed, status=9/KILL
May 14 09:36:57 systemd-testsuite systemd[1]: testsuite-fail-runtime.service: Failed with result 'timeout'.
May 14 09:36:57 systemd-testsuite systemd[1]: testsuite-fail-stop.service: Failed with result 'timeout'.
May 14 09:37:50 systemd-testsuite systemd[1]: testsuite.service: Failed with result 'exit-code'.
May 14 09:37:50 systemd-testsuite systemd[1]: Failed to start Testsuite: Assess all other testsuite-*.services worked as expected.
```

This sounds like a flake, and not closely related to a different meson or OS version, so I'll retry this one as well. I haven't followed these tests recently, is this a common one? @keszybz

**Comment by martinpitt** [comment]
Nope, same [TEST-16-EXTEND-TIMEOUT failure](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/amd64/s/systemd-upstream/20180514_110823_ea53d@/log.gz) as last time.

**Comment by keszybz** [comment]
> is this a common one?

No. I don't think I've seen it before.

**Comment by yuwata** [comment]
artful-amd64 in #8955 seems to fail the [same error](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-artful-pitti-systemd-semaphore/artful/amd64/s/systemd-upstream/20180510_165756_9f742@/log.gz).
```
May 10 16:25:08 systemd-testsuite systemd[1]: testsuite-success-start.service: Start operation timed out. Terminating.
May 10 16:25:09 systemd-testsuite systemd[1]: testsuite-success-start.service: Failed with result 'timeout'.
May 10 16:25:09 systemd-testsuite systemd[1]: Failed to start Testsuite: Success Start (EXTEND_TIMEOUT_USEC > WATCHDOG_USEC however < TimeoutStartSec).
May 10 16:25:10 systemd-testsuite systemd[1]: testsuite-fail-start.service: Start operation timed out. Terminating.
May 10 16:25:10 systemd-testsuite systemd[1]: testsuite-fail-start.service: Failed with result 'timeout'.
May 10 16:25:10 systemd-testsuite systemd[1]: Failed to start Testsuite: Fail Start (EXTEND_TIMEOUT_USEC Didn't occur in sufficient time after TimeoutStartSec.).
May 10 16:25:13 systemd-testsuite systemd[1]: testsuite-success-runtime.service: Service reached runtime time limit. Stopping.
May 10 16:25:14 systemd-testsuite systemd[1]: testsuite-success-runtime.service: Failed with result 'timeout'.
May 10 16:25:18 systemd-testsuite systemd[1]: testsuite-fail-runtime.service: Service reached runtime time limit. Stopping.
May 10 16:25:18 systemd-testsuite systemd[1]: testsuite-fail-runtime.service: Failed with result 'timeout'.
May 10 16:25:21 systemd-testsuite systemd[1]: testsuite-fail-stop.service: State 'stop-sigterm' timed out. Killing.
May 10 16:25:21 systemd-testsuite systemd[1]: testsuite-fail-stop.service: Main process exited, code=killed, status=9/KILL
May 10 16:25:22 systemd-testsuite systemd[1]: testsuite-fail-stop.service: Failed with result 'timeout'.
May 10 16:26:19 systemd-testsuite systemd[1]: testsuite.service: Failed with result 'exit-code'.
May 10 16:26:19 systemd-testsuite systemd[1]: Failed to start Testsuite: Assess all other testsuite-*.services worked as expected.
```
So, the failure is not caused by this PR.

**Comment by martinpitt** [comment]
Indeed, PR #8984 [fails for the same reason](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-artful-pitti-systemd-semaphore/artful/amd64/s/systemd-upstream/20180515_003713_1b139@/log.gz), so this isn't a regression between 17.10 and 18.04. I've flipped the amd64 test to bionic, too.

**Comment by martinpitt** [comment]
[s390x](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/s390x/s/systemd-upstream/20180515_062727_ea53d@/log.gz) succeeded as well, so I flipped the webhook.

Now all our tests use a current meson, so this is unblocked.

**Comment by yuwata** [comment]
@martinpitt Thanks a lot!

**Comment by keszybz** [comment]
Something is wrong with amd64, but it seems unrelated to this PR. Let's merge.

**Comment by martinpitt** [comment]
@kesbyz: "something is wrong" - I retried the test about an hour ago, to see if the `EXTEND_TIMEOUT_USEC` test would succeed after a few retries. But as said above, this isn't related to the artful → bionic upgrade, it's just a flaky test.

**Pull request merged**
