### PR TITLE
mount-setup.c: fix handling of symlink Smack labelling in cgroup setup

### PR DESCRIPTION
**Pull request by pohly**
The code introduced in f8c1a81c51 (= systemd 227) failed for me with:
  Failed to copy smack label from net_cls to /sys/fs/cgroup/net_cls: No such file or directory

There is no need for a symlink in this case because source and target
are identical. The symlink() call is allowed to fail when the target
already exists. When that happens, copying the Smack label must be
skipped.

But the code also failed when there is a symlink, like "cpu ->
cpu,cpuacct", because mac_smack_copy() got called with
src="cpu,cpuacct" which fails to find the entry because the current
directory is not inside /sys/fs/cgroup. The absolute path to the existing
entry must be used instead.

Tested based on systemd v228, built as part of OpenEmbedded master, using
meta-intel-iot-security (https://github.com/01org/meta-intel-iot-security).
The boot failure before the fix can be seen here:
https://travis-ci.org/01org/meta-intel-iot-security/jobs/97893904

### CODE REVIEW

**Comment by pohly** [comment]
I'm not sure how this code worked before. I've not tried 227. Perhaps systemd temporarily changed the current working directory? Then the code would just have read the Smack label of "net_cls" and written it back on the same entry.

**Comment by zonque** [comment]
This PR is currently based on v228. However, some commits went in after that which are needed in order to make the qemu based test suite work. Could you please rebase this PR to current master? A new build with Semaphore is then automatically triggered.

**Comment by pohly** [comment]
Rebased (automatically, with no conflicts) onto current master. Semaphore test run is pending.

@again4you if you are still around, can you review this? You wrote the original code.

**Comment by pohly** [comment]
Pushed revised commit with error handling for strappend().

**Pull request merged**
