### PR TITLE
hwdb: Add Logitech G100s Optical Gaming Mouse

### PR DESCRIPTION
**Pull request by genpfault**
Add an entry for the Logitech G100s to `70-mouse.hwdb`.

### CODE REVIEW

**Comment by whot** [comment]
To verify: this is the configuration it ships with, not otherwise modified?

**Comment by phomes** [comment]
I have a G100s too and can confirm that those are the default settings on the mouse.

**Comment by whot** [comment]
thanks, that's all I needed :)

**Pull request merged**
