### PR TITLE
man: add missing cleanup-age to tmpfiles.d quickref

### LINKED ISSUE #23285: tmpfiles.d(5) quickref lacks age for v, q, Q, C, x and X
**systemd version the issue has been seen with**
 > systemd v249 and v251-rc2

**Used distribution**
 > Fedora 35

**Expected behaviour you didn't see**
 > Following lines in tmpfiles.d(5) will have cleanup-age (or ignore-age)
```
       v     /subvolume-or-directory/to/create        mode user group -           -
       q     /subvolume-or-directory/to/create        mode user group -           -
       Q     /subvolume-or-directory/to/create        mode user group -           -
       C     /target/to/create                        -    -    -     -           /source/to/copy
       x     /path-or-glob/to/ignore/recursively      -    -    -     -           -
       X     /path-or-glob/to/ignore                  -    -    -     -           -
```

**Additional info**
 > In tmpfiles.d(5), Type v, q, Q, and C descriptions say nothing about age parameter, it's hard to notice that age field is available in these types.

### PR DESCRIPTION
**Pull request by kmoriwak**
Fixes #23285

### CODE REVIEW

**Review by yuwata — APPROVED** [review]
Thank you. LGTM.

**Comment by keszybz** [comment]
This change is good, but please also mention this in the descriptions of the options.
(This is reference documentation, so one should be able to look at the description of the option and get a full understanding of the option or pointers to other parts of the documentation.)
For other options we say "Contents of the directories are subject to time based cleanup if the age argument is specified.". Please do the same for those.

**Comment by kmoriwak** [comment]
I checked descriptions of types which can take age argument.
 - d, e, x, X - have description for age.
 - D, v, q, Q - "Similar to d", "same way as d", "identical to d", "same as v" implys they will treat age
 - C - missing description about age

I added "Contents of the directories are subject to time based cleanup if the age argument is specified." to C type description.

**Comment by keszybz** [comment]
OK. I would have preferred maybe a bit more verbosity, but the current form is a clear improvement, let's merge it.

**Pull request merged**
