### PR TITLE
shutdown: several fixlets

### LINKED ISSUE #28645: Failed to move /run/initramfs to /
### systemd version the issue has been seen with

254-1-arch

### Used distribution

Archlinux

### Linux kernel version used

6.4.7

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

I want to see my shutdown clean and fast

### Unexpected behaviour you saw

While shutting down / reboot archlinux receiving errors but system reboot correctly.

systemd-shutdown: Failed to move /run/initramfs to /: invalid argument

systemd-shutdown: Failed to switch root to "run/initramfs" invalid argument

### Steps to reproduce the problem

Shutdown system / reboot system

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes #28645.

### CODE REVIEW

**Comment by bluca** [comment]
uhm doesn't this undo the fix that I did before the release? Where stuff under /run was lost in the transition to initrd?

**Comment by yuwata** [comment]
IIUC, the previous issue is on initramfs -> host transition on boot. But this is for shutting down, and host -> initramfs transition.

**Review by bluca — APPROVED** [review]
Ok, let's give it a shot

**Comment by yuwata** [comment]
I'd like to wait for reporter feedback for a while, as I have not tested it.

**Comment by mrc0mmand** [comment]
Nope, still seeing the error (+ an extra debug message just to confirm I run the correct binary):

image

**Comment by mrc0mmand** [comment]
> @mrc0mmand Could you test again?

*The computer* is still unhappy:
image

**Comment by yuwata** [comment]
@mrc0mmand Does v253 work fine?

**Comment by Freyon77** [comment]
> @mrc0mmand Does v253 work fine?

Yep

**Comment by mrc0mmand** [comment]
> @mrc0mmand Does v253 work fine?

It seems so, I don't see any errors even with some debug output sprinkled around:
image

**Comment by mrc0mmand** [comment]
And just a note: on v253 it seems to go through the `pivot_root()` branch, but it works even if I force it to use `MS_MOVE` instead:
image

**Comment by yuwata** [comment]
@mrc0mmand @Freyon77 Could you test again?

**Comment by mrc0mmand** [comment]
> @mrc0mmand @Freyon77 Could you test again?

This looks promising:

```
[  OK  ] Reached target shutdown.target.
[  OK  ] Reached target final.target.
[  OK  ] Finished systemd-halt.service.
[  OK  ] Reached target halt.target.
[  118.668517] reboot: System halted
```

**Comment by yuwata** [comment]
Thank you!

**Comment by mrc0mmand** [comment]
And it looks like both paths now work as expected:

```
[  OK  ] Reached target final.target.
[  OK  ] Finished systemd-halt.service.
[  OK  ] Reached target halt.target.
[  136.920177] systemd-shutdown[1]: switch_root: about to pivot_root()
[  136.920863] systemd-shutdown[1]: switch_root: pivot_root() succeeded
[  137.005165] reboot: System halted
```

```
[  OK  ] Reached target final.target.
[  OK  ] Finished systemd-halt.service.
[  OK  ] Reached target halt.target.
[   82.735416] systemd-shutdown[1]: switch_root: about to move '.' to '/'
[   82.735798] systemd-shutdown[1]: switch_root: about to chroot into '.'
[   82.736169] systemd-shutdown[1]: switch_root: about to chdir into '.'
[   82.736542] systemd-shutdown[1]: switch_root: all done!
[   82.752997] reboot: System halted
```

**Comment by Freyon77** [comment]
I don't have the skills to verify that the fix works. Therefore, I will rely here on the statement above.
Anyway, thank you for taking the time to write the code and understanding the problem.

**Comment by nl6720** [comment]
Seems to fix the issue for me. :+1:

**Comment by yuwata** [comment]
@mrc0mmand Could you test again?

**Comment by mrc0mmand** [comment]
> @mrc0mmand Could you test again?

Still looks good!

```
[  OK  ] Reached target shutdown.target.
[  OK  ] Reached target final.target.
[  OK  ] Finished systemd-halt.service.
[  OK  ] Reached target halt.target.
[39099.296592] systemd-shutdown[1]: switch_root: about to pivot_root()
[39099.297278] systemd-shutdown[1]: switch_root: pivot_root() succeeded
[39099.394763] reboot: System halted
```

```
[  OK  ] Reached target shutdown.target.
[  OK  ] Reached target final.target.
[  OK  ] Finished systemd-halt.service.
[  OK  ] Reached target halt.target.
[  208.428841] systemd-shutdown[1]: Pivoting root file system failed, moving mounts instead: Operation not permitted
[  208.429875] systemd-shutdown[1]: switch_root: about to move '.' to '/'
[  208.430518] systemd-shutdown[1]: switch_root: about to chroot() into '.'
[  208.431182] systemd-shutdown[1]: switch_root: about to chdir() to '.'
[  208.431922] systemd-shutdown[1]: switch_root: all done!
[  208.458289] reboot: System halted
```

**Comment by Freyon77** [comment]
What about pivoting root file system failed?

**Comment by mrc0mmand** [comment]
> @mrc0mmand what about pivoting root file system failed?

That's just me setting r to -1 to test the fallback branch, probably should've dropped that from the output.

**Comment by yuwata** [comment]
Thank you for testing so many times!

@bluca Could you take a look again?

**Review by bluca — APPROVED** [review]

**Comment by keszybz** [comment]
I queued up all three commits for v254.1.

**Comment by poettering** [comment]
So I am pretty sure the 2nd commit is not right. It's not load-bearing for the bugfix this PR is supposed to be, is it?

I prepped #28793 that reverts that part. Please take a look for an explanation.

**Pull request merged**
