### PR TITLE
load-fragment: do not create empty array

### PR DESCRIPTION
**Pull request by yuwata**
C.f. 8249bb728db6c2abaf12575d661b52571bdc1ab1 and #6746.

### CODE REVIEW

**Comment by keszybz** [comment]
Also c.f. 4589f5bb0a973e9a41be93de06c87072cea4dfb9.

**Comment by keszybz** [comment]
`config_parse_unit_path_strv_printf` is used for `Socket.symlinks`, and all users should not care:
```console
$ git grep -e '->symlinks\b' src/
src/core/socket.c:        strv_free(s->symlinks);
src/core/socket.c:        if (!strv_isempty(s->symlinks) && !socket_find_symlink_target(s)) {
src/core/socket.c:                STRV_FOREACH(i, s->symlinks)
src/core/socket.c:        STRV_FOREACH(i, s->symlinks) {
```

`config_parse_user_group_strv` is only used for `exec_context.supplementary_groups`:
```console
$ git grep -e '->supplementary_groups\b' src/
src/core/dbus-execute.c:                                c->supplementary_groups = strv_free(c->supplementary_groups);
src/core/dbus-execute.c:                                r = strv_extend_strv(&c->supplementary_groups, l, true);
src/core/dbus-execute.c:                                joined = strv_join(c->supplementary_groups, " ");
src/core/execute.c:        if (!c->supplementary_groups)
src/core/execute.c:        STRV_FOREACH(i, c->supplementary_groups) {
src/core/execute.c:        if (context->supplementary_groups) {
src/core/execute.c:        c->supplementary_groups = strv_free(c->supplementary_groups);
src/core/execute.c:        if (strv_length(c->supplementary_groups) > 0) {
src/core/execute.c:                strv_fprintf(f, c->supplementary_groups);
```
But here we check if the array exists, not just with `strv_isempty`.

**Comment by keszybz** [comment]
`supplementary_groups` also seems to be OK, but it's wasn't obvious from the code. I force-pushed to your branch with another cleanup commit on top. PTAL.

**Comment by yuwata** [comment]
Thanks. lgtm

**Pull request merged**
