### PR TITLE
networkd: add support for Macvtap

### PR DESCRIPTION
**Pull request by ssahani**
```
#cat macvtap.netdev
[NetDev]
Name=macvtap-test
Kind=macvtap

[MACVTAP]
Mode = private

#cat macvtap.network
[Match]
Name=enp0s25

[Network]
MACVTAP=macvtap-test

# ip link
8: macvtap-test@enp0s25: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 500
    link/ether ee:7a:3a:7b:fd:e2 brd ff:ff:ff:ff:ff:ff
```

### CODE REVIEW

**Comment by poettering** [comment]
Looks good to me, @teg?

**Comment by zonque** [comment]
Out of curiosity: do you have real world use-cases for all these additions? Which setups do you test this in?

**Comment by johannbg** [comment]
@zonque macvlan/tap is virtualized bridged networking used by hypervisors and containers based on the the tun/tap interface hence it follows the plethora of real world use cases that belongs to those ( kvm/qemu/docker/lxc yata yata ) 

The benefits of using it over the other solutions is that it does not require any interruption to your primary network interface so you basically get what the performance of the ovs but at a lower cpu price

I think it's safe to assume he has tested this with host+nspawned containers . . .

**Comment by ssahani** [comment]
@johannbg has answered it . 

http://virt.kernelnewbies.org/MacVTap
it also does create a tap interface under /dev/
on my machine it's

ls /dev/tap*
/dev/tap11  /dev/tap13

**Comment by fishface60** [comment]
@ssahani am I wrong in thinking that macvtap is mostly the same to macvlan (which is already in) but that it also adds a /dev/tap device then?

I understood the reason that QEMU/KVM used macvtap instead of macvlan is that the VM program historically worked by using a different kind of tap device, so it made sense to add a bridging type that behaved the same way.

Containers don't need the tap device, I'm just wondering how macvtaps configured in networkd are intended to be used, since virt-manager creates its own macvtap devices.

**Comment by ssahani** [comment]
VM need a tap like interface.
There are two ways: either we can pass directly macvtap fd to qemu-kvm command line
or libvirt creates macvtap and pass on file fd to Qemu.
So we create it via networkd which is persistent . Qemu or any user space  process can use it.

**Pull request merged**
