### PR TITLE
Nss link less 2

### PR DESCRIPTION
**Pull request by keszybz**
Replacement for #2006 rebased on latest git.

### CODE REVIEW

**Comment by dvdhrm** [comment]
See #2008 for a comment from @martinpitt. This seems to be solved by enabling `--as-needed`.

**Comment by fsateler** [comment]
@dvdhrm the debian machinery patches lt-main.sh for that to work correctly. Unfortunately, libtool reordering of flags results in --as-needed not being called at the right place.

http://sources.debian.net/src/dh-autoreconf/10/ltmain-as-needed.diff/

**Comment by keszybz** [comment]
It would be great to add `--as-needed` into the right places / or fix it to work. But this is another independent step. Since the nss modules do not currently require anything from libshared, in the spirit of keeping them lean, it seems better to link them only to libsystemd(-internal).

An additional advantage is that it makes the build slightly faster, allows for better more parallelization,  and improves developer builds without `--as-needed`.

**Comment by keszybz** [comment]
@dvdhrm> @keszybz, did you verify that --gc-sections and --as-needed are really used?

If you check libnss-\* modules from systemd-libs in Fedora, they link to more libraries than they should. So this issue is present also in "release" builds.

**Comment by martinpitt** [comment]
> Since the nss modules do not currently require anything from libshared, in the spirit of keeping them lean, it seems better to link them only to libsystemd(-internal).

For the record, with my comment I didn't want to say that linking less was bad. I think that's a good idea still, independently of using `--as-needed`. This PR will make the build fail right away when some change inadvertently starts using a symbol from the full libsystemd, as we really want to avoid that for libnss*. `--as-needed` doesn't help there, as it would just silently add the dozen new libraries without raising a red flag.

So big :+1 from me, thanks!

**Comment by poettering** [comment]
I think we shouldn't fix bugs in systemd that are actually in libtool?

We decided to rely on gc-sections and as-needed for making our builds minimal, instead of splitting everything up into a multitude of separate build units. I am not convinced we should depart from that in this case... If this is fixed in libtool every consumer of libtool benefits, not just systemd.

**Comment by keszybz** [comment]
> I think we shouldn't fix bugs in systemd that are actually in libtool?

Yes, we should. I think we are very much in agreement here.
But we _do_ have basic a.k.a. libsystemd-internal separate from libshared. I don't see why the nss modules should share anything with systemd, as they are loaded into various other software and should be minimalistic and independent. _If_ things change and it turns out that they need stuff from shared, no issue, we can change the linkage.

Maybe I'm missing something, but I don't see the downside to this change. Is there some particular reason why linking to libshared is better?

**Pull request merged**
