### PR TITLE
test: fix LUKS2 support

### PR DESCRIPTION
**Pull request by mrc0mmand**
10MB is not enough for a LUKS2 partition.

---

This fixes TEST-02-CRYPTSETUP on Arch.

LUKS2 log:
```
[vagrant@arch build]$ sudo cryptsetup --debug luksFormat /dev/loop0p2
# cryptsetup 2.1.0 processing "cryptsetup --debug luksFormat /dev/loop0p2"
# Running command luksFormat.
# Locking memory.
# Installing SIGINT/SIGTERM handler.
# Unblocking interruption on signal.
# Allocating context for crypt device /dev/loop0p2.
# Trying to open and read device /dev/loop0p2 with direct-io.                                                                                                                                                                                 
# Initialising device-mapper backend library.

WARNING!
========
This will overwrite data on /dev/loop0p2 irrevocably.

Are you sure? (Type uppercase yes): YES
# Interactive passphrase entry requested.
Enter passphrase for /dev/loop0p2:
Verify passphrase:
# Crypto backend (OpenSSL 1.1.1b  26 Feb 2019) initialized in cryptsetup library version 2.1.0.
# Detected kernel Linux 5.0.1-arch1-1-ARCH x86_64.
# Only 2 active CPUs detected, PBKDF threads decreased from 4 to 2.
# PBKDF argon2i, hash sha256, time_ms 2000 (iterations 0), max_memory_kb 1048576, parallel_threads 2.
# Formatting device /dev/loop0p2 as type LUKS2.
# Topology: IO (512/0), offset = 0; Required alignment is 1048576 bytes.
# Checking if cipher aes-xts-plain64 is usable.
# Using userspace crypto wrapper to access keyslot area.
# Formatting LUKS2 with JSON metadata area 12288 bytes and keyslots area 16744448 bytes.
# Creating new digest 0 (pbkdf2).
# Setting PBKDF2 type key digest 0.
# Running pbkdf2(sha256) benchmark.
# PBKDF benchmark: memory cost = 0, iterations = 728177, threads = 0 (took 45 ms)
# PBKDF benchmark: memory cost = 0, iterations = 826952, threads = 0 (took 634 ms)
# Benchmark returns pbkdf2(sha256) 826952 iterations, 0 memory, 0 threads (for 512-bits key).
# Segment 0 assigned to digest 0.
WARNING: Data offset is outside of currently available data device.
# Wiping LUKS areas (0x000000 - 0x1000000) with zeroes.
Device wipe error, offset 9437184.
Cannot wipe header on device /dev/loop0p2.
# Releasing crypt device /dev/loop0p2 context.
# Releasing device-mapper backend.
# Unlocking memory.
Command failed with code -1 (wrong or missing parameters).
```

LUKS1 log:
```
[vagrant@arch build]$ sudo cryptsetup --debug luksFormat --type luks1 /dev/loop0p2
# cryptsetup 2.1.0 processing "cryptsetup --debug luksFormat --type luks1 /dev/loop0p2"
# Running command luksFormat.
# Locking memory.
# Installing SIGINT/SIGTERM handler.
# Unblocking interruption on signal.
# Allocating context for crypt device /dev/loop0p2.
# Trying to open and read device /dev/loop0p2 with direct-io.
# Initialising device-mapper backend library.
WARNING: Device /dev/loop0p2 already contains a 'crypto_LUKS' superblock signature.

WARNING!
========
This will overwrite data on /dev/loop0p2 irrevocably.

Are you sure? (Type uppercase yes): YES
# Interactive passphrase entry requested.
Enter passphrase for /dev/loop0p2:
Verify passphrase:
# Crypto backend (OpenSSL 1.1.1b  26 Feb 2019) initialized in cryptsetup library version 2.1.0.
# Detected kernel Linux 5.0.1-arch1-1-ARCH x86_64.
# PBKDF pbkdf2, hash sha256, time_ms 2000 (iterations 0), max_memory_kb 0, parallel_threads 0.
Existing 'crypto_LUKS' superblock signature on device /dev/loop0p2 will be wiped.
Existing 'crypto_LUKS' superblock signature on device /dev/loop0p2 will be wiped.
# Formatting device /dev/loop0p2 as type LUKS1.
# Topology: IO (512/0), offset = 0; Required alignment is 1048576 bytes.
# Checking if cipher aes-xts-plain64 is usable.
# Using userspace crypto wrapper to access keyslot area.
# Generating LUKS header version 1 using hash sha256, aes, xts-plain64, MK 64 bytes
# Running pbkdf2(sha256) benchmark.
# PBKDF benchmark: memory cost = 0, iterations = 799219, threads = 0 (took 41 ms)
# PBKDF benchmark: memory cost = 0, iterations = 836185, threads = 0 (took 627 ms)
# Benchmark returns pbkdf2(sha256) 836185 iterations, 0 memory, 0 threads (for 512-bits key).
# Data offset 4096, UUID 3a70b14c-6795-4cbd-af7e-3048143c23ab, digest iterations 104523
# Wiping LUKS areas (0x000000 - 0x200000) with zeroes.
# Wiping keyslot 0 area (0x001000 - 0x03f800) with random data.
# Wiping keyslot 1 area (0x040000 - 0x07e800) with random data.
# Wiping keyslot 2 area (0x07f000 - 0x0bd800) with random data.
# Wiping keyslot 3 area (0x0be000 - 0x0fc800) with random data.
# Wiping keyslot 4 area (0x0fd000 - 0x13b800) with random data.
# Wiping keyslot 5 area (0x13c000 - 0x17a800) with random data.
# Wiping keyslot 6 area (0x17b000 - 0x1b9800) with random data.
# Wiping keyslot 7 area (0x1ba000 - 0x1f8800) with random data.
# Updating LUKS header of size 1024 on device /dev/loop0p2
# Key length 64, device size 100352 sectors, header size 4036 sectors.
# Reading LUKS header of size 1024 from device /dev/loop0p2
# Key length 64, device size 100352 sectors, header size 4036 sectors.
# Adding new keyslot -1 using volume key.
# Selected keyslot 0.
# Calculating data for key slot 0
# Running pbkdf2(sha256) benchmark.
# PBKDF benchmark: memory cost = 0, iterations = 840205, threads = 0 (took 39 ms)
# PBKDF benchmark: memory cost = 0, iterations = 834853, threads = 0 (took 628 ms)
# Benchmark returns pbkdf2(sha256) 834853 iterations, 0 memory, 0 threads (for 512-bits key).
# Key slot 0 use 1669706 password iterations.
# Using hash sha256 for AF in key slot 0, 4000 stripes
# Updating key slot 0 [0x1000] area.
# Using userspace crypto wrapper to access keyslot area.
# Key slot 0 was enabled in LUKS header.
# Updating LUKS header of size 1024 on device /dev/loop0p2
# Key length 64, device size 100352 sectors, header size 4036 sectors.
# Reading LUKS header of size 1024 from device /dev/loop0p2
# Key length 64, device size 100352 sectors, header size 4036 sectors.
Key slot 0 created.
# Releasing crypt device /dev/loop0p2 context.
# Releasing device-mapper backend.
# Unlocking memory.
Command successful.
```

### CODE REVIEW

**Comment by mrc0mmand** [comment]
The second commit is necessary for LUKS2 as well, as the machine was running out of memory when attempting to mount the LUKS2 volume during boot.

**Comment by poettering** [comment]
I figure we should pass `--pbkdf pbkdf2` so that cryptsetup doesn't do the argon stuff that uses so much memory. (And maybe even `--pbkdf-force-iterations 10` or so, to make this quicker)

**Comment by mrc0mmand** [comment]
> 
> 
> I figure we should pass `--pbkdf pbkdf2` so that cryptsetup doesn't do the argon stuff that uses so much memory. (And maybe even `--pbkdf-force-iterations 10` or so, to make this quicker)

That sound like a better idea than just blindly bumping up the memory, will try.

**Comment by mrc0mmand** [comment]
Using PBKDF2 instead of Argon2 indeed resolves the memory issue. Also, reducing number of iterations is a good idea as well, so I went ahead and set it to 1000 (allowed minimum by cryptsetup). Thanks!

**Comment by poettering** [comment]
excellent! thanks!

**Comment by keszybz** [comment]
LGTM too.

**Pull request merged**
