### PR TITLE
Add support for machine secrets

### PR DESCRIPTION
**Pull request by lkundrak**
These are going to be useful with RFC7217 privacy stable addressing. Let's add a common and generic infrastructure that NetworkManager, systemd-networkd, network.service and other userspace plumbing can use.

### CODE REVIEW

**Comment by lkundrak** [comment]
Some things were not clear to me:
- Is a new functionality in systemd-machine-id-setup a good idea? Would it be better to have a separate tool?
- Likewise, is the systemd-firstboot argument useful? Wouldn't it be a better idea to fold the functionality into --setup-machine-id instead?

Cc: @teg

**Comment by teg** [comment]
Looks mostly fine to me. Though, maybe we should consider merging machine-secret and machine-id completely in the tools. I.e., only have one argument, which triggers the generation of both?

At any rate, before working more on this I suppose we need to figure out if this is API we actually want to support, and we need to agree (and document) what exactly is meant by 'secret'. The obvious problem here is that one user will expose this in a way that another does not expect.

One option, which differs from what we discussed so far is: Make the file only readable by root, and provide access to it by dbus only. Preferably a GetMachineSecret method would take a "salt" argument which would be hashed together with the real secret key before returning it. Each user would then pass a unique (but constant) salt, making sure that even if one user leaks their version of the secret, the other users are not compromised. This obviously does not protect against malicious users using someone else's salt (as the salts will be compiled into the various applications and hence be publicly known), but that is part of the deal with a shared system secret I guess. This still gives a benefit over every app maintaining their own secret, namely that no writes to disk are necessary to save the secret, it is all generated on the fly.

@poettering @kaysievers @dvdhrm @zonque ?

**Comment by dvdhrm** [comment]
Can someone explain why this needs to be a system-wide unique secret? I didn't read the RFC, so maybe I'm missing something. However, why not make each tool maintain its own secret? Is there ever a use-case where multiple tools need to share a secret?

Furthermore, why put it in /etc? Shouldn't this belong in /var? Unlike the machine-id, a secret state usually should be updated when it got leaked, right? Hence, machine-secret is inherently persistent system state, not configuration? But /var is mounted late (_sigh_) so maybe that rules it out.

Anyway, I miss a discussion of the feature in the PR or commit-message. A rationale why this is global configuration, why it needs to be shared and why its implemented the way it is. The implementation looks mostly fine, though.

**Comment by lkundrak** [comment]
Pushed an updated branch.

Changes since v1:
- Merge machine-secret(5) manual into machine-id(5) manual.
- Fold machine_secret_setup() into machine-id-setup.c, de-duplicate with machine_secret_id()
- Similarly, re-use code in sd_id128_get_machine() and sd_id128_get_machine_secret()
- Ditto in systemd-firstboot's process_machine_id() and process_machine_secret()

Didn't change the API as @teg suggested; will do when there's opinions he asked for.

> Can someone explain why this needs to be a system-wide unique secret? I didn't read the RFC, so maybe I'm missing something. However, why not make each tool maintain its own secret? Is there ever a use-case where multiple tools need to share a secret?

This was done for the simplicity of the management. The system operators need to remember one location for the system secret and the installation tools just need to write one file at known and standard location. It also removes some duplication; the network management userspace plumbing doesn't need to deal with the initialization/management of the secrets itself.

The secrets can in future be used by other uses than stable privacy addressing without bothering with creation of a separate secret file. I believe @teg had some other use already?

> Furthermore, why put it in /etc? Shouldn't this belong in /var? Unlike the machine-id, a secret state usually should be updated when it got leaked, right? Hence, machine-secret is inherently persistent system state, not configuration? But /var is mounted late (sigh) so maybe that rules it out.

I'm really not too sure about how to tell system state from configuration honestly. We just put it in /etc because its use cases and management is practically same as one of the machine-id; essentially it's just the protection bits that differ. @teg?

The machine secret should be initialized at system installation time. It should e.g. be put into initramfs for systems that set up networking early.

> Anyway, I miss a discussion of the feature in the PR or commit-message. A rationale why this is global configuration, why it needs to be shared and why its implemented the way it is. The implementation looks mostly fine, though.

I believe this qualifies as the discussion? Should I update update the PR cover letter now or wait for an outcome?

**Comment by kaysievers** [comment]
I am still not convinced that it is worth to push this to the system level. If there is no strict requirement to share a secret in a public file, it should better not be not shared and be kept private to the tools who really need it.

**Comment by poettering** [comment]
I agree with @kaysievers and @dvdhrm. I think this should really be stored in a private file that belongs to the subsystem that needs the secret, with minimal access rights. There's no need to share this, as noone should see this anyway, and all users (of which I cannot see that many besides the IP subsystem) would hash the secret anyway together with some other identifiers in order to not leak the original value.

Also, /etc/machine-id is stored in /etc only for the reason that we want it around during the entire runtime of the system, as soon as we transitioned from the initrd, all-the-way until we shut down. If we wouldn't have the requirement we would have stored it in /var instead, presumably. Now, this new secret doesn't really have such strict requirements, hence it doesn't belong in /etc anyway I think.

Anyway, I think the systemd folks mostly agree that this should stay a per-subsystem concept, and not be a system-wide concept, hence closing.

Sorry!

**Pull request closed without merging**
