### PR TITLE
udev: link_update() should fail if the entry in symlink dir couldn't …

### PR DESCRIPTION
**Pull request by fbuihuu**
…have been created

Follow-up for 30f6dce62cb3a738b20253f2192270607c31b55b

### CODE REVIEW

**Comment by fbuihuu** [comment]
Cc @msekletar @poettering

**Comment by fbuihuu** [comment]
That said I'm wondering why the solution based on a busy loop and stat(2), was preferred over simply using a lock like @mwilck had implemented at the beginning...

@msekletar, do we have any numbers that show this solution has any real advantage ?

I'm asking because the solution based on a lock would have been way simpler and the old code could have been simplified even more.

**Comment by msekletar** [comment]
> @msekletar, do we have any numbers that show this solution has any real advantage ?

AFAICT, we don't. I was proposing a different locking scheme but Lennart was really not in favour.

**Comment by fbuihuu** [comment]
Well that's a pity because there should have been some real justification for this solution which seems overly complex compare to a solution based on a lock file.

**Comment by msekletar** [comment]
> Well that's a pity because there should have been some real justification for this solution which seems overly complex compare to a solution based on a lock file.

Well, lock based solution would certainly have more correctness guarantees. Now, we run algorithm twice because in the first invocation we may actually produce symlinks that point to incorrect targets. But in the grant scheme of things what we have now is miles better than previous state.

**Comment by poettering** [comment]
> Well that's a pity because there should have been some real justification for this solution which seems overly complex compare to a solution based on a lock file.

Maybe read the discussions first, before complaining? I think I made very clear why locks suck for this, in particular ones that have no clean-up regime.

**Comment by poettering** [comment]
lgtm

**Comment by fbuihuu** [comment]
Well I did read it of course and I didn't find any arguments against a solution based on locks. AFAICT you had strong objections against SysV IPC only.

I'm not complaining I just found curious to have selected the most complex solution (whose correctness is really not obvious) whereas @mwilck provided a simple solution (we know for sure it fixed the prob [1]) with numbers and guaranty. I would have considered it first and if it would have appeared to not be enough then I would have considered adding complexity _after_.

[1] it's still not clear to me whether the current solution actually works for all cases given its commit message contains  "make algorithm that selects highest priority devlink less susceptible to race conditions"... I'm wondering what "less susceptible to race conditions" actually means.

**Comment by poettering** [comment]
> [1] it's still not clear to me whether the current solution actually works for all cases given its commit message contains "make algorithm that selects highest priority devlink less susceptible to race conditions"... I'm wondering what "less susceptible to race conditions" actually means.

device management on Linux is by design racy: you cannot query the udev db and then open the device and be sure that you actually go the device you learnt about in the udev db. That's because device names are reused: if you plug in a USB stick it will get the name /dev/sdb, if you then remove it quickly and replace it by another it will also get the /dev/sdb name even though it is an entirely different device. This is something we cannot fix in userspace. It would require major rework in the kernel so that the device names somehow are not reused anymore, or so. Which is unlikely.

When you start a system that has lots of devices which result in the same symlinks, during the start-up phase you never know in which order devices will be probed, which makes accessing such devices a lot more racy even: when you access those symlinks you never know which device you end up with. you'll end up with some device with the right label, but it could be any, and the priority encoded in the rules file is only what we'll eventually settle on, but during the probing phase the symlink might point anywhere.

hence: this all remains racy as fuck. You never know what you end up with. the only guarantee we give now is that ultimately, eventually, after all devices have shown up and the device list becomes stable the symlink will point to the right device with the highest prio.

(And no, using ugly locking for this wouldn't change a thing about all of this)

**Pull request merged**
