### PR TITLE
detect-virt: do not try to read all of /proc/cpuinfo

### PR DESCRIPTION
**Pull request by keszybz**
Quoting https://github.com/systemd/systemd/issues/10074:
> detect_vm_uml() reads /proc/cpuinfo with read_full_file()
> read_full_file() has a file max limit size of READ_FULL_BYTES_MAX=(4U*1024U*1024U)
> Unfortunately, the size of my /proc/cpuinfo is bigger, approximately:
> echo $(( 4* $(cat /proc/cpuinfo | wc -c)))
> 9918072
> This causes read_full_file() to fail and the Condition test fallout.

Let's just read line by line until we find an intersting line. This also
helps if not running under UML, because we avoid reading as much data.

I couldn't test this on UML. I installed the package from Debian unstable and for some reason I get empty /proc/cpuinfo there. @justinrernst can you test this?

### CODE REVIEW

**Comment by poettering** [comment]
lgtm. Lets wait for @justinrernst's reply before merging though

**Comment by justinrernst** [comment]
Thanks for the reply and patch. I've attached my /proc/cpuinfo to #10074 
I should have some time on the system later today or tomorrow to implement the patch and test it.

**Comment by keszybz** [comment]
Hmm, my plan was to bind-mount the patch file and let `systemd-detect-virt` read that, but it's not the same as actually reading the file from procfs. So let's actually wait for @justinrernst to test this.

**Comment by justinrernst** [comment]
I'm having difficulty implementing the patch. Do you have any recommendations for methods to get this patch implemented? I'm unable to get a build environment working for this repository, so I am attempting to add the patch to an older source rpm (228 from sles).
Is there is a quicker way I can get a source rpm with this patch?
Thanks.

**Comment by keszybz** [comment]
See https://copr.fedorainfracloud.org/coprs/zbyszek/systemd/build/798045 – there's an srpm and hopefully binary rpms if the build succeeds.

Otherwise, it should be OK to just apply the patch to any older version of systemd (not sure how far back it can apply cleanly though).

**Comment by justinrernst** [comment]
I implemented the patch and testing shows the error is gone, with systemd-detect-virt -v correctly returning "none"
It doesn't seem to be possible for me to test this patch under a UML instance.
Thanks

**Comment by keszybz** [comment]
@justinrernst thanks for testing. I think testing that your usecase is fixed, I don't think this could break UML detection.

**Pull request merged**
