### PR TITLE
Do not say " left" on every timer in LEFT column

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Review by yuwata — APPROVED** [review]

**Comment by poettering** [comment]
hmm, but the "passed" column should show "ago" for every entry?

**Comment by mrguitar** [comment]
I don't have a strong opinion on this, but when reading `list-timers` on a lot of units, it's kind of nice to see "left & ago". I definitely get @keszybz 's point that it's redundant. If you visually lock-in on one or more of the timer(s) seeing those words does help avoid column mix-up and does make it clear. That said, I think it would be fine either way.

**Comment by keszybz** [comment]
> hmm, but the "passed" column should show "ago" for every entry?

It's less obvious there. "How much is left? 5 minutes. When did we pass it? 2 minutes ago.". Without that last word, it would be less clear.

**Comment by keszybz** [comment]
mkosi / ci (centos, 8): Failed to dissect image '/home/runner/work/systemd/systemd/mkosi.output/centos~8/image.raw': Connection timed out
jammy-ppc64el: TEST-29-PORTABLE:                   FAIL     (1209 s)

jammy-* also all fail with
```
======================================================================
FAIL: test_bash_crash (__main__.CoredumpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.rIoSms/build.Lsd/systemd/debian/tests/boot-and-services", line 447, in test_bash_crash
    self.assertNotEqual(cores, [])
AssertionError: [] == []
```

Looks all unrelated.

**Pull request merged**
