### PR TITLE
test: dont use anchor char '$' with bash regexp match operator '=~'

### PR DESCRIPTION
**Pull request by fbuihuu**
If anyone can shed some light that would be nice.

### CODE REVIEW

**Comment by yuwata** [comment]
Did you see any failure?

**Comment by fbuihuu** [comment]
Yes, running lead `testsuite-73.sh` to:

```
+ assert_in 'X11 Model: pc105$' 'System Locale: LANG=en_US.UTF-8
    VC Keymap: us-acentos
   X11 Layout: us
    X11 Model: pc105
  X11 Variant: intl
  X11 Options: terminate:ctrl_alt_bksp'
+ set +ex
FAIL: 'X11 Model: pc105$' not found in:
System Locale: LANG=en_US.UTF-8
    VC Keymap: us-acentos
   X11 Layout: us
    X11 Model: pc105
  X11 Variant: intl
  X11 Options: terminate:ctrl_alt_bksp

```

**Comment by yuwata** [comment]
Interesting, why the failure not detected in our CIs?

**Review by yuwata — APPROVED** [review]

**Comment by fbuihuu** [comment]
`us-acentos` is only tested if `kbd-legacy` is installed. I suppose it's not the case for the CIs.

**Comment by fbuihuu** [comment]
But I'm still wondering why '$' is not working as I'm expecting with bash... maybe I'm missing something.

**Comment by mrc0mmand** [comment]
>'$' is supposed to match the null string at the end of a line but for some
> reasons it doesn't work as expected with "=~" operator:

That's because the `=~` operator is defined as:
> The  pattern  will  match  if  it matches any part of the string.  Anchor the pattern using the ^ and $ regular expression operators to force it to match the entire string.

**Comment by mrc0mmand** [comment]
> But I'm still wondering why '$' is not working as I'm expecting with bash... maybe I'm missing something.

The `$` behavior you describe works only with `REG_NEWLINE`, but bash uses only `REG_EXTENDED` (or `REG_ICASE` if you use `shopt -s nocasematch`).

**Comment by fbuihuu** [comment]
> That's because the `=~` operator is defined as:
> 
> > The  pattern  will  match  if  it matches any part of the string.  Anchor the pattern using the ^ and $ regular expression operators to force it to match the entire string.

Ah thanks, I was looking at the man page of bash 4.4 and this part is missing.

Let me update the commit message.

**Comment by fbuihuu** [comment]
Commit message updated.

**Pull request merged**
