### PR TITLE
handle corrupted /etc/machine-id nicer

### LINKED ISSUE #4475: RFE: handle corrupted /etc/machine-id nicer (e.g. warn loudly and overmount temporarily with a valid one)
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

231
### Used distribution

Fedora 25
### In case of bug report: Expected behaviour you didn't see

journald working.
### In case of bug report: Unexpected behaviour you saw

```
# systemctl | grep failed
● systemd-journald.service               loaded failed failed    Journal Service
● systemd-tmpfiles-setup-dev.service     loaded failed failed    Create Static Device Nodes in /dev
● systemd-tmpfiles-setup.service         loaded failed failed    Create Volatile Files and Directories
● systemd-journald-audit.socket          loaded failed failed    Journal Audit Socket
● systemd-journald-dev-log.socket        loaded failed failed    Journal Socket (/dev/log)
● systemd-journald.socket                loaded failed failed    Journal Socket
```
### In case of bug report: Steps to reproduce the problem
1. Boot Fedora 25. 
### Notes
- Potentially applies to ARM machines only.
- [Downstream bug report.](https://bugzilla.redhat.com/show_bug.cgi?id=1387799)

### PR DESCRIPTION
**Pull request by evverx**
Fixes #4475

### CODE REVIEW

**Comment by poettering** [comment]
lgtm.

**Comment by evverx** [comment]
@poettering , hm, `systemctl daemon-reexec` skips `machine_id_setup`. I.e. live upgrades from `v230` to `v233` are broken.

I've implemented a compat mode.
```diff
diff --git a/src/libsystemd/sd-id128/sd-id128.c b/src/libsystemd/sd-id128/sd-id128.c
index 0d673ba..43b10fc 100644
--- a/src/libsystemd/sd-id128/sd-id128.c
+++ b/src/libsystemd/sd-id128/sd-id128.c
@@ -103,8 +103,27 @@ _public_ int sd_id128_get_machine(sd_id128_t *ret) {

         if (sd_id128_is_null(saved_machine_id)) {
                 r = id128_read("/etc/machine-id", ID128_PLAIN, &saved_machine_id);
-                if (r < 0)
-                        return r;
+                if (r < 0) {
+                        /* v230-compat mode */
+                        _cleanup_close_ int fd = -1;
+                        char buf[33];
+
+                        fd = open("/etc/machine-id", O_RDONLY|O_CLOEXEC|O_NOCTTY);
+                        if (fd < 0)
+                                return -errno;
+
+                        r = loop_read_exact(fd, buf, 33, false);
+                        if (r < 0)
+                                return r;
+
+                        if (buf[32] !='\n')
+                                return -EIO;
+
+                        buf[32] = '\0';
+                        r = sd_id128_from_string(buf, &saved_machine_id);
+                        if (r < 0)
+                                return r;
+                }

                 if (sd_id128_is_null(saved_machine_id))
                         return -EINVAL;
```
I can push this commit. What do you think?

**Comment by poettering** [comment]
I merged this PR for now as everything in it looks good to me as it is. any further additions can be new PRs.

**Comment by poettering** [comment]
@evverx i am not sure I understand why you say that such live-upgrades are broken? I mean, if you have a broken /etc/machine-id, it won't be fixed for you, that's true, but I don't think it really should be, in particular as we shouldn't change the machine ID during runtime really.

Where do these broken machine IDs actually come from? Are they caused by our own code? If not I think we should leave this to fix to downstreams. Specifically, they should probably add code to their package update scripts, to sanitize any broken /etc/machine-id. But that can happen in shell really I think.

**Comment by evverx** [comment]
> i am not sure I understand why you say that such live-upgrades are broken?

Well, I mean:
```
$ cat /etc/machine-id
ace35669f0b24a84ba4de3caa96c0d44
e3d

# v230 works fine

# daemon-reexec from 230 to 233

$ systemctl restart systemd-journald
Job for systemd-journald.service failed because the control process exited with error code.
See "systemctl status systemd-journald.service" and "journalctl -xe" for details.

$ dmesg | grep -i journal
...
[  167.622154] systemd-journald[155]: Failed to open runtime journal: Invalid argument

$ SYSTEMD_LOG_LEVEL=debug systemd-tmpfiles --create
...
[/usr/lib/tmpfiles.d/systemd.conf:26] Failed to replace specifiers: /run/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:28] Failed to replace specifiers: /run/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:29] Failed to replace specifiers: /run/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:30] Failed to replace specifiers: /run/log/journal/%m/*.journal*
[/usr/lib/tmpfiles.d/systemd.conf:33] Failed to replace specifiers: /var/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:34] Failed to replace specifiers: /var/log/journal/%m/system.journal
[/usr/lib/tmpfiles.d/systemd.conf:38] Failed to replace specifiers: /var/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:39] Failed to replace specifiers: /var/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:40] Failed to replace specifiers: /var/log/journal/%m/system.journal
...
```
and so on

> it won't be fixed for you, that's true, but I don't think it really should be

I agree. We shouldn't change the `/etc/machine-id` during runtime.

> Where do these broken machine IDs actually come from?

As far as I understand they come from the broken images. But `systemd` worked fine (before `v231`)

> Specifically, they should probably add code to their package update scripts, to sanitize any broken /etc/machine-id

OK, makes sense. Thanks!

**Pull request merged**
