### PR TITLE
bpf: actually skip RestrictFileSystems= when not supported

### PR DESCRIPTION
**Pull request by keszybz**
Units would fail to start, incl. systemd-journald.service and systemd-udevd.service.
Since unit->manager->restrict_fs will be set if and only if we can use it,
we can just check for that and remove the other checks.
Follow-up for 299d9417238e0727a48ebaabb5a9de0c908ec5c8.

### CODE REVIEW

**Comment by bluca** [comment]
```
FAIL: test-firewall-util20:00
Using nftables as firewall backend.20:00
/* test_v4(backend=nftables) */20:00
/* test_v6(backend=nftables) */20:00
Assertion 'fw_add_masquerade(&ctx, true, AF_INET6, &u3, prefixlen) >= 0' failed at src/test/test-firewall-util.c:34, function test_v6(). Aborting.
```

Does that use the BPF LSM?

**Review by anitazha — APPROVED** [review]
So the previous logic was proceeding when LSM BPF was "supported", but failed to check that it was actually set up. This PR makes sense for fixing that.

> Assertion 'fw_add_masquerade(&ctx, true, AF_INET6, &u3, prefixlen) >= 0' failed at src/test/test-firewall-util.c:34, function test_v6(). Aborting.
> 
> Does that use the BPF LSM?

The firewall-util code doesn't use BPF AFAICT. It existed before BPF LSM was added to systemd.

**Comment by bluca** [comment]
I don't remember seeing it fail - but I've restarted it, let's see

**Comment by bluca** [comment]
It passed, so it was a coincidence, let's merge

**Pull request merged**
