### PR TITLE
hwdb: add axis range corrections for the Lenovo ThinkPad Edge 13 (02173BG)

### PR DESCRIPTION
**Pull request by snorreflorre**
add axis range corrections for the Lenovo ThinkPad Edge 13 (02173BG)

### CODE REVIEW

**Comment by poettering** [comment]
hmm something is off there, CI fails on debian:

```
Cannot parse /tmp/autopkgtest.XzBmhH/build.4Ed/debian/hwdb/60-evdev.hwdb: Expected stringEnd (at char 10442), (line:378, col:1)
```

**Comment by keszybz** [comment]
```
211/255 parse-hwdb                              FAIL     4.32 s

--- command ---
/tmp/autopkgtest.XzBmhH/build.4Ed/debian/hwdb/parse_hwdb.py
--- stdout ---
/tmp/autopkgtest.XzBmhH/build.4Ed/debian/hwdb/60-input-id.hwdb: 1 match groups, 1 matches, 2 properties
/tmp/autopkgtest.XzBmhH/build.4Ed/debian/hwdb/70-mouse.hwdb: 80 match groups, 109 matches, 93 properties
/tmp/autopkgtest.XzBmhH/build.4Ed/debian/hwdb/60-keyboard.hwdb: 136 match groups, 211 matches, 712 properties
/tmp/autopkgtest.XzBmhH/build.4Ed/debian/hwdb/70-pointingstick.hwdb: 8 match groups, 22 matches, 11 properties
/tmp/autopkgtest.XzBmhH/build.4Ed/debian/hwdb/70-joystick.hwdb: 2 match groups, 3 matches, 2 properties
Cannot parse /tmp/autopkgtest.XzBmhH/build.4Ed/debian/hwdb/60-evdev.hwdb: Expected stringEnd (at char 10442), (line:378, col:1)
/tmp/autopkgtest.XzBmhH/build.4Ed/debian/hwdb/60-evdev.hwdb: 0 match groups, 0 matches, 0 properties
/tmp/autopkgtest.XzBmhH/build.4Ed/debian/hwdb/70-touchpad.hwdb: 3 match groups, 5 matches, 3 properties
/tmp/autopkgtest.XzBmhH/build.4Ed/debian/hwdb/60-sensor.hwdb: 40 match groups, 43 matches, 40 properties
```

**Comment by keszybz** [comment]
I think it's just the matter of trailing whitespace in the separator line.

**Comment by whot** [comment]
@snorreflorre please force-push your branch with the trailing whitespace removed, thanks

**Comment by yuwata** [comment]
I've removed the unnecessary space. Then, now at least two Ubuntu CIs pass. If the change is fine, then please use 'squash and merge'.

**Pull request merged**
