### PR TITLE
sysroot: Support x-systemd.makefs

### PR DESCRIPTION
**Pull request by ElvishJerricco**
`systemd-fstab-generator` does not generate `systemd-makefs` units for sysroot and sysusr. To need this might seem unusual, as these file systems ought to have been formatted when the OS was installed, but this patch allows these file systems to be created as an automation during first boot instead.

I needed this while trying to make NixOS's systemd-initrd implementation use `root=` on the cmdline instead of having `/sysroot` in `/etc/fstab`. NixOS's automated testing uses virtual machines that create their root file systems during boot in initrd because the OS isn't stored in sysroot or sysusr. It's in `/nix/store`, which is a `9p` file system for these virtual machines. (As a side note, `/nix/store` is in many ways NixOS's equivalent of `/usr` though in many ways not, so it's often unfortunate that systemd hard codes this path to `/usr` rather than allowing it to be configurable.)

We wouldn't have to use `root=` on the cmdline if #3551 was resolved, because `systemd-fstab-generator` does correctly create the systemd-makefs unit for `/sysroot` as found in the initrd's `/etc/fstab`. But this fails for other reasons. 1) The file systems in initrd's `/etc/fstab` are wanted by `local-fs.target` instead of `initrd-{root-,}fs.target`, so `initrd-root-fs.target` and `initrd-root-device.target` don't function correctly (see #24904). And 2) `systemctl isolate initrd-switch-root.target` causes `systemd-makefs@ROOT_DEVICE.service` to be stopped since it isn't wanted by `initrd-{root-,}fs.target` which unmounts `/sysroot` due to its `Requires` dependency on the systemd-makefs unit. This can be prevented by adding a `initrd-fs.taget -> local-fs.target` wants dependency, but this doesn't fix `#1` and is also just morally incorrect considering the motivations of the two targets.

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, so our thinking was that once you want more complex stuff (and I'd consider generating the root fs on first boot) systemd-repart is the way to go. It can even do encryption and so on automatically...

(not opposed to also making systemd-makefs@.service work in the root fs, just saying, that systemd-repart sounds like the way to go, no?

**Comment by poettering** [comment]
> We wouldn't have to use `root=` on the cmdline if #3551 was resolved, because `systemd-fstab-generator` does correctly create the systemd-makefs unit for `/sysroot` as found in the initrd's `/etc/fstab`. But this fails for other reasons. 1) The file systems in initrd's `/etc/fstab` are wanted by `local-fs.target` instead of `initrd-{root-,}fs.target`, so `initrd-root-fs.target` and `initrd-root-device.target` don't function correctly (see #24904). And 2) `systemctl isolate initrd-switch-root.target` causes `systemd-makefs@ROOT_DEVICE.service` to be stopped since it isn't wanted by `initrd-{root-,}fs.target` which unmounts `/sysroot` due to its `Requires` dependency on the systemd-makefs unit. This can be prevented by adding a `initrd-fs.taget -> local-fs.target` wants dependency, but this doesn't fix `#1` and is also just morally incorrect considering the motivations of the two targets.

Fixing #3551 shouldn't be hard. Just needs some special casing to order deps for sysroot.mount more carefully. The fact this is not done is oversight, not intention. Also happy to take patches for that.

**Comment by poettering** [comment]
Anyway, patch looks good to me. A patch addressing #3551 would also be very welcome. But either way, consider looking into systemd-repart, I am pretty sure it's the tool you actually should consider using for this.

**Review by bluca — APPROVED** [review]

**Comment by ElvishJerricco** [comment]
Hm whoops, I just realized that I didn't add an ordering dependency between `systemd-makefs@sysroot.service` and `initrd-root-fsck.service` to match the one between `systemd-makefs@.service` and `systemd-fsck@.service`. (Frankly, I'm not entirely sure why that service is different rather than just generating the same `systemd-fsck@sysroot.service` like the other file systems).

@poettering `systemd-repart` would indeed work in the case that we have a GPT. But A) Our test VM infrastructure has always assumed to just put the root fs directly on a disk rather than partitioning it, and B) We also *currently* support users that don't use GPT at all either because they still use MBR or because they do as our VMs do and use a disk as their FS device directly.

**Pull request merged**
