### PR TITLE
Empty .network file warning and documentation

### PR DESCRIPTION
**Pull request by zv**
Warn over completely commented .network files & update documentation.

In reference to #717

### CODE REVIEW

**Comment by poettering** [comment]
The man page should probably also clarify that an empty or missing [Match] section means the .network file will apply to _all_ interfaces.

**Comment by poettering** [comment]
Also, please add the same logic to handling of `.link` files.

**Comment by keszybz** [comment]
> Also, there a checks missing for match_host, match_virt, match_kernel, match_arch

I think that those **should not** be checked. They are either true for all interfaces, or for none, and are about the .network file itself (should it be enabled or not), and not the interfaces.

**Comment by poettering** [comment]
I think i agree with what @keszybz just said.

**Comment by zonque** [comment]
This doesn't apply anymore, and there was no new version of the patches. I'm closing this for now, please reopen a new PR if you think it's still needed. Thanks!

**Pull request closed without merging**
