### PR TITLE
mkosi: Update to latest commit

### LINKED ISSUE #1128: journald can create invalid journal files
I discovered on one of my systems, that I could no longer query the journal via `journalctl`. All operations failed with:

```
Error was encountered while opening journal files: Invalid argument
```

Increasing the log level shows:

```
mymachine me # SYSTEMD_LOG_LEVEL=debug journalctl
Root directory /run/log/journal added.
Considering /run/log/journal/bc3b4c575faf4633afd61696078ab975.
Directory /run/log/journal/bc3b4c575faf4633afd61696078ab975 added.
File /run/log/journal/bc3b4c575faf4633afd61696078ab975/system.journal added.
File /run/log/journal/bc3b4c575faf4633afd61696078ab975/system@e5cf6fa206e9474aa499f0215cf49163-00000000017c74ad-00051ec93a05cef7.journal added.
...
File /run/log/journal/bc3b4c575faf4633afd61696078ab975/system@e5cf6fa206e9474aa499f0215cf49163-000000000176d4a8-00051ec53358fbbd.journal added.
Considering /run/log/journal/d706862542094104b0e5ccdbcebe16e6.
Directory /run/log/journal/d706862542094104b0e5ccdbcebe16e6 added.
File /run/log/journal/d706862542094104b0e5ccdbcebe16e6/system.journal added.
Root directory /var/log/journal added.
Considering /var/log/journal/bc3b4c575faf4633afd61696078ab975.
Directory /var/log/journal/bc3b4c575faf4633afd61696078ab975 added.
File /var/log/journal/bc3b4c575faf4633afd61696078ab975/system@65243c7ee4474ecc8e68b469272aaee3-0000000001729cfa-000512a3eb95ab05.journal added.
...
File /var/log/journal/bc3b4c575faf4633afd61696078ab975/system@65243c7ee4474ecc8e68b469272aaee3-00000000016db1a2-0005129da494bec5.journal added.
Failed to add file /var/log/journal/bc3b4c575faf4633afd61696078ab975/system.journal: Invalid argument
```

Upon further investigation, this appears to be because the `size` parameter for `journal_file_move_to()` is zero. This is called by `journal_file_map_field_hash_table()`, where `size` is `f->header->field_hash_table_size`. Breaking in GDB confirms this:

```
print/x *f->header
$1 = {signature = {0x4c, 0x50, 0x4b, 0x53, 0x48, 0x48, 0x52, 0x48}, compatible_flags = 0x0, incompatible_flags = 0x1, state = 0x0, reserved = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, 
  file_id = {bytes = {0xbe, 0x8d, 0x71, 0x6d, 0x5e, 0xd7, 0x48, 0x7f, 0xb3, 0x90, 0xce, 0x4f, 0x4, 0xd0, 0xca, 0xb9}, qwords = {0x7f48d75e6d718dbe, 0xb9cad0044fce90b3}}, machine_id = {
    bytes = {0xbc, 0x3b, 0x4c, 0x57, 0x5f, 0xaf, 0x46, 0x33, 0xaf, 0xd6, 0x16, 0x96, 0x7, 0x8a, 0xb9, 0x75}, qwords = {0x3346af5f574c3bbc, 0x75b98a079616d6af}}, boot_id = {bytes = {0x55, 
      0x22, 0xce, 0x72, 0x1, 0xcc, 0x44, 0x60, 0x9b, 0x2a, 0x8b, 0xdd, 0x7e, 0x52, 0x2b, 0x5a}, qwords = {0x6044cc0172ce2255, 0x5a2b527edd8b2a9b}}, seqnum_id = {bytes = {0x65, 0x24, 0x3c, 
      0x7e, 0xe4, 0x47, 0x4e, 0xcc, 0x8e, 0x68, 0xb4, 0x69, 0x27, 0x2a, 0xae, 0xe3}, qwords = {0xcc4e47e47e3c2465, 0xe3ae2a2769b4688e}}, header_size = 0xf0, arena_size = 0x0, 
  data_hash_table_offset = 0x0, data_hash_table_size = 0x0, field_hash_table_offset = 0x0, field_hash_table_size = 0x0, tail_object_offset = 0x0, n_objects = 0x0, n_entries = 0x0, 
  tail_entry_seqnum = 0x1772777, head_entry_seqnum = 0x0, entry_array_offset = 0x0, head_entry_realtime = 0x0, tail_entry_realtime = 0x0, tail_entry_monotonic = 0x0, n_data = 0x0, 
  n_fields = 0x0, n_tags = 0x0, n_entry_arrays = 0x0}
```

How did this struct member end up with an invalid value? My guess is that in `journal_open_file()`, there was a failure between `journal_file_init_header()` and `journal_file_setup_field_hash_table()`. It is possible for the function to exit with a partially initialized header. Why isn't all of initialization done in `journal_file_init_header()`?

### LINKED ISSUE #1128: Can't build OpenSUSE images
Looks like OpenSUSE's pam package dropped the `/usr/etc/` stuff, which breaks building an OpenSUSE image using mkosi (notice both locally and in systemd CI):

```
Executing %posttrans scripts ................................................................................................................................................................................................................................[done]
‣   Unmounting API VFS
RPM files caching has been disabled for repository 'repo-oss'.
RPM files caching has been disabled for repository 'repo-update'.
‣  (Unmounting Package Cache)
‣  (Unmounting image)
‣  (Detaching /dev/loop0)
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 36, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/mkosi/__main__.py", line 27, in main
    run_verb(a)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 8409, in run_verb
    manifest = build_stuff(args)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 7764, in build_stuff
    image = build_image(args, root, do_run_build_script=True)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 7500, in build_image
    install_distribution(args, root, do_run_build_script, cached_tree)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 3293, in install_distribution
    install[args.distribution](args, root, do_run_build_script)
  File "/usr/lib64/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/site-packages/mkosi/__init__.py", line 3225, in install_opensuse
    shutil.copy2(root / "usr/etc/pam.d/common-auth", root / "etc/pam.d/common-auth")
  File "/usr/lib64/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/mkosi-4edkdp7v/root/usr/etc/pam.d/common-auth'
```

OpenSUSE change: https://build.opensuse.org/request/show/984917

Relevant code:
https://github.com/systemd/mkosi/blob/28835f79035ab4cb519ef0fd0358a7ce18261b36/mkosi/__init__.py#L2920-L2921

The `common-auth` module is now under `/usr/lib/pam.d/common-auth`:
```
$ rpm -ql mkosi.cache/repo-oss/x86_64/pam-1.5.2-7.1.x86_64.rpm | grep common-auth
warning: mkosi.cache/repo-oss/x86_64/pam-1.5.2-7.1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
/usr/lib/pam.d/common-auth
```

### PR DESCRIPTION
**Pull request by daandemeyer**
Fixes https://github.com/systemd/mkosi/issues/1128

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by mrc0mmand** [comment]
mkosi seems to be _very_ unhappy for some reason, but I can't parse anything useful from the logs apart from failing `systemd-firstboot.service`...

**Comment by DaanDeMeyer** [comment]
Trying to figure out why we get no logs

**Comment by keszybz** [comment]
Tests pass now, let's merge this.

**Comment by mrc0mmand** [comment]
I mean, the Ubuntu job still fails: https://github.com/systemd/systemd/runs/7954570522?check_suite_focus=true

**Comment by keszybz** [comment]
(I might have gotten confused as to the state of things. Please revert the merge if appropriate.)

**Comment by mrc0mmand** [comment]
It's a different fail, but it's caused by the second commit. But anyway, I'm sure @DaanDeMeyer will figure something out ;)

**Pull request merged**
