### PR TITLE
Increase /tmp size to 50% of RAM

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by cmurf** [comment]
Should the title be 50% instead of 25%? I see:

+ Options=mode=1777,strictatime,nosuid,nodev,size=50%,nr_inodes=400k

**Comment by cmurf** [comment]
Well I'm not sure if the title was the mistake or the value in the commit, because 25% would fix the problem.

**Comment by topimiettinen** [comment]
50% is the default limit set by kernel, so this change makes the block limit pretty much useless. Also the total allowed RAM for all tmpfs mounts could get too high. Maybe it's better to remove the mount limits entirely and instead introduce a single limit for RAM consumption for tmpfs mounts on kernel side.

**Comment by keszybz** [comment]
> 50% is the default limit set by kernel, so this change makes the block limit pretty much useless.

It makes the limit explicit, which I think makes it easier to see what is going on.

> Also the total allowed RAM for all tmpfs mounts could get too high.

The other tmpfs mounts have smaller limits. When compression is taken into account, I think the limits are OK.

> Maybe it's better to remove the mount limits entirely and instead introduce a single limit for RAM consumption for tmpfs mounts on kernel side.

That'd make things less predictable. Right now it is possible to use `df` and make appropriate decisions based on the result, and if this limit was shared between all tmpfs mounts, this would not be possible. Also, not all mount are equal. I think it is reasonable to set separate limits on all mounts.

**Comment by poettering** [comment]
Looks OK but could you also adjust TMPFS_LIMITS_TMP according to this? i.e. nspawn should get the same settings I figure...

**Comment by poettering** [comment]
BTW, it really sounds as if dnf is placing large data in /tmp that shouldn't be in /tmp but in /var/tmp...

(And given that dnf has its own hierarchies below /var it should probably just put the data there and not bother with /tmp or /var/tmp at all...)

**Comment by keszybz** [comment]
> Looks OK but could you also adjust TMPFS_LIMITS_TMP according to this? i.e. nspawn should get the same settings I figure...

I didn't bump TMPFS_LIMITS_TMP on purpose: I think we should use lower limits for guest things (like nspawn). After all, there can be multiple of those, and they might not be as trusted as the main machine, etc.

**Comment by poettering** [comment]
hmm, but that's confusing then. needs a comment in the header file then, to indicate that the host /tmp is not sized like 
TMPFS_LIMITS_TMP, suggests...

**Comment by cmurf** [comment]
>BTW, it really sounds as if dnf is placing large data in /tmp that shouldn't be in /tmp but in /var/tmp...

This is installation media, /var is on a memory based overlay. There is nothing disk based until partitioning happens, and the downloading of repository metadata happens before that.

Subsetting the repo metadata so that the user can make decisions, and then only download complete repo data after partitioning has happened, might be a good idea but there's no design or implementation for that.

**Comment by keszybz** [comment]
Updated with additional comments.

**Comment by poettering** [comment]
> > BTW, it really sounds as if dnf is placing large data in /tmp that shouldn't be in /tmp but in /var/tmp...
> 
> This is installation media, /var is on a memory based overlay. There is nothing disk based until partitioning happens, and the downloading of repository metadata happens before that.

Still, large data should not be place in /tmp but in /var/tmp. 

Yes, maybe the specific system has both backed by memory, but that's besides the point: /tmp is not for large data, that's what /var/tmp is for. So yes, fixing dnf won't fix this specific bug, but it's still using the wrong dir.

**Comment by cmurf** [comment]
> Yes, maybe the specific system has both backed by memory, but that's besides the point: /tmp is not for large data, that's what /var/tmp is for. So yes, fixing dnf won't fix this specific bug, but it's still using the wrong dir.

I don't know how anyone could know this. What is large data? Something that will take up most of /tmp? Or something that could conceivably risk filling /tmp? In the context of /tmp on tmpfs in Fedora being 50% of RAM since 2012, the answer to these questions is, the payload isn't large. It's not expected to be even half of /tmp, as long as /tmp is 50% of RAM.

The FHS says /tmp is temporary/volatile, cleaned up on reboot. Whereas /var/tmp is persistent or at least less volatile than /tmp. It doesn't say anything about their relative capacities.

**Comment by AdamWill** [comment]
It kind of doesn't matter anyway, because it's not a dnf setting, it's an [anaconda one](https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/payload/dnf/utils.py#L34). dnf's default for that setting is not in `/tmp` (it's in `/var/cache` I think).

Sure, you can make the very theoretical argument that anaconda should use `/var/tmp` not `/tmp`, but we're definitely in angels-dancing-on-a-pinhead territory there, since we know for a certainty that neither is going to be disk-backed in the installer environment.

**Pull request merged**
