### PR TITLE
creds-util: switch to OpenSSL 3.0 APIs

### PR DESCRIPTION
**Pull request by poettering**
Let's switch from the low-level SHA256 APIs to EVP APIs. The former are
deprecated on OpenSSL 3.0, the latter are supported both by old
OpenSSL and by OpenSSL 3.0, hence are the better choice.

Fixes: #20775

### CODE REVIEW

**Comment by bluca** [comment]
Add a revert for https://github.com/systemd/systemd/pull/20773 ? Or is there other stuff to update?

**Comment by poettering** [comment]
I added the revert now. ptal!

**Review by bluca — APPROVED** [review]
lgtm

**Comment by bluca** [comment]
Is there a minimum openssl version that we should encode in meson?

**Comment by poettering** [comment]
we so far use EVP apis everywere and required only 1.1.0 as minimum version. I don't think we need to change anything there.

**Comment by poettering** [comment]
https://www.openssl.org/docs/man1.1.0/man3/EVP_MD_CTX_new.html ← that#s the man page from openssl 1.1.0 and it lists everything we need. so we should be good.

**Comment by mrc0mmand** [comment]
CI is still unhappy:

```
../src/shared/openssl-util.c: In function ‘rsa_pkey_to_suitable_key_size’:
../src/shared/openssl-util.c:61:9: error: ‘EVP_PKEY_get0_RSA’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   61 |         rsa = EVP_PKEY_get0_RSA(pkey);
      |         ^~~
In file included from ../src/shared/openssl-util.h:8,
                 from ../src/shared/openssl-util.c:3:
/usr/include/openssl/evp.h:1346:22: note: declared here
 1346 | const struct rsa_st *EVP_PKEY_get0_RSA(const EVP_PKEY *pkey);
      |                      ^~~~~~~~~~~~~~~~~
../src/shared/openssl-util.c:65:9: error: ‘RSA_bits’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   65 |         bits = RSA_bits(rsa);
      |         ^~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/ssl.h:31,
                 from ../src/shared/openssl-util.h:10,
                 from ../src/shared/openssl-util.c:3:
/usr/include/openssl/rsa.h:203:27: note: declared here
  203 | OSSL_DEPRECATEDIN_3_0 int RSA_bits(const RSA *rsa);
      |                           ^~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by poettering** [comment]
Added another commit, let's see if we are good now.

**Comment by poettering** [comment]
seems packit CI passed now

**Review by yuwata — APPROVED** [review]
LGTM.

**Pull request merged**
