### PR TITLE
kernel-install create efi directory if missing

### PR DESCRIPTION
**Pull request by johannbg**
Let's create efi directory based on current $MACHINE_ID if it's missing so users can update and boot into new kernels.

### CODE REVIEW

**Comment by keszybz** [comment]
What issue is this trying to solve? 341890de866f2ee34919a47ce3fc6c8cd3c1924c made `bootctl install` create `$BOOT/<machine-id>`, and cf73f650890b56a59bfb713c4c82b4e29daa7316 changed `kernel-install` to **not** create it. The reasoning is a bit convoluted, but we have to cooperate with other tools which check for the presence of this directory, so it certainly should not be created unconditionally.

**Comment by johannbg** [comment]
With my admin hat on be a tool,an administrator who needs to regenerate the machine id for whatever reason ( might have gotten corrupt or might have cloned a machine which is more likely these days etc) the system should remain bootable at all cost after update or in general since the end user or the administator most certanly is no efi shell expert or might not have remote access to the machine to recover it.

**Comment by johannbg** [comment]
As I see it there might be three ways to solve this problem.

a) Rename the current efi directory string to match what's in machine id
b) create new directory based on the string in machine-id ( might be required for auditing purposes hence this hack of mine ) 
c) replace the current string in machined-id with the existing directory string.

And relevant tools check if the efi directory and the machine-id string match and if not do something of   the above.

Obviously there might be usecase beyond my knowledge as you point out and I most certainly am putting the highest priority on leaving the end user with a bootable system at all cost while ymmv in that regard.

**Comment by keszybz** [comment]
In general, there is no requirement for the machine-id to match the string under `$BOOT`. So even if the machine-id is reset, existing boot entries will remain bootable. There is a caveat: in the longer term, if the directory does not exist when the kernel is upgraded, kernel-install might not create the expected entries, so after a kernel upgrade, it might not be possible to boot the latest kernel.

This patch will currently break e.g. users of grub, so certainly can't merge it as is.

**Comment by johannbg** [comment]
@keszybz right ( with the upgrade ) as a side node is grub still a relevant thing in the 21 century ( which makes this a no no then I suppose )? ;)

**Comment by keszybz** [comment]
>  is grub still a relevant thing in the 21 century 

I don't use it, but plenty of people do.

**Comment by johannbg** [comment]
Based on commit reference Fedora should be obsoleting it now ( along with quite few other things on the core/baseOS level ) otherwise it's going to take up 8 years before it's done ( RHEL 10 ) Atleast some distro needs to go ahead and just do it and lead the way ( I'm looking at you Arch! ) Given that this is a political hot potato I'm closing this since it's highly unlikely this will pass until Grub gets scrubbed hence closing...

**Pull request closed without merging**
