### PR TITLE
systemctl: return success for set-default

### PR DESCRIPTION
**Pull request by eworm-de**

### CODE REVIEW

**Comment by evverx** [comment]
I run `systemctl set-default multi-user.target`:

``` sh
-bash-4.3# systemctl set-default multi-user.target
Segmentation fault (core dumped)
```

``` sh
(gdb) thread apply all bt

Thread 1 (Thread 0x7fcd71c0f880 (LWP 286)):
#0  0x00005637ed326ce4 in bus_deserialize_and_dump_unit_file_changes (m=0x5637ed87e390, quiet=false, changes=0x0, n_changes=0x0) at src/shared/bus-unit-util.c:893
#1  0x00005637ed2f2ad4 in set_default (argc=2, argv=0x7ffea3b11230, userdata=0x0) at src/systemctl/systemctl.c:2101
#2  0x00005637ed396dbe in dispatch_verb (argc=3, argv=0x7ffea3b11228, verbs=0x5637ed43f4a0 <verbs>, userdata=0x0) at src/basic/verbs.c:92
#3  0x00005637ed305a38 in systemctl_main (argc=3, argv=0x7ffea3b11228) at src/systemctl/systemctl.c:7468
#4  0x00005637ed3069c2 in main (argc=3, argv=0x7ffea3b11228) at src/systemctl/systemctl.c:7737
```

I think we should fix this first.

**Comment by eworm-de** [comment]
That's a different problem... It happens within a running system.

I am hit by my issue inside a chroot, without running dbus session.

**Comment by keszybz** [comment]
Hm, set_default is called from dispatch_verb which is called from systemctl_main, which is called from main, which has this:

```
        return r < 0 ? EXIT_FAILURE : r;
```

This is borked, it should be ": EXIT_SUCCESS".

**Comment by evverx** [comment]
@keszybz , see 404f08d341c6fc :)

> /\* Note that we return r here, not EXIT_SUCCESS, so that we can implement the LSB-like return codes */

**Comment by evverx** [comment]
I've tried https://github.com/systemd/systemd/pull/1839 :)

**Comment by eworm-de** [comment]
Following the code comment my patch is correct, no?
We do it this way more than once, for example in `enable_unit()`.

**Comment by eworm-de** [comment]
Rebased on current master...

**Comment by evverx** [comment]
Actually, you've just fixed another regression. See https://github.com/systemd/systemd/commit/af3d811352094f3f1304bdf8ba9cdd2b4b03b55c#diff-69ea3a0848eb29638bc663cf16af1b2dL2031

Did you check other commands?

**Comment by evverx** [comment]
~~Seems like `add-wants/add-requires` don't work properly too.~~.
~~I was wrong.~~
Seems like `add-wants/add-requires` don't work properly too.

``` sh
-bash-4.3# systemctl --root=/ add-wants graphical.target testsuite.service
Created symlink /etc/systemd/system/graphical.target.wants/testsuite.service → /etc/systemd/system/testsuite.service.

-bash-4.3# echo $?
1
```

**Comment by eworm-de** [comment]
Added some more changes... Did I catch everything?

**Pull request merged**
