### PR TITLE
RFC: journald: keep console fd open

### PR DESCRIPTION
**Pull request by utezduyar**
Seems like an overkill to open and close the console every time we are forwarding a message to it.

However, this change conflicts with console-gettty.service's TTYVHangup=yes setting. console-getty.service kicks journald out from /dev/console.

### CODE REVIEW

**Comment by poettering** [comment]
We can't really do this, it's incompatible with the "SAK" functionality of the Linux kernel. (SAK = Secure Attention Key, which is a special key combo that kills everything on the console, so that you may then log in knowing that nothing else can listen in. It's a generally understood that priviliged code that logs to the console (specifically PID 1 and the logging daemon) should not leave the console open continiously in order to ensure that they are not SIGKILLed by the kernel when the user on the console presses SAK.

(Also, as you already found out, TTYReset= kicks all clients from the console, and so do any kind of vhangup() actually, which is regularly part of gettys and suchlike. Hence we'd have to reopen the console all the time anyway if we get kicked off it. And if we need the code for that I think it's much simpler and safer to just open it each time individually).

To turn this around, what's the big benefit you see in keeping it open?

**Comment by utezduyar** [comment]
Thank for explaining. 

I thought it would be a performance benefit but maybe it is not big of a deal to send 1000 messages to console.

Maybe it is better only to forward important messages to console for production code.

**Comment by evverx** [comment]
@poettering , this is the second attempt to leave the console open (see also https://github.com/systemd/systemd/pull/4262/files).
Shouldn't we document that SAK-issue somewhere?

**Comment by poettering** [comment]
@evverx yeah, i figure we should add some comments about the SAK case to the appropriate places in the sources. (i.e. once for PID 1 and once for journald)

**Comment by poettering** [comment]
@evverx added two comments about this now, waiting in #4414. Please have a look.

I figure we can close this one now.

**Pull request closed without merging**
