### PR TITLE
Add pam_namespace to user@.service pam stack

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Review by Edu4rdSHL — APPROVED** [review]

**Comment by poettering** [comment]
or to ask this differently: do debian/ubuntu/suse have pam namespace in their default stacks?

**Comment by keszybz** [comment]
Debian doesn't use our file at all. It has a completely different setup that replaces most of the file by `include @common-account` and so on. The file here is supposed to be something that is provides a functional minimum. Obviously we can't accommodate everything, but including pam_namespace in this place is the correct thing for most users and thus it seems suitable for upstream.

**Comment by Werkov** [comment]
IIUC the reasoning in the commit, the need of `pam_namespace` is induced by presence of `pam_namespace` in other PAM stacks, which by itself is likely caused by some `common-*` files in the particular's distro stack. I.e. it'd make more sense to invoke `pam_namespace` in a unified way (i.e. from the common parts) and stick to the minimality of the shipped file.

FWIW, SUSE overrides usptream `systemd-user` anyway.

0.02€

**Comment by pbrezina** [comment]
I am not that familiar with pam_namespace and I did not do any attempts to try it, but from the man page it sounds to me that if I log in as user `foo` and the `su bar` and pam_namespace runs for both log in and su then I will end up with too different namespaces, one for `foo` and one for `bar`. My expectation is that the namespace for user `foo` is kept. Therefore I think it should not be placed in common pam stack.

If we get the same namespace, then yes, we probably can include it in common stack.

**Comment by keszybz** [comment]
> IIUC the reasoning in the commit, the need of `pam_namespace` is induced by presence of `pam_namespace` in other PAM stacks, which by itself is likely caused by some `common-*` files in the particular's distro stack. I.e. it'd make more sense to invoke `pam_namespace` in a unified way (i.e. from the common parts) and stick to the minimality of the shipped file.

> if I log in as user `foo` and then `su bar` and pam_namespace runs for both log in and su then I will end up with two different namespaces, one for `foo` and one for `bar`. My expectation is that the namespace for user `foo` is kept. Therefore I think it should not be placed in common pam stack.

It's as @pbrezina said: pam_namespace should not be included in the common part of the stack, because we don't want to create a separate environment when su/sudo/runuser and such are called. pam_namespace is included in the non-shared part of the stack by the distros that support it. This pull request adds it to our config file to show the distros where and how it should be included. If they use our config file with no changes, it'll do the right thing. If they modify our config file, it makes it easier to not forget to put pam_namespace in the right place (e.g. Fedora). And if they replace our config file completely (Debian, SUSE), it doesn't matter.

I added a bit more rationale to the commit message and updated without any other changes.

**Comment by keszybz** [comment]
Can we get this merged? It makes life easier for Fedora and derivatives and doesn't matter for the distros which don't use the upstream file at all.

**Comment by poettering** [comment]
So I take it, unless people actually write some pam_namespace config this is basically a NOP?

i.e. I am concerned for distros that neither inherit from fedora nor from other distros, and just use naked systemd built from source. If this is just a NOP there, I guess it's fine. Otherwise not

**Comment by keszybz** [comment]
> So I take it, unless people actually write some pam_namespace config this is basically a NOP?

Yes.

> i.e. I am concerned for distros that neither inherit from fedora nor from other distros, and just use naked systemd built from source. If this is just a NOP there, I guess it's fine. Otherwise not

Yes. If you have `pam_namespace.so` installed, without a config file this is a noop. If you have a config file installed, then this fixes an bug. It would create a problem if `pam_namespace.so` was not installed (like any configuration referring to a module that does not exist). But `pam_namespace.so` is part of upstream pam and it's generally part of the main pam package everywhere I checked (Fedora/RHEL/CentOS, Debian/Ubuntu, Arch). In this regard, it is very similar to the `pam_keyinit.so` config we added a while back.

**Review by bluca — APPROVED** [review]
this seems sensible to me

**Pull request merged**
