### PR TITLE
test: drop to use hardcoded device '/sys/class/net/lo'

### LINKED ISSUE #10431: test-suite failure: test-udev-device-thread                 FAIL
Trying to build git master in Debian sid buildd chroot I get the following failure:
```
434/494 test-udev-device-thread                 FAIL     0.02 s (killed by signal 6 SIGABRT)

--- command ---
PATH='/build/systemd-239+upstream20181016/build-deb:/usr/sbin:/usr/bin:/sbin:/bin' SYSTEMD_KBD_MODEL_MAP='/build/systemd-239+upstream20181016/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/build/systemd-239+upstream20181016/src/locale/language-fallback-map' /build/systemd-239+upstream20181016/build-deb/test-udev-device-thread
--- stderr ---
Assertion 'loopback = udev_device_new_from_syspath(NULL, "/sys/class/net/lo")' failed at ../src/libsystemd/sd-device/test-udev-device-thread.c:26, function main(). Aborting.
-------
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #10431.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @mbiebl.

**Comment by yuwata** [comment]
The situation reported in the issue #10431 seems strange, but dropping the hardcoded device may be nice, no?

**Comment by mbiebl** [comment]
the buildd chroot environment is using cowbuilder
```
├─/var/cache/pbuilder/build/cow.17572/proc        /proc          proc                rw,relatime
├─/var/cache/pbuilder/build/cow.17572/sys         sysfs          sysfs               rw,nosuid,nodev,noexec,relatime
├─/var/cache/pbuilder/build/cow.17572/dev/shm     tmpfs          tmpfs               rw,relatime
├─/var/cache/pbuilder/build/cow.17572/dev/pts     devpts         devpts              rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666
├─/var/cache/pbuilder/build/cow.17572/dev/ptmx    devpts[/ptmx]  devpts              rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666
└─/var/cache/pbuilder/build/cow.17572/dev/console devpts[/0]     devpts              rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000
```
Inside the chroot I have
```
# ls -la /sys/class/net/lo/
total 0
drwxr-xr-x  5 root root    0 Oct 17 13:15 .
drwxr-xr-x 12 root root    0 Oct 17 13:11 ..
-r--r--r--  1 root root 4096 Oct 17 13:11 addr_assign_type
-r--r--r--  1 root root 4096 Oct 17 13:12 addr_len
-r--r--r--  1 root root 4096 Oct 17 13:11 address
-r--r--r--  1 root root 4096 Oct 17 13:15 broadcast
-rw-r--r--  1 root root 4096 Oct 17 13:15 carrier
-r--r--r--  1 root root 4096 Oct 17 13:15 carrier_changes
-r--r--r--  1 root root 4096 Oct 17 13:15 carrier_down_count
-r--r--r--  1 root root 4096 Oct 17 13:15 carrier_up_count
-r--r--r--  1 root root 4096 Oct 17 13:11 dev_id
-r--r--r--  1 root root 4096 Oct 17 13:15 dev_port
-r--r--r--  1 root root 4096 Oct 17 13:15 dormant
-r--r--r--  1 root root 4096 Oct 17 13:15 duplex
-rw-r--r--  1 root root 4096 Oct 17 13:15 flags
-rw-r--r--  1 root root 4096 Oct 17 13:15 gro_flush_timeout
-rw-r--r--  1 root root 4096 Oct 17 13:15 ifalias
-r--r--r--  1 root root 4096 Oct 17 13:11 ifindex
-r--r--r--  1 root root 4096 Oct 17 13:15 iflink
-r--r--r--  1 root root 4096 Oct 17 13:15 link_mode
-rw-r--r--  1 root root 4096 Oct 17 13:15 mtu
-r--r--r--  1 root root 4096 Oct 17 13:11 name_assign_type
-rw-r--r--  1 root root 4096 Oct 17 13:15 netdev_group
-r--r--r--  1 root root 4096 Oct 17 13:12 operstate
-r--r--r--  1 root root 4096 Oct 17 13:11 phys_port_id
-r--r--r--  1 root root 4096 Oct 17 13:15 phys_port_name
-r--r--r--  1 root root 4096 Oct 17 13:15 phys_switch_id
drwxr-xr-x  2 root root    0 Oct 17 13:15 power
-rw-r--r--  1 root root 4096 Oct 17 13:15 proto_down
drwxr-xr-x  4 root root    0 Oct 17 13:15 queues
-r--r--r--  1 root root 4096 Oct 17 13:15 speed
drwxr-xr-x  2 root root    0 Oct 17 13:15 statistics
lrwxrwxrwx  1 root root    0 Oct 17 13:11 subsystem -> ../../../../class/net
-rw-r--r--  1 root root 4096 Oct 17 13:15 tx_queue_len
-r--r--r--  1 root root 4096 Oct 17 13:11 type
-rw-r--r--  1 root root 4096 Oct 17 13:11 uevent

# mount
/proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,relatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
devpts on /dev/ptmx type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
```

**Comment by mbiebl** [comment]
This patch doesn't really fix #10431, see my recent findings

**Comment by yuwata** [comment]
Let's close this, as this doesn't help #10431.

**Pull request closed without merging**
