### PR TITLE
Don't unescape paths from libmount

### PR DESCRIPTION
**Pull request by keszybz**
The first three commits from #12218.

### CODE REVIEW

**Comment by keszybz** [comment]
Updated. The test is updated to ignore errors more consistently. No other changes.

**Comment by keszybz** [comment]
`Assertion 'r == 0' failed at ../src/test/test-libmount.c:43, function test_libmount_unescaping_one(). Aborting.`

Argh, it doesn't want to parse the line with empty source at all. I'll update the test once more.

**Comment by keszybz** [comment]
bionic-i386: "FAILED TESTS:  test/TEST-30-ONCLOCKCHANGE" — unrelated.

**Comment by evverx** [comment]
The test fails under Valgrind and ASan when libmount-2.32.1-1.fc29 is used:
```
==8653==
==8653== HEAP SUMMARY:
==8653==     in use at exit: 208 bytes in 1 blocks
==8653==   total heap usage: 111 allocs, 110 frees, 54,807 bytes allocated
==8653==
==8653== 208 bytes in 1 blocks are definitely lost in loss record 1 of 1
==8653==    at 0x483AB1A: calloc (vg_replace_malloc.c:762)
==8653==    by 0x4B97336: mnt_new_fs (in /usr/lib64/libmount.so.1.1.0)
==8653==    by 0x4BA1F6C: mnt_table_parse_stream (in /usr/lib64/libmount.so.1.1.0)
==8653==    by 0x4014C5: test_libmount_unescaping_one (test-libmount.c:30)
==8653==    by 0x401E65: test_libmount_unescaping (test-libmount.c:93)
==8653==    by 0x401EA5: main (test-libmount.c:116)
==8653==
==8653== LEAK SUMMARY:
==8653==    definitely lost: 208 bytes in 1 blocks
==8653==    indirectly lost: 0 bytes in 0 blocks
==8653==      possibly lost: 0 bytes in 0 blocks
==8653==    still reachable: 0 bytes in 0 blocks
==8653==         suppressed: 0 bytes in 0 blocks
==8653==
==8653== For counts of detected and suppressed errors, rerun with: -v
==8653== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

Other that that I'm wondering why the test for `libmount` should be kept in the repository? Wouldn't it be better to keep it there? cc @karelzak

**Comment by evverx** [comment]
> Wouldn't it be better to keep it there?

It probably would if `util-linux` was built with ASan but looking at https://travis-ci.org/karelzak/util-linux/builds/518734784?utm_source=github_status&utm_medium=notification I can't find anything like that. @karelzak would it be possible to also compile `util-linux` with ASan on Travis CI? Judging by https://github.com/systemd/systemd/issues/8504, it doesn't seems to be the first time memory leaks in `libmount` have been discovered.

**Comment by karelzak** [comment]
I'll think about it. We have --enable-asan, but it's unused on travis for now. Need to test it a little bit.

**Comment by karelzak** [comment]
BTW, where in the test is mnt_unref_table() ?

Anyway, we have regression test for both use cases in upstream tree:
empty source: https://github.com/karelzak/util-linux/blob/master/tests/ts/libmount/files/mountinfo_nosrc
\r in path: https://github.com/karelzak/util-linux/blob/master/tests/ts/libmount/files/mountinfo

**Comment by poettering** [comment]
@karelzak we use gcc's cleanup attribute heavily in systemd, i.e. `_cleanup_(mnt_free_tablep)` is applied to the `table` variable, which means the table is freed automatically when it leaves scope.

**Comment by karelzak** [comment]
> @karelzak we use gcc's cleanup attribute heavily in systemd, i.e. `_cleanup_(mnt_free_tablep)` is applied to the `table` variable, which means the table is freed automatically when it leaves scope.

Ah, I've read only end of the function. Sorry.

**Pull request merged**
