### PR TITLE
terminal-util: temporarily turn on nonblocking mode when waiting for …

### PR DESCRIPTION
**Pull request by poettering**
…ANSI seq responses

We never know, maybe there's some spurious POLLIN and read() will fail with EAGAIN even though we saw POLLIN. Handle that.

(this can happen if we area not the only process reading from the tty, or in case of hups and such).

Fixes: #35499

### CODE REVIEW

**Comment by AdamWill** [comment]
the i386 build failure is interesting - my scratch build of 257 with this patch applied failed the same way in koji, https://kojipkgs.fedoraproject.org/work/tasks/7291/126807291/build.log .

**Comment by poettering** [comment]
@bluca did you forget to post your review comments? you set the orange label, but i see nothing that wasn't right?

**Comment by bluca** [comment]
> @bluca did you forget to post your review comments? you set the orange label, but i see nothing that wasn't right?

Ah sorry, I wanted to link the issue and forgot - it's been reported that the problem still happens with this patch: https://github.com/systemd/systemd/issues/35499#issuecomment-2543170557

**Comment by poettering** [comment]
that's not a review, and not really actionable? just a random screenshot?

it appears that this PR generally fixes *something*, and quite objectively I think it's what we should be doing. If there's more to fix, fine, but not a reason to block this PR.

**Comment by bluca** [comment]
If it's not solely intended to solve that issue then sure, no problem. I thought the change was solely an attempt to fix the boot hang, and it doesn't work for that as reported sadly

**Comment by poettering** [comment]
I pushed a modified version now. Instead of toggling the fd's O_NONBLOCK it reopens the tty in a separate fd, and sets O_NONBLOCK on that.

That should be typically the better option, since the input fd might potentially be shared with other code or even other processes which might be confused if O_NONBLOCK is suddenly on.

**Comment by bluca** [comment]
> I pushed a modified version now. Instead of toggling the fd's O_NONBLOCK it reopens the tty in a separate fd, and sets O_NONBLOCK on that.
> 
> That should be typically the better option, since the input fd might potentially be shared with other code or even other processes which might be confused if O_NONBLOCK is suddenly on.

Thanks, I'll ask in the issue to try this new version, fingers crossed

**Comment by poettering** [comment]
> If it's not solely intended to solve that issue then sure, no problem. I thought the change was solely an attempt to fix the boot hang, and it doesn't work for that as reported sadly

It certainly is supposed to address that issue. But if it solves it fully or only partially I can't tell you. That's a different question though from figuring out whether it should be merged or not.

At this point, this appears to fix the issue for many folks, but not for all, but there's no useful data available for that still failing case, it might be an entirely different case who knows.

**Comment by bluca** [comment]
> > If it's not solely intended to solve that issue then sure, no problem. I thought the change was solely an attempt to fix the boot hang, and it doesn't work for that as reported sadly
> 
> It certainly is supposed to address that issue. But if it solves it fully or only partially I can't tell you. That's a different question though from figuring out whether it should be merged or not.
> 
> At this point, this appears to fix the issue for many folks, but not for all, but there's no useful data available for that still failing case, it might be an entirely different case who knows.

Well it's a race condition somewhere, so it's really hard to say whether it fixes the issue for some of the reporters for real, or it was just luck. There's at least one report of a repro, so that's enough to say it's not solved yet. But again, if you think it's a good change to have regardless, no problem in merging the PR. Just trying to track the original regression, that's all.

**Pull request merged**
