### PR TITLE
force PropertiesChanged bus signal on all unit state changes

### PR DESCRIPTION
**Pull request by poettering**
A fix for #10185

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

**Comment by keszybz** [comment]
TEST-03-JOBS fails:
```
[  OK  ] Started unstoppable.service.
+ cat
+ cat
++ date -u +%s
+ START_SEC=1543409550
+ systemctl start --wait wait2.service
[  OK  ] Started Wait for 2 seconds.
++ date -u +%s
+ END_SEC=1543409550
+ ELAPSED=0
+ [[ 0 -ge 2 ]]
+ exit 1
[FAILED] Failed to start Testsuite service.
See 'systemctl status testsuite.service' for details.
         Starting End the test...
```
(It fails with the second commit, but not with the first.)

**Comment by poettering** [comment]
I force pushed a new version now, that hopefully fixes the CI. At least here locally all tests pass fine now.

**Comment by poettering** [comment]
(unfortunately this new version is a bit larger, as there was quite a bit borked that caused the CI failure)

**Comment by keszybz** [comment]
Still LGTM.

I see that we don't print anything if `--wait` fails, but its unrelated, this PR does not change this.

**Comment by muktupavels** [comment]
This seems to have introduced regression. In Unity and GNOME Flashback logout has stopped working after upgrading to systemd 240. Both sessions are started with:
`systemctl --user start --wait target`

After some debugging I found that there was 3 `PropertiesChanged` signals:
- ActiveState = active, Job = { 338, /org/freedesktop/systemd1/job/338 }
- ActiveState = active, Job = { 338, /org/freedesktop/systemd1/job/338 }
- ActiveState = inactive, Job = { 338, /org/freedesktop/systemd1/job/338 }

After that followed also `JobRemoved` signal for 338, but that did not cause `PropertiesChanged` signal. Now we have stopped target with systemctl still waiting when that will happen...

After looking at changes I found that in `src/core/job.c` was added explicit `unit_add_to_dbus_queue` call to notify that Job property has changed. I added same call in `job_uninstall` before `unit_add_to_gc_queue` and after rebuild I got 4th `PropertiesChanged` signal with expected `ActiveState = inactive, Job { 0 }`.

@poettering @keszybz Does that makes any sense? Should I open new issue and/or merge request (if  adding `unit_add_to_dbus_queue` to `job_uninstall` is right thing)?

**Comment by yuwata** [comment]
I am not sure whether this is a regression or not, but please open a new issue. Otherwise, we easily forget your comment. Thank you.

**Pull request merged**
