### PR TITLE
test: temporary disable TEST-36-NUMAPOLICY and TEST-50-DISSECT on ubuntu ppc64el CI

### PR DESCRIPTION
**Pull request by yuwata**
These tests are quite unstable on Ubuntu ppc64el.
In these tests PID1 segfaults, but no coredump is observed. Unfortunately, Ubuntu ppc64el CI environment is not reliable, and there is mostly nothing we can do, at least right now. Let's disable the tests on the environment.

https://autopkgtest.ubuntu.com/results/autopkgtest-jammy-upstream-systemd-ci-systemd-ci/jammy/ppc64el/s/systemd-upstream/20230813_023411_de0f4@/log.gz

From TEST-36-NUMAPOLICY:
```
Aug 13 10:01:26 H kernel: systemd[1]: segfault (11) at 7ce720aea268 nip 7ce7e7857de0 lr 7ce7e7858284 code 1 in libsystemd-core-254.so[7ce7e76e0000+220000]
Aug 13 10:01:26 H kernel: systemd[1]: code: 3cc2fff5 3c62fff3 38a0039c 388946c3 38c65f58 386361f8 4bed5e59 e8410018
Aug 13 10:01:26 H kernel: systemd[1]: code: 60000000 e9428470 81230008 7d291ef4 <7d2a482a> e98900d0 7d8903a6 4e800421
Aug 13 10:01:26 H systemd[1]: Caught <SEGV> from PID 548315752.
Aug 13 10:01:27 H systemd-coredump[442]: Due to PID 1 having crashed coredump collection will now be turned off.
Aug 13 10:01:28 H systemd-journald[320]: Failed to write entry to /var/log/journal/eda8443379704fcaa4d04cbcb3faa52a/system.journal (47 items, 9330445 bytes) despite vacuuming, ignoring: Argument list too long
Aug 13 10:01:27 H systemd[1]: Caught <SEGV>, dumped core as pid 441.
```

From TEST-50-DISSECT:
```
Aug 13 10:33:46 H systemd[1]: Caught <SEGV> from PID -1083519179.
Aug 13 10:33:46 H systemd-coredump[1066]: Due to PID 1 having crashed coredump collection will now be turned off.
Aug 13 10:33:47 H systemd-journald[318]: Failed to write entry to /var/log/journal/eda8443379704fcaa4d04cbcb3faa52a/system.journal (47 items, 10649526 bytes) despite vacuuming, ignoring: Argument list too long
Aug 13 10:33:47 H systemd[1]: Caught <SEGV>, dumped core as pid 1065.
Aug 13 10:33:47 H systemd[1]: Freezing execution.
```

### CODE REVIEW

**Comment by yuwata** [comment]
https://autopkgtest.ubuntu.com/results/autopkgtest-jammy-upstream-systemd-ci-systemd-ci/jammy/ppc64el/s/systemd-upstream/20230812_173246_7b643@/log.gz

Also, TEST-29-PORTABLE and TEST-55-OOMD may need to be disabled.

**Comment by yuwata** [comment]
```
Aug 13 01:23:49 H systemd-coredump[389]: [🡕] Process 388 (systemd) of user 0 dumped core.
                                         
                                         Stack trace of thread 388:
                                         #0  0x00007980c4cd5fc0 syscall (libc.so.6 + 0x165fc0)
                                         #1  0x00007980c504277c propagate_signal (libsystemd-shared-254.so + 0x24277c)
                                         #2  0x000009eaa4e21e04 n/a (systemd + 0x11e04)
                                         #3  0x00007980c5560444 __kernel_sigtramp_rt64 (linux-vdso64.so.1 + 0x444)
                                         #4  0x00007980c5417dc0 unit_active_state (libsystemd-core-254.so + 0x177dc0)
                                         #5  0x00007980c5411140 n/a (libsystemd-core-254.so + 0x171140)
                                         #6  0x00007980c5412180 transaction_activate (libsystemd-core-254.so + 0x172180)
                                         #7  0x00007980c53b1f38 manager_add_job (libsystemd-core-254.so + 0x111f38)
                                         #8  0x00007980c53fd5dc n/a (libsystemd-core-254.so + 0x15d5dc)
                                         #9  0x00007980c5403c20 n/a (libsystemd-core-254.so + 0x163c20)
                                         #10 0x00007980c514d660 n/a (libsystemd-shared-254.so + 0x34d660)
                                         #11 0x00007980c514da08 sd_event_dispatch (libsystemd-shared-254.so + 0x34da08)
                                         #12 0x00007980c5151ed8 sd_event_run (libsystemd-shared-254.so + 0x351ed8)
                                         #13 0x00007980c53b9330 manager_loop (libsystemd-core-254.so + 0x119330)
                                         #14 0x000009eaa4e18a5c n/a (systemd + 0x8a5c)
                                         #15 0x00007980c4b9d6a4 n/a (libc.so.6 + 0x2d6a4)
                                         #16 0x00007980c4b9d888 __libc_start_main (libc.so.6 + 0x2d888)
                                         ELF object binary architecture: PowerPC64
Aug 13 01:23:50 H systemd-user-runtime-dir[387]: Failed to acquire runtime directory size, ignoring: Transport endpoint is not connected
Aug 13 01:23:50 H systemd-user-runtime-dir[387]: Failed to acquire number of inodes for runtime directory, ignoring: Transport endpoint is not connected
Aug 13 01:23:49 H systemd[1]: Caught <SEGV>, dumped core as pid 388.
Aug 13 01:23:49 H (d-logind)[385]: Remounted /run/systemd/mount-rootfs/run/credentials.
Aug 13 01:23:49 H systemd[1]: Freezing execution.
```

**Comment by mrc0mmand** [comment]
I think all the issues are related to #25091 - @bluca I guess there are no news about a possible fix, right?

**Comment by bluca** [comment]
Yeah I pinged on launchpad, but there were no news. This is not specific to any one test, but anything that runs in qemu can crash like that due to apparent memory corruption.

**Comment by yuwata** [comment]
Ah, then how about to completely disable qemu on PPC64 CI?

**Comment by bluca** [comment]
Yeah we'd lose a bit of coverage, but not much we can do. Not sure it can be done globally though, probably needs to be done for all test cases individually

**Comment by yuwata** [comment]
https://salsa.debian.org/systemd-team/systemd/-/merge_requests/206

**Pull request closed without merging**
