### PR TITLE
build: only install tmpfiles.d/systemd-remote.conf when necessary

### PR DESCRIPTION
**Pull request by fbuihuu**
Also only include the relevant parts for systemd-journal-remote and
systemd-journal-upload when needed.

### CODE REVIEW

**Comment by keszybz** [comment]
Merged as 5e354b22520bbb02e5079672a6f97fe05f185d63 with a whitespace fixup.

**Comment by fbuihuu** [comment]
@keszybz, unfortunately it's broken (it was due to some last second changes :( )

I submitted a fix through #6061.

Sorry for the troubles.

**Comment by keszybz** [comment]
Heh, I only tested the meson build ;)

**Comment by fbuihuu** [comment]
yeah that's probably what people will do once they'll try the meson build.

meson is soooooooo much better than the autotools cr!#@p ;)

**Pull request closed without merging**
