### PR TITLE
resolved: don't filter extra DNS stubs on parse

### PR DESCRIPTION
**Pull request by poettering**
…ers"

This reverts commit 0ad4efb14beea9148838a0d974821e3b98cafc47.

See
https://github.com/systemd/systemd/pull/20559#issuecomment-1028011030
for reasoning.

### CODE REVIEW

**Comment by keszybz** [comment]
> …ers"
> 
> This reverts commit [0ad4efb](https://github.com/systemd/systemd/commit/0ad4efb14beea9148838a0d974821e3b98cafc47).
> 
> See [#20559 (comment)](https://github.com/systemd/systemd/pull/20559#issuecomment-1028011030) for reasoning.

Before I follow the link, a meta-comment on the work-flow: please paste the actual justification for a commit in the commit message. Github might go away at some point, links breaks, comments can be removed or edited, and foremost, github links are not visible in git log or gitk.

**Comment by keszybz** [comment]
Makes sense. But please adjust the commit message as requested above.

**Comment by poettering** [comment]
Force pushed new version, with the relevant comment pasted in. Merging.

**Pull request merged**
