### PR TITLE
network: Add support to configure protodown for the interface

### PR DESCRIPTION
**Pull request by ssahani**

### CODE REVIEW

**Review by yuwata — COMMENTED** [review]
Maybe .link file should have this option, instead of .network file...

**Comment by ssahani** [comment]
> Maybe .link file should have this option, instead of .network file...

These are same as group/multicast/allmulticast etc. Hence it should be here. Thanks for the review .ptal

**Comment by yuwata** [comment]
Same here. In what sense "these are the same"? Though, I do not have any strong opinion about that. Just I want to know.

**Comment by ssahani** [comment]
> Same here. In what sense "these are the same"? Though, I do not have any strong opinion about that. Just I want to know.

How can you set this via .link file ?

**Comment by yuwata** [comment]
> > Same here. In what sense "these are the same"? Though, I do not have any strong opinion about that. Just I want to know.
> 
> How can you set this via .link file ?

Almost the same code you implemented in networkd, that is, by using netlink command `RTM_SETLINK`.

**Comment by ssahani** [comment]
> > > Same here. In what sense "these are the same"? Though, I do not have any strong opinion about that. Just I want to know.
> > 
> > 
> > How can you set this via .link file ?
> 
> Almost the same code you implemented in networkd, that is, by using netlink command `RTM_SETLINK`.

Then why it is not done yet ?

**Comment by poettering** [comment]
I don't get this. Can you describe a real usecase for this? This appears to be supposed to be a notification of some kind, but setting it to on unconditionally from a .network file sounds wrong? Please, let's think twice about hte options we expose here!

**Comment by poettering** [comment]
So I am still pretty sure that this should not be configurable. Let's close this. We can reopen if a usecase appears!

**Pull request closed without merging**
