### PR TITLE
core: reenable nosuid mount flag when NoNewPrivileges=yes

### PR DESCRIPTION
**Pull request by yuwata**
But only when SELinux is disabled.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @topimiettinen and @doverride.

**Comment by doverride** [comment]
Fine with me. Not sure why you all are so eager to push this through but then again if this makes you all feel more secure then by all means.

**Comment by keszybz** [comment]
Yeah, I think this is a reasonable workaround. We shouldn't block useful functionality on selinux quirks.

**Comment by doverride** [comment]
> Yeah, I think this is a reasonable workaround. We shouldn't block useful functionality on selinux quirks.

Maybe, but this is closer to *redundant* functionality than it is to *useful* functionality.

**Pull request merged**
