### PR TITLE
udev: ignore additional newline at the end on verify

### LINKED ISSUE #19314: fileio.c: verify_file broken for sysfs writes on s390
**systemd version the issue has been seen with**
 >246 

**Used distribution**
 > SUSE Linux Enterprise Server 15 SP3

**Linux kernel version used** (`uname -a`)

 > ` Linux s390vsl004 5.3.18-53-default #1 SMP Wed Mar 31 13:11:52 UTC 2021 (85a0bf4) s390x s390x s390x GNU/Linux`

**CPU architecture issue was seen on**
 > s390x

**Expected behaviour you didn't see**
 > no error message on multiple writes into sysfs files, for example:
> /sys/devices/qeth/0.0.0800/portno

**Unexpected behaviour you saw**
 >Apr 13 16:10:33 s390vsl004 systemd-udevd[807]: 0.0.0800: /etc/udev/rules.d/41-qeth-0.0.0800.rules:18 Failed to write ATTR{/sys/devices/qeth/0.0.0800/portno}, ignoring: Operation not permitted
>Apr 13 16:10:33 s390vsl004 systemd-udevd[807]: 0.0.0800: /etc/udev/rules.d/41-qeth-0.0.0800.rules:19 Failed to write ATTR{/sys/devices/qeth/0.0.0800/layer2}, ignoring: Operation not permitted
>Apr 13 16:10:33 s390vsl004 systemd-udevd[807]: 0.0.0800: /etc/udev/rules.d/41-qeth-0.0.0800.rules:20 Failed to write ATTR{/sys/devices/qeth/0.0.0800/online}, ignoring: Invalid argument

Actually it is normal that writes to those sysfs files only succeed first time and subsequent writes fail.
verify_file should be able to cope with that since the same value is written again. 

**Steps to reproduce the problem**
 > journalctl -axb | grep 'Failed to write'

 > udevadm test /sys/devices/qeth/0.0.0800
 > (requires udev rules generated by chzdev which is done during installation)

**Additional program output to the terminal or log subsystem illustrating the issue**

with the following instrumentation:

```
diff --git a/src/basic/fileio.c b/src/basic/fileio.c
index c3d55d209a..690a3ae40e 100644
--- a/src/basic/fileio.c
+++ b/src/basic/fileio.c
@@ -284,8 +284,10 @@ fail:
          * contents in place already. If so, eat up the error. */
 
         q = verify_file(fn, line, !(flags & WRITE_STRING_FILE_AVOID_NEWLINE));
-        if (q <= 0)
+        if (q <= 0) {
+                log_warning("tblume: verify_file failed for %s retval is %d returning %d", fn, q, r);
                 return r;
+        }
 
         return 0;
 }
@@ -351,8 +353,10 @@ int verify_file(const char *fn, const char *blob, bool accept_extra_nl) {
         if (ferror(f))
                 return errno_or_else(EIO);
 
-        if (k != l && k != l + accept_extra_nl)
+        if (k != l && k != l + accept_extra_nl) {
+                log_warning("tblume: k !=l succeeded, k is %ld, l is %ld l + newline is %ld", k, l, (l + accept_extra_nl));
                 return 0;
+        }
         if (memcmp(buf, blob, l) != 0)
                 return 0;
         if (k > l && buf[l] != '\n')
```

I get the udevadm test output:

```
path '[ccwgroup/0.0.0800]portno' is '/sys/devices/qeth/0.0.0800/portno'
0.0.0800: /etc/udev/rules.d/41-qeth-0.0.0800.rules:18 ATTR '/sys/devices/qeth/0.0.0800/portno' writing '0'
tblume: k !=l succeeded, k is 2, l is 1 l + newline is 1
tblume: verify_file failed for /sys/devices/qeth/0.0.0800/portno retval is 0 returning -1
0.0.0800: /etc/udev/rules.d/41-qeth-0.0.0800.rules:18 Failed to write ATTR{/sys/devices/qeth/0.0.0800/portno}, ignoring: Operation not permitted
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #19314.

### CODE REVIEW

**Comment by poettering** [comment]
lgtm

**Comment by bluca** [comment]
`test-sd-device` crashed, could you please double check that it's not related? Don't remember seeing this before:

```
19:17:38                 #0  0x00007f17fcbacef5 raise (libc.so.6 + 0x3cef5)
19:17:38                 #1  0x00007f17fcb96862 abort (libc.so.6 + 0x26862)
19:17:38                 #2  0x00007f17fce96d0c log_assert_failed (libsystemd-shared-248.so + 0x14dd0c)
19:17:38                 #3  0x0000556fc7c54cc7 test_sd_device_enumerator_filter_subsystem_one (test-sd-device + 0x2cc7)
19:17:38                 #4  0x0000556fc7c54fa5 test_sd_device_enumerator_filter_subsystem (test-sd-device + 0x2fa5)
19:17:38                 #5  0x0000556fc7c554b2 main (test-sd-device + 0x34b2)
19:17:38                 #6  0x00007f17fcb97b25 __libc_start_main (libc.so.6 + 0x27b25)
19:17:38                 #7  0x0000556fc7c5435e _start (test-sd-device + 0x235e)
```

**Comment by yuwata** [comment]
@bluca This does not change anything in sd-device, hence the failure should not related. @mrc0mmand Could you restart CentOS CI (Arch Linux)?

**Comment by yuwata** [comment]
Note, if I remember correctly, `test-sd-device` may fail some devices are added or removed during the test is running.

**Comment by bluca** [comment]
bionic-i386 is the usual timeout in `test-process-util`

**Pull request merged**
