### PR TITLE
Refuse aliases to non-aliasable units in more places

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by evverx** [comment]
https://github.com/systemd/systemd/pull/2735 passed (there is no crash)!

```
# findmnt /
TARGET SOURCE    FSTYPE OPTIONS
/      /dev/sda1 ext4   ro,relatime,data=ordered

# journalctl --no-hostname -b | grep root.mount
Apr 29 16:42:56 systemd[1]: root.mount: Unit type of root.mount does not support alias names, refusing loading via symlink.
Apr 29 16:42:56 systemd[1]: root.mount: Failed to load configuration: Too many levels of symbolic links
Apr 29 16:42:57 systemd[1]: root.mount: Collecting.

# journalctl --no-hostname -b | grep -- -.mount
Apr 29 16:42:56 systemd[1]: -.mount: Changed dead -> mounted
```

But `systemctl enable` doesn't reject buggy units:

```
# cat <<'EOF' >/etc/systemd/system/-.mount
[Unit]
Before=local-fs.target

[Mount]
What=/dev/sda1
Where=/
Type=ext4
Options=errors=remount-ro,noatime

[Install]
WantedBy=local-fs.target
Alias=root.mount
EOF

# systemctl enable -- -.mount
Created symlink /etc/systemd/system/root.mount, pointing to /etc/systemd/system/-.mount.
Created symlink /etc/systemd/system/local-fs.target.wants/-.mount, pointing to /etc/systemd/system/-.mount.

# echo $?
0

# systemctl start root.mount
Failed to start root.mount: Unit root.mount not found.

# journalctl -b --no-hostname | grep -i root.mount
Apr 29 16:59:09 systemd[1]: root.mount: Unit type of root.mount does not support alias names, refusing loading via symlink.
Apr 29 16:59:09 systemd[1]: root.mount: Failed to load configuration: Too many levels of symbolic links
Apr 29 16:59:09 systemd[1]: root.mount: Trying to enqueue job root.mount/start/replace
Apr 29 16:59:09 systemd[1]: Sent message type=error sender=n/a destination=n/a object=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 error=Unit root.mount not found.
Apr 29 16:59:09 systemd[1]: Failed to process message [type=method_call sender=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=StartUnit signature=ss]: Unit root.mount not found.
```

`systemd-analyze verify` couldn't detect that problem too:

```
# systemd-analyze verify /etc/systemd/system/-.mount
# echo $?
0
```

**Comment by evverx** [comment]
Hm...

```
# findmnt /
TARGET SOURCE    FSTYPE OPTIONS
/      /dev/sda1 ext4   ro,relatime,data=ordered
```

should be

```
/      /dev/sda1 ext4   rw,noatime,errors=remount-ro,data=ordered
```

seems like `systemd-remount-fs.service` doesn't respect mount units:

```
# journalctl -b --no-hostname | grep remount
Apr 29 17:42:13 systemd[1]: systemd-remount-fs.service: Installed new job systemd-remount-fs.service/start as 42
Apr 29 17:42:13 systemd[1]: systemd-remount-fs.service: ConditionPathExists=/etc/fstab failed.
Apr 29 17:42:13 systemd[1]: systemd-remount-fs.service: Starting requested but condition failed. Not starting unit.
Apr 29 17:42:13 systemd[1]: systemd-remount-fs.service: Job systemd-remount-fs.service/start finished, result=done
```

**Comment by poettering** [comment]
@evverx systemd-analyze currently doesn't verify the [Install] section at all. It probably should, but that's really something for another PR... Similar, "systemctl enable" doesn't know a thing about the unit types it operates for, hence Alias= won't fail for these types. And yeah, we should fix that, but that's for another PR too I am sure.

And yes, systemd-remount-fs is really just about apply /etc/fstab, and that's documented. It wouldn't exist otherwise.

Hence I think all is good for now?

**Comment by evverx** [comment]
>  It probably should, but that's really something for another PR... 
> but that's for another PR too I am sure

I agree

> Hence I think all is good for now?

There is no crash. It's good:)

But I'm not sure about that noop-`-.mount`

```
# systemctl status --no-pager / # note mountinfo (not -.mount)
● -.mount - /
   Loaded: loaded (/proc/self/mountinfo; enabled; vendor preset: enabled)
   Active: active (mounted) since Fri 2016-04-29 18:56:11 UTC; 32s ago
    Where: /
     What: /dev/sda1
    Tasks: 0 (limit: 512)
   CGroup: /system.slice/-.mount

# systemctl cat --no-pager /
# /etc/systemd/system/-.mount
[Unit]
Before=local-fs.target

[Mount]
What=/dev/sda1
Where=/
Type=ext4
Options=errors=remount-ro,noatime

[Install]
WantedBy=local-fs.target
Alias=root.mount

# systemctl daemon-reexec

# systemctl status --no-pager /
● -.mount - /
   Loaded: loaded (/etc/systemd/system/-.mount; enabled; vendor preset: enabled)
   Active: active (mounted) since Fri 2016-04-29 18:56:11 UTC; 1min 12s ago
    Where: /
     What: /dev/sda1
   CGroup: /system.slice/-.mount
```

**Comment by poettering** [comment]
@evverx hmm, that is weird, indeed. We store as source path where we saw the device first... I guess that's different in both cases, which is werid indeed, but probably also something to fix in a different PR...

Could you open a new issue for that, and include the ""systemctl show -a" output for both cases? Or even better, just the the "diff -u" between both?

**Comment by poettering** [comment]
@evverx btw, I invited you to the maintainer team for systemd on github a while back. If you feel that a commit looks good and works, please feel invited to press the green button to merge the pull request. (use the "squash" method to merge single commits, and otherwise normal merges, in case github asks you)

**Comment by evverx** [comment]
> We store as source path where we saw the device first
> Could you open a new issue for that

Sure. I'll open a new issue on Monday.

But the source path doesn't really matter. We don't apply mount options from the `-.mount`. So, `/` is `ro` instead of `rw` (`/` still `ro` after `daemon-reexec`).

> If you feel that a commit looks good and works please feel invited to press the green button to merge the pull request. 

OK, thanks!
(just to be sure: do you mean this PR? or any other PR?)

Anyway, I'm not sure about `-.mount`.

**Comment by keszybz** [comment]
> But the source path doesn't really matter. We don't apply mount options from the -.mount. So, / is ro instead of rw (/ still ro after daemon-reexec).

I think that's expected. Unless you issue a remount, mount options won't change.

**Comment by keszybz** [comment]
> (just to be sure: do you mean this PR? or any other PR?)

This PR _and_ any other ;)

**Comment by evverx** [comment]
> Unless you issue a remount, mount options won't change.

I think you are right.
But that's not so easy:

`/etc/systemd/system/-.mount`:

``` ini
[Unit]
DefaultDependencies=no

[Mount]
What=/dev/sda1
Where=/
Type=ext4
Options=rw
```

`/etc/systemd/system/remount-root-mount.service`:

``` ini
[Unit]
DefaultDependencies=no
Conflicts=shutdown.target
After=systemd-fsck-root.service
Before=local-fs-pre.target local-fs.target shutdown.target
Wants=local-fs-pre.target
ConditionPathExists=!/etc/fstab

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/systemctl reload /
```

```
mkdir -p /etc/systemd/system/local-fs.target.wants/
ln -fs ../remount-root-mount.service /etc/systemd/system/local-fs.target.wants/remount-root-mount.service
ln -fs /lib/systemd/system/systemd-fsck-root.service /etc/systemd/system/local-fs.target.wants/systemd-fsck-root.service
```

And

```
< After=systemd-remount-fs.service
---
> After=systemd-remount-fs.service remount-root-mount.service
```

in

```
./systemd-journal-flush.service:After=systemd-remount-fs.service
./systemd-timesyncd.service:After=systemd-remount-fs.service systemd-tmpfiles-setup.service systemd-sysusers.service
./systemd-backlight@.service:After=systemd-remount-fs.service
./systemd-update-utmp.service:After=systemd-remount-fs.service systemd-tmpfiles-setup.service auditd.service
./systemd-hwdb-update.service:After=systemd-remount-fs.service
./systemd-coredump@.service:After=systemd-remount-fs.service systemd-journald.socket
./systemd-random-seed.service:After=systemd-remount-fs.service
./systemd-quotacheck.service:After=systemd-remount-fs.service
./systemd-rfkill.service:After=sys-devices-virtual-misc-rfkill.device systemd-remount-fs.service
./systemd-sysusers.service:After=systemd-remount-fs.service
./systemd-firstboot.service:After=systemd-remount-fs.service
```

**Comment by poettering** [comment]
@evverx yeah, there's a bit of a gap in systemd there: when you define a mount unit on the host system for a file system that is already mounted in the initrd, we won't bother with applying the configuration encoded in it at boot – unlike the configuration listed in /etc/fstab, which we do apply via systemd-remount-fs.service. After all, units are generally left running after they are started and only get new settings applied when they are restarted. We have been discussing this asymmetry on and off, but always decided to just leave it the way it is, following the logic that the mount should really have been done correctly right from the beginning, and having to change mount options half-way through the boot is less than ideal anyway...

But yeah, it's a valid point to raise. It is kinda weird that you can express stuff with out legacy support more easily than with native units... But it's also one of the reasons why we generally don't consider /etc/fstab obsolete: it is after all more expressive in shorter form.

Hope that makes some sense.

**Comment by poettering** [comment]
@evverx and yeas, please feel free to hit the green merge button for any PR you feel comfortable with. Just apply some common sense, and go ahead and merge stuff that looks reasonably good and not too controversial!

**Comment by poettering** [comment]
Btw, I figure a simpler way to do the remount-fs thing for the root dir unit, would be to simply add a drop-in `/etc/systemd/system/systemd-remount-fs.service.d/50-reload-root-dir.conf` and then add this to it:

```
[Service]
ExecStart=/usr/bin/systemctl reload /
```

Or something like that. That way the already existing service will do both: reload the unit file and apply the options from /etc/fstab...

**Pull request merged**
