### PR TITLE
Build systemd-shutdown.standalone

### PR DESCRIPTION
**Pull request by keszybz**
The idea is to use it for the exitrd. I'm making it a draft for now to get the CI running, but the actual exitrd work is only begninning so it wouldn't make sense to merge this now.

### CODE REVIEW

**Comment by medhefgo** [comment]
> The idea is to use it for the exitrd.

I like the name; I shall remember it.

What's the usecase for reducing the footprint of this? I assume it's to keep `/run/initramfs` as small as possible during system operation?

Imho, a better way to achieve this is by doing it the way arch does for years now: the initrd doesn't touch `/run/initramfs` at all (so there is no memory cost during runtime). Instead there is a .service that runs during system shutdown that will mount a ramfs there and populate it with sd-shutdown and any dependencies. This has the benefit that the initrd does not have to carry anything needed for shutdown (kexec, shutdown hooks and any dependencies those need like libc etc.). The generated exitrd also benefits from any updates performed during system operation as it doesn't have to pull stuff from the initrd (though, I guess an initrd could just take stuff from the just mounted system).

**Comment by keszybz** [comment]
> What's the usecase for reducing the footprint of this?

Yes, reducing footprint. I don't think the approach with storing stuff in `/run/initramfs` for shutdown makes much sense and I want to do what you describe, i.e. unpack a minimal image from the host filesystem. I don't want to take things from the host system for the same reasons why I don't want to take them for the initrd. The exitrd should just be a package like any other, updated by the package manager.

**Comment by poettering** [comment]
i figure the exitrd also needs sysext and stuff, so that people can issue UPS poweroff requests from there, hence a single static binary is not going to suffice.

I am not a fan of the ".standalone" proliferation, but in this case it does make more sense than at most other places, hence ok by me.

With this applied, how do the ELF deps of the resulting binary actually look like?

**Comment by poettering** [comment]
> unpack a minimal image from the host filesystem.

why unpack? my thinking was to just switch root into a squashfs/erofs on shutdown, i.e. no unpacking, just mounting of the DDI directly.

Of course, the DDI would have to be backed by RAM, not disk, hence the actual approach would probably be: allocate tmpfs superblock, copy DDI into it, mount it from there, then lazy umount the tmpfs superblock, and transition into the mounted fs.

**Comment by poettering** [comment]
the tmpfs to copy the DDI into wouldn#t even have to be mounted, we could use the new mount apis, to create an unattached superblock, then populate it via the mount fd, and never actually attach it, but immediately create a loopback device from it, then close the superblock already, then dissect/mount the DDI, and transition into it.

this would be a RAM backed loopback device more or less hence.

**Comment by poettering** [comment]
(not setting green label, since still marked as "draft"?)

**Comment by keszybz** [comment]
> With this applied, how do the ELF deps of the resulting binary actually look like?

```
$ ldd build/systemd-shutdown.standalone
	linux-vdso.so.1 (0x00007fff3b3e6000)
	libmount.so.1 => /lib64/libmount.so.1 (0x00007f8a5a90b000)
	libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f8a5a8d2000)
	libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007f8a5a400000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f8a5a8a5000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f8a5a320000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f8a5a143000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8a5a96a000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f8a5a889000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f8a5a0a6000)
```

This is much less than libsystemd-shared, so it's probably worth because of this.
libpcre2 must be there anyway because of libselinux.

> why unpack?

Because of the reasons you list: we'd need to copy over the block device into a ramdisk, and that seems more work than unpacking an archive into `/run` or such.

But thinking about it some more, maybe there's no need to unpack anything. We could just have `/usr/lib/systemd/exitrd` or `/usr/lib/exitrd` and just copy the entire contents of that to tmpfs. If we follow symlinks, we could just symlink to libraries in the real root instead of having copies there. Dunno, I don't have a clear view how this would be best delivered, but whether it's a block device that is copied and mounted, or an archive that is unpacked, or a filesystem that is copied, is something that can be decided later.

> (not setting green label, since still marked as "draft"?)

I'll mark it as "ready" now.

**Comment by poettering** [comment]
> Because of the reasons you list: we'd need to copy over the block device into a ramdisk, and that seems more work than unpacking an archive into `/run` or such.
> 
> But thinking about it some more, maybe there's no need to unpack anything. We could just have `/usr/lib/systemd/exitrd` or `/usr/lib/exitrd` and just copy the entire contents of that to tmpfs. If we follow symlinks, we could just symlink to libraries in the real root instead of having copies there. Dunno, I don't have a clear view how this would be best delivered, but whether it's a block device that is copied and mounted, or an archive that is unpacked, or a filesystem that is copied, is something that can be decided later.

Yes, this question is independent of this PR. 

I am pretty convinced though that the way to go is to copy the whole DDI into a tmpfs and then transition into the DDI natively. i.e. copy the DDI around, not the files in the DDI. The reason is security: we do the whole dm-verity dance with DDI to establish trust in the executed binaries, to make them cryptographically immutable, and thus allow strict policies in kernel (via IPE and such) to be enforced on them. If you copy the files onto a tmpfs the files become mutable however, the kernel won't know anymore whether it can trust them.

(moreover, you open a whole bunch of MAC/selinux issues: when you copy those files over for later execution, you need to copy their labels too, but that would mean the copy routine would have to run with privileges to be able to label everything the way it wants, which is a very high privilege. Hence I think it would be really wise to just hand over the ready-made fs and transition into that, to avoid any such mess.)

**Comment by poettering** [comment]
thinking about this, I think all we need is a memfd actually, i.e. take DDI, stream it into a memfd, and attach a loopback file to that.

how stupid, why didn't I think about that earlier? ;-)

**Comment by poettering** [comment]
I played around with the loopback-backed-by-memfd thing, and it works great. I turned this into something useful in #25665, to create ephemeral writable copies of disk images while working with them with "sytemd-dissect". (where it makes sense, in particular with --mount + --with)

I made the logic for that generic, hence adding support for transitioning into a proper DDI backed by memfd during shutdown should become basically a three-liner addition to shutdown.c. I really like the simplicity of it.

The copy actual copying into the memfd is done with sendfile(), hence should be quite efficient.

**Pull request merged**
