### PR TITLE
Make FOREACH_DIRENT and FOREACH_DIRENT_ALL declare the iterator variables

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by bluca** [comment]
```
../src/basic/virt.c: In function ‘detect_vm_device_tree’:
../src/basic/virt.c:117:32: error: declaration of ‘dent’ shadows a previous local [-Werror=shadow]
  117 |                 FOREACH_DIRENT(dent, dir, return -errno)
      |                                ^~~~
../src/basic/dirent-util.h:18:30: note: in definition of macro ‘FOREACH_DIRENT_ALL’
   18 |         for (struct dirent *(de) = readdir_ensure_type(d);; (de) = readdir_ensure_type(d)) \
      |                              ^~
../src/basic/virt.c:117:17: note: in expansion of macro ‘FOREACH_DIRENT’
  117 |                 FOREACH_DIRENT(dent, dir, return -errno)
      |                 ^~~~~~~~~~~~~~
../src/basic/virt.c:101:32: note: shadowed declaration is here
  101 |                 struct dirent *dent;
      |                                ^~~~
```

**Comment by keszybz** [comment]
Oh, that part of the code had arch #ifdefs, so I missed it in the conversion. Should be OK now.

**Comment by bluca** [comment]
Is this new?

```
../src/src/import/import-compress.h:7:10: fatal error: lzma.h: No such file or directory
    7 | #include <lzma.h>
      |          ^~~~~~~~
```

**Comment by keszybz** [comment]
Where is this from? I only see focal-ppc64el as failed, and I don't see that there.

**Comment by keszybz** [comment]
Thanks, that was indeed an error in the patch. We need to declare libxz as a dependency to get the include directory injected. Opensuse does packaging differently by using subdirectories for some include files, so it compiled pretty much everywhere where liblzma.h is directly in /usr/include, but didn't there.

**Comment by bluca** [comment]
opensuse build is still not happy:

```
In file included from ../src/src/import/import-compress.c:3:
../src/src/import/import-compress.h:7:10: fatal error: lzma.h: No such file or directory
    7 | #include <lzma.h>
      |          ^~~~~~~~
```

**Comment by keszybz** [comment]
It turned out to be "more complicated". Meson has build_by_default=true as default for static_library(), so when I added the convenience lib, the code started being built by default even though the deps were missing. My previous guess that this is about include paths was wrong, though the fix to add libxz and others as dependencies is generally correct.

After fixing the issue I found various other things to improve…

**Review by bluca — APPROVED** [review]

**Comment by keszybz** [comment]
Since this is just build changes, I think this is relatively low risk if all CI passes. I'd merge it for v251 because it makes the build process a bit nicer.

**Comment by bluca** [comment]
> Since this is just build changes, I think this is relatively low risk if all CI passes. I'd merge it for v251 because it makes the build process a bit nicer.

Did you mean merging it for v250?

**Pull request merged**
