### PR TITLE
test-network: skip erspan test if not available

### PR DESCRIPTION
**Pull request by ssahani**
Closes one of https://github.com/systemd/systemd-centos-ci/issues/23

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Thank you, @ssahani!

The original ERSPAN issue is indeed resolved, but a few other tests keep failing:

```
======================================================================
FAIL: test_routing_policy_rule_invert (__main__.NetworkdNetWorkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "systemd/test/test-network/systemd-networkd-tests.py", line 684, in test_routing_policy_rule_invert
    self.assertRegex(output, 'tcp')
AssertionError: Regex didn't match: 'tcp' not found in '0:\tfrom all lookup local \n111:\tnot from 192.168.100.18 tos throughput lookup 7 \n32766:\tfrom all lookup main \n32767:\tfrom all lookup default'

======================================================================
FAIL: test_routing_policy_rule_port_range (__main__.NetworkdNetWorkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "systemd/test/test-network/systemd-networkd-tests.py", line 667, in test_routing_policy_rule_port_range
    self.assertRegex(output, '1123-1150')
AssertionError: Regex didn't match: '1123-1150' not found in '0:\tfrom all lookup local \n111:\tnot from 192.168.100.18 tos throughput lookup 7 \n111:\tfrom 192.168.100.18 tos throughput lookup 7 \n32766:\tfrom all lookup main \n32767:\tfrom all lookup default'

======================================================================
FAIL: test_dhcp_server (__main__.NetworkdNetworkDHCPServerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "systemd/test/test-network/systemd-networkd-tests.py", line 1019, in test_dhcp_server
    self.assertRegex(output, '192.168.5.*')
AssertionError: Regex didn't match: '192.168.5.*' not found in '● 113: veth99\n       Link File: /usr/lib/systemd/network/99-default.link\n    Network File: /run/systemd/network/dhcp-client.network\n            Type: ether\n           State: degraded (configuring)\n          Driver: veth\n      HW Address: 12:34:56:78:9a:bc\n         Address: fe80::1034:56ff:fe78:9abc'

======================================================================
FAIL: test_ipv6_prefix_delegation (__main__.NetworkdNetworkRATests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "systemd/test/test-network/systemd-networkd-tests.py", line 988, in test_ipv6_prefix_delegation
    self.assertRegex(output, '2002:da8:1:0')
AssertionError: Regex didn't match: '2002:da8:1:0' not found in '● 118: veth99\n       Link File: /usr/lib/systemd/network/99-default.link\n    Network File: /run/systemd/network/ipv6-prefix-veth.network\n            Type: ether\n           State: degraded (configuring)\n          Driver: veth\n      HW Address: 12:34:56:78:9a:bc\n         Address: fe80::1034:56ff:fe78:9abc'

----------------------------------------------------------------------
Ran 69 tests in 733.649s
```

Full log: http://ix.io/1zyQ

**Comment by yuwata** [comment]
So, then this itself is OK to merge. @ssahani Do you want to fix the remaining failure in this PR? Or in other PRs?

**Comment by ssahani** [comment]
@yuwata I am Brno office for few hrs . WIll be travelling back . Until monday I am not able to work in this. Feel free to open PR. I think we have to similar patch for routing rules. and skip them . I think the older kernel does not have those feature.

**Comment by yuwata** [comment]
OK. Then let's merge this now.

**Pull request merged**
