### PR TITLE
udev: build by-path identifiers for ATA devices.

### PR DESCRIPTION
**Pull request by ghost**
/dev/disk/by-path

total 0
lrwxrwxrwx. 1 root root  9 Sep  4 10:02 pci-0000:00:1f.2-ata-2 -> ../../sr0
lrwxrwxrwx. 1 root root  9 Sep  4 10:02 pci-0000:00:1f.2-ata-3 -> ../../sdd
lrwxrwxrwx. 1 root root 10 Sep  4 10:02 pci-0000:00:1f.2-ata-3-part1 -> ../../sdd1
lrwxrwxrwx. 1 root root 10 Sep  4 10:02 pci-0000:00:1f.2-ata-3-part2 -> ../../sdd2
lrwxrwxrwx. 1 root root 10 Sep  4 10:02 pci-0000:00:1f.2-ata-3-part3 -> ../../sdd3
lrwxrwxrwx. 1 root root  9 Sep  4 10:02 pci-0000:03:00.0-ata-4 -> ../../sda
lrwxrwxrwx. 1 root root 10 Sep  4 10:02 pci-0000:03:00.0-ata-4-part1 -> ../../sda1
lrwxrwxrwx. 1 root root 10 Sep  4 10:02 pci-0000:03:00.0-ata-4-part2 -> ../../sda2
lrwxrwxrwx. 1 root root  9 Sep  4 10:02 pci-0000:08:00.0-ata-1 -> ../../sdc
lrwxrwxrwx. 1 root root 10 Sep  4 10:02 pci-0000:08:00.0-ata-1-part1 -> ../../sdc1
lrwxrwxrwx. 1 root root 10 Sep  4 10:02 pci-0000:08:00.0-ata-1-part2 -> ../../sdc2

### CODE REVIEW

**Comment by poettering** [comment]
Code looks fine, but I'll leave this one to @kaysievers. 

But could you fix one thing: a patch should not have "Patch to" in the subject.. Of course it's a patch... Please prefix subjects with the component name the patch touches. In this case maybe: "udev: build by-path identifiers for ATA devices", or so...

Feel free to force push a fix for that.

**Comment by kaysievers** [comment]
Looks all good to me. Thanks for the proper fix.

**Comment by poettering** [comment]
@davidmilburn please fix the subject line, will then merge.

**Comment by ghost** [comment]
Ok, fixed subject line, thanks.

**Pull request merged**
