### PR TITLE
networkd: introduce team 

### PR DESCRIPTION
**Pull request by ssahani**

### CODE REVIEW

**Comment by teg** [comment]
Hm, don't we need proper integration with teamd? I haven't studied this stuff properly, but I think this won't be as easy as this. @msekletar?

**Comment by ssahani** [comment]
It just the first part to to create a team device.

**Comment by msekletar** [comment]
I'd advice against reimplementing teamd. Feel free to look at my WIP patch introducing team support.
https://github.com/msekletar/systemd/tree/team

**Comment by ssahani** [comment]
@msekletar I dint know you are working on this :)

**Comment by ssahani** [comment]
Thanks @msekletar !

**Comment by poettering** [comment]
Yeah, I am pretty sure we need to interface with teamd somehow. I'd prefer merging team support only if we know it is reasonably useful, and I doubt the patch just like this is sufficient, given that much of the control logic of team sits in the userspace teamd component, which we don't want to reimplement.

**Pull request closed without merging**
