### PR TITLE
Do not order systemd-backlight before sysinit.target

### PR DESCRIPTION
**Pull request by paulmenzel**

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, so after thinking about this more I am a bit unsure about this. The current ordering deps mean that wayland/gnome/X11 and our backlight code usually won't step on each others toes: we'll restore the values before handing off to wayland/gnome/X11, and we'll save them only after w/g/x stopped during shutdown. Now, this is a bit racy already, as backlight devices might show up any time, including after sysinit.target is long reached, at which point w/g/x and our code might touch the devices at the same time, but during shutdown it's *not* racy, and I think that's a good thing.

Hence I am not sure we should really merge this. I think there's actually good reason to keep this ordered.

**Comment by keszybz** [comment]
Yeah, things seem to be working as they are now. If this fixes some issue, please reopen with more details.

**Comment by paulmenzel** [comment]
As I ran into this issue again, one question.

> but during shutdown it's not racy, and I think that's a good thing.

The commit only removes the ordering during startup, doesn’t it. So the shutdown behavior would be kept.

**Comment by arvidjaar** [comment]
> The commit only removes the ordering during startup, doesn’t it. So the shutdown behavior would be kept.

Systemd ordering is symmetrical. To ensure order on shutdown you must configure it on startup. If you remove startup order, shutdown order becomes unpredictable. Without your patch service is stopped late (at least after normal user services); with your patch it is stopped concurrently with other user services.

**Pull request closed without merging**
