### PR TITLE
debug: Disable file truncation and hole punching in journald

### PR DESCRIPTION
**Pull request by daandemeyer**
Part of figuring out the root cause of #21675

### CODE REVIEW

**Comment by mrc0mmand** [comment]
This seems to work:

```
Dec 15 12:31:07 n41.dusty.ci.centos.org systemd-networkd[238192]: ip6tnl0: Link state is up-to-date
Dec 15 12:31:07 n41.dusty.ci.centos.org systemd-networkd[238192]: ip6tnl0: State changed: initialized -> unmanaged
Dec 15 12:31:07 n41.dusty.ci.centos.org systemd-networkd[238192]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_3232 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=5 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Dec 15 12:31:07 n41.dusty.ci.centos.org systemd-networkd[238192]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_3232 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=5 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Dec 15 12:31:07 n41.dusty.ci.centos.org kernel: device test1 entered promiscuous mode
Dec 15 12:31:07 n41.dusty.ci.centos.org systemd-journald[908]: Failed to write entry (25 items, 952 bytes), rotating before retrying: Argument list too long
Dec 15 12:31:07 n41.dusty.ci.centos.org audit: ANOM_PROMISCUOUS dev=test1 prom=256 old_prom=0 auid=4294967295 uid=982 gid=982 ses=4294967295
Dec 15 12:31:07 n41.dusty.ci.centos.org audit[238192]: SYSCALL arch=c000003e syscall=44 success=yes exit=32 a0=3 a1=113fbf0 a2=20 a3=0 items=0 ppid=1 pid=238192 auid=4294967295 uid=982 gid=982 euid=982 suid=982 fsuid=982 egid=982 sgid=982 fsgid=982 tty=(none) ses=4294967295 comm="systemd-network" exe="/usr/lib/systemd/systemd-networkd" subj=system_u:system_r:systemd_networkd_t:s0 key=(null)
Dec 15 12:31:07 n41.dusty.ci.centos.org audit: PROCTITLE proctitle="(networkd)"
Dec 15 12:31:07 n41.dusty.ci.centos.org rsyslogd[1345]: imjournal: journal files changed, reloading...  [v8.2102.0-6.el8 try https://www.rsyslog.com/e/0 ]
Dec 15 12:31:07 n41.dusty.ci.centos.org systemd-networkd[238192]: sit0: Link state is up-to-date
Dec 15 12:31:07 n41.dusty.ci.centos.org systemd-networkd[238192]: sit0: State changed: initialized -> unmanaged
```

https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos8/5246/artifact//systemd-centos-ci/artifacts_buym30hg/testsuite-logs-upstream.ATh/journalctl-testsuite_PASS.log

**Comment by DaanDeMeyer** [comment]
I suspect it's the hole punching, let me push again with just hole punching disabled to confirm.

**Comment by mrc0mmand** [comment]
Still looks good in CentOS CI as well:

```
Dec 15 14:07:30 n46.crusty.ci.centos.org systemd-networkd[236199]: sit0: Link state is up-to-date
Dec 15 14:07:30 n46.crusty.ci.centos.org systemd-networkd[236199]: sit0: State changed: initialized -> unmanaged
Dec 15 14:07:30 n46.crusty.ci.centos.org systemd-networkd[236199]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_3165 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=6 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Dec 15 14:07:30 n46.crusty.ci.centos.org systemd-networkd[236199]: ifb1: Link state is up-to-date
Dec 15 14:07:30 n46.crusty.ci.centos.org systemd-journald[893]: Failed to write entry (26 items, 768 bytes), rotating before retrying: Argument list too long
Dec 15 14:07:30 n46.crusty.ci.centos.org rsyslogd[1250]: imjournal: journal files changed, reloading...  [v8.2102.0-6.el8 try https://www.rsyslog.com/e/0 ]
Dec 15 14:07:30 n46.crusty.ci.centos.org systemd-networkd[236199]: ifb1: State changed: initialized -> unmanaged
Dec 15 14:07:30 n46.crusty.ci.centos.org systemd-networkd[236199]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_319 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=7 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
```

**Comment by DaanDeMeyer** [comment]
Let's close this PR since it seems that the hole punching is the culprit. Pushed #21784 which hopefully fixes the issue.

**Pull request closed without merging**
