### PR TITLE
Use ./configure-d paths in man pages

### PR DESCRIPTION
**Pull request by keszybz**
This is straightforward revert of #293 (with the few trivial conflicts resolved) plus additional patches on top to describe $PATH properly. I _think_ it gets most of the places correct, but I haven't looked through all the man pages to check.

@mbiebl, @martinpitt, @filbranden, @teg

### CODE REVIEW

**Comment by zonque** [comment]
FTR: Semaphore uses split usr and fails in `test-path-util`.

**Comment by kaysievers** [comment]
This still has different paths in man pages than in the code? Then we cannot do that.

They need to match completely, or we just keep the intended default of a merged /usr. Split-usr does not add any value to any system, there is no need to support that mode in a non-essential part like man pages, especially if it is not correctly done.

**Comment by kaysievers** [comment]
> there is no need to support that mode in a non-essential part like man pages

In case I wasn't clear enough, we need a reason to add features we need to maintain, not a reason not to add them. And changing the build-sys to fully render man pages to reflect the actual paths in the code is not justified. Split-usr is a dead end, and not worth to carry things like this.

**Comment by filbranden** [comment]
Sorry @kaysievers but I really fail to see how this PR makes things **worse**.

If anything, it helps distros that are still using split-usr, of which we have at least two very active contributors on the list. Instead of having them maintain messy patches downstream that require a lot of review as man page maintenance, they can focus on more worthy efforts (such as, for instance, considering whether merging usr might work and seeing that a path towards it exists.)

I can see your point about the documentation not being 100% accurate in the split-usr case since it only includes one of the /lib vs. /usr/lib path and not the other, but as already mentioned by @mbiebl and @martinpitt on the other thread that's OK with them since the intent is really to document the one path users are _supposed_ to be using. In fact, that's what their manpages have now anyways...

I, of course, support pushing this change in. (On the other hand, I wonder if it's so important to warrant this whole discussion about it.)

How can we get to a middle ground here? Is some form of compromise possible? I really want to try to be constructive and get to a solution that everybody is happy with (or at least everybody can live with, or is not totally unhappy about...)

Cheers,
Filipe

**Comment by kaysievers** [comment]
Split-usr in most cases ADDS paths, does not replace them. The patch is just plain wrong and we better ship the recommended and not broken unified /usr man pages for everybody, instead of pretending we support split /usr man pages and they are not even correct. This is all backwards.

**Comment by filbranden** [comment]
In the particular case of `/lib/systemd/system` and `/usr/lib/systemd/system`, @mbiebl has previously said he's OK with including only one of them, in fact, that's the intention: https://github.com/systemd/systemd/pull/293#issuecomment-113291486

Considering the consumers of split-usr seem to be OK with it... Why block it?

**Comment by kaysievers** [comment]
> @mbiebl has previously said he's OK with including only one of them, in fact, that's the intention: #293 (comment)

Sure, downstream can make such decision. Upstream must not ship such "broken" man pages.

> Considering the consumers of split-usr seem to be OK with it... Why block it?

Because the man pages are technically incorrect.

And again, systemd's split-usr support is limited to essential functionality. We make it boot as good as we can, not we make it look pretty.

Split-usr does not add any value to any system, it is pure legacy and hence it is acceptable to put the burden of the non-essential parts to the users which do not support all features of systemd.

**Comment by martinpitt** [comment]
For the record, in Debian/Ubuntu I applied some seddery in the build
process which fixes (almost?) all of the paths. That's "good enough"
for the time being, and certainly not much more (perhaps even less)
incorrect than always keeping in mind to use macros when writing new
manpages.

**Comment by poettering** [comment]
OK, with @martinpitt's input, closing this now.

**Pull request closed without merging**
