### PR TITLE
RFC: boot: Build EFI binaries natively

### PR DESCRIPTION
**Pull request by medhefgo**
(This has gotten quite large due to the printf stall, so don't bother giving this a full review just yet. I'll be making separate PRs to gradually gets things in. The interesting stuff starts at "meson: Cross-build EFI binaries natively")

This PR provides us with the ability to "natively" build EFI binaries without all the gnu-efi atrocities. To give this a try you'd need a current meson git checkout (until https://github.com/mesonbuild/meson/commit/9f6b1b8a6844b9789c75b7e09fd716fe75f7be36 and https://github.com/mesonbuild/meson/commit/ded57707c8196eda2fcf7ea507e7e2b38f9a7d19 are backported) and mingw installed. To then build it you pass a proper cross file to meson:

    ~/meson/meson.py setup --cross-file src/boot/efi/cross-mingw-x86_64.ini build-boot-x86_64
    ninja -C build-boot-x86_64

Or with clang also installed, you can use cross-clang-x86_64.ini.

These builds are proper meson cross builds that target windows (so I guess systemd is officially ported to windows KEKW). As such the build machinery is much cleaner and nicer to look at. The files are cleanly built PE binaries unlike with gnu-efi where they target ELF which then gets converted to PE along with some linker magic and a stub that then does ELF relocations at runtime (yuck).

Some more benefits:
 - No more gnu-efi!
 - Trivially easy to cross build other arches and therefore to test
 - Easier to get debugging to work (gnu-efi based binaries have to be stripped or they won't run, but these can run with debug symbols still around)
 - We benefit from meson machinery such as proper flags detection when cross building. We also don't have to manually create the build command lines anymore.
 - Optimized builds, LTO etc work work out of the box (well, I found a [bfd bug with LTO](https://sourceware.org/bugzilla/show_bug.cgi?id=29998))
 - Free NX/ASLR support (I wonder if there is firmware that actually makes use of it)

Now some disadvantages:
 - riscv support would be dropped on the floor as clang does not have a riscv PE/COFF writer
   I am toying with the idea of providing a means to build sd-boot with EDK2. It *should* be relatively easy and simple, but it's only an idea atm.
 - I can't say much about testing the binaries on real hardware other than they work on mine. (I did test them on different arches and compilers under qemu a lot, including secure boot with custom keys and/or MS keys+shim and they work like a charm)
 - sd-boot build process is separate from regular userspace because it simply has to be (it's a meosn cross build after all)
   One could probably add a custom target that calls meson for sd-boot on regular userspace builds, but I kinda dislike the idea…
 - Needs a separate toolchain (mingw) installed
   Well, technically, you can get away with just clang+compiler-rt. But it's nice to piggyback on mingw-libgcc on x86.
 - Needs meson 0.63.0+ for `efi_application` with `win_subsystem` support (and those backports from above)
   I assume this might be one of the bigger showstoppers. There is probably some wriggle room by using wrapper scripts that fix up the compiler/linker command line, but gcc makes this hard to do as `-fuse-ld` does not accept arbitrary paths. Changing the cross target system to something custom like `uefi` instead of `windows` might also work, but I am not particularly sure how meson would behave. I'd much rather we just bump the minimum meson version; I really hate ancient distros stomping progress…

*drumroll on build tests* (mkosi should work, I've tested it locally :cat:)

### CODE REVIEW

**Comment by bluca** [comment]
> Free NX/ASLR support (I wonder if there is firmware that actually makes use of it)

NX is coming as a hard requirement for windows machines very soon (TM)

> riscv support would be dropped on the floor as clang does not have a riscv PE/COFF writer

This is a bit of a problem, although not a huge blocker as Ubuntu doesn't build systemd-boot-efi for riscv yet, Debian does but it's an unofficial port so it is not part of the official releases. Although I'm not sure I follow, you are also saying mingw is enough? Is clang needed if you use mingw?

> sd-boot build process is separate from regular userspace because it simply has to be (it's a meosn cross build after all)
One could probably add a custom target that calls meson for sd-boot on regular userspace builds, but I kinda dislike the idea…

This is a bit of an annoyance, because all the distro packaging will need a manual change to call this, if we had a target that is part of the default build (if enabled) it would be very nice

> Needs meson 0.63.0+

Should be fine to do in v254, in fact we should be able to change it the minute after v253 is released

**Comment by bluca** [comment]
> > riscv support would be dropped on the floor as clang does not have a riscv PE/COFF writer
> 
> This is a bit of a problem, although not a huge blocker as Ubuntu doesn't build systemd-boot-efi for riscv yet, Debian does but it's an unofficial port so it is not part of the official releases. Although I'm not sure I follow, you are also saying mingw is enough? Is clang needed if you use mingw?

Ah just saw that mingw is x86 only, never mind - shows how much I know about windows stuff

**Comment by medhefgo** [comment]
Nice, arch+debian mkosi  work.

> NX is coming as a hard requirement for windows machines very soon (TM)

For EFI? Got any pointers?

So the toolchains needed are either one of:
 - mingw+bfd (x86/86_64 only)
 - clang+lld with mingw installed for libgcc (x86/x86_64)
 - clang+lld+compiler-rt (arm/aarch64/x86/x86_64)

> This is a bit of an annoyance, because all the distro packaging will need a manual change to call this, if we had a target that is part of the default build (if enabled) it would be very nice

They need to do adjustments on version upgrades anyways. And for things like reproducible builds it would probably be better if they call meson etc for themselves. I am thinking more on the developer side here as without such a target you only build-test sd-boot if done manually. I'd prefer any such a built target to be only for developer mode.

**Comment by bluca** [comment]
> > NX is coming as a hard requirement for windows machines very soon (TM)
> 
> For EFI? Got any pointers?

Yeah for EFI - I don't have any links, just hearing things

> So the toolchains needed are either one of:
> 
> * mingw+bfd (x86/86_64 only)
> * clang+lld with mingw installed for libgcc (x86/x86_64)
> * clang+lld+compiler-rt (arm/aarch64/x86/x86_64)
> 
> > This is a bit of an annoyance, because all the distro packaging will need a manual change to call this, if we had a target that is part of the default build (if enabled) it would be very nice
> 
> They need to do adjustments on version upgrades anyways. And for things like reproducible builds it would probably be better if they call meson etc for themselves. I am thinking more on the developer side here as without such a target you only build-test sd-boot if done manually. I'd prefer any such a built target to be only for developer mode.

Having to override dh_auto_build is a pain, as then you have to manually keep in sync as things change, etc. If a single build invocation is possible, it would be really nice to have it.

**Comment by DaanDeMeyer** [comment]
You can add a mkosi prepare script with `python3 -m pip install meson` to get an up-to-date meson in the images that need it.

**Comment by medhefgo** [comment]
> Can we please keep Linux free of any Micro$@$ crap? thank jooo...

rofl. You made my day. Do we really have to lock this PR to outsiders? :joy_cat:

**Comment by TriMoon** [comment]
> > Can we please keep Linux free of any Micro$@$ crap? thank jooo...
> 
> rofl. You made my day. Do we really have to lock this PR to outsiders? joy_cat

If that is how you want to be free of counter arguments from the comunity, then please step out of the Free Open Source market....

**Comment by bluca** [comment]
> If that is how you want to be free of counter arguments from the comunity, then please step out of the Free Open Source market....

First warning against pointless spam - there will not be a second

**Comment by medhefgo** [comment]
Just FYI for anyone uninformed, mingw-gcc is from GNU and is just a compiler/toolchain. You can all put down your pitchforks. Also, what bluca said.

**Comment by DaanDeMeyer** [comment]
Can we just use clang in the mkosi builds? We already install llvm anyway so we could use the clang cross build there instead of installing mingw maybe? Not sure which cross build we want to test by default.

**Comment by TriMoon** [comment]
> First warning against pointless spam - there will not be a second

Although i can understand your warning, i have to object to the spam part, especially while his post still stays um-flagged in same way.

Because everyone has the same rights to react to aggressiveness.
_(His was personal towards me and the community as a whole)_

Anyhow carry on with the RFC topic, i just wanted to clear my stand point.
_(And will report higher up if needed in case you block me  as a longtime contributor from outside your repo)_

---
-- Pointing out wrong info, can be done in many ways, aggression is not among them.

**Comment by bluca** [comment]
> Can we just use clang in the mkosi builds? We already install llvm anyway so we could use the clang cross build there instead of installing mingw maybe? Not sure which cross build we want to test by default.

if mingw is supported, then I think it would be good to test it? it's not that commonly used, so chances things might go wrong are non-zero

**Comment by medhefgo** [comment]
I played around with the EDK2 build system and it's way too ugly. But in the process I learned way more than I ever wanted about how ELF and PE images work. There are basically 3.5 ways to produce a PE/EFI image:
 - gnu-efi: Produce ELF image, convert to PE (using objcopy) and perform relocations at runtime (aka, life-surgery).
 - EDK2: Produce ELF, convert to PE *including* conversion/translation of ELF relocations to PE relocations (https://github.com/tianocore/edk2/tree/master/BaseTools/Source/C/GenFw). PE relocation will be performed at runtime by the PE loader/firmware before the image is run.
 - Use ld emulations (learned this from https://github.com/davmac314/elf2efi/): Apparently, the linker can output PE images even when using an ELF toolchain if a PE emulation is used (`-mi386pep`). The issue is that meson+gcc have assumptions about what command line flags can be passed to the linker. So one would have to do the link step manually, and that's a pita for LTO.
 - Using a PE toolchain (the approach of this PR)

The gnu-efi way is just ugly and the ld emulation is difficult to use and requires support for the arch (I think binutils only supports it for x86/x86_64).

The EDK2 way, though, isn't all that ugly if you look carefully at it. Aside from the fact that their conversion tool is written in that horrible C-style of theirs (the relocation translation function spans several pages).

I actually considered adding a build option that uses their GenFw tool, but it also does some annoying things like merge our private sections (including .sbat) into .data. So instead I gave my newfound python-fu a go and wrote my own elf2efi.py. It's surprisingly easy (borderline trivial) to convert ELF to PE. The hard part is understanding the ELF relocations and how to convert them, which I don't (and GenFw source code might as well be assembler). So I was going to abandon this when looking at gnu-efi showed me that if the ELF binary is built as a shared object instead of a static binary, we only get `R_*_RELATIVE` relocation types that are dead easy to convert to PE relocations.

I am actually kind of surprised how well this conversion tool works right now and it's fairly small (550 lines). And now I am wondering if maybe we should go with this one instead of using a native toolchain. The one huge benefit is that new arches should be easy to add (LOONGARCH, for example should be trivial). We could also go both ways, as I think the differences in the build steps should be minimal.

**Comment by rossburton** [comment]
I totally understand why you're doing this and and it's probably the right thing to do, but as someone who is already cross-compiling systemd this is going to be _fun_ to integrate.

**Comment by bluca** [comment]
> I totally understand why you're doing this and and it's probably the right thing to do, but as someone who is already cross-compiling systemd this is going to be _fun_ to integrate.

Note that the approach taken in the end is https://github.com/systemd/systemd/pull/26641 which should make things considerably easier for that case too. The ELF -> EFI conversion does not need any other toolchain, just python3 and python3-pyelftools (which is also a pure python module, no compiled module needed). It should "just work" (TM) for any architecture.

**Comment by rossburton** [comment]
Ah perfect, thanks. It was late and I was tired. I'm a fan of the new approach.

**Comment by bluca** [comment]
@medhefgo can we close this now that the other is merged?

**Pull request closed without merging**
