### PR TITLE
Personality fixes

### PR DESCRIPTION
**Pull request by poettering**
Let's make use of architecture.h's arch definitions for the personality strings.

Also contains an alternative fix for #2696

### CODE REVIEW

**Comment by martinpitt** [comment]
This regressed the nspawn test, which certainly does touch personalities as it uses seccomp: 
http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/tests/boot-and-services#n173

```
FAIL: test_service (__main__.NspawnTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/adt-run.7Sc0ob/build.CBm/systemd/debian/tests/boot-and-services", line 228, in test_service
    self.assertIn(b'Stopped Container c1', out)
AssertionError: b'Stopped Container c1' not found in b"\xe2\x97\x8f systemd-nspawn@c1.service - Container c1\n   Loaded: loaded (/lib/systemd/system/systemd-nspawn@.service; disabled; vendor preset: enabled)\n   Active: inactive (dead)\n     Docs: man:systemd-nspawn(1)\n\nFeb 22 15:59:47 adt systemd-nspawn[1126]:     1 0        init\nFeb 22 15:59:47 adt systemd-nspawn[1126]:     2 0        {rcS} /bin/sh /etc/init.d/rcS\nFeb 22 15:59:47 adt systemd-nspawn[1126]:     3 0        {exe} ps aux\nFeb 22 15:59:47 adt systemd-nspawn[1126]: umount: can't remount tmpfs read-only\nFeb 22 15:59:47 adt systemd-nspawn[1126]: umount: can't remount /dev/vda1 read-only\nFeb 22 15:59:47 adt systemd-nspawn[1126]: [47B blob data]\nFeb 22 15:59:47 adt systemd-nspawn[1126]: [30B blob data]\nFeb 22 15:59:47 adt systemd-nspawn[1126]: [30B blob data]\nFeb 22 15:59:48 adt systemd-nspawn[1126]: [30B blob data]\nFeb 22 15:59:48 adt systemd-nspawn[1126]: [27B blob data]\n"
```

However, `test_boot()` (which calls nspawn directly instead of via the generated unit) does succeed, so nspawn is not generally broken. This might certainly be a bug in the test, but it has been very stable so far, so I think this deserves a closer look at least.

I also started the CI test for x86 32 bit and ppc64el to get results for a few more platforms.

**Comment by poettering** [comment]
hmm, what precisely fails there, I have trouble reading the output...It appears to fail in the umount loop? Unfortunately the log data is all suppressed because it contains weird chars apparently. Do you get that data from journalctl? if so, could you add "--all" to its invocation, so that it prints even the rubbish it got?

**Comment by poettering** [comment]
OK, so I pushed two more commits that simplify things a bit and add an explicit test case for this, maybe this helps finding out what's going on.

(but please, the --raw thing would still be useful)

**Comment by poettering** [comment]
Hmm, the update either fixed things or the issue was spurious after all. CI passed now. 

Anyway, would be cool if someone could review this and press the green button! Thanks!

**Comment by martinpitt** [comment]
Works on 32 bit:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/i386/s/systemd-upstream/20160222_175319@/log.gz

Fails to build on ppc64el:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/ppc64el/s/systemd-upstream/20160222_170315@/log.gz

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -include ./config.h -DPKGSYSCONFDIR=\"/etc/systemd\" -DSYSTEM_CONFIG_UNIT_PATH=\"/etc/systemd/system\" -DSYSTEM_DATA_UNIT_PATH=\"/lib/systemd/system\" -DSYSTEM_SYSVINIT_PATH=\"/etc/init.d\" -DSYSTEM_SYSVRCND_PATH=\"/etc\" -DUSER_CONFIG_UNIT_PATH=\"/etc/systemd/user\" -DUSER_DATA_UNIT_PATH=\"/usr/lib/systemd/user\" -DCERTIFICATE_ROOT=\"/etc/ssl\" -DCATALOG_DATABASE=\"/var/lib/systemd/catalog/database\" -DSYSTEMD_CGROUP_AGENT_PATH=\"/lib/systemd/systemd-cgroups-agent\" -DSYSTEMD_BINARY_PATH=\"/lib/systemd/systemd\" -DSYSTEMD_FSCK_PATH=\"/lib/systemd/systemd-fsck\" -DSYSTEMD_SHUTDOWN_BINARY_PATH=\"/lib/systemd/systemd-shutdown\" -DSYSTEMD_SLEEP_BINARY_PATH=\"/lib/systemd/systemd-sleep\" -DSYSTEMCTL_BINARY_PATH=\"/bin/systemctl\" -DSYSTEMD_TTY_ASK_PASSWORD_AGENT_BINARY_PATH=\"/bin/systemd-tty-ask-password-agent\" -DSYSTEMD_STDIO_BRIDGE_BINARY_PATH=\"/usr/bin/systemd-stdio-bridge\" -DROOTPREFIX=\"\" -DRANDOM_SEED_DIR=\"/var/lib/systemd/\" -DRANDOM_SEED=\"/var/lib/systemd/random-seed\" -DSYSTEMD_CRYPTSETUP_PATH=\"/lib/systemd/systemd-cryptsetup\" -DSYSTEM_GENERATOR_PATH=\"/lib/systemd/system-generators\" -DUSER_GENERATOR_PATH=\"/usr/lib/systemd/user-generators\" -DSYSTEM_SHUTDOWN_PATH=\"/lib/systemd/system-shutdown\" -DSYSTEM_SLEEP_PATH=\"/lib/systemd/system-sleep\" -DSYSTEMD_KBD_MODEL_MAP=\"/usr/share/systemd/kbd-model-map\" -DSYSTEMD_LANGUAGE_FALLBACK_MAP=\"/usr/share/systemd/language-fallback-map\" -DUDEVLIBEXECDIR=\"/lib/udev\" -DPOLKIT_AGENT_BINARY_PATH=\"/usr/bin/pkttyagent\" -DQUOTACHECK=\"/usr/sbin/quotacheck\" -DKEXEC=\"/usr/sbin/kexec\" -DMOUNT_PATH=\"/bin/mount\" -DUMOUNT_PATH=\"/bin/umount\" -DLIBDIR=\"/usr/lib/powerpc64le-linux-gnu\" -DROOTLIBDIR=\"/lib/powerpc64le-linux-gnu\" -DROOTLIBEXECDIR=\"/lib/systemd\" -DTEST_DIR=\"/tmp/adt-run.msrafq/build.N2e/systemd/build-deb/../test\" -I ../src -I ./src/basic -I ../src/basic -I ../src/shared -I ./src/shared -I ../src/network -I ../src/login -I ../src/journal -I ./src/journal -I ../src/timedate -I ../src/timesync -I ../src/nspawn -I ../src/resolve -I ./src/resolve -I ../src/systemd -I ./src/core -I ../src/core -I ../src/libudev -I ../src/udev -I ../src/udev/net -I ./src/udev -I ../src/libsystemd/sd-bus -I ../src/libsystemd/sd-event -I ../src/libsystemd/sd-login -I ../src/libsystemd/sd-netlink -I ../src/libsystemd/sd-network -I ../src/libsystemd/sd-hwdb -I ../src/libsystemd/sd-device -I ../src/libsystemd-network -Wdate-time -D_FORTIFY_SOURCE=2 -pipe -Wall -Wextra -Wundef -Wformat=2 -Wformat-security -Wformat-nonliteral -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Werror=overflow -Wdate-time -Wnested-externs -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -Werror=shadow -pthread -O0 -c ../src/basic/random-util.c  -fPIC -DPIC -o src/basic/.libs/libbasic_la-random-util.o
../src/basic/process-util.c: In function ‘personality_from_string’:
../src/basic/process-util.c:726:24: error: ‘PER_LINUX_32’ undeclared (first use in this function)
                 return PER_LINUX_32;
                        ^
../src/basic/process-util.c:726:24: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by poettering** [comment]
urks. thanks. will fix.

**Comment by martinpitt** [comment]
> Do you get that data from journalctl?

No, it's the output of `systemctl status` from here: http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/tests/boot-and-services#n223

So `--all` isn't available here, but I can add `-o verbose` -- I suppose that will have blob data. I'll commit that change as it seems useful in the failure case. I'll also refine it to convert the byte array to a string, so that it's easier to read.

It seems the main error messages were `umount: can't remount tmpfs read-only` and `umount: can't remount /dev/vda1 read-only` and thus it never got to the successful `Stopped Container c1`. Anyway, if that was just a rare error, it's not that important for now, it's the first time that I saw it.

**Comment by poettering** [comment]
@martinpitt which version did you test on ppc? the newest or the original one?

**Comment by poettering** [comment]
i found a different bug, btw, will update anyway.

**Comment by martinpitt** [comment]
I tested the original one, before "simplify personality() string matching". I'll re-trigger it, but I'll wait for your "different bug". In the meantime I'll figure out why checking out the git branch doesn't work on the s390x machine (some firewall issue again), then we can test on that platform too (and perhaps also on ARM).

**Comment by poettering** [comment]
I pushed a new, rebased version now, which fixes one more thing. @martinpitt please check if this one works on ppc too!

Thanks!

**Comment by martinpitt** [comment]
Triggered the tests. That will take a while, queues are quite full ATM. I'll report back tomorrow morning first thing, if that's enough.

**Comment by poettering** [comment]
Hmm, this is likely going to fail actually, because of #2700...

I am really surprised that git is currently not buildable... How come the CI for #2685 didn't figure out this would break things?

(I am currently prepping a fix for #2700 btw, should be up very soon)

**Comment by martinpitt** [comment]
The ubuntu-ci test ran and passed for #2685, but there was no semaphore run. The ubuntu-ci check doesn't run "distcheck", so it didn't catch that -- that's what semaphore is supposed to cover.

**Comment by poettering** [comment]
oh, i wonder why that didn't run...

Any chance you can run "make distcheck" on ubuntu-ci too?

Fix for that part is waiting in #2704 now. Please review and merge. When that's done I can rebase this PR (and someothers) on top of it!

**Comment by martinpitt** [comment]
> Any chance you can run "make distcheck" on ubuntu-ci too?

In principle yes, but it's already taking long enough as it is -- distcheck is essentially doing a whole second build, which would add another 15 minutes or so. I'd much rather do this in parallel on semaphore, like we've done so far. @zonque was looking into why semaphore was AWOL in the last days, not sure what the status is. I've certainly seen it running again in today's PRs, including this one.

**Comment by martinpitt** [comment]
#2704 merged (note: this won't affect the ubuntu-ci test)

**Comment by poettering** [comment]
ok, rebased on current git master, this time it should hopefully pass CI.

**Comment by martinpitt** [comment]
passed on x86 32 bit: https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/i386/s/systemd-upstream/20160223_021225@/log.gz

passed on ppc64le: https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/ppc64el/s/systemd-upstream/20160222_231427@/log.gz

build and make check succeed on s390x. There are some test failures, but that's ok -- I never ran the upstream tests in an LXC container/on that arch before: https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/s390x/s/systemd-upstream/20160222_222918@/log.gz

So all good on the CI front.

**Comment by martinpitt** [comment]
LGTM, and thanks for the new test cases -- these make it easy and obvious to add tests for more architectures if/when things misbehave there.

**Comment by jsynacek** [comment]
The tests, which I have fixed in the original PR, still fail, because the service file for PPCs hasn't been added.

```
FAIL: test-execute
==================

+ test /tmp/test-exec_workingdirectory = /tmp/test-exec_workingdirectory
[/var/tmp/systemd/test/test-execute/exec-personality-x86.service:7] Failed to parse personality, ignoring: x86
++ uname -m
+ c=ppc64le
+ test ppc64le = i686
exec-personality-x86.service: Main process exited, code=exited, status=1/FAILURE
exec-personality-x86.service: Unit entered failed state.
exec-personality-x86.service: Failed with result 'exit-code'.
```

**Comment by poettering** [comment]
@jsynacek i don't have such hw, but i prepped a fix for that test now in #2715.

**Comment by jsynacek** [comment]
https://github.com/systemd/systemd/pull/2696 added test/test-execute/exec-personality-ppc64.service. You probably also need one for ppc64le, since that's what I get when running uname on a testing machine.

**Pull request merged**
