### PR TITLE
meson: several fixlets

### PR DESCRIPTION
**Pull request by yuwata**
Replaces #24134.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @eli-schwartz

**Review by bluca — APPROVED** [review]

**Comment by evverx** [comment]
I'd wait for @eli-schwartz to confirm that this PR replaces https://github.com/systemd/systemd/pull/24134

**Comment by eli-schwartz** [comment]
I'm not sure why @yuwata bothered to ping me shortly after midnight on a weekend for a PR that was going to be merged hours later. TBH, you could have just suggested the change as a review comment on my PR, but whatever.


Anyway, I was offline all Sabbath (sundown to sundown) for a religious holiday and had no opportunity to respond during the <8 hours that this PR lasted. But FWIW after the fact, yes, this seems to work.

**Comment by yuwata** [comment]
@eli-schwartz Sorry for interrupting your holidays.

> But FWIW after the fact, yes, this seems to work.

I am happy to hear that. Thank you.

**Pull request merged**
