### PR TITLE
hwdb: ACCEL_MOUNT_MATRIX for Irbis TW118

### PR DESCRIPTION
**Pull request by brainrom**
This was required to get orientation sensor work properly in my tablet.

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM. I'll squash it though, since the commit message is only present in the PR description.

**Comment by brainrom** [comment]
What should I do? I checked another ACCEL_MOUNT_MATRIX PRs and  don't found messages inside commits.

**Comment by keszybz** [comment]
Yeah, we're not always very good with commit messages. But since you wrote a comment in the PR, I think it's useful to put in the commit message. (Don't discount the comment as trivial: for example it tells us that you own the hardware and tested the patch.)

**Comment by brainrom** [comment]
So? Force re-push with the commit message and PR'll be accepted?

**Pull request merged**
