### PR TITLE
scope rmdir cgroup path return EBUSY cause session remain

### PR DESCRIPTION
**Pull request by JackFangXN**
There is a scenario where all cgroup processes have been killed.
when session**.scope state is dead, will call unit_prune_cgroup to clear cgroup
path. Call rmdir to clear the cgroup path maybe return EBUSY, cause session
cgroup path remain.

Signed-off-by: fangxiuning <fangxiuning@huawei.com>

### CODE REVIEW

**Comment by poettering** [comment]
Not sure I grok this. this is a debug log message only on EBUSY? What precisely are you trying to fix?

**Comment by JackFangXN** [comment]
> Not sure I grok this. this is a debug log message only on EBUSY? What precisely are you trying to fix?

can fix this issue https://github.com/systemd/systemd/issues/16350

**Comment by JackFangXN** [comment]
> Not sure I grok this. this is a debug log message only on EBUSY? What precisely are you trying to fix?

after patch this commt, and the systemd run 42 hours, the sessions stop inscreasing. 

Storage:/sys/fs/cgroup/systemd/user.slice/user-5000.slice # date
Sat Jul  4 15:05:59 CST 2020
Storage:/sys/fs/cgroup/systemd/user.slice/user-5000.slice # ls
cgroup.clone_children  session-1338.scope  session-1908.scope  session-2439.scope  session-2944.scope  session-4682.scope  session-5518.scope  session-6525.scope  session-739.scope
cgroup.procs           session-14.scope    session-1912.scope  session-2440.scope  session-3101.scope  session-4703.scope  session-5566.scope  session-6541.scope  session-763.scope
notify_on_release      session-1409.scope  session-1918.scope  session-2465.scope  session-3129.scope  session-4711.scope  session-5568.scope  session-6542.scope  session-775.scope
session-1033.scope     session-1428.scope  session-1924.scope  session-2481.scope  session-3131.scope  session-4782.scope  session-5620.scope  session-6594.scope  session-785.scope
session-1089.scope     session-1466.scope  session-1985.scope  session-2504.scope  session-318.scope   session-4802.scope  session-5720.scope  session-6597.scope  session-827.scope
session-11.scope       session-1563.scope  session-1998.scope  session-2562.scope  session-3199.scope  session-4817.scope  session-5721.scope  session-6631.scope  session-843.scope
session-1100.scope     session-1571.scope  session-2053.scope  session-2576.scope  session-3211.scope  session-4886.scope  session-5882.scope  session-6648.scope  session-848.scope
session-1116.scope     session-1608.scope  session-2099.scope  session-2605.scope  session-3243.scope  session-4925.scope  session-59.scope    session-6656.scope  session-85.scope
session-1132.scope     session-1670.scope  session-21.scope    session-2614.scope  session-3253.scope  session-4974.scope  session-5901.scope  session-6657.scope  session-851.scope
session-1137.scope     session-1679.scope  session-2193.scope  session-2615.scope  session-3260.scope  session-4989.scope  session-5905.scope  session-6672.scope  session-859.scope
session-1144.scope     session-1690.scope  session-2241.scope  session-2643.scope  session-3263.scope  session-5022.scope  session-5929.scope  session-673.scope   session-875.scope
session-1160.scope     session-1692.scope  session-2284.scope  session-2654.scope  session-330.scope   session-5064.scope  session-5956.scope  session-6782.scope  session-879.scope
session-1170.scope     session-1735.scope  session-2296.scope  session-2679.scope  session-331.scope   session-5084.scope  session-5965.scope  session-68.scope    session-904.scope
session-1199.scope     session-1739.scope  session-2299.scope  session-2682.scope  session-3366.scope  session-5173.scope  session-6158.scope  session-6861.scope  session-939.scope
session-1243.scope     session-1778.scope  session-23.scope    session-2702.scope  session-3371.scope  session-519.scope   session-6164.scope  session-6868.scope  session-956.scope
session-1248.scope     session-1808.scope  session-2304.scope  session-2705.scope  session-3394.scope  session-5246.scope  session-6211.scope  session-6871.scope  session-c15.scope
session-1249.scope     session-1838.scope  session-2314.scope  session-271.scope   session-3401.scope  session-5252.scope  session-6225.scope  session-693.scope   tasks
session-1250.scope     session-1844.scope  session-2343.scope  session-273.scope   session-3423.scope  session-5414.scope  session-6356.scope  session-6933.scope  user-runtime-dir@5000.service
session-1267.scope     session-1860.scope  session-2394.scope  session-276.scope   session-3463.scope  session-5421.scope  session-6364.scope  session-6971.scope  user@5000.service
session-1278.scope     session-1866.scope  session-2395.scope  session-2785.scope  session-3474.scope  session-5422.scope  session-6408.scope  session-699.scope
session-1298.scope     session-1882.scope  session-2412.scope  session-2825.scope  session-3527.scope  session-5435.scope  session-6409.scope  session-7069.scope
session-1299.scope     session-1883.scope  session-2419.scope  session-2834.scope  session-3537.scope  session-5450.scope  session-6442.scope  session-7090.scope
session-13.scope       session-1884.scope  session-2424.scope  session-2854.scope  session-3920.scope  session-5475.scope  session-6451.scope  session-7092.scope
session-130.scope      session-1887.scope  session-2436.scope  session-292.scope   session-400.scope   session-5485.scope  session-6521.scope  session-728.scope
Storage:/sys/fs/cgroup/systemd/user.slice/user-5000.slice # ls session-* | grep scope | wc -l
205
Storage:/sys/fs/cgroup/systemd/user.slice/user-5000.slice # journalctl | grep "r=-16"
Storage:/sys/fs/cgroup/systemd/user.slice/user-5000.slice # ls session-* | grep scope | wc -l
204
Storage:/sys/fs/cgroup/systemd/user.slice/user-5000.slice # date
Mon Jul  6 08:58:13 CST 2020

**Comment by Werkov** [comment]
@JackFangXN There may be valid use cases when cgroup is populated after unit is deactivated (consider `KillMode=none`), hence, `EBUSY` needn't be explicitly handled and cgroup should be removed when empty notification arrives (that's how it _should_ be, I'm not sure if it indeed happens now, the #16350 suggests it doesn't).

Retries typically aren't good way to solve such problems, what would be justification for the count and delays? Furhtermore, you sleep 100 ms up to 25s in the main loop of PID 1, basically blocking any other processing that could've been done in that period. I'd NAK this PR.

**Comment by JackFangXN** [comment]
> @JackFangXN There may be valid use cases when cgroup is populated after unit is deactivated (consider `KillMode=none`), hence, `EBUSY` needn't be explicitly handled and cgroup should be removed when empty notification arrives (that's how it _should_ be, I'm not sure if it indeed happens now, the #16350 suggests it doesn't).
> 
> Retries typically aren't good way to solve such problems, what would be justification for the count and delays? Furhtermore, you sleep 100 ms up to 25s in the main loop of PID 1, basically blocking any other processing that could've been done in that period. I'd NAK this PR.

en, you are right, delay is not better. how do you think about using a timer to fix this problem. Start a timer when return 'EBUSY', if you agree i will push a PR.

**Comment by Werkov** [comment]
Timer would be indeed better for the implementation of the retry idea. However, the ultimate source of information should be emptiness notification. Could you please share more details in #16350 to uncover the real cause of the cgroup directories accummulation?

**Comment by poettering** [comment]
sleeping like this in PID 1 is not OK. But I don#t grok the issue really. we watch cgroup empty notifications and should clean up eventually, once we see that.

Is this on cgroupv1 or cgroupv2?

are the cgroup empty notifications not seen? or do they happen when the cgroup till returns EBUSY when deleted?

This really doesn't look like an appropriate fix, more like taping over another bug?

**Pull request closed without merging**
