### PR TITLE
Rotation info for Teclast F5 accel sensor

### PR DESCRIPTION
**Pull request by lbernstone**

### CODE REVIEW

**Comment by luluprat** [comment]
hello @lbernstone
do you own a teclast F5 because my touchpad suspend mod is broken ?
any help would be apriciate
Thanks
Lucile

**Comment by hadess** [comment]
> do you own a teclast F5 because my touchpad suspend mod is broken ?
> any help would be apriciate
> Thanks
> Lucile

This isn't relevant here, please take the discussion elsewhere.

**Comment by luluprat** [comment]
i would like to talk to him but i don't know how to go else where ?
i don't have his email ?

**Comment by keszybz** [comment]
`upstream             FAIL timed out` — I guess that's unrelated.

**Pull request merged**
