### PR TITLE
Generalize FailureAction=, and add SuccessAction=

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by keszybz** [comment]
Looks nice.

**Comment by keszybz** [comment]
`upstream` fails on s390x. I'll restart the test.

**Comment by keszybz** [comment]
```
+ [  205.921569] rc.local[25]: /etc/rc.local: 2: /etc/rc.local: iptables: not found
[[0;32m  OK  [0m] Started /etc/rc.local Compatibility.
set -ex
+ set -o pipefail
/testsuite.sh: 5: set: Illegal option -o pipefail
[[0;1;31mFAILED[0m] Failed to start Testsuite service.
See 'systemctl status testsuite.service' for details.
         Starting End the test...
[[0;32m  OK  [0m] Started Permit User Sessions.
[[0;32m  OK  [0m] Started Console Getty.
[[0;32m  OK  [0m] Reached target Login Prompts.
[[0;32m  OK  [0m] Started D-Bus System Message Bus.
[[0;32m  OK  [0m] Started Login Service.
[[0;32m  OK  [0m] Reached target Multi-User System.
         Starting Update UTMP about System Runlevel Changes...
         Stopping D-Bus System Message Bus...
[[0;32m  OK  [0m] Stopped target Timers.
[[0;32m  OK  [0m] Stopped Daily Cleanup of Temporary Directories.
[[0;32m  OK  [0m] Stopped End the test.
[[0;32m  OK  [0m] Stopped Update UTMP about System Runlevel Changes.
[[0;32m  OK  [0m] Stopped target Multi-User System.
[[0;32m  OK  [0m] Stopped target Login Prompts.
         Stopping Console Getty...
         Stopping Login Service...
[[0;32m  OK  [0m] Stopped Login Service.
[[0;32m  OK  [0m] Stopped Console Getty.
[[0;32m  OK  [0m] Stopped /etc/rc.local Compatibility.
         Stopping Permit User Sessions...
[[0;32m  OK  [0m] Stopped D-Bus System Message Bus.
[[0;32m  OK  [0m] Stopped Permit User Sessions.
[[0;32m  OK  [0m] Stopped target Basic System.
[[0;32m  OK  [0m] Stopped target Sockets.
[[0;32m  OK  [0m] Closed D-Bus System Message Bus Socket.
[[0;32m  OK  [0m] Stopped target Paths.
[[0;32m  OK  [0m] Stopped target Slices.
[[0;32m  OK  [0m] Removed slice User and Session Slice.
[[0;32m  OK  [0m] Stopped target System Initialization.
[[0;32m  OK  [0m] Stopped Rebuild Hardware Database.
[[0;32m  OK  [0m] Stopped target Local Encrypted Volumes.
[[0;32m  OK  [0m] Stopped Forward Password Requests to Wall Directory Watch.
[[0;32m  OK  [0m] Stopped Dispatch Password Requests to Console Directory Watch.
         Stopping Update UTMP about System Boot/Shutdown...
[[0;32m  OK  [0m] Stopped Update UTMP about System Boot/Shutdown.
[[0;32m  OK  [0m] Stopped Create Volatile Files and Directories.
[[0;32m  OK  [0m] Stopped target Local File Systems.
         Unmounting /tmp...
         Unmounting /run/systemd/nspawn/incoming...
[[0;32m  OK  [0m] Unmounted /run/systemd/nspawn/incoming.
[[0;32m  OK  [0m] Unmounted /tmp.
[[0;32m  OK  [0m] Reached target Unmount All Filesystems.
[[0;32m  OK  [0m] Stopped target Local File Systems (Pre).
[[0;32m  OK  [0m] Stopped target Swap.
[[0;32m  OK  [0m] Reached target Shutdown.
[[0;32m  OK  [0m] Reached target Final Step.
         Starting Power-Off...
Container nspawn-root has been shut down.
-rw-r-----+ 1 root systemd-journal 8388608 Nov 20 05:21 /var/tmp/systemd-test.f2x6Oq/journal/da23c4aa5d3e4b9aa96b0b8e6dbd20ff/system.journal
TEST RUN: FailureAction= operation [FAILED]
Makefile:4: recipe for target 'run' failed
make: Leaving directory '/tmp/autopkgtest.Z4KDvG/build.svT/debian/test/TEST-18-FAILUREACTION'
---- /var/tmp/systemd-test.f2x6Oq/journal/da23c4aa5d3e4b9aa96b0b8e6dbd20ff ----
make: *** [run] Error 1
```

**Comment by poettering** [comment]
Force pushed a new version, which hopefully fixes the CI test issue (bash vs. sh, gahhh)

**Comment by keszybz** [comment]
`s390x` — `E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)`.
Let's see what the other two say.

**Comment by keszybz** [comment]
artful-s390x failed on efi partition detection, I'll restart it.

**Comment by poettering** [comment]
i386 and s390x worked now, that should be good enough. let's merge this

**Pull request merged**
