### PR TITLE
meson: sysctl.d/ and other early boot configs should be installed to /lib

### LINKED ISSUE #8481: sysctl.d and other files are unconditionally installed to /usr/lib; our docs say this is wrong
### Submission type

 - Bug report

### systemd version the issue has been seen with

* source code of git master (`prefixdir` v.s. `rootprefixdir` usage in `/meson.build`).
* 232-25+deb9u1

### Used distribution

Debian 9

### In case of bug report: Expected behaviour you didn't see

> systemd itself is actually completely fine with /usr on a separate file system that is not pre-mounted at boot time.

-- as per https://freedesktop.org/wiki/Software/systemd/separate-usr-is-broken/

This is public documentation, which claims that people will read it because systemd prints a warning about split `/usr` w/o pre-mounting.  (Presently I understand this exists in the form of the taint message logged at boot time).  Therefore I presume it's supposed to be kept up to date.

### In case of bug report: Unexpected behaviour you saw

systemd-sysctl.service has `DefaultDependencies=no` and no explicit dependency on `/usr`.  (Also it is pulled in by sysinit.target.  The docs for which, tell us "System services pulled in by this target should declare DefaultDependencies=no and specify all their dependencies manually, including access to anything more than a read only root filesystem.)

But `50-coredump.conf` is installed to `/usr/lib/sysctl.d/`

There are other files in /usr/lib/systemd which I am also suspicious about...

### In case of bug report: Steps to reproduce the problem

Look at a current Debian system (w/o the non-default adoption of usr merge).  You will see both `/lib/systemd` and `/usr/lib/systemd`.  The directory under `/usr` includes a non-empty `sysctl.d`.

---

Apart from sysctl, the other paths in master `/meson.build` that look suspicious to me are

* `sysusersdir = join_paths(prefixdir, 'lib/sysusers.d')` - systemd-sysusers.service
* `binfmtdir = join_paths(prefixdir, 'lib/binfmt.d')` - systemd-binfmt.service
* `modulesloaddir = join_paths(prefixdir, 'lib/modules-load.d')` - systemd-modules-load.service
* `systemenvgeneratordir = join_paths(prefixdir, 'lib/systemd/system-environment-generators')` - man systemd.environment-generator

Such paths are exported in `systemd.pc`, and in principle in rpm macros.  (Internally, I see only `sysctl.d` and `sysusers.d`).

### PR DESCRIPTION
**Pull request by sourcejedi**
and not /usr/lib.  E.g. systemd-sysctl.service has DefaultDependencies=no,
and no explicit dependency on /usr.  Closes #8481.

* binfmt.d
* modules-load.d
* sysctl.d
* sysusers.d
* systemd/system-environment-generators
* tmpfiles.d

Scope
-----

This would affect setups which start systemd without /usr pre-mounted (in
initramfs).  While we claimed systemd itself supported such setup, nowadays
this should be pretty rare.  Debian stretch has officially withdrawn
support for it.

The problem is more that Debian is currently still carrying the /usr split.
This makes systemd's failure to support mounting /usr quite visible...
when you look at the installed paths, or the doctored manpages from the
Debian systemd package.

Given that we make this distinction *at all* between installing things to
`prefixdir` and `rootprefixdir`, let's make a story for readers which is
consistent, one which doesn't look like there's a bug, without assuming
they are up to date on the latest developments.

How we avoid breaking existing setups
-------------------------------------

No extra migration work should be necessary.  While upstream manpages
pretend the /usr split doesn't exist, in fact when we are built with
split_usr=true we are looking in both /lib AND /usr/lib for config files.
So when /usr is pre-mounted, we will read it opportunistically.
(Also, we do so in such a way that allows a graceful migration.  It
shouldn't matter if /lib/foo.conf and /usr/lib/foo.conf end up being two
different aliases of the same file, because only one of them will be read).

A change may be desirable in the Debian package, to include these new
directories in the `sed` command which doctors their man pages :).

Tested
------

On a small nspawn, without /lib/ being a symlink to /usr/lib, boot remains
successful with no error messages in `journalctl -b`.

### CODE REVIEW

**Comment by sourcejedi** [comment]
> The other approach would be for systemd to stop installing it's own stuff separately to /lib and /usr/lib. Only use separate paths for consuming files, installed by people who have not yet migrated to merged-usr thinking. Drop entirely the claim that systemd can support mounting /usr part-way through the boot. Maybe it's the opportune time to do that?

**Comment by poettering** [comment]
lgtm. I have the suspicion though that this will trip up all CIs that build packages from git, as none of the sources will be right anymore.

**Comment by poettering** [comment]
> The other approach would be for systemd to stop installing it's own stuff separately to /lib and /usr/lib. Only use separate paths for consuming files, installed by people who have not yet migrated to merged-usr thinking. Drop entirely the claim that systemd can support mounting /usr part-way through the boot. Maybe it's the opportune time to do that?

Would love to do that, but I doubt downstreams are ready for that yet. It's one thing to declare that boots without /usr pre-mounted are unsupported. It's another thing to actually merge /usr, so that /bin and /usr/bin point to the same dir, so that it doesn't matter anymore which path we drop our binaries in. AFAICS Debian still hasn't properly merged /usr, and that means that the paths used to reference the binaries are still their API that we can't just break.

It's a mess. I wish Debian would really just merge the thing, but they move in glacial speeds...

**Comment by sourcejedi** [comment]
Ah, yes.  So it's not 100% churn-free for split-usr downstreams, but it's not too obscure and at least it signals itself with a build error.

**Comment by poettering** [comment]
Closing as per discussion in #8481.

**Pull request closed without merging**
