### PR TITLE
Fix bogus fragment paths in units in .wants/.requires

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
I think we *must* always ignore the path targets. Ever looking at them leads to "heisenbugs":
- if the unit file is found in two places in our search path, depending on unit loading order, we'll get either the one or the other. In #9921 different instances of the *same* unit file get different contents!
- if the unit file is somewhere outside our search path, starting the unit directly will fail, but starting it as a dependency of another unit will succeed.

We already have a system for bringing in units outside of the load path: `systemctl link`. This works and has cleanly defined semantics.

**Comment by arvidjaar** [comment]
> I think we must always ignore the path targets. Ever looking at them leads to "heisenbugs"

In this case what's the point in having symlink in the first place? It is equally confusing to have link pointing to one unit definition but systemd picking up entirely different one. Just replace symlinks with `touch xxx.wants/yyy.service` as handle. 

BTW how should symlink with missing target be interpreted?

**Comment by keszybz** [comment]
Yes, but there was an RFE to allow that. But even if we never do that, I think it'd be very confusing to have very different semantics for the main unit files, drop-ins, and symlink dirs. We currently warn if the target of the symlink points to a file with a mismatching name. This should be enough to warn people if they just link to the wrong file. What remains, is to actually ignore the contents of the symlink fully, which this patch does.

**Comment by arvidjaar** [comment]
> We can't use empty files or symlinks to `/dev/null` because that has a different meaning: a mask.

I did not suggest using symlinks to `/dev/null`. And we **can** use empty file as unit name token and symlink to `/dev/null` as indication that unit is masked. And we never did it in `.wanted` directories anyway so there is no incompatibility here.

**Comment by keszybz** [comment]
IIUC, you are suggesting to allow empty files, but not symlinks to `/dev/null` to signify enablement. I think this would be even more confusing, because we give special meaning to empty files. So there would be **three** semantics in play depending on systemd version and configuration type: 1. allow both /dev/null and empty to mask, 2. allow only /dev/null to mask, 3. current semantics of no masking.

The semantics you propose are also incompatible with the RFE to allow masking in .wants/.requires.

**Comment by fbuihuu** [comment]
> The semantics you propose are also incompatible with the RFE to allow masking in .wants/.requires.

Since https://github.com/systemd/systemd/commit/871768e94938a6a01555da0d02d29449a6c1585f, the semantic is currently 1. (not 3.), no ?

**Comment by poettering** [comment]
Merging. This probably deserves some mention in NEWS though

**Pull request merged**
