### PR TITLE
man: add missing /usr/local/lib in search paths

### PR DESCRIPTION
**Pull request by behrmann**

### CODE REVIEW

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by keszybz** [comment]
Hmm, so we have this policy of **not** documenting /usr/local/lib. If we do add this, I think it should be added in all places. @poettering, WDYT?

**Comment by behrmann** [comment]
Yeah, after opening this, I noticed it was missing everywhere and I was about to open a followup, when I got called out of my office. I have the changes queued locally and can add them. Having just gone through them, they are already documented for generators and environment-generator (and units, though there only further down in a table).

Back of the envelope, the following man pages would be touched (with some false positives).
```
# git grep /run -- man | grep '<member>' | awk '{print $1}' | uniq
man/binfmt.d.xml:
man/coredump.conf.xml:
man/dnssec-trust-anchors.d.xml:are needed
man/environment.d.xml:
man/homed.conf.xml:
man/journal-remote.conf.xml:
man/journald.conf.xml:
man/logind.conf.xml:
man/modules-load.d.xml:
man/networkd.conf.xml:
man/oomd.conf.xml:
man/pstore.conf.xml:
man/repart.d.xml:
man/resolved.conf.xml:
man/sysctl.d.xml:
man/systemd-sleep.conf.xml:
man/systemd.environment-generator.xml:
man/systemd.generator.xml:
man/systemd.nspawn.xml:
man/systemd.pcrlock.xml:
man/systemd.preset.xml:
man/systemd.unit.xml:
man/sysupdate.d.xml:
man/sysusers.d.xml:
man/timesyncd.conf.xml:
man/tmpfiles.d.xml:
man/udev.conf.xml:
```

**Comment by keszybz** [comment]
I think it's reasonable to do this. The old policy of not documenting those paths had some merit, but OTOH, it's confusing and doesn't really make sense, since those paths *are* supported and there is no plan to stop supporting them. So this also goes against our policy of documenting supported and non-deprecated features.

**Comment by behrmann** [comment]
I've updated this to add `/usr/local/lib` every where it was missing, to make it consistent. I think it should be documented, because, as just said, it's supported. As long as it's supported not having it documented, it could be confusing to users to find (or worse, not find) files there that affect the configuration. Also, in the NEWS for the current release, we explicitly mention
> Various programs will now attempt to load the main configuration file
          from locations below /usr/lib/, /usr/local/lib/, and /run/, not just
          below /etc/. 

If it's in the news, it should be in the man pages as well.

**Review by keszybz — APPROVED** [review]
Yeah, let's do this.

I expect that there are other places which may/should be updated too, but we can do that separately as we notice them.

**Comment by behrmann** [comment]
Making the changes, I went through the tools using the configs and looked for `CONF_PATHS_STRV` and `config_parse_standard_file_with_dropins_full` and made the changes where I found them (or similar in case `user-tmpfiles`). I hope i didn't miss or misidentify anything.

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
Umpf, this should not have been merged.

/usr/local is such a fucked up concept, people assume it can be mounted late. But you now documented this to be supported for various super early boot stuff. This is a total mess.

**Comment by behrmann** [comment]
Sorry for having brought this up.

As I see it, it's been documented already for the most important ones already: the `systemd.unit` man page lists it in a table, where people already found it, the man pages `systemd.generator` and `systemd.environment-generator` list it directly in the listing at the top. They all do since at least v247. The `systemd.link` man pages mentions `/usr/local/lib/systemd/network` since v251 and `systemd.network` mentions it since at least v247, too. As quoted above, the NEWS for v256 mentions it, too.

**Comment by keszybz** [comment]
But that's pretty much those things which are ran during early boot…

**Pull request merged**
