### PR TITLE
Coredump fixes and more

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by zonque** [comment]
LGTM. @keszybz, could you have a look as well?

**Comment by keszybz** [comment]
Looks good. I made some small comments on the way, but the `--fdname` thing is the only real issue, others are suggestions. `--fdname` can be changed later if wanted.

**Comment by keszybz** [comment]
BTW, what happens with pages marked MADV_DONTDUMP or excluded in /proc/PID/coredump_filter? Does the kernel do the filteing for us and we get 0's?

**Comment by poettering** [comment]
Yes, the kernel suppresses select VMAs from dumping to our tool.

**Comment by poettering** [comment]
will prep a fix and force push.

**Comment by poettering** [comment]
thanks for the review!

**Comment by poettering** [comment]
I now force-pushed a new version with the added comment as @keszybz suggested, plus a reword of one commit msg, to clarify the RLIMIT_CORE thing @keszybz was wondering about.

I also added a new commit that documents the coredump changes in NEWS.

**Comment by poettering** [comment]
OK, pressing the green button myself now, as this was already reviewed and I just made comment fixes and semaphore likes it too.

**Pull request merged**
