### PR TITLE
test: support the new lvm udev autoactivation

### PR DESCRIPTION
**Pull request by mrc0mmand**
Introduced in lvm 2.03.14.
See: https://sourceware.org/git/?p=lvm2.git;a=commit;h=67722b312390cdab29c076c912e14bd739c5c0f6

### CODE REVIEW

**Review by bluca — APPROVED** [review]
lgtm

**Comment by mrc0mmand** [comment]
Whoops, I need to fix `TEST-64` as well, since it explicitly checks for the `lvm2-pvscan@.service` status.

**Comment by mrc0mmand** [comment]
So, I tested this locally, and it seems to work. However, I'm not completely sure if it won't introduce a race condition, since the `vgchange` in the new udev rule is run with `systemd-run --no-block`, so there may be a synchronization issue?

```
  IMPORT{program}="(LVM_EXEC)/lvm pvscan --cache --listvg --checkcomplete --vgonline --udevoutput --journal=output $env{DEVNAME}"
  ENV{LVM_VG_NAME_COMPLETE}=="?*", RUN+="/usr/bin/systemd-run -r --no-block --property DefaultDependencies=no --unit lvm-activate-$env{LVM_VG_NAME_COMPLETE} lvm vgchange -aay --nohints $env{LVM_VG_NAME_COMPLETE}"
  GOTO="lvm_end"
```

New rule: https://sourceware.org/git/?p=lvm2.git;a=blob;f=udev/69-dm-lvm.rules.in;h=39e5b98074010745f78a7a86a05929700c9cd690;hb=67722b312390cdab29c076c912e14bd739c5c0f6#l82)
Old rule: https://sourceware.org/git/?p=lvm2.git;a=blob;f=udev/69-dm-lvm-metad.rules.in;h=78f506520c45ef7fb03fefa7f97b76770cdc1557;hb=67722b312390cdab29c076c912e14bd739c5c0f6#l103

/cc @yuwata

**Comment by yuwata** [comment]
Previously, `lvm2-pvscan@.service` activates VG on the PV. So, it was sufficient to check if the service is started.
But now, `lvm-activate-$vgroup.service` activates the VG. So, it seems we need to check the service is finished. Otherwise, no uevent for the VG may not triggered when we call `udevadm settle`.
How about to introduce, say `helper_wait_for_lvm_activate()` which wait for lvm-activate-$vgroup.service? I guess the new helper can be simpler than `helper_wait_for_pvscan()` as we can simply use `$vgroup` variable.

**Comment by mrc0mmand** [comment]
> Previously, `lvm2-pvscan@.service` activates VG on the PV. So, it was sufficient to check if the service is started. But now, `lvm-activate-$vgroup.service` activates the VG. So, it seems we need to check the service is finished. Otherwise, no uevent for the VG may not triggered when we call `udevadm settle`. How about to introduce, say `helper_wait_for_lvm_activate()` which wait for lvm-activate-$vgroup.service? I guess the new helper can be simpler than `helper_wait_for_pvscan()` as we can simply use `$vgroup` variable.

Thanks, that definitely makes it clear. I tested the new implementation on both "old" and new lvm and it seems to work like a charm, PTAL!

**Review by yuwata — APPROVED** [review]
LGTM.

**Comment by mrc0mmand** [comment]
Both CI fails are unrelated, merging.

**Pull request merged**
