### PR TITLE
Enable more tests by default, and even more with `--enable-tests=unsafe`

### PR DESCRIPTION
**Pull request by keszybz**
Tests that are not run, even to return EXIT_TEST_SKIP tend to bitrot faster. Run more by default.

CI tests should be run with `--enable-tests=unsafe`.

### CODE REVIEW

**Comment by keszybz** [comment]
Test failure seems unrelated:

```
======================================================================
FAIL: test_service (__main__.NspawnTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/adt-run.giaVty/build.gpL/systemd/debian/tests/boot-and-services", line 229, in test_service
    self.assertTrue('Stopped Container c1' in out, out)
AssertionError: False is not true : ● systemd-nspawn@c1.service - Container c1
   Loaded: loaded (/lib/systemd/system/systemd-nspawn@.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:systemd-nspawn(1)
```

**Comment by evverx** [comment]
> Test failure seems unrelated

Yeah, it's a known issue:
- https://github.com/systemd/systemd/pull/2719#issuecomment-188140269
- https://github.com/systemd/systemd/pull/2698#issuecomment-187270049

@martinpitt , I've reproduced that fail locally:

```
ubuntu@ubuntu-xenial:~$ sudo journalctl --sync
ubuntu@ubuntu-xenial:~$ sudo systemctl status systemd-nspawn@c1
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]:     1 0        init
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]:     2 0        {rcS} /bin/sh /etc/init.d/rcS
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]:     3 0        {exe} ps aux
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: umount: can't remount tmpfs read-only
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: umount: can't remount /dev/sda1 read-only
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: [47B blob data]
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: [30B blob data]
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: [30B blob data]
Feb 28 01:22:51 ubuntu-xenial systemd-nspawn[4949]: [30B blob data]
Feb 28 01:22:51 ubuntu-xenial systemd-nspawn[4949]: [27B blob data]

ubuntu@ubuntu-xenial:~$ sudo journalctl -u systemd-nspawn@c1.service -a
...
Feb 28 01:22:50 ubuntu-xenial systemd[1]: Starting Container c1...
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: mount(/var/lib/machines/c1/sys/fs/selinux) failed, ignoring: No such file or directory
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: mount(/var/lib/machines/c1/sys/fs/selinux) failed, ignoring: Invalid argument
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: Timezone Etc/UTC does not exist in container, not updating container timezone.
Feb 28 01:22:50 ubuntu-xenial systemd[1]: Started Container c1.
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: fake container started
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: PID   USER     COMMAND
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]:     1 0        init
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]:     2 0        {rcS} /bin/sh /etc/init.d/rcS
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]:     3 0        {exe} ps aux
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: umount: can't remount tmpfs read-only
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: umount: can't remount /dev/sda1 read-only
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: ^Mcan't run 'swapoff': No such file or directory
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: ^MThe system is going down NOW!
Feb 28 01:22:50 ubuntu-xenial systemd-nspawn[4949]: ^MSent SIGTERM to all processes
Feb 28 01:22:51 ubuntu-xenial systemd-nspawn[4949]: ^MSent SIGKILL to all processes
Feb 28 01:22:51 ubuntu-xenial systemd-nspawn[4949]: ^MRequesting system poweroff

ubuntu@ubuntu-xenial:~$ sudo journalctl | grep 'Stopped.*c1'
Feb 28 01:12:31 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:13:07 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:14:59 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:15:33 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:15:42 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:16:45 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:16:50 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:16:56 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:17:03 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:17:09 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:17:15 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:17:22 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:17:29 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:17:36 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:17:48 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:17:56 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:18:08 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:18:27 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:18:35 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:19:08 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:19:18 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:19:24 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:20:40 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:20:48 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:20:55 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:22:35 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:22:41 ubuntu-xenial systemd[1]: Stopped Container c1.
Feb 28 01:22:46 ubuntu-xenial systemd[1]: Stopped Container c1.
```

So, we lose `Stopped Container c1` sometimes.

**Comment by keszybz** [comment]
Hm, and why do we get those '^M's in the log lines, is this a known issue too?

**Comment by evverx** [comment]
> and why do we get those '^M's in the log lines

`init` (from the `busybox`) [adds](https://anonscm.debian.org/git/d-i/busybox.git/tree/init/init.c?id=f1f1700ab1be58afc5695218503875ac4f1e8674#n222) `\r`.

```
$ tree c1
c1
├── bin
│   ├── busybox
│   └── sh -> busybox
├── etc
│   ├── init.d
│   │   └── rcS
│   ├── machine-id
│   └── os-release
└── sbin
    └── init -> ../bin/busybox

$ sudo systemd-nspawn -D ./c1 -b |& cat -A
Spawning container c1 on /home/ubuntu/./c1.$
Press ^] three times within 1s to kill container.$
Failed to create directory /home/ubuntu/./c1/sys/fs/selinux: Read-only file system$
Failed to create directory /home/ubuntu/./c1/sys/fs/selinux: Read-only file system$
Timezone Etc/UTC does not exist in container, not updating container timezone.$
fake container started$
PID   USER     COMMAND$
    1 0        init$
    2 0        {rcS} /bin/sh /etc/init.d/rcS$
    3 0        busybox ps aux$
umount: can't remount tmpfs read-only$
umount: can't remount /dev/sda1 read-only$
^Mcan't run 'swapoff': No such file or directory$
^MThe system is going down NOW!$
^MSent SIGTERM to all processes$
^MSent SIGKILL to all processes$
^MRequesting system poweroff$
Container c1 has been shut down.$
$
```

**Comment by keszybz** [comment]
```
adt-run [03:23:37]: test timedated: [-----------------------
original tz: Etc/UTC
timedatectl works
change timezone
reset timezone to original
no adjtime file
UTC set in adjtime file
non-zero values in adjtime file
fourth line adjtime file
no final newline in adjtime file
Failed to set local RTC: Failed to set RTC to local/UTC: Input/output error
adt-run [03:23:38]: test timedated: -----------------------]
adt-run [03:23:38]: test timedated:  - - - - - - - - - - results - - - - - - - - - -
timedated            FAIL non-zero exit status 1
adt-run [03:23:38]: test timedated:  - - - - - - - - - - stderr - - - - - - - - - -
Failed to set local RTC: Failed to set RTC to local/UTC: Input/output error
```

**Comment by evverx** [comment]
Seems like you should rebase your branch to c9410dd47f4e9ba20

**Comment by keszybz** [comment]
Good point. Let's see how that goes.

**Comment by keszybz** [comment]
It's the same old

```
FAIL: test_service (__main__.NspawnTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/adt-run.8WpilC/build.kbc/systemd/debian/tests/boot-and-services", line 229, in test_service
    self.assertTrue('Stopped Container c1' in out, out)
AssertionError: False is not true : ● systemd-nspawn@c1.service - Container c1
   Loaded: loaded (/lib/systemd/system/systemd-nspawn@.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:systemd-nspawn(1)
```

**Comment by evverx** [comment]
> It's the same old

I've prepared a patch https://gist.githubusercontent.com/evverx/bcff0e97baa37dbb595a/raw/026b7b190d545eb061be04ea5bcb9c223c113682/0001-debian-tests-boot-and-services-don-t-rely-on-Stopped.patch

> So, we lose Stopped Container c1 sometimes.

Is this a known issue? I can't find.

**Comment by martinpitt** [comment]
@evverx: Did you ever see this fail on `test_boot()`? I didn't. This test also asserts the presence of the "shut down" message, although directly from nspawn's output, not from the journal.

So I suspect the race condition is maybe just that sometimes the container takes more than 5 seconds to start, run, and stop (although that's rather unlikely)? I. e. the `time.sleep(5)` is certainly bad there.

I committed http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=5406a85f now which properly waits for units. Let's see how far that gets us, and if that failure still happens, we can still disable the journal line test.

**Comment by evverx** [comment]
> Did you ever see this fail on test_boot()?

I didn't.

But `test_boot`
- doesn't run `systemd-nspawn` via `systemctl`
- doesn't check the message: `systemd[1]: Stopped Container c1`

:)

> Let's see how far that gets us

Ok. Thanks!

**Comment by martinpitt** [comment]
Evgeny Vereshchagin [2016-03-07  9:00 -0800]:

> But `test_boot`
> - doesn't run `systemd-nspawn` via `systemctl`

That's right.

> - doesnt't check the message: `systemd[1]: Stopped Container c1`

Ah right, sorry -- it checks for "Container c1.*shut down" which is
slightly diffeent.

**Comment by evverx** [comment]
> and if that failure still happens, we can still disable the journal line test.

@martinpitt , https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20160309_161216@/log.gz

**Comment by martinpitt** [comment]
@evverx just followed up to PR #2816 about that, I just pushed a test update which now stops relying on that journal message. This does not affect _this_ PR, all 3 tests are green.

**Comment by martinpitt** [comment]
This looks great, thank you!

@zonque: Can you please add `--enable-tests=unsafe` to the Semaphore recipe?

**Comment by evverx** [comment]
> I just pushed a test update which now stops relying on that journal message

Thanks!

> This does not affect this PR, all 3 tests are green.

Oh, I missed the last commit. Sorry.

**Comment by keszybz** [comment]
@martinpitt, @evverx thanks for looking into this.
I added `--enable-tests=unsafe` to semaphore now and fired off a new build of master. Let's see how this goes.

**Pull request merged**
