### PR TITLE
Smack v10: set only the default smack process label if the command path has no execute label

### PR DESCRIPTION
**Pull request by walyong**
- util: add getxattr helper apis
- smack-util: revise smack-util apis and add read smack attr apis
- core: set default process label only exec label is none

### CODE REVIEW

**Comment by zonque** [comment]
> v is free-ed in ahead of this scope.

Yes, but not if you return with `return -errno;`. In this case, `free(v);` is not called.

**Comment by zonque** [comment]
> If the size of the buffer is not enought, {l}getxattr() just return -1. (does not return of the real size of the value.) So if the return is negative then we have to get the size of the value by calling {l}getxattr() with NULL pointer and size 0.
> And if we allocate the same size of {l}getxattr(), we have to get again the size for the null-terminate string.

Ok, but in that case, I'd suggest to call into `getxattr()` with a NULL pointer in the first place, in order to get the needed size. The call again with the newly allocated buffer. This way, you also avoid passing back a buffer which is much too big for the content it holds, which is the case right now if the needed size is less than 100 bytes. You can write that as a `while(1) { ... }` loop and bail out as soon as the 2nd `getxattr()` call with the real buffer succeeds. This makes the code easier to read.

**Comment by zonque** [comment]
IOW, something like this should work, but I didn't test it:

``` c
int getxattr_malloc(const char *path, const char *name, char **value, bool allow_symlink) {
        _cleanup_free_ char *v = NULL;
        ssize_t n;

        assert(path);
        assert(name);
        assert(value);

        while (1) {
                if (allow_symlink)
                        n = lgetxattr(path, name, NULL, 0);
                else
                        n = getxattr(path, name, NULL, 0);
                if (n < 0)
                        return -errno;

                v = realloc(v, n + 1);
                if (!v)
                        return -ENOMEM;

                if (allow_symlink)
                        n = lgetxattr(path, name, v, n);
                else
                        n = getxattr(path, name, v, n);
                if (n < 0) {
                        if (errno == ERANGE)
                                continue;

                        return -errno;
                }

                break;
        }

        v[n] = 0;
        *value = v;
        v = NULL;
        return n;
}
```

**Comment by zonque** [comment]
Ok, after discussing this internally: please ignore my last two comments, sorry about the confusion. Lennart has a point that wasting some memory is probably not as bad as always issuing twice the amount of syscalls. So just stick with what you had before, and address the memory leak and the exponential growth.

We're very close, so let's get this merged :)

**Comment by walyong** [comment]
Hmm, I can not understand what you want yet. What of memory leak? And which exponential growth? Do you want similar style of #745 with some of changes for the allow_link? But as I said, we can not use the return size, because the buffer size is not enough then {l}getxattr() return -1. So if you really want to use a style of #745 then we have to do (l *= 2;) for each loop.

Please, give me some more hint, then I will do re-work.

**Comment by poettering** [comment]
OK, I think I get what you are saying. Yeah the exponential loop is pointless. We can as well just try with a fixed size, and on failure then query the precise size. That is safe as long as we do it in a loop.

**Comment by poettering** [comment]
And I am very sorry for the constant forth and back on this. I acknowledge that neither @zonque and I, nor I with myself were very consistent with our message... Sorry for that!

**Comment by zonque** [comment]
@walyong the only remaining issues with your latest patch set are the following two comments then:

https://github.com/systemd/systemd/pull/752#commitcomment-12390315
https://github.com/systemd/systemd/pull/752#issuecomment-126108258

Ignore everything else, file a new PR and we can hopefully finally merge this :)

**Comment by poettering** [comment]
Obsoleted by #860

**Pull request closed without merging**
