### PR TITLE
test-systemctl-enable: make titles more consistent

### PR DESCRIPTION
**Pull request by diegoviola**

### CODE REVIEW

**Comment by diegoviola** [comment]
I'm not sure about: https://github.com/systemd/systemd/blob/c9b97545ad3617cecbfb4db64107b826d44d0e29/test/test-systemctl-enable.sh#L593 though.

**Comment by diegoviola** [comment]
@keszybz ping?

**Comment by diegoviola** [comment]
@yuwata ping?

**Review by yuwata — APPROVED** [review]
I do not think it is necessary to adjust such cosmetic lines. But, not bad. Merging.

**Pull request merged**
