### PR TITLE
hwdb: Force no "mouse" type on Logitech MX Keys

### PR DESCRIPTION
**Pull request by bdaase**
Fixes https://gitlab.freedesktop.org/upower/upower/-/issues/128

### CODE REVIEW

**Review by bluca — APPROVED** [review]
Lgtm - cc @hadess

**Comment by hadess** [comment]
> `Failed to parse: 'ID_INPUT_MOUSE=0'`

I haven't looked at why it fails, but it does.

**Comment by hadess** [comment]
@keszybz do you know why we only allow `1` as the value for those `ID_*` properties?

https://github.com/systemd/systemd/blob/master/hwdb.d/parse_hwdb.py#L136

**Comment by keszybz** [comment]
> @keszybz do you know why we only allow `1` as the value for those `ID_*` properties?
> 
> https://github.com/systemd/systemd/blob/master/hwdb.d/parse_hwdb.py#L136

That was the only thing that we set. I guess the assumption was that it is either set to =1, or not set at all. If it makes sense to set it to =0 too, then the test should be relaxed to allow that.

**Comment by BjoernDaase** [comment]
@keszybz Setting it to 0 in my local `/usr/lib/udev/hwdb.d/60-input-id.hwdb` works as expected in the "wild". Therefore, I addes a second commit relaxing the condition of the parsing script.

**Comment by hadess** [comment]
> @keszybz Setting it to 0 in my local `/usr/lib/udev/hwdb.d/60-input-id.hwdb` works as expected in the "wild". Therefore, I addes a second commit relaxing the condition of the parsing script.

The code probably looks fine, but there's loads of whitespace changes that shouldn't be in there. Take a look at the diff and please amend those, thanks.

**Comment by BjoernDaase** [comment]
> The code probably looks fine, but there's loads of whitespace changes that shouldn't be in there. Take a look at the diff and please amend those, thanks.

Whoops, VSCode auto-formatting :(  
Nevertheless, fixed now.

**Comment by hadess** [comment]
The Centos problem is a crash running the seccomp test, which isn't our fault. Let's merge this. Thanks for the patch!

**Comment by BjoernDaase** [comment]
Thanks for the guidance!

**Pull request merged**
