### PR TITLE
execute: run setrlimit before getrlimit

### PR DESCRIPTION
**Pull request by tblume**
get_supplementary_groups in the ExecStart code triggers a call to libtirpc
in order to resolve NIS groups.
libtirpc uses getrlimit in its code, but at the time of this call, rlimits
aren't applied yet.
That causes getrlimit to return a wrong value.

Make sure that setrlimit is called before get_supplementary_groups.

### CODE REVIEW

**Comment by poettering** [comment]
i don't get this? Which rlimit is this precisely about? why would libtirpc care?

Note that NSS modules really should be careful with everything they do, they might be called in any kind of environment, with any kind of limits set. This means they should be very careful with assumptions and minimize what they allocate.

**Comment by tblume** [comment]
Maybe I was unclear, I'm not doubting that there is a problem with too much resource allocation in libtirpc. But that's a different issue.

In my understanding, getrlimit should return the limits that are set for a process, right?
If so, is there a restriction about when getrlimit can be used?
At the time when libtirpc uses getrlimit the limits are not yet set and hence a wrong value is returned (compared with /proc/$PID-OF-SYSTEMD-USER-INSTANCE/limits).

The question is, is this an invalid usage of getrlimit?
If so, why?

**Comment by tblume** [comment]
Or looking at it another way, the limits for the systemd user instance are set after a shared library tries to get them.
Is this attempt to get the limits for the systemd user instance invalid at this stage?

**Comment by vcaputo** [comment]
Before we can try determine if this is a valid usage of getrlimit we need answers to the questions: "Which rlimit is this precisely about? why would libtirpc care?"

From a distance, it's strange for a library to be playing with getrlimit unless its intended purpose is to operate on such things.

**Comment by poettering** [comment]
> In my understanding, getrlimit should return the limits that are set for a process, right?

Dunno. It should return whatever is set at that moment... NSS modules need to be prepared to be called at any time really and need to deal with that. And that means the should work fine both before we call the per-service setrlimit() (i.e. let's call this "systemd's context") and after (i.e. let's call this "the service's context"). It's not an option for NSS modules to only work in one of the context, it must be prepared to work in either of these two. 

> At the time when libtirpc uses getrlimit the limits are not yet set and hence a wrong value is returned (compared with /proc/$PID-OF-SYSTEMD-USER-INSTANCE/limits).

Why are these limits "wrong"? when we do the NSS lookups the values of "systemd's context" apply, not yet the values of "the service's context". Both are entirely valid. And I'd argue that since it's systemd's code that does the NSS query it's probably more appropriate if the rlimits the NSS module sees are the one from systemd's context.

**Comment by tblume** [comment]
> > In my understanding, getrlimit should return the limits that are set for a process, right?
> 
> Dunno. It should return whatever is set at that moment... NSS modules need to be prepared to be called at any time really and need to deal with that. And that means the should work fine both before we call the per-service setrlimit() (i.e. let's call this "systemd's context") and after (i.e. let's call this "the service's context"). It's not an option for NSS modules to only work in one of the context, it must be prepared to work in either of these two.

Yes, I fully agree with that and that needs to be fixed.
Still, it doesn't change the fact that getrlimit doesn't return the value (e.g. the service context rlimit) of the process that is later visible via /proc/$PID/limits.
And this is only because it is called before setrlimit_closest_all.
When called afterwards, it will get the service context rlimits.
The code flow could probably trigger other shared libraries that use getrlimit too.
Are they all supposed to deal with such a behaviour?

> > At the time when libtirpc uses getrlimit the limits are not yet set and hence a wrong value is returned (compared with /proc/$PID-OF-SYSTEMD-USER-INSTANCE/limits).
> 
> Why are these limits "wrong"? when we do the NSS lookups the values of "systemd's context" apply, not yet the values of "the service's context". 

I can see for all daemons started via system services that the system rlimits (from system.conf) are set.
I also can see that for all user services, except, the systemd-user instance at the time of the NSS lookups the user rlimits (from user.conf) are set.
So, why is this different for the systemd user instance?

> Both are entirely valid. And I'd argue that since it's systemd's code that does the NSS query it's probably more appropriate if the rlimits the NSS module sees are the one from systemd's context.

Hm, well if we do NSS lookups for the service context via get_supplementary_groups, I would expect that also the rlimits of the service context are used.

**Comment by tblume** [comment]
I'd like to elaborate on my point of view a bit more in order to continue the discussion.

libtirpc uses getrlimt NOFILE in order to get the maximum file descriptor that the systemd user process could open.
But the return of this call is not the NOFILE of the systemd user process, but the NOFILE of the whole system.

Now, Lennarts argument is: 
"NSS modules need to be prepared to be called at any time really and need to deal with that. And that means the should work fine both before we call the per-service setrlimit() (i.e. let's call this "systemd's context") and after (i.e. let's call this "the service's context")."

True, but is it realistic that a systemd user daemon would get called with the NOFILE rlimit of the whole system? That would mean it could create an oom itself when opening too many files.
Extending that, is it realistic that any daemon that calls NSS modules would run with NOFILE of the whole system?

As discussed before, I'm not doubting that the libtirpc code needs improvement. But changing the code to not use getrlimit will only hide the problem that the getrlimit call returns the wrong value (compared to the configured rlimit) at this point, it will not fix it.

**Comment by poettering** [comment]
> Yes, I fully agree with that and that needs to be fixed.
> Still, it doesn't change the fact that getrlimit doesn't return the value (e.g. the service context rlimit) of the process that is later visible via /proc/$PID/limits.

But why would that be a problem? I mean, the NSS call is *not* done by the service, hence it sounds more appropriate if it actually runs with systemd's own limits, no?

> And this is only because it is called before setrlimit_closest_all.
> When called afterwards, it will get the service context rlimits.
> The code flow could probably trigger other shared libraries that use getrlimit too.
> Are they all supposed to deal with such a behaviour?

Yes, the libraries PID1 links against need to be ready to work with PID1's resource limits, it's that simple. If they can't work with that, we shouldn't link against them.

And this is true for libraries systemd explicitly links against but also what it implicitly links against through NSS: any code that might end up being loaded into PID1 must be ready to deal with our rlimits.

> > > At the time when libtirpc uses getrlimit the limits are not yet set and hence a wrong value is returned (compared with /proc/$PID-OF-SYSTEMD-USER-INSTANCE/limits).
> > 
> > 
> > Why are these limits "wrong"? when we do the NSS lookups the values of "systemd's context" apply, not yet the values of "the service's context".
> 
> I can see for all daemons started via system services that the system rlimits (from system.conf) are set.
> I also can see that for all user services, except, the systemd-user instance at the time of the NSS lookups the user rlimits (from user.conf) are set.
> So, why is this different for the systemd user instance?

The systemd --user instance is a service like any other really. Key really here is that if an NSS query done from the context of the service manager it probably should have the service manager's limits, and if it's done from within a service it should have the service's own limits. And if we talk about the specific case of the system service manager launching the per-user service manager, then given that we do NSS before the exec() it should be the system service mangaer's limits that apply.

> > Both are entirely valid. And I'd argue that since it's systemd's code that does the NSS query it's probably more appropriate if the rlimits the NSS module sees are the one from systemd's context.
> 
> Hm, well if we do NSS lookups for the service context via get_supplementary_groups, I would expect that also the rlimits of the service context are used.

I'd find that quite surprising, no? I'd say what might be expected most obviously is that if an NSS lookup is done from the service manager codebase it probably should have the limits of the service manager set, and if it is done from some daemon codebase it should have thta daemon's limits set, and everything else would just be confusing?

> I'd like to elaborate on my point of view a bit more in order to continue the discussion.
> 
> libtirpc uses getrlimt NOFILE in order to get the maximum file descriptor that the systemd user process could open.
> But the return of this call is not the NOFILE of the systemd user process, but the NOFILE of the whole system.

It's more complicated: we typically raise the soft RLMIT_NOFILE to the hard limit in our own programs, but we reset it to 1024 for compat when invoking foreign code. That's because PID1 nowadays bumps the hard limit to 512K for all programs at boot (in order to practically remove artifical limits on fds), but the soft limit is special: old select() based code cannot deal with fds > 1023 hence we need to make sure that the limit is back at 1024 when invoking foreign code that might want to use select().

NSS modules *must* be able to run in any context, and that means they *must* be able to deal with a high RLIMIT_NOFILE soft limit. If they don't they are just broken. This effectively means: NSS modules (and any libraries they pull in) are not allowed to use select(). If they do anyway it's on them.

> True, but is it realistic that a systemd user daemon would get called with the NOFILE rlimit of the whole system? That would mean it could create an oom itself when opening too many files.

Not sure I follow.

All our programs that possibly need more than a handful of fds are supposed to call rlimit_nofile_bump(), which wraps the logic of bumping the soft to the hard limit.

> Extending that, is it realistic that any daemon that calls NSS modules would run with NOFILE of the whole system?

I am not sure what you mean by "NOFILE of the whole system". But yes, they *must* be able to deal with a high RLIMIT_NOFILE soft limit. They are broken if they can#t do that. They are broken if they still use select()

> As discussed before, I'm not doubting that the libtirpc code needs improvement. But changing the code to not use getrlimit will only hide the problem that the getrlimit call returns the wrong value (compared to the configured rlimit) at this point, it will not fix it.

It's not the wrong value. And we don't work around borked NSS modules like this, sorry. NSS modules authors have to accept the fact they write code that is linked into arbitrary programs with arbitrary limits enforced. They need to be exceptionally carefuly what they do and be prepared for anything. If they use select() then they are not up to the task sorry.

Sorry, but I am very sure this should not be changed. I mean, even if we'd change this around here, and lower the RLIMIT_NOFILE soft limit to 1024 right before invoking the NSS module, for compat with crappy NSS modules which use select(), this then would make that NSS module work with systemd, but it would still break with *any* other program doing NSS while rasing RLIMIT_NOFILE. So what is won through this? it just shifts around the blame, and you cannot possibly add work-arounds to all NSS users like this. You have to fix the actual culprit, the NSS module instead, so that it starts working with everything.

I hope that makes some sense, let's close this here hence.

**Comment by poettering** [comment]
Or to say this differently, think of this service:

```
[Service]
LimitNOFILE=16000:16000
ExecStart=/usr/bin/getent passwd wuffwuff
```

This service runs with elevated RLIMIT_NOFILE soft+hard limit, both set to 16000, i.e. above 1024. The service command does an NSS lookup, and that's pretty much it. If you don#t fix that libtirpcs NSS module, then this service would fail, regardless if we add your work-around or not... Hence what is won? if, otoh you fix the NSS module, then suddently everything works for everyone, just like that: in the service above the same as the original problem you ran into...

**Pull request closed without merging**
