### PR TITLE
test: rename TEST-EXECRELOAD to avoid name conflict

### PR DESCRIPTION
**Pull request by mrc0mmand**
As discussed in https://github.com/systemd/systemd/pull/13369#issuecomment-532132299, let's rename the TEST-37-EXECRELOAD to TEST-39-EXECRELOAD to avoid conflict with the already existing TEST-37-RUNTIMEDIRECTORYPRESERVE.

Following changes in other PRs should be also pursued to avoid possible future conflicts:
 - PR #13369 - rename TEST-37-EXEC-COMMAND-EX to TEST-40-EXEC-COMMAND-EX
 - PR #13512 - rename TEST-37-FREEZER to TEST-38-FREEZER

cc  @anitazha (ExecXYZEx PR), @msekletar (freezer PR), @keszybz

### CODE REVIEW

**Comment by mrc0mmand** [comment]
The EXECRELOAD test failed on aarch64 probably because of this:

```
...
execreloadRTJ.service: Trying to enqueue job execreloadRTJ.service/stop/replace
Added job execreloadRTJ.service/stop to transaction.
execreloadRTJ.service: Installed new job execreloadRTJ.service/stop as 195
execreloadRTJ.service: Enqueued job execreloadRTJ.service/stop as 195
execreloadRTJ.service: Changed running -> stop-sigterm
Received SIGCHLD from PID 73 (sleep).
Child 73 (sleep) died (code=killed, status=15/TERM)
execreloadRTJ.service: Failed to read oom_kill field of memory.events cgroup attribute: No such file or directory
execreloadRTJ.service: Child 73 belongs to execreloadRTJ.service.
execreloadRTJ.service: Main process exited, code=killed, status=15/TERM
execreloadRTJ.service: Succeeded.
execreloadRTJ.service: Changed stop-sigterm -> dead
execreloadRTJ.service: Job 195 execreloadRTJ.service/stop finished, result=done
execreloadRTJ.service: Collecting.
Configuration file /etc/systemd/system/execreloadRTJ.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
execreloadRTJ.service: Collecting.
Configuration file /etc/systemd/system/execreloadRTJ.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
execreloadRTJ.service: Collecting.
execreloadRTJ.service: Failed to send unit change signal for execreloadRTJ.service: Connection reset by peer
Received SIGCHLD from PID 28 (bash).
Child 28 (bash) died (code=exited, status=1/FAILURE)
testsuite.service: Failed to read oom_kill field of memory.events cgroup attribute: No such file or directory
testsuite.service: Child 28 belongs to testsuite.service.
testsuite.service: Main process exited, code=exited, status=1/FAILURE
testsuite.service: Failed with result 'exit-code'.
testsuite.service: Changed start -> failed
```

I'm not sure if the `Failed to send unit change signal for execreloadRTJ.service: Connection reset by peer` message has to do anything with why the `bash` process suddenly received a non-zero exit code (most likely from `systemctl stop`), but it's the only explanation I was able to read out from the logs, which are somewhat confusing due to missing pieces.

@keszybz isn't this related to this https://github.com/systemd/systemd/pull/13369#issuecomment-532139280?

**Comment by keszybz** [comment]
`Failed to send unit change signal for execreloadRTJ.service: Connection reset by peer` normally means that `systemctl` (or something else), which started the job terminated before the signal was sent. So I don't think that's directly related.

In #13369 the code was status=2.

**Comment by mrc0mmand** [comment]
Hm, I see, thanks. I'll try to create a local aarch64 VM to debug this further then.

**Comment by mrc0mmand** [comment]
Well, I tried a QEMU aarch64 VM and also a real aarch64 hardware, and after a couple of hundreds iteration I couldn't reproduce the issue. Let's hope it was indeed a fluke, at least until we get more information about it.

**Pull request merged**
