### PR TITLE
test: use `useradd` instead of `adduser`

### PR DESCRIPTION
**Pull request by mrc0mmand**
`adduser` is in certain cases a standalone package which provides a
better user experience. In other cases it's just a symlink to `useradd`.
And some distributions don't have `adduser` at all, like Arch Linux.
Let's use the `useradd` binary instead, which should provide the same
functionality everywhere.

---

Related PR: https://github.com/systemd/systemd-centos-ci/pull/155

### CODE REVIEW

**Comment by keszybz** [comment]
Indeed.

**Comment by evverx** [comment]
```
autopkgtest [12:56:12]: test networkd-test.py: -----------------------]^M
autopkgtest [12:56:12]: test networkd-test.py:  - - - - - - - - - - results - - - - - - - - - -^M
networkd-test.py     FAIL stderr: useradd: user 'systemd-network' already exists^M
autopkgtest [12:56:13]: test networkd-test.py:  - - - - - - - - - - stderr - - - - - - - - - -^M
useradd: user 'systemd-network' already exists^M
```

**Comment by evverx** [comment]
To judge from https://salsa.debian.org/systemd-team/systemd/blob/master/debian/tests/control#L41 the test isn't supposed to print anything to `stderr`.

**Comment by keszybz** [comment]
Hmm, the semaphore build seems to die halfway. I'll restart it.

**Comment by mrc0mmand** [comment]
Thanks. I added a check for the `systemd-network` user existence before calling `useradd` which should, hopefully, fix the issue (and feels nicer than suppressing the `useradd`'s stderr).

**Comment by evverx** [comment]
> I added a check for the systemd-network user existence before calling useradd which should, hopefully, fix the issue (and feels nicer than suppressing the useradd's stderr).

Agreed. The test no longer fails on Semaphore so that particular issue seems to be gone.

But it apparently still sends standard error to `/dev/null` as mentioned at the end of https://github.com/systemd/systemd/pull/13223#issuecomment-516355757.

**Comment by mrc0mmand** [comment]
> But it apparently still sends standard error to `/dev/null` as mentioned at the end of [#13223 (comment)](https://github.com/systemd/systemd/pull/13223#issuecomment-516355757).

Good point. I'll look into that as well.

**Comment by evverx** [comment]
Just to clarify, that has nothing to do with this PR. I'm just trying to figure out why it took almost a day to discover the "Uh? Unexpected data type." message.

**Comment by evverx** [comment]
According to https://docs.python.org/3/library/subprocess.html#subprocess.check_output
> To also capture standard error in the result, use stderr=subprocess.STDOUT

I'm not sure whether it's OK to mix stdout and stderr there though

**Comment by mrc0mmand** [comment]
> According to https://docs.python.org/3/library/subprocess.html#subprocess.check_output
> 
> > To also capture standard error in the result, use stderr=subprocess.STDOUT
> 
> I'm not sure whether it's OK to mix stdout and stderr there though

Indeed. This is just a part of my *throw everything at it and see what sticks* debugging attempt, as I can't reproduce the issue anywhere locally and using `--no-pager` didn't help as well. In the end I'd like to stick with `subprocess.call()` (hopefully).

**Comment by mrc0mmand** [comment]
@evverx interestingly enough, in this particular case (i.e. SIGABRT), `networkctl status` simply has no output at all. I added a simple *error* message to stdout (as stderr is collected into a separate file, thus not shown under the `--- networkctl status xxx ---` log message), so now it should at least tell you that something is wrong, instead of returning nothing. The usefulness of this message is questionable, as a proper back/stack-trace would be much better :-)

**Comment by mrc0mmand** [comment]
```
---- interface status ----
16: test_eth42@router_eth42: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether de:ad:be:ef:47:11 brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.129/24 brd 192.168.5.255 scope global dynamic test_eth42
       valid_lft 3590sec preferred_lft 3590sec
    inet6 fe80::dcad:beff:feef:4711/64 scope link 
       valid_lft forever preferred_lft forever
---- networkctl status test_eth42 ----
'networkctl status' exited with unexpected code -6
---- systemd-networkd.service ----
```

Apart from the missing article it looks like it might get the *job* done.

**Comment by evverx** [comment]
> The usefulness of this message is questionable, as a proper back/stack-trace would be much better :-)

I think by analogy with the test where we run `networkd` and then look for ASan reports, we could search for backtraces `systemd-coredump` accumulates. I'm not sure whether it's set up properly on Ubuntu though.

**Comment by mrc0mmand** [comment]
> I think by analogy with the test where we run `networkd` and then look for ASan reports, we could search for backtraces `systemd-coredump` accumulates. I'm not sure whether it's set up properly on Ubuntu though.

That would be indeed great. However, I'd merge this PR in its current state, so I can continue with https://github.com/systemd/systemd-centos-ci/pull/155 and play with the coredump stuff in a new PR.

Regarding the `systemd-coredump` and Ubuntu CI debugging - @ddstreet is it possible to access the incomplete CI logs in some way? The landing page shows just a few lines and in certain cases (like this PR), the test you're trying to debug is somewhere around the middle of the *test suite*, but you still have to wait until everything finishes to get the full logs.

**Comment by ddstreet** [comment]
> is it possible to access the incomplete CI logs in some way? 

Unfortunately not AFAIK, currently, although this has frustrated me also.  It's one of the things I would like to improve (or see improved) in the autopkgtest-cloud code, where the Ubuntu ci runs.

**Pull request merged**
