### PR TITLE
test: fix a memleak

### LINKED ISSUE #9968: test-install-root seems to be failing under ASan
Since https://github.com/systemd/systemd/pull/9901 was merged, `test-install-root` has been failing under ASan with
```
=================================================================
==12695==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7f479dccfc40 in realloc (/lib64/libasan.so.4+0xdec40)
    #1 0x7f479ce2a5bd in unit_file_changes_add ../src/shared/install.c:298
    #2 0x7f479ce2d0b5 in create_symlink ../src/shared/install.c:457
    #3 0x7f479ce396e7 in install_info_symlink_wants ../src/shared/install.c:1795
    #4 0x7f479ce39f6c in install_info_apply ../src/shared/install.c:1851
    #5 0x7f479ce3a4ef in install_context_apply ../src/shared/install.c:1919
    #6 0x7f479ce45c49 in execute_preset ../src/shared/install.c:3054
    #7 0x7f479ce47530 in unit_file_preset_all ../src/shared/install.c:3216
    #8 0x55dde9ea46ad in test_preset_multiple_instances ../src/test/test-install-root.c:1032
    #9 0x55dde9ea659a in main ../src/test/test-install-root.c:1071
    #10 0x7f479b7eaf29 in __libc_start_main (/lib64/libc.so.6+0x20f29)

Indirect leak of 231 byte(s) in 3 object(s) allocated from:
    #0 0x7f479dc68238 in __interceptor_strdup (/lib64/libasan.so.4+0x77238)
    #1 0x7f479ce2a65e in unit_file_changes_add ../src/shared/install.c:303
    #2 0x7f479ce2d0b5 in create_symlink ../src/shared/install.c:457
    #3 0x7f479ce396e7 in install_info_symlink_wants ../src/shared/install.c:1795
    #4 0x7f479ce39f6c in install_info_apply ../src/shared/install.c:1851
    #5 0x7f479ce3a4ef in install_context_apply ../src/shared/install.c:1919
    #6 0x7f479ce45c49 in execute_preset ../src/shared/install.c:3054
    #7 0x7f479ce47530 in unit_file_preset_all ../src/shared/install.c:3216
    #8 0x55dde9ea46ad in test_preset_multiple_instances ../src/test/test-install-root.c:1032
    #9 0x55dde9ea659a in main ../src/test/test-install-root.c:1071
    #10 0x7f479b7eaf29 in __libc_start_main (/lib64/libc.so.6+0x20f29)

Indirect leak of 154 byte(s) in 2 object(s) allocated from:
    #0 0x7f479dc68238 in __interceptor_strdup (/lib64/libasan.so.4+0x77238)
    #1 0x7f479ce2a65e in unit_file_changes_add ../src/shared/install.c:303
    #2 0x7f479ce2e5d6 in remove_marked_symlinks_fd ../src/shared/install.c:631
    #3 0x7f479ce2dfaa in remove_marked_symlinks_fd ../src/shared/install.c:583
    #4 0x7f479ce2ed57 in remove_marked_symlinks ../src/shared/install.c:679
    #5 0x7f479ce45a13 in execute_preset ../src/shared/install.c:3046
    #6 0x7f479ce47530 in unit_file_preset_all ../src/shared/install.c:3216
    #7 0x55dde9ea46ad in test_preset_multiple_instances ../src/test/test-install-root.c:1032
    #8 0x55dde9ea659a in main ../src/test/test-install-root.c:1071
    #9 0x7f479b7eaf29 in __libc_start_main (/lib64/libc.so.6+0x20f29)

Indirect leak of 111 byte(s) in 3 object(s) allocated from:
    #0 0x7f479dc68238 in __interceptor_strdup (/lib64/libasan.so.4+0x77238)
    #1 0x7f479ce2a6b5 in unit_file_changes_add ../src/shared/install.c:305
    #2 0x7f479ce2d0b5 in create_symlink ../src/shared/install.c:457
    #3 0x7f479ce396e7 in install_info_symlink_wants ../src/shared/install.c:1795
    #4 0x7f479ce39f6c in install_info_apply ../src/shared/install.c:1851
    #5 0x7f479ce3a4ef in install_context_apply ../src/shared/install.c:1919
    #6 0x7f479ce45c49 in execute_preset ../src/shared/install.c:3054
    #7 0x7f479ce47530 in unit_file_preset_all ../src/shared/install.c:3216
    #8 0x55dde9ea46ad in test_preset_multiple_instances ../src/test/test-install-root.c:1032
    #9 0x55dde9ea659a in main ../src/test/test-install-root.c:1071
    #10 0x7f479b7eaf29 in __libc_start_main (/lib64/libc.so.6+0x20f29)

SUMMARY: AddressSanitizer: 616 byte(s) leaked in 9 allocation(s).
-------
```
@peterbaouoft could you take a look?

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for #9901.

Fixes #9968.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx and @peterbaouoft.

**Comment by yuwata** [comment]
@evverx I just checked this with valgrind. Not tested with ASan.

**Comment by peterbaouoft** [comment]
@yuwata thanks a lot, I was going to submit the same change :D.

**Comment by yuwata** [comment]
@evverx Thanks.
@peterbaouoft I am sorry for interrupting your work...

**Comment by peterbaouoft** [comment]
> I am sorry for interrupting your work

no, no worries at all :).

**Comment by keszybz** [comment]
`boot-and-services    FAIL stderr: Failed to dump process list for 'systemd-nspawn@c1.service', ignoring: Unit systemd-nspawn@c1.service not loaded.` — looks unrelated.

**Pull request merged**
