### PR TITLE
basic: fix system-wide IPv6 detection

### PR DESCRIPTION
**Pull request by dm0-**
This is an update to #2713.

### CODE REVIEW

**Comment by ssahani** [comment]
git diff

```
diff --git a/src/basic/socket-util.c b/src/basic/socket-util.c
index 5c829e0..9a247c8 100644
--- a/src/basic/socket-util.c
+++ b/src/basic/socket-util.c
@@ -441,7 +441,14 @@ const char* socket_address_get_path(const SocketAddress *a) {
 }

 bool socket_ipv6_is_supported(void) {
-        if (access("/proc/net/if_inet6", F_OK) != 0)
+        _cleanup_free_ char *line = NULL;
+        int r;
+
+        r = read_one_line_file("/proc/net/if_inet6", &line);
+        if (r < 0)
+                return false;
+
+        if (isempty(line))
                 return false;

         return true;
```

**Comment by ssahani** [comment]
yes please modify the patch. Apparently I disabled from kernel command line that triggered to disable whole stack.

**Comment by keszybz** [comment]
Looking at the contents of /proc/net/if_inet6, it seems to list addresses on various interfaces. Is there a time during early boot where this function could be called before lo is up, and falsely return a negative result?

Also needs some comment in that function so that we don't forget why it's like that in the future.
/\* If IPv6 is disabled on the kernel command line with ipv6.disable=1, /proc/net/if_inet6
- is not present at all. If IPv6 is disabled with net.ipv6.conf.all.disable_ipv6=1 sysctl, this
- file exists, but is empty.
  */

Also, if the file is missing, i.e. if ipv6 is disabled permanently, we should cache the result.

**Comment by dm0-** [comment]
@keszybz  From a quick glance, it appears that the `proc` file is registered before the handlers that would include the loopback device during module initialization, so it may be possible to be empty briefly.  See the ordering of these two lines: https://github.com/torvalds/linux/blob/master/net/ipv6/af_inet6.c#L937-L949 .

And with this in mind, if a system has built `ipv6` as a kernel module, that `proc` file may not exist during the first check and appear later when the module is loaded, so is it safe to cache that the file is missing?  (I think it is safe to assume that the `proc` file will not disappear, though; since unloading the `ipv6` module is not supported.)

**Comment by dm0-** [comment]
It looks like the sysctl path is registered in `addrconf_init` during module initialization, so checking for the existence of `/proc/sys/net/ipv6/conf/all/disable_ipv6` would determine if the `ipv6` kernel module is loaded, and verifying its contents starts with `0` would determine if IPv6 is globally enabled.

Would that be a more reliable file to check?  Is there any other way to globally disable IPv6 that needs to be considered, besides sysctl and lacking the kernel module?  Note this requires `CONFIG_SYSCTL` is enabled in the kernel config, but other parts of systemd seem to use this proc/sysctl interface unconditionally, so I'm assuming it isn't a problem.

Edit: Also note that the `all` or `default` interface sysctl value won't quite work for the case where `all` is disabled, and then an interface is re-enabled individually, if that is a scenario that should be covered by the `socket_ipv6_is_supported` function.

**Comment by ssahani** [comment]
/\* If IPv6 is disabled on the kernel command line with ipv6.disable=1, /proc/net/if_inet6
    is not present at all. If IPv6 is disabled with net.ipv6.conf.all.disable_ipv6=1 sysctl, this
    file exists, but is empty. */

if disabled from command line `/proc/net/if_inet6`  or `/proc/sys/net/ipv6/conf/all/disable_ipv6`
is not available at all.

If enabled from command line /proc/net/if_inet6 is available but again does not contain anything if
`/proc/sys/net/ipv6/conf/all/disable_ipv6` is 1 else we do have IPv6 addresss.

tested it 

```
$ cat /proc/sys/net/ipv6/conf/all/disable_ipv6
cat: /proc/sys/net/ipv6/conf/all/disable_ipv6: No such file or directory



 cat /boot/grub/
fonts/            grub.cfg          grub.cfg~         grub.cfg.example  grubenv           i386-pc/          locale/           themes/           
[root@Arch ~]# cat /boot/grub/grub.cfg | grep ipv6
    linux   /boot/vmlinuz-linux root=UUID=336db6ec-ab83-4257-ba6d-d3b7a6f6b1d6 rw  ipv6.disable=1
```

Also no IPv6 addresses including LL.

Enabling from command line and disabling from systctl

file exists but contains nothing.

```
  cat /proc/sys/net/ipv6/conf/all/disable_ipv6
1

# cat /proc/net/if_inet6

```

tested with the code.

**Comment by dm0-** [comment]
@ssahani Thanks for looking into that.  I've done some testing and pushed what I think results in the most desirable behavior.

This PR now looks at the individual interfaces' `sysctl` values for `disable_ipv6` in `link_ipv6_enabled`, and it uses this link-specific check throughout `networkd-link.c` instead of the global check.  This supports cases where `...all.disable_ipv6=1` but then an interface is enabled directly with e.g. `...ens3.disable_ipv6=0`.  The global check function continues to use `if_inet6`, since it is only one place to look as opposed to each interface's `sysctl` value.

Edit:  Forgot to mention I saw something like this from your #4216, but that PR was closed with no comments.  Is there a problem with this approach?

**Comment by ssahani** [comment]
I think there is no need to look at individual interface as we dynamically enable per interface IPv6 if we have configured that interface with IPv6 `link_enable_ipv6`.

```
  /* DHCPv6 client will not be started if no IPv6 link-local address is configured. */                                                                                             
        return link_ipv6ll_enabled(link) || network_has_static_ipv6_addresses(link->network); 
```

So the first commit is good enough.

**Comment by dm0-** [comment]
From my testing without the second commit, running e.g. `sysctl net.ipv6.conf.ens3.disable_ipv6=1` to disable IPv6 on an interface will still cause `systemd-networkd-wait-online` to timeout and the interface to never get out of the `configuring` state.

**Comment by ssahani** [comment]
```
#   cat /proc/sys/net/ipv6/conf/enp0s3/disable_ipv6 
1
 #   cat /proc/sys/net/ipv6/conf/all/disable_ipv6
1
 # /lib/systemd/systemd-networkd-wait-online 
ignoring: lo
# networkctl 
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 enp0s3           ether              routable    configured
  3 enp0s8           ether              routable    configured
  4 enp0s9           ether              routable    configured
  5 enp0s10          ether              off         unmanaged 

5 links listed.
#   cat /proc/sys/net/ipv6/conf/enp0s8/disable_ipv6 
1
#   cat /proc/sys/net/ipv6/conf/enp0s9/disable_ipv6 
1
```

works for me

**Comment by dm0-** [comment]
I meant cases where IPv6 is still enabled for `all`, but disabled for an individual interface.  (Sorry, I think I wrote it backwards two comments ago.)  The following commands will break without the second commit.

```
localhost ~ # echo 1 > /proc/sys/net/ipv6/conf/ens3/disable_ipv6 
localhost ~ # systemctl restart systemd-networkd
localhost ~ # cat /proc/sys/net/ipv6/conf/all/disable_ipv6 
0
localhost ~ # cat /proc/sys/net/ipv6/conf/ens3/disable_ipv6
1
localhost ~ # networkctl 
IDX LINK             TYPE               OPERATIONAL SETUP
  1 lo               loopback           carrier     configured
  2 ens3             ether              routable    configuring

2 links listed.
localhost ~ # /usr/lib/systemd/systemd-networkd-wait-online
ignoring: lo
Event loop failed: Connection timed out
```

**Comment by ssahani** [comment]
aah yes I can reproduce this. I think the we need to look at the sysctl variables too .  
Could you please test with https://github.com/systemd/systemd/commit/342579b17118ac89e06339bbde3150a806eadf76 .

```
# cat  /proc/sys/net/ipv6/conf/all/disable_ipv6 
0
# cat  /proc/sys/net/ipv6/conf/enp0s3/disable_ipv6 
1
# cat  /proc/sys/net/ipv6/conf/enp0s8/disable_ipv6 
1
# networkctl 
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 enp0s3           ether              routable    configured
  3 enp0s8           ether              routable    configured
```

**Comment by poettering** [comment]
Hmm, not sure I follow, but the per-interface "disable_ipv6" flag file in /proc/sys/net is actually _managed_ by networkd, and set to on or off, depending on the IPv6 configuration in .network files. It sounds wrong for a global IPv6 check to ever be based on dynamic configuration we ourselves apply depending on temporal states...

What's the precise issue you are trying to fix here?

**Comment by dm0-** [comment]
@ssahani That commit seems to work as well.  I can cherry-pick it into this pull request, unless you've taken care of it already.

@poettering The real issue I wanted to address is #2713.  We have users that disabled IPv6 via a sysctl drop-in for `all` interfaces, which was causing the timeout and service failures, so that case was the priority here.  However, during my testing of it, I found the same timeout was trivially reproducible by setting the interface-specific sysctl flag as well.  It seemed like a good idea to correct the issue in this case, too, but as far as I know no one has actually hit this specific problem yet.

**Comment by ssahani** [comment]
@dm0- Ok

**Comment by poettering** [comment]
I am sorry, but this PR looks very wrong to me. It should be networkd that configures IPv6 for an interface, not one that reads the setting back. If you want to disable Ipv6, then disable Ipv6 in the .network files and all should be good.

**Pull request closed without merging**
