### PR TITLE
test: use DECIMAL_STR_FMT() macro

### PR DESCRIPTION
**Pull request by Integral-Tech**

### CODE REVIEW

**Review by yuwata — COMMENTED** [review]
Sorry, the macro is for printing integers in macros, see shared/test.h . Closing.

**Comment by Integral-Tech** [comment]
@yuwata But IMO, since we have defined this macro, it can also be used in `xprintf` function arguments.

**Comment by yuwata** [comment]
It _can_ be used, but not necessary. That's super redundant in general and complicated. All we are familiar with traditional `%u` or friends. Even if we made some mistake, all changes here are for test, so that should not be a big matter.

Or, do you have any explicit pros over the traditional `%` specifiers?

**Comment by Integral-Tech** [comment]
@yuwata Okay, I see

**Pull request closed without merging**
