### PR TITLE
network: use VRF's route table if VRF= is set

### LINKED ISSUE #14940: networkd: manually specified Gateway added to main route table instead of VRF's
Seen on systemd v244.3 on debian testing:

When an interface is configured for VRF, any manually added gateways are added to the main routing table, instead of VRF's routing table. This otherwise works fine when using DHCP for example.

```
[Network]
VRF=test
Address=192.168.2.2/24
Gateway=192.168.2.1
```
```
# ip route show vrf test
192.168.2.0/24 dev eth0 proto kernel scope link src 192.168.2.2
192.168.3.0/24 dev eth1 proto kernel scope link src 192.168.3.1
```
```
# ip route show
default via 192.168.2.1 dev eth0 proto static
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #14940.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @ssahani.

**Comment by ssahani** [comment]
CI is failing because of the the new test case..

**Comment by yuwata** [comment]
Ouch. Will fix it.

**Comment by yuwata** [comment]
Fixed.

**Comment by ssahani** [comment]
LGTM

**Pull request merged**
