### PR TITLE
barrier: replace IN_SET with ||

### PR DESCRIPTION
**Pull request by evverx**
Fixes https://github.com/systemd/systemd/issues/10332.

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, but if this is just a bug in ubsan, then why work around? This sounds like something to better get fixed in ubsan?

**Comment by evverx** [comment]
As far as I can tell, the bug has already been fixed (at least I can't reproduce it with a more or less recent version of `clang`). But I'm not sure how long it will take for the fix to make it to `gcc` and `libubsan` or how likely it is people will upgrade the toolchain they're using after it gets patched.

Plus, this kludge is no different conceptually from, for example, 2e69f4114c4a71a874 (which gets around another issue that should be fixed elsewhere), so I thought it wouldn't hurt to change the code a little bit more :-)

**Comment by keszybz** [comment]
Hmm, 2e69f41 was nice and self-contained. This one is pretty ugly. If the bug only affected a recent version of ubsan and has since been fixed in a point release, I'd prefer not to patch systemd for this.

**Comment by evverx** [comment]
I don't think it's ugly. I'd also say that `||` is easier to understand than `IN_SET` in the sense that `IN_SET` isn't the most trivial macro I've ever seen. I agree that it's inconsistent with the rest of the code, but if you took a look at the history of `barrier.h` you would see that nobody really reads or changes this code (apart from cosmetic changes and changes made automatically).

Regarding the fix, it's hard to tell whether it has been fixed in `gcc` or not (all I can say is that isn't reproducible in a recent version of clang) and I don't think that spending a couple of hours trying to figure out where the bug was introduced and fixed is worth the hassle. It seems reasonable to me to just change the code that is almost never touched to save a lot of time that can be spent elsewhere.

**Comment by evverx** [comment]
Plus, I didn't really add anything new. I just partly reverted https://github.com/systemd/systemd/commit/3742095b27f8df4b195d530b52d15bc5fea70bf1#diff-b0133acc8886f812d5f42c67527ee180 (which was made entirely automatically, by the way).

**Comment by poettering** [comment]
Well, we are interested in legibility, and I do think IN_SET() helps with that in particular if we have many values to compare against, i.e. while the benefit with two items is not that big, starting with three it *really* makes a difference.

It also has the benefit that it automatically detects and refuses duplicate switch items.

 (Moreover there's a good chance it produces better code since it explicitly drops the requirement for the compiler to compare left-to-right, but a good optimizer might figure this out too, and this doesn't matter too much anyway)

So, yes, IN_SET is a *good* thing, and we should prefer using it in almost all cases.

**Comment by evverx** [comment]
OK, I see where this is going :-) I'm totally fine with not merging the PR. After all, I have my ways to silence `ubsan` :-)

**Pull request closed without merging**
