### PR TITLE
Fix unexpected unmounts after fstab changes w/o daemon-reload

### PR DESCRIPTION
**Pull request by msekletar**

### CODE REVIEW

**Comment by msekletar** [comment]
Hi @poettering,

This is my attempt to finally fix #9869 because that bug never got fully resolved. We've never stopped adding BindsTo to underlying device units (actually we continued to do so in most cases). At first I thought we should just get rid of BindsTo but eventually I reconsidered and instead came up with following fixes.

I am still testing this so keeping in Draft state for now. But PTAL anyway to get the idea.

**Comment by msekletar** [comment]
CI failure seems unrelated (networkd test case failed).

**Comment by poettering** [comment]
Hmm, so the code actually looks pretty clean for what it does ;-) But I am not a fan, I must admit. The thing is: we want our configured dep tree to remain unaffected by runtime changes. That's why we track from which sources deps originate, so that we can remove them again to revert to the status quo ante when we need to.

The thing is that people can configure deps from various sources on any of the involved units. They can do .mount.d/ or .device.d/ drop-ins or fstab options and they can use any of the .device units name for that. Once we migrated any of those over to another .device then we need a way to migrate it back eventually, but tracking htat would be hard, because when migrating deps originating from many "following" units might end up on one device, and we don't know where they are from...

As I understand the problem this i supposed to fix this is more a problem of that BindsTo= is simply to struct for the usecase, and I think we should probably address that instead. Two ideas:

1. Add a new dep type. There are two options for this:
  a. A new weaker version of BindsTo=, that operates "edge-triggered" instead of "level-triggered" on stop. i.e. it will try to shut down deps once when a unit goes from active to inactive, but never checks things otherwise.
  b. A more specific dep type PropagatesStopFrom=/PropagatesStopTo=, that is a lot like PropagatesReloadFrom=/…To= but only operates on stop. i.e. this would focus only and exclusively on the stop event, and nothing else. We'd then bind the .mount units to the .device units via a regular Requires= in combination with PropagatesStopFrom= and this would fix the original, issue, no?
2. Maybe start tracking for each unit whether a unit appeared as effect what *we* did, or is caused by something else. Then, for mount units, if it was established due to something else simply never enforce BindsTo=.

I think 1b is kinda the nicest of these ideas. @keszybz @msekletar ideas?

I think the 1b idea should be pretty simple to implement, we have a good template in PropagatesReloadFrom=/To=

**Comment by poettering** [comment]
I implemented what I proposed in #19322 now. Let's continue dicussion there. I hope it's OK if I close this now.

**Pull request closed without merging**
