### PR TITLE
networkd: vxlan rename ARPProxy to ReduceARPProxy

### PR DESCRIPTION
**Pull request by ssahani**
Fixes: #4768

### CODE REVIEW

**Comment by tixxdz** [comment]
@ssahani apart from the patch, what about backward compatibility here ?

Thank you!

**Comment by keszybz** [comment]
I don't think the new name is good at all. With "ARPProxy" or "ProxyARP" one has a general idea what this is about. With "ARPReduction", not so much.

**Comment by ssahani** [comment]
@keszybz I picked up the name from http://lists.openwall.net/netdev/2012/11/15/97 and https://goo.gl/i5c5a4 .  "ARPProxy" is all reduce the ARP.

@tixxdz  Yes right. I will fix it.

**Comment by poettering** [comment]
If "reduction" is the technical term being used it sounds fine to name it like this. Another idea would be "ARPReductionProxy=" or "ARPReduceProxy=" or "ReduceARPProxy="... I slightly prefer the latter...

I also think we should rename the other arp proxy option to IPv4ProxyARP= in order to clarify its relationship to IPv4, and map to the various IPv6 options we have. 

And in both cases there should be some compat left, even though we should only document and advertise the new option names.

**Comment by ssahani** [comment]
yes I think that makes sense to update too .

**Comment by poettering** [comment]
lgtm

**Pull request merged**
