### PR TITLE
man: PIDFile is respected only when Type=forking

### PR DESCRIPTION
**Pull request by johnlinp**

### CODE REVIEW

**Comment by arvidjaar** [comment]
I do not see any restrictions in code regarding `PIDFile`; it is used unconditionally if it is set in unit definition. Why do you think it is not used in other cases?

**Comment by johnlinp** [comment]
@arvidjaar I saw this item in the TODO file:

```
- allow Type=simple with PIDFile=
  https://bugzilla.redhat.com/show_bug.cgi?id=723942
```

So I guess `Type=simple` does not respect `PIDFile=`. Other `Type=` of services are described as "is similar to simple" except `Type=forking`. So I think `PIDFile=` is only respected when `Type=forking`.

Or, is there any other `Type=` respect `PIDFile=`?

**Comment by arvidjaar** [comment]
> is there any other Type= respect `PIDFile=`?

```bor@bor-Latitude-E5450:~$ systemctl --user start pid.service
bor@bor-Latitude-E5450:~$ systemctl --user status pid.service -l
● pid.service - test PIDFile
   Loaded: loaded (/run/user/1001/systemd/user/pid.service; static; vendor preset: enabled)
   Active: active (running) since Вт 2018-01-09 07:32:16 MSK; 3s ago
 Main PID: 10461 (sleep)
   CGroup: /user.slice/user-1001.slice/user@1001.service/pid.service
           └─10461 sleep 10000000

янв 09 07:32:16 bor-Latitude-E5450 systemd[1499]: Started test PIDFile.
bor@bor-Latitude-E5450:~$ cat /run/user/1001/systemd/user/pid.service
[Unit]
Description=test PIDFile

[Service]
Type=simple
PIDFile=/tmp/pid.pid
ExecStart=/bin/sh -c 'sleep 10000000 & echo $! > /tmp/pid.pid'
```
systemd 229.

**Comment by johnlinp** [comment]
@arvidjaar Thank you. Sorry for submitting this false pull request.

**Pull request closed without merging**
