### PR TITLE
network: tc: fix n_prio bounds check

### PR DESCRIPTION
**Pull request by vcaputo**
Looks like a simple copy and paste error

Fixes https://github.com/systemd/systemd/issues/16367

### CODE REVIEW

**Comment by vcaputo** [comment]
Untested quick fix on this slow quiet evening...

**Comment by evverx** [comment]
Thank you! Could you add https://oss-fuzz.com/download?testcase_id=6247961001197568 to https://github.com/systemd/systemd/tree/master/test/fuzz/fuzz-network-parser and name it oss-fuzz-23895 so that the CI could make sure that the issue is gone and won't be reintroduced anytime soon?

**Comment by vcaputo** [comment]
Ok, added the testcase as requested

**Comment by yuwata** [comment]
Thanks.

**Comment by evverx** [comment]
I've just realized that since the bug was found with honggfuzz the testcase probably wasn't minimized at all due to https://github.com/google/oss-fuzz/issues/3886 so it seems we might end up keeping 2.4Kbytes in the repository instead of what I assume could be a 100-byte file. If it isn't desirable I can manually minimize it later today.

**Comment by keszybz** [comment]
LGTM.

**Pull request merged**
