### PR TITLE
fix(hostname): Increase id of all-in-one machine,mapped to 'desktop'.

### PR DESCRIPTION
**Pull request by KT-lcz**
The chassis type of all-in-one is 0xD,we can get all-in-one'chassis by hostname1's Chassis.

### CODE REVIEW

**Comment by keszybz** [comment]
Hmm, what does "all-in-one" even mean? I think it should be mapped to the one of the other types instead of creating a new (very vague) category.

**Comment by poettering** [comment]
yeah, what#s an "all-in-one"?

The list of types we recognize is redacted a bit in our handling, since so many entries made no sense to us. "all-in-one" was one of them. Can you elaborate on what you think an "all-in-one" machine is?

**Comment by KT-lcz** [comment]
> Hmm, what does "all-in-one" even mean? I think it should be mapped to the one of the other types instead of creating a new (very vague) category.

All-in-one means,a computer with a built-in monitor but no built-in battery and requires an external power source, just like iMac.
Desktop、laptop and tablet can not represent this type of computer.

**Comment by KT-lcz** [comment]
> yeah, what#s an "all-in-one"?
> 
> The list of types we recognize is redacted a bit in our handling, since so many entries made no sense to us. "all-in-one" was one of them. Can you elaborate on what you think an "all-in-one" machine is?

All-in-one means,a computer with a built-in monitor but no built-in battery and requires an external power source, just like iMac.
Desktop、laptop and tablet can not represent this type of computer.

**Comment by keszybz** [comment]
I'd translate to "desktop". The monitor is not separate, but otherwise there's little difference.

**Comment by poettering** [comment]
"all in one" for this kind of device is a pretty stupid name though I#d claim, but I guess this is not for us to fix...

I think we should add comments at the appropriate places explaining what this is supposed to be though, since neither of the systemd maintainers heard about the name for this concept before, and I have the suspicion others are in the same situation...

**Comment by keszybz** [comment]
Nah, let's just map this to desktop. I'm looking  at https://www.morele.net/kategoria/komputery-all-in-one-40/, and at least the ones you get in Central Europe are all desktopy things.

**Comment by poettering** [comment]
ok, let's treat it as desktop

**Comment by poettering** [comment]
(after all a "tower" and "mini-tower" is also the same as "desktop")

**Comment by yuwata** [comment]
I agree with that it should be mapped to 'desktop', though at least in Japan, the name `all-in-one` is familiar, e.g., https://kakaku.com/pc/desktop-pc/itemlist.aspx?pdf_Spec101=4, but this page state the type `all-in-one desktop PC`.

**Comment by KT-lcz** [comment]
> ok, let's treat it as desktop

Now,0x0D should be mapped to 'desktop'?

**Comment by yuwata** [comment]
> > ok, let's treat it as desktop
> 
> Now,0x0D should be mapped to 'desktop'?

Right. Please update the commit. Maybe, it is better to also add a comment about the value.

**Comment by poettering** [comment]
Merged in 7c5c59d4b1811fb9e63db8c8cca877ea00217963.

Thanks!

**Pull request closed without merging**
