### PR TITLE
test: Create convenience macros to declare tests

### PR DESCRIPTION
**Pull request by medhefgo**
Just something that came to mind. If we want this, I'll adjust the other tests.

### CODE REVIEW

**Review by yuwata — APPROVED** [review]
LGTM. Interesting.

**Comment by bluca** [comment]
@medhefgo coverity doesn't seem happy about these changes:

```
CID 1465901 (#1 of 1): Wrong sizeof argument (SIZEOF_MISMATCH)
suspicious_sizeof: Passing argument t + 1 of type TestFunc * and argument 8UL /* sizeof (TestFunc *) */ to function ALIGN_TO is suspicious.
  	Did you intend to use sizeof (TestFunc) instead of sizeof (TestFunc *)?
76                t = ALIGN_TO_PTR(t + 1, sizeof(TestFunc*));
77        }
```

```
  	addr_non_null: The address of an object __start_SYSTEMD_TEST_TABLE is never null.
  	notnull: At condition __start_SYSTEMD_TEST_TABLE, the value of __start_SYSTEMD_TEST_TABLE cannot be NULL.
  	dead_error_condition: The condition !__start_SYSTEMD_TEST_TABLE cannot be true.
69        if (!__start_SYSTEMD_TEST_TABLE)
  	
CID 1465902 (#1 of 1): Logically dead code (DEADCODE)
dead_error_line: Execution cannot reach this statement: return;.
70                return;
```

```
  	
CID 1465903 (#1 of 1): Array compared against 0 (NO_EFFECT)
array_null: Comparing an array to null is not useful: __start_SYSTEMD_TEST_TABLE, since the test will always evaluate as true.
  	Was __start_SYSTEMD_TEST_TABLE formerly declared as a pointer?
69        if (!__start_SYSTEMD_TEST_TABLE)
```

Are these false positives?

**Comment by medhefgo** [comment]
Well, it uses the same pattern from static-destruct.h. What does coverity say about those?

**Comment by bluca** [comment]
we dismissed them as false positives, so I'll do the same here

**Comment by bluca** [comment]
Actually not true, it's not complaining about the sizeof comparison. It's complaining about that only in this version:

```
```
CID 1465901 (#1 of 1): Wrong sizeof argument (SIZEOF_MISMATCH)
suspicious_sizeof: Passing argument t + 1 of type TestFunc * and argument 8UL /* sizeof (TestFunc *) */ to function ALIGN_TO is suspicious.
  	Did you intend to use sizeof (TestFunc) instead of sizeof (TestFunc *)?
76                t = ALIGN_TO_PTR(t + 1, sizeof(TestFunc*));
77        }
```

**Comment by medhefgo** [comment]
static-destruct.h uses `sizeof(void *)`. Either way, sizeof(TestFunc) would be incorrect...

Honestly, I don't know why we don't use destructor attribute. The header says something about controlling the time stuff is destructed, but so far, all uses call it right before returning from main...

**Pull request merged**
