### PR TITLE
Do not provide default NTP servers. Fixes #437.

### LINKED ISSUE #437: timeX.google.com provide non standard time
systemd should not default to using time{1,2,3,4}.google.com.

Google doesn't provide timeX.google.com as a public service(0).  We don't maintain this to the same level of reliability/availability that we work hard to provide with other services (eg Google Public DNS, websearch etc).  We use this for systems outside of our datacenters that need to understand our concept of time.

Google (famously(1)) runs a non standard concept of time, that works well if everything in your infrastructure knows and understands this and is designed to work with this. If you mix and match NTP servers within a machine you'll run into problems (since Google's timeservers are deliberately false ticking).  If you mix and match between machines (eg some hosts use Google's time servers, and some use NIST timeservers) then your time won't match up between them.  As I write this Google's clock is ≈-0.4s out from UTC.  

Services such as NFS are likely to be confused as to the creation times of files and so on, logs won't be comparable between hosts etc.

People shouldn't be using these time servers for their own use.  People should definitely /not/ be using these time servers by default without realising it.

Please change systemd's default time servers to some service that is designed to provide a reliable public NTP service.

(0): http://googlecloudplatform.blogspot.com/2015/05/Got-a-second-A-leap-second-that-is-Be-ready-for-June-30th.html
(1): http://googleblog.blogspot.com/2011/09/time-technology-and-leaping-seconds.html

### PR DESCRIPTION
**Pull request by aneeshusa**
Google's NTP servers do not provide UTC time but 'Google Time' so it is
not appropriate to use them as default. As we are not a vendor, do not
use a vendor pool. Instead, provide no default and require distributions
to provide ntp server values.

### CODE REVIEW

**Comment by aneeshusa** [comment]
FYI: semaphore would need to pass in ntp servers when configuring for tests to pass, tests not passing right now means the patch works as expected.

**Comment by martinpitt** [comment]
@zonque, would you mind setting some distro NTP pool for semaphore? As that's what most vendors are doing anyway, it would be "closer to reality" to test with some explicit values anyway?

**Comment by xnox** [comment]
hm... a config option to specify vendor ID of the NTP pool would be nicer. With text encouraging to allocate a vendor pool.

**Comment by dvdhrm** [comment]
Why is your so called 'Google Time' not an appropriate default? Why is 'weird UTC' worse than no time? Your commit-message lacks an elaborate description of the topic.

**Comment by aneeshusa** [comment]
I don't think a separate configure option for a NTP pool vendor ID is useful: it creates a duplication of functionality which would be confusing, and it's possible a sysadmin may not want to use a vendor pool, say if they have in-house or custom ntp servers. The existing --with-ntp-servers option does the job fine without too much extra typing, and many distributions already use --with-ntp-servers in their configure scripts; any new distros that are forced to add that option by this breaking change would then use a different option, causing fragmentation which may lead to confusion down the road.

However, I do think documentation for distributions to allocate a vendor pool would be a good idea and explicitly encouraged - where would you want that to go? I can add it to the error line in configure, but it already seems a bit long and I think we should document it elsewhere.

**Comment by aneeshusa** [comment]
@dvdhrm: Google does not provide UTC time but performs special smearing; this difference from UTC time can cause issues that a sysadmin could easily be unaware of.

More importantly, per the original issue (#437) Google does not provide those nameservers as a public service, and hence we should not be using them as defaults for systemd.

**Comment by mbiebl** [comment]
@aneeshusa what about documenting it in README?

**Comment by aneeshusa** [comment]
I put a note in DISTRO_PORTING, let me know if you'd like to document somewhere else.

**Comment by dvdhrm** [comment]
We now print a warning if you fail to pass proper nameservers during `./configure`. This should fix the issue. If not, please discuss in #437 further options.

**Pull request closed without merging**
