### PR TITLE
test: merge TEST-58-REPART and test-repart.sh

### PR DESCRIPTION
**Pull request by yuwata**
And fixes one udev bug. Please backport the second commit for udev (and maybe the third commit) to v251-stable.

Partially replaces #24327.

### CODE REVIEW

**Comment by yuwata** [comment]
Still I do not know why test-repart is so unstable, as we have almost no log for the issue.
Hopefully, at least, we can now obtain helpful logs on failure with this PR.

**Comment by yuwata** [comment]
The failure on CentOS CI (Arch Linux) is by TEST-13-NSPAWN-SMOKE, unrelated.
The failure on focal-amd64 is by TEST-13-NSPAWN-SMOKE and TEST-38-FREEZER, unrelated.

**Review by DaanDeMeyer — APPROVED** [review]
differential shellcheck seems like a false positive, rest of CI failures are unrelated

**Comment by yuwata** [comment]
The second commit for udevd needs further rework. Please also backport the first commit in #24442.

**Pull request merged**
