### PR TITLE
Free up some resources on Azure Pipelines

### PR DESCRIPTION
**Pull request by evverx**
Let's drop the tests we also run on CentOS CI to free up some resources
for something more useful.

@mrc0mmand once this PR is merged it's going to be idle for the most part so if there is anything you'd like to move there it should be safe to add 2 more jobs. We can always retire Debian CI on Semaphore to also free up 4 machines.

### CODE REVIEW

**Comment by evverx** [comment]
Regarding CentOS CI, while in general I think it would be great to get more machines there, I think it could be used more efficiently. I'd start by trying not to run the tests when it's unnecessary. For example, PRs like this can be skipped altogether there because they affect Azure Pielines only. Similarly it should be enough for PRs where the documentation is changed to go through `meson` and `ninja` to make sure it can be built successfully. More generally, something like `git diff --name-only` could be used to detect the scope of PRs.

**Comment by yuwata** [comment]
It is not necessary to wait for CIs to be finished. Let's merge this.

**Comment by evverx** [comment]
@yuwata sure. I wouldn't have waited either.

This PR was more of a contingency plan I came up with in response to @mrc0mmand's email regarding CentOS CI. Hope it helps to keep the ball rolling.

**Comment by mrc0mmand** [comment]
> Regarding CentOS CI, while in general I think it would be great to get more machines there, I think it could be used more efficiently. I'd start by trying not to run the tests when it's unnecessary. For example, PRs like this can be skipped altogether there because they affect Azure Pielines only. Similarly it should be enough for PRs where the documentation is changed to go through `meson` and `ninja` to make sure it can be built successfully. More generally, something like `git diff --name-only` could be used to detect the scope of PRs.

@evverx thank you! Skipping the tests for certain PRs definitely makes sense, will look into it as soon as possible.

> 
> Plus, I think https://github.com/systemd/systemd-centos-ci/blob/master/vagrant/Vagrantfiles/Vagrantfile_arch-sanitizers-gcc could be skipped for the time being (providing we keep that part where systemd is built with clang/ASan/UBsan). That I think should save some time.

Yeah, that should basically cut the time needed for that job in half (to ~1 hour), will do.

**Pull request merged**
