### PR TITLE
resolvectl: Document help verb

### PR DESCRIPTION
**Pull request by Hendrikto**
The help verb is already implemented but undocumented.

### CODE REVIEW

**Comment by bluca** [comment]
Mmh I'm not sure, there's a lot of effort to unify the common flags/outputs across commands, so maybe the intention is to deprecate the verb in favour of the argument? @yuwata @poettering

**Comment by keszybz** [comment]
Yeah, that's on purpose. We support `-h/--help` uniformly anywhere, and don't want to advertise the aliases.

**Comment by Hendrikto** [comment]
In that case, I think a deprecation notice should be added. The help verb is part of the public interface of `resolvectl`, and thus will inevitable be used. The longer it is included without any warning, the more scripts will depend on it.

**Comment by keszybz** [comment]
We do this quite often: when something becomes obsolete, it is removed from document and `--help` output, but not from code. This way, we keep backwards compatibility (for scripts and such), without having clutter in the documentation. There is no need to a deprecation notice... It's fine that people keep using this in places where it was already used. By removing it from documentation, we discourage people from using it in new places.

**Pull request closed without merging**
