### PR TITLE
hwdb accel work

### PR DESCRIPTION
**Pull request by jwrdegoede**
This pull-request is mostly about dealing with 360 degree hinges style 2-in-1s with 2 accelerometers (one in the display and 1 in the base). The first 4 commits deal with these.

Commits 5 and 6 are 2 normal accelerometer orientation quirk additions.

### CODE REVIEW

**Comment by jwrdegoede** [comment]
@germanztz, this pull-req makes some changes to the hwdb entry which you added for the Medion Akoya E2221T. I don't expect these changes to cause any issues. Still it would be nice if you can test the new 60-sensor.hwdb file on your device.

**Comment by germanztz** [comment]
hello Hans, yes, I already tested it in my device, thanks!

**Comment by hadess** [comment]
@jwrdegoede Did you check what Windows thinks is the expected orientation for the sensors that are in the base, rather than the display? I couldn't find any mention of the expected orientation in this doc:
https://docs.microsoft.com/en-us/windows-hardware/design/whitepapers/integrating-motion-and-orientation-sensors

If there isn't a documented "corrected" orientation, we probably need to have some diagrams made to show how we expect those sensors to be oriented.

**Comment by jwrdegoede** [comment]
> @jwrdegoede Did you check what Windows thinks is the expected orientation for the sensors that are in the base, rather than the display? I couldn't find any mention of the expected orientation in this doc:
> https://docs.microsoft.com/en-us/windows-hardware/design/whitepapers/integrating-motion-and-orientation-sensors
> 
> If there isn't a documented "corrected" orientation, we probably need to have some diagrams made to show how we expect those sensors to be oriented.

AFAIK Windows does not define any standards for this. It seems that 360 degree hinges 2-in-1s using a 2 accelerometer setup all have a set of custom drivers for this using an HingeAngleService process and this process even calls back into ACPI / to the embedded-controller to update the EC's notion of tablet-mode or laptop-mode. I recently added a patch to one of the iio-sensor to mimick the ACPI call which the HingeAngleService process  makes when going into laptop-mode because sometimes these devices come up in tablet-mode with kbd and touchpad events suppressed:

https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/staging.git/commit/?h=staging-linus&id=e5b1032a656e9aa4c7a4df77cb9156a2a651a5f9

Did you see that I did actually add some docs about the expectations for the base-sensor mount-matrix? See commit b24e437ab00efe191f57d5. As mentioned in the commit message there this is based on the mount-matrices provided inside the ACPI tables for the BOSC0200 devices on Lenovo Thinkpad Yoga 11e models.

As I try to explain in the comment the mount-matrix for the base sensor should be such that it gives the exact same values as the display sensor when the lid is closed. IOW lid-closed == 0 degrees angle, so the gravity g-force vector seen by both accelerometers should be the same. I'm not sure a diagram will help here. What would help is a way to dump readings from both accelerometers *with the matrices applied*.

**Pull request merged**
