### PR TITLE
basic/missing_loop.h: fix missing lo_flags LO_FLAGS_DIRECT_IO definition

### PR DESCRIPTION
**Pull request by gwbres**
Signed-off-by: Guillaume W. Bres <guillaume.bressaix@gmail.com>

### CODE REVIEW

**Comment by poettering** [comment]
We don't use S-o-b on systemd btw. See: https://systemd.io/CODING_STYLE/#commiting-to-git

**Comment by gwbres** [comment]
Hello,
I'm facing an issue on ARM/cross-compiled context, against a 5.10 linux kernel.

When building the 250.4 tag, `LO_FLAGS_DIRECT_IO` and `LOOP_SET_DIRECT_IO` are not defined and the build fails. My "understanding" is you have core portions of the linux kernel imported into systemd (to make it self sufficient?) and these flags wind up as missing in my context. Any inputs ?

**Comment by poettering** [comment]
patch looks good. 

and yes, we import some kernel headers for more recent stuff. Our current intended minimum kernel baseline is 3.15, see README. We hence add fallback definitions for anything newer than that that we make use of. So your patch is absolutely right, since the loopback direct IO stuff was added in kernel 4.10

**Comment by gwbres** [comment]
> We don't use S-o-b on systemd btw. See: https://systemd.io/CODING_STYLE/#committing-to-git

hello @poettering 
sorry, missed that one. I just forced push / rewrote the commit, without the signature

**Comment by gwbres** [comment]
Hello @bluca,
what does stable backport mean ? should I provide similar PR to systemd-stable? I can take care of it if it helps,

see you,

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
> Hello @bluca, what does stable backport mean ? should I provide similar PR to systemd-stable? I can take care of it if it helps,
> 
> see you,

it's just for our benefit, don't worry about it

**Pull request merged**
