### PR TITLE
network: dhcp-server:  support static lease

### PR DESCRIPTION
**Pull request by yuwata**
Replaces #15556.

### CODE REVIEW

**Comment by yuwata** [comment]
The following several super minor changes are applied:
- reorder and merge commits to make each commit can be built.
- drop unnecessary line breaks.
- use `_cleanup_` attribute at more places.
- disable RA on test.
- refuse ANY address, and null or multicast MAC address.
- sort headers
- drop unnecessary headers

I already reviewed #15556. So, setting the green label.

cc @borna-blazevic.

**Comment by poettering** [comment]
lgtm

**Review by bluca — APPROVED** [review]
lgtm too - `TEST-39-EXECRELOAD` times out in CentOS but I don't see how it could be related

**Comment by borna-blazevic** [comment]
@yuwata @poettering thanks for the support during this pull request!

**Pull request merged**
