### PR TITLE
dbus: propagate errors from bus_init_system() and bus_init_api()

### LINKED ISSUE #7782: Log more information when DBus connection fails
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

- upstream (master)

### Problems

Many systemd functions are not available or degraded when systemd is not connected to DBus. Such situations are not entirely obvious. When we are connecting to the bus and any step in the process fails (or takes unusually long) e.g. authentication, name registration or match registration, we should log the failure and also log in big red letters from ```manager_startup()``` that connection failed.

Also systemd could remember that connection failed and retry connecting later.

In ```manager_startup()``` we ignore errors from ```manager_connect_bus()```,

```C
/* Let's connect to the bus now. */
(void) manager_connect_bus(m, !!serialization);
```
In ```unit_notify()``` we also ignore errors from ```bus_init()```,

```C
if (unit_has_name(u, SPECIAL_DBUS_SERVICE))
        /* The bus might have just become available,
        * hence try to connect to it, if we aren't
        * yet connected. */
        bus_init(m, true);
```

### PR DESCRIPTION
**Pull request by msekletar**
The aim of this change is to make sure that we properly log about all
D-Bus connection problems. After all, we only ever attempt to get on the
bus if dbus-daemon is around, so any failure in the process should be
treated as an error.

bus_init_system() is only called from bus_init() and in
bus_init() we have a bool flag which governs whether we should attempt
to connect to the system bus or not.
Hence if we are in bus_init_system() then it is clear we got called from
a context where connection to the bus is actually required and therefore
shouldn't be treated as the "best effort" type of operation. Same
applies to bus_init_api().

We make use of those error codes in bus_init() and log high level
message that informs admin about what is going on (and is easy to spot
and makes sense to an end user).

Also "retrying later" bit is actually a lie. We won't retry unless we
are explicitly told to reconnect via SIGUSR1 or re-executed. This is
because bus_init() is always called from the context where dbus-daemon
is already around and hence bus_init() won't be called again from
unit_notify().

Fixes #7782

### CODE REVIEW

**Comment by msekletar** [comment]
Semaphore CI failure seems unrelated.

**Comment by poettering** [comment]
hmm, the semaphore Ci issue should have been fixed already since yesterday. Could you rebase your patch on top of current git? it should go away then

**Comment by msekletar** [comment]
Rebased and force-pushed.

**Comment by poettering** [comment]
Hmm, yeah, patch looks good... I figure we could really wrap the bus_init() calls in (void) casts to clarify that we eat up the errors there, and hence can propagate them up to this point....

Anyway, merging.

**Pull request merged**
