### PR TITLE
bsod: restore vt on SIGTERM/SIGINT

### PR DESCRIPTION
**Pull request by mrc0mmand**
Let's install a simple no-op signal handler without SA_RESTART for SIGINT/SIGTERM, which allows us to interrupt read_one_char() and follow it up with a proper cleanup, including restoring the vt to the original state.

Resolves: #29478

Not sure if this is the best solution, but it seems to be the simplest one that appears to do the right thing. It should also unblock https://github.com/systemd/systemd/pull/29056 wrt the testing efforts.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by mrc0mmand** [comment]
I tweaked the logic a bit, so we always attempt to restore the vt if any error occurs after we switch to a new one, to make it a bit more robust (especially in tests).

**Comment by 1awesomeJ** [comment]
Thank you @mrc0mmand for the fix.
I hope you can find time to guide further on #29056.

Thanks again sir.

**Comment by 1awesomeJ** [comment]
@bluca,
I saw you virtually at the main conference room in Berlin.

It was awesome!
Thanks again for all the time you committed to mentoring me.

**Comment by 1awesomeJ** [comment]
Good evening @poettering.
It's nice to read from you sir.

**Pull request merged**
