### PR TITLE
DEBUG: run CI with packages from archive

### PR DESCRIPTION
**Pull request by eworm-de**
Currently we see a kernel panic with `TEST-25-IMPORT`, regarding btrfs. This is to "bisect" with Arch package archive to find the first bad release, and therefore find a limited number of candidate commits.
```
[   17.312369] ------------[ cut here ]------------
[   17.312666] WARNING: CPU: 1 PID: 527 at fs/btrfs/qgroup.c:1843 btrfs_remove_qgroup+0x26a/0x450 [btrfs]
[   17.312976] Modules linked in: joydev mousedev psmouse serio_raw atkbd libps2 intel_rapl_msr vivaldi_fmap iTCO_wdt intel_pmc_bxt iTCO_vendor_support intel_rapl_common kvm_amd pcspkr i2c_i801 intel_agp intel_gtt i8042 mac_hid vfat fat lpc_ich cfg80211 rfkill nfnetlink ip_tables btrfs blake2b_generic xor raid6_pq ccp libcrc32c crc32c_generic kvm crct10dif_pclmul crc32_pclmul crc32c_intel polyval_clmulni polyval_generic ghash_clmulni_intel sha512_ssse3 sha256_ssse3 sha1_ssse3 aesni_intel gf128mul crypto_simd cryptd i2c_smbus i2c_mux virtio_blk virtio_scsi virtio_balloon serio loop dm_mod qemu_fw_cfg vmw_vsock_virtio_transport vmw_vsock_virtio_transport_common vsock virtio_console virtio_rng x_tables
[   17.314686] CPU: 1 UID: 0 PID: 527 Comm: (sd-imgrm) Not tainted 6.12.4-arch1-1 #1 7c6e9657ff18c9ac01abfce09529b4cbe186f917
[   17.315082] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.16.3-3.fc41 04/01/2014
[   17.315521] RIP: 0010:btrfs_remove_qgroup+0x26a/0x450 [btrfs]
[   17.315896] Code: c0 0f 85 2d fe ff ff 48 8b 43 b0 4c 39 f0 75 d6 4d 8d a5 18 09 00 00 4c 89 e7 e8 e1 df 5a ea 48 83 7b 98 00 0f 84 20 01 00 00 <0f> 0b 4c 89 ef e8 ec df ff ff 83 f8 01 0f 84 28 01 00 00 49 8b bd
[   17.316387] RSP: 0018:ffffac0f80d7bb78 EFLAGS: 00010206
[   17.316535] RAX: 0000000000000000 RBX: ffff8d6bd4048eb8 RCX: 0000000219114001
[   17.316734] RDX: 0000000000000001 RSI: 00003ea34400baf0 RDI: ffff8d6bc20b0918
[   17.316901] RBP: 00ff000000000258 R08: 0000000000000000 R09: 00000000000016a1
[   17.317089] R10: 00000000ffffffff R11: 0000000000001000 R12: ffff8d6bc20b0918
[   17.317204] R13: ffff8d6bc20b0000 R14: ffff8d6bd4048e68 R15: 0000000000000000
[   17.317351] FS:  00007b6fb3877880(0000) GS:ffff8d6c3bd00000(0000) knlGS:0000000000000000
[   17.317568] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   17.317719] CR2: 00007fffcad87ff0 CR3: 0000000108efe006 CR4: 0000000000370ef0
[   17.317914] Call Trace:
[   17.317987]  <TASK>
[   17.318057]  ? btrfs_remove_qgroup+0x26a/0x450 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.318438]  ? __warn.cold+0x93/0xf6
[   17.318690]  ? btrfs_remove_qgroup+0x26a/0x450 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.319040]  ? report_bug+0xff/0x140
[   17.319156]  ? handle_bug+0x58/0x90
[   17.319243]  ? exc_invalid_op+0x17/0x70
[   17.319349]  ? asm_exc_invalid_op+0x1a/0x20
[   17.319457]  ? btrfs_remove_qgroup+0x26a/0x450 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.319712]  ? btrfs_remove_qgroup+0x25f/0x450 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.320009]  btrfs_ioctl+0x22c1/0x25c0 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.320353]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.320499]  ? path_openat+0x99a/0x12e0
[   17.320606]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.320710]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.320816]  ? release_extent_buffer+0x9c/0xb0 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.321121]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.321281]  ? __seccomp_filter+0x303/0x520
[   17.321424]  __x64_sys_ioctl+0x94/0xd0
[   17.321592]  do_syscall_64+0x82/0x190
[   17.321798]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.321924]  ? btrfs_statfs+0x472/0x5e0 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.322178]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.322477]  ? do_statfs_native+0xaf/0xe0
[   17.322591]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.322754]  ? __memcg_slab_free_hook+0xf7/0x140
[   17.322920]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.323060]  ? kmem_cache_free+0x3fa/0x450
[   17.323156]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.323273]  ? syscall_exit_to_user_mode_prepare+0x149/0x170
[   17.323424]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.323536]  ? syscall_exit_to_user_mode+0x37/0x1c0
[   17.323639]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.323777]  ? do_syscall_64+0x8e/0x190
[   17.323869]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.323989]  ? do_syscall_64+0x8e/0x190
[   17.324121]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.324242]  ? do_syscall_64+0x8e/0x190
[   17.324345]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.324479]  ? do_user_addr_fault+0x36c/0x620
[   17.324630]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.324740]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.324892]  entry_SYSCALL_64_after_hwframe+0x76/0x7e
[   17.325038] RIP: 0033:0x7b6fb3323ced
[   17.325151] Code: 04 25 28 00 00 00 48 89 45 c8 31 c0 48 8d 45 10 c7 45 b0 10 00 00 00 48 89 45 b8 48 8d 45 d0 48 89 45 c0 b8 10 00 00 00 0f 05 <89> c2 3d 00 f0 ff ff 77 1a 48 8b 45 c8 64 48 2b 04 25 28 00 00 00
[   17.325688] RSP: 002b:00007fffcad88ea0 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
[   17.325887] RAX: ffffffffffffffda RBX: 000000000000000b RCX: 00007b6fb3323ced
[   17.326093] RDX: 00007fffcad88f00 RSI: 000000004010942a RDI: 0000000000000014
[   17.326316] RBP: 00007fffcad88ef0 R08: 0000000000000069 R09: 00000000fffffffe
[   17.326525] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000014
[   17.326730] R13: 00007fffcad88f00 R14: 0000000000000000 R15: 0000000000000008
[   17.326941]  </TASK>
[   17.327033] Kernel panic - not syncing: kernel: panic_on_warn set ...
[   17.327184] CPU: 1 UID: 0 PID: 527 Comm: (sd-imgrm) Not tainted 6.12.4-arch1-1 #1 7c6e9657ff18c9ac01abfce09529b4cbe186f917
[   17.327443] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.16.3-3.fc41 04/01/2014
[   17.327577] Call Trace:
[   17.327606]  <TASK>
[   17.327647]  dump_stack_lvl+0x5d/0x80
[   17.327700]  panic+0x118/0x2db
[   17.327794]  ? btrfs_remove_qgroup+0x26a/0x450 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.328011]  check_panic_on_warn.cold+0xf/0x1e
[   17.328147]  __warn.cold+0x9f/0xf6
[   17.328208]  ? btrfs_remove_qgroup+0x26a/0x450 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.328641]  report_bug+0xff/0x140
[   17.328946]  handle_bug+0x58/0x90
[   17.329152]  exc_invalid_op+0x17/0x70
[   17.329286]  asm_exc_invalid_op+0x1a/0x20
[   17.331930] RIP: 0010:btrfs_remove_qgroup+0x26a/0x450 [btrfs]
[   17.332179] Code: c0 0f 85 2d fe ff ff 48 8b 43 b0 4c 39 f0 75 d6 4d 8d a5 18 09 00 00 4c 89 e7 e8 e1 df 5a ea 48 83 7b 98 00 0f 84 20 01 00 00 <0f> 0b 4c 89 ef e8 ec df ff ff 83 f8 01 0f 84 28 01 00 00 49 8b bd
[   17.332625] RSP: 0018:ffffac0f80d7bb78 EFLAGS: 00010206
[   17.332776] RAX: 0000000000000000 RBX: ffff8d6bd4048eb8 RCX: 0000000219114001
[   17.332927] RDX: 0000000000000001 RSI: 00003ea34400baf0 RDI: ffff8d6bc20b0918
[   17.333130] RBP: 00ff000000000258 R08: 0000000000000000 R09: 00000000000016a1
[   17.333259] R10: 00000000ffffffff R11: 0000000000001000 R12: ffff8d6bc20b0918
[   17.333378] R13: ffff8d6bc20b0000 R14: ffff8d6bd4048e68 R15: 0000000000000000
[   17.333483]  ? btrfs_remove_qgroup+0x25f/0x450 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.333666]  btrfs_ioctl+0x22c1/0x25c0 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.333821]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.333906]  ? path_openat+0x99a/0x12e0
[   17.333977]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.334050]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.334097]  ? release_extent_buffer+0x9c/0xb0 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.334254]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.334349]  ? __seccomp_filter+0x303/0x520
[   17.334396]  __x64_sys_ioctl+0x94/0xd0
[   17.334445]  do_syscall_64+0x82/0x190
[   17.334483]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.334553]  ? btrfs_statfs+0x472/0x5e0 [btrfs 12cb3b04f8d850052e05206a5c6326a21e90c1b6]
[   17.334692]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.334767]  ? do_statfs_native+0xaf/0xe0
[   17.334865]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.334949]  ? __memcg_slab_free_hook+0xf7/0x140
[   17.335032]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.335110]  ? kmem_cache_free+0x3fa/0x450
[   17.335183]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.335269]  ? syscall_exit_to_user_mode_prepare+0x149/0x170
[   17.335390]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.335465]  ? syscall_exit_to_user_mode+0x37/0x1c0
[   17.335542]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.335625]  ? do_syscall_64+0x8e/0x190
[   17.335698]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.335793]  ? do_syscall_64+0x8e/0x190
[   17.335856]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.335901]  ? do_syscall_64+0x8e/0x190
[   17.335927]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.335974]  ? do_user_addr_fault+0x36c/0x620
[   17.336016]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.336097]  ? srso_alias_return_thunk+0x5/0xfbef5
[   17.336165]  entry_SYSCALL_64_after_hwframe+0x76/0x7e
[   17.336212] RIP: 0033:0x7b6fb3323ced
[   17.336250] Code: 04 25 28 00 00 00 48 89 45 c8 31 c0 48 8d 45 10 c7 45 b0 10 00 00 00 48 89 45 b8 48 8d 45 d0 48 89 45 c0 b8 10 00 00 00 0f 05 <89> c2 3d 00 f0 ff ff 77 1a 48 8b 45 c8 64 48 2b 04 25 28 00 00 00
[   17.336469] RSP: 002b:00007fffcad88ea0 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
[   17.336567] RAX: ffffffffffffffda RBX: 000000000000000b RCX: 00007b6fb3323ced
[   17.336646] RDX: 00007fffcad88f00 RSI: 000000004010942a RDI: 0000000000000014
[   17.336750] RBP: 00007fffcad88ef0 R08: 0000000000000069 R09: 00000000fffffffe
[   17.336828] R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000014
[   17.336924] R13: 00007fffcad88f00 R14: 0000000000000000 R15: 0000000000000008
[   17.337006]  </TASK>
[   17.337511] Kernel Offset: 0x28e00000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
```

### CODE REVIEW

**Comment by eworm-de** [comment]
Please do not merge, running CI only!

**Comment by bluca** [comment]
> Please do not merge, running CI only!

please use "draft" for such PRs

**Comment by eworm-de** [comment]
Does CI run for drafts?

**Comment by DaanDeMeyer** [comment]
Yes

**Comment by eworm-de** [comment]
Same issue with linux 6.10.10-arch1-1.

**Comment by eworm-de** [comment]
```
 49/93 systemd:integration-tests / TEST-25-IMPORT                                                OK               19.66s
```
So linux 6.9.10-arch1-1 was ok...

**Comment by eworm-de** [comment]
OK, linux 6.10.arch1-2 is fine as well... That is kind of unexpected.

**Comment by eworm-de** [comment]
Linux 6.10.8.arch1-1 is good as well.

**Comment by eworm-de** [comment]
And last but not least... Linux 6.10.9.arch1-1 is good.

🎉🥳 So we have a winner! 🎉🥳

The issue was introduced with **linux 6.10.10**, probably by one of these commit:

* [btrfs: fix race between direct IO write and fsync when using same fd](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/id=01681aa609b5f110502f56c4e3b2938efcf4a5bc)
* [btrfs: initialize location to fix -Wmaybe-uninitialized in btrfs_lookup_dentry()](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/id=55b046ec8a4fca2a77880768d882c7e930b43f07)
* [btrfs: don't BUG_ON() when 0 reference count at btrfs_lookup_extent_info()](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/id=ef9a8b73c8b60b27d9db4787e624a3438ffe8428)
* [btrfs: replace BUG_ON() with error handling at update_ref_for_cow()](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/id=f895db00c65e5d77c437cce946da9ec29dcdf563)
* [btrfs: handle errors from btrfs_dec_ref() properly](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/id=a7f16a7a709845855cb5a0e080a52bda5873f9de)
* [btrfs: clean up our handling of refs == 0 in snapshot delete](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/id=03804641ec2d0da4fa088ad21c88e703d151ce16)
* [btrfs: replace BUG_ON with ASSERT in walk_down_proc()](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/id=a7dfb14798bc57245b6ca2c7245047762898bfd8)
* [btrfs: don't BUG_ON on ENOMEM from btrfs_lookup_extent_info() in walk_down_proc()](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/id=704c359b4093a2af650a20eaa030c435d7c30f91)
* [btrfs: slightly loosen the requirement for qgroup removal](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/id=ab6a217ac57741ec9649457d70bbc43caf0a922d)
* [btrfs: zoned: handle broken write pointer on zones](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/id=e91dab550dd1d2221333cac9f5c012ab5193696f)
* [btrfs: qgroup: don't use extent changeset when not needed](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/id=c3ae6e7b970d7445a277fd7ffff6e12c18f725d0)

**Comment by maharmstone** [comment]
@eworm-de, if you cherry-pick https://github.com/btrfs/linux/commit/c61ffaa0a3d9a2094e24d1fe2b17f20e109d2cc8 does it make your warning go away?

**Comment by eworm-de** [comment]
Built a package with that commit included, and testing with CI in https://github.com/systemd/systemd/pull/35598...

The relevant test `TEST-25-IMPORT` passed already, so looks good! Thanks a lot for fixing this!

Feel free to add a `Signed-off-by:` or `Tested-by:` for me.

Waiting for this to pop up in Linus' tree then...

**Pull request closed without merging**
