### PR TITLE
unbreak the build

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by evverx** [comment]
@mrc0mmand as far as I can remember, you experimented with bots on GitHub. I'm wondering if you could unleash one of them so that it would complain about PRs where CI hasn't been triggered for more than, say, 2 weeks and urge contributors to rebase and force-push their commits.

**Comment by evverx** [comment]
Having said that, it doesn't seem to happen very often so it looks like total overkill :-)

**Comment by mrc0mmand** [comment]
@evverx actually, something like this crossed my mind when I was trying to figure out how that change got into the master in the first place. I might experiment with that when I get some spare time :-)

**Comment by mrc0mmand** [comment]
@evverx thought about it on my way to work a little bit more and maybe having a bot tagging PRs with results older than, let's say 7 days, would be nice. And the tag could be something like `out-of-date-ci-results`.

**Comment by evverx** [comment]
@mrc0mmand I've just signed up for the GitHub Actions beta. I think once the systemd organization is approved, it will be possible to use something like https://github.com/actions/starter-workflows/blob/master/automation/stale.yml to mark "stale" PRs and comment on them automatically. Though I'm not sure what it's considered stale. I turned the actions on for my repositories just yesterday.

**Comment by mrc0mmand** [comment]
@evverx that sounds great! Also, it looks like it's configurable: https://github.com/actions/stale/blob/master/action.yml#L12

**Pull request merged**
