### PR TITLE
udev: do not append newline when write attributes

### LINKED ISSUE #13985: udev ATTR command fails to write snd_hda_intel id attribute
systemd version 243.78
Arch Linux

Background: On my system there are 2 sound devices using the same module (snd_hda_intel). The original problem is, that the recognition order of the devices is unstable, which results in unstable ALSA device names. I tried overwriting the device ids using udev rules (as described here https://alsa-project.org/wiki/Changing_card_IDs_with_udev and here https://alsa.opensrc.org/Udev#Writing_udev_rules).

Expected behavior:
Using the ATTR command in udev rules should write the specified string to the attribute.
DEVPATH=="/devices/pci0000:00/0000:00:08.1/0000:05:00.1/sound/card?", ATTR{id}="HDMI"

Unexpected behaviour you saw:
Using the ATTR command fails with the following debug log entries:

Nov 09 20:07:18 hostname systemd-udevd[331]: card0: /etc/udev/rules.d/97-alsa.rules:8 ATTR '/sys/devices/pci0000:00/0000:00:08.1/0000:05:00.1/sound/card0/id' writing 'HDMI'
Nov 09 20:07:18 hostname systemd-udevd[331]: card0: /etc/udev/rules.d/97-alsa.rules:8 Failed to write ATTR{/sys/devices/pci0000:00/0000:00:08.1/0000:05:00.1/sound/card0/id}, ignoring: Invalid argument

Using the RUN command and a bash/echo command succeeds.
Using echo without the parameter "-n" also results in the "Invalid argument" error.

Steps to reproduce the problem:
Use the specified rule to change the id of your snd_hda_intel sound device.

By taking a short look at the udev code, my guess is, that the ATTR command might try to add a newline to the string, which seems not to be allowed for the id attribute. However, I don't know how to test this assumption.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #13985.

### CODE REVIEW

**Comment by poettering** [comment]
hm, isn't this something that will break stuff elsewhere? did olden days udev append \n for this?

**Comment by yuwata** [comment]
No. The issue was introduced by 25de7aa7b90c23d33ea50ada1e50c5834a414237 (v243). Before the commit, the content is written by `fprintf()` without new line. The issue is a regression.

**Comment by keszybz** [comment]
LGTM.

**Comment by mbiebl** [comment]
@keszybz sounds like something which should be pulled into v243-stable. 
Would it make sense to introduce new labels for this for easier tracking? Say like `v243-candidate` or `v243-cherrypick`

**Comment by keszybz** [comment]
Not really, that just duplicates work. I'll pick it up in the usual fashion.
(I should have already made another stable batch, but I was busy with other PRs. I'll try to do it tomorrow.)

**Pull request merged**
