### PR TITLE
Backport stuff to v256-stable

### PR DESCRIPTION
**Pull request by daandemeyer**

### CODE REVIEW

**Comment by YHNdnzj** [comment]
Ugh, looks like I messed up the udev-ctrl commit, which got unnoticed because later commits in the PR drop the problematic part again...

**Comment by DaanDeMeyer** [comment]
> Ugh, looks like I messed up the udev-ctrl commit, which got unnoticed because later commits in the PR drop the problematic part again...

I dropped it

**Comment by bluca** [comment]
Please also drop the ambient cap changes, they will very very likely cause LSM failures so it's not appropriate for backporting, too risky

**Comment by DaanDeMeyer** [comment]
> Please also drop the ambient cap changes, they will very very likely cause LSM failures so it's not appropriate for backporting, too risky

Who's the dummy that put the label on that PR :(

**Comment by bluca** [comment]
Do the commits changing how FDs are handled fix actual issues? It is unclear from the PR/commit messages - if there are actual bugs being fixed they are probably fine, but if it's just cleanups then we shouldn't backport those either

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
> There's no associated bug report but they do fix theoretical issues

If the issues can be triggered with a test then it's fine to backport, but otherwise let's avoid introducing risks in the stable trees

**Pull request merged**
