### PR TITLE
list: drop unnecessary line continuation

### LINKED ISSUE #21886: Incorrect code in macros.h
**systemd version the issue has been seen with**
Master on github

In the fiel `macros.h` we see in the lines 168 ff:
```
#define LIST_JUST_US(name,item)                                         \
        (!(item)->name##_prev && !(item)->name##_next)                  \
#define LIST_FOREACH(name,i,head)                                       \
```
I think the line:
```
        (!(item)->name##_prev && !(item)->name##_next)                  \
```
is incorrect and should read:
```
        (!(item)->name##_prev && !(item)->name##_next)
```
so no continuation character (`\`).

Analogous problem in `list.h`.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #21886.

### CODE REVIEW

**Comment by albert-github** [comment]
Only list.h has been addressed, not macros.h (which is more serious) or is macros.h not used anymore?

**Comment by yuwata** [comment]
We do not have macros.h. We have macro.h, but the line 168 is not a macro... Which version do you see??

**Comment by albert-github** [comment]
The file is in the directory `coccinelle`

**Comment by yuwata** [comment]
Hm, I checked macro.h and macro-fundamental.h, but I cannot find any strange definitions...

**Comment by mrc0mmand** [comment]
It's here

https://github.com/systemd/systemd/blob/34b56848467a0348b724148fe3e0d9080eb56402/coccinelle/macros.h#L168

since I copied the macros verbatim for Coccinelle to work correctly.

**Comment by yuwata** [comment]
@mrc0mmand Thank you! The file is also fixed now.

**Review by mrc0mmand — APPROVED** [review]
LGTM!

**Pull request merged**
