### PR TITLE
networkd: Allow ':' in label

### PR DESCRIPTION
**Pull request by ssahani**
IFA_LABEL does not need much of a validation except the length
that is IFNAMSIZ as seen from kernel code.

Also revert https://github.com/systemd/systemd/commit/a341dfe563bf3be791107a0c98d47f74366c637d

### CODE REVIEW

**Comment by keszybz** [comment]
@peoronoob does this version work for you?

**Comment by peoro** [comment]
Hey, I can't try it right now, I might be able to try tonight (CET).

By looking at the code I believe that this patch seems to allow any string as a valid label, but the old checks will stay in place anywhere else an interface name is used.
I don't know if this semantics is the correct one: @ssahani could you please give us more information?

---

I need interface aliases to connect the same physical interface to two different subnets (I need `eth0:0` to be `192.168.0.1/24` and `eth0:1` to be `192.168.1.1/24`) and then forward the traffic received on `eth0:1` to `eth0:0`.
I believe that this PR will prevent me from doing what I need with systemd-network (i.e. using [`IPForward` and `IPMasquerade`](https://www.freedesktop.org/software/systemd/man/systemd.network.html#IPForward=)), since [src/shared/firewall-util.c:62](https://github.com/systemd/systemd/blob/4682047cf23f3471894d83d847cdac6b3bec92e1/src/shared/firewall-util.c#L62) and :64 will reject `eth0:0` and `eth0:1` as valid interface names. I haven't tested this theory though, and won't be able for a few hours.

**Comment by ssahani** [comment]
Please take a look https://github.com/systemd/systemd/pull/5116.

**Comment by peoro** [comment]
I see now, thanks.

`ip link` shows information about layer 2 (data link), while I believe that alias interfaces are on layer 3 (network/IP).

Many other tools support alias interfaces (e.g. `ifconfig`, `ip addr`, `iptables` etc), and I believe that we want to accept layer 3 interface names in many places in the systemd codebase.
See for instance [src/shared/firewall-util.c:62](https://github.com/systemd/systemd/blob/4682047cf23f3471894d83d847cdac6b3bec92e1/src/shared/firewall-util.c#L62): you can configure forwarding and masquerade on an alias interface called `enp0s9:hello` using `iptables`, and I believe you should be allowed to do this also using `systemd.network`.

At this point I guess that we should split `ifname_valid` in two different functions: one to check that an interface name is valid for level 2 (used where we expect a layer 2 interface name, e.g. to parse [OriginalName](https://www.freedesktop.org/software/systemd/man/systemd.link.html#OriginalName=) and similar fields in `systemd.link` files), and one to check level 3 interface names (which I believe will be used in most other cases).

**Comment by ssahani** [comment]
Quick look . Isn't the `entry_fill_basics 'out_interface` param passed as NULL from  both the calling functions ? `Label`  does not look like it's  used .

**Comment by poettering** [comment]
I'd prefer if we'd introduce an iflabel_valid() call or so for this, after all we probably shouldn't permit control chars to be used as labels... a label with a newline?

**Pull request merged**
