### PR TITLE
terminal: drop unfinished code

### PR DESCRIPTION
**Pull request by dvdhrm**
This drops the libsystemd-terminal and systemd-consoled code for various
reasons:
- It's been sitting there unfinished for over a year now and won't get
  finished any time soon.
- Since its initial creation, several parts need significant rework: The
  input handling should be replaced with the now commonly used libinput,
  the drm accessors should coordinate the handling of mode-object
  hotplugging (including split connectors) with other DRM users, and the
  internal library users should be converted to sd-device and friends.
- There is still significant kernel work required before sd-console is
  really useful. This includes, but is not limited to, simpledrm and
  drmlog.
- The authority daemon is needed before all this code can be used for
  real. And this will definitely take a lot more time to get done as
  no-one else is currently working on this, but me.
- kdbus maintenance has taken up way more time than I thought and it has
  much higher priority. I don't see me spending much time on the
  terminal code in the near future.

If anyone intends to hack on this, please feel free to contact me. I'll
gladly help you out with any issues. Once kdbus and authorityd are
finished (whenever that will be..) I'll definitely pick this up again. But
until then, lets reduce compile times and maintenance efforts on this code
and drop it for now.

### CODE REVIEW

**Comment by poettering** [comment]
I'd really like to see this done eventually I must say.

**Comment by keszybz** [comment]
I think the maintenance cost is negligible. Compile times can't be more than a small fraction of total build time. I think it would be better to instead provide a roadmap/todo so that other interested people can hack on this more easily.

**Comment by zonque** [comment]
If we resurrect this code, it may well live in a separate repository. As discussed in person last Friday, I agree with the removal.

**Comment by poettering** [comment]
@zonque this "separate repository" myth is something you really should forget. Unless you want to fork out src/shared and src/basic too, and allow it to deviate... There's a reason why we can do things quickly within systemd, and that's the huge library we have. If you do things externally, then you don't have that, and that's a _massive_ hurdle.

Also, this is code that is necessary for emergency paths if the console is turned off the kernel. As such it must be integrated with systemd, otherwise you just create non-sensical complexity.

So, when this happens one day: yes it really should live inside of the system repo, nothing else makes sense.

**Comment by teg** [comment]
I agree with Lennart that we want this inside systemd. A fallback/debug console should be somehow available as a basic building block, either as part of the kernel or as part of systemd. The only way a third-party repository makes any sense to me is if we argue that a console does not belong in the base OS at all (which I don't agree with, but I guess there is an argument there somewhere).

I don't agree with the removal, but as David is doing all the work on this, I guess it is all up to him.

**Comment by zonque** [comment]
@poettering, @teg Fair enough.

**Comment by dvdhrm** [comment]
If nobody minds the code sitting there, I'd be totally fine keeping it.

Regarding a roadmap: I should probably write one, but a lot of the work ahead is figuring out how the login infrastructure should look like.

**Comment by dvdhrm** [comment]
Merging this now, as most of the code needs significant rework and redesign. I don't see anyone but me working on this, so there's little reason to keep the code here. Furthermore, I don't see this getting finished anytime soon.
The codebase so far was far more sophisticated than it needs to be for a fallback console. If we want a console in systemd, it really should be a very stripped down version of systemd-consoled we have now.
As a last point: The code really is not lost. Just revert the commit to get it back.

**Comment by 257** [comment]
wait, what about users? i have been using this for a good while now and does the work (256-colour terminal for mutt for one). if compile-time difference is negligible then i would ask for it to be put back in place, if possible.

**Comment by dvdhrm** [comment]
The terminal implementation was always marked experimental and is not included in the API stability guarantees of systemd [1]. I'm not aware of any distro including it, either. Hence, it was never supported as full part of systemd, sorry.

Currently, there are other plans to provide said functionality, but it hasn't been fully figured out, yet. It is highly unlikely to be part of systemd, though.

[1] http://www.freedesktop.org/wiki/Software/systemd/InterfacePortabilityAndStabilityChart/

**Comment by bratwiz** [comment]
I do not have much background regarding these various issues, and I am curious what the issues / challenges are and why it is apparently so difficult to write or re-write the kernel to support more than one physical console? If you have more than one frame-buffer device, mouse and keyboard, what's the big holdup?

This is a feature that I would seriously like to see in linux, particularly for the smaller "embedded" form-factor boards which have come out of late, such as the Odroid, Raspberry Pi, etc. where you have the possibility for more than one display device and radically differing usage modes like a regular hdmi monitor and a LCD-TFT display, for instance. Which leads to potential usage modes such as being able to sit down and work on a full-size hdmi monitor when it's available and/or use the smaller LCD display when it's not and/or use the LCD display as an adjunct / alternate function display/input device, or perhaps a debugging console for a robotics project, etc. It seems to me that this functionality is likely a lot more desirable than it may seem, especially to people who's main focus is the typical desktop mode of operation.

Just my 2 cents ;-)

**Comment by sjnewbury** [comment]
Is there any documentation on what the plans are or what needs to be done? I just tried out KMSCON, and fixed the hwaccel which wasn't working with modern drm/kms. It seems wasteful to do any work getting the missing features of KMSCON working, like hw cursor and mouse support for example when what I really should be working on is right here.. unless there is another plan?

**Comment by Conan-Kudo** [comment]
With the adoption of SimpleDRM in Fedora Linux 36 (and presumably other distros to follow soon), it seems it might make sense to revive this now? We can now effectively guarantee that there's a DRI/DRM device for a KMS-based console implementation.

cc: @martinezjavier

**Comment by martinezjavier** [comment]
@Conan-Kudo unfortunately, one of the required pieces to make it useful is still missing, that is [drmlog](https://lwn.net/Articles/589858/) (or something similar).

Since there are two reasons why `CONFIG_FB` and `CONFIG_DRM_FBDEV_EMULATION` still need to be enabled: 1) a `fbdev` device for `fbcon` to bind and 2) to have kernel logs in a video console.

`sd-console` will solve (1) but no (2), for that we need some minimal in-kernel DRM client that just outputs kernel logs to a framebuffer during early boot and in oops/panics.

**Comment by AdamWill** [comment]
Hey folks, just checking in to register that one of the main reasons I'd love to see something like this happen is still throwing up problems: keyboard layouts.

We (Fedora, and distributions generally) still have all kinds of fun dealing with the big gap between how keyboard layouts work with kbd and xkb. It's just a constant pain point and systemd is still lugging around the `kbd-model-map` insanity to deal with it. It really would be *hugely* nice if something like this could get done and we could finally ditch kbd, all the legacy kbd layouts, and stop having to make complex guesses about what console layout best matches any arbitrary or pre-defined choice of xkb layouts, because it's stupidly hard to get right and annoying to remember how to maintain.

This comment inspired by https://bugzilla.redhat.com/show_bug.cgi?id=2121106 , the latest bug in a sad procession of them...

**Comment by keszybz** [comment]
The latest idea that was floated during LPC in Dublin, is to use a small wayland implementation to provide a terminal, e.g. weston with a full-screen terminal. This seems to be a more reasonable approach wrt. to long-term maintainance. For example, it's hard to imagine that an implementation in systemd could ever provide proper rendering of complex scripts, but with a "real" terminal implementation, we get that out of the box. Such an approach would provide much better opportunities for i18n, and with additional work, also for a11y.

**Comment by poettering** [comment]
Yeah, I want emojis on the console, but doing all that is *hard* and kinda pointless if VTE already does that. @fooishbar volunteered to work on a minimal Weston/VTE thing that just brings a full screen terminal to screen.

@fooishbar, i remember you said something like, you'll have it ready in a week, no? where can @AdamWill track progress on that? ;-)

**Comment by dvdhrm** [comment]
One of the biggest reasons to drop this from systemd was that we felt it was hard to justify a use-case for it. One major focus was to provide a fallback console that can be brought up on broken systems so you can still interact with the system and try to recover. This was certainly a developer/poweruser-focused feature. However, to be useful, we had to be able to bring this up under situations where other UIs failed. It needed to be minimal and non-invasive and avoid relying on whatever made the system fail in the first place.

This was in stark contrast to the demand of supporting non-English script, images/colors, complex input devices, vsync/atomic-modesetting, tabbing, etc. To get a fully functioning font-renderer up, as well as a keyboard subsystem, you need such a vast amount of code and infrastructure that it kinda worked against being a safe fallback.

This is a tough decision to make. It felt wrong to refuse depending on pango/harfbuzz, or refusing input-methods for better accessibility. But it would have pulled in lots of dependencies into a fail-safe fallback system and systemd felt like the wrong place for this. I believe that you can certainly create a system-compositor, or use an existing wayland compositor and create a full-screen text console. But I also believe that you certainly should not expect it to work in situations where your normal DE fails. Hence, there was little justification to work on it, if a normal gnome-terminal sufficed.

The alternative idea was to take what the kernel has right now, and properly encapsulate it into a modern fallback console. So you take the half-baked keyboard and font support, the direct on-screen framebuffer writers, and put it into a self-contained kernel module that simply reacts to a SysRq-Magic-Key and claims the screen+keyboard to provide a recovery console. This would suffer from lack of proper internationalization and accessibility, but it would certainly be able to recover in more situations than the alternatives.

Note, though, that the biggest obstacle in all this was retaining backwards-compatibility. It is not just the VT layer that prevents recovery systems from working, but also PAM, or the quite complex DRM drivers that might fail to reset to a directly-mapped framebuffer without tiling, or the input devices that are locked by X.org, etc. I still believe a purely user-space based fully-featured console would not serve a useful recovery console (though I am not saying I wouldn't appreciate it as a base-level DE!). Hence, no further efforts were made on systemd-console.

**Comment by AdamWill** [comment]
To be clear, personally I don't care about "images/colors, complex input devices, vsync/atomic-modesetting, tabbing". (Non-English script I care to some extent, but then, that already works on the current kernel implementation if you use an appropriate console font). My main desire is for basic keyboard input - *not* complex input methods - to use xkb layouts, and implement switching, so it is possible to use the same configuration for keyboard input at a VT as in a DE. Right now it's literally impossible to do this, so distributions are eternally doomed to attempting to translate between xkb and kbd configurations, which is impossible to do perfectly and hard to do well.

**Comment by fooishbar** [comment]
@poettering Yeah, Weston 10.0 or 11.0 will work with [foot](https://codeberg.org/dnkl/foot) as a terminal emulator.

```
weston -Sshell-vt${i} --shell=kiosk-shell.so --use-pixman --idle-time=0 --continue-without-input &
WAYLAND_DISPLAY=shell-vt${i} foot
```

We do have some [pre-rolled systemd bits](https://wayland.pages.freedesktop.org/weston/toc/running-weston.html#running-weston-from-a-systemd-service) for encapsulating it into a session too.

That works out of the box for me, but @martinezjavier was reporting that it was broken for him on virtio-gpu.

**Pull request merged**
