### PR TITLE
sd-bus: do not connect to dbus-1 socket when kdbus is available

### PR DESCRIPTION
**Pull request by kaysievers**
We should not fall back to dbus-1 and connect to the proxy when kdbus
returns an error that indicates that kdbus is running but just does not
accept new connections because of quota limits or something similar.

### CODE REVIEW

**Comment by keszybz** [comment]
This is becoming pretty hard to read. What about adding a helper function like

```
static bool connection_refused(r) {
   return r < 0 && !IN_SET(...);
}
```

and replacing the ifs with

```
container_kdbus_available |= connection_refused(r);
...
kdbus_available |= connection_refused(r);
```

?

**Comment by poettering** [comment]
I'd really prefer if the sources would be more explanatory on what's happening here, i.e. why we check exactly for -ENOENT and -ESOCKTNOSUPPORT and nothing else. A comment would be nice. But a comment and @keszybz's suggestion would be even better (though I'd call the function kdbus_shall_fallback_to_dbus1() or so, with the comment inside, why these two errors and no others).

Otherwise we'll look at this in two months and wonder what precisely these errors are about.

**Comment by dvdhrm** [comment]
Why so complex?

``` c
diff --git a/src/libsystemd/sd-bus/sd-bus.c b/src/libsystemd/sd-bus/sd-bus.c
index 0f07590..009883b 100644
--- a/src/libsystemd/sd-bus/sd-bus.c
+++ b/src/libsystemd/sd-bus/sd-bus.c
@@ -1173,7 +1173,10 @@ int bus_set_address_system(sd_bus *b) {
         if (e)
                 return sd_bus_set_address(b, e);

-        return sd_bus_set_address(b, DEFAULT_SYSTEM_BUS_ADDRESS);
+        if (is_kdbus_available())
+                return sd_bus_set_address(b, KERNEL_SYSTEM_BUS_ADDRESS);
+
+        return sd_bus_set_address(b, UNIX_SYSTEM_BUS_ADDRESS);
 }

 _public_ int sd_bus_open_system(sd_bus **ret) {
```

**Comment by poettering** [comment]
@dvdhrm we want the fallback to the UNIX transport if the kdbus kernel API version changes. Kay's patch delivers this, but yours doesn't.

**Comment by dvdhrm** [comment]
@poettering: What? `is_kdbus_available()` returns 'false' if the kernel runs a newer kdbus version than sd-bus can use.

**Comment by poettering** [comment]
It does? ok, then it should be good.

but hmm, i see it does KDBUS_CMD_BUS_MAKE with KDBUS_FLAG_NEGOTIATE. What's the specific effect of that? how does it do the version check? by comparing ioctl buf sizes?

**Comment by dvdhrm** [comment]
`is_kdbus_available()` checks that kdbusfs is mounted _and_ that the ioctl `KDBUS_CMD_BUS_MAKE` is actually a valid ioctl. When you execute an ioctl with `KDBUS_FLAG_NEGOTIATE`, it will not have any effect, the kernel just returns information which flags and items are allowed on the ioctl.

Hence, is_kdbus_available() will return 'false' if the ioctl-magic changed, or if kdbusfs is not mounted, or if kdbus is disabled via the command-line.

Note that we don't check for '0-system' to be available. This should not be necessary. If kdbusfs is mounted, then someone already initialized kdbus. We _rely_ on this being PID1. If you boot your system without kdbus but load kdbus.ko late, you better not mount it!

Btw., if you want to play with kdbus, you can just use `KDBUS_EXT=2` in the kernel build, to get `kdbus2.ko` (and kdbus2fs etc.).

**Comment by poettering** [comment]
Pach looks OK then. But I'd prefer if we'd cache the result of the check. Kay's approach has the benefit that strace looks nicer, and we only ever open() the device once instead of twice... With the caching this becomes a bit less visible...

**Comment by zonque** [comment]
It also has different runtime semantics, as the dry run is now done always, before actually trying. A logic that has "if I can't connect, see if negotiation works, and then decide whether or not to fail" is actually saner, because the error case is less likely then the success case.

**Comment by dvdhrm** [comment]
Fixing it via my approach gets way heavier, btw. See below. If we go that route, we should probably add helpers `const char *system_bus_address(void)` and `int user_bus_address(char **out)`.

Anyway, no time to fix this now.. feel free to pick this up or go with Kay's approach. However, that has the downside that we suddenly apply magic to the "A;B;C;..." listings of bus addresses. It's no longer visible to the caller why a secondly listed address might be skipped, even though it is unrelated to one before. Sure, under normal circumstances, no-one should mix and match unix and kdbus buses on the same system, but I still dislike enforcing this.

``` c
diff --git a/src/basic/def.h b/src/basic/def.h
index 5aaba1f..e0d6822 100644
--- a/src/basic/def.h
+++ b/src/basic/def.h
@@ -63,7 +63,6 @@

 #define UNIX_SYSTEM_BUS_ADDRESS "unix:path=/var/run/dbus/system_bus_socket"
 #define KERNEL_SYSTEM_BUS_ADDRESS "kernel:path=/sys/fs/kdbus/0-system/bus"
-#define DEFAULT_SYSTEM_BUS_ADDRESS KERNEL_SYSTEM_BUS_ADDRESS ";" UNIX_SYSTEM_BUS_ADDRESS
 #define UNIX_USER_BUS_ADDRESS_FMT "unix:path=%s/bus"
 #define KERNEL_USER_BUS_ADDRESS_FMT "kernel:path=/sys/fs/kdbus/"UID_FMT"-user/bus"

diff --git a/src/bus-proxyd/bus-proxyd.c b/src/bus-proxyd/bus-proxyd.c
index 3cc3b33..6e07aea 100644
--- a/src/bus-proxyd/bus-proxyd.c
+++ b/src/bus-proxyd/bus-proxyd.c
@@ -177,8 +177,9 @@ static int help(void) {
                "     --configuration=PATH Configuration file or directory\n"
                "     --machine=MACHINE    Connect to specified machine\n"
                "     --address=ADDRESS    Connect to the bus specified by ADDRESS\n"
-               "                          (default: " DEFAULT_SYSTEM_BUS_ADDRESS ")\n",
-               program_invocation_short_name);
+               "                          (default: %s)\n",
+               program_invocation_short_name,
+               is_kdbus_available() ? KERNEL_SYSTEM_BUS_ADDRESS : UNIX_SYSTEM_BUS_ADDRESS);

         return 0;
 }
@@ -262,7 +263,7 @@ static int parse_argv(int argc, char *argv[]) {
         }

         if (!arg_address) {
-                arg_address = strdup(DEFAULT_SYSTEM_BUS_ADDRESS);
+                arg_address = strdup(is_kdbus_available() ? KERNEL_SYSTEM_BUS_ADDRESS : UNIX_SYSTEM_BUS_ADDRESS);
                 if (!arg_address)
                         return log_oom();
         }
diff --git a/src/bus-proxyd/stdio-bridge.c b/src/bus-proxyd/stdio-bridge.c
index f275f67..c5dac39 100644
--- a/src/bus-proxyd/stdio-bridge.c
+++ b/src/bus-proxyd/stdio-bridge.c
@@ -50,8 +50,9 @@ static int help(void) {
                "     --version            Show package version\n"
                "     --machine=MACHINE    Connect to specified machine\n"
                "     --address=ADDRESS    Connect to the bus specified by ADDRESS\n"
-               "                          (default: " DEFAULT_SYSTEM_BUS_ADDRESS ")\n",
-               program_invocation_short_name);
+               "                          (default: %s)\n",
+               program_invocation_short_name,
+               is_kdbus_available() ? KERNEL_SYSTEM_BUS_ADDRESS : UNIX_SYSTEM_BUS_ADDRESS);

         return 0;
 }
@@ -137,7 +138,7 @@ static int parse_argv(int argc, char *argv[]) {
         }

         if (!arg_address) {
-                arg_address = strdup(DEFAULT_SYSTEM_BUS_ADDRESS);
+                arg_address = strdup(is_kdbus_available() ? KERNEL_SYSTEM_BUS_ADDRESS : UNIX_SYSTEM_BUS_ADDRESS);
                 if (!arg_address)
                         return log_oom();
         }
diff --git a/src/dbus1-generator/dbus1-generator.c b/src/dbus1-generator/dbus1-generator.c
index 4980fcc..641c242 100644
--- a/src/dbus1-generator/dbus1-generator.c
+++ b/src/dbus1-generator/dbus1-generator.c
@@ -84,7 +84,8 @@ static int create_dbus_files(
                         fprintf(f, "Environment=DBUS_STARTER_BUS_TYPE=%s\n", type);

                         if (streq(type, "system"))
-                                fprintf(f, "Environment=DBUS_STARTER_ADDRESS=" DEFAULT_SYSTEM_BUS_ADDRESS "\n");
+                                fprintf(f, "Environment=DBUS_STARTER_ADDRESS=%s\n",
+                                        is_kdbus_available() ? KERNEL_SYSTEM_BUS_ADDRESS : UNIX_SYSTEM_BUS_ADDRESS);
                         else if (streq(type, "session")) {
                                 char *run;

@@ -94,8 +95,12 @@ static int create_dbus_files(
                                         return -EINVAL;
                                 }

-                                fprintf(f, "Environment=DBUS_STARTER_ADDRESS="KERNEL_USER_BUS_ADDRESS_FMT ";" UNIX_USER_BUS_ADDRESS_FMT "\n",
-                                        getuid(), run);
+                                if (is_kdbus_available())
+                                        fprintf(f, "Environment=DBUS_STARTER_ADDRESS="KERNEL_USER_BUS_ADDRESS_FMT "\n",
+                                                getuid(), run);
+                                else
+                                        fprintf(f, "Environment=DBUS_STARTER_ADDRESS="UNIX_USER_BUS_ADDRESS_FMT "\n",
+                                                getuid(), run);
                         }
                 }

diff --git a/src/libsystemd/sd-bus/sd-bus.c b/src/libsystemd/sd-bus/sd-bus.c
index 0f07590..11d8093 100644
--- a/src/libsystemd/sd-bus/sd-bus.c
+++ b/src/libsystemd/sd-bus/sd-bus.c
@@ -1173,7 +1173,10 @@ int bus_set_address_system(sd_bus *b) {
         if (e)
                 return sd_bus_set_address(b, e);

-        return sd_bus_set_address(b, DEFAULT_SYSTEM_BUS_ADDRESS);
+        if (is_kdbus_available())
+                return sd_bus_set_address(b, KERNEL_SYSTEM_BUS_ADDRESS);
+
+        return sd_bus_set_address(b, UNIX_SYSTEM_BUS_ADDRESS);
 }

 _public_ int sd_bus_open_system(sd_bus **ret) {
@@ -1221,16 +1224,17 @@ int bus_set_address_user(sd_bus *b) {
                 return sd_bus_set_address(b, e);

         e = secure_getenv("XDG_RUNTIME_DIR");
-        if (e) {
+        if (is_kdbus_available())
+                (void) asprintf(&b->address, KERNEL_USER_BUS_ADDRESS_FMT, getuid());
+        else if (e) {
                 _cleanup_free_ char *ee = NULL;

                 ee = bus_address_escape(e);
                 if (!ee)
                         return -ENOMEM;

-                (void) asprintf(&b->address, KERNEL_USER_BUS_ADDRESS_FMT ";" UNIX_USER_BUS_ADDRESS_FMT, getuid(), ee);
-        } else
-                (void) asprintf(&b->address, KERNEL_USER_BUS_ADDRESS_FMT, getuid());
+                (void) asprintf(&b->address, UNIX_USER_BUS_ADDRESS_FMT, ee);
+        }

         if (!b->address)
                 return -ENOMEM;
```

**Comment by kaysievers** [comment]
Replaced by: https://github.com/systemd/systemd/pull/932

**Pull request closed without merging**
