### PR TITLE
fstab-generator: always add Before= dependency to mount units.

### PR DESCRIPTION
**Pull request by neilbrown**
The current practice of omitting the Before= dependency for
select mount units is both problematic and unnecessary.

It is problematic because there is then no ordering imposed
at shutdown, so the mount units can be - and often are - stopped
before various services which might be using the mounted
filesystem.  This causes the unmount to fail, but allows shutdown
to proceed.
If the filesystem was an NFS filesystem, then once the network is
disabled it will become impossible to perform a final fsync,
and shutdown hangs indefinitely.

It is unnecessary because there is no harm in having the Before=
dependency.
The two cases where Before= is omitted are automount and nofail.
For automount, the mount unit will not even be started in
the same transaction as the *-fs.target, so - much as was the case
for "noauto" mounts which were also affected until recently
(commit bd6bcce4d7fd9) - there is no meaning to any ordering
between the .mount and the *-fs.target.

For "nofail", the intended use case is when the device doesn't
exist.  In that case there will be no delay, the mount unit will
simply fail immediately.  Using "Wants" instead of "Requires"
is the correct way to handle this, and that already happens.
Omitting "Before=" doesn't help.

The worst case for mounts at boot time is if the mount or the fsck could
take a long time.  If that is likely, and if the delay should not delay
the rest of the boot process, then automount should be used,
possibly with some mechanism to trigger the automount early so the
fsck/mount gets started early.  Disabling Before= is, at best, a poor
substitute for automount.

Fixes 5991.

### CODE REVIEW

**Comment by arvidjaar** [comment]
> For "nofail", the intended use case is when the device doesn't
> exist. In that case there will be no delay, the mount unit will
> simply fail immediately.

Not, it won't. Mount unit is ordered after fsck unit which itself is ordered after device unit. Before mount unit has chance to even try to fail systemd waits for device to appear. That is what causes delay.

**Comment by neilbrown** [comment]
Yes, you are right.  There will be a 90 second delay, as device units get a default JobTimeout (or JobRunningTimeout - I don't know how they relate yet).
So there will be a delay, but "nofail' mounts will still not cause the whole boot to fail.
Should "nofail" impose a shorter timeout on the device, do you think?

**Comment by neilbrown** [comment]
In the interests of forward-progress, I've revised the patch to only change the behaviour in the "automount" case.  For automount mounts, we need the Before= and it causes no harm.  For "nofail" mounts, the Before= is still omitted.

Is that an acceptable change?

**Comment by fbuihuu** [comment]
> Is that an acceptable change?

I think it does.

**Comment by fbuihuu** [comment]
FWIW, this change looks good to me.

**Comment by fbuihuu** [comment]
@poettering could you please have a look ?

**Comment by neilbrown** [comment]
This patch is wrong.  We really don't want the Before= dependency on automounted units.  If the mount gets triggered before XXX-fs.target is reached (unlikely but possible), and if the mount attempt takes a long time, then XXX-fs.target will be incorrectly delayed.
I think that we need to add the Before= dependency only once the filesystem has been mounted.  A separate pull request does this.
So I'm closing this pull request.

**Comment by keszybz** [comment]
Ah, OK.

**Comment by fbuihuu** [comment]
> I f the mount gets triggered before XXX-fs.target is reached (unlikely but possible)

I would say that if this case happens it should be an error since any service that would attempt to access to the automount should be scheduled after local-fs.target.

> I think that we need to add the Before= dependency only once the filesystem has been mounted. A separate pull request does this.

For the record it's #6102 and @poettering doesn't seem to like it.

I think the code would be easier to understand if the generator simply adds the `Before=` constraint durint the boot process only when "!nofail" is set. The other cases would get the ordering constraint only once the fs has been mounted (#6102).

**Comment by keszybz** [comment]
There's also the idea of adding asymmetrical Before/After that only apply to stop jobs. In the end, that might be a cleaner solution.

**Comment by fbuihuu** [comment]
Well in my understanding it was decided to avoid implementing those asymmetrical ordering constraints: that would probably open the door to users who will write units with fancy ordering deps. It might not worth the troubles specially if this case would be the only user.

**Comment by neilbrown** [comment]
My understanding is that the preferred way forward is to record ownership for each dependency.  So instead of ->dependencies[UNIT_BEFORE] being a set of units, it would be a set of `{unit,owner}`.
Then when a filesystem is mounted, `{SPECIAL_???_FS_TARGET,"mount.c"}` is added to the UNIT_BEFORE set, and when the filesystem is unmounted, `{SPECIAL_???_FS_TARGET,"mount.c"}` would be removed.
If the unit file generated by fstab-generator specified a dependency, then `{SPECIAL_???_FS_TARGET,"load-fragment.c"}` would also be in the set, and would not get removed.

**Pull request closed without merging**
