### PR TITLE
core: support %j in unit dependency resolution

### PR DESCRIPTION
**Pull request by williamspatrick**
Commit 250e9fadbcc0ca90e697d7efb40855b054ed3b8f introduced
support for %j/%J specifier in unit files.  The function
unit_name_printf is used in unit dependency resolution,
such as Wants / After directives, but was missing support
for the %j.  Add to allow directives such as:

    [Unit]
    Wants=bar-%j.target

Fixes: systemd/systemd#11217
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>

### CODE REVIEW

**Comment by keszybz** [comment]
Any chance you could add a unit test that this works as expected?

**Comment by williamspatrick** [comment]
@keszybz - Attempted to write a unit test.

**Comment by williamspatrick** [comment]
CentOS CI passed but I'm not convinced it ran my testcase from reading the console log. Would appreciate pointers.

**Comment by yuwata** [comment]
The unit files under test/test-execute/ are used by src/test/test-execute.c. So, please also update test-execute.c.

Or, you can create test/TEST-XX-YYYY to test these units.

**Comment by williamspatrick** [comment]
@yuwata - thanks for the pointers.  Pushed an addition to test-execute.

**Comment by mrc0mmand** [comment]
CentOS CI doesn't seem to be happy:

```
exec-specifier-j-wants.service: About to execute: /usr/bin/sh -c 'test $$(systemctl show --value -p Wants exec-specifier-j-wants.service) = exec-specifier-j-depends-wants.service'
exec-specifier-j-wants.service: Forked /usr/bin/sh as 11453
exec-specifier-j-wants.service: Changed dead -> start
sys-subsystem-net-devices-n.device: Changed dead -> plugged
sys-devices-virtual-net-n.device: Changed dead -> plugged
exec-specifier-j-wants.service: Executing: /usr/bin/sh -c 'test $(systemctl show --value -p Wants exec-specifier-j-wants.service) = exec-specifier-j-depends-wants.service'
/usr/bin/sh: line 0: test: =: unary operator expected
Received SIGCHLD from PID 11453 (sh).
Child 11453 (sh) died (code=exited, status=2/INVALIDARGUMENT)
exec-specifier-j-wants.service: Child 11453 belongs to exec-specifier-j-wants.service.
exec-specifier-j-wants.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
exec-specifier-j-wants.service: Failed with result 'exit-code'.
exec-specifier-j-wants.service: Changed start -> failed
exec-specifier-j-wants.service: Unit entered failed state.
Assertion 'service->main_exec_status.status == status_expected' failed at ../src/test/test-execute.c:64, function check(). Aborting.
```

**Comment by williamspatrick** [comment]
I couldn't figure out how to do the test I needed with the test-execute framework.  Nothing else in there handles Wants/Afters, so I seemed to be treading new ground.

Switched it over to a TEST-xx style test.  Waiting for CI to give :+1:.

**Comment by mrc0mmand** [comment]
@williamspatrick the integration tests (TEST-??-*) expect the `testsuite.service` to exist [[0]](https://github.com/systemd/systemd/blob/master/test/test-functions#L680-L690) [[1]](https://github.com/systemd/systemd/blob/master/test/TEST-01-BASIC/test.sh#L23-L31), so you have to incorporate it to your unit set.

**Comment by williamspatrick** [comment]
@mrc0mmand - Thanks for the pointers.

**Comment by williamspatrick** [comment]
Log-file from CentOS CI indicates test-case ran now.  I'm satisfied with this PR now for merge.

```
specifier-j-wants.service: Installed new job specifier-j-wants.service/start as 84
specifier-j-depends-wants.service: Installed new job specifier-j-depends-wants.service/start as 85
testsuite.target: Installed new job testsuite.target/start as 1
testsuite.service: Installed new job testsuite.service/start as 83
testsuite.target: Enqueued job testsuite.target/start as 1
```

```
         Starting Dependent service for percent-j specifier...
[  OK  ] Started Dependent service for percent-j specifier.
         Starting Wants with percent-j specifier...
[  OK  ] Started Wants with percent-j specifier.
         Starting Testsuite: Ensure testsuite Wants directives work...
[  OK  ] Started Testsuite: Ensure testsuite Wants directives work.
```

**Pull request merged**
