### PR TITLE
Add rx-gro-hw support

### PR DESCRIPTION
**Pull request by daandemeyer**

### CODE REVIEW

**Comment by poettering** [comment]
hmm, you added GenericReceiveOffloadHardware= even though GenericReceiveOffload= already exists. Are those two options supposed to be orthogonal? Doesn't look like it, no?

i.e. shouldn't this just be a new value accepted for GenericReceiveOffload=? i.e. that you can set it to yes|no|hardware?

**Comment by DaanDeMeyer** [comment]
So it seems it was intended to be orthogonal: https://lists.openwall.net/netdev/2017/12/04/66. I guess the idea is that with the GRO feature you either turn GRO on or off and with the gro-hw feature you configure whether hardware offloading should be used when GRO is on.

With the current implementation, you can enable/disable GRO without touching whether HA should be used or not. This allows the main link file to configure whether HA GRO should be used or not while a drop in can enable/disable GRO without having to know whether HA should be used or not.

**Comment by TriMoon** [comment]
I might be mind-bugged today but...
Doesn't "offloading" already imply that it is handled by hardware?
(Else you would not need it)

**Comment by DaanDeMeyer** [comment]
> I might be mind-bugged today but...
Doesn't "offloading" already imply that it is handled by hardware?
(Else you would not need it)

> My interpretation of that word is different as "buffering", which can be done in both software and hardware...

I find it slightly confusing as well but according to the kernel the feature itself is called GRO (Generic Receive Offload) which can then be either done in hardware or in software.

**Comment by poettering** [comment]
if they were purely orthogonal then all four combinations of on/off would make sense. do they though? 

they way i see it?

gro=on grohw=off → gro in sw, makes sense
gro=on grohw=on → gro in hw, makes sense
gro=off grohw=off → gro off fully
gro=off growh=on → gro also off fully

the latter two cases are identical, hence they aren't orthogonal, no?

to me it appears we should have 

GenericReceiveOffload=no|yes|software|hardware

for gro off, gro on with default kernel choice of hw/sw, gro on with sw, gro on with hw

**Comment by poettering** [comment]
(but i don't grok thus stuff really, documentation absent for networking features in kernel, as usual)

**Comment by anitazha** [comment]
@kuba-moo do you have insight on gro vs gro-hw? Specifically I guess on the difference and how these should be toggled

**Comment by DaanDeMeyer** [comment]
> for gro off, gro on with default kernel choice of hw/sw, gro on with sw, gro on with hw

What about kernel default for GRO on/off with hw? That wouldn't be representable with the suggested scheme I think

**Comment by kuba-moo** [comment]
GRO-HW is really a form of LRO which is supposed to not break packet boundaries. Adding it as option to `LargeReceiveOffload` would make more sense than coalescing into `GenericReceiveOffload` IMHO, but the naming (chosen by vendors for "marketing purposes") would then be confusion.
I think all sw/hw combinations make sense. HW won't cover as many cases as SW can so hw+sw makes sense, in cases where the workload is well covered by hw disabling sw will save CPU cycles, if hw is misbehaving sw only makes sense. And what does one do if user chose "hw-only" but the underlying driver does not have gro-hw support? There's also no "kernel default" for hw setting because it's a per-driver/vendor thing. 
Frankly I'd recommend adding `GenericReceiveOffloadHardware=` - GRO is a mess of options so added confusion would outweigh the gain from coalescing things. Second choice for me would be adding "GRO-compatible" as a setting for `LargeReceiveOffload`.

**Comment by yuwata** [comment]
LGTM.

**Pull request merged**
