### PR TITLE
network: accept NUL character in SendOption=

### LINKED ISSUE #14609: systemd-networkd fails to decode DHCP SendOption with a null character (\00)
**systemd version the issue has been seen with**
> 244

**Used distribution**
 > Archlinux

**Expected behaviour you didn't see**
 >My ISP waits for a DHCP AUTH string starting with \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1a\x09\x00\x00\x05\x58\x01\x03\x41\x01\x0d followed by a credential. Putting the following line in my 10-wan.network file should allow the string to be sent:
SendOption=90:string:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1a\x09\x00\x00\x05\x58\x01\x03\x41\x01\x0dcredential

>Using tcpdump, I should see this message in the DHCP packet :
`AUTH Option 90, length 31: 0.0.0.0.0.0.0.0.0.0.0.26.9.0.0.5.88.1.3.65.1.12.114.101.100.101.110.116.105.97.108`

**Unexpected behaviour you saw**
 > The message does not appear in the packet sent and the following errors are found in journalctl:

```
/etc/systemd/network/10-wan.network:11: Failed to decode DHCPv4 option data, ignoring assignment: \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1a\x09\x00\x00\x05\x58\x01\x03\x41\x01\x0dcredential
/etc/systemd/network/10-wan.network:11: Failed to store DHCPv4 option 'x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1a\x09\x00\x00\x05\x58\x01\x03\x41\x01\x0dcredential', ignoring assignment: Invalid argument
```
>Removing all the `\00` characters works. This null character seems to be the problem.

**Steps to reproduce the problem**
On any interface in DHCP (eg. wan), use the option SendOption in the DHCP block:
```
[DHCPv4]
SendOption=90:string:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1a\x09\x00\x00\x05\x58\x01\x03\x41\x01\x0dcredential
```
On the same interface, listen to udp packets with `tcpdump -i wan -v udp`
Restart systemd-networkd with `systemctl restart systemd-networkd`

### PR DESCRIPTION
**Pull request by yuwata**
Closes #14609.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @ssahani.

**Comment by mrc0mmand** [comment]
```
=================================================================
==51703==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 31 byte(s) in 1 object(s) allocated from:
    #0 0x7f0cf22adaca in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f0cf159a2ae in malloc_multiply ../src/basic/alloc-util.h:96
    #2 0x7f0cf159a2ae in cunescape_length_with_prefix ../src/basic/escape.c:303
    #3 0x5562d06ca164 in cunescape_length ../src/basic/escape.h:47
    #4 0x5562d06ca164 in cunescape ../src/basic/escape.h:50
    #5 0x5562d06ca81a in test_cunescape ../src/test/test-escape.c:106
    #6 0x5562d06cb954 in main ../src/test/test-escape.c:176
    #7 0x7f0cf0138152 in __libc_start_main (/lib64/libc.so.6+0x27152)

Direct leak of 19 byte(s) in 1 object(s) allocated from:
    #0 0x7f0cf22adaca in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f0cf159a2ae in malloc_multiply ../src/basic/alloc-util.h:96
    #2 0x7f0cf159a2ae in cunescape_length_with_prefix ../src/basic/escape.c:303
    #3 0x5562d06ca164 in cunescape_length ../src/basic/escape.h:47
    #4 0x5562d06ca164 in cunescape ../src/basic/escape.h:50
    #5 0x5562d06ca7bb in test_cunescape ../src/test/test-escape.c:103
    #6 0x5562d06cb954 in main ../src/test/test-escape.c:176
    #7 0x7f0cf0138152 in __libc_start_main (/lib64/libc.so.6+0x27152)

Direct leak of 13 byte(s) in 1 object(s) allocated from:
    #0 0x7f0cf22adaca in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f0cf159a2ae in malloc_multiply ../src/basic/alloc-util.h:96
    #2 0x7f0cf159a2ae in cunescape_length_with_prefix ../src/basic/escape.c:303
    #3 0x5562d06ca164 in cunescape_length ../src/basic/escape.h:47
    #4 0x5562d06ca164 in cunescape ../src/basic/escape.h:50
    #5 0x5562d06ca75c in test_cunescape ../src/test/test-escape.c:100
    #6 0x5562d06cb954 in main ../src/test/test-escape.c:176
    #7 0x7f0cf0138152 in __libc_start_main (/lib64/libc.so.6+0x27152)

Direct leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x7f0cf22adaca in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f0cf159a2ae in malloc_multiply ../src/basic/alloc-util.h:96
    #2 0x7f0cf159a2ae in cunescape_length_with_prefix ../src/basic/escape.c:303
    #3 0x5562d06ca164 in cunescape_length ../src/basic/escape.h:47
    #4 0x5562d06ca164 in cunescape ../src/basic/escape.h:50
    #5 0x5562d06ca70f in test_cunescape ../src/test/test-escape.c:97
    #6 0x5562d06cb954 in main ../src/test/test-escape.c:176
    #7 0x7f0cf0138152 in __libc_start_main (/lib64/libc.so.6+0x27152)

SUMMARY: AddressSanitizer: 73 byte(s) leaked in 4 allocation(s).
````

**Comment by yuwata** [comment]
@mrc0mmand Thanks. Fixed.

**Comment by ssahani** [comment]
LGTM thanks

**Pull request merged**
