### PR TITLE
introduce empty_or_dash() helper

### PR DESCRIPTION
**Pull request by poettering**
A simple helper to replace some frequently used expression.

### CODE REVIEW

**Comment by cdown** [comment]
Looks great. Would it also be worth adding a coccinelle rule for this?

**Comment by poettering** [comment]
actually, I did, and then forgot to add it to the PR.

**Comment by poettering** [comment]
Pushed in the missing coccinelle script, leaving green label on, since change is minimal, and coccinelle scripts are run by devs only on demand, and thus not part of the regular build process or runtime

**Comment by keszybz** [comment]
This looks safe enough, let's merge.

**Pull request merged**
