### PR TITLE
tree-wide: use 'signed int' instead of 'int' for bit field variables

### PR DESCRIPTION
**Pull request by yuwata**
Suggested by LGTM.

### CODE REVIEW

**Comment by evverx** [comment]
Thank you. I think it would be helpful to add a link to https://lgtm.com/rules/1506024027114/ to the commit message or copy-paste something from there.

**Comment by evverx** [comment]
This pull request **fixes 2 alerts** when merging 2ac9e24d40eecd7757503baf2c6f0c8972750ada into 874b5ad2488d75c6bbc4388ef0fd07e6a1baf4d0 - [view on LGTM.com](https://lgtm.com/projects/g/systemd/systemd/rev/pr-a4cf43cd4ef95027c6f84bd7d5fea8e954665332)

**fixed alerts:**

* 2 for Ambiguously signed bit\-field member

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by yuwata** [comment]
@evverx Thank you for the suggestion. Updated.

**Comment by evverx** [comment]
This pull request **fixes 2 alerts** when merging 456cd588b57f4daeac4ac23154161f11a25a003c into 283c2653877f2b958045ad99493869fe1a88be95 - [view on LGTM.com](https://lgtm.com/projects/g/systemd/systemd/rev/pr-a068785776ef9dec91c617652e552de9c6b2e0c4)

**fixed alerts:**

* 2 for Ambiguously signed bit\-field member

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by poettering** [comment]
interesting. i didn't know the compiler had freedom to pick the signedness for bit fields. oh man.

**Pull request merged**
