### PR TITLE
Call unlockpt in machine_openpt

### LINKED ISSUE #1139: machinectl shell terminates connection
```
(# or $, does not matter) machinectl shell
Connected to the local host. Press ^] three times within 1s to exit session.

Connection to the local host terminated.
```

Attach gdb and break in `src/machine/machinectl.c:process_forward` near `pty_forward_get_last_char(*forward, &last_char);`

```
(gdb) print **forward
$1 = {event = 0x5555555cf9d0, master = 7, stdin_event_source = 0x5555555d3860, stdout_event_source = 0x5555555d3950, master_event_source = 0x0, sigwinch_event_source = 0x5555555d3b30, saved_stdin_attr = {
    c_iflag = 27906, c_oflag = 5, c_cflag = 1215, c_lflag = 35387, c_line = 0 '\000', c_cc = "\003\034\177\025\004\000\001\377\021\023\032\377\022\017\027\026\377", '\000' <repeats 14 times>, c_ispeed = 15, 
    c_ospeed = 15}, saved_stdout_attr = {c_iflag = 26624, c_oflag = 5, c_cflag = 1215, c_lflag = 2608, c_line = 0 '\000', 
    c_cc = "\003\034\177\025\004\000\001\377\021\023\032\377\022\017\027\026\377", '\000' <repeats 14 times>, c_ispeed = 15, c_ospeed = 15}, read_only = false, saved_stdin = true, saved_stdout = true, 
  stdin_readable = false, stdin_hangup = false, stdout_writable = true, stdout_hangup = false, master_readable = false, master_writable = false, master_hangup = true, ignore_vhangup = false, 
  last_char_set = false, last_char = 0 '\000', in_buffer = '\000' <repeats 2047 times>, out_buffer = '\000' <repeats 2047 times>, in_buffer_full = 0, out_buffer_full = 0, escape_timestamp = 0, 
  escape_counter = 0}
```

`master_hangup = true,`

So someone hanged up on us. This leads us to `src/machine/machine-dbus.c:bus_machine_method_open_shell`:

``` c
        description = strjoina("Shell for User ", isempty(user) ? "root" : user);
        r = sd_bus_message_append(tm,
                                  "(sv)(sv)(sv)(sv)(sv)(sv)(sv)(sv)(sv)(sv)(sv)(sv)(sv)",
                                  "Description", "s", description,
                                  "StandardInput", "s", "tty",
                                  "StandardOutput", "s", "tty",
                                  "StandardError", "s", "tty",
                                  "TTYPath", "s", pty_name,
                                  "SendSIGHUP", "b", true,
                                  "IgnoreSIGPIPE", "b", false,
                                  "KillMode", "s", "mixed",
                           >>>    "TTYVHangup", "b", true,
                                  "TTYReset", "b", true,
                                  "UtmpIdentifier", "s", utmp_id,
                                  "UtmpMode", "s", "user",
                                  "PAMName", "s", "login");
```

Could this be the reason for the hangup? Note that there is no such thing in `bus_machine_method_open_login` and no hangup is observed.

### PR DESCRIPTION
**Pull request by hvenev**
This fixes #1139 for me. Sorry about the commit spam.

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, the unlockpt should stay in the namespace really, and not moved onto the host. But of course it's currently missing completely from the ".host" case...

**Comment by poettering** [comment]
I have prepped a new patch now. Will file a PR for it shortly.

**Comment by hvenev** [comment]
Does the behavior of `unlockpt` depend on the namespace it is run in? Can it actually fail?

**Comment by poettering** [comment]
@mustrumr yes, it tries to stat() the pty file.

**Comment by poettering** [comment]
My patch is now submitted as PR #1165. Closing this one. Thank you very much for your patch though!

**Pull request closed without merging**
