### PR TITLE
udev: optimize devlink creation

### PR DESCRIPTION
**Pull request by yuwata**
Replaces #25839.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
This improves performance of `testcase_simultaneous_events_2` ~30%.

Before (32.8 sec):
```
## 3 iterations start: 11:13:44.690953163
## 3 iterations end: 11:14:17.493974927
```
After (23.8 sec):
```
## 3 iterations start: 11:17:53.869938387
## 3 iterations end: 11:18:17.624268345
```

**Comment by yuwata** [comment]
@fbuihuu The base idea of this PR is equivalent to yours. But this does not create another symlink 'owner'. I think this is simpler. WDYT?

**Comment by yuwata** [comment]
The CIFuzz failure looks related to #25842.

**Comment by evverx** [comment]
> The CIFuzz failure looks related to https://github.com/systemd/systemd/pull/25842.

It's related to that but CIFuzz shouldn't have failed here. I restarted the CIFuzz job and reported the CIFuzz issue at https://github.com/google/oss-fuzz/issues/9318#issuecomment-1383548570.

**Comment by fbuihuu** [comment]
@yuwata I tried this approach before but preferred https://github.com/systemd/systemd/pull/25839 at the end.

The main reason is that retrieving the current owner of the symlink with your approach must be obtained from udev DB and uevent, which takes more time but more importantly it can be racy when devices are unplugged and hence harder to figure out what's going on when these cases happen.

OTOH, "owner" symlinks are contained in "link" directories hence getting the priority and the devname of the current owner is much simpler, doesn't need any access outside the link directories and those accesses are protected by link directory locks so it's conceptually simpler.

Finally the creation/removal of the "owner" symlinks adds a bit more code indeed but it's simple code.

**Comment by yuwata** [comment]
@fbuihuu 

> The main reason is that retrieving the current owner of the symlink with your approach must be obtained from udev DB and uevent

No. If files in "/run/udev/links" are symlink (that is, "new format"), then the current logic to obtain "owner" does _not_ read udev DB. It _does_ read uevent file, but I think that provides extra safety, like the call of `access()` in `stack_directory_read_one()`. Actually, such extra safety may reduce performance theoretically, but have you already observe significant difference? At least, it does not change the order of complexity. So, unless the performance difference is significant, I prefer the logic of this PR over introducing additional "owner" symlink.

> but more importantly it can be racy when devices are unplugged and hence harder to figure out what's going on when these cases happen.

In that case, we will receive "remove" uevent for the device (hopefully soon), and another device node symlink for still existing device will be created. Or, do you already observe any issues that cannot cover with that?


The above comments are not strong rejection of your PR. I may simply not understand 'race' or further 'performance regression' (or 'performance improvement' by your PR). I'd like to know more concrete analysis. Please elaborate more.

> Finally the creation/removal of the "owner" symlinks adds a bit more code indeed but it's simple code.

Yeah. If it actually improves something, then that's welcome.


So, If you do not mind, I'd like to merge this PR at first, and then discuss the importance of the "owner" symlink later. WDYT? The difference of your and my PRs is only how to obtain the current owner. So, your main patch will become simpler, I guess.

**Comment by yuwata** [comment]
Another point why I'd like to avoid to introduce 'owner' symlink is that it essentially duplicates information about the owner: we can obtain the current owner through the 'owner' symlink under /run/udev/links and device node symlink under /dev. If the two sources contradict each other, then what should we do? Which symlink should have priority over the other? Of course, by carefully writing code, such conflict can be resolved. But at least, we need to extra care if we introduce the 'owner' symlink.

**Comment by fbuihuu** [comment]
> No. If files in "/run/udev/links" are symlink (that is, "new format"), then the current logic to obtain "owner" does _not_ read udev DB. It _does_ read uevent file, but I think that provides extra safety, like the call of `access()` in `stack_directory_read_one()`. 

Indeed it only has to access the uevent file and some stuff in /sys.

But this approach can lead to some inconsistencies where the data in the link directories are no more consistent with the other data (saved in uevent file or udev DB or /sys)  until the relevant (remove) uevents are processed by udev. And if you try to handle these inconsistencies when processing an uevent for an unrelated device, then you introduce new consistencies because the selection of the new owner is no more consistent to the data saved in the link directories.

It's also conceptually simpler because all data needed to update a symlink are self contained in the link directories.

For these reasons I think my approach is simpler.

> So, If you do not mind, I'd like to merge this PR at first, and then discuss the importance of the "owner" symlink later. WDYT? The difference of your and my PRs is only how to obtain the current owner. So, your main patch will become simpler, I guess.

No my patch will become outdated and I will have to rebase again. AFAIK there's no hurry so I don't see why we couldn't wait and discuss until we agree on the best approach.

**Comment by fbuihuu** [comment]
> Another point why I'd like to avoid to introduce 'owner' symlink is that it essentially duplicates information about the owner: we can obtain the current owner through the 'owner' symlink under /run/udev/links and device node symlink under /dev.

Well any data saved in the link directories already duplicate information (to make the retrieving of these data faster/safer). And the "owner" symlink actually doesn't introduce any device data duplication, it just points to the current owner.

> If the two sources contradict each other, then what should we do? Which symlink should have priority over the other? Of course, by carefully writing code, such conflict can be resolved. But at least, we need to extra care if we introduce the 'owner' symlink.

I think we should wait the relevant uevents and act according to the state of the link directories only. It's simpler.

**Comment by fbuihuu** [comment]
@yuwata could we try to make some progress here ? See my previous comments on why I think this version is preferable.

**Comment by yuwata** [comment]
@fbuihuu Sorry for late reply. Yeah, let's restart the discussion.

Most of the comments below may be duplicated to the above, but I'd like to rephrase them (that's simply for sorting out my points explained in the above, and not emphasize my opinions. Please understand this is just for preparation for restarting our discussion).

- First of all, the basic concepts of this PR and yours are mostly identical, except for whether we should introduce the new "owner" symlink or not. (So, in that sense, if the "owner" symlink is really useful, we can adopt it later after merging this PR. Of course, that requests another work to rebase your PR on top of this PR. I feel sorry, but such complexity (unfortunately?) does not have priority.)
- As you can see in my commit, we have all information about which device owns the devlink and its priority. `sd_device_new_from_devname()` provides the `sd_device` object which owns the symlink. Then, we can obtain the priority of the devlink by using `device_get_device_id()` and `stack_directory_read_one()`. These steps are quite simple, and I have no idea about why we need to introduce the new "owner" symlink.
- Of course, the current owner device may be removed during we call `node_get_current()` or later process.
  - If the current owner device is removed _during_ `node_get_current()` is called, then it should return one of `-ENODEV`, `-ENXIO`, or `-ENOENT`, and these can be handled with `ERRNO_IS_DEVICE_ABSENT()`. In that case, udevd will search the most prioritized device, hence there should be no problem, except for the performance.
  - If the current owner device is removed _after_ `node_get_current()` is called, then the current process may do a "wrong" decision about if we should update the devlink or not, but the wrong decision should be (hopefully extremely) soon recovered when processing the `remove` uevent for the current owner device.

These are the summary of my point in the previous discussion.

------------
> But this approach can lead to some inconsistencies where the data in the link directories are no more consistent with the other data (saved in uevent file or udev DB or /sys) until the relevant (remove) uevents are processed by udev. And if you try to handle these inconsistencies when processing an uevent for an unrelated device, then you introduce new consistencies because the selection of the new owner is no more consistent to the data saved in the link directories.

Sorry, I cannot follow what kind of inconsistencies introduced by this PR? There exists some kind of inconsistencies described in the above, but that is not introduced by this PR, and should already exist. Or, do I misunderstand your point?

> It's also conceptually simpler because all data needed to update a symlink are self contained in the link directories.
>
> For these reasons I think my approach is simpler.

I hope, this PR does not introduce any new race window or inconsistency. If you notice this PR actually introduce _NEW_ one, then please let me know. Otherwise, introducing new "owner" symlink does not sound simple for me.

> > So, If you do not mind, I'd like to merge this PR at first, and then discuss the importance of the "owner" symlink later. WDYT? The difference of your and my PRs is only how to obtain the current owner. So, your main patch will become simpler, I guess.
> 
> No my patch will become outdated and I will have to rebase again. AFAIK there's no hurry so I don't see why we couldn't wait and discuss until we agree on the best approach.

I feel that's sorry, but our rule is that we accept commits in a 'complete' form.
If you do not mind, and you will illustrate that your method actually has some benefits, then I can rebase your PR.

**Comment by fbuihuu** [comment]
@yuwata sorry for the late reply.

OK I think you got a point and the "owner" symlink may actually not be needed, at least for the first version. I remember that the stack/link directory should be self contained and should contain any data needed to find the prioritized devnode and the current node with the highest prio without relying on data saved elsewhere (ie in /sys or in the uevent file) but couldn't come up anymore with a use case which would lead to an inconsistency.

However I think the code in https://github.com/systemd/systemd/pull/25839 is globally simpler, compare  the 2 versions of `link_update()` for example or the use of the `add` parameter, which is propagated down to the stack. Also some other functions such as `stack_directory_read_one()` or `stack_directory_find_prioritized_id()` are simpler.

So if you don't mind, I'll update https://github.com/systemd/systemd/pull/25839 one more time to drop the "owner" symlink part and we can take a final decision.

Thanks.

**Comment by yuwata** [comment]
> However I think the code in #25839 is globally simpler, compare the 2 versions of `link_update()` for example or the use of the `add` parameter, which is propagated down to the stack. Also some other functions such as `stack_directory_read_one()` or `stack_directory_find_prioritized_id()` are simpler.

I do not think so, but not sure. Maybe.

But, comparing with my version, your code seems to lack some conditions for "the current device ID" vs "evetn's device ID", and "the priority of the current devlink" vs "the priority of the requested devlink". Yeah, the conditions in my code are slightly complicated, but each branch has comment what happens in that case and why we need to care about that. I think my code is at least not so bad.

> So if you don't mind, I'll update #25839 one more time to drop the "owner" symlink part and we can take a final decision.

I do not mind which code will be accepted or merged. I only care is if the code in the end is correct and has clear comments.

**Comment by yuwata** [comment]
@fbuihuu OK. Let's, at least as the first step, go with this version. Dropping 'needs-discussion' tag.

**Comment by yuwata** [comment]
@poettering @keszybz @bluca, @mwilck Could you take a look?

**Comment by mwilck** [comment]
I am unsure whether this PR or #25839 is the primary merge candidate now. But I think the following concern applies to both approaches. How is this safe against the following race?
```
device A (remove)			device B (add)
node_get_current() -> A        		node_get_current() -> A
stack_directory_update()
    (A is deleted under /run/udev/links)
stack_directory_find_prioritized_devnode
    (finds no device)
					stack_directory_update()
					    (B is created under /run/udev/links)
					returns because link is owned by A
unlinks slink and parents
```
In this (admittedly unlikely) scenario we'd end up without a device owning the symlink (and thus, the symlink deleted), even though `B` should own it. Am I overlooking something? (I don't think the current udev tests cover this scenario).

**Comment by mwilck** [comment]
I suppose the above race might be avoided by updating the stack directory before running `node_get_current()`. Then the adding worker would need to verify that the device returned by `node_get_current()` still exists before returning. My head is aching, I can't make up my mind if that would be sufficient.

**Comment by mwilck** [comment]
> Each udev worker takes a lock for the stack directory, hence the scenario @mwilck concerned never happens.

Thanks for explaining it. At least we have it documented now.

**Review by mwilck — APPROVED** [review]
This looks good to me.

I also ran a scaling test with up to 1000 contenders for a symlink, and found no scalability issue / livelock as I'd seen previously. That was on an 8-core system; we may need to repeat that test on a system with more cores.

**Comment by mwilck** [comment]
I ran a second test on a 24-CPU system with `udev-test.pl 162` (`all_block_devs`):

|    N | time (sys+user) / s  |
|------|----------------------|
|   10 |                    6 |
|  100 |                   30 |
| 1000 |                  310 |
| 2000 |                  704 |
| 5000 |                 2500 |

This looks ok to me. 

Note that the `all_block_devs` test has one device (`sda6`) stick out with increased priority. The way the udev test is currently implemented, we can't create a test case with multiple devices all having the same (highest) priority. Therefore the current test doesn't represent the potential worst case where all devices have the same priority.

**Comment by poettering** [comment]
lgtm

**Comment by fbuihuu** [comment]
@yuwata this has an unexpected side effect: with this commit applied and when a block device has several partitions and one of the partition and the parent device share the same label then the symlink `/dev/disk/by-label/<shared-label>` will be owned by the parent device, not by the partition anymore.

This is a pretty common setup with ISO-Hybrid images actually, see https://github.com/systemd/systemd/issues/12409 for more details.

The problem is that if one mounts the device by following the label symlink it will mount the parent device instead of the partition one as before. And mounting the parent device prevents the partitions from being mounted.

I know that there hasn't been any guaranty for the partition device to always get the symlink but from the user perspective this is a regression.

We could simply workaround this by increasing the priority of by-label symlinks for partition devices but I'm not sure whether this won't introduce other new issues.

WDYT ?

**Comment by bluca** [comment]
if this is a regression, could you please open an issue with a reproducer?

**Comment by fbuihuu** [comment]
I'm not sure if we can call it a regression because ISO-Hybrid images relies on an undefined behavior (several devices share the same label). But until this commit udev chose to attribute the symlink to the partition devices, which is what users expect.

Ok I'll open an issue.

**Comment by dustymabe** [comment]
> @yuwata this has an unexpected side effect: with this commit applied and when a block device has several partitions and one of the partition and the parent device share the same label then the symlink `/dev/disk/by-label/<shared-label>` will be owned by the parent device, not by the partition anymore.

We hit this problem in Fedora CoreOS testing. I opened https://github.com/systemd/systemd/issues/28803 to document the issue with a reproducer.

**Pull request merged**
