### PR TITLE
systemd-analyze cat-presets

### PR DESCRIPTION
**Pull request by keszybz**
This fills in a bit of functionality that is useful when debugging preset issues.

### CODE REVIEW

**Comment by boucman** [comment]
Would it be possible to either extend cat-config to deal with directories, so we can solve the whole class of problem, or alternatively to have another word cat-directory that would do that logic ?

Or is there some other value on cat-preset I don't really understand ?

**Comment by keszybz** [comment]
You're right, I should probably do that instead.

**Comment by poettering** [comment]
Yes, it would be nice if this would also cover #10256 (see #10225 for context)

**Comment by keszybz** [comment]
Hmm, so the problem is that every tool has a slightly different search path:
system presets: /etc/systemd/system-preset, /run/systemd/system-preset, /usr/local/lib/systemd/system-preset, /usr/lib/systemd/system-preset, /lib/systemd/system-preset (a.k.a. `CONF_PATHS_STRV("systemd/system-preset")`)
user presets: /etc/systemd/user-preset, /run/systemd/user-preset, /usr/local/lib/systemd/user-preset, /usr/lib/systemd/user-preset
hwdb: /etc/udev/hwdb.d, /usr/lib/udev/hwdb.d or /lib/hwdb/udev/hwdb.d
tmpfiles system: `CONF_PATHS_NULSTR("tmpfiles.d")`
tmpfiles user: a complicated list generated based on user name
etc.

I don't see a good solution. Some ideas:
1. encode the knowledge about search paths in the tool, so we'd say e.g. `systemd-analyze cat-files udev/hwdb.d` and it would know that it should use prefixes /etc and /usr/lib or /lib, and so on, for each of our config sets.
2. add knowledge to individual tools, like we already have with `--cat-config`.

The first is feels very artificial, but would provide a uniform interface. The second would require many small modifications. Ideas?

**Comment by poettering** [comment]
hmm, CONF_PATHS_NULSTR()/CONF_PATHS_STRV() should cover the system level stuff pretty OK, no? i.e. with the exception of the --user stuff that should cover things pretty nicely I think?

**Comment by keszybz** [comment]
>  CONF_PATHS_NULSTR()/CONF_PATHS_STRV() should cover the system level stuff pretty OK, no?

See hwdb case above.

**Comment by poettering** [comment]
Hmm, but the "/lib/hwdb/udev/hwdb.d" looks like a bug to me, maybe fix that?

**Comment by keszybz** [comment]
Updated. I went to the approach suggested by @poettering:
- paths in various tools are updated to be uniform
- systemd-analyze cat can be used for most paths. See the commit for details.

**Comment by keszybz** [comment]
Rebased.

**Pull request merged**
