### PR TITLE
tree-wide: Load entry-token and layout.conf from /usr/lib/kernel/ as well

### PR DESCRIPTION
**Pull request by daandemeyer**

### CODE REVIEW

**Review by yuwata — APPROVED** [review]
LGTM.

**Comment by keszybz** [comment]
Why `needs-stable-backport`?

**Comment by DaanDeMeyer** [comment]
@keszybz I considered these bug fixes as we should have been reading these files from /usr/lib from the beginning. Feel free to skip if you think otherwise

**Comment by keszybz** [comment]
I think it's more of a "new feature". If we just somehow forgot one directory from a list or read it in the wrong order, then it'd be more of a bugfix. But the kernel-install stuff was initially written with only `/etc` in mind. We also should change ukify, and I think it's better if it all happens in a release.

**Pull request merged**
