### PR TITLE
man: document that separate /usr/local/ must not be used for config

### PR DESCRIPTION
**Pull request by keszybz**
Since we document /usr/local/lib/systemd/ and other paths for various things, add notes that this is not supported if /usr/local is a separate partition.

Also, split paragraphs in one place where the subject changes without any transition.

Follow-up for 02f35b1c905ac63ba62f94efebf858412e961fc1. Replaces https://github.com/systemd/systemd/pull/33231.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by keszybz** [comment]
Hmm, I pushed to the branch, but the update is not showing up here. Is github broken or did I mess something up?

**Comment by bluca** [comment]
I see the update fetching your repo, and I don't see it here, try to force push again?

**Comment by YHNdnzj** [comment]
> Hmm, I pushed to the branch, but the update is not showing up here. Is github broken or did I mess something up?

The PR is linked to the `man-usr-local` branch in `systemd/systemd` repo, rather than your fork. Something went wrong back when you opened the PR?

**Comment by keszybz** [comment]
@YHNdnzj thanks. I must've messed up the push command.

**Pull request merged**
