### PR TITLE
journal: reduce DEFAULT_SYNC_INTERVAL_USEC to 1min

### PR DESCRIPTION
**Pull request by vcaputo**
We get enough reports of watchdog-induced core dumps in CoreOS
to suggest this default of 5 minutes is inappropriate.  Increasing the
frequency of the periodic sync should reduce the amount of time the sync
takes to complete.

### CODE REVIEW

**Comment by keszybz** [comment]
IIUC, this will _increase_ the total amount of IO, but make the chunks smaller, thus reducing latency. I'm not against merging this, if it helps, but this does not seem like optimum solution. What we really want is for the kernel to start flushing those pages after we write them. Would something like madvise with `POSIX_MADV_DONTNEED` help?

**Comment by vcaputo** [comment]
From linux/mm/madvise.c:

```
/*
 * Application no longer needs these pages.  If the pages are dirty,
 * it's OK to just throw them away.  The app will be more careful about
 * data it wants to keep.  Be sure to free swap resources too.  The
 * zap_page_range call sets things up for shrink_active_list to actually free
 * these pages later if no one else has touched them in the meantime,
 * although we could add these pages to a global reuse list for
 * shrink_active_list to pick up before reclaiming other pages.
 *
 * NB: This interface discards data rather than pushes it out to swap,
 * as some implementations do.  This has performance implications for
 * applications like large transactional databases which want to discard
 * pages in anonymous maps after committing to backing store the data
 * that was kept in them.  There is no reason to write this data out to
 * the swap area if the application is discarding it.
 *
 * An interface that causes the system to free clean pages and flush
 * dirty pages is already available as msync(MS_INVALIDATE).
 */
static long madvise_dontneed(struct vm_area_struct *vma,
```

So we don't want MADV_DONTNEED.

What we'd really prefer is msync w/MS_ASYNC, but from linux/mm/msync.c:

```
/*
 * MS_SYNC syncs the entire file - including mappings.
 *
 * MS_ASYNC does not start I/O (it used to, up to 2.5.67).
 * Nor does it marks the relevant pages dirty (it used to up to 2.6.17).
 * Now it doesn't do anything, since dirty pages are properly tracked.
 *
 * The application may now run fsync() to
 * write out the dirty pages and wait on the writeout and check the result.
 * Or the application may run fadvise(FADV_DONTNEED) against the fd to start
 * async writeout immediately.
 * So by _not_ starting I/O in MS_ASYNC we provide complete flexibility to
 * applications.
 */
SYSCALL_DEFINE3(msync, unsigned long, start, size_t, len, int, flags)
```

So MS_ASYNC is a noop since 2.6.17.

Honestly this change is just a trivial stop-gap attempt to mitigate the problem.  We need to fix this more thoroughly.

It may make sense to add some concept of a configurable `SyncThresholdBytes`, so the user can just configure the maximum amount of PROT_WRITE mmap_get() buffers that can be acquired before an offline is triggered, and have offline reset the PROT_WRITE counter.  This would give users some ability to control the amount of outstanding work that can be queued up before fsync occurs, limiting how long they take to complete.

Ideally we make the fsyncs asynchronous and it's less of a problem, but that's complicated.

edit:
sync_file_range() may be a useful alternative to msync w/MS_ASYNC, but the man page says it may still block if the amount of dirty pages in the range exceeds the request queue size.  Also note that initiating asynchronous writeback will cause more IO just like calling fsync() more often would.

**Comment by poettering** [comment]
I'd really prefer if we'd instead turn this into some logic where we sync either after certain number of bytes added or after a (long) timeout, whatever is reached earlier. The long timeout of 5min we have right now sounds good to me for this... Hence I'd rather not change it, but instead would love to see a patch that adds a counter of bytes written to each JournalFile and triggers a sync whenever it crosses a specific threshold.

And I am very conservative at adding user-configurable knobs, unless we really know they have a future and make a ton of sense. In this case using a constant threshold of syncing ever 16MB or so, sounds good enough...

**Comment by vcaputo** [comment]
Sounds reasonable to me, I'll put something together.

**Comment by keszybz** [comment]
It seems we have two semi-indendent things:
1. we need to sync the file to disk periodically to assure that in case of a system crash too much logs are not lost
2. we need to tell the flush the data we wrote to disk so that it doesn't buffer too much data and when we try to do 1. we have to wait too long.

For 1. the timeout of 5 min seems reasonable. For 2. we shouldn't use a timeout, that's too inflexible. Also I'm not sure if we want to do accounting like this. Why not `fadvise(FADV_DONTNEED)`?
(I guess we would call it for bigger chunks, maybe after writing an entry above above a certain size?).

I tried the following program:

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>

// compile with gcc -Wall -o madvise_test madvise_test.c
// run as  truncate -s100M file  && strace -ttt -T ./madvise_test file

int main(int argc, char **argv) {
    struct stat st = {};
    int fd = open(argv[1], O_RDWR, 00644);
    stat(argv[1], &st);

    char *buf = mmap(NULL, st.st_size,
             PROT_WRITE|PROT_READ, MAP_SHARED, fd, 0);

    printf("mmaped fd %d at 0x%p size %zu\n",
           fd, buf, st.st_size);
    char x = 'A' + (buf[0]-'A' + 1)%('Z'-'A');
    printf("writing %c's\n", x);
    memset(buf, x, st.st_size);
    // madvise(buf, st.st_size, MADV_DONTNEED);
    posix_fadvise(fd, 0, st.st_size, POSIX_FADV_DONTNEED);
    printf("sleeping\n");
    sleep(1);
    fdatasync(fd);
    return 0;
}
```

`madvise` indeed does nothing.
With `fadvise` I get the following:

```
1454989325.686082 fadvise64(3, 0, 104857600, POSIX_FADV_DONTNEED) = 0 <0.169437>
1454989325.855866 nanosleep({1, 0}, 0x7ffcadcb5cc0) = 0 <1.000273>
1454989326.856266 fdatasync(3)          = 0 <0.026109>
```

When I remove `fadvise` the time for `fdatasync` is at least 0.5 s, sometimes above 1.0. So `fadvise` seems to do the job as advertised.

**Pull request closed without merging**
