### PR TITLE
core: introduce a restart counter

### PR DESCRIPTION
**Pull request by poettering**
This adds a per-service restart counter. Each time an automatic
restart is scheduled (due to Restart=) it is increased by one. Its
current value is exposed over the bus as NRestarts=. It is also logged
(in a structured, recognizable way) on each restart.

Note that this really only counts automatic starts triggered by Restart=
(which it nicely complements). Manual restarts will reset the counter,
as will explicit calls to "systemctl reset-failed". It's supposed to be
a tool for measure the automatic restart feature, and nothing else.

Fixes: #4126

### CODE REVIEW

**Comment by davidstrauss** [comment]
Given that this is already designed to only track restarts triggered by failures, I think it would be better to have a counter for failures of the unit of *any sort* -- whether they trigger a restart or not. It would be particularly nice if it tracked failures based on the same categories that `Restart=` can automatically handle (signal, exit code, etc.).

A "counter by failure type" approach would be better for a few reasons:

 * `Restart=` isn't the only reason why a service might repeatedly start and then fail. Another service that starts on-demand could depend on it, or a configuration tool like Chef might start it (if not running) every hour.
 * It would help administrators and packagers choose the right `Restart=` setting based on the types of failures encountered.
 * It would avoid confusing users who might think that `NRestarts=` simply counts restarts.

**Comment by poettering** [comment]
@davidstrauss i am pretty sure having a counter that counts all restarts would make sense too, but i think that should be an orthogonal thing independent of this patch, as it requires a systematically different approach.

Specifically: this is a runtime counter that isn't maintained on storage but purely in memory. And that works only as long as the unit isn't unloaded in the middle and thus this data lost, for example due to the GC logic. If we'd maintain a runtime counter that would count all kinds of starts, then this would conflict with the GC logic: if the counter is non-zero we couldn't unload a unit anymore, because then we'd forget the current counter's value.

Hence, implementing a more comprehensive start counter would mean storing things to disk, to keep things scalabale, and the place for that would be the journal i figure, and in a way we have all necessary bits in place there already: we could simply count the log messages reporting a start operation for the unit. Of course, this wouldn't really scale, as counting matching lines grows with the number of them, and gets corrupted by rotation... If we don't use the journal however, then things would start becoming nasty, as we'd have to come up with a new storage concept, and then deal with garbage collection it for old units and so on. And at that point I figured a more minimal option that is independent of all of this, that we can deliver now, and nicely augments the existing Restart= concept would be the better option for now...

Hence, I am not denying that a more comprehensive start counter (as opposed to a more limited restart counter this PR adds) makes sense, and I am all for adding that too, but I think it is quite a bit harder to implement properly, involving non-trivial new infrastructure, that needs a log of extra designing...

Hence, let's focus on something simple for now, and maybe later go for the more complex option, too.

**Comment by davidstrauss** [comment]
> Specifically: this is a runtime counter that isn't maintained on storage but purely in memory.

I'm not actually asking for anything more durable than the current boot. I'm just saying that services could easily go through:

1. 13:00 Chef starts the service.
2. 13:50 The service fails.
3. 14:00 Chef starts the service.
4. Over and over...

Tools like Sensu also offer remediation when they detect failure, and that would also be invisible with the proposed `NRestarts=` design.

What I am saying is that would be useful to see a counter of failures for a unit (for the current boot) climb even if there is no `Restart=` configured for the service.

Instead of `NRestarts=`, it would be counters like:

* `NFailureUncleanExit=`
* `NFailureUncleanSignal=`
* `NFailureTimeout=`
* `NFailureWatchdog=`

And the appropriate counter would be incremented regardless of whether the failure triggers PID 1 to restart the service. Like the proposal for `NRestarts=`, they would reset on `reset-failed`, on manual interaction via `systemctl`, and (because it's only in memory) on reboots.

If I have a configuration for `Restart=` on a service, I can use the failure counters in the bullets above to determine how many times it would have restarted, anyway.

**Comment by poettering** [comment]
> What I am saying is that would be useful to see a counter of failures for a unit (for the current boot) climb even if there is no Restart= configured for the service.

I am sure that would be useful, but again: any such scheme would mean we couldn't GC the unit from memory anymore! If we unload a unit we forget everything about it that hasn't been logged to disk. Hence, any counter that wants to remain valid even when a unit is stopped and no job for it is queued would mean that it would have to pin the unit into memory, and that's something I really don't like!

systemd is built so that you can have transient units and instance units, as well as units that are automatically synthesized from external objects, such as mount points or udev devices. All these units are very likely just active once for a short time and then never seen again, if we'd now stop GC'ing them altogether, just because the start counters for each of them that was ever started is 1, then the amount of units we'd have to keep in memory would grow without bounds.

Hence, the Restart counter this patch implements binds itself to the Restart= setting, as the unit is guaranteed to remain in memory as long as Restart= is set, and hence the counter can be maintained at no cost, and does not interfere with GC'ing!

Counters that are supposed to persist through units being fully shut down either imply pinning of units in memory or disk-level storage. And the pinning is really not an option, and the disk-level storage is hard, since then you'd have to come up with rotation and stuff too, because while we can grow the data on disk much larger than in memory we still have to put limits on it eventually...

So again, I don't doubt having persistent counters make sense, and would be useful, but the implementation comes with implications that make them much much more complex to implement.

Does that make sense?

**Comment by davidstrauss** [comment]
Okay, I see what you mean now in terms of the lifecycle of counter state. With that in mind, I agree that the current proposal is probably as good as it gets without major changes there.

**Comment by poettering** [comment]
I force pushed a new, rebased version now. Would be very thankful for a review!

**Comment by davidstrauss** [comment]
Looks good to me!

**Comment by poettering** [comment]
thanks for having a look!

**Pull request merged**
