### PR TITLE
ci: build with clang-13

### PR DESCRIPTION
**Pull request by mrc0mmand**
Also, drop clang-10 builds to conserve resources.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Filed as https://bugs.llvm.org/show_bug.cgi?id=51865.

**Comment by yuwata** [comment]
Haha, so many `_unused_` variables. Nice!

**Comment by mrc0mmand** [comment]
> Haha, so many `_unused_` variables. Nice!

Hehe, yeah. I ran a local build with clang-13 and hopefully got them all (all of them seem to be indeed "unused" - either intentionally, or only used from a cleanup handler). Let's see if CIs agree with me.

**Comment by mrc0mmand** [comment]
I singled-out the last case CI was complaining about, since there the variable is actually used, but only when compiled with `-Db_ndebug=false` (where we expand `assert()` macros). It feels a bit iffy, but we've already done similar thing in the past (dfa64b64a7e2b9bffea260953b30e6236047fffb), so I guess it's a way to go.

**Comment by mrc0mmand** [comment]
Looks like the build test is finally happy as well, @yuwata, @poettering PTAL.

**Review by yuwata — APPROVED** [review]
LGTM.

**Pull request merged**
