### PR TITLE
Re-realize devices before forking

### PR DESCRIPTION
**Pull request by iainlane**
This is for #14322.

The change works for me¹, but I'm not really confident on it. I don't particularly understand the cgroup stuff yet. I'm not sure if any other unit types need to have the same treatment. Feel free to guide me if you want, but if it's easier then I don't mind someone else just directly fixing the PR.

¹but I couldn't get `mkosi` to work on my Ubuntu host, so it's not fully tested locally; will be relying on CI

### CODE REVIEW

**Comment by yuwata** [comment]
Hmm. It seems that `networkd` does not like this...

**Comment by iainlane** [comment]
@yuwata In what way? Can you point me to something?

CI seems OK; the arm64 failure appears to be:

```
418/773 test-journal-flush                      FAIL     0.63 s (killed by signal 6 SIGABRT)

--- command ---
PATH='/tmp/autopkgtest.ATWeei/build.y6d/systemd/build-deb:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games' SYSTEMD_LANGUAGE_FALLBACK_MAP='/tmp/autopkgtest.ATWeei/build.y6d/systemd/src/locale/language-fallback-map' SYSTEMD_KBD_MODEL_MAP='/tmp/autopkgtest.ATWeei/build.y6d/systemd/src/locale/kbd-model-map' /tmp/autopkgtest.ATWeei/build.y6d/systemd/build-deb/test-journal-flush
--- stderr ---
journal_file_copy_entry failed: Bad message
Assertion 'r >= 0' failed at src/journal/test-journal-flush.c:52, function main(). Aborting.
-------
```

which smells like flakiness?

The CentOS ones return 404s for me.

**Comment by yuwata** [comment]
> The CentOS ones return 404s for me.

Hmm. @mrc0mmand? When I see the CentOS CI failure, networkd tests failed.

**Comment by mrc0mmand** [comment]
> > The CentOS ones return 404s for me.
> 
> Hmm. @mrc0mmand? When I see the CentOS CI failure, networkd tests failed.

Sigh, I'm afraid the logs for this job fell victim of the recent out-of-space situation on the Jenkins master in CentOS CI. As the jobs don't exist anymore, the only solution here is a force push. Sorry!

**Comment by iainlane** [comment]
hmm yeah OK I see networkd failing there now:

> Dec 17 10:07:23 n42.crusty.ci.centos.org systemd[543937]: systemd-networkd.service: Failed to set up standard input: Operation not permitted
> Dec 17 10:07:23 n42.crusty.ci.centos.org systemd[543937]: systemd-networkd.service: Failed at step STDIN spawning /usr/lib/systemd/systemd-networkd: Operation not permitted

and that does look related to this MR of course. But it works in my test VM - I thought it might be flaky since 81 tests passed, but I've been restarting networkd in a loop for hours now and it's never failed.

so, hints would be appreciated! Could it be that I've created a race here because `unit_invalidate_cgroup_bpf_devices()` is adding to the queue and not realizing *now*?

**Comment by keszybz** [comment]
Both changes look reasonable, but I think we need to figure out the Jendkins failure before merging.

**Comment by poettering** [comment]
hmm, on cgroupsv1 we cannot replace the cgroup devices list up atomically which is probably the cause of the CI failure (i.e. it is set up step by step). on cgroupsv2 we can. shite. Not sure what the best approach is

**Comment by iainlane** [comment]
ah HMM, this sucks

I guess I can see two different approaches to the original bug then

  * Add a new Requires/Before unit to logind to do the modprobe
  * Invent a new `LoadModule=` stanza which is executed early enough to avoid this bug, i.e. add support for the modprobing directly into systemd

wdyt?

**Comment by iainlane** [comment]
This'll be obsolete now with #14504

**Pull request closed without merging**
