### PR TITLE
Allow dots in usernames

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
I am really not a fan of this. The fact is that there's ambiguity about what "." means when you do a chown. i.e. "chown foo.bar x" has a very different effect on systems that have a user "foo.bar" compared to those which have only a user "foo" and group "bar".

I am very sure we should retain compat with such users in subsystems such as logind, i.e. where we'd actively would break stuff that worked before logind by refusing them. However, for stuff where our infrastructure is used to *register* new users with such a questionable, ambiguous spelling in the NSS, and where we are the ones introducing new functionality, we should refuse right away, and not make our tools a vehicle to amplify the problem. It will help in the long run. Or in other words: I really don't see the benefit of making DynamicUser= work with such user names because it *never* worked before as there simply was no concept of DynamicUser= before.

If people want to make use of DynamicUser= then they have to adjust their stuff anyway a bit (i.e. at the very least it needs to be added to the service file, but usually more since the semantics are very constrained), and I am very sure that the requirement not to use a dot in the username is not too much to ask.

**Comment by poettering** [comment]
In particularly I really don't like the complexity this adds, by adding multiple codepaths to checking validity. For what preicsely?

**Comment by keszybz** [comment]
> Or in other words: I really don't see the benefit of making DynamicUser= work

DynamicUsers are explicitly excluded from this change. It is even mentioned in the patch description.

> I am very sure we should retain compat with such users in subsystems such as logind, i.e. where we'd actively would break stuff that worked before logind by refusing them. However, for stuff where our infrastructure is used to register new users with such a questionable, ambiguous spelling in the NSS, and where we are the ones introducing new functionality, we should refuse right away

I agree, we should not allow creation of such users through our interfaces and we should not allow use of such users in new stuff. I'll change the PR to also disallow this in sysusers too.

> In particularly I really don't like the complexity this adds, by adding multiple codepaths to checking validity. For what preicsely?

The general motivation is that people *do* have systems with such users. Such users are well supported by existing tools. Apparently there are places which have systems with lots of such users and it's hard for them to switch away.

**Comment by keszybz** [comment]
Updated. I now reverted the logic: the default is to be strict, and _compat() functions are added and used in specific places. PTAL.

**Comment by wiad** [comment]
As one of those sysadmins with hundreds of application usernames with dots in them (.u for dev and .t for testing) this would be immensely helpful in our migration effort from rhel7 to rhel8 (granted that red hat would backport it which I really think they would)

**Comment by keszybz** [comment]
After talking this over with @poettering, this is OK to merge, but a warning should be emitted. I now pushed a commit to add a `log_warning` for each name with a dot.

**Comment by yuwata** [comment]
LGTM.

**Pull request merged**
