### PR TITLE
test PR to figure out the long double JSON issues on ppc64le

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by poettering** [comment]
btw, i figure this has something to do with this:

https://fedoraproject.org/wiki/Changes/PPC64LE_Float128_Transition

**Comment by yuwata** [comment]
Hmm?? Memory is corrupted?
```
/* test_float */
value 10 is integer: yes
value 10 as double: 10
value 10 as integer: 10
value 10 as doubleâ†’integerâ†’double: 10
value 10 conversion same: yes
value -10 is integer: yes
value -10 as double: -10
value -10 as integer: -10
value -10 as doubleâ†’integerâ†’double: -10
value -10 conversion same: yes
size of float: 4
size of double: 8
size of long double: 16
Assertion 'json_variant_is_real(json_variant_by_index(v, 7)) && json_variant_is_integer(json_variant_by_index(v, 7)) && json_variant_integer(json_variant_by_index(v, 7)) == 10' failed at src/test/test-json.c:540, function test_float_match(). Aborting.
```

**Comment by mrc0mmand** [comment]
I did some more investigation:

```diff
diff --git a/src/test/test-json.c b/src/test/test-json.c
index 05adc68fe5..864d015f64 100644
--- a/src/test/test-json.c
+++ b/src/test/test-json.c
@@ -538,6 +538,11 @@ static void test_float_match(JsonVariant *v) {
         assert_se(json_variant_is_integer(json_variant_by_index(v, 6)));
         assert_se(json_variant_integer(json_variant_by_index(v, 6)) == 0);
         assert_se(json_variant_is_real(json_variant_by_index(v, 7)));
+
+        log_info("%s: value 10 is integer: %s", __func__, yes_no(json_variant_is_integer(json_variant_by_index(v, 7))));
+        log_info("%s: value 10 is real: %s", __func__, yes_no(json_variant_is_real(json_variant_by_index(v, 7))));
+        log_info("%s: value 10 as double: %Lg", __func__, json_variant_real(json_variant_by_index(v, 7)));
+        log_info("%s: value 10 as integer: %ji", __func__, json_variant_integer(json_variant_by_index(v, 7)));
         assert_se(json_variant_is_integer(json_variant_by_index(v, 7)));
         assert_se(json_variant_integer(json_variant_by_index(v, 7)) == 10);
         assert_se(json_variant_is_real(json_variant_by_index(v, 8)));
```

```
test_float_match: value 10 is integer: no
test_float_match: value 10 is real: yes
test_float_match: value 10 as double: 10
Real 10 requested as integer, and cannot be converted losslessly, returning 0.
test_float_match: value 10 as integer: 0
Assertion 'json_variant_is_integer(json_variant_by_index(v, 7))' failed at src/test/test-json.c:546, function void test_float_match(JsonVariant *)(). Aborting.
Aborted (core dumped)
```

**Comment by mrc0mmand** [comment]
Apparently the issue happens after:

```c
        assert_se(json_variant_format(v, 0, &text) >= 0);
        assert_se(json_parse(text, 0, &w, NULL, NULL) >= 0);
```

a bit lower in the code. Because running

```c
        assert_se(json_variant_format(v, 0, &text) >= 0);
        assert_se(json_parse(text, 0, &w, NULL, NULL) >= 0);
        assert(10.0 == json_variant_real(json_variant_by_index(v, 7)));
        assert(10.0 == json_variant_real(json_variant_by_index(w, 7)));
```

yields

```
Assertion '10.0 == json_variant_real(json_variant_by_index(w, 7))' failed at src/test/test-json.c:185, function test_float(). Aborting.
Aborted (core dumped)
```

Which is weird, since
```
(v) x.boolean: 0
(v) x.real: 10
(v) x.integer: 4621819117588971520
(v) x.unsig: 4621819117588971520

(w) y.boolean: 0
(w) y.real: 10
(w) y.integer: 4621819117588971520
(w) y.unsig: 4621819117588971520
```

I guess there's some issue with the internal representation after we dump&parse the data to/from text?

**Comment by mrc0mmand** [comment]
*sigh*

```
(v) x.boolean: 0
(v) x.real: 1.0000000000000000000000000000000000E+01
(v) x.integer: 4621819117588971520
(v) x.unsig: 4621819117588971520

(w) y.boolean: 0
(w) y.real: 1.0000000000000000000000000000000000E+01
(w) y.integer: 4621819117588971520
(w) y.unsig: 4621819117588971520
Assertion 'x->value.real == y->value.real' failed at src/test/test-json.c:190, function test_float(). Aborting.
Aborted (core dumped)
```

**Comment by mrc0mmand** [comment]
Also:

```
(v) x.boolean: 0
(v) x.real: 1.0000000000000000000000000000000000E+01
(v) x.integer: 4621819117588971520
(v) x.unsig: 4621819117588971520

(w) y.boolean: 0
(w) y.real: 1.0000000000000000000000000000000000E+01
(w) y.integer: 4621819117588971520
(w) y.unsig: 4621819117588971520

10.0 - x.real: 0.0000000000000000000000000000000000E+00
10.0 - y.real: -9.8607613152626475676466070660348279E-32
y.real - x.real: -9.8607613152626475676466070660348279E-32
```

**Comment by mrc0mmand** [comment]
Also, after adding some output around

https://github.com/systemd/systemd/blob/0da6973c17406f8ae222725e5d1ddd2f7d1c3b1e/src/shared/json.c#L2621-L2623

it shows it's indeed some precision-related shenanigans:

```
json_parse_number: 2.225073858507201383090232717332404e-308 parsed as: 2.22507385850720237122152439982549E-308
json_parse_number: (parsed) - 10.0: -1.00000000000000000000000000000000E+01
json_parse_number: 1.797693134862315708145274237317044e+308 parsed as: 1.79769313486231570814527423731700E+308
json_parse_number: (parsed) - 10.0: 1.79769313486231570814527423731700E+308
json_parse_number: 0.000000000000000000000000000000000e+00 parsed as: 0.00000000000000000000000000000000E+00
json_parse_number: (parsed) - 10.0: -1.00000000000000000000000000000000E+01
json_parse_number: 1.000000000000000000000000000000000e+01 parsed as: 1.00000000000000000000000000000000E+01
json_parse_number: (parsed) - 10.0: 9.86076131526264756764660706603483E-32
json_parse_number: -1.000000000000000000000000000000000e+01 parsed as: -1.00000000000000000000000000000000E+01
json_parse_number: (parsed) - 10.0: -2.00000000000000000000000000000000E+01
```

but apart from adding printf's to various parts of the code, I'm not sure what should be the next steps.

**Comment by mrc0mmand** [comment]
There's a significant difference with and without `-ffast-math`:

**WITH** `-ffast-math` (i.e. with reverted 394ac84df9ecc1556b922c1161503ef74962fe6a):
```
/* test_float */
value 10 is integer: yes
value 10 as double: 10
value 10 as integer: 10
value 10 as double→integer→double: 10
value 10 conversion same: yes
value -10 is integer: yes
value -10 as double: -10
value -10 as integer: -10
value -10 as double→integer→double: -10
value -10 conversion same: yes
size of float: 4
size of double: 8
size of long double: 16
[
	2.225073858507201383090232717332404e-308,
	1.797693134862315708145274237317044e+308,
	nan,
	inf,
	-inf,
	inf,
	0.000000000000000000000000000000000e+00,
	1.000000000000000000000000000000000e+01,
	-1.000000000000000000000000000000000e+01
]
Assertion 'json_variant_is_null(json_variant_by_index(v, 2))' failed at src/test/test-json.c:532, function test_float_match(). Aborting.
Aborted (core dumped)
```

**WITHOUT** `-ffast-math`:
```
/* test_float */
value 10 is integer: yes
value 10 as double: 10
value 10 as integer: 10
value 10 as double→integer→double: 10
value 10 conversion same: yes
value -10 is integer: yes
value -10 as double: -10
value -10 as integer: -10
value -10 as double→integer→double: -10
value -10 conversion same: yes
size of float: 4
size of double: 8
size of long double: 16
[
	2.225073858507201383090232717332404e-308,
	1.797693134862315708145274237317044e+308,
	null,
	null,
	null,
	null,
	0.000000000000000000000000000000000e+00,
	1.000000000000000000000000000000000e+01,
	-1.000000000000000000000000000000000e+01
]
[
	2.225073858507202371221524399825492e-308,
	1.797693134862315708145274237316999e+308,
	null,
	null,
	null,
	null,
	0.000000000000000000000000000000000e+00,
	1.000000000000000000000000000000000e+01,
	-1.000000000000000000000000000000000e+01
]
Assertion 'json_variant_is_integer(json_variant_by_index(v, 7))' failed at src/test/test-json.c:541, function test_float_match(). Aborting.
Aborted (core dumped)
```

**Comment by mrc0mmand** [comment]
Closing in favor of #21424.

**Pull request closed without merging**
