### PR TITLE
test-network: check port range and ipproto attributs are supported by kernel and ip command

### PR DESCRIPTION
**Pull request by yuwata**
Not tested, but hopefully fixes all failures in test-network.

cc @ssahani and @mrc0mmand.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Thanks for the patch! After giving it a quick run there's still one failing test:

```
<snip>
test_routing_policy_rule_invert (__main__.NetworkdNetWorkTests) ... 
0:	from all lookup local 
111:	not from 192.168.100.18 tos throughput lookup 7 
32766:	from all lookup main 
32767:	from all lookup default
FAIL
<snip>
======================================================================
FAIL: test_routing_policy_rule_invert (__main__.NetworkdNetWorkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./systemd-networkd-tests.py", line 707, in test_routing_policy_rule_invert
    self.assertRegex(output, 'tcp')
AssertionError: Regex didn't match: 'tcp' not found in '0:\tfrom all lookup local \n111:\tnot from 192.168.100.18 tos throughput look'

----------------------------------------------------------------------
Ran 69 tests in 743.502s

FAILED (failures=1, expected failures=6)
```

**Comment by yuwata** [comment]
@mrc0mmand Thank you for testing. Please test again.

**Comment by mrc0mmand** [comment]
```
----------------------------------------------------------------------
Ran 69 tests in 743.197s

OK (expected failures=7)
```

Looks like all failures have been fixed, thank you!

**Comment by yuwata** [comment]
Yey! Thank you for testing so many times.

**Comment by ssahani** [comment]
LGTM

**Pull request merged**
