### PR TITLE
travis: also build systemd with clang

### PR DESCRIPTION
**Pull request by evverx**

### CODE REVIEW

**Comment by evverx** [comment]
This PR will be ready to roll as soon as the warnings mentioned in https://github.com/systemd/systemd/pull/10948#discussion_r238037112 has been fixed.

**Comment by ssahani** [comment]
How do I push to your branch. It gives me 
```
remote: Permission to evverx/systemd.git denied to ssahani.
fatal: unable to access 'https://github.com/evverx/systemd/': The requested URL returned error: 403
```

https://github.com/ssahani/systemd/commit/49a456423974f0210b98dbf2825c802ed3c651b3

**Comment by evverx** [comment]
Another option would be to wait for me until Monday when I get my laptop.

By the way, I thought it would be better to use `PRIu16` there instead of `hu` in the sense that `PRIu16` seems to make it a little bit clearer that what is printed is basically an unsigned 16-bit value.

**Comment by ssahani** [comment]
> PRIu16

Done @evverx thanks for the suggestion.

**Comment by evverx** [comment]
I used my phone to juggle the commits (which was a very strange experience :-) Everything should be fine now.

**Comment by ssahani** [comment]
Awesome

**Comment by evverx** [comment]
Let't merge it while TravisCI is still green.

**Comment by yuwata** [comment]
@evverx and @ssahani Sorry for late response. LGTM.

**Comment by evverx** [comment]
@yuwata no problem. Actually, I'm glad you didn't take part in the mess I made here.

`clang` strikes again in https://github.com/systemd/systemd/pull/11025 :-)

**Pull request merged**
