### PR TITLE
nss-systemd: fix pointer calculation

### LINKED ISSUE #21935: SIGBUS on SPARC caused by NSS lookups
**systemd version the issue has been seen with**
>Known good versions:
>- sys-apps/systemd-249.4-r4 (but not recompiled it yet)
>
>Known bad versions:
>- sys-apps/systemd-249.6-r1
>- sys-apps/systemd-249.7
>- sys-apps/systemd-250-r1

**Used distribution**
 > Gentoo Linux.

**Linux kernel version used** (`uname -a`)

 > `5.15.5-gentoo`

**CPU architecture issue was seen on**
 > sparc64

**Expected behaviour you didn't see**
 > Commands which end up involving NSS lookups like `ls -al` succeeding.

**Unexpected behaviour you saw**
 > SIGBUS on `ls -al`, `sudo su`.

**Steps to reproduce the problem**
 > 1. Install >sys-apps/systemd-249.4 on a `sparc64` machine
 > 2. Have systemd configured for NSS lookups in `/etc/nsswitch.conf`
 > 3. Try to run `ls -al` or some other command which will need to lookup entries via NSS

**Additional program output to the terminal or log subsystem illustrating the issue**

Originally reported downstream in Gentoo [here](https://bugs.gentoo.org/830275).

```
$ sudo su
Bus error (core dumped)
```

```
$ ls -al
Bus error (core dumped)
```

Backtrace:
```
(gdb) bt
#0  copy_synthesized_group (dest=0xfff800010049bf90 <resbuf>, src=0xfff8000100706b08 <root_group>, buffer=0x100001382a0 "root", buflen=1024, errnop=0xfff800010002fbd8)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:254
#1  0xfff80001005b6730 in _nss_systemd_getgrgid_r (gid=<optimized out>, gr=0xfff800010049bf90 <resbuf>, buffer=0x100001382a0 "root", buflen=1024, errnop=0xfff800010002fbd8)
    at ../systemd-250/src/nss-systemd/nss-systemd.c:498
#2  0xfff80001002f1f54 in __getgrgid_r (gid=<optimized out>, resbuf=0xfff800010049bf90 <resbuf>, buffer=0x100001382a0 "root", buflen=1024, result=0x7fefff207e0) at ../nss/getXXbyYY_r.c:274
#3  0xfff80001002f150c in getgrgid (gid=<optimized out>) at ../nss/getXXbyYY.c:135
#4  0x0000010000012d3c in getgroup (gid=<optimized out>) at lib/idcache.c:167
#5  0x000001000000dc84 in format_group_width (g=0) at src/ls.c:4183
#6  gobble_file (name=0x1000012f623 "glibc-2.30-r9.ebuild", type=<optimized out>, command_line_arg=<optimized out>, dirname=<optimized out>, inode=0) at src/ls.c:3534
#7  0x000001000000e484 in print_dir (name=0x100001276e0 ".", realname=<optimized out>, command_line_arg=<optimized out>) at src/ls.c:2989
#8  0x00000100000046e4 in main (argc=<optimized out>, argv=<optimized out>) at src/ls.c:1778
(gdb)
```

Note that the machine is running glibc-2.33 and the 2.30 reference in the backtrace is just because there's a bunch of glibc ebuilds (=filenames) in the directory I was in.

I don't think there was anything else related/useful in the journal.

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for 1e65eb8f9b7d567462030b2e625998d77677e636.

Fixes #21935.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
```
ESC[31mFAIL: test-nss-usersESC[0m
======== systemd ========
_nss_systemd_getpwnam_r("root") → status=NSS_STATUS_SUCCESS
                   errno=999/---
        "root" / 0:0
        passwd="x"
        gecos="Super User"
        dir="/root"
        shell="/bin/sh"
_nss_systemd_getgrnam_r("root") → status=NSS_STATUS_SUCCESS
                   errno=999/---
        "root" / 0
        passwd="x"
        members=
_nss_systemd_getpwnam_r("nobody") → status=NSS_STATUS_SUCCESS
                   errno=999/---
        "nobody" / 65534:65534
        passwd="!*"
        gecos="User Nobody"
        dir="/"
        shell="/usr/sbin/nologin"
_nss_systemd_getgrnam_r("nobody") → status=NSS_STATUS_NOTFOUND
                   errno=999/---
_nss_systemd_getpwnam_r("foo_no_such_user") → status=NSS_STATUS_NOTFOUND
                   errno=999/---
_nss_systemd_getgrnam_r("foo_no_such_user") → status=NSS_STATUS_NOTFOUND
                   errno=999/---
_nss_systemd_getpwnam_r("0") → status=NSS_STATUS_NOTFOUND
                   errno=999/---
_nss_systemd_getgrnam_r("0") → status=NSS_STATUS_NOTFOUND
                   errno=999/---
_nss_systemd_getpwnam_r("65534") → status=NSS_STATUS_NOTFOUND
                   errno=999/---
_nss_systemd_getgrnam_r("65534") → status=NSS_STATUS_NOTFOUND
                   errno=999/---
_nss_systemd_getpwuid_r(0) → status=NSS_STATUS_SUCCESS
                   errno=999/---
        "root" / 0:0
        passwd="x"
        gecos="Super User"
        dir="/root"
        shell="/bin/sh"
_nss_systemd_getgrgid_r(0) → status=NSS_STATUS_SUCCESS
                   errno=999/---
        "root" / 0
        passwd="x"
        members=
_nss_systemd_getpwuid_r(65534) → status=NSS_STATUS_SUCCESS
                   errno=999/---
        "nobody" / 65534:65534
        passwd="!*"
        gecos="User Nobody"
        dir="/"
        shell="/usr/sbin/nologin"
_nss_systemd_getgrgid_r(65534) → status=NSS_STATUS_SUCCESS
                   errno=999/---
        "nogroup" / 65534
        passwd="!*"
        members=
 
======== mymachines ========
Failed to load module mymachines: libnss_mymachines.so.2: cannot open shared object file: No such file or directory
```

**Comment by Arfrever** [comment]
> ```
> ESC[31mFAIL: test-nss-usersESC[0m
> ...
> ======== mymachines ========
> Failed to load module mymachines: libnss_mymachines.so.2: cannot open shared object file: No such file or directory
> ```

While this ideally would need fixing (probably in #21946), the same `libnss_mymachines.so.2: cannot open shared object file: No such file or directory` failure most likely happens both without and with this patchset (#21944).

**Comment by evverx** [comment]
> ESC[31mFAIL: test-nss-usersESC[0m

I'm pretty sure it has nothing with this patch. The systemd autopkgtest should be fixed instead. In https://github.com/systemd/systemd/pull/21778 I "fixed" it by skipping that test on Ubuntu CI/Semaphore CI with
```
To make the nss tests work various libnss_* packages should be
listed among the "unit-tests" dependencies in
https://salsa.debian.org/systemd-team/systemd/-/blob/upstream-ci/debian/tests/control

Currently only libnss-systemd is installed there to judge from
https://autopkgtest.ubuntu.com/results/autopkgtest-focal-upstream-systemd-ci-systemd-ci/focal/amd64/s/systemd-upstream/20211231_014851_745d6@/log.gz

autopkgtest [00:52:42]: test unit-tests: preparing testbed
Get:1 file:/tmp/autopkgtest.1eS7IS/binaries  InRelease
Ign:1 file:/tmp/autopkgtest.1eS7IS/binaries  InRelease
Get:2 file:/tmp/autopkgtest.1eS7IS/binaries  Release [816 B]
Get:2 file:/tmp/autopkgtest.1eS7IS/binaries  Release [816 B]
Get:3 file:/tmp/autopkgtest.1eS7IS/binaries  Release.gpg
Ign:3 file:/tmp/autopkgtest.1eS7IS/binaries  Release.gpg
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
0 upgraded, 0 newly installed, 9 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/11.0 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 file:/tmp/autopkgtest.1eS7IS/binaries  libsystemd0 250.85.g765d4da642.0 [405 kB]
Get:2 file:/tmp/autopkgtest.1eS7IS/binaries  systemd-timesyncd 250.85.g765d4da642.0 [135 kB]
Get:3 file:/tmp/autopkgtest.1eS7IS/binaries  systemd 250.85.g765d4da642.0 [4502 kB]
Get:4 file:/tmp/autopkgtest.1eS7IS/binaries  systemd-sysv 250.85.g765d4da642.0 [116 kB]
Get:5 file:/tmp/autopkgtest.1eS7IS/binaries  libudev1 250.85.g765d4da642.0 [185 kB]
Get:6 file:/tmp/autopkgtest.1eS7IS/binaries  udev 250.85.g765d4da642.0 [1591 kB]
Get:7 file:/tmp/autopkgtest.1eS7IS/binaries  libnss-systemd 250.85.g765d4da642.0 [254 kB]
Get:8 file:/tmp/autopkgtest.1eS7IS/binaries  libpam-systemd 250.85.g765d4da642.0 [312 kB]
Get:9 file:/tmp/autopkgtest.1eS7IS/binaries  systemd-tests 250.85.g765d4da642.0 [3476 kB]
```

**Comment by evverx** [comment]
Apparently `test/TEST-02-UNITTESTS/deny-list-ubuntu-ci` can't be used to skip the "unit tests" test on Ubuntu CI/Semaphore CI. I'm not sure why it's still there though considering the "upstream" test basically includes the "unit tests" test.

**Comment by bluca** [comment]
I don't remember seeing this fail before, and it seems too unlucky for a coincidence - I've restarted the job, let's see what happens

**Comment by evverx** [comment]
As far as I can tell @yuwata temporarily included https://github.com/systemd/systemd/pull/21946 in this PR and it seems that test failed because of that. Currently those tests are "manual" and shouldn't be run by the CI.

>  it seems too unlucky for a coincidence

Agreed.

**Comment by yuwata** [comment]
Yeah, the error should not be related to this. I guess there is some confusion in the CI environment caused when I dropped the commit about enabling the tests by default.

**Comment by yuwata** [comment]
Yay. All green! Merging.

**Comment by evverx** [comment]
It would be great to fix the "unit tests" test on Ubuntu CI though to make it possible to run the nss tests there though. It should unblock https://github.com/systemd/systemd/pull/21946

**Pull request merged**
