### PR TITLE
seccomp: minor seccomp syscall sets cleanups 

### PR DESCRIPTION
**Pull request by tixxdz**

### CODE REVIEW

**Comment by tixxdz** [comment]
Forget to mention that the 'gettid' syscall is already in the '@default' syscall set.

**Comment by poettering** [comment]
hmm, are you sure about the first patch? isn't setgid() allowed for unprivileged processes if the specified group is in the aux group set? You patch would make that a `@privileged` operation, but it isn't currently...

second patch looks good though

**Comment by keszybz** [comment]
@tixxdz ping

**Comment by tixxdz** [comment]
@poettering @keszybz indeed, changing real to effective uids and back is allowed, we may complicate different use cases with such patch, drop it for now. Better define maybe for later something abstracted that blocks these syscalls and can coupled with no_new_privs bit, etc.

Anyway pushed now, thank you for the catch!

**Comment by poettering** [comment]
> @poettering @keszybz indeed, changing real to effective uids and back is allowed, we may complicate different use cases with such patch, drop it for now.

Well, that's not what I meant really. I think it's fine to consider fiddling with the real/effective/saved UID a privileged concept, even if you can create setups where you don't have to be root to do it. It's still a privileges game, you are playing there, that you can't do with very special setup (i.e. setuid bits on files). 

What i was concerned about is the supplementary group list. IIRC you can setgid() to any gid included in your supplementary group list, or am I wrong? And that's a case that is pretty regular, as users tend to be members of multiple groups quite often..

**Comment by tixxdz** [comment]
@poettering the supplementary list is usually for ACL access, for setgid and others it works only if the value provided matches current rgid or egid if not privileged, otherwise any arbitrary value.

**Comment by poettering** [comment]
@tixxdz are you saying that setgid() on a GID in my supplementary GIDs list will still fail with EPERM?

if so, then I figure that part of the patch is actually OK to go in, too

**Comment by tixxdz** [comment]
@poettering yes for setgid() if the passed value is not the current rgid then it will fail if the calling process does not have the appropriate privileged capability, and for other setregid() variants the passed value needs to be either real, effective or at least saved gid if not privileged, otherwise it will fail. So using other values from supplementary GIDs list will fail with EPERM.

Ok it was better to do the release without that patch, so we can think more about it.

Ultimately I see the '@privileged' syscall set as a collection of something like:
Reboot, load modules or load new system features, sysctl, change privileges etc. Depending on what the users want and as discussed in your comment on mutating seccomp https://github.com/systemd/systemd/pull/6963#issuecomment-333592208 and mine https://github.com/systemd/systemd/pull/6963#issuecomment-333662789  the '@privileged' group can be constructed dynamically based on what users want from a higher perspective.

**Pull request merged**
