### PR TITLE
use __fsetlocking() to turn off thread locking in STDIO where applicable

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by yuwata** [comment]
lgtm. needs to be rebased.

**Comment by poettering** [comment]
force pushed a new, rebased version. No other changes.

**Comment by yuwata** [comment]
Sorry, needs to rebase again...

**Comment by poettering** [comment]
Force pushed another version!

**Comment by yuwata** [comment]
Thanks.

**Comment by poettering** [comment]
KVM errors in the CI. Merging.

**Pull request merged**
