### PR TITLE
Change license of code examples in docs to MIT-0

### PR DESCRIPTION
**Pull request by keszybz**
Quoting Richard Fontana in [1]:

  CC0 has been listed by Fedora as a 'good' license for code and content
  (corresponding to allowed and allowed-content under the new system). We plan
  to classify CC0 as allowed-content only, so that CC0 would no longer be
  allowed for code.

  Over a long period of time a consensus has been building in FOSS that
  licenses that preclude any form of patent licensing or patent forbearance
  cannot be considered FOSS. CC0 has a clause that says: "No trademark or
  patent rights held by Affirmer are waived, abandoned, surrendered, licensed
  or otherwise affected by this document." (The trademark side of that clause
  is nonproblematic from a FOSS licensing norms standpoint.) The regular
  Creative Commons licenses have similar clauses.

For the case of our documentation snippets, patent issues do not matter much.
But it is always nicer to have a license that is considerred acceptable without
any further considerations. So let's change the license to the (now recommended
replacement) MIT-0.

[1] https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/NO7KGDNL5GX3KCB7T3XTGFA3QPSUJA6R/

@poettering 
@teg 
@bluca 
~~@keszybz~~
@tmuehlbacher 
@DaanDeMeyer 
@martinpitt 
@yuwata 
@elmarco 

Please give your acks. Effectively, this changes the license from one non-attribution to another non-attribution license, but drops the explicit trademark and license grant exclusion.

### CODE REVIEW

**Comment by elmarco** [comment]
Acked-by: Marc-André Lureau <marcandre.lureau@redhat.com>

**Comment by martinpitt** [comment]
Ack from me, Martin Pitt mpitt /at/ redhat.com, possibly also still from martin.pitt /at ubuntu.com. Thanks!

**Comment by teg** [comment]
acked-by: teg@jklm.no / tgunders@redhat.com

**Comment by yuwata** [comment]
ACK.

**Review by bluca — APPROVED** [review]
ack

**Comment by poettering** [comment]
ack

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by tmuehlbacher** [comment]
ack

**Review by bluca — APPROVED** [review]
Looks like we got a full house - do you want to copy the acks in the commit messages, or is the PR enough?

**Comment by keszybz** [comment]
I think here is enough. We didn't do acked-by before.

**Pull request merged**
