### PR TITLE
core: fix CapabilityBoundingSet merging

### PR DESCRIPTION
**Pull request by evverx**
Fixes: #1221

### CODE REVIEW

**Comment by poettering** [comment]
Patch looks right. Will merge. WOuld still appreciate an extra test though, as @ronnychevalier suggested!

**Comment by evverx** [comment]
@ronnychevalier , yes, you are right. This code requires some tests. I'll read `test-execute.c` on evening.

Is there any high-level description of the testing process?

[Also](https://github.com/systemd/systemd/blob/master/NEWS#L5194):

> Harald Hoyer's systemd test suite has been integrated into
>           systemd which allows easy testing of systemd builds in qemu
>           and nspawn. (This is really awesome! Ask us for details!)

I've found [`test-functions`](https://github.com/systemd/systemd/blob/master/test/test-functions). Is it the part of Harald Hoyer's systemd test suite?  How can I use it?

**Comment by ronnychevalier** [comment]
@evverx No, you need to use test-execute.c which is ran with make check.
- Add multiple sample services in test/ (e.g. simple one, one that use merging, one that reset, one that use inversing,...)
- Add a test function in test-execute.c, like this:
  
  static void test_exec_capabilityboundingset(Manager *m) {
          test(m, "exec-capabilityboundingset-testA.service", 0, CLD_EXITED);
          test(m, "exec-capabilityboundingset-testB.service", 0, CLD_EXITED);
          [...]
  }

The other test suite is to test systemd by booting it in virtual machines and/or systemd-nspawn, and yes test-functions is part of this test-suite. But the CapababilityBoundingSet tests don't really need this. 

Thanks :)

**Comment by evverx** [comment]
@ronnychevalier , thanks.

I've found my mistake:
- I run `make check` as non-root -> skip some tests (e.g. `test-execute`) :)

`sudo ./test-execute` fails with:

```
Assertion 'service->main_exec_status.status == status_expected' failed at src/test/test-execute.c:58, function check(). Aborting.
```

I don't have the group `nobody`:)

> The other test suite is to test systemd by booting it in virtual machines and/or systemd-nspawn

Yes, I see.
Currently, I have a script for `make`, `make check`, `make install DESTDIR=container-root`, `nspawn`.
Looks like I reinvent the wheel:)

**Comment by ronnychevalier** [comment]
@evverx Ok I will update it to check if there is the group/user nobody exists before executing the tests using it later today. Thanks

See test/README.testsuite for how to use the test-suite

**Comment by evverx** [comment]
@ronnychevalier , you are genius!
I wrote a test and found a bug:)
Please, take a look #1713

**Pull request merged**
