### PR TITLE
sd-ipv4acd: split out as separate library from sd-ipv4ll

### PR DESCRIPTION
**Pull request by teg**
This allows the address conflict detection (comparable to IPv6 Duplicate Address Detection) to be reused for either static or DHCP addresses in the future.

Replaces #1135.

### CODE REVIEW

**Comment by krillenilsson** [comment]
@teg 
Hi, I tested this and the collision detection seems to work, however the rate limit doesn't seems to work..
The IPV4ACD_STATE_INIT (which checks if conflicts reached max) isn't called for each conflict, nor is ipv4acd_on_conflict called to increment the counter.
I guess this is where the rate limitation should be detected?
My setup is  quite simple, i hardcoded the IP given in ipv4ll_pick_address and give the same IP to another host (statically), this will cause it to retry same address over and over again, causing conflicts.

**Comment by teg** [comment]
Hm, I can't reproduce exactly what you describe. But there is a bug: the conlfict counter was reset on _start(), which it should not be. I moved that now, and it works for me. I force pushed as it was only a one-line change. Care to take it for another spin?

**Comment by krillenilsson** [comment]
@teg Seems to work fine now :+1: !

**Comment by teg** [comment]
Thanks for testing!

**Pull request merged**
