### PR TITLE
import: Draw progress bars

### PR DESCRIPTION
**Pull request by daandemeyer**
Currently every progress update results in a new progress message which is extremely verbose. Instead, let's use the progress bar infra to draw a proper progress bar similar to what we do in systemd-repart now.

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, so hmm these import tools were supposed to be the backend for importctl/importd, sysupdate/sysupdated and so on. And the idea was that the frontend draws the progress bars, i.e. importctl and so on.

Hence this seems like the wrong place, and might even break the importctl output quite a bit, because the communication between importd and its backends isn't precisely ready for ansi sequences and stuff...

**Comment by DaanDeMeyer** [comment]
> Hmm, so hmm these import tools were supposed to be the backend for importctl/importd, sysupdate/sysupdated and so on. And the idea was that the frontend draws the progress bars, i.e. importctl and so on.
> 
> Hence this seems like the wrong place, and might even break the importctl output quite a bit, because the communication between importd and its backends isn't precisely ready for ansi sequences and stuff...

@poettering systemd-sysupdate just shows the systemd-import output directly which leads to a spew of output that isn't exactly useful.

**Comment by DaanDeMeyer** [comment]
@poettering 

> Hmm, so hmm these import tools were supposed to be the backend for importctl/importd, sysupdate/sysupdated and so on. And the idea was that the frontend draws the progress bars, i.e. importctl and so on.
> 
> Hence this seems like the wrong place, and might even break the importctl output quite a bit, because the communication between importd and its backends isn't precisely ready for ansi sequences and stuff...

@poettering Added it behind a tty check for stderr. If systemd-import is writing to a tty it should use a progress bar instead of individual log messages, this also makes it nicer to test systemd-import. I agree it might be nicer to handle this in sysupdate, but this will require bigger changes as in that case we probably won't want to give direct tty access to systemd-import anymore, otherwise we'll still end up with systemd-import logging individual messages to the tty on top of sysupdate's progress bar.

**Comment by DaanDeMeyer** [comment]
Additional context here is that mkosi invokes systemd-sysupdate directly and doesn't go via sysupdated since we want the update to be picked up directly from mkosi's output directory.

**Comment by poettering** [comment]
Hmm, this looks OK I guess, but after the download is done we should always call clear_progress_bar() do get rid of it again

**Pull request merged**
