### PR TITLE
udev: search for udev callouts in both /lib/udev and /usr/lib/udev

### PR DESCRIPTION
**Pull request by mbiebl**
When systemd is built with split-usr support, udev rules can be
installed in both /lib/udev/rules.d and /usr/lib/udev/rules.d.
For udev callouts that aren't specified with a full path, try to find
the executable in both locations.

### CODE REVIEW

**Comment by poettering** [comment]
This doesn't make sense to me. Can you explain? If you have a split-usr setup, then the rules and whatever they execute must be placed in rootprefixdir, and that's what UDEVLIBEXECDIR points to. If you place them elswhere they will not be found given you apparently want to support split-usr stuff...

**Comment by mbiebl** [comment]
In a split-usr setup, you might have udev rules in either /lib/udev/rules.d or /usr/lib/udev/rules.d, and udev processess them and executes those rules from both locations just fine.
What it currently doesn't do, is to look up a RUN+= callout without a full path and only looks in rootprefixdir

**Comment by mbiebl** [comment]
udev reads the udev rules from
```
#define RULES_DIRS (const char* const*) CONF_PATHS_STRV("udev/rules.d")
```
which means /etc, /run, /usr/local/lib/, /usr/lib and /lib

So, strictly speaking, we should lookup all those paths for RUN+= callouts without a full path.
I could update the patch accordingly, if you want.

**Comment by poettering** [comment]
udev rules are not binaries. Not sure why the same rules should apply for them?

**Comment by poettering** [comment]
Are you fixing a real problem? i.e. is there a bugzilla/debbug link or so where people had issues with this?

**Comment by mbiebl** [comment]
Yeah, I've seen (3rd party) packages installing udev rules (and its helper) to /usr/lib/. And while the udev rule was processed, the helper was not called.

**Comment by mbiebl** [comment]
It also feels kinda odd, that you can install a udev rule to /usr/local/lib/udev/rules.d, but then have to install the helper to /lib/udev/

**Comment by mbiebl** [comment]
> udev rules are not binaries.

The packages I checked don't use separate paths when installing the helper binary and the udev rule. They are in the same prefix.

**Comment by bluca** [comment]
In our documentation we do specify ```/usr/lib/udev```, but we don't mention a difference w.r.t. split vs non-split /usr

> Execute an external program specified as the assigned value. If no absolute path is given, the program is expected to live in /usr/lib/udev; otherwise, the absolute path must be specified.

https://www.freedesktop.org/software/systemd/man/udev.html#program

**Comment by mbiebl** [comment]
The documentation is incomplete/incorrect for a split-usr system. This is a known issue.

**Comment by poettering** [comment]
split usr stuff is legacy. We don't document it in the man page.

**Comment by poettering** [comment]
the helper can be placed anywhere. I really see no reason to search for it. The helpers may be referenced by path after all, while the udev rules are not, they are discovered automaticlly. Hence different rules apply, and I see nothing wrong with that.

**Comment by mbiebl** [comment]
You are making up rules on the fly and shifting goal posts.
Anyway, I'll apply this downstream then. Thought this might be useful for other distros which use split-usr, but I guess it's more fun to add useless stuff like homed then to add fixes for stuff people actually care about.

**Comment by floppym** [comment]
I would appreciate this being merged upstream for Gentoo.

**Comment by poettering** [comment]
> You are making up rules on the fly and shifting goal posts.

Hmm? The way we find rules and helpers *is* different. That's a statement of fact.

**Pull request closed without merging**
