### PR TITLE
src: simplify branch statements to make it easier to understand

### PR DESCRIPTION
**Pull request by FrazerClews**
remove unnecessary conditional statements and
simplify statements to make it easier to read

### CODE REVIEW

**Comment by keszybz** [comment]
I didn't look through the whole patch, but I like it. I think that comparing "<=0" on unsigned is misleading and I always end up checking a few times if the value cannot be negative. But @poettering likes this form...

**Comment by evverx** [comment]
I wonder if it was inspired by https://twitter.com/matalaz/status/1257335220321292288.

FWIW if it's decided it should be merged, I think it would be much better if there was a way to automatically catch issues like that when PRs are opened. Otherwise, this type of comparisons will just keep popping up.

As an aside, CIFuzz can't be restarted because of https://github.com/google/oss-fuzz/issues/3732. @FrazerClews could you force-push the PR to trigger it once again properly?

**Comment by FrazerClews** [comment]
> I wonder if it was inspired by https://twitter.com/matalaz/status/1257335220321292288.
> 
> FWIW if it's decided it should be merged, I think it would be much better if there was a way to automatically catch issues like that when PRs are opened. Otherwise, this type of comparisons will just keep popping up.
> 
> As an aside, CIFuzz can't be restarted because of [google/oss-fuzz#3732](https://github.com/google/oss-fuzz/issues/3732). @FrazerClews could you force-push the PR to trigger it once again properly?

I was using a linter called `cppcheck` which I love and could be incorporated into the CI, which detected pretty much all of these issues, plus some more but don't want to make the MR bigger than it needs to be without potentially breaking things. I'll try and restart it

**Comment by poettering** [comment]
I am not a fan of the <= → == and >= → == changes I must say. If you look at such an expression, you will often (typically even?) not be aware of the precise type of the variable that is being compared. To me it appears a lot clearer to encode the effect of such comparison in them, i.e. if i exit early if a value x is <= 0, then it's obviously clear that the remaining valid values for x are > 0. However, if I would just do a x == 0, then it's totally not clear what the effect is, unless I know whether the type is signed or not. Because if the type is signed, then afterwards the possible values are all negative and all positive values, just not zero. If it is unsigned it is > 0 however. This is particular relevant if we use types that opaque. Consider this example:

```c
…
int example_func(time_t t) {
        if (t <= 0)
                return -EINVAL;

        …
        /* body of the function: do something with t */
        …
        return 0;
}
```

So, just by looking at it, do you know what the possible range of `t` is in the body of the function? In the above example, even if we don't know whether `time_t` is signed or not (Which is something I personally have to check in the POSIX docs every single time) we know that it must be a non-zero positive value. However, if we had used a `t == 0` check instead, we'd know much less unless we check the POSIX docs to see if time_t is signed... I think `time_t` illustrates this very nicely, but even if the type is more obvious it might be scrolled off screen, or part of some struct you don#t have at hand or so. I think knowing that after an `if` check filtered some disallowed range out what the now valid range is, is a really important thing to now if we want to write safe code...

I mean, in the best case this is a matter of taste, bikeshedding no?

Can you elaborate why precisely you believe that it becomes more "readable" to change all those <= and >= to ==? I really fail to see that?

**Comment by poettering** [comment]
I think there are plenty other fixes in the PR though that I like much better, and that should go in. Any chance you can separate this out into two PRs? The other stuff is something we probably can all agreee very quickly on and get merged quickly.

**Comment by keszybz** [comment]
Right... When the type is unclear, as with `time_t`, I think it makes sense to keep `<=`. But when we have stuff like `unsigned n_members`, I think `==` is better, so I'd lean towards merging at list parts of those changes. But I agree that this is a style thing with no good answer.

**Comment by vcaputo** [comment]
I disagree, I'm totally with @poettering on this one.  It's benign to do the signed comparison on unsigned types and the code is more resilient to future changes potentially turning unsigned variables signed without revisiting all the affected conditionals.

**Comment by FrazerClews** [comment]
Valid points, but I feel you can't assume that future changes will fall under the `<=` scope, when you may want something else. For future changes to a function, you can just do a `git grep <function>` and change accordingly which you should do anyway. Also keeping it == makes it easier to understand what you want out of the if statement, making it clear you're only going to get a 0 return, or a range of negative error codes you have to look for. For someone new to systemd, it was annoying trying to find out what error codes a certain function was trying to give me, when it was just 0 in the end. It's also just not correct that an `unsigned` can be `< 0` and is misleading, I know the compiler sorts it, but I really don't like that argument for many reasons personally, for the previous reason, compilers are not perfect, and it can sometimes lead to other issues not being resolved by the compiler, but with something like this unlikely, but not impossible.

**Comment by poettering** [comment]
I still would prefer if we could split the PR into two: the stuff everyone is happy with and the other stuff that still warrants further discussion.

**Comment by FrazerClews** [comment]
@poettering how would you want me to split the PR, one being the simplifying of conditional branches, and one for removing `unsigned <= 0`?

**Comment by poettering** [comment]
yeah, something like that. for example the first change in this commit definitely makes sense either way and should be uncontroversial. Just the unsigned <= 0 stuff is the stuff that warrants further discussion I think

**Comment by poettering** [comment]
Let's close this since this has stalled, and the idea was to split this up anyway (resulting in a new, separate PR anyway). If there's still interest, needs a hefty rebase, and a new PR of the split out stuff I guess.

**Pull request closed without merging**
