### PR TITLE
Some Fixes for SYSTEMD.NETDEV(5)

### PR DESCRIPTION
**Pull request by OnkelUlla**

### CODE REVIEW

**Comment by keszybz** [comment]
I removed `squash-on-merge`, since the commits were nicely split to separate out the typo fixes…

@yuwata what's the plan with predictable device naming for bridges: we don't do predictable device naming for the anymore?

**Comment by keszybz** [comment]
(Note that https://github.com/systemd/systemd/issues/12558 talks about a bridge with a single device, but https://github.com/systemd/systemd/pull/12560 just does a blanket disabling of predictable mac addresses afaict.)

**Comment by yuwata** [comment]
(I will consider the current behavior later. Please wait for a while.)

**Comment by keszybz** [comment]
@yuwata so what's the plan here?

**Comment by yuwata** [comment]
Sorry for late response. I think the current behavior is OK, and this PR explains it. Hence, LGTM.

It may be better that .netdev files support
```
MACAddress=random
```
if people requests that a bridge device with random MAC address.

**Pull request merged**
