### PR TITLE
fuzz: do not assume the existence of /sys/class/net/lo

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes [oss-fuzz#13440](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13440).

### CODE REVIEW

**Comment by poettering** [comment]
hmm, how come the loopback device went missing there?

**Comment by evverx** [comment]
On ClusterFuzz fuzzers are run in [a kind of hermetic environment created with `minijail`](https://github.com/google/oss-fuzz/issues/1983#issuecomment-442243360). That's for the most part totally fine especially when people fuzz json parsers :-) The runtime environment on FuzzBuzz is more realistic in this regard. I've just opened https://github.com/systemd/systemd/pull/11887, which makes it possible to run the fuzzers there too.

**Comment by poettering** [comment]
but the part i don't grok is how they create a netns environment with "lo" missing? or is it that /sys is simply not mounted?

**Comment by evverx** [comment]
Last time I checked `/sys` didn't exist there so it seems that it wasn't even created (let alone mounted). If you're interested, the full command looked like
```
echo minijail0 -U -m \"0 $UID 1\" -T static \
  -c 0 -n -v -p -l -I \
  -k proc,/proc,proc,1 -P /tmp/chroot \
  -b /lib,/lib,0 -b /lib64,/lib64,0 -b /usr/lib,/usr/lib,0 \
  -b /tmp,/tmp,1 \
  -b $EXE_DIR,$EXE_DIR,0 $FULL_EXE_PATH $@
```
but I'm not sure I can decipher it right now :-)

**Pull request merged**
