### PR TITLE
Update 60-sensor.hwdb

### PR DESCRIPTION
**Pull request by ErrantSpore**
Chuwi Hi12
Different bios version includes different pn. Submitted change fixed my inverted screen after reboot. Included bvr and bd as combo is presumed unique.

### CODE REVIEW

**Comment by poettering** [comment]
Why is checking by pn (and not bvr/pd) not enough? what am i missing?

**Comment by ErrantSpore** [comment]
I honestly don't know. I reinstalled Ubuntu twice. Both times the screen came up inverted. xrandr could be used to invert it to normal, but it would revert on reboot. I followed instructions I found on creating a local hwdb file and created my own 61-sensor-hwdb file with the submitted settings (but the same accel_mount_matrix) and the and it has fixed my screen.
I should say that the updated bios also changed how the tablet interacts with my WinToUSB version of Windows 10. I'll poke around more. I just submitted this as it works for my tablet.

**Comment by ErrantSpore** [comment]
Could you put this on hold for a bit?

**Comment by keszybz** [comment]
@ErrantSpore your patch was OK, but it hardcoded some version details which are not necessary. Just remove `bvr5.11:bd08/04/2016:` (so that your new line looks like the preceding line), and you're good.

**Comment by ErrantSpore** [comment]
[Chuwi_Hi12_modalias_bd04-28-2016.txt](https://github.com/systemd/systemd/files/5224532/Chuwi_Hi12_modalias_bd04-28-2016.txt)

[Chuwi-HI12-udevadm-28042016.txt](https://github.com/systemd/systemd/files/5224560/Chuwi-HI12-udevadm-28042016.txt)

**Comment by keszybz** [comment]
I think this looks OK. Not pretty, but that's not our fault that the vendor screwed up a bit.

**Comment by keszybz** [comment]
Please click "ready for review" when you are done with updates.

**Comment by ErrantSpore** [comment]
[Chuwi_Hi12_modalias_bd08042016.txt](https://github.com/systemd/systemd/files/5224771/Chuwi_Hi12_modalias_bd08042016.txt)
[Chuwi-HI12-udevadm-bd08042016.txt](https://github.com/systemd/systemd/files/5224773/Chuwi-HI12-udevadm-bd08042016.txt)

These files are from the newest bios.
I should mention that I have an original version Chuwi Hi12 with the X5-Z8300.

**Comment by ErrantSpore** [comment]
I stepped back up to the latest bios with no complaints from Ubuntu. Ready for submission.

**Pull request merged**
