### PR TITLE
man: rescue.target could be seen as single-user.target

### PR DESCRIPTION
**Pull request by johnlinp**
It will be nice to have single-user.target for systemd newcomers since it makes multi-user.target more comprehensible.

### CODE REVIEW

**Comment by poettering** [comment]
Hmm... I am not sure redundant names are really that much better. Ultimately the concept of "single user mode" is UNIX folklore, and "rescue mode" is more descriptive. I wonder if a this time we really should add more UNIX compatbility...

I wonder if this wouldn't better be handles as documentation issue, i.e. we beef up documentation so that people looking for single user mode easily find to rescue.target.

Dunno, @keszybz any idea about this one?

**Comment by mbiebl** [comment]
We already have a plethora of aliases for rescue mode (on the kernel command line). Please let's not add another one (systemd.unit=single-user.target).

I'm also with Lennart on this one, that "rescue.target" better describes what it is for.

**Comment by johnlinp** [comment]
Just to make it clear, I'm not going to replace rescue.target with single-user.target. I just created a symlink, like runlevel1.target.

May I ask why multi-user.target is acceptable while single-user.target is not?

**Comment by keszybz** [comment]
`multi-user.target` is *the* name. Your proposal would add another alias, and we already have many of those. My initial reaction was the same as @poettering's and @mbiebl — non multiplicanda entia sine necessitate — but I deleted my comment to wait for other opinions.

**Comment by poettering** [comment]
> May I ask why multi-user.target is acceptable while single-user.target is not?

Well, it's a very good question why we named multi-user.target the way we named it. And the main reason for that is that we really couldn't come up with a better name back then. For "single-user mode" we did come up with a better name however, and then used that. 

Aliases are not a good thing in general, I'd rather have less of them, than more. We add them when there's a technical necessity for them, but they not only make the technical implementation of things a bit harder, but are also a bit more confusing for the user, as there are multiple terms then to refer to the same concept. The "runlevel1.target" alias btw where created as that's how the initctl compat layer of systemd worked, and back then we wanted to support that people can map their legacy runlevel numbers in different ways to the modern names. That turned out to be a bad idea, but we *did* have a technical reason back then... Adding aliases today is a different thing: there's no technical reason for it, afaics. It's mostly about adding some kind of "conceptual compatibility", but I both think it's too late for that now (given that sysvinit was phased out on many distros years ago), and I also think it comes at a price.

hence, let's treat this as documentation issue. let's not add yet another alias.

I hope that makes some sense?

**Comment by johnlinp** [comment]
@poettering Thank you for your kind explanations. Yes, it makes sense to me.

I was hoping that `single-user.target` would appear somewhere. If creating an alias is too much, I can understand and accept that. I will try to modify my pull request to add descriptions in documentation.

**Comment by keszybz** [comment]
We already had "single user" somewhere in the text, but I guess it's good to have "single-user.target" spelled exactly this way, in case somebody greps. It'll also appear in systemd.directives(8).

**Comment by johnlinp** [comment]
@keszybz Thank you! I was thinking about grep too.

**Pull request merged**
