### PR TITLE
Use a bitmask in fd_add_uid_acl_permission()

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
CI fails, for a good reason

**Comment by keszybz** [comment]
Updated, should be OK now. I added new headers, so not setting the green label.

**Comment by poettering** [comment]
```
../../src/systemd/src/shared/acl-util.h:5:10: fatal error: 'linux/posix_acl.h' file not found
#include <linux/posix_acl.h>
```

**Comment by poettering** [comment]
CI issue appears to be unrelated (repart loopback ioctl mess)

**Pull request merged**
