### PR TITLE
bsod: change background color to black  #30429

### PR DESCRIPTION
**Pull request by ghost**
I changed the bsod background color to black as the default color.
related to this issue: #30429

### CODE REVIEW

**Comment by bluca** [comment]
Uhm, why? It was made blue intentionally

**Comment by YHNdnzj** [comment]
Hmm, if this is made configurable like discussed in #30429, then OK. Simply changing one to another is bikeshedding and I don't see the point?

**Comment by 0keeper1** [comment]
It doesn't look good to have features like another OS,
with a similar name, so changing it to black doesn't affect the name (bsod), Black Screen of Death is a better name which makes it feel horrible to the user when see the screen.

also having a configuration for this is awesome but the default config matters.

**Comment by bluca** [comment]
Yeah no, sorry but this is the literal definition of bikeshedding

**Comment by 0keeper1** [comment]
yes, that's true, but let the community discuss this ...
This definition comes from Microsoft, but there is a question Can open-source projects, create or change a definition for themselves?

**Comment by mrc0mmand** [comment]
> It doesn't look good to have features like another OS, with a similar name

What sort of argument is this? So if another OS has a feature that improves user experience, we are then barred from adopting it?

>, so changing it to black doesn't affect the name (bsod), Black Screen of Death is a better name which makes it feel horrible to the user when see the screen.

Not sure if I'd call association with the [Black Death](https://en.wikipedia.org/wiki/Black_Death) an improvement ;)

**Comment by 0keeper1** [comment]
about the feature, I agree with you, but how much blue screen is close to kernel panic?

**Comment by marcosfrm** [comment]
Your patch does not change the escape code.

There is a tradition to follow here with blue.

**Comment by poettering** [comment]
Sorry, but I think this is bikeshedding. 

As discussed elsewhere I am open to deriving the color from the distro color as encoded in ANSI_COLOR= in os-release, but otherwise I think blue is fine as the default, and any further discussion on the color is just comically bikeshedding.

Let's close this PR.

**Pull request closed without merging**
