### PR TITLE
udevd: inform only once when max number value of children is reached

### PR DESCRIPTION
**Pull request by fbuihuu**
When booting with "udev.log-priority=debug" for example, the output might be
spammed with messages like this:

    systemd-udevd[23545]: maximum number (248) of children reached
    systemd-udevd[23545]: maximum number (248) of children reached
    systemd-udevd[23545]: maximum number (248) of children reached
    systemd-udevd[23545]: maximum number (248) of children reached
    systemd-udevd[23545]: maximum number (248) of children reached
    systemd-udevd[23545]: maximum number (248) of children reached
    systemd-udevd[23545]: maximum number (248) of children reached

While the message itself is useful, printing it only once should be enough.

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

Considering that this is purely informative and not actionable in any way, doing it just once seems completely fine.

**Comment by poettering** [comment]
hmm, this is a debug message, and shouldn't matter much, is it really worth tweaking this? At least shouldn't we log about this again after a while? i.e. please make this at least a ratelimit test, using the API from ratelimit.h...

**Comment by fbuihuu** [comment]
Well having the debug logs spammed with such many messages is pretty useless as they add no values. So if we can avoid it simply, why not ?

I'm not sure about the use of a rate limit because what is interesting is that the max value has been reached once. The fact that it's reached again later isn't really important I think. And as you said it's mostly debugging stuff so I chose the simplest way.

**Comment by yuwata** [comment]
The number of children will become lower than the limit after reach to the limit. And after that, it may reach to the limit again... So, maybe, the flag is reset when the number becomes lower than the limit.

**Comment by fbuihuu** [comment]
@yuwata it sounds like a good compromise as the message would be emitted once for each batch of events.

I'll update the patch, thanks !

**Comment by fbuihuu** [comment]
New version force pushed, PTAL.

**Pull request merged**
