### PR TITLE
systemd-link: Add support to configure tx-tcp6-segmentation

### LINKED ISSUE #6854: TCPSegmentationOffload=false does not disable TSO.
My link file looks like this:

[Match]
Driver=r8152

[Link]
WakeOnLan=off
TCPSegmentationOffload=false
GenericSegmentationOffload=false

While GSO does get disabled, TSO partially gets disabled. here's what i mean:

[mangix@mangix ~]$ ethtool -k enp0s20f0u5u3 | grep seg
tcp-segmentation-offload: on
	tx-tcp-segmentation: off
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp-mangleid-segmentation: off
	tx-tcp6-segmentation: on

tx-tcp-segmentation is what actually gets disabled and not the whole thing.

I looked at the code and it seems that the ethtool names in src/udev/net/ethtool-util.c seems to be old and outdated. For example when running tx-generic-segmentation manually in ethtool this happens:

[mangix@mangix ~]$ sudo ethtool -K enp0s20f0u5u3 tx-generic-segmentation on
Actual changes:
generic-segmentation-offload: on

Normally ethtool is silent. I was going to make a patch fixing this but wanted to hear feedback first.

### Used distribution

Fedora 26

### In case of bug report: Expected behaviour you didn't see

TSO fully off

### In case of bug report: Unexpected behaviour you saw

TSO partially off

### PR DESCRIPTION
**Pull request by ssahani**
closes #6854

tcp-segmentation-offload: off
	tx-tcp-segmentation: off
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp-mangleid-segmentation: off
	tx-tcp6-segmentation: off <==========================

### CODE REVIEW

**Comment by neheb** [comment]
Is there a point in disabling IPv6 separately?

**Comment by ssahani** [comment]
These are two different features as defined by the kernel not clubbed together.

**Comment by neheb** [comment]
I ask since replacing "tx-tcp-segmentation" with just "tso" turns both off.

**Comment by ssahani** [comment]
yes right , I think this is more flexible.

**Pull request merged**
