### PR TITLE
execute: fix the condition of private mounts for user namespacing

### PR DESCRIPTION
**Pull request by hexchain**
See https://github.com/systemd/systemd/issues/26744#issuecomment-1585564238 and following comments.

### CODE REVIEW

**Comment by bluca** [comment]
mmh there are some tests in src/test/test-execute to adjust, probably simply adapt the return code, can you run it locally and check?

**Comment by hexchain** [comment]
Unit tests seem to pass now, but I cannot decipher the remaining failures.

**Comment by poettering** [comment]
Could you add `Follow-up for: 6ef721cbc7dadee4ae878ecf0076d87e57233908` to the commit msg, please?

**Comment by poettering** [comment]
lgtm otherwise

**Comment by hexchain** [comment]
Done.

**Comment by poettering** [comment]
lgtm, but i'll leave the merge to @bluca

**Review by bluca — APPROVED** [review]

**Pull request merged**
