### PR TITLE
tests: various fixes

### PR DESCRIPTION
**Pull request by evverx**
- tests: add exec-spec-interpolation.service to Makefile.am
- tests: fix x86 personality tests to only on x86
- tests: add exec-runtimedirectory\* to Makefile.am
- tests: add exec-capabilityambientset\* to Makefile.am

### CODE REVIEW

**Comment by poettering** [comment]
lgtm

**Comment by poettering** [comment]
@jsynacek does this look ok to you?

**Comment by evverx** [comment]
@martinpitt , what do you think about

```
--> subprocess.check_call(['journalctl', '--sync']) <--
systemctl = subprocess.Popen(
            ['systemctl', 'status', '-overbose', '-l', 'systemd-nspawn@c1'],
            stdout=subprocess.PIPE)
```

in http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/tests/boot-and-services#n214 ?

**Comment by martinpitt** [comment]
@evverx: sure, this can't hurt. Committed.

Merging this MP now, both CIs are green.

**Comment by jsynacek** [comment]
Tests are now passing on both ppc64 and ppc64le.

**Comment by evverx** [comment]
> both CIs are green.

Yeah. But this code has already failed: https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20160223_162928@/log.gz

```
FAIL: test_service (__main__.NspawnTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/adt-run.ARYZJm/build.Cf0/systemd/debian/tests/boot-and-services", line 228, in test_service
    self.assertTrue('Stopped Container c1' in out, out)
```

I can't reproduce this error locally.

**Pull request merged**
