### PR TITLE
units: add Conditions for systemd-oomd.service

### PR DESCRIPTION
**Pull request by anitazha**
Prompted by https://bugzilla.redhat.com/show_bug.cgi?id=1927148 and
https://bugzilla.redhat.com/show_bug.cgi?id=1931181.

cc @keszybz

### CODE REVIEW

**Comment by keszybz** [comment]
Implementation-wise, no issues.
But I'm missing an explanation on the story for containers and oomd: is not usable there at all? 

Also, please add (as a seperate commit) info in the README what the right kconfig incantations are.

**Comment by anitazha** [comment]
It is usable in containers as shown by the one extended test I wrote that seems to be working in nspawn. I initially had left the ConditionVirtualization= line out since it isn't actually a blocker for running systemd-oomd. So if there are people that might want to run in containers I can remove that line again.

**Comment by anitazha** [comment]
Updated the README and removed the ConditionVirtualization= since it's not a blocker for running systemd-oomd. People can mask out or add their own overrides if they don't want to run it in containers.

**Comment by poettering** [comment]
hmm, conditioning of bus activated services is icky. a client that talks to oomd via the bus will see an ugly failure if they try to activate and the activation then fails. but then again i see no better way.

**Pull request merged**
