### PR TITLE
unit: re-add AF_INET and AF_INET6 to RestrictAddressFamilies= in systemd-logind.service

### LINKED ISSUE #9072: doc: may need to document AF_INET is dropped from systemd-logind.service
In #8839, I dropped `AF_INET` and `AF_INET6` from `RestrictAddressFamilies=` in systemd-logind.service. Then, when I try to login a NIS enabled system, I get
```
May 23 12:39:23 systemd-logind[1130]: yp_bind_client_create_v3: RPC: Remote system error - Address family not supported by protocol
May 23 12:39:23 sshd[6979]: pam_systemd(sshd:session): Failed to create session: No such file or directory
May 23 12:39:23 sshd[6979]: pam_unix(sshd:session): session opened for user yu.watanabe by (uid=0)
```

Are there any workaround for this? Or should I revert #8839?

Used distribution is Fedora 28 x86_64.
\==========
As discussed in #9073, we have already set `IPAddressDeny=any`. So instead of reverting #8839, we should document the change, may be in NEWS.

### PR DESCRIPTION
**Pull request by yuwata**
This partially revert dea6363533a8190493692941593e9afdfa92685a (#8839), as logind may try to connect network to resolve network user. E.g., without this, on NIS client system, logind may get the following error.
```
systemd-logind[1130]: yp_bind_client_create_v3: RPC: Remote system error - Address family not supported by protocol
```

Fixes #9072.

### CODE REVIEW

**Comment by yuwata** [comment]
Hmm. We have also already set `IPAddressDeny=any`...

**Comment by poettering** [comment]
Hmm, we documented this change explicitly in the NEWS entry for 235:

https://github.com/systemd/systemd/blob/master/NEWS#L585

So this was in a way deliberate, documented breakage, and I am not sure we should revert it upstream (it's totally OK however if downstreams patch this out again if they are willing to value nss-nis compat over generally security).

**Comment by yuwata** [comment]
I noticed that NEWS for v235 already stressed that the default service unit for logind does not have compatibility to NIS. Let's close this.

**Comment by yuwata** [comment]
@poettering We posted at almost same time. Yeah, we may need to document in the NEWS. Anyway, this should not be merged, I think.

**Pull request closed without merging**
