### PR TITLE
hwdb: add entries for QEMU and QEMU USB HARDDRIVE

### PR DESCRIPTION
**Pull request by pizhenwei**
add usb:v46F4 for QEMU vendor type.
and add usb:v46F4p0001 for QEMU USB HARDDRIVE.

Signed-off-by: zhenwei.pi <zhenwei.pi@youruncloud.com>

### CODE REVIEW

**Comment by keszybz** [comment]
This file is autogenerated from source data pulled from the web (see the update-hwdb target in meson.build). So this change would be overwritten on the next update.

Ideally, this registration would go upstream to http://www.linux-usb.org/usb.ids. If that is not possible, please explain why, and add some mechanism to override this in systemd. We do something like that with `20-acpi-vendor.hwdb.patch`.

**Comment by pacepi** [comment]
@keszybz 
Thank you.
I will close this PR( #8287) later.

**Comment by keszybz** [comment]
No need to close, it's better to force-push any replacement patches.

**Comment by pacepi** [comment]
@keszybz 
OK.
I have sent entries as patch to linux.usb.ids@gmail.com.

**Comment by keszybz** [comment]
Oh, OK. Yes, then close this when that is accepted.

**Comment by keszybz** [comment]
OK, let's hope that this get's handled there. Please reopen if there's something to fix in systemd.

**Comment by pacepi** [comment]
@keszybz 
Hi, 
I had sent entries as patch to linux.usb.ids@gmail.com,  but rebot rejected. 
And I tried to contact linux.usb.ids+err@gmail.com, but administrator did't reply.
So what's the next step?

**Pull request closed without merging**
