### PR TITLE
Use double and int64_t types in json

### PR DESCRIPTION
**Pull request by keszybz**
See commit messages for explanations.

### CODE REVIEW

**Comment by keszybz** [comment]
packit failures are all this: fatal: unable to access 'https://src.fedoraproject.org/rpms/systemd/': The requested URL returned error: 503

**Comment by bluca** [comment]
What about the lgtm alert?

**Comment by keszybz** [comment]
> What about the lgtm alert?

Indeed. `exp10l()` slipped through. Should be good now.

**Comment by poettering** [comment]
Heh, I was thinking the same thing: the long double/intmax_t experiment was a bad idea. I was very close to doing this very same patch. Seems you beat me to it! Excellent!

**Review by bluca — APPROVED** [review]

**Pull request merged**
