### PR TITLE
resolved: proxy upstream local requests to our stub with DO bit set

### PR DESCRIPTION
**Pull request by poettering**
Fixes: #23662 #31223 #19227 #23737 #25105

### CODE REVIEW

**Comment by poettering** [comment]
added a couple of additional fixes on top.

**Comment by poettering** [comment]
@mrc0mmand this commit disables one of the DNSSEC tests you added, since we'll now just propagate a request upstream as is, and the result is now different, but we don#t really care because we don#t want to test knot, but resolved.

I just commented the code for now, because there's something weird going on here: the server refuses to recurse for us, but that means the server is misconfigured: it shouldn't be an upstream resolver to resolved if it doesn#t recurse...

**Comment by poettering** [comment]
> The Knot DNS server in our case is configured as an authoritative DNS server (well, it can be configured _only_ as an authoritative DNS server) and iirc in that case it shouldn't allow recursion?

iirc there's nothing stopping a dns server being authoritative for some zone but also provide recursion. Right now it seems the server refuses to do recursion though. At least that#s what the dig output says.

**Comment by mrc0mmand** [comment]
> > The Knot DNS server in our case is configured as an authoritative DNS server (well, it can be configured _only_ as an authoritative DNS server) and iirc in that case it shouldn't allow recursion?
> 
> iirc there's nothing stopping a dns server being authoritative for some zone but also provide recursion. Right now it seems the server refuses to do recursion though. At least that#s what the dig output says.

From what I've read so far it's generally agreed upon that an authoritative DNS server should not do recursion (except for maybe queries coming from localhost). And Knot does this separation _completely_, so Knot DNS is an authoritative DNS server (that doesn't support recursion) and Knot Resolver is a recursive resolver. Once I have a bit of spare time I'll tweak the test so resolved talks to the recursive resolver instead of directly to the authoritative server.

**Comment by pemensik** [comment]
It is considered best practice to have authoritative servers and recursive servers separate. Basically the only open-source implementation offering both in single package is bind9. All others have special instances. nsd/unbound, powerdns/pdns-recursor, knot/knot-resolver. Check https://www.fedoraproject.org/wiki/SIGs/DNS#Implementations for examples with links.

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
> > > The Knot DNS server in our case is configured as an authoritative DNS server (well, it can be configured _only_ as an authoritative DNS server) and iirc in that case it shouldn't allow recursion?
> > 
> > 
> > iirc there's nothing stopping a dns server being authoritative for some zone but also provide recursion. Right now it seems the server refuses to do recursion though. At least that#s what the dig output says.
> 
> From what I've read so far it's generally agreed upon that an authoritative DNS server should not do recursion (except for maybe queries coming from localhost). And Knot does this separation _completely_, so Knot DNS is an authoritative DNS server (that doesn't support recursion) and Knot Resolver is a recursive resolver. Once I have a bit of spare time I'll tweak the test so resolved talks to the recursive resolver instead of directly to the authoritative server.

Let's merge with that test case disabled for now, and it can be enabled again as a follow-up

**Pull request merged**
