### PR TITLE
test: install correct kpartx udev rules on Debian

### PR DESCRIPTION
**Pull request by mrc0mmand**
Resolves: #30703

/cc @mbiebl

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Review by yuwata — APPROVED** [review]

**Comment by mbiebl** [comment]
Looking at https://packages.ubuntu.com/jammy/amd64/kpartx/filelist it says 95-kpartx.rules

Was the Ubuntu change really correct?

**Comment by mrc0mmand** [comment]
> Looking at https://packages.ubuntu.com/jammy/amd64/kpartx/filelist it says 95-kpartx.rules
> 
> Was the Ubuntu change really correct?

No, that's definitely an unfortunate typo, will fix that in a follow-up PR.

**Comment by mbiebl** [comment]
I guess the problem is that this test is not enabled in upstream-ci https://salsa.debian.org/systemd-team/systemd/-/tree/upstream-ci?ref_type=heads

**Comment by mrc0mmand** [comment]
Yeah, because is excruciatingly slow in QEMU without KVM (or any other accel).

**Pull request merged**
