### PR TITLE
Link nss modules to libsystemd-internal instead of libshared

### PR DESCRIPTION
**Pull request by keszybz**
New convention: `src/shared/*-macro.h` files are header-only includes and they do not require linking to libshared.la.

Purely cosmetic changes, but they reduce overlinking in the nss-*.so.2 files.

### CODE REVIEW

**Comment by dvdhrm** [comment]
What exactly is the problem with linking to libshared? Link-time? I mean, we explicitly use gc-sections, so I cannot see any other problem with libshared.

**Comment by poettering** [comment]
I think the nss-util.h stuff really should just move from src/shared to src/basic, it doesn't depend on anything from src/libsystemd/ or so.

And regarding the clean-up macros: I have been wondering a while now about whether to expose them in the official APIs instead. i.e. when we detect a compatible compiler, just define them in sd-bus.h. Effectively, people will only build this stuff with compatible compilers anyway, and as long as we document the semantics of it, and that it requires a non-standard C compiler I think it should be OK.

GLib nowadays exposes the cleanup stuff too, in the official API as "autoptr" stuff. If they do that with their clear focus on portability I think we should really have no problem doing the same. It would be a matter of adding some macros to _sd_common.h and then making use of that in sd-bus.h.

**Comment by dvdhrm** [comment]
Why not just expose the static-inline helpers with the `p` suffix? This is fully standards compatible and is perfectly usable with `_cleanup_(foobarp)`.

**Comment by poettering** [comment]
Yeah, well, if we do that, we can fully expose the cleanup stuff too. I am working on that now.

**Comment by poettering** [comment]
@dvdhrm ok, changed my mind. so far we didn't define any public macros for making gcc's own syntax easier, and I figure we shouldn't start with that either. Hence, I figured I'll do what you suggest, and define public versions of the "p" calls, and people can then use that directly with gcc's cleanup syntax, or define their own macros to make use of gcc's cleanup syntax.

**Comment by poettering** [comment]
OK, I prepped a patch in #2052, that makes the gcc cleanup helper stuff public. That PR also moves the nss-util.h file to src/basic/.

@keszybz can you elaborate on the linking points @dvdhrm made?

**Comment by keszybz** [comment]
> What exactly is the problem with linking to libshared? Link-time? I mean, we explicitly use gc-sections, so I cannot see any other problem with libshared.

Try running ldd on the output .so file, as described in the commits. E.g. for `myhostname`:

```
.libs/libnss_myhostname.so.2:
        linux-vdso.so.1 (0x00007ffeb8adb000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f03fd45c000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007f03fd257000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f03fd04e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f03fcd4c000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f03fcb31000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f03fc90a000)
        liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f03fc6f8000)
        libgcrypt.so.20 => /lib64/libgcrypt.so.20 (0x00007f03fc413000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f03fc20e000)
        libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f03fbffb000)
        libacl.so.1 => /lib64/libacl.so.1 (0x00007f03fbdf2000)
        libidn.so.11 => /lib64/libidn.so.11 (0x00007f03fbbbd000)
        libseccomp.so.2 => /lib64/libseccomp.so.2 (0x00007f03fb991000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f03fb774000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f03fb3b2000)
        /lib64/ld-linux-x86-64.so.2 (0x000055cada448000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f03fb142000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00007f03faf3c000)
```

```
.libs/libnss_myhostname.so.2:
        linux-vdso.so.1 (0x00007ffc24b94000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007faa744d1000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007faa742cc000)
        librt.so.1 => /lib64/librt.so.1 (0x00007faa740c3000)
        libm.so.6 => /lib64/libm.so.6 (0x00007faa73dc1000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007faa73ba6000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007faa73988000)
        libc.so.6 => /lib64/libc.so.6 (0x00007faa735c7000)
        /lib64/ld-linux-x86-64.so.2 (0x000055d188cdb000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007faa73357000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007faa73152000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00007faa72f4c000)
```

I don't know what is the exact mechanism which causes gc-sections not to work as expected. But it feels cleaner not to overlink in the first place. For nss modules this is more important than for our own binaries because they are linked into random processes.

@poettering: I'll rebase on top of your changes.

**Comment by dvdhrm** [comment]
@keszybz, did you verify that --gc-sections and --as-needed are really used? We skip them for developer builds (without optimizations). I'd really like to see why exactly all that stuff is linked.

**Comment by martinpitt** [comment]
FTR, in Debian we use `--as-needed` as that helps quite a lot, and libnss-myhostname only depends on libc:

```
$ ldd /lib/x86_64-linux-gnu/libnss_myhostname.so.2 
    linux-vdso.so.1 =>  (0x00007ffff53bb000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7ea1447000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7ea1229000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7ea0e5e000)
    /lib64/ld-linux-x86-64.so.2 (0x00005557d8576000)
```

**Pull request closed without merging**
