### PR TITLE
Remove need of `--force` option

### PR DESCRIPTION
**Pull request by amit-tewari**
Issue: https://github.com/systemd/systemd/issues/22826

@bluca , other reviewers,
This PR is starting point to provide boilerplate for new unit files based on the unit type.
I went with a different approach where we don't need any new verb, and check if a file exists already or not. If not, prompt user and create new file. Prompt covers case where command may have a typo in unit file's name.

If this looks a sane approach, I can continue with this feature. Just a couple of questions...

- Where from we should be picking up boilerplate for a unit file?
- Should boilerplate be hard-coded in the command itself or should be picked from files in filesystem?
- If from file system, any convention on paths?

```
ninja -C build

build/systemctl edit abc --user
build/systemctl edit abc --user
build/systemctl edit abc --user --full
build/systemctl edit abc --user --runtime

sudo build/systemctl edit abc
sudo build/systemctl edit abc
sudo build/systemctl edit abc --full

sudo build/systemctl edit abc --runtime
```

Also, added placeholder for unit file identification to fill new unit file with boilerplate configuration.

```
$ build/systemctl edit abc1 --user
No files found for abc1.service.
"abc1.service" does not exist. Should new unit be created? [(y)es, (n)o]
y

 new_path: /[EDITED_HOME]/.config/systemd/user/abc1.service
 type: -22
 type_str: service
 unit_template: @o
```

### CODE REVIEW

**Review by yuwata — CHANGES_REQUESTED** [review]
This sounds still in WIP, turning this into draft. 

Before pushing "Ready for review" button,
- please read docs/CODING_STYLE.md and follow our coding style, especially, use 8ch indentation, and `/* */` style comment.
- please update the commit message to explain what you want to fix.

**Comment by YHNdnzj** [comment]
I personally prefer the approach of
https://github.com/systemd/systemd/pull/23359 and plan to implement that
after
https://github.com/systemd/systemd/pull/26303 is merged 🤔️

**Comment by amit-tewari** [comment]
@yuwata ,
sorry for the statue confusion.
May please have a look at the questions as where the boilerplate should be picked from?

**Comment by YHNdnzj** [comment]
@amit-tewari With `edit-util` now in place, we can resume the discussion/work on this one :)

**Comment by amit-tewari** [comment]
@YHNdnzj ,
I tried a rebase and see there are substantial changes. Feel free to proceed with https://github.com/systemd/systemd/issues/22826 .
I shall be closing this draft MR.

**Pull request closed without merging**
