### PR TITLE
resolved: report svc params as a json object

### PR DESCRIPTION
**Pull request by rpigott**
This representation is significantly more useful. The previous array format omitted the svc param key, which is not very useful.

### CODE REVIEW

**Comment by bluca** [comment]
`TEST-75-RESOLVED` is failing in various jobs, seems related

**Comment by rpigott** [comment]
Hm
```
TEST-75-RESOLVED: [ 2576.222980] ns1.unsigned.test systemd-resolved[298]: varlink-28-28: Return parameters for method reply SubscribeQueryResults() didn't pass validation on field 'answer', ignoring: Wrong medium type
[ 2576.223136] ns1.unsigned.test systemd-resolved[298]: varlink-27-27: Return parameters for method reply SubscribeQueryResults() didn't pass validation on field 'answer', ignoring: Wrong medium type
[ 2576.276871] ns1.unsigned.test systemd-resolved[298]: varlink-28-28: Return parameters for method reply SubscribeQueryResults() didn't pass validation on field 'answer', ignoring: Wrong medium type
[ 2576.277006] ns1.unsigned.test systemd-resolved[298]: varlink-27-27: Return parameters for method reply SubscribeQueryResults() didn't pass validation on field 'answer', ignoring: Wrong medium type
```

**Comment by DaanDeMeyer** [comment]
Isn't this breaking compat?

**Comment by rpigott** [comment]
Maybe? I'm not sure what stability guarantees there are. I could add a new field with the svc param keys in order if that would be more amenable, just the current format is pretty useless unfortunately.

**Comment by bluca** [comment]
This is in a released protocol so yeah, we need to keep backward compat. A new parameter would be fine I think?

**Comment by rpigott** [comment]
Actually, this field is nullable anyway, so not guaranteed to be present. I can just replace it then with a differently named field, right? A new "svcparams" field?

**Comment by bluca** [comment]
> Actually, this field is nullable anyway, so not guaranteed to be present. I can just replace it then with a differently named field, right? A new "svcparams" field?

That should be fine - a bit of manual testing to ensure mixing old/new doesn't explode would be appreciated

**Comment by bluca** [comment]
Have you checked that mixing old client + new server or viceversa handle this gracefully?

**Comment by rpigott** [comment]
I got the expected results from both servers using both `varlinkctl`s if that's what you mean. I can't think of any specific issue that would arise as the interface definition is provided by the server.

<details><summary> new varlinkctl, old server</summary>

```
$ ./build/varlinkctl call /run/systemd/resolve/io.systemd.Resolve io.systemd.Resolve.ResolveRecord `jq -nc '$ARGS.named' --argjson name '"crypto.cloudflare.com"' --argjson type 65` | jq -r '.rrs[].rr'
{
  "key": {
    "class": 1,
    "type": 65,
    "name": "crypto.cloudflare.com"
  },
  "priority": 1,
  "target": "",
  "params": [
    "CGh0dHAvMS4xAmgy",
    "op+JVaKfilU=",
    "AEX+DQBBnwAgACAUQ4ZKovbx5/VN+VumhopTTgH7f43u5aVhzTyaQcThBgAEAAEAAQASY2xvdWRmbGFyZS1lY2guY29tAAA=",
    "JgZHAAAHAAAAAAAAop+JVSYGRwAABwAAAAAAAKKfilU="
  ]
}
```
</details>

<details><summary> old varlinkctl, new server</summary>

```
$ /usr/bin/varlinkctl call /run/systemd/resolve/io.systemd.Resolve io.systemd.Resolve.ResolveRecord `jq -nc '$ARGS.named' --argjson name '"crypto.cloudflare.com"' --argjson type 65` | jq -r '.rrs[].rr'
{
  "key": {
    "class": 1,
    "type": 65,
    "name": "crypto.cloudflare.com"
  },
  "priority": 1,
  "target": "",
  "svcparams": {
    "alpn": "CGh0dHAvMS4xAmgy",
    "ipv4hint": "op+JVaKfilU=",
    "ech": "AEX+DQBBnwAgACAUQ4ZKovbx5/VN+VumhopTTgH7f43u5aVhzTyaQcThBgAEAAEAAQASY2xvdWRmbGFyZS1lY2guY29tAAA=",
    "ipv6hint": "JgZHAAAHAAAAAAAAop+JVSYGRwAABwAAAAAAAKKfilU="
  }
}
```
</details>

Originally I think I intended to just dump the params with key number and all as b64, since some of the future keys may not be known to us anyway. With this change an unknown svc params key 1234 should be represented as "key1234": "\<b64\>".

I did consider parsing the fields a little more, e.g. a list representation for alpn, ipv4hint, etc. Some fields like [ech](https://www.ietf.org/archive/id/draft-ietf-tls-esni-18.html#section-4) would potentially require a more complex representation though, and again some (future) svc params may not be known to us and therefore have no obvious representation. So for now I'm just leaving the values uniformly as b64 strings and the format of the svcparams field is not specified beyond "object".

**Comment by evverx** [comment]
> this field is nullable anyway, so not guaranteed to be present. I can just replace it then with a differently named field, right?

I don't think it's backward-compatible because it technically breaks client expecting and relying on "params". To be fully backward-compatible both "params" (in the old format) and "svcparams" (in the new format) should be emitted. It would probably look like
```sh
                        "rr" : {
                                "key" : {
                                        "class" : 1,
                                        "type" : 65,
                                        "name" : "one.one.one.one"
                                },
                                "priority" : 1,
                                "target" : "",
                                "params" : [
                                        "AmgzAmgy",
                                        "AQEBAQEAAAE=",
                                        "JgZHAEcAAAAAAAAAAAARESYGRwBHAAAAAAAAAAAAEAE="
                                ],
                                "svcparams" : {
                                        "alpn" : "AmgzAmgy",
                                        "ipv4hint" : "AQEBAQEAAAE=",
                                        "ipv6hint" : "JgZHAEcAAAAAAAAAAAARESYGRwBHAAAAAAAAAAAAEAE="
                                 }
                        },
```
That being said I'm not sure why "params" would be relied on with no keys so it isn't clear why it should be kept.

> Originally I think I intended to just dump the params with key number and all as b64

I think in terms of processing it automatically it would be the best option because it should be stable. It offloads some things onto clients but at least they shouldn't be broken when, say, `key1234` is replaced with `whatever-new-key`.

**Comment by rpigott** [comment]
I think that it is backward compatible though? Since the params field was never guaranteed to be present, a client cannot rely on its presence. A client might not do much of anything useful without the params field present, but, well, in its current form a client can't do much useful when it is present either.

For stability, maybe I should just use integers as the keys? If we want to aid clients, maybe something like so?

`{"1": {"key": "alpn", "raw": "AmgzAmgy", "value": ["h3", "h2"]}, ...}`? The rr is already presented in raw format alongside a parsed format, this is the same idea.

**Comment by bluca** [comment]
> I got the expected results from both servers using both `varlinkctl`s if that's what you mean. I can't think of any specific issue that would arise as the interface definition is provided by the server.

That's great, thanks for checking

**Review by bluca — APPROVED** [review]

**Comment by evverx** [comment]
> Since the params field was never guaranteed to be present, a client cannot rely on its presence

If I had a hypothetical client relying on "params" for some reason it would stop working with this patch applied and I would have to change it to start consuming the new params so I don't think it's backward compatible in the sense that old clients have to be changed to start working again.

>  The rr is already presented in raw format alongside a parsed format

Generally I think the "raw" field is the only thing that can actually be relied on by clients.

**Comment by rpigott** [comment]
Stop working how? It can't be an error to omit this field because the interface explicitly marks that it might not be present. It can't stop doing whatever useful behavior it was doing with params before, because... there is no useful behavior.

Also, I prolly shoulda marked this one draft. Would have been better to finish the discussion before merging. We can still correct it before a release though.

**Comment by evverx** [comment]
> It can't be an error to omit this field because the interface explicitly marks that it might not be present

I agree with you that since it's nullable it isn't not guaranteed that it's present but that hypothetical client subscribed to the, say, monitor interface would start missing the params even though they would still be present in the actual resource records.

**Comment by evverx** [comment]
>  It can't stop doing whatever useful behavior it was doing with params before, because... there is no useful behavior.

The problem is that it isn't clear what clients do and why they do it. They could look for the presence of the field, or check if the array is empty, or look for signatures in the values to flag something. Who knows. Now they can't do that properly because the field is just dropped and have to be changed so it isn't backward-compatible (by most standards at least).

Anyway clients that do something useful and correct are likely to consume the "raw" field anyway.

**Comment by evverx** [comment]
Also I opened https://github.com/systemd/systemd/issues/33828. It should probably be documented what the varlink stability actually means.

**Pull request merged**
