### PR TITLE
clock-util: modernize settimeofday() timezone calls

### PR DESCRIPTION
**Pull request by poettering**
Let's use structured initialization, and avoid the weird `tv_null`
indirection.

No changes in behaviour, just some clean-ups.

### CODE REVIEW

**Comment by bluca** [comment]
settimeofday manpage on my machine says:

```
If either tv or tz is NULL, the corresponding structure is not set or returned.  (However, compilation warn‐
ings will result if tv is NULL.)
```

Should we suppress the warnings, or is it just outdated?

**Comment by poettering** [comment]
Man page is almost 10 years out of date. Since glibc's 4b7634a5e03b0da6f8875de9d3f74c1cf6f2a6e8 commit from 2012 there's no warning generated anymore... I don't think we have to care about such old libcs anymore...

But thanks for figuring out why the indirection was there in the first place. I did some spelunking in our codebase and couldn't figure it out, and the glibc headers didn't help me either figure its out. But the man page and really old glibc's explain why we did this...

**Comment by poettering** [comment]
Fun, man pages even have a comment about that:

https://github.com/mkerrisk/man-pages/blob/master/man2/gettimeofday.2#L109

**Comment by bluca** [comment]
eheh that's even older than Debian old-old-stable, pretty sure we are safe yes

**Review by bluca — APPROVED** [review]
LGTM

**Comment by yuwata** [comment]
Interesting. LGTM too.

**Pull request merged**
