### PR TITLE
build: add some coloring to --version output

### PR DESCRIPTION
**Pull request by poettering**
Make it easier to discern enabled and disabled build options.

### CODE REVIEW

**Comment by medhefgo** [comment]
Needs more emojis :thinking:

**Review by bluca — APPROVED** [review]

**Comment by keszybz** [comment]
> Needs more emojis thinking

People use this with grep… Let's not make it harder than necessary.

---

Another option would be to make this static, i.e. provide two strings, one without. It'd probably save a few bytes, because the machine code is more verbose than the ~35 color code characters. But it doesn't matter much either way.

**Comment by medhefgo** [comment]
> People use this with grep… Let's not make it harder than necessary.

You missed my sarcasm.

**Comment by keszybz** [comment]
:]

**Pull request merged**
