### PR TITLE
don't try to access the crypt-device if crypttab contains 'noauto'

### PR DESCRIPTION
**Pull request by tblume**
When I add the option 'noauto' to a crypt device in /etc/crypttab, systemd shouldn't set any dependencies for this device and shouldn't try to run fsck at startup.
Sure, this means that I need to check myself for the presence of the backend device and probably do fsck, once I want to start the crypt device manually. Still I deem this less problematic than systemd on startup looking for a device that I explicitly don't want to enable automatically.

### CODE REVIEW

**Comment by poettering** [comment]
Let me get this right? You specify "noauto" in /etc/crypttab, but do not specify "noauto" in /etc/fstab, and you think the /etc/fstab entry should then inherit the "noauto" automatically?

I am pretty sure such logic should not be used, after all /etc/crypttab is not the only source of crypto config, and this really feels more like a config mistake.

Or am I missing something?

**Comment by tblume** [comment]
Hm, why specifying 'noauto' twice? For fstab it should be sufficient to add 'nofail'.
But using this setup on testmachine (SUSE Installation using systemd v228):

kvm130:~ # cat /etc/crypttab 
cr_encrypted    /dev/disk/by-id/ata-QEMU_HARDDISK_QM00007-part1 none       noauto
kvm130:~ # cat /etc/fstab | grep cr_encrypted
/dev/mapper/cr_encrypted /encrypted           xfs        nofail                0 2

I still get prompted for the password to unlock the crypt device:

-->--
kvm130:~ # journalctl -axb | grep cryptsetup
Apr 07 13:02:23 linux-jnjj systemd-cryptsetup[418]: Set cipher aes, mode xts-plain64, key size 256 bits for device /dev/disk/by-id/ata-QEMU_HARDDISK_QM00007-part1.
-- Subject: Unit systemd-cryptsetup@cr_encrypted.service has finished start-up
-- Unit systemd-cryptsetup@cr_encrypted.service has finished starting up.
-- Subject: Unit cryptsetup.target has finished start-up
-- Unit cryptsetup.target has finished starting up.
--<--

This isn't really convenient.

**Comment by keszybz** [comment]
I see your use case, but it's a bit of an edge case, and I don't think we should add support for it. It just doesn't fit in the systemd model, where "higher" units (in this case the mount unit) try to pull in "lower" units (the decrypted device). You should just add `noauto` twice.

**Comment by poettering** [comment]
@keszybz and I both agree that this really shouldn#t be added. Or to turn this around: if the user says about a file system that it should be automatically mounted, then I think we should do our best to do this.

I hope this makes some sense. Closing.

**Pull request closed without merging**
