### PR TITLE
sd-journal: check sd-event state before setting up post change timer

### LINKED ISSUE #30644: `systemd-journald` triggers an assert during rotation (yet another `e->state != SD_EVENT_FINISHED`)
Another failing `assert_return()`, noticed in a single failing job so far:

```
           PID: 220643 (6)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Tue 2023-12-26 16:33:51 UTC (18min ago)
  Command Line: /usr/lib/systemd/systemd-journald
    Executable: /usr/lib/systemd/systemd-journald
 Control Group: /machine.slice/TEST-43-PRIVATEUSER-UNPRIV.scope/payload/system.slice/systemd-journald.service
          Unit: TEST-43-PRIVATEUSER-UNPRIV.scope
         Slice: machine.slice
       Boot ID: 14250fad86d64806b379c3f73b3d513f
    Machine ID: 72684097a36443c7b6750794fb7c6f3f
      Hostname: H
       Storage: /var/lib/systemd/coredump/core.6.0.14250fad86d64806b379c3f73b3d513f.220643.1703608431000000.zst (present)
  Size on Disk: 210.0K
       Message: Process 220643 (6) of user 0 dumped core.
                
                Stack trace of thread 19:
                #0  0x00007f67ce2ac83c n/a (libc.so.6 + 0x8e83c)
                #1  0x00007f67ce25c668 raise (libc.so.6 + 0x3e668)
                #2  0x00007f67ce2444b8 abort (libc.so.6 + 0x264b8)
                #3  0x00007f67ce602d8d log_assert_failed (libsystemd-shared-255.so + 0x202d8d)
                #4  0x00007f67ce60407c log_assert_failed_return (libsystemd-shared-255.so + 0x20407c)
                #5  0x00007f67ce6d040c sd_event_add_time (libsystemd-shared-255.so + 0x2d040c)
                #6  0x00007f67ce6a8632 journal_file_enable_post_change_timer (libsystemd-shared-255.so + 0x2a8632)
                #7  0x00007f67ce6ab9aa journal_file_open (libsystemd-shared-255.so + 0x2ab9aa)
                #8  0x00007f67ce529be7 journal_file_rotate (libsystemd-shared-255.so + 0x129be7)
                #9  0x00005591aacafbc2 server_do_rotate (systemd-journald + 0xbbc2)
                #10 0x00005591aacb3242 server_rotate (systemd-journald + 0xf242)
                #11 0x00005591aacb566d server_write_to_journal (systemd-journald + 0x1166d)
                #12 0x00005591aacb7e80 server_dispatch_message_real (systemd-journald + 0x13e80)
                #13 0x00005591aacb8113 server_driver_message (systemd-journald + 0x14113)
                #14 0x00005591aacacbae run (systemd-journald + 0x8bae)
                #15 0x00005591aacacd67 main (systemd-journald + 0x8d67)
                #16 0x00007f67ce245cd0 n/a (libc.so.6 + 0x27cd0)
                #17 0x00007f67ce245d8a __libc_start_main (libc.so.6 + 0x27d8a)
                #18 0x00005591aacac3a5 _start (systemd-journald + 0x83a5)
                ELF object binary architecture: AMD x86-64
```

```gdb
Thread 1 (Thread 0x7f67cd8a5940 (LWP 19)):
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f67ce2ac8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f67ce25c668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f67ce2444b8 in __GI_abort () at abort.c:79
#4  0x00007f67ce602d8d in log_assert_failed (text=<optimized out>, file=<optimized out>, line=<optimized out>, func=<optimized out>) at ../build/src/basic/log.c:968
#5  0x00007f67ce60407c in log_assert_failed_return (text=text@entry=0x7f67ce733f13 "e->state != SD_EVENT_FINISHED", file=file@entry=0x7f67ce7195d9 "src/libsystemd/sd-event/sd-event.c", line=line@entry=1399, func=func@entry=0x7f67ce767190 <__func__.134> "sd_event_add_time") at ../build/src/basic/log.c:987
#6  0x00007f67ce6d040c in sd_event_add_time (e=0x5591aca6b350, ret=ret@entry=0x7ffe920f0e80, clock=clock@entry=1, usec=usec@entry=0, accuracy=accuracy@entry=0, callback=callback@entry=0x7f67ce6a83c9 <post_change_thunk>, userdata=0x5591aca83680) at ../build/src/libsystemd/sd-event/sd-event.c:1399
#7  0x00007f67ce6a8632 in journal_file_enable_post_change_timer (f=f@entry=0x5591aca83680, e=<optimized out>, t=t@entry=250000) at ../build/src/libsystemd/sd-journal/journal-file.c:2463
#8  0x00007f67ce6ab9aa in journal_file_open (fd=fd@entry=-1, fname=0x5591aca73880 "/var/log/journal/9392ab40bfa04361a2814d6317b1be08/system.journal", open_flags=<optimized out>, file_flags=file_flags@entry=_JOURNAL_FILE_FLAGS_MAX, mode=416, compress_threshold_bytes=compress_threshold_bytes@entry=18446744073709551615, metrics=0x0, mmap_cache=0x5591aca6b2c0, template=0x5591aca7c2d0, ret=0x7ffe920f0fb0) at ../build/src/libsystemd/sd-journal/journal-file.c:4253
#9  0x00007f67ce529be7 in journal_file_rotate (f=f@entry=0x5591aca6afb0, mmap_cache=0x5591aca6b2c0, file_flags=_JOURNAL_FILE_FLAGS_MAX, compress_threshold_bytes=18446744073709551615, deferred_closes=0x5591aca6d458) at ../build/src/shared/journal-file-util.c:448
#10 0x00005591aacafbc2 in server_do_rotate (s=s@entry=0x5591aca6aef0, f=f@entry=0x5591aca6afb0, name=name@entry=0x5591aacceb74 "system", seal=<optimized out>, uid=uid@entry=0) at ../build/src/journal/journald-server.c:544
#11 0x00005591aacb3242 in server_rotate (s=s@entry=0x5591aca6aef0) at ../build/src/journal/journald-server.c:700
#12 0x00005591aacb566d in server_write_to_journal (s=s@entry=0x5591aca6aef0, uid=0, iovec=iovec@entry=0x7ffe920f1370, n=21, priority=priority@entry=6) at ../build/src/journal/journald-server.c:941
#13 0x00005591aacb7e80 in server_dispatch_message_real (s=s@entry=0x5591aca6aef0, iovec=iovec@entry=0x7ffe920f1370, n=<optimized out>, m=m@entry=63, c=0x5591aca6f5c0, tv=tv@entry=0x0, priority=<optimized out>, object_pid=<optimized out>) at ../build/src/journal/journald-server.c:1155
#14 0x00005591aacb8113 in server_driver_message (s=0x5591aca6aef0, object_pid=object_pid@entry=0, message_id=message_id@entry=0x5591aacc9230 "MESSAGE_ID=d93fb3c9c24d451a97cea615ce59c00b", format=format@entry=0x5591aacce388 "MESSAGE=%.0dJournal stopped") at ../build/src/journal/journald-server.c:1189
#15 0x00005591aacacbae in run (argc=argc@entry=1, argv=argv@entry=0x7ffe920f2208) at ../build/src/journal/journald.c:127
#16 0x00005591aacacd67 in main (argc=1, argv=0x7ffe920f2208) at ../build/src/journal/journald.c:135

 #0  __pthread_kill_implementation (threadid=<optimized out>, 
    signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {
          __val = {140731348880592}
        }
        ret = <optimized out>
#1  0x00007f67ce2ac8a3 in __pthread_kill_internal (signo=6, 
    threadid=<optimized out>) at pthread_kill.c:78
No locals.
#2  0x00007f67ce25c668 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007f67ce2444b8 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {
          __sigaction_handler = {
            sa_handler = 0x20,
            sa_sigaction = 0x20
          },
          sa_mask = {
            __val = {140083821909465, 140731348880704, 2, 140083821909465, 
              1399, 140083822227856, 140083822726336, 140731348880800, 
              140083820768610, 0, 0, 0, 140083822726336, 140083822227856, 
              5616, 94084155431344}
          },
          sa_flags = -831308013,
          sa_restorer = 0x7f67ce7195d9
        }
#4  0x00007f67ce602d8d in log_assert_failed (text=<optimized out>, 
    file=<optimized out>, line=<optimized out>, func=<optimized out>)
    at ../build/src/basic/log.c:968
No locals.
#5  0x00007f67ce60407c in log_assert_failed_return (
    text=text@entry=0x7f67ce733f13 "e->state != SD_EVENT_FINISHED", 
    file=file@entry=0x7f67ce7195d9 "src/libsystemd/sd-event/sd-event.c", 
    line=line@entry=1399, 
    func=func@entry=0x7f67ce767190 <__func__.134> "sd_event_add_time")
    at ../build/src/basic/log.c:987
        _saved_errno_ = 32766
#6  0x00007f67ce6d040c in sd_event_add_time (e=0x5591aca6b350, 
    ret=ret@entry=0x7ffe920f0e80, clock=clock@entry=1, usec=usec@entry=0, 
    accuracy=accuracy@entry=0, 
    callback=callback@entry=0x7f67ce6a83c9 <post_change_thunk>, 
    userdata=0x5591aca83680)
    at ../build/src/libsystemd/sd-event/sd-event.c:1399
        type = <optimized out>
        s = 0x0
        d = <optimized out>
        r = <optimized out>
        __func__ = "sd_event_add_time"
#7  0x00007f67ce6a8632 in journal_file_enable_post_change_timer (
    f=f@entry=0x5591aca83680, e=<optimized out>, t=t@entry=250000)
    at ../build/src/libsystemd/sd-journal/journal-file.c:2463
        timer = 0x0
        r = <optimized out>
        __func__ = "journal_file_enable_post_change_timer"
#8  0x00007f67ce6ab9aa in journal_file_open (fd=fd@entry=-1, 
    fname=0x5591aca73880 "/var/log/journal/9392ab40bfa04361a2814d6317b1be08/system.journal", open_flags=<optimized out>, 
    file_flags=file_flags@entry=_JOURNAL_FILE_FLAGS_MAX, mode=416, 
    compress_threshold_bytes=compress_threshold_bytes@entry=18446744073709551615, metrics=0x0, mmap_cache=0x5591aca6b2c0, template=0x5591aca7c2d0, 
    ret=0x7ffe920f0fb0)
    at ../build/src/libsystemd/sd-journal/journal-file.c:4253
        newly_created = true
        f = 0x5591aca83680
        h = 0x7f67cd8a4000
        r = 0
        __func__ = "journal_file_open"
#9  0x00007f67ce529be7 in journal_file_rotate (f=f@entry=0x5591aca6afb0, 
    mmap_cache=0x5591aca6b2c0, file_flags=_JOURNAL_FILE_FLAGS_MAX, 
    compress_threshold_bytes=18446744073709551615, 
    deferred_closes=0x5591aca6d458)
    at ../build/src/shared/journal-file-util.c:448
        path = 0x5591aca73880 "/var/log/journal/9392ab40bfa04361a2814d6317b1be08/system.journal"
        new_file = 0x0
        r = 0
        __func__ = "journal_file_rotate"
#10 0x00005591aacafbc2 in server_do_rotate (s=s@entry=0x5591aca6aef0, 
    f=f@entry=0x5591aca6afb0, name=name@entry=0x5591aacceb74 "system", 
    seal=<optimized out>, uid=uid@entry=0)
    at ../build/src/journal/journald-server.c:544
        file_flags = <optimized out>
        r = <optimized out>
        __func__ = "server_do_rotate"
#11 0x00005591aacb3242 in server_rotate (s=s@entry=0x5591aca6aef0)
    at ../build/src/journal/journald-server.c:700
        f = 0x3f
        k = 0x5591aca6aef0
        r = <optimized out>
        __func__ = "server_rotate"
#12 0x00005591aacb566d in server_write_to_journal (s=s@entry=0x5591aca6aef0, 
    uid=0, iovec=iovec@entry=0x7ffe920f1370, n=21, priority=priority@entry=6)
    at ../build/src/journal/journald-server.c:941
        vacuumed = false
        rotate = <optimized out>
        ts = {
          realtime = 1703608431887240,
          monotonic = 827950850
        }
        f = <optimized out>
        r = <optimized out>
        __func__ = "server_write_to_journal"
#13 0x00005591aacb7e80 in server_dispatch_message_real (
    s=s@entry=0x5591aca6aef0, iovec=iovec@entry=0x7ffe920f1370, 
    n=<optimized out>, m=m@entry=63, c=0x5591aca6f5c0, tv=tv@entry=0x0, 
    priority=<optimized out>, object_pid=<optimized out>)
    at ../build/src/journal/journald-server.c:1155
        source_time = "\340\025\017\222\376\177\000\000.\000\000\000\000\000\000\000hcr\316g\177\000\000\001\000\000\000\000\000\000\000`\023\017\222\376\177\000\000\320\023\017\222\376\177\000\000P"
        cmdline1 = <optimized out>
        cmdline2 = 0x0
        journal_uid = <optimized out>
        o = 0x7f67ce72d4bc
        __func__ = "server_dispatch_message_real"
#14 0x00005591aacb8113 in server_driver_message (s=0x5591aca6aef0, 
    object_pid=object_pid@entry=0, 
    message_id=message_id@entry=0x5591aacc9230 "MESSAGE_ID=d93fb3c9c24d451a97cea615ce59c00b", 
    format=format@entry=0x5591aacce388 "MESSAGE=%.0dJournal stopped")
    at ../build/src/journal/journald-server.c:1189
        iovec = 0x7ffe920f1370
        n = 6
        k = 5
        m = 63
        ap = {{
            gp_offset = 48,
            fp_offset = 48,
            overflow_arg_area = 0x7ffe920f20a0,
            reg_save_area = 0x7ffe920f1fb0
          }}
        r = <optimized out>
        __func__ = "server_driver_message"
#15 0x00005591aacacbae in run (argc=argc@entry=1, 
    argv=argv@entry=0x7ffe920f2208) at ../build/src/journal/journald.c:127
        s = 0x5591aca6aef0
        namespace = <optimized out>
        log_target = <optimized out>
        r = <optimized out>
        __func__ = "run"
#16 0x00005591aacacd67 in main (argc=1, argv=0x7ffe920f2208)
    at ../build/src/journal/journald.c:135
        r = <optimized out>
        __func__ = "main"
```

### PR DESCRIPTION
**Pull request by yuwata**
The similar check already exists in schedule_post_change().

The function is currently called at two places.
- journal_file_open() in sd-journal: In this case, if the timer is not set up, then journal_file_post_change() will be called at the end of journal_file_append_entry(). So, the necessary task will be done sequentially when an journal entry is stored to the opened journal file. That is desired when the function is called at outside of the event loop.
- server_open_journal() in journald: This is not called after we exit the event loop.

So, we can safely do nothing in the function if the event loop is being finished or already finished.

Fixes #30644.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
LGTM, I'm just a bit confused about the commit message, since there's no `journal_file_post_change()` call in `journal_file_open()`, or am I missing something here?

**Comment by mrc0mmand** [comment]
I assume you meant `journal_file_append_entry()`, since there we would call `journal_file_post_change()` immediately if we didn't _copy_ the timer from the template?

**Comment by yuwata** [comment]
> I assume you meant `journal_file_append_entry()`, since there we would call `journal_file_post_change()` immediately if we didn't _copy_ the timer from the template?

Yeah. Updated the commit message. PTAL.

**Review by mrc0mmand — APPROVED** [review]

**Comment by mrc0mmand** [comment]
Thank you!

**Comment by vcaputo** [comment]
I would have preferred a comment added to the `return 1` path you added `journal_file_enable_post_change_timer()` explaining its purpose/effect.  At a glance that change in this commit seems spurious/potentially unintentional...

**Pull request merged**
