### PR TITLE
conf-parser: downstream conf file drop-ins should never override main…

### PR DESCRIPTION
**Pull request by fbuihuu**
… user conf file

Previously all drop-ins, including those shipped by downstream, usually shipped
in /usr, could override user's main configuration file (located in /etc)
because the main file was always parsed first.

This was problematic for downstreams because their customization should never
override the users one in general. Therefore the only way to make this logic
usable was by teaching users to never use the main conf files and to put all
theirs settings in drop-ins with a higher priority than the one downsteam would
use. However customizing the defaults through the main conf file is something
very well established since a long time hence this is not something
conceivable.

This patch reworks the way we parse configuration files by introducing "early"
conf files (idea from Zbigniew Jędrzejewski-Szmek), which always have a
priority lower than the main config file and hence other conf file drop-ins
too.

Early conf files can be located in any locations where regular conf snippets
can be installed and are sorted between them using the same sorting rules that
apply to other conf files. A conf file is considered as an early one if its
filename is prefixed with "__" (double underscore).

Hence for example, drop-in "/usr/lib/systemd/logind.conf.d/__99-foo.conf" will
never be parsed before:

  /etc/systemd/logind.conf
  /etc/systemd/logind.conf.d/00-foo.conf
  /usr/lib/systemd/logind.conf.d/00-foo.conf

This isn't backwards-compatible, strictly speaking, but the '__' prefix is
something that anyone is unlikely to use normally. Hence the risk should be
pretty low.

Fixes: #2121

### CODE REVIEW

**Comment by yuwata** [comment]
> However customizing the defaults through the main conf file is something
very well established since a long time

Hmm, is it true?

**Comment by fbuihuu** [comment]
@yuwata in my experience I've never seen any sysadmin creating a drop-in to override a default setting, all changes was done by editing the main conf file.

**Comment by yuwata** [comment]
> @yuwata in my experience I've never seen any sysadmin creating a drop-in to override a default setting, all changes was done by editing the main conf file.

Hmm, I'd like to emphasize at somewhere to use drop-in instead of editing the main conf file, and I think we should not introduce such further complexity. The precedence of each drop-in config files is already complex enough... And, I do not think it does not provide any convenience, but just 'support wrong way' to edit units.

Also, I think we should encourage downstream packagers to use names prefixed with digits for drop-in configs, e.g., `/usr/lib/systemd/system/foo.service.d/00-disable-some-feature.conf`, then user can easily order their drop-ins to re-enable the feature with some other setting, e.g., `/etc/systemd/system/foo.service.d/50-enable-some-feature-and-configure-other-features.conf`. Of course, user can also use a link to `/dev/null` to disable the drop-in provided by the downstream packager.

I have not followed the discussions in the previous PR or original issue. So I may misunderstand the motivation of this PR. But I do not agree with introducing this new drop-in type.

**Comment by fbuihuu** [comment]
> I have not followed the discussions in the previous PR or original issue. So I may misunderstand the motivation of this PR. But I do not agree with introducing this new drop-in type.

Please do so, the motivation is explained there and also in the commit message. It's quite simple: drop-ins shipped by downstreams should never override main config files shipped in /etc.

**Comment by yuwata** [comment]
Let's consider the case that /usr/lib/systemd/system/foo.service does _not_ have e.g. `PrivateTmp=`, and downstream enables the setting by `__enable-private-tmp.conf` with `PrivateTmp=yes`. Then the service run with the private /tmp by default. And users (administrators) can disable it by creating a drop-in conf or editing the main unit file.
However, when a new release of `foo.service`, the upstream may explicitly set `PrivateTmp=no`. Then, the early drop-in does not work. And the setting `PrivateTmp=yes` may be necessary for the distribution to work `foo.service` correctly... So, after the new release, the downstream needs to create a 'late' drop-in to override the setting.

The concept of early drop-in _only_ works if the main unit file does not have the setting. And the situation may be changed when a new version of the service is released. So, still I think the idea is not a good way to 'solve' the issue.

(BTW, `PrivateTmp=` in the above may not be a good example, but please consider any setting you want to override.)

**Comment by poettering** [comment]
humpf, the complexity this adds, for such a corner usecase… I am really not convinced this should be added. Every logic we add comes at a price, and I am not sure this is worth it.

**Comment by poettering** [comment]
> @yuwata in my experience I've never seen any sysadmin creating a drop-in to override a default setting, all changes was done by editing the main conf file.

Note that "systemctl edit" defaults to adding a drop-in. I am pretty sure most people will thus add one instead of overriding the whole unit file.

**Comment by poettering** [comment]
So, again, what's the usecase? i.e. in which packages do you actually intend to use this? I mean, if you now say "nss-ldap", then I'll outright tell you: no way, that's legacy sw, we are not going to add new concepts to cover such legacy software. So please be specific, what is this for? No generic terms. List package names that will benefit from this.

**Comment by fbuihuu** [comment]
@yuwata, the patch is only intended for overriding configuration files, ie it doesn't change the way *unit* files are parsed (for the moment). 

The reason is that unit files are less problematic because users barely overwrite the whole unit file when he needs to tune one single service option. For example if he needs to overwrite option `FOO=` in unit file shipped in `/usr/lib/sytemd/system/a.service` he knows and expects that creating  `/etc/sytemd/system/a.service` would overwrite the original version shipped in /usr. Hence using a drop-in here is more natural (but yes the problem still exists for unit files when users decides to overwrite the whole unit file but let's try to address the main config file case first as it seems the easiest one).

OTOH main configuration files, such as `/etc/systemd/system.conf`, have always been shipped in /etc without any counterpart in or drop-ins in /usr probably because they're unusable by downstream. So customization of systemd components have continued to happen in main config files like any other applications. Hence asking downstream to use "late" drop-ins to ship its defaults is not possible since it's not backward compatible.

Hence if downstream needs to override a setting defined in `/etc/systemd/system.conf` properly, currently it can do that by only patching the source code, which makes the drop-in mechanism for downstream unusable, which is pity because it would be a convenient way to override some systemd defaults otherwise (and the documentation suggests them for this use case IIRC).

If we hadn't shipped main configuration files from the beginning (they're pretty useless actually since they contain only commented entries) or shipped them through drop-ins instead then relying on the existing drop-ins mechanism would have worked but it's unfortunately too late.

Perhaps a more acceptable approach (even though I'm not sure to understand why the proposed approach is complex) would be to parse the config in this order:

1. /usr/lib/sytemd/system/system.conf
2. /etc/sytemd/system/system.conf
3. drop-ins

But it still has drawbacks since other packages still can't override main configuration files without taking the risk to beak users own settings. For example openSUSE ships rsyslog which ships in its turn in /usr a drop-in which does `ForwardToSyslog=yes`. This drop-in may override user settings defined in /etc/systemd/journald.conf which is bad.

Also not sure how the unit file case will be addressed later.

**Comment by fbuihuu** [comment]
> So, again, what's the usecase? 

Several use cases have been given already in issue #2121 and pr #17161.

Downstream needs to ship different defaults from the upstream one without patching the code.

They also need to ship different defaults depending on the distros they're installed on without the need to rebuild the binary packages. In openSUSE the same binary package can be installed in different distro flavors where only the defaults differ.

External packages may need to override main config files or unit files, see the previous example with rsyslog.

**Comment by fbuihuu** [comment]
@poettering @keszybz I fear that we going to drop the ball on that one again...

Can you please take a final decision either by making clear that drop-ins aren't for downstreams (in that case the documentation needs to be fixed) or by fixing the current behavior and considering this patch or one of its alternatives ?

I still think that it would be more natural to let drop-ins override only the main config files at the same level:

 1. read main conf file (if any) in /usr 
 2. the result can be overridden by drop-ins in /usr if any
 3. the result can be overridden by the main conf file in /etc if any
 4. the result can be overridden by drop-ins in /etc if any

That wouldn't be backward compatible but I don't think that would be a problem in practice since I don't think any downstream relies on the current behavior.

**Comment by keszybz** [comment]
For completeness, two clarifications:

> Let's consider the case that /usr/lib/systemd/system/foo.service does _not_ have e.g. `PrivateTmp=`, and downstream enables the setting by `__enable-private-tmp.conf` with `PrivateTmp=yes`. Then the service run with the private /tmp by default. And users (administrators) can disable it by creating a drop-in conf or editing the main unit file.
> However, when a new release of `foo.service`, the upstream may explicitly set `PrivateTmp=no`. Then, the early drop-in does not work. And the setting `PrivateTmp=yes` may be necessary for the distribution to work `foo.service` correctly... So, after the new release, the downstream needs to create a 'late' drop-in to override the setting.

I don't think this is a concern. Dropins in /usr/lib are intended for use by packagers when it is necessary to split configuration between packages, and not as a way to override unknown settings. So we certainly expect that if the main configuration file is modified, vendor dropins will be modified by the packagers to match.

> Hence if downstream needs to override a setting defined in `/etc/systemd/system.conf` properly, currently it can do that by only patching the source code, which makes the drop-in mechanism for downstream unusable, which is pity because it would be a convenient way to override some systemd defaults otherwise (and the documentation suggests them for this use case IIRC).

"only patching the source code" is an exaggeration. It *is* possible to provide vendor overrides in at least two ways. Firstly by patching the main configuration file in /etc. This is somewhat ugly but certainly doable by distribution scriplets. E.g. we do that in Fedora for `/etc/nsswitch.conf` and the same thing can be done for any file. Systemd config files actually make this much easier to do because they have a very simple syntax. Secondly by providing a "vendor dropin" in /usr/lib. As discussed, this might have some semantics which can be surprising to users, but it certainly works.

--

So... I'll let @yuwata's and @poettering's opinion take precedence. I think the issue that @fbuihuu is addressing is valid, but I also agree that this would add a lot of complexity, and in general I'd be at best weakly positive, certainly not enough to override the negative opinions. @fbuihuu sorry for suggesting something that wasn't accepted in the end. We should try to improve the docs wherever necessary instead.

One more negative thing that now came to mind: our logic is exactly duplicated in zram-generator and some other libraries. If we were to add new semantics, we should coordinate with those other projects. It just doesn't seem worth the trouble.

**Comment by fbuihuu** [comment]
> "only patching the source code" is an exaggeration. It _is_ possible to provide vendor overrides in at least two ways. Firstly by patching the main configuration file in /etc. This is somewhat ugly but certainly doable by distribution scriplets. E.g. we do that in Fedora for `/etc/nsswitch.conf` and the same thing can be done for any file. Systemd config files actually make this much easier to do because they have a very simple syntax. 

Well I'll skip this one as it's "ugly" (your word and I totally agree): downstream is not supposed to hack main config files in /etc, it's just not possible to maintain in the long run, it's easy to get it wrong and I really don't see the point since the proper solution for systemd is almost implemented, drop-ins can perfectly do the job, we just have to make sure that drop-ins in /usr don't override sysadmins settings defined in main configuration files (living in /etc).

> Secondly by providing a "vendor dropin" in /usr/lib. As discussed, this might have some semantics which can be surprising to users, but it certainly works.

IMHO that's not acceptable, again downstream settings should not override sysadmins customization in any way. 

> @fbuihuu sorry for suggesting something that wasn't accepted in the end.

Not the decision that I would have liked to hear but that's fine, we'll do with it.

Thanks for your feedback.

**Pull request closed without merging**
