### PR TITLE
test: improve handling of ASan under clang

### PR DESCRIPTION
**Pull request by mrc0mmand**
Running integration tests with ASan is somewhat tricky to begin with, as
we need to pre-load the ASan runtime DSO for certain services (like
dbus), otherwise they won't start or behave as expected. In case of gcc
this is pretty easy, as we need the runtime DSO during compilation, so
it's already present on the host system. For clang things get more
complicated, as ASan is compiled in statically by default, thus to
enable the necessary dynamic-ish behavior one needs to compile with
-shared-libasan and then correctly set LD_PRELOAD_PATH, as the runtime
libraries are not in a standard library path.

---

See: https://github.com/systemd/systemd-centos-ci/pull/114#issuecomment-495399367

Setting the `dont-merge` flag as I'll be using this PR for [debugging purposes](https://github.com/systemd/systemd-centos-ci/pull/116) in CentOS CI for a while :-)

### CODE REVIEW

**Comment by mrc0mmand** [comment]
After a not-so-short *put this piece of code here and see what it does* journey tracked [here](https://github.com/systemd/systemd-centos-ci/pull/116) I'll try to sum up what and why needs to be done to make `TEST-01-BASIC` run under ASan when compiled with clang:

1. systemd needs to be compiled with `-shared-libasan`
  In case of clang, the ASan library is compiled in statically instead of dynamically (as is default in gcc). Without this switch, we wouldn't be able to pre-load ASan's DSO to workaround issues with application, which make use of libsystemd, but are not compiled with ASan (looking at you, dbus)

2. Set `LD_LIBRARY_PATH` accordingly on the host, create a `ldconfig` dropin in the VM
  Compiling with `-shared-libasan` has a one unfortunate side-effect - as the clang's ASan DSO is not in any standard library path, we need to tell the applications where to find it. To not mess with the underlying system, I use `LD_LIBRARY_PATH` on the guest, which shouldn't have any permanent effects, and in the test VM I simply create a dropin under `/etc/ld.so.conf.d/` so `ldconfig` can pick it up and correctly guide applications to it.

3. Install `llvm-symbolizer`
  To make the *San reports useful (e.g adding line numbers, etc.), `llvm-symbolizer` needs to be present in `PATH` in the test VM image

4. Increase the VM disk size
  Apparently, 1 GB is not enough for clang with ASan & UBsan, so I bumped it to 2 GB (the base size - 500 MB - for non-ASan runs remains the same)

Currently, there are two unresolved issues/questions:

1. Should we tweak the meson.build config as well to compile with `-shared-libasan` *by default* or it should be left to respective CI?
2. Even with `LD_LIBRARY_PATH` there's something which still complains about missing ASan DSO during the test setup phase (`make setup`):

```
Installing /build/build/po/zh_CN.gmo to /var/tmp/systemd-test.Yx6tzD/root/usr/share/locale/zh_CN/LC_MESSAGES/systemd.mo
Installing /build/build/po/zh_TW.gmo to /var/tmp/systemd-test.Yx6tzD/root/usr/share/locale/zh_TW/LC_MESSAGES/systemd.mo
==12738==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
==12769==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
'/var/tmp/systemd-test.Yx6tzD/root/usr/bin/init' -> '../lib/systemd/systemd'
mkdir: created directory '/var/tmp/systemd-test.Yx6tzD/root/usr/lib/environment.d'
'/var/tmp/systemd-test.Yx6tzD/root/usr/lib/environment.d/99-environment.conf' -> '../../../etc/environment'
'/var/tmp/systemd-test.Yx6tzD/root/usr/bin/resolvconf' -> 'resolvectl'
'/var/tmp/systemd-test.Yx6tzD/root/usr/bin/systemd-resolve' -> 'resolvectl'
```

Even though it apparently doesn't have any visible impact on the test results, it may be worth checking into further.

**Comment by mrc0mmand** [comment]
>  Even with `LD_LIBRARY_PATH` there's something which still complains about missing ASan DSO during the test setup phase (`make setup`):
> 
> 
> ```
> Installing /build/build/po/zh_CN.gmo to /var/tmp/systemd-test.Yx6tzD/root/usr/share/locale/zh_CN/LC_MESSAGES/systemd.mo
> Installing /build/build/po/zh_TW.gmo to /var/tmp/systemd-test.Yx6tzD/root/usr/share/locale/zh_TW/LC_MESSAGES/systemd.mo
> ==12738==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
> ==12769==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
> '/var/tmp/systemd-test.Yx6tzD/root/usr/bin/init' -> '../lib/systemd/systemd'
> mkdir: created directory '/var/tmp/systemd-test.Yx6tzD/root/usr/lib/environment.d'
> '/var/tmp/systemd-test.Yx6tzD/root/usr/lib/environment.d/99-environment.conf' -> '../../../etc/environment'
> '/var/tmp/systemd-test.Yx6tzD/root/usr/bin/resolvconf' -> 'resolvectl'
> '/var/tmp/systemd-test.Yx6tzD/root/usr/bin/systemd-resolve' -> 'resolvectl'
> ```
> 
> Even though it apparently doesn't have any visible impact on the test results, it may be worth checking into further.

This was actually caused by this piece of code:

```bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/asan/dso/dir
```

When `LD_LIBRARY_PATH` is empty, this expands to `LD_LIBRARY_PATH=:/path/to/asan/dso/dir`. Even though it a valid path expression and the first path element is an empty one, it triggers the ASans error above. Rewriting this statement to:

```bash
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/path/to/asan/dso/dir"
```

fixes the issue.

**Comment by mrc0mmand** [comment]
I added a short documentation file, because I'll surely forget most of this stuff in a week or so :-)

@evverx PTAL!

**Comment by evverx** [comment]
@mrc0mmand thank you! I'll try to take a closer look later today. In the meantime, regarding the documentation, it would probably make sense to mention ASan+UBsan somewhere in https://github.com/systemd/systemd/blob/master/docs/CODE_QUALITY.md (where we collect things related to testing in general as far as I know). Plus I'd probably add a link to `asan_wrapper`, which I hope will never be out-of-date (unlike the documentation)).

**Comment by evverx** [comment]
@mrc0mmand could you temporarily turn on TEST-01-BASIC on Azure Pipelines to make sure that this PR doesn't break anything there?

**Comment by evverx** [comment]
I'm looking at https://github.com/systemd/systemd-centos-ci/pull/116 and I'm not sure I understand how it works :-) Did you point CentOS CI to this PR somehow?

**Comment by mrc0mmand** [comment]
> I'm looking at [systemd/systemd-centos-ci#116](https://github.com/systemd/systemd-centos-ci/pull/116) and I'm not sure I understand how it works :-) Did you point CentOS CI to this PR somehow?

Yeah, in the background it (temporarily) checks out this PR.

This is the Jenkins script covered in the shadows, which I edit as needed:

```bash
#!/bin/bash

function at_exit() {
    mkdir _artifacts_all
    mv artifacts_* _artifacts_all
    mv _artifacts_all artifacts_all
    
    utils/generate-index.sh artifacts_all index.html
}

trap at_exit EXIT

ARGS="--no-index"

if [ "$ghprbPullId" ]; then
	ARGS="$ARGS --ci-pr $ghprbPullId "
fi

EC=0

(
    set -e
    #./agent-control.py --pr 12618 $ARGS
    #./agent-control.py $ARGS
    #./agent-control.py --rhel 7 $ARGS
    #./agent-control.py --rhel 8 $ARGS
    #./agent-control.py --vagrant-sync $ARGS
    ./agent-control.py --pr 12663 --vagrant arch-sanitizers-clang $ARGS
    #./agent-control.py --vagrant arch-sanitizers-gcc $ARGS
    #./agent-control.py --vagrant arch $ARGS
)

EC=$?

exit $EC
```

It's not nice nor transparent, but it's convenient when I need to test only a particular part of the CI :-)

**Comment by mrc0mmand** [comment]
Also, looks like it didn't break anything, so far:

```
TEST RUN: Basic systemd setup
+ timeout --foreground 900 /usr/bin/qemu-system-x86_64 -smp 4 -net none -m 1536M -nographic -kernel /boot/vmlinuz-4.15.0-1041-azure -drive format=raw,cache=unsafe,file=/var/tmp/systemd-test.Xi6hmg/rootdisk.img -append 'ro root=/dev/sda1 raid=noautodetect loglevel=2 init=/lib/systemd/systemd-under-asan console=ttyS0 selinux=0 printk.devkmsg=on   '
...
systemd-testsuite login: [  144.577747] sh[279]: + systemctl --state=failed --no-legend --no-pager
[  152.219379] sh[279]: + systemctl daemon-reload
[  210.087230] sh[279]: + echo OK
[‌  OK  ‌] Started ‌Testsuite service‌.‌
         Starting ‌End the test‌...‌
[  212.566072] sh[311]: + systemctl poweroff --no-block
...
TEST RUN: Basic systemd setup [OK]
make: Leaving directory '/home/vsts/work/1/s/test/TEST-01-BASIC'
```

**Comment by evverx** [comment]
> ./agent-control.py --pr 12663 --vagrant arch-sanitizers-clang $ARGS

OK. As far as I understand, this runs the tests build with clang and ASan+UBSan only. Would it be possible to run everything else there just to make sure all the tests are in good shape?

> Also, looks like it didn't break anything, so far

I guess `TEST-01-BASIC` can be safely turned off there :-)

**Comment by mrc0mmand** [comment]
> > ./agent-control.py --pr 12663 --vagrant arch-sanitizers-clang $ARGS
> 
> OK. As far as I understand, this runs the tests build with clang and ASan+UBSan only. Would it be possible to run everything else there just to make sure all the tests are in good shape?

Will do. This will take a few hours though :-)

**Comment by evverx** [comment]
On Fedora the test fails with
```sh
+ PATH_TO_ASAN=/usr/lib64/clang/7.0.1/lib/libclang_rt.asan-x86_64.so
+ [[ -n /usr/lib64/clang/7.0.1/lib/libclang_rt.asan-x86_64.so ]]
+ DEFAULT_ENVIRONMENT='ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1 UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_error='
+ echo /usr/lib64/clang/7.0.1/lib
+ ldconfig
/usr/lib/systemd/systemd-under-asan: line 22: ldconfig: command not found
+ echo DefaultEnvironment=ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1 UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_erro
+ echo DefaultTimeoutStartSec=180s
+ echo DefaultStandardOutput=journal+console
+ find / -name '*.service' -type f
+ xargs sed -i 's/^\(MemoryDeny\|SystemCall\)/#\1/'
+ JOURNALD_CONF_DIR=/etc/systemd/system/systemd-journald.service.d
```
Looks like `ldconfig` should be installed explicitly or PATH should be set accordingly or both. I'm wondering what pulls it on Arch

**Comment by evverx** [comment]
It seems `ldconfig` is installed but `/usr/bin` isn't listed in `PATH`. Here's what I got running `make` with `KERNEL_APPEND=init=/bin/bash`
```
bash-4.4# find / -name ldconfig
/usr/sbin/ldconfig
bash-4.4# echo $PATH
/usr/local/bin:/usr/bin
bash-4.4# ldconfig
bash: ldconfig: command not found
```
so something like `export PATH="$PATH:/usr/sbin"` should help I think.

**Comment by mrc0mmand** [comment]
> so something like `export PATH="$PATH:/usr/sbin"` should help I think.

Thanks! Should be fixed now.

**Comment by evverx** [comment]
Given that `bash` is run as PID1 there it seems generally we can't expect PATH to be set properly. I think it would make sense to just use `export PATH=/sbin:/bin:/usr/sbin:/usr/bin` explicitly to avoid issues like that in the future.

**Comment by mrc0mmand** [comment]
> Given that `bash` is run as PID1 there it seems generally we can't expect PATH to be set properly. I think it would make sense to just use `export PATH=/sbin:/bin:/usr/sbin:/usr/bin` explicitly to avoid issues like that in the future.

Good point, I didn't think of that. 

https://github.com/systemd/systemd/blob/37ee8dc80f070311896f4a92e56a2333b8da735d/test/test-functions#L402-L404

This should indeed make it more reliable.

**Pull request merged**
