### PR TITLE
pam: fix warning "Attempted to close sd-bus after fork, this should not happen." on session close

### PR DESCRIPTION
**Pull request by yuwata**
Fixes one cosmetic issue in #28514.

split-out of #31033.

### CODE REVIEW

**Comment by yuwata** [comment]
@poettering Could you review this? I think this can be go without waiting for the way you suggested in #31033 is implemented.

**Comment by poettering** [comment]
So hmm, not sure how I feel about this one.

So, sd-bus really doesn't like if people pass sd_bus objects across fork(), and try to use them in the child. This is protection in particular as queued buffers are duplicated across fork(), and we really don't want that two processes end up servicing the same connection, flushing buffers on close and so on.

So I added these protections to the pam bus connection release functions to detect this. I forgot at that moment, that we ourselves in sd-pam do this weird stuff where we execve() the pam service program in the parent and let the child around to call pam_service_close() eventually... Which collides with this of course.

I think the best fix might be to explicitly close the bus connection in pam_service_open(), i.e. before we fork(), so that the issue goes away, and no bus connection could possibly be passed over.

**Comment by poettering** [comment]
Uh, so we already do this in both implementations pam_sm_open_session(): we disconnect the bus connections. 

I am a bit puzzled why we have a problem here at all...

**Comment by yuwata** [comment]
As mentioned in the revised commit, the issue here is we wrongly warn about bus connection opened _after_ fork.
Instead of closing the connection in pam_systemd or pam_systemd_home, in the revised commit the check now is more strict and only warn when the connection is opened before the fork.

**Review by YHNdnzj — APPROVED** [review]

**Pull request merged**
