### PR TITLE
Enable ccache and mount it into the build/test container

### PR DESCRIPTION
**Pull request by thedrow**
This PR should make our builds run faster.

### CODE REVIEW

**Comment by keszybz** [comment]
Hmm, does this really work on travis? I'd expect that travis gives a pristine environment for each run, so the cache could only be shared within the same run, and within the same run the whole compilation happens at once, and the same files are not compiled multiple times.

**Comment by thedrow** [comment]
The cache is persisted to S3 between runs.
I'm 100% sure that you can do the same on Semaphore.

**Comment by keszybz** [comment]
OK. I guess this won't hurt.

**Comment by evverx** [comment]
As far as I know, Travis has never built anything due to https://github.com/systemd/systemd/issues/8023, so it would probably be better to make it work first :-)

**Pull request merged**
