### PR TITLE
Added a buffer to worker timeout

### PR DESCRIPTION
**Pull request by sushmbha**
/* In case of a timeout, for example one caused by a script called by the udev rule, the script / program forked by the worker should get killed after the configured timeout - the worker itself should not get killed after the same timeout. The worker should get time to detect that its child has timed out, kill the child, then detect that the child has exited (using SIGCHLD), and then it should continue with remaining tasks. Giving an extra buffer time of 10 seconds for the worker, to make sure the worker can kill the forked child after it times out, and get unblocked after child exited/died. The 10 seconds is just an arbitrary buffer, big enough to  make sure that udevd does not kill the worker, before the worker gets a chance to kill its child. */

### CODE REVIEW

**Comment by sushmbha** [comment]
This PR fixes https://github.com/systemd/systemd/issues/30436

**Review by yuwata — CHANGES_REQUESTED** [review]
Indeed, the timer event source should be improved.
But I think it should not be done in such heuristic way...

**Comment by sushmbha** [comment]
> Indeed, the timer event source should be improved. But I think it should not be done in such heuristic way...
Hi, thanks for your review comment. Do you think this worker timeout should be stored in a data structure like how the arg_timeout is stored ?

**Comment by yuwata** [comment]
@sushmbha I reconsidered your idea, and I cannot find any better idea. So, I picked your commit in #30532.

**Comment by poettering** [comment]
Closing, as https://github.com/systemd/systemd/pull/30532 took over, and contains this commit. (And is already green lit)

**Pull request closed without merging**
