### PR TITLE
Add Zowie ZA12 details to mouse hwdb

### PR DESCRIPTION
**Pull request by poinu**
This patch adds DPI and mousewheel specific hardware properties for the Zowie ZA12 mouse. This mouse has the same specifications as the Zowie FK2 (already in hwdb), it just has a different shape.

#### Additional info
Device as shown by `lsusb`:
```
Bus 001 Device 006: ID 1af3:0001 Kingsis Peripherals ZOWIE Gaming mouse
```

Property updated as seen by `libinput`:

(before) 
```
$ sudo libinput debug-events /dev/input/event5
-event5   DEVICE_ADDED     Kingsis Peripherals ZOWIE Gaming mouse seat0 default group1  cap:p left scroll-nat scroll-button
 event5   POINTER_AXIS     +0.000s	vert -15.00/-1* horiz 0.00/0 (wheel)
 event5   POINTER_AXIS     +0.268s	vert -15.00/-1* horiz 0.00/0 (wheel)
 event5   POINTER_AXIS     +0.653s	vert -15.00/-1* horiz 0.00/0 (wheel)
 event5   POINTER_AXIS     +1.662s	vert 15.00/1* horiz 0.00/0 (wheel)
 event5   POINTER_AXIS     +2.045s	vert 15.00/1* horiz 0.00/0 (wheel)
 event5   POINTER_AXIS     +2.292s	vert 15.00/1* horiz 0.00/0 (wheel)
```

(after)
```
$ sudo libinput debug-events /dev/input/event5
-event5   DEVICE_ADDED     Kingsis Peripherals ZOWIE Gaming mouse seat0 default group1  cap:p left scroll-nat scroll-button
 event5   POINTER_AXIS     +0.000s	vert -22.50/-1* horiz 0.00/0 (wheel)
 event5   POINTER_AXIS     +0.274s	vert -22.50/-1* horiz 0.00/0 (wheel)
 event5   POINTER_AXIS     +0.590s	vert -22.50/-1* horiz 0.00/0 (wheel)
 event5   POINTER_AXIS     +1.283s	vert 22.50/1* horiz 0.00/0 (wheel)
 event5   POINTER_AXIS     +1.600s	vert 22.50/1* horiz 0.00/0 (wheel)
 event5   POINTER_AXIS     +2.571s	vert 22.50/1* horiz 0.00/0 (wheel)
```

### CODE REVIEW

**Comment by poinu** [comment]
*Offtopic:*
                                                                                
Even though the mouse wheel properties have been successfully updated (as shown by `libinput` commands in the description), the scrolling speed hasn't been altered.
                                                                                
After trying different values for the `MOUSE_WHEEL_CLICK_ANGLE` property, I've noticed that values above 15 don't seem to have any effect on the scrolling speed (values lower than 15 do decrease it).
                                                                                
Do you have any idea on what could be the problem? I'm using libinput on Xorg (and gnome).
                                                                                
Any help is much appreciated!

**Comment by poettering** [comment]
lgtm

**Comment by poettering** [comment]
the libput/xorg/gnome question is something for @whot to answer I guess. But the patch looks good otherwise, let's merge it.

**Comment by poinu** [comment]
Thank you @poettering!

**Comment by whot** [comment]
for better or worse, nothing really uses the wheel click angles. scroll speed is in most compositors (and X) calculated as click count * fixed factor. it's good to have it for mere correctness' sake but it doesn't have an effect in the current desktop stack.

**Comment by poinu** [comment]
Hi @whot, thanks a lot for the explanation. I see how this approach works fine for the standard 24 wheel-click mouse, but you are probably aware how it can be quite annoying for 16 wheel-click mice like this one.

By any chance do you happen to know whether this fixed factor can be changed in Xorg (or Mutter for that matter) without having to recompile? I've browsed through plenty of bug tracker issues but I haven't been able to figure this one out.

Thank you very much!

**Comment by whot** [comment]
it's hardcoded, so you're out of luck there. Doubly so because these mice are often advertised as "high-precision scrolling" because the wheel moves slower and thus you can pretend it's more precise. So it's actually working as intended by the vendor.

Solution around it would be to have the kernel support the actual high-res wheel if the device has that ability, but that requires the device-specific protocol in the kernel (if we have that). We do that for MS (standard HID) and Logitech mice (see hid-logitech-dj.c). But even then you only get events more often than now, you don't actually speed up things. That would require wheel acceleration which we don't have in libinput (see this [issue](https://gitlab.freedesktop.org/libinput/libinput/-/issues/7)).

**Comment by poinu** [comment]
> it's hardcoded, so you're out of luck there. Doubly so because these mice are often advertised as "high-precision scrolling" because the wheel moves slower and thus you can pretend it's more precise. So it's actually working as intended by the vendor.

That's unfortunate :( I see how making the wheel move slower can appear to be "more precise" when it actually isn't, marketing tricks I guess :man_shrugging: 

I don't know whether this device has high-res scrolling, but I doubt it (how could I check?). Even if it did, and were to be supported in the kernel, I understand this would only have an effect on smoothness, not speed (as you mention).

So IIUC the only way scrolling speed could be increased for this mouse is by having wheel acceleration implemented in libinput, which would not help to increase it linearly, but rather accelerate it when scrolling through a large document or webpage (at first scrolling would be still slow).

There is something I don't quite understand though: In your first answer you mention that the `MOUSE_WHEEL_CLICK_ANGLE` doesn't have an effect in the current desktop stack, but I noticed decreasing it does actually slow the scrolling speed down further. Somehow this property seems to be used, just not past a certain value (15 degrees in this case).

**Comment by whot** [comment]
> I don't know whether this device has high-res scrolling

check with [hid-recorder](https://gitlab.freedesktop.org/libevdev/hid-tools/) and look for a `Resolution Multiplier` - the kernel would set this automatically. Otherwise it's down to querying the vendor or reverse-engineering the protocol if they have any. Check their windows driver if they have one, if they support it there it'll be implemented in the firmware and "just" needs to be enabled by the kernel. And yes, it is for smoothness, not speed. So say 4 * 25% scrolling instead of 1 * 100% scrolling.

> Somehow this property seems to be used, just not past a certain value (15 degrees in this case).

There's a [hack in the xf86-input-libinput driver](https://gitlab.freedesktop.org/xorg/driver/xf86-input-libinput/-/blob/master/src/xf86libinput.c#L1537) to work around mice with small click angles, this may be what you're encountering here. libinput doesn't care about the click angle, it just passes it on and so does the rest of the Wayland stack (afaik).

> So IIUC the only way scrolling speed could be increased for this mouse is by having wheel acceleration implemented in libinput,

That, or have a toolkit that allows you to modify the speed of scrolling.

**Pull request merged**
