### PR TITLE
missing_syscall: fixup syscall numbers for x32 vs. amd64

### PR DESCRIPTION
**Pull request by mbiebl**

### CODE REVIEW

**Comment by poettering** [comment]
hmm, x32 is gone in the upstream kernel, iirc? maybe we should just drop it too in systemd and refuse building? simplifies stuff quite a bit i think

**Comment by poettering** [comment]
hmm, apparently it is not gone yet, that was just discussed.

**Comment by keszybz** [comment]
LGTM.

**Comment by keszybz** [comment]
centosci: 10:24:55   File "./test/test-network/systemd-networkd-tests.py", line 2138, in test_route_static. Looks unrelated.

**Pull request merged**
