### PR TITLE
sd-bus: add async convenience method call API

### PR DESCRIPTION
**Pull request by utezduyar**
Let's start with only method call. If we don't want to have
a reason why we don't want async convenience APIs, I will
go ahead and implement async property get/set API too.

### CODE REVIEW

**Comment by utezduyar** [comment]
https://github.com/systemd/systemd/blob/master/src/network/networkd-link.c#L751 can be simplified with the patch.

**Comment by dvdhrm** [comment]
I like the idea. I always wondered why we don't have it. However, please use sd_bus_slot like all other async objects do. This is required to allow the caller to cancel the async request.

**Comment by teg** [comment]
Makes sense to me (once you fix it up according to David's comments of course).

**Comment by utezduyar** [comment]
Does it look ok now?

**Comment by utezduyar** [comment]
I tried to keep the same convention as "sd_bus_call_async" vs "sd_bus_call" in terms of where the sd_bus_slot should go in the argument list even though I would prefer to have the sd_bus_slot kind of lastish on both APIs.

**Comment by poettering** [comment]
I am pretty sure the timeout parameter should not be there in the convenience call. If people want to set anything but the default timeout they should use the complex functions instead.

**Comment by poettering** [comment]
Please file a new PR with the three commits as one with a clean commit msg, referencing this PR.

(this github workflow is really broken)

**Comment by poettering** [comment]
(patches look otherwise good now, though, except for the fact that i don't want to merge them in three seperate commits with those commit msgs...)

**Comment by filbranden** [comment]
GitHub workflow is usually for the author to override their branch using `git push -f` (yeah, I know, terrible practice) which will update the PR, so they can essentially squash their commits and use `git rebase -i` or `git commit --amend` as much as they want and still keep the discussion in a single place...

Yes, GitHub is really annoying overall... but no real need to spawn another PR for this particular case.

**Comment by poettering** [comment]
@filbranden well, this cannot work for us really. I mean, we want the full history of the comments plus the original patches around. If we force push all the time, then the old patch versions get removed from the history, which is really annoying.

I think in general we should try to require people to submit issues for all PRs, so that we can have multiple PRs for them. THis is particularly necessary if a couple of different people make patch suggestions for a specific issue, which is pretty common for us.

**Comment by filbranden** [comment]
@mezcalero Well I just did a force push for the unquote_first_word one in 44 (won't reference it here not to create the bogus link...)

Just creating new PRs and keeping the references around might not be enough, since I will most likely remove the branch from the "old" PR from my clone, so that might mean the comments will be purged (I'm not 100% sure about that, but I saw some comments indicating the comments lived in the "cloned" repository.)

Looks like we quickly got to the point where GitHub is hampering the workflows more than it's helping... I'm not too surprised, because I saw the same happen on another project on GitHub as well... If we need to create special "rules" on top of GitHub, then is it really the best tool?

(And, yeah, this discussion clearly doesn't belong here... maybe in the mailing list or a dedicated issue for it... Sorry!)

**Comment by poettering** [comment]
To my knowledge (which is actually @zonque's who is sitting next to me) at the time the PR is created the commits are actually added to the target repo too. Unfortunately though the review comments stay with the originating repo, hence when you remove the branch there the review comments are lost. Which is a pity.

Right now, I see major issues with the github model, but I also believe it is a ton better in other ways than the awful model we had before. The overall verdict from my side is positive for github so far.

**Comment by poettering** [comment]
@filbranden btw, here's a link @zonque just found that indicates that the patches are indeed copied into the target repo;

https://speakerdeck.com/holman/more-git-and-github-secrets?slide=114

**Comment by utezduyar** [comment]
@filbranden,
I have actually force pushed my branch after squashing changes but github automatically created a new pull request (instead of updating the existing PR), opposite of what you are saying. Could you please double check that PR gets updated? 

My steps:
1) git rebase -i SHA (Squash commits)
2) git -f push origin feat/async-api-for-method-call:feat/async-api-for-method-call

**Comment by filbranden** [comment]
@utezduyar Hmmm... My understanding is that GitHub will keep a 1:1 relationship from a PR to a user branch, so as long as you're keeping the same branch name on your clone it should reuse the same PR... But I see this one and 116 are using the same branch name... Maybe you deleted the branch between the two pushes? Or maybe this one was already "closed" when you pushed the branch again and therefore it didn't update this one? Not really sure what went on there...

**Comment by utezduyar** [comment]
@filbranden it was actually "closed". So, it could be it then.

**Comment by filbranden** [comment]
@mezcalero Agree that GitHub is better than before, particularly if you want to attrack drive-by contributions since the barrier to entry of `git send-email` is high and the worload on maintainers to keep track of it is very high...

Though I don't think it's very practical to require opening multiple pull requests for the several revisions and requiring that authors do not use `git push -f`, particularly since most users of GitHub are already used to that... Also, requiring an open issue to keep track of the multiple PRs will probably quickly produce a sea of ids that will be really hard to keep track of.

I think a more productive advice would be for _reviewers_ to avoid using line comments for anything that is wanted for posterity and instead only use them to say "typo" or "comment here" or to point out what exactly in the code the comment on the main thread is making reference to. Wouldn't you think that would be preferrable?

Cheers,
Filipe

**Comment by filbranden** [comment]
Moved to the GitHub announce thread on the mailing list... Sorry for starting the discussion on this PR!

**Pull request closed without merging**
