### PR TITLE
po: update Russian translation

### PR DESCRIPTION
**Pull request by nnz1024**
Portable service stuff.

Translated "inspect portable service" as "прочитать образ переносимой
службы" ("read the portable service image"), because there is no exact
Russian analog for "inspect" ("инспектировать" has a slightly different
meaning). I think reading (some data from) images is the main job for
bus_image_common_get_metadata and bus_image_common_get_os_release, so
this translation will be more or less correct.

### CODE REVIEW

**Comment by yuwata** [comment]
When I translated that to Japanese, I used 検索(search).

**Comment by nnz1024** [comment]
@yuwata Thank you for suggestion.
As I can see from the code (correct me if I'm wrong), `bus_image_acquire` searches the image, and loads it into cache. However, it is used in all "portable" actions translated in this PR (`inspect-images`, `attach-images`, `manage-images`).
Specifically with mode `inspect-images`, the function `bus_image_acquire` is used in `bus_image_common_get_metadata` and `bus_image_common_get_os_release`, which is not only searches the image, but fetches some metadata from it. So I think my suggestion is accurately enough.

**Comment by yuwata** [comment]
Sorry, my previous comment is not a suggestion. By this PR, I just noticed that my translation was not good.
How about '検証(verify)' for 'inspect'? The command reads and checks the image, right? So, 'verify' may not bad.

**Comment by nnz1024** [comment]
Firstly, I'm not the author of the code, so I can be wrong in my assumptions (maybe it is better to ask Lennart directly?)

But IMHO, "verify" is not an optimal choice. Yes, these functions checks for errors after the most of operations, however, I don't think that full checking of the image is their main job. For example, `bus_image_common_get_os_release` calls `image_read_metadata`, which is only looks for some configuration files (such as `/etc/os-release`), but don't check that the image is appropriate for portable service (i.e. contains service binary and corresponding unit file).

I don't know the Japanese at all, so can't give you good suggestion. But it may be worth to consider something like "look into"?

**Comment by keszybz** [comment]
"Прочитать" sounds OK.

**Pull request merged**
