### PR TITLE
Mount fix fstab nofail

### PR DESCRIPTION
**Pull request by fbuihuu**
This patchset to make sure we always stop mount/swap units (generated by the fstab-generator) after all service units during shutdown specially when 'nofail' or 'noauto' are used.

### CODE REVIEW

**Comment by keszybz** [comment]
> So... this looks like it could work.

Yeah, technically this would work, but the user experience is not nice:
- during boot we will get the following messages:

```
level notice: dev-xxx.device: Job dev-xxx.device/start timed out.
lever error: Timed out waiting for device dev-xxx.device.
level notice: Dependency failed for yyy.
level notice: yyy.mount: Job yyy.mount/start failed with result 'dependency'.
level notice: dev-xxx.device: Job dev-xxx.device/start failed with result 'timeout'.
```

Those message _are_ harmless, but we don't emit error (or notice messages) as a principle unless there is a real problem. So your solution unfortunately is not going to work, unless we somehow redesign the system to avoid those messages. But this doesn't seem like the right approach. The whole thing is a bit of a hack, and we shouldn't add scaffolding for it.

A better option might be an asymmetrical Before/After option, which would only apply during shutdown (stop). There have been various times where something like this would have been useful, but we always managed to do with existing dependencies. Maybe it's time to revisit this.

**Comment by fbuihuu** [comment]
On 11/26/2015 08:37 PM, Zbigniew Jędrzejewski-Szmek wrote:

> ```
> So... this looks like it could work.
> ```
> 
> Yeah, technically this would work, but the user experience is not nice:
> - during boot we will get the following messages:
> 
> |level notice: dev-xxx.device: Job dev-xxx.device/start timed out. lever
> error: Timed out waiting for device dev-xxx.device. level notice:
> Dependency failed for yyy. level notice: yyy.mount: Job yyy.mount/start
> failed with result 'dependency'. level notice: dev-xxx.device: Job
> dev-xxx.device/start failed with result 'timeout'. |
> 
> Those message /are/ harmless, but we don't emit error (or notice
> messages) as a principle unless there is a real problem. So your
> solution unfortunately is not going to work, unless we somehow redesign
> the system to avoid those messages. But this doesn't seem like the right
> approach. The whole thing is a bit of a hack, and we shouldn't add
> scaffolding for it.

Agreed.

However I think this is better than the current situation: I would
prefer a harmless warning over an incorrect behavior during shutdown.

> A better option might be an asymmetrical Before/After option, which
> would only apply during shutdown (stop). There have been various times
> where something like this would have been useful, but we always managed
> to do with existing dependencies. Maybe it's time to revisit this.

Yes it might be the right thing to do. However until this is done, I
preferred sending a temporary workaround.

Thanks.

**Comment by fbuihuu** [comment]
@keszybz I've updated the branch according to your feedback, Feel free to drop the workaround.

**Comment by keszybz** [comment]
Sorry, if I wasn't clear: this approach cannot be merged (apart from the first commit, which I now merged). I left the pull request open to discuss a better solution.

**Comment by fbuihuu** [comment]
On 11/27/2015 03:52 AM, Zbigniew Jędrzejewski-Szmek wrote:

> Sorry, if I wasn't clear: this approach cannot be merged 

As I wrote, the current behaviour is wrong and is worse: you'll also get
a warning when shutting down the machine because systemd will try to
unmount mount units with 'nofail' or 'noauto' before stopping any services.

IMHO, getting a harmless warning is still better...

> (apart from the first commit, which I now merged).

You might have missed the new patch I added during my last update:

"fstab-gen: don't convert device timeout into seconds when initializing
JobTimeOutSec"

As I wrote in my one of my previous comments, converting device timeout
into seconds is incorrect.

PS: I'm not sure you got notifications for my replies to your commit
comments. BTW, is it allowed to send patches directly to the systemd
mailing list ? I don't really see the point to use this webui...

Thanks.

**Comment by martinpitt** [comment]
This PR is almsot year old and thus stale, and got rejected in its present form. Hence I am closing it now. If this is still relevant, please fix and rebase to current master, and either reopen this PR or open a new one. Thank you for understanding!

**Pull request closed without merging**
