### PR TITLE
fd-util: make TAKE_FD free of double evaluation

### PR DESCRIPTION
**Pull request by poettering**
Better be safe than sorry.

### CODE REVIEW

**Comment by yuwata** [comment]
I do not oppose with this, but this prohibits some case:
```
int fds[N];
...
TAKE_PTR(*(fds + i)); /* This does not work anymore. */
TAKE_PTR(fds[i]); /* Still this works fine. */
p = fds;
TAKE_PTR(*p++) /* This did not work. Neither with this patch. */
```

**Comment by keszybz** [comment]
Looks reasonable… I wouldn't worry about `TAKE_PTR(*(fds + i));` — the form with array access is easier to read anyway.

**Comment by yuwata** [comment]
So, how about `TAKE_PTR` and `TAKE_PID`?

**Comment by poettering** [comment]
> TAKE_PTR(*(fds + i)); /* This does not work anymore. */

This should actually work? Why do you think it does not?

(Will add a test case for this, which compiles and works fine here...)

**Comment by poettering** [comment]
Added a bunch of additional patches that:

1. do the same for TAKE_PTR() and TAKE_PID() as the original patch did for TAKE_FD
2. add a test showing that the relevant line of https://github.com/systemd/systemd/pull/21216#issuecomment-958004185 actually *does* work
3. ports various places to use TAKE_PID()
4. adds some tweaks to process-util.c

ptal!

**Comment by yuwata** [comment]
> > TAKE_PTR(_(fds + i)); /_ This does not work anymore. */
> 
> This should actually work? Why do you think it does not?
> 
> (Will add a test case for this, which compiles and works fine here...)

Oh, I did not know it works. Sorry for the noise.

**Review by yuwata — APPROVED** [review]
LGTM.

**Pull request merged**
