### PR TITLE
gpt-auto: allow using without cryptsetup

### LINKED ISSUE #24978: systemd-gpt-auto-generator implicitly requires cryptsetup to work
### systemd version the issue has been seen with

251

### Used distribution

Gentoo

### Linux kernel version used

5.15.72-gentoo-dist

### CPU architectures issue was seen on

x86_64

### Component

systemd-gpt-auto-generator

### Expected behaviour you didn't see

When systemd is compiled with `-LIBCRYPTSETUP`, `systemd-gpt-auto-generator` can mount a root filesystem if a drive contains no LUKS partitions.

### Unexpected behaviour you saw

Instead, `systemd-gpt-auto-generator` fails with the error message

`Partition is encrypted, but the project was compiled without libcryptsetup support`

even though the drive contains no LUKS partitions.

### Steps to reproduce the problem

Drive without LUKS/encrypted partitions. Here's my simple setup:

```
Device            Start        End    Sectors  Size Type
/dev/nvme0n1p1     2048    2099199    2097152    1G EFI System
/dev/nvme0n1p2  2099200   18876415   16777216    8G Linux swap
/dev/nvme0n1p3 18876416 3907028991 3888152576  1,8T Linux root (x86-64)
```

If I enable `+LIBCRYPTSETUP` in systemd, the initrd-root switch works fine.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by SoapGentoo**
Fixes #24978

### CODE REVIEW

**Review by yuwata — COMMENTED** [review]
I guess this triggers unused function warning. No?

I think, it is better that `add_root_cryptsetup()` does nothing when cryptsetup is disabled.

**Comment by SoapGentoo** [comment]
so you suggest to just return `0`?

**Comment by yuwata** [comment]
> so you suggest to just return `0`?

Yes.

**Comment by SoapGentoo** [comment]
@yuwata done and tested, works

**Comment by yuwata** [comment]
No, no, I meant `add_root_cryptsetup()` instead of `add_cryptsetup()`...

**Comment by SoapGentoo** [comment]
@yuwata attempt #3 :D

**Review by yuwata — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
