### PR TITLE
test: fix TEST-50-DISSECT build on Ubuntu CI

### PR DESCRIPTION
**Pull request by bluca**
Ubuntu CI's just got the dependencies require dto run this test added,
and it seems the build is different enough from other platforms
that it fails to create the required directories:

cp: cannot create regular file '/var/tmp/systemd-test.JJMOBY/minimal/usr/lib/os-release': No such file or directory

I cannot reproduce this on Debian testing. Failures observed at least on https://github.com/systemd/systemd/pull/17366 - squashfs-tools got added yesterday to the package list for Ubuntu via https://salsa.debian.org/systemd-team/systemd/-/merge_requests/105

### CODE REVIEW

**Comment by bluca** [comment]
PSA: when the Ubuntu CI fails, the CI artifacts (including full systemd journal) can be found in the same web directory as the logs.gz file - the archive is called artifacts.tar.gz - looking...

**Comment by bluca** [comment]
> Oct 16 15:34:07 systemd-testsuite testsuite-50.sh[261]: /usr/lib/systemd/tests/testdata/units/testsuite-50.sh: line 33: systemd-dissect: command not found

**Comment by bluca** [comment]
The Ubuntu CI packaging does not install systemd-dissect when building the packages that are then installed: https://salsa.debian.org/systemd-team/systemd/-/merge_requests/108

**Comment by bluca** [comment]
Looks like it will take a game of whack-a-bug, I'd suggest to disable to unblock others via: https://github.com/systemd/systemd/pull/17372 and then I'll re-enable here

**Comment by bluca** [comment]
Looks like we are good now

**Comment by keszybz** [comment]
LGTM.

**Pull request merged**
