### PR TITLE
Remove systemd-bootchart

### PR DESCRIPTION
**Pull request by zonque**
This commit rips out systemd-bootchart. It has be given a new home, outside of the systemd repository:

  https://github.com/systemd/systemd-bootchart

The code itself isn't actually specific to systemd and can be used without systemd even, so let's put it somewhere else.

### CODE REVIEW

**Comment by zonque** [comment]
Let's wait for an Ack on the standalone codebase from @sofar before we merge this.

**Comment by poettering** [comment]
lgtm

**Comment by zonque** [comment]
Ubuntu does integration tests with bootchart, which fail if the component is missing. @martinpitt, could you make that test optional, so that is skipped if the binary is missing? Or maybe it can simply be dropped?

**Comment by martinpitt** [comment]
@zonque: Did this for now: http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=3e405eab16 so you should be able to retry.

Once this lands in master, I'll move the test into the "don't run for upstream" section, and once we have a separate package for it I'll move the autopkgtest to that.

**Comment by poettering** [comment]
BTW, the PROC_CPUINFO_MODE stuff form architecture.h can be removed too, when bootchart is gone...

**Comment by zonque** [comment]
Good point. Now implemented in a new patch on top.

**Comment by teg** [comment]
LGTM

**Comment by zonque** [comment]
@sofar, could you give your final Ack on this?

**Comment by sofar** [comment]
Ack, :+1:

**Pull request merged**
