### PR TITLE
Revert soft-reboot unit reordering

### PR DESCRIPTION
**Pull request by yuwata**
Replaces #32950.

### CODE REVIEW

**Comment by bluca** [comment]
Are these changes enough to stop the test issues? If so this is fine by me (but I agree with you we should redo this in the next release)

**Comment by yuwata** [comment]
> Are these changes enough to stop the test issues? If so this is fine by me (but I agree with you we should redo this in the next release)

Hopefully. 
`Conflicts=systemd-soft-reboot.service` is not necessary, right?

**Comment by yuwata** [comment]
The reverted change was done after -rc2. So, please merge this before -rc3.

**Comment by bluca** [comment]
I've restarted the mkosi jobs, to ensure the issue is still gone

**Review by bluca — APPROVED** [review]
I've restarted all mkosi jobs twice, so 3 full runs and the test didn't fail, so it looks like this fixes the issue too, so I'll merge it. We should revisit this for 257.

**Comment by bluca** [comment]
Looks like the test started failing again:

https://github.com/systemd/systemd/actions/runs/9199086141/job/25303190028?pr=32724

**Pull request merged**
