### PR TITLE
tests: add a rudimentary fuzzer for server_process_syslog_message

### PR DESCRIPTION
**Pull request by evverx**
I'm going to add reproducers for https://github.com/systemd/systemd/issues/9795, https://github.com/systemd/systemd/issues/9820, https://github.com/systemd/systemd/issues/9829, and https://github.com/systemd/systemd/pull/9827#issuecomment-411335241 tomorrow, but I think it's ready to be merged even without them.

### CODE REVIEW

**Comment by evverx** [comment]
Credit to OSS-Fuzz as usual.

By the way, I received a notification from https://github.com/google/oss-fuzz/issues/1720 where the future of the fuzzer stats page is being discussed. If anyone has any suggestions, it'd be great to share them there.

**Comment by keszybz** [comment]
Sure, this can be probably improved in the future, but it seems useful as-is.

**Comment by yuwata** [comment]
Hmm?? Why does the logind test fail?
```
autopkgtest [12:31:32]: test logind: [-----------------------
 * try-restarting systemd-logind
 * daemon is started
 * loginctl succeeds
 * XDG_SESSION_ID=
1:name=systemd:/user.slice/user-1000.slice/session-1.scope
0::/user.slice/user-1000.slice/session-1.scope
 * process is in session cgroup
-- Logs begin at Sat 2018-08-25 03:20:57 UTC. --
Aug 30 12:14:25 autopkgtest systemd-logind[381]: New session 1 of user ubuntu.
Aug 30 12:15:00 autopkgtest systemd[1]: /lib/systemd/system/systemd-logind.service:33: Unknown system call group, ignoring: @system-service
Aug 30 12:31:33 autopkgtest systemd[1]: Stopping Login Service...
Aug 30 12:31:33 autopkgtest systemd[1]: Stopped Login Service.
Aug 30 12:31:33 autopkgtest systemd[1]: Starting Login Service...
Aug 30 12:31:33 autopkgtest systemd-logind[7735]: Watching system buttons on /dev/input/event0 (Power Button)
Aug 30 12:31:33 autopkgtest systemd-logind[7735]: Watching system buttons on /dev/input/event1 (AT Translated Set 2 keyboard)
Aug 30 12:31:33 autopkgtest systemd-logind[7735]: New seat seat0.
Aug 30 12:31:33 autopkgtest systemd[1]: Started Login Service.
Aug 30 12:31:33 autopkgtest systemd-logind[7735]: New session 1 of user ubuntu.
Fake Lid Switch: /dev/input/event4
Aug 30 12:31:36 autopkgtest systemd-logind[7735]: Watching system buttons on /dev/input/event4 (Fake Lid Switch)
   waiting for suspend, 30s remaining...
   waiting for suspend, 25s remaining...
   waiting for suspend, 20s remaining...
   waiting for suspend, 15s remaining...
   waiting for suspend, 10s remaining...
   waiting for suspend, 5s remaining...
   waiting for suspend, 0s remaining...
closing lid did not cause suspend
autopkgtest [12:32:08]: test logind: -----------------------]
logind               FAIL non-zero exit status 1
```

**Comment by evverx** [comment]
@yuwata to be honest, I don't know. I'm pretty sure it has nothing to do with the fuzzer.

**Comment by yuwata** [comment]
I thought that my recent PR breaks something, but other PRs which include my PR pass the CIs... Could you restart the Ubuntu CIs?

**Comment by evverx** [comment]
I'm afraid there's nothing I can do right now without my laptop. There're instructions at https://www.freedesktop.org/wiki/Software/systemd/autopkgtest/ on how to manually trigger the tests, but it would probably be easier to just force-push the code. As far as I know, anyone with write access to the repository can do that. Though, perhaps, it would make sense to save the logs somewhere just in case.

**Comment by evverx** [comment]
I've just taken a look at https://oss-fuzz-build-logs.storage.googleapis.com/index.html. The fuzzer was built successfully and passed all checks. Let's hope it'll found nothing :-)

**Pull request merged**
