### PR TITLE
virt: Fix Xen PV detection when nested inside another hypervisor

### PR DESCRIPTION
**Pull request by bogsen**
Currently, when Xen PV domains are nested within a hypervisor which is detected through CPUID (such as VMware), the detected hypervisor might not be Xen, because we don't check for Xen until after the CPUID check.

This change moves the Xen check before CPUID checks to fix the issue, and moves Dom0 checking to detect_vm_xen so that we keep ignoring Xen when we are in Dom0.

Output before this change on Xen PV running inside VMware VM:
```
[user@dev-systemd bogsen-systemd]$ SYSTEMD_LOG_LEVEL=debug build/systemd-detect-virt
Failed to read $container of PID 1, ignoring: Permission denied
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
No virtualization found in DMI vendor table.
Unable to read /sys/firmware/dmi/entries/0-0/raw, using the virtualization information found in DMI vendor table, ignoring: No such file or directory
UML virtualization not found in /proc/cpuinfo.
Virtualization found, CPUID=VMwareVMware
Found VM virtualization vmware
vmware
```

Output after this change on Xen PV running inside VMware VM:
```
[user@dev-systemd bogsen-systemd]$ SYSTEMD_LOG_LEVEL=debug build/systemd-detect-virt
Failed to read $container of PID 1, ignoring: Permission denied
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
No virtualization found in DMI vendor table.
Unable to read /sys/firmware/dmi/entries/0-0/raw, using the virtualization information found in DMI vendor table, ignoring: No such file or directory
UML virtualization not found in /proc/cpuinfo.
Virtualization XEN found (/proc/xen exists)
Virtualization XEN, found /sys/hypervisor/properties/features with value 000020f0, XENFEAT_dom0 (indicating the 'hardware domain') is not set.
Found VM virtualization xen
xen
```

### CODE REVIEW

**Comment by yuwata** [comment]
Not familiar with xen, but the code looks superficially good to me.

**Comment by poettering** [comment]
Isn't this a bug in Xen that it allows the outer VM metadata to leak into the inner VM this way? sounds like something they should fix, otherwise not just everything with systemd but a llot of other stuff too will break.

**Comment by bogsen** [comment]
> Isn't this a bug in Xen that it allows the outer VM metadata to leak into the inner VM this way? sounds like something they should fix, otherwise not just everything with systemd but a llot of other stuff too will break.

I think either result is technically correct, but if only one hypervisor can be returned from the detection, the inner-most hypervisor seems more likely to be useful, since a guest is very likely to care about the hypervisor that is providing its virtual hardware. PV even more so since running guests through paravirtualization needs significant involvement from the guest kernel (https://wiki.xenproject.org/wiki/Xen_Project_Software_Overview#PV_.28x86.29), but there are some user space components involved as well (such as [xendriverdomain.service](https://fossies.org/linux/xen/tools/hotplug/Linux/systemd/xendriverdomain.service.in), which uses `ConditionVirtualization=xen` to know when it should be enabled).

**Comment by poettering** [comment]
> I think either result is technically correct, but if only one hypervisor can be returned from the detection, the inner-most hypervisor seems more likely to be useful, since a guest is very likely to care about the hypervisor that is providing its virtual hardware. PV even more so since running guests through paravirtualization needs significant involvement from the guest kernel (https://wiki.xenproject.org/wiki/Xen_Project_Software_Overview#PV_.28x86.29), but there are some user space components involved as well (such as [xendriverdomain.service](https://fossies.org/linux/xen/tools/hotplug/Linux/systemd/xendriverdomain.service.in), which uses `ConditionVirtualization=xen` to know when it should be enabled).

Well, still, it appears to me that the inner VM manager should *always* hide the cpuid stuff the outer VM manager places there, and any case where that's not done should be considered a bug.

**Pull request merged**
