### PR TITLE
Modified send_iovec to truncate the message until it can be delivered

### PR DESCRIPTION
**Pull request by nipakoo**
Fix for https://github.com/systemd/systemd/issues/3573 by adding message length check and message fragmentation if necessary to send_iovec.

### CODE REVIEW

**Comment by poettering** [comment]
this is not going to work this way i fear. The receiving side expects one data field per datagram, and just splitting up the fields into two datagrams means that a second field is added here...

I think it's OK to simply truncate the fields if they get too large, this is just some helpful metadata anyway, and not essential data. maybe we should just add a simple logic of: try to send it, and if it fails, truncate to half its size and try again, and so on, until the datagram can be delivered.

**Comment by nipakoo** [comment]
Or just cut the message at the /proc/sys/net/core/wmem_max length if necessary?

**Comment by poettering** [comment]
@nipakoo is that value accurate? iirc wmem_length is actually a limit enforced on the datagram plus its in-kernel metadata. from our userspace pov truncating at that limit is probably not going to suffice, or is it?

**Comment by nipakoo** [comment]
I believe /proc/sys/net/core/wmem_max - 32 is the exact value for maximum here. This seemed to hold true at least on my tests. However not completely sure what value the 32 represents.

**Comment by poettering** [comment]
it's probably some kernel internal header structure, and it might very well have a different size on a different arch... I am pretty sure we should avoid looing at wmem, except for maybe a start value for the algorithm halving the datagram size or so?

**Comment by nipakoo** [comment]
Sure I'll make the changes on monday

**Comment by poettering** [comment]
I prepped a fix for this now in #3780, replacing this one, please have a look!

**Pull request closed without merging**
