### PR TITLE
meson: install udev rule 70-joystick.rules

### PR DESCRIPTION
**Pull request by eworm-de**

### CODE REVIEW

**Comment by eworm-de** [comment]
Oh, we do not install `70-joystick.hwdb`, so is this by intention?
Building with auto-tools installs `70-joystick.rules` but `70-joystick.hwdb` is missing there as well.

**Comment by keszybz** [comment]
Ooops. It's accidental and both files should be installed.

/cc @hadess

**Comment by eworm-de** [comment]
Updated to install `70-joystick.{rules,hwdb}` for meson and auto-tools.

**Comment by hadess** [comment]
Yep, I completely forgot the hwdb file in #5413...
Patches look fine.

**Pull request merged**
