### PR TITLE
man: correct the default slice for systemd-run units

### PR DESCRIPTION
**Pull request by poettering**
As suggested in #15362

### CODE REVIEW

**Comment by elmarco** [comment]
lgtm (although I have to learn what "root slice" means for --user now ;)

**Comment by poettering** [comment]
the user instance of systemd manages a cgroup subtree of the main cgroup tree. hence the root slice for the user instance of systemd is just the topmost cgroup of that subtree...

**Comment by elmarco** [comment]
Why is it under user@.service?
/user.slice/user-1000.slice/user@1000.service/run-r42e6ac3d03ec49989f380cd3116efdeb.scope

I think I am looking for a systemd-user(1) for an overview of changes (such as delegation, limitations etc)

**Comment by poettering** [comment]
`user@1000.service` is the system service that encapsulates the per-user instance of systemd of the user with UID 1000.

It's nicely recursive: there's a system wide instance of systemd, running as PID 1 in the root of the cgroup tree. And then for each user in the same there's another systemd instance, running as system service, managed by PID1 and itself managing the respective user's services. And each gets their own per-user cgroup tree below the cgroup tree PID 1 manages.

i.e. the systemd instances is like for dbus-daemon where you have one bus instance for the system and one bus each for each user.

And the cgroup tree is like the directory tree, where you have files and directories owned by the system in the top of the directory tree, and then for each user their own directory in /home/<username>/…

Thanks for the review, let's merge!

**Pull request merged**
