### PR TITLE
Rename uid0 to run0

### PR DESCRIPTION
**Pull request by keszybz**
Naming is always a matter of preference, and the old name would certainly work, but I think the new one has the following advantages:
- A verb is better than a noun.
- The name more similar to "the competition", i.e. 'sudo', 'pkexec', 'runas', 'doas', which generally include an action verb.
- The connection between 'systemd-run' and 'run0' is more obvious.

There has been no release yet with the old name, so we can rename without caring for backwards compatibility.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
I'll fix the debian packaging after merging, it can only match one or the other

**Comment by keszybz** [comment]
```
debian/tmp/var/lib/systemd
dh_install: warning: Cannot find (any matches for) "usr/bin/uid0" (tried in ., debian/tmp)

dh_install: warning: systemd missing files: usr/bin/uid0
dh_install: error: missing files, aborting
make: *** [debian/rules:291: binary] Error 255
```
I guess this means that we need to update some debian config somewhere? @bluca please help.

**Comment by keszybz** [comment]
OK, so most of the CI passes. Anything using Debian packaging will fail, so let's not wait for those.

**Comment by DaanDeMeyer** [comment]
So I should probably document this somewhere, but probably the proper way to go about stuff like this is to land the change in the debian packaging first and then update the corresponding submodule in the same PR that makes the change.

**Comment by mbiebl** [comment]
> So I should probably document this somewhere, but probably the proper way to go about stuff like this is to land the change in the debian packaging first and then update the corresponding submodule in the same PR that makes the change.

If we do the changes in the Debian packages first, then other PRs would be broken.
We'd need a PR specific debian branch with the packaging updates.

**Comment by mbiebl** [comment]
we could have upstream-PRXXXX branches in  https://salsa.debian.org/systemd-team/systemd for PRs which add new files.
and then we could pass the debian branch name via an env var.

**Comment by DaanDeMeyer** [comment]
> > So I should probably document this somewhere, but probably the proper way to go about stuff like this is to land the change in the debian packaging first and then update the corresponding submodule in the same PR that makes the change.
> 
> If we do the changes in the Debian packages first, then other PRs would be broken. We'd need a PR specific debian branch with the packaging updates.

They would not be broken because we pin a specific commit of the debian repository in systemd as a git submodule. So any PRs merged in the Debian repository are not pulled in until we explicitly update the commit pointed to by the submodule.

**Comment by mbiebl** [comment]
> They would not be broken because we pin a specific commit of the debian repository in systemd as a git submodule. So any PRs merged in the Debian repository are not pulled in until we explicitly update the commit pointed to by the submodule.

Ah, ok. That works too. Thanks for the clarification.

**Pull request merged**
