### PR TITLE
enhance the priority of syslog

### PR DESCRIPTION
**Pull request by syyhao1994**
https://github.com/systemd/systemd/issues/18065

### CODE REVIEW

**Comment by vcaputo** [comment]
Relevant: https://github.com/systemd/systemd/commit/48cef29504b1ffc0df9929f2d8b2af2ad74d2b4a

**Comment by bluca** [comment]
I'm not sure, why should this one source be prioritized over other user sources like stream and native?

**Comment by syyhao1994** [comment]
> 
> 
> I'm not sure, why should this one source be prioritized over other user sources like stream and native?

As i mentioned in the issue, if journald process the logs in stdout or other resouce rather than /dev/log, and there are a lot of logs flush into the /dev/log at the same time, so the /dev/log will full and dont receive any logs util the journald process the logs in /dev/log. And a lot of important system logs will stuck for flushing into /dev/log which will influence the common use of system. For example, i can't use ssh to login as the /dev/log is full.
I think the logs that flush in to /dev/log are much more than others, and it will affect the normal use of system if the /dev/log is  full. So i think the /dev/log should have high priority than others besides kmesg.

**Comment by bluca** [comment]
> > I'm not sure, why should this one source be prioritized over other user sources like stream and native?
> 
> As i mentioned in the issue, if journald process the logs in stdout or other resouce rather than /dev/log, and there are a lot of logs flush into the /dev/log at the same time, so the /dev/log will full and dont receive any logs util the journald process the logs in /dev/log. And a lot of important system logs will stuck for flushing into /dev/log which will influence the common use of system. For example, i can't even use ssh to login as the /dev/log is full and ssh login is waitting for flushing logs into /dev/log.
> I think the logs that flush in to /dev/log are much more than others, and it will affect the normal use of system if the /dev/log is full. So i think the /dev/log should have high priority than others besides kmesg.

It seems to me that wether native, stream or syslog are "more than others" is subjective, system-dependent and implementation-dependent. In your specific use case, if ssh at some point switched to sd_journal or stdout, you'd then have the opposite problem. Besides, the implementation actually tries avoiding starvation between same-priority queues, to the extent made possible by the epoll interface.

Most importantly, the priority is _lower first_ - this patch causes syslog sources to be processed _after_ the other sources, not before, which would suggest that either it wasn't tested or the root cause was something unrelated?

**Comment by syyhao1994** [comment]
> 
> 
> > > I'm not sure, why should this one source be prioritized over other user sources like stream and native?
> > 
> > 
> > As i mentioned in the issue, if journald process the logs in stdout or other resouce rather than /dev/log, and there are a lot of logs flush into the /dev/log at the same time, so the /dev/log will full and dont receive any logs util the journald process the logs in /dev/log. And a lot of important system logs will stuck for flushing into /dev/log which will influence the common use of system. For example, i can't even use ssh to login as the /dev/log is full and ssh login is waitting for flushing logs into /dev/log.
> > I think the logs that flush in to /dev/log are much more than others, and it will affect the normal use of system if the /dev/log is full. So i think the /dev/log should have high priority than others besides kmesg.
> 
> It seems to me that wether native, stream or syslog are "more than others" is subjective, system-dependent and implementation-dependent. In your specific use case, if ssh at some point switched to sd_journal or stdout, you'd then have the opposite problem. Besides, the implementation actually tries avoiding starvation between same-priority queues, to the extent made possible by the epoll interface.
> 
> Most importantly, the priority is _lower first_ - this patch causes syslog sources to be processed _after_ the other sources, not before, which would suggest that either it wasn't tested or the root cause was something unrelated?

Sorry i make a mistake that thinks SD_EVENT_PRIORITY_NORMAL is the same as SD_EVENT_PRIORITY_IMPORTANT. I just encounter such a prolem so i figure out the prolem is here.
May be it is just my own opinion that the logs flush into /dev/log is more than others. So i think the problem i encountered would be fixed by just adjust the /dev/log priority. 
What you said is also reasonable. So if you think it is no need to do so, you could close the pr.
Thank you for your attention. :-)

**Comment by vcaputo** [comment]
As described in the commit I linked above, these priorities were specifically made equal to avoid starvation caused by favoring a busy, prioritized source over others.

This PR attempts to do the opposite, restoring the previous DoS/starvation potential.

If you think there's a bug in handling these situations with equal priority, this is not the correct fix, but it would still be worth characterizing and fixing correctly if so.

**Pull request closed without merging**
