### PR TITLE
assemble multidevice btrfs volumes without external tools

### PR DESCRIPTION
**Pull request by g0tar**
This self-contained approach introduce very little overhead, unless
someone has a large number of devices composing many btrfs volumes,
in which case btrfs device scan would be faster. Still, having robust
implementation is a nice to have alternative for btrfs-progs.

This solves https://github.com/systemd/systemd/issues/6605

### CODE REVIEW

**Comment by poettering** [comment]
I am not entirely sure how I feel about this, triggering devices from udev rules is kinda ugly, as it feels like it could end up in endless busy loops of devices playing ping pong... dunno. I see where you are coming from. @kaysievers do you have an opinion on this?

**Comment by poettering** [comment]
OK, i briefly talked to @kaysievers about this, and he indicated this is probably OK to go in. But before we do that, can you rework the patch so that the udevadm path is properly generated? specifically, it needs to use rootprefixdir...

**Comment by arvidjaar** [comment]
`btrfs device ready` is completely unsuitable for deciding whether btrfs can be mounted. We should get rid of this hack, not pile heaps of more workarounds. For a start, it obviously does not solve problem of mounting fiesystem with missing device. Nor is it right to trigger events for **all** devices while you only should consider those that are part of filesystem in question. This simply does not scale.

**Comment by g0tar** [comment]
> `btrfs device ready` is completely unsuitable for deciding whether btrfs can be mounted.

The current problem is, that systemd won't even try to mount btrfs device until it is marked as ready.

> We should get rid of this hack, not pile heaps of more workarounds.

How do you propose to mark btrfs device as ready, when no 3rd party userspace takes the responsibility? I can see several other approaches:
1. ignoring not-ready state and try to mount despite after timeout,
2. issue a second round of device discovery by udevd itself.
3. print some meaningful message instead "device timed out" (like "btrfs device X not ready, make sure it is scanned") as a minimum.

The hack I've proposed triggers second round targetted only to the devices, that MIGHT profit from that.

To be clear: yes, this proposal *IS* a hack to overcome problem I've mentioned in #6605. The proper solution is to issue 3rd party "btrfs device scan", sure.

The actual question is: should systemd/udev be robust, trying to recover from user faults, misconfigurations, 3rd party software failures etc? If yes - what is the acceptable price?

> For a start, it obviously does not solve problem of mounting fiesystem with missing device.

It's not about mounting anything with missing device, please read again the issue linked.

> Nor is it right to trigger events for all devices

Not **all** but **all pending btrfs**.

> while you only should consider those that are part of filesystem in question. This simply does not scale.

Sure, If only we could get devices that are part of *THE* (specific) filesystem. But this *IS still limited* to **not ready btrfs devices**, not **all** the devices. Is this price acceptable in general? Honestly don't know. But if not, this hacky-solution might be commented-out by default, so the ones that accept the price could easily uncomment this for inceased chance of proper system boot.

**Comment by poettering** [comment]
> btrfs device ready is completely unsuitable for deciding whether btrfs can be mounted. We should get rid of this hack, not pile heaps of more workarounds. For a start, it obviously does not solve problem of mounting fiesystem with missing device

Well, it's either this or some external btrfs-maintained daemon. The policies how to handle arrays with missing devices are highly specific to the usecase, we cannot apply any default behaviour to that, except for what we are doing now -- consider every raid that isn't fully and totally safely complete as something we stay away from.

systemd is ultimately not in the business of being a storage manager, neither for btrfs, nor for LVM, DM, MD or anything else. As long as all we need to do is a trivial ioctl and a udev rule we can cover the safe and obvious bits. But if you want anything fancier than that, including timeout management, missing device management, yadda yadda, then it really shouldn't happen in systemd, but somewhere else, maintained by people who actually are storage people, and grok that stuff.

This PR is about readjusting some systemd-specific bits of the current logic in systemd a bit, to make it less ugly, hence we are fine with it. But yeah, I think the btrfs folks should put together some daemon if they want RAID properly handled, it's really not our business.

**Comment by poettering** [comment]
> btrfs device ready is completely unsuitable for deciding whether btrfs can be mounted.
> 
> The current problem is, that systemd won't even try to mount btrfs device until it is marked as ready.

Note that the current systemd logic actually works fine — as long as your mount via a stable device name, such as UUID=, because then the last member appearing gets the symlink and all is good. What is broken though is mounting through an explicit kernel device name, like you are doing, which is specific to one specific member...

**Comment by poettering** [comment]
Anyway, I still think this shoudl go in, but please rework the patch so that the udevadm path is properly generated at build-time.

**Comment by g0tar** [comment]
I'm not familiar with meson, but now it seems to substitute the path properly during build time.

**Comment by poettering** [comment]
lgtm

**Pull request merged**
