### PR TITLE
3 minor improvements for notification message handling

### PR DESCRIPTION
**Pull request by poettering**
Some extra safety checks.

### CODE REVIEW

**Comment by fbuihuu** [comment]
> FWIW, this makes sense.

I meant this commit " manager: be stricter with incomining notifications, warn properly about too large ones" makes sense.

(I used this "Review changes" github thing but this didn't work as (I) expected)

**Comment by fbuihuu** [comment]
BTW, manager_dispatch_signal_fd() uses:

`n = read(m->signal_fd, &sfsi, sizeof(sfsi));`
`if (n != sizeof(sfsi) && n >=0)  return -EIO;`

Shouldn't we return 0 in this case ?

**Comment by poettering** [comment]
> n = read(m->signal_fd, &sfsi, sizeof(sfsi));
> if (n != sizeof(sfsi) && n >=0) return -EIO;
> 
> Shouldn't we return 0 in this case ?

If that happens then we are seriously fucked, as the kernel broke its own API then... But yeah, I figure this could be turned into a log_warning() + return 0.

**Comment by keszybz** [comment]
I pushed a commit to change  manager_dispatch_signal_fd().

**Comment by poettering** [comment]
zbigniew's additoin looks good to me (though in the last branch we might also want an explicit log msg using log_error_errno(), but it's fine i figure the way it is)

**Comment by keszybz** [comment]
I didn't add it here, because we get an explicit notification from sd-event, so I thought it'd just repeat the same message.

**Comment by poettering** [comment]
The message sd-event prints is just a debug message. i.e. kind of a fallback msg, in case people forget to log themselves... I figure in this case we should have a log_error_errno() message however, so that this is always shown...

**Comment by keszybz** [comment]
Repushed.

**Comment by poettering** [comment]
excellent. lgtm.

I figure this is ready to go in as soon as CI is happy, as both @fbuihuu and @keszybz looked at this PR and liked it enough to say so or improve it further.

**Comment by evverx** [comment]
Shouldn't we recreate disabled event-source from scratch on `daemon-reexec`?

**Comment by poettering** [comment]
> Shouldn't we recreate disabled event-source from scratch on daemon-reexec?

Not sure what you mean, but a reexec means we'll free all sd-event objects in the old process, and allocate them afresh in the new process.

**Comment by evverx** [comment]
> but a reexec means we'll free all sd-event objects in the old process, and allocate them afresh in the new process

Right. But we don't close "broken" fds. So https://github.com/systemd/systemd/pull/4240#issuecomment-252199581

> What I am just concerned about is that we busy loop when for some reason we can't read the incoming datagram (let's say because of some LSM or so sending us EPERM because of an fd attached to the datagram, or something like that). 

is unfixable, right?

**Comment by poettering** [comment]
@evverx well, we could of course close the signalfd and allocate a new one. But then again, this should never ever happen, and if it happens anyway then the kernel is fucking with us. And if it is, then I am not sure why it would be a good idea to close and allocate a new signalfd in this case. I mean, why would the kernel not be broken for the new signalfd too?

I think with @keszybz most recent addition we are as goot as we can get: if the kernel fucks with us, we just give up: we log about it, we stop using the facility, but we'll allow the system to continue working to the limited degree it is still capable of working, and we won't consume resources without bounds keeping retrying and retrying. I think it's the best we can do in a fucked up situation, that of course should never actually really happen anyway...

**Comment by evverx** [comment]
@poettering , sorry, I don't mean signalfd. I mean `/run/systemd/notify`-socket

**Comment by evverx** [comment]
> But then again, this should never ever happen

I know: https://github.com/systemd/systemd/pull/3658 :-)

**Comment by poettering** [comment]
merging now, as Ci passed.

**Pull request merged**
