### PR TITLE
ci: assorted workarounds for recent flakes

### PR DESCRIPTION
**Pull request by mrc0mmand**
My original `unbuffer` workaround was actually a no-op, and the real culprit is `hwdb-test`, which, for some strange reason, sometimes locks up the whole run when executed under ASan. Such run then stops completely responding and even meson's timeout won't help here. Let's disable it, temporarily, until I manage to find out what's really happening.

Also, during debugging of the aforementioned issue I noticed that `test-execute` fails sporadically in the same fashion as it did in Travis (https://github.com/systemd/systemd/issues/10696#issuecomment-758501797), so let's skip it in GH Actions as well.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Dropping the green label, since there's still something fishy going on, which I failed to reproduce in my couple of hundreds of attempts, *sigh*.

**Comment by mrc0mmand** [comment]
> ~~My original `unbuffer` workaround was actually a no-op, and the real culprit is `hwdb-test`, which, for some strange reason, sometimes locks up the whole run when executed under ASan. Such run then stops completely responding and even meson's timeout won't help here. Let's disable it, temporarily, until I manage to find out what's really happening.~~

So, the `hwdb-test` just managed to get into the *debugging crossfire* - it runs fine, unfortunately it runs just around the moment where the machine stops responding. After a yet another debugging session the issue can be worked around by running a simple "watchdog" in the background, which just prints something to the output from time to time (or at least I couldn't reproduce the issue with it anymore). The `unbuffer` workaround indeed helped a bit, but not in every case, unfortunately.

I still have no clue what's happening, and if the issue is in the test suite, meson, GH Actions, or somewhere else. The debugging is quite a challenge, since there's no ssh/other access to the VMs and *printf-debugging* is not a viable option, since it actually mitigates the issue. On the other hand, I at least managed to find a reliable reproducer. So, until I figure out the culprit, let's keep the builds alive using this workaround.

**Review by bluca — APPROVED** [review]
lgtm

**Comment by bluca** [comment]
Is there a ticket to track the underlying issue?

**Comment by mrc0mmand** [comment]
> Is there a ticket to track the underlying issue?

Not yet, so far I've been playing with it in https://github.com/mrc0mmand/systemd/pull/8, but I'll create one once I have at least some clue what's going on.

**Pull request merged**
