### PR TITLE
travis: add missing closing quote sign

### LINKED ISSUE #14127: travis: invalid env var: jobs.include.env TOOL_ARCHIVE="/var/tmp/cov-analysis-$PLATFORM.tgz
travis config check complains:

`invalid env var: jobs.include.env TOOL_ARCHIVE="/var/tmp/cov-analysis-$PLATFORM.tgz`
(note the missing closing quote sign)

https://github.com/systemd/systemd/blob/78af8a798aa9f1100a1228454ff8ebf98ce1b9e5/.travis.yml#L129

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #14127.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @mrc0mmand and @evverx.

**Comment by evverx** [comment]
LGTM. Thank you!

I think ideally `travis lint -x` should be run automatically when PRs are opened. On the other hand, it can't seem to keep up with new features (for example, it failed to recognize the "jobs" section at the time and now judging by "jobs.include.arch: dropping unknown value: s390x" it appears it can't figure out what `s390x` is).

**Comment by evverx** [comment]
Having said that, I don't think `s390x` is used anywhere in the systemd repository so in theory it should be possible to remove `sudo: required`, which according to `travis lint` has no effect anymore, and unleash `travis lint -x` :-) @mrc0mmand what do you think?

**Comment by mrc0mmand** [comment]
As #13785 won't be ready anytime soon, I'm all for adding `travis lint -x` :-)

**Pull request merged**
