### PR TITLE
Drop the -Dvalgrind configuration option

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Review by yuwata — CHANGES_REQUESTED** [review]
Maybe, you forget to stage meson.build ?
E.g. https://github.com/systemd/systemd/blob/2ed35b2f3e183ad6455142bbca455167e3b08f39/meson.build#L1024
https://github.com/systemd/systemd/blob/2ed35b2f3e183ad6455142bbca455167e3b08f39/meson.build#L4612

**Comment by yuwata** [comment]
The following files also need to be updated:
- src/libsystemd/sd-journal/lookup3.c
- src/libsystemd-network/test-dhcp-client.c
- src/test/test-set.c

**Comment by keszybz** [comment]
I'm not sure what happened here. I must have messed up the compile test somehow.

**Comment by poettering** [comment]
lgtm

**Comment by keszybz** [comment]
> lgtm

Hmm, I pushed approx. 1 s before your comment ;)

**Comment by keszybz** [comment]
Ah, wait, I see a thing that needs updating. Will push again in a few minutes. Sorry.

**Comment by keszybz** [comment]
I added one more commit 'sd-journal: use a dynamic check for valgrind'. This should be ready for review now.

**Review by yuwata — APPROVED** [review]
LGTM.

**Review by bluca — APPROVED** [review]

**Pull request merged**
