### PR TITLE
Color support in logs

### PR DESCRIPTION
**Pull request by gnikandrov**
This is a simple patch to support coloring in journalctl and others, inspired by dmesg --color.
I suppose it's pretty straightforward, I tried to keep things similar to color handling in print_multiline().

### CODE REVIEW

**Comment by poettering** [comment]
Uh, I am not entirely sure I like this. We already have color support in journalctl, but it's on purpose used very conservatively: we only highlight high priority log messages in bold or red depending on their priority. The more color we add the less useful color becomes to highlight relevant bits. Or to say this differently: we should use color only where we actually want to highlight stuff, where we have a reason to, and not just because we can highlight it.

**Comment by gnikandrov** [comment]
Well, coloring allows you to distinguish fields at a glance. IMO, dmesg became much easier to read after coloring was added, but that's not even the main reason. While distinguishing fields isn't much of a problem on a single machine (first two fields being the same length), reading journal for several machines with hostnames of different lengths can be quite unpleasant (for each line you have to try to find the fields in order, from the leftmost one). See example (fields are timestamp-hostname-identifier-message, obviously).

Monochrome
Color

Hope I make myself clear.

Anyway, should we perhaps wait for others to speak up? Just ditch the whole thing? Or maybe some extra flag to journalctl will do?

**Comment by benjarobin** [comment]
I really think this is a good thing, the real question is: do we want to enable it by default ?
There is actually no --color option, maybe we should add one:
- The default is the current coloring
 - --color=none for disabling
 - --color=context for more color, or anything like that ?

**Comment by silverwind** [comment]
I'd suggest these options:

- `--color=source` full unmodified coloring from the source as-is
- `--color=priority` current behaviour that just highlights errors
- `--color=none` no colors at all (default when TERM=dumb)

I use colors quite extensively in my apps and colors help me parse logs much faster. I think the default should be `source` coloring, but I could live with having `priority` as the default too.

**Comment by bluca** [comment]
Does https://github.com/systemd/systemd/pull/17702 supersede this?

**Comment by keszybz** [comment]
> Does #17702 supersede this?

Not really.

Hmm, I think this could be useful. It was just forgotten.

**Comment by silverwind** [comment]
I think we need to distinguish colors logged by application in journalctl and colors emitted by journalctl itself, probably by also having separate options for them.

**Comment by keszybz** [comment]
https://github.com/systemd/systemd/pull/23635 implements this is a more flexible way. Let's close this one. (Sorry for not making a decision on this earlier.)

**Pull request closed without merging**
