### PR TITLE
Setup the logger ASAP to fix silent booting. Fixes #919

### LINKED ISSUE #919: inserted module 'ip_tables'
can't get rid of this in any way. what's wrong with the logger?

### PR DESCRIPTION
**Pull request by ninja-**
This commit moves the setup of logging level earlier to make sure it's always respected. @zonque

### CODE REVIEW

**Comment by floppym** [comment]
`log_parse_enviroment` reads from /proc/cmdline. I don't think you can call it before `mount_setup_early`.

**Comment by ninja-** [comment]
good point @floppym , maybe here https://github.com/ninja-/systemd/blob/7620f9b6c580b87e1387f790858f422da973a497/src/core/main.c#L1415

**Comment by floppym** [comment]
That looks reasonable to me.

**Comment by poettering** [comment]
This is wrong, sorry.

The environment variables shall overwrite the config files, hence log_parse_environment() really needs to be called after parse_config_file().

Also, log_parse_environment() reads /proc/cmdline, hence needs to be called after /proc is mounted.

The kernel module loading needs to be done before the mounting of the various file systems though, since they partly cover modules that need to be loaded before mounting them.

This ordering problem is not resolvable hence, and we really should find a different solution for this.

**Comment by ninja-** [comment]
this has been fixed @ master in another way. thanks!

**Pull request closed without merging**
