### PR TITLE
networkd: add support to configure IPv6 MTU

### PR DESCRIPTION
**Pull request by ssahani**

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, how does this relate to the MTU= value we already made configurable?

**Comment by ssahani** [comment]
we are setting MTU=  on link level

here we set the MTU tp ipv6_devconf structure
        .procname       = "mtu",
        .data           = &ipv6_devconf.mtu6,

**Comment by poettering** [comment]
I still wonder what the effective difference is.

@michich, do you know?

**Comment by ssahani** [comment]
The mtu6 variables used when we actually forward the packet
ip6_forward
  ip6_dst_mtu_forward

This patch explains it.
http://patchwork.ozlabs.org/patch/308520/

**Comment by michich** [comment]
> This patch explains it.
> http://patchwork.ozlabs.org/patch/308520/

The parameter is actually much older than this patch. It appeared already in Linux 2.1.89.

I think the reason Linux has this IPv6-specific MTU parameter is that Router Advertisement messages may carry an MTU option that tells the node it should use a lower MTU than it otherwise would (https://tools.ietf.org/html/rfc4861#section-4.6.4).

Here the kernel sets the "mtu6" parameter of the net device to the value received by the neighbor discovery protocol:
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/net/ipv6/ndisc.c?id=v4.2#n1378

Still, the use case for writing to it in /proc/sys/net/ipv6/conf/.../mtu is not clear to me.

**Comment by klausenbusk** [comment]
> Still, the use case for writing to it in /proc/sys/net/ipv6/conf/.../mtu is not clear to me.

I think it make sense to provide a way to change the MTU for IPv6 only (ex: you want a static IPv6 address for your server, and your ISP use 6RD). I have opened a issue to track it: https://github.com/systemd/systemd/issues/8632

**Pull request closed without merging**
