### PR TITLE
man: document some sd-bus functions

### PR DESCRIPTION
**Pull request by mahkoh**
I've just written a program that uses the sd-bus api and had to dig through the libsystemd source code because most sd-bus functions are not documented. This PR contains some of the information I've brought back from there. Some of the claims made in this documentation are only inferred and someone who actually knows how those functions behave should read everything in this PR and correct my mistakes.

### CODE REVIEW

**Comment by mahkoh** [comment]
I've also not documented everything. For example, I've no clue what the `slot` arguments are used for. But having some documentation is better than having none at all.

**Comment by poettering** [comment]
the "slot" concept basically refers to a "handle" for a match or an exposed object or suchlike. 

Basically, a match can either be "floating" (which means it has no slot, and the slot argument when creating the match was NULL), in which case the match sticks around all the time until the bus object itself is destroyed. Or it has a slot  associated. In this the match is created with a non-NULL slot parameter, where the slot is placed into. As long as that slot object stays referenced the match is in effect. As soon as you drop the last reference to the slot object the match will los its effect.

slots are not only used for matches, but for all kinds of cases of "register a method callback function for me, please", e.g. sd_bus_add_object() returns them too.

Hope that makes sense?

**Comment by poettering** [comment]
thanks a ton for doing these docs btw, highly appreciated!

**Comment by keszybz** [comment]
Nice. I marked those functions as done in #235.

**Pull request merged**
