### PR TITLE
docs: import password agents documentation

### PR DESCRIPTION
**Pull request by gdamjan**
imported from:
https://cgit.freedesktop.org/wiki/www/plain/Software/systemd/PasswordAgents.mdwn

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, the links aren't right:

https://github.com/systemd/systemd/blob/67a40f217c8e0f9ecaae3a2088621266f4476ebe/docs/PASSWORD_AGENTS.md

Any chance you can fix the links?

Also, this probably should be in "Interfaces", not "Concepts"

**Comment by poettering** [comment]
ohh, the [[ ]] stuff are not links, they are the opposite of links... i.e. they should just be replaced, as markdown doesn't recognize magic WikiWords

**Comment by gdamjan** [comment]
on it

**Comment by gdamjan** [comment]
BTW, I was thinking that some of the things need to be enclosed in backticks, so to be rendered in monospace font. I'll fix the links first, then add those in a separate commit.

**Comment by keszybz** [comment]
Yeah, more backticks, and more links to stuff like http://man7.org/linux/man-pages/man1/wall.1.html would be nice. A prominent link to https://www.freedesktop.org/software/systemd/man/systemd-ask-password.html would also be nice. But this can be done later.

**Comment by keszybz** [comment]
Hmmm, I used the squash-and-merge button again and I got a non-squashed merge. Either I pressed something different than I think I did, or github completely changed the meaning of that button...

**Comment by gdamjan** [comment]
hm, that pipe in `IN_CLOSE_WRITE|IN_MOVED_TO` got rendered strangely on the web site. It tried to make a table it seems.

**Pull request merged**
