### PR TITLE
What is up with arm

### PR DESCRIPTION
**Pull request by evverx**

### CODE REVIEW

**Comment by evverx** [comment]
@mrc0mmand not that it matters but it looks like when draft PRs are opened GitHub doesn't create the "refs/pull/*/merge" branches. It would probably make sense to fall back to `git checkout & git rebase` in this case.

**Comment by mrc0mmand** [comment]
> @mrc0mmand not that it matters but it looks like when draft PRs are opened GitHub doesn't create the "refs/pull/*/merge" branches. It would probably make sense to fall back to `git checkout & git rebase` in this case.

Interesting, thanks for the hint! That definitely makes sense, will fix it.

**Comment by keszybz** [comment]
CentOS CI seems fine. semaphoreci fails...

**Comment by mrc0mmand** [comment]
Semaphore needs a minor tweaking in config, but unfortunately I don't have an access there. I guess we'll need to wait for @evverx.

**Comment by evverx** [comment]
The point of this PR was to turn on `bionic-arm64` again to see how it goes. Looks like "test_no_options (__main__.JournalTest)" still fails there (and there is an issue about it: https://github.com/systemd/systemd/issues/11104). @martinpitt @xnox would it be possible to skip that test on `arm` so that it won't be necessary to turn it off?

Regarding draft PRs vs Semaphore :-), @poettering @keszybz can you invite @mrc0mmand to the systemd organization on Semaphore? I'm sure @mrc0mmand will get round to it much faster that me.

**Comment by evverx** [comment]
I forgot I'm an admin there :-) @mrc0mmand I invited you to the organization (at least I hope I did it :-))

**Comment by mrc0mmand** [comment]
> I forgot I'm an admin there :-) @mrc0mmand I invited you to the organization (at least I hope I did it :-))

Yup, just got the invite, thank you!

**Comment by mrc0mmand** [comment]
The compilation in semaphore is finally running, but the oneliner it now uses is pretty disgusting

image

I'll open a PR and move it to a separate script as it's done for the next two steps:

image

**Comment by evverx** [comment]
That one-liner is there to make sure that all PRs are rebased on top of master. If you move it to a separate script semaphore will be red for a week or so until everybody rebase their PRs manually (which I think is annoying). Let's just live with that :-)

**Comment by mrc0mmand** [comment]
Ah, good point, let's leave it this way then.

**Comment by evverx** [comment]
What would be great though is [to join these two scripts together](https://github.com/systemd/systemd/pull/11814#issuecomment-466997742).

**Comment by mrc0mmand** [comment]
> What would be great though is [to join these two scripts together](https://github.com/systemd/systemd/pull/11814#issuecomment-466997742).

So I guess a similar thing we did with the Travis [managers](https://github.com/systemd/systemd/blob/master/travis-ci/managers/debian.sh).

**Comment by evverx** [comment]
Exactly. But on semaphore we don't even need to create the "SETUP" and "RUN" stages. We could just paste `gcc-compilation.sh` at the end of `setup.sh` (removing the variables that are set over and over again) and rename it to `run.sh`.

**Comment by mrc0mmand** [comment]
Will look into that. Also, semaphore is finally passing, so we've fixed *everything* except the reason why this PR was created in the first place!

**Comment by evverx** [comment]
I turned it on mainly because I wanted to find out how it fares in https://github.com/systemd/systemd/pull/12151 (where `libbpf` is being introduced). As Ubuntu CI keeps failing and doesn't support submodules and it wasn't possible to get it around by using meson wraps (due to `--wrap-mode=nodownload`) I'll go ahead and turn it off again shortly.

**Pull request closed without merging**
