### PR TITLE
gpt-auto-generator: don't wait for udev

### PR DESCRIPTION
**Pull request by poettering**
Generators run in a context where waiting for udev is not an option,
simply because it's not running there yet. Hence, let's not wait for it
in this case.

This is generally OK to do as we are operating on the root disk only
here, which should have been probed already by the time we come this
far.

An alternative fix might be to remove the udev dependency from image
dissection again in the long run (and thus replace reliance on
/dev/block/x:y somehow with something else).

Fixes: #11205

### CODE REVIEW

**Comment by poettering** [comment]
hmm, there's something not right here...

**Comment by poettering** [comment]
Pushed a new version, that performs better.

**Comment by asavah** [comment]
This PR indeed solves the issue, however I'm getting this:
```
Dec 19 20:19:44 msib450ig systemd-gpt-auto-generator[213]: Assertion 'd' failed at ../../../src/systemd/src/shared/dissect-image.c:164, function wait_for_partitions_to_appear(). Aborting.
Dec 19 20:19:44 msib450ig systemd[203]: /usr/lib/systemd/system-generators/systemd-gpt-auto-generator terminated by signal ABRT.
```
"Newer" version was used to do a runtime test.

**Comment by poettering** [comment]
@asavah please have a look at the version i now pushed!

**Comment by asavah** [comment]
@poettering much better now, clean and fast boot and no asserts, thanks!

**Pull request merged**
