### PR TITLE
machine: increase timeouts in attempt to fix #35115

### LINKED ISSUE #35115: TEST-13-NSPAWN.machined is flaky
Added by PR https://github.com/systemd/systemd/pull/34472

```
03:42:24 [   26.982193] TEST-13-NSPAWN.sh[526]: + varlinkctl call /run/systemd/machine/io.systemd.Machine io.systemd.Machine.Kill '{"name":"long-running", "whom": "leader", "signal": 5}'
03:42:24 [   26.986561] TEST-13-NSPAWN.sh[1273]: {}
03:42:25 [   26.986935] TEST-13-NSPAWN.sh[526]: + timeout 30 bash -c 'until test -e /var/lib/machines/long-running/trap; do sleep .5; done'
03:42:25 [   56.991686] TEST-13-NSPAWN.sh[526]: + at_exit
```

https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-vagrant-archlinux/18949/console

### PR DESCRIPTION
**Pull request by ikruglov**
An attempt to fix https://github.com/systemd/systemd/issues/35115

cc @bluca

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Review by yuwata — COMMENTED** [review]
Hm... I do not think terminating container takes more than 10 seconds, even if the test environment is slow...
Or, do you observe something that the container is actually terminating but it just timed out because of slow test environment?

**Comment by ikruglov** [comment]
> Hm... I do not think terminating container takes more than 10 seconds, even if the test environment is slow... Or, do you observe something that the container is actually terminating but it just timed out because of slow test environment?

(from the original issue)
```
03:42:24 [   26.982193] TEST-13-NSPAWN.sh[526]: + varlinkctl call /run/systemd/machine/io.systemd.Machine io.systemd.Machine.Kill '{"name":"long-running", "whom": "leader", "signal": 5}'
03:42:24 [   26.986561] TEST-13-NSPAWN.sh[1273]: {}
03:42:25 [   26.986935] TEST-13-NSPAWN.sh[526]: + timeout 30 bash -c 'until test -e /var/lib/machines/long-running/trap; do sleep .5; done'
03:42:25 [   56.991686] TEST-13-NSPAWN.sh[526]: + at_exit
```

the control loop timed out after 30s. I don't know if the container actually died.

**Comment by yuwata** [comment]
Yes, I know the issue. But, we (at least I) do not know if the container actually received the signal and started to handle it correctly. If the container does not receive the signal for some reasons, then extending the timeout is meaningless. We should investigate the root cause of the issue at first.

**Comment by yuwata** [comment]
I think, enabling debugging logs for systemd-nspawn@.service should be the first step.

**Comment by ikruglov** [comment]
> I think, enabling debugging logs for `systemd-nspawn@.service` should be the first step.

sorry, I'm new but I can't find io-systemd-Job-List 

> I think, enabling debugging logs for `systemd-nspawn@.service` should be the first step.

ahm.. there is no such service. Which one did you mean @yuwata? Or I'm missing something?

**Comment by yuwata** [comment]
> > I think, enabling debugging logs for `systemd-nspawn@.service` should be the first step.
> 
> ~ahm.. there is no such service. Which one did you mean @yuwata? Or I'm missing something?~
> 
> UPD: ignore me, found it

Good to hear that. Sorry for late response.

**Comment by bluca** [comment]
Any update on this?

**Review by bluca — APPROVED** [review]
Let's merge this for now, and see if it makes things better, in general CI can be very slow so this usually helps

**Pull request merged**
