### PR TITLE
event hwdb fix for Lenovo ThinkPad E540

### PR DESCRIPTION
**Pull request by sphakka**
Synaptics touchpad edge fix for Lenovo ThinkPad E540

### CODE REVIEW

**Comment by poettering** [comment]
@whot please have a look

**Comment by whot** [comment]
we already have a fix for the whole *40 generation, see line 250 after # Lenovo *40 series. That sets the resolution only because those touchpads used to be accurate for axis ranges. @sphakka -does this one not apply to your box?

**Comment by sphakka** [comment]
Apparently the default *40 set up gives too much range on my E540: I had to trim it down as was getting "outside expected range" errors with libinput-v1.6.2, xf86-input-libinput-v0.24.0 (Gentoo builds)...

**Comment by whot** [comment]
@sphakka huh, that can't be right. I have a T440 here which in theory is the same hardware and the axis ranges are larger than what you submitted. Since libinput only complains when you're outside the ranges, this can't happen.

What's the axis range without your hwdb entry, and is anything but the resolution applied to the device? evemu-describe and udevadm info /sys/class/input/eventX

**Comment by sphakka** [comment]
Indeed there's something fishy. So, I checked again.

Original hwdb setup (no edge correction):
```
# udevadm info /sys/class/input/event1
P: /devices/platform/i8042/serio1/input/input2/event1
N: input/event1
S: input/by-path/platform-i8042-serio-1-event-mouse
E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-1-event-mouse
E: DEVNAME=/dev/input/event1
E: DEVPATH=/devices/platform/i8042/serio1/input/input2/event1
E: ID_INPUT=1
E: ID_INPUT_HEIGHT_MM=83
E: ID_INPUT_TOUCHPAD=1
E: ID_INPUT_WIDTH_MM=105
E: ID_PATH=platform-i8042-serio-1
E: ID_PATH_TAG=platform-i8042-serio-1
E: ID_SERIAL=noserial
E: LIBINPUT_DEVICE_GROUP=11/2/7/1b1:isa0060/serio1
E: LIBINPUT_MODEL_SYNAPTICS_SERIAL_TOUCHPAD=1
E: MAJOR=13
E: MINOR=65
E: SUBSYSTEM=input
E: USEC_INITIALIZED=4493366
```
which causes (Xorg):

    [  1495.462] (II) Axis 0x35 value 1032 is outside expected range [1043, 5895]

I did again the edge test (it's really that smaller: 100x70, though my previous measurement was done on a wrong 100x75 basis, sorry for that):
```
# touchpad-edge-detector 100x70 /dev/input/event1
Touchpad SynPS/2 Synaptics TouchPad on /dev/input/event1
Move one finger around the touchpad to detect the actual edges
Kernel says:	x [1264..5675], y [1171..4688]
Touchpad sends:	x [1025..5110], y [2021..4832] /^C

Touchpad size as listed by the kernel: 105x83mm
User-specified touchpad size: 100x70mm
Calculated ranges: 4085/2811

Suggested udev rule:
# <Laptop model description goes here>
evdev:name:SynPS/2 Synaptics TouchPad:dmi:bvnLENOVO:bvrJ9ET9EWW(2.24):bd09/23/2016:svnLENOVO:pn20C6003AMZ:pvrThinkPadEdgeE540:rvnLENOVO:rn20C6003AMZ:rvr0B98401PRO:cvnLENOVO:ct10:cvrNotAvailable:*
 EVDEV_ABS_00=1025:5110:41
 EVDEV_ABS_01=2021:4832:40
 EVDEV_ABS_35=1025:5110:41
 EVDEV_ABS_36=2021:4832:40
```
No more out-of-range messages from Xorg. However, the behavior is quite different! Please note that the "soft buttons" are supposed to be on the _top_ edge, where the red and dotted marks are.

**Original:** buttons are mapped to the _bottom_ edge; the full pad surface (button area included) is available to the pointer irrespective of the gesture.

**Patched:** buttons are mapped to both the bottom and top edges; the pad surface is fully available if the gesture starts _away_ from the button area (top or bottom edge), but if the gesture crosses the _top_ edge (f.i., sliding the finger from the middle upwards and off the top edge, or in reverse direction), sometimes the pointer is lost and I need to tap in the middle to get it back.

All in all, the **original** set up looks better, apart from the inverted soft buttons mapping -- should I file a bug for that? The informational out-of-edge messages still persist but look harmless... Let me know if you need further tests. Otherwise you can ignore this merge request.

**Comment by whot** [comment]
weird, this range is actually set by the kernel (see kernel commit bce4f9e764c36bc35dd5c), I've now contacted the author of that patch to verify those ranges. I suspect it may just be out and needs re-measuring. easiest would be to overwrite this in systemd but I'd like to wait for a response first. Ping me if this is still open in a week.

as for the buttons: this generation of touchpads are special and has *two* sets of software buttons, the top ones which 'belong' to the trackpoint and the bottom ones which are configurable.  See https://wayland.freedesktop.org/libinput/doc/latest/clickpad_softbuttons.html and https://wayland.freedesktop.org/libinput/doc/latest/t440_support.html. The behaviour should be described there too but basically: a touch starting inside the button areas doesn't move the pointer.

**Comment by bsagal** [comment]
This is the dmesg with full detail of the touchpad i tested with, and created the kernel patch:

`psmouse serio1: synaptics: Touchpad model: 1, fw: 8.1, id: 0x1e2b1, caps: 0xd001a3/0x940300/0x12f800, board id: 2964, fw id: 2560`

Does your touchpad have the same information?

**Comment by sphakka** [comment]
@whot, thanks for the info. I understand that losing the pointer when crossing the top buttons area is a feature ("dead finger"?), though I find it pretty annoying -- I'll try to disable the trackstick...

@bsagal, my HW looks the same indeed. Here's the dmesg output:
```
psmouse serio1: synaptics: queried max coordinates: x [..5112], y [..3834]
psmouse serio1: synaptics: queried min coordinates: x [1024..], y [1024..]
psmouse serio1: synaptics: quirked min/max coordinates: x [1264..5675], y [1171..4688]
psmouse serio1: synaptics: Touchpad model: 1, fw: 8.1, id: 0x1e2b1, caps: 0xd001a3/0x940300/0x127c00/0x0, board id: 2722, fw id: 1484859
```
BTW,  what's this "quirked" range?

**Comment by bsagal** [comment]
@sphakka  There is a firmware problem with the thinkpad *40 touchpads that they report the wrong size, the queried range is the overridden range from kernel.

Looks like you have a different  board id: and fw id: to mine. That could explain the different range.

**Comment by whot** [comment]
ok, the rabbit hole goes deeper.

Background: those devices shipped with bogus axes  in the first iteration but mostly corrected them in the second iteration (I think @bsagal's device may be from the second iteration).

The kernel goes by PNPID which is shared with other touchpads, the LEN2003 is shared by the E440 and the E540 and apparently those have different ranges. The PNPID didn't change in the second iteration though so we quirk by board ID.

The kernel applies a different range for board IDs <= 2691, see kernel commit 98dc07037. @bsagal's commit came before the board ID detection and applies to anything higher.

Right now, our ranges are
* fw <= 2691: x [1024..5054] y [2457..4832]
* fw higher: x [1264..5675] y [1171..4688]

So we need a kernel patch here for the 2722 range:

* fw <= 2772: x [1024..5112] y [2021..4832]

@sphakka: look at kernel commit 98dc0703735d9cfc483522d5ffbce0c0b07c1f86, it's the blueprint for what you have to do. Bonus points for sending that to the lkml and getting everything upstream. This should be CC stable too. Riches and fame guaranteed ;) also, if you do that, run the touchpad-edge-detector a few times because you really don't want to get the ranges wrong :)

Either way, this must be a kernel fix because we don't have access to the board id in userspace and there are already quirks for these devices in the kernel. Once it's in there and the existing *40 quirk doesn't apply, we can add that one for resolution but the axis ranges need to be quirked in the kernel.

**Pull request closed without merging**
