### PR TITLE
core/cgroup: Apply IODevice*= directives in configured order

### LINKED ISSUE #34126: When multiple IOReadBandwidthMax values are configured, the effective configuration does not comply with common rules
### systemd version the issue has been seen with

255

### Used distribution

NA

### Linux kernel version used

NA

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

8:0 rbps=18878 wbps=max riops=max wiops=max

### Unexpected behaviour you saw

8:0 rbps=18879 wbps=max riops=max wiops=max

### Steps to reproduce the problem

```
[root@localhost system.slice]# systemctl cat testcg
# /usr/lib/systemd/system/testcg.service
[Unit]
Description=test

[Service]
IOReadBandwidthMax=/dev/sda1 18879
IOReadBandwidthMax=/dev/sda2 18878
ExecStart=/usr/bin/sleep 1000

[Install]
WantedBy=multi-user.target
```
1. systemctl start testcg
2. cat /sys/fs/cgroup/system.slice/testcg.service/io.max

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
8:0 means /dev/sda.

[root@localhost system.slice]# lsblk
NAME             MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda                8:0    0  100G  0 disk
├─sda1             8:1    0  600M  0 part /boot/efi
├─sda2             8:2    0    1G  0 part /boot
└─sda3             8:3    0 98.4G  0 part
  ├─euleros-root 253:0    0   61G  0 lvm  /
  ├─euleros-swap 253:1    0  7.7G  0 lvm  [SWAP]
  └─euleros-home 253:2    0 29.8G  0 lvm  /home
sr0               11:0    1  1.2G  0 rom
```

### PR DESCRIPTION
**Pull request by Werkov**
Different device paths may resolve to same device node (lookup_block_device()), e.g.
        IOReadBandwidthMax=/dev/sda1 18879
        IOReadBandwidthMax=/dev/sda2 18878
where both partitions resolve to /dev/sda and when these values are applied (they are associated with original paths, i.e. as if applied for different device) in the order from io_device_limits.

The parsing code prepends, so they end up in reverse order wrt config file. Switch the direction so that the order of application matches the order of configuration -- i.e. semantics in all other unit file directives.

Apply same change to all directives that use per-device lists. (The question whether partitions should be resolved to base device is independent.)

Fixes #34126

Thanks for the accurate analysis @JetXujing! Would you mind reviewing this fix?

### CODE REVIEW

**Comment by JetXujing** [comment]
lgtm

**Review by yuwata — APPROVED** [review]
LGTM.

**Review by yuwata — CHANGES_REQUESTED** [review]
Uh, I forgot. Please also update dbus-cgroup.c.

Also, could you add a simple test case ?

**Comment by Werkov** [comment]
Thanks for the reviews. Good catch with DBus inputs -- force pushed a fix.

Re: testing -- this would need to check the actual value written to cgroupfs (`systemctl show -p` would list all configured values before device resolution), is it relieable to presume existence of `/dev/sdaN` partitions inside the testing image?

**Comment by yuwata** [comment]
> Re: testing -- this would need to check the actual value written to cgroupfs (`systemctl show -p` would list all configured values before device resolution), is it relieable to presume existence of `/dev/sdaN` partitions inside the testing image?

If it is not simple, then I think it is OK.
Note, TEST-64 have several block devices, so maybe you can use the test, though the test is mostly for udevd. You can sneak cgroup test cases into the test. Or, maybe do something similar in TEST-19-CGROUP.

**Review by yuwata — APPROVED** [review]
The code change LGTM.

**Review by yuwata — APPROVED** [review]
LGTM.

**Comment by poettering** [comment]
btw, i think it would be really nice to warn about this case, i.e. when we are resolving the device nodes before writing to the cgroup attr, collect major/minor pairs in a Set and warn if we see duplicates. After all, this is most likely a misconfiguration. It's nice to behave systematic in case of misconfiguration, but it#s even nicer to warn about misconfiguration.

**Pull request merged**
