### PR TITLE
units: install dbus-org.freedesktop.resolve1.service alias

### LINKED ISSUE #14220: dbus-org.freedesktop.resolve1.service alias was lost in meson conversion
The old build scripts created a symlink `/usr/lib/systemd/system/dbus-org.freedesktop.resolve1.service` -> `systemd-resolved.service`

https://github.com/systemd/systemd/blob/d60c527009133a1ed3d69c14b8c837c790e78d10/Makefile.am#L5608-L5610

This has been lost in the meson conversion:

https://github.com/systemd/systemd/blob/cb515608030fe05f4a46ed32e1cd30aaca6e3381/units/meson.build#L150-L151

Equivalent snippet for `hostname1`:

https://github.com/systemd/systemd/blob/d60c527009133a1ed3d69c14b8c837c790e78d10/Makefile.am#L4977

https://github.com/systemd/systemd/blob/cb515608030fe05f4a46ed32e1cd30aaca6e3381/units/meson.build#L187

As `dbus-org.freedesktop.resolve1.service` is referenced from `system-services/org.freedesktop.resolve1.service`, e.g. resolvectl fails with
`Failed to get global data: Unit dbus-org.freedesktop.resolve1.service not found.`

See also
- https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1795852
- https://bugs.archlinux.org/task/61738

### PR DESCRIPTION
**Pull request by fsateler**
In the autotools->meson conversion, this alias was lost.

Fixes #14220

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, what about @mbiebl's comments over on https://github.com/systemd/systemd/issues/14220#issuecomment-568682620

I think @mbiebl is right: we stopped creating these links. Yes, we accideintly might have dropped the link earlier but it looks wrong to readd it now. Right @keszybz?

**Comment by fsateler** [comment]
I believe dbus aliases are semantically different than multi-user.wants.d symlinks. Names should not change due to install state (unless the name is "special" like display-manager.service)

**Comment by poettering** [comment]
But we want to make sure that resolved is only activated when it is enables, thus we install the dbus symlink via `[Install]` and have the dbus-x.y.yz.service alias concept at all...

**Comment by fsateler** [comment]
OK, I guess that makes sense. We do install other aliases though (machined, localed, and more), I wonder if those should be removed then.

The error message on resolvectl should be improved if the alias is not reinstated.

**Comment by poettering** [comment]
those other services don#t support "systemctl enable", i.e. we ship no [install] for them.

**Comment by poettering** [comment]
I think all is cleared up here now, and we can close this, no?

**Pull request closed without merging**
