### PR TITLE
Hwdb update and sorting

### PR DESCRIPTION
**Pull request by keszybz**
This adds a pyparsing-based implementation of the OUI/PCI/USB/SDIO hwdb files generator. Entries in the hwdb files are sorted alphabetically by the key and duplicate entries are dropped.

I'm not too happy with this PR: the original generator was in perl. I'd like to get rid of perl as a build dependency (we only use it for this and two test scripts). It seems like a good chance to rewrite this, before doing significant changes. First I rewrote the generator in Python keeping the same approach, but it was only slightly shorter than the perl version and didn't feel very clear. Then I decided to write a grammar, hoping for a shorter and more maintaineable implementation. In the end, the result is slightly shorter, but runs quite slowly. I think that the generation of hwdb files is now much clearer (the generation is not interleaved with parsing anymore).

This does not include the last step of dropping the old script and updating the meson rule. I'll do that if the general approach is deemed acceptable.

### CODE REVIEW

**Comment by keszybz** [comment]
Oh, and I forgot to say, that the result of sorting will be apparent after we wait a few months and generate a new update. Right now the sorting doesn't really do anything apart from dropping a few duplicate lines.

**Comment by poettering** [comment]
looks all good to me.

hmm, currently the parser doesn't do the acpi/pnp bits. Wouldn't it make sense to add that too, so that we have the same pipeline for everything, get things sorted properly, and so on?

**Comment by keszybz** [comment]
Yeah, makes sense. But maybe as separate PR.

**Comment by keszybz** [comment]
The acpi stuff is already sorted... And the data is scraped from HTML. I don't think it makes sense to re-code this, so I'll just leave things as they are for now.

**Pull request merged**
