### PR TITLE
seccomp: remove '@credentials' syscall set

### PR DESCRIPTION
**Pull request by tixxdz**
Most of these syscalls are simple that we do not want to filter them.
They work on the current calling process, doing only read operations,
they do not have a deep kernel path.

The problem may only be in 'capget' syscall since it can query arbitrary
processes, and used to discover processes, however sending signal 0 to
arbitrary processes can be used to discover if a process exists or not.
It is infortunate that Linux allows to query processes of different
users. Lets put it now in '@process' syscall set, and later we may add
it to a new '@basic-process' set that allows most basic process
operations.

### CODE REVIEW

**Comment by tixxdz** [comment]
This PR solves the `@credentials` point discussed here: https://github.com/systemd/systemd/issues/6955

**Comment by poettering** [comment]
I am not sure I agree. information leakage is leakage too. Yes, in most cases leaking the UID and things like that isn't too much of a loss, but still i don't see the real need to not have a group for these syscalls, given how similar they are.

Note that syscall groupings have a number of purposes:

1. for whitelisting them explicitly
2. for blacklisting them explicitly
3. as a quick way to assemble other groups

And I am pretty sure item 3 in the list above is reason enough to keep it: if you put together a more complex filter or group then it makes a ton of sense to just these syscalls with a brief moniker than listing them always individually.

Hence, I am really not convinced what you are proposing here is that clear cut, and that having this group would really hurt...

**Comment by tixxdz** [comment]
Yes, grouping them has its own benefit, my main goal is that users should not have to allow them explicitly. If we add a group for them then later if we are running in whitelisting mode for RootImage= or any future extension, or if users are using a whitelist sandbox mode, then they will have to remember to add this group explicitly.

These syscalls are used by libraries, shells scripts `$$` , most of the services out there use these syscalls one way or another, etc.

I agree on the grouping points, but for information leakage they work on current process, I guess nothing to hide there.

Hmm some syscalls in `@default` have more side effects than these ones, hmm I really think that these should be available, what if we add `@basic` group and import this group then ?

**Comment by tixxdz** [comment]
or import this `@credentials` group directly into `@default` ?

**Comment by poettering** [comment]
Hmm, so I thought a bit about this. I noticed two things:

1. libc says these syscalls cannot fail (see man page), and getuid() and friends hence have no way to propagate any failures regarding these issues, hence we should not make them fail ever I figure.
2. much information is available in getauxval(), hence the leaking argument doesn't make sense I figure, as the information is provided for free without involving any syscalls anyway...

I am withdrawing my doubts hence. Let's merge this.

**Comment by poettering** [comment]
hmm, this is actually lacking an update to src/nspaw/nspawn-seccomp.c, too, as it uses the group.

**Comment by poettering** [comment]
and an update for NEWS would be good too

**Comment by keszybz** [comment]
If you could also mention in the commit message that this group was added in `v234-468-gcd0ddf6f75`, so there's no compatibility break.

**Comment by tixxdz** [comment]
@poettering @keszybz oups, ok will do it , thank you!

**Comment by tixxdz** [comment]
pushed, please check again, thanks!

**Comment by poettering** [comment]
NEWS entry of `@credentials` is still there, no?

**Comment by tixxdz** [comment]
Indeed, fixed again, thank you!

**Pull request merged**
