### PR TITLE
build: fix overlinking

### PR DESCRIPTION
**Pull request by michich**
Avoid overlinking to libdw, libcap, libdl.

### CODE REVIEW

**Comment by michich** [comment]
Semaphore broken? It failed early, before it set up the build environment.

**Comment by zonque** [comment]
> Semaphore broken? It failed early, before it set up the build environment.

restarted.

**Comment by poettering** [comment]
Looks fine to me... Seems Semephore insists on being broken though...

**Comment by martinpitt** [comment]
Indeed http://ppa.launchpad.net/beineri/opt-qt541-trusty/ubuntu/dists/trusty/main/binary-amd64/Packages does not exist any more -- this corresponds to https://launchpad.net/~beineri/+archive/opt-qt541-trusty which apprently got removed. Why do we need a Qt backport for systemd semaphore anyway?

If you need it, then I guess we need to move it to https://launchpad.net/~beineri/+archive/ubuntu/opt-qt542-trusty? @zonque

**Comment by poettering** [comment]
qt? as dep of our stuff? that's kinda surprising...

**Comment by zonque** [comment]
Right. What's pulling that in?

**Comment by martinpitt** [comment]
@zonque : Oh, I thought you knew as you had control over that environment and the recipes? I. e. didn't you add my PPA for the util-linux backport too? Or maybe something over at semaphoreci.com just went broken?

**Comment by zonque** [comment]
Ok, that's an apt source Semaphore installs by default. We don't need that and never did. I'm now removing the apt file before running `apt-get update` to fix this.

**Pull request merged**
