### PR TITLE
Tag DRM devices with *systemd*

### PR DESCRIPTION
**Pull request by paulmenzel**

### CODE REVIEW

**Comment by paulmenzel** [comment]
My Weston problem turned out to be a different issue, so I personally don’t need this ordering. No idea, if the change is still useful, or if that would harm overall performance – from `man udev`:

>       TAG […] The implementation can only work efficiently if only a few tags are attached to a device. It is only meant to be used in contexts with specific device filter requirements, and not as a general-purpose flag. Excessive use might result in inefficient event handling.

**Comment by poettering** [comment]
we should be careful with tagging too many devices needlessly. unless there is a good generic reason to do this on all systems i'd really avoid it. tagging comes at a price (bloom filter in the udev msgs gets too crowded), we should use them but not as if they were free.

**Comment by poettering** [comment]
Let's close this for now, unless there's some scenario that makes this really desirable to have in the default rules files. I hop that's OK?

**Comment by paulmenzel** [comment]
Sure, no problem.

**Pull request closed without merging**
