### PR TITLE
test: skip TEST-17 on ubuntu ppc64el

### LINKED ISSUE #21603: TEST-17-UDEV randomly fails on Ubuntu ppc64el
E.g. https://autopkgtest.ubuntu.com/results/autopkgtest-focal-upstream-systemd-ci-systemd-ci/focal/ppc64el/s/systemd-upstream/20211202_024112_d0130@/log.gz

I am not sure the failure is a simple timeout or not.

### PR DESCRIPTION
**Pull request by yuwata**
The test fails without syncing /run/udev before checking its contents.
This should be a testing emvironment issue, instead of a issue on udev.

C.f. #22357.

Fixes #21603.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @mrc0mmand and @bluca I am not familiar with how to skip specific tests on Ubuntu CI. Please let me know when I made something wrong.

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
Is this a kernel bug? Or a virtualization environment bug?

**Comment by yuwata** [comment]
> Is this a kernel bug? Or a virtualization environment bug?

Still I am not sure. But I cannot find anything on baremetal kernel feature. I guess the issue is on nested KVM or any other virtualization environment stuff.

**Comment by bluca** [comment]
> > Is this a kernel bug? Or a virtualization environment bug?
> 
> Still I am not sure. But I cannot find anything on baremetal kernel feature. I guess the issue is on nested KVM or any other virtualization environment stuff.

Ok, let's try again once Ubuntu 22.04 ships and we rebase on that

**Comment by yuwata** [comment]
Sure. Extended the commit message. PTAL.

**Pull request merged**
