### PR TITLE
IN_SET() compile time check fixes

### PR DESCRIPTION
**Pull request by poettering**
An attempt for a fix for #10332.

@evverx could you give this a whirl? for me ubsan doesn't detect anything with this, but maybe my ubsan is too old.

### CODE REVIEW

**Comment by evverx** [comment]
UBSan is still complaining, but I think it's a false positive because the following code (which doesn't have any issues, as far as I can tell) triggers the overflow:
```sh
$ cat TEST.c
#include "stdint.h"

int main(int argc, char *argv[]) {
	int64_t i = 1;
	switch (i) {
		case INT64_MIN + 1:
		case INT64_MIN + 2:
			return 1;
		default:
			return 0;
	}
}

$ gcc  -fsanitize=undefined ./TEST.c
$ ./a.out
<unknown>: runtime error: signed integer overflow: 1 - -9223372036854775807 cannot be represented in type 'long int'
```
Besides, the same code compiled with `clang version 8.0.0 (trunk 343342)` works fine in the sense that UBSan stays silent.

The only way to get around this I've come up with is to put `return` after the first case statement, so, in theory, the macro could be changed so that it would generate something like `case A: found=true; break; case B: found=true; break` instead of `case A: case B: found=true; break`, but, to be honest, I'm not sure it's worth the hassle.

**Comment by yuwata** [comment]
Though this does not fixes #10332, using `long double` seems nice.

**Comment by poettering** [comment]
Yeah, so even if this doesn't fix #10332, I think we should still merge this PR, if it looks fine otherwise...

**Comment by evverx** [comment]
Sure, I have no problem with that :-) Meanwhile, I've just opened https://github.com/systemd/systemd/pull/10374 where I replaced `IN_SET` with `||`.

**Pull request merged**
