### PR TITLE
meson: we cannot call get_compiler('cpp') if we didn't "add" it

### PR DESCRIPTION
**Pull request by keszybz**
Follow-up for f6d783ac3d145f3f3ffc2023d4ad90f76cf7fe34.

/cc @yuwata

### CODE REVIEW

**Comment by poettering** [comment]
thanks, this makes mkosi -if work for me again

**Comment by yuwata** [comment]
@keszybz Thanks. lgtm.

**Comment by poettering** [comment]
merged, since it unbreaks my build. if there's more get_compiler() stuff to fix, please do so in a separate PR

**Comment by keszybz** [comment]
> BTW, there are two more get_compiler('cpp') for fuzzer. Do they need to be conditionalized? 

I'll submit a PR.

> Why they use 'cpp' instead of 'c'?

Those are C++ libraries and ... I guess the whole process requires C++.

**Pull request merged**
