### PR TITLE
2 small fixes, stopping mount and service units

### PR DESCRIPTION
**Pull request by sourcejedi**
These are the first two commits in my PR #6623.

My other PR has not been resolved, but not because of these commits.  The commits stand on their own, so I'm splitting them out for review as such.  My other PR does not have a hard dependency on these changes, so it's also not a big problem if these two commits need a little re-working.  Thanks :).

### CODE REVIEW

**Comment by keszybz** [comment]
rawhide — `Assertion 'cg_pid_get_path(NULL, 0, &cgroup_root) >= 0' failed at ../src/test/test-helper.c:29, function enter_cgroup_subroot(). Aborting.`

xenial-amd64 — KMV hardware error, can be ignored.

xenial-s390x —
```
checking that there are no running jobs
running jobs after remaining timeout -1: 545 systemd-localed.service start running
autopkgtest [09:55:37]: test boot-smoke: -----------------------]
autopkgtest [09:55:37]: test boot-smoke:  - - - - - - - - - - results - - - - - - - - - -
boot-smoke           FAIL non-zero exit status 1
```

**Comment by keszybz** [comment]
Ah, we fixed at least the rawhide error a while back. Please rebase onto latest master.

**Comment by sourcejedi** [comment]
Thanks!!

**Comment by sourcejedi** [comment]
Rebased w/o conflicts.

**Comment by keszybz** [comment]
`xenial-amd64` fails the same as before, `xenial-s390x` now fails with `zipl not found`.

**Pull request merged**
