### PR TITLE
mkosi: Adapt configuration to take into account configuration rework

### PR DESCRIPTION
**Pull request by daandemeyer**
In https://github.com/systemd/mkosi/pull/2847, the '@' specifier is
removed, CLI arguments take priority over configuration files again
and the "main" image is defined at the top level instead of in
mkosi.images/. Additionally, not every setting from the top level
configuration is inherited by the images in mkosi.images/ anymore,
only settings which make sense to be inherited are inherited.

This commit gets rid of all the usages of '@', moves the "main" image
configuration from mkosi.images/system to the top level and gets rid
of various hacks we had in place to deal with quirks of the old
configuration parsing logic.

We also remove usages of Images= and --append as these options are
removed by the mentioned PR.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by evverx** [comment]
Looks like something is broken somewhere again:
```sh

ERROR: Directory is not empty and does not contain a previous build:
/work/build
error: Bad exit status from /var/tmp/rpm-tmp.d9CYZc (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.d9CYZc (%build)
‣ "/work/build-script" returned non-zero exit code 1.
‣  (Fixing ownership of package manager cache directory)
```

**Comment by DaanDeMeyer** [comment]
@evverx Can you try rebuilding with `-ff`? And if that doesn't work get me the full logs? Hard to operate on just what you gave me here.

**Comment by evverx** [comment]
It seems it can be "fixed" by removing `-E WIPE=1` from the command line. I'll attach a bit later.

**Comment by DaanDeMeyer** [comment]
That's enough for me to work with, I'll try and come up with a fix.

**Pull request merged**
