### PR TITLE
meson: add version.h dependency to more components

### PR DESCRIPTION
**Pull request by mrc0mmand**
Follow-up to c47511da7e2bab1a429fc1958a73d3f426ebb3da.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by mrc0mmand** [comment]
The verification might take a bit, as CentOS CI is FUBAR due to RHEL 8.7 being released which introduced some... incompatibilities in the CI provisioning stuff.

**Comment by mrc0mmand** [comment]
Ah, I see, this is another game of whack-a-mole, lemme grab my hammer...

**Comment by mrc0mmand** [comment]
Looks like meson is finally content, PTAL.

**Review by bluca — APPROVED** [review]

**Comment by keszybz** [comment]
Thanks!

LGTM.

**Comment by mrc0mmand** [comment]
Feel free to ignore the C8S job, that's just AWS stealing our CPU time again...

**Pull request merged**
