### PR TITLE
add editorconfig configuration

### PR DESCRIPTION
**Pull request by eworm-de**
We want indention with spaces, so specify in editorconfig.
http://editorconfig.org/

### CODE REVIEW

**Comment by zonque** [comment]
Interesting project, about time for some unified configuration of such project-level details.

**Comment by zonque** [comment]
We have a `.vimrc` as well, so let's merge this. If it turns out to be a dead horse, we can remove it again.

**Comment by zonque** [comment]
Ah, this needs to be added to `EXTRA_DIST` in `Makefile.am` however. Care to amend the PR, please?

**Comment by eworm-de** [comment]
Updated the PR:
- Added `trim_trailing_whitespace = true`
- added to `EXTRA_DIST` in `Makefile.am`

**Comment by eworm-de** [comment]
BTW, adding `set exrc` to `~/.vimrc` is a security risk. Perhaps we should mention `set secure` as well?

**Comment by zonque** [comment]
> BTW, adding set exrc to ~/.vimrc is a security risk. Perhaps we should mention set secure as well?

Sure, go ahead.

**Pull request merged**
