### PR TITLE
Add HP Elitebook 2760p ACCEL_MOUNT_MATRIX

### PR DESCRIPTION
**Pull request by AlexCatze**
Like   #22779 but without ACCEL_LOCATION, just correct mount matrix.

### CODE REVIEW

**Comment by hadess** [comment]
> Like #22779 but without ACCEL_LOCATION, just correct mount matrix.

How did you test this, and which accelerometer orientation did you use for the mount matrix for the base? We have documentation for the display orientation, but not for the base orientation.

As this patch is half of https://github.com/systemd/systemd/pull/22779 it's unlikely that it is in the right orientation for a base display where the Z axis would shoot upwards from the keyboard, in the same way as it shoots away from the display.

**Comment by AlexCatze** [comment]
> How did you test this
I`d test this in tablet mode, with ACCEL_LOCATION=display. 

> it's unlikely that it is in the right orientation for a base display where the Z axis would shoot upwards from the keyboard, in the same way as it shoots away from the display.

In this device vector that perpendicular to keyboard in laptop mode, equals to vector that perpendicular to screen in tablet mode.

**Comment by hadess** [comment]
> I`d test this in tablet mode, with ACCEL_LOCATION=display.

That means that the Z axis is going in the wrong direction. I'm nak'ing this again. I would really rather you waited until iio-sensor-proxy supported this particular scenario, rather than trying to hack around it.

**Comment by poettering** [comment]
So where are we at this? @keszybz did the suggested changes land in iio sensor package?

**Comment by keszybz** [comment]
https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/issues/345 is still open.
@hadess said that it should be fixed there first. Let's close this.

**Pull request closed without merging**
