### PR TITLE
Drop systemd-resolve compat symlink

### PR DESCRIPTION
**Pull request by mbiebl**
I guess we had the compat symlink for long enough. Unless we want to keep this compat symlink for all eternity, dropping it after the v243 release seems like a reasonable point in time.

### CODE REVIEW

**Comment by keszybz** [comment]
Dunno, I don't think we should drop the symlink. It costs very little, so I would drop it a few years in the future, if at all.

**Comment by mbiebl** [comment]
True, creating the symlink is pretty cheap. 
I'm more worried that the longer we ship the compat symlink, the more likely it is, that users get used to it, use it in scripts, documentation etc.

If we continue to ship systemd-resolve, executing the binary should print out a big fat warning imho.

**Comment by keszybz** [comment]
After sleeping on this, I'm even more convinced that dropping the symlink is not a good idea. We generally keep backwards compat for renamed options almost indefinitely, and we should do so the same here. We document the new name, and it causes no problems whatsoever if the old name is used. No need to break scripts. A few years ago we removed the compat names for libsystemd.so, and the churn is caused was not worth the trouble imho. But in that case it could at least be argued that the duplicate libraries use up resources. Here, no such argument can be made.

**Comment by mbiebl** [comment]
In that case, please consider adding a man page alias for systemd-resolve pointing at the resolvectl man page, so `man systemd-resolve` yields something useful.

**Comment by mbiebl** [comment]
We've been shipping Debian/Ubuntu without this compat symlink for three years now:
https://salsa.debian.org/systemd-team/systemd/-/blob/debian/master/debian/rules#L204

No complaints/bug reports so far.

Could this be reconsidered?

**Pull request closed without merging**
