### PR TITLE
bus: vtable-related changes

### PR DESCRIPTION
**Pull request by hvenev**
- make keeping ABI compatibility easier
- turn _SD_BUS_VTABLE_WRITABLE_PROPERTY into a flag, preserving backwards compatibility
- support argument names in vtables, preserving backwards compatibility

### CODE REVIEW

**Comment by hvenev** [comment]
I will soon submit a v2 with some minor (in code size) bugfixes. Anything else to change?

**Comment by poettering** [comment]
Hmm, can you elaborate on what you are trying to do here precisely? I figure this is primarily about adding support for naming method call paramters, is that correct? and the earlier commits are just preparatory for that?

I am not sure I grok what the big benefit of copying the vtables is? Is this simply to hide the fact that the elements might have different sizes? If so, can't we find a different way for that? For example a new macro (or function call) VTABLE_MEMBER_GET_PARAMETERS(vtable, member) or so, that deals with the two differnt sizes, and returns NULL for the old version, and the actual field for the new one?

What's the precise benefit of having the writable prop thing being a flag?

**Comment by hvenev** [comment]
Adding support for naming method call paramters is the main feature I wanted to implement. The first commit is a preparatory commit for handling ABI changes in a backwards-compatible manner.

I considered using macros. However code using the vtable would get more complex. Macros for getting elements and iteration would also depend on the start element to compute the size. Making the fields always available improves code readability. Compare:

``` c
introspect_write_arguments(i, strempty(m->x.signal.signature), m->x.signal.names, NULL);
```

``` c
introspect_write_arguments(i, strempty(m->vtable->x.signal.signature), VTABLE_MEMBER_GET_PARAMETERS(m->parent->vtable, m->vtable, x.signal.names), NULL);
```

The second commit is just a cleanup. Having the writable property being a flag means that we can change `type == _SD_BUS_VTABLE_PROPERTY || type == _SD_BUS_VTABLE_WRITABLE_PROPERTY`, to just `type == _SD_BUS_VTABLE_PROPERTY` which is the majority of the cases such a check is done.

**Comment by hvenev** [comment]
Closed in favor of #2230

**Pull request closed without merging**
