### PR TITLE
Revert "test: make unit tests relocatable and add an "install-tests" make target"

### PR DESCRIPTION
**Pull request by keszybz**
Reverts systemd/systemd#5298

The tests work when run through make, but not directly. We need to figure out something different.

### CODE REVIEW

**Comment by mbiebl** [comment]
Can you be more specific what the problem is you see?
The tests seem to work fine when run from the installed directory

**Comment by mbiebl** [comment]
@keszybz All the Makefile does is set TEST_DIR=$(pwd)/test 
Have you tried that?

**Comment by martinpitt** [comment]
Yeah, as we discussed in PR #5298, the tests will need a `$TEST_DIR` when running in-tree, as there is no predictable path. This is set via `$TESTS_ENVIRONMENT`, so `make check` works fine (otherwise semaphore would have failed).

**Comment by evverx** [comment]
1) `make valgrind-tests` is broken

2) `./libtool --mode=execute ./some-test` doesn't work

I should use
```
make check TESTS=some-test
```
or
```
TEST_DIR=$(pwd)/test ./libtool --mode=execute ./some-test
```

3) It's not clear why does the test fail
```
./libtool --mode=execute ./test-engine
...
Test1: (Trivial)
error: org.freedesktop.systemd1.NoSuchUnit: Unit c.service not found.
Assertion 'r == 0' failed at src/test/test-engine.c:62, function main(). Aborting.
Aborted (core dumped)
```
I'm not sure I should run the test under `gdb`/`strace`, read the source just to figure out that `./.libs/testdata` doesn't exists. (Anyway, that's not easy to run test under `gdb`. See 2))

**Comment by evverx** [comment]
Another question
```
$ sudo make install-tests
$ cd /usr/lib/systemd/tests
$ ./test-acl-util
$ ./test-acl-util: error while loading shared libraries: libsystemd-shared-232.so: cannot open shared object file: No such file or directory

$ ldd ./test-acl-util
	linux-gate.so.1 =>  (0xb774a000)
	libsystemd-shared-232.so => not found
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb771c000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb7560000)
	/lib/ld-linux.so.2 (0x8009a000)
```

 How can we guarantee that people run our tests against the correct `libsystemd-shared-*.so`?

**Comment by martinpitt** [comment]
@evverx: Pushed improvements for this to PR #5338, please have a look. I fixed valgrind-tests (which was already slightly broken) and the tests now show a proper error message if $TEST_DIR is missing.

As for the shared library: That shouldn't happen when packaging the tests (which is the main target here), but we might make `install-tests` depend on installing the library as well?

**Comment by evverx** [comment]
@martinpitt , thanks!

> As for the shared library: That shouldn't happen when packaging the tests (which is the main target here), but we might make install-tests depend on installing the library as well?

Maybe, I'm missing something. I'll read #5298, #5257.

**Comment by keszybz** [comment]
I'll dearly miss the ability to run tests with `./test-whatever` straight from the command line.

But OK, maybe that's the price to pay. I hope we'll figure out something that'll restore that ability.

**Comment by poettering** [comment]
hmpf, can't we make this work so that we search for testdir automatically, based on the current working directory?

**Comment by martinpitt** [comment]
We could first check in dir_of_exe/testdata/, and then try dir_of_exe/../testdata/, so that it would work in the common case of builddir == srcdir. Then one only needs to set `$TEST_DIR` for builddir != srcdir. That should cover most of the "run test manually" cases and for the remainder we have an useful error message now.

**Comment by evverx** [comment]
Sorry for the delay

>  I'll read #5298, #5257

Well, I got it. The use case is:
```
apt-get install systemd systemd-container # and so on
apt-get install systemd-test
apt-get install systemd-dbg
run-tests-against-installed-systemd
```
Maybe, there is no problem. But I've just tried something like:
```
$ make install DESTDIR=$(pwd)/TARGET
$ make install-tests DESTDIR=$(pwd)/TARGET
$ make check DESTDIR=$(pwd)/TARGET # this doesn't really work. `make check` ignores `DESTDIR`
$ TARGET/usr/lib/systemd/tests/test-acl-util
TARGET/usr/lib/systemd/tests/test-acl-util: error while loading shared libraries: libsystemd-shared-232.so: cannot open shared object file: No such file or directory
```
i.e. `make install-tests` doesn't make sense if `DESTDIR != /`

Also, there is [`make installcheck`](https://www.gnu.org/software/automake/manual/html_node/Install-Tests.html)
> The installcheck target is available to the user as a way to run any tests after the package has been installed. You can add tests to this by writing an installcheck-local rule.

Seems like we try to `make installcheck` via 
```
make install; make install-tests; run-all-tests-against-installed-systemd
```

But `make distcheck` runs `make installcheck` only.

Not sure what to do about it. Maybe, we should simply add the section "how to properly make install-tests" to the `README`

**Pull request closed without merging**
