### PR TITLE
watchdog: add support for fifo watchdog

### PR DESCRIPTION
**Pull request by mikkorapeli**
This patch adds a fifo watchdog to systemd.

At runtime systemd will detect the watchdog device mode based on
watchdog file type. If the the configured file is a device node the
watchdog is handled as before using device driver interface for hardware
watchdog. If the file is a fifo, the protocol for handlling watchdog in
this mode is applied.

The watchdog on fifo protocol follows the same steps as hardware watchdog
but writing ascii text messages on the fifo instead of doing ioctl() calls.
Each message starts with MACHINE and HOSTNAME fields (sd-id128 and
machine hostname) followed by the command and value (see watchdog_set_message()).
Commands are send for setting the timeout (SET_TIMEOUT), send heartbeat
(KEEPALIVE) and disarm the watchdog (DISARM).

This enables using HW watchdog on a native host with systemd and fifo based
watchdog to a container running its own systemd init.

### CODE REVIEW

**Comment by boucman** [comment]
I'm not sure I understand... who handles the fifo watchdog ? is it the host systemd ? another daemon ? I never heard of that protocol...

I would expect the guest-systemd to use sd_notify to talk to the host-systemd to handle watchdog... not use a fifo...

**Comment by mikkorapeli** [comment]
Native host systemd has a HW watchdog to kick. Native host starts and LXC container with its own systemd init.

The container systemd can't use the HW watchdog if we want to just restart the container if something goes wrong. If container has issues, we would just like to restart the container.

The container is started as a systemd service on the native host, and there we prepare a monitor service with the fifo. The fifo file is bind mounted into the container and configured as watchdog for the container systemd init. If container init is not responding to watchdog fifo, the host side monitor can restart the systemd service.

Does this explanation help?

**Comment by boucman** [comment]
Yes, partly... my question is : why can't the container-systemd detect that the environment variable SD_NOTIFY is set and then just use the normal software-watchdog from the host systemd ? why introduce a new mechanism (and a host side daemon) rather than using the existing mechanism

container-systemd already uses the SD_NOTIFY mechanism to tell host-systemd when it is READY, wouldn't it be enough to extend that to also ping the watchdog ?

**Comment by mikkorapeli** [comment]
Does SD_NOTIFY watchdog work between host systemd init and container systemd init? If yes, that would be perfect and we could use that instead of this patch.

AFAIK SD_NOFITY watchdog only works between host systemd init and a single containerized service.

**Comment by boucman** [comment]
I don't know... but if it doesn't that would probably be a better way of doing that than introducing a new watchdog protocol...

**Comment by mikkorapeli** [comment]
The normal sd_notify protocol uses PID which isn't suitable for containers where PID namespaces are used. Thus this patch uses machine id over the fifo. systemd-nspawn supports some aspects of sd_notify but watchdog support is missing.

In our case we are not using systemd-nspawn but lxc. The fifo protocol is really simple though. Not sure how complex sd_notify protocol is on the socket level for non-systemd containers to implement and it would need to be extended for namespaces, if they are not yet supported via nspawn code for example.

Any hints how to achieve similar watchdog with existing systemd functionality is of course welcome, and converting this patch from fifo to sd_notify is also possible, but I'd need some hints to the implementation details.

**Comment by anpopax** [comment]
The decision to extend watchdog protocol in the way proposed in this patch is based on a series of factors specific to our use case which can very well apply to other systemd users. 

We have a host platform running systemd serving hardware watchdog as usual. This platform has to monitor container services for activity (eg. watch container init main event loop). Some of these containers are systemd based and some are not. A service on host platform can monitor all containers and take actions if the heartbeat is missing. The protocol is using fifo(7) to use the same syscalls as much as possible for systemd container instances. This is consistent with normal device handling except for ioctls of course which in this case are replaced with string messages.

With this patch the proposed watchdog protocol is selected at runtime based on the watchdog file configured. The behaviour doesn't change for device nodes (hardware watchdog) and gives a way to monitor init process in containers by reusing watchdog mechanism.

**Comment by poettering** [comment]
why a new protocol for that? sd_notify() sounds great for this. And if that doesn't work, why isn't CUSE good enough that emulates the device node?

**Comment by mikkorapeli** [comment]
> why a new protocol for that? sd_notify() sounds great for this. And if that doesn't work, why isn't CUSE good enough that emulates the device node?

sd_notify() AFAIK doesn't work right away. PID can not be used due to namespaces. Could we add machine-id as variable to sd_notify()?

**Comment by poettering** [comment]
sd_notify() should just work. It's the PID1 in the container that just needs to send a dgram to its container manager, and then container manager knows the right external uid to care for.

**Comment by mikkorapeli** [comment]
So for example with an LXC container, host systemd init uses sd_notify with LXC controller, which talks sd_notify protocol with container systemd init. For watchdog the container init ping needs to be routed from container init through LXC controller to host systemd init, and LXC needs to e.g. convert the PID to the host native one. Did I miss something?

**Comment by boucman** [comment]
well... "through lxc" is not really true. sd_notify messages go through a socket. LXC would need to pass the socket to the container's rootfs, but once that's done, LXC doesn't need to do anything during normal watchdog updates...

Inserting a socket into a rootfs should be an easy thing to do for all container managers, it's pretty standard stuff, you just need to configure it properly

**Comment by mikkorapeli** [comment]
But then we need more than just PID=1 in sd_notify messages since we need to identify the services/containers. Adding machine-id to sd_notify would do this.

**Comment by boucman** [comment]
IIUC the socket is  a connected socket, so systemd knows who it is talking to... but I may be wrong. I'll leave the precise answer to someone more authoritative than me on the subject...

**Comment by anpopax** [comment]
Both solutions proposed by Lennart were on our list when we discussed how to approach this problem. The sd_notify() looks like the preferred solution for systemd project and we will reopen internally the discussions for this.

Will be helpful to clarify the following point:

The watchdog ping is sent in the manager loop for every iteration. This was one of our health and stability requirements for container init processes. Do we have sd_notify() message sent on every manager event loop as heartbeat? If yes, what is this message so we can start from there.

**Comment by anpopax** [comment]
The keep-alive message is not sent by PID1 to the container manager, it is sent to a dedicated watchdog service which informs a recovery manager service responsible with containers and system recovery. The containers are handled as systemd type simple services. I understand how this approach will disregard some of the advantages of a container manager, but most of them are irrelevant for our use case. Our system is not homogeneous when it comes to containers type, containers content and containers criticality (some are allowed to exit, some can be restarted and some shall trigger a fast hardware reset on failure). A container restart for example can be postponed until the system receives a series of external events. Because the recovery logic is so complex we cannot let the container manager nor the service manager to immediately react on a missing keep-alive message from containers.

The patch provides the watchdog information and container identification to an external interface which can be used by such health and lifecycle components directly as one of the input sources. 
We can conclude that our use case is to specific in which case we will maintain the change as external patch and happily continue with upstream efforts for other systemd changes when will be the case.

**Comment by poettering** [comment]
I think we can close this here. I think we should open up the usual event loop watchdog logic systemd supports i.e. the WATCHDOG=1 sd_notify() protocol we support elsewhere. If the container manager then sets $NOTIFY_SOCKET or some external service and the socket is just pushed through lxc doesn#t really matter much.

I don't think we need to leave this PR open. I don't think this FIFO approach is the way to go, and for supporting WATCHDOG=1 sd_notify() msgs between a container PID 1 and its supervising container manager is on the TODO list since a long time anyway. hence closing.

**Pull request closed without merging**
