### PR TITLE
Update 60-sensor.hwdb for chromebooks

### PR DESCRIPTION
**Pull request by estevez-dev**

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, so this merges the matches for chromebooks from two entirely different vendors, i.e. Dell and Samsung. That kind of generalization sounds quite a big step. Who knows what other kind of devices they'll develop sooner or later? If we merge this like this and they then end up building new devices with the sensors placed differently it's kinda hard to return to the more fine-grained rules we so far had...

I mean, I am all for simplifying rules, and not making them needlessly specific if there's a good chance that some manufacturer is likely to stick to one way to build stuff. But generalizing across multiple very different Chromebook vendors like this goes too far, this is just too likely to break. it feels like you generalize mere coincidence here, without any statistical relationship.

hence, instead of generalizing this so much, can you just add the rule for the specific laptop you got?

**Comment by hadess** [comment]
Very NAK, unless you can point at documentation that shows that Google mandates a particular accelerometer orientation.

**Comment by estevez-dev** [comment]
Hi @poettering and @hadess 
I agree with you, let's just close this PR.

**Pull request closed without merging**
