### PR TITLE
sd-bus: Add sd_bus_get/set_exit_on_disconnect docs

### PR DESCRIPTION
**Pull request by daandemeyer**

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Quick question, wrapping at 100 columns is what we're going for, right? The D-Bus API docs seemed to wrap at a little more than 100 columns so I'm not exactly sure if all the rewrapping I'm doing at 100 columns is correct.

**Comment by keszybz** [comment]
It's 109 actually. We have had long discussions about this, and 109 is a compromise. I now realize that I don't quite remember why this value, though it seemed important at the time. All the canonical values are in `.dir-locals.el`.

**Comment by keszybz** [comment]
... personally, I mostly notice if lines don't fit in the github review window.

**Comment by keszybz** [comment]
LGTM.

**Pull request merged**
