### PR TITLE
networkd: handle MTU field in IPv6 RA

### PR DESCRIPTION
**Pull request by ssahani**
This patch handles the custom MTU field in IPv6 RA.

fixes RFE #4464

### CODE REVIEW

**Comment by poettering** [comment]
lgtm, didn't test it but i hope you did!

**Comment by ssahani** [comment]
Yes . As we can see 1280 I added to the `radvd.conf` same seen on the mtu

```
# ip -6 route show
2001:db8:1::/64 dev enp0s3 proto ra metric 1024  pref medium
2001:db8:1::/64 dev br0 proto ra metric 1024  pref medium
fe80::/64 dev enp0s8 proto kernel metric 256  pref medium
fe80::/64 dev enp0s3 proto kernel metric 256  pref medium
fe80::/64 dev br0 proto kernel metric 256  pref medium
default via fe80::db06:6734:fce6:9659 dev enp0s8 proto ra metric 1024  mtu 1280 pref medium
default via fe80::db06:6734:fce6:9659 dev enp0s3 proto ra metric 1024  mtu 1280 pref medium
default via fe80::aecf:85ff:fe4e:dcd4 dev enp0s3 proto ra metric 1024  pref high
default via fe80::aecf:85ff:fe4e:dcd4 dev br0 proto ra metric 1024  pref high
default via fe80::db06:6734:fce6:9659 dev br0 proto ra metric 1024  pref medium

```

radvd.conf

interface vboxnet0
{
	AdvSendAdvert on;
	MinRtrAdvInterval 30;
        MaxRtrAdvInterval 40;
        AdvLinkMTU 1280;

	prefix 2001:db8:1:0::/64
	{
		AdvOnLink on;
		AdvAutonomous on;
		AdvRouterAddr off;
	};

};

**Comment by poettering** [comment]
CI failure appears unrelated. Merging.

**Comment by poettering** [comment]
@ssahani btw, next time could you please make sure to include a line like the following in your PRs descriptions or commit texts:

```
Fixes: #4464
```

github recognizes lines like this and will close the issue when the PR is merged.

You used a line that is similar to the above but doesn't follow the right syntax, hence github didn't recognize it.

**Pull request merged**
