### PR TITLE
network: tc-next

### PR DESCRIPTION
**Pull request by yuwata**
This includes #14844, #14854, #14847, #14843, and #14522.

### CODE REVIEW

**Comment by yuwata** [comment]
@ssahani I changed `[GRED]` -> `GenericRandomEarlyDetection`. (I think D is not Drop, but Detection.)

**Comment by yuwata** [comment]
Soon, I will include CAKE within this PR. Of course with a test.

Any comments are welcome.

**Comment by ssahani** [comment]
Thank you @yuwata. I am working on ULA.

**Comment by yuwata** [comment]
@ssahani I've slightly modified the parser for `CAKE.Overhead=`. PTAL.

**Comment by ssahani** [comment]
LGTM

**Comment by k0ste** [comment]
Since this support HTB's, should close #11618?

**Comment by yuwata** [comment]
Oh, thanks.

**Pull request merged**
