### PR TITLE
login: optionally respect inhibitors for root too

### LINKED ISSUE #949: add an option to respect inhibitor locks also for root users
Inhibitor locks are awesome. While one user is in the middle of something, we can prevent some non-root user with console access from rebooting, sleeping, shutting down. Awesome.

Unfortunately, the vast majority of server installations never have physical logins; it's most common that users only login over ssh. So:
1. Users login over ssh
2. Non-root users don't get magic power to reboot over ssh; therefore, non-root users understand that they always need root access to reboot
3. So non-root users always use su/sudo to reboot the machine, making inhibitor locks useless

See where I'm going with this? What if we could also warn root users that try to, e.g., reboot when block-locks are present? Use case:
1. Multiple users have sudo access
2. One user uses `sudo systemd-inhibit` to start some important process that should not be interrupted ... or maybe they're simply doing package-management operations
3. Another user comes in, runs into an issue and decides to `sudo reboot` but instead of rebooting, thankfully, the command errors out with a warning and explanation (with hint that `systemctl reboot --ignore-inhibitors` could be used)

Of course you can use `/run/nologin` to prevent new logins, but that doesn't help if someone has already su'd over to root. It just doesn't cover enough cases. This is a valid new feature that would be welcomed by many sysadmins.

---

I work for Red Hat Support and I can tell you that it's not uncommon for someone with sudo access to reboot a machine that's doing something important. systemd's inhibitor locks could help with that problem ... but not in their current form unfortunately.

So, assuming you see value in what I'm suggesting, let's talk about solutions. We could make inhibitors infinitely more useful to server admins by doing one of the 2 following things.
1.  Simply remove the `if (geteuid() == 0)` check in systemctl's **`check_inhibitors()`**
   - I'll submit a pull request momentarily with this change.
   - I haven't tried to build systemd with this change, but presumably this would make it so that trying to run `reboot` or `poweroff` or `shutdown` or `systemctl reboot` (etc etc) as root would fail with the same warning that non-root users get.
   - I could see some folks making the argument that scripted shutdowns as root should always succeed or that root should always be able to do what they want and teaching folks to use `-i` or `--ignore-inhibitors` is just too big of a change. From a teacher/trainer, sysadmin, and support tech perspective, I say pooh pooh but if that's how the developers feel, what about:
2. Make root-user systemctl actions that would override an inhibitor trigger a warning and a countdown timer, e.g., something silly like "Inhibitor lock present: ....; Ctrl-c in the next 10 seconds to cancel"
   - To be clear, in this scenario, the original action would still happen unless Ctrl-c was pressed, so scripted executions wouldn't need to be affected. Actually, I just noticed the `if (!on_tty())` check ... hmmm.
   - Personally, I would much rather we just start socializing the idea that if root REALLY wants to SHUTDOWN NOW they should use `-i`. To that end, we could also enable the `-i` and `--ignore-inhibitors` option for `reboot`, `poweroff`, `shutdown`, etc. I'll submit a simple pr momentarily that does this.

Thanks for reading!

### PR DESCRIPTION
**Pull request by dtardon**
Fixes #949.

### CODE REVIEW

**Comment by poettering** [comment]
hmm, do we really want this as a global option?

Other options could be: make this an extra flag when registering an inhibitor: if it is set then it would be a "super-inhibitor" and also affect root. Or the other way round it could be a special flag to "systemctl poweroff" and friends, that explicitly requests that inhibitors are tested even if the caller is root...

**Comment by boucman** [comment]
maybe attach to "reboot -f" ? after all, skiping inhibitors fits the decription of a forced reboot...

**Comment by dtardon** [comment]
@poettering This solution was suggested by you some time ago :) I think that the extra flag for an inhibitor (and option for systemd-inhibit) idea wouldn't work well for the use case of #949: people would have to learn to actively use it, otherwise it wouldn't change anything. Similarly for the extra option for "systemctl poweroff".

**Comment by amishxda** [comment]
I would suggest 5 options instead of 2 as follows.

EnforceInhibitors would be whitespace-separated list of following.

1) EnforceInhibitors=Unprivileged (Default - existing behavior)
Same as in PR

2) EnforceInhibitors=NonInteractive
i.e. respect inhibitors even if called from script. Currently calling systemctl poweroff from scripts ignore inhibitors.

This will take care of https://github.com/systemd/systemd/issues/2680

3) EnforceInhibitors=Legacy 
i.e. shutdown, root, poweroff, halt which are infact symlink to systemctl should also respect inhibitors. Currently they dont.

This will take care of objections by @poettering to https://github.com/systemd/systemd/pull/951

4) EnforceInhibitors=Privileged
Same as "Global" option in PR

5) EnforceInhibitors=Always
i.e. respect inhibitors for all of above

Ofcourse -i / --ignore-inhibitors can still be used to NOT enforce inhibitors.

**Comment by keszybz** [comment]
I don't like the approach to make this a configuration option at all. The decision to ignore inhibitors from root seems to have been a mistake, and wrapping configuration around this only makes the mistake permanent. Also, this will make behaviour inconsistent between systems, causing more confusion.

I think the goal state should be that we:
1. honour inhibitors for root
2. have on option to ignore them

The only problem is how to introduce this without breaking backwards compat too much. My suggestion would be to add a *compile* time option (for the next release), `-Droot-inhibitors=`, with values `no` (same as current behaviour), and `yes` (the default), and add a big note in NEWS that behaviour is changing, and that we'll remove this compile option in the future.

**Comment by mbiebl** [comment]
@keszybz I agree that this should *not* be a logind config option.
The use cases that I could think of where inhibitors locks for root are involved are on the command line, i.e. using `systemd-inhibit`. Would a new command line switch like `systemd-inhibit --root` suffice?

**Comment by keszybz** [comment]
>  Would a new command line switch like systemd-inhibit --root suffice?

Not really. As described in #949, most reboot requests *should* honour inhibitors, because ignoring them effectively leads to data loss of various sorts. It's not that there are some special operations that should be called with `systemd-inhibit --root`, but rather then almost all operations are like that. Thus, ignoring inhibitors is akin to `reboot -f`, a special measure to circumvent normal shutdown procedure.

**Comment by keszybz** [comment]
We discussed during a meeting, and came to the following tentative conclusion:
the reboot commands when run as root should block and wait for the inhibitors to go away. This is preferable to failing, because scripts don't expect failure at this point. And waiting can be justified by the fact that when a reboot is scheduled (without `-f` and friends), the reboot might take arbitrarily long too depending on what jobs are scheduled, and this adds yet another wait for the reboot to be delayed.

An option ('--inhibitors=ignore` ?) should be added to restore previous behaviour.

A big problem is that such a change would allow unprivileged users to block the operation by root. How to mitigate this remains an open question.

**Comment by q2dg** [comment]
> I don't like the approach to make this a configuration option at all. The decision to ignore inhibitors from root seems to have been a mistake, and wrapping configuration around this only makes the mistake permanent. Also, this will make behaviour inconsistent between systems, causing more confusion.
> 
> I think the goal state should be that we:
>     1. honour inhibitors for root
>     2. have on option to ignore them
> 
> The only problem is how to introduce this without breaking backwards compat too much. My suggestion would be to add a _compile_ time option (for the next release), `-Droot-inhibitors=`, with values `no` (same as current behaviour), and `yes` (the default), and add a big note in NEWS that behaviour is changing, and that we'll remove this compile option in the future.

If concern is retro-compatibility, why  not do what you propose ina LTS version of systemd?

**Comment by mbiebl** [comment]
> If concern is retro-compatibility, why not do what you propose ina LTS version of systemd?

What's a LTS version of systemd?

**Comment by q2dg** [comment]
Ooh, sorry, my head was fooled. You're right. Sorry a lot

**Comment by fbuihuu** [comment]
@keszybz why not, at least, letting systemctl honors inhibitors when run interactively by root ?

That should solve a big part of the problem without breaking existing scripts ?

I agree that inhibitors should be honored in most cases but fixing interactive requests looks pretty trivial to solve so I don't see any reasons to not change it.

If it's too much change for users to switch from `reboot` to `systemctl -i reboot`, maybe we could make the change only for direct invocation to `systemctl`.

**Comment by fbuihuu** [comment]
> A big problem is that such a change would allow unprivileged users to block the operation by root. How to mitigate this remains an open question.

Why not allowing root to wait for "privileged" locks only by default ?

**Comment by bluca** [comment]
> We discussed during a meeting, and came to the following tentative conclusion:
> the reboot commands when run as root should block and wait for the inhibitors to go away. This is preferable to failing, because scripts don't expect failure at this point. And waiting can be justified by the fact that when a reboot is scheduled (without `-f` and friends), the reboot might take arbitrarily long too depending on what jobs are scheduled, and this adds yet another wait for the reboot to be delayed.
> 
> An option ('--inhibitors=ignore` ?) should be added to restore previous behaviour.
> 
> A big problem is that such a change would allow unprivileged users to block the operation by root. How to mitigate this remains an open question.

The command line implementation is good, but we also have a DBUS interface. Especially when running within some form of namespacing/isolation, running systemctl requires exposing a lot more from the host than I like - the DBUS socket is not enough.
And also shelling out from programs is just meh in general.
Can we bring this back, maybe using your suggestion of a build-time flag rather than a config one?

**Comment by bluca** [comment]
> > We discussed during a meeting, and came to the following tentative conclusion:
> > the reboot commands when run as root should block and wait for the inhibitors to go away. This is preferable to failing, because scripts don't expect failure at this point. And waiting can be justified by the fact that when a reboot is scheduled (without `-f` and friends), the reboot might take arbitrarily long too depending on what jobs are scheduled, and this adds yet another wait for the reboot to be delayed.
> > An option ('--inhibitors=ignore` ?) should be added to restore previous behaviour.
> > A big problem is that such a change would allow unprivileged users to block the operation by root. How to mitigate this remains an open question.
> 
> The command line implementation is good, but we also have a DBUS interface. Especially when running within some form of namespacing/isolation, running systemctl requires exposing a lot more from the host than I like - the DBUS socket is not enough.
> And also shelling out from programs is just meh in general.
> Can we bring this back, maybe using your suggestion of a build-time flag rather than a config one?

@keszybz to be more specific about my use case, I have multiple programs running independently as portable service (mount namespacing and friends) that can do various upgrades to different parts (board firmware, cards, OS, and so on) and then call a reboot via dbus. I would really like to avoid telling everybody to start shelling out, and to have to start mounting the entire /run from the host so that systemctl can run.

**Comment by poettering** [comment]
BTW; there's now #16215 which is related

**Comment by bluca** [comment]
> BTW; there's now #16215 which is related

There's also https://github.com/systemd/systemd/pull/17492 which on the same topic - but those two deal with the systemctl command line - which is great. But not sufficient IMHO though, as mentioned above.

**Comment by deepak-rawat** [comment]
> There's also #17492 which on the same topic - but those two deal with the systemctl command line - which is great. But not sufficient IMHO though, as mentioned above.

If I understand the code correctly, polkit can be used to disable root from rebooting/shutting-down when blocked inhibitor is active. https://github.com/systemd/systemd/blob/9a01c6f095aa453984badbf59662ac4f14d19a9f/src/login/logind-dbus.c#L1835

**Comment by deepak-rawat** [comment]
> We discussed during a meeting, and came to the following tentative conclusion:
> the reboot commands when run as root should block and wait for the inhibitors to go away. This is preferable to failing, because scripts don't expect failure at this point. And waiting can be justified by the fact that when a reboot is scheduled (without `-f` and friends), the reboot might take arbitrarily long too depending on what jobs are scheduled, and this adds yet another wait for the reboot to be delayed.
> 
> An option ('--inhibitors=ignore` ?) should be added to restore previous behaviour.
> 
> A big problem is that such a change would allow unprivileged users to block the operation by root. How to mitigate this remains an open question.

@keszybz I implemented the above suggestion with PR https://github.com/systemd/systemd/pull/17492. This is for systemctl only. I am not sure if we can block when reboot/shutdown is called over dbus. Since reboot/shutdown there is implemented asynchronously. Any thoughts?

**Comment by keszybz** [comment]
We have  #17492 (merged) and #18316 (in review, very similar to this PR really). Let's close this one, since it doesn't apply any more. @dtardon your work lives on in spirit, even if not in actual text ;)

**Comment by dtardon** [comment]
I'm fine with that :)

**Pull request closed without merging**
