### PR TITLE
hwdb: fix indentation

### PR DESCRIPTION
**Pull request by poettering**
a bunch of entries use 2ch instead of 1ch indentation. Fix that.

### CODE REVIEW

**Comment by poettering** [comment]
@keszybz maybe the hwdb validator should check this too?

**Review by bluca — APPROVED** [review]
lgtm

**Comment by keszybz** [comment]
> @keszybz maybe the hwdb validator should check this too?

It should. No idea why it didn't catch that.

**Comment by keszybz** [comment]
The checker has:
```python
propertyline = (White(' ', exact=1).suppress() +
                    Combine(UDEV_TAG - '=' - Optional(Word(alphanums + '_=:@*.!-;, "'))
                            - Optional(pythonStyleComment)) +
                    EOL)
```
But it ignores additional whitespace.

Hmm, this only happens when invoked through the script. When invoking the partial parses, it refuses the double space. Very strange.

**Pull request merged**
