### PR TITLE
rpm: Fix typo in %_environmentdir

### PR DESCRIPTION
**Pull request by Conan-Kudo**
Signed-off-by: Neal Gompa <ngompa13@gmail.com>

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@keszybz Please review, thanks! 💯

**Comment by mvo5** [comment]
:+1:

**Comment by keszybz** [comment]
Looks good obviously, but I think if we shouldn't keep the old name with typo for ~two releases for compatibility.

**Comment by Conan-Kudo** [comment]
@keszybz It only existed in systemd 239, and no one has that yet in a released distro...

**Comment by Conan-Kudo** [comment]
@keszybz Backwards compat macro added with note of how long it will be around.

**Comment by ignatenkobrain** [comment]
Can we do `%{warn:…}` when someone uses that macro?

**Comment by Conan-Kudo** [comment]
@ignatenkobrain Would that mess up the output when used in a spec?

**Comment by ignatenkobrain** [comment]
It should work just fine and print annoying message when parsing spec.

Which is exactly what we want I think.

**Comment by keszybz** [comment]
I went away for a few days, and I hoped this would have resolved itself in the meantime ;)

But considering that 239 has been out for a week, now the compat layer is needed. Let's merge.

If somebody wants to add the %warn to it later, that can be done in a separate patch.

**Pull request merged**
