### PR TITLE
Drop build-api support

### PR DESCRIPTION
**Pull request by mbiebl**
It appears the build-api effort at
https://github.com/cgwalters/build-api hasn't really caught on. systemd appears one of the very few projects actually supporting it.

It does confuse certain tools though. E.g. debhelper by finding a configure script wrongly assumes this is an autoconf project and thus needs to be told explicitly that this is in fact a Meson project [1].

Given that Meson is an established build system by now, it appears ok to drop this compat layer, which will never be fully complete anyway.

[1] https://salsa.debian.org/systemd-team/systemd/-/blob/debian/master/debian/rules?ref_type=heads#L281

### CODE REVIEW

**Comment by mbiebl** [comment]
This basically reverts e7e157032bb5a9cb2d951fc6b28394d66cb513ad

**Review by cgwalters — APPROVED** [review]
Oh yeah, it was a failure.  Definitely feel free to kill it.

**Comment by mbiebl** [comment]
As additional info: back in 2017 I was the one who asked for this to be added in the first place.

**Review by bluca — APPROVED** [review]

**Comment by cgwalters** [comment]
> As additional info: back in 2017 I was the one who asked for this to be added in the first place.

Right, I think it kind of made sense at a time when meson was still pretty new, projects were transitioning, etc; that time is long past.  Also personally all my new projects are in Rust and `cargo` is by far the dominant build system there and very easy to detect and programmatically introspect unlike autotools (e.g. for build-time features), so there's no value in wrapping it with this build api.  Though I often do add a basic `Makefile` just so typing `make` does something useful.

**Comment by poettering** [comment]
@cgwalters thanks for reporting back! any chance you put something up on https://github.com/cgwalters/build-api to mark it as withdrawn or so? just in case somebody looks for that.

Anyway, seems everybody is on the same page here, let's merge this.

**Comment by cgwalters** [comment]
> any chance you put something up on https://github.com/cgwalters/build-api to mark it as withdrawn or so? just in case somebody looks for that.

:heavy_check_mark:

**Pull request merged**
