### PR TITLE
Rename rules/ and hwdb/

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
```
journal_file_copy_entry failed: Bad message
Assertion 'r >= 0' failed at src/journal/test-journal-flush.c:52, function main(). Aborting.
```
Looks unrelated.

**Comment by keszybz** [comment]
`FAILED TESTS:  test/TEST-25-IMPORT` — this one is flakey too.

**Comment by mrc0mmand** [comment]
> ```
> journal_file_copy_entry failed: Bad message
> Assertion 'r >= 0' failed at src/journal/test-journal-flush.c:52, function main(). Aborting.
> ```
> 
> Looks unrelated.



> `FAILED TESTS: test/TEST-25-IMPORT` — this one is flakey too.

Ahh, that's it, I'm going to revert the nested KVM stuff (for now) as, apparently, it's still not as good as I'd like it to be. The first fail is pretty common since I enabled the nested KVM. I guess the CentOS 7 kernel & KVM stuff doesn't help much to improve the stability and reliability in this case.

**Comment by keszybz** [comment]
If that's just this test failing, then I think it'd be fine to make it skip itself on nested KVM.

**Comment by yuwata** [comment]
needs to be rebased.

**Comment by keszybz** [comment]
Rebased

**Pull request merged**
