### PR TITLE
cgroup-util: Do not assume the cgroup is empty without kernel confirmation on cgroupsv2 after kill

### PR DESCRIPTION
**Pull request by msizanoen1**
In some cases, the kernel can spawn kernel threads associated with a user process inside the same cgroup (e.g. kvm-nx-lpage-recovery), that eventually disappears when the associated user process is terminated. Such kernel threads are never visible inside a PID namespace, either in `cgroup.{proc,threads}` or `/proc`, casuing systemd to believe that the cgroup is empty.

This sometimes results in the following error inside a `systemd-nspawn` container:
```
Feb 05 17:10:11 fedora systemd[1]: Stopped user@1000.service - User Manager for UID 1000.
Feb 05 17:10:11 fedora systemd[1]: user@1000.service: Consumed 1.194s CPU time.
Feb 05 17:10:11 fedora systemd[1]: Starting user@1000.service - User Manager for UID 1000...
Feb 05 17:10:11 fedora systemd[21076]: user@1000.service: Failed to attach to cgroup /user.slice/user-1000.slice/user@1000.service: Device or resource busy
Feb 05 17:10:11 fedora systemd[21076]: user@1000.service: Failed at step CGROUP spawning /usr/lib/systemd/systemd: Device or resource busy
Feb 05 17:10:11 fedora systemd[1]: user@1000.service: Main process exited, code=exited, status=219/CGROUP
Feb 05 17:10:11 fedora systemd[1]: user@1000.service: Failed with result 'exit-code'.
Feb 05 17:10:11 fedora systemd[1]: Failed to start user@1000.service - User Manager for UID 1000.
```

Fix this by not assuming the cgroup is empty unless the kernel says so in case of cgroupsv2 with SIGKILL.

### CODE REVIEW

**Comment by poettering** [comment]
I don't get this? cg_kill() returns whether anything was killed, not whether the cgroup is empty?

Which kernel are you on? You are touching a codepath that only matters for old kernels?

**Comment by msizanoen1** [comment]
> I don't get this? cg_kill() returns whether anything was killed, not whether the cgroup is empty?

The code assumes `cg_kill` not killing anything means that the doesn't have any processes. As stated above, this is not true for some kinds of threads that are not visible inside a PID namespace in case systemd is running in a container, like kernel managed threads created by kvm or io_uring. The only way to know if the cgroup is empty in this case is to query `cgroup.events`, which is what `cg_is_empty_recursive` does on cgroupsv2.

This unfortunately means we can't do anything about this on cgroupsv1, but you aren't supposed to be running systemd inside a container with cgroupsv1 anyway.

> Which kernel are you on? You are touching a codepath that only matters for old kernels?

6.1.8. This extra check does not have anything to do with the existing workaround codepath, it just happens to reuse the same cgroupsv2 check.

**Comment by msizanoen1** [comment]
I did some more thorough investigation and apparently, no, this is not caused by hidden kernel threads. This is actually caused by the new mgLRU patches in 6.1. It introduces a new `lru_gen` structure holding a reference to the memcg inside the `struct mm`, which is only destroyed *after* the process dies. This means that references to the cgroup can be held even after there are no more processes inside the cgroup, which leads to this (and this will also affect systemd ouside containers).

**Comment by msizanoen1** [comment]
> cg_kill() returns whether anything was killed, not whether the cgroup is empty?

I've moved the change to a more appropriate place.

**Comment by Werkov** [comment]
I'm not sure this needs to be fixed/worked around in systemd[^1].

a) io-uring threads are forked from respective unit's process (i.e. they inherit cgroup and pidns membership), so they're not different from another child tasks.

b) KVM threads are forked from kthreadd and then [migrated](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/virt/kvm/kvm_main.c#n6088) to associated cgroup. That is IMO an [abomination](https://lore.kernel.org/all/20211222225350.1912249-1-vipinsh@google.com/). But if it's done, it should be done properly, i.e. also enter the respective pidns so that it's visible as the associated parent context.

c) Proper kthreads providing an OS service will always stay in root cgroup (and charge resources accordingly when necessary).

[^1]: Contemplating whehter the `wait_for_exit` should be always bound to `cg_is_empty_recursive()==0` regardless of number of killed tasks.

**Comment by msizanoen1** [comment]
This could be some other behavior changes that causes the kernel to not consider the cgroup removable after all processes died (e.g. could be the recent mgLRU patch holding a reference to the memcg from `struct mm`). Changing systemd to query cgroup.events instead will ensure that it will never assume the cgroup to be empty when it is not, even with further future kernel behavior changes.

Doing this means that the old workaround here can also be removed: https://github.com/systemd/systemd/blob/8ad6e519d5098b68379f49adc056e35d64795e42/src/basic/cgroup-util.c#L369

**Comment by msizanoen1** [comment]
I did some more extensive reading of the kernel source code and noticed this: https://github.com/torvalds/linux/blob/05ecb680708a1dbe6554d6fc17e5d9a8a7cb5e6a/kernel/cgroup/cgroup.c#L918

Note that the task is removed from userspace visibility (`css_set_skip_task_iters` and `list_del_init` on the task) before the newly empty cgroup is acknowledged by the kernel as empty. This means it's possible for cgroups to be populated while containing only invisible tasks, causing issues like this.

**Comment by poettering** [comment]
@htejun any idea what is going on here?

**Comment by Werkov** [comment]
@msizanoen1 Can you reproduce the issue with sufficient confidence? How do you evaluate effectiveness of your patch? (Also, crossref #23164.)

**Comment by msizanoen1** [comment]
The issue is completely gone after the patch. This should also prevent any future cgroup `-EBUSY` related failures by using the kernel as the sole authority on whether the cgroup is actually empty.

**Comment by Werkov** [comment]
Do you run (qemu) KVM under `user@1000.service` (or any other process not belonging to (container) PID1's pidns)? I'd like to understand what's the cause of the issue here.

**Comment by msizanoen1** [comment]
After extensive debugging of both kernel and userspace with `bpftrace` and `gdb`, I managed to isolate the issue to the following line of code (!):
https://github.com/systemd/systemd/blob/8586e8ab84b46d22ce904a84b6f1c3f798dad24e/src/core/unit.c#L4503

The `0` return value is recorded by
https://github.com/systemd/systemd/blob/8586e8ab84b46d22ce904a84b6f1c3f798dad24e/src/basic/cgroup-util.c#L306

and then set as return value in
https://github.com/systemd/systemd/blob/8586e8ab84b46d22ce904a84b6f1c3f798dad24e/src/basic/cgroup-util.c#L319

As the only process remaining in the cgroup at the time was `(sd-pam)` this means `cg_kill` will actually return `0`, causing systemd to believe that no process was killed.

**Comment by msizanoen1** [comment]
Superseded by #26332

**Pull request closed without merging**
