### PR TITLE
sysupdate: Add update-all verb

### PR DESCRIPTION
**Pull request by AdrianVovk**
TODO:
- [ ] Add reasoning to commit message
- [ ] Figure out relationship between components and our auto-discovered images/directories
  - What are components _for_ exactly?
  - Should we recursively update all components inside of each resource we update?
  - Should we just synthesize components for each resource we find?
- [ ] Figure out how to handle the files that appear in /usr
  - Just don't update them?
- [ ] Finish implementing

### CODE REVIEW

**Comment by poettering** [comment]
So this certainly makes sense. And I definitely want this too.

You can use image_discover() to find all images installed on the system.

My assumption would be that update info should always be included inside the images, and we'd just iterate through all the images, and process them that way, one by one. But no, i wouldn't recursively continue inside images, that's for the images to manage themselves i am sure.

**Comment by AdrianVovk** [comment]
So just to clarify: `update-all` should update:

- The default component of the host system
- All the alternate components of the host system (maybe it shouldn't?)
- For each DDI image we find
   - The default component of the image
   - NOT any other alternate components of the image
   - NOT any other images possibly embedded in the image

Should we try updating directories too (quick glance implies that `image_discover` just handles that)? What about images found under `/usr`?

I don't quite grok the purpose of "components", especially if we're auto-discovering images... Is there some example usecase you can give?

**Comment by AdrianVovk** [comment]
I'm thnking of this PR in the context of a DBus API also, and I'm not sure building in `update-all` into systemd-sysupdate itself makes sense. Here's my latest thinking of what would be most reasonable:

- `systemd-sysupdate` itself remains as-is, with no `update-all` mode. In other words, I close this PR
- The _dbus service_ is what gets a high-level overview over all components & images that need to be kept up-to-date. Each component/image is exported in its own dbus object
- Each dbus object has methods to check/update/vacuum/etc the corresponding component/image. These method calls translate into invocations of `systemd-sysupdate` with the right `--image`/`--root`/`--component` flags set.
- A new CLI tool, `updatectl`, is introduced. This tool talks to the dbus service and can orchestrate updates at a bit of a higher level than `systemd-sysupdate`. It would be built to operate on a collection of components/images all at once (either all of them or some user-specified subset)
   - `updatectl status`: List the status of all components/images (what are they, what's the current version, what definitions make it up, etc)
   - `updatectl check`: Check all components/images for updates and say which need updating, how much needs to be downloaded, etc
   - `updatectl update`: Update all components/images to the latest version for each component
   - `updatectl update component:version ...`: Update specified list of components to specified versions (???)
   - `updatectl vacuum`: Vacuum all components/images
   - I think you get the idea
- We can plumb AppStream metadata through the dbus service, which will allow GUI software centers to present rich UIs about the various components being updated (including changelogs)

Please let me know what you think!

**Comment by AdrianVovk** [comment]
Ah whoops you probably won't see my questions unless i do this:

/please-review

**Comment by poettering** [comment]
> I don't quite grok the purpose of "components", especially if we're auto-discovering images... Is there some example usecase you can give?

Could be microcode packages for example. i.e. some blob placed in the ESP that is passed to the kernel and uploaded by the kernel into the CPU early on. It has a different update cycle than the OS, but usually should be updated too.

**Comment by poettering** [comment]
> Should we try updating directories too (quick glance implies that `image_discover` just handles that)? What about images found under `/usr`?

I'd just update anything we could update. I mean it's fine to focus on DDIs only initially, we can extend this later, but I'd always keep the concepts generic enough so that dir/subvol stuff *and* DDIs can be updated the exact same way.

**Comment by poettering** [comment]
> * The default component of the host system
> 
> * All the alternate components of the host system (maybe it shouldn't?)
> 
> * For each DDI image we find
>   
>   * The default component of the image
>   * NOT any other alternate components of the image
>   * NOT any other images possibly embedded in the image

That sounds good to me. Might make sense to make this configurable, i.e.

```
systemd-sysupdate update-all --update-what=components,images
```

vs:

```
systemd-sysupdate update-all --update-what=components
```

vs.

```
systemd-sysupdate update-all --update-what=images
```

You get the idea. i.e. people can pick exactly what they want updated, by default we'd really update *everything*

**Comment by poettering** [comment]
I haven't bothered with D-Bus service because my focus so far was on entirely automatic background updates, without user interaction beyond "hey, a new version of the OS was installed, click here to reboot into it".

that said, I think we can add a dbus service here too. it probably should be modelled after systemd-importd, systemd-userdbd, systemd-homed: they all are one daemon process that fork off worker processes as children that do the actual and "slow" work. I think this is a really nice model, as it means IPC calls are speedily processed by the main daemon, while IO heavy work is done by the worker children and they don't slow each other down.

systemd-import worker processes call the parent via sd_notify() about progress, which maps nicely to systemd-sysupdate, too.

hence my suggestion: implement systemd-sysupdated which speaks D-Bus and leaves the heavy work to system-sysupdate that it invokes as child process. Make sure to set NOTIFY_SOCKET so that system-sysupdate workers send progress report to systemd-sysupdated. Make sure that systemd-sysupdate can output things in JSON form to stdout for everything expensive it does, and parse that from systemd-sysupdated before passing it to clients via D-Bus.

**Comment by AdrianVovk** [comment]
As I mentioned before, I think it would be significantly better for systemd-sysupdate itself to _not_ do an `update-all` mode and instead have the dbus service itself manage multiple instances of sysupdate at a time.

Some of my reasons:
- Exposing this in sysupdate would essentially force me to duplicate each command (not just for update, but for check and vacuum and etc). This would make the CLI, at least IMO, very annoying 
- conceptually it's a bit messy. sysupdate is a tool for updating one resource. To me, adding an update-all mode is like adding the ability to download multiple files at a time to systemd-import; why not just fork off another instance?
-  it makes the implementation significantly more complicated. Logging would have to be extended/redesigned to include information about what specifically is being updated in the moment (since it can be any number of things now). Progress updates sent over the notify socket would need to be manipulated to aggregate information across all downloads, instead of just the one.
- I don't see a clear way to do this in parallel other than just forking itself off for each update target anyway. Otherwise we'd just install everything in serial
- the dbus service will need to re-implement the same "discover what should be updated" logic anyway, since it needs to expose these items separately to a UI or other clients 

Thoughts?

**Comment by AdrianVovk** [comment]
Sorry, but bumping again

**Comment by poettering** [comment]
sure, doing the enumeraiton of the images client side makes sense to me.

**Comment by poettering** [comment]
or wait, now i am confused. not sure we are talking of the same stuff. here's what i had in mind:

* systemd-sysupdated is a dbus service, which accepts update requests via dbus calls
* systemd-sysupdate is the a low-level tool you either can call from the cmdline on a specific image (you need privs), or that is invoked by systemd-sysupdated as worker process (which opens this up to certain unpriv scenarios)
* a new tool sysupdatectl or so could be a client for systemd-sysupdated, that fires off requests to it, and shows progress. alternatively, some UI tool could tak to systemd-sysupdated.
* systemd-sysupdated should be able to handle multuiple image updates in parallel, i.e. fork off multiple worker processes at the same time
* sysupdatectl should have an "update-all" mode, where it enumerates images and then enqueues a multitude of jobs on systemd-sysupdated, one for each image, which will thus end up in a bunch of parallel worker processes being forked off systemd-sysupdate.

does that make sense?

**Comment by AdrianVovk** [comment]
Looks like we're almost on the same page. What I envisioned is that sysupdated (the dbus service) does the enumeration of images and exports each image as a separate dbus object. Then clients (sysupdatectl or a UI) can then enumerate the exported objects from the dbus service and present them however appropriate.

So, revising your previous comment:

- systemd-sysupdated is a dbus service, which accepts update requests via dbus calls
- systemd-sysupdate is the a low-level tool you either can call from the cmdline on a specific image (you need privs), or that is invoked by systemd-sysupdated as worker process (which opens this up to certain unpriv scenarios)
- a new tool sysupdatectl or so could be a client for systemd-sysupdated, that fires off requests to it, and shows progress. alternatively, some UI tool could talk to systemd-sysupdated.
- systemd-sysupdated should be able to handle multuiple image updates in parallel, i.e. fork off multiple worker processes at the same time
- systemd-sysupdated enumerates the images available on the device. For each image it finds, it creates a dbus object that can be used to update that specific image
- sysupdatectl should have an "update-all" mode, where it enumerates the dbus objects exported by systemd-sysupdated and then enqueues a multitude of jobs on systemd-sysupdated, one for each image, which will thus end up in a bunch of parallel worker processes being forked off systemd-sysupdate.
- a UI tool would enumerate the dbus objects exported by systemd-sysupdated and then present each object as a separate component to be updated

Maybe to help further demonstrate here's a rough sketch of what the service may look like:
```
org.freedesktop.sysupdate1
    /org/freedesktop/sysupdate1
        org.freedesktop.sysupdate1.Manager
            GetUpdatableObjects()
    /org/freedesktop/sysupdate1/portable/foo
        org.freedesktop.sysupdate1.Updatable
            bool NeedsReboot
            String AppstreamData
            Check()
            Update(s version)
            Vacuum()
            ...
    /org/freedesktop/sysupdate1/extension/bar
        org.freedesktop.sysupdate1.Updatable
            bool NeedsReboot
            String AppstreamData
            Check()
            Update(s version)
            Vacuum()
            ...
    /org/freedesktop/sysupdate1/component/baz
        org.freedesktop.sysupdate1.Updatable
            bool NeedsReboot
            String AppstreamData
            Check()
            Update(s version)
            Vacuum()
            ...
    /org/freedesktop/sysupdate1/system
        org.freedesktop.sysupdate1.Updatable
            bool NeedsReboot
            String AppstreamData
            Check()
            Update(s version)
            Vacuum()
            ...
    ...
```

**Comment by poettering** [comment]
so we have an image enumerator now in machined and portabled, and now another one in sysupdated? this starts smelling as if we are doing something wrong ;-)

**Comment by poettering** [comment]
but anyway, sounds ok to me.

**Comment by AdrianVovk** [comment]
> sounds ok to me

Then I'll close this in favor of the rework. Thanks

**Pull request closed without merging**
