### PR TITLE
udev/dmi-memory-id: update table with latest SMBIOS specification

### LINKED ISSUE #30699: DDR5 Ram not detected by udevadm
### systemd version the issue has been seen with

255

### Used distribution

Archlinux

### Linux kernel version used

kernel-6.6.8-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

udevadm

### Expected behaviour you didn't see

`udevadm info -p /sys/devices/virtual/dmi/id` reports my memory informations. 
`MEMORY_DEVICE_0_TYPE` should be `DDR5` but its "\<OUT OF SPEC\>"

### Unexpected behaviour you saw

"\<OUT OF SPEC\>" instead of DDR5

### Steps to reproduce the problem

If I am correct in this list is the DDR5 entry missing: 
https://github.com/systemd/systemd/blob/6b9cac874c33f4fa27aa4b4b5b980f60c28ee043/src/udev/dmi_memory_id/dmi_memory_id.c#L307

But I'm not an expert on this codebase so I guess there might be more work to do to support DDR5 memory.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[root@archlinux IdeaProjects]# udevadm info -p /sys/devices/virtual/dmi/id
P: /devices/virtual/dmi/id
M: id
U: dmi
E: DEVPATH=/devices/virtual/dmi/id
E: SUBSYSTEM=dmi
E: MODALIAS=dmi:bvnINSYDECorp.:bvr03.03:bd10/17/2023:br3.3:svnFramework:pnLaptop13(AMDRyzen7040Series):pvrA7:rvnFramework:rnFRANMDCP07:rvrA7:cvnFramework:ct10:cvrA7:skuFRANDGCP07:
E: USEC_INITIALIZED=2010156
E: ID_VENDOR=Framework
E: ID_MODEL=Laptop 13 _AMD Ryzen 7040Series_
E: MEMORY_ARRAY_LOCATION=System Board Or Motherboard
E: MEMORY_ARRAY_MAX_CAPACITY=68719476736
E: MEMORY_DEVICE_0_TOTAL_WIDTH=64
E: MEMORY_DEVICE_0_DATA_WIDTH=64
E: MEMORY_DEVICE_0_SIZE=34359738368
E: MEMORY_DEVICE_0_FORM_FACTOR=SODIMM
E: MEMORY_DEVICE_0_LOCATOR=DIMM 0
E: MEMORY_DEVICE_0_BANK_LOCATOR=P0 CHANNEL A
E: MEMORY_DEVICE_0_TYPE=<OUT OF SPEC>
E: MEMORY_DEVICE_0_TYPE_DETAIL=Synchronous Unbuffered (Unregistered)
E: MEMORY_DEVICE_0_SPEED_MTS=5600
E: MEMORY_DEVICE_0_MANUFACTURER=Kingston
E: MEMORY_DEVICE_0_SERIAL_NUMBER=A3066864
E: MEMORY_DEVICE_0_ASSET_TAG=Not Specified
E: MEMORY_DEVICE_0_PART_NUMBER=KF556S40-32
E: MEMORY_DEVICE_0_RANK=2
E: MEMORY_DEVICE_0_CONFIGURED_SPEED_MTS=5600
E: MEMORY_DEVICE_0_MINIMUM_VOLTAGE=1
E: MEMORY_DEVICE_0_MAXIMUM_VOLTAGE=1
E: MEMORY_DEVICE_0_CONFIGURED_VOLTAGE=1
E: MEMORY_DEVICE_0_MEMORY_TECHNOLOGY=DRAM
E: MEMORY_DEVICE_0_MEMORY_OPERATING_MODE_CAPABILITY=Volatile memory
E: MEMORY_DEVICE_0_FIRMWARE_VERSION=Unknown
E: MEMORY_DEVICE_0_MODULE_MANUFACTURER_ID=Bank 2, Hex 0x98
E: MEMORY_DEVICE_0_VOLATILE_SIZE=34359738368
E: MEMORY_DEVICE_1_TOTAL_WIDTH=64
E: MEMORY_DEVICE_1_DATA_WIDTH=64
E: MEMORY_DEVICE_1_SIZE=34359738368
E: MEMORY_DEVICE_1_FORM_FACTOR=SODIMM
E: MEMORY_DEVICE_1_LOCATOR=DIMM 0
E: MEMORY_DEVICE_1_BANK_LOCATOR=P0 CHANNEL B
E: MEMORY_DEVICE_1_TYPE=<OUT OF SPEC>
E: MEMORY_DEVICE_1_TYPE_DETAIL=Synchronous Unbuffered (Unregistered)
E: MEMORY_DEVICE_1_SPEED_MTS=5600
E: MEMORY_DEVICE_1_MANUFACTURER=Kingston
E: MEMORY_DEVICE_1_SERIAL_NUMBER=A20667E2
E: MEMORY_DEVICE_1_ASSET_TAG=Not Specified
E: MEMORY_DEVICE_1_PART_NUMBER=KF556S40-32
E: MEMORY_DEVICE_1_RANK=2
E: MEMORY_DEVICE_1_CONFIGURED_SPEED_MTS=5600
E: MEMORY_DEVICE_1_MINIMUM_VOLTAGE=1
E: MEMORY_DEVICE_1_MAXIMUM_VOLTAGE=1
E: MEMORY_DEVICE_1_CONFIGURED_VOLTAGE=1
E: MEMORY_DEVICE_1_MEMORY_TECHNOLOGY=DRAM
E: MEMORY_DEVICE_1_MEMORY_OPERATING_MODE_CAPABILITY=Volatile memory
E: MEMORY_DEVICE_1_FIRMWARE_VERSION=Unknown
E: MEMORY_DEVICE_1_MODULE_MANUFACTURER_ID=Bank 2, Hex 0x98
E: MEMORY_DEVICE_1_VOLATILE_SIZE=34359738368
E: MEMORY_ARRAY_NUM_DEVICES=2
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #30699.

### CODE REVIEW

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by qwertychouskie** [comment]
What are the chances of this being backported to the stable branches?  I am working of software that requires this information (https://gitlab.com/mission-center-devs/mission-center/-/merge_requests/104) and this is a pretty major issue holding up the switch away from `dmidecode` (which requires root, and is therefore a bad user experience).

**Comment by yuwata** [comment]
I set the backport tag.

**Comment by qwertychouskie** [comment]
@yuwata Awesome!  What versions of systemd will get the backport?

**Comment by yuwata** [comment]
> @yuwata Awesome! What versions of systemd will get the backport?

If there is no problem, then I hope it should be in the next point release.

**Comment by qwertychouskie** [comment]
Does that only apply to the current release (255) or all the releases getting active backports at https://github.com/systemd/systemd-stable/tags (248-255)?

**Comment by yuwata** [comment]
All active ones. Though, the last stable releases are kind of critical releases. So, not all of them may not have future bacports, e.g. v248 is already too old to be maintained in upstream.

@bluca Maybe we should write a short note in the top page of stable repository which versions are maintained on the repository?

**Comment by bluca** [comment]
Older branches are maintained as far as somebody finds the time to do it, and they are useful, so not sure about a formal committment

**Pull request merged**
