### PR TITLE
meson: Use files() for source lists for boot and fundamental

### PR DESCRIPTION
**Pull request by medhefgo**

### CODE REVIEW

**Comment by kanavin** [comment]
Works for me, see https://github.com/systemd/systemd/pull/22047 for the issue.

**Comment by yuwata** [comment]
All Ubuntu CIs are red...

**Comment by medhefgo** [comment]
> All Ubuntu CIs are red...

Those are unrelated (and all over the place https://github.com/systemd/systemd/pull/22013#issuecomment-1007922259).

**Comment by evverx** [comment]
> All Ubuntu CIs are red...

I opened https://github.com/systemd/systemd/pull/22053. It would be nice to get it merged so that Ubuntu CI would stop bothering contributors.

**Comment by keszybz** [comment]
> Works for me, see #22047 for the issue.

@medhefgo – if the patch fixes something, please describe this in the commit message. If the patch is just a no-functional-change refactoring, please also mention that in the commit message. It's hard to review to pull request if I don't know what I'm looking at.

**Comment by keszybz** [comment]
Oh, it's all clear now, thanks!

**Pull request merged**
