### PR TITLE
git-contrib: use 'git shortlog' command

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Review by mrc0mmand — APPROVED** [review]
Seems to work as expected (or even better, since the old version didn't properly filter out Weblate:

```diff
diff --git a/contrib.old b/contrib.new
index eaf2662b7c..042a12026e 100644
--- a/contrib.old
+++ b/contrib.new
@@ -37,7 +37,6 @@ ninja: Entering directory `build'
         Takashi Sakamoto, Temuri Doghonadze, Thilo Fromm, Thomas Blume,
         TobiPeterG, Tomáš Pecka, Topi Miettinen, Tycho Andersen, Unique-Usman,
         Vasiliy Kovalev, Vasiliy Stelmachenok, Vishal Chillara Srinivas,
-        Vitaly Kuznetsov, Vladimir Stoiakin, wangyuhang, Weblate,
-        Werner Sembach, Will Springer, Winterhuman, Xiaotian Wu,
-        Yuri Chornoivan, Yu Watanabe, Zbigniew Jędrzejewski-Szmek, Zmyeir,
-        zzywysm, 我超厉害
+        Vitaly Kuznetsov, Vladimir Stoiakin, wangyuhang, Werner Sembach,
+        Will Springer, Winterhuman, Xiaotian Wu, Yuri Chornoivan, Yu Watanabe,
+        Zbigniew Jędrzejewski-Szmek, Zmyeir, zzywysm, 我超厉害
```

And it also makes the script _slightly_ less horrible.

**Comment by teknoraver** [comment]
`git shortlog -sn` already removes duplicates, consider trying it and get rid of `sort -u`

**Comment by yuwata** [comment]
@teknoraver Thanks.

@mrc0mmand Could you check again? Now the sort algo is changed, so the diff becomes much larger.

**Comment by mrc0mmand** [comment]
> @teknoraver Thanks.
> 
> @mrc0mmand Could you check again? Now the sort algo is changed, so the diff becomes much larger.

The diff is indeed much larger, but the content appears to be the same (as the previous version of this PR). That is, with this beauty that aspires to be next thing that comes out of `/dev/random`:

```diff
$ diff <(tail -n +3 contrib.old | awk -F"," '{ for(i=1; i<=NF; i++) { gsub(/ /, "", $i); print $i; }}' | sort) <(tail -n +3 contrib.new | awk -F"," '{ for(i=1; i<=NF; i++) { gsub(/ /, "", $i); print $i; }}' | sort)
40a41
> 김인수
55d55
< A S Alam
70c70
< Contributionsfrom:김인수
---
> Contributionsfrom:A S Alam
201d200
< Weblate
```

I get just the (expected) missing Weblate mention.

Just for comparison how the sorted list looks:

<details>
<summary>Without this PR:</summary>

```
        Adrian Wannenmacher, AKHIL KUMAR, Alan Liang, Alberto Planas,
        Alexander Zavyalov, Anders Jonsson, Andika Triwidada, Andres Beltran,
        Andrew Sayers, Antonio Alvarez Feijoo, Arthur Zamarin, Artur Pak,
        A S Alam, aslepykh, AtariDreams, Benjamin Franzke,
        Bernhard M. Wiedemann, Black-Hole1, Burak Gerz, Carlos Garnacho,
        Chandra Pratap, chenjiayi, Chris Simons, Christian Wesselhoeft,
        Clayton Craft, Colin Geniet, Colin Walters, Costa Tsaousis,
        cpackham-atlnz, Cristian Rodríguez, cunshunxia, Daan De Meyer,
        Damien Challet, Dan Streetman, David Tardon, David Venhoek,
        dependabot[bot], Diego Viola, Dionna Amalie Glaze, djantti,
        Dmitry Konishchev, Edson Juliano Drosdeck, Eisuke Kawashima,
        Eli Schwartz, Emanuele Giuseppe Esposito, Eric Daigle,
        Evgeny Vereshchagin, Felix Riemann, Fernando Fernandez Mancera,
        Florian Schmaus, Franck Bui, Frantisek Sumsal, Friedrich Altheide,
        Gabríel Arthúr Pétursson, Gaël Donval, Georges Basile Stavracas Neto,
        Gerd Hoffmann, Göran Uddeborg, Guilhem Lettron, Hans de Goede,
        Harald Brinkmann, Heinrich Schuchardt, hfavisado, Holger Assmann,
        hulkoba, İ. Ensar Gülşen, Ivan Shapovalov, Jakub Sitnicki, James Muir,
        Jan Engelhardt, Jan Macku, Jeff King, JmbFountain, Joakim Nohlgård,
        Jörg Behrmann, Keian, Krzesimir Nowak, ksaleem, Lars Ellenberg,
        Lennart Poettering, Luca Boccassi, Ludwig Nussel, Lukáš Nykrýn,
        Luxiter, Maanya Goenka, Mariano Giménez, Markus Merklinger,
        Martin Ivicic, Martin Trigaux, Matteo Croce, Matthias Lisin,
        Matt Layher, Matt Muggeridge, Max Gautier, Max Staudt, medusalix,
        Michael Biebl, Michal Koutný, Michal Sekletár, Mike Gilbert, Mike Yuan,
        Mikko Ylinen, mille-feuille, MkfsSion, mkubiak, mooo, MrSmör,
        msizanoen, Nandakumar Raghavan, networkException, Nick Cao,
        Nick Rosbrook, nl6720, Oğuz Ersen, Ondrej Kozina, Pierre GRASSER,
        Piotr Drąg, QuonXF, Rafaël Kooi, Raito Bezarius, Reid Wahl,
        Renjaya Raga Zenta, Richard Maw, Roland Hieber, Ronan Pigott, Rose,
        Ross Burton, runiq, r-vdp, Sam Leonard, Samuel BF, samuelvw01,
        Sergei Zhmylev, Sergey A, sharad3001, Shulhan, SidhuRupinder, Sludge,
        Štěpán Němec, Stuart Hayhurst, Susant Sahani, sushmbha,
        Takashi Sakamoto, Temuri Doghonadze, Thilo Fromm, Thomas Blume,
        TobiPeterG, Tomáš Pecka, Topi Miettinen, Tycho Andersen, Unique-Usman,
        Vasiliy Kovalev, Vasiliy Stelmachenok, Vishal Chillara Srinivas,
        Vitaly Kuznetsov, Vladimir Stoiakin, wangyuhang, Weblate,
        Werner Sembach, Will Springer, Winterhuman, Xiaotian Wu,
        Yuri Chornoivan, Yu Watanabe, Zbigniew Jędrzejewski-Szmek, Zmyeir,
        zzywysm, 我超厉害
```
</details>

<details>
<summary>With this PR:</summary>

```
        Contributions from: A S Alam, AKHIL KUMAR, Abraham Samuel Adekunle,
        Adrian Vovk, Adrian Wannenmacher, Alan Liang, Alberto Planas,
        Alexander Zavyalov, Anders Jonsson, Andika Triwidada, Andres Beltran,
        Andrew Sayers, Antonio Alvarez Feijoo, Arthur Zamarin, Artur Pak,
        AtariDreams, Benjamin Franzke, Bernhard M. Wiedemann, Black-Hole1,
        Burak Gerz, Carlos Garnacho, Chandra Pratap, Chris Simons,
        Christian Wesselhoeft, Clayton Craft, Colin Geniet, Colin Walters,
        Costa Tsaousis, Cristian Rodríguez, Daan De Meyer, Damien Challet,
        Dan Streetman, David Tardon, David Venhoek, Diego Viola,
        Dionna Amalie Glaze, Dmitry Konishchev, Edson Juliano Drosdeck,
        Eisuke Kawashima, Eli Schwartz, Emanuele Giuseppe Esposito,
        Eric Daigle, Evgeny Vereshchagin, Felix Riemann,
        Fernando Fernandez Mancera, Florian Schmaus, Franck Bui,
        Frantisek Sumsal, Friedrich Altheide, Gabríel Arthúr Pétursson,
        Gaël Donval, Georges Basile Stavracas Neto, Gerd Hoffmann,
        Guilhem Lettron, Göran Uddeborg, Hans de Goede, Harald Brinkmann,
        Heinrich Schuchardt, Holger Assmann, Ivan Shapovalov, Jakub Sitnicki,
        James Muir, Jan Engelhardt, Jan Macku, Jeff King, JmbFountain,
        Joakim Nohlgård, Jörg Behrmann, Keian, Krzesimir Nowak, Lars Ellenberg,
        Lennart Poettering, Luca Boccassi, Ludwig Nussel, Lukáš Nykrýn,
        Luxiter, Maanya Goenka, Mariano Giménez, Markus Merklinger,
        Martin Ivicic, Martin Trigaux, Matt Layher, Matt Muggeridge,
        Matteo Croce, Matthias Lisin, Max Gautier, Max Staudt, Michael Biebl,
        Michal Koutný, Michal Sekletár, Mike Gilbert, Mike Yuan, Mikko Ylinen,
        MkfsSion, MrSmör, Nandakumar Raghavan, Nick Cao, Nick Rosbrook,
        Ondrej Kozina, Oğuz Ersen, Pierre GRASSER, Piotr Drąg, QuonXF,
        Rafaël Kooi, Raito Bezarius, Reid Wahl, Renjaya Raga Zenta,
        Richard Maw, Roland Hieber, Ronan Pigott, Rose, Ross Burton,
        Sam Leonard, Samuel BF, Sergei Zhmylev, Sergey A, Shulhan,
        SidhuRupinder, Sludge, Stuart Hayhurst, Susant Sahani,
        Takashi Sakamoto, Temuri Doghonadze, Thilo Fromm, Thomas Blume,
        TobiPeterG, Tomáš Pecka, Topi Miettinen, Tycho Andersen, Unique-Usman,
        Vasiliy Kovalev, Vasiliy Stelmachenok, Vishal Chillara Srinivas,
        Vitaly Kuznetsov, Vladimir Stoiakin, Werner Sembach, Will Springer,
        Winterhuman, Xiaotian Wu, Yu Watanabe, Yuri Chornoivan,
        Zbigniew Jędrzejewski-Szmek, Zmyeir, aslepykh, chenjiayi,
        cpackham-atlnz, cunshunxia, dependabot[bot], djantti, hfavisado,
        hulkoba, ksaleem, medusalix, mille-feuille, mkubiak, mooo, msizanoen,
        networkException, nl6720, r-vdp, runiq, samuelvw01, sharad3001,
        sushmbha, wangyuhang, zzywysm, İ. Ensar Gülşen, Štěpán Němec, 我超厉害,
        김인수
```
</details>

I don't really have a preference there, so both versions look fine to me. Maybe @keszybz should take a look as well.

Possibly one note: while comparing the diffs I noticed we include `dependabot[bot]` in the output, maybe it should also get filtered out.

**Comment by yuwata** [comment]
> Possibly one note: while comparing the diffs I noticed we include `dependabot[bot]` in the output, maybe it should also get filtered out.

Done.

**Comment by teknoraver** [comment]
> @teknoraver Thanks.
> 
> @mrc0mmand Could you check again? Now the sort algo is changed, so the diff becomes much larger.

It's different because `-sn` sorts the authors by number of commits descending, but the names are still the same.

**Comment by yuwata** [comment]
> > @teknoraver Thanks.
> > @mrc0mmand Could you check again? Now the sort algo is changed, so the diff becomes much larger.
> 
> It's different because `-sn` sorts the authors by number of commits descending, but the names are still the same.

Note, now `-s` is used, rather than `-sn`. So, the sorted with the author name.

**Comment by keszybz** [comment]
LGTM too.

**Pull request merged**
