### PR TITLE
core: introduce UB to see how it goes

### PR DESCRIPTION
**Pull request by evverx**
This is mostly to make sure that the pipeline added in 52899bebc4f4a52c2e966e288fc1040aaf966375
is triggered when PRs are opened and fails as hard as it can when it has to.

### CODE REVIEW

**Comment by evverx** [comment]
To judge from https://dev.azure.com/evvers/systemd-systemd/_build/results?buildId=2, it's alive! Let's see whether it fails as expected.

**Comment by evverx** [comment]
The script failed: https://dev.azure.com/evvers/systemd-systemd/_build/results?buildId=2&view=logs&jobId=12f1170f-54f2-53f3-20dd-22fc7dff55f9&taskId=9c939e41-62c2-5605-5e05-fc3554afc9f5&lineStart=5036&lineEnd=5043&colStart=1&colEnd=48. Let me see whether `fuzzbuzz.sh` is ready to be moved there.

**Comment by evverx** [comment]
So it seems that the fuzzbuzz CLI (which downloads and builds images and runs the fuzzers against the corpora) can work in non-interactive mode while `./infra/helper.py` sometimes passes `-i` to docker and fails with
```sh
Successfully built 6bcfc7f1786e
Successfully tagged gcr.io/oss-fuzz/systemd:latest
the input device is not a TTY
the input device is not a TTY
Fuzzers build failed.
Running: docker build -t gcr.io/oss-fuzz/systemd projects/systemd
Cleaning existing build artifacts.
Running: docker run --rm -i --privileged -v /tmp/oss-fuzz/build/out/systemd:/out -t gcr.io/oss-fuzz/systemd /bin/bash -c 'rm -rf /out/*'
Running: docker run --rm -i --privileged -v /tmp/oss-fuzz/build/work/systemd:/work gcr.io/oss-fuzz-base/msan-builder bash -c 'cp -r /msan /work'
Running: docker run --rm -i --cap-add SYS_PTRACE -e FUZZING_ENGINE=libfuzzer -e SANITIZER=memory -e MSAN_LIBS_PATH=/work/msan -v /tmp/oss-fuzz/build/out/systemd:/out -v /tmp/oss-fuzz/build/work/systemd:/work -t gcr.io/oss-fuzz/systemd
##[error]Bash exited with code '1'.
##[section]Finishing: This is where it gets darker
```
Before I start adding kludges, @dor1s @jonathanmetzman would it be possible to make it possible to run `build_fuzzers` and `check_build` without `-i`?

**Comment by Dor1s** [comment]
I don't know :) cc @oliverchang who should know, please see https://github.com/systemd/systemd/pull/12542#issuecomment-491563572

**Comment by evverx** [comment]
To figure out whether it works, I pointed the script running `./infra/helper.py` to a repository where it's run without `-i`: https://github.com/evverx/oss-fuzz/commit/6260a6a62bc38e35d668526670a734b8ec00f546. To judge from https://dev.azure.com/evvers/systemd-systemd/_build/results?buildId=32&view=logs, it helps.

**Comment by evverx** [comment]
So I'm going to wrap `helper.py` up in `script` to trick it into thinking that it's "interactive". Though, it would be great if there was something like `--no-interactive` I could pass to `helper.py` to make it work smoothly in non-interactive environments.

**Comment by mrc0mmand** [comment]
I'd maybe set the `NSPAWN_TIMEOUT` and `QEMU_TIMEOUT` explicitly in https://github.com/systemd/systemd/blob/master/travis-ci/managers/xenial.sh (as we do, for example, in [CentOS CI](https://github.com/systemd/systemd-centos-ci/blob/master/vagrant/vagrant-test-sanitizers.sh#L26)) so we don't *have* to wait for the global timeout to kill the pipeline. I guess 10 - 15 minutes should be enough for the `TEST-01-BASIC`.

The `journalctl --flush` issue is being hit pretty often, but that has to be addressed by @poettering in the varlink thread.

Otherwise the PR looks pretty good, thank you!

**Comment by evverx** [comment]
@mrc0mmand thank you for the review!

I agree both NSPAWN_TIMEOUT and QEMU_TIMEOUT should be set explicitly and I also should probably change "this is where it gets darker" to something meaningful :-) I hope I'll get round to it later this week.

Regarding `journalctl --flush`, given that the same test is run on Arch and it seems to be less flaky there I think we can temporarily turn off the QEMU part on Azure Pipelines so as not to annoy people.

Anyway, I'll go ahead and merge it because I really can't take the suffering of Travis CI under a heavy load any more :-)

**Comment by oliverchang** [comment]
> I don't know :) cc @oliverchang who should know, please see [#12542 (comment)](https://github.com/systemd/systemd/pull/12542#issuecomment-491563572)

oops, missed this because of bad email filters. sorry about it! I replied on https://github.com/google/oss-fuzz/issues/2417

**Pull request merged**
