### PR TITLE
test: parallelize tasks in TEST-24-UNIT-TESTS

### PR DESCRIPTION
**Pull request by mrc0mmand**
Followup for https://github.com/systemd/systemd-centos-ci/pull/76#issuecomment-469588124.

This is a test & demonstration if parallelization is going to make any significant difference in CI jobs runtime. The `CHUNK_SIZE` still needs to be set more appropriately IMHO.

cc @evverx

### CODE REVIEW

**Comment by mrc0mmand** [comment]
I guess it could be optimized even more by replacing finished tasks with running ones immediately instead of waiting for entire chunk to complete. I'm not sure, how reliable it would be in bash, though.

**Comment by mrc0mmand** [comment]
Runtime comparison (CentOS CI, baremetal, latest master):

Old version:
```
real	1m27.396s
user	0m40.097s
sys	0m7.512s
```

New version:
```
real	0m41.590s
user	0m39.458s
sys	0m8.249s
```

**Comment by mrc0mmand** [comment]
According to the test results, the runtime, at least for the TEST-24-UNIT-TESTS in Vagrant, has been significantly reduced:

Old run:
```
[TASK] test/TEST-24-UNIT-TESTS
Waiting for PID 20390 to finish
.................................................................................................................................................................................
PID 20390 finished with EC 0 in 1771s
[RESULT] PASS (log file: /build/vagrant-arch-testsuite.UCq/TEST-24-UNIT-TESTS_PASS.log)
```

New run:
```
[TASK] test/TEST-24-UNIT-TESTS
Waiting for PID 20549 to finish
....................................................................................................................
PID 20549 finished with EC 0 in 1161s
[RESULT] PASS (log file: /build/vagrant-arch-testsuite.Gpy/TEST-24-UNIT-TESTS_PASS.log)
```

---

Also, is there any reason, why `QEMU_SMP` is not dynamically set by default, and is set to `1` for all non-ASan runs, @evverx? I guess we could save additional time by using proper `QEMU_SMP` value for all test runs. If so, I'm, again, not sure if this should be done globally in `test/test-functions` or overridden manually for each CI job.

**Comment by mrc0mmand** [comment]
After fixing the missing `nproc` dependency in QEMU (and changing the `QEMU_SMP` appropriately), there's a significant improvement in runtime on baremetal as well:

Old run:
```
[TASK] test/TEST-24-UNIT-TESTS
Waiting for PID 9245 to finish
............................
PID 9245 finished with EC 0 in 280s
[RESULT] PASS (log file: /root/testsuite-logs.NNF/TEST-24-UNIT-TESTS_PASS.log)
```

New run:
```
[TASK] test/TEST-24-UNIT-TESTS
Waiting for PID 9347 to finish
..............
PID 9347 finished with EC 0 in 140s
[RESULT] PASS (log file: /root/testsuite-logs.udy/TEST-24-UNIT-TESTS_PASS.log)
```

**Comment by mrc0mmand** [comment]
Also, by setting the `QEMU_SMP` more appropriately (ac42859fbd87730c438d184dd64fc01e497853ab), the runtime of CentOS CI Vagrant run went from 1h 40m to ~45 minutes, so it's definitely something worth looking into as well.

**Comment by keszybz** [comment]
OK, let's try this. I don't grok all the details, but it's just a test, so if it something is wrong, we can always fix things later.

**Pull request merged**
