### PR TITLE
open-file: Fix user-after-free

### PR DESCRIPTION
**Pull request by daandemeyer**

### CODE REVIEW

**Comment by vcaputo** [comment]
lgtm

**Comment by DaanDeMeyer** [comment]
> So the UAF is only in the cleanup when path_extract_filename() fails?

I think that's what causing the UAF in oss-fuzz. But yeah, we free once, do not set to NULL, path_extract_filename() fails, and we free again in the cleanup function => double free

**Comment by evverx** [comment]
@vcaputo I'm not sure if you're interested in having access to full backtraces and testcases or not but I can add your email address to https://github.com/google/oss-fuzz/blob/master/projects/systemd/project.yaml. It should be a gmail address due to https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication unfortunately. Another option would be to make all those bug reports public. This way at least testcases would be public and could be downloaded. Hopefull full backtraces should follow eventually: https://github.com/google/oss-fuzz/issues/8921#issuecomment-1356785464.

Those fuzz targets kind of reached their limit though in the sense that even the dbus parser is fuzzed it's still possible to find stuff like https://github.com/systemd/systemd/issues/23097 (that one was triggerable by unprivileged users under some circumstances as far as I can remember), even though the ndisk parser is fuzzed it can't prevent https://github.com/systemd/systemd/issues/25891 and so on.

**Comment by vcaputo** [comment]
Is there any particular reason they're not public?

Thanks for the consideration...

**Comment by evverx** [comment]
OSS-Fuzz by default follows Google's disclosure policy: https://google.github.io/oss-fuzz/getting-started/bug-disclosure-guidelines/#bug-disclosure-guidelines and uses that bug tracker for somewhat enforcing it: https://google.github.io/oss-fuzz/faq/#why-do-you-use-a-different-issue-tracker-for-reporting-bugs-in-oss-projects. In general I don't think it makes much sense when fuzz targets are public and can be run by anyone.

**Comment by evverx** [comment]
Anyway I think they should be public. @keszybz @mrc0mmand I wonder if you're fine with flipping the default by analogy with https://github.com/google/oss-fuzz/commit/a13af45f88e3678ff06f677245fbacc891e804d2?

**Pull request merged**
