### PR TITLE
fuzz-journal-remote: do not assert on resource conditions

### PR DESCRIPTION
**Pull request by keszybz**
We have a number of issues where oss-fuzz reports input-independent crashes of
fuzz-journal-remote. Instead of asserting that stuff that allocated fds and
memory never fails, let's instead just return an error.

https://oss-fuzz.com/testcase-detail/4791099424112640
https://oss-fuzz.com/testcase-detail/4531912477638656

I don't see any docs as to whether LLVMFuzzerTestOneInput() is allowed to
return non-zero. Propagating the error code is easiest, so let's just do that.
If it turns out that this causes oss-fuzz to still report a failure, we can
suppress that later.

### CODE REVIEW

**Comment by bluca** [comment]
Looks like the CI is wildly unhappy:

> Assertion 'fd >= 0 && fd < (ssize_t) s->sources_size' failed at src/journal-remote/journal-remote.c:390, function journal_remote_handle_raw_source(). Aborting.

**Comment by keszybz** [comment]
> Looks like the CI is wildly unhappy:
> 
> > Assertion 'fd >= 0 && fd < (ssize_t) s->sources_size' failed at src/journal-remote/journal-remote.c:390, function journal_remote_handle_raw_source(). Aborting.

Eh, details.

**Review by bluca — APPROVED** [review]
LGTM

**Comment by bluca** [comment]
uh, where did the bionic-* test results disappear to? Is it just me or they are not in the list?

**Comment by poettering** [comment]
i can see why letting this pass when /tmp is full makes sense. but out of fds or memory? that's an actual bug, I'd claim. I mean, malloc() never fails on Linux, unless you turn off overcommit, but i doubt google does that. and we shouldn't run out of our fds, here afaics. if we do it's our own fault, because we got a fixed pool assigned just for us, we don't share with anyone else.

maybe the journal fuzz tests should have an `(void) rlimit_nofile_bump(HIGH_RLIMIT_NOFILE);` early on btw, like journalctl has...

**Comment by poettering** [comment]
btw, do we know what the actual failure here is? is it memory or fd?

**Comment by keszybz** [comment]
> i can see why letting this pass when /tmp is full makes sense. but out of fds or memory? that's an actual bug, I'd claim. I mean, malloc() never fails on Linux, unless you turn off overcommit, but i doubt google does that. and we shouldn't run out of our fds, here afaics. if we do it's our own fault, because we got a fixed pool assigned just for us, we don't share with anyone else.

The fuzzer is linked into libFuzzer which drives multi-threaded testing. We don't control the execution environment, and we don't control and shouldn't touch resource limits. There's also allocation amplification: with memory sanitizers, the overhead of allocations can be quite large. Over all, we should assume the resource allocations can fail, and gracefully fail.

**Comment by keszybz** [comment]
> uh, where did the bionic-* test results disappear to? Is it just me or they are not in the list?

No idea. I started two by hand. This code isn't arch specific, to that should be enough.

> btw, do we know what the actual failure here is? is it memory or fd?

Nope. It only fails in the oss-fuzz runner, and only sometimes.

**Comment by poettering** [comment]
> The fuzzer is linked into libFuzzer which drives multi-threaded testing. We don't control the execution environment, and we don't control and shouldn't touch resource limits. There's also allocation amplification: with memory sanitizers, the overhead of allocations can be quite large. Over all, we should assume the resource allocations can fail, and gracefully fail.

Oh, you are seeing that libfuzzer will spawn many of our functions in parallel? hmm, i see

**Comment by keszybz** [comment]
I'll merge this here and check in oss-fuzz what the result is.

**Pull request merged**
