### PR TITLE
Cryptsetup _netdev fixes

### PR DESCRIPTION
**Pull request by keszybz**
When neither remote-cryptsetup.target or remote-cryptsetup-pre.target were pulled in, it was possible to start a _netdev unit that would not wait for the network. There was an After= dependency on remote-cryptsetup-pre.target, but since it wasn't pulled in, there was no dependency on network-online.target, and the ordering dependency was moot. Both the first and the second commit will independently fix this.

### CODE REVIEW

**Comment by fsateler** [comment]
The second commit transforms `cryptsetup-pre` from a passive to an active target (and similarly for `remote-cryptsetup-pre`, but this one is not documented in `systemd.special`).

**Comment by keszybz** [comment]
Damn, you're right. That's why remote-fs.target does not have a direct dependency on remote-fs-pre.target. I'll rework this along the same lines.

**Comment by keszybz** [comment]
After looking at this some more, I changed the commit descriptions, and undid the change to _netdev mounts (so this PR only touches _netdev crypttab devices).

I now think the way that remote-fs-pre.target is set up is unnecessarily complicated, but that's a separate story.

For reference, here's a snippet of IRC discussion about the requirement to add _netdev in crypttab and fstab:
```
21:02 <npmccallum> Also, that note is really unfortunate.
21:02 <npmccallum> It will result in support cases.
21:03 <npmccallum> Is it not possible to discover this automatically?
21:07 <zbyszek> Not really, at least not without refactoring how the whole thing works.
21:08 <zbyszek> Right now, each generator is independent (they ever run in parallel). So the fstab 
                generator just uses the device, without going out of its way to find out how the device 
                is configured.
21:08 <npmccallum> Okay, thanks...
21:09 <zbyszek> And even further, each line in fstab or crypttab is independent, and if you have /a/b 
                mountpoint which has no _netdev, and /a with _netdev, you'll get a loop.
21:09 <npmccallum> Fantastic...
21:10 <zbyszek> I was thinking about making fstab-generator an automatically propagating _netdev. But
                doing this between fstab and crypttab would be much harder.
21:10 <zbyszek> *smarter and
21:11 <zbyszek> This is something worth discussing, but the note I think is better than nothing for now.
```

**Comment by keszybz** [comment]
Hmm, I discussed this with @haraldh, and now here's yet another version. This does away with remote-cryptsetup-pre.target. Justification in the middle commit.

**Pull request merged**
