### PR TITLE
Confidentiality: constrain default machine-id file permissions

### PR DESCRIPTION
**Pull request by jayaddison**

### CODE REVIEW

**Comment by poettering** [comment]
nope. This is defined a concept to local unpriv programs. We can't take that away. that would be a massive compat break. 

This comes with a very weak concept fo confidentiality. It would be wise not to directly leak it externally, but unpriv local programs certainly should be allowed to have access.

**Comment by jayaddison** [comment]
Ok, thanks for the explanation.  In practical terms this is intended to address the idea that the set of programs that could and might leak the value only increases over time, and that requiring some level of privilege to access the contents should (dramatically, I think) reduce the angle of that curve.  Finding breakage could determine the valid use cases and possible solutions - but I understand that that's likely not acceptable (so I'm OK with no change here).

**Comment by jayaddison** [comment]
Yep, having app-based rules seems worthwhile for applications that have well-declared behaviour boundaries.  That doesn't conflict with opportunities for system-level safety improvements, though.

Long-term, avoiding potentially-untrustworthy identifier interfaces seems preferable than adding additional layers to obscure them, especially when those layers aren't cost-free in terms of computational resource, maintenance and debugging.

The question seems to be what the requirement for the identifiers is, and whether the system can function without them.  I'll do some more background reading about `machine-id` and `boot_id` soon.

**Comment by poettering** [comment]
Note that these where just examples, other unpriv accessible ids i am aware of are fs and partition uuids (which are as good as the machine ID to identify a host), subvolume uuids on btrfs, WWNs and NVME EUI, MAC addresses, usb serials, battery serial numbers, and so on. Each one of those is probably more or less as good for identifying a specific system as /etc/machine-id is. And all are world-readable.

**Comment by topimiettinen** [comment]
> Note that these where just examples, other unpriv accessible ids i am aware of are fs and partition uuids (which are as good as the machine ID to identify a host), subvolume uuids on btrfs, WWNs and NVME EUI, MAC addresses, usb serials, battery serial numbers, and so on. Each one of those is probably more or less as good for identifying a specific system as /etc/machine-id is. And all are world-readable.

That seems like an oversight. Perhaps we could help here. I use these `tmpfiles.d` rules to block NVME and USB serials:
```
z /sys/devices/*/*/*/serial 0400 root root
z /sys/devices/*/*/*/*/serial 0400 root root
z /sys/devices/*/*/*/*/*/serial 0400 root root
```
Could we ship rules like these, or perhaps add a new directive `ProtectSerials=` which would do the same?

I don't think FS or partition UUIDs are user accessible. Blocking or faking MAC addresses to unpriv users would need fixing in kernel.

**Comment by jayaddison** [comment]
It does feel like rules-based permissions could help, yep.

If a device identifier exposed by the kernel could be annotated as personally-identifiable, then perhaps the symlinks created for that identifier could be placed into directories that are created with more restrictive permissions.

**Comment by poettering** [comment]
> > 
> 
> That seems like an oversight. Perhaps we could help here. I use these `tmpfiles.d` rules to block NVME and USB serials:
> 
> ```
> z /sys/devices/*/*/*/serial 0400 root root
> z /sys/devices/*/*/*/*/serial 0400 root root
> z /sys/devices/*/*/*/*/*/serial 0400 root root
> ```
> 
> Could we ship rules like these, or perhaps add a new directive `ProtectSerials=` which would do the same?
> 
> I don't think FS or partition UUIDs are user accessible. Blocking or faking MAC addresses to unpriv users would need fixing in kernel.

Look at `udevadm info --tree` output. udev db is world readable. So is the stuff udisks and so on expose. And it's not just about the providers of such info, it's also about the consumers. i.e. for starters /etc/fstab uses the UUID paths for block devices typically, and is world readable.

identifiers are useful and that's why they exist, if you just stick your head in the sand and try to make them inaccessible as a whole then you are in a world of pain as they are *everywhere*. If you want to hide this, then fine, but do that in a pinpointed fashion, for specific unpriv apps, by locking them into a sandbox. But stuff that runs on the host itself, outside of any sandbox really should be able to use these ids, they server a purpose.

Moreover, changing access modes after these files were initially world-readable is just not how you do security...

**Comment by topimiettinen** [comment]
> Look at `udevadm info --tree` output. udev db is world readable. So is the stuff udisks and so on expose. And it's not just about the providers of such info, it's also about the consumers. i.e. for starters /etc/fstab uses the UUID paths for block devices typically, and is world readable.

```
$ udevadm info --tree
Failed to scan for devices and subsystems: Permission denied
$ cat /etc/fstab 
cat: /etc/fstab: Permission denied
```
But then there are UUIDs in mount unit files and they are world readable (until maybe I change them to mode 0400). Also memory chips and the motherboard may have serial numbers. 

> identifiers are useful and that's why they exist, if you just stick your head in the sand and try to make them inaccessible as a whole then you are in a world of pain as they are _everywhere_. If you want to hide this, then fine, but do that in a pinpointed fashion, for specific unpriv apps, by locking them into a sandbox. But stuff that runs on the host itself, outside of any sandbox really should be able to use these ids, they serve a purpose.
> 
> Moreover, changing access modes after these files were initially world-readable is just not how you do security...

OK, let's forget the tmpfiles snippet. But isn't something like `ProtectSerialNumbers=` for services viable? I don't think for example `systemd-timesyncd` would ever have any need to know any serial numbers. The directive would make some paths in `/sys` and `/run/udev`  inaccessible (perhaps assisted by udev tag rules) and maybe block access to udevd from the service.

**Comment by poettering** [comment]
> $ udevadm info --tree
> Failed to scan for devices and subsystems: Permission denied
> $ cat /etc/fstab 
> cat: /etc/fstab: Permission denied

Well, this is quite a non-standard setup you are having there. Also note that the udev database is kept in /run/, not in /sys/, thus even if you remove access mode of the latter, the former will still give you most of the data.

**Pull request closed without merging**
