### PR TITLE
Added Teclast X4 ACCEL_MOUNT_MATRIX

### PR DESCRIPTION
**Pull request by marcus905**
Hi,

I added the accelerometer matrix for my Teclast X4 2-in-1 tablet.

### CODE REVIEW

**Comment by poettering** [comment]
CI failure:

```
Cannot parse /home/runner/work/systemd/systemd/build/../hwdb.d/60-sensor.hwdb: Expected stringEnd, found '#'  (at char 30124), (line:752, col:1)
```

**Comment by poettering** [comment]
i.e. there's spurious whitespac in that separating empty line. please remove.

**Comment by marcus905** [comment]
Oh, I'm sorry. I'll make another pull request soon. Thanks!

**Comment by marcus905** [comment]
Fixed, thank you!

**Pull request merged**
