### PR TITLE
Fix memory protection default setting

### PR DESCRIPTION
**Pull request by Werkov**
### Expected behavior

> systemctl set-property bar.service MemoryLow=200M
> cat /sys/fs/cgroup/foo.slice/bar.service/memory.low
> 209715200
> 
> systemctl set-property bar.service MemoryLow=
> cat /sys/fs/cgroup/foo.slice/bar.service/memory.low
> 0 # or DefaultMemoryLow= from foo.slice

### Actual behavior

> systemctl set-property bar.service MemoryLow=200M
> cat /sys/fs/cgroup/foo.slice/bar.service/memory.low
> 209715200
> 
> systemctl set-property bar.service MemoryLow=
> cat /sys/fs/cgroup/foo.slice/bar.service/memory.low
> max

When the value is unset (via `systemctl set-property`) the behavior should return back to the default, i.e. no protection (or inherited from parent). See invididual commits for implementation details.

Cc: @cdown

### CODE REVIEW

**Comment by cdown** [comment]
Nice catch, thanks! Just went through the changes and they look good to me.

**Comment by cdown** [comment]
(A test would be nice, if possible, but I won't block you on it.)

**Comment by keszybz** [comment]
I don't have an opinion on the bus semantics change... It should work, but it'll make the returned values incompatible with the api declared for introspection. @poettering ?

**Comment by poettering** [comment]
looks ok I guess.

I don't like the macro stuff though, we should rework that one day, and turn this into regular functions that just take enough parameters to deduce what they need. code generation with macros kinda sucks, and generates a lot of duplicate code...

But that's for another PR, given that this just continues a scheme that already is in place.

**Comment by poettering** [comment]
> I don't have an opinion on the bus semantics change... It should work, but it'll make the returned values incompatible with the api declared for introspection. @poettering ?

not sure what you mean precisely?

Yes this breaks API a bit, but only in minor ways, i.e. what UINT64_MAX/0 means. But otherwise?

**Comment by poettering** [comment]
oh, sorry, i misread the patch. I grok what you mean.

Hmpf, overloading props like this with multiple is not OK I guess. We shouldn't do that...

In previouses cases we just added a separate "hidden" property that we use to communicate the additional way to pass information.

**Comment by poettering** [comment]
So I proposed #16122 now as a revert. Sorry for merging this so blindly. I apparently wasn't really awake. Either we merge #16122 or we merge a quick follow-up PR that removes the overloading of the prop (and instead introduces a new "hidden" prop with a related name that can be used to communicate that). See MemoryLimit= and MemoryLimitScale= for a blueprint for such a hidden prop.

I marked the revert PR for the next milestone, so that we don't forget about this. But this doesn't mean it has to be merged, if @Werkov provides an alternative...

**Comment by Werkov** [comment]
The DBus API of `SetProperties` [is declared](https://www.freedesktop.org/wiki/Software/systemd/dbus/) declares the type as variant, i.e. the implementation still fits the "wire" format. The analogy with *Scale didn't occur to me, it would be more consistent. Let me look into it.

**Pull request merged**
