### PR TITLE
Emit better errors for rpm macro misuse

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by mikhailnov** [comment]
Looks useful, I had to use `rpmspec --parse --trace` to find out which exactly macro gave this error.
Btw, using @bindir@/systemctl there is not correct. Here https://abf.io/import/systemd/blob/ef394a1e28/systemd.spec#lc-940 the file is put to /bin/systemctl (`-Dsplit-bin=true`), but `@bindir@` is still /usr/bin/ and macros do not work if not adjusted manually.

**Comment by mikhailnov** [comment]
I did not try to fix it in upstream because it will probably require some complex logic and I will be told that migration to /usr is needed and I would agree that it is needed.

**Comment by keszybz** [comment]
Thanks for the review.

> Btw, using `@bindir@/systemctl` there is not correct. Here https://abf.io/import/systemd/blob/ef394a1e28/systemd.spec#lc-940 the file is put to /bin/systemctl (`-Dsplit-bin=true`), but `@bindir@` is still /usr/bin/ and macros do not work if not adjusted manually.

Feel free to submit a patch which simply drops the full path from the scriptlet. It'll solve this without any additional logic.

**Pull request merged**
