### PR TITLE
mountpoint-util: make path_get_mnt_id_at() work with a NULL path

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by poettering** [comment]
This is split out of https://github.com/systemd/systemd/pull/26826.

But makes sense on its own, easily.

**Review by yuwata — APPROVED** [review]
LGTM.

Some functions added or modified by @DaanDeMeyer refuse `NULL` for path but accept `""`. But I think this PR makes sense, and we should make all `_at()` variants accept `NULL`.

@DaanDeMeyer WDYT?

**Comment by poettering** [comment]
so kernel apis expect "" usually plus an extra flag (AT_EMPTY_PATH). I find this quite cumbersome. My guess is that they require the flag so that paths that previously caused EINVAL (i.e. open("") does) would not suddenly do something and succeed. For internal APIs we define we don't need to care for that though, we can just say from the beginning that "" means the referenced inode itself for our APIs.

And across our codebase we allow NULL as shortcut for "empty set", "empty string", "empty list" and so on, depending on context. I think we should here too.

So I think in new code we should systematically allow path as NULL or as "" and then if we pass it to lower-level apis convert this to "" + AT_EMPTY_PATH (where applicable).

**Comment by DaanDeMeyer** [comment]
Makes sense, can you add a coding style update to solidify this?

**Pull request merged**
