### PR TITLE
resolved: hide public mDNS configuration knobs for now

### PR DESCRIPTION
**Pull request by zonque**

### CODE REVIEW

**Comment by johannbg** [comment]
What's the logic behind hiding the configuration knobs?

**Comment by zonque** [comment]
Don't confuse people with features that aren't ready. We're about to make a release soon, and for that, I'd like to have them out of the way. I already have a local patch queued that adds them back in.

**Comment by poettering** [comment]
Hmm, I'd have that `<!--` xml-commented `-->` instead of fully removed, but I figure the git history keeps this around too, for readding it.

**Comment by johannbg** [comment]
Just beer in mind hiding in hiding changes in the end is more or less just hiding them from testers always ( with the exception of perhaps Arch community but Tom should know how fast they adopt new releases there or if they are only adopting the stable releases ) 

As such it might be a better approach to just leave them in and flag things as "experimental" ( or just leave them in ) so you get the early exposure,adoption and feedback unless of course the release that's coming will replace the current stable release and or is flagged as such hence no experimental features should be in it as an result of that.

**Pull request merged**
