### PR TITLE
Modernize networkd-tests.py style

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
Rebased.

**Comment by yuwata** [comment]
Thank you for working this.
```
======================================================================
ERROR: test_delete_links (__main__.NetworkctlTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 394, in test_delete_links
    wait_online(['test1:degraded', 'veth99:degraded', 'veth-peer:degraded'])
  File "./test/test-network/systemd-networkd-tests.py", line 282, in wait_online
    check_output(args, env=env)
  File "./test/test-network/systemd-networkd-tests.py", line 37, in check_output
    command = command[0].split() + list(command[1:])
AttributeError: 'list' object has no attribute 'split'
```

**Comment by mrc0mmand** [comment]
One feature request when you're at it - it would be great if one could filter which test should be run to make debugging easier (as in recent ASan efforts with @evverx).

**Comment by keszybz** [comment]
>  it would be great if one could filter which tests should be run to make debugging easier 

This should be handled by the test harness. I don't think we want to duplicate such functionality in our own code.

**Comment by evverx** [comment]
@mrc0mmand looks like one of my comments in https://github.com/systemd/systemd-centos-ci/pull/117 was too vague. Just to clarify, when I was saying that "I think it would be easier to figure out what's going on if we ran the tests one by one by passing the names of the tests to systemd-networkd-tests.py" I didn't mean that it's impossible to do that. What I was trying to say is that it would be great if someone did it :-)

What would also be great if we could stick to Python 3.5. I'm looking at the "f"-strings of course :-)

**Comment by mrc0mmand** [comment]
> @mrc0mmand looks like one of my comments in [systemd/systemd-centos-ci#117](https://github.com/systemd/systemd-centos-ci/pull/117) was too vague. Just to clarify, when I was saying that "I think it would be easier to figure out what's going on if we ran the tests one by one by passing the names of the tests to systemd-networkd-tests.py" I didn't mean that it's impossible to do that. What I was trying to say is that it would be great if someone did it :-)

Ah, I see, that was indeed a misinterpretation on my side :-)

**Pull request merged**
