### PR TITLE
NEWS: add note about the CPUAffinity= changes

### PR DESCRIPTION
**Pull request by keszybz**
/cc @msekletar

### CODE REVIEW

**Comment by yuwata** [comment]
(We usually merge commits about NEWS entries without review. Should we wait for @msekletar 's comment?)

**Comment by keszybz** [comment]
I don't think we need to wait. If the text seems legible to you, this should be enough.

**Comment by yuwata** [comment]
Ok. Let's merge this as usual.

**Comment by msekletar** [comment]
LGTM too. Sorry for not responding earlier.

**Pull request merged**
