### PR TITLE
Man page updates

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by bluca** [comment]
If you are in the mood for fixing manpage syntax... any chance you know how to fix these warnings? Lintian has been bugging me since forever but I've really got no idea:

```
groff-message 193: warning [p 1, 3.0i, div '3tbd11,1', 0.0i]: can't break line [usr/share/man/man3/sd_bus_message_append_basic.3.gz:1]
groff-message 225: warning [p 1, 6.5i, div '3tbd11,1', 0.0i]: can't break line [usr/share/man/man3/sd_bus_message_read.3.gz:1]
groff-message 235: warning [p 1, 8.0i, div '3tbd11,1', 0.0i]: can't break line [usr/share/man/man3/sd_bus_message_append.3.gz:1]
groff-message 280: warning [p 1, 6.5i, div '3tbd16,1', 0.0i]: can't break line [usr/share/man/man3/sd_bus_message_read.3.gz:2]
groff-message 290: warning [p 1, 8.0i, div '3tbd16,1', 0.0i]: can't break line [usr/share/man/man3/sd_bus_message_append.3.gz:2]
groff-message 296: warning [p 1, 6.5i, div '3tbd18,1', 0.0i]: can't break line [usr/share/man/man3/sd_bus_message_read.3.gz:3]
groff-message 308: warning [p 1, 8.0i, div '3tbd18,1', 0.0i]: can't break line [usr/share/man/man3/sd_bus_message_append.3.gz:3]
groff-message 1530: warning [p 11, 5.0i, div '3tbd5,3', 0.0i]: can't break line [usr/share/man/man5/systemd.exec.5.gz:1]
groff-message 176: warning [p 2, 2.8i, div '3tbd1,0', 0.0i]: can't break line [usr/share/man/man7/systemd.net-naming-scheme.7.gz:1]
groff-message 213: warning [p 2, 0.5i, div '3tbd3,0', 0.0i]: can't break line [usr/share/man/man8/systemd-gpt-auto-generator.8.gz:2]
groff-message 266: warning [p 2, 9.8i, div '3tbd4,0', 0.0i]: can't break line [usr/share/man/man7/systemd.net-naming-scheme.7.gz:2]
groff-message 4643: warning [p 19, 29.8i, div '3tbd12,2', 0.3i]: can't break line [usr/share/man/man5/systemd.exec.5.gz:2]
groff-message 4664: warning [p 19, 29.8i, div '3tbd15,2', 0.2i]: can't break line [usr/share/man/man5/systemd.exec.5.gz:3]
groff-message 500: warning [p 4, 10.5i, div '3tbd4,0', 0.0i]: can't break line [usr/share/man/man5/systemd.unit.5.gz:1]
groff-message 85: warning [p 1, 6.5i, div '3tbd1,0', 0.2i]: can't break line [usr/share/man/man8/systemd-gpt-auto-generator.8.gz:1]
groff-message file '<standard input>', around line 244: [usr/share/man/man7/systemd.net-naming-scheme.7.gz:3]
groff-message table wider than line width [usr/share/man/man7/systemd.net-naming-scheme.7.gz:4]
```

**Review by bluca — APPROVED** [review]

**Comment by medhefgo** [comment]
May I suggest something crazy: Moving away from xml and instead use something like asciidoc?

**Comment by keszybz** [comment]
Last time I checked, asciidoc was missing many many features. It we move to something else, we should move to something good.

**Comment by keszybz** [comment]
`TEST-29-PORTABLE:                   FAIL     ( 71 s)`

**Comment by medhefgo** [comment]
> Last time I checked, asciidoc was missing many many features. It we move to something else, we should move to something good.

Do you happen to remember when that was and what sort of features you think were missing. From a cursory look, I think asciidoctor meets all the needs. And I wouldn't mind starting a conversion process unless I can find a huge show-stopper.

**Comment by keszybz** [comment]
1. I think the syntax is not all that great. In particular, when nesting markup asciidoc seems to get confused very easily. E.g. stuff like an italicized word inside of a monospaced sequence, etc.
2. Internal links that show the target title.
3. An index of terms with multiple classes. I.e. what we do now with `<term class='…'>`. Of course doing it through a postprocessing script is ugly. I would hope that this would be supported natively by the text processing tool.
4. Diagnostics for syntax and link errors.
5. Automatic inclusion of pages in indices.
6. Search over the contents.
7. Automatic TOCs.
8. Navigation between pages.
9. Uniform rendering of terms (e.g. the same font for all commands, functions, option names, etc.)
10. Reliable generation of troff man pages.

When I checked a few years ago, 1–6 and 8 were problematic on the Fedora website which uses asciidoc/antora.

**Pull request merged**
