### PR TITLE
Set maximum line length in editorconfig for C and XML files

### PR DESCRIPTION
**Pull request by andir**
As part of the review of #20479 @poettering mentioned that I didn't reflow the comments to the correct width. While working on that PR I did assume the `.editorconfig` file in the repo would contain everything relevant (as I've used and edited that in the past). I was wrong. With this PR the maximum line length with be set to 109 characters.

### CODE REVIEW

**Comment by poettering** [comment]
last time i checked this isn't part of the editorconfig spec and noone knows what it precisely is supposed to mean. For us the 109 are a "target" column, and we are flexible about it. It's used for rebreaking paragraphs and stuff.

I mean, it's OK to add this, even if this is not in the spec, but I'd prefer if we had some confirmation what this actually does for popular editors. (I am ok if "popular editors" is just the set of one editor that @andir uses).

**Comment by andir** [comment]
> last time i checked this isn't part of the editorconfig spec and noone knows what it precisely is supposed to mean. For us the 109 are a "target" column, and we are flexible about it. It's used for rebreaking paragraphs and stuff.
> 
> I mean, it's OK to add this, even if this is not in the spec, but I'd prefer if we had some confirmation what this actually does for popular editors. (I am ok if "popular editors" is just the set of one editor that @andir uses).

Mhm, you are right it doesn't seem to be in the spec. I just looked it up in their wiki and they list a couple of popular editors that support it: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#supported-by-a-limited-number-of-editors

While it is unfortunate I think it is unlikely to go away any time from any of the implementations. Any editor that doesn't support this will not have any downsides and those that support it will have a slightly different line break behavior.
I'm generally not in favor of using out-of-spec stuff but this seems like a side-quest that we shouldn't be too concerned about.

**Comment by poettering** [comment]
> Mhm, you are right it doesn't seem to be in the spec. I just looked it up in their wiki and they list a couple of popular editors that support it: https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#supported-by-a-limited-number-of-editors

"Hard line wrapping"? That sounds as if it is not what we actually want to configure. We want a "soft" target column, that's all...

**Comment by poettering** [comment]
which user do you use if i may ask?

**Comment by andir** [comment]
> which editor do you use if i may ask?

Neovim with the [editorconfig-vim](https://github.com/editorconfig/editorconfig-vim/blob/master/plugin/editorconfig.vim) plugin. The code looks like it does what the `.vimrc` in this repo does: https://github.com/editorconfig/editorconfig-vim/blob/3078cd10b28904e57d878c0d0dab42aa0a9fdc89/plugin/editorconfig.vim#L461-L471

**Comment by keszybz** [comment]
I think we can merge this… If it turns out that it's causing misbehaviour in some editor setups, we can always revert. That seems easier than trying to figure out a priori if it doesn't cause breakage somewhere.

**Pull request merged**
