### PR TITLE
ptyfwd: do not erase line after NL

### PR DESCRIPTION
**Pull request by yuwata**
Otherwise, moving upwards in less does not work.

Follow-up for https://github.com/systemd/systemd/commit/d0aa368c85adf2efa29c363a6671927fe7e8e76f.

### CODE REVIEW

**Comment by poettering** [comment]
hmmm, but that would mean the bg tinting won't work anymore?

but why would erasing after NL break scrolling up? i don't grok the relationship? is that just an observation, or do you know why precisely?

**Comment by yuwata** [comment]
> hmmm, but that would mean the bg tinting won't work anymore?
> 
> but why would erasing after NL break scrolling up? i don't grok the relationship? is that just an observation, or do you know why precisely?

That's observation base, at least with Xfce's Terminal app (and tested command is `sudo systemd-nspawn -xD /`). Without this PR, scrolling up single line in 'less' clears the second line, and hitting PgUp in 'less' clears all except for the first line. With this patch, everything including bg tinting _does_ work fine.
I do neither know why d0aa368c85adf2efa29c363a6671927fe7e8e76f does not work, nor why this works fine.

Do other terminal applications work fine without this PR?

**Comment by bluca** [comment]
> Do other terminal applications work fine without this PR?

Nope they don't, same issue in gnome-terminal (debian stable, gnome 43.9, gnome-terminal 3.46.8), trivially reproducible by booting in nspawn from main and doing journalctl | less

**Review by bluca — APPROVED** [review]
Yes this fixes the issue, and also background tinting still works here (nspawn image in mkosi was blue tinted), so let's merge this

**Pull request merged**
