### PR TITLE
hwbd: 60-sensor.hwdb: Add Pipo W2Pro

### PR DESCRIPTION
**Pull request by MRiddickW**
Add accelerometer matrix for Pipo W2Pro tablet. Y-axis was backwards (normal <--> bottom-up).

### CODE REVIEW

**Comment by poettering** [comment]
looks superficially ok to me.

/cc @hadess

**Comment by hadess** [comment]
LGTM

**Comment by jwrdegoede** [comment]
Looks good to me too.

**Review by bluca — APPROVED** [review]

**Pull request merged**
