### PR TITLE
lgtm: enable more queries

### PR DESCRIPTION
**Pull request by mrc0mmand**

### CODE REVIEW

**Comment by keszybz** [comment]
Will it find all security issues for us? ;)

Looks reasonable.

**Comment by mrc0mmand** [comment]
> Will it find all security issues for us? ;)

I certainly hope so ;)

When running some queries manually - like the cpp-uninitialized-local one - it found quite a lot issues, not sure how many of them are *real* (yet): https://lgtm.com/query/1870682584949497098/.

**Comment by keszybz** [comment]
Seems to be all false positives.

**Comment by mrc0mmand** [comment]
Yeah, I suspected. I guess it would be useful to enable just errors, since warnings and recommendations aren't very useful.

**Comment by mrc0mmand** [comment]
So, looking at the query which detects use of an uninitialized variable I got an idea that we could tweak it a bit to do the stuff I've been trying to do (and failing) with Coccinelle - detect uninitialized variables using the cleanup macros.

After spending a way too much time with CodeQL I finally managed to procure something which seems to do what it should. I need to do some more testing before trusting this completely, but it successfully complains when reverting 58d9d89b4b41189bdcea86c2ad5cf708b7d54aca, which gave us some substantial grief in RHEL (/cc @msekletar):

```
$ codeql query run --search-path ~/repos/codeql/ -d codeql_db/ /home/mrc0mmand/repos/codeql/cpp/ql/src/UninitializedVariableWithCleanup.ql -vvv
...
Starting evaluation of codeql/cpp-queries/UninitializedVariableWithCleanup.ql.                                                                                                                                                                 
Evaluation completed (845ms).                                                                                                                                                                                                                  
|       va        |                                  col1                                   |        v        |      col3       |
+-----------------+-------------------------------------------------------------------------+-----------------+-----------------+
| canonical_where | The variable $@ may not be initialized here, but has a cleanup handler. | canonical_where | canonical_where |
Shutting down query evaluator.                                                                                         
```

**Comment by mrc0mmand** [comment]
I gave this some testing and it indeed seems to work as advertised. Reverting 58d9d89 in a PR causes:

image
image

This query won't have an immediate effect, since the custom rules are processed by LGTM by a daily cron job (so it may take up to 24h for LGTM to register it).

I also went through all available LGTM queries and enabled those which (in my opinion) may be useful to have. Among these is `cpp/inconsistent-null-check`, which, when run on the current main, shows 19 alerts:

https://lgtm.com/query/4289774217412150278/ (scroll down)

I'm not completely sure about this one, but it feels like we should assert() in most (if not all) of these cases.

Anyway, PTAL.

**Comment by evverx** [comment]
I think those queries should probably be added eventually to the CodeQL action as well:  https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-codeql-query-packs

**Comment by mrc0mmand** [comment]
> I think those queries should probably be added eventually to the CodeQL action as well: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-codeql-query-packs

That's definitely on my TODO list, for now I just want to "monitor" the *new* query set for a couple of days to see how it fares.

**Comment by bluca** [comment]
> I'm not completely sure about this one, but it feels like we should assert() in most (if not all) of these cases.

Yeah, pretty sure those calls should be checked

**Comment by mrc0mmand** [comment]
> > I'm not completely sure about this one, but it feels like we should assert() in most (if not all) of these cases.
> 
> Yeah, pretty sure those calls should be checked

Sweet. In that case this PR should be ready to go, I'll prep a follow-up for the asserts later.

**Review by bluca — APPROVED** [review]

**Pull request merged**
