### PR TITLE
 Revert "core/execute: RuntimeDirectory= or friends requires mount namespace"

### LINKED ISSUE #7761: execute: RuntimeDirectory= or friends always creates unnecessary mount namespace
### Submission type

 - Bug report

### systemd version the issue has been seen with

v236

### Used distribution

Debian sid
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885325

### In case of bug report: Expected behaviour you didn't see

A mount point that is mounted manually from a SSH session is visible to systemd service

### In case of bug report: Unexpected behaviour you saw

login via SSH, mount a partition. That mount point is only visible withing the SSH session but not to systemd services.

### In case of bug report: Steps to reproduce the problem

For testing purposes I created the following service:
```
[Unit]
Description=List mount points

[Service]
Type=oneshot
ExecStart=/bin/findmnt
```
Then I logged in locally on tty1, attached an USB disk, mounted it via ```mount /dev/sdb1 /mnt/disk```, then ran ```systemctl start test.service```. Checking the journal, I get:
```
...
Dez 29 10:27:32 pluto findmnt[1532]: ├─/mnt/disk                           /dev/
Dez 29 10:27:32 pluto systemd[1]: Started List mount points.
Dez 29 10:27:32 pluto findmnt[1532]: ├─/tmp                                tmpfs
Dez 29 10:27:32 pluto findmnt[1532]: ├─/home                               /dev/
Dez 29 10:27:32 pluto findmnt[1532]: ├─/apps                               /dev/
Dez 29 10:27:32 pluto findmnt[1532]: └─/mnt/data 
```
Then I started a local SSH service, logged in as root via SSH (``` ssh root@localhost```) , mounted the partition again, started the test service again. This time I get:
```
...
Dez 29 10:28:28 pluto systemd[1]: Started List mount points.
Dez 29 10:28:28 pluto findmnt[1640]: ├─/tmp                                tmpfs
Dez 29 10:28:28 pluto findmnt[1640]: ├─/home                               /dev/
Dez 29 10:28:28 pluto findmnt[1640]: ├─/apps                               /dev/
Dez 29 10:28:28 pluto findmnt[1640]: └─/mnt/data                           /dev/
```
As can be seen the /mnt/disk mount point is not visible to test.service

This appears to be a regression in v236 as reported by the downstream bug report.

### PR DESCRIPTION
**Pull request by yuwata**
This reverts commit 652bb26.

Fixes #7761.

### CODE REVIEW

**Comment by yuwata** [comment]
@mbiebl Please take a look. I've not tested this under the situation reported in #7761.

**Comment by yuwata** [comment]
Updated. But I just split the original commits and add more commit messages.

**Comment by yuwata** [comment]
Hmm, this does not fix #7761. I will update this.

**Comment by yuwata** [comment]
Updated. Now this revert 652bb2637aee54e3503a22d2928a929ecd7a84b3. I hope this fixes #7761.

**Comment by mbiebl** [comment]
@yuwata should I test the complete PR or only the latest commit?

**Comment by yuwata** [comment]
@mbiebl Please test the complete PR. I hope that the first one fixes the issue. The consequent two commits are just clean-ups. Thank you.

**Comment by keszybz** [comment]
Yep, looks good.

**Pull request merged**
