### PR TITLE
network: further rework for reconfiguring interfaces

### LINKED ISSUE #35092: Assertion 'link->state == LINK_STATE_CONFIGURING' failed
### systemd version the issue has been seen with

257~rc1-3

### Used distribution

Debian unstable

### Linux kernel version used

6.10.2

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

systemd-networkd crashes on `networkctl reload` after changing a pppoe config.

### Steps to reproduce the problem

1. Use systemd-networkd for IPv6-PD on a PPPoE link.
/etc/systemd/network/99-ppp0.network:
    ```
    [Match]
    Name=ppp0
    Type=ppp
    
    [Link]
    ActivationPolicy=manual
    
    [Network]
    KeepConfiguration=yes
    DHCP=ipv6
    IPv6AcceptRA=yes
    
    [DHCPv6]
    WithoutRA=solicit
    UseAddress=no
    UseDNS=no
    UseNTP=no
    UseHostname=no
    UseCaptivePortal=no
    ```
3. Comment out the `WithoutRA` line.
4. `networkctl reload`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemd-networkd[563]: ppp0: Found matching .network file, based on potentially unpredictable interface name: /etc/systemd/network/99-ppp0.network
systemd-networkd[563]: ppp0: Reconfiguring with /etc/systemd/network/99-ppp0.network.
systemd-networkd[563]: Assertion 'link->state == LINK_STATE_CONFIGURING' failed at src/network/networkd-link.c:1093, function link_drop_unmanaged_config(). Aborting.
systemd[1]: systemd-networkd.service: Main process exited, code=killed, status=6/ABRT
systemd[1]: systemd-networkd.service: Failed with result 'signal'
```

### PR DESCRIPTION
**Pull request by yuwata**
Follow-ups for #35035.
Split-out of #34989.
Fixes #35092.

### CODE REVIEW

**Comment by bluca** [comment]
This looks new, although I'm not sure it's related, but it's netlink:

```
[   14.388588] TEST-62-RESTRICT-IFACES.sh[560]: + ip link del veth2
[   14.429074] BUG: unable to handle page fault for address: 000000002aeaefc7
[   14.430150] #PF: supervisor read access in kernel mode
[   14.441847] #PF: error_code(0x0000) - not-present page
[   14.442120] PGD 0 P4D 0 
[   14.442228] Oops: Oops: 0000 [#1] PREEMPT SMP NOPTI
[   14.442406] CPU: 1 UID: 0 PID: 709 Comm: ip Not tainted 6.11.5-cloud-amd64 #1  Debian 6.11.5-1
[   14.443187] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.16.3-debian-1.16.3-2 04/01/2014
[   14.443600] RIP: 0010:__dev_get_by_index+0x28/0x50
[   14.443794] Code: 90 90 f3 0f 1e fa 0f 1f 44 00 00 48 8b 87 30 01 00 00 40 0f b6 d6 48 8b 04 d0 48 [85](https://github.com/systemd/systemd/actions/runs/11715859745/job/32632963390?pr=35059#step:12:86) c0 74 1f 48 2d 40 04 00 00 48 85 c0 74 14 <39> b0 e0 00 00 00 74 0c 48 8b 80 40 04 00 00 48 85 c0 75 e1 e9 ba
[   14.445404] RSP: 0018:ffffa27f80ab3890 EFLAGS: 00010206
[   14.445774] RAX: 000000002aeaeee7 RBX: ffff8e08[86](https://github.com/systemd/systemd/actions/runs/11715859745/job/32632963390?pr=35059#step:12:87)d64000 RCX: ffffffff981f2820
[   14.446260] RDX: 0000000000000000 RSI: 0000000000000000 RDI: ffff8e08[87](https://github.com/systemd/systemd/actions/runs/11715859745/job/32632963390?pr=35059#step:12:88)7933c0
[   14.446430] RBP: ffff8e0886d64000 R08: 0000000000000000 R09: 0000000000000000
[   14.446605] R10: 0000000000000001 R11: 0000000000000000 R12: ffffa27f80ab33b0
[   14.446766] R13: ffff8e0[88](https://github.com/systemd/systemd/actions/runs/11715859745/job/32632963390?pr=35059#step:12:89)6d64520 R14: 0000000000000000 R15: 0000000000000000
[   14.446972] FS:  00007ffbefd3a800(0000) GS:ffff8e08fbd00000(0000) knlGS:0000000000000000
[   14.447338] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   14.447481] CR2: 000000002aeaefc7 CR3: 000000010a878006 CR4: 0000000000370ef0
[   14.447663] Call Trace:
[   14.447962]  <TASK>
[   14.448136]  ? __die_body.cold+0x19/0x27
[   14.448383]  ? page_fault_oops+0x15a/0x2d0
[   14.448671]  ? exc_page_fault+0x7e/0x180
[   14.448742]  ? asm_exc_page_fault+0x26/0x30
[   14.448807]  ? __dev_get_by_index+0x28/0x50
[   14.44[89](https://github.com/systemd/systemd/actions/runs/11715859745/job/32632963390?pr=35059#step:12:90)23]  rfc2863_policy+0x44/0xd0
[   14.449013]  linkwatch_do_dev+0x16/0x60
[   14.449106]  netdev_run_todo+0xb0/0x530
[   14.449238]  ? srso_alias_return_thunk+0x5/0xfbef5
[   14.449357]  ? security_capable+0x44/0x70
[   14.449438]  rtnetlink_rcv_msg+0x14d/0x3f0
[   14.449543]  ? __pfx_rtnetlink_rcv_msg+0x10/0x10
[   14.450286]  netlink_rcv_skb+0x53/0x100
[   14.450676]  netlink_unicast+0x245/0x3[90](https://github.com/systemd/systemd/actions/runs/11715859745/job/32632963390?pr=35059#step:12:91)
[   14.450892]  netlink_sendmsg+0x21b/0x470
[   14.451090]  ____sys_sendmsg+0x3a0/0x3d0
[   14.451317]  ? srso_alias_return_thunk+0x5/0xfbef5
[   14.451488]  ___sys_sendmsg+0x9a/0xe0
[   14.451811]  ? syscall_exit_to_user_mode_prepare+0x149/0x170
[   14.452837]  __sys_sendmsg+0xcc/0x100
[   14.452963]  do_syscall_64+0x82/0x160
[   14.453135]  ? srso_alias_return_thunk+0x5/0xfbef5
[   14.453301]  ? __count_memcg_events+0x58/0xf0
[   14.453458]  ? srso_alias_return_thunk+0x5/0xfbef5
[   14.453576]  ? count_memcg_events.constprop.0+0x1a/0x30
[   14.453715]  ? srso_alias_return_thunk+0x5/0xfbef5
[   14.453881]  ? handle_mm_fault+0x1bb/0x2c0
[   14.454036]  ? srso_alias_return_thunk+0x5/0xfbef5
[   14.454151]  ? do_user_addr_fault+0x36c/0x620
[   14.454377]  ? srso_alias_return_thunk+0x5/0xfbef5
[   14.454569]  ? srso_alias_return_thunk+0x5/0xfbef5
[   14.455351]  entry_SYSCALL_64_after_hwframe+0x76/0x7e
[   14.4558[91](https://github.com/systemd/systemd/actions/runs/11715859745/job/32632963390?pr=35059#step:12:92)] RIP: 0033:0x7ffbeffd7bf0
[   14.456863] Code: 00 f7 d8 64 89 02 b8 ff ff ff ff eb bb 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 00 80 3d 79 c4 0d 00 00 74 17 b8 2e 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 58 c3 0f 1f 80 00 00 00 00 48 83 ec 28 89 54
[   14.457252] RSP: 002b:00007ffe3d5f4f18 EFLAGS: 00000202 ORIG_RAX: 000000000000002e
[   14.457424] RAX: ffffffffffffffda RBX: 00000000672c38e1 RCX: 00007ffbeffd7bf0
[   14.457564] RDX: 0000000000000000 RSI: 00007ffe3d5f4f80 RDI: 0000000000000003
[   14.457720] RBP: 00007ffe3d5f4f80 R08: 0000000000000010 R09: 0000000000000004
[   14.457891] R10: 00007ffe3d5f49b4 R11: 0000000000000202 R12: 00007ffe3d5f5670
[   14.458077] R13: 0000000000000000 R14: 000055ebb2e14020 R15: 0000000000000000
[   14.458247]  </TASK>
[   14.458341] Modules linked in: veth intel_rapl_msr intel_rapl_common iosf_mbi kvm_amd kvm nls_ascii nls_cp437 vfat fat button evdev serio_raw binfmt_misc nfnetlink ip_tables btrfs blake2b_generic xor raid6_pq libcrc32c crct10dif_pclmul crc32_pclmul crc32c_intel ghash_clmulni_intel sha512_ssse3 virtio_scsi scsi_mod sha256_ssse3 sha1_ssse3 virtio_blk virtio_balloon scsi_common loop efi_pstore dm_mod configfs qemu_fw_cfg vmw_vsock_virtio_transport vmw_vsock_virtio_transport_common vsock virtio_console virtio_rng x_tables autofs4 aesni_intel gf128mul crypto_simd cryptd
[   14.459647] CR2: 000000002aeaefc7
[   14.459751] ---[ end trace 0000000000000000 ]---
[   14.459890] RIP: 0010:__dev_get_by_index+0x28/0x50
[   14.460037] Code: 90 90 f3 0f 1e fa 0f 1f 44 00 00 48 8b 87 30 01 00 00 40 0f b6 d6 48 8b 04 d0 48 85 c0 74 1f 48 2d 40 04 00 00 48 85 c0 74 14 <39> b0 e0 00 00 00 74 0c 48 8b 80 40 04 00 00 48 85 c0 75 e1 e9 ba
[   14.460499] RSP: 0018:ffffa27f80ab3890 EFLAGS: 00010206
[   14.460614] RAX: 000000002aeaeee7 RBX: ffff8e0886d64000 RCX: ffffffff981f2820
[   14.460830] RDX: 0000000000000000 RSI: 0000000000000000 RDI: ffff8e08877[93](https://github.com/systemd/systemd/actions/runs/11715859745/job/32632963390?pr=35059#step:12:94)3c0
[   14.461023] RBP: ffff8e0886d64000 R08: 0000000000000000 R09: 0000000000000000
[   14.461197] R10: 0000000000000001 R11: 0000000000000000 R12: ffffa27f80ab33b0
[   14.461350] R13: ffff8e0886d64520 R14: 0000000000000000 R15: 0000000000000000
[   14.461520] FS:  00007ffbefd3a800(0000) GS:ffff8e08fbd00000(0000) knlGS:0000000000000000
[   14.461724] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   14.461904] CR2: 000000002aeaefc7 CR3: 000000010a878006 CR4: 0000000000370ef0
[   14.462116] Kernel panic - not syncing: Fatal exception
[   14.462739] Kernel Offset: 0x15400000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
```

**Comment by yuwata** [comment]
Even if it is triggered by a netlink call, this is certainly a bug in the kernel.

**Comment by yuwata** [comment]
> Can you report it to netdev please?

I cannot find the CI result anymore... If we hit the error again, I will do.

**Comment by bluca** [comment]
Maybe the backtrace would be enough? Could be a known issue

**Review by bluca — APPROVED** [review]

**Pull request merged**
