### PR TITLE
various fixes to pam_systemd + pam_systemd_home

### PR DESCRIPTION
**Pull request by poettering**
Most robustness fixes, addressing various ugly log messages seen in the PAM logs when using "sudo" and such.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
CentOS CI's fail is a flake (see https://github.com/systemd/systemd-centos-ci/issues/251#issuecomment-624890277).

**Comment by mrc0mmand** [comment]
I though the `TEST-43-PRIVATEUSER-UNPRIV` fail is a flake, as I commented above, but after a closer look, the issue is different and probably related to this PR (since it failed the same way in every run, i.e. three consecutive times):

```
[   14.427019] testsuite-43.sh[340]: + su testuser -s /bin/sh -c 'XDG_RUNTIME_DIR=/run/user/$UID exec "$@"' -- sh systemd-run --user --unit=test-private-users -p PrivateUsers=yes -P echo hello
[   14.458414] audit[342]: USER_AUTH pid=342 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication grantors=pam_rootok acct="testuser" exe="/usr/bin/su" hostname=? addr=? terminal=? res=success'
[   14.458694] audit[342]: USER_ACCT pid=342 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:accounting grantors=pam_unix acct="testuser" exe="/usr/bin/su" hostname=? addr=? terminal=? res=success'
[   14.458802] su[342]: (to testuser) root on none
[   14.471992] systemd[1]: n/a: New incoming connection.
[   14.472184] systemd[1]: n/a: Connections of user 0: 0 (of 1024 max)
[   14.472270] systemd[1]: varlink-54: varlink: setting state idle-server
[   14.472353] systemd[1]: varlink-54: New incoming message: {"method":"io.systemd.UserDatabase.GetMemberships","parameters":{"userName":"testuser","service":"io.systemd.DynamicUser"},"more":true}
[   14.472437] systemd[1]: varlink-54: varlink: changing state idle-server → processing-method-more
[   14.472518] systemd[1]: varlink-54: Sending message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
[   14.472596] systemd[1]: varlink-54: varlink: changing state processing-method-more → processed-method
[   14.472755] systemd[1]: varlink-54: varlink: changing state processed-method → idle-server
[   14.473333] audit[342]: CRED_ACQ pid=342 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="testuser" exe="/usr/bin/su" hostname=? addr=? terminal=? res=success'
[   14.473455] systemd[1]: varlink-54: Got POLLHUP from socket.
[   14.473584] systemd[1]: varlink-54: varlink: changing state idle-server → pending-disconnect
[   14.473674] su[342]: pam_unix(su:session): session opened for user testuser by (uid=0)
[   14.474211] systemd[1]: varlink-54: varlink: changing state pending-disconnect → processing-disconnect
[   14.474349] systemd[1]: varlink-54: varlink: changing state processing-disconnect → disconnected
[   14.474547] audit[342]: USER_START pid=342 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_open grantors=pam_unix acct="testuser" exe="/usr/bin/su" hostname=? addr=? terminal=? res=success'
[   14.538751] testsuite-43.sh[343]: Failed to create bus connection: No such file or directory
[   14.544142] su[342]: pam_unix(su:session): session closed for user testuser
[   14.544411] audit[342]: USER_END pid=342 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_close grantors=pam_unix acct="testuser" exe="/usr/bin/su" hostname=? addr=? terminal=? res=success'
[   14.544529] audit[342]: CRED_DISP pid=342 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="testuser" exe="/usr/bin/su" hostname=? addr=? terminal=? res=success'
[   14.557645] systemd[1]: Received SIGCHLD from PID 340 (bash).
[   14.557802] systemd[1]: Child 340 (bash) died (code=exited, status=1/FAILURE)
[   14.557914] systemd[1]: testsuite-43.service: Child 340 belongs to testsuite-43.service.
[   14.558178] systemd[1]: testsuite-43.service: Main process exited, code=exited, status=1/FAILURE

```

Full journal: https://ci.centos.org/job/systemd-pr-build-vagrant/7206/artifact//systemd-centos-ci/artifacts_ilwICC/vagrant-logs.if6/vagrant-arch-testsuite.f9h/TEST-43-PRIVATEUSER-UNPRIV/system.journal

**Comment by poettering** [comment]
I split the two first remaining commits into another separate PR, in #15794. Let's see if that works.

**Comment by poettering** [comment]
#15864 consists of two more split out commits now.

**Comment by poettering** [comment]
So, after only one commit is left in this PR I figure I know what's going on: the test fails because it starts user@.service for a test user without letting logind do that, but directly. But in that case there is likely no User object instantiated for the user, since after all the user was not see before. And the remaining patch asks logind about the runtime dir of the user, from the pam module which then fails.

I figure what is missing here is a concept of a RefUser() call or so, which returns an fd and instantiates a user without creating a session. so that CreateSession() creates a user and thus implicitly refs a user, and that RefUser() only refs the user without creating a session. A user would only be destroyed when all its sessions and direct refs are gone.

**Comment by poettering** [comment]
Obsoleted by #30226

**Pull request closed without merging**
