### PR TITLE
systemctl: rework properties to use bus_map_all_properties

### PR DESCRIPTION
**Pull request by ssahani**
- Rework systemctl's GetAll property parsing to use the generic
  bus_map_all_properties() API

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, the indentation of this patch is weird, all that inner whitespace.

I think moving to bus_map_all_properties() makes a lot of sense, but only for the "systemctl status" codepath, not for the "systemctl show" codepath. I think we should just seperate those two out, the fact that they are intermingled don#t really help readabilityanyway I must say.

**Comment by ssahani** [comment]
yes that makes sense. About indenting I must say I was confused what would look better .

**Comment by ssahani** [comment]
I think this should make use of `unit_exists`  too.

**Comment by ssahani** [comment]
Closing this one will open a new PR based on comments thanks .

**Pull request closed without merging**
