### PR TITLE
basic: add fallback in chase_symlinks_and_opendir() for cases when /proc is not mounted

### PR DESCRIPTION
**Pull request by msekletar**
https://bugzilla.redhat.com/show_bug.cgi?id=2136916

### CODE REVIEW

**Comment by msekletar** [comment]
Not sure about this fix so marking as draft.

But I think we should fix the issue rather sooner then later as we operate in enviroment where /proc isn't mounted often (e.g. installer chroot()) and `systemctl preset` is completely borked now because it consideres *everything* to be enabled.

@poettering @keszybz PTAL.

For minimal reproducer see, https://bugzilla.redhat.com/show_bug.cgi?id=2136916#c26

**Comment by poettering** [comment]
This really is a bug in their chroot environment. half the Linux api is available through procfs, they have to mount it (and sysfs too) into their chroot env before invoking dnf. Sorry. But this is just broken in their tool. Our approach so far has been to generate recognizable errors in this case, but working around this cannot work. Just fix it properly in their code. Mounting procfs and sysfs before invoking dnf isnt particularly hard...

**Comment by msekletar** [comment]
I understand your point of view but this implicit requirement (i.e. systemctl unit file management verbs work properly only in environments where /proc is mounted") is new. We should mention it also in the NEWS so people are not surprised and have the chance to adjust their stuff. Also, we don't know what are all the tools that are affected.

In any case we should either check for this and refuse to do anything if /proc isn't mounted or have the fallback as proposed here. Current state isn't acceptable in my opinion. We pretend it doesn't matter that /proc isn't mounted and as a result we wreak complete havoc in the unit file directories and enable every unit file that we can. To me the current state is a clear regression.

**Comment by poettering** [comment]
It's not new though, this came up over and over again. We even added infra to detect these cases better: 883fff25f4841bcaec88ef49078b3512ce6eb07c

Where this came up before: 1a25a77f3e87d88e7bdd0e883527fe3b8abeb3cd 01131684ac66e82faae18e40e110089003d7c536 f8606626ed3c2582e06543550d58fe9886cdca5f

and so on and so on.

And this will become more and more and more, as we switch to using O_PATH fds more, to eliminate races arounds path handling. Because the only way how you can convert an O_PATH fd to a proper one is via /proc/self/fd/

Sorry, but the first time this came up this should have been fixed in your build environment, the fact that this still comes up, over and over and over again and the build environment still is a mess is sad. Just fix the thing.

We can certainly replicate 01131684ac66e82faae18e40e110089003d7c536 in systemctl, but then we also have to replicate it for bootctl, and basically all our programs.

**Comment by msekletar** [comment]
> We can certainly replicate [0113168](https://github.com/systemd/systemd/commit/01131684ac66e82faae18e40e110089003d7c536) in systemctl, but then we also have to replicate it for bootctl, and basically all our programs.

I think we should do that.

**Comment by keszybz** [comment]
Yeah, we don't really have a choice. This used to work, even if the environment is not set up "correctly", and needs to continue to work. For new functionality, we can add additional constraints, as long as they are documented and error messages are clear. But we can't just break existing scriptlets in all rpm invocations.

Patch LGTM. If we're in a chroot environment and `/proc` is not mounted, taking this fallback path is OK.

**Comment by poettering** [comment]
I am sorry. But this is conceptually wrong and code-wise wrong (ignores --root=). Sorry, this should not have gotten in.

Come on, we are having this dicussion every other year. We can't turn back time to go back from O_PATH.

And please, let's not merge broken code.

**Comment by poettering** [comment]
> Yeah, we don't really have a choice. 

We don't? How so?

**Comment by poettering** [comment]
btw, chase_symlinks_and_opendir() actually already contains a shortcut to just opendir() when it's safe to do. So here you thus add a *second* shortcut to opendir() that apparently is called in a context it really shouldn't be called from apparently.

**Comment by poettering** [comment]
I'd be fine with adding a fallback that if /proc/ is not mounted will use the new kernel mount API to acquire an unattached superblock to procfs, and then convert the fd through that.

And seriously, this has been an issue years ago: did anyone who cares about this ever bothered to ping the rpm folks to just fix the environment this is called in?

**Comment by keszybz** [comment]
> I am sorry. But this is conceptually wrong and code-wise wrong (ignores --root=). Sorry, this should not have gotten in.
> 
> Come on, we are having this dicussion every other year. We can't turn back time to go back from O_PATH.
> 
> And please, let's not merge broken code.

This is pretty tiring and counterproductive. You apparently looked the pull request, and had some questions but no comments about the implementation. Your questions were answered by @msekletar above, and I provided some additional explanation. Since all the issues that were raised have been resolved, and the patch was simple enough, I merged the pull request. Saying "please let's not merge broken code" implies that the code was merged knowingly broken. There is no basis for this accusation.

In the future, if you notice that a patch is broken, please comment. And if you notice after it's been already merged, still comment. In cases where the fix is really trivial, it's much nicer to immediately merge a fix than to deal with a revert.

> > Yeah, we don't really have a choice.
> 
> We don't? How so?

Well, the rest of my comment was answering that question.

**Comment by poettering** [comment]
@keszybz the way I read it @msekletar already agreed we should instead just replicate 01131684ac66e82faae18e40e110089003d7c536 in systemctl too. (see https://github.com/systemd/systemd/pull/25581#issuecomment-1333589687)  But then suddenly this patch was just merged, without chance for a further discussion. I am not happy if that discussion is that just ignored and a patch is basically merged without any code review.

**Comment by keszybz** [comment]
What do you mean "without code review"? I reviewed the patch before merging it, and actually tested it on my system. I missed the thing about root, but well, bugs do slip through review occasionally. I assume you also looked at the patch and apparently didn't have any comments about the implementation, so I assumed that the *implementation* is OK. Since this is fixing a major regression in functionality I wanted to merge this sooner later than later.

> @msekletar already agreed we should instead just replicate https://github.com/systemd/systemd/commit/01131684ac66e82faae18e40e110089003d7c536 in systemctl too

I missed that. I don't think this is a good idea, but it's a separate topic anyway: we need to fix the regression asap, and then we can talk about introducing additional warnings and requirements at leisure.

**Pull request merged**
