### PR TITLE
Reduce test boilerplate

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by mrc0mmand** [comment]
`TEST-31-DEVICE-ENUMERATION` started consistently failing in CentOS CI:

```
Oct 08 09:30:49 systemd-testsuite systemd[462]: systemd-logind.service: Executing: /sbin/modprobe -abq drm
Oct 08 09:30:49 systemd-testsuite systemd[1]: dev-cdrom.device: Changed dead -> plugged
Oct 08 09:30:49 systemd-testsuite bash[466]: Oct 08 08:30:49 systemd-testsuite bash[466]: + grep -e '\.device: Changed plugged -> dead'
Oct 08 09:30:49 systemd-testsuite bash[466]: + exit 1
Oct 08 09:30:49 systemd-testsuite systemd[1]: Received SIGCHLD from PID 466 (bash).
Oct 08 09:30:49 systemd-testsuite systemd[1]: Child 466 (bash) died (code=exited, status=1/FAILURE)
Oct 08 09:30:49 systemd-testsuite systemd[1]: testsuite.service: Child 466 belongs to testsuite.service.
Oct 08 09:30:49 systemd-testsuite systemd[1]: testsuite.service: Main process exited, code=exited, status=1/FAILURE
Oct 08 09:30:49 systemd-testsuite systemd[1]: testsuite.service: Failed with result 'exit-code'.
Oct 08 09:30:49 systemd-testsuite systemd[1]: testsuite.service: Changed start -> failed
Oct 08 09:30:49 systemd-testsuite systemd[1]: testsuite.service: Job 195 testsuite.service/start finished, result=failed
Oct 08 09:30:49 systemd-testsuite systemd[1]: Failed to start Testsuite service.
Oct 08 09:30:49 systemd-testsuite systemd[1]: testsuite.service: Unit entered failed state.
Oct 08 09:30:49 systemd-testsuite systemd[1]: Child 462 (modprobe) died (code=exited, status=1/FAILURE)
```

[Full journal](https://ci.centos.org/job/systemd-pr-build/8347/artifact//systemd-centos-ci/artifacts_1b5vUl/testsuite-logs-upstream.1XI/TEST-31-DEVICE-ENUMERATION/journal/cdb068f193244fdab01286949df3fdc8/system.journal) from the CentOS 7 job

Journal from the KVM job should be available soon

**Comment by mrc0mmand** [comment]
Ah, I see, it now matches the grep command itself, as it's logged into journal as well, thanks to `set -x`, ugh.

**Comment by mrc0mmand** [comment]
I guess we can't use `--grep` without tweaking the CI configuration first:

```
Oct 08 11:33:59 systemd-testsuite bash[462]: Compiled without pattern matching support
Oct 08 11:33:58 systemd-testsuite systemd[459]: Not remounting /run/systemd/unit-root/var/tmp blacklisted by /run/systemd/unit-root/var/tmp, called for /run/systemd/unit-root
Oct 08 11:33:59 systemd-testsuite bash[462]: + exit 1
```

**Comment by keszybz** [comment]
> I guess we can't use --grep without tweaking the CI configuration first:

Can we do that? I think it'd be useful to dogfood.

**Comment by mrc0mmand** [comment]
> > I guess we can't use --grep without tweaking the CI configuration first:
> 
> Can we do that? I think it'd be useful to dogfood.

I noticed that we already do that in the Arch jobs, so enabling it for the CentOS 7 job makes sense. I pushed the fix and re-triggered the failing job.

**Comment by keszybz** [comment]
I'll just merge this. After all, it's just tests and the change is rather trivial. This should fix TEST-40 flakiness.

**Comment by filbranden** [comment]
Thanks for taking care of this @keszybz !

Let's now see if this will take care of most of the flakiness...

**Pull request merged**
