### PR TITLE
Restore backwards compat in 60-evdev.rules

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Review by yuwata — APPROVED** [review]
This slightly changes the way that the commit 57bb707d48131f4daad2b1b746eab586eb66b4f3 expects, i.e., the commit expects we can override the entry in the non-extended format by specifying an extended entry, but now we need to first undo what the non-extended entry specified in the extend entry:

If we have the following
```
evdev:name:foo:dmi:*
 PROP_A=foo
evdev:name:foo:phys:phys_xxx:ev:*:dmi:*
 PROP_B=bar
```
then, a device matching with the extended format had only `PROP_B`, but now it has both `PROP_A` and `PROP_B`. Hence, we need to rewrite the hwdb like the following:
```
evdev:name:foo:dmi:*
 PROP_A=foo
evdev:name:foo:phys:phys_xxx:ev:*:dmi:*
 PROP_A=
 PROP_B=bar
```
But I think this is the way to go.
Fortunately, our hwdb does not have entry with the extended format.

**Comment by yuwata** [comment]
cc @jwrdegoede

**Comment by keszybz** [comment]
Yes, this is true. But I think it's acceptable.
I expect that if you have two devices with the same name on the same system, you'd add two extended matches, instead of one extended match and one non-extended match.

**Comment by yuwata** [comment]
Let's wait @jwrdegoede's comment for a while before merge.

**Comment by jwrdegoede** [comment]
This is not really my area of expertise, with that said this looks good to me and I have no objections against merging this.

**Comment by yuwata** [comment]
@jwrdegoede Thank you! Merging.

**Comment by yuwata** [comment]
I set 'stable-backport' tag, but feel free to drop it, if you do not think this should be backported.

**Comment by keszybz** [comment]
> I set 'stable-backport' tag, but feel free to drop it, if you do not think this should be backported.

I think we should. There *might* be people who are relying on the new behaviour, but I hope that's at most a small minority.

**Pull request merged**
