### PR TITLE
test: temporarily block test 48 on Ubuntu's autopkgtest

### PR DESCRIPTION
**Pull request by bluca**
This test runs fine locally (both on Qemu and nspawn) but sporadically fails on
autopkgtest for some reason.
Disable it while the issue is investigated to reduce noise.

### CODE REVIEW

**Comment by ddstreet** [comment]
the ubuntu ci tests don't seem to be getting run at all since early this morning, did they get disabled?

**Comment by mrc0mmand** [comment]
Ignore the CentOS CI fail, that's #15978...

**Comment by evverx** [comment]
> the ubuntu ci tests don't seem to be getting run at all (for any PR) since early this morning, did they get disabled?

@ddstreet no, they didn't. Some of the requests seem to have timed out
Screenshot 2020-06-01 at 16 22 53

According to https://www.githubstatus.com/, the webhooks are operational so it seems something is going on on the Ubuntu CI side.

**Comment by ddstreet** [comment]
@evverx do you have the ubuntu ci retry script?  or @keszybz ?  I don't have it myself, nor do i have access to the credentials to submit systemd-upstream test re-runs.  Could either of you re-submit the ubuntu ci tests for this to see if it's still timing out trying to submit?  If you can share the script (and credentials) with me I could try re-running tests in the future.

**Comment by evverx** [comment]
@ddstreet I restarted Ubuntu CI by pressing the "redeliver" button on the "webhooks "dashboard.

> @evverx do you have the ubuntu ci retry script?

No, I don't. I think @keszybz has it but as far as I know it has never been updated in the sense that it still points to the wrong branch and passes environments variables that are different from the ones passed via the webhooks so I wouldn't recommend using it.

**Comment by evverx** [comment]
FWIW I don't have the credentials either.

**Comment by ddstreet** [comment]
> @ddstreet I restarted Ubuntu CI by pressing the "redeliver" button on the "webhooks "dashboard.

Thanks!  It looks like rabbitmq had died in the ubuntu ci infrastructure, so we just got it restarted and hopefully things should work again.

> No, I don't. I think @keszybz has it but as far as I know it has never been updated in the sense that it still points to the wrong branch and passes environment variables that are different from the ones passed via the webhooks so I wouldn't recommend using it.

ack, if there's a button in the github webhooks dashboard, probably best to just use that instead of the script.

**Comment by evverx** [comment]
> if there's a button in the github webhooks dashboard, probably best to just use that instead of the script.

Given that the requests aren't grouped by PR and are scattered over the five different webhooks I would say it isn't always obvious which button should be pressed so I think it would be better to keep the script in sync (somewhere in the systemd repository) and give the credentials to people who should probably have them. Though unfortunately nobody who can do that has gotten round to it.

**Comment by keszybz** [comment]
> I think @keszybz has it but as far as I know it has never been updated in the sense that it still points to the wrong branch and passes environment variables that are different from the ones passed via the webhooks so I wouldn't recommend using it.

Exactly. And I have no idea how to update it.

> I think it would be better to keep the script in sync (somewhere in the systemd repository)

```sh

#!/bin/sh -e
# this needs https://git.launchpad.net/autopkgtest-cloud/plain/tools/retry-github-test
[ -n "$2" ] || { echo "Usage: $0 <PR> <arch> [release]" >&2; exit 1; }

#if [ "$2" = i386 ]; then
#    branch="%23mpitt/ci-loop-debug"
#fi
#branch="%23master"
branch="%23upstream-ci"

./retry-github-test https://api.github.com/repos/systemd/systemd/pulls/$1 'https://autopkgtest.ubuntu.com/request.cgi?release='${3:-bionic}'&arch='$2'&build-git=https%3A%2F%2Fsalsa.debian.org%2Fsystemd-team%2Fsystemd.git'$branch'&env=CFLAGS%3D-O0%3BDEB_BUILD_PROFILES%3Dnoudeb%3BTEST_UPSTREAM%3D1%3BCONFFLAGS_UPSTREAM%3D--werror&package=systemd-upstream&ppa=upstream-systemd-ci%2Fsystemd-ci' ./github-secret-systemd.txt
```
If someone knows the right values to plug into this, please submit it as PR to add it to tools/.

**Comment by keszybz** [comment]
Anyway, let's merge this. `bionic-amd64` timed out.

**Pull request merged**
