### PR TITLE
man: alias names can't be used with enable command

### PR DESCRIPTION
**Pull request by fbuihuu**
It's actually described in the next paragraph.

### CODE REVIEW

**Comment by hramrach** [comment]
- it does not mention the enable command
 - doesn't systemd know about the aliases since it reads the unit files in advance? Can't it enable the service that provides the alias if there is only one?

**Comment by fbuihuu** [comment]
>     * it does not mention the enable command

Indeed. Then I think it should be clarified unless I misunderstood how aliases are supposed to work...

>     * doesn't systemd know about the aliases since it reads the unit files in advance?

systemd doesn't load all existing units, it just loads the units it needs to operate on, probably for speed concerns.

> Can't it enable the service that provides the alias if there is only one?

What do you mean by "if there's only one" ?

I don't think the same alias can be shared by several units if that what you meant.

**Comment by fbuihuu** [comment]
If I try to enable a service through its alias name and the service was already enabled, I can see:

```
# systemctl enable network
Failed to enable unit: Too many levels of symbolic links
```

which is not really meaningful.

**Comment by fbuihuu** [comment]
I pushed a fix so the message is hopefully a bit clearer.

```
# systemctl enable network
Failed to enable unit: Refusing to operate on alias name or linked unit file: network.service
```

**Comment by hramrach** [comment]
> > ```
> > * it does not mention the enable command
> > ```
> 
> Indeed. Then I think it should be clarified unless I misunderstood how aliases are supposed to work...
> 
> > ```
> > * doesn't systemd know about the aliases since it reads the unit files in advance?
> > ```
> 
> systemd doesn't load all existing units, it just loads the units it needs to operate on, probably for speed concerns.

How it can enable a unit that is disabled then? 

It would not know about it because it does not need to operate on it, right?

However it learns about units currently disabled to perform the enable operation it learns about their aliases as well.

> 
> > Can't it enable the service that provides the alias if there is only one?
> 
> What do you mean by "if there's only one" ?
> 
> I don't think the same alias can be shared by several units if that what you meant.

What's stopping them?

Of course, only one will own the alias at a time but if there are multiple providers and none owns it the alias is ambiguous.

**Comment by hramrach** [comment]
> I pushed a fix so the message is hopefully a bit clearer.
> 
> ```
> # systemctl enable network
> Failed to enable unit: Refusing to operate on alias name or linked unit file: network.service
> ```

Why is it refusing to operate on alias? If it finds the unit it can as well enable it. Also if cannot not it should at least give you the non-aliased unit name rather just saying "Fuck you, not doing that."

**Comment by keszybz** [comment]
Originally, the thinking was that `systemctl enable` *creates* aliases, so we shouldn't use aliases to decide what to operate on. But I agree with @hramrach that that seems bogus — if we were able to find the unit, we should shut up and just do the job.

There's a tricky aspect this though: if a unit has `[Install] Also=foobar-alias.service`, we the unit is not enabled, would have to read the unit file to see the alias. In that case, I think it's fine if we just say "cannot find unit".

How hard would it be to rework this to simply allow `enable` to operate on aliases that are already present on disk?

**Comment by boucman** [comment]
What are alias for ? I alwasy thought that the point was to have all ssh servers have a common alias, so people could Want sshd.service and not care what implementation was used...

If my understanding is correct, there is a need for Also=<an alias> but that might be a TODO for a later time...

**Comment by fbuihuu** [comment]
That's what I initially thought too but given that aliases can easily
lead to inconsistent states and many behaviors are still undefined,
I'm not sure anymore...

Some questions:

Let's have {a,b,c}.service, all defining the same alias
"foo-alias". "foo-alias" is currently redirecting to a.service.

What should "systemct enable foo-alias" do if neither of them was
enabled previously ?  randomly pick up one service (probably the first
found) ?

What should be done if "foo-alias" is already pointing to a.service
and b.service is now enabled ? fail, ignore ?

As a consequence of the previous question, the user can decide to
start b.service explicitly. From that point using the alias should be
forbidden since the alias points to the first enabled service but not
the active one.

Even worse when the services defining the same alias can work in //,
for example SUSE uses "network" alias name (which is admittedly not
the best name) as a common name for network manager services (such as
NM, systemd-networkd, ...). One can decide to use one specific network
manager for some interfaces and another for the rest of the
interfaces. In this specific case the use of an alias doesn't seem to
make any sense.

**Comment by keszybz** [comment]
> Let's have {a,b,c}.service, all defining the same alias
> "foo-alias". "foo-alias" is currently redirecting to a.service.
> 
> What should "systemct enable foo-alias" do if neither of them was
> enabled previously ? randomly pick up one service (probably the first
> found) ?

At any given time, foo-alias points to some specific unit, and this would be alias
that we use. I.e. `systemctl enable` would operate on the same symlink that
runtime commands like `systemctl start/stop/status` operate on. Then there's
no ambiguity, and I think it would match user expectations.

> What should be done if "foo-alias" is already pointing to a.service
> and b.service is now enabled ? fail, ignore ?

That is not possible. If foo-alias points to a.service, then b.service is not
(fully) enabled. Even if some other part of enablement of b.service is present,
e.g. a symlink in multi-user.target.wants/, that's germane to the issue of the
alias.
 
> As a consequence of the previous question, the user can decide to
> start b.service explicitly. From that point using the alias should be
> forbidden since the alias points to the first enabled service but not
> the active one.

No.

> Even worse when the services defining the same alias can work in //,
> for example SUSE uses "network" alias name (which is admittedly not
> the best name) as a common name for network manager services (such as
> NM, systemd-networkd, ...). One can decide to use one specific network
> manager for some interfaces and another for the rest of the
> interfaces. In this specific case the use of an alias doesn't seem to
> make any sense.

No. There's never any ambiguity where an alias points to. Those other units
may be active, but the alias is where the symlink points.

**Comment by fbuihuu** [comment]
> > What should be done if "foo-alias" is already pointing to a.service
> > and b.service is now enabled ? fail, ignore ?
> 
> That is not possible. If foo-alias points to a.service, then b.service is not
> (fully) enabled. Even if some other part of enablement of b.service is present,
> e.g. a symlink in multi-user.target.wants/, that's germane to the issue of the
> alias.

Sorry but I don't understand that.

Let's assume that only a.service has been enabled and therefore foo-alias points to a.service.

What should return "systemctl enable b.service" ?

If the main enablement symlinks have been installed (basically symlinks in xxx.wants/) and therefore on next reboot b.service is just running fine, why should systemctl fail like it does currently (it currently returns 1) if the alias was already taken by a.service but that's something we accept ?

When systemctl returned an error, my assumption would be that nothing was created and systemctl left a clean state as it was before it was invoked.

**Comment by fbuihuu** [comment]
That said I think commit "shared/install: fix error codes returned by install_context_apply() " in this patchset should be apply anyway as it fixes a bug.

**Comment by keszybz** [comment]
So... we're talking about calling enable on symlinks. I was trying to say that it doesn't matter that `foo-alias` *could* be an alias to `b.service`, if it currently *is* an alias to `a.service`. That means that calling `enable a.service` and `enable foo-alias.service` should behave exactly the same, if we allow operating on aliases in this manner.

Right now `enable b.service` will fail saying that the symlink cannot be created. I don't think this should change when if operating on aliases is allowed.

**Comment by keszybz** [comment]
>  It seems better if "enable b.service" was returning succes and potentially warn about the impossibility to create the alias.

Current behaviour is to fail. I don't see a good reason to change this. In particular, often the alias is more important than the service name itself, in the case where there are multiple services which implement the same thing. For example, `gdm.service` might have `Alias=display-manager.service`, and the user might be always referring to the alias to pick one of several possible display managers.

**Comment by fbuihuu** [comment]
> Current behaviour is to fail. I don't see a good reason to change this.

Because if enabling b.service does fail (due to the alias name already taken by a.service), I wouldn't expect that b.service was still enabled and b.service is started after rebooting the system.

If it's expected that the alias name can be busy then enabling b.service shouldn't return a failure status, a warning or even a notification message with a success status sounds better.

>  In particular, often the alias is more important than the service name itself, in the case where there are multiple services which implement the same thing. For example, `gdm.service` might have `Alias=display-manager.service`, and the user might be always referring to the alias to pick one of several possible display managers.

I'm still not sure that allowing an alias name during enablement is  a good idea. It's currently not working (we would need to parse [Install] section of all units otherwise) [1] and even if we make it work, it would randomly pick up one service if multiple services using the same alias were installed.

But at least we should fix the documentation either like this patchset does or document the current shortcoming that might be fixed in the future.

**Comment by keszybz** [comment]
OK, let's merge this then. I still think we should allow enabling units by alias (in some cases), but we can discuss that separately.

**Comment by fbuihuu** [comment]
> OK, let's merge this then. I still think we should allow enabling units by alias (in some cases), but we can discuss that separately.

Should I open an RFE ?

**Comment by fbuihuu** [comment]
@keszybz also I just realized that you dropped this part of systemd.unit(5):

> with the limitation that aliases specified through Alias= are only effective when the unit is enabled.

I think describing this limitation until it will be removed makes sense...

**Pull request merged**
