### PR TITLE
Drop dbus activation stub service

### PR DESCRIPTION
**Pull request by mbiebl**
This fixes the following problem:

> At the very end of the boot, just after the first user logs in
> (usually using sddm / X) I get the following messages in my logs:
> Nov 18 07:02:33 samd dbus-daemon[2879]: [session uid=1000 pid=2877] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
> Nov 18 07:02:33 samd dbus-daemon[2879]: [session uid=1000 pid=2877] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1

These messages are caused by the "stub" service files that systemd
installs. It installed them because early versions of systemd activation
required them to exist.

Since dbus 1.11.0, a dbus-daemon that is run with --systemd-activation
automatically assumes that o.fd.systemd1 is an activatable
service. As a result, with a new enough dbus version,
/usr/share/dbus-1/services/org.freedesktop.systemd1.service and
/usr/share/dbus-1/system-services/org.freedesktop.systemd1.service should
become unnecessary, and they can be removed.

dbus 1.11.0 was released 2015-12-02.

Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=914015

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Interesting, the CentOS 7 job now fails because of a coredump generated by `test-sd-device`. See https://ci.centos.org/job/systemd-pr-build/7888/artifact//systemd-centos-ci/artifacts_tWhyz8/testsuite-logs-upstream.c9S/coredumpctl_collect_FAIL.log

It doesn't seem relevant to this PR though.

**Comment by mrc0mmand** [comment]
Gave it a second try and it indeed was a flake - unsetting the CI label.

**Comment by mbiebl** [comment]
cc @dvdhrm would this affect dbus-broker?

**Comment by mbiebl** [comment]
If there is concern, that dbus 1.11.0 from 2015 is not "recent enough", I can add a meson check to install the files conditionally and we completely drop them at a later point.
Let me know what you prefer.

**Pull request merged**
