### PR TITLE
units: disable systemd-time-sync-wait inside containers

### LINKED ISSUE #8535: `systemd-time-wait-sync.service` seems to be failing to start inside user namespace containers
I haven't read https://github.com/systemd/systemd/pull/8494 where `systemd-time-wait-sync.service` was introduced yet, so I'm not sure whether it is a bug or not:
```sh
bash-4.4# systemd-detect-virt
systemd-nspawn

bash-4.4# systemd-detect-virt --private-users
bash-4.4# echo $?
0

bash-4.4# systemctl --failed --no-pager
  UNIT                           LOAD   ACTIVE SUB    DESCRIPTION
● systemd-time-wait-sync.service loaded failed failed Wait Until Kernel Time Synchronized

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.

bash-4.4# journalctl -b | grep -i time-wait-sync
Mar 20 13:34:27 systemd-testsuite systemd[23]: systemd-time-wait-sync.service: Executing: /usr/lib/systemd/systemd-time-wait-sync
Mar 20 13:34:27 systemd-testsuite systemd-time-wait-sync[23]: Failed to read adjtimex state: Operation not permitted
```

### PR DESCRIPTION
**Pull request by pabigot**
Fixes #8535

### CODE REVIEW

**Comment by pabigot** [comment]
I think this is trivial, so it's submitted, but in honesty I'm still testing it.

**Comment by pabigot** [comment]
This passes the testing I know how to do (container boots, no failures, systemd-time-wait-sync inactive from start condition failed).

**Comment by poettering** [comment]
lgtm

**Comment by evverx** [comment]
I wouldn't say I'm familiar with what is happening here because I'm still reading https://github.com/systemd/systemd/pull/8494 (and the pace of my reading appears to be too slow to keep up with you all :-)). Would it make sense to add a comment about why `CAP_SYS_TIME` is used? I don't think that https://github.com/systemd/systemd/issues/8535#issuecomment-375119255 is the most obvious thing I've ever seen. Also, the service seems to have to be in sync with `systemd-timesyncd.service`, which should probably be mentioned somewhere so that it would be easier to made changes in the future.

**Comment by pabigot** [comment]
I don't think time-sync-wait has to be in sync with timesyncd; either can be enabled independently and do what they're documented to do.  The only intended relation is that time-sync-wait happens to be able to detect an event that's caused by timesyncd, but it detects that event from other (non-systemd) services as well (e.g. connman).

Re `CAP_SYS_TIME`: I'm not one to complain about adding documentation, but I'm also not qualified to provide it in this case.  I'm just 24 hours into my period of understanding how `Wants=` works....

**Comment by evverx** [comment]
Indeed, it seems to have to be in sync with whatever is used to advance the system time, so people who will use anything different from `systemd-timesynd.service` in "system" containers might have to fix the unit file manually.

**Comment by evverx** [comment]
The CI failure has nothing to do with this PR. I opened https://github.com/systemd/systemd/issues/8543.

**Comment by pabigot** [comment]
@evverx what do you mean by "in sync"?  Or, what concerns you about the `systemd-time-wait-sync.service` unit file that suggests it would need to be modified for use with something other than timesyncd?

time-sync-wait will "work" only with something that uses the NTP standard protocol for adjusting the system realtime clock (i.e. adjtimex(2)), but that's noted in the man page.

**Comment by evverx** [comment]
I'm sorry for being vague. I'll get back as soon as I've read https://github.com/moby/moby/issues/33126. It seems to me that `ConditionVirtualization=!container` might be too strict.

**Comment by evverx** [comment]
Having read https://github.com/moby/moby/issues/33126, I can imagine scenarios where containers are able to call `adjtimex` with `modes=0` without `CAP_SYS_TIME` (https://github.com/moby/moby/pull/33403) relying on whatever is used on the host to advance the system time. `ConditionCapability=CAP_SYS_TIME` and `ConditionVirtualization=!container` make it impossible to use `systemd-time-wait-sync.service` in such scenarios, which doesn't look correct to me.

**Comment by evverx** [comment]
I think that it would be better to ignore `EPERM` in `src/time-wait-sync/time-wait-sync.c` and print something like "assuming containerized execution, ignoring" as we usually do.

**Comment by evverx** [comment]
If https://github.com/moby/moby/pull/33403 has been released, any docker container could be used to test this. A more `systemd`-way would probably be to run `systemd-nspawn` with `--system-call-filter=adjtimex`. I actually think `adjtimex` should be whitelisted in `systemd-nspawn` too, but that's another matter.

There are people who put everything in containers, so it is possible that containers are being started before or in parallel with `systemd-timesyncd` or whatever is used on the host to call `adjtimex(2)`. In this case, the assumptioion that the time in containers has been synced is incorrect. That's why I think that `ConditionVirtualization=!container` is too strict.

**Comment by evverx** [comment]
> adjtimex(2) is not an incidental system call here that can be ignored: it defines the behavior of the service.

That's true. Maybe it would be better to add something like `detect_container > 0` so that the service wouldn't bail out in a container only.

**Comment by evverx** [comment]
I may be missing the idea behind `systemd-time-sync-wait` entirely. If it is supposed to work only outside of containers, so it should probably be documented, so nobody will ever assume that it can be relied on inside containers.

**Comment by evverx** [comment]
Anyway, this PR fixes #8535 in the sense that `systemd-time-wait-sync.service` has stopped failing. Containers could be discussed.

**Comment by pabigot** [comment]
I don't use containers and in fact it never crossed my mind to consider them: I need `time-sync.target` to work on Yocto-based IoT gateways.  AFAICT if a container allows use of adjtime(2) with a zero mode setting just like a "real" system, and whatever implements that system call behaves as a real kernel would including indicating sync status in the return value and supporting `timerfd_create` and the behavior of cancelling timers on realtime clock set, it should work just fine.  If the container environment doesn't do that, then it falls under "won't work" category that is already documented in the NOTES section of the man page.

In such a case, as in any other case where the environment does not support indication that the realtime clock is synchronized the service should be disabled.  Hacking the unit file to do this automatically based on `ConditionVirtualization` is probably not the right solution, though it is the expedient one.

Adding the following might be worthwhile:

> See the source code for details on expected behavior of the execution environment.  Be aware that container environments may not satisfy the expectations of this service, and it should not be enabled in such situations.

**Comment by evverx** [comment]
On second thought, it seems that `ConditionVirtualization=!container` in the unit file makes it clear that containers are somewhat different and it might be tricky to make everything work, so I think additional documentation is unnecessary. People who tend to read the code will read it anyway without any documentation :-)

Thank you!

**Comment by poettering** [comment]
Hmm, is it really a realistic usecase to run some NTP server in one docker container, and this new tool in a second one, and expect it to work? I am not sure this is likely to ever happen...

**Comment by evverx** [comment]
I doubt anyone would run an `NTP` server and `systemd-time-wait-sync.service` in two different containers. The use case I was trying to describe is a normal `NTP` server outside of any container and `systemd-time-wait-sync.service` running in a container before or in parallel with that normal `NTP` server.

**Comment by evverx** [comment]
What I don't understand is why the CI didn't run `systemd-time-wait-sync.service` when https://github.com/systemd/systemd/pull/8494 was opened and apparently hasn't run it since then. @martinpitt, @mbiebl could it be that some magic like https://salsa.debian.org/systemd-team/systemd/blob/master/debian/rules#L214 happens preventing the service from starting?

**Pull request merged**
