### PR TITLE
sd-ipv4acd: split out as separate library from sd-ipv4ll

### PR DESCRIPTION
**Pull request by teg**
This will allow us to reuse this for addresses obtained over DHCP and/or set statically.

Replaces #1011.

### CODE REVIEW

**Comment by teg** [comment]
@utezduyar reworked this a bit, please look at this instead.

**Comment by zonque** [comment]
What's wrong with the test? Does that succeed locally on your machine?

**Comment by teg** [comment]
Yikes, that's meant to be a manual test. I'll push a fix.

**Comment by teg** [comment]
Force-pushed the fix (moving the test to manual_tests in the makefile).

**Comment by utezduyar** [comment]
Regarding "rework callbacks" change, we on purpose triggered STOP events so the intelligent logic to start/stop LL would be entirely in the callback instead of the API caller handling it. This was the case with dhcp4. If this is not valid anymore, I am OK with that commit.
This change needs to be announced so that API users of ipv4ll won't get surprised when they don't get stop events.

**Comment by utezduyar** [comment]
Note that one of the possibilities of an address conflict resolution is defending the address but defending the address need to be done according to rfc3927. So, things like DEFEND_INTERVAL etc are specific to IPv4 LL. 

Are these specs same that we can use sd-ipv4acd API to defend DHCP addresses?

**Comment by utezduyar** [comment]
@teg @krillenilsson from Axis has been helping me reviewing your changes. He has already found a corner case which he will post shortly. He is a fireball, if you need help with anything related to networkd (implementing bus API etc) he is available and I am sure he wouldn't mind helping out.

**Comment by krillenilsson** [comment]
Hi, I tested the conflict case and I found something that seems strange.
In ipv4ll_on_acd when getting a IPV4ACD_EVENT_CONFLICT, it will call ipv4ll_pick_address to set ll->address. Then it will go on to start ll (sd_ipv4ll_start) but then check ll->address == 0 will cause it to exit immediately. No retry seems to be done either, causing it never to try a new address again. Or am I missing something?

**Comment by teg** [comment]
I think allowing _start() on already running clients, and hence supporting turning that into a STOP event if it fails was a mistake. Moreover, we were not relying on this in networkd (i.e., we were never starting an already running client without having stopped it first). I should do the same for the other clients though. That said, I'll have another look at turning sd_ipv4ll_stop() into a STOP event, that probably does make sense indeed.

**Comment by teg** [comment]
As to address defense, RFC3927 and RFC5227 are the same here (the latter being a subset of the former by design). For DHCP this is not really specified in detail, but the idea would be to use the same constants, but react differently on real conflicts (rather than picking a new address ourselves we would request a new one from the server (but in case of a runtime rather than configure time conflict the issue is more subtle for DHCP so something to discuss)).

**Comment by teg** [comment]
Thanks for looking at this @krillenilsson. That is indeed totally bogus, I'll fix!

**Comment by teg** [comment]
Please see the new PR. Added another test program, and addressed your comments (in particular fixed the bug found by @krillenilsson  and restorted the sd_ipv4ll_stop() behavior as pointed out by @utezduyar).

**Pull request closed without merging**
