### PR TITLE
login: mark nomodeset fb devices as master-of-seat

### PR DESCRIPTION
**Pull request by keszybz**
Based on a patch from Adam Jackson.
For https://bugzilla.redhat.com/show_bug.cgi?id=1683197.

C.f. #11833.

### CODE REVIEW

**Comment by poettering** [comment]
#11978 is very similar. Closed that one though, since this one is nicer as it uses IMPORT{cmdline}

**Comment by poettering** [comment]
My question from the other bug remains though:

KMS and DRM are two different things, no? Is KMS strictly a precondition for DRM?

**Comment by keszybz** [comment]
Oh, @nwnk, I didn't know you were going to open a PR. I only took your patch from bugzilla and updated it to use import. Could you test if that still works?

**Comment by nwnk** [comment]
@keszybz just tested your patch, works fine. Didn't know about IMPORT, thanks for pointing it out.

@poettering KMS is a DRM feature. All KMS drivers are DRM drivers, not all DRM drivers support kernel modesetting.

There do still exist KMS-less DRM drivers, which do not examine `nomodeset` as a parameter and will still initialize. IIRC all such drivers are mutually exclusive with any fbdev driver that might also try to claim the device, so this patch would still be valid, you would only ever have `/dev/dri/card0` or `/dev/fb0`. (As far as I know there is no reliable way to determine if a dri and fbdev device node correspond to the same device.)

For the KMS-ful DRM drivers, at this point, saying `nomodeset` prevents the DRM driver from binding at all, and there will be no `/dev/dri/card0` for the device.

**Comment by jlinton** [comment]
This looks to fix the immediate "nomodeset" option, but as I mentioned in the other defect https://bugzilla.redhat.com/show_bug.cgi?id=1679801 there are a lot of other ways for this to happen too.  

The rPI case was lack of a functional driver leaving the efifb device active, no kernel command line options necessary. I'm actually not sure of a good way to set this and still avoid the race of setting in on a fbdev that is about to be disabled/replaced by a more advanced driver.

**Comment by keszybz** [comment]
I force-pushed the patch to reset authorship back to @nwnk.

**Comment by keszybz** [comment]
@jlinton the case of https://bugzilla.redhat.com/show_bug.cgi?id=1679801 is hard to solve nicely. If you have any ideas how to solve it, that'd be great. One ugly option would be to have a list of options that have the same effect as nomodeset, but this list is open-ended. Another option would be to simply document this, and ask people to add "nomodeset" to the kernel command line if they blacklist modules, simply to force this rule we added here to take effect. Actually, a combination of both might be the best approach...

**Comment by nwnk** [comment]
Another possibility, if udev rules are expressive enough for this, is to apply `master-of-seat` to drm devices first, and only to fbdev devices if there are no drm devices. This would also let us drop the hyperv hack...

**Comment by poettering** [comment]
> Another possibility, if udev rules are expressive enough for this, is to apply `master-of-seat` to drm devices first, and only to fbdev devices if there are no drm devices. This would also let us drop the hyperv hack...

the only reason we stopped marking fb devices with master-of-seat was that gdm/gnome and friends got confused by this: the availability of a master-of-seat marked device synthesizes a graphical seat. Since there's no strict ordering between appearance of fb and drm devices for the same hw this mean that gdm might start initialization already when fb became available thus thinking drm was not available even though that device would shortly later show up too.

now, we were informed back than that all relevant hw now has drm and thus the fb devices wouldn't matter, and we could just stop marking them altogether. That appears not to be the one true single truth however. 

The thing is we never know whether drm might show up for an fb device we see popping up. If we had a way to determine that we could of course mark all fb devices as "master-of-seat" for which we know drm is never going to show up, but I don't see how we could do that without races

**Comment by halfline** [comment]
well we know efifb (and uvesafb i guess?) don't have drm drivers.  so we could tag efifb devices as `master-of-seat` only if no pci devices seen at cold plug have drivers available (in the `# modprobe -n pci:v0000...` sense).

**Comment by jlinton** [comment]
Probably needs to be more complex than that. The rPI's efifb device is deactivated by the device tree described vc4 driver (which can fail to attach for various reasons).

I was thinking last week that what is really needed is something tied to udevadm settle (although i'm not sure by itself that will work) which tags any remaining fbX devices as master of seat. The basic goal being to assure that all drivers have had a chance to load and attach, before udev runs through and tags any remaining devices. That said, AFAIK the original reason for master-of-seat was to fix the load race, and just delaying fbX creation until the whole system has settled would have had a similar effect as delaying the master-of-seat tagging.

**Pull request merged**
