### PR TITLE
man: document that noauto doesn't affect automount units configured t…

### PR DESCRIPTION
**Pull request by poettering**
…hrough /etc/fstab

Fixes: #6937

### CODE REVIEW

**Comment by yuwata** [comment]
lgtm.

**Comment by keszybz** [comment]
Hmm, is this the right solution really? Having an automount unit and pulling the mount unit automatically makes very little sense. I'd really expect (like the OP in #6937), that 'noauto,x-systemd.automount' means that the whole thing (mount *and* autoumount units) are not activated automatically, i.e. are not added to local-fs.target or remote-fs.target automatically. That is what makes sense from user POV. Current behaviour and what is documented in this PR is consistent, but not particularly useful.

**Comment by poettering** [comment]
Well, the original thinking was that automount fstab entries are used for parallelization only, not so much for lazy-mounting stuff. And if all you care is parallelization, then the focus for auto/noauto is really just about whether to make trigger it right-away or lazily...

That said, let's turn this around: typically "noauto" in fstab is useful to have a mount point defined that you can just do "mount /foo" with, to mount it. But automount mount points are not like that, so why would you mix the two options anyway?

But then again, I figure documenting the status quo is the right way anyway. I'd be totally onboard with adding another option, that also drops the deps on automount lines, but that should be done in a compatible way, separately of this doc PR. (maybe beef up x-systemd.automount to take parameters? x-systemd.automount=noauto or so?)

**Comment by keszybz** [comment]
Mounts *are* parallelized already, so I don't think using automount for that is useful. Maybe I'm missing something, but for me `x-systemd.automount` has always been about mounting lazily.

> That said, let's turn this around: typically "noauto" in fstab is useful to have a mount point defined that you can just do "mount /foo" with, to mount it.

Agreed.

> But automount mount points are not like that, so why would you mix the two options anyway?

To have an automount point that is very much like a plain mount point. I.e. the fact that it is an automount point is an implementation detail.

Let's ask a different question: what is the effect of `noauto` in `x-systemd.automount,noauto`? It turns out that there is no effect, the dependencies that are generated for `x-systemd.automount,noauto` are exactly the same as for `x-systemd.automount` (*). My problem with status quo is that adding the automount option defeats the noauto option — suddenly this mountpoint is pulled into the initial transaction.

I don't think we need to add a new option, because the existing combination had no effect, so it should not be used too widely. Instead of "cementing" the meaning that is not useful, let's make this combination useful instead.

--

(*) I added
```
# /etc/fstab
/dev/foo /mnt/foo ext4 x-systemd.automount,noauto 0 0
/dev/foo2 /mnt/foo2 ext4 x-systemd.automount 0 0
```
and then did
```sh
systemctl show mnt-foo.mount mnt-foo.automount > /tmp/foo
systemctl show mnt-foo2.mount mnt-foo2.automount |sed s/foo2/foo/g > /tmp/foo2
diff -u /tmp/foo{,2}
```

**Comment by michaelolbrich** [comment]
@keszybz there is a big difference:
With noauto the mount unit is not active at the beginning so the dependencies do not matter. So local-fs.target can be reached before the device that contains the filesystem is available.
This can speed things up considerably: Any application that may need the filesystem can start much earlier and may block later once it actually accesses the filesystem. All other applications don't need to wait for a filesystem they don't need.

**Comment by keszybz** [comment]
Are you sure? In commit https://github.com/systemd/systemd/pull/7350#issuecomment-344884641 I show that there is no difference between a line with x-systemd.automount,noauto and x-systemd.automount. If you see a difference, please show that.

**Comment by michaelolbrich** [comment]
The difference is in Requires= / After= in local-fs.target. The automount unit is always there, but the mount unit is only there if noauto is not set.

**Comment by keszybz** [comment]
Did you test your hypothesis?

I see

<pre>~$ systemctl show --no-pager -p Requires,After local-fs.target|grep mnt-foo
Requires=<font color="#CC0000"><b>mnt-foo</b></font>2.automount boot-efi.mount boot.mount -.mount <font color="#CC0000"><b>mnt-foo</b></font>.automount home.mount
After=home.mount boot.mount <font color="#CC0000"><b>mnt-foo</b></font>.automount <font color="#CC0000"><b>mnt-foo</b></font>2.automount run-media-system-dm\x2d4.mount tmp.mount systemd-remount-fs.service systemd-fsck-root.service run-user-42.mount -.mount run-user-6.mount local-fs-pre.target run-user-1000.mount ostree-remount.service run-user-1000-gvfs.mount boot-efi.mount fedora-readonly.service
</pre>

i.e.
1) the .mount unit is never there
2) noauto **when combined with x-systemd.automount** has no effect

**Comment by michaelolbrich** [comment]
You are correct. It used to be that way when I first worked on the expire support for automount units, that's why I remember that way, but it was changed soon afterwards (in v230).
And I only checked the `noauto` case earlier... sorry.

So it's just a matter of compatibility. Applying `noauto` to automount units will break a lot of older fstabs.

**Pull request merged**
