### PR TITLE
tests: pass --werror to meson on Semaphore

### PR DESCRIPTION
**Pull request by evverx**

### CODE REVIEW

**Comment by evverx** [comment]
I took a look at the debian package and apparently whatever is passed via `CONFFLAGS` can theoretically be overridden with `CONFFLAGS_DISTRO` and `CONFFLAGS_deb`. @ddstreet @mbiebl I'm wondering if there is a way to somehow enforce `--werror` (and everything else we pass via `CONFFLAGS` for that matter) globally.

**Comment by evverx** [comment]
Anyway, it seems to be working. I'll go ahead and merge the PR. I suppose we can figure out how to make it more reliable later.

**Comment by ddstreet** [comment]
I think that sed should work, CONFFLAGS isn't ever replaced by CONFFLAGS_DISTRO or _deb/_udeb, those are passed in addition to CONFFLAGS.

I also have a patch to add --werror for all Ubuntu CI tests, but there are a couple warnings that need fixing first, since they cause the s390 build to fail when --werror is enabled:
https://launchpad.net/~ddstreet/+archive/ubuntu/systemd-upstream/+build/17316580
https://launchpad.net/~ddstreet/+archive/ubuntu/systemd-upstream/+build/17316934
I'll try to open PR for those soon

**Comment by evverx** [comment]
> those are passed in addition to CONFFLAGS

In theory, as far as I understand, if for example, `-Dslow-tests=true` is included in `CONFFLAGS` and at the same time `CONFFLAGS_DISTRO` contains `-Dslow-tests=false`, "false" takes precedence and overrides "true" passed via CONFFLAGS.

**Comment by ddstreet** [comment]
Ah ok, I see what you mean, yeah.

I opened this MR to add a CONFFLAGS_UPSTREAM param which you could use:
https://salsa.debian.org/systemd-team/systemd/merge_requests/43

**Pull request merged**
