### PR TITLE
meson: simplify handling of the version tag

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Review by medhefgo — APPROVED** [review]
The split was done in #18192 for "performance" reasons. Personally, I don't give a damn, but like it simple.

**Comment by medhefgo** [comment]
There is also the `fallback` arg on `vsc_tag`…

**Comment by keszybz** [comment]
> The split was done in #18192 for "performance" reasons. Personally, I don't give a damn, but like it simple.

Indeed. I forgot about this. I redid the measurements, and I think it's justified to drop this. I added a longer justification in the commit message. 

> There is also the `fallback` arg on `vsc_tag`…

I don't think it's useful. The way that our script is written, we can figure out if the fallback is needed directly in meson, and if we call the scriptlet, we expect it to succeed always.

I force-pushed to update the commit message. There is no code change.

**Comment by bluca** [comment]
Just to be sure, currently by setting `-Dversion-tag=fixed` I can stop `meson configure` from automatically re-running, which is incredibly slow, every time the commit id changes - rebasing, switching branches, committing a change, etc. Does this still work with these changes?

**Comment by medhefgo** [comment]
`vcs_tag` is run by ninja , so it shouldn't affect meson setut at all.

**Review by bluca — APPROVED** [review]

**Comment by YHNdnzj** [comment]
> Now that we use vcs_tag, meson should take care of building it early enough.

https://mesonbuild.com/Reference-manual_functions.html#vcs_tag says the following though:

> This method returns a custom_tgt should be used to signal dependencies if other targets use the file outputted by this.
>
> For example, if you generate a header with this and want to use that in a build target, you must add the return value to the sources of that build target. Without that, Meson will not know the order in which to build the targets.

**Comment by keszybz** [comment]
→ https://github.com/systemd/systemd/pull/28995

**Pull request merged**
