### PR TITLE
hwdb: Add Lenovo Thinkpad P14s Gen1/2 rule

### LINKED ISSUE #20394: Missing hwdb entry for Thinkpad P14s/T14 Gen 2 touchpad
**systemd version the issue has been seen with**
 > 249

**Used distribution**
 > Arch Linux

The hwdb currently lists these settings for recent Thinkpad T-Models:
https://github.com/systemd/systemd/blob/e908236e054bd246f0bc764a0b1412da8172d741/hwdb.d/60-evdev.hwdb#L570-L576

I have the recent P14s Gen 2 Model which should be identical to the T14 Gen 2. It still seems to use the same touchpad as previous models. Without a hwdb entry the touchpad sensitivity is very low. I ran `touchpad-edge-detector` and got the same resolution as for the T490/T14 Gen 1. With my model added to the hwdb the touchpad works as expected with reasonable sensitivity. The P14s Gen 2 is identified by the following filter:

`evdev:name:SynPS/2 Synaptics TouchPad:dmi:*:svnLENOVO:*pvrThinkPadP14sGen2a:*`

Probably the P14s Gen 1 and T14 Gen 2 should also be added, but I cannot verify how these system identify.

### PR DESCRIPTION
**Pull request by svonohr**
Add rules for Thinkpad P14s which shares the same hardware with the T14.
Fixes #20394

### CODE REVIEW

**Comment by yuwata** [comment]
LGTM.

**Comment by bdaase** [comment]
Hmmm, I measure slightly different values for a P14s Gen2 AMD...


```
evdev:name:SynPS/2 Synaptics TouchPad:dmi:*svnLENOVO:*pvrThinkPadP14sGen2a**
 EVDEV_ABS_00=::44
 EVDEV_ABS_01=::51
 EVDEV_ABS_35=::44
 EVDEV_ABS_36=::51
```

What should we do with this?

**Comment by svonohr** [comment]
How did  you find those values? I ran `touchpad-edge-detector` and got the following output:
```
$ touchpad-edge-detector 100x68 /dev/input/event15
Touchpad SynPS/2 Synaptics TouchPad on /dev/input/event15
Move one finger around the touchpad to detect the actual edges
Kernel says:    x [1266..5678], y [1162..4694]
Touchpad sends: x [1266..5678], y [1161..4694] |^C

Touchpad size as listed by the kernel: 100x67mm
User-specified touchpad size: 100x68mm
Calculated ranges: 4412/3533

Suggested udev rule:
# <Laptop model description goes here>
evdev:name:SynPS/2 Synaptics TouchPad:dmi:bvnLENOVO:bvrR1MET35W(1.05):bd04/23/2021:br1.5:efr1.5:svnLENOVO:pn21A1S00E00:pvrThinkPadP14sGen2a:skuLENOVO_MT_21A1_BU_Think_FM_ThinkPadP14sGen2a:rvnLENOVO:rn21A1S00E00:rvrNotDefined:cvnLENOVO:ct10:cvrNone:*
 EVDEV_ABS_00=1266:5678:44
 EVDEV_ABS_01=1161:4694:52
 EVDEV_ABS_35=1266:5678:44
 EVDEV_ABS_36=1161:4694:52
```

These values match what was reported in #15694 for the T490.

**Comment by bdaase** [comment]
I used `sudo libinput measure touchpad-size 100x69`, but they seem to map to the same thing.

However, I think the difference is in the specified touchpad size. I used, according to https://thinkstation-specs.com/wp-content/uploads/2020/04/P14s-_-Lenovo-ThinkStation.pdf (page 3) and matching my personal measurements, a size of 100mm x 69mm.

**Pull request merged**
