### PR TITLE
revert spawn_read for reading stdout or stderr of spawned process

### PR DESCRIPTION
**Pull request by gaoyi1988**
Even if the priority is set, there is a possibility that the on_spawn_sigchld is executed first.

I have verified that this fix https://github.com/systemd/systemd/issues/18190

### CODE REVIEW

**Comment by yuwata** [comment]
Hmm? Why this fixes the issue? If this fixes the issue, then there exists a bug in sd-event. We should fix the bug instead of 'revert'ing something to not use sd-event.

**Comment by gaoyi1988** [comment]
@yuwata 
The reason of the problem is on_spawn_sigchld executed before on_spawn_io.
The PR https://github.com/systemd/systemd/pull/13941 try to fix this by setting priorities. But I think this just can solve the situation that sd-event receive both WEXITED and IO events. But if it received WEXITED first, it may execute on_spawn_sigchld first.
Before revert to spawn_read, I try to find a solution to ensure the order of on_spawn_sigchld and on_spawn_io, but failed.

**Comment by poettering** [comment]
This "fix" looks a bit drastic.

if the io event source has a higher prio than the child event source, and the IO event source sees I/O and the child dies we give the guarantee that the IO event source is dispatched first. If that guarantee doesn't hold, then this is a bug in sd-event, and thus nothing to fix in udev, but in sd-event.

Let's close this here, this really isn't right.

if you think there's a bug in sd-event, and that it dispatches things in this case in the wrong order, then please file a bug against sd-event, and ideally provide a minimal reproducer.

that said, maybe the issue you are trying to fix is more like this: a child process down the process tree keeps running (for maybe just a bit) at a time where the child udev itself forked off already died? in this case, udev will process everything written to the streams until the immediate child, but might miss whatever the child further down might still generate?

if that really matters (which I am not sure of...) then the only fix is to wait for the immediate child to die + EOF on the pipe, but place a timeout on things, started once the child died. The timeout is necessary since a grandhcild might keep the fd open as long as it wants, and we shouldn't wait indefenitely for it, if it doesn't want to die.

either way, this specific PR is not the right way. let's close this here. if there's an issue with sd-event, or the issue you are seeing is the one i describe above, then please open a new issue/PR about this with a better fix.

**Comment by poettering** [comment]
(hmm, thinking more about this, maybe the extra timeout might not be necessary, since we already have a timeout on the whole thing anyway, so maybe it actually is OK to wait for both EOF and the child in any order, and finish only after having seen both)

**Pull request closed without merging**
