### PR TITLE
core: don't do pam_setcred() for DynamicUser=1 and system user services

### PR DESCRIPTION
**Pull request by poettering**
Fixes: #14567

### CODE REVIEW

**Comment by poettering** [comment]
Hmpf, so this is not actually going to fix #14567 because the user there is one created via tmpfiles, not DynamicUser=1...

I am not sure I like the effect of #11199 that only users that can be authenticated against work with PAMName= now. That's pretty much *against* the whole concept of User=, i.e. allowing to run stuff as user *without* a login phase of any kind.

I am tempted to revert #11199 entirely I must say.

**Comment by poettering** [comment]
Hmm, so we could fix this for the user@.service, by adding "pam_allow" to the authentication stack for it. But PAMName= is more generic than that, it can be use in any context people like, and breaking all other setups sounds like a bad idea.

**Comment by poettering** [comment]
Another option would be do add PAMSetCredentials= and default to off, including for user@.service. That way the few folks who actually need this can use it, but we wouldn't break everybody's system on upgrade.

This is otherwise quite hard to work around on package upgrade, because it would mean patching the service files of any service that might use PAMName= and include pam_allow in it.

**Comment by poettering** [comment]
I updated my patch now. I don't like it much, because it makes something configurable that's almost impossible grok for even well versed technical people, and we shouldn't have such options, but I saw no other way.

PTAL. @dargad

**Comment by poettering** [comment]
Setting "priority" label, since this is needed to unfuck CI.

**Comment by dargad** [comment]
The heuristic looks reasonable as well as the fact that under normal conditions the new parameter does not have to be explicitly set.

Thank you for addressing this.

**Comment by keszybz** [comment]
It should be OK to simply ignore the return value of PAM_CRED_UNAVAIL (with a debug log). The man page says
> The pam_setcred function is used to establish, maintain and delete the credentials of a user. It should be called to set the credentials **after a user has been authenticated**

So this is not about trust, but about some extras. We could just continue on that error. That is reasonable, because up until the previous PR was merged, we would simply never call this function, so all those users were running without the extra credentials. Apparently this wasn't the end of the world.

**Comment by poettering** [comment]
> It should be OK to simply ignore the return value of PAM_CRED_UNAVAIL (with a debug log). The man page says

This is pretty much what this PR does now by default: it ignores the return value by default, but it's still noisy in the logs and looks like a bug (because PAM logs about it, not us), hence I added this logic that for system and dynamic users we bypass the thing entirely.

> > The pam_setcred function is used to establish, maintain and delete the credentials of a user. It should be called to set the credentials **after a user has been authenticated**
> 
> So this is not about trust, but about some extras. We could just continue on that error. That is reasonable, because up until the previous PR was merged, we would simply never call this function, so all those users were running without the extra credentials. Apparently this wasn't the end of the world.

My thinking too, that's why the new logic does that.

I was a bit scare though about the heuristic (dynamic + system users vs. the rest), and thus made this configurable. And then I figured, if I have to make this configurable anyway, then I might as well add a mode that makes the failure count, for the people who care. But it's opt-in with the current patch, by default we don't care about the return value.

**Comment by keszybz** [comment]
I think we can and even should call pam_setcred() even for dynamic users. True, right now it does nothing, but it's part of the pam protocol, and maybe it'll do something in the future. I don't see why the user would ever want to configure PAMSetCredentials=no. If they want that effect, they should just not configure any additional credentials. We generally don't have options to disable parts of the call tree (when those parts can be configured to be noops). So the choice comes down to whether ignore the error or not. And we *could* make the error fatal, but meh, so far nobody asked for it, and pam_setcred() does not seem to be something that is critical in any way. Basically, the user doesn't get some extra permissions. It is most likely better to still start the user.

Generally, I think we should be wary of adding yet another option, esp. one that describes *actions*, and not *state*, because that locks us into implementation details. And additionally, I don't think that the issue warrants the additional combined cost of yet another (very obscure, as you said) option.

**Comment by keszybz** [comment]
... what about reusing the condition that was used to set the default value for the config setting and using it as a flag whether to use log_debug or log_warning on failure?

**Comment by poettering** [comment]
the problem is not so much what we log, it is what PAM itself logs. i.e. can we live with noisy authentication logs?

**Comment by keszybz** [comment]
I think this should be fixed in pam. If it turns out that it's impossible, then we should reconsider.

**Comment by poettering** [comment]
@keszybz so i figure #14581 is what you are looking for? ptal!

**Comment by poettering** [comment]
Let's close this one, since #14581 has been merged.

**Pull request closed without merging**
