### PR TITLE
network: networkd does not disable IPv6 .

### PR DESCRIPTION
**Pull request by ssahani**
Since ```link_enable_ipv6``` called in set_mtu when mtu is not set
networkd does not disable IPv6  by writing to sysctl.

### CODE REVIEW

**Comment by wak-google** [comment]
LGTM

**Comment by yuwata** [comment]
Hmm, I may not like this. I think we should not write to sysctl rather than when it is really necessary.
Moreover, we read and cache the value. So is it really safe??
More and moreover, the value written `link_enable_ipv6()` seems not correct for me. What happens when `DHCP=ipv6` with `MTUBytes=`?

I'd like to drop `link_enable_ipv6()` in `link_set_mtu()` rather than move to somewhere. At least, it seems necessary to update that.

**Comment by ssahani** [comment]
> Hmm, I may not like this. I think we should not write to sysctl rather than when it is really necessary.

How do we disable IPv6 then ? The logic just moved from MTU set to the first call in link_configure
was a bug only working for while setting MTU.

> Moreover, we read and cache the value. So is it really safe??

Isn't it before doing any read the write is happening ?


> More and moreover, the value written link_enable_ipv6() seems not correct for me. What happens when DHCP=ipv6 with MTUBytes=?

If IPv6LL is disabled DHCP6 won't work   . What MTU has to do here ? 

>I'd like to drop link_enable_ipv6() in link_set_mtu() rather than move to somewhere. At least, it seems necessary to update that.

No depending on the user configuration we automatically update the sysctl value so that user does not have to configure manually via external means.

**Comment by yuwata** [comment]
> > More and moreover, the value written link_enable_ipv6() seems not correct for me. What happens when DHCP=ipv6 with MTUBytes=?
> 
> If IPv6LL is disabled DHCP6 won't work . What MTU has to do here ?

Right! Thanks. Please forget that point.

OK. I will test on this weekend.

**Comment by ssahani** [comment]
@yuwata ping

**Comment by yuwata** [comment]
Sorry for late reply.

> > Hmm, I may not like this. I think we should not write to sysctl rather than when it is really necessary.
> 
> How do we disable IPv6 then ? The logic just moved from MTU set to the first call in link_configure
> was a bug only working for while setting MTU.
>
> > I'd like to drop link_enable_ipv6() in link_set_mtu() rather than move to somewhere.
> 
> No depending on the user configuration we automatically update the sysctl value so that user does not have to configure manually via external means.

Then, maybe, we should introduce `EnableIPv6=` setting. We should not disable IPv6 even if .network file does not have any IPv6 related configs, as users may want to configure IPv6 addresses after `networkd` initialized the link.

I've created #13349.

**Comment by ssahani** [comment]
>as users may want to configure IPv6 addresses after networkd initialized the link.

Precisely when and how ?

**Comment by keszybz** [comment]
LGTM. https://github.com/systemd/systemd/pull/13349#issuecomment-522451187 explains why I think this appropriate.

**Comment by yuwata** [comment]
The current code causes a conflict between the cached value and the sysctl value. Even if this is the right way to handle the sysctl value, please update the patch.

**Comment by ssahani** [comment]
Then we should drop the cached one and always read from proc.

**Comment by ssahani** [comment]
updated thanks

**Comment by yuwata** [comment]
Not tested, but I believe this does not work. `link_ipv6_enabled()` calls `link_sysctl_ipv6_enabled()`. So, if `disable_ipv6` is `1`, then `link_ipv6_enabled()` returns `false`, and the sysctl value is not updated.

Also, please do not drop the caching... We call `link_sysctl_ipv6_enabled()` not few times.

**Comment by ssahani** [comment]
Ann ? link_ipv6_enabled() does not call  link_sysctl_ipv6_enabled().  And it does not disable any more just enables it.

>Also, please do not drop the caching... We call link_sysctl_ipv6_enabled() not few times.

Caching is not a right idea . It's not pid() that won't change . caching is broken for sysctl

**Comment by keszybz** [comment]
Caching in this case is both useful (because we query the value multiple times and we don't want to do it over and over) and necessary (because we need to base our logic on one value of the setting, either on or off). Even if somebody modifies the setting underneath us, we can't react properly to this.

I pushed a new PR that simply updates the cached value. Let's close this one.

**Comment by ssahani** [comment]
yes but what happens if the link down then the user modifies the sysctl value link comes up ? I have not tested this scenario though.

**Pull request closed without merging**
