### PR TITLE
tree-wide: avoid some loaded terms

### PR DESCRIPTION
**Pull request by poettering**
https://tools.ietf.org/html/draft-knodel-terminology-02
https://lwn.net/Articles/823224/

This gets rid of most but not occasions of these loaded terms:

1. scsi_id and friends are something that is supposed to be removed from
   our tree (see #7594)

2. The test suite defines an API used by the ubuntu CI. We can remove
   this too later, but this needs to be done in sync with the ubuntu CI.

3. In some cases the terms are part of APIs we call or where we expose
   concepts the kernel names the way it names them. (In particular all
   remaining uses of the word "slave" in our codebase are like this,
   it's used by the POSIX PTY layer, by the network subsystem, the mount
   API and the block device subsystem). Getting rid of the term in these
   contexts would mean doing some major fixes of the kernel ABI first.

Regarding the replacements: when whitelist/blacklist is used as noun we
replace with with allow list/deny list, and when used as verb with
allow-list/deny-list.

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

**Comment by evverx** [comment]
> when whitelist/blacklist is used as noun we
replace with with allow list/deny list, and when used as verb with
allow-list/deny-list

I wonder if it would be better to always use "allowlist/denylist" (without hyphens) so as not to confuse spell checkers like [codespell](https://fossies.org/linux/test/systemd-master.tar.gz/codespell.html) (which, by the way, knows what "blocklist" is and has no idea what "denylist" is (which makes me think that "blocklist" is much more common)).

**Comment by evverx** [comment]
> The test suite defines an API used by the ubuntu CI. We can remove this too later, but this needs to be done in sync with the ubuntu CI.

It was briefly discussed in https://github.com/systemd/systemd/pull/13568#issuecomment-539779165 and at the time it was decided that "blacklist" was apparently better. @ddstreet could you switch Ubuntu CI to "denylist"?

**Comment by poettering** [comment]
> I wonder if it would be better to always use "allowlist/denylist" (without hyphens) so as not to confuse spell checkers like [codespell](https://fossies.org/linux/test/systemd-master.tar.gz/codespell.html) (which, by the way, knows what "blocklist" is and has no idea what "denylist" is (which makes me think that "blocklist" is much more common)).

But it knows allowlist???

googling for it showed that the spelling "denylist" and "allowlist" are much less used among the top entires than "deny list" and "allow list"...

I am not convinced these words are established enough to be considered new words one can write together like that. We shouldn't be the ones who decide that.

**Comment by evverx** [comment]
> But it knows allowlist???

Yes, it does. It can even suggest using it instead of "whitelist".

> I am not convinced these words are established enough to be considered new words one can write together like that. We shouldn't be the ones who decide that.

I agree to some extent. But as far as I can tell the idea is to switch to those words eventually and normalize them along the way so to avoid a follow-up PR where hyphens are removed I'd go with "allowlist/denylist".

**Comment by evverx** [comment]
> googling for it showed that the spelling "denylist" and "allowlist" are much less used among the top entires than "deny list" and "allow list"...

I have to admit I didn't google it but judging by https://go.googlesource.com/go/+/8157a31deb75768b5998ed925c15bf20241a3f18, https://bugs.chromium.org/p/chromium/issues/detail?id=981129 and https://lore.kernel.org/lkml/20200609122549.26304-1-sjpark@amazon.com/ "blocklist" seems to be more common when it comes to software projects.

**Comment by keszybz** [comment]
I think both blocklist and denylist would be OK. Both are clear. So let's not bikeshed ;)

**Pull request merged**
