### PR TITLE
[RFC] core: support "nsdelegate" cgroup v2 mount option

### PR DESCRIPTION
**Pull request by htejun**
cgroup namespace wasn't useful for delegation because it allowed resource
control interface files (e.g. memory.high) to be written from inside the
namespace - this allowed the namespace parent's resource distribution to be
disturbed by its namespace-scoped children.

A new mount option, "nsdelegate", was added to cgroup v2 to address this issue.
The flag is meangingful only when mounting cgroup v2 in the init namespace and
makes a cgroup namespace a delegation boundary.  The kernel feature is pending
for v4.13.

This should have been the default behavior on cgroup namespaces and this commit
makes systemd try "nsdelegate" first when trying to mount cgroup v2 and fall
back if the option is not supported.

Note that this has danger of breaking usages which depend on modifying the
parent's resource settings from the namespace root, which isn't a valid thing
to do, but such usages may still exist.

[RFC] because the kernel change is still pending (it's highly likely to remain as-is tho)
and due to the above risk of breakages. What do you think?

### CODE REVIEW

**Comment by htejun** [comment]
For reference, [this](https://git.kernel.org/pub/scm/linux/kernel/git/tj/cgroup.git/commit/?h=for-4.13&id=5136f6365ce3eace5a926e10f16ed2a233db5ba9) is the commit implementing the nsdelegate option.

**Comment by keszybz** [comment]
The code looks trivially correct, and the change sounds like the right thing to do. So let's now just wait for for the patch to land upstream (hence POSTPONED). The new code will work with older kernels, so we can merge the patch as soon as the kernel gets support. (I think we shouldn't *release* systemd before the kernel with the patch is released, but it should be OK to provisionally include it in systemd git master after Linus merges that patch into his tree).

**Comment by htejun** [comment]
Pulled into Linus's tree.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/kernel/cgroup/cgroup.c?id=5136f6365ce3eace5a926e10f16ed2a233db5ba9

Thanks.

**Comment by poettering** [comment]
looks good, but let's wait for the v235 cycle for this

**Comment by utezduyar** [comment]
Is it reasonable to put a flag around the mount option for kernels that are older then when kernel got this feature?

**Pull request merged**
