### PR TITLE
namespace: Make private /dev noexec and readonly

### PR DESCRIPTION
**Pull request by topimiettinen**
Private /dev will not be managed by udev or others, so we can make it
noexec and readonly after we have made all device nodes. As /dev/shm
needs to be writable, we can't use bind_remount_recursive().

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, last time I checked "echo foo > /dev/null" will fail with EROFS if /dev is read-only.

Also, mmap() with PROT_EXEC on an fd generated via open("/dev/null") will fail if /dev is mounted with noexec. And that's something we really shouldn't break, for JITs and stuff...

So I think both changes won't work, or did you test this?

**Comment by topimiettinen** [comment]
Writing to devices works with read-only /dev. You are right about PROT_EXEC, though it does not seems to be very common based on this old discussion about changing devtmpfs defaults to noexec;
http://www.gossamer-threads.com/lists/linux/kernel/1633541

Also Chromium OS has had noexec /dev for some time:
https://bugs.chromium.org/p/chromium/issues/detail?id=214855

Here's a small test program:

```
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>

int main(void) {
        int fd;

        fd = open("/dev/zero", O_RDWR);
        write(fd, "foo", 3);
        mmap(NULL, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE, fd, 0);
        mmap(NULL, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);
        return 0;
}
```

Excerpt of strace of the compiled program run with noexec /dev:

```
open("/dev/zero", O_RDWR)               = 3
write(3, "foo", 3)                      = 3
mmap(NULL, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE, 3, 0) = -1 EPERM (Operation not permitted)
mmap(NULL, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc59d137000

```

Excerpt of strace with exec /dev:

```
open("/dev/zero", O_RDWR)               = 3
write(3, "foo", 3)                      = 3
mmap(NULL, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE, 3, 0) = 0x7f476b290000
mmap(NULL, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f476b28f000

```

Stracing a few programs, including Java and qemu, do not show /dev/zero method to be used but MAP_ANONYMOUS method. I haven't had any problems either, with system services or with userspace (browser etc), with noexec /dev throughout the system. I've had it for a long time.

But if you want to be very conservative, I can change the patch to only remount /dev read-only.

**Comment by poettering** [comment]
Given that we define the concept of PrivateDevices= I figure it's Ok to set both flags. However, could you add a quick note about the PROT_EXEC thing to the man page documentation for PrivateDevices=? I think people should should be made aware of that.

**Comment by keszybz** [comment]
Replaced by #3250.

**Pull request closed without merging**
