### PR TITLE
man: mention that DynamicUser= should not be mixed with ReadWriteDire…

### PR DESCRIPTION
**Pull request by poettering**
…ctory= or AF_UNIX dir fd passing

### CODE REVIEW

**Comment by yuwata** [comment]
Should we warn about such a configuration when the unit is loaded?

**Comment by poettering** [comment]
> Should we warn about such a configuration when the unit is loaded?

I don't think so. There are valid cases where this is not a problem. For example if you re-chown the stuff before you use it (think: `ExecStartPre=!` that does that). Hence, I wouldn't really consider this warning-worthy, though definitely documentation-worthy.

**Comment by yuwata** [comment]
> (think: `ExecStartPre=!` that does that). 

I see. Thanks.

**Comment by keszybz** [comment]
I think the docs addition is good enough.

**Pull request merged**
