### PR TITLE
util: Refactor common cunescape block in unquote_first_word

### PR DESCRIPTION
**Pull request by haraldh**
Get rid of code duplication here.

### CODE REVIEW

**Comment by zonque** [comment]
Is this pull request still necessary after our discussion in the ML? Will it be super-seeded by a new one?

**Comment by haraldh** [comment]
asking @filbranden

**Comment by filbranden** [comment]
I still have it on my tree.

We might as well just discuss it here...

Main questions is whether this is good enough or we could look into a more efficient approach, such as:
- Keep the "escape" in a separate bool, so that whenever we go to the "escape" case we still know whether our state is "no quotes" or "inside single quotes" or "inside double quotes".
- Turn the "escape" into a separate bit value so that we can do something like `state &= ~ESCAPE` to return to the unescaped value/single_quote/double_quote.

I can rework it to take one of the approaches above if you prefer, or we can just submit it as is and rework it in a follow up commit, that's also fine.

**Comment by filbranden** [comment]
This is now part of #44 so let's close this one.

**Pull request closed without merging**
