### PR TITLE
ci: Add/Drop labels on pull request activity and comment

### PR DESCRIPTION
**Pull request by daandemeyer**
When a pull request is opened/updated, add "please-review" and remove a few other labels.

When a comment is made with /please-review on a PR. Add the "please-review" label to the PR.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Tested in my fork: https://github.com/DaanDeMeyer/systemd/pull/1

Seems to work

**Comment by bluca** [comment]
> When a comment is made with /please-review on a PR. Add the "please-review" label to the PR.

Can you document this in one of the contributing docs?

**Review by yuwata — APPROVED** [review]
Not familiar with the GitHub action, but superficially LGTM.
Let's merge, and adjust the script or document later if necessary.

**Comment by yuwata** [comment]
Further possible improvements:
- also drop needs-rebase on force-push,
- do not add please-review when a PR already has one of the green label,
- do not add please-review for draft PRs,
- add please-review when a PR becomes ready.

**Pull request merged**
