### PR TITLE
escape: fix octescape()

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug introduced by https://github.com/systemd/systemd/commit/95052df3760523e1f3bb9705c918d85aae7fb431.

This also makes octescape() support NULL or zero length string.

Fixes [oss-fuzz#54059](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54059).

Fixes https://github.com/systemd/systemd/issues/25643.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx and @keszybz

**Comment by poettering** [comment]
ouch!

**Comment by keszybz** [comment]
Queued up for v252.3.

**Pull request merged**
