### PR TITLE
Added post-install script for mkosi

### PR DESCRIPTION
**Pull request by AsciiWolf**
This pull request fixes the _systemd-journal-catalog-update.service_ not working inside a booted mkosi generated image, as [noted](https://github.com/systemd/systemd/pull/4949#issuecomment-268688753) in my previous pull request.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Oops, don't merge this yet! It looks like it works correctly only when I boot the image for the first time. After next boot, it crashes again with "ConditionNeedsUpdate=/etc was not met", even if I try to run "touch /etc/" inside the booted image and manually restart the _systemd-journal-catalog-update.service_ afterwards. That's weird.

**Comment by AsciiWolf** [comment]
Does anyone have any idea how to fix this issue? @poettering?

**Comment by poettering** [comment]
Oh, I think there's a misunderstanding what the service does. All it does is invoke "journalctl --update-catalog" which generates a binary index in /var for the textual catalog files included in /usr/lib/systemd/catalog/. Normally RPM/DEB package postinst scripts call that tool after dropping in new catalog files, to update it. The only reason the service exists is to implement a scheme where /usr can be update atomically and isolated from specific /etc of /var instances, so that the latter are updated automatically on the next boot if a such a /usr tree is updated.

Usecase: you are building an embedded device that uses a writable root directory on ext4, plus a verity-protected, read-only squashfs /usr that is updated automatically from the internet. This way, user configuration and state is maintained locally, but the vendor OS resources can be updated atomically as they are monopolized in /usr. A system update then becomes: drop in a new /usr version on the host, reboot, and the old /var+/etc is now booted with the new OS version. Now, in this case a couple of caches in /etc and /var need to be refreshed based on the new data in /usr. That's stuff like ld.so.cache, but also the catalog index file. Now, systemd will run this cache updates automatically actually, if it notices that /usr is newer than /etc or /var. And the unit file systemd-journal-catalog-update.service rebuilds the catalog in this case.

If you build a fresh image, outside of this atomic /usr update mode, then the service should not run at all, as the RPM scriplets already rebuild the stuff anyway... That's why the condition doesn't hold, and that's really intended.

Hence, if the service doesn't run at boot, due to the condition, then that's a good thing, and everything works as intended.

Hence I am not sure what precisely you intend with the patch?

**Comment by AsciiWolf** [comment]
Ah, thanks for the clarification! I was just following [your comment](https://github.com/systemd/systemd/pull/4949#issuecomment-268755665) from my previous pull request.

**Comment by AsciiWolf** [comment]
@poettering So if I understand it correctly, this pull request is not needed?

**Comment by poettering** [comment]
yupp, not needed!

**Pull request closed without merging**
