### PR TITLE
sd-radv: fix memory leak

### PR DESCRIPTION
**Pull request by ssahani**
May fix https://github.com/systemd/systemd/issues/28985

### CODE REVIEW

**Comment by bluca** [comment]
please rebase to pick up fix for unit test failure

**Comment by keszybz** [comment]
LGTM.

**Comment by evverx** [comment]
Given that https://github.com/systemd/systemd/pull/28565 was merged with no tests I think it would be great to add a basic test exercising those codepaths.
```
[IPv6PREF64Prefix]
Prefix=64:ff9b::/96
LifetimeSec=30m
```
should be enough to trigger that memory leak on CentOS CI without this PR (and make sure that it's actually fixed here).

**Comment by ssahani** [comment]
> Given that #28565 was merged with no tests I think it would be great to add a basic test exercising those codepaths.
> 
> ```
> [IPv6PREF64Prefix]
> Prefix=64:ff9b::/96
> LifetimeSec=30m
> ```
> 

We will be able to send this via the radv but we are not consuming it in client side i.e. ndisc. How about add a PR like UsePREF64= and show this in networkctl and add a test ?

**Comment by evverx** [comment]
> We will be able to send this via the radv but we are not consuming it in client side i.e. ndisc

networkd is compiled with ASan on CentOS CI so it can catch memory leaks and stuff like that without anything else on the receiving side. To test that it works correctly something should receive those RAs though and it shouldn't necessarily be networkd.

> How about add a PR like UsePREF64= and show this in networkctl and add a test ?

Dunno. If it's just for testing purposes I'm not sure it should be added.

**Comment by ssahani** [comment]
> > We will be able to send this via the radv but we are not consuming it in client side i.e. ndisc
> 
> networkd is compiled with ASan on CentOS CI so it can catch memory leaks and stuff like that without anything else on the receiving side.
ACK

> To test that it works correctly something should receive those RAs though and it shouldn't necessarily be networkd.
 
> > How about add a PR like UsePREF64= and show this in networkctl and add a test ?
> 
> Dunno. If it's just for testing purposes I'm not sure it should be added.

https://github.com/systemd/systemd/issues/23674 is related. We need to parse and store these in the process to address https://github.com/systemd/systemd/issues/23674.

**Comment by evverx** [comment]
> https://github.com/systemd/systemd/issues/23674 is related. We need to parse and store these in the process to address https://github.com/systemd/systemd/issues/23674.

Got it. I just thought that the idea was to use `UsePREF64=` to test the part sending RAs only. If it can be consumed somewhere it should probably be fine.

Having taken a look at that feature request (where `clatd` is mentioned) I came across https://github.com/toreanderson/clatd/issues/32 and it seems that `clatd` could make use of PREF64s exposed by `networkd`:
> It is very unlikely that I would be able to implement this in clatd, because the receipt and parsing of ICMPv6 RAs are either done by the kernel or some user-space network management service like NetworkManager or systemd-networkd.

> If they expose the prefix somewhere, like in sysfs or dbus, I guess it would be possible to look it up. I am not aware of any way to do it, though.

**Review by yuwata — COMMENTED** [review]
Belated LGTM.

**Pull request merged**
