### PR TITLE
Introduce $LISTEN_NAMES

### PR DESCRIPTION
**Pull request by maciejaszek**

### CODE REVIEW

**Comment by poettering** [comment]
I love where this is going!

**Comment by lemenkov** [comment]
+1 here. Sorry for the noise but @github doesn't have Subscribe button for particular issues/pull requests.

**Comment by philips** [comment]
@lemenkov There is a subscribe button under the "labels" section near the description on the right of the pages. See https://help.github.com/articles/subscribing-to-conversations/

**Comment by maciejaszek** [comment]
Thanks for reviews, I'll prepare v2.

**Comment by maciejaszek** [comment]
v2: https://github.com/systemd/systemd/pull/1247

**Pull request closed without merging**
