### PR TITLE
 udev-manager: actually remove the property

### PR DESCRIPTION
**Pull request by dtardon**

### CODE REVIEW

**Review by yuwata — APPROVED** [review]

**Comment by yuwata** [comment]
(IIRC, setting/unsetting property is not tested in our CI. Let's add test cases later.)

**Comment by dtardon** [comment]
> (IIRC, setting/unsetting property is not tested in our CI. Let's add test cases later.)

Working on this, I've noticed an inconsistency of handling of the global properties in rules: they work only in matches, not in assignments. E.g., given the following rule:

`ENV{FOO}=="?*", ENV{HAS_FOO}="1", TAG+="$env{FOO}"`

running

```sh
udevadm control --reload
udevadm control -p FOO=foo
udevadm trigger -c change -w /devices/virtual/block/loop0
udevadm info /devices/virtual/block/loop0
```

`/devices/virtual/block/loop0` will have property `HAS_FOO=1`, but not tag `foo`. I assume this is a bug...

**Comment by yuwata** [comment]
Interesting. I will take a look.

**Comment by dtardon** [comment]
> Interesting. I will take a look.

There's no need for that, I think I've already fixed it. I just want a confirmation that it's really a bug, not a (weird) feature.

**Comment by dtardon** [comment]
Test is awaiting in #30016, hence removing the `test-candidate` label.

**Pull request merged**
