### PR TITLE
NL → CRNL conversion fixes when logging at the same time as ptyfwd runs

### PR DESCRIPTION
**Pull request by poettering**
An alternative for #30177 

Fixes: #30155

### CODE REVIEW

**Comment by poettering** [comment]
This is mostly a cosmetical issue. I am not sure we should hurry this into 255. It's not clear to me whether writing out the extra CR might trigger some problems elsewhere, hence maybe leave this for 256.

**Comment by poettering** [comment]
I stole the first commit from @yuwata's #30177

**Comment by bluca** [comment]
Is this fixing a recent regression, or a pre-existing issue?

**Comment by bluca** [comment]
Ok, then I'd say not material for v255

**Review by yuwata — APPROVED** [review]
LGTM.

I guess this also fixes #30184.

**Comment by poettering** [comment]
> I guess this also fixes #30184.

It does not. That uses a different output path. Will cook up a fix in a minute.

**Pull request merged**
