### PR TITLE
add Lenovo Yoga 510-14IKB

### PR DESCRIPTION
**Pull request by jonasBoss**
the patch works flawless on my machine.

`$ udevadm info --export-db`:
[udev-db.txt](https://github.com/systemd/systemd/files/1294073/udev-db.txt)

### CODE REVIEW

**Comment by hadess** [comment]
Could you please amend your commit to have the "hwdb: " prefix in the commit subject, and mention which quirk you're adding "add Lenovo Yoga..." doesn't tell us that.

**Comment by poettering** [comment]
@hadess btw, if you do a "squash and merge" merge with github you get to edit the commit msg. For minor commit msg edits it's probably easier to just do that instead of going through another review cycle.

/me does that now.

**Comment by hadess** [comment]
> @hadess btw, if you do a "squash and merge" merge with github you get to edit the commit msg. For minor commit msg edits it's probably easier to just do that instead of going through another review cycle.

Every day, I learn something new :)

**Pull request merged**
