### PR TITLE
ci: skip TEST-02-UNITTESTS on Ubuntu CI

### PR DESCRIPTION
**Pull request by evverx**
It should address https://github.com/systemd/systemd/issues/22059 until it's fixed properly. The test is run there as a normal unit test and as part of the "unit-tests" test so it's still covered there.

### CODE REVIEW

**Comment by bluca** [comment]
Which package needs an update?

**Comment by evverx** [comment]
The systemd debian package has to be updated. FWIW I somehow spend too much time trying to make it work (see https://github.com/systemd/systemd/issues/21975 for example) and I'm not particularly interested in that so if anyone is interested they can figure out what's going on there, fix it and then unblock the test.

**Comment by bluca** [comment]
I had already updated the package following the suggestion in that issue, what else is missing?

Anyway rather than skipping the whole suite, please mark the one unit test as manual so that we don't lose coverage from all of them

**Comment by evverx** [comment]
> please mark the one unit test as manual so that we don't lose coverage from all of them

Nah, the test isn't manual and it passes everywhere else so I don't think Ubuntu CI is sop special that it should prevent the test from being run everywhere else.

**Comment by bluca** [comment]
> > please mark the one unit test as manual so that we don't lose coverage from all of them
> 
> Nah, the test isn't manual and it passes everywhere else so I don't think Ubuntu CI is sop special that it should prevent the test from being run everywhere else.

Sorry, but it makes no sense to lose coverage from hundreds of unit tests because of a single one, that was added just the other day on top of that. Making it so that the faulty one doesn't run is much more sensible.

**Comment by evverx** [comment]
> it makes no sense to lose coverage from hundreds of unit tests

I don't think it affects any other CI service apart from Ubuntu CI so I'm not sure where exactly the coverage is lost.

> Making it so that the faulty one doesn't run is much more sensible

It makes sense to actually fix it. But since it doesn't happen as fast or as often as it should be those "deny-list" files were added to make it possible to keep it afloat until it's somehow fixed and that's exactly what I'm doing here.

**Comment by evverx** [comment]
@mbiebl I'm not sure what kind of discussion is needed here? I agree that the test should be fixed somehow but until then to avoid bothering contributors it can safely be skipped.

And by the way it runs and passes on Ubuntu CI as a normal unit tests. It's just that the "upstream" test is broken somehow because it interacts weirdly with the debian package.

**Comment by evverx** [comment]
@mrc0mmand could you take a look?

**Comment by mbiebl** [comment]
blacklisting tests is a last resort. It wasn't meant as a mechanism to hide (valid) issues 

> Sorry, but it makes no sense to lose coverage from hundreds of unit tests because of a single one, that was added just the other day on top of that. Making it so that the faulty one doesn't run is much more sensible.

agreed. Or actually investigate why the recent PR broke the test.

**Comment by evverx** [comment]
> Or actually investigate why the recent PR broke the test.

I'm not going to do that. As I said
>  FWIW I somehow spend too much time trying to make it work (see #21975 for example) and I'm not particularly interested in that so if anyone is interested they can figure out what's going on there, fix it and then unblock the test.

**Comment by mbiebl** [comment]
> I'm not going to do that.

You don't have to

**Comment by evverx** [comment]
Has anyone started looking into that? How long is it going to fix that? Obviously I'd be happy to close this PR in favor of a PR where it is fixed.

**Comment by mrc0mmand** [comment]
I'll give it a shot later today.

**Comment by evverx** [comment]
@mrc0mmand I'd just skip it until Monday at least to avoid bothering contributors but I don't think I can stop you :-)

**Comment by evverx** [comment]
> It wasn't meant as a mechanism to hide (valid) issues

@mbiebl I'm pretty sure it actually was back in 2019 but even if it wasn't I'm not sure issues like https://github.com/systemd/systemd/issues/21975 are important to people who aren't actually interested in keeping Ubuntu CI afloat. Apart from that one-off fix could the debian package be updated to be always up-to-date with the systemd test suite?

**Comment by evverx** [comment]
It would also be nice to switch to a newer kernel there to really start covering the bpf framework there

**Comment by evverx** [comment]
It would also be nice to figure out whether https://github.com/systemd/systemd/issues/21603 is valid or it can be skipped with a deny-list file.

**Comment by evverx** [comment]
It's been 11 hours since this PR was opened and Ubuntu CI hasn't finished yet and there seem to be PRs where it's been running for 2-3 days. Looks like it's either down or turned off so I don't think skipping the test can actually improve anything there. Since @mrc0mmand seems to be on it I'll go ahead and close this PR.

**Comment by evverx** [comment]
@mrc0mmand could you tag me when/if it's fixed? I'm not sure why the test is run in three different modes there (in two of which it currently passes) and why the package can't be trimmed to make it easier to write tests and I think that should be fixed along with the test. Thanks!

**Comment by mrc0mmand** [comment]
Oh well. There are multiple things going "wrong":

1) `debuild` strips empty directories
2) `debuild` (or something along the way) doesn't like dangling symlinks

Now, the `install_subdir()` in meson explicitly ignores `.gitatrributes`, so the respective installed `test-fstab-generator/*.expected/*.requires/` directory ends up with only a dangling symlink. And it looks like `debuild` doesn't like dangling symlinks so it strips then as well, leading to `test-{01..11}*.expected/*.requires/` directories being empty and subsequently stripped as well. All this ends up in the `systemd-tests*.deb` package, which is then used when running the integration tests.

The `systemd-tests` package then looks like this: 

```
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-01-dev-nfs.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-02-dhcp.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-03-dhcp6.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-04-nfs.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-05-nfs4.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-06-ipv4.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-07-ipv6.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-08-implicit-nfs.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-09-cifs.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-10-iscsi.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-11-live.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-12-dev-sdx.expected/initrd-root-device.target.d/50-root-device.conf
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-12-dev-sdx.expected/initrd-root-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-12-dev-sdx.expected/initrd-usr-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-12-dev-sdx.expected/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-12-dev-sdx.expected/systemd-fsck-root.service
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-12-dev-sdx.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-13-label.expected/initrd-root-device.target.d/50-root-device.conf
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-13-label.expected/initrd-root-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-13-label.expected/initrd-usr-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-13-label.expected/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-13-label.expected/systemd-fsck-root.service
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-13-label.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-14-uuid.expected/initrd-root-device.target.d/50-root-device.conf
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-14-uuid.expected/initrd-root-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-14-uuid.expected/initrd-usr-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-14-uuid.expected/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-14-uuid.expected/systemd-fsck-root.service
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-14-uuid.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/initrd-root-device.target.d/50-root-device.conf
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/initrd-root-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/initrd-usr-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.expected/systemd-fsck-root.service
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-15-partuuid.input
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-16-tmpfs.expected/initrd-root-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-16-tmpfs.expected/initrd-usr-fs.target.requires/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-16-tmpfs.expected/sysroot.mount
D: Installing /usr/lib/systemd/tests/testdata/test-fstab-generator/test-16-tmpfs.input
```

causing the test to fail, for obvious reasons.

So far I don't know enough about Debian packaging to propose what should be the next steps though...

**Comment by mrc0mmand** [comment]
Let me open a new issue, since there's another thing possibly wrong with the test.

**Comment by evverx** [comment]
> agreed. Or actually investigate why the recent PR broke the test.

@mbiebl it was investigated in https://github.com/systemd/systemd/issues/22059#issuecomment-1008211651 and it appears to be a bug in `install_debian_systemd` used on Ubuntu CI only to install files provided by the systemd packages. The test passes everywhere else. It even passes on Ubuntu when it's run with `make clean setup run`.

**Pull request closed without merging**
