### PR TITLE
WIP: fido2: add compatibility for AuthenTrend ATKey.Pro

### PR DESCRIPTION
**Pull request by poettering**
The AuthenTrend ATKey.Pro FIDO2 token supports FIDO2/hmac-secret. But
it's handling of "up" differs from how I think this should work. It
advertises that it supports "up", but we'd like to turn that off, but if
we do that, it'll tell us FIDO_ERR_UNSUPPORTED_OPTION. This commit then
will reset "up" to OMIT, and try again.

This appears to work at first. But the weird thing is that in this case
when we remove the token and replug it, it appears to forget its HMAC
logic. Something is still off.

### CODE REVIEW

**Comment by nuno0529** [comment]
@poettering thanks for testing this great feature on ATKey.Pro, I'm the firmware owner of this key and below is my comment for the issues you encounter.
1. Q: _It advertises that it supports "up", but we'd like to turn that off, but if
we do that, it'll tell us FIDO_ERR_UNSUPPORTED_OPTION_
     - A: The assertion request with asking hmac-secret can only work with “up” is true (default value is true if the command doesn’t specify this). 
       - In ctap2.0 spec, there is (The authenticator waits for user consent)[under https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#sctn-hmac-secret-extension]
       - In latest ctap2.1 Review Draft spec, there is [If "up" is set to false, authenticator returns CTAP2_ERR_UNSUPPORTED_OPTION.](https://fidoalliance.org/specs/fido-v2.1-rd-20201208/fido-client-to-authenticator-protocol-v2.1-rd-20201208.html#sctn-hmac-secret-extension)

     - IIUC, at beginning the hmac-secret was designed to login local system in offline scenario that without the capability to check the signature but hmac. So user consent check was added for login purpose.
1. Q:  _...the weird thing is that in this case when we remove the token and replug it, it appears to forget its HMAC
logic._
     - A: This is an issue in the ATKey.Pro's firmware side when handling this hmac-secret with "rk"=false credential case (i.e. `non-discoverable credentials` in latest ctap2.1 spec ). Because my original implementation on this hmac-secret didn't consider "rk"=false case well and latest ctap2.1 Review Draft spec has clarify this to prevent this [If authenticator supports this extension, authenticator MUST support it for both discoverable and non-discoverable credentials.](https://fidoalliance.org/specs/fido-v2.1-rd-20201208/fido-client-to-authenticator-protocol-v2.1-rd-20201208.html#sctn-hmac-secret-extension)
     - So the workaround solution I can propose is to use `fido_cred_set_rk` when making a credential before the new firmware of ATKey.Pro is ready. But I can't tell if no other FIDO2 security key will has the same issue due to misunderstanding of this part in ctap2.0 spec, so this may be an option.

1. Besides, during investigating your feedback, I think there may be an potential problem needs to highlight. 
     - A: In latest ctap2.1 Review Draft spec, there is a behavior change [The authenticator chooses which CredRandom to use for next step based on whether user verification was done or not in above steps.](https://fidoalliance.org/specs/fido-v2.1-rd-20201208/fido-client-to-authenticator-protocol-v2.1-rd-20201208.html#sctn-hmac-secret-extension). So the hmac-secret in the response will be different if the assertion comes just after UV (User Verification likes fingerprint or clientPin) or not. And due to ATKey.Pro is a fingerprint security key and our firmware has a special behavior that, once the fingerprint is configured and then all the request for assertion with "up"=true (default value is true if the command doesn’t specify this, except specify this to false), the fingerprint verification will always be asked. So somethings in your application scenario will be different before/after configuring fingerprint on the ATKey.Pro even with the same request.

**Comment by poettering** [comment]
@nuno0529 thanks for the quick feedback

So do I understand this properly, an upcoming firmware update for the devices will fix the "hmac-secret key is forgotten" issue for us? When can this firmware update be expected? (And how does one do a firmware upgrade? can that be done from Linux? Any chance AuthenTrend could hook this up via fwupd/lvfs?)

If I understand this properly then enabling "rk" would mean we'd actually store out key on the device. I'd rather not do that. The current property that you can easily enroll 100 encrypted devices to a single fido2 key is a very good thing. This only works because we store nothing on the device, but everything on disk. I think i'd rather wait until the firmware is fixed to support rk=false hmac-secret usage.

I am not sure I understand the third issue you raise? are you saying that once a user enrolls a fingerprint onto the device the hmac-secret key on the device is going to be difference than before – at least for our own use? If so, I figure that'd be fine, as people would just have to re-enroll thei device then. Or did I misunderstand what you are saying?

**Comment by hughsie** [comment]
> does lvfs/fwupd already do firmware upgrades for similar fido2 secureity tokens

Yes, the SoloKey is already updatable using fwupd and firmware is on the LVFS. @nuno0529 send me an email (richard_at_hughsie.com) and we can get the discussion started.

**Comment by nuno0529** [comment]
@poettering Thanks for the comments.
1. Yes, we will have an firmware update to fix this hmac-secret issue under rk=false case. The timeline will be around mid-March within a scheduled release. So far we only support FW update through our app on Windows 10 only. And soon we will support the FW update though our website on chromium based browsers through WebHID. Although highly interested in lvfs/fwupd, I'm afraid this support won't be ready soon. Anyway, if above methods couldn't work in time, we will send you a new one with new firmware.
2. Yes, your concern on rk=true in this case is reasonable. The rk is originally designed to support roaming feature and best practice is to use with User Verification protection likes PIN or fingerprint. So the expected hmac-secret can only be respond after user verification.
3. Yes, your understanding is correct. Below `CredRandom` in spec is the hmac key to use in fido2 key.
    - If uv bit is set to 1 in the response (this means user verification is requested), let CredRandom be CredRandomWithUV. 
    - If uv bit is set to 0 in the response (this means user verification is not requested),, let CredRandom be CredRandomWithoutUV.

    So once the user enrolls a fingerprint, the fido2 (ATKey.Pro's behavior) will always request User Verification when doing get assertion and you won't get the expected hmac value by using CredRandomWithoutUV originally that you ever used somewhere.
   This behavior to separate them is to add the protection on the hmac-secret in different security levels,  1)everyone can get case and 2)only verified user case.

@hughsie thanks for your information, I will send you an email to discuss the detail.

**Comment by poettering** [comment]
@nuno0529 hey, any update on the fixed firmware?

**Comment by nuno0529** [comment]
@poettering sorry for the late reply, we will send you a new key with fixed firmware first and we are still working for new firmware for upgrades.

**Comment by poettering** [comment]
Closing, as this has been subsumed by #19756

**Pull request closed without merging**
