### PR TITLE
networkd: add support to configure IPv6 router_solicitation

### PR DESCRIPTION
**Pull request by ssahani**
#1570 re-based the patch

### CODE REVIEW

**Comment by teg** [comment]
We should not just be adding all these options unless they make sense. Each needs an argument why we should support it.

**Comment by zonque** [comment]
Apart from that, the branch needs a rebase.

**Comment by teg** [comment]
Actually, hold off on the rebase on this, I'm about to move this from the kernel to userspace, so it would need to be a bigger patch (but we should first discuss if we want it at all).

**Comment by teg** [comment]
With PR #1843 the logic was moved from the kernel to userspace, so this should be rebased on top of that (if we want it).

**Pull request closed without merging**
