### PR TITLE
DocBook validation fixes (part 2)

### PR DESCRIPTION
**Pull request by dtardon**
This is on top of https://github.com/systemd/systemd/pull/30615. These changes are larger or subject to opinion.

### CODE REVIEW

**Comment by yuwata** [comment]
```
1105/1616 systemd:dist / check-version-history                                              FAIL             1.28s   exit status 1
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
systemd.unit.xml /refsynopsisdiv/variablelist/varlistentry[term="System Unit Search Path"] is undocumented
systemd.unit.xml /refsynopsisdiv/variablelist/varlistentry[term="User Unit Search Path"] is undocumented
Hint: if you reorganized this part of the documentation, please update tools/commands_ignorelist.
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

**Comment by bluca** [comment]
Given you seem knowledgeable on manpages syntax, any idea how to fix all these groff warnings?

```
W: libsystemd-dev: groff-message troff:<standard input>:193: warning [p 1, 2.8i, div '3tbd11,1', 0.0i]: cannot break line [usr/share/man/man3/sd_bus_message_append_basic.3.gz:1]
W: libsystemd-dev: groff-message troff:<standard input>:225: warning [p 1, 6.3i, div '3tbd11,1', 0.0i]: cannot break line [usr/share/man/man3/sd_bus_message_read.3.gz:1]
W: libsystemd-dev: groff-message troff:<standard input>:235: warning [p 1, 7.8i, div '3tbd11,1', 0.0i]: cannot break line [usr/share/man/man3/sd_bus_message_append.3.gz:1]
W: libsystemd-dev: groff-message troff:<standard input>:280: warning [p 1, 6.3i, div '3tbd16,1', 0.0i]: cannot break line [usr/share/man/man3/sd_bus_message_read.3.gz:2]
W: libsystemd-dev: groff-message troff:<standard input>:290: warning [p 1, 7.8i, div '3tbd16,1', 0.0i]: cannot break line [usr/share/man/man3/sd_bus_message_append.3.gz:2]
W: libsystemd-dev: groff-message troff:<standard input>:296: warning [p 1, 6.3i, div '3tbd18,1', 0.0i]: cannot break line [usr/share/man/man3/sd_bus_message_read.3.gz:3]
W: libsystemd-dev: groff-message troff:<standard input>:308: warning [p 1, 7.8i, div '3tbd18,1', 0.0i]: cannot break line [usr/share/man/man3/sd_bus_message_append.3.gz:3]
W: systemd: groff-message 256: warning: table wider than line length minus indentation [usr/share/man/man7/systemd.net-naming-scheme.7.gz:3]
W: systemd: groff-message 329: warning: table wider than line length minus indentation [usr/share/man/man5/sysupdate.d.5.gz:2]
W: systemd: groff-message troff:<standard input>:1683: warning [p 12, 6.7i, div '3tbd5,3', 0.0i]: cannot break line [usr/share/man/man5/systemd.exec.5.gz:1]
W: systemd: groff-message troff:<standard input>:182: warning [p 2, 3.5i, div '3tbd1,0', 0.0i]: cannot break line [usr/share/man/man7/systemd.net-naming-scheme.7.gz:1]
W: systemd: groff-message troff:<standard input>:215: warning [p 2, 0.7i, div '3tbd3,0', 0.0i]: cannot break line [usr/share/man/man8/systemd-gpt-auto-generator.8.gz:2]
W: systemd: groff-message troff:<standard input>:222: warning [p 3, 2.2i]: cannot break line [usr/share/man/man5/systemd-sleep.conf.5.gz:1]
W: systemd: groff-message troff:<standard input>:283: warning [p 3, 0.7i, div '3tbd4,0', 0.0i]: cannot break line [usr/share/man/man7/systemd.net-naming-scheme.7.gz:2]
W: systemd: groff-message troff:<standard input>:337: warning [p 3, 1.3i, div '3tbd0,4', 0.5i]: cannot break line [usr/share/man/man5/sysupdate.d.5.gz:1]
W: systemd: groff-message troff:<standard input>:500: warning [p 4, 9.3i, div '3tbd4,0', 0.0i]: cannot break line [usr/share/man/man5/systemd.unit.5.gz:1]
W: systemd: groff-message troff:<standard input>:5078: warning [p 24, 13.0i, div '3tbd12,2', 0.3i]: cannot break line [usr/share/man/man5/systemd.exec.5.gz:2]
W: systemd: groff-message troff:<standard input>:5099: warning [p 24, 13.0i, div '3tbd15,2', 0.2i]: cannot break line [usr/share/man/man5/systemd.exec.5.gz:3]
W: systemd: groff-message troff:<standard input>:850: warning [p 6, 10.8i]: cannot break line [usr/share/man/man7/daemon.7.gz:1]
W: systemd: groff-message troff:<standard input>:87: warning [p 1, 6.3i, div '3tbd1,0', 0.2i]: cannot break line [usr/share/man/man8/systemd-gpt-auto-generator.8.gz:1]
W: systemd-boot: groff-message troff:<standard input>:416: warning [p 4, 10.8i]: cannot break line [usr/share/man/man5/loader.conf.5.gz:1]
W: systemd-boot: groff-message troff:<standard input>:421: warning [p 4, 11.3i]: cannot break line [usr/share/man/man5/loader.conf.5.gz:2]
W: systemd-container: groff-message troff:<standard input>:324: warning [p 3, 7.3i]: cannot break line [usr/share/man/man1/systemd-nspawn.1.gz:1]
W: systemd-resolved: groff-message troff:<standard input>:388: warning [p 5, 6.2i]: cannot break line [usr/share/man/man5/resolved.conf.5.gz:1]
W: systemd-resolved: groff-message troff:<standard input>:429: warning: macro 'an-trap' not defined [usr/share/man/man5/org.freedesktop.resolve1.5.gz:1]
```

**Comment by yuwata** [comment]
part1 was merged. Please rebase.

**Comment by dtardon** [comment]
> part1 was merged. Please rebase.

Done.

**Comment by dtardon** [comment]
> Given you seem knowledgeable on manpages syntax, any idea how to fix all these groff warnings?

I'm sorry... I'm reasonably knowledgeable on DocBook, but not on groff.

**Review by yuwata — APPROVED** [review]

**Comment by DaanDeMeyer** [comment]
@dtardon This broken update-man-rules.py (specifically the changes to standard-conf.xml), can you take a look

**Pull request merged**
