### PR TITLE
A couple of Packit/Super-Linter tweaks

### PR DESCRIPTION
**Pull request by mrc0mmand**

### CODE REVIEW

**Review by yuwata — APPROVED** [review]
LGTM.

**Comment by evverx** [comment]
Thanks!

**Comment by evverx** [comment]
@mrc0mmand I don't think superlinter should complain about GITHUB_TOKEN when MULTI_STATUS isn't set either but turning it off explicitly with MULTI_STATUS=false is better anyway :-)

**Comment by evverx** [comment]
FWIW @mrc0mmand to judge from https://github.com/evverx/systemd/pull/89 `super-linter` has been released with your patch included so I think if those errors have been bugging you it should be possible to pin superlinter to that commit without waiting for Dependabot to update it in March.

**Comment by mrc0mmand** [comment]
> FWIW @mrc0mmand to judge from [evverx#89](https://github.com/evverx/systemd/pull/89) `super-linter` has been released with your patch included so I think if those errors have been bugging you it should be possible to pin superlinter to that commit without waiting for Dependabot to update it in March.

Not really, I was just curious if there's a way to get rid of them, since they might be confusing to users which are not familiar with super-linter. So I guess we can wait for the regular Dependabot update :-)

**Pull request merged**
