### PR TITLE
support the Debian-style tmp= argument in crypttab

### PR DESCRIPTION
**Pull request by poettering**
Fixes: #952

### CODE REVIEW

**Comment by poettering** [comment]
Hmm @mrc0mmand @xnox hmm, so this changes the crypttab "tmp" option to mean "ext4" rather than "ext2". This breaks the ubuntu test that checks for that. How do I get the ubuntu check fixed?

(this change follows a similar change debian made a while back in its cryptsetup package)

**Comment by mrc0mmand** [comment]
> Hmm @mrc0mmand @xnox hmm, so this changes the crypttab "tmp" option to mean "ext4" rather than "ext2". This breaks the ubuntu test that checks for that. How do I get the ubuntu check fixed?
> 
> (this change follows a similar change debian made a while back in its cryptsetup package)

Maybe @ddstreet would be able to help there.

**Comment by keszybz** [comment]
LGTM, but we need to wait for @ddstreet or @xnox to fix the ubuntu tests.

**Comment by ddstreet** [comment]
sorry for the delay, the Ubuntu CI 'storage' test should check for the crypttab 'tmp' default fs to be either ext2 or ext4, so this pr should pass ubuntu ci now:

https://salsa.debian.org/systemd-team/systemd/-/commit/36f4cfe5dfe4cffb2ffe134558a1ca72074b50e4

**Comment by poettering** [comment]
repused to retrigger all CIs

**Comment by poettering** [comment]
Ok, let's merge, @keszybz liked it already afte rall and the CI passed now.

**Pull request merged**
