### PR TITLE
backlight: modified read_brightness function to fallback to attribute …

### PR DESCRIPTION
**Pull request by panzerox123**
…'brightness' if 'absolute_brightness' is greater than 'max_brightness'.

This fixes an issue with device amdgpu_bl0(tentatively intel_backlight as well. Not sure) as 'actual_brightness' stores a 16 bit unsigned integer, and is much higher than 'max_brightness'. Because of this, the brightness would be set to max brightness on boot.

[Bug report](https://bugzilla.kernel.org/show_bug.cgi?id=203905)

### CODE REVIEW

**Comment by poettering** [comment]
I am not too much of a fan of this. This is a work-around around a kernel bug, and I am quite confident that they'll fix it there soon. systemd is not a place for piling up work-arounds. The kernel is open source just like our code, and hence this bug can be fixed where it is.

**Comment by poettering** [comment]
what I'd be willing to merge is a patch that stores the max brightness value we see along with the brightness level we save, so that when the driver gets updated with finer granularity we can rescale the brightness to the new range.

i.e. allowing smooth updating of drivers makes a lot of sense, but working around driver bugs sounds wrong to me.

**Comment by panzerox123** [comment]
I believe it should've been fixed with this [patch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=35dad45d5cad3c9ca8d6a338cbf668cd7ea86469) on Kernel 5.0. Not sure why actual_brightness still returns unreal values. I'll do a little more digging.

**Comment by panzerox123** [comment]
Looked around, and it seems to be an intentional change by AMD to their driver ([commit](https://github.com/torvalds/linux/commit/262485a50fd4532a8d71165190adc7a0a19bcc9e#diff-b496037255b7766a782d3f3711b50db8)). Probably means they're not going to go back to 8 bit even if I send in a patch. 

> what I'd be willing to merge is a patch that stores the max brightness value we see along with the brightness level we save, so that when the driver gets updated with finer granularity we can rescale the brightness to the new range.

I'll try to work something out when I find some time tomorrow.

**Pull request closed without merging**
