### PR TITLE
Avoid spurious warnings about unknown sections in .netdev files

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
semaphore is very unhappy!

**Comment by keszybz** [comment]
"Semaphore is under maintenance. Processing of incoming jobs has been paused."

I think the PR is OK and build failure is unrelated.

**Comment by poettering** [comment]
any chance you can rebase and repush this? would love to have at least some CI coverage about this

**Comment by keszybz** [comment]
Updated.

**Comment by poettering** [comment]
yay, all green!

**Pull request merged**
