### PR TITLE
Update opensuse packaging specs submodule to latest

### PR DESCRIPTION
**Pull request by daandemeyer**
The "pages build and deployment" action only checks out the latest commit of each submodule, which causes failures if we're not tracking the latest submodule.

Issue reported: https://github.com/orgs/community/discussions/112984 but until it's fixed let's make sure we're using the latest commit.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by evverx** [comment]
I was wondering why Dependabot never opened a PR. 2 days ago it failed with
```
updater | Submodule 'pkg/arch' (https://gitlab.archlinux.org/daandemeyer/systemd) registered for path 'pkg/arch'
updater | Submodule 'pkg/centos' (https://git.centos.org/rpms/systemd) registered for path 'pkg/centos'
updater | Submodule 'pkg/debian' (https://salsa.debian.org/systemd-team/systemd) registered for path 'pkg/debian'
updater | Submodule 'pkg/fedora' (https://src.fedoraproject.org/rpms/systemd) registered for path 'pkg/fedora'
updater | Submodule 'pkg/opensuse' (https://code.opensuse.org/package/systemd) registered for path 'pkg/opensuse'
updater | Cloning into '/home/dependabot/dependabot-updater/repo/pkg/arch'...
updater | warning: redirecting to https://gitlab.archlinux.org/daandemeyer/systemd.git/
updater | Cloning into '/home/dependabot/dependabot-updater/repo/pkg/centos'...
updater | Cloning into '/home/dependabot/dependabot-updater/repo/pkg/debian'...
updater | warning: redirecting to https://salsa.debian.org/systemd-team/systemd.git/
updater | Cloning into '/home/dependabot/dependabot-updater/repo/pkg/fedora'...
updater | Cloning into '/home/dependabot/dependabot-updater/repo/pkg/opensuse'...
updater | warning: redirecting to https://gitlab.archlinux.org/daandemeyer/systemd.git/
updater | warning: redirecting to https://gitlab.archlinux.org/daandemeyer/systemd.git/
updater | From https://gitlab.archlinux.org/daandemeyer/systemd
updater |  * branch            733045c8f6b0acf2f0cfaac207500483a678f4d2 -> FETCH_HEAD
updater | Submodule path 'pkg/arch': checked out '733045c8f6b0acf2f0cfaac207500483a678f4d2'
updater | From https://git.centos.org/rpms/systemd
updater |  * branch            3cf45106c8bc5a050901851be6b2ac85b6f5c571 -> FETCH_HEAD
updater | Submodule path 'pkg/centos': checked out '3cf45106c8bc5a050901851be6b2ac85b6f5c571'
updater | Submodule path 'pkg/debian': checked out '5451923e3e7f5d6cc54f78a8b1d08317a42b4109'
updater | Submodule path 'pkg/fedora': checked out '2822a03dded26b9453bddbba7c6a152de8204aec'
updater | error: Server does not allow request for unadvertised object 37aca188c2ef606319217b30ff8b0c66df6c60f1
updater | fatal: Fetched in submodule path 'pkg/opensuse', but it did not contain 37aca188c2ef606319217b30ff8b0c66df6c60f1. Direct fetching of that commit failed.
updater | fatal:
updater | 2024/03/15 09:31:46 INFO <job_800533910> Finished job processing
updater | 2024/03/15 09:31:46 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------+
updater | |       Errors       |
updater | +--------------------+
updater | | job_repo_not_found |
updater | +--------------------+
```

**Comment by DaanDeMeyer** [comment]
I guess this is because code.opensuse.org uses pagure as the git forge

**Comment by evverx** [comment]
As far as I understand once "pkg/opensuse" gets updated it should break the action and Dependabot again and in the case of Dependabot prevent the other submodules from being updated automatically. Looks like it should be excluded explicitly to avoid that.

**Comment by DaanDeMeyer** [comment]
@evverx I have now switched the opensuse url to a different git mirror that is backed by gitea instead of pagure. Hopefully that works better.

**Comment by DaanDeMeyer** [comment]
@evverx Can you link to where you found these dependabot logs?

**Comment by evverx** [comment]
https://github.com/systemd/systemd/network/updates/800533910

**Pull request merged**
