### PR TITLE
Implement boot counting scheme in systemd-boot

### PR DESCRIPTION
**Pull request by msekletar**
This PR implements (roughly) scheme as proposed by Kay here

https://github.com/systemd/systemd/issues/909#issuecomment-128789172

### CODE REVIEW

**Comment by keszybz** [comment]
The code looks nice.

**Comment by msekletar** [comment]
@kaysievers any chance you can have a look at this?

**Comment by msekletar** [comment]
ping?

**Comment by msekletar** [comment]
@neersighted as you originally reported #909...I'd be very glad if you could have a look at this PR and let me know if you find this actually useful.

**Comment by neersighted** [comment]
Not quite the use case I had in mind, but it looks well implemented and useful. :+1: from me.

**Comment by msekletar** [comment]
> I believe this is a typo, should be ConditionPathExists

Good catch. Thanks. Will fix that in the future. For now I am withdrawing this PR.

**Pull request closed without merging**
