### PR TITLE
network: refuse 169.254.0.0/24 and 169.254.255.0/24

### PR DESCRIPTION
**Pull request by yuwata**
Follow-ups for #23927.

cc @AndreKalb

### CODE REVIEW

**Comment by AndreKalb** [comment]
I think you could change this too on `networkd-ipv4ll.c` line 298 (`in4_addr_is_link_local()` to `in4_addr_is_link_local_dynamic()`)

```
        if (!in4_addr_is_link_local(&a.in)) {
                log_syntax(unit, LOG_WARNING, filename, line, 0,
                           "Not a IPv4 link local address, ignoring assignment: %s", rvalue);
                return 0;
        }
```
to prevent to set this IPs reserved ip ranges, with a parsing error.

**Comment by yuwata** [comment]
I already did. Is it not enough? Or do I misunderstand your comment?

**Comment by AndreKalb** [comment]
No, sorry my misstake. I don't see the last patch block. Looks fine.

**Comment by yuwata** [comment]
No problem. Thank you for the review.

**Review by bluca — APPROVED** [review]

**Pull request merged**
