### PR TITLE
Backport various commits to v256-stable

### PR DESCRIPTION
**Pull request by daandemeyer**

### CODE REVIEW

**Comment by yuwata** [comment]
The last commit is not a bug fix. Do you really need it?

**Comment by DaanDeMeyer** [comment]
> The last commit is not a bug fix. Do you really need it?

It woulf be rather handy for use in mkosi. I figure since it's a' environment variable and doesn't break compat it'd be ok.

**Comment by yuwata** [comment]
> > The last commit is not a bug fix. Do you really need it?
> 
> It would be rather handy for use in mkosi. I figured since it's an environment variable and doesn't break compat it'd be ok.

OK.

**Review by yuwata — APPROVED** [review]

**Comment by keszybz** [comment]
@DaanDeMeyer please use rebase&merge in the systemd-stable branches.

**Pull request merged**
