### PR TITLE
test: exercise sytemd-integritysetup & generator

### PR DESCRIPTION
**Pull request by tasleson**
Ensures we can open a dm-integrity volume formated with
integritysetup.

### CODE REVIEW

**Review by bluca — APPROVED** [review]
lgtm

**Comment by bluca** [comment]
```
In /github/workspace/test/units/testsuite-67.sh line 53:
    integritysetup format ${loop} --batch-mode -I ${algorithm} || exit 1
                          ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    integritysetup format "${loop}" --batch-mode -I ${algorithm} || exit 1


In /github/workspace/test/units/testsuite-67.sh line 54:
    integritysetup open -I ${algorithm} ${loop} "${DM_NAME}" || exit 1
                                        ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    integritysetup open -I ${algorithm} "${loop}" "${DM_NAME}" || exit 1


In /github/workspace/test/units/testsuite-67.sh line 69:
    if [[ ! -e "/run/systemd/generator/systemd-integritysetup@"${DM_NAME}".service" ]]; then
                                                               ^--------^ SC2027: The surrounding quotes actually unquote this. Remove or escape them.


In /github/workspace/test/units/testsuite-67.sh line 80:
        if [ "${FULL_DM_DEV_NAME}" != `blkid -U "${FS_UUID}"` ]; then
                                      ^---------------------^ SC2046: Quote this to prevent word splitting.
                                      ^---------------------^ SC2006: Use $(...) notation instead of legacy backticked `...`.

Did you mean: 
        if [ "${FULL_DM_DEV_NAME}" != $(blkid -U "${FS_UUID}") ]; then
```

**Comment by bluca** [comment]
new test is also failing on CentOS 8

**Comment by tasleson** [comment]
@bluca @mrc0mmand
> new test is also failing on CentOS 8

The test is failing as it's unable to copy all the required files into the VM image.  I see in the `test/README.testsuite` that there's a process listed for the Ubuntu CI, but none that I've seen for EL8?

The following rpms are needed:
 * integritysetup
 * util-linux
 * device-mapper
 * device-mapper-event

**Comment by mrc0mmand** [comment]
> @bluca @mrc0mmand
> 
> > new test is also failing on CentOS 8
> 
> The test is failing as it's unable to copy all the required files into the VM image. I see in the `test/README.testsuite` that there's a process listed for the Ubuntu CI, but none that I've seen for EL8?
> 
> The following rpms are needed:
> 
>     * integritysetup
> 
>     * util-linux
> 
>     * device-mapper
> 
>     * device-mapper-event

Thanks for the heads-up - I added the missing dependency into the C8 bootstrap script and restarted the job.

**Pull request merged**
