### PR TITLE
core: manager logs firmware and loader time when startup finished

### LINKED ISSUE #7721: analyze: systemd-analyze doesn't report kernel time
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v230, checked no significant changes of code in v236 

### Used distribution

> custom embedded

### Observation
systemd_7721

`systemd-analyze` doesn't report the kernel time:
`Startup finished in 1.860s (userspace) = 5.957s`

But this is reported in journal by `manager.c`:
`systemd[1]: Startup finished in 4.097s (kernel) + 1.860s (userspace) = 5.957s.`

`gdbus introspect -y -d org.freedesktop.systemd1 -o /org/freedesktop/systemd1 | grep Kernel` returns
```
readonly t KernelTimestamp = 0;
readonly t KernelTimestampMonotonic = 0;
```

At the main.c, directly after `dual_timestamp_from_monotonic(&kernel_timestamp, 0);`, `kernel_timestamp.realtime` is 0

### Expectation
I am not sure if in this case the kernel time shall not be reported by `systemd-analyze`.
Also, the report from `systemd-analyze` and `manager.c` is not consistent. (see above)

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by yuwata** [comment]
Before this,
```
Dec 25 09:55:12 systemd[1]: Startup finished in 878ms (kernel) + 890ms (initrd) + 5.827s (userspace) = 19.264s.
```
After this,
```
Dec 25 13:26:09 systemd[1]: Startup finished in 7.797s (firmware) + 1.172s (loader) + 877ms (kernel) + 861ms (initrd) + 5.841s (userspace) = 16.550s.
```
Note that `systemd-analyze` shows
```
Startup finished in 7.797s (firmware) + 1.172s (loader) + 877ms (kernel) + 861ms (initrd) + 5.841s (userspace) = 16.550s
```

**Comment by keszybz** [comment]
This looks good, but I pushed a fixup commit to initialize the temporary buffer.

**Comment by yuwata** [comment]
@keszybz Thanks. @Shuangistan reports that this does not fix #7721. I've dropped the reference to the issue.

**Comment by yuwata** [comment]
It seems #7721 does not fixed by this, as @Shuangistan reported the issue is only happens on arm64 board, but this does not do anything architecture specific. So, I do not think we need to wait his report about this PR. Can I merge this after CI tests pass?

**Pull request merged**
