### PR TITLE
Check behavior of -Werror=shadow before deciding to use it

### LINKED ISSUE #406: We should remove -Werror=shadow from the CFLAGS when we detect we run on an older gcc version
I am not sure why you guys don't see these errors but I see many shadow errors since we enabled the switch. I started fixing some but then decided to ask first. Is it our compiler acting crazy? 

```
shadow/src/libsystemd/sd-bus/bus-kernel.c: In function 'bus_message_setup_kmsg':
shadow/src/libsystemd/sd-bus/bus-kernel.c:323:33: error: declaration of 'now' shadows a global declaration [-Werror=shadow]
In file included from shadow/src/basic/util.h:47:0,
                 from shadow/src/libsystemd/sd-bus/bus-kernel.c:37:
shadow/src/basic/time-util.h:72:8: error: shadowed declaration is here [-Werror=shadow]


shadow/src/basic/hashmap.c: In function 'get_hash_key':
shadow/src/basic/hashmap.c:386:34: error: declaration of 'hash_key' shadows a global declaration [-Werror=shadow]
shadow/src/basic/hashmap.c:376:17: error: shadowed declaration is here [-Werror=shadow]

shadow/src/basic/rm-rf.c: In function 'rm_rf_children':
shadow/src/basic/rm-rf.c:65:22: error: declaration of 'is_dir' shadows a global declaration [-Werror=shadow]
In file included from shadow/src/basic/rm-rf.c:22:0:
shadow/src/basic/util.h:838:5: error: shadowed declaration is here [-Werror=shadow]

shadow/src/shared/fstab-util.h: In function 'fstab_test_yes_no_option':
shadow/src/shared/fstab-util.h:39:75: error: declaration of 'yes_no' shadows a global declaration [-Werror=shadow]
In file included from shadow/src/shared/generator.c:24:0:
shadow/src/basic/util.h:87:27: error: shadowed declaration is here [-Werror=shadow]

shadow/src/core/device.c: In function 'device_update_found_one':
shadow/src/core/device.c:444:82: error: declaration of 'now' shadows a global declaration [-Werror=shadow]
In file included from shadow/src/basic/util.h:47:0,
                 from shadow/src/basic/hashmap.h:28,
                 from shadow/src/shared/install.h:32,
                 from shadow/src/core/unit.h:36,
                 from shadow/src/core/dbus-device.h:24,
                 from shadow/src/core/device.c:28:
shadow/src/basic/time-util.h:72:8: error: shadowed declaration is here [-Werror=shadow]
shadow/src/core/device.c: In function 'device_update_found_by_sysfs':
shadow/src/core/device.c:476:106: error: declaration of 'now' shadows a global declaration [-Werror=shadow]
In file included from shadow/src/basic/util.h:47:0,
                 from shadow/src/basic/hashmap.h:28,
                 from shadow/src/shared/install.h:32,
                 from shadow/src/core/unit.h:36,
                 from shadow/src/core/dbus-device.h:24,
                 from shadow/src/core/device.c:28:
shadow/src/basic/time-util.h:72:8: error: shadowed declaration is here [-Werror=shadow]
shadow/src/core/device.c: In function 'device_update_found_by_name':
shadow/src/core/device.c:492:104: error: declaration of 'now' shadows a global declaration [-Werror=shadow]
In file included from shadow/src/basic/util.h:47:0,
                 from shadow/src/basic/hashmap.h:28,
                 from shadow/src/shared/install.h:32,
                 from shadow/src/core/unit.h:36,
                 from shadow/src/core/dbus-device.h:24,
                 from shadow/src/core/device.c:28:
shadow/src/basic/time-util.h:72:8: error: shadowed declaration is here [-Werror=shadow]
shadow/src/core/device.c: In function 'device_found_node':
shadow/src/core/device.c:767:87: error: declaration of 'now' shadows a global declaration [-Werror=shadow]
In file included from shadow/src/basic/util.h:47:0,
                 from shadow/src/basic/hashmap.h:28,
                 from shadow/src/shared/install.h:32,
                 from shadow/src/core/unit.h:36,
                 from shadow/src/core/dbus-device.h:24,
                 from shadow/src/core/device.c:28:
shadow/src/basic/time-util.h:72:8: error: shadowed declaration is here [-Werror=shadow]
```

### PR DESCRIPTION
**Pull request by filbranden**
Fixes #406

@utezduyar Can you please check if this solves your build without the need for a downstream patch?

Cheers!
Filipe

### CODE REVIEW

**Comment by poettering** [comment]
Looks fine to me. Let's see if Semaphore and @utezduyar agree too.

**Comment by utezduyar** [comment]
@filbranden I applied the patch on systemd 222 and unfortunately it didn't work for me. 

```
make -C build/mipsisa32r2el-axis-linux-gnu all
make[1]: Entering directory '/home/umuttl/Development/q7436.lfp.back.from.vacation.2015.09.03.10.00/apps/systemd/build/mipsisa32r2el-axis-linux-gnu'
make --no-print-directory all-recursive
Making all in .
  CC       src/libsystemd/sd-bus/libsystemd_la-bus-kernel.lo
/home/umuttl/Development/q7436.lfp.back.from.vacation.2015.09.03.10.00/apps/systemd/systemd/src/libsystemd/sd-bus/bus-kernel.c: In function 'bus_message_setup_kmsg':
/home/umuttl/Development/q7436.lfp.back.from.vacation.2015.09.03.10.00/apps/systemd/systemd/src/libsystemd/sd-bus/bus-kernel.c:323:33: error: declaration of 'now' shadows a global declaration [-Werror=shadow]
In file included from /home/umuttl/Development/q7436.lfp.back.from.vacation.2015.09.03.10.00/apps/systemd/systemd/src/basic/util.h:47:0,
                 from /home/umuttl/Development/q7436.lfp.back.from.vacation.2015.09.03.10.00/apps/systemd/systemd/src/libsystemd/sd-bus/bus-kernel.c:37:
/home/umuttl/Development/q7436.lfp.back.from.vacation.2015.09.03.10.00/apps/systemd/systemd/src/basic/time-util.h:72:8: error: shadowed declaration is here [-Werror=shadow]
cc1: some warnings being treated as errors
Makefile:15637: recipe for target 'src/libsystemd/sd-bus/libsystemd_la-bus-kernel.lo' failed
make[3]: *** [src/libsystemd/sd-bus/libsystemd_la-bus-kernel.lo] Error 1
Makefile:18408: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
Makefile:9090: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/umuttl/Development/q7436.lfp.back.from.vacation.2015.09.03.10.00/apps/systemd/build/mipsisa32r2el-axis-linux-gnu'
/home/umuttl/Development/q7436.lfp.back.from.vacation.2015.09.03.10.00/tools/build/rules/autoconf.mak:80: recipe for target 'all_autoconf' failed
make: *** [all_autoconf] Error 2

```

Following is the link to my generated configure file - https://drive.google.com/file/d/0B_uiALgWpGXtRThHazFxQ3RSalU/view?usp=sharing

Thanks for looking into this though to be complete there is also `implicit-function-declaration` problem, same reason as shadow declaration. I resolve it with env variable `export cc_cv_CFLAGS__Werror_implicit_function_declaration=no`

**Comment by filbranden** [comment]
Hey @utezduyar,

The contents of the configure script look sane, I can see that the generated C sources look right.

Are you sure you re-ran configure before doing your build?

Perhaps look inside config.log to see if it says something about testing `-Werror=shadow` and what those results are?

You can also try to create a C source file with these contents:

``` c
#include <unistd.h>
int main(void) {
        int unlink = 7;
        return 0;
}
```

And compile it with `-Werror=shadow` using your compiler to see whether it will complain about it or not... If it does, that's what's expected (from the errors you're seeing while building systemd), if it doesn't, it might be a problem somewhere else...

Cheers!
Filipe

**Comment by filbranden** [comment]
Looking at the patch again, I wish:
1) We supported `CC_CHECK_FLAGS_APPEND` as well (should be a fairly simple change)
2) We didn't have a backslash at the end of the line before the C program:

``` shell
CC_CHECK_FLAG_APPEND([with_cflags], [CFLAGS], [-Werror=shadow], [\
```

It looks like that backslash is making it into the `configure` script. Not sure if it actually makes it into any C sources, since the shell might be stripping it before creating the actual file, but I still think a blank newline would have been less harmful.

Planning to rework the patch with these modifications before this (or something like it) gets submitted.

**Comment by utezduyar** [comment]
@filbranden Nothing in the log saying testing -Werror=shadow. Also the program compiles fine.

```
umuttl@lnxumuttl:systemd$ cat umut.c 
#include <unistd.h>
int main(void) {
        int unlink = 7;
        return 0;
}

umuttl@lnxumuttl:systemd$ mipsisa32r2el-axis-linux-gnu-gcc -Werror=shadow umut.c && echo $?
0
```

**Comment by filbranden** [comment]
Hi @utezduyar perhaps try the following snippet which more closely matches what the real build is bumping into?

``` c
#include <time.h>
#include <inttypes.h>
typedef uint64_t usec_t;
usec_t now(clockid_t clock);
int main(void) {
        struct timespec now;
        return 0;
}
```

When I compile it with gcc 4.6 I do get the warning:

```
$ gcc-4.6 -c -Werror=shadow shadow-test.c
shadow-test.c: In function 'main':
shadow-test.c:6:25: error: declaration of 'now' shadows a global declaration [-Werror=shadow]
shadow-test.c:4:8: error: shadowed declaration is here [-Werror=shadow]
cc1: some warnings being treated as errors
```

Not so with a more recent compiler...

Regarding `-Werror=implicit-function-declaration` we can also look at that, all we need is a relevant snippet that fails in your compiler but succeeds in a more recent one. (Or perhaps it's some header files with the problem?)

Cheers!
Filipe

**Comment by utezduyar** [comment]
This snippet looks more OK.

```
umuttl@lnxumuttl:q7436.lfp.back.from.vacation.2015.09.03.10.00$ cat umut.c 
#include <time.h>
#include <inttypes.h>
typedef uint64_t usec_t;
usec_t now(clockid_t clock);
int main(void) {
        struct timespec now;
        return 0;
}
umuttl@lnxumuttl:q7436.lfp.back.from.vacation.2015.09.03.10.00$ mipsisa32r2el-axis-linux-gnu-gcc -c -Werror=shadow umut.c 
umut.c: In function 'main':
umut.c:6:25: error: declaration of 'now' shadows a global declaration [-Werror=shadow]
umut.c:4:8: error: shadowed declaration is here [-Werror=shadow]
cc1: some warnings being treated as errors
```

**Comment by dvdhrm** [comment]
@filbranden Care to submit v2 with the fixed program?

**Comment by filbranden** [comment]
Sorry for the delay... Done in #1341, please take a look at that one. Thanks!

**Pull request closed without merging**
