### PR TITLE
boot: exclude the trailing padding from initrd size in initrd_prepare()

### PR DESCRIPTION
**Pull request by keszybz**
This is a follow-up for f8fa4222c9ac3e74e91c64e25e9532c99559cf99 (boot: Make initrd_prepare() semantically equivalent to combine_initrds()). That commit changed the way that the initrd is prepared, but it also effectively rounded up the size to a multiple of 4. In [1], the users report that the extra 0 results in the calculated hash being different. Let's try to avoid changing the hash calculation results in that case by not including the last pad in the reported size.

Fixes https://github.com/systemd/systemd/issues/35439. The other changes to the way the initrd is constructed are kept, so hopefully the original issue with booting in qemu is not recreated.

[1] https://bugzilla.suse.com/show_bug.cgi?id=1233752

### CODE REVIEW

**Comment by bluca** [comment]
Do we need corresponding changes in ukify/sd-measure?

**Comment by DaanDeMeyer** [comment]
We should be explicit here about what we do with UKIs. We do padding there as well and this doesn't touch that. This might be intended to keep compat but we should explicitily mention that in the commit message.

**Comment by keszybz** [comment]
OK, after a long detour into mkosi configs, I tested boot with this, and it seems to work as expected. Update the commit message, no other changes.

**Comment by yuwata** [comment]
commit title: exlude -> exclude

**Review by yuwata — APPROVED** [review]
LGTM.

**Comment by keszybz** [comment]
mkosi/ci arch: `93/93 systemd:integration-tests / TEST-25-IMPORT                                                TIMEOUT        1800.27s   killed by signal 15 SIGTERM`
mkosi/ci fedora rawhide: `libsepol.policydb_read: policydb version 34 does not match my version range 15-33`
mkosi/ci opensuse: `/var/tmp/rpm-tmp.dEIjH5: line 1: /usr/sbin/sysusers2shadow: No such file or directory`
noble/arm64:
```
 3355s update-initramfs: Generating /boot/initrd.img-6.8.0-49-generic
3355s W: No lz4 in /usr/bin:/sbin:/bin, using gzip
3805s autopkgtest-virt-ssh [22:36:04]: ------- nova console-log b9569add-eada-4ce2-8b6e-42cd2f2728f4 (adt-noble-arm64-systemd-upstream-20241206-172638-juju-7f2275-prod-proposed-migration-environment-20-fddb5f22-2ab3-4635-b292-412a3f92ed19) ------
3805s ERROR (CommandError): No server with a name or ID of 'b9569add-eada-4ce2-8b6e-42cd2f2728f4' exists.
3805s ---------------------------------------------------
3805s ------- nova show b9569add-eada-4ce2-8b6e-42cd2f2728f4 (adt-noble-arm64-systemd-upstream-20241206-172638-juju-7f2275-prod-proposed-migration-environment-20-fddb5f22-2ab3-4635-b292-412a3f92ed19) ------
3805s ERROR (CommandError): No server with a name or ID of 'b9569add-eada-4ce2-8b6e-42cd2f2728f4' exists.
3805s ---------------------------------------------------
3805s 
3810s nova [W] Using flock in prodstack6-arm64
3810s Creating nova instance adt-noble-arm64-systemd-upstream-20241206-172638-juju-7f2275-prod-proposed-migration-environment-20-fddb5f22-2ab3-4635-b292-412a3f92ed19 from image adt/ubuntu-noble-arm64-server-20241206.img (UUID 025f8169-829a-4383-957c-8f13fe70f488)...
3810s ERROR (CommandError): Unable to delete the specified server(s).
3810s autopkgtest [22:36:09]: ERROR: testbed failure: testbed auxverb failed with exit code 255
```
noble/ppc64el:
```
2534s DEBUG (session:936) GET call to compute for https://nova.ps6.canonical.com:8774/v2.1/flavors?is_public=None used request id req-330b9b73-7116-45cf-a56f-c1e747fde233
2534s DEBUG (session:517) REQ: curl -g -i -X GET https://nova.ps6.canonical.com:8774/v2.1/flavors/f40b2dbc-5d69-40b0-a9fc-71c32de93ca3 -H "Accept: application/json" -H "OpenStack-API-Version: compute 2.87" -H "User-Agent: python-novaclient"ERROR (CommandError): Unable to delete the specified server(s).
2534s Unexpected error:
2534s Traceback (most recent call last):
2534s   File "/home/ubuntu/autopkgtest/lib/VirtSubproc.py", line 833, in mainloop
2534s     command()
2534s   File "/home/ubuntu/autopkgtest/lib/VirtSubproc.py", line 762, in command
2534s     r = f(c, ce)
2534s   File "/home/ubuntu/autopkgtest/lib/VirtSubproc.py", line 395, in cmd_revert
2534s     caller.hook_revert()
2534s   File "/home/ubuntu/autopkgtest/virt/autopkgtest-virt-ssh", line 433, in hook_revert
2534s     host_setup('revert')
2534s   File "/home/ubuntu/autopkgtest/virt/autopkgtest-virt-ssh", line 252, in host_setup
2534s     execute_setup_script(command)
2534s   File "/home/ubuntu/autopkgtest/virt/autopkgtest-virt-ssh", line 209, in execute_setup_script
2534s     sys.stderr.write(err)
2534s BlockingIOError: [Errno 11] write could not complete without blocking
2534s autopkgtest [20:01:41]: ERROR: testbed failure: unexpected eof from the testbed
```

Those don't look related.

**Pull request merged**
