### PR TITLE
semaphore: switch back to the master branch

### PR DESCRIPTION
**Pull request by evverx**

### CODE REVIEW

**Comment by evverx** [comment]
@mbiebl before I start changing the Ubuntu CI webhooks, could you merge https://salsa.debian.org/systemd-team/systemd/merge_requests/43 and move that commit to the master branch so that we can pass `--werror` to `meson`? cc @ddstreet

**Comment by evverx** [comment]
In the meantime, I've just pointed Ubuntu CI to the master branch as well. Let's see how it goes.

Interestingly, it seems Ubuntu CI didn't cancel the jobs run against the "experimental" branch after I switched it to the "master" branch and force-pushed the code so currently the tests are running against both branches in parallel. @iainlane I'm wondering if it's expected.

**Comment by mbiebl** [comment]
thanks @evverx

**Comment by mbiebl** [comment]
Is merging https://salsa.debian.org/systemd-team/systemd/merge_requests/43 a prerequisite for switching back the webhooks?

**Comment by evverx** [comment]
No, it isn't. I already pointed Ubuntu CI to the right branch. I just wanted to fix outstanding issues in one fell swoop while I was editing the webhooks.

**Comment by mbiebl** [comment]
I finally got around merging https://salsa.debian.org/systemd-team/systemd/merge_requests/43 
Sorry for the delay.

**Comment by evverx** [comment]
@mbiebl thank you! `--werror` is on. Once it's more or less settled I'll try to unleash the "slow" and "unsafe" tests on Ubuntu CI to see whether it can withstand them.

@ddstreet I'm wondering if bionic-ppc64el is ready to accept PRs. I think we could start by just running the unit tests there if it's possible.

**Comment by evverx** [comment]
Apparently it isn't possible to pass `--werror -Dslow-tests=true` to Ubuntu CI via the webhooks. It complains that
> You submitted an invalid request: Invalid environment variable format "CONFFLAGS_UPSTREAM='--werror -Dslow-tests=true'"

@ddstreet @iainlane I'm wondering how exactly environment variables with spaces and equal signs can be passed to Ubuntu CI?

**Comment by evverx** [comment]
@ddstreet I think `test_bad_env` should probably be updated as well:
```diff
diff --git a/webcontrol/request/tests/test_submit.py b/webcontrol/request/tests/test_submit.py
index bae9185..f514d9c 100644
--- a/webcontrol/request/tests/test_submit.py
+++ b/webcontrol/request/tests/test_submit.py
@@ -376,7 +376,7 @@ class GitRequestValidationTests(SubmitTestBase):
         is_valid_ppa.return_value = True
         with self.assertRaises(ValueError) as cme:
             self.submit.validate_git_request('testy', 'C51', 'ab',
-                                             env=['foo=1', 'bar=1\n='],
+                                             env=['foo=1', 'CONFFLAGS_UPSTREAM=--werror -Dslow-tests=true', 'bar=1\n='],
                                              **{'build-git': 'https://x.com/proj',
                                                 'ppas': ['a/b']})
         self.assertIn('Invalid environment', str(cme.exception))
```

If the PR is merged, I'd appreciate it if you could pass `--werror -Dtests=unsafe -Dslow-tests=true` somewhere on a local instance of Ubuntu CI to see how it goes. It's going to be much faster because before rolling out something like that globally so as not to mess with other people's PRs I wait until the activity here is minimal, edit the webhooks and restart failed requests if something goes wrong. Another option would be to keep files containing environment variables Ubuntu CI would read before running the tests in the systemd repository. This way it would be possible to avoid rolling out untested changes and experiment with Ubuntu CI without having access to the webhooks as one way or another we do everywhere else.

**Comment by ddstreet** [comment]
> I'd appreciate it if you could pass --werror -Dtests=unsafe -Dslow-tests=true somewhere on a local instance of Ubuntu CI to see how it goes. 

that definitely makes sense - however, the code in autopkgtest-cloud has a special code path for requests from github, so in order to test that code path I have to either:
1) set up webhooks from my ddstreet/systemd fork and get my webhooks secret credentials added to the autopkgtest.ubuntu.com server, so i can send requests myself from github
2) set up a local instance of autopkgtest-cloud with a public IP addr, so I can use that for testing with my ddstreet/systemd fork

The fastest way is 1, but I have to defer to @iainlane if it makes sense to add a github key for me to test with.

I do want to do 2, and set up a local autopkgtest-cloud system for testing/devel; but I spent a day or two on it and didn't quite get it working.  I'll try again next week and try to get some help figuring it out.

> Another option would be to keep files containing environment variables Ubuntu CI would read before running the tests in the systemd repository.

This works as well - there already are several places that check for TEST_UPSTREAM, so adding another check to read an upstream-provided env var file seems logical to me.

**Comment by evverx** [comment]
@ddstreet got it. Thank you!

In the meantime, I turned on the slow tests  once the PR on launchpad had been merged. Among other things it helped to partly bring the fuzzing infrastructure to architectures different from x86_64 so it's safe to say that the systemd repository is more or less ready to run the regression tests there without kludges like the ones OSS-Fuzz uses. I hope I'll get round to https://github.com/systemd/systemd/pull/12608 to set up continuous fuzzing as well.

**Comment by ddstreet** [comment]
@evverx I'm still working on setting up a local test/devel env for Ubuntu CI, I haven't forgot about that.

I think you've already set the webhooks to pass 'CONFFLAGS_UPSTREAM=--werror -Dslow-tests=true', right?  So for this change, everything is ok; but as I said I'll get a test env setup to test future chanages (and work on devel to make it better, e.g. to allow updated PR's to cancel jobs in progress).

**Pull request merged**
