### PR TITLE
barrier: fix typo in barrier cleanup function call

### PR DESCRIPTION
**Pull request by ImanSeyed**

### CODE REVIEW

**Comment by yuwata** [comment]
No, that's correct.

**Comment by ImanSeyed** [comment]
@yuwata  How that's correct if [there is no function called `barrier_destroyp()`](https://github.com/search?q=repo%3Asystemd%2Fsystemd%20barrier_destroyp&type=code)?

**Comment by mrc0mmand** [comment]
> @yuwata How that's correct when [there is no function called `barrier_destroyp()`](https://github.com/search?q=repo%3Asystemd%2Fsystemd%20barrier_destroyp&type=code)?

Because the suffixed function is defined through a macro https://github.com/systemd/systemd/blob/57ffa99daae30375ec72a4c998d9c5b74a1f9023/src/shared/barrier.h#L42.

**Comment by yuwata** [comment]
It's defind by `DEFINE_TRIVIAL_CLEANUP_FUNC()` macro or so. We have bunch of such cleanup functions, freep, strv_freep, sd_bus_unrefp, etc, etc.

**Comment by ImanSeyed** [comment]
Oh, I see. The line `static inline void func##p(type *p)` escaped my notice.

**Pull request closed without merging**
