### PR TITLE
A variety of sd-event, sd-login and cgroup fixes

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by dvdhrm** [comment]
```
ERROR: files left in build directory after distclean:
./man/sd_peer_get_cgroup.3
./man/sd_pid_get_cgroup.3
```

Is that related? If not, just request a rebuild.

**Comment by poettering** [comment]
I need to fix that distclean thing, will push an update soon

**Comment by poettering** [comment]
I force-pushed a fixed version now. Let's see if semaphore likes it.

**Comment by poettering** [comment]
Hmm, how do we get samphore to retry this?

**Comment by dvdhrm** [comment]
You can't. Force-push disables semaphore.

**Comment by poettering** [comment]
Oh, really? gah... why that?

**Pull request merged**
