### PR TITLE
udev: modernize style in path_id

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
artful-s390x — `could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)`

**Comment by keszybz** [comment]
I'll restart amd64 and s390x tests.

**Comment by poettering** [comment]
lgtm

**Comment by poettering** [comment]
ci failed...

**Comment by keszybz** [comment]
Not yet, it's still running.

**Comment by keszybz** [comment]
```
TEST RUN: Basic systemd setup
+ /usr/bin/qemu-system-x86_64 -smp 1 -net none -m 512M -nographic -kernel /boot/vmlinuz-4.13.0-17-generic -drive format=raw,cache=unsafe,file=/var/tmp/systemd-test.BCbmbS/rootdisk.img -initrd /boot/initrd.img-4.13.0-17-generic -machine accel=kvm -enable-kvm -cpu host -append 'ro root=/dev/sda1 raid=noautodetect loglevel=2 init=/lib/systemd/systemd console=ttyS0 selinux=0   '
KVM: entry failed, hardware error 0x0
EAX=00000000 EBX=00000000 ECX=00000000 EDX=000306a9
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=0000fff0 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 0000ffff 00009300
CS =f000 ffff0000 0000ffff 00009b00
SS =0000 00000000 0000ffff 00009300
DS =0000 00000000 0000ffff 00009300
FS =0000 00000000 0000ffff 00009300
GS =0000 00000000 0000ffff 00009300
LDT=0000 00000000 0000ffff 00008200
TR =0000 00000000 0000ffff 00008b00
GDT=     00000000 0000ffff
IDT=     00000000 0000ffff
CR0=60000010 CR2=00000000 CR3=00000000 CR4=00000000
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000000
Code=d8 66 e8 d8 a2 ff ff 66 5b 66 83 c4 08 66 5b 66 5e 66 c3 90 <ea> 5b e0 00 f0 30 36 2f 32 33 2f 39 39 00 fc 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
autopkgtest [19:53:07]: ERROR: timed out on command "su -s /bin/bash root -c set -e; export USER=`id -nu`; . /etc/profile >/dev/null 2>&1 || true;  . ~/.profile >/dev/null 2>&1 || true; buildtree="/tmp/autopkgtest.uUYGPH/build.dMk/debian"; mkdir -p -m 1777 -- "/tmp/autopkgtest.uUYGPH/upstream-artifacts"; export AUTOPKGTEST_ARTIFACTS="/tmp/autopkgtest.uUYGPH/upstream-artifacts"; export ADT_ARTIFACTS="$AUTOPKGTEST_ARTIFACTS"; mkdir -p -m 755 "/tmp/autopkgtest.uUYGPH/autopkgtest_tmp"; export AUTOPKGTEST_TMP="/tmp/autopkgtest.uUYGPH/autopkgtest_tmp"; export ADTTMP="$AUTOPKGTEST_TMP"; export DEBIAN_FRONTEND=noninteractive; export LANG=C.UTF-8; export DEB_BUILD_OPTIONS=parallel=1; unset LANGUAGE LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE   LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS   LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL;rm -f /tmp/autopkgtest_script_pid; set -C; echo $$ > /tmp/autopkgtest_script_pid; set +C; trap "rm -f /tmp/autopkgtest_script_pid" EXIT INT QUIT PIPE; cd "$buildtree"; export AUTOPKGTEST_NORMAL_USER=ubuntu; export ADT_NORMAL_USER=ubuntu; export 'CFLAGS=-O0'; export 'DEB_BUILD_PROFILES=noudeb'; export 'TEST_UPSTREAM=1'; export 'UPSTREAM_PULL_REQUEST=7415'; export 'GITHUB_STATUSES_URL=https://api.github.com/repos/systemd/systemd/statuses/a6856129ec0b72c15788bdb56f6b1584cbea07bd'; chmod +x /tmp/autopkgtest.uUYGPH/build.dMk/debian/debian/tests/upstream; touch /tmp/autopkgtest.uUYGPH/upstream-stdout /tmp/autopkgtest.uUYGPH/upstream-stderr; /tmp/autopkgtest.uUYGPH/build.dMk/debian/debian/tests/upstream 2> >(tee -a /tmp/autopkgtest.uUYGPH/upstream-stderr >&2) > >(tee -a /tmp/autopkgtest.uUYGPH/upstream-stdout);" (kind: test)
autopkgtest [19:53:08]: test upstream: -----------------------]
autopkgtest [19:53:08]: test upstream:  - - - - - - - - - - results - - - - - - - - - -
upstream             FAIL timed out
```

I'll restart amd64 once more.

**Comment by poettering** [comment]
Merging. The CI failure is caused by #7445, and things lookg good otherwise, and the CI passed on artful-amd64, which should be enough

**Pull request merged**
