### PR TITLE
Add LXD VM Support

### PR DESCRIPTION
**Pull request by bryanyork**
LXD is detected as KVM which makes it hard to target lxd-agent service support in other packages. See https://github.com/home-assistant/operating-system/pull/2145

This is tested working in an LXD VM. (Not container)

### CODE REVIEW

**Comment by stgraber** [comment]
LXD isn't particularly special here, not any more special than Openstack or Kubevirt's own use of kvm.
Having LXD detected as `lxd` rather than `kvm` would break any unit which currently relies on LXD being detected as `kvm`.

If you specifically must detect LXD for a particular job, I'd recommend:
```
ConditionPathExists=/dev/virtio-ports/org.linuxcontainers.lxd
```

I think it may be useful to eventually have a way to differentiate the various kvm flavors (openstack, libvirt, kubevirt, lxd, ...) but such an addition should be made backward compatible so that they all still will satisfy the `kvm` condition while also satisfying a more specific condition.

**Comment by poettering** [comment]
I am not opposed to this, but would like @stgraber's take on this. Stephane, what would you prefer? if  `ConditionVirtualization=kvm` or if `ConditioVirtualization=lxd` when systemd is running in an lxd vm should hold? do you consider lxd a runner for kvm/qemu vms, or is kvm/qemu just an implementation detail?

(background: systemd, for historical reasons, reports `kvm` for `kvm+qemu`, and `qemu` for non-qeu.

**Comment by poettering** [comment]
bingo, our comments crossed in mid air ;-)

**Comment by poettering** [comment]
so we explicit detect OpenStack and Kubevirt as kvm (via dmi check, since the cpuid check doesn't work on non-x86). So we indeed should handle lxd the same way I guess, and explicitly map it to kvm.

so this pr sounds wrong then. But we might want to add a DMI check for lxd and make it point to kvm. Does LXD set a DMI vendor string on non-x86, the way openstack/kubevirt do it?

**Comment by stgraber** [comment]
LXD currently only sets the smbios information (which lands in DMI) on UEFI platforms, so that's x86_64 and aarch64 currently.
This is effectively done through a simple `-smbios type=2,manufacturer=Canonical Ltd., product=LXD`.

The other supported architectures for virtual machines are ppc64le and s390x, neither of those currently expose such an identifier to the guest.

**Comment by bryanyork** [comment]
@stgraber Thanks for the context. This is to target lxd-agent to only run on LXD VM's. HAOS was running an old version of systemd, as this was previously detected as qemu. It looks like newer versions have this fixed but we have not yet backported. I'll work on a temporary patch for HAOS then.

**Comment by bryanyork** [comment]
@poettering would we be able to get a backport to systemd-stable for the v250 series so that LXD is properly detected as KVM here? PR's #22945 #22952 look to have added/modified this.

**Comment by poettering** [comment]
@bryanyork file an RFE on the systemd-stable repo for that.

**Comment by poettering** [comment]
@stgraber i am curious: if you run "systemd-detect-virt" in a lxd vm on aarch64, does it correctly identify this as "kvm"? if not, we should add a dmi test, like we have for openstack/kubevirt

**Pull request closed without merging**
