### PR TITLE
network: do not create default route when DefaultRouteOnDevice=no

### LINKED ISSUE #13418: Unexpected "default" route to a container
I have a systemd-nspawn container with private networking. systemd-networkd on the cost creates a route:
```console
$ ip r
default via 192.168.43.1 dev wlan0 proto dhcp src 192.168.43.71 metric 1024 
default dev ve-rawhide proto static scope link metric 2048            <-------------------------------------
169.254.0.0/16 dev ve-rawhide proto kernel scope link src 169.254.136.213 
192.168.43.0/24 dev wlan0 proto kernel scope link src 192.168.43.71 
192.168.43.1 dev wlan0 proto dhcp scope link src 192.168.43.71 metric 1024 
192.168.58.176/28 dev ve-rawhide proto kernel scope link src 192.168.58.177 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 
```

The cost (2048) is pretty high, so most of the time the other routes win, but not
always. In particular, NetworkManager sometimes creates wireless routes with
higher cost. I don't think the default route should be created at all.

```console
$ networkctl status ve-rawhide
● 26: ve-rawhide                                                        
             Link File: /usr/lib/systemd/network/99-default.link        
          Network File: /usr/lib/systemd/network/80-container-ve.network
                  Type: ether                                           
                 State: routable (configured) 
                Driver: veth                                            
            HW Address: 0a:e8:42:0f:39:d8                               
                   MTU: 1500 (min: 68, max: 65535)                      
  Queue Length (Tx/Rx): 1/1                                             
      Auto negotiation: no                                              
                 Speed: 10Gbps                                          
                Duplex: full                                            
                  Port: tp                                              
               Address: 192.168.58.177                                  
                        169.254.136.213                                 
                        fe80::8e8:42ff:fe0f:39d8                        
          Connected To: rawhide on port host0                           
```

(I don't have NetworkManager running.)

### PR DESCRIPTION
**Pull request by yuwata**
When nspawn container with private network starts, `networkd` creates
the default route for the interface. The route may cause problem on
the host side, and it can be created with `DefaultRouteOnDevice=` now.
Hence, this makes `networkd` not create the route implicitly any more.

Closes #13418.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @keszybz

**Comment by ssahani** [comment]
This looks suspicious  already . Why you chasing the code for Networkd ?

**Comment by keszybz** [comment]
> This looks suspicious already . Why you changing the code for Networkd ?

@ssahani did you see the bug report? The issue is pretty clear, and the commit description also describes the issue quite well.

**Comment by ssahani** [comment]
@keszybz The Link local route is created because the of link local addressing. 
```
169.254.0.0/16 dev ve-rawhide proto kernel scope link src 169.254.136.213 
```
Would not ```LinkLocalAddresssing=no``` stop creating the address and the route itself.

Now Adding ```LinkLocalAddressing=``` adds it's routes by default and it should . This commits stops that and user has to know what is ```DefaultRouteOnDevice=``` and has to turn on this .

**Comment by yuwata** [comment]
Of course, we need to advertise this change in the NEWS file.

The problem is that currently there is no way to stop creating the default route with LinkLocalAddressing=yes|ipv4. Or, in other words, now LinkLocalAddressing=yes|ipv4 implies DefaultRouteOnLink=yes. I think each setting should have single effect if possible, and should not imply other orthogonal settings.

**Comment by ssahani** [comment]
> Of course, we need to advertise this change in the NEWS file.

This breaks the existing `LinkLocalAddressing` and does not maintain any backward compatibility which is stable.  

> The problem is that currently there is no way to stop creating the default route with 

How the system will talk the network if it does not have the route itself. 

>LinkLocalAddressing=yes|ipv4`. Or, in other words, now `LinkLocalAddressing=yes|ipv4` implies `DefaultRouteOnLink=yes`.

Don't it feel odd ? . Right now it has the right implementation  which makes sense like `address->routes`  Why user has to turn on this  . In a private network the container does not have to talk to outside world hence I am trying to figure out why link local address is needed not routes which can be turned off by setting no and it has other addresses .  Again LinkLocalAddresses are set when network interfaces when no external, stateful mechanism of address configuration exists in this case there is a address.

 >I think each setting should have single effect if possible, and should not imply other orthogonal settings.

Yes this is not required . If needed we can have an another setting `LinkLocalAddressRoute=` defaults to true but I am not sure why even this is required.

**Comment by yuwata** [comment]
Yeah, backward compatibility is a big concern... I will try to fix the issue in another way.

**Comment by yuwata** [comment]
@ssahani and @keszybz Updated. PTAL. 
In the revised version, the behavior of `LinkLocalAddressing=` is not changed when `DefaultRouteOnDevice=` is not set. So, Only when `DefaultRouteOnDevice=no`, `LinkLocalAddressing=yes` does not create the default route.

**Comment by yuwata** [comment]
@ssahani and @keszybz ping?

**Comment by ssahani** [comment]
I would request @keszybz to take a look .

**Comment by keszybz** [comment]
I read RFC3927 again, and I still don't understand why we'd want to keep existing behaviour. LL addressing is mainly a means to provide addresses to hosts in a LAN with no gateway. RFC3927  section 2.6.2. describes a mode where packets are sent to global addresses from the LL non-routable address, but that can only work in very special circumstances. I guess we can provide such a mode, but it should only be opt-in. We already have DefaultRouteOnDevice= to enable this.

With the first version of @yuwata's patch, that simply drops the creation of the default route, I get exactly the expected behaviour: on the host I don't get double routes on every device, and on the container side, I get just the one route `169.254.0.0/16 dev host0 proto kernel scope link src 169.254.…`. Communication using the link-local addreses works exactly as expected.

All of the complications added to the second version of this PR are IMHO not necessary. I'll pick the patches I think should go in and resubmit them as separate PR to get the CI going.

**Comment by keszybz** [comment]
```diff
-            Defaults to false. This is useful when creating routes on point-to-point interfaces.
+            Defaults to false when IPv4 link local addressing is disabled, and true when it is enabled.
+            This is useful when creating routes on point-to-point interfaces.
```
Right. Even this description shows the issue: LL does not mean point-to-point. There is no reason to conflate the two.

**Pull request closed without merging**
