### PR TITLE
export sd_device_get_action() API + more

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by bluca** [comment]
Ci is unhappy:

```
../src/udev/udev-event.c:834:37: error: expression which evaluates to zero treated as a null pointer constant of type 'const char *' [-Werror,-Wnon-literal-null-conversion]
        if (!device_for_action(dev, DEVICE_ACTION_ADD))
                                    ^~~~~~~~~~~~~~~~~
../src/udev/udev-event.c:907:49: error: expression which evaluates to zero treated as a null pointer constant of type 'const char *' [-Werror,-Wnon-literal-null-conversion]
        bool apply_mac = device_for_action(dev, DEVICE_ACTION_ADD);
```

**Comment by poettering** [comment]
weird that i didn't catch this locally, earlier. pushed with a fix

**Comment by keszybz** [comment]
```
 ../src/udev/udevd.c:395:37: error: expression which evaluates to zero treated as a null pointer constant of type 'const char *' [-Werror,-Wnon-literal-null-conversion]
        if (!device_for_action(dev, DEVICE_ACTION_ADD))
                                    ^~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by keszybz** [comment]
> This new API wraps the existing device_get_action() function, but
returns a string instead of the low-level enum. Why return a string
instead of the enum? Simply because C enums are not a great concept in
public APIs, since adding more values to it might cause its size to
change. This enum is one that might very likely get more values sooner
or later, hence better export this string.

Sorry, I don't buy this at all. Just define the type as `uint64_t` and the issue is gone.
This api isn't very widely used, so the its effect is not going to be very wide either way,
but I wouldn't like to use such an antipattern in public systemd headers...

**Comment by poettering** [comment]
antipattern? and uint64_t is not?

**Comment by keszybz** [comment]
> antipattern?

A matter of opinion ;) 

> and `uint64_t` is not?

What would be wrong with it? It's a well-defined thing.

**Comment by yuwata** [comment]
Please rebase.

**Comment by poettering** [comment]
@keszybz any chance you can bless #18557 so that i can rework this one accordingly?

**Comment by keszybz** [comment]
> antipattern? and uint64_t is not?

FWIW, after sleeping on this a bit, I'd like to refine my review a bit. I think the approach with strings is OK for things which are mutually exclusive and must and always will be just an enumeration and are not used in hot paths.

As a particular example, `int flags` in `open(2)` is done properly: the flags are not mutually exclusive, and the bitmask makes it easy to combine and test them in arbitrary ways. We can compare that with the `fopen(3)` interface which has `const char *mode`, and is worse in every regard. We end up with stuff like "a+cemx" which is not clear at all. And when the arg is passed through functions, and e.g. we want to append one of those flags, this becomes messy, since we potentially need to allocate just to store an extra byte. I was mostly thinking about this case when I said "antipattern".

Another consideration is how the client will use this information. In C, dispatch on an enum is well-supported with `switch`. But dispatch on a string is less convenient: we need to do repeated `strcmp`s, with much less allowance ffor the compiler to optimize things. So I don't think we should use strings to specify event type, because it makes client code slower and uglier.

**Comment by poettering** [comment]
Force pushed a new version, now on top of #18557. Hopefully less contentious. PTAL!

**Comment by poettering** [comment]
centos CI failure appears unrelated (network connectivity issues)

**Comment by yuwata** [comment]
LGTM.

**Comment by keszybz** [comment]
LGTM too.

**Pull request merged**
