### PR TITLE
Move activate to bin, extend --fdnames functionality

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, wouldn't it make sense to automatically multiply the fdnames to the number of fds set if only one is specified? i.e. add a mode that is compatbile with the current behaviour of --fdname=, so that people can choose if they want to use separate names for each fd, or the same for all?

I am fine with promoting the tool to /usr/bin. But, I wonder if we should rename it at the same time? systemd-activate sounds so overly generic. Maybe call it "systemd-activate-test", or "systemd-test-activation" or something like that? (just an idea...)

Also, the man page includes a reference to the old path in the `<cmdsynopsis>` section, this should be fixed, too.

**Comment by keszybz** [comment]
>  i.e. add a mode that is compatbile with the current behaviour of --fdname

Hm, maybe. My version gives you a bit more flexibility, but maybe I'm overcomplicating this.

I think the current name is OK. it _can_ be used to do some crazy things, not just testing. And there're quite a few references to it on the net (I checked when I was reviewing your pull request to add `--inetd` mode; nobody uses `systemd-activate -a`.)

I'll fix the man page.

**Comment by keszybz** [comment]
Unless we rename it to `socket-activate`. That's a nice name.

**Comment by poettering** [comment]
> > i.e. add a mode that is compatbile with the current behaviour of --fdname
> 
> Hm, maybe. My version gives you a bit more flexibility, but maybe I'm overcomplicating this.

Well, I am not saying to remove your version. I am just saying to make it compatible with the old version. i.e. that this:

```
systemd-activate --fdname=foo:foo:foo -l 4711 -l 4712 -l 4713 …
```

and this:

```
systemd-activate --fdname=foo -l 4711 -l 4712 -l 4713 …
```

should both be accepted as valid and equivalent. In the first case a separate name is specified for each configured socket to listen on. In the second case, only one name is specified, which is taken as hint to use it for each of the three names.

And I'd also say that this:

```
systemd-activate --fdname=foo:foo -l 4711 -l 4712 -l 4713 … 
```

should not be accepted, because the number of specified names neither matches the number of sockets, nor is 1.

I think this way we provide both flexibility for those who want to define individual names for each fd and the simplicity for those who are fine with one name for all fds.

**Comment by poettering** [comment]
> Unless we rename it to socket-activate. That's a nice name.

Yeah, I'd prefer that.

**Comment by poettering** [comment]
I think renaming the thing is OK. After all, it was in the private directory so far, and it's also a developer tool (well, primarily), and I think that developer compat is much less of a requirement than user compat is.

Oh, and preparing a reminder about this change in NEWS right-away would be nice to have in the patch too!

**Comment by keszybz** [comment]
I implemented suggested changes, except that if the specified number of names does not match, only a warning is emitted, not an error.

**Comment by keszybz** [comment]
Rebased because of file conflict.

**Comment by poettering** [comment]
oh. you dropped the "systemd-" suffix too? I'd be careful with that. I mean, we only really drop the prefix for primary interfaces (i.e. the various *ctl tools), but this isn't really a primary interface I would say. Yes, "systemd-socket-activate" is long and stuff, but I think that's OK given this still is a developer tool.

Looks fine otherwise.

**Comment by keszybz** [comment]
Force pushed with `socket-activate` → `systemd-socket-activate`.

**Pull request merged**
