### PR TITLE
Misc resolved cache fixes

### PR DESCRIPTION
**Pull request by teg**

### CODE REVIEW

**Comment by poettering** [comment]
I included something resembling the first patch also to #2129, btw, because I touched some code this involved, and didnt want to update the stuff if it needs to go anyway...

What's the state of the rest of this patch? I think you want to update once more and and resubmit?

**Comment by poettering** [comment]
Needs  rebase now that #2129 got merged.

**Comment by teg** [comment]
Rebased and (accidentally) force-pushed.

**Comment by poettering** [comment]
@teg i will fix the issue i pointed out above.

**Pull request merged**
