### PR TITLE
core: verify WorkingDirectory= is outside of API VFS only under mount namespacing

### LINKED ISSUE #33361: Relax WorkingDirectory= restrictions regarding /proc/, /sys/ or /dev/ in user services
After #31210, `WorkingDirectory=` may not be below `/proc/`, `/sys/` or `/dev/`. It is understandable as a hardening measure, but it hurts user experience in graphical environments.

Now we can't even open a terminal or open files in a text editor from that directories. Because app slices obviously want to start in the respective working directory.

It is already starting to be reported as a bug: https://bugs.kde.org/show_bug.cgi?id=488177

### PR DESCRIPTION
**Pull request by YHNdnzj**
Fixes #33361

### CODE REVIEW

**Comment by poettering** [comment]
hmm, is this the right approach?

I was thinking we should instead bind this to whether mountns based sandboxing is used or not. Wouldn't that be simpler and safer?

**Comment by YHNdnzj** [comment]
> hmm, is this the right approach?
> 
> I was thinking we should instead bind this to whether mountns based sandboxing is used or not. Wouldn't that be simpler and safer?

Hmm? I don't grok this at all? DEs/file managers certainly do not run under mountns?

**Comment by YHNdnzj** [comment]
> > > 
> > 
> > Hmm? I don't grok this at all? DEs/file managers certainly do not run under mountns?
> 
> precisely! hence we don't need to protect them from pinned directory accesses, they run with full perms anyway.
> 
> i.e. the safety check exists so that some dir in /proc/ as cwd doesn't make part of the mountns sandbox ineffective. But if there is no mountns sandbox to apply anyway, then this protection is unnecessary.
> 

Ah, now I understand (the way you modified the title of the original issue drove me to the existing approach), will update.

**Comment by YHNdnzj** [comment]
Updated with the suggested approach, PTAL.

**Review by bluca — APPROVED** [review]

**Pull request merged**
