### PR TITLE
Revert "nspawn: remove unnecessary mount option parsing logic"

### PR DESCRIPTION
**Pull request by iaguis**
This reverts commit 72d967d.

Revert this because it broke the `norbind` option of the bind flags
because it does bind-mounts unconditionally recursive.

Let's bring the old logic back.

Also, add a test for this.

Fixes: #13170

### CODE REVIEW

**Comment by evverx** [comment]
@ddstreet @iainlane it seems Ubuntu CI has been unstable today in the sense that some requests (like the one that should have triggered `amd64` here) have timed out:
Screenshot 2019-07-24 at 18 55 44

Could you take a look?

**Comment by evverx** [comment]
In the meantime, I triggered bionic-amd64 manually here.

**Comment by ddstreet** [comment]
> @ddstreet @iainlane it seems Ubuntu CI has been unstable today in the sense that some requests (like the one that should have triggered `amd64` here) have timed out:
> Screenshot 2019-07-24 at 18 55 44
> 
> Could you take a look?

I don't have access to the lab where the Ubuntu CI runs, but there were (and apparently still are) problems in the lab I do have access to.  The Canonical infrastructure team is working on it; I don't think there is anything I'm able to do, although it seems like the production lab where Ubuntu CI runs is working better now.

**Comment by iainlane** [comment]
Sorry I'm at Debconf right now and so I don't have very good availability this week. I checked a couple of other recent PRs (https://github.com/systemd/systemd/pull/13176 and https://github.com/systemd/systemd/pull/13175) which seem to have gone OK - did this resolve itself?

**Comment by evverx** [comment]
@ddstreet @iainlane thank you. To judge from the logs the webhook triggering amd64 last failed at 18:36 yesterday and has been successful since then so it looks like Ubuntu CI is up and running now.

**Comment by yuwata** [comment]
`TEST-01-BASIC` failure is caused by #13141. Not related.

**Pull request merged**
