### PR TITLE
remove bus-proxyd

### PR DESCRIPTION
**Pull request by zonque**
As kdbus won't land in the anticipated way, the bus-proxy is not needed in
its current form. It can be resurrected at any time thanks to the history,
but for now, let's remove it from the sources. If we'll have a similar tool
in the future, it will look quite differently anyway.

Note that stdio-bridge is still available. It was restored from a version
prior to f252ff17, and refactored to make use of the current APIs.

### CODE REVIEW

**Comment by poettering** [comment]
This really needs some NEWS explanation, as this effectively is what kills kdbus in systemd. (can be a separate commit).

**Comment by zonque** [comment]
We can do that shortly before the next release, as we always do. This shouldn't hold back this PR, right?

**Comment by utezduyar** [comment]
We have been using this to dbus proxy to the product over network (just for testing purposes). Wouldn't it be better to strip of kdbus part and still keep the proxy?

**Comment by utezduyar** [comment]
Ah! I haven't read the PR message entirely. systemd-stdio-bridge is back.

**Pull request merged**
