### PR TITLE
Enable our units using presets in the usual fashion

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
lgtm. But this probably deserves some notice in NEWS, as it changes the effect of "ninja -C build install" quite a bit, as nothing is enabled then by default.

**Comment by mbiebl** [comment]
Fwiw, in Debian/Ubuntu, we remove the symlinks in `etc/systemd/system` that are created by `ninja install` anyway, as we enable the service dynamically in the maintainer scripts (so we can respect local admin changes). See https://salsa.debian.org/systemd-team/systemd/blob/master/debian/rules#L224

**Comment by keszybz** [comment]
I'll push an update to NEWS after CI passes. I don't want to push it now to avoid resetting the wait.

**Comment by jameshilliard** [comment]
I've attempted to restore the previous behavior for cross builds only in #12769 since this change breaks cross compilation.

**Pull request merged**
