### PR TITLE
fstab-generator: don't warn on "noauto" symlinks

### PR DESCRIPTION
**Pull request by karelzak**
The fstab-generator tries to canonicalize symlinks. It's strange when
unsuccessful canonicalization is reported as error if the fstab entry
is explicitly marked as "noauto". In this case users assume that
systemd will not try to be smart on the fstab entry. Note that user
cannot do anything more than use "noauto"...

The patch does not change the current behavior, but suppress the error
message for "noauto" only

Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=1537969

### CODE REVIEW

**Comment by poettering** [comment]
hmm, i think if we should downgrade the log message wholesale to LOG_DEBUG. If we can't canonicalize it we should just accept it, and proceed without complaints.

**Comment by sourcejedi** [comment]
That sounds sensible, then systemd would only raise an issue if you tried to activate the mount unit, as units are only supposed to be loaded on-demand...

The mount unit check (unit_fail_if_noncanonical()) takes a similar approach, if we get an error while checking for a symlink then we only log a debug message.

**Comment by poettering** [comment]
I have prepped my alternative fix as suggested in PR #8281. PTAL

**Comment by poettering** [comment]
Let's close this in favour of #8281

**Pull request closed without merging**
