### PR TITLE
ISSUE_TEMPLATE: Use a list for submission type so that it appears as a checkbox

### PR DESCRIPTION
**Pull request by daurnimator**

### CODE REVIEW

**Comment by keszybz** [comment]
Hm, maybe we can also get rid of the NOTEs. Reading them in every issue gets old quickly.

**Comment by daurnimator** [comment]
> Hm, maybe we can also get rid of the NOTEs. Reading them in every issue gets old quickly.

I'm happy to add that to this PR; or it can be a separate one, I don't mind.

**Comment by johannbg** [comment]
Just drop those templates altogether it was a mistake enabling them in the first place.

**Comment by poettering** [comment]
@keszybz i added the notes, because people weren't reading the contribution guidelines and posting bugs against old centos versions of systemd upstream. i'd rather see the notes in each issue, then have to close all those issues which always makes me feel a bit like a dick ;-)

**Comment by keszybz** [comment]
OK, I guess that the notices will have to stay for now. Maybe github will grow a feature to display them without them ending up in the actual post.

**Pull request merged**
