### PR TITLE
v256 stable batch up to ca10784ac1f846941d0137b3e3bc9f03bf2aa505

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by bluca** [comment]
Please also add 6fd3496cfd

**Comment by keszybz** [comment]
There are no commits which touch `src/network`, `src/libsystemd/sd-network`, or `test/test-network`. So I don't think this can be related.

**Comment by yuwata** [comment]
Yeah, please ignore them. If they hit so frequently, I will take a look.

**Comment by keszybz** [comment]
mkosi/ci (fedora 41) is the network test issue.
4f6d8ab0767e534553bfa130f39dbb07ebb804a4 says that radvd-2.20 is need to run the test. But F41 has 2.19, so probably the skipping of the test just doesn't work.

mkosi/ci (centos 10) is a packaging problem there.

noble/arm64: `146s autopkgtest [07:37:41]: ERROR: |  builddeps:/tmp/autopkgtest.hqbUNf/build.D2W/systemd : Depends: dh-sequence-dlopenlibdeps but it is not installable`. No idea. Looks unrelated.
noble/ppc64el: same
noble/s390x: same

testing-farm:fedora-rawhide-x86_64 is different:
48/92 systemd:integration-tests / TEST-22-TMPFILES                                              FAIL             15.32s   exit status 1
52/92 systemd:integration-tests / TEST-26-SYSTEMCTL                                             FAIL              6.65s   exit status 127
61/92 systemd:integration-tests / TEST-43-PRIVATEUSER-UNPRIV                                    TIMEOUT        1800.52s   killed by signal 15 SIGTERM

`tmpfiles.d` was touched for `HAVE_SYSV_COMPAT`, but the tests uses HAVE_SYSV_COMPAT=1, so this shouldn't matter. (-Dsysvinit-path=/etc/rc.d/init.d -Drc-local=/etc/rc.d/rc.local)

systemctl: script is missing → b72761a67d5c14b84f940258b42cb59865c9799b. But we have that in b72761a67d5c14b84f940258b42cb59865c9799b. So it's some similar error. Let's ignore it.

---

I'll drop the commits related to sysvinit compat. I submitted a revert for one of the patches for `main`. We can do them in the next batch.

**Comment by keszybz** [comment]
I'll merge this when some initial CI passes. It's the same as previous iteration but with two commits dropped.

**Comment by keszybz** [comment]
OK, at least a few of the builds that run unit tests passed. noble/* fails as described above.

**Pull request merged**
