### PR TITLE
remove duplicate slashes in systemd-path output if rootprefixdir is "/" 

### LINKED ISSUE #16773: Apparent ABI change following 4a56315a990b path: use ROOTPREFIX properly
**systemd version the issue has been seen with**
> v246

**Used distribution**
 > Yocto Poky

**Expected behaviour you didn't see**
 > `sysusers_dir`, `sysctl_dir`, `binfmt_dir`, `modules_load_dir` reference directories in `/usr/lib`

**Unexpected behaviour you saw**
 > `sysusers_dir`, `sysctl_dir`, `binfmt_dir`, `modules_load_dir` reference directories in `/lib` - this appears to be a change in the ABI from v245 when split-usr is enabled

**Steps to reproduce the problem**

Build with split-usr enabled, the paths are then:

```
root@qemux86-64:~# systemd-path sysusers sysctl modules-load
//lib/sysusers.d
//lib/sysctl.d
//lib/modules-load.d
```

This appears to be a result of 4a56315a990b path: use ROOTPREFIX properly

Full configuration:

```
Message: systemd 246
         split /usr:                        true
         split bin-sbin:                    true
         prefix directory:                  /usr
         rootprefix directory:              /
         sysconf directory:                 /etc
         include directory:                 /usr/include
         lib directory:                     /usr/lib
         rootlib directory:                 /lib
         SysV init scripts:                 /etc/init.d
         SysV rc?.d directories:            /etc
         PAM modules directory:             /lib/security
         PAM configuration directory:       /etc/pam.d
         RPM macros directory:              /usr/lib/rpm/macros.d
         modprobe.d directory:              /lib/modprobe.d
         D-Bus policy directory:            /usr/share/dbus-1/system.d
         D-Bus session directory:           /usr/share/dbus-1/services
         D-Bus system directory:            /usr/share/dbus-1/system-services
         bash completions directory:        /usr/share/bash-completion/completions
         zsh completions directory:         /usr/share/zsh/site-functions
         extra start script:                /etc/rc.local
         debug shell:                       /bin/sh @ /dev/tty9
         TTY GID:                           5
         users GID:                         -
         maximum system UID:                999
         maximum system GID:                999
         minimum dynamic UID:               61184
         maximum dynamic UID:               65519
         minimum container UID base:        524288
         maximum container UID base:        1878982656
         /dev/kvm access mode:              0666
         render group access mode:          0666
         certificate root directory:        /etc/ssl
         support URL:                       https://lists.freedesktop.org/mailman/listinfo/systemd-devel
         nobody user name:                  nobody
         nobody group name:                 nobody
         fallback hostname:                 localhost
         symbolic gateway hostnames:        _gateway
         default DNSSEC mode:               no
         default DNS-over-TLS mode:         no
         default mDNS mode:                 yes
         default LLMNR mode:                yes
         default cgroup hierarchy:          hybrid
         default net.naming-scheme setting: latest
         default KillUserProcesses setting: true
         default locale:                    C
         default user $PATH:                (same as system services)
         systemd service watchdog:          3min
         default DNS servers:               1.1.1.1
                                            8.8.8.8
                                            1.0.0.1
                                            8.8.4.4
                                            2606:4700:4700::1111
                                            2001:4860:4860::8888
                                            2606:4700:4700::1001
                                            2001:4860:4860::8844
         default NTP servers:               time1.google.com
                                            time2.google.com
                                            time3.google.com
                                            time4.google.com
         time epoch:                        1596812993 (2020-08-07T15:09:53+00:00)
         static libsystemd:                 false
         static libudev:                    false

         enabled features: libfdisk, IMA, xz, ACL, idn, initrd, binfmt, vconsole, quotacheck, tmpfiles, environment.d, sysusers, randomseed, backlight, rfkill, xdg-autostart, logind, machined, userdb, hostnamed, timedated, timesyncd, localed, networkd, resolve, pstore, kmod, xkbcommon, blkid, nss-myhostname, nss-mymachines, nss-resolve, nss-systemd, hwdb, tpm, SysV compat, utmp, ldconfig, hibernate, adm group, wheel group, gshadow, link-systemctl-shared, link-networkd-shared, link-timesyncd-shared, kernel-install, systemd-analyze

         disabled features: libcryptsetup, PAM, pwquality, p11kit, libfido2, AUDIT, AppArmor, SELinux, SECCOMP, SMACK, zlib, zstd, lz4, bzip2, gcrypt, qrencode, microhttpd, gnutls, openssl, libcurl, libidn2, libidn, libiptc, elfutils, repart, firstboot, portabled, homed, importd, DNS-over-TLS(gnutls), DNS-over-TLS(openssl), coredump, polkit, legacy pkla, efi, gnu-efi, pcre2, dbus, glib, man pages, html pages, man page indices, debug hashmap, debug mmap cache, debug siphash, valgrind, trace logging, install tests, link-udev-shared
```

### PR DESCRIPTION
**Pull request by poettering**
Fixes #16773

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM, but I wonder if the second commit will not break things for the distros which play with installation prefixes (nixos?).

**Comment by poettering** [comment]
> LGTM, but I wonder if the second commit will not break things for the distros which play with installation prefixes (nixos?).

my guess is that the pkg-config file is the least of their probs...

**Comment by poettering** [comment]
> my guess is that the pkg-config file is the least of their probs...

(i.e. we hardcode the search paths as /usr in code, and the .pc files were just the outliers really)

**Comment by flokli** [comment]
Hmm, so far most locations seem to have honored `--prefix` if we configured meson with it (which NixOS essentially sets to something like `/nix/store/…-systemd-…/`).

That PR doesn't change much of that behaviour, does it?

On the pkgconfig changes, why do we stop adding `prefix` there?

**Comment by flokli** [comment]
I need to check the rest of the changes since `246…master`, but having `--prefix` point to another location did work surprisingly well so far. Not sure if we need to break it on purpose.

**Comment by arianvp** [comment]
Correct me if I'm wrong but I don't think we use the paths from `systemd.pc` anywhere in NixOS. Instead all the systemd configuration files are always installed in and picked up from `/etc/systemd/system`.    

We do rely on https://github.com/systemd/systemd/blob/master/src/libsystemd/libsystemd.pc.in   having `prefix=@prefix@` such that the nix build system links dependencies depending on systemd to the correct version.   But this PR doesn't touch it.

**Comment by keszybz** [comment]
OK, so it sounds like this will be cause a regression for you. Please check though.

**Comment by poettering** [comment]
@keszybz i think you meant to write *not* cause a regression for you? Or what am I misunderstanding?

**Comment by flokli** [comment]
@arianvp I know we patch some paths in `systemd.pc` (`systemd_system_unit_path`, `systemd_user_unit_path`) - either for consistency with the changes in the same patch touching actual logic, or because some other packages actually use it.

In any case, is there a reason honoring a configured prefix needs to be dropped from `systemd.pc`?

**Comment by poettering** [comment]
> In any case, is there a reason honoring a configured prefix needs to be dropped from `systemd.pc`?

Because the matching stuff in sd-path and everywhere else ignores it. i.e. CONF_PATHS_NULSTR()  is the macro that we use to build search paths, i.e. it generates a list of directories where we look into. $prefix is not listed there, but /usr is. systemd.pc is supposed to expose the very same list. Currently it does not. With this change it does.

**Comment by flokli** [comment]
> > In any case, is there a reason honoring a configured prefix needs to be dropped from `systemd.pc`?
> 
> Because the matching stuff in sd-path and everywhere else ignores it. i.e. CONF_PATHS_NULSTR() is the macro that we use to build search paths, i.e. it generates a list of directories where we look into. $prefix is not listed there, but /usr is. systemd.pc is supposed to expose the very same list. Currently it does not. With this change it does.

We do that in https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/systemd/0014-add-rootprefix-to-lookup-dir-paths.patch (and not only for the reasons written in the commit message).

**Comment by keszybz** [comment]
OK, let's merge this then. The nixos patch doesn't replace /usr/lib in the list, it only adds $prefix/lib at the end. So this patch doesn't really change much for nixos.

**Comment by flokli** [comment]
Well, this PR /did/ change the output of `systemd.pc` to not include various paths - it might cause regressions for downstream packages using any of these values.

I need to check and will report back.

**Comment by jtojnar** [comment]
Unfortunately, it turned out the pkg-config file change did actually break packages built (not only) using Nix. Opened https://github.com/systemd/systemd/issues/18082 to track the issue.

**Pull request merged**
