### PR TITLE
github: how to report bugs for older distribution versions

### PR DESCRIPTION
**Pull request by lnykryn**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Nice, thanks!

P.S. Please also add [Debian](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=systemd) to the list.

**Comment by lnykryn** [comment]
I have forced-pushed new version with debian link.

**Comment by keszybz** [comment]
I think this can go in, but we need to cover more popular distros: Arch, OpenSUSE, Ubuntu, Gentoo, Mandriva. Maybe also include a note like "(If your distro is missing, please file an issue here.)".

**Comment by lnykryn** [comment]
I think those can be added through additional pull-request. I don't want to upset other maintainers by setting a wrong site :-)

**Pull request merged**
