### PR TITLE
path-util: introduce path_prefix_root_cwd(), and use it in find_esp() and friends

### PR DESCRIPTION
**Pull request by yuwata**
split-out of #27186.

### CODE REVIEW

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by lnussel** [comment]
this one breaks things for me. `bootctl list` now only works when called with / as current directly.

```
future-tw:/etc # bootctl list
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Found container virtualization none.
Failed to check file system type of "efi": No such file or directory
File system "boot" is not a FAT EFI System Partition (ESP) file system.
Using EFI System Partition at /etc/boot/efi.
```

**Comment by yuwata** [comment]
@lnussel Indeed. Thanks. Will fix soon.

**Comment by yuwata** [comment]
@lnussel Fix is waiting in #27299.

**Comment by keszybz** [comment]
Hmm. This commit also messes up `bootctl -p/-x`:
```console
$ build/bootctl --print-esp-path
/home/zbyszek/src/systemd-stable/efi
$ build/bootctl --print-boot-path
/home/zbyszek/src/systemd-stable/efi
```
I'll test #27299.

**Pull request merged**
