### PR TITLE
dissect: make the --image= switch of our various tools honour Verity …

### PR DESCRIPTION
**Pull request by poettering**
…data

This adds simple Verity support to
mount_image_privately_interactively(): we dicover the verity metadata
and use it.

### CODE REVIEW

**Comment by poettering** [comment]
/cc @bluca 

(This makes systemd-tmpfiles/systemd-sysuser/… all support verity data when using --image=)

**Comment by bluca** [comment]
> /cc @bluca
> 
> (This makes systemd-tmpfiles/systemd-sysuser/… all support verity data when using --image=)

But aren't those tools _modifying_ the image? Using verity metadata makes the image mount read-only, no?

with dissect-image:

```
$ sudo ~/git/systemd/buildx86/systemd-dissect --mount ./img.raw /tmp/img
$ mount | grep img
/dev/mapper/a265e13e4c28abe709583c62a6e0d59116798cb5c3ef690c4883c04c6686a468-verity on /tmp/img type ext4 (ro,nodev,relatime)
```

**Comment by poettering** [comment]
> > 
> 
> But aren't those tools _modifying_ the image? Using verity metadata makes the image mount read-only, no?

This is useful for images where /usr is a verity-enabled partition but / is a regular one. In that case we should still honour the verity data for /usr.

And even for the cases where verity is for the root fs itself it might make sense to honour verity, maybe for cases where people want to see what tmpfiles would do or if all it does would be a NOP because already applied. i.e. sometimes there's value in testing for failures that shouldn't be there...

**Review by bluca — APPROVED** [review]
Ok, makes sense to me. LGTM

**Pull request merged**
