### PR TITLE
Revert "missing: re-add mistakenly dropped entries"

### PR DESCRIPTION
**Pull request by evverx**
This reverts commit b6459df80fb48cfa16aab44249a60da05b7ce656.

I'm going to break CentOS here a little bit to see how it goes :-) The webhook is on.

cc @mrc0mmand

### CODE REVIEW

**Comment by evverx** [comment]
I can't believe this is happening: https://ci.centos.org/job/systemd-pr-build/3680/console

**Comment by evverx** [comment]
As far as I can tell, the only issue is that CentOS can't update the status of the PR. On the bright side, it tried to build `systemd` and failed as expected with:
```
'src/libsystemd/src@libsystemd@@systemd_static@sta/sd-netlink_netlink-types.c.o' -c ../src/libsystemd/sd-netlink/netlink-types.c
../src/libsystemd/sd-netlink/netlink-types.c:636:10: error: ‘FRA_SUPPRESS_IFGROUP’ undeclared here (not in a function)
         [FRA_SUPPRESS_IFGROUP]    = { .type = NETLINK_TYPE_U32 },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:636:9: error: array index in initializer not of integer type
         [FRA_SUPPRESS_IFGROUP]    = { .type = NETLINK_TYPE_U32 },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:636:9: error: (near initialization for ‘rtnl_routing_policy_rule_types’)
../src/libsystemd/sd-netlink/netlink-types.c:637:10: error: ‘FRA_SUPPRESS_PREFIXLEN’ undeclared here (not in a function)
         [FRA_SUPPRESS_PREFIXLEN]  = { .type = NETLINK_TYPE_U32 },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:637:9: error: array index in initializer not of integer type
         [FRA_SUPPRESS_PREFIXLEN]  = { .type = NETLINK_TYPE_U32 },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:637:9: error: (near initialization for ‘rtnl_routing_policy_rule_types’)
```
I'd say it's a huge step forward. I've reverted the revert and now it's running the integration tests.

**Comment by mrc0mmand** [comment]
> Something seems to have gone wrong:
> 
> ```
> [systemd-pr-build] $ /bin/sh -xe /tmp/jenkins3430706288356091020.sh ba09d891e8cd90ebacb4cc16604c07c3ed3553a9 failure https://ci.centos.org/job/systemd-pr-build/3680/ "build failed" "CentOS CI"
> [PostBuildScript] - Build does not have any of the results [NOT_BUILT, ABORTED, UNSTABLE]. Did not execute /home/systemd/systemd-centos-ci/github-status.py $ghprbActualCommit error $BUILD_URL "build errored" "CentOS CI".
> Setting status of ba09d891e8cd90ebacb4cc16604c07c3ed3553a9 to FAILURE with url https://ci.centos.org/job/systemd-pr-build/3680/ and message: 'Build finished. '
> FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or the user account does not have write access to the repo.
> ```
> 
> @mrc0mmand do you know what that could be?

Don't worry about those PostBuildScript messages, these are from the jenkins plugin, which is set to "anonymous" mode to manage the webhook, but it still tries to update the state, which is now handled by the python wrapper. There was a typo in *failure* reporting, should be fixed now.

**Comment by evverx** [comment]
I'll wait for the current build (which should be successful) to finish and then push the revert or the reverted revert to break it again :-)

**Comment by evverx** [comment]
@mrc0mmand I'm wondering why the CentOS icon didn't appear in the two PRs opened after this one. Does it pop up only when PRs breaks CentOS CI?

**Comment by mrc0mmand** [comment]
It does, it's just limited to two concurrent jobs. However, apparently the post-build script doesn't work as I expected, will look into it...

**Comment by mrc0mmand** [comment]
Ha, replaced the weird jenkins thingy with other weird jenkins thingy and the reporting seems to be finally working.

**Comment by mrc0mmand** [comment]
Thanks to Brian we managed to update the token for the GitHub PRB plugin, so the workaround script can be safely dropped. This means the credentials errors seen before should be gone.

**Pull request closed without merging**
