### PR TITLE
slice: clean up empty slices

### PR DESCRIPTION
**Pull request by rphibel**

### CODE REVIEW

**Comment by poettering** [comment]
what's the precise issue this is supposed to address?

generally we should not make cgroup changes on unit freeing, but on unit stopping. "freeing" just releases information about a unit from memory, "stopping" is actually when units go down. freeing also happens when we reload or reexec the service manager, where we free all data, and disassemble basically everything but leave the units around and then after coming back put everything back together.

**Comment by rphibel** [comment]
> what's the precise issue this is supposed to address?
> 
> generally we should not make cgroup changes on unit freeing, but on unit stopping. "freeing" just releases information about a unit from memory, "stopping" is actually when units go down. freeing also happens when we reload or reexec the service manager, where we free all data, and disassemble basically everything but leave the units around and then after coming back put everything back together.

This addresses the following scenario where the slice's cgroup is not cleaned up:
- create a slice
- put a service unit under it with `KillMode=none`
- stop the slice (changes state to inactive immediately, but the service is not killed because of `KillMode=none`),
- then stop the service.

The service's cgroup gets cleaned up but the slice's cgroup doesn't.

We do receive a cgroup empty notification for the slice's cgroup. But, at this point, the slice is already inactive. So I don't know if we go through the unit stopping code. I will have a look.

**Comment by poettering** [comment]
friends should not allow friends to use KillMode=none. It comes with the concept. Maybe just something to document?

hmm, if we get the empty notification can we still figure out the "closest slice" for it? if so maybe deliver the event to that and make it prune the subtree?

**Comment by rphibel** [comment]
> friends should not allow friends to use KillMode=none. It comes with the concept. Maybe just something to document?

There is a big yellow warning already :smile: 

> 
> hmm, if we get the empty notification can we still figure out the "closest slice" for it? if so maybe deliver the event to that and make it prune the subtree?

I can have a look at that. Is there an easy way to figure out the "closest slice"?

**Comment by poettering** [comment]
> I can have a look at that. Is there an easy way to figure out the "closest slice"?

hmm, so looking into this again, we keep a hash table of inotify watch descriptors that allow us to find the right unit for a cgroup empty event (which we get via inotify). This does not allow us to do such "closest parent" logic, since watch descriptors have no information about that.

but here's another idea: whenever we stop a unit but fail to remove its cgroup, then we should updat the inotify watch hash table and move the watch descriptors over to the parent. Thus each unit might then have multiple watch descriptors associated with it, not just one.

**Comment by rphibel** [comment]
New PR: https://github.com/systemd/systemd/pull/27183

**Pull request closed without merging**
