### PR TITLE
ci: build the Fedora RPMs with -Werror

### PR DESCRIPTION
**Pull request by mrc0mmand**
Prompted by https://github.com/systemd/systemd/pull/18396#issuecomment-769265776.

### CODE REVIEW

**Review by bluca — APPROVED** [review]
Lgtm

**Comment by evverx** [comment]
As far as I know, `-werror` is still broken: https://github.com/mesonbuild/meson/issues/7360. Given that it seems `-Db_lto=true` is used there I think it would be better to pass it via `CFLAGS` and `CXXFLAGS` directly.

**Comment by mrc0mmand** [comment]
> As far as I know, `-werror` is still broken: [mesonbuild/meson#7360](https://github.com/mesonbuild/meson/issues/7360). Given that it seems `-Db_lto=true` is used there I think it would be better to pass it via `CFLAGS` and `CXXFLAGS` directly.

Hah, completely forgot about this one, thanks! I'll prep a patch shortly.

**Comment by mrc0mmand** [comment]
@evverx do you know if it happens only with `--werrorr` or if `-Dc_args=-Werror -Dcpp_args=-Werror` doesn't work as well? Unfortunately, I can't tweak the `CFLAGS/CXXFLAGS` in the spec file without wiping the Fedora defaults, so the meson options would be the next acceptable solution (without introducing some dark magic).

**Comment by evverx** [comment]
@mrc0mmand I think -Dc_args and -Dcpp_args should work but just to make sure I'd try to revert https://github.com/systemd/systemd/pull/16227/commits/65830c00f9465d04e54a020e4d1cc3a8315ad3bb and build `systemd` with `meson   --optimization=3 -Db_lto=true   build && ninja -C build`.

**Comment by mrc0mmand** [comment]
> @mrc0mmand I think -Dc_args and -Dcpp_args should work but just to make sure I'd try to revert [65830c0](https://github.com/systemd/systemd/commit/65830c00f9465d04e54a020e4d1cc3a8315ad3bb) and build `systemd` with `meson --optimization=3 -Db_lto=true build && ninja -C build`.

Thanks! I couldn't revert the mentioned commit, since the code in question doesn't exist the codebase anymore, but another warning resurfaced, which may be a bit of an issue. In a nutshell, the SELinux stuff still uses the deprecated `mallinfo()`, and turning on `-Werror` causes the meson's check to fail:

```
Compiler stderr:
 /systemd/build/meson-private/tmpy1tcjdn3/testfile.c: In function 'main':
/systemd/build/meson-private/tmpy1tcjdn3/testfile.c:9:13: error: 'mallinfo' is deprecated [-Werror=deprecated-declarations]
    9 |             void *a = (void*) &mallinfo;
      |             ^~~~
In file included from /systemd/build/meson-private/tmpy1tcjdn3/testfile.c:1:
/usr/include/malloc.h:118:24: note: declared here
  118 | extern struct mallinfo mallinfo (void) __THROW __MALLOC_DEPRECATED;
      |                        ^~~~~~~~
cc1: all warnings being treated as errors
...
Checking for function "mallinfo" : NO
```

That triggers the `#warning` branch in `selinux-util.h`:
https://github.com/systemd/systemd/blob/8885fed4e3a52cf1bf105e42043203c485ed9d92/src/basic/selinux-util.c#L86-L96

```
../src/basic/selinux-util.c:95:6: error: #warning "mallinfo() is missing, add mallinfo2() supported instead." [-Werror=cpp]
   95 | #    warning "mallinfo() is missing, add mallinfo2() supported instead."
      |      ^~~~~~~
cc1: all warnings being treated as errors
```

So, I guess, the good news is that the meson options indeed work :-)

**Pull request merged**
