### PR TITLE
Unconditionally pull in cryptsetup-remote.target in the initramfs

### PR DESCRIPTION
**Pull request by keszybz**
/cc @jlebon

### CODE REVIEW

**Comment by poettering** [comment]
lgtm

**Comment by jlebon** [comment]
> All the targets that depend on this one would need to be split also. That condition is true for initrd-fs.target, but not for sysinit.target.

Hmm, can't we just resolve this by only statically enabling it in the initramfs? IOW:

```diff
diff --git a/units/meson.build b/units/meson.build
index a55e717868..95461eebb6 100644
--- a/units/meson.build
+++ b/units/meson.build
@@ -28,8 +28,7 @@ units = [
         ['hybrid-sleep.target',                 'ENABLE_HIBERNATE'],
         ['suspend-then-hibernate.target',       'ENABLE_HIBERNATE'],
         ['initrd-cleanup.service',              'ENABLE_INITRD'],
-        ['initrd-cryptsetup.target',            'HAVE_LIBCRYPTSETUP ENABLE_INITRD',
-         'sysinit.target.wants/'],
+        ['initrd-cryptsetup.target',            'HAVE_LIBCRYPTSETUP ENABLE_INITRD']
         ['initrd-fs.target',                    'ENABLE_INITRD'],
         ['initrd-parse-etc.service',            'ENABLE_INITRD'],
         ['initrd-root-device.target',           'ENABLE_INITRD'],
```

And in dracut:

```diff
diff --git a/modules.d/90crypt/module-setup.sh b/modules.d/90crypt/module-setup.sh
index 3deee65e..4ead94df 100755
--- a/modules.d/90crypt/module-setup.sh
+++ b/modules.d/90crypt/module-setup.sh
@@ -152,8 +152,8 @@ install() {
                       $systemdsystemunitdir/cryptsetup.target \
                       $systemdsystemunitdir/sysinit.target.wants/cryptsetup.target \
                       $systemdsystemunitdir/initrd-cryptsetup.target \
-                      $systemdsystemunitdir/sysinit.target.wants/initrd-cryptsetup.target \
                       systemd-ask-password systemd-tty-ask-password-agent
+        systemctl --root "$initdir" add-wants sysinit.target initrd-cryptsetup.target
     fi

     dracut_need_initqueue
```

What we have here is OK too, but let's make sure that's what we want the ideal setup to look like (also whenever we change approaches, I have to keep reverting corresponding patches in dracut).

**Comment by keszybz** [comment]
We don't want to encode logic intro dracut — quite the opposite, we want to completely remove any special knowledge and setup code from dracut. In the long term, dracut should be just installing a selection of rpms.

**Comment by jlebon** [comment]
Sanity-checked that this addresses the Tang use case. Once this merges, I can submit the corresponding dracut patch.

Looks like `bionic-i386` failed with:

```
upstream             FAIL timed out
```

> We don't want to encode logic intro dracut

Yup, no arguments there. :)

**Comment by keszybz** [comment]
> Sanity-checked that this addresses the Tang use case.

Thanks. Let's merge then.

**Pull request merged**
