### PR TITLE
core: expose `SyslogFacility` and `SyslogLevel` as properties on dbus

### PR DESCRIPTION
**Pull request by evverx**
Expose:
- [`SyslogFacility`](http://www.freedesktop.org/software/systemd/man/systemd.exec.html#SyslogFacility=)
- [`SyslogLevel`](http://www.freedesktop.org/software/systemd/man/systemd.exec.html#SyslogLevel=)

on dbus.

### CODE REVIEW

**Comment by keszybz** [comment]
This one looks good to. I only wonder if it wouldn't be better to expose the level and facility as numbers on the bus. It would certainly be easier to pass them around this way.

**Comment by poettering** [comment]
Yeah, I think so too, these should be exposed as numbers, as the man pages and everything document them as such, and they regularly are used in threshold comparisons. They really are more a linearly ordered thing rather than a real enum...

**Comment by evverx** [comment]
@keszybz , @poettering , fixed.

**Comment by poettering** [comment]
Looks great now, but could you merge the fixups and the original patches, so that this only becomes two patches? (or actually, you could even make this a single patch, as this is so closely related...)

We generally try to avoid merging patches with immediately following fixup patches in the same PR...

**Comment by evverx** [comment]
oh, sorry. done.

**Comment by keszybz** [comment]
Shouldn't the type be 'u' or 'y'?

**Comment by poettering** [comment]
Very good question. But I am tempted to say "i" is right, since syslog()'s first argument is int, and we should probably stick to the types glibc uses for this...

Of course, glibc should not have used "int" as type for this, but that's UNIX I guess, hence we should follow what it did there...

**Comment by keszybz** [comment]
OK, makes sense.

**Pull request merged**
