### PR TITLE
nspawn: allow combination of private_network and network-namespace-path

### PR DESCRIPTION
**Pull request by zhsj**
Fixes: #14289

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, I think I would prefer if we'd simply allow combination of --private-network and -network-namespace-path= instead. (not combination of the latter and other options, but just of these two). Any chance you can rework the patch accordingly?

**Comment by zhsj** [comment]
okay, I will try. Still quite new to this codebase.

**Comment by zhsj** [comment]
So I think I only need to change the error out condition. And it seems to work.

**Comment by mrc0mmand** [comment]
I guess the `TEST-13-NSPAWN` test needs to be updated to reflect the new behavior:

https://github.com/systemd/systemd/blob/fb4b0465abbd96e6d342e5606c61c919c99a82ff/test/TEST-13-NSPAWN-SMOKE/test.sh#L124-L155

**Pull request merged**
