### PR TITLE
boot: fix pretty nasty typo

### PR DESCRIPTION
**Pull request by poettering**
Note to self: should I ever become a black hat hacker, this is how I'd
hide a vulnerability. ;-)

(No, this one is not a vulnerability)

Follow-up for: 163d1ea5dd69c75d889ba4c2d1b51432ed14127f

### CODE REVIEW

**Comment by poettering** [comment]
(sad, that none of the static checkers noticed that alignment didn't match what this does. I mean, gcc does check alignment these days, but not this way apparently)

**Review by bluca — APPROVED** [review]

**Comment by evverx** [comment]
Judging by https://pvs-studio.com/en/docs/warnings/v5001/ pvs-studio could have caught this I think. I played with it back in 2018 in https://github.com/systemd/systemd/pull/11223#discussion_r243946461.

**Comment by mrc0mmand** [comment]
> Judging by https://pvs-studio.com/en/docs/warnings/v5001/ pvs-studio could have caught this I think. I played with it back in 2018 in [#11223 (comment)](https://github.com/systemd/systemd/pull/11223#discussion_r243946461).

FTR, I filed https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104367 to check if this couldn't be handled by gcc/clang as well.

**Review by medhefgo — APPROVED** [review]
Yikes

**Pull request merged**
