### PR TITLE
tree-wide: the last batch of shellcheck shenanigans

### PR DESCRIPTION
**Pull request by mrc0mmand**
This should be, hopefully, the last batch of shellcheck-related changes, since this PR also introduces a shellcheck CI (Super-Linter in GH Actions).

Since for PR workflow Super-Linter should be configured to check only changed files in the respective PR, I gave it a more thorough spin in https://github.com/systemd-ci-incubator/systemd/pull/14 (as it can be overridden via the `VALIDATE_ALL_CODEBASE` env variable).

### CODE REVIEW

**Review by bluca — APPROVED** [review]
Nice!

**Comment by yuwata** [comment]
Hmm? CentOS CI results looks strange...

**Comment by mrc0mmand** [comment]
> Hmm? CentOS CI results looks strange...

Whoops, my ~~spring~~ autumn cleanup in CentOS CI uncovered a "bug", just pushed a fix. I'll restart the Arch Linux run just to confirm it works as expected and then look at the test fail.

**Comment by yuwata** [comment]
OK, then let's set the green label again.

**Comment by bluca** [comment]
@keszybz expressed desire to avoid removing `configure`, can that be made shellcheck-happy instead?

**Comment by mrc0mmand** [comment]
> @keszybz expressed desire to avoid removing `configure`, can that be made shellcheck-happy instead?

I'll look into that.

**Comment by mrc0mmand** [comment]
Updated with a shellcheck-compliant configure script, PTAL.

**Comment by keszybz** [comment]
Belatedly, LGTM, thanks.

**Pull request merged**
