### PR TITLE
Small fixes

### LINKED ISSUE #7858: systemd-logind.service.xml not referencing sd-login.xml
man/systemd-logind.service.xml references
   url="https://www.freedesktop.org/wiki/Software/systemd/multiseat">Multi-Seat
but the latter states that it has been superseded by sd-login.  So the link shall be updated to point to sd-login.

The wiki page talks about sd-login(3) and sd-login(7), but I think only the former one exists.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #7858, #7866, #7882, #7883. Also, includes revised version of #7595.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx @pfl @fsateler @cpsw, @dilyanpalauzov.

Especially, @dilyanpalauzov if you already prepare the fix for #7866, please let me know, I will drop the commit. And, if you want to change the author information, also please let me know.

**Comment by poettering** [comment]
looks excellent thanks!

**Comment by evverx** [comment]
The leak mentioned in #7882 is gone. Thank you.

**Comment by pfl** [comment]
Guys, you are too fast for me... ;-)

**Pull request merged**
