### PR TITLE
network: Add IFF_DYNAMIC

### PR DESCRIPTION
**Pull request by ssahani**
we may skip removing addresses when this flag is set

### CODE REVIEW

**Comment by yuwata** [comment]
What is the use case of this? The flag `IFF_DYNAMIC` seems not used in the kernel, maybe deprecated flag??

**Comment by ssahani** [comment]
Have you tested? Please see http://man7.org/linux/man-pages/man7/netdevice.7.html. Use case is kernel will delete addresses when interface goes down networkd can skip sending messages to delete addresses

**Comment by yuwata** [comment]
Which code in kernel removes addresses?

**Comment by yuwata** [comment]
> Have you tested? Please see http://man7.org/linux/man-pages/man7/netdevice.7.html.

Yes, and I have no difference between `Dynamic=yes` and `no`, except for `ip a` shows `DYNAMIC` flag or not. Addresses are always removed when the interface becomes down. I also tested with `IgnoreCarrierLoss=yes`, in that case networkd does not remove the address, but kernel removes them even if `Dynamic=no`.

You can see https://elixir.bootlin.com/linux/latest/ident/IFF_DYNAMIC. It seems that `IFF_DYNAMIC` is defined, but almost not used by the kernel, and the code is not changed since [2.6.11](https://elixir.bootlin.com/linux/v2.6.11/ident/IFF_DYNAMIC).

**Comment by ssahani** [comment]
It seems I got it wrong. It means user's pace program supposed to set this if addresses are dynamic to indicate this. You are right.

**Pull request closed without merging**
