### PR TITLE
network: make config_parse_address() assume full prefix length

### LINKED ISSUE #26102: networkd: should not default to /0 as IPv6 prefix
### systemd version the issue has been seen with

252

### Used distribution

Debian Unstable

### Linux kernel version used

6.1.7

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

IPv6 default prefix should be /128

2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:ba:f6:bc brd ff:ff:ff:ff:ff:ff
    inet6 2a01:238:42bc:a192:5054:ff:feba:f6bc/64 scope global deprecated dynamic mngtmpaddr noprefixroute
       valid_lft 3476sec preferred_lft 0sec
    inet6 2a01:238:42bc:a192::d1:100/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:feba:f6bc/64 scope link
       valid_lft forever preferred_lft forever

### Unexpected behaviour you saw

If no prefix is given on an Address line for IPv6, the IP address is configured with a /0 prefix. The kernel then proceeds to expect the complete Internet on-link which kind of makes Internet communication impossible despite the rest of the system configuration being correct.

2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:ba:f6:bc brd ff:ff:ff:ff:ff:ff
    inet6 2a01:238:42bc:a192:5054:ff:feba:f6bc/64 scope global deprecated dynamic mngtmpaddr noprefixroute
       valid_lft 3498sec preferred_lft 0sec
    inet6 2a01:238:42bc:a192::d1:100/0 scope global
       valid_lft forever preferred_lft forever

### Steps to reproduce the problem

Have a local network with a correct and working RA, add the following networkd configuration:

```
[Match]
Name=e*

[Network]
DHCP=no
IPForward=no
IPv6AcceptRA=yes
IPv6SendRA=no
DHCPv6PrefixDelegation=no

[Address]
Address=2a01:238:42bc:a192::d1:100
```

Not the missing prefix in the "Address" line, adding /64 leads to a correctly configured network.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
C.f. #11307.
Closes #26102.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
```
../src/test/test-in-addr-util.c: In function ‘test_in_addr_prefix_from_string_one’:
../src/test/test-in-addr-util.c:50:57: error: ‘PREFIXLEN_LEGACY’ undeclared (first use in this function); did you mean ‘PREFIXLEN_REFUSE’?
   50 |         r = in_addr_prefix_from_string_auto_internal(p, PREFIXLEN_LEGACY, &f, &q, &l);
      |                                                         ^~~~~~~~~~~~~~~~
      |                                                         PREFIXLEN_REFUSE
```

**Comment by yuwata** [comment]
Oops. I forgot to update the test code. Setting the green label again.

**Comment by bluca** [comment]
`Assertion 'a->prefixlen == prefixlen' failed at src/network/test-networkd-conf.c:189, function test_config_parse_address_one(). Aborting.`

**Comment by yuwata** [comment]
Nah, should be fine now...

**Pull request merged**
