### PR TITLE
basic/linux: copy magic.h from kernel to our code

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by yuwata** [comment]
I mean, it fails if the header file _in our tree_ is updated.

**Comment by keszybz** [comment]
> I mean, it fails if the header file _in our tree_ is updated.

I don't understand. Please rephrase.

**Comment by yuwata** [comment]
> > I mean, it fails if the header file _in our tree_ is updated.
> 
> I don't understand. Please rephrase.

With this PR, we do not use system's linux/magic.h. So, even if the kernel header in the system is newer and have new `XYZ_SUPER_MAGIC`, the test will not fail.
The gperf file needs to be updated only when we update linux/magic.h in our tree and it has a new MAGIC.

So, with this PR it is not necessary to downgrade the message in meson, as if it fails in stable-branch, that should be caused by a wrong cherry-picking.

**Comment by yuwata** [comment]
Even #32134 is merged, still I think this should be good. PTAL.

**Pull request merged**
