### PR TITLE
Consider aliases in /usr when disabling units

### PR DESCRIPTION
**Pull request by fbuihuu**

### CODE REVIEW

**Comment by fbuihuu** [comment]
So test-install-root unit test is now failing due to the fact that broken symlinks in the config paths are no more allowed.

This can be fixed easily by using `CHASE_NONEXISTENT` flag with chase_symlinks() but on the other hand I'm wondering if we really should allow such dangling symlinks...

For instance the test creates the following dangling enablement symlink:

> /tmp/rootMQHOvY/etc/systemd/system/multi-user.target.wants/a.service -> /usr/lib/systemd/system/a.service

and the current code accepts it even if /usr/lib/systemd/system/a.service points to nowhere. If we're only interested in the generic name "a.service", wouldn't it have been better to use a symlink pointing to itself rather than allowing such dangling symlink ?

**Comment by fbuihuu** [comment]
@keszybz could you please have a look ?

**Comment by keszybz** [comment]
> This can be fixed easily by using `CHASE_NONEXISTENT` flag with chase_symlinks() but on the other hand I'm wondering if we really should allow such dangling symlinks...

That is explicitly allowed and we must accept such symlinks. In particular, it is totally OK to create a symlink to a unit file in /etc, and than have that file moved to /usr/lib.

Apart from that, I think the changes in this PR are good.

**Comment by fbuihuu** [comment]
> That is explicitly allowed and we must accept such symlinks. In particular, it is totally OK to create a symlink to a unit file in /etc, and than have that file moved to /usr/lib.

Fair enough.

I'm still wondering why we use (potentially dangling) symlinks in *.wants/ or *.requires/... empty files would have been less ambiguous IMHO.

**Comment by keszybz** [comment]
> I'm still wondering why we use (potentially dangling) symlinks in *.wants/ or *.requires/... empty files would have been less ambiguous IMHO.

Because empty files mean masking, and this would be very confusing. Things are as they are, a clean design from scratch would probably be different.

**Comment by fbuihuu** [comment]
@keszybz any chance you can review this one ? Thanks.

**Comment by keszybz** [comment]
LGTM.

**Pull request merged**
