### PR TITLE
core: make sure to restore the control command id, too

### PR DESCRIPTION
**Pull request by poettering**
Fixes: #15356

### CODE REVIEW

**Comment by poettering** [comment]
Didn't test this too much myself. Would be thankful for a review from @msekletar and feedback from @fayeinseu and @JackFangXN!

**Comment by keszybz** [comment]
Looks reasonable, but a confirmation that this fixes the issue would be great.

**Comment by fayeinseu** [comment]
This issue has been fixed.

**Comment by keszybz** [comment]
Thanks for the confirmation.

**Pull request merged**
