### PR TITLE
shared: Don't try calling NULL callback in bus_wait_for_units_clear

### PR DESCRIPTION
**Pull request by rbalint**
BugLink: https://bugs.launchpad.net/bugs/1870930

### CODE REVIEW

**Comment by keszybz** [comment]
There's a few other place in the file that call the callback, and they should be modified to match.

Buuuuuut, looking at the code, WaitForItem is only instatiated in bus_wait_for_units_add_unit(), and bus_wait_for_units_add_unit() is *always* called with callback=NULL. If that analysis is correct, it'd be better to just nuke the the callback thing. It also seems that `current` is only set, and never used.

**Comment by rbalint** [comment]
@keszybz Yes, I'm not sure what the intention was with the callbacks. This minimal change fixed  the issue we observed frequently, but I agree that there are more to fix here.

**Comment by keszybz** [comment]
It was added in 3572d3df8f822d4cf1601428401a837f723771cf and never used. Please just nuke it.

**Comment by poettering** [comment]
Hmm, I'd really merge this like this actually, if that's OK.

BusWaitForUnits is supposed to be used by all our client code sooner or latter that wants to wait for some unit to change state, and depending on the usecase we might want to have a per-unit callback. That's at least what my original intention was.

Right now only systemctl has been ported over, but at least systemd-run should be ported over, too. And logind next (in logind in particular we care about a per-unit state, since we track multiple instances of user@.service). Hence, to make it easy to eventually port this over, I'd really keep this in for now, if that's OK.

Hope that makes sense?

**Comment by poettering** [comment]
(let's merge this. if we realize eventually that noone ever ported this over we can still drop it, but for now, the fix in this PR looks totally right to me)

**Comment by keszybz** [comment]
OK, if there is a plan... But then the patch should be fixed to fix the other call sites too. I didn't mention that in the review, because I wanted to remove the whole thing.

**Comment by keszybz** [comment]
→ https://github.com/systemd/systemd/pull/15563

**Pull request merged**
