### PR TITLE
expose resolv.conf mode bus property

### PR DESCRIPTION
**Pull request by poettering**
A fix for #17159

### CODE REVIEW

**Comment by keszybz** [comment]
```
src/resolve/resolved-bus.c:1633:18: error: unused variable ‘m’ [-Werror=unused-variable]
 1633 |         Manager *m = userdata;
      |                  ^
cc1: all warnings being treated as errors
```

CI no like, but looks great otherwise.

**Comment by poettering** [comment]
Force pushed new version. Only chance is a fix for the CI failure. Since the change is so minor and @keszybz already liked it, taking liberty to set green label

**Comment by keszybz** [comment]
> taking liberty to set green label

Gotcha! It was already set.

**Comment by poettering** [comment]
yeah, i noticed when i wanted to set it ;-)

**Pull request merged**
