### PR TITLE
tests: fix x86 personality tests to only on x86

### PR DESCRIPTION
**Pull request by poettering**
More fixes for #2698.

### CODE REVIEW

**Comment by martinpitt** [comment]
LGTM, thanks.

**Comment by keszybz** [comment]
Hm, maybe I'm missing something, but I don't think this can work. `exec-spec-interpolation.service` is not mentioned in `Makefile.am` at all.

**Comment by jsynacek** [comment]
To me, this looks like it's only going to hide the fact that there are service files missing for the correct personalities. Now, the tests at least fail.

**Comment by keszybz** [comment]
Actually they don't fail, which suggests that something is wrong: I mean, that if the service file is missing from `Makefile.am`'s `EXTRA_DIST` list, and the test _passes_ in `make distcheck`, there are two bugs:
1. the file is missing from `EXTRA_DIST`.
2. the check does not return failure properly? Or does not use the file actually? (I haven't looked at the test yet).

**Comment by evverx** [comment]
> exec-spec-interpolation.service is not mentioned in Makefile.am at all.

My bad. I'll prep a patch.

> Actually they don't fail, which suggests that something is wrong

`make distcheck` doesn't fail.
`sudo make distcheck` fails.

`make check` skips many tests. See https://github.com/systemd/systemd/pull/2259#issuecomment-168579837

**Comment by poettering** [comment]
@evverx could you incorporate this patch then in your new PR? Thanks!

**Comment by evverx** [comment]
done: https://github.com/systemd/systemd/pull/2719

**Pull request closed without merging**
