### PR TITLE
Revert "Merge pull request #19811 from anitazha/revert_mount_rl"

### PR DESCRIPTION
**Pull request by yuwata**
This reverts commit 7ad9bad71b077f6a4629f4e48fb9ad26e1784809, reversing
changes made to 390a22f4b11c0f409872fe628ba526b31d6e8b18.

### CODE REVIEW

**Comment by yuwata** [comment]
Yay! This passes all upstream tests in Ubuntu CIs. So, #19811 seems to cause the nspawn issue #19903.

**Comment by yuwata** [comment]
cc @anitazha

**Comment by keszybz** [comment]
bionic-s390x failed with "networkd-test.py".

I'll restart all the tests to see if they still pass. If they do, let's see: if we can figure out the issue quickly, then great. If not, let's merge this to get the CI working again.

**Comment by keszybz** [comment]
cc @msekletar

**Comment by yuwata** [comment]
The networkd-test.py failure in s390x should be fixed by #19914.

**Comment by anitazha** [comment]
The nspawn timeout issue seems to be specific to i386; looking at some of the recent PRs the other bionic CIs fail frequently but not for the same nspawn timeout reason as in #19903 . But I also don't see anything in particular about this PR that would break on i386 in particular...

**Comment by yuwata** [comment]
> The nspawn timeout issue seems to be specific to i386

No, the nspawn issue occurs randomly on any architecture. See other `dont-merge` tagged PRs.

**Comment by anitazha** [comment]
I looked at #19908 #19907 #19906 #19904 again and it's i386, ppc64el, and one instance of amd64. Which I guess is not much of a connection at all except that arm64 isn't affected and I didn't bother looking at s390x due to that other issue :(

**Comment by bluca** [comment]
It's quite strange as it did work on https://github.com/systemd/systemd/pull/19811 so there must have been some changes on the infra

**Comment by bluca** [comment]
Or maybe it's not that PR by itself, but the combination with one more that was merged in parallel?

**Comment by anitazha** [comment]
I am a believer it is definitely this PR. I rolled out a version with this patch to a small subset of our fleet and we're getting `systemd[1]: Assertion 'a <= b' failed at src/libsystemd/sd-event/sd-event.c:2897, function sleep_between(). Aborting.` in addition to the failures that look really similar to the ones from the bionic CI failures (`[org.freedesktop.DBus.Error.TimedOut], message: [Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)]`)

**Comment by anitazha** [comment]
Let's merge this but we still need to fix the sd-event rate limiting not fully working :(

**Comment by yuwata** [comment]
I think it is not necessary to merge this. I hope #19924 fixes the issue.

**Pull request closed without merging**
