### PR TITLE
Use a convenience library for the sources shared between core/ and shutdown/

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
looks good. but note that mount-setup.[ch] is used in plenty other places. I wonder if we can rework that to split out the bit that everybody needs, and move that to mount-util.h or so...

**Comment by keszybz** [comment]
Indeed. Updated to fix the issue comprehensively.

**Comment by poettering** [comment]
This is one of those cases were one hopes that downstreams use LTO to build things, otherwise their binaries will now grow a bit larger.

**Comment by keszybz** [comment]
> This is one of those cases were one hopes that downstreams use LTO to build things, otherwise their binaries will now grow a bit larger.

Why do you think that? The fact that the objects are taken from an .a file shouldn't matter: they compiler should only link the ones it needs, no? I should probably test this, but my expectation is that there is no size change.

**Comment by keszybz** [comment]
Hmm, there *are* differences in size:
```
(old)
-rwxrwxr-x. 1 zbyszek zbyszek 4012800 Mar  6 17:55 build/systemd*
-rwxrwxr-x. 1 zbyszek zbyszek  100896 Mar  6 17:55 build/systemd-fstab-generator*
-rwxrwxr-x. 1 zbyszek zbyszek   57464 Mar  6 17:55 build/systemd-machine-id-setup*
-rwxrwxr-x. 1 zbyszek zbyszek  629128 Mar  6 17:55 build/systemd-nspawn*
-rwxrwxr-x. 1 zbyszek zbyszek   64904 Mar  6 17:55 build/systemd-remount-fs*
-rwxrwxr-x. 1 zbyszek zbyszek  137472 Mar  6 17:55 build/systemd-shutdown*

(new)
-rwxrwxr-x. 1 zbyszek zbyszek 4012800 Mar  6 18:01 build/systemd*
-rwxrwxr-x. 1 zbyszek zbyszek  105336 Mar  6 18:01 build/systemd-fstab-generator*
-rwxrwxr-x. 1 zbyszek zbyszek   57696 Mar  6 18:01 build/systemd-machine-id-setup*
-rwxrwxr-x. 1 zbyszek zbyszek  602200 Mar  6 18:01 build/systemd-nspawn*
-rwxrwxr-x. 1 zbyszek zbyszek   65248 Mar  6 18:01 build/systemd-remount-fs*
-rwxrwxr-x. 1 zbyszek zbyszek  137816 Mar  6 18:01 build/systemd-shutdown*
```
systemd is exactly the same, nspawn loses 27k, a few others gain a few k. So the overall size is reduced, but this seems to be very noisy.

**Pull request merged**
