### PR TITLE
journald: Look for _UDEV_DEVLINK at a child block device

### PR DESCRIPTION
**Pull request by tbzatek**
In case of SCSI devices the identifier received along the message from kernel
resolves to a `SUBSYSTEM=scsi` udev record while udev maintains probed information
at a `SUBSYSTEM=block` record. This patch would look up a child udev device
of type block when device symlinks are missing.

---

This is my attempt to enhance messages related to SCSI devices coming from `/dev/kmsg` with stable identifiers. Apart from the well known fact that getting the identifiers from udev is racy as long as the newly appearing block device may still being probed (or it's gone already in the opposite case), this patch is trying to solve the scenario where the device has been probed successfully and messages are being reported during regular operation.

However as the information is always being looked up some time after the event happened in the kernel, there's theoretical possibility that the information we'd look up from udev would in fact belong to a different block device, e.g. in case of rapidly changing block devices (load tests...). Still, having at least some information is better than none, until we fix the kernel side of things.

Steps to reproduce:
1. `# modprobe scsi_debug opts=2 every_nth=1`
2. `# udevadm settle`
3. `# dd if=/dev/sdX of=/dev/null`
4. observe whether the journal messages carry the `_UDEV_DEVLINK` attribute

Remarks to the patch:
* I'm bit unsure about the `sd_device` memory ownership taken from `sd_device_enumerator`, thus the explicit ref/unref.
* Can't find a way to limit the enumerator to return devices only one level deep, thus the complicated matching to find direct child. Another way would be to read `/sys/devices/.../block/` directory instead of traversing actual udevdb hierarchy.

### CODE REVIEW

**Comment by poettering** [comment]
hmm, the idea was always to do it the other way round: instead of looking for children during collection of the data, looking for parents while viewing it. i.e. "journalctl /dev/sda" should really start at the specified node and then go up, and add additional matches for all parents too. And that's what it does afaics. Are you saying that doesn't work?

**Comment by tbzatek** [comment]
That's a bit different use case - viewing journal events by device node starts with resolving the device tree up and setting up matches. That's done at the moment of viewing and it may point to a completely different device than in the past.

The only information we usually get from kernel as a part of a structured message is a volatile ID like        `"_KERNEL_DEVICE" : "+scsi:3:0:0:0"`. That's why it's important to resolve and log any stable identifier at the time of the event.

**Comment by poettering** [comment]
Well, sure, the identifiers are volatile, that's true. But searching down the tree appears so wrong to me. I mean, there might be a single SCSI device with many block devices and we never know what these errors belong to...

**Comment by tbzatek** [comment]
Closing this attempt as a different, more general approach is being taken and discussed within the storage group.

**Pull request closed without merging**
