### PR TITLE
test-network: improve stability of DHCP client tests

### PR DESCRIPTION
**Pull request by yuwata**
Fixes the CI failure in https://github.com/systemd/systemd/pull/12741#issuecomment-498793324.

### CODE REVIEW

**Comment by keszybz** [comment]
```
test_dhcp_client_ipv4_ipv6 (__main__.NetworkdDHCPClientTests) ... 
FAIL
test_dhcp_client_listen_port (__main__.NetworkdDHCPClientTests) ... 
FAIL
test_dhcp_client_reuse_address_as_static (__main__.NetworkdDHCPClientTests) ... 
FAIL
```
No idea what is happening here, but it looks related.

**Comment by yuwata** [comment]
CentOS CI (Arch in KVM) failure is caused by `TEST-09-ISSUE-2691`. Not related.

**Comment by yuwata** [comment]
Yey, all green now. PTAL.

**Comment by keszybz** [comment]
LGTM.

**Pull request merged**
