### PR TITLE
network: bunch of cleanups and fixes for addressing

### LINKED ISSUE #25843: RouteMetric= settings for prefix routes in [Address] sections get lost
### systemd version the issue has been seen with

252.3 and 251.8

### Used distribution

gentoo

### Linux kernel version used

6.0.11-gentoo-x86_64

### CPU architectures issue was seen on

None

### Component

systemd-networkd

### Expected behaviour you didn't see

I have multiple `[Address]` sections annotated with `RouteMetric=` statements for various interfaces (eg., a wireguard tunnel wg0 and a bridge br0). For example,
```
[Address]                                                                                                                    
Address=192.168.100.1/24
RouteMetric=30
```
which then shows up as intended:
```
$ ip route show
192.168.100.0/24 dev br0 proto kernel scope link src 192.168.100.1 metric 30
```

I would expect that this setting is persistent. In particular, the setting should survive restarts of systemd-networkd, changes in network settings, and hibernates.

### Unexpected behaviour you saw

But the moment I do a suspend, hibernate, or simply restart the systemd-networkd daemon the metric setting gets lost:
```
$ systemctl restart systemd-networkd
$ ip route show
192.168.100.0/24 dev br0 proto kernel scope link src 192.168.100.1
```

Only fully deleting the interface and restarting systemd-networkd brings back the metric:
```
$ ip link del br0
$ systemctl restart systemd-networkd
192.168.100.0/24 dev br0 proto kernel scope link src 192.168.100.1 metric 30
```

As a workaround it is possible to do something like this:
```
[Address]
Address=192.168.100.1/24
AddPrefixRoute=false

[Route]
PreferredSource=192.168.100.1
Destination=192.168.100.0/24
Metric=30
```
Which works as intended:
```
$ ip route show
192.168.100.0/24 dev br0 proto kernel scope link src 192.168.100.1 metric 30
$ systemctl restart systemd-networkd
$ ip route show
192.168.100.0/24 dev br0 proto kernel scope link src 192.168.100.1 metric 30
```

Related to #19344

### PR DESCRIPTION
**Pull request by yuwata**
Preparation for fixing #28009 and #28358.
Split-out of #28325.

### CODE REVIEW

**Review by bluca — CHANGES_REQUESTED** [review]
Can a test be added for the update functionality?

**Comment by yuwata** [comment]
> Can a test be added for the update functionality?

@bluca Done. And added several tiny fixes found during adding/updating the test. PTAL.

**Review by DaanDeMeyer — APPROVED** [review]

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
Could this be related?

```
5187s testsuite-75.sh[804]: + dig stale1.unsigned.test -t A
5203s testsuite-75.sh[805]: ;; communications error to 127.0.0.53#53: timed out
5203s testsuite-75.sh[805]: ;; communications error to 127.0.0.53#53: timed out
5203s testsuite-75.sh[805]: ;; communications error to 127.0.0.53#53: timed out
5203s testsuite-75.sh[805]: ; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> stale1.unsigned.test -t A
5203s testsuite-75.sh[805]: ;; global options: +cmd
5203s testsuite-75.sh[805]: ;; no servers could be reached
```

I don't think I've seen it before

**Comment by yuwata** [comment]
That seems to be a resolved issue. Always 5sec stall after `Processing query...`.
```
Jul 31 20:56:44 ns1.unsigned.test systemd-resolved[272]: Processing query...
Jul 31 20:56:49 ns1.unsigned.test systemd-resolved[272]: Received dns UDP packet of size 61, ifindex=0, ttl=64, fragsize=0, sender=127.0.0.1, destination=127.0.0.53
Jul 31 20:56:49 ns1.unsigned.test systemd-resolved[272]: Got DNS stub UDP query packet for id 29767
Jul 31 20:56:49 ns1.unsigned.test systemd-resolved[272]: Looking up RR for stale1.unsigned.test IN A.
Jul 31 20:56:49 ns1.unsigned.test systemd-resolved[272]: Processing query...
Jul 31 20:56:49 ns1.unsigned.test systemd-resolved[272]: Timeout reached on transaction 64246.
```

**Comment by yuwata** [comment]
@bluca I have no idea why the test passed before. But I hope the last commit fixes the issue.
@mrc0mmand Do you have any idea?

**Comment by mrc0mmand** [comment]
> @bluca I have no idea why the test passed before. But I hope the last commit fixes the issue. @mrc0mmand Do you have any idea?

No idea, but I noticed another issue reported by TEST-75 in one of the nightly cron jobs as well, which didn't appear in other PR jobs.

**Comment by yuwata** [comment]
> > @bluca I have no idea why the test passed before. But I hope the last commit fixes the issue. @mrc0mmand Do you have any idea?
> 
> No idea, but I noticed another issue reported by TEST-75 in one of the nightly cron jobs as well, which didn't appear in other PR jobs.

Is it already filed?

**Comment by mrc0mmand** [comment]
> > > @bluca I have no idea why the test passed before. But I hope the last commit fixes the issue. @mrc0mmand Do you have any idea?
> > 
> > 
> > No idea, but I noticed another issue reported by TEST-75 in one of the nightly cron jobs as well, which didn't appear in other PR jobs.
> 
> Is it already filed?

Not yet, but I should be able to get to it soon.

**Comment by yuwata** [comment]
@bluca Anyway, I think the resolved test failure is not related. Dropping the green label. Could you review the last commit?

**Review by bluca — APPROVED** [review]

**Comment by mrc0mmand** [comment]
> > > > @bluca I have no idea why the test passed before. But I hope the last commit fixes the issue. @mrc0mmand Do you have any idea?
> > > 
> > > 
> > > No idea, but I noticed another issue reported by TEST-75 in one of the nightly cron jobs as well, which didn't appear in other PR jobs.
> > 
> > 
> > Is it already filed?
> 
> Not yet, but I should be able to get to it soon.

-> https://github.com/systemd/systemd/pull/28600

**Comment by yuwata** [comment]
The last commit should be backported to stable.

**Comment by keszybz** [comment]
Last commit queued up for v254.1.

**Pull request merged**
