### PR TITLE
resolved: Read /proc/net/pnp for DNS servers

### PR DESCRIPTION
**Pull request by suihkulokki**
Proposal for systemd-resolved to read DNS servers from kernel, if the machine has been booted with kernel IP autoconfig. First patch splits manager_read_resolv_conf so the same code can be used to parse more files, second one adds reading /proc/net/pnp.

### CODE REVIEW

**Comment by poettering** [comment]
Is there documentation available for /proc/net/pnp somewhere?

**Comment by suihkulokki** [comment]
As far as I know, https://www.kernel.org/doc/Documentation/filesystems/nfs/nfsroot.txt only briefly mentions it (can be linked to resolv.conf). Code implementing this is at:

http://lxr.free-electrons.com/source/net/ipv4/ipconfig.c#L1297

**Comment by poettering** [comment]
We don't use Signed-Off-By btw, patches should not include that.

**Comment by poettering** [comment]
So, what's the logic you are implementing here? You merge the data from the two files? Shouldn't this rather be a search path logic? i.e. use /proc/net/pnp if it exists, otherwise /etc/resolve.conf?

Can you elaborate on what and why you did it the way you did?

**Comment by suihkulokki** [comment]
As far as I understand the code (which I'm rather new to, so might be wrong), the existing code will merge existing entries. So it would read /proc/net/pnp and then resolv.conf. Admittedly I'm not sure how useful that is - I can change that to search path logic, which would make the patch a lot smaller.

**Comment by poettering** [comment]
Yeah, I think I'd prefer if we would read /etc/resolv.conf as first source of configuration. If it doesn't exist or is a symlink to our own snippet we'd then fallback to /proc/net/pnp and use that if it exists. We'd never merge the lists, and we'd follow our usual logic that admin config always overrides automatic config. Makes sense?

**Comment by johannbg** [comment]
cant you simply check the presence of ip=<foo> on the kernel commandline and if it's present then use  /proc/net/pnp otherwise dont?

**Comment by poettering** [comment]
@johannbg well, /proc/net/pnp doesn't exist if the kernel doesn't use the ip autoconfig stuff. And checking if it exists is certainly much cheaper than parsing /proc/cmdline one more time...

**Comment by suihkulokki** [comment]
The reworked patch now follows the "manual settings over autoconfig" logic. However, the existing goto logic was a bit confusing, so I might have missed something while converting the logic to the new should_read_resolv_conf function.

**Comment by poettering** [comment]
We generally don't do force push github PR updates in order not to loose commenting history (unless things are completely trivial, or nobody has commented yet). Next time, please open a new PR and close the old one instead, referencing it from the new one.

**Comment by poettering** [comment]
Looks OK otherwise.

**Comment by zonque** [comment]
@suihkulokki any update on this, is it still wanted? resolved has seen many updated lately, so this needs to be rebased. Please let us know whether you're still working on this.

**Comment by poettering** [comment]
OK, closing this one, since there hasn't been a response in quite some time. I'd still be willing to merge a patch for this though, if there's interest!

**Pull request closed without merging**
