### PR TITLE
journal: Skip over corrupt entry items in enumerate_data()

### LINKED ISSUE #21407: systemd-journal-upload fails and never resumes after Failed to move to next field in entry: Bad message
**systemd version the issue has been seen with**
 > 249.6-3

**Used distribution**
 > archlinux

**Linux kernel version used** (`uname -a`)
 > `5.15.2-arch1-1`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > systemd-journal-upload should be able to move past corrupt messages

**Unexpected behaviour you saw**
 > systemd-journal-upload failed and refused to ever continue until manual intervention. My primary issue is that the uploader should be able to skip any corrupt message. My second issue is that it actually failed on a journal-entry that seems perfectly fine. My workaround was to manually update the cursor in `/var/lib/systemd/journal-upload/state`

**Steps to reproduce the problem**
 > unknown

**Additional program output to the terminal or log subsystem illustrating the issue**

Uploader failing:
```text
systemd-journal-upload: Failed to move to next field in entry: Bad message
systemd-journal-upload: Upload to http://xxxx/upload failed: operation aborted by callback
systemd[1]: systemd-journal-upload.service: Scheduled restart job, restart counter is at 54644.
```

Content of journal showing `journalctl -c "$LAST_CURSOR" -o json -n3 |cat` (this should show the offending message, not sure why it only shows 2 lines instead of 3):
```
{"MESSAGE":"audit: type=1701 audit(1635413692.883:77691): auid=4294967295 uid=99 gid=99 ses=4294967295 pid=1879717 comm=\"php-7.3.32\" exe=\"xxx\" sig=11 res=1","__CURSOR":"s=a073513a93f74c4092fb43cdf2e627f2;i=5422e;b=0fc7f964ab7f48a2af9d7cb306804fe3;m=3356477aae0;t=5cf666c3a1365;x=e83c14b06ee24778","SYSLOG_FACILITY":"0","_HOSTNAME":"xxx","SYSLOG_IDENTIFIER":"kernel","_BOOT_ID":"0fc7f964ab7f48a2af9d7cb306804fe3","_SOURCE_MONOTONIC_TIMESTAMP":"3527832324093","PRIORITY":"5","__MONOTONIC_TIMESTAMP":"3527853714144","_MACHINE_ID":"f548e490a8794a558c2851018c04faa0","__REALTIME_TIMESTAMP":"1635413692912485","_TRANSPORT":"kernel"}
{"_PID":"1","_SOURCE_REALTIME_TIMESTAMP":"1635413724408653","_COMM":"systemd","CODE_FILE":"src/core/cgroup.c","_SYSTEMD_SLICE":"-.slice","__CURSOR":"s=a073513a93f74c4092fb43cdf2e627f2;i=5422f;b=0fc7f964ab7f48a2af9d7cb306804fe3;m=335665844aa;t=5cf666e1aad2f;x=469ce1a8b7fc2530","_HOSTNAME":"xxx","_SYSTEMD_UNIT":"init.scope","_MACHINE_ID":"f548e490a8794a558c2851018c04faa0","INVOCATION_ID":"2810c0dca3114a6f94a3cb97ca2dfb84","TID":"1","UNIT":"xxx","CODE_FUNC":"unit_check_oom","_SYSTEMD_CGROUP":"/init.scope","MESSAGE":"xxx: A process of this unit has been killed by the OOM killer.","SYSLOG_IDENTIFIER":"systemd","__MONOTONIC_TIMESTAMP":"3527885210794","_UID":"0","_TRANSPORT":"journal","_GID":"0","PRIORITY":"5","_CAP_EFFECTIVE":"1ffffffffff","_EXE":"/usr/lib/systemd/systemd","MESSAGE_ID":"fe6faa94e7774663a0da52717891d8ef","CODE_LINE":"2960","_BOOT_ID":"0fc7f964ab7f48a2af9d7cb306804fe3","_CMDLINE":"/usr/lib/systemd/systemd --system --deserialize 74","SYSLOG_FACILITY":"3","__REALTIME_TIMESTAMP":"1635413724409135"}
```

`journalctl --verify` does show some corruption due to filesystem issues so that might be the rootcause.

### PR DESCRIPTION
**Pull request by daandemeyer**
Similar to sd_journal_next(), if trying to access an entry item
offset's data results in EBADMSG, skip to the next entry item so
we handle corruption better.

Fixes #21407

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Did the same change for sd_journal_get_data() as well.

**Comment by poettering** [comment]
lgtm, but please add brief log_debug() messages when this happens

**Comment by DaanDeMeyer** [comment]
Awesome, thanks for taking the time to test this!

**Comment by SjonHortensius** [comment]
@DaanDeMeyer thank you for your fast PR fixing my issue :)

**Comment by DaanDeMeyer** [comment]
Added debug messages, upgrading green label

**Comment by poettering** [comment]
lgtm! thanks!

**Comment by DaanDeMeyer** [comment]
Forgot to use PRIu64

**Comment by poettering** [comment]
CI failures appear unrelated

**Pull request merged**
