### PR TITLE
tmpfiles,sysusers,pid1: add a bunch of more specifiers

### PR DESCRIPTION
**Pull request by poettering**
let's make selected fields from /etc/os-release resolvable with specifiers, as well as the local architecture.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
The CIfuzz fail is caused by (now reverted) https://github.com/google/oss-fuzz/commit/c580d0d626247017dede2847869e1eb8a3705ee1, see https://github.com/google/oss-fuzz/issues/3727. I re-triggered the workflow and it seems to do something behind the curtains, so hopefully it will pass a propagate back to his PR.

**Comment by poettering** [comment]
@mrc0mmand hmm, the fuzz ci thing failed again. Merge or restart that CI?

**Comment by mrc0mmand** [comment]
> @mrc0mmand hmm, the fuzz ci thing failed again. Merge or restart that CI?

I guess I restarted it too soon after the outage was marked as "resolved". Retriggered it again, hopefully should finish in ~20 minutes.

**Comment by mrc0mmand** [comment]
Apparently, there's something else broken as well, reported to oss-fuzz. In the meantime, merging this one, since is has the green flag and rest of the CIs passed.

**Pull request merged**
