### PR TITLE
cgroup: remove support for NetClass= directive

### PR DESCRIPTION
**Pull request by zonque**
Support for `net_cls.class_id` through the `NetClass=` configuration directive
has been added in v227 in preparation for a per-unit packet filter mechanism.
However, it turns out the kernel people have decided to deprecate the `net_cls`
and `net_prio` controllers in v2. Tejun provides a comprehensive justification
for this in his commit, which has landed during the merge window for kernel
v4.5:

  https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=bd1060a1d671

As we're aiming for full support for the v2 cgroup hierarchy, we can no
longer support this feature. Userspace tool such as `nftables` are moving over
to setting rules that are specific to the full cgroup path of a task, which
obsoletes these controllers anyway.

This commit removes support for tweaking details in the `net_cls` controller,
but keeps the `NetClass=` directive around for legacy compatibility reasons.

### CODE REVIEW

**Comment by zonque** [comment]
Ay, thanks for spotting. But why the 'coredump' label?

**Comment by zonque** [comment]
FTR: force-pushed a new version fixing the NEWS section.

**Comment by poettering** [comment]
i figure the github complete-as-you-type logic fucked the label up. sorry for that!

**Comment by alban** [comment]
I wanted to use `NetClass=` for traffic control (tc) rules :(
Do you know if there will be a way to do per-cgroup-v2 classification in tc-land?

**Pull request merged**
