### PR TITLE
meson: use prefixdir instead of hardcoded /usr in rootprefixdir

### PR DESCRIPTION
**Pull request by Keruspe**
There are systems where prefix is not /usr, support those

### CODE REVIEW

**Comment by poettering** [comment]
uh? we only support /usr as prefixdir, see https://github.com/systemd/systemd/blob/master/README#L205

What other setup are you using?

**Comment by Keruspe** [comment]
In Exherbo, everything is under /usr/${CHOST} and stuff like /bin and /usr/bin are symlinks to /usr/${CHOST}/bin.
Installing to /bin or /usr/bin is thus forbidden by the package manager.

**Comment by Keruspe** [comment]
With the current setting, the resulting image looks like this, which seems wrong:
```
Lou ~ # ls /var/tmp/paludis/build/sys-apps-systemd-scm/image/usr/bin                                                                                                                                                                                                  
journalctl  loginctl  machinectl  networkctl  systemctl  systemd-ask-password  systemd-escape  systemd-firstboot  systemd-hwdb  systemd-inhibit  systemd-machine-id-setup  systemd-notify  systemd-sysusers  systemd-tmpfiles  systemd-tty-ask-password-agent  udevadm
Lou ~ # ls /var/tmp/paludis/build/sys-apps-systemd-scm/image/usr/x86_64-pc-linux-gnu/bin                                                                                                                                                                              
bootctl  coredumpctl  kernel-install  systemd-analyze  systemd-cgls   systemd-delta        systemd.halt  systemd-mount   systemd-path      systemd.reboot   systemd-run       systemd.shutdown         systemd-stdio-bridge  systemd-umount  udevd
busctl   hostnamectl  localectl       systemd-cat      systemd-cgtop  systemd-detect-virt  systemd.init  systemd-nspawn  systemd.poweroff  systemd-resolve  systemd.runlevel  systemd-socket-activate  systemd.telinit       timedatectl
```

**Comment by keszybz** [comment]
Hmm. Would just reverting ee4bfa21f6 work for you?

**Comment by yuwata** [comment]
I like this fix. If split-usr is on, then some binary is installed in / and the others in prefix. If split-usr is off then everything is in prefix. This is almost trivial and works for many cases including @Keruspe 's.
(I do not know well about the case split-usr=true, Should we fix prefix to /usr?)

@Keruspe At least README is need to be also adjusted.

**Comment by Keruspe** [comment]
@keszybz Actually reverting this commit would be even better for us

**Comment by keszybz** [comment]
Revert in https://github.com/systemd/systemd/pull/7493.

**Comment by poettering** [comment]
> In Exherbo, everything is under /usr/${CHOST} and stuff like /bin and /usr/bin are symlinks to /usr/${CHOST}/bin.
> Installing to /bin or /usr/bin is thus forbidden by the package manager.

That sounds like a really strange setup. i.e. something where prefixdir and DESTDIR have been misunderstood and mixed up

I mean, the prefixdir paths are API ultimately. It's where people should drop their unit files and so on. Fiddling with that sounds really off too me, just a call for trouble

**Comment by poettering** [comment]
I guess we can close this now, since #7493 got merged.

**Comment by fbuihuu** [comment]
Just to let you know: for "historical" reasons, openSUSE has split-usr=true and rootprefix=/usr so ee4bfa2 also broke this distro.

I think this was done to support old paths such as /lib/udev but want the default installation happens in /usr.

**Pull request closed without merging**
