### PR TITLE
tests: catch broken fuzz targets as early as possible

### PR DESCRIPTION
**Pull request by evverx**
See https://github.com/google/oss-fuzz/pull/2419.

### CODE REVIEW

**Comment by evverx** [comment]
It seems that Ubuntu CI has been having trouble connecting to testbeds via ssh, as far as I can tell, for at least two days:
```sh
Ubuntu 18.04.2 LTS autopkgtest ttyS0

autopkgtest login:
---------------------------------------------------
------- nova show 91e76a78-d05c-412a-b383-55a26010ae69 (adt-bionic-amd64-systemd-upstream-20190516-051604) ------
+--------------------------------------+------------------------------------------------------------------------------------+
| Property                             | Value                                                                              |
+--------------------------------------+------------------------------------------------------------------------------------+
| OS-DCF:diskConfig                    | MANUAL                                                                             |
| OS-EXT-AZ:availability_zone          | nova                                                                               |
| OS-EXT-SRV-ATTR:host                 | euler                                                                              |
| OS-EXT-SRV-ATTR:hypervisor_hostname  | euler.lcy01.scalingstack                                                           |
| OS-EXT-SRV-ATTR:instance_name        | instance-003d216a                                                                  |
| OS-EXT-STS:power_state               | 1                                                                                  |
| OS-EXT-STS:task_state                | -                                                                                  |
| OS-EXT-STS:vm_state                  | active                                                                             |
| OS-SRV-USG:launched_at               | 2019-05-16T07:00:42.000000                                                         |
| OS-SRV-USG:terminated_at             | -                                                                                  |
| accessIPv4                           |                                                                                    |
| accessIPv6                           |                                                                                    |
| config_drive                         |                                                                                    |
| created                              | 2019-05-16T07:00:33Z                                                               |
| flavor                               | autopkgtest (f878e70e-9991-46e0-ba02-8ea159a71656)                                 |
| hostId                               | 1722c5f2face86c3fc9f338ae96835924721512372342f664e6941bd                           |
| id                                   | 91e76a78-d05c-412a-b383-55a26010ae69                                               |
| image                                | adt/ubuntu-bionic-amd64-server-20190516.img (d00bf12c-467e-433f-a4f5-15720f13bff1) |
| key_name                             | testbed-juju-prod-ues-proposed-migration-machine-11                                |
| metadata                             | {}                                                                                 |
| name                                 | adt-bionic-amd64-systemd-upstream-20190516-051604                                  |
| net_ues_proposed_migration network   | 10.42.40.13                                                                        |
| os-extended-volumes:volumes_attached | []                                                                                 |
| progress                             | 0                                                                                  |
| security_groups                      | autopkgtest@lcy01-27.secgroup                                                      |
| status                               | ACTIVE                                                                             |
| tenant_id                            | afaef86b96dd4828a1ed5ee395ea1421                                                   |
| updated                              | 2019-05-16T07:00:42Z                                                               |
| user_id                              | 8524250971084851b3792a68fbc398dd                                                   |
+--------------------------------------+------------------------------------------------------------------------------------+
---------------------------------------------------
<VirtSubproc>: failure: Timed out on waiting for ssh connection
autopkgtest [07:07:45]: ERROR: testbed failure: cannot send to testbed: [Errno 32] Broken pipe
```
@iainlane could you take a look?

**Comment by evverx** [comment]
Or it could be that it has nothing to do with the infrastructure and `boot-and-services` is just failing to reboot VMs. If this is the case, @xnox could you take a look at https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/amd64/s/systemd-upstream/20190516_070748_1200c@/log.gz and https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/i386/s/systemd-upstream/20190516_081533_1200c@/log.gz?

Anyway, I'll just keep working on this PR (which is almost ready to roll).

**Comment by evverx** [comment]
Judging by ["Check build failed"](https://dev.azure.com/evvers/systemd-systemd/_build/results?buildId=199&view=logs&jobId=23a67116-225a-5276-33a6-5ba4a5085c78&taskId=6729ca11-c892-5de7-65c0-543a9c24e368&lineStart=6969&lineEnd=6970&colStart=1&colEnd=1), images with https://github.com/google/oss-fuzz/commit/2361c62433d840ed2a85821deed7fd766f099948 have been rolled out so I think this PR is ready to go. @mrc0mmand could you take a look?

**Comment by mrc0mmand** [comment]
Looks great, thank you!

**Pull request merged**
