### PR TITLE
bus: Use OrderedSet for introspection

### PR DESCRIPTION
**Pull request by medhefgo**
Otherwise, the generated xml files are not reproducible.

### CODE REVIEW

**Comment by keszybz** [comment]
I wonder why we didn't hit this before…

LGTM anyway.

**Comment by yuwata** [comment]
Indeed. LGTM.

**Comment by bluca** [comment]
```
TEST-38-FREEZER:                    FAIL     (293 s)
TEST-39-EXECRELOAD:                 SUCCESS  (  6 s)
TEST-40-EXEC-COMMAND-EX:            SUCCESS  (  8 s)
TEST-41-ONESHOT-RESTART:            SUCCESS  ( 12 s)
TEST-42-EXECSTOPPOST:               SUCCESS  ( 26 s)
TEST-43-PRIVATEUSER-UNPRIV:         SUCCESS  (  5 s)
TEST-44-LOG-NAMESPACE:              SUCCESS  (  5 s)
TEST-46-HOMED:                      SUCCESS  (  6 s)
TEST-47-ISSUE-14566:                SUCCESS  ( 12 s)
TEST-48-START-STOP-NO-RELOAD:       SUCCESS  ( 16 s)
TEST-49-RUNTIME-BIND-PATHS:         SUCCESS  ( 16 s)
TEST-50-DISSECT:                    FAIL     (641 s)
TEST-51-ISSUE-16115:                SUCCESS  ( 10 s)
TEST-52-HONORFIRSTSHUTDOWN:         SUCCESS  (  4 s)
TEST-53-ISSUE-16347:                SUCCESS  (184 s)
TEST-54-CREDS:                      SUCCESS  (  4 s)
TEST-55-OOMD:                       SUCCESS  ( 11 s)
TEST-56-EXIT-TYPE:                  SUCCESS  (  8 s)
TEST-57-ONSUCCESS-UPHOLD:           SUCCESS  ( 17 s)
TEST-58-REPART:                     FAIL     (216 s)
```

Don't think I've seen `TEST-38-FREEZER` fail before?

**Comment by bluca** [comment]
```
test_systemctl() {
    echo "Test that systemctl freeze/thaw verbs:"

    systemctl start "$unit"

    echo -n "  - freeze: "
    systemctl freeze "$unit"
    check_freezer_state "${unit}" "frozen"
    check_cgroup_state "$unit" 1
    # Freezing already frozen unit should be NOP and return quickly
    timeout 3s systemctl freeze "$unit"
    echo "[ OK ]"

    echo -n "  - thaw: "
    systemctl thaw "$unit"
    check_freezer_state "${unit}" "running"
    check_cgroup_state "$unit" 0
    # Likewise thawing already running unit shouldn't block
    timeout 3s systemctl thaw "$unit"
    echo "[ OK ]"

    systemctl stop "$unit"

    echo
}
```

```
Jan 19 16:12:06 H testsuite-38.sh[271]: + test_systemctl
Jan 19 16:12:06 H testsuite-38.sh[271]: + echo 'Test that systemctl freeze/thaw verbs:'
Jan 19 16:12:06 H testsuite-38.sh[271]: Test that systemctl freeze/thaw verbs:
Jan 19 16:12:06 H testsuite-38.sh[271]: + systemctl start testsuite-38-sleep.service
Jan 19 16:12:07 H kernel: ext4 filesystem being remounted at /run/systemd/unit-root/var/lib/systemd/linger supports timestamps until 2038 (0x7fffffff)
Jan 19 16:12:07 H kernel: ext4 filesystem being remounted at /run/systemd/unit-root/var/tmp supports timestamps until 2038 (0x7fffffff)
Jan 19 16:12:08 H kernel: ext4 filesystem being remounted at /run/systemd/unit-root/tmp supports timestamps until 2038 (0x7fffffff)
Jan 19 16:12:08 H kernel: ext4 filesystem being remounted at /run/systemd/unit-root/etc supports timestamps until 2038 (0x7fffffff)
Jan 19 16:12:09 H kernel: ext4 filesystem being remounted at /run/systemd/unit-root/etc supports timestamps until 2038 (0x7fffffff)
Jan 19 16:12:13 H kernel: ext4 filesystem being remounted at /run/systemd/unit-root/tmp supports timestamps until 2038 (0x7fffffff)
Jan 19 16:12:13 H kernel: ext4 filesystem being remounted at /run/systemd/unit-root/var/lib/systemd/linger supports timestamps until 2038 (0x7fffffff)
Jan 19 16:12:13 H kernel: ext4 filesystem being remounted at /run/systemd/unit-root/var/tmp supports timestamps until 2038 (0x7fffffff)
Jan 19 16:12:16 H testsuite-38.sh[271]: + echo -n '  - freeze: '
Jan 19 16:12:16 H testsuite-38.sh[271]:   - freeze: + systemctl freeze testsuite-38-sleep.service
Jan 19 16:12:17 H systemd-logind[305]: Watching system buttons on /dev/input/event0 (Power Button)
Jan 19 16:12:17 H systemd-logind[305]: Watching system buttons on /dev/input/event1 (AT Translated Set 2 keyboard)
Jan 19 16:12:17 H systemd-logind[305]: New seat seat0.
Jan 19 16:12:18 H testsuite-38.sh[271]: + check_freezer_state testsuite-38-sleep.service frozen
Jan 19 16:12:18 H testsuite-38.sh[271]: + local name object_path suffix
Jan 19 16:12:18 H testsuite-38.sh[271]: + suffix=service
Jan 19 16:12:18 H testsuite-38.sh[271]: + name=testsuite-38-sleep
Jan 19 16:12:18 H testsuite-38.sh[271]: + object_path=/org/freedesktop/systemd1/unit/testsuite_2d38_2dsleep_2eservice
Jan 19 16:12:18 H testsuite-38.sh[271]: + for _ in {0..10}
Jan 19 16:12:18 H testsuite-38.sh[334]: ++ busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1/unit/testsuite_2d38_2dsleep_2eservice org.freedesktop.systemd1.Unit FreezerState
Jan 19 16:12:18 H testsuite-38.sh[336]: ++ tr -d '"'
Jan 19 16:12:19 H testsuite-38.sh[335]: ++ cut -d ' ' -f2
Jan 19 16:12:19 H audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-logind comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 19 16:12:19 H kernel: audit: type=1130 audit(1642608739.772:30): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-logind comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 19 16:12:22 H testsuite-38.sh[271]: + state=frozen
Jan 19 16:12:22 H testsuite-38.sh[271]: + [[ frozen =~ ^(freezing|thawing)$ ]]
Jan 19 16:12:22 H testsuite-38.sh[271]: + break
Jan 19 16:12:22 H testsuite-38.sh[271]: + '[' frozen = frozen ']'
Jan 19 16:12:22 H testsuite-38.sh[271]: + check_cgroup_state testsuite-38-sleep.service 1
Jan 19 16:12:22 H testsuite-38.sh[271]: + grep -q 'frozen 1' /sys/fs/cgroup/system.slice/testsuite-38-sleep.service/cgroup.events
Jan 19 16:12:22 H testsuite-38.sh[271]: + timeout 3s systemctl freeze testsuite-38-sleep.service
Jan 19 16:12:23 H audit[337]: SYSTEM_RUNLEVEL pid=337 uid=0 auid=4294967295 ses=4294967295 msg='old-level=N new-level=3 comm="systemd-update-utmp" exe="/usr/lib/systemd/systemd-update-utmp" hostname=? addr=? terminal=? res=success'
Jan 19 16:12:24 H kernel: audit: type=1129 audit(1642608743.828:31): pid=337 uid=0 auid=4294967295 ses=4294967295 msg='old-level=N new-level=3 comm="systemd-update-utmp" exe="/usr/lib/systemd/systemd-update-utmp" hostname=? addr=? terminal=? res=success'
Jan 19 16:12:25 H audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-update-utmp-runlevel comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 19 16:12:25 H kernel: audit: type=1130 audit(1642608745.420:32): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-update-utmp-runlevel comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 19 16:12:25 H kernel: audit: type=1131 audit(1642608745.424:33): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-update-utmp-runlevel comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 19 16:12:25 H audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-update-utmp-runlevel comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 19 16:12:26 H audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=testsuite-38 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jan 19 16:12:26 H kernel: audit: type=1130 audit(1642608746.768:34): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=testsuite-38 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jan 19 16:12:27 H sh[343]: + systemctl poweroff --no-block
Jan 19 16:12:28 H systemd-logind[305]: System is powering down.
```

**Comment by bluca** [comment]
I've restarted, let's see if it was a fluke

**Comment by bluca** [comment]
It passed now, let's merge, probably a fluke.

**Review by bluca — APPROVED** [review]

**Comment by arianvp** [comment]
Heya! I was wondering if it's possible to cherry-pick this into systemd-stable's v250 branch?

**Pull request merged**
