### PR TITLE
Master minutes

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by martinpitt** [comment]
Do we actually use 'm' as unit for minutes anywhere? This sounds wrong, the official unit symbol is 'min' indeed, 'm' is meter..

**Comment by mulkieran** [comment]
That's what the source looks like, and my missing logs, too.

https://github.com/systemd/systemd/blob/master/src/basic/time-util.c#L707

All suffixes should be documented in the man-page, in a perfect world, but that would lengthen the man-page considerably.

**Comment by poettering** [comment]
@martinpitt we support a lot of unofficial syntaxes, there actually.

**Comment by poettering** [comment]
@martinpitt the lightdm CI check failed again without reason. Merged anyway now.

**Pull request merged**
