### PR TITLE
portable: add support for confext [Do not merge]

### PR DESCRIPTION
**Pull request by goenkam**
Fix mixing sysext and confext in ExtensionImages= and add support for confext to portabled

New PR here: https://github.com/systemd/systemd/pull/29839

### CODE REVIEW

**Comment by goenkam** [comment]
New PR here: https://github.com/systemd/systemd/pull/29839

**Comment by bluca** [comment]
Why?

**Comment by goenkam** [comment]
> Why?

There were two different PRs that were out for this task. This one was not meant to go in main, only for debugging, hence the branch name. This is where the new PR (with your changes) lives: https://github.com/systemd/systemd/pull/29839

**Comment by bluca** [comment]
The branch name doesn't matter

**Comment by goenkam** [comment]
> The branch name doesn't matter

I understand, I just wanted to keep it consistent with what I had documented the name as in previous iterations and mentions of the work. But yes, doesn't matter too much I believe.

**Pull request closed without merging**
