### PR TITLE
resolved: Break include cycles

### PR DESCRIPTION
**Pull request by daandemeyer**
[clangd](https://clangd.llvm.org/) was tripping on the circular includes in the resolved code so I went ahead and removed them.

### CODE REVIEW

**Comment by poettering** [comment]
did we forget a `#pragma once` here somewhere?

**Comment by DaanDeMeyer** [comment]
I checked and I don't think there were any missing pragmas. Still, even with pragma's, I can imagine it isn't easy to handle the case where a header includes itself transitively which is what was happening here in many cases. I'm actually surprised it compiled without warnings/errors before. This just removes all the cases where a resolved header includes itself transitively.

**Comment by vcaputo** [comment]
@DaanDeMeyer 

This broke the build for me:
```
../src/resolve/resolved-dnstls-openssl.c: In function ‘dnstls_stream_connect_tls’:
../src/resolve/resolved-dnstls-openssl.c:72:36: error: dereferencing pointer to incomplete type ‘Manager {aka struct Manager}’
         s = SSL_new(stream->manager->dnstls_data.ctx);
                                    ^~
../src/resolve/resolved-dnstls-openssl.c:77:38: error: dereferencing pointer to incomplete type ‘DnsServer {aka struct DnsServer}’
         r = SSL_set_session(s, server->dnstls_data.session);
                                      ^~
../src/resolve/resolved-dnstls-openssl.c:82:51: error: ‘DNS_OVER_TLS_YES’ undeclared (first use in this function)
         if (server->manager->dns_over_tls_mode == DNS_OVER_TLS_YES) {
                                                   ^~~~~~~~~~~~~~~~
../src/resolve/resolved-dnstls-openssl.c:82:51: note: each undeclared identifier is reported only once for each function it appears in
```

It looks like you've turned Manager and DnsServer into forward declarations w/incomplete types in resolved-dns-stream.h, so resolved-dnstls-openssl.c can't derference into their members anymore.

How'd this get past CI for merge?

**Comment by keszybz** [comment]
Build fails with `-Ddns-over-tls=openssl`. @DaanDeMeyer could you look into this please?
CI doesn't seem to test this combination.

**Pull request merged**
