### PR TITLE
journal-next (v256)

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by yuwata** [comment]
@mrc0mmand It seems newly added `verify_seqnum()` test makes TEST-04 slower and timeout. Do you have any idea to improve performance of the test? Or, maybe extend its timeout?

**Comment by mrc0mmand** [comment]
> @mrc0mmand It seems newly added `verify_seqnum()` test makes TEST-04 slower and timeout. Do you have any idea to improve performance of the test? Or, maybe extend its timeout?

That's interesting, I'll look into it, since there's something strange going on with TEST-04 in the C9S job even in other PRs.

**Comment by mrc0mmand** [comment]
So, first of all, this is not caused by the newly added test, as that runs as part of `TEST-09-REBOOT`.

However, there's a _significant_ slowdown when running the `journal-apend` test case from `TEST-04-JOURNAL`:

main:
```
# time make -C test/TEST-04-JOURNAL/ clean setup run TEST_MATCH_SUBTEST=journal-append BUILD_DIR=$PWD/build TEST_NO_QEMU=1
...
-rw-r----- 1 root root 8388608 Feb 15 12:26 /var/tmp/systemd-tests/systemd-test.1tTtQR/system.journal
TEST-04-JOURNAL RUN: Journal-related tests [OK]
make: Leaving directory '/root/systemd/test/TEST-04-JOURNAL'

real    1m39.790s
user    0m42.078s
sys     0m59.726s
```

This PR:
```
# time make -C test/TEST-04-JOURNAL/ clean setup run TEST_MATCH_SUBTEST=journal-append BUILD_DIR=$PWD/build TEST_NO_QEMU=1
...
-rw-r----- 1 root root 16777216 Feb 15 12:41 /var/tmp/systemd-tests/systemd-test.D0VTgo/system.journal
TEST-04-JOURNAL RUN: Journal-related tests [OK]
make: Leaving directory '/root/systemd/test/TEST-04-JOURNAL'

real    12m48.757s
user    12m33.116s
sys     7m9.444s

```

No idea, yet, if that's expected or not. The C9S job started complaining because I forgot to bump `$NSPAWN_TIMEOUT` to 900s as I did in the other jobs.

**Comment by mrc0mmand** [comment]
This is from the unprivileged run of TEST-02:

```
00:14:47.797 Container TEST-02-UNITTESTS has been shut down.
00:14:47.797 === Failed test log ===
00:14:47.797 --- test-journal begin ---
...
00:14:47.798 Detected btrfs file system with copy-on-write disabled, all is good.
00:14:47.798 PR_SET_MM_ARG_START failed: Operation not permitted
00:14:47.798 Reserving 333 entries in field hash table.
00:14:47.798 Reserving 2047 entries in data hash table.
00:14:47.798 Successfully forked off intermediary '(journal-archiver)' as PID 1918.
00:14:47.798 Detected btrfs file system with copy-on-write disabled, all is good.
00:14:47.798 PR_SET_MM_ARG_START failed: Operation not permitted
00:14:47.798 Reserving 333 entries in field hash table.
00:14:47.798 Reserving 2047 entries in data hash table.
00:14:47.798 Done...
00:14:47.798 Deleted empty archived journal ./test@5591c7bd92bd4548bc63e81af09e677f-0000000000000000-0000000000000000.journal (40.0K).
00:14:47.798 Deleted archived journal ./test@5591c7bd92bd4548bc63e81af09e677f-0000000000000001-0006116c67e849b1.journal (40.0K).
00:14:47.798 Vacuuming done, freed 80.0K of archived journals from ..
00:14:47.798 Assertion 'rm_rf(t, REMOVE_ROOT|REMOVE_PHYSICAL) >= 0' failed at src/libsystemd/sd-journal/test-journal.c:115, function test_non_empty_one(). Aborting.
```

**Pull request closed without merging**
