### PR TITLE
test: expect mmap to fail in seccomp test on s390 and s390x

### PR DESCRIPTION
**Pull request by rbalint**

### CODE REVIEW

**Comment by rbalint** [comment]
The patch is carried in Ubuntu starting with ubuntu/243-2ubuntu1 (in 20.04). Since CI is run on bionic here, this will make the s390x run fail.
I'd like to run Ubuntu CI tests on latest Ubuntu release instead of the latest release to make the CI environment more similar to where new systemd releases would eventually land and possibly map stable branch CI to the appropriate older Ubuntu releases, but the infrastructure is not there yet.
If we want to keep running CI on latest Ubuntu LTS then we can wait with merging this fix until 20.04 is released.

**Comment by rbalint** [comment]
There are a few more fixes at https://github.com/cpaelzer/systemd/commits/fix-MemoryDenyWriteExecute-x86-s390-bug-1853852-UPSTREAM to work with libseccomp 2.4.2. Those may make the change pass CI even on 18.04.

**Comment by keszybz** [comment]
bionic-s390x dies with
```
/* test_memory_deny_write_execute_mmap */
Operating on architecture: s390
Failed to add pkey_mprotect() rule for architecture s390, skipping: Numerical argument out of domain
Operating on architecture: s390x
Failed to add pkey_mprotect() rule for architecture s390x, skipping: Numerical argument out of domain
Assertion 'p == MAP_FAILED' failed at src/test/test-seccomp.c:536, function test_memory_deny_write_execute_mmap(). Aborting.
memoryseccomp-mmap terminated by signal ABRT.
Assertion 'wait_for_terminate_and_check("memoryseccomp-mmap", pid, WAIT_LOG) == EXIT_SUCCESS' failed at src/test/test-seccomp.c:550, function test_memory_deny_write_execute_mmap(). Aborting.
--- test-seccomp end ---
```

**Comment by keszybz** [comment]
Ah, the failure is expected. Dunno, can we make it pass on both? We certainly can't merge this until the tests pass, and having tests that only pass on some versions of the testbed is problematic.

**Comment by poettering** [comment]
hmm, so what's the background here? why does this work on some s390 and not on others?

**Comment by cpaelzer** [comment]
From all my tests I think this "just" depends on the version of kernel and libseccomp.
Rbalint has this code for 20.04 and there it works, but the CI runs on Bionic which makes this fix appear as failing.

This is the mmap test, for the shmat test in the past it was already given up to track which combination works well and which doesn't. See commit 67fb5f338 for that.

This also affects my PR #14167 which I formerly based on this one, maybe we can add a similar strategy as we did for shmat to the mmap test.
I'm making mmap do the same in my PR #14167 which should fix this CI issue here (it also would supersede/replace this PR as s390/s390x would no more need to be added to the ifdef check line).

**Comment by cpaelzer** [comment]
FYI - Tests on #14167 now succeeded on s390x on the 18.04 CI as well as in Ubuntu 20.04 locally. When #14167 is merged we can close/abort this PR here IMHO.

**Comment by poettering** [comment]
OK, let's close in favour of #14167

**Pull request closed without merging**
