### PR TITLE
Second Commit

### PR DESCRIPTION
**Pull request by guptamansi**

### CODE REVIEW

**Comment by yuwata** [comment]
Haha. He/she also join Hacktoberfest https://hacktoberfest.digitalocean.com/stats/guptamansi

**Comment by sebastienros** [comment]
Please label these PRs as "invalid" c.f. https://twitter.com/mhmd_azeez/status/1047912845730615296

**Comment by mbiebl** [comment]
@sebastienros there is no such label, which I guess means we have to create it manually?

**Comment by sebastienros** [comment]
Yes, it's there by default, but I assume it got cleaned at some point.

**Comment by mbiebl** [comment]
ok, I've (re)created this label and tagged the recent PRs accordingly

**Comment by mbiebl** [comment]
Interesting way to get a free T-shirt

**Comment by mbiebl** [comment]
@sebastienros In case you are involved with Hacktoberfest: could you change the criteria for contributions to only count actually merged PRs? Otherwise this is just an incentive for spammers...

**Pull request closed without merging**
