### PR TITLE
make pid1 namespace code independent of umask

### LINKED ISSUE #19899: Interaction of UMask=, TemporaryFileSystem= and BindPaths= results in inacessible bound paths
**systemd version the issue has been seen with**
 > systemd 248 (248.3-2-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux $HOST 5.11.19-hardened1-1-hardened #1 SMP PREEMPT Sat, 08 May 2021 22:06:31 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > AMD64

**Expected behaviour you didn't see**
When configuring a unit with UMask=, TemporaryFilesystem= and BindPaths=, I expect:
1. The configured BindPaths to be available and accessible to the unit's user
2. The UMask to be applied to the running process

**Unexpected behaviour you saw**
When configuring a too restrictive UMask missing `o+x` (e.g. `UMask=0007`), the configured BindPaths are inaccessible to units running as unpriveledged users.

**Steps to reproduce the problem**

Minimal reproducer:

1. SystemD-Unit `/etc/systemd/system/umasktest.service`

```ini
[Unit]
Description=UMask testing

[Service]
Type=oneshot
User=nobody
Group=nobody
TemporaryFileSystem=/tmp:ro
BindPaths=/tmp/subdir/subsub
; Fails
UMask=0007
; Works
; UMask=0006
ExecStartPre=ls -lahd /tmp/subdir
ExecStart=/tmp/subdir/subsub/script.sh
```

2. Filesystem Setup

```
$ ls -lahd /tmp /tmp/subdir /tmp/subdir/subsub /tmp/subdir/subsub/script.sh
drwxrwxrwt 20 root root 400 Jun 11 21:50 /tmp
drwxr-xr-x  3 root root  60 Jun 11 21:46 /tmp/subdir
drwxr-xr-x  2 root root  60 Jun 11 21:47 /tmp/subdir/subsub
-rwxr-xr-x  1 root root  36 Jun 11 21:47 /tmp/subdir/subsub/script.sh
```

3. Script `/tmp/subdir/subsub/script.sh`

```bash
#!/usr/bin/env bash

echo "TEST OK"
```

Then start the unit by running `systemctl start umasktest.service`.
Journal-Output for this `UMask=0007`:

```
Jun 11 21:52:48 $HOST systemd[1]: [🡕] /etc/systemd/system/umasktest.service:6: Special user nobody configured, this is not safe!
Jun 11 21:52:48 $HOST systemd[1]: Starting UMask testing...
Jun 11 21:52:48 $HOST ls[4075925]: drwxr-x--- 3 root root 60 Jun 11 21:52 /tmp/subdir
Jun 11 21:52:48 $HOST systemd[4075926]: umasktest.service: Failed to execute /tmp/subdir/subsub/script.sh: Permission denied
Jun 11 21:52:48 $HOST systemd[4075926]: umasktest.service: Failed at step EXEC spawning /tmp/subdir/subsub/script.sh: Permission denied
Jun 11 21:52:48 $HOST systemd[1]: umasktest.service: Main process exited, code=exited, status=203/EXEC
Jun 11 21:52:48 $HOST systemd[1]: umasktest.service: Failed with result 'exit-code'.
Jun 11 21:52:48 $HOST systemd[1]: Failed to start UMask testing.
```
As can be seen, execution of the unit fails to execute `/tmp/subdir/subsub/script.sh`, most likely because `nobody` may not traverse through `/tmp/subdir`.

If one switches to `UMask=0006`, all works as intended:
```
Jun 11 21:53:20 $HOST systemd[1]: [🡕] /etc/systemd/system/umasktest.service:6: Special user nobody configured, this is not safe!
Jun 11 21:53:20 $HOST systemd[1]: Starting UMask testing...
Jun 11 21:53:20 $HOST ls[4075977]: drwxr-x--x 3 root root 60 Jun 11 21:53 /tmp/subdir
Jun 11 21:53:20 $HOST script.sh[4075978]: TEST OK
Jun 11 21:53:20 $HOST systemd[1]: umasktest.service: Deactivated successfully.
Jun 11 21:53:20 $HOST systemd[1]: Finished UMask testing.
```

As can be seen, the permission for `/tmp/subdir` differ between the two `UMask=-values`, and syncs with the contained in- or exclusion of `o+x`.

I would assume that this is the effect of applying the umask value too early (Please note: this is just guesswork and grepping through unfamiliar sources, so I might be wrong):
When executing a child, [umask](https://github.com/systemd/systemd/blob/756755d0fc5a0ef380416a54346b6438c3fb7ba5/src/core/execute.c#L4137) is applied before [mount namespaces](https://github.com/systemd/systemd/blob/756755d0fc5a0ef380416a54346b6438c3fb7ba5/src/core/execute.c#L4259) are set up. As bindmounting entails creating parent directories for nested filesystem hierarchies within [apply_one_mount](https://github.com/systemd/systemd/blob/756755d0fc5a0ef380416a54346b6438c3fb7ba5/src/core/namespace.c#L1368) and thus creating new directories, those are already subject to the new umask, resulting in inaccessible directories.
Probably, it is sufficient to move the umask call after the namespace-setup code. Unfortunately, I do not know if this has any functional or security implications, and do not have a devsetup at hand to test this without potentially bricking my device.

Thank you for reading so far, please let me know if I can be of any further assistance or you have any questions. I'm sorry if this is documented and expected behaviour and I've thus wasted your time. However I could not find anything in this regard within the docs.
   ~ Simon

### PR DESCRIPTION
**Pull request by poettering**
Fixes #19899

### CODE REVIEW

**Review by bluca — APPROVED** [review]
lgtm - maybe enhancing one of the tests that use MountAPIVFS would be nice, to avoid regressions

**Comment by bluca** [comment]
> lgtm - maybe enhancing one of the tests that use MountAPIVFS would be nice, to avoid regressions

the bug has a minimal repro attached, so should be easy to integrate?

**Comment by poettering** [comment]
Added a test inspired by the original reproducer. Updating green label.

**Comment by keszybz** [comment]
LGTM too.

**Pull request merged**
