### PR TITLE
udev: support -= operator for SYMLINK

### LINKED ISSUE #24607: udev: support SYMLINK-=
### systemd version the issue has been seen with

237, 250, 251

### Used distribution

Ubuntu 18.04, Fedora 36, Archlinux

### Linux kernel version used

5.19.6-lqx1.0.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

udev rule files

### Expected behaviour you didn't see

Symlink `/dev/test` shouldn't exist

### Unexpected behaviour you saw

Symlink `/dev/test` was created

### Steps to reproduce the problem

We have a number of system rules we want to override, but the "official" way with copying a `.rules` file is fragile, because the system file may change upon packages update, file names may change, so everything will silently break. So instead we use `-=` to remove from lists unwanted names, which is expected to work per `man udev`. Well, it actually doesn't 🤷

Steps to reproduce in terms of terminal commands:

```
# echo 'ENV{DEVTYPE}=="disk", SYMLINK+="test"' > /etc/udev/rules.d/98-test.rules
# echo 'ENV{DEVTYPE}=="disk", SYMLINK-="test"' > /etc/udev/rules.d/99-test.rules
# udevadm control --reload-rules && udevadm trigger
# ls /dev/test
/dev/test
```

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Replaces #9463.
Closes #24607.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @fbuihuu

**Comment by fbuihuu** [comment]
Since it's a pretty old request I'm not sure if it's still needed. @mwilck any opinion ? can this still be useful for you ?

**Comment by Hi-Angel** [comment]
> Since it's a pretty old request I'm not sure if it's still needed. @mwilck any opinion ? can this still be useful for you ?

I'm not sure if I correctly understand your question, but that addresses a bug that any user trying to override udev rules will stumble upon. I did in particular, the PR refers my recent bugreport.

**Comment by Hi-Angel** [comment]
There's also [a stackoverflow answer](https://stackoverflow.com/a/73661279/2388257) that refers this and other bugs.

**Comment by mwilck** [comment]
> Since it's a pretty old request I'm not sure if it's still needed. @mwilck any opinion ? can this still be useful for you ?

Yes I think the idea from #9463 could still  be helpful on some systems.

**Comment by poettering** [comment]
i think the usecase is garbage, people shouldn't do that. but patch looks good and i guess closes a gap in systematic behaviour.

**Comment by poettering** [comment]
fix the rules that create them in the first place? why have rules in effect that add a lot of stuff you then end up dropping again?

**Comment by arvidjaar** [comment]
> fix the rules that create them in the first place?

There is no way to disable single rule and replacing the whole ruleset file will inevitably cause problems in the future when the content of this file will change, This PR actually is as close to "disable single rule" as you can get.

**Comment by Hi-Angel** [comment]
> fix the rules that create them in the first place? why have rules in effect that add a lot of stuff you then end up dropping again?

@arvidjaar already commented on that, but just to clarify: the "rules that create them in the first place" come with the distro as part of systemd package. What you can do? Delete them? But they will appear again on update. Try to upstream them to systemd? Well, nobody will want them due to being too custom. E.g. at my work AFAIR we do want symlinks created, but they should have special names with UUIDs, which are different from what systemd creates by default. So we want to override systemd defaults. You would not want these changes upstream, they don't make much sense aside the specific usecase at my work.

So overall, I don't really imagine how your suggestion could be implemented.

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
> @arvidjaar already commented on that, but just to clarify: the "rules that create them in the first place" come with the distro as part of systemd package. What you can do? Delete them? But they will appear again on update. 

systemd places its rules in /usr/lib/udev/rules.d/. Files in /etc/udev/rules.d/ with the same name will override them. If you place a symlink to /dev/null in /etc/udev/rules.d/ then it will "mask" them, i.e. disable entirely.

/usr/lib/udev/rules.d/ is where rpm puts stuff.

/etc/udev/rules.d/ is where the admin can put stuff and then *override* the same stuff from rpm, and whatever rpm does it won't override your personal changes in /etc/udev/rules.d.

> Try to upstream them to systemd? Well, nobody will want them due to being too custom. E.g. at my work AFAIR we do want symlinks created, but they should have special names with UUIDs, which are different from what systemd creates by default. So we want to override systemd defaults. You would not want these changes upstream, they don't make much sense aside the specific usecase at my work.

why don't you create the upstream names *and* your local names?

but anyway, if you reconfigure the whole symlink creation, then the right approach is to disconnect yourself from upstream's symlink choices, i.e. copy /usr/lib/udev/rules.d/60-persistent-storage.rules to /etc/udev/rules.d/60-persistent-storage.rules and then edit it there to your liking. rpm won't fuck with that, and udev will reads yours, not the masked rpm version.

(we have similar mechanisms in *all* systemd tools btw. it's always the same: stuff in /etc/ with the same name will override stuff in /usr/).

Anyway, SYMLINK-= is frickin' hack for people who can't read docs. not more.

**Comment by poettering** [comment]
Also note, we honour the udev var UDEV_DISABLE_PERSISTENT_STORAGE_RULES_FLAG. If it is set, we'll not create a single block device symlink for you.

**Comment by poettering** [comment]
anyway, so far all usecases for SYMLINK-= people came up with originate in a misunderstanding how configuration handling in systemd works.

**Comment by mwilck** [comment]
> /etc/udev/rules.d/ is where the admin can put stuff and then override the same stuff from rpm, and whatever rpm does it won't override your personal changes in /etc/udev/rules.d.

Sure. But it's all-or-nothing. It means that you'll silently miss any updates that the distribution might ship. With `SYMLINK-=`, you can benefit from the distro's updates and apply small corrections. Compare this to systemd's drop-in directories.

**Comment by Hi-Angel** [comment]
Did you even read the discussion about the usecase for `-=`? I'm asking because you wrote a wall of text and 3 comments and even claimed I didn't read documentation whereas the only point you make "override systemd rules by creating `.rules` file named similarly" and the point have been debunked multiple times in this and the other discussion.

To avoid repeating myself, I'll just quote two comments [from here](https://github.com/systemd/systemd/pull/9463, I think they are good ones, and note that they make 2 *separate* points about why overriding the full file is bad:

> Overriding system files is obviously a worse solution. It's exactly what we have at $WORK ATM, and this resulted in problems when updating system packages to newer versions, because those changed both the file content and their names, so the overrides just silently break.
> […]
> I care more about maintanability. When you have in git a full `.rules` copy, it is hard to figure out which changes were done by developers, and which ones weren't. I can think of ways to make it easier, but ideally I'd prefer to just keep files that only have our changes and nothing else. The workaround would solve that problem.

**Comment by Hi-Angel** [comment]
> the only point you make

Sorry, not the only one *(there's a suggestion about keeping symlinks)*, but it's the main one.

**Comment by poettering** [comment]
moreover, i really don't grok the point of disabling systemd's own symlink names. These things are API in  a way, we generate them for example if you specify UUID= or PARTUUID= or LABEL= in fstab, or we generate them in gpt-auto-generator too for the stuff we find. if you take them away all these things will suddently break.

So, you said you want your own names. Fine, but that's not a reason to remove the standard names? Why would you? Unless your intent is breaking API there's nor eason to do so.

You are aware that you basically can establish as many symlinks as you like, right?

**Comment by Hi-Angel** [comment]
> You are aware that you basically can establish as many symlinks as you like, right?

I asked a colleague why we do this. Apparently, it's performance related: if there are multiple symlinks to the same device, that would make zfs scan multiple times the same device *(or at least that was that way with an older version)* searching for imports. Also, I don't know if LVM utilities aren't a subject to the same problem, may well be.

You might say that should be fixed in ZFS and LVM, and I'd wholeheartedly agree with you. I will remember this in case we could do that. But that's kinda hard, because I am basically the only one in team who try to make us contribute changes to upstream projects, and obviously there are other tasks I'm busy with as well.

**Comment by poettering** [comment]
i am sorry what? zfs iterates through /dev/ and follows symlinks there? that's amazingly broken. consult the udev db, that's what it is for.

generally, when there's a fuckup somewhere, fix it were it is, don't fix it in systemd/udev. Given that zfs and lvm are all open source a fix to their codebase is as much possible as to ours and everyone will win.

**Comment by mwilck** [comment]
@poettering, there's also the fact that udev carries technical debt in the form of certain symlinks. systemd maintainers are conservative about this, for fear of regressions, and distribution maintainers are even more conservative. In some situations, on some systems, it can be beneficial to remove some of the, and `SYMLINK-=`  simplifies that a lot for end users.

**Comment by poettering** [comment]
which technical debt do you mean specifically?

if you care about technical debt, i doubt a great approach is to add even more workarounds on top. that *increases* technical debt, doesn't lower it.

**Comment by yuwata** [comment]
The feature should be only used by administrators to tentatively disable symlinks requested by rules provided by their distribution (that is, files in /usr/lib/udev), and should not be used by any packaged rules.

We usually support drop-in config to enable/disable/modify settings provided by packaged unit files. But, udev rules files do not (and mostly cannot) support such drop-in style of override. Supporting '-=' for `SYMLINK` should be an alternative way to override the default settings.

I cannot follow why the above discussion is so heated. But this PR is just for the above mentioned overriding, and not for anything other than that. (Of course, people may start to use the feature in an unexpected way, but who cares?)

**Comment by mwilck** [comment]
> which technical debt do you mean specifically?

I meant symlinks that used to be useful but are not any more, or are only useful on very few old systems while being problematic on others. There are a few such symlink types e.g. for SCSI. The way SCSI devices are identified has changed over the years, and e.g. the combination of vendor/model/serial number, which used to be a reliable ID, isn't any more (again, there are exceptions).

I realize that upsteam is less affected by this than I thought. It seems to be rather a distribution problem. Distributions are very conservative wrt removing symlinks that used to exist, or replaced the symlink for a given device, for good reason. If someone uses a symlink like this to refer to device in `fstab` or anywhere else, and we simply repace this symlink with an arguably "better" one (like NAA identifier instead of vendor/device/serial), this users's system will fail to boot and that's what distributions tend to try to avoid. Therefore our policy (at SUSE/openSUSE at least) has been to *add*  the symlinks rather than replace the previous ones. But this has the side effect that symlinks have accumulated over time. This is *technical debt*, no doubt about  that, but one which is hard to avoid when you must support production systems that run over a decade or more.

Adding `-=` gives us the chance to fix issues on end-user systems with such old symlinks without replacing the entire rule set.

Side note: this change makes `SYMLINK` behave like the man page says, and like other udev "keys" behave, which improves consistency and is a good thing by itself, IMO.

**Comment by poettering** [comment]
Legacy symlinks don't cost much. Just leave them in as long as you want. But adding in udev rules to remove them again after they have been added is just piling on technical debt, locally. Sounds like a really terrible way to make a bad problem worse.

But anyway, I admit, it makes sense to close the gap in being systematic here, and it was merged. But the usecases still are flawed.

**Comment by mwilck** [comment]
> Legacy symlinks don't cost much

The problem is: sometimes they do. Some storage systems use the same vendor/model/serial combination for all LUNs, which may be thousands, and this leads to lengthy repetitions in the symlink-claiming code. OTOH, there are still some devices out there that need these symlinks to be present.

**Comment by poettering** [comment]
it sounds to me as if suse's additions (which are apparently quite problematic, as you describe) would be split out into their own rules file that can easily be masked out. or alternatively condition them with some prop check such as ID_SUSE_BROKEN_COMPAT_SYMLINKS, and then tell people to set that prop to "0" or so to turn off that stuff.

Both things are better than to suggest people to use SYMLINKS-=...

**Pull request merged**
