### PR TITLE
meson: allow the linker to be overridden

### LINKED ISSUE #6169: meson: provide an option to build withouth gold
The gold linker is regularly causing issues on various architectures in Debian.
I also noticed, that gold produces slightly bigger binaries while only being marginally faster.
I would therefor suggest to either switch to the default linker or provide an option which allows distros to disable gold.

### PR DESCRIPTION
**Pull request by keszybz**
Fixes #6169.

### CODE REVIEW

**Comment by poettering** [comment]
isn't that configurable anyway thorugh $LD or so?

**Comment by mbiebl** [comment]
> isn't that configurable anyway thorugh $LD or so?

meson.build currently sets ```-Wl,-fuse-ld=gold``` unconditionally, if available.
I suppose you could pass ```-Wl,-fuse-ld=bfd``` or ```-Wl,-fuse-ld=ld``` via LDFLAGS, but I'm not sure which one would be picked then dependening on the order of arguments.
Depending on that sounds brittle and it would be very confusing seeing you have ```-Wl,-fuse-ld=``` set twice in your build flags when you try to analyze build logs.

**Comment by mbiebl** [comment]
@poettering you have a point though, maybe we should stop fiddling with ```-Wl,-fuse-ld=``` altogether and use the plattform default. If someone wants to use gold, then setting it via LDFLAGS is simple.

**Comment by keszybz** [comment]
Yeah, I'll rework the patch.

**Comment by keszybz** [comment]
OK, updated to just drop the setting.

**Comment by poettering** [comment]
Are the differences between gold and bfd really not relevant anymore? Wasn't there something with the function GC logic that bfd didn't implement?

Also, what about speed, are you sure bfd can match gold's speed? have any stats?

**Comment by keszybz** [comment]
Initially, I think we switched to it for better ifunc support for libsystemd-*.so compatibility, but then it turned out that ifuncs don't work everywhere (on arm IIRC). Dunno, I don't have stats, but with the meson build, linking seems hardly noticeable.

**Pull request merged**
