### PR TITLE
sd-journal: use new() instead of newa()

### PR DESCRIPTION
**Pull request by yuwata**
The size may not be under our control.

Split-out of #24974.

@DaanDeMeyer This is just a reminder. If you have a better way, feel free to replace this.

### CODE REVIEW

**Comment by keszybz** [comment]
Looks reasonable.

**Comment by poettering** [comment]
lgtm

**Comment by yuwata** [comment]
@keszybz and @poettering Thank you for the review.

@DaanDeMeyer WDYT about this? Is it OK to merge this now, and revert later when we find a better way?

**Comment by DaanDeMeyer** [comment]
Well if @poettering and @keszybz don't see any problem we can go ahead. I'm just worried that journal_file_append_entry() function is called for millions of log entries so allocating might actually be noticeable here.

**Comment by keszybz** [comment]
Can we get some measurement then? If this causes a noticable slowdown, maybe we can find a more nuanced approach.

**Comment by yuwata** [comment]
Actually, this slightly regress performance:
Without this:
```
$ time ./test-journal-flush

real	0m1.128s 
user	0m1.029s
sys	0m0.056s
```
With this:
```
$ time ./test-journal-flush

real	0m1.191s
user	0m1.098s
sys	0m0.056s
```

Without this, the test typically takes from 1.12ms to 1.18ms.
With this, from 1.18ms to 1.24ms.
Hmm...

**Comment by keszybz** [comment]
This is noticeable, and journal flushing is already something that people complain about…

Are such large arrays something that we can legitimately expect? If yes, then let's check the size and malloc() a buffer only if the size is >ALLOCA_MAX. If no, then just refuse with an error.

**Comment by yuwata** [comment]
Yeah, I will rework on this.

**Review by DaanDeMeyer — APPROVED** [review]

**Pull request merged**
