### PR TITLE
network: enable KeepConfiguration= when running on network filesystem

### LINKED ISSUE #21967: systemd-250 fails to boot with root-on-NFS
**systemd version the issue has been seen with**
 > systemd 250 (250-4-arch)

**Used distribution**
 > Arch Linux ARM

**Linux kernel version used** (`uname -a`)
> `Linux 5.10.89-1-rpi-legacy-ARCH #1 SMP Sun Jan 2 13:38:35 AEST 2022 armv7l GNU/Linux`

**CPU architecture issue was seen on**
 > ARMv7h 32-bit, Raspberry Pi

**Expected behaviour you didn't see**
 > I expected the system to boot normally as it did with systemd-249.5 and earlier.

**Unexpected behaviour you saw**
 > System froze during boot, with kernel messages saying the NFS server providing the root filesystem is not responding.  The system stops responding to pings at this point as well, suggesting the network interface used for the root filesystem was brought down but not brought back up again.

**Steps to reproduce the problem**
 > Boot a machine with its root filesystem on NFS.  Observe it works perfectly with systemd 249.5 and earlier, but it does not finish booting with systemd 250.  Observe that the machine responds to pings during the boot process until the freeze, at which point it stops responding to pings.

**Additional program output to the terminal or log subsystem illustrating the issue**

Reverting to systemd 249.5 resolves the problem.

I am still working on getting useful output from the debug logs.  Sometimes the kernel complains that the `systemd-udevd` process blocked for more than 120 seconds.  If I enable debugging output via a serial console, the last lines of output I get are:
```text
[  136.362428] systemd-udevd[221]: kprobe: Device processed (SEQNUM=1139, ACTION=add)
[  136.362855] systemd-udevd[223]: armv7_cortex_a7: sd-device-monitor: Passed 158 byte to netlink monitor
[  136.363271] systemd-udevd[221]: kprobe: sd-device-monitor: Passed 149 byte to netlink monitor
[  136.363685] systemd-udevd[219]: cam1_regulator: Device ready for processing (SEQNUM=1145, ACTION=add)
[  136.364166] systemd-udevd[222]: arm-pmu: /usr/lib/udev/rules.d/50-udev-default.rules:14 Importing properties from results of builtin command 'hwdb --subsyst'
[     *] (2 of 3) A start job is running for...e Configured (1min 58s / no limit)
```
I am booting with the command line parameters `systemd.log_level=debug systemd.log_target=console systemd.journald.forward_to_console=1 console=ttyAMA0,115200`.

If there is a way to narrow down the output to only udev or only systemd-networkd let me know, as I am suspecting this is where the issue is.  It seems like systemd is trying to reconfigure the network interface being used for the root filesystem, and while the interface is down, it is trying to access the root filesystem.  Since NFS blocks the process until the server can be contacted again, it would appear this results in a deadlock (NFS is waiting for the network, and systemd is waiting for NFS before restoring the network).

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #21967.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
Hmm, is this really the right thing to do?

Wouldn't it make more sense to check if root fs is network fs? i.e. fstype_is_network() style check?

**Comment by poettering** [comment]
I mean, the nfsroot stuff could also be implemented by an initrd, where things are different...

I figure if we could detect if network was configured by kernel via cmdline (i.e. not by initrd) + use network rootfs, then we should imply KeepConfiguration=...

Can we reasonably detect that?

**Comment by bluca** [comment]
> Hmm, is this really the right thing to do?
> 
> Wouldn't it make more sense to check if root fs is network fs? i.e. fstype_is_network() style check?

Isn't that what the pr is doing, by checking the nfsroot= kernel command line option?

**Comment by poettering** [comment]
> Isn't that what the pr is doing, by checking the nfsroot= kernel command line option?

Well, the root fs might be mounted by other means too, and NFS is not the only network fs. i.e. it should be a simpler and safer check to verify the effect of such a switch than to try to second guess the kernel on parsing the switch again, on our own.

**Comment by yuwata** [comment]
@poettering and @bluca Updated. Now the default value of `KeepConfiguration=` is determined by if the root filesystem is a network filesystem, or networkd is running in initrd. PTAL.

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
```
 389/1264 test-networkd-conf                                                                                                              FAIL             0.25s   killed by signal 11 SIGSEGV
>>> PATH=/home/runner/work/systemd/systemd/build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin SYSTEMD_LANGUAGE_FALLBACK_MAP=/home/runner/work/systemd/systemd/src/locale/language-fallback-map MALLOC_PERTURB_=190 /home/runner/work/systemd/systemd/build/test-networkd-conf
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stderr:
filename:1: Failed to extract DUID type from '', ignoring.
"" → 0 (Success)
"link-layer-time" → 1 (Success)
"link-layer-time:2000-01-01 00:00:00 UTC" → 1 (Success)
"vendor" → 2 (Success)
filename:1: Invalid syntax, ignoring: vendor:2000-01-01 00:00:00 UTC
"vendor:2000-01-01 00:00:00 UTC" → 0 (Success)
"link-layer" → 3 (Success)
filename:1: Invalid syntax, ignoring: link-layer:2000-01-01 00:00:00 UTC
"link-layer:2000-01-01 00:00:00 UTC" → 0 (Success)
"uuid" → 4 (Success)
filename:1: Invalid syntax, ignoring: uuid:2000-01-01 00:00:00 UTC
"uuid:2000-01-01 00:00:00 UTC" → 0 (Success)
filename:1: Failed to parse DUID type 'foo', ignoring.
"foo" → 0 (Success)
filename:1: Failed to parse DUID type 'foo', ignoring.
"foo:2000-01-01 00:00:00 UTC" → 0 (Success)
"" → "" (Success)
"00:11:22:33:44:55:66:77" → "0011223344556677" (Success)
"00:11:22:" → "001122" (Success)
filename:1: Invalid length - DUID byte: 000, ignoring assignment: 000:11:22.
"000:11:22" → "" (Success)
filename:1: Invalid length - DUID byte: 111, ignoring assignment: 00:111:22.
"00:111:22" → "" (Success)
"0:1:2:3:4:5:6:7" → "0001020304050607" (Success)
"11::" → "11" (Success)
filename:1: Invalid length - DUID byte: abcdef, ignoring assignment: abcdef.
"abcdef" → "" (Success)
filename:1: Max DUID length exceeded, ignoring assignment: 0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:10:11:12:13:14:15:16:17:18:19:1a:1b:1c:1d:1e:1f:20:21:22:23:24:25:26:27:28:29:2a:2b:2c:2d:2e:2f:30:31:32:33:34:35:36:37:38:39:3a:3b:3c:3d:3e:3f:40:41:42:43:44:45:46:47:48:49:4a:4b:4c:4d:4e:4f:50:51:52:53:54:55:56:57:58:59:5a:5b:5c:5d:5e:5f:60:61:62:63:64:65:66:67:68:69:6a:6b:6c:6d:6e:6f:70:71:72:73:74:75:76:77:78:79:7a:7b:7c:7d:7e:7f:80.
"0:1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:10:11:12:13:14:15:16:17:18:19:1a:1b:1c:1d:1e:1f:20:21:22:23:24:25:26:27:28:29:2a:2b:2c:2d:2e:2f:30:31:32:33:34:35:36:37:38:39:3a:3b:3c:3d:3e:3f:40:41:42:43:44:45:46:47:48:49:4a:4b:4c:4d:4e:4f:50:51:52:53:54:55:56:57:58:59:5a:5b:5c:5d:5e:5f:60:61:62:63:64:65:66:67:68:69:6a:6b:6c:6d:6e:6f:70:71:72:73:74:75:76:77:78:79:7a:7b:7c:7d:7e:7f:80" → "" (Success)
"1:2:3:4:5:6:7:8:9:a:b:c:d:e:f:10:11:12:13:14:15:16:17:18:19:1a:1b:1c:1d:1e:1f:20:21:22:23:24:25:26:27:28:29:2a:2b:2c:2d:2e:2f:30:31:32:33:34:35:36:37:38:39:3a:3b:3c:3d:3e:3f:40:41:42:43:44:45:46:47:48:49:4a:4b:4c:4d:4e:4f:50:51:52:53:54:55:56:57:58:59:5a:5b:5c:5d:5e:5f:60:61:62:63:64:65:66:67:68:69:6a:6b:6c:6d:6e:6f:70:71:72:73:74:75:76:77:78:79:7a:7b:7c:7d:7e:7f:80" → "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f80" (Success)
filename:1: Not a valid MAC address, ignoring assignment: no:ta:ma:ca:dd:re
filename:1: Not a valid MAC address, ignoring assignment: aa:bb:cc:dd:ee:fx
filename:1: Not a valid MAC address, ignoring assignment:  aa:bb:cc:dd:ee:ff
filename:1: Not a valid MAC address, ignoring assignment: aa:bb:cc:dd:ee:ff 	
filename:1: Not a valid MAC address, ignoring assignment: aa:bb:cc:dd:ee:ff 	
xxx
filename:1: Not a valid MAC address, ignoring assignment: aa:bb:cc: dd:ee:ff
filename:1: Not a valid MAC address, ignoring assignment: aa:bb:cc:d d:ee:ff
filename:1: Not a valid MAC address, ignoring assignment: aa:bb:cc:dd:ee
filename:1: Not a valid MAC address, ignoring assignment: 9:aa:bb:cc:dd:ee:ff
filename:1: Not a valid MAC address, ignoring assignment: aa:bb:cc:dd:ee:ff:gg
filename:1: Not a valid MAC address, ignoring assignment: 123.4567.89ab.
filename:1: Not a valid MAC address, ignoring assignment: aabbcc.ddeeff
filename:1: Not a valid MAC address, ignoring assignment: aabbccddeeff
filename:1: Not a valid MAC address, ignoring assignment: aabbccddee:ff
filename:1: Not a valid MAC address, ignoring assignment: 012345.6789ab
filename:1: Not a valid MAC address, ignoring: no:ta:ma:ca:dd:re
filename:1: Not a valid MAC address, ignoring: aa:bb:cc:dd:ee:fx
filename:1: Not a valid MAC address, ignoring: xxx
filename:1: Not a valid MAC address, ignoring: aa:bb:cc:
filename:1: Not a valid MAC address, ignoring: dd:ee:ff
filename:1: Not a valid MAC address, ignoring: aa:bb:cc:d
filename:1: Not a valid MAC address, ignoring: d:ee:ff
filename:1: Not a valid MAC address, ignoring: aa:bb:cc:dd:ee
filename:1: Not a valid MAC address, ignoring: 9:aa:bb:cc:dd:ee:ff
filename:1: Not a valid MAC address, ignoring: aa:bb:cc:dd:ee:ff:gg
filename:1: Not a valid MAC address, ignoring: 123.4567.89ab.
filename:1: Not a valid MAC address, ignoring: aabbcc.ddeeff
filename:1: Not a valid MAC address, ignoring: aabbccddeeff
filename:1: Not a valid MAC address, ignoring: aabbccddee:ff
filename:1: Not a valid MAC address, ignoring: 012345.6789ab
filename:1: Not a valid MAC address, ignoring: aa:bb:cc:dd:ee:fx
filename:1: Not a valid MAC address, ignoring: hogehoge
filename:1: Not a valid MAC address, ignoring: aaaa
filename:1: Invalid address '', ignoring assignment: Invalid argument
```

**Comment by yuwata** [comment]
Ouch.

**Comment by poettering** [comment]
looks ok to me.

**Comment by yuwata** [comment]
Test is updated. Setting the green label.

**Pull request merged**
