### PR TITLE
Add accelerometer quirk for HP Pavilion CW0xxx

### PR DESCRIPTION
**Pull request by brietaylor**

### CODE REVIEW

**Comment by poettering** [comment]
lgtm. /cc @hadess

**Comment by hadess** [comment]
For all HP laptops, this is the same problem as:
https://github.com/systemd/systemd/issues/5160

Maybe @dsd has had the chance to look into it?

**Comment by poettering** [comment]
@hadess so not merge this one?

**Comment by hadess** [comment]
> @hadess so not merge this one?

Not until somebody figures it out for all the HP laptops. They're currently all broken.

**Comment by poettering** [comment]
OK, then let's close this as duplicate of #5160.

**Comment by jefftaylor42** [comment]
> Not until somebody figures it out for all the HP laptops. They're currently all broken.

Not sure I follow.  #5160 is just an orientation problem, right? (lots of other stuff happening in that thread, but that seems to be the main issue?)  I added a quirk for this laptop because that's what I have available to test with.

Are you proposing someone should try to add all the HP quirks at the same time?  Or have I misunderstood #5160?

Thanks,
Jeff

**Comment by hadess** [comment]
> Not sure I follow. #5160 is just an orientation problem, right? (lots of other stuff happening in that thread, but that seems to be the main issue?) I added a quirk for this laptop because that's what I have available to test with.
> 
> Are you proposing someone should try to add all the HP quirks at the same time? Or have I misunderstood #5160?

The problem is that the device as implemented in the kernel, for all HP laptops, is in the wrong orientation. This driver also has quirks. We need to figure out whether we want to modify the kernel driver, or, have a single mount-matrix for all HP computers that use this particular device driver.

I think the latter might be the easiest way to do things, with quirks specific to each HP laptop being added to the HP driver.

**Pull request closed without merging**
