### PR TITLE
Check return value of pam_get_item/pam_get_data functions

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by bluca** [comment]
Any specific reasons these are being added?

**Comment by poettering** [comment]
hmm, we don't relly need these fields to work, hence we ignore failures on them. Any specific reason you think that's wrong to do?

**Comment by ret2libc** [comment]
AFAIK it is good practice to check the return values of PAM functions. This is done in all places in pam_systemd_home.c and I don't think it's too different from these uses in pam_systemd. If PAM returns something different from those expected values it's probably better to just fail instead of keep calling PAM functions and maybe even return PAM_SUCCESS at the end. Considering this is a very important piece of the authentication process where logind is made aware of a session I think it should try to check everything.

**Comment by jacekmigacz** [comment]
> hmm, we don't relly need these fields to work, hence we ignore failures on them. Any specific reason you think that's wrong to do?

Actually we do. As example `display` is assumed to be either NULL, empty or successful-call's value:
https://github.com/jacekmigacz/systemd/blob/63878c52beec442f1b3314ca223e54c897de499b/src/login/pam_systemd.c#L722
Same applies for `service`, `tty`, `remote_user` and `remote_host` from this section.

**Comment by keszybz** [comment]
I think we can merge this. The failures from those calls would signify either some error in how we call the functions (which is unlikely since the module works as expected), or some pam state fuckup (also unlikely, but if it happens, I think it's better to fail). It's one of those cases where the check is unlikely to make a difference, but it's low-cost and it seems marginally better to have than not.

**Comment by poettering** [comment]
we should probably add pam_get_item_and_log()/pam_get_data_and_log() helpers for this

**Pull request merged**
