### PR TITLE
libsystemd-network: LLDP export sd_lldp_packet_append*

### PR DESCRIPTION
**Pull request by ssahani**
1. Export the lldp append APIS. This is will be useful for
   externals use.

### CODE REVIEW

**Comment by teg** [comment]
What exactly is the intended usecase for this?

**Comment by ssahani** [comment]
As of now we don't  export sd_lldp_packet_append_\* 

This is useful for the external programs to use sd-lldp as a library  for the TX part. 
We already have the RX part exported . The TX part of the APIs will help to form LLDP packets and 
send them across network.

For example:

```
sd_lldp_packet_new();                                                                                                                                          
sd_lldp_packet_append_bytes(m, &ether, sizeof(struct ether_header));                                                                                             
sd_lldp_packet_close_container(m); 
```

**Comment by teg** [comment]
I'm not sure we want to expose these low-level functions though. Wouldn't a consumer want high-level stuff?

**Comment by ssahani** [comment]
I agree .

**Pull request closed without merging**
