### PR TITLE
sd-bus: Async properties callbacks

### PR DESCRIPTION
**Pull request by igo95862**
https://github.com/systemd/systemd/commit/532056696bc6d12dcb8291c812fc02175ff4453e this commit makes properties callbacks being able to return positive integer to indicate that the response will be handled async. (just like methods callbacks can)

https://github.com/systemd/systemd/commit/b58bf3f3503508cf23fd1ebf65db0806c59bc89d This commit fixes test cases returning 1 in some cases even though they did not want async handle.

I ran the test cases and they work without issues.

I think there should be a documentation that if you make an async property callback its your responsibility to close the message. I can add that to man page.

Fixes: https://github.com/systemd/systemd/issues/18193

### CODE REVIEW

**Comment by poettering** [comment]
Hmm? I don't get this? As reaction to GetAll() we call a bunch of property handlers, how is this patch handling that?

In general, client sides generally assume (in particular gdbus) that properties are "cheap" to acquire, can be cached and cannot fail. Asynchronous behaviour for handling them hence is against these assumption, since that suggests they are slow, require work to acquire and thus are more likely to fail.

hence, the PR doesn't make too much sense to me?

**Comment by igo95862** [comment]
> As reaction to GetAll() we call a bunch of property handlers, how is this patch handling that?

Well it does not...

However, there is `SD_BUS_VTABLE_PROPERTY_EXPLICIT` flag is used  ' because the value is large or slow to calculate'. I looked at source code and it seems like 'GetAll' will skip over those methods. Maybe allow async properties only with that flag set?

**Comment by igo95862** [comment]
After thinking about it I probably won't need async properties. However, I think it should be documented that properties are always sync. Currently there is no mention of this in man pages.

**Comment by poettering** [comment]
yeah, a patch for the man page would be lovely!

**Pull request closed without merging**
