### PR TITLE
journal: Hole punching improvements

### PR DESCRIPTION
**Pull request by daandemeyer**
Let's do fixed size reads that aren't affected by the disk block
size. This commit also updates the logic to use the same buffer
size as copy.h and various smaller style fixes.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Hopefully fixes #21675

**Comment by mrc0mmand** [comment]
Looks like the delay is almost gone:

```
Dec 15 19:40:11 n47.dusty.ci.centos.org systemd-networkd[239271]: eth0: Link state is up-to-date
Dec 15 19:40:11 n47.dusty.ci.centos.org systemd-networkd[239271]: eth0: State changed: initialized -> unmanaged
Dec 15 19:40:11 n47.dusty.ci.centos.org systemd-networkd[239271]: eth0: State changed: initialized -> unmanaged
Dec 15 19:40:12 n47.dusty.ci.centos.org kernel: device test1 entered promiscuous mode
Dec 15 19:40:12 n47.dusty.ci.centos.org systemd-journald[915]: Failed to write entry (26 items, 768 bytes), rotating before retrying: Argument list too long
Dec 15 19:40:11 n47.dusty.ci.centos.org audit: ANOM_PROMISCUOUS dev=test1 prom=256 old_prom=0 auid=4294967295 uid=982 gid=982 ses=4294967295
Dec 15 19:40:11 n47.dusty.ci.centos.org audit[239271]: SYSCALL arch=c000003e syscall=44 success=yes exit=32 a0=3 a1=1e66a70 a2=20 a3=0 items=0 ppid=1 pid=239271 auid=4294967295 uid=982 gid=982 euid=982 suid=982 fsuid=982 egid=982 sgid=982 fsgid=982 tty=(none) ses=4294967295 comm="systemd-network" exe="/usr/lib/systemd/systemd-networkd" subj=system_u:system_r:systemd_networkd_t:s0 key=(null)
Dec 15 19:40:11 n47.dusty.ci.centos.org audit: PROCTITLE proctitle="/usr/lib/systemd/systemd-networkd"
```

The messages are still out of order, but I'm not sure how much of a deal that actually is.

**Comment by bluca** [comment]
focal-ppc64el also passes

**Review by bluca — APPROVED** [review]

**Review by yuwata — APPROVED** [review]
LGTM. But which commit fixes the issue?

**Comment by DaanDeMeyer** [comment]
I think the first commit is what fixes the issue. We were doing an enormous amount of hole punching since there can be hundreds of thousands of entry arrays in a journal file.

The second commit is also a fix that I don't think what was causing the issue but definitely also a bug since it potentially causes us to skip entry arrays.

Third and fourth commit are mostly simplifications.

**Comment by bluca** [comment]
all green! woop woop!

**Comment by yuwata** [comment]
@DaanDeMeyer Thanks. I slightly concern that the first commit just hide the issue...

**Comment by keszybz** [comment]
LGTM too.

**Pull request merged**
