### PR TITLE
Fix module loading from udev rule

### PR DESCRIPTION
**Pull request by fbuihuu**

### CODE REVIEW

**Comment by keszybz** [comment]
Travis failed in test-seccomp. semaphore timed out.

**Comment by mrc0mmand** [comment]
@keszybz uh, why was this merged? All CentOS CIs fail during `TEST-01-BASIC` because of `sys-fs-fuse-connections.mount` which is failing...

**Comment by keszybz** [comment]
I see that now. The log is rather noisy, so I missed that in all that output.

**Comment by fbuihuu** [comment]
Are the logs still available somewhere ?

**Comment by mrc0mmand** [comment]
CentOS 7: https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos7/762/artifact/systemd-centos-ci/artifacts_vDrHiw/bootstrap-logs-upstream.IWy/sanity-boot-check.log
Arch: https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux/765/artifact/systemd-centos-ci/artifacts_QwWGzx/vagrant-logs.0eQ/vagrant-arch-sanity-boot-check.log

**Comment by mrc0mmand** [comment]
Relevant part is probably:

```
[  619.847226] mount[43]: mount: /sys/fs/fuse/connections: mount point does not exist.
```

and
```
[0;38;5;245mChild 43 (mount) died (code=exited, status=32/n/a)[0m
[0;38;5;245msys-fs-fuse-connections.mount: Failed to read oom_kill field of memory.events cgroup attribute: No such file or directory[0m
[0;38;5;245msys-fs-fuse-connections.mount: Child 43 belongs to sys-fs-fuse-connections.mount.[0m
[0;1;39msys-fs-fuse-connections.mount: Mount process exited, code=exited, status=32/n/a[0m
[0;1;38;5;185msys-fs-fuse-connections.mount: Failed with result 'exit-code'.[0m
[0;38;5;245msys-fs-fuse-connections.mount: Changed mounting -> failed[0m
[0;1;38;5;185msys-fs-fuse-connections.mount: Failed to destroy cgroup /sys-fs-fuse-connections.mount, ignoring: Read-only file system[0m
[0;38;5;245msys-fs-fuse-connections.mount: Job 29 sys-fs-fuse-connections.mount/start finished, result=failed[0m
[[0;1;31mFAILED[0m] Failed to mount [0;1;39mFUSE Control File System[0m.
See 'systemctl status sys-fs-fuse-connections.mount' for details.
```

Taken from: https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/765/artifact//systemd-centos-ci/artifacts_all/artifacts_mnXzwi/vagrant-logs.jMB/vagrant-arch-sanitizers-clang-testsuite.tS5/TEST-01-BASIC_sanitizers-nspawn_FAIL.log

**Comment by fbuihuu** [comment]
So the load of fuse failed:

> modprobe@fuse.service: ConditionCapability=CAP_SYS_MODULE failed.

which makes `sys-fs-fuse-connections.mount` fail in its turn because the condition `ConditionPathExists=/sys/fs/fuse/connections` has been dropped.

which makes the main transaction fails because sysinit.target requires the mount unit.

**Comment by fbuihuu** [comment]
ah no sysinit.target has only a' Wants' dep on the mount unit. 

So the main transaction went fine, that's the test which consists in making sure that no units is in 'failed' state which fails now.

**Comment by fbuihuu** [comment]
I'm not really sure how to deal with this... maybe we could add `ConditionCapability=CAP_SYS_MODULE` to `sys-fs-fuse-connections.mount` too ?

**Comment by poettering** [comment]
Maybe downgrade:

Requires=modprobe@fuse.service → Wants=modprobe@fuse.service in the mount unit.

Also, readd the sysfs condition in the mount unit. That's safe, after all conditions are only checked *after* all deps ordered before are complete.

**Comment by fbuihuu** [comment]
> Also, readd the sysfs condition in the mount unit. That's safe, after all conditions are only checked after all deps ordered before are complete.

Correct, restoring the sysfs condition does the trick.

**Comment by fbuihuu** [comment]
fix waiting in https://github.com/systemd/systemd/pull/17677

**Pull request merged**
