### PR TITLE
cgroup: assume the use of v1 when all the preceding checks fail

### PR DESCRIPTION
**Pull request by evverx**
This patch restores the default that was changed in 2977724b09eb997fc8,
making the tools depending on it work again.

Closes: #6477 and https://github.com/lxc/lxc/issues/1669.

I'd like to thank @graysky2 for the testing and @brauner for helping me with `lxc`.

### CODE REVIEW

**Comment by poettering** [comment]
lgtm

**Comment by evverx** [comment]
Does anybody know what `test-cgroup-util` tests and how to reproduce the environment where it runs?

**Comment by evverx** [comment]
I can see the same error in https://github.com/systemd/systemd/pull/7364, so the failure doesn't seem to be related to this PR.

I'm wondering whether the test passed when it was merged in https://github.com/systemd/systemd/pull/7356. Is there anything to look at apart from http://38.145.33.116/systemd-pr/17/f0/17f01ace62fb24cee8a06c0bee64dd0db9aac4e0_dev/rpmbuild.log?

**Comment by brauner** [comment]
Hi guys! :)
Thanks @evverx for debugging this with me and writing the patch!

**Comment by keszybz** [comment]
> I'm wondering whether the test passed when it was merged in #7356.

Tests were broken (Fedora CI was disabled, and Ubuntu didn't have an updated gettext yet) when #7356 was merged. Fix waiting in #7371.

**Comment by keszybz** [comment]
```
64/247 test-unit-file                          TIMEOUT 30.03 s
```
that doesn't look right.

**Comment by evverx** [comment]
I've run `test-unit-file` on Ubuntu Artful several times without any failures. I'm not sure what exactly caused it to fail, but the output suggests that `test_unit_file_get_set` probably hung trying to get the list of unit files. I doubt the failure has anything to do with this PR. It would be nice if the failure could be somehow reproduced again, though.

**Pull request merged**
