### PR TITLE
udev-builtin-blkid: Add --filter-superblock-type and --filter-partition-type

### PR DESCRIPTION
**Pull request by credmon**
Add command-line options to udev's builtin blkid application that allow the
user to filter filesystem probing for a specific filesystem by superblock
type, and to filter filesystem probing by partition type.

ex: blkid --filter-supblock-type nilfs2
ex: blkid --filter-partition-type gpt

This change was motivated by blkid incorrectly identifying a device's
partition type as nilfs2 when it was looking at the whole device (/dev/mmcblk0).
This is because nilfs2 looks for superblocks at location 0x400, and at location
(((part_size-512)/8)*512). The data at the end of the disk in the backup
superblock was part of an ext4 partition (/dev/mmcblk0p25), but libblkid's
nilfs2 checking identified the data in the partition to have matched the
superblock magic (0x3434), but failed the CRC check. It resulted in the disk
being identified as having a nilfs2 partition with a bad checksum (SBBADCSUM),
and the udev data was tainted by values set by the nilfs2 probing routine,
affecting subsequent udev rules.

### CODE REVIEW

**Comment by arvidjaar** [comment]
This sounds like chicken and egg problem. Where filter list comes from?

**Comment by credmon** [comment]
If this code is running, it shouldn't be a chicken and egg problem. The filter list comes from the udev rule.

**Comment by arvidjaar** [comment]
`blkid` is used in udev rules precisely to detect filesystem type (among other things). Where restrictions for possible types are expected to come from?

**Comment by credmon** [comment]
There is currently no restriction on possible types detected by blkid other than the fact that the number of filesystem types supported by libblkid is finite. Adding this option is a means to achieve the goal of filtering out detectable filesystem types. An end user can setup their udev rules to filter out filesystem types if they find it is necessary.

**Comment by poettering** [comment]
I am not convinced this should really be made configurable. If you want auto-detection I figure you have to live with with the fact that auto-detection isn't totally reliable. If you don't want that then reference devices explicitly, and don't rely on auto-detection.

I think the data udev attaches about auto-detected metadata should really be taken as hint only. If you want reliable behaviour, don't use it. 

Or to say this differently: if there should be tweakability here, then I am pretty sure it should be in libblkid, but not in udev... it shouldapply to all consumers of the library (including the cmdline blkid tool), and not just udev.

I have the suspicion though that @karelzak (the libblkid maintainer) might be interested in fixing the auto-detection so that the entire problem goes away, and no tweaking might even be necesary.

Either way, I think we should close this here, and continue the discussion over at libblkid instead, do see if configurability is desired there, or if the auto-detection for this case may be made more robust in general.

I hope this makes sense.

**Comment by karelzak** [comment]
Sure, if you know about any libblkid disadvantage then I'm ready to fix/improve. It's definitely better than create any blacklists or so.

**Pull request closed without merging**
