### PR TITLE
test/TEST-18-FAILUREACTION: fix typo to actually run firstphase action

### PR DESCRIPTION
**Pull request by ddstreet**
The if test for running the firstphase of the test should be negated
so the firstphase is actually executed.

### CODE REVIEW

**Comment by ddstreet** [comment]
I'm pretty sure the TEST-18 failure is due to the older version of qemu currently being used for all systemd-upstream autopkgtests:

> [[0;32m  OK  [0m] Reached target [0;1;39mReboot[0m.
> [   30.291qemu-system-x86_64: Trying to execute code outside RAM or ROM at 0x0000000099d823e0
> This usually means one of the following happened:
> 
> (1) You told QEMU to execute a kernel for the wrong machine type, and it crashed on startup (eg trying to run a raspberry pi kernel on a versatilepb QEMU machine)
> (2) You didn't give QEMU a kernel or BIOS filename at all, and QEMU executed a ROM full of no-op instructions until it fell off the end
> (3) Your guest kernel has a bug and crashed by jumping off into nowhere
> 
> This is almost always one of the first two, so check your command line and that you are using the right type of kernel for this machine.
> If you think option (3) is likely then you can try debugging your guest with the -d debug options; in particular -d guest_errors will cause the log to include a dump of the guest register state at this point.
> 
> Execution cannot continue; stopping here.
> 

I don't get this failure with the updated qemu I use for my testing.  @martinpitt could you add me to the ubuntu ci LP team so I can add/maintain a newer qemu in the PPA used by systemd-upstream?
https://launchpad.net/~upstream-systemd-ci

**Comment by ddstreet** [comment]
> I'm pretty sure the TEST-18 failure is due to the older version of qemu currently being used for all systemd-upstream autopkgtests:
> 
...
> 
> I don't get this failure with the updated qemu I use for my testing.

@mbiebl @xnox can either of you copy the 'device-tree-compiler' and 'qemu' packages from my ppa:
https://launchpad.net/~ddstreet/+archive/ubuntu/systemd-upstream/+packages

over to the upstream-systemd-ci ppa:
https://launchpad.net/~upstream-systemd-ci/+archive/ubuntu/systemd-ci

and if you're able to add me to that team, I'd appreciate it.

**Comment by mbiebl** [comment]
My last PPA upload was a long time ago. I'll need to checkout again how to do that.

**Comment by ddstreet** [comment]
Thanks!  The qemu is updated in the Ubuntu CI ppa now, hopefully this should pass.

**Comment by yuwata** [comment]
LGTM.

**Pull request merged**
