### PR TITLE
Allow more inodes in /dev and /tmp

### PR DESCRIPTION
**Pull request by keszybz**
This is very simple solution that just raises the limits. #21626 and #21673 take more complicated approaches
that we may do anyway, but let's just raise the limits anyway.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
Maybe bump /run too? There was a report for that too

**Comment by keszybz** [comment]
Do you mean #21626? It was mistaken, afaict.

**Comment by bluca** [comment]
Ah, ok

**Comment by topimiettinen** [comment]
There is a relation between `nr_inodes` and `size` by assuming an inode size of 4k, so the memory usage limits would be roughly similar. Now 1M inodes would correspond to 4G size and 20M inodes to 80GB, or rather ineffective limits.

**Comment by keszybz** [comment]
I did a test in a VM, and it seems that the memory use grows as approx. 1500bytes / inode.

> Now 1M inodes would correspond to 4G size

/dev/ is privileged, so that's OK. The guard is there to catch silly mistakes.

> 20M inodes to 80GB

Hmm, indeed. I'll adjust the commit to 1m. It's still more than the 400k we had so far, and the memory use should be about 1.5G, which seems OK for most machines.

**Review by topimiettinen — APPROVED** [review]

**Comment by fbuihuu** [comment]
> Do you mean #21626? It was mistaken, afaict.

I don't see why it was mistake. Could you explain ?

**Comment by fbuihuu** [comment]
Honestly I still believe that setting such arbitrary limits is the wrong approach. /run is currently used by many different daemons, including udev that can creates many dirs/file. Trying to run services with PrivateRun= (suggested by @topimiettinen I think) might be a better approach as (most of) services could have its separate runtime dir.

Also there's no distinction between /dev and private /dev. In the latter case the limit should be much lower I think.

**Comment by bluca** [comment]
I think it's better to be safe than sorry. Can one change these parameters with a `mount -o remount`?

**Comment by keszybz** [comment]
> > Do you mean #21626? It was mistaken, afaict.
> 
> I don't see why it was mistake. Could you explain ?

See my commit message. I talks about /run, but the arch discussion in links to talks about /tmp.

**Comment by keszybz** [comment]
Oh, I missed that. So I think we were OK to raise the limit for /tmp, but you are right, we should do the same for /run. Please add that to #21641.

**Comment by fbuihuu** [comment]
> There is a relation between `nr_inodes` and `size` by assuming an inode size of 4k, so the memory usage limits would be roughly similar. Now 1M inodes would correspond to 4G size and 20M inodes to 80GB, or rather ineffective limits.

**Comment by keszybz** [comment]
One thing is how much memory is actually used (seems to be ~1.5k per inode, but is probably more for some other inode types). The other thing is how the kernel accounts this. Unfortunately it does not count this memory usage toward the limit, and that's what was meant by "don't take any space".

**Comment by topimiettinen** [comment]
> > There is a relation between `nr_inodes` and `size` by assuming an inode size of 4k, so the memory usage limits would be roughly similar. Now 1M inodes would correspond to 4G size and 20M inodes to 80GB, or rather ineffective limits.
> 
> @topimiettinen I'm a bit confused here because in another [comment](https://github.com/systemd/systemd/pull/21641#discussion_r763261160) you wrote:
> 
> > Devices and symlinks don't take any space, so there shouldn't be any need to not limit the size. Regular files shouldn't exist there either.

This applied to `/dev` and the fact that kernel doesn't count the memory usage (which is non-zero of course). There's no need for regular files in `/dev`, so the `size` limit could be very small. For `/tmp` and `/run` the situation is different since there should be no devices and few symlinks, so there's more direct relation.

**Pull request merged**
