### PR TITLE
Debug

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by yuwata** [comment]
@mrc0mmand Could you run the portabled test with this PR?

**Comment by mrc0mmand** [comment]
> @mrc0mmand Could you run the portabled test with this PR?

Will do!

**Comment by mrc0mmand** [comment]
Here's a journal from the failed test with this PR: https://jenkins-systemd.apps.ocp.ci.centos.org/job/ci-build/1261/artifact//artifacts_all/artifacts_youvth5o/vagrant-logs.WAp/vagrant-arch-sanitizers-clang-testsuite.0Op/TEST-29-PORTABLE/system.journal

**Comment by yuwata** [comment]
@mrc0mmand Thanks.

BTW, is it necessary to open a PR like this for running stress test on systemd-centos-ci repo? If not, I will just create a branch and send you the link.

**Comment by mrc0mmand** [comment]
> @mrc0mmand Thanks.
> 
> BTW, is it necessary to open a PR like this for running stress test on systemd-centos-ci repo? If not, I will just create a branch and send you the link.

Having a branch available should be enough, I'll tweak the internal CentOS CI logic to make it work (a simple fix).

**Pull request closed without merging**
