### PR TITLE
docs: use absolute links for our pages 

### PR DESCRIPTION
**Pull request by mrc0mmand**
Since https://github.com/systemd/systemd/commit/56b297094ab6937689d3b2021307a2ea856f95db has proven to be a no-go for us, as it breaks existing
links, let's embrace the trailing slash and use absolute links
everywhere for our pages. This way we'll get around browser cleverly
appending the relative link to the current location (since it ends with
a slash), and given our docs/ layout is flat it's not much of a hassle
either.

Converted using this beauty:
```
  $ sed -ri 's/(\[.+\]\()([A-Z_]+\))/\1\/\2/g' *.md
```
Resolves: https://github.com/systemd/systemd/issues/32088 (again) and https://github.com/systemd/systemd/issues/32310

### CODE REVIEW

**Review by yuwata — APPROVED** [review]
LGTM, at least superficially.

**Review by bluca — APPROVED** [review]

**Comment by samuelvw01** [comment]
> > Links are still broken (they need docs/ prefix and .md suffix)
> 
> What? No they aren't? I checked most of the links both in a local Jekyll instance and on https://systemd.io/, and everything seems to be in order. Do you have any example of a broken link? They don't have to be prefixed by `docs`, because the website is deployed from the `docs` directory, and the `.md` suffixes aren't supposed to be there, because the page permalink is configured with just the page title.

For example [this](https://github.com/systemd/systemd/blob/main/docs/USERDB_AND_DESKTOPS.md) (first 4 links)

**Comment by mrc0mmand** [comment]
That's expected, the docs are supposed to be rendered on our website (https://systemd.io/), we don't really care if they don't work in the GH previews.

**Comment by samuelvw01** [comment]
> That's expected, the docs are supposed to be rendered on our website (https://systemd.io/), we don't really care if they don't work in the GH previews.

Oh, okay then. Sorry for the noise.

**Pull request merged**
