### PR TITLE
TEST-50: gracefully skip parts that require openssl

### LINKED ISSUE #21719: TEST-50-DISSECT failure
Version: 250~rc2

The upstream test suite fails on Debian. One of the failing tests is TEST-50-DISSECT
```
---- /var/tmp/systemd-test.7vZ8XM/root/var/log/journal/10527707c0074fd9b009379879acd8aa ----
-- Journal begins at Fri 2021-12-10 00:07:36 UTC, ends at Fri 2021-12-10 00:08:38 UTC. --
[    0.048000] kernel: tsc: Unable to calibrate against PIT
[    2.244339] kernel: acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[   13.729582] kernel: sd 0:0:0:0: [sda] Asking for cache data failed
[   13.729667] kernel: sd 0:0:0:0: [sda] Assuming drive cache: write through
[   17.812055] systemd[1]: Failed to find module 'autofs4'
[   33.444980] systemd-tmpfiles[203]: Cannot set file attributes for '/var/log/journal', maybe due to incompatibility in specified attributes, previous=0x00080000, current=0x00080000, exp
ected=0x00880000, ignoring.
[   33.529212] systemd-tmpfiles[203]: Cannot set file attributes for '/var/log/journal/10527707c0074fd9b009379879acd8aa', maybe due to incompatibility in specified attributes, previous=0x
00080000, current=0x00080000, expected=0x00880000, ignoring.
[   52.758806] kernel: device-mapper: core: CONFIG_IMA_DISABLE_HTABLE is disabled. Duplicate IMA measurements will not be recorded in the IMA log.
[   80.762461] systemd[1]: testsuite-50.service: Failed with result 'exit-code'.
[   80.837892] systemd[1]: Failed to start testsuite-50.service.
TEST-50-DISSECT: (failed; see logs)
-rw-r----- 1 root root 8388608 Dec 10 00:08 /tmp/autopkgtest.sdmqNj/upstream-artifacts/TEST-50-DISSECT.journal
QEMU test failed
make: *** [Makefile:4: run] Error 1
make: Leaving directory '/tmp/autopkgtest.sdmqNj/tree/test/TEST-50-DISSECT'
[00:08:40] --x-- Result of TEST-50-DISSECT: 2 --x--

TEST-50-DISSECT:                    FAIL     (175 s)
```

Full log attached 
[log.txt](https://github.com/systemd/systemd/files/7689260/log.txt)

### PR DESCRIPTION
**Pull request by keszybz**
I think we should just do the easy thing and make the test pass.
Fixes #21719.

### CODE REVIEW

**Comment by bluca** [comment]
mmh I'm not convinced tbh - we have the build time knob for the feature, a combination with the build time support for openssl without the requirements for the test is a bug in the config to me.

the core logic is that we shouldn't get regression in coverage because of a mistake in how the images are built

**Comment by keszybz** [comment]
But the configuration option is for whether you have openssl-the-library installed and want to make use of it. openssl-the-binary is a separate thing. The test will still be performed if you have both.

**Comment by bluca** [comment]
> But the configuration option is for whether you have openssl-the-library installed and want to make use of it. openssl-the-binary is a separate thing. The test will still be performed if you have both.

But it's the same configuration though - at least for the debian/ubuntu CI, they are contextual, the required meson config, the build-time packages and the test-time packages. So if it's missing in the latter, it's a configuration problem.

**Comment by bluca** [comment]
Or to put it in another way: I don't think it makes sense to allow enabling build-time support for openssl but disable test-time coverage for it. I don't think there's a valid use case for it, and it's most likely just a configuration mistake (which it was indeed in the reported bug, and when we introduced it in the test code).

**Comment by keszybz** [comment]
@mbiebl what's your take on this?

**Comment by bluca** [comment]
What about logging an explicit error in testfail so that it's obvious it's missing?

**Comment by mbiebl** [comment]
> What about logging an explicit error in testfail so that it's obvious it's missing?

Yeah, I'm fine with failing the test if openssl support is enabled but not available in the test bed.  A clearer error message would have certainly been nice.

**Comment by keszybz** [comment]
I think the message is clear enough, can't do much better than "openssl: command not available". Let's close this.

**Comment by mbiebl** [comment]
> I think the message is clear enough, can't do much better than "openssl: command not available". Let's close this.

I just didn't easily spot the error message.
Maybe it would help if we had a common "ERROR: " prefix or the like which would make such errors more easily greppable.

**Comment by bluca** [comment]
I think we could make it obvious by echoing something like "openssl command not found" in /failed - that way it should be displayed immediately outside, without having to look inside the journal

**Pull request closed without merging**
