### PR TITLE
prepare v249-rc1

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

**Comment by bluca** [comment]
The NEWS line that begins with `Journal files, which are allocated in fixed incremenets, are now` needs to be removed, as https://github.com/systemd/systemd/pull/19934 reverted the change due to a regression - can be done after the PR, but should happen before the tag

**Comment by yuwata** [comment]
> The NEWS line that begins with `Journal files, which are allocated in fixed incremenets, are now` needs to be removed, as #19934 reverted the change due to a regression - can be done after the PR, but should happen before the tag

#19945. PTAL.

**Review by bluca — APPROVED** [review]
LGTM

**Pull request merged**
