### PR TITLE
Revert "sd-bus: change "int" → "signed int" on bitfield"

### PR DESCRIPTION
**Pull request by evverx**
This reverts commit b8a736d7a0e8ee00bdd026bb4c68c50bbe49d2ef.

https://lgtm.com/blog/announcing_github_apps_migration

### CODE REVIEW

**Comment by evverx** [comment]
It seems to be working. I'll revoke access to my GitHub account and delete the LGTM webhook to see how it goes.

**Comment by evverx** [comment]
In the meantime, I've just activated automated code review for systemd-stable and casync. You're welcome :-)

**Comment by evverx** [comment]
@mrc0mmand just FYI, I've just updated the systemd-centos-ci repository.

@samlanning thank you again for the heads-up! The transition seems to be completed here. What was confusing though is that it seems that the "activate automated code review" button on lgtm.com wasn't updated so I almost turned on what I'd just turned off :-)

**Comment by evverx** [comment]
@samlanning by the way, now that the purple background is gone I finally noticed the logo. I can't help but wonder what this creature in the bot's picture is :-)

**Comment by samlanning** [comment]
> @samlanning thank you again for the heads-up! The transition seems to be completed here. What was confusing though is that it seems that the "activate automated code review" button on lgtm.com wasn't updated so I almost turned on what I'd just turned off :-)

Ah yep, sorry about that. We made the minimum changes to the UI to get this functional enough to launch, so some things may be a little strange for projects that have migrated. We'll be completely phasing out the old OAuth mechanism soon, and updating the UI further so things like this should be reduced :)

> @samlanning by the way, now that the purple background is gone I finally noticed the logo. I can't help but wonder what this creature in the bot's picture is :-)

It's a tarsier: https://en.wikipedia.org/wiki/Tarsier :)

**Comment by evverx** [comment]
@samlanning thank you! My first guess was Yoda but it didn't add up :-) Also I was going to say that it would be great if there was a grumpy bot appearing when new alerts are introduced. Then I googled "a grumpy tarsier" and got lost :-)

**Pull request closed without merging**
