### PR TITLE
permit bus clients to pin units to avoid automatic GC

### PR DESCRIPTION
**Pull request by poettering**
This adds a concept of ref counting of units to the bus API. Two new calls on the Unit interface (Ref() and Unref()), plus the matching calls on the Manager interface (RefUnit() and UnrefUnit()) permit influencing the GC logic of systemd units, and make sure that units are not GC'ed right-away after they exited. A new pseudo-property AddRef is also added that may be specified when a transient unit is created, so that a Ref() and a StartTransientUnit() call may be combined atomically.

This is ref counting concept deals with a long-standing problem of the GC logic: a service that exited cleanly would likely be cleaned up immediately, thus losing all runtime information, such as CPU times and suchlike. With the new GC logic a client may now pin a unit into memory, thus ensuring the that exit status information can still be read before the unit is cleaned up.

Note that ref counting is only opened up to privileged clients, so that unprivileged clients cannot pin units into memory unbounded.

This PR includes a patch that extends "systemd-run" with a new "--wait" switch that makes use of this. When specified, systemd-run will wait for the created service to finish and show terse information about its runtime. This is particularly useful to see the consumed CPU time and such. Example invocation:

``` sh
# systemd-run -p CPUAccounting=1 --wait dd if=/dev/urandom of=/dev/null bs=1024 count=102400
Running as unit: run-u42547.service
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 614ms
CPU time consumed: 610ms
```

### CODE REVIEW

**Comment by poettering** [comment]
hmm, CI failure appears unrelated.

**Comment by martinpitt** [comment]
I've never seen the storage test fail so far, so that's at least suspicious. Anyway, retried the test(s).

**Comment by poettering** [comment]
i have rebased the patch set on current git (since it didn't apply anymore). I added a trivial patch on top.

**Comment by davide125** [comment]
Thank you! We were considering adding a `--wait` to `systemd-run` as well to use it kickoff expensive processes from Chef, this will save us a lot of work :-)

**Comment by arvidjaar** [comment]
It probably needs to extend `systemctl list-units` manual page by adding pinned units to list.

**Comment by evverx** [comment]
Is this an expected behaviour?

``` sh
-bash-4.3# systemd-run -p CPUAccounting=1 --wait sleep 10 & sleep 1; systemctl restart dbus; kill -TERM %1; sleep 15
[1] 141
Running as unit: run-u3.service
Warning! D-Bus connection terminated.
[1]+  Terminated              systemd-run -p CPUAccounting=1 --wait sleep 10

# still in memory
-bash-4.3# systemctl status run-u3 --no-pager
● run-u3.service - /usr/bin/sleep 10
   Loaded: loaded (/run/systemd/transient/run-u3.service; transient; vendor preset: enabled)
Transient: yes
   Active: inactive (dead) since Tue 2016-08-16 16:48:52 UTC; 23s ago
  Process: 143 ExecStart=/usr/bin/sleep 10 (code=exited, status=0/SUCCESS)
 Main PID: 143 (code=exited, status=0/SUCCESS)
```

**Comment by poettering** [comment]
I force pushed another version now, that is rebase on current git. It also adds a short doc fix, as suggested by @arvidjaar. It also adds infrastructure to deal with the issue pointed out by @evverx: we need to handle the tracking of peers properly if we lose the bus connection and hence will never actually see the peer disappear from the bus.

**Comment by evverx** [comment]
> we need to handle the tracking of peers properly if we lose the bus connection and hence will never actually see the peer disappear from the bus

@poettering , thanks!
This fixes the issue.

**Pull request merged**
