### PR TITLE
journalctl: Fix usage of -n and -b

### PR DESCRIPTION
**Pull request by jo-so**
When `-b` and `-n` are given, the output should be the first N lines after
boot. Currently, `-n` seeks to the tail and crushes the cursor from `-b`.

### CODE REVIEW

**Comment by yuwata** [comment]
> Currently, `-n` seeks to the tail and crushes the cursor from `-b`.

I cannot reproduce this. It seems to work fine for me.

With this PR, `-n 10 -b` shows the _first_ 10 lines. That conflicts with the explanation of `-n` in journalctl(1).

**Comment by jo-so** [comment]
@yuwata The manual page says nothing about the output of `-n` when used with other switches. Try `journalctl --since=today -n10` and you get the *first* 10 entries of the day. And `journalctl --until=today -r -n10` gives you the last 10 records of yesterday.

In which way would you say `--since=…` differs from `-b`, that `--since -n` should show the first entries, but `-b -n` should show the last entries?

**Comment by yuwata** [comment]
Indeed. Then, please also update the man page journalctl(1).

**Comment by fsateler** [comment]
> The manual page says nothing about the output of `-n` when used with other switches

That would suggest that the previous wording of:

> > Show the most recent journal events and limit the number of events shown.

Also applies when mixing with other flags.

**Comment by yuwata** [comment]
After re-considering this, `-n` should always shows the most recent journals even if `--since` or other options are set.

**Comment by jo-so** [comment]
If `-n` and `--lines` shows always the last entries, how would it be possible to limit the number of entries shown?

**Comment by jo-so** [comment]
Using `-n` for limit the number of records would align with `head` and `tail` where `-n` is used to limit the shown lines. In comparison with SQL, `-n` is like `LIMIT` and `--since`, `--until` and `-b` are like `WHERE`. Without any `WHERE` the default is an `ORDER BY id DESC`, which gives a sensible output when used alone.

If you want to change `-n` to always start at the end of the log, you're missing some way of `LIMIT`. If the first implementer would really had thought this way of `-n`, he had added more checks to conflict `-n` with `--since` et al. as it's done for `--since` and `--until`.

**Comment by keszybz** [comment]
`-n` and `--since` and `--boot` are supposed act as separate filters. Ideally, if all three are present, we would show entries from the specified boot only *and* after the specified time *and* then only show at most the specified number of them. And `-n` shows the last lines.

I can't reproduce the bug either. `-b -n 200000` shows the whole boot, and `-b -n 20` shows just the last twenty lines... So maybe it's just a misunderstanding of what `-n` is supposed to do.

The addition to the man page looks good though.

**Comment by YHNdnzj** [comment]
I think this should be closed now. After #26669 the mentioned incorrect behavior has been fixed, and this PR indeed seems to be some sort of misunderstanding.

**Pull request closed without merging**
