### PR TITLE
tmpfiles: Allow C escapes

### LINKED ISSUE #26955: tmpfiles.d rules do not allow C escapes, contrary to documentation
### systemd version the issue has been seen with

252.5

### Used distribution

NixOS unstable

### Linux kernel version used

6.2.7

### CPU architectures issue was seen on

x86_64

### Component

systemd-tmpfiles

### Expected behaviour you didn't see

C-style backslash escapes in tmpfiles rules are replaced with their corresponding characters in all fields

### Unexpected behaviour you saw

they're replaced only in the argument, in other fields the backslash is stripped and the remainder of the escape sequence is copied

### Steps to reproduce the problem

add a tmpfiles rule:
```
f "/tmp/x/\x20a\nb" 0644 0 0 - \x20foo\nbar
```
the created directory will not contain a newline or a space in its filename, even though the manpage explicitly says that all files are allowed to contain c-style escapes. file contents have spaces and newline at the expected position.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by ElvishJerricco**
Fixes #26955

This might be considered a breaking change, because the example from the bug report (`f "/tmp/x/\x20a\nb" 0644 0 0 - \x20foo\nbar`) will now produce a file whose name has the escaped characters instead of a file named `x20anb`. But this behavior reflects the current documentation that says C style escapes are supported.

### CODE REVIEW

**Comment by keszybz** [comment]
In cases like this, it is paramount to include a test case. Please extend either `test/test-systemd-tmpfiles.py` or `test/units/testsuite-22.*` to test this. Ideally, first add a commit that adds the test (with the old behaviour), and then do you change and adjust the test in the second commit. The diff for the second commit will show what changed.

**Comment by keszybz** [comment]
> This might be considered a breaking change, because the example from the bug report (`f "/tmp/x/\x20a\nb" 0644 0 0 - \x20foo\nbar`) will now produce a file whose name has the escaped characters instead of a file named `x20anb`. But this behavior reflects the current documentation that says C style escapes are supported.

Yeah, I agree that treating this is a bugfix sounds fine. People were unlikely to put in escape sequences that didn't actually work.

**Comment by ElvishJerricco** [comment]
@keszybz How does that look for the test? First is a commit where the test passes the old behavior, and then the commit that changes the behavior also changes the test to reflect the new behavior.

**Review by yuwata — APPROVED** [review]

**Review by keszybz — COMMENTED** [review]
LGTM.

**Comment by ElvishJerricco** [comment]
Thanks! It'd be nice to have this backported to stable.

**Comment by ElvishJerricco** [comment]
@keszybz Any chance of this getting backported?

**Pull request merged**
