### PR TITLE
Fix for 26839

### PR DESCRIPTION
**Pull request by fbuihuu**

### CODE REVIEW

**Comment by fbuihuu** [comment]
It looks simple, maybe too simple... what am I overlooking ?

**Comment by YHNdnzj** [comment]
> It looks simple, maybe too simple... what am I overlooking ?

Units with `PropagateStopTo=` don't necessarily want/require the other unit I believe. But you are propagating restart job to them as well

**Comment by fbuihuu** [comment]
Indeed there's one difference compare to the previous behavior: given two services `A` and `B` and with `A.PropagatesStopTo=B`. When `A` doesn't pull `B` in and both are started, if `A` is restarted then `B` is restarted as well whereas it was only stopped (but not started again).

I don't know maybe there's an acceptable tweak to fix this... will look at it later.

**Comment by YHNdnzj** [comment]
Just added what I mentioned as a test in #26844. Feel free to apply it here if you find a better solution :)

**Pull request closed without merging**
