### PR TITLE
meson: support building fuzzers with meson <0.48.0

### PR DESCRIPTION
**Pull request by mrc0mmand**
Addresses https://github.com/systemd/systemd/pull/15886#issuecomment-634275846

/cc @evverx @anitazha

### CODE REVIEW

**Comment by evverx** [comment]
I think another option would be to pass `-01` via `CFLAGS` and `CXXFLAGS`, get rid of `get_option('optimization')` altogether and wait until `meson` gets updated on CentOS.

@mrc0mmand would it be possible not to install `meson` via `pip3` on CentOS CI to make it easier to catch issues like that?

**Comment by mrc0mmand** [comment]
> 
> @mrc0mmand would it be possible not to install `meson` via `pip3` on CentOS CI to make it easier to catch issues like that?

I don't even remember why I bothered with the pip stuff in the first place, so I'll definitely give it a shot.

**Comment by evverx** [comment]
> I don't even remember why I bothered with the pip stuff in the first place

My guess would be that at the time `meson` either wasn't packaged there or it was too old to build `systemd`.

 Anyway, LGTM (even though I'd go with `CFLAGS` because it works everywhere :-))

**Comment by keszybz** [comment]
> I think another option would be to pass `-01` via `CFLAGS` and `CXXFLAGS`, get rid of `get_option('optimization')` altogether and wait until `meson` gets updated on CentOS.

I don't have an opinion, so I'll leave merging the PR to @mrc0mmand.

**Comment by mrc0mmand** [comment]
The CentOS CI fails are unrelated.

**Comment by evverx** [comment]
@mrc0mmand I've just noticed that something weird appeared at https://github.com/systemd/systemd/actions:
Screenshot 2020-05-27 at 14 58 07

I wonder if you've been doing anything unusual to GitHub actions.

**Comment by mrc0mmand** [comment]
@evverx I noticed that too (thanks to the emails it sent) and was wondering what's going on. Especially the first one is weird, since it was triggered by a deleted user:

image

But since the most recent build has passed, I refrained from contacting GH (for now,) to see if it's going to appear again.

**Comment by mrc0mmand** [comment]
> But since the most recent build has passed, I refrained from contacting GH (for now), to see if it's going to appear again.

@evverx  I went through the jobs once again and the more I look at them, the more weird they look, so I went ahead and opened a GH ticket. I'm not sure if there's any way to CC you, so I'll post an update here once I get it.

**Comment by evverx** [comment]
Just to make sure it was a glitch and nobody messed with our GitHub Actions using, say, exposed credentials I contacted GitHub too just in case: Ticket ID: 706633.

**Comment by mrc0mmand** [comment]
> Just to make sure it was a glitch and nobody messed with our GitHub Actions using, say, exposed credentials I contacted GitHub too just in case: Ticket ID: 706633.

Since I got the ticket ID 706634, I updated my ticket with a reference to the one you filed to get them deduplicated :-)

**Pull request merged**
