### PR TITLE
Drop bundled copy of linux/if_arp.h

### PR DESCRIPTION
**Pull request by keszybz**
As far as I can see, we use this to get a list of ARPHRD_* defines (used in
particular for Type= in .link files). If we drop our copy, and build against
old kernel headers, the user will have a shorter list of types available.  This
seems OK, and I don't think it's worth carrying our own version of this file
just to have newest possible entries.

7c5b9952c4f6e2b72f90edbe439982528b7cf223 recently updated this file, but we'd
have to update it every time the kernel adds new entries. But if we look at
the failure carefully:

```
src/basic/arphrd-from-name.gperf:65:16: error: ‘ARPHRD_MCTP’ undeclared (first use in this function); did you mean ‘ARPHRD_FCPP’?
   65 | MCTP, ARPHRD_MCTP
      |                ^~
      |                ARPHRD_FCPP
```

we see that the list we were generating was from the system headers, so it was
only as good as the system headers anyway, without the newer entries in our
bundled copy, if there were any. So let's make things simpler by always using
system headers.

And if somebody wants to fix things so that we always have the newest list,
then we should just generate and store the converted list, not the full header.

### CODE REVIEW

**Comment by yuwata** [comment]
Question: the header includes `linux/netdevice.h`. If system's if_arp.h is used, then which netdevice.h from system or our tree is used?

**Comment by poettering** [comment]
afaics we actually use these ARPHRD_ types:

ARPHRD_ETHER, ARPHRD_INFINIBAND, ARPHRD_SLIP, ARPHRD_CAN, ARPHRD_VOID

Are these all defined in reasonably old versions of the header file already?

**Comment by bluca** [comment]
> Question: the header includes `linux/netdevice.h`. If system's if_arp.h is used, then which netdevice.h from system or our tree is used?

Given that's still listed in src/basic/meson.build it should be ours, no?

**Comment by bluca** [comment]
> ARPHRD_VOID

The most recent one of those is ARPHRD_CAN which was added in 2.6.25, the others are even older: https://github.com/torvalds/linux/commit/cd05acfe65ed2cf2db683fa9a6adb8d35635263b

**Review by bluca — APPROVED** [review]
LGTM

**Comment by keszybz** [comment]
So, anything left to do here?

**Comment by bluca** [comment]
Only one thing :-)

**Pull request merged**
