### PR TITLE
Revert "boot: efi - remove a couple of Loader* variables"

### PR DESCRIPTION
**Pull request by jhol**
This patch reintroduces the `LoaderDeviceIdentifier` EFI variable, because it was being used in my project to find the ESP device node in initrd by means of a [shell-script](https://gist.github.com/jhol/391c0821c5727eb08ef3).

Since the variable was removed there doesn't appear to be another way to find the ESP device except `LoaderDevicePartUUID` which isn't guaranteed to be unique if you have multiple cloned disks present in the system.

### CODE REVIEW

**Comment by jhol** [comment]
@kaysievers What's you opinion about this?

**Comment by kaysievers** [comment]
Systemd-boot does not support the gnu-efi-invented device string anymore. The format makes no sense.

The entry-specific variables are also not supported by systemd-boot, we limit the use of EFI variables to the absolute minimum.

Sorry, we don't want to add this back.

**Comment by jhol** [comment]
Sure OK, but what's the alternative? What method should I be using to figure out which partition we booted from?

**Comment by kaysievers** [comment]
We export the GPT partition UUID (not the UUID of the ESP type) of the ESP.

**Pull request closed without merging**
