### PR TITLE
test: skip TPM-70-TPM2 on ppc64el Ubuntu CI

### PR DESCRIPTION
**Pull request by yuwata**
This is quite unstable on ppc64el, and failed on various place of the test script. Let's skip it.

### CODE REVIEW

**Review by mrc0mmand — APPROVED** [review]

**Comment by bluca** [comment]
it didn't use to be, must be a recent regression, what's failing?

**Comment by yuwata** [comment]
I could not remember when it started to fail, but it has been quite unstable for a while IIRC.
Unfortunately, Ubuntu ppc64el CI is unstable in general, not only on the TPM2 test.

**Comment by yuwata** [comment]
Hm.. In the stable repository, it succeeds on recent PRs.
Let's keep the test.

**Comment by mrc0mmand** [comment]
iirc it's caused by one of my recent additions, but I still think it's some kind of environment issue, as I can't reproduce it anywhere else, see https://github.com/systemd/systemd/pull/27602#issuecomment-1543854533

**Pull request closed without merging**
