### PR TITLE
LLDP: add API to export neighbors list (v3)

### PR DESCRIPTION
**Pull request by bengal**
v3 of #546

The LLDP support in libsystemd-network at the moment only allows to
save the list of discovered neighbors to a text file.

It would be useful to have an API to export information about
neighbors in a more flexible way to users of the library. These
patches export the TLV structure as a public opaque type and provide
public functions to access its content.

Changes since v2:
- renamed sd_lldp_tlv to sd_lldp_tlv_packet
- added sd_lldp_tlv_packet_get_destination_type() function
- added support for organizationally specific TLVs

### CODE REVIEW

**Comment by poettering** [comment]
Looks good in general.

**Comment by bengal** [comment]
> We need to add generic APIs that should work with other type if it's get repeated.

The 802.1AB standard describes two types of TLVs: the basic management
TLVs and organizationally specific ones. The difference between the
two is that the latter have a specific type (127) and carry additional
fields containing the OUI (3 bytes) and a subtype (1 byte). Type 127
is the only type of TLV that can appear multiple times (with different
OUI/subtype) and there aren't any constraints on the order of TLVs,
except for the first 3 which must be Chassis-id,Port-id,TTL and the
last one which must be End.

A LLDP frame could have for example the following TLVs:
- TLV type=1 (chassis id)
- TLV type=2 (port id)
- TLV type=3 (TTL)
- TLV type=127 oui=00120f subtype=2 (power over MDI)
- TLV type=5 (system name)
- TLV type=127 oui=00120f subtype=1 (MAC/PHY conf/status)
- TLV type=6 (system description)
- TLV type=0 (end)

If I understand correctly, the API you suggest seems to assume some
sort of encapsulation of the organizationally specific TLVs or, at
least, the fact that they are contiguous. So the first call would
position the pointer at the first TLV with type 127 and the second
call would search the given OUI and subtype. But given the fact that
there isn't any encapsulation and those TLVs aren't contiguous, I'm
not sure how you're suggesting to do it.

IMHO we need only an additional way to seach an org-specific TLV given
its OUI/subtype. If your concern is to avoid changing signature of
existing methods, maybe we can just add a new function

  enter_container_org_specific (packet, oui, subtype)

and leave the existing enter_container() untouched.

**Comment by ssahani** [comment]
Not really  contiguous .   Let me explain you again,
1. lldp_tlv_packet_find_container_subtype 
   Here you already know  what type (container) you are looking for.  if you loop throw the list you can go to any type  not necessary  continuous. All the types are parsed and stored in a list. 
   if you look at the tlv_section it has a type.
2.  lldp_tlv_packet_find_container_subtype(uint16_t subtype, void *_user, uint16_t  user_len, void *_*data,   uint16_t len) {
     switch(type) {
     case LLDP_TYPE_PRIVATE:
         here you know you should look for oui. 
      case : something else:
                do something else
        break:
        default:
        return -1;
       }
   }

**Comment by bengal** [comment]
> 1. lldp_tlv_packet_find_container_subtype
> 2. lldp_tlv_packet_find_container_subtype(uint16_t subtype, void _user, uint16_t user_len, void *_data, uint16_t len) {

Just wondering, which is the advantage of having a first function to
build a list of TLV sections matching the given type and another to
search the section with given OUI/subtype in that list?

As they will always be called in sequence, wouldn't be simpler to just
merge them into a function which accepts type/OUI/subtype, goes
through the list of sections and returns the matching one? Note that
the switch in the code above is not necessary as TYPE_PRIVATE is the
only type accepting subtypes.

In my opinion we don't need an abstraction level to handle subtypes in
a generic way, but if you think that it's better choice I'll follow
that way.

**Comment by ssahani** [comment]
That is what exactly what we want to avoid. 
1. lldp_tlv_packet_enter_container '
    for single unrepeated match' for type match
2. lldp_tlv_packet_find_container_subtype
   or lldp_tlv_packet_find_container_next_subtype

 or something else nice definition clearly defines the behaviour  that it's for repeated types.
 which should iterate and find next type and extra matches inside a type

**Comment by bengal** [comment]
> or something else nice definition clearly defines the behaviour that it's for repeated types.
> which should iterate and find next type and extra matches inside a type

Seems reasonable, I'll try to implement this in v4, thanks.

**Comment by bengal** [comment]
Closing, superseded by #905.

**Pull request closed without merging**
