### PR TITLE
tmpfile: do not specify mode and owner to /run/systemd/netif

### LINKED ISSUE #9369: network: fail to save link state
**systemd version the issue has been seen with**

3fe9107

**Used distribution**

Fedora 28 x86_64

**Expected behaviour you didn't see**

link state is saved, and not logs error.

**Unexpected behaviour you saw**

I noticed that `link_save()` fails every 12 hours.
```
Jun 19 13:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 19 13:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 19 13:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 19 13:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 19 13:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 01:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 01:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 01:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 01:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 01:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 01:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 01:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 13:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 13:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 13:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 13:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 13:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 13:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 20 13:33:45 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 21 01:33:44 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 21 01:33:44 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 21 01:33:44 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 21 01:33:44 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 21 01:33:44 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 21 01:33:44 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Jun 21 01:33:44 systemd-networkd[545]: enp0s25: Failed to save link data to /run/systemd/netif/links/2: Permission denied
```
The link enp0s25 enables DHCP, and its lease T1 is 12h:
```
T1=43200
T2=75600
LIFETIME=86400
```
Other informations:
```
$ networkctl status enp0s25 
● 2: enp0s25
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/99-default.network
            Type: ether
           State: routable (configured)
            Path: pci-0000:00:19.0
          Driver: e1000e
          Vendor: Intel Corporation
           Model: Ethernet Connection (3) I218-V
      HW Address: b8:ae:ed:76:1e:77 (Elitegroup Computer Systems Co.,Ltd.)
         Address: 10.226.31.234
                  fe80::baae:edff:fe76:1e77
         Gateway: 10.226.31.254 (ALAXALA Networks Corporation)
             DNS: 10.224.254.1
                  10.224.253.11
  Search Domains: kuins.net
$ cat /etc/systemd/network/99-default.network 
[Match]
Name=!lo

[Network]
DHCP=ipv4
IPv6AcceptRA=no

[DHCP]
UseHostname=no
UseDomains=yes
```

I will enable `SYSTEMD_LOG_LEVEL=debug` and report detailed log later.

**Steps to reproduce the problem**
enable DHCP, and wait.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #9369.

The issue is introduced by d4e9e574ea0b5d23598a317e68399584d229568b. So, please include this in v239.

### CODE REVIEW

**Comment by yuwata** [comment]
The issue #9369 is caused by updating systemd.rpm.
systemd.rpm of Fedora calls `systemd-tmpfiles --create`. So, updating systemd.rpm changes owner of /run/systemd/netif, hence, networkd cannot write states in the directory.

**Comment by keszybz** [comment]
Hmm, I'm a bit confused. Does this also work if tmpfiles runs first and networkd second?

**Comment by yuwata** [comment]
Yeah, the runtime directories are chowned.

**Comment by poettering** [comment]
hmm, but actually we could leave the mode in place, no? and only drop the user/group columns?

**Comment by filbranden** [comment]
> Yeah, the runtime directories are chowned.

@yuwata Are you positive?

I'm running v239-142-g99352de644c0 which includes #9400 and I'm getting a `/run/systemd/netif` owned by root.

During initialization, systemd-networkd complains loudly:

```
Jul 15 01:27:10 rawhide.libvirt systemd[1]: Starting Network Service...
Jul 15 01:27:10 rawhide.libvirt systemd-networkd[712]: Directory "/run/systemd/netif" already exists, but is owned by 0:0 (192:192 was requested), refusing.
Jul 15 01:27:10 rawhide.libvirt systemd-networkd[712]: Could not create runtime directory: File exists
Jul 15 01:27:10 rawhide.libvirt systemd-networkd[712]: Directory "/run/systemd/netif/links" already exists, but is owned by 0:0 (192:192 was requested), refusing.
Jul 15 01:27:10 rawhide.libvirt systemd-networkd[712]: Could not create runtime directory 'links': File exists
Jul 15 01:27:10 rawhide.libvirt systemd-networkd[712]: Directory "/run/systemd/netif/leases" already exists, but is owned by 0:0 (192:192 was requested), refusing.
Jul 15 01:27:10 rawhide.libvirt systemd-networkd[712]: Could not create runtime directory 'leases': File exists
Jul 15 01:27:10 rawhide.libvirt systemd-networkd[712]: Could not create runtime directory 'lldp': No such file or directory
Jul 15 01:27:10 rawhide.libvirt systemd-networkd[712]: lo: Failed to save link data to /run/systemd/netif/links/1: Permission denied
Jul 15 01:27:10 rawhide.libvirt systemd-networkd[712]: ens3: Failed to save link data to /run/systemd/netif/links/2: Permission denied
```

But maybe I'm missing something there?

I have an override file which is disabling DynamicUser for systemd-networkd due to an issue with the SELinux policy, but otherwise everything is as shipped.

**Comment by yuwata** [comment]
The directories specified in `RuntimeDirectory=` are not chown()ed when `DynamicUser=` is disabled.
C.f. I've created #9586. PTAL.

**Comment by yuwata** [comment]
Please provide `ls -l /run/systemd/netif`. Also, please provide log of networkd. `networkctl` shows only last few lines. Please use `journalctl -b -u systemd-networkd.service`.

**Comment by ltagliamonte-dd** [comment]
@yuwata here the info you requested:
```
root@ip-172-30-146-99:~# ls -l /run/systemd/netif
total 4
drwxr-xr-x 2 systemd-timesync systemd-resolve  60 Aug 27 00:34 leases
drwxr-xr-x 2 systemd-timesync systemd-resolve 220 Aug 27 00:40 links
drwxr-xr-x 2 systemd-timesync systemd-resolve  40 Aug 26 23:34 lldp
-rw-r--r-- 1 systemd-network  systemd-network 153 Aug 27 00:40 state
```
logs they repeat over and over:
```
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni0fa894cef37: Failed to save link data to /run/systemd/netif/links/14: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni4d5499ea17d: Failed to save link data to /run/systemd/netif/links/27: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni80ec7e525eb: Failed to save link data to /run/systemd/netif/links/11: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: ens8: Failed to save link data to /run/systemd/netif/links/4: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enie2eba12e920: Failed to save link data to /run/systemd/netif/links/20: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni30eab68d83c: Failed to save link data to /run/systemd/netif/links/12: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enib4319a0fe21: Failed to save link data to /run/systemd/netif/links/22: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni8184409143d: Failed to save link data to /run/systemd/netif/links/39: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni89100fb288b: Failed to save link data to /run/systemd/netif/links/19: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enia07b43e2f85: Failed to save link data to /run/systemd/netif/links/23: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni6728e90b42f: Failed to save link data to /run/systemd/netif/links/26: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni24820243c08: Failed to save link data to /run/systemd/netif/links/28: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni8075726b68c: Failed to save link data to /run/systemd/netif/links/29: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enia660f37d2ba: Failed to save link data to /run/systemd/netif/links/30: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enic5286d4ad10: Failed to save link data to /run/systemd/netif/links/16: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: ens6: Failed to save link data to /run/systemd/netif/links/3: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni658fdd98980: Failed to save link data to /run/systemd/netif/links/37: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni68cd3b8f162: Failed to save link data to /run/systemd/netif/links/24: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni0fa894cef37: Failed to save link data to /run/systemd/netif/links/14: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni4d5499ea17d: Failed to save link data to /run/systemd/netif/links/27: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni80ec7e525eb: Failed to save link data to /run/systemd/netif/links/11: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: ens8: Failed to save link data to /run/systemd/netif/links/4: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enie2eba12e920: Failed to save link data to /run/systemd/netif/links/20: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni30eab68d83c: Failed to save link data to /run/systemd/netif/links/12: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enib4319a0fe21: Failed to save link data to /run/systemd/netif/links/22: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni8184409143d: Failed to save link data to /run/systemd/netif/links/39: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni89100fb288b: Failed to save link data to /run/systemd/netif/links/19: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enia07b43e2f85: Failed to save link data to /run/systemd/netif/links/23: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni6728e90b42f: Failed to save link data to /run/systemd/netif/links/26: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni24820243c08: Failed to save link data to /run/systemd/netif/links/28: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni8075726b68c: Failed to save link data to /run/systemd/netif/links/29: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enia660f37d2ba: Failed to save link data to /run/systemd/netif/links/30: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enic5286d4ad10: Failed to save link data to /run/systemd/netif/links/16: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: ens6: Failed to save link data to /run/systemd/netif/links/3: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni658fdd98980: Failed to save link data to /run/systemd/netif/links/37: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni68cd3b8f162: Failed to save link data to /run/systemd/netif/links/24: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni0fa894cef37: Failed to save link data to /run/systemd/netif/links/14: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni4d5499ea17d: Failed to save link data to /run/systemd/netif/links/27: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni80ec7e525eb: Failed to save link data to /run/systemd/netif/links/11: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: ens8: Failed to save link data to /run/systemd/netif/links/4: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enie2eba12e920: Failed to save link data to /run/systemd/netif/links/20: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni30eab68d83c: Failed to save link data to /run/systemd/netif/links/12: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enib4319a0fe21: Failed to save link data to /run/systemd/netif/links/22: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni8184409143d: Failed to save link data to /run/systemd/netif/links/39: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni89100fb288b: Failed to save link data to /run/systemd/netif/links/19: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enia07b43e2f85: Failed to save link data to /run/systemd/netif/links/23: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni6728e90b42f: Failed to save link data to /run/systemd/netif/links/26: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni24820243c08: Failed to save link data to /run/systemd/netif/links/28: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: eni8075726b68c: Failed to save link data to /run/systemd/netif/links/29: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enia660f37d2ba: Failed to save link data to /run/systemd/netif/links/30: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: enic5286d4ad10: Failed to save link data to /run/systemd/netif/links/16: Permission denied
Aug 29 13:10:34 ip-172-30-146-99 systemd-networkd[1031]: ens6: Failed to save link data to /run/systemd/netif/links/3: Permission denied
```

**Comment by yuwata** [comment]
Please try to once remove /run/systemd/netif and restart networkd. Not sure, but I guess you updated systemd but not networkd is not restarted.

**Comment by ltagliamonte-dd** [comment]
@yuwata sorry for the late follow up, but I have the same logs on brand new server:
```
uptime
 16:13:20 up 4 days, 22:17,  1 user,  load average: 1.07, 0.60, 0.47
```

```
systemctl --version
systemd 245 (245.4-4ubuntu3.15)
```

```
ls -l /run/systemd/netif
total 4
drwxr-xr-x 2 systemd-timesync systemd-resolve  60 Apr  8 17:56 leases
drwxr-xr-x 2 systemd-timesync systemd-resolve 120 Apr  8 17:59 links
drwxr-xr-x 2 systemd-timesync systemd-resolve  40 Apr  8 17:56 lldp
-rw-r--r-- 1 systemd-network  systemd-network 151 Apr  8 17:59 state
```

```
networkctl status ens5
● 2: ens5                                                              
             Link File: /usr/lib/systemd/network/99-default.link       
          Network File: /run/systemd/network/10-netplan-ens5.network   
                  Type: ether                                          
                 State: routable (configured)
     Alternative Names: enp0s5                                         
                  Path: pci-0000:00:05.0                               
                Driver: ena                                            
                Vendor: Amazon.com, Inc.                               
                 Model: Elastic Network Adapter (ENA)                  
            HW Address: 06:81:3d:e8:2e:3f                              
                   MTU: 9001 (min: 128, max: 9216)                     
  Queue Length (Tx/Rx): 16/16                                          
               Address: 10.4.162.140 (DHCP4)                           
                        fe80::481:3dff:fee8:2e3f                       
               Gateway: 10.4.160.1                                     
                   DNS: 10.4.0.2                                       
        Search Domains: us-west-2.compute.internal                     
     Activation Policy: up                                             
   Required For Online: yes                                            

Apr 13 16:14:21 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:21 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:21 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:21 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:21 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:22 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:22 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:22 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:22 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
Apr 13 16:14:22 ip-10-4-162-140 systemd-networkd[543]: ens5: Failed to save link data to /run/systemd/netif/links/2: Permission denied
```

**Pull request merged**
