### PR TITLE
Revert "units: lock down logind with fs namespacing options"

### PR DESCRIPTION
**Pull request by keszybz**
Reverts systemd/systemd#10744

Let's see if this fixes tests.

### CODE REVIEW

**Comment by evverx** [comment]
Another PR that was merged a little bit earlier than https://github.com/systemd/systemd/pull/10744 and also got stuck is https://github.com/systemd/systemd/pull/10743. I missed it because for some unknown reason it's green on [the list of the PRs that have been merged](https://github.com/systemd/systemd/pulls?q=is%3Apr+is%3Aclosed).

**Comment by evverx** [comment]
On the other hand, there are other PRs where the tests passed but the "details" panel shows something completely different so I'd stick to https://github.com/systemd/systemd/pull/10744 :-)

**Comment by evverx** [comment]
I'm looking at the queues at http://autopkgtest.ubuntu.com/running#pkg-systemd-upstream and it seems that this PR is going to wait for a long time. I'm wondering if it is possible to cancel everything except for this PR. @xnox @martinpitt could you do that? Otherwise, PRs are just going to pile up even further.

**Comment by martinpitt** [comment]
Just a quick drive-by.. @xnox, @iainlane: can you please clean these up? I don't have access to that queue any more.

**Comment by iainlane** [comment]
Done, thanks for the ping (FTR, @xnox doesn't have access, but you can try @sil2100 @julian-klode in addition to me). I didn't bother killing the in-progress jobs though, let me know if that's a problem.

**Comment by keszybz** [comment]
bionic-amd64 passed.

**Comment by poettering** [comment]
uh... why did this get merged? i'd prefer if we'd fix things, not just revert them

**Comment by evverx** [comment]
As far as I can tell, Ubuntu CI is still stuck and I'm not sure how long it's going to take for it to figure out automatically that, for example, https://github.com/systemd/systemd/pull/10744 shouldn't be run any more so as not to waste resources while other PRs are waiting in the queue.

**Comment by iainlane** [comment]
I just deleted all the in progress jobs. Push commits to PRs (rebasing them to get this revert?) to get them re-triggered.

**Comment by keszybz** [comment]
I agree with @evverx here.

**Pull request merged**
