### PR TITLE
shared/varlink: add missing setting of output_buffer_allocated

### PR DESCRIPTION
**Pull request by keszybz**
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14708,
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14735,
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14725,
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14720,
and probably others.

### CODE REVIEW

**Comment by keszybz** [comment]
OK, bionic-amd64 and bionic-s390x passed. bionic-i386 is still running. Everything else passed. Let's merge.

**Comment by johannbg** [comment]
Does one need some kind of access to see those fuzz bugs at this chromium platform?

**Comment by evverx** [comment]
@johannbg usually the OSS-Fuzz project follows https://github.com/google/oss-fuzz#bug-disclosure-guidelines.

**Comment by keszybz** [comment]
Yep. I can add you if you want (this applies also to other contributors). Just ping me with an e-mail address. You'll have to do a CLA for oss-fuzz too to commit anything unfortunately. But just for viewing the reports and fixes, CLA is not necessary.

**Comment by evverx** [comment]
@keszybz by the way I'm wondering how you can do anything there with no gmail address. I tried to use my main address (connected to a gmail account with the CLA signed) but gave up when I realized that I could only receive email notifications and created a single-purpose gmail account.

**Comment by keszybz** [comment]
@evverx I use my normal e-mail address there, and the `@redhat.one` is linked to it (because of the CLA). I don't use a g-mail address.

**Comment by evverx** [comment]
@keszybz that's exactly what I don't understand :-) Apparently I can't seem to make my non-gmail account work there.

**Comment by evverx** [comment]
And judging by https://github.com/google/oss-fuzz/issues/2261 I'm not alone :-)

**Comment by evverx** [comment]
@johannbg I'm not sure how critical this is to you but given that your email address is hidden on GitHub it might be worth mentioning that it will end up on the list https://github.com/google/oss-fuzz/blob/master/projects/systemd/project.yaml if you decide to join the club.

**Comment by johannbg** [comment]
@evverx well my gmail account is all over the place anyway so :)

**Pull request merged**
