### PR TITLE
Better support for DANE, shell completion

### PR DESCRIPTION
**Pull request by keszybz**
I'm not sure if the command line switch should be `--tlsa` or `--tls` (probably not) or `--dane`. I used the first option, because it seems most intuitive.

`service_family_from_string` is written with the assumption that it will be expanded to support slightly different mappings later on. DANE defines `_tcp`, `_udp`, `_sctp`, but for example DNS-SD uses only `_tcp` and `_udp`, with the latter being used for anything that is not `tcp`. So I don't want to use a standard table mapping, because it'll grow more corner cases as time goes on.

<strike>@martinpitt The first commit should fix your build. If I'm right, you might want to simply merge the first commit to master by hand, without waiting for the rest of the pull request.</strike>

### CODE REVIEW

**Comment by keszybz** [comment]
Pfff, why can't github show commits in order...

**Comment by keszybz** [comment]
I dropped the first comment, because the issue was independently fixed in #2652.

**Comment by martinpitt** [comment]
FTR, the ubuntu-ci failure is some transient networking problem, I just committed a robustification and restarted the test. Unfortunately this can't be replayed from the github web UI because that got force-pushed, so you don't see an "in progress" (I'll push the result manually after it finished). @zonque is looking into why semaphore is not shown here, although it is running on https://semaphoreci.com/systemd/systemd/branches/pull-request-2648.

**Comment by keszybz** [comment]
Thanks for the review. Force pushed.

**Comment by poettering** [comment]
hmm, i wonder where semaphore went now...

**Comment by keszybz** [comment]
Valgrind is now happy. Force pushed again.

**Comment by keszybz** [comment]
Oh, OK, I see that `-t help` includes `ANY`. Will fix.

**Comment by poettering** [comment]
looks good to me now. given how long CI takes now, let's invent a new label for cases like this where human review gives this a thumbs-up but CI is still not done.

**Comment by poettering** [comment]
There we go, "good-to-merge/waiting-for-ci" shell henceforth be the label to stick on code that is ready to merge but waits for CI still.

**Comment by martinpitt** [comment]
I disabled the journal check in test_bash_crash now, so any test from now on should succeed boot-and-services; this never fails downstream, so there's something fishy there, but this needn't make all PRs red. The `test_hotplug_dhcp_ip6` looks racy, all other tests succeed.

The latest build on https://semaphoreci.com/systemd/systemd/branches/pull-request-2648 failed, looks transient. I restarted it too. Not sure why it isn't shown here, though.

**Comment by martinpitt** [comment]
semaphore failed again, retried again...

**Comment by martinpitt** [comment]
No idea what's up with semaphore on this, I restarted about 5 times (two of them are actually shown), but it never even starts the tests. It does work for other PRs, and the build/make/make check dance was done by ubuntu-ci, so let's not stall this any further.

**Comment by zonque** [comment]
I have pinged Semaphore support on this, but did receive a reply yet. I'm sure it's a temporary hick-up.

**Comment by evverx** [comment]
> I disabled the journal check in test_bash_crash now, so any test from now on should succeed boot-and-services

I've read http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/tests/boot-and-services#n446

@martinpitt , try `journalctl -t systemd-coredump` instead of `journalctl /lib/systemd/systemd-coredump`. We lose `_EXE` sometimes.

```
# 10 SEGVs
-bash-4.3# for i in {1..10}; do bash -c 'kill -SEGV $$'; done
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)

# 10 lines
-bash-4.3# coredumpctl --no-pager --no-legend
Thu 2016-02-25 19:07:39 UTC     428     0     0  11 * /usr/bin/bash
Thu 2016-02-25 19:07:42 UTC     431     0     0  11 * /usr/bin/bash
Thu 2016-02-25 19:07:44 UTC     434     0     0  11 * /usr/bin/bash
Thu 2016-02-25 19:07:47 UTC     437     0     0  11 * /usr/bin/bash
Thu 2016-02-25 19:07:47 UTC     440     0     0  11 * /usr/bin/bash
Thu 2016-02-25 19:07:49 UTC     443     0     0  11 * /usr/bin/bash
Thu 2016-02-25 19:07:50 UTC     448     0     0  11 * /usr/bin/bash
Thu 2016-02-25 19:07:50 UTC     451     0     0  11 * /usr/bin/bash
Thu 2016-02-25 19:07:51 UTC     456     0     0  11 * /usr/bin/bash
Thu 2016-02-25 19:07:52 UTC     461     0     0  11 * /usr/bin/bash

# 9 lines
-bash-4.3# journalctl -b /lib/systemd/systemd-coredump | grep 'dumped core'
Feb 25 19:07:42 systemd-testsuite systemd-coredump[433]: Process 431 (bash) of user 0 dumped core.
Feb 25 19:07:44 systemd-testsuite systemd-coredump[436]: Process 434 (bash) of user 0 dumped core.
Feb 25 19:07:47 systemd-testsuite systemd-coredump[439]: Process 437 (bash) of user 0 dumped core.
Feb 25 19:07:47 systemd-testsuite systemd-coredump[442]: Process 440 (bash) of user 0 dumped core.
Feb 25 19:07:49 systemd-testsuite systemd-coredump[445]: Process 443 (bash) of user 0 dumped core.
Feb 25 19:07:50 systemd-testsuite systemd-coredump[450]: Process 448 (bash) of user 0 dumped core.
Feb 25 19:07:50 systemd-testsuite systemd-coredump[453]: Process 451 (bash) of user 0 dumped core.
Feb 25 19:07:51 systemd-testsuite systemd-coredump[458]: Process 456 (bash) of user 0 dumped core.
Feb 25 19:07:52 systemd-testsuite systemd-coredump[463]: Process 461 (bash) of user 0 dumped core.

# 10 lines
-bash-4.3# journalctl -b | grep 'dumped core'
Feb 25 19:07:39 systemd-testsuite systemd-coredump[430]: Process 428 (bash) of user 0 dumped core.
Feb 25 19:07:42 systemd-testsuite systemd-coredump[433]: Process 431 (bash) of user 0 dumped core.
Feb 25 19:07:44 systemd-testsuite systemd-coredump[436]: Process 434 (bash) of user 0 dumped core.
Feb 25 19:07:47 systemd-testsuite systemd-coredump[439]: Process 437 (bash) of user 0 dumped core.
Feb 25 19:07:47 systemd-testsuite systemd-coredump[442]: Process 440 (bash) of user 0 dumped core.
Feb 25 19:07:49 systemd-testsuite systemd-coredump[445]: Process 443 (bash) of user 0 dumped core.
Feb 25 19:07:50 systemd-testsuite systemd-coredump[450]: Process 448 (bash) of user 0 dumped core.
Feb 25 19:07:50 systemd-testsuite systemd-coredump[453]: Process 451 (bash) of user 0 dumped core.
Feb 25 19:07:51 systemd-testsuite systemd-coredump[458]: Process 456 (bash) of user 0 dumped core.
Feb 25 19:07:52 systemd-testsuite systemd-coredump[463]: Process 461 (bash) of user 0 dumped core.

# there is no _EXE field
-bash-4.3# journalctl -t systemd-coredump _PID=430 -o verbose
...
Thu 2016-02-25 19:07:39.254412 UTC [s=e38f498615d64b5d8b70d78cc6c7f2c7;i=d3c;b=172d45b51c5c4287885bc78bedeba156;m=5a77fa7;t=52c9ce56e0c4c;x=73e3bfece816da96]
    _TRANSPORT=journal
    _BOOT_ID=172d45b51c5c4287885bc78bedeba156
    _MACHINE_ID=8cadfd6a7cda416c8c71001ec5b90205
    _HOSTNAME=systemd-testsuite
    _PID=430
    _COMM=systemd-coredum
    _SYSTEMD_CGROUP=/system.slice/system-systemd\x2dcoredump.slice/systemd-coredump@0-429-0.service
    _SYSTEMD_UNIT=systemd-coredump@0-429-0.service
    _SYSTEMD_SLICE=system-systemd\x2dcoredump.slice
    SYSLOG_IDENTIFIER=systemd-coredump
    CODE_FILE=src/coredump/coredump.c
    _UID=986
    _GID=986
    _CAP_EFFECTIVE=0
    COREDUMP_UNIT=session-1.scope
    COREDUMP_PID=428
    COREDUMP_UID=0
    COREDUMP_GID=0
    COREDUMP_SIGNAL=11
    COREDUMP_RLIMIT=18446744073709551615
    COREDUMP_SESSION=1
    COREDUMP_OWNER_UID=0
    COREDUMP_SLICE=user-0.slice
    COREDUMP_COMM=bash
    COREDUMP_EXE=/usr/bin/bash
    COREDUMP_CMDLINE=bash -c kill -SEGV $$
    COREDUMP_CGROUP=/user.slice/user-0.slice/session-1.scope
    COREDUMP_OPEN_FDS=0:/dev/ttyS0
                      pos:  0
                      flags:    0100002
                      mnt_id:   18

                      1:/dev/ttyS0
                      pos:  0
                      flags:    0100002
                      mnt_id:   18

                      2:/dev/ttyS0
                      pos:  0
                      flags:    0100002
                      mnt_id:   18
    COREDUMP_PROC_STATUS=Name:  bash
                         State: S (sleeping)
                         Tgid:  428
                         Ngid:  0
                         Pid:   428
                         PPid:  427
                         TracerPid: 0
                         Uid:   0   0   0   0
                         Gid:   0   0   0   0
                         FDSize:    256
                         Groups:
                         NStgid:    428
                         NSpid: 428
                         NSpgid:    428
                         NSsid: 427
                         VmPeak:        9636 kB
                         VmSize:        9632 kB
                         VmLck:        0 kB
                         VmPin:        0 kB
                         VmHWM:     2352 kB
                         VmRSS:     2352 kB
                         VmData:         204 kB
                         VmStk:      136 kB
                         VmExe:      992 kB
                         VmLib:     2052 kB
                         VmPTE:       44 kB
                         VmPMD:       12 kB
                         VmSwap:           0 kB
                         Threads:   1
                         SigQ:  0/1876
                         SigPnd:    0000000000000000
                         ShdPnd:    0000000000000000
                         SigBlk:    0000000000000000
                         SigIgn:    0000000000000004
                         SigCgt:    0000000000010000
                         CapInh:    0000000000000000
                         CapPrm:    0000003fffffffff
                         CapEff:    0000003fffffffff
                         CapBnd:    0000003fffffffff
                         CapAmb:    0000000000000000
                         Seccomp:   0
                         Cpus_allowed:  1
                         Cpus_allowed_list: 0
                         Mems_allowed:  00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
                         Mems_allowed_list: 0
                         voluntary_ctxt_switches:   2
                         nonvoluntary_ctxt_switches:    14
    COREDUMP_PROC_MAPS=5612dfd07000-5612dfdff000 r-xp 00000000 08:01 22759                      /usr/bin/bash
                       5612dfffe000-5612e0002000 r--p 000f7000 08:01 22759                      /usr/bin/bash
                       5612e0002000-5612e000b000 rw-p 000fb000 08:01 22759                      /usr/bin/bash
                       5612e000b000-5612e0010000 rw-p 00000000 00:00 0
                       5612e0e29000-5612e0e4a000 rw-p 00000000 00:00 0                          [heap]
                       7ff614198000-7ff61434f000 r-xp 00000000 08:01 22653                      /usr/lib64/libc-2.22.so
                       7ff61434f000-7ff61454f000 ---p 001b7000 08:01 22653                      /usr/lib64/libc-2.22.so
                       7ff61454f000-7ff614553000 r--p 001b7000 08:01 22653                      /usr/lib64/libc-2.22.so
                       7ff614553000-7ff614555000 rw-p 001bb000 08:01 22653                      /usr/lib64/libc-2.22.so
                       7ff614555000-7ff614559000 rw-p 00000000 00:00 0
                       7ff614559000-7ff61455c000 r-xp 00000000 08:01 22575                      /usr/lib64/libdl-2.22.so
                       7ff61455c000-7ff61475b000 ---p 00003000 08:01 22575                      /usr/lib64/libdl-2.22.so
                       7ff61475b000-7ff61475c000 r--p 00002000 08:01 22575                      /usr/lib64/libdl-2.22.so
                       7ff61475c000-7ff61475d000 rw-p 00003000 08:01 22575                      /usr/lib64/libdl-2.22.so
                       7ff61475d000-7ff614783000 r-xp 00000000 08:01 22505                      /usr/lib64/libtinfo.so.5.9
                       7ff614783000-7ff614982000 ---p 00026000 08:01 22505                      /usr/lib64/libtinfo.so.5.9
                       7ff614982000-7ff614986000 r--p 00025000 08:01 22505                      /usr/lib64/libtinfo.so.5.9
                       7ff614986000-7ff614987000 rw-p 00029000 08:01 22505                      /usr/lib64/libtinfo.so.5.9
                       7ff614987000-7ff6149a8000 r-xp 00000000 08:01 22702                      /usr/lib64/ld-2.22.so
                       7ff614ba0000-7ff614ba3000 rw-p 00000000 00:00 0
                       7ff614ba6000-7ff614ba7000 rw-p 00000000 00:00 0
                       7ff614ba7000-7ff614ba8000 r--p 00020000 08:01 22702                      /usr/lib64/ld-2.22.so
                       7ff614ba8000-7ff614ba9000 rw-p 00021000 08:01 22702                      /usr/lib64/ld-2.22.so
                       7ff614ba9000-7ff614baa000 rw-p 00000000 00:00 0
                       7fffd9873000-7fffd9894000 rw-p 00000000 00:00 0                          [stack]
                       7fffd9987000-7fffd9989000 r--p 00000000 00:00 0                          [vvar]
                       7fffd9989000-7fffd998b000 r-xp 00000000 00:00 0                          [vdso]
                       ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
    COREDUMP_PROC_LIMITS=Limit                     Soft Limit           Hard Limit           Units
                         Max cpu time              unlimited            unlimited            seconds
                         Max file size             unlimited            unlimited            bytes
                         Max data size             unlimited            unlimited            bytes
                         Max stack size            8388608              unlimited            bytes
                         Max core file size        unlimited            unlimited            bytes
                         Max resident set          unlimited            unlimited            bytes
                         Max processes             1876                 1876                 processes
                         Max open files            1024                 4096                 files
                         Max locked memory         65536                65536                bytes
                         Max address space         unlimited            unlimited            bytes
                         Max file locks            unlimited            unlimited            locks
                         Max pending signals       1876                 1876                 signals
                         Max msgqueue size         819200               819200               bytes
                         Max nice priority         0                    0
                         Max realtime priority     0                    0
                         Max realtime timeout      unlimited            unlimited            us
    COREDUMP_PROC_CGROUP=11:perf_event:/
                         10:memory:/user.slice/user-0.slice/session-1.scope
                         9:devices:/user.slice/user-0.slice/session-1.scope
                         8:pids:/user.slice/user-0.slice/session-1.scope
                         7:hugetlb:/
                         6:freezer:/
                         5:net_cls,net_prio:/
                         4:blkio:/user.slice/user-0.slice/session-1.scope
                         3:cpu,cpuacct:/user.slice/user-0.slice/session-1.scope
                         2:cpuset:/
                         1:name=systemd:/user.slice/user-0.slice/session-1.scope
    COREDUMP_CWD=/root
    COREDUMP_ROOT=/
    COREDUMP_ENVIRON=XDG_SESSION_ID=1
                     TERM=vt220
                     SHELL=/bin/bash
                     USER=root
                     MAIL=/var/mail/root
                     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
                     PWD=/root
                     SHLVL=1
                     HOME=/root
                     LOGNAME=root
                     XDG_RUNTIME_DIR=/run/user/0
                     _=/usr/bin/bash
    COREDUMP_TIMESTAMP=1456427253000000
    MESSAGE_ID=fc2e22bc6ee647b6b90729ab34a250b1
    PRIORITY=2
    COREDUMP_FILENAME=/var/lib/systemd/coredump/core.bash.0.172d45b51c5c4287885bc78bedeba156.428.1456427253000000000000.xz
    MESSAGE=Process 428 (bash) of user 0 dumped core.
    CODE_LINE=676
    CODE_FUNC=submit_coredump
    _SOURCE_REALTIME_TIMESTAMP=1456427259254412
```

**Pull request merged**
