### PR TITLE
wireguard: fix exponential backoff when resolving hosts

### PR DESCRIPTION
**Pull request by Mic92**
It should stop at 25s, not start.

### CODE REVIEW

**Comment by poettering** [comment]
Would probably benefit from a "Closes: #12134" line in the commit msg...

**Comment by poettering** [comment]
a bingo, you already force pushed exactly that... thanks!

**Comment by Mic92** [comment]
Already force pushed.

**Comment by Mic92** [comment]
Knock knock...
Race condition!
Who is there?

**Pull request merged**
