### PR TITLE
nspawn: use getgrouplist() to get group credentials

### PR DESCRIPTION
**Pull request by jsynacek**
Spawning getent is not needed. Furthermore, "getent initgroups" might not
be available on older systems.

### CODE REVIEW

**Comment by jsynacek** [comment]
@martinpitt How do I tell if the failure is actually because of my commit? Doesn't seem like it.

**Comment by martinpitt** [comment]
@jsynacek : indeed it doesn't seem to be, I just retried it.

**Comment by poettering** [comment]
Sorry, this isn't right. The process this is running in originates from the host, but lives in the container's namespace. As such it cannot really do any NSS calls directly, as the NSS expectations it has are from the host's but the NSS modules and configuration is from the containers. This breaks apart at various places: first of all if the host and container archs differ, hence the NSS calls couldn't even load the container's NSS plugins. Moreover the container's NSS modules might be linked against a different libc, different version or differently compiled, and hence cannot really combined with the host's libc even if the arch would be theoretically compatible. Then, the configuration in the container might differ substantially from the hosts, i.e. /etc/nsswitch.conf lists a very different set of modules than the host, but if the configuration is already loaded earlier before the transition into the container namespace then everything will be confusion.

We really really need the exec() transition here, so that the ABI of the container is used in configuraiton of the container. That's the only safe way to do this.

And yeah, it sucks that we use "getent" for that, but it's the only option I saw to make this work, as its the only tool for this that is generically available. I hope that makes sense.

Also see the original commit adding this bit:

0cb9fbcd44517ec90b2a678876194607beab5dec

Closing hence, I hope this makes sense

**Comment by jsynacek** [comment]
Ok, sounds reasonable, only one thing that I don't understand.

> first of all if the host and container archs differ, hence ...

A container of a different architecture than that of a host is not really runnable, right?

**Comment by poettering** [comment]
> Ok, sounds reasonable, only one thing that I don't understand.
> 
>     first of all if the host and container archs differ, hence ...
> 
> A container of a different architecture than that of a host is not really runnable, right?

Ah, sorry, that was supposed to say the archs *may* differ... And that's the case if the host is x86-64 and the payload i386. Which we do support just fine, but which makes any dlopen()ing of NSS modules of the container from the host's NSS code impossible. execve()ing i386 code from x86-64 is fully supported by the Linux kernel however.

**Pull request closed without merging**
