### PR TITLE
hwdb: add support for PineTab2 to 60-sensor.hwdb

### PR DESCRIPTION
**Pull request by entekadesign**
Add accelerometer support for PineTab2

### CODE REVIEW

**Review by yuwata — APPROVED** [review]

**Comment by raboof** [comment]
Are you confident these are the right values? I see this is what's discussed in https://forum.pine64.org/archive/index.php?thread-18322-3.html as well, but with this configured (with NixOS/Gnome) I don't get sensible behaviour.

Looking at `/sys/bus/iio/devices/iio:device1/in_accel_*_raw`, `y` is high when the tablet is flat on the table facing up, so I'd say the matrix should definitely be `? 0 ?; ? 0 ?; 0 1 0` - with that indeed all `tilt` and `face` output of `monitor-sensor` look correct.

I'm not entirely sure I understand the meaning of 'normal'.

With `1 0 0; 0 0 1; 0 1 0` the tablet seems to behave as I'd expect (`monitor-sensor` shows it considers itself 'normal' in portrait mode with the side with the physical buttons pointing upwards, and gnome correctly rotates the screen as necessary).

Trying with `0 0 1; 1 0 0; 0 1 0`, `monitor-sensor` shows it considers itself 'normal' in landscape mode with the keyboard connector at the bottom. This would also make sense to me, but then the rotation makes no sense, so I suppose this is not the way ;).

**Comment by raboof** [comment]
Looking at the 'official' image, that uses `0, 0, -1; 1, 0 0; 0, -1, 0` - and indeed `monitor-sensor` reports `face-up` when the tablet is facing down and vice-versa.

This does consider landscape 'normal' and works fine in KDE/Plasma here

**Comment by raboof** [comment]
`0, 0, -1; 1, 0 0; 0, 1, 0` seems to work correctly (considering the orientation with the keyboard connector at the bottom as 'normal').

Should I PR that to this repo?

**Comment by yuwata** [comment]
@raboof Please submit a fix. Thank you!

**Comment by raboof** [comment]
I haven't quite gotten it to work in GNOME yet (https://discourse.gnome.org/t/screen-orientation-auto-rotate-on-the-pinetab2/34026). This makes me not quite confident in the values yet - I'll PR when I find a configuration that I can get to work both in GNOME and Plasma.

**Comment by howl** [comment]
@raboof if you are into getting the screen output you should be more confident with GNOME, actually for KDE some devicex may have issues particularly if the panel mounted in another way. I can't found that for this device this is the case.

Anyway, you should take care of the monitor-sensor values are set to follow the panel orientation and not the casing.

**Pull request merged**
