### PR TITLE
Replace msgmerge use by gettext-domain= references

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by mbiebl** [comment]
nice. this will also cut down the installed size a bit. /usr/share/polkit-1/actions/org.freedesktop.login1.policy alone is over 200K

**Comment by mbiebl** [comment]
```
ninja -C build-deb/ systemd-pot
ninja: Entering directory `build-deb/'
[0/1] Running external command systemd-pot.
xgettext: cannot read /home/michael/debian/build-area/systemd-237/src/core/org.freedesktop.systemd1.policy.in.in: failed to load external entity "/home/michael/debian/build-area/systemd-237/src/core/org.freedesktop.systemd1.policy.in.in"

xgettext: warning: file 'src/core/org.freedesktop.systemd1.policy.in.in' extension 'policy' is unknown; will try C
xgettext: error while opening "src/core/org.freedesktop.systemd1.policy.in.in" for reading: No such file or directory
FAILED: meson-systemd-pot 
/usr/bin/python3 /usr/bin/meson --internal commandrunner /home/michael/debian/build-area/systemd-237 /home/michael/debian/build-area/systemd-237/build-deb po /usr/bin/python3 /usr/bin/meson /usr/bin/python3 /usr/bin/meson --internal gettext pot --pkgname=systemd --extra-args=--keyword=NC_:1c,2@@--flag=N_:1:pass-c-format@@--flag=g_string_append_printf:2:c-format@@--keyword=g_dcgettext:2@@--flag=g_strdup_printf:1:c-format@@--keyword=N_@@--keyword=_@@--keyword=g_dpgettext2:2c,3@@--flag=NC_:2:pass-c-format@@--flag=g_set_error:4:c-format@@--flag=C_:2:pass-c-format@@--flag=g_dngettext:2:pass-c-format@@--flag=g_error_new:3:c-format@@--add-comments@@--keyword=C_:1c,2@@--from-code=UTF-8@@--flag=g_string_printf:2:c-format@@--keyword=g_dngettext:2,3
ninja: build stopped: subcommand failed.
```
I guess po/POTFILES.in and po/POTFILES.skip needs to be updated accordingly

**Comment by mbiebl** [comment]
```
Index: systemd-237/po/POTFILES.in
===================================================================
--- systemd-237.orig/po/POTFILES.in↦    2018-02-16 14:05:13.000000000 +0100
+++ systemd-237/po/POTFILES.in↦ 2018-02-16 14:05:13.000000000 +0100
@@ -1,9 +1,9 @@
-src/core/org.freedesktop.systemd1.policy.in.in
-src/hostname/org.freedesktop.hostname1.policy.in
-src/import/org.freedesktop.import1.policy.in
-src/locale/org.freedesktop.locale1.policy.in
-src/login/org.freedesktop.login1.policy.in
-src/machine/org.freedesktop.machine1.policy.in
-src/timedate/org.freedesktop.timedate1.policy.in
+src/core/org.freedesktop.systemd1.policy.in
+src/hostname/org.freedesktop.hostname1.policy
+src/import/org.freedesktop.import1.policy
+src/locale/org.freedesktop.locale1.policy
+src/login/org.freedesktop.login1.policy
+src/machine/org.freedesktop.machine1.policy
+src/timedate/org.freedesktop.timedate1.policy
 src/core/dbus-unit.c
 src/fsckd/fsckd.c
Index: systemd-237/po/POTFILES.skip
===================================================================
--- systemd-237.orig/po/POTFILES.skip↦  2018-02-16 14:05:13.000000000 +0100
+++ systemd-237/po/POTFILES.skip↦       2018-02-16 14:05:53.767882852 +0100
@@ -12,9 +12,9 @@
 src/core/dbus-timer.c
 src/core/dbus-unit.c
 src/core/dbus-scope.c
+src/core/org.freedesktop.systemd1.policy
 src/hostname/hostnamed.c
 src/locale/localed.c
-src/core/org.freedesktop.systemd1.policy.in
 src/timedate/timedated.c
 units/user@.service.in
 units/debug-shell.service.in
```
should do the trick

**Comment by martinpitt** [comment]
I'm working on updating the https://code.launchpad.net/~pitti/systemd/+git/debian mirror for the recently changed Debian packaging git location; this might help with fixing CI.

**Comment by keszybz** [comment]
@mbiebl can you just push that to my branch?

**Comment by mbiebl** [comment]
> @mbiebl can you just push that to my branch?

How can I do that? I don't think I can push to https://github.com/keszybz/systemd or can I?

**Comment by keszybz** [comment]
You should see "Add more commits by pushing to the avoid-msgmerge branch on keszybz/systemd." at the bottom of this page. If yes, you can push to my branch. Something along the lines of:
```sh
git push git@github.com:keszybz/systemd {src}:{dst}
```

**Comment by mbiebl** [comment]
```
git push git@github.com:keszybz/systemd keszybz-avoid-msgmerge:keszybz-avoid-msgmerge 
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 621 bytes | 621.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:keszybz/systemd
 ! [remote rejected]     keszybz-avoid-msgmerge -> keszybz-avoid-msgmerge (permission denied)
error: failed to push some refs to 'git@github.com:keszybz/systemd'
```

**Comment by mbiebl** [comment]
Ah, my bad.
works with ```git push git@github.com:keszybz/systemd keszybz-avoid-msgmerge:avoid-msgmerge```

**Comment by keszybz** [comment]
I pushed an updated version that keeps polkit.{its,loc} and fixes the systemd-pot target.

**Pull request merged**
