### PR TITLE
Fix the ejectcd button on Alienware M17XR3 laptops.

### LINKED ISSUE #14232: Alienware M17X R3 laptop ejectcd fix.
**Every** distribution i have used , i have to _manually_ setup my ejectcd button. After reading the comments in `/lib/udev/hwdb.d/60-keyboard.hwdb`, i would like to try and fix this issue.

in /lib/udev/hwdb.d/60-keyboard.hwdb there is this line:

`evdev:atkbd:dmi:bvn*:bvr*:bd*:svnAlienware*:pn*`
`KEYBOARD_KEY_8a=ejectcd`

This can be changed by creating:

`/lib/udev/hwdb.d/70-alienware-fix.hwdb`

with the contents of:

`evdev:atkbd:dmi:bvn*:bvr*:bd*:svnAlienware*:pn*`
` KEYBOARD_KEY_89=ejectcd`

However, the output of `udevadm info /dev/input/event4` looks like this:
(event4 being the AT keyboard)

P: /devices/platform/i8042/serio0/input/input4/event4
N: input/event4
S: input/by-path/platform-i8042-serio-0-event-kbd
E: BACKSPACE=guess
E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-0-event-kbd
E: DEVNAME=/dev/input/event4
E: DEVPATH=/devices/platform/i8042/serio0/input/input4/event4
E: ID_BUS=i8042
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_PATH=platform-i8042-serio-0
E: ID_PATH_TAG=platform-i8042-serio-0
E: ID_SERIAL=noserial
E: KEYBOARD_KEY_89=ejectcd
E: KEYBOARD_KEY_8a=ejectcd
E: KEYBOARD_KEY_bf=!prog1
E: KEYBOARD_KEY_c1=!prog2
E: KEYBOARD_KEY_c2=!power
E: LIBINPUT_ATTR_KEYBOARD_INTEGRATION=internal
E: LIBINPUT_DEVICE_GROUP=11/1/1:isa0060/serio0
E: MAJOR=13
E: MINOR=68
E: SUBSYSTEM=input
E: TAGS=:power-switch:
E: USEC_INITIALIZED=44528998
E: XKBLAYOUT=us
E: XKBMODEL=pc105

While editing rules directly in `/lib/udev/hwdb.d/60-keyboard.hwdb`, afer running `udevadm info /dev/input/event4` i get:

P: /devices/platform/i8042/serio0/input/input4/event4
N: input/event4
S: input/by-path/platform-i8042-serio-0-event-kbd
E: BACKSPACE=guess
E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-0-event-kbd
E: DEVNAME=/dev/input/event4
E: DEVPATH=/devices/platform/i8042/serio0/input/input4/event4
E: ID_BUS=i8042
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_PATH=platform-i8042-serio-0
E: ID_PATH_TAG=platform-i8042-serio-0
E: ID_SERIAL=noserial
E: KEYBOARD_KEY_89=ejectcd
E: KEYBOARD_KEY_bf=!prog1
E: KEYBOARD_KEY_c1=!prog2
E: KEYBOARD_KEY_c2=!power
E: LIBINPUT_ATTR_KEYBOARD_INTEGRATION=internal
E: LIBINPUT_DEVICE_GROUP=11/1/1:isa0060/serio0
E: MAJOR=13
E: MINOR=68
E: SUBSYSTEM=input
E: TAGS=:power-switch:
E: USEC_INITIALIZED=44528998
E: XKBLAYOUT=us
E: XKBMODEL=pc105

As you can see, it's really only one character that needs changing...

These are some of the best sources i can find on the subject (aside from the comments in `/lib/udev/hwdb.d/60-keyboard.hwdb`):

https://wiki.archlinux.org/index.php/Keyboard_input
https://wiki.archlinux.org/index.php/Map_scancodes_to_keycodes#Using_udev

### PR DESCRIPTION
**Pull request by lothrond**
I would like to try and help fix this.

Fixes #14232.

### CODE REVIEW

**Comment by poettering** [comment]
hmm, the rule seems overly generic... I figure the new rule should be more specific? Or are you sure that all Alienware laptops are affected by the wrong key mapping?

hmm, @jwrdegoede @whot maybe this is something you can comment on? any idea? (@whot you committed the original line says git blame?)

**Comment by whot** [comment]
Nah, I decline any responsibility here :)

`git blame` shows me because I replaced the `keyboard:` prefix with `evdev:` a while ago but that's it. That match has always been in the hwdb, it came from udev commit 46505c52a61cbc9c9465eb676d3693bb32e65615 and goes back to https://bugs.launchpad.net/ubuntu/+source/udev/+bug/901513.

@lothrond: let's assume that all Alienwares so far had the eject button configured correctly, so this new one needs a separate match specific to this machine.

**Comment by lothrond** [comment]
I see. So, maybe something like:

    evdev:atkbd:dmi:bvn*:bvr*:bd*:svnAlienware*:pn*0520*
     KEYBOARD_KEY_89=ejectcd

Should i submit this as a seperate pull request?

**Comment by yuwata** [comment]
Please use force-push.

**Comment by yuwata** [comment]
Please drop the first commit...

**Comment by whot** [comment]
@lothrond what's your full dmi modalias? it's always a bit hard to guess whether a match string is correct or not, seeing the full dmi modalias helps with that.

**Comment by lothrond** [comment]
> Please drop the first commit...

Sorry. 

@whot Should i just post the output of  `dmidecode` ?

**Comment by whot** [comment]
@lothrond just `cat /sys/class/dmi/id/modalias`, that's what we match against

**Comment by lothrond** [comment]
@whot output of `cat /sys/class/dmi/id/modalias`:

    dmi:bvnAlienware:bvrA08:bd07/29/2011:svnAlienware:pnM17xR3:pvrA08:rvnAlienware:rnM17xR3:rvrA08:cvnAlienware:ct8:cvrA08:

**Comment by lothrond** [comment]
@whot I'm not sure if this is helpful, but here also is the output of `lsusb | grep Alienware`:

    Bus 002 Device 004: ID 187c:0520 Alienware Corporation

**Comment by whot** [comment]
I'd go with this one then:
```
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnAlienware*:pnM17xR3:*
 KEYBOARD_KEY_89=ejectcd
```
Easier to identify. Please do test this though, I just copy/pasted it.

And I wonder: how did the `pn*0520*` work? there's no 0520 string in the modalias so this couldn't have applied.

**Comment by lothrond** [comment]
@whot I am not sure if my understanding on this is correct. For this laptop it seems `svn` can be something like `Alienware*` or `*187c*` etc. While `pn` can be `M17xR3*` or `*0520*` etc. I'm just not sure which is more appropriate. (All of these seem to work after reloading rules, rebooting, etc). Is this correct?

**Comment by whot** [comment]
wait, what? the dmi modalias actually changes? 187c is the Alienware usb vendor ID. but the hwdb modalias match is a string match so unless the modalias has different value you're getting a false positive.

have you removed the original entry and run `systemd-hwdb --update`? If not, you still have the original entry in the binary hwdb and the new chances haven't taken effect yet.

**Comment by lothrond** [comment]
@whot Whenever i change `/lib/udev/hwdb.d/60-keybord.hwdb` i issue the following commands as root:

    systemd-hwdb update
    udevadm trigger /dev/input/event4

(I copy/paste these from the comments)

I check to see if it works, and it does. Then i reboot. Everything still works...

**Comment by whot** [comment]
check with `sudo udevadm test /sys/class/input/event4` if the `KEYBOARD_KEY_...` property shows up correctly please.

**Comment by lothrond** [comment]
> `sudo udevadm test /sys/class/input/event4`

Yes it does.

**Comment by whot** [comment]
honestly, I don't know then. That `pn` match you had should not match against that modalias but I don't know of any good debugging tools to give simple instructions to debug this further. I'm ok with merging that modified snippet though (with the actual model name) because it looks correct and I don't see a reason why it shouldn't work.

**Comment by lothrond** [comment]
> I'd go with this one then:
> 
> ```
> evdev:atkbd:dmi:bvn*:bvr*:bd*:svnAlienware*:pnM17xR3:*
>  KEYBOARD_KEY_89=ejectcd
> ```
>
I think you are right.

**Pull request merged**
