### PR TITLE
Remove python-systemd

### PR DESCRIPTION
**Pull request by keszybz**
python-system has moved to it's own repository:
https://github.com/systemd/python-systemd

This isn't supposed to be merge right away. The right time frame is probably about systemd-223.

### CODE REVIEW

**Comment by zonque** [comment]
Nice, thanks for that! We still have to wait for the distros to catch up and package that new project. I'd suggest we give a heads-up in the release notes of v222 and remove it once the release is done. @poettering, @kaysievers?

**Comment by martinpitt** [comment]
OOI, what's the gain for splitting this out? The two projects/packages need to be kept in sync, and you already need python as a build dependency for systemd itself to build the documentation.

**Comment by martinpitt** [comment]
Nevermind, the PR in my mailbox came before the ML discussion. For reference: http://lists.freedesktop.org/archives/systemd-devel/2015-July/033443.html

**Comment by zonque** [comment]
Ok, v222 is out, time to open the flood gates :)

**Pull request merged**
