### PR TITLE
systemctl fallback error propagation fix

### PR DESCRIPTION
**Pull request by poettering**
A fix for #11546

### CODE REVIEW

**Comment by yuwata** [comment]
```
test_unit_sysv_alias_disable (__main__.EnableTests)
with sysv: disable unit with an alias ... Synchronizing state of test_enable.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable test_enable
Usage: /lib/systemd/systemd-sysv-install [--root=path] enable|disable|is-enabled <sysv script name>
ERROR
test_unit_sysv_alias_enable (__main__.EnableTests)
with sysv: enable unit with an alias ... Synchronizing state of test_enable.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable test_enable
Usage: /lib/systemd/systemd-sysv-install [--root=path] enable|disable|is-enabled <sysv script name>
ERROR
test_unit_sysv_disable (__main__.EnableTests)
with sysv: disable unit ... Synchronizing state of test_enable.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable test_enable
Usage: /lib/systemd/systemd-sysv-install [--root=path] enable|disable|is-enabled <sysv script name>
ERROR
test_unit_sysv_enable (__main__.EnableTests)
with sysv: enable unit ... Synchronizing state of test_enable.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable test_enable
Usage: /lib/systemd/systemd-sysv-install [--root=path] enable|disable|is-enabled <sysv script name>
ERROR
```

**Comment by poettering** [comment]
I don't really grok the CI failure. In order to making this simpler I have now split out some work into #12052, ptal.

**Comment by poettering** [comment]
OK, now i am weirded out. When splitting out #12052 i ssumed that it was this one remaining commit that was causing the earlier CI failures. But as it turns out this is the one that works...

Anyway, please have a look, apparently this one should work fine then

**Comment by keszybz** [comment]
This looks simple and safe enough. Let's merge.

**Pull request merged**
