### PR TITLE
Fix shutdown hang caused by recent udev change

### LINKED ISSUE #14128: A stop job is running for udev Kernel Device Manager - systemd 243.162-2 - initramfs delay
**systemd version the issue has been seen with**
> systemd 243.162-2
>
>systemd 243 (243.162-2-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
>ARCH
>
>Linux 5.3.12-arch1-1 SMP PREEMPT Wed, 20 Nov 2019 19:45:16 +0000 x86_64 GNU/Linux

**Expected behaviour you didn't see**
 > normal boot including initramfs

**Unexpected behaviour you saw**
 > 30 sec delay due to "A stop job is running for udev Kernel Device Manager" message

**Steps to reproduce the problem**
>Boot with systemd initramfs with version systemd 243.162-2. 
>
>Steps to avoid - revert commit [5db454b](https://github.com/systemd/systemd-stable/commit/5db454b8031c58a743cc4ee3d5d1dd01dcff17e8)
>
>Dmesg from an affected [boot](http://0x0.st/z6DJ.txt)

### PR DESCRIPTION
**Pull request by mwilck**
This should fix #14128 and #14140.

### CODE REVIEW

**Comment by mwilck** [comment]
030f457 is an alternative fix for the NULL pointer dereference that 5db454b was supposed to fix, but without the side effects.

I still don't fully understand why these side effects occured, but I have a theory. The monitor is basically a netlink socket. With 5db454b, we  keep the socket open until manager_free(), so some worker might try to use it and block in the process. This in turn might cause the worker not to terminate, and the manager to keep waiting for it. If, OTOH, the socket is closed, any attempt  by a worker to access it would fail, and the worker would just exit.

Whether or not this theory is correct, the new fix should avoid side effects, because it preserves the previous runtime behavior, except trying to use the freed monitor pointer.

**Comment by mwilck** [comment]
I can confirm that the crash in `on_sigchld()` isn't observed any more with this code.
Reporters of regressions in #14128 and #14140 confirmed also that their regressions are gone.

**Comment by yuwata** [comment]
The change itself is OK. But I'd like to understand why the previous code causes the issues.

**Comment by mwilck** [comment]
@yuwata, I haven't reproduced it. I can only offer the theory above, which is the only possible explanation I can think of. Other than that, the only option I see is to add debug code to verify or falsify my theory.

**Comment by yuwata** [comment]
OK. Anyway, this fixes the issues. Let's merge.

**Comment by mwilck** [comment]
Here's another theory, and this time I think I got it right. It's based on my analysis of @CarbonChauvinist's last logs from https://github.com/systemd/systemd/issues/14128#issuecomment-55868043. 

    Nov 26 09:56:45 archlinux systemd[1]: systemd-udevd.service: Changed running -> stop-sigterm 
    ...
    Nov 26 09:56:45 archlinux systemd-udevd[195]: Worker [200] exited
    ...
    Nov 26 09:56:45 archlinux systemd-udevd[195]: target1:0:0: Device (SEQNUM=2021, ACTION=add) is queued
    ...
    Nov 26 09:56:45 archlinux systemd-udevd[195]: Worker [215] exited
    Nov 26 09:56:45 archlinux systemd-udevd[195]: 1-4: Device (SEQNUM=2025, ACTION=add) is queued
    ...
    Nov 26 09:56:45 archlinux systemd-udevd[195]: 1-12: Device (SEQNUM=2032, ACTION=bind) is queued
    ...
    Nov 26 09:57:15 archlinux systemd-udevd[195]: Giving up waiting for workers to finish.
    Nov 26 09:57:15 archlinux systemd-udevd[195]: Event loop failed: Connection timed out
   
You can see that new events are being queued after udevd received SIGTERM. If the queue isn't empty, `on_post()` returns immediately, and `sd_event_exit()` isn't called, so udevd's event loop continues to run. Obviously, if the device monitor has been shut down, this can't happen - no new events can be received and queued. That's why my patch deferring the device monitor shutdown caused the regression: Now udevd could receive more events after being told to exit.

One might argue that the logic in `on_post()` is flawed, and that the test for `manager->exit` should be made first, before checking for pending events. But as the patch provided here fixes the issue, I'd rather not take this route at this time.

**Pull request merged**
