### PR TITLE
Always create dependencies for bind mounts

### PR DESCRIPTION
**Pull request by Werkov**
Dependencies were not created for `_netdev` mountpoints, the reasoning for this
is in the commit fc676b00, i.e. to avoid adding dependencies for network
mountpoints where `What=` appears like a path. Thus proposing this semantically
more correct condition when dependencies are added for _actual_ bind mounts
only. Consequently, it allows to add `_netdev` option to bind mounts, which
includes them in `remote-fs.target`, which simplifies configuration.

### CODE REVIEW

**Comment by poettering** [comment]
@keszybz hmm, you made the original change here, any idea?

**Comment by keszybz** [comment]
I think the comment was misleading:

```
  /* Adds in links to other mount points that might be needed
          * for the source path (if this is a bind mount) to be
          * available. */
```

`unit_require_mounts_for` in fact also applies to other things, for example loop mounts.

I added the following example line in `/etc/fstab`:

```
/home/zbyszek/testfile /mnt/testfile             ex4      loop 0 0
```

This results in

```
$ systemctl show -p After,Before,RequiresMountsFor,Wants,Requires /mnt/testfile
Requires=system.slice home.mount -.mount
Wants=
Before=umount.target local-fs.target
After=system.slice local-fs-pre.target -.mount systemd-journald.socket home.mount
RequiresMountsFor=/mnt /home/zbyszek/testfile
```

With you patch this would be broken and the dependencies on /home would not be generated.

I think you instead must add mount_is_bind as as an alternate condition:

```
 if (pm && pm->what && path_is_absolute(pm->what) &&
     (mount_is_bind(pm) || !mount_is_network(pm))) {
```

**Comment by Werkov** [comment]
> `unit_require_mounts_for` in fact also applies to other things, for example loop mounts.

Right, I've forgotten about this. I've updated the patch to your suggestion.
I've also added another test that'd enable the loop devices mentioned by you.

(A different approach would be to replace the original `mount_is_network` condition with check for `//` to prevent cifs mounts addresses to be interpreted as a local absolute path. It'd suffer the opposite drawback, there could be useless dependencies for other filesystems whose address would appear as an absolute path.)

**Comment by poettering** [comment]
This looks fishy to me. @keszybz's original patch was supposed to avoid these incorrect dependencies when a CIFS file system is used, but this patch adds them to bind mounds of CIFS file systems again, which looks really wrong.

Ideally we could use /proc/filesystems to identify "nodev" file systems correctly, but unfortunately that file is only populated after the kernel modules are loaded, hence not useful as a database for generated dependencies to require before we can mount a file system...

I think we should try harder to identify local file system paths. Currently we use path_is_absolute(), but that's not sufficient to detect CIFS file systems. I think we should add a new function to mount.c that looks something like this:

``` c
static bool mount_source_is_local_path(const char *p) {
        if (isempty(p))
                return false;
        /* Require a slash at the beginning, but filter out CIFS paths that start with a double slash. 
           Note that strictly speaking local Linux paths names may use multiple slashes instead of one
           to seperate directory names, but at least the kernel cleans that up in /proc/self/mountinfo. */
        return p[0] == '/' && p[1] != '/';
}
```

And then use that to detect local paths in a slightly stricter way than path_is_absolute(). Does this make sense?

**Comment by Werkov** [comment]
The bind bound can't be a CIFS mount at the same time, so the dependencies won't be added in this case. However, you're right it's not targeting the original issue nicely, I like the semantics of `is_local_path` better. @keszybz, do you see any catches in that approach?

**Comment by keszybz** [comment]
I don't think that `is_local_path` can work, because it would be very unreliable. This logic is used on "fragment" paths, so we cannot rely on the kernel to help us. And whether a path starts with "//" is a hint, but not useful for automatic detection: so far it was perfectly legal to specify a path with "//" and we shouldn't suddenly disallow that, and on the other hand, not all network filesystems uses paths that start with "//", e.g. nfs.

The patch in this PR is correct. I see the following cases:
before:

```
//server/share  /foo cifs   defaults    → no
non-path        /foo some-type  defaults    → no
server:/path    /foo nfs    defaults    → no
/server/path    /foo new-network-fs defaults    → yes ²
/server/path    /foo new-network-fs _netdev → no
```

with proposed patches:

```
/some/mount /foo none   _netdev,bind    → yes
/some/file  /foo ext4   loop        → yes ³
```

(where "yes" means call `unit_require_mounts_for(u, what)`).

² If we don't know the fs type, we default to yes. We allow _netdev to be explicitly specified to allow users to override the logic.

³ The second patch in the PR adds loop mounts as an explicit test case. It doesn't change much because normally loop would be used with some local fs type. But it's good to be explicit about this case.

I think we should merge this.

**Comment by keszybz** [comment]
See also #3140.

**Pull request merged**
