### PR TITLE
network: include linux/fou.h if it exists

### LINKED ISSUE #10474: `systemd` seems to be failing to compile on CentOS
It was originally discovered in https://github.com/systemd/systemd-centos-ci/issues/14#issuecomment-431569212. Looks like the `ifdef` magic added in  53cb501a1314740fa777f doesn't work
```sh
../src/libsystemd/sd-netlink/netlink-types.c:742:10: error: ‘FOU_ATTR_PORT’ undeclared here (not in a function)
         [FOU_ATTR_PORT]              = { .type = NETLINK_TYPE_U16 },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:742:9: error: array index in initializer not of integer type
         [FOU_ATTR_PORT]              = { .type = NETLINK_TYPE_U16 },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:742:9: error: (near initialization for ‘genl_fou_types’)
../src/libsystemd/sd-netlink/netlink-types.c:743:10: error: ‘FOU_ATTR_AF’ undeclared here (not in a function)
         [FOU_ATTR_AF]                = { .type = NETLINK_TYPE_U8 },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:743:9: error: array index in initializer not of integer type
         [FOU_ATTR_AF]                = { .type = NETLINK_TYPE_U8 },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:743:9: error: (near initialization for ‘genl_fou_types’)
../src/libsystemd/sd-netlink/netlink-types.c:744:10: error: ‘FOU_ATTR_IPPROTO’ undeclared here (not in a function)
         [FOU_ATTR_IPPROTO]           = { .type = NETLINK_TYPE_U8 },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:744:9: error: array index in initializer not of integer type
         [FOU_ATTR_IPPROTO]           = { .type = NETLINK_TYPE_U8 },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:744:9: error: (near initialization for ‘genl_fou_types’)
../src/libsystemd/sd-netlink/netlink-types.c:745:10: error: ‘FOU_ATTR_TYPE’ undeclared here (not in a function)
         [FOU_ATTR_TYPE]              = { .type = NETLINK_TYPE_U8 },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:745:9: error: array index in initializer not of integer type
         [FOU_ATTR_TYPE]              = { .type = NETLINK_TYPE_U8 },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:745:9: error: (near initialization for ‘genl_fou_types’)
../src/libsystemd/sd-netlink/netlink-types.c:746:10: error: ‘FOU_ATTR_REMCSUM_NOPARTIAL’ undeclared here (not in a function)
         [FOU_ATTR_REMCSUM_NOPARTIAL] = { .type = NETLINK_TYPE_FLAG },
          ^
../src/libsystemd/sd-netlink/netlink-types.c:746:9: error: array index in initializer not of integer type
         [FOU_ATTR_REMCSUM_NOPARTIAL] = { .type = NETLINK_TYPE_FLAG },
         ^
../src/libsystemd/sd-netlink/netlink-types.c:746:9: error: (near initialization for ‘genl_fou_types’)
[177/1650] Compiling C object 'src/libsystemd/src@libsystemd@@systemd_static@sta/sd-netlink_rtnl-message.c.o'.
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for 53cb501a1314740fa777f145067cefccda954487.

Fixes #10474.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx and @mrc0mmand .

**Comment by evverx** [comment]
@yuwata thank you! It seems that there is one `HAVE_FOU_CMD_GET` left in `missing.h`:
```sh
[1/1191] Compiling C object 'src/network/src@network@@networkd-core@sta/meson-generated_.._netdev-gperf.c.o'.
FAILED: src/network/src@network@@networkd-core@sta/meson-generated_.._netdev-gperf.c.o
cc -Isrc/network/src@network@@networkd-core@sta -Isrc/network -I../src/network -Isrc/basic -I../src/basic -Isrc/shared -I../src/shared -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/udev -I../src/udev -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I../ -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-error=nonnull -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -fPIE -Werror=shadow -include config.h -g -O0 -ftrapv -fPIC  -MD -MQ 'src/network/src@network@@networkd-core@sta/meson-generated_.._netdev-gperf.c.o' -MF 'src/network/src@network@@networkd-core@sta/meson-generated_.._netdev-gperf.c.o.d' -o 'src/network/src@network@@networkd-core@sta/meson-generated_.._netdev-gperf.c.o' -c src/network/netdev-gperf.c
In file included from ../src/basic/util.h:28:0,
                 from ../src/basic/hashmap.h:10,
                 from ../src/basic/set.h:5,
                 from ../src/libsystemd-network/network-internal.h:11,
                 from ../src/network/netdev/netdev-gperf.gperf:7:
../src/basic/missing.h:1433:24: error: expected identifier before numeric constant
 #define FOU_CMD_UNSPEC 0
                        ^
```

**Comment by evverx** [comment]
Judging by https://github.com/torvalds/linux/commit/7a6c8c34e5b71ac50e39588e20b39494a9e1d8e5#diff-dac4cbde9d4d041e26c9e2ba210790cd, the absence of `FOU_CMD_GET` doesn't mean that everything else doesn't exist.

**Comment by evverx** [comment]
Judging by https://github.com/torvalds/linux/commit/fe881ef11cf0220f118816181930494d484c4883#diff-dac4cbde9d4d041e26c9e2ba210790cd, the use of `HAVE_FOU_ATTR_REMCSUM_NOPARTIAL` isn't entirely correct either.

Anyway I wouldn't say I fully understand what's going on there. I'd wait for @ssahani to take a look.

**Comment by yuwata** [comment]
@evverx Updated. Thank you for the references.

**Comment by mrc0mmand** [comment]
Tried to compile systemd with this PR on CentOS 7 and it went flawlessly, thanks!
```
[root@host-8-244-57 ~]# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 
[root@host-8-244-57 ~]# uname -r
3.10.0-862.14.4.el7.x86_64
[root@host-8-244-57 ~]# systemctl --version
systemd 239
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**Comment by evverx** [comment]
That's what happened when I copied and pasted `1-fou-tunnel.netdev` from https://github.com/systemd/systemd/pull/9170:
```sh
fou-tun: Failed to allocate generic netlink message: Connection timed out
Could not load configuration files: Connection timed out
systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
systemd-networkd.service: Failed with result 'exit-code'.
```
Is it expected that `networkd` fails to start? Why doesn't it simply ignore the error on a machine where the feature isn't supported? Can't it detect that and log something more useful like "the feature isn't supported here"?

**Comment by evverx** [comment]
That's what happened when I copied and pasted `1-fou-tunnel.netdev` from https://github.com/systemd/systemd/pull/9170:
```sh
fou-tun: Failed to allocate generic netlink message: Connection timed out
Could not load configuration files: Connection timed out
systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
systemd-networkd.service: Failed with result 'exit-code'.
```
Is it expected that `networkd` fails to start? Why doesn't it simply ignore the error on a machine where the feature isn't supported? Can't it detect that and log something more useful like "the feature isn't supported here"?

**Comment by evverx** [comment]
That's what happened when I copied and pasted `1-fou-tunnel.netdev` from https://github.com/systemd/systemd/pull/9170:
```sh
fou-tun: Failed to allocate generic netlink message: Connection timed out
Could not load configuration files: Connection timed out
systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
systemd-networkd.service: Failed with result 'exit-code'.
```
Is it expected that `networkd` fails to start? Why doesn't it simply ignore the error on a machine where the feature isn't supported? Can't it detect that and log something more useful like "the feature isn't supported here"?

**Comment by poettering** [comment]
> Is it expected that `networkd` fails to start? Why doesn't it simply ignore the error on a machine where the feature isn't supported? Can't it detect that and log something more useful like "the feature isn't supported here"?

Yes, that's how it should work. If it doesn't, it's a bug. Please file it as one.

**Comment by evverx** [comment]
@yuwata I don't think anything has changed since I wrote the last comment so it's most likely 100% reproducible. On the other hand, I can't keep up with all the issues I've already opened as it is :-) and it's unlikely that I'd be able to respond in a timely manner if the issue was created (plus, honestly, I wouldn't say that that particular issue bothers me too much) so I decided to let it go :-)

**Pull request merged**
