### PR TITLE
boot: More BCD parser fixes

### PR DESCRIPTION
**Pull request by medhefgo**
Partially fixes: #21917

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
We'd probably want this on both ARM and x86, since those are the architectures that Windows is available on.

**Comment by evverx** [comment]
Thanks!

I'm not familiar with that part of the build system so I have a (probably stupid) question about `efi_arch`. Is it set correctly when `systemd-boot` is cross-compiled? Looking at docs/PORTING_TO_NEW_ARCHITECTURES.md it seems it isn't auto detected but just to be sure.

> We'd probably want this on both ARM

The bcd parser should align memory on the fly to make it work and it doesn't do that currently

**Comment by medhefgo** [comment]
> Is it set correctly when `systemd-boot` is cross-compiled?

[It should be.](https://github.com/systemd/systemd/blob/e99f8605e2990afa030b67d2bf7c275f3326509f/src/boot/efi/meson.build#L20)

**Comment by evverx** [comment]
Thanks for the link! Looking at https://mesonbuild.com/Reference-manual_builtin_target_machine.html#target-machine-information-target_machine-extends-build_machine it seems `target_machine` should be there instead of `host_machine` but given that nobody seems to have complained so far it probably works as expected.

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
Why not fix `get_bcd_title()`??

**Comment by evverx** [comment]
> Why not fix get_bcd_title()??

@yuwata my understanding is that the parser was supposed to work on x86 only (at least initially) so I thought it wouldn't make sense to fix it to just please UBSan. If it should work elsewhere I agree it should probably be fixed. Then again, I came across the parser accidentally trying to build my fuzzers with honggfuzz/afl so I'm in the dark about it generally :-)

**Comment by yuwata** [comment]
@evverx I see. Thanks.

**Comment by evverx** [comment]
Those warnings should be dealt with on x86 somehow though: https://github.com/systemd/systemd/pull/21727#issuecomment-1001624144 but considering there is no testing infrastructure yet it can be ignored kind of :-)

**Comment by medhefgo** [comment]
It seems the only locations ubsan is complaining about are these and rejecting those offsets is fine. I assume the compiler does some magic sauce if the (unaligned) data is accessed through structs? Or the fuzzer just hasn't tried misaligned those.

**Comment by evverx** [comment]
@medhefgo as far as I can see on non-x86 architectures the parser seems to just crash with something like
```
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==98234==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x08eb8000 (pc 0x080c61f1 bp 0xffee4718 sp 0xffee4670 T98234)
==98234==The signal is caused by a READ memory access.
    #0 0x80c61f1 in get_key_value /home/vagrant/systemd/build/../src/boot/efi/bcd.c:184:33
    #1 0x80c5369 in get_bcd_title /home/vagrant/systemd/build/../src/boot/efi/bcd.c:260:46
    #2 0x80c4dfd in LLVMFuzzerTestOneInput /home/vagrant/systemd/build/../src/boot/efi/fuzz-bcd.c:21:27
    #3 0x80779e6 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned int) (/home/vagrant/systemd/out/fuzz-bcd+0x80779e6)
    #4 0x8078711 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned int, bool, fuzzer::InputInfo*, bool, bool*) (/home/vagrant/systemd/out/fuzz-bcd+0x8078711)
    #5 0x807b2be in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/vagrant/systemd/out/fuzz-bcd+0x807b2be)
    #6 0x807b7a8 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/vagrant/systemd/out/fuzz-bcd+0x807b7a8)
    #7 0x8060641 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned int)) (/home/vagrant/systemd/out/fuzz-bcd+0x8060641)
    #8 0x804ecd0 in main (/home/vagrant/systemd/out/fuzz-bcd+0x804ecd0)
    #9 0xf71c0468 in __libc_start_call_main (/lib/libc.so.6+0x25468)
    #10 0xf71c0549 in __libc_start_main@GLIBC_2.0 (/lib/libc.so.6+0x25549)
    #11 0x804ed3b in _start (/home/vagrant/systemd/out/fu
```

**Comment by evverx** [comment]
To be precise it seems to crash on i386 as well so as far as I can tell it can only work on x86_64

**Comment by medhefgo** [comment]
Is that with the new code, though?

**Comment by evverx** [comment]
Oh, sorry. I haven't pulled the latest version of the PR yet. I'll report back once it's ready

**Comment by evverx** [comment]
Looks like on x86_64 UBsan no longer complains. Thanks!

I also compiled it with `-m32` and it seems to be failing there with
```
==104646==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x0a115000 (pc 0x080c62bf bp 0xffdd9f98 sp 0xffdd9ef0 T104646)
==104646==The signal is caused by a READ memory access.
    #0 0x80c62bf in get_key_value /home/vagrant/systemd/build/../src/boot/efi/bcd.c:185:33
    #1 0x80c579c in get_bcd_title /home/vagrant/systemd/build/../src/boot/efi/bcd.c:308:45
    #2 0x80c4dfd in LLVMFuzzerTestOneInput /home/vagrant/systemd/build/../src/boot/efi/fuzz-bcd.c:21:27
    #3 0x80779e6 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned int) (/home/vagrant/systemd/out/fuzz-bcd+0x80779e6)
    #4 0x8078711 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned int, bool, fuzzer::InputInfo*, bool, bool*) (/home/vagrant/systemd/out/fuzz-bcd+0x8078711)
    #5 0x8079c6a in fuzzer::Fuzzer::MutateAndTestOne() (/home/vagrant/systemd/out/fuzz-bcd+0x8079c6a)
    #6 0x807b948 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/vagrant/systemd/out/fuzz-bcd+0x807b948)
    #7 0x8060641 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned int)) (/home/vagrant/systemd/out/fuzz-bcd+0x8060641)
    #8 0x804ecd0 in main (/home/vagrant/systemd/out/fuzz-bcd+0x804ecd0)
    #9 0xf71ce468 in __libc_start_call_main (/lib/libc.so.6+0x25468)
    #10 0xf71ce549 in __libc_start_main@GLIBC_2.0 (/lib/libc.so.6+0x25549)
    #11 0x804ed3b in _start (/home/vagrant/systemd/out/fuzz-bcd+0x804ed3b)

UndefinedBehaviorSanitizer can not provide additional info.
SUMMARY: UndefinedBehaviorSanitizer: SEGV /home/vagrant/systemd/build/../src/boot/efi/bcd.c:185:33 in get_key_value
==104646==ABORTING
```
I'm not sure it should block this PR though

**Comment by medhefgo** [comment]
Apparently, some of sizeof calculation can overflow in 32bit. Will fix it tomorrow.

**Comment by evverx** [comment]
FWIW systemd generally doesn't fare well on 32-bit platforms. Issues like
```
==125298==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf4c00a50 at pc 0x080e414d bp 0xff981568 sp 0xff981140
READ of size 11 at 0xf4c00a50 thread T0
    #0 0x80e414c in __interceptor_memchr.part.0 asan_interceptors.cpp.o
    #1 0xf76b6f1c in validate_nul /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:3309:13
    #2 0xf76a4731 in message_peek_field_string /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:4951:22
    #3 0xf765af5a in bus_message_parse_fields /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:5331:29
    #4 0xf7657c56 in bus_message_from_malloc /home/vagrant/systemd/build/../src/libsystemd/sd-bus/bus-message.c:568:13
    #5 0x81a2ced in LLVMFuzzerTestOneInput /home/vagrant/systemd/build/../src/libsystemd/sd-bus/fuzz-bus-message.c:30:13
    #6 0x808e866 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned int) (/home/vagrant/systemd/out/fuzz-bus-message+0x808e866)
    #7 0x80714be in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned int) (/home/vagrant/systemd/out/fuzz-bus-message+0x80714be)
    #8 0x80776b3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned int)) (/home/vagrant/systemd/out/fuzz-bus-message+0x80776b3)
    #9 0x8065b50 in main (/home/vagrant/systemd/out/fuzz-bus-message+0x8065b50)
    #10 0xf69f3468 in __libc_start_call_main (/lib/libc.so.6+0x25468)
    #11 0xf69f3549 in __libc_start_main@GLIBC_2.0 (/lib/libc.so.6+0x25549)
    #12 0x8065bbb in _start (/home/vagrant/systemd/out/fuzz-bus-message+0x8065bbb)
```
pop up here and there so I'm not sure particular crash should prevent this PR from getting merged. I mean, it would be great if it could be fixed but it wouldn't be the end of the world if it couldn't :-) Thanks again!

**Review by evverx — APPROVED** [review]
I'm not sure if it helps but I can no longer reproduce the crash on 32 bit machines and according to https://github.com/systemd/systemd/runs/4659396385?check_suite_focus=true (where the fuzz target ran for about 10 minutes under ASan, UBSan (with the alignment check) and MSan) it seems to be working on x86_64 as well.

**Pull request merged**
