### PR TITLE
util, import: make sure paths are maximum NAME_MAX long

### PR DESCRIPTION
**Pull request by jsynacek**
https://bugzilla.redhat.com/show_bug.cgi?id=1266775

### CODE REVIEW

**Comment by jsynacek** [comment]
Longer paths are simply trimmed. A cleaner solution would probably be to use hashes.

**Comment by zonque** [comment]
Well, but simply trimming such over-long file names seems dangerous. What about name clashes then? I really think the utility functions should up-chain the error in such cases and let the caller deal with it.

**Comment by zonque** [comment]
IOW: importd needs to learn a better way of naming its download files.

**Comment by jsynacek** [comment]
If you really want no possibility (almost) of name clashes, using filename hashes instead of filenames would be the way to go.

Update: I mean, use some user-friendly part of the filename and append `-<hash>` or something like that. And make sure it's shorter than NAME_MAX.

**Comment by zonque** [comment]
> If you really want no possibility (almost) of name clashes, using filename hashes instead of filenames would be the way to go.
> 
> Update: I mean, use some user-friendly part of the filename and append -<hash> or something like that. And make sure it's shorter than NAME_MAX.

Yes, but that would be a change in importd only, I even think that change can be made unconditionally, because the download file names are an internal implementation detail. @poettering?

In any case, the utility functions should not work around such conditions.

**Comment by poettering** [comment]
Nah, just cutting this off doesn't sound like a good idea, it would just hide the issue and possibly cause issues later on, since two slightly different urls might end up too easily in the same filename on disk. Instead, I'd prefer to have a logic of: try to use the full URL in the name, if it fails with ENAMETOOLONG, hash the url with SipHash (which is cryptographically secure, and which we already have in place), and use that instead. That way, things stay nicely readable in most cases, and in the cases where we hit the limit things still work, and the names are pretty much always unique.

**Comment by jsynacek** [comment]
@poettering I don't think this will work if only open() is checked. There are multiple places where pull_make_path() is used and it doesn't seem that the rest would work without any changes. pull_make_path() is, IMHO, the right place to check for overly long paths.

**Comment by zonque** [comment]
Either way, this PR should be closed and be superseded by new one addressing the issue in importd only.

**Comment by jsynacek** [comment]
Ok, I'll submit a new PR.

**Pull request closed without merging**
