### PR TITLE
resolve: skip IP_UNICAST_IF for local sockets

### PR DESCRIPTION
**Pull request by rpigott**
~~This tests a theory for #31528. I want CI to run the test.~~

---

SO_BINDTODEVICE was used during connect() to fix an issue where IP_UNICAST_IF was improperly ignored for route lookups made by connect in linux. This has since been resolved upstream, but as a result we must apply the local socket excpetion to IP_UNICAST_IF as well.
    
The SO_BINDTODEVICE is no longer necessary, but left in place for 5.x kernels.

Fixes: #31528 #10487 (duplicate)

### CODE REVIEW

**Comment by bluca** [comment]
triggered the noble-amd64 job where it fails - it's not yet enabled by default

**Comment by mbiebl** [comment]
@rpigott at least for my local build, networkd-test.py passes now on Debian sid \o/.
Let's see what ubuntu-ci has to say.

**Comment by bluca** [comment]
ubuntu noble blesses this as well, so sounds like you are heading in the right direction

**Comment by bluca** [comment]
One question: you mentioned the issue worked around with the bind was fixed in a kernel, which version was that?

**Comment by bluca** [comment]
jammy is fixed too, nice

**Comment by rpigott** [comment]
> One question: you mentioned the issue worked around with the bind was fixed in a kernel, which version was that?

Fixed upstream in torvalds/linux@0e4d354762ce + torvalds/linux@526682b458b1, the latter first appeared in v6.2.

The ipv6 fix was backported to v6.1.2 in torvalds/linux@526682b458b1

...and both to v6.0.16 in torvalds/linux@45304d0db4b5 + torvalds/linux@b9c6c96523f9 respectively.

There doesn't appear to be any v5.x release with the ipv6 fix.

**Comment by rpigott** [comment]
Possibly related: #30577

**Comment by rpigott** [comment]
Just curious what kernel versions is systemd expected to support?

**Comment by mbiebl** [comment]
> Just curious what kernel versions is systemd expected to support?

See https://github.com/systemd/systemd/blob/main/README

If certain networkd functionality requires a newer kernel, we can just list it there.

**Comment by mbiebl** [comment]
@poettering what's your take on this?

**Comment by mbiebl** [comment]
btw, @rpigott , I very much appreciate that you spent the time and effort to diagnose this issue.
Thanks a lot!

**Comment by poettering** [comment]
looks good!

**Pull request merged**
