### PR TITLE
stub: add comment on measurement of io.systemd.stub.kernel-cmdline-extra

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by bluca** [comment]
@poettering I think we want this, no? It was simply forgotten?

**Comment by DaanDeMeyer** [comment]
The idea was that SMBIOS is already measured into some PCR, so there was no point in measuring it again here.

**Comment by bluca** [comment]
> The idea was that SMBIOS is already measured into some PCR, so there was no point in measuring it again here.

Ah, do you have a reference? So I can add a comment

**Comment by DaanDeMeyer** [comment]
https://github.com/systemd/systemd/pull/26258#issuecomment-1410580256

**Pull request merged**
