### PR TITLE
sd-bus: simplify sd_bus_reply()

### PR DESCRIPTION
**Pull request by poettering**
there's no point in having two arguments, if one does as well.

### CODE REVIEW

**Comment by poettering** [comment]
maybe we should fine a better name for the call, i see no reason to make it useful for replies only.

**Comment by DaanDeMeyer** [comment]
Yeah I was wondering about this myself. I decided against making a PR because having two parameters makes it consistent with all the other reply functions that also take the original call message as an argument but as you say, it can perfectly do without it.

I chose sd_bus_reply because when writing all the docs for sd-bus, I was expecting sd_bus_call to have a counterpart for replying which didn't exist which really tripped me up. But if we're removing the consistency with the other reply functions, maybe we should rename at the same time as well. `sd_bus_transfer()` ?

**Comment by keszybz** [comment]
The man page also needs to be updated, setting label

Maybe call this `sd_bus_message_send()` ?

**Comment by poettering** [comment]
force pushed a new version. ptal

**Comment by keszybz** [comment]
Looks great.

**Comment by DaanDeMeyer** [comment]
Maybe `sd_bus_send_message`? AFAIK, all the other stuff in sd-bus puts the verb first as well (`call_method, `reply_method`, `emit_signal`, ...)

**Comment by poettering** [comment]
hmm, well, i mean, its a method of the `sd_bus_message` object this way, and we often name things following the scheme `<object type> + <verb> [+ <other object type>]`, hence here `object type = sd_bus_message` and `verb = send` → hence `sd_bus_message_send()` – the object type is always the type of the first parameter.

sd_bus_call_method() and sd_bus_emit_signal() should be read as `object type = sd_bus` (as the first arg is sd_bus*), and then `verb = call` + `other object type = method` resp. `verb = emit` + `other object type = signal`. 

if you follow what i babble here?

we try to follow superficial OOP techniques basically, even though this C. And we don't always follow it, but often.

**Review by DaanDeMeyer — APPROVED** [review]

**Pull request merged**
