### PR TITLE
core: do not filter out systemd.unit= from kernel command line

### PR DESCRIPTION
**Pull request by yuwata**
Fixes a bug introduced by 846f1da465beda990c1c01346311393f485df467.

The commit 846f1da465beda990c1c01346311393f485df467 made systemd.unit=
filtered out from the command line. That causes debug-generator does not
work as expected on daemon-reexecute, and we cannot call `systemctl
daemon-reexecute` in our test suite running on nspawn.

Fixes issue reported in https://github.com/systemd/systemd/pull/23851#issuecomment-1170992052.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @mrc0mmand and @keszybz

**Comment by mrc0mmand** [comment]
Nice, thanks!

Could you throw a `systemctl daemon-reexec` into `TEST-03-JOBS` (since it runs only in nspawn and runs for a while, which has a high chance of hitting this issue)?

```diff
diff --git a/test/units/testsuite-03.sh b/test/units/testsuite-03.sh
index 070e978cda..67a88ec2a3 100755
--- a/test/units/testsuite-03.sh
+++ b/test/units/testsuite-03.sh
@@ -3,6 +3,9 @@
 set -eux
 set -o pipefail
 
+# See: https://github.com/systemd/systemd/pull/23883
+systemctl daemon-reexec
+
 # Test merging of a --job-mode=ignore-dependencies job into a previously
 # installed job.
 
```

should probably do the trick.

**Review by mrc0mmand — APPROVED** [review]
LGTM, thanks!

**Comment by keszybz** [comment]
Is this safe enough to backport to v251 and earlier?

**Comment by yuwata** [comment]
> Is this safe enough to backport to v251 and earlier?

Yeah, I think so.

**Pull request merged**
