### PR TITLE
network: remove unnecessary bridge vlan IDs

### LINKED ISSUE #15291: Add support to remove DefaultPVID in network-files
**Is your feature request related to a problem? Please describe.**
When realizing a VM-Host, which would have a bridge shared with the VMs and a physical interface, but the VM-Host should not be reachable on this bridge for security reasons, systemd-networkd can only add new VIDs to a bridge, never remove the DefaultPVID. The problem occurs when trying to use systemd-networkd to achieve https://vincent.bernat.ch/en/blog/2017-linux-bridge-isolation

**Describe the solution you'd like**
BridgeVLAN-Blocks in network-files should include an option to remove VIDs from the port. That would allow to create a bridge with `DefaultPVID=1` and removing the VID 1 only from this bridge-port, just like `bridge vlan del vid 1 dev br0 self` would do.

**Describe alternatives you've considered**
You could set `DefaultPVID=none` and configure all networks which should be part of the bridge manually. This however is errorprone and at least does not work properly for tun-devices created by libvirt (vnet*).

### LINKED ISSUE #29975: systemd-networkd: changing the vlan in configuration file does not remove the vlan from the old configuration
### systemd version the issue has been seen with

254.5-1-arch

### Used distribution

Arch Linux

### Linux kernel version used

6.1.60-1-lts

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

The interface enp0s31f6 should have changed vlan from VLAN 10 to VLAN 20.

### Unexpected behaviour you saw

The interface enp0s31f6 remained in the VLAN 10 and also got added to VLAN 20.

### Steps to reproduce the problem

1. create a bridge interface with VLANFiltering enabled
    1-brvlan.netdev:
    ```
    [NetDev]
    Name=brvlan
    Kind=bridge

    [Bridge]
    VLANFiltering=1
    DefaultPVID=none
    ```
    3-brvlan.network:
    ```
    [Match]
    Name=brvlan

    [Network]
    ConfigureWithoutCarrier=yes
    ```
2. Add interface enp0s31f6 to bridge brvlan and assign it to VLAN 10
    3-enp0s31f6.network
    ```
    [Match]
    Name=enp0s31f6

    [Network]
    Bridge=brvlan

    [BridgeVLAN]
    VLAN=10
    ```
3. Call `networkctl reload` or `systemctl restart systemd-networkd` to apply the configuration
4. Ensure the configuration has been applied using the `bridge vlan show` command with the following output:
    ```
    port              vlan-id
    enp0s31f6         10
    ```
5. Modify the file `3-enp0s31f6.network` to the following configuration:
    ```
    [Match]
    Name=enp0s31f6

    [Network]
    Bridge=brvlan

    [BridgeVLAN]
    VLAN=20
    ```
6. Call `networkctl reload` or `systemctl restart systemd-networkd` to apply the configuration
7. Ensure the configuration has been applied using the `bridge vlan show` command with the following output:
    ```
    port              vlan-id
    enp0s31f6         10
                      20
    ```

The same issue happens if I use the untagged VLAN configuration, for example (starting from step 2.):

2. Add interface enp0s31f6 to bridge brvlan and assign it to VLAN 10
    3-enp0s31f6.network
    ```
    [Match]
    Name=enp0s31f6

    [Network]
    Bridge=brvlan

    [BridgeVLAN]
    PVID=10
    EgressUntagged=10
    ```
3. Call `networkctl reload` or `systemctl restart systemd-networkd` to apply the configuration
4. Ensure the configuration has been applied using the `bridge vlan show` command with the following output:
    ```
    port              vlan-id
    enp0s31f6         10 PVID Egress Untagged
    ```
5. Modify the file `3-enp0s31f6.network` to the following configuration:
    ```
    [Match]
    Name=enp0s31f6

    [Network]
    Bridge=brvlan

    [BridgeVLAN]
    PVID=20
    EgressUntagged=20
    ```
6. Call `networkctl reload` or `systemctl restart systemd-networkd` to apply the configuration
7. Ensure the configuration has been applied using the `bridge vlan show` command with the following output:
    ```
    port              vlan-id
    enp0s31f6         10 Egress Untagged
                      20 PVID Egress Untagged
    ```

In both of these described examples I'm expecting to see that the interface enp0s31f6 has changed the VLAN from VLAN 10 to VLAN 20, instead of being assigned to both VLAN 10 and VLAN 20. It seems to me that the new configuration is applied, but the old one isn't cleared. Since the configuration file is not deleted (i.e. the interface is still being managed by systemd-networkd) I would expect the new configuration to be applied and the old one to be cleared.

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #29975.
Closes #15291.

### CODE REVIEW

**Comment by yuwata** [comment]
> Is this targeted at v255?

No, feel free to postpone. But it is tested, and should be fine in v255.

**Review by bluca — APPROVED** [review]

**Comment by LiveFreeAndRoam** [comment]
This fix broke us. We manually create vlan's using the `bridge` command.  Once networkd starts it deletes all the dynamically created VLANs.  We have about 34 VLANs to create per 4-port switch, so this was done in a script that runs before systemd-networkd.  E.g. the script executs lots of these type of commands:

```
bridge vlan add dev swp0 vid 1200
```

When systemd-networkd starts, it deletes our manually created VLANs.

We can workaround this, presumably by creating our VLANs after systemd-networkd starts (there may be some hidden risks in rearranging the startup order) or move our manual config into network files (that's a *lot* of network files that need to be created - do network files support any type of templating?).

Or is this is a bug in systemd-networkd that can be rectified?

**Comment by yuwata** [comment]
@LiveFreeAndRoam Yeah, our basic assumption not only here is, interfaces managed by systemd-networkd should not be managed by other ways (daemon, tools, scripts,,,). E.g. if an address is set to an interface, systemd-networkd will remove it on start or reconfigure.

To avoid such, we have several settings, e.g. `KeepConfiguration=`, `ManageForeignRoutes=no`, or so.
I am not sure we should extend `KeepConfiguration=` or introduce another option, say `[BridgeVLAN] Keep=BOOL`.

**Comment by yuwata** [comment]
Hm, I noticed that with this, if nothing is requested in .network file, then the assigned VLAN settings are not changed.
So, I guess you also configure some bridge vlan in a .network file? Could you provide .network files you use?

**Comment by LiveFreeAndRoam** [comment]
I wonder if this new behaviour ought to be put in some sort of "opt-in" variable?

> So, I guess you also configure some bridge vlan in a .network file

Yes.  We create a couple of static VLANs and then a bunch of dynamic VLANs.  This is our `/usr/lib/systemd/network/10-swp0.network` file:

```
[Match]
Name=swp0
KernelCommandLine=!nfsroot

[Network]
BindCarrier=eno2
Bridge=br0
# By default, systemd only tracks neighbors that are bridges, but
# the swp0 neighbor is the PDHC (which is a "station" in LLDP terms)
# Tell systemd to accept and use data from any type.
LLDP=true

[Link]
Multicast=no

[BridgeVLAN]
# NOTE: VLAN 100 is vlocal, only between RMP and PDHC on this chassis
# NOTE: VLAN 105 is vRMP, do not include SWP0 port to the PDHC
VLAN=100
VLAN=110
```

**Comment by LiveFreeAndRoam** [comment]
> @LiveFreeAndRoam Yeah, our basic assumption not only here is, interfaces managed by systemd-networkd should not be managed by other ways (daemon, tools, scripts,,,)

Yes, when I finally uncovered the cause of the failure, I had the same thought.  I'm not opposed to treating it as a bug in our code.  Though, this change in behavior has the potential to catch anybody out that issues a casual `bridge` command and sometime later restarts `systemd-networkd`.

**Comment by LiveFreeAndRoam** [comment]
> I am not sure we should extend KeepConfiguration= or introduce another option, say [BridgeVLAN] Keep=BOOL.

Yes, I feel similarly. It is a breaking change, so I guess it depends on the stance of the systemd community.

Whatever is decided, documenting it so it can be found in a google search will help.

**Comment by LiveFreeAndRoam** [comment]
BTW, it seems to be silently deleting the VLANs. My initial attempt to narrow this down was to run `journalctl -u systemd-networkd` and I saw no indication of it deleting VLANs.  Had there been some messages, I would have possibly got to the root cause more quickly.

**Comment by yuwata** [comment]
> Yes. We create a couple of static VLANs and then a bunch of dynamic VLANs. This is our `/usr/lib/systemd/network/10-swp0.network` file:

Hmm, I do not think we should (at least officially) support such mixture of config source, .network file and your custom script. That's easily conflict each other.

> Whatever is decided, documenting it so it can be found in a google search will help.

> BTW, it seems to be silently deleting the VLANs. My initial attempt to narrow this down was to run `journalctl -u systemd-networkd` and I saw no indication of it deleting VLANs. Had there been some messages, I would have possibly got to the root cause more quickly.

OK. I will add several debugging logs, and mention the change in NEWS. I guess this change is not backpoted to stable branch. So documenting the potential backward compatibility breakage in NEWS should be enough. Thanks.

**Comment by LiveFreeAndRoam** [comment]
> I do not think we should (at least officially) support such mixture of config source, .network file and your custom script.

I agree with your stance on this too. We've been getting away with it for a few years, and v256 will be our day of reckoning :wink:

Thanks @yuwata.

**Pull request merged**
