### PR TITLE
Fix rotation for Nuvision Solo 10 Draw

### PR DESCRIPTION
**Pull request by ShapeShifter499**
Model number TM101W610L

This fixes issue #11683

Also add proper label for other Nuvision tablet.

### CODE REVIEW

**Comment by yuwata** [comment]
Hmm, maybe CI failures are propagated from #11685... cc @evverx.

**Comment by ShapeShifter499** [comment]
@yuwata Why did this one fail part of the checks but a similar type of change someone else made succeeded? #11688

**Comment by evverx** [comment]
As far as I know Ubuntu CI is having trouble reporting its status. @xnox is [aware of that](https://github.com/systemd/systemd/pull/11591#issuecomment-462057164) so I hope it will be fixed soon.

**Comment by ShapeShifter499** [comment]
@evverx @yuwata any reason why my changes couldn't be accepted right now?

**Comment by evverx** [comment]
@ShapeShifter499 I was just minding my own business in https://github.com/systemd/systemd/pull/11685 :-) and got here just to answer @yuwata's question. I think the PR will get merged once someone takes a closer look at it.

**Comment by ShapeShifter499** [comment]
I've been reading the other issues posted here and it seems like the failures in building tests are false positives.

@poettering I noticed you approved the other hwdb change that was submitted after mine. Is there something odd about my edit preventing it from being accepted?

**Comment by yuwata** [comment]
> @poettering I noticed you approved the other hwdb change that was submitted after mine. Is there something odd about my edit preventing it from being accepted?

Please wait for a while :-) Just this is not reviewed yet.

**Comment by ShapeShifter499** [comment]
Alright

**Comment by ShapeShifter499** [comment]
Thank you for merging.

**Pull request merged**
