### PR TITLE
bootchart: fix per-cpu & small scales.

### PR DESCRIPTION
**Pull request by xnox**
Closes systemd/systemd#330

### CODE REVIEW

**Comment by xnox** [comment]
also related to #211

**Comment by zonque** [comment]
Seen the Semaphore CI build error?

```
../src/bootchart/svg.c: In function ‘svg_header’:
../src/bootchart/svg.c:93:53: error: ‘cpus’ undeclared (first use in this function)
             + psize + ksize + esize + (arg_percpu ? cpus * 15 * arg_scale_y : 0.0);
                                                     ^
```

**Comment by xnox** [comment]
@zonque took v219 patch instead of v221 patch...

**Comment by gmacario** [comment]
Hello @xnox,

Thanks for your patch!

I would not apply the change

```
         for (d = graph_start; d <= finalsample;
-             d += (arg_scale_x < 2.0 ? 60.0 : arg_scale_x < 10.0 ? 1.0 : 0.1)) {
+             d += (arg_scale_x < 2.0 ? 60.0 : arg_scale_x < 10.0 ? 1.0 : 0.01)) {
```

to adjust the correction factor to `0.01`, otherwise when running

```
./systemd-bootchart --rel --freq=50 --samples=500 --scale-x=100 --scale-y=20 --no-filter --cmdline --per-cpu
```

the labels displaying time units in the resulting .svg are overlapped and unreadable.
Tested on Chrome (Version 43.0.2357.130 m) running on MS Windows.

The other changes are OK and indeed fix https://github.com/systemd/systemd/issues/330

**Comment by xnox** [comment]
@gmacario  ok, let me drop that hunk for now.

**Comment by zonque** [comment]
Applied, thanks!

**Pull request merged**
