### PR TITLE
fuzz-ndisc-rs: also test packets with sd-radv

### PR DESCRIPTION
**Pull request by yuwata**
Addresses https://github.com/systemd/systemd/pull/32267#discussion_r1566715787.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx

**Comment by evverx** [comment]
As far as I can see `radv_process_packet` calls `radv_send_router` (which calls `sendmsg` under the hood) and `sendmsg` should be overridden somewhere to prevent it from actually sending anything and I can't seem to find that part. Let me double-check.

**Comment by evverx** [comment]
Got it. `test_fd` is in `icmp6-util-unix.c` and `sendmsg` sends advertisements to `test_fd[1]` so it seems it should work.

**Comment by yuwata** [comment]
> Got it. `test_fd` is in `icmp6-util-unix.c` and `sendmsg` sends advertisements to `test_fd[1]` so it seems it should work.

Right.

**Pull request merged**
