### PR TITLE
units: move resolved to sysinit.target (from basic.target)

### PR DESCRIPTION
**Pull request by poettering**
79a67f3ca4d32c37b5e754501852a85eae908a6a pulled systemd-resolved.service
in from basic.target instead of multi-user.target, i.e. the idea is to
make it an early boot service, instead of a regular service.

However, early boot services are supposed to be in sysinit.target, not
basic.target (the latter is just one that combines the early boot
services in sysinit.target, the sockets in sockets.targt, the mounts in
local-fs.target and so on into one big target).

Also, the comit actually didn't add a synchronization point, i.e. not
Before=, so that the whole thing was racy.

let's fix that.

FOllow-up for 79a67f3ca4d32c37b5e754501852a85eae908a6a

### CODE REVIEW

**Comment by poettering** [comment]
@yuwata we should probably do something similar and make networkd an official early-boot service the same way, too.

**Comment by yuwata** [comment]
networkd has `After=network-pre.target`, and firewalld.service has
```
Before=network-pre.target
Wants=network-pre.target
After=dbus.service
After=polkit.service
```
and does not have `DefaultDependency=no`, that implies `After=sysinit.target basic.target`.
polkit.service neither has `DefaultDependency=no`.

Also, nftables.service has
```
Wants=network-pre.target
Before=network-pre.target
```
and does not have `DefaultDependency=no`.

Hence, right now we cannot set `Before=sysinit.target` to networkd. We need to fix these service units at first.

In stead of sysinit.target, how about the following?
```diff
diff --git a/units/systemd-networkd.service.in b/units/systemd-networkd.service.in
index 95dd2665b2..2366ea37c9 100644
--- a/units/systemd-networkd.service.in
+++ b/units/systemd-networkd.service.in
@@ -14,7 +14,7 @@ ConditionCapability=CAP_NET_ADMIN
 DefaultDependencies=no
 # systemd-udevd.service can be dropped once tuntap is moved to netlink
 After=systemd-networkd.socket systemd-udevd.service network-pre.target systemd-sysusers.service systemd-sysctl.service
-Before=network.target multi-user.target shutdown.target
+Before=network.target shutdown.target
 Conflicts=shutdown.target
 Wants=systemd-networkd.socket network.target
 
@@ -52,7 +52,7 @@ User=systemd-network
 {{SERVICE_WATCHDOG}}
 
 [Install]
-WantedBy=multi-user.target
+WantedBy=network.target
 Also=systemd-networkd.socket
 Alias=dbus-org.freedesktop.network1.service
 
```

**Comment by poettering** [comment]
Ah, hmpf, that firewalld thing is a mess indeed... So I guess it's not that easy with networkd unfortunately... :-(

(I mean, not a fan of firewalld myself, but they probably should move it to early boot too if they want it to be useful)

**Comment by poettering** [comment]
> In stead of sysinit.target, how about the following?

That change would mean that unless someone else pulls in network.target systemd-networkd.service would not be started anymore though. 

i.e. network.target is currently defined as "passive" unit, i.e. it's pulled in by the implementor (i.e. by systemd-networkd.service), and not the consumer of the serve (i.e. not by ngnx.service or so). Changing that is hard... And I am not sure why we would...

**Comment by poettering** [comment]
@keszybz does this look good to you?

**Comment by keszybz** [comment]
The addition of Before= is a clear bug fix. I don't know why I didn't add it — I guess I forgot that DefaultDependencies=no is set.

> And, resolved has `After=systemd-networkd.service`. So, I do not think this does not work as expected.

Oops, do we still need this? I would hope that resolved would be able to react to dynamic state changes of networkd. While this is in place, the new Before would create an ordering loop.

> However, early boot services are supposed to be in sysinit.target, not
> basic.target (the latter is just one that combines the early boot
> services in sysinit.target, the sockets in sockets.targt, the mounts in
> local-fs.target and so on into one big target).

Hmm, but wouldn't it be better to redefine `basic.target` to include "normal" services that run after the system is up. I.e. I'd prefer to have systemd-resolved after updates and modules and sysctls and binftms and other paraphernalia have been done.

I.e. have After=sysinit.target, Before=basic.target, WantedBy=basic.target.

**Comment by poettering** [comment]
> Oops, do we still need this? I would hope that resolved would be able to react to dynamic state changes of networkd. While this is in place, the new Before would create an ordering loop.

i would agree → #22602

**Comment by poettering** [comment]
I added one more patch, that is closely related to all this. ptal.

**Comment by keszybz** [comment]
LGTM. But #22602 needs to go in first.

**Review by yuwata — APPROVED** [review]
LGTM too.

**Comment by keszybz** [comment]
Arrgh, it needs a fixup now.

**Review by bluca — APPROVED** [review]

**Pull request merged**
