### PR TITLE
test: use synthesize_nobody() in test-execute

### LINKED ISSUE #8276: `test-execute` seems to fail when the uid of nobody is not 65534 and the uid of nfsnobody is 65534
After merging https://github.com/systemd/systemd/pull/8235 I thought that `nobody` would stop annoying everybody, but I seem to have overlooked a scenario where the uid of `nfsnobody` is 65534:
```sh
$ id nobody
uid=99(nobody) gid=99(nobody) groups=99(nobody)

$ id 65534
uid=65534(nfsnobody) gid=65534(nfsnobody) groups=65534(nfsnobody)

$ sudo ./build/test-execute
...
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=18 reply_cookie=0 signature=s error-name=n/a error-message=n/a
+ test nfsnobody = nobody
Got message type=method_return sender=org.freedesktop.DBus destination=:1.24 path=n/a interface=n/a member=n/a cookie=19 reply_cookie=18 signature=u error-name=n/a error-message=n/a
Got cgroup empty notification for: /user.slice/user-1000.slice/session-3.scope/28c956931acec8a8/exec-environmentfile.service
Received SIGCHLD from PID 2739 (sh).
Child 2739 (sh) died (code=exited, status=1/FAILURE)
exec-group.service: Child 2739 belongs to exec-group.service.
exec-group.service: Main process exited, code=exited, status=1/FAILURE
exec-group.service: Failed with result 'exit-code'.
exec-group.service: Changed start -> failed
exec-group.service: Unit entered failed state.
	PID: 2739
	Start Timestamp: Mon 2018-02-26 09:02:21 UTC
	Exit Timestamp: Mon 2018-02-26 09:02:21 UTC
	Exit Code: exited
	Exit Status: 1
Assertion 'service->main_exec_status.status == status_expected' failed at ../src/test/test-execute.c:74, function check(). Aborting.
Aborted
```
I've got around this by creating `/etc/systemd/dont-synthesize-nobody`, but the proper fix would probably be to add `synthesize_nobody()` to `test-execute`.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #8276.

### CODE REVIEW

**Comment by evverx** [comment]
The test seems to still be failing:
```sh
$ sudo ./build/test-execute
...
exec-group.service: Executing: /bin/sh -x -c 'test "$(id -n -g)" = "nobody"'
++ id -n -g
Got message type=method_return sender=org.freedesktop.DBus destination=:1.52 path=n/a interface=n/a member=n/a cookie=18 reply_cookie=17 signature=u error-name=n/a error-message=n/a
Got cgroup empty notification for: /user.slice/user-1000.slice/session-3.scope/151b5ad32e8cb27f/exec-environment-empty.service
exec-group.service: User lookup succeeded: uid=4294967295 gid=65534
Got message type=signal sender=:1.0 destination=n/a path=/org/freedesktop/systemd1/agent interface=org.freedesktop.systemd1.Agent member=Released cookie=670 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=18 reply_cookie=0 signature=s error-name=n/a error-message=n/a
+ test nfsnobody = nobody
Got message type=method_return sender=org.freedesktop.DBus destination=:1.52 path=n/a interface=n/a member=n/a cookie=19 reply_cookie=18 signature=u error-name=n/a error-message=n/a
Got cgroup empty notification for: /user.slice/user-1000.slice/session-3.scope/151b5ad32e8cb27f/exec-environmentfile.service
Received SIGCHLD from PID 12106 (sh).
Child 12106 (sh) died (code=exited, status=1/FAILURE)
exec-group.service: Child 12106 belongs to exec-group.service.
exec-group.service: Main process exited, code=exited, status=1/FAILURE
exec-group.service: Failed with result 'exit-code'.
exec-group.service: Changed start -> failed
exec-group.service: Unit entered failed state.
	PID: 12106
	Start Timestamp: Wed 2018-02-28 08:33:58 UTC
	Exit Timestamp: Wed 2018-02-28 08:33:58 UTC
	Exit Code: exited
	Exit Status: 1
Assertion 'service->main_exec_status.status == status_expected' failed at ../src/test/test-execute.c:74, function check(). Aborting.
Aborted
```
I think this is because `id` used in `exec-group.service` has never had a chance to call `get_user_creds` provided by `systemd` being tested. I'm not sure what to do about it. The first thing that I thought of was to fake `/etc/passwd` and `/etc/nsswitch.conf` when the test is run. This seems too complex to me, though, so maybe it would be better to skip the test altogether or to check that `id -n` is `65534`.

**Comment by yuwata** [comment]
Hmm, I may misunderstand the bug. But I think the commit itself is good. I will try to add more to really fix the bug. Thank you for testing this.

**Comment by yuwata** [comment]
Updated. Now, checking not only nobody is synthesized or not, but also /etc/passwd and /etc/group have entries conflict to nobody user/group. It may be too strict, and can be relaxed. But, this is just a test. I do not want to see any errors caused by wrong setup of system.

**Comment by yuwata** [comment]
Updated.

**Comment by yuwata** [comment]
Updated. Changes are
- fix wrong condition which causes CI failure.
- add a test for the case that NOBODY_GROUP_NAME is nogroup.

**Comment by evverx** [comment]
@yuwata, thank you. I need a CentOS machine to check whether it works. The last one I had faded into oblivion when I was frustrated about a bug I mentioned in https://github.com/systemd/systemd/issues/8286 :-) I'll get back as soon as I've created a new one.

I was also thinking about using `daemon` instead of `nobody`, which should simplify `test-execute`. Does anybody know why we started to use `nobody` in the first place?

**Comment by evverx** [comment]
The test has stopped failing, but I'm a bit worried that the code deciding what to run is more complex than the code being tested. Would it be simpler to use `daemon`? According to http://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/usernames.html `daemon` is a required user, so in theory it should be almost everywhere :-)

**Comment by yuwata** [comment]
Ok, I will add tests in daemon. Thank you for testing this.

**Comment by yuwata** [comment]
@evverx I've added tests which use user/group daemon. Please take a look.

**Comment by evverx** [comment]
@yuwata, thank you. I'm wondering if `nobody` could be removed altogether now that `daemon` is used.

**Comment by keszybz** [comment]
Yeah, I think those tests with nobody/nfsnobody are more trouble than they are worth. I'd be for dropping them altogether and just testing using `daemon`.

**Comment by yuwata** [comment]
I thought that I implemented the check function strictly more than necessary. So, I do not think we should drop them until they will cause any false alerts.

Or in other words, of course I can drop them, but is it necessary? Now CIs pass, and I believe that the test cases by @evverx also pass.

**Comment by keszybz** [comment]
OK, works for me.

**Comment by keszybz** [comment]
```
Ubuntu 17.10 autopkgtest ttyS0

autopkgtest login: 
---------------------------------------------------
<VirtSubproc>: failure: Timed out on waiting for ssh connection
autopkgtest [10:35:39]: ERROR: testbed failure: cannot send to testbed: [Errno 32] Broken pipe
```

**Pull request merged**
