### PR TITLE
[WIP] Sandbox: seccomp: add more basic syscall groups

### PR DESCRIPTION
**Pull request by tixxdz**
This is a WIP do not merge.

This PR is a follow up this issue: https://github.com/systemd/systemd/issues/6955

Right now in systemd we have two syscall groups for seccomp:
`@default`  for default allowed syscalls.
`@privileged` for privileged syscalls.

We intend at least to add at max 2 or 3 other syscall groups that could fit between these two groups:

- `@basic`: that contain most basic Linux operations that do not have side effects or that can work inside a restricted sandbox without affecting the outside world.

- `@portable` ? : a less restrictive version of `@basic` , to be defined...

In this PR I am trying to add groups that can go into `@basic`. The final aim is users will not have to write complex system call filter profiles , they could just use one group to at least have the minimum functionality. Then combining other systemd abstracted options like: `ReadWritePaths=`, `StateDirectory=`, `CacheDirectory=` , etc, we can allow these syscalls to work inside their sandbox or container context within `RootImage=`.

### CODE REVIEW

**Comment by poettering** [comment]
hmm, so, hmm, can we settle #6958 and #6952 first? I think it makes less controversial changes, that are also included in this PR, that we can get in first

**Comment by tixxdz** [comment]
@poettering of course, I will fix https://github.com/systemd/systemd/pull/6958, and for this one l do not expect it to be merged, but I have to make the PRs now ;-)

**Comment by poettering** [comment]
hmm, in general, after the experience with turning nspawn into a whitelist, i wonder if it wouldn't be better to just do the following:

1. move the nspawn whitelist logic somehow into seccomp-util.[ch], so that we can reuse it for service management in PID 1. This effectively means two things, first of all we'd gain a new group `@container` or so, that encapsulates what nspawn is currently using. Secondly, have some magic in the whole seccomp logic that allows mutating the policies based on capabilities, the way nspawn's seccomp filter currently implements it.

2. the same way we defined a baseline whitelist for nspawn, define one for regular system services. This would actually be very similar, but probably cover more ground. Basically it would allow everything containers can do, plus some more. It would als exclude obsolete stuff, NFS stuff, kexec stuff, `@cpu-emulation` and suchlike highly specialized stuff, but otherwise permit the majority of things. Now, one could argue that having such a comprehensive whitelist is not too useful, but it actually is because of the caps-based automatic mutation mentioned in item 1 above: if you use caps (and many people do these days, as it is a relatively easily graspable concept), the seccomp policy would automatically be adjusted to that, the same way this is already done in nspawn...

3. as syntactic sugar extend SystemCallFilter= so that the "~" prefix cannot only appear at the beginning of the rvalue, but also before each word in it.

Now, on top of this whitelist people could then whitelist or blacklist additional syscalls. I figure however, that for most cases the caps-derived approach should already be pretty powerful and good enough.

Or to say this differently, currently we push people towards one of two schemes:

1. they easiest thing is blacklisting: people allow everything, except a few groups we defined for them. that's how systemd uses seccomp for all its long-running services right now. Blacklisting is great, but of course whitelisting is better

2. we offer whitelisting, but it's tough to use, since you need to construct things from the ground up. Yes `@default` is a start, but a real-world policy still is hard to write, since `@default` is so far away from what actually is needed IRL, and the SystemCallFilter= lines become very very long. This fully additive approach is cumbersome, requires a lot of knowledge and results in verbose policies.

What I am proposing now is to offer a starting point in the middle: neither start from "allow everything" (like in approach 1) nor from "allow basically nothing" (like in approach 2), but from "allow the common", and then permit people to add or remove stuff from that.

**Comment by poettering** [comment]
@tixxdz can you file the sched_yield commit as separate PR too?

**Comment by tixxdz** [comment]
@poettering I will start from your last comment first:
> Or to say this differently, currently we push people towards one of two schemes:

> 1. they easiest thing is blacklisting: people allow everything, except a few groups we defined for them. that's how systemd uses seccomp for all its long-running services right now. Blacklisting is great, but of course whitelisting is better

> 2. we offer whitelisting, but it's tough to use, since you need to construct things from the ground up. Yes @default is a start, but a real-world policy still is hard to write, since @default is so far away from what actually is needed IRL, and the SystemCallFilter= lines become very very long. This fully additive approach is cumbersome, requires a lot of knowledge and results in verbose policies.

> What I am proposing now is to offer a starting point in the middle: neither start from "allow everything" (like in approach 1) nor from "allow basically nothing" (like in approach 2), but from "allow the common", and then permit people to add or remove stuff from that.

This does not differ from what I am proposing, I was referring to `@basic` you can use another alias but the aim is to have something that is basic operations that works inside a sandbox, then you can add `@portable`, `@container` or `@common` what ever that refers to a starting point or something in the middle that can fits between 1) `@default`... 2) `@basic` ... 2) X ... 4) Y ... `@privileged`  I think 4 or 5 groups is already enough as a standard.

Here I started to add those "basic" concepts since most technical people are used to them. However for normal users if they want something strict they should just use `@basic` or again another name whatever... but it can be a lot easier than `@common + black list syscalls ` . Of course we need to come up with real examples later to cope up with reality... I am investigating it.


Now allow me to go back to your first comment:
> Now, on top of this whitelist people could then whitelist or blacklist additional syscalls. I figure however, that for most cases the caps-derived approach should already be pretty powerful and good enough.

The caps-derived approach is cool, however I would not take it from nspawn or take nspawn as a reference for systemd, nspawn is far from being the most used software here.

Embedded linux apps and some smart gateways cases may need an abstracted model. Most developers there do not have the background of traditional developers of services/servers, and we may find javascript, golang apps etc. However if systemd is there then most of the time it is using simple units, run as root, in rare cases it is run as normal user if applicable with some restrictions and that's it.

Mutating seccomp policies based on caps or the caps-derived approach is a good starting point, however as you know caps are far from being perfect, some of them allow lot of stuff, others do only one restricted thing... and we need to figure out the rest that is not covered by capabilities, we need to abstract this, an upper layer for this that can of course use caps and mutate seccomp.

As an example we added this:
* `RestrictAddressFamilies=`  not covered by capabilities, it is powerful but also not abvious for some users or developers. `ACCESS_INTERNET=yes|no` can be simple for inet sockets. `ADMIN_ACCESS_INTERNET=yes|no` will allow the above, + raw packets capability + bind privileged ports capability. Advanced users can tune up capabilities and seccomp to restrict what `ADMIN_ACCESS_INTERNET` can do.

* `ADMIN_SYSTEM_NETWORK_STATE=` for the system network manager which will combine cap_net_admin + /proc/sys/net writes.

* `READ_SYSTEM_NETWORK_STATE` read /proc/net state, black list mount syscalls and block network admin tuning, if set to `no` then mount procfs only with pids /proc/pids/* which will hide all other kernel data, and related network information.

* `ADMIN_SYSTEM_TIME` equivalent for CAP_SYS_TIME
* `ADMIN_SYSTEM_TIME_ZONE ? ` to bind mount host timezone files, some embedded devices have specific services for this matter.

* `ACCESS_SYSTEM_MANAGER` access systemd bus socket.

* `ADMIN_SYSTEM_LOGS` manipulate system logs, luckily we own journald and can control its unit, however there are use cases there that also want to manipulate the system logs. I am referring to all what's needed to manipulate the logs not CAP_SYSLOG.

* `READ_DEVICES` restrict capabilities, no mount syscalls, /dev read-only

* `ADMIN_KILL_PROCESSES` => CAP_KILL  usually can be used with another monitor related to watchdog to restart apps.

* `ADMIN_SYSTEM_SETTING` => mount /etc writable inside and give it the necessary capabilities to write files.

Of course some of this may only make sense in embedded linux, and only if used in RootImage= or any other sandbox context, but the message is: we can use a higher layer and adjust capabilities and seccomp from there, advanced users can just go with the comprehensive `@container` set or caps-based approach. Others may use abstracted options to adjust and restrict the `@container` or `@privileged` sets and *also adjust the resources, files, etc available inside the container/sandbox*, The caps-based approach can be less expressive in this matter, as an example you want the app to be sandboxed but also allow it to talk to systemd manager...

Finally this approach is more for a runtime mode based on whitelisting.

**Comment by tixxdz** [comment]
@poettering regardless of my comments here, should we add the basic groups ?  to recap:

* Have an alias to run commands/programs with seccomp  `@basic` set for something like transient units...
* Then you can also do `@basic + @file-system` for most filesystem operations...
* Later you may add another alias group that translate to `@basic + @file-system + @X` automatically, mutating caps etc. 

Lets first get this basic done, ah some bits of this PR were already merged.

If you agree, I will update the PR later.

Thanks!

**Comment by tixxdz** [comment]
and my use case for this: instead of writing code for some specific cases, I will use `systemcallfilter="@basic @file-system ..."` on most of unix tools, run as transient units and combine systemd timers, jobs and magic.

**Comment by poettering** [comment]
@tixxdz hmm, so not following what you want to add right now next. But my current thinking is that we should add `@system-service` as first step now, that includes everything pretty much any system service will need, and which services can base their stuff off. i.e. most of the stuff that we provide containers with, except for stuff that is specific to some purposes.

When implementing this we should also start using this immediately in all our own long-running services, to see the fallout this produces.

later on we might want to add `@user-service` too, to cover --user instances, but I#d focus on system instances for now.

**Comment by poettering** [comment]
btw, `@system-service` has been added now. @tixxdz what does this mean for this PR? anything you would still suggest we add?

**Comment by poettering** [comment]
OK, let's close this. If there's anything else left to be done, please file new RFE issues.

**Pull request closed without merging**
