### PR TITLE
fstab-generator: make sure explicit deps configured via mount options apply to .mount, not .automount unit

### PR DESCRIPTION
**Pull request by fbuihuu**

### CODE REVIEW

**Comment by fbuihuu** [comment]
This was initially discussed in https://github.com/systemd/systemd-stable/issues/69.

**Comment by fbuihuu** [comment]
Cc @cdown

**Comment by poettering** [comment]
lgtm. but can you update the man page to make this clear that this is what happens?

**Comment by fbuihuu** [comment]
@poettering , done.

**Comment by keszybz** [comment]
LGTM.

**Comment by cdown** [comment]
Sorry, this one slipped my radar. Looks good to me as well, and should hopefully avoid the confusion in https://github.com/systemd/systemd-stable/issues/69 from happening again.

**Pull request merged**
