### PR TITLE
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1224211

### PR DESCRIPTION
**Pull request by keszybz**
Please see bug for discussion.

### CODE REVIEW

**Comment by msekletar** [comment]
Is rework in journald really necessary? I checked what `getpeercon` does [1] and it calls `getsockopt` with `SO_PEERSEC` already.

On top of that, so far we gathered and stored label (in `dispatch_message_real`) only for SELinux enabled systems. `getpeersec` will gather the label regardless LSM used, but we will not use it in `dispatch_message_real` if SELinux support is compiled out or SELinux is not enabled. 

Thus I think that on system where no LSM is used you get a lot of error messages, because there will be no hook in kernel LSM subsystem to handle the `getsockopt` request. In case you are running SMACK or AppArmor `getpeersec` will gather _some_ label but it won't be used anyway.

[1] https://github.com/SELinuxProject/selinux/blob/master/libselinux/src/getpeercon.c

**Comment by keszybz** [comment]
On Sun, Jun 07, 2015 at 01:22:56AM -0700, Michal Sekletar wrote:

> Is rework in journald really necessary? I checked what `getpeercon` does [1] and it calls `getsockopt` with `SO_PEERSEC` already.
> It's not necessary. I think we should convert both parts to be
> similar, but that can happen later though.

But since getpeercon does almost exactly the same thing as getpeersec,
I don't like usin oneg in one part of the code, and the other in the other.
You're right, the call should be made not to warn when selinux is disabled.

> On top of that, so far we gather and stored label (in `dispatch_message_real`) only for SELinux enabled systems. `getpeersec` will gather the label regardless LSM used, but we will not use it in `dispatch_message_real` if SELinux support is compiled out or SELinux is not enabled. 
> 
> Thus I think that on system where no LSM is used you get a lot of error messages, because there will be no hook in kernel LSM subsystem to handle the `getsockopt` request. In case you are running SMACK or AppArmor `getpeersec` will gather _some_ label but it won't be used anyway.

Hm, I'll boot w/o selinux and see what happens.

I made a copr package to make it easier to test: https://copr.fedoraproject.org/coprs/zbyszek/systemd/.

**Comment by poettering** [comment]
BTW, I think our own getpeersec() is not going to be sufficient in the long run, and we probably should introduce some form of higher-level wrapper instead, The thing is that getpeersec() ignores whether things are an selinux label or a smack label or whatever else. We currently assume it's always an selinux label, but that is actually wrong...

(Also, selinux has this weird label translation service, and we don't bother talking to that at all, currently, but getpeercon() does that. Maybe we should do that too -- but i am tempted to say that we better shouldn't, as this is likely to explode brutally due to dep loops: systemd components talking to this selinux service which in turn relies on systemd...). 

In generally, should we decide to adopt getpeercon() then I'd avoid always calling into getpeercon() directly though, since it's fucked up errno handling and the #ifdeffery required around it. Hence, if we want to fix this properly, maybe we should leave getpeersec() the way it is, but then introduce getpeersec_selinux(), getpeersec_smack() or so, that wrap it or getpeercon(), and return -ENOSUP or so if selinux/smack are not enabled. 

I always ignored this issue so far, since I assumed if anybody from the selinux/smack camps really cared, they would do something about it... so far nobody cared...

**Comment by keszybz** [comment]
Merged as b078b5a7abf4ca81d83fc1db7d6fb1047129280f.

(I wonder how github thinks it can merge this automatically even though there's a merge conflict. I'm fixed it up locally, I'm afraid to try the automatic stuff for this...)

**Pull request closed without merging**
