### PR TITLE
Journald preserve acl when rotating

### PR DESCRIPTION
**Pull request by fbuihuu**

### CODE REVIEW

**Comment by poettering** [comment]
hmm, acls are just xattrs, why isn't sufficeint to copy those?

**Comment by poettering** [comment]
for the second patch, adding the COPY_XATTR_ALL flag should suffice, no?

**Comment by fbuihuu** [comment]
> hmm, acls are just xattrs, why isn't sufficeint to copy those?

Well I must admit that I haven't looked at how acls are implemented, but AFAICS they're not part of the xattrs returned by `flistxattr_malloc()`, which are:

```
user.crtime_usec
user.crtime_usec
system.posix_acl_access
```

**Comment by fbuihuu** [comment]
Ah ok then passing `COPY_XATTR_ALL` should be sufficient. Let me give it a test.

**Comment by fbuihuu** [comment]
Passing `COPY_XATTR_ALL` fixed the issue.

I force pushed a new version which does that, PTAL.

**Review by DaanDeMeyer — APPROVED** [review]

**Review by bluca — APPROVED** [review]

**Pull request merged**
