### PR TITLE
Bump mkosi config for F34

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Review by bluca — APPROVED** [review]
lgtm

**Comment by bluca** [comment]
Some tests are failing now in the mkosi fedora build, is that expected?

```
151/439 hwdb-test                                 FAIL           0.01s (exit status 1)
264/439 test-mount-util                           FAIL           0.57s (killed by signal 6 SIGABRT)
279/439 test-os-util                              FAIL           0.22s (killed by signal 6 SIGABRT)
358/439 test-execute                              FAIL           0.32s (killed by signal 6 SIGABRT)
```

**Comment by keszybz** [comment]
> Some tests are failing now in the mkosi fedora build, is that expected?

No, not expected. They didn't fail here…

**Comment by keszybz** [comment]
[1065/1670] Linking target systemd-hwdb
--- command ---
14:28:29 /root/src/test/hwdb-test.sh
--- stdout ---
./systemd-hwdb does not exist, please build first


14:28:39 PATH='/root/build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' SYSTEMD_LANGUAGE_FALLBACK_MAP='/root/src/src/locale/language-fallback-map' SYSTEMD_KBD_MODEL_MAP='/root/src/src/locale/kbd-model-map' /root/build/test-mount-util
Assertion 'bind_remount_one_with_mountinfo("/proc/idontexist", MS_RDONLY, MS_RDONLY, proc_self_mountinfo) == -ENOENT' failed at src/test/test-mount-util.c:149, function test_bind_remount_one(). Aborting.

I don't understand either failure. I also don't see how this is related to the Fedora version.

**Comment by bluca** [comment]
different kernel version, for the mount stuff?

**Comment by keszybz** [comment]
12:13:05 /root/src/test/hwdb-test.sh /root/build/systemd-hwdb
Hmm, no idea what's going on here.

**Comment by keszybz** [comment]
My best guess is that it's some Ubuntu thing. I get lost in all the layers, but the mkosi action compiles rpm from source, and a bunch of other libraries, 'cause Ubuntu. The tests definitely pass on F34, and rawhide, in arbitrary combinations.

**Comment by keszybz** [comment]
Let's try again, now that F34 has been released.

**Comment by poettering** [comment]
lgtm

**Pull request merged**
