### PR TITLE
network: several follow-ups for DHCP server lease file

### PR DESCRIPTION
**Pull request by yuwata**
Follow-ups for #30021.

Prompted by https://github.com/systemd/systemd/pull/30021#discussion_r1518478633

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx

**Comment by evverx** [comment]
Looks like with this patch applied networkd on the host gets stuck in the "degraded (configuring)" state and containers end up with link-local IPv4 addresses only. They keep sending discover messages with no replies:
```
19:35:19.156612 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 36:30:b6:30:94:d7 (oui Unknown), length 287
19:35:23.865778 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 36:30:b6:30:94:d7 (oui Unknown), length 287
19:35:28.010490 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 36:30:b6:30:94:d7 (oui Unknown), length 287
19:35:35.316774 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 36:30:b6:30:94:d7 (oui Unknown), length 287
```
It could be I screwed something up somewhere. Let me double check.

**Comment by yuwata** [comment]
Now this is ready. PTAL.

@evverx `PersistLeases=BOOL` setting will be submitted after this PR merged.

**Comment by evverx** [comment]
FWIW I've been using networkd with this patch applied for a couple of days and it works.

**Pull request merged**
