### PR TITLE
random-util: call initialize_srand() after fork()

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by poettering** [comment]
Patch doesn't look alright. What matters is that each forked off *process* reinitializes the seed, not each *thread*. i.e. calling fork() means the invoking thread gets copied into the new proces sand continues running there, and that means srand() is not called again.

This is one of the few cases where pthread_atfork() is useful: we should use it to reset the boolean srand_called boolean in the child, so that after the fork() the child will definitely call srand() again.

That said, I think we should also switch the MAC code to use genuine randomness (though with RANDOM_ALLOW_RDRAND after all the MAC address is not cryptographic material), but that's another PR I figure.

**Comment by yuwata** [comment]
I see. Thanks. I will rework on this later.

**Comment by yuwata** [comment]
@poettering Updated. I hope I understand your suggestion, but not sure...

**Comment by poettering** [comment]
lgtm. @iangehc can you check if this works?

(as mentioned, still think we should switch over the MAC generation to genuine RNG, but this PR nevertheless looks good)

**Comment by iangehc** [comment]
Tested here.  lgtm.  Thank you!

**Comment by yuwata** [comment]
@iangehc Thank you for testing!

**Pull request merged**
