### PR TITLE
add vconsole.conf comment for localectl

### PR DESCRIPTION
**Pull request by xiacunshun**
https://github.com/systemd/systemd/issues/29717
Although it is stated in manpage, I think it can be more clear if add a comment in it.

### CODE REVIEW

**Comment by poettering** [comment]
hu, i am not sure "Generated" is the right word for this. We read it, and we write it out again, possible with changed settings. So we don't "generate" it, we just change it. HEnce I think this change is misleading.

**Comment by xiacunshun** [comment]
> hu, i am not sure "Generated" is the right word for this. We read it, and we write it out again, possible with changed settings. So we don't "generate" it, we just change it. HEnce I think this change is misleading.

You are right. This file is not generated by localectl, so I guess "rewritten" should be a better choice.

**Comment by yuwata** [comment]
-> #29763.

**Comment by xiacunshun** [comment]
Umm, so this pr is replaced by https://github.com/systemd/systemd/pull/29763, and I did some useless work. :(

**Comment by yuwata** [comment]
> Umm, so this pr is replaced by #29763, and I did some useless work. :(

Your PR reminds us about the issue. That's important contribution. Thanks.
I will add co-author tag with your affiliation in #29763.

**Comment by xiacunshun** [comment]
> > Umm, so this pr is replaced by #29763, and I did some useless work. :(
> 
> Your PR reminds us about the issue. That's important contribution. Thanks. I will add co-author tag with your affiliation in #29763.

It really makes me feel much better~ Thank you!

**Comment by xiacunshun** [comment]
@yuwata Hello, I would like to ask if co-authors will appear in the list of contributors in the release notes. As a beginner, if I could be listed, it would be a great encouragement for me.

**Comment by yuwata** [comment]
-> #30261

**Comment by xiacunshun** [comment]
Thank you so much！I really appreciate it.

**Pull request closed without merging**
