### PR TITLE
man: DynamicUser= does not imply PrivateDevices=

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for effbd6d2eadb61bd236d118afc7901940c4c6b37.

### CODE REVIEW

**Comment by yuwata** [comment]
Or should `DynamicUser=` imply `PrivateDevices=`? If so, I think we need to add
```
ec->private_devices = true;
```
at around https://github.com/systemd/systemd/blob/master/src/core/unit.c#L3581.

**Comment by tixxdz** [comment]
Reading this it seems that DynamicUser= should imply PrivateDevices= , however I have the following observations that may help:

You need to move https://github.com/systemd/systemd/blob/master/src/core/unit.c#L3559 and the other capability remove after `ec->dynamic_user` , however this enforces DynamicUser= to run without CAP_MKNOD capability... which can be restrictive, and this may break current programs since they may expect the capability...

Furthermore, it seems that we will also remove those capabilities even if user did include them explicitly in the bounding set `CapabilityBoundingSet=` ? I did not confirm this and it is a separate issue, so do not fully trust my words but I would say that if unit has `CapabilityBoundingSet=~` then it should not drop those capabilities... If this issue is confirmed and fixed, it will allow you to improve documentation by saying that in DynamicUser=  you can restore capabilities by setting them in `CapabilityBoundingSet=~ or cap`, still in the end this will require the users to explicitly specify capabilities which is not the easy way.

To conclude, I am not sure if this is the best approach, for me it seems that DynamicUser= should not remove caps from the bounding set, with this and how we are planning RootImage= it will be easy to have an easy abstracted model: RootImage + Seccomp + capabilities + DynamicUser , in the other hand if DynamicUser= starts to get into capabilities territory, we will have to work around that... so maybe we should just fix documentation to say that if DynamicUser= is set you should also set PrivateDevices= + your current patch ? sorry not helpful.

**Comment by yuwata** [comment]
Hmm... I do not imagine the situation that units with `PrivateDevices=yes` require `CAP_MKNOD`.

**Comment by poettering** [comment]
i don't see a reason why DynamicUser= should imply PrivateDevices= I must say. The only reason we imply some namespacing settings when DynamicUser= is set is because we need to make sure that the service run that way doesn't write files with its UID to arbitrary places, as the UID remains "sticky" on them surviving beyond the point where it already is released again. However, as /dev isn't a place where unprivileged processes can create stuff I don't think this issue really applies here, hence I see no reason to imply PrviateDevices= from DynamicUser=

**Pull request merged**
