### PR TITLE
core: treat empty /etc/machine-id as first boot

### PR DESCRIPTION
**Pull request by jlebon**
Previously, we only considered the existence of `/etc/machine-id` to
determine whether we were in the first boot. This however is not
compatible with system images which ship with an empty `/etc/machine-id`
(as recommended in `machine-id(5)`) and which initially boot with a
read-only root at switchroot (but which is remounted rw later on,
allowing `systemd-machine-id-commit.service` to run).

Thus, on such systems, `ConditionFirstBoot` units do not fire even
though it's clear from the empty `/etc/machine-id` that it is the first
boot.

This patch changes the logic so that systemd also considers empty
`/etc/machine-id` files as a first boot. This then allows units with
`ConditionFirstBoot=true` to fire.

---

Note that one case where this drastically changes the behaviour is systems in which `/etc` remains read-only and ship with an empty `/etc/machine-id` to be bind-mounted over on every boot (and instead ensure a consistent ID across reboots through e.g. kargs or `--machine-id`). On such systems, units with `ConditionFirstBoot=true` will now fire on *every* boot. Are there such setups out there? I would expect systems with sealed `/etc`s to also already bake in all their configurations, including a machine ID to begin with, though I'm not sure if that's truly the case. Anyway, prior to this patch, `ConditionFirstBoot` units on such systems would not have fired at all (not even on the first boot), so it doesn't seem like they could have made use of it in the first place.

### CODE REVIEW

**Comment by filbranden** [comment]
Fixes #8268.

Not sure if this is desirable... But I'll leave it for others to comment on.

**Comment by jlebon** [comment]
We worked around this in rpm-ostree by adding an option to remove `/etc/machine-id` from the OSTree commit: https://github.com/projectatomic/rpm-ostree/pull/1425. However, this then caused e.g. journal failures on systems which switched root in read-only mode: https://github.com/projectatomic/rpm-ostree/pull/1425#issuecomment-409626076.

**Comment by jlebon** [comment]
> Fixes #8268.

Thanks! Clearly I should've searched a little harder for context around this (though I did stumble upon #7849 which seems to align with the behaviour change here).

**Comment by cgwalters** [comment]
Let's discuss in https://github.com/systemd/systemd/issues/8268

**Comment by poettering** [comment]
l really don't like this, see my comments here:

https://github.com/systemd/systemd/issues/8268#issuecomment-410205766

Please always explain the usecase, i.e. why do you want to ship /etc/machine-id at all in your case, if you ship it empty anyway?

**Comment by jlebon** [comment]
Closing this as per discussions in #8268.

**Pull request closed without merging**
