### PR TITLE
tmpfiles: drop /run/nologin creation during startup

### LINKED ISSUE #8228: We basically block login during boot, and yet we tell people that it is possible for privileged users
I've noticed it is in the repo and included by default in few distros, however I can't figure out case why someone would want to have it.

Current behaviour (from what I can observe) is basically "forbid any non-root login until system started", which in our case was "just dont allow actual system admins to log in for few minutes(till systemd goes from "starting" to "degraded") to fix/debug the problem" (which i our case was some service timing out on network resource), because as every nice admin we don't use `root` account to manage servers but use sudo instead.

I can see the case when you'd want prevent users to log in before system is booted, but without distinction between sysadmins (users managing actual system) and users (users using services on system or deploying apps on it) that just isn't very useful (and afaik pam_nologin doesn't have option to allow particular group of users to log in).

I mean turning it off is easy enough but seems like a mine waiting for someone to step into it

### PR DESCRIPTION
**Pull request by keszybz**
We created /run/nologin during boot to mimic sysvinit. But it turns out that
sysvinit didn't really do that:
> I just checked an old Debian jessie installation with sysvinit. Seems the
> mechanism for creating /run/nologin is there, but it's only activate when
> DELAYLOGIN=yes has been set in /etc/default/rcS. The default is no.

/run/login during boot is problematic because it stops users from logging
in and investigating issues (using sudo or otherwise), and there really
isn't much point in delaying logins like that.

Fixes #8228.

### CODE REVIEW

**Comment by poettering** [comment]
> I just checked an old Debian jessie installation with sysvinit. Seems the
> mechanism for creating /run/nologin is there, but it's only activate when
> DELAYLOGIN=yes has been set in /etc/default/rcS. The default is no.

Uh, but that's debian. I am pretty sure Red Hat did that differently...

**Comment by poettering** [comment]
This appears quite half hearted to me. If we kill it we should kill it for good, i.e. also not create the file during shutdown...

That said, I think it actually does make sense to prohibit regular users to login before everything is set up properly. Otherwise clients might get access to stuff they shouldn't get access too, for example might end up taking up predictable names in /tmp such as the X11 sockets that they really shouldn't be able to, or take possession of well-known abstract namespace sockets, or are able to see stuff in directories before it gets overmounted...

**Comment by poettering** [comment]
I am pretty sure the better approach would be to work with the PAM folks to relax nologin behaviour in pam_nologin for members of the "wheel" group or something like that...

**Comment by keszybz** [comment]
Delaying loggins is a terrible defence mechanism. Stuff that needs that really sucks. But anyway, we *do* take precautions: `/tmp/.X11-unix` is created by tmpfiles early. Similarly for any mounts and such: those all happen early during boot, and realistically the only ways you can log in is through gettys, ssh, or graphical, and all three mechanism become available only after everything has been mounted and created.

I understand your concerns, but I think they are unrealistic, when OTOH, we *do* have issues with /run/nologin being active during boot. Apart from the issues described in #8228, before we had that Fedora bug that /run/nologin was recreated when tmpfiles was run and users were locked out of the machine. While all those are fixable, this is a brittle mechanism.

During shutdown, I think it's good to prevent users from logging in for their own good. I mean, you log in, start working, and then the machine goes down and you lose state.

**Comment by poettering** [comment]
> Delaying loggins is a terrible defence mechanism. Stuff that needs that really sucks. But anyway, we do take precautions: /tmp/.X11-unix is created by tmpfiles early. Similarly for any mounts and such: those all happen early during boot, and realistically the only ways you can log in is through gettys, ssh, or graphical, and all three mechanisms become available only after everything has been mounted and created.

hmm, i thought that at lest ssh is optionally already available in the initrd on specific systems where local access is not provided...

**Comment by poettering** [comment]
so i am really unsure about this one. 

I have to admit I couldn't find the nologin stuff in rc.sysinit either from fedora's old days... But that probably is just because /run/nologin used to be in /etc/nologin and hence was persistent. Which meant that the file created at shutdown on the previous boot was still there on the next boot, until it is removed explicitly in late boot.

also we have systemd-user-session.service whose primary purpose is to schedule when exactly the system is ready for unprivileged logins. Currently stuff can be ordered before that and we guarantee that no user code will run before it marked things to be safe for that. If we drop /run/nologin then we might as well drop that too no?

In general I think it does make some sense to schedule the readiness to login: it's not only a security thing but also pretty annoying for users if they log into a system that is barely usable, i.e. where /home might be missing and such.

One could argue that sshd should be ordered after systemd-user-sessions.service as a replacement for /run/nologin, but that doesn't really work that well, as whether sshd is started or not controls substantially more than just unpriv-user-login, it also controls priv-user-login, which is something /run/nologin can distuingish...

I do sympathize with the sudo issue, i.e. that it's good style to not use the root user too much. But I am pretty sure that allowing wheel users (or so) to bypass /run/nologin really *is* the better approach here, as that would allow finegrained scheduling when which user can log in...

Personally I think my main issue with /run/nologin is actually that I think it's inverted: it should be the other way round — it shuld be a flag file that has to exist for login to be allowed, not the other way round...

**Comment by sourcejedi** [comment]
Uhh, I don't think `root` logins have any way to bypass the ordering on `systemd-user-sessions.service` at the moment?  I think that's only possible with the emergency/rescue/debug shells.

But I think the general point holds, that creating or not creating `nologin` in early boot isn't going to change much on it's own.  My opinion was it's actually preferable if you get an error message, and you can google it, rather than a mysterious hang when you try to log in.  https://github.com/systemd/systemd/issues/8228#issuecomment-367285459

**Comment by XANi** [comment]
@poettering From what I digged into old centos 5 and 6 installs, nothing in system touched `nologin` on boot and only trace in centos 6 was SELinux permissions.So it seems there it was intended as tool for sysadmin to stop new users from logging in when system is under maintenance.

There is also a problem between "user gets bad experience because system has not booted yet" and "there is something broken but sysadmin can't log in to check what it happening and can only guess from logs" (I just had that recently when I fucked up firewall and after reboot it took ages for iscsi to timeout...).
 
Also currently:

* the message on nologin is nonsense. 
* ssh logs something that looks like someone trying something nasty while in reality they just tried to ssh too early (because SSH doesn't say which PAM module refused login, just that it refused),

*Ideally* it would just display the message that the system is booting without kicking user off (which probably would be pretty tricky to actually do) and only kicks user if boot takes long time (mostly as a way to limit some automated script from opening hundreds of sessions that are stuck).

**Comment by poettering** [comment]
> @poettering From what I digged into old centos 5 and 6 installs, nothing in system touched nologin on boot and only trace in centos 6 was SELinux permissions.So it seems there it was intended as tool for sysadmin to stop new users from logging in when system is under maintenance.

As mentioned: The file used to be called /etc/nologin, i.e. was on persistent storage. Hence, the file created during shutdown would still be there during the next reboot and only removed in late boot.

**Comment by poettering** [comment]
> the message on nologin is nonsense.

Well, I'd not call it "nonsense". Maybe we can improve it, but brevity is a quality too and it is googleable, and does contain references to the implementing PAM concept.

I'd be happy to extend the text, please make a proposal!

> ssh logs something that looks like someone trying something nasty while in reality they just tried to ssh too early (because SSH doesn't say which PAM module refused login, just that it refused),

I am pretty sure the PAM/ssh maintainers would be happy to improve their handling in that area.

**Comment by keszybz** [comment]
OK, it seems that just dropping /run/nologin is not the way to go. Most likely pam_nologin should be improved to exclude certain groups. Let's close this.

**Pull request closed without merging**
