### PR TITLE
Errno or else

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM too.

**Comment by keszybz** [comment]
bionic-amd64 test in TEST-25-import with "Failed to transfer image: Connection timed out". I'll restart the test.

**Comment by keszybz** [comment]
CentOS CI (Arch in KVM) fails with
```
FAIL: test_dhcp_client_use_dns_yes (__main__.NetworkdDHCPClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 2733, in test_dhcp_client_use_dns_yes
    self.assertRegex(output, '2600::1')
AssertionError: Regex didn't match: '2600::1' not found in 'Link 80 (veth99): 192.168.5.1'
```
@mrc0mmand ?

The other one fails with `archlinux_systemd_ci: ninja: build stopped: subcommand failed.`, but I don't see anything more.

**Comment by mrc0mmand** [comment]
@keszybz the error in the KVM one is *cleverly* masked by a fact, that the meson's *setup* phase runs twice because of sanitizers, so you have to scroll past that. Anyway, here's the error, which should be fixed by #13025, so I'll re-trigger the CIs for this PR.

```
    archlinux_systemd_ci: FAILED: systemd-tmpfiles@exe/src_tmpfiles_tmpfiles.c.o 
    archlinux_systemd_ci: cc -Isystemd-tmpfiles@exe -I. -I.. -Isrc/basic -I../src/basic -Isrc/boot -I../src/boot -Isrc/shared -I../src/shared -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/udev -I../src/udev -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -Isrc/shutdown -I../src/shutdown -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -Isrc/libsystemd-network -I../src/libsystemd-network -I../ -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=gnu99 -g -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -Werror=shadow -include config.h -g -O0 -ftrapv -MD -MQ 'systemd-tmpfiles@exe/src_tmpfiles_tmpfiles.c.o' -MF 'systemd-tmpfiles@exe/src_tmpfiles_tmpfiles.c.o.d' -o 'systemd-tmpfiles@exe/src_tmpfiles_tmpfiles.c.o' -c ../src/tmpfiles/tmpfiles.c
    archlinux_systemd_ci: ../src/tmpfiles/tmpfiles.c: In function ‘parse_line’:
    archlinux_systemd_ci: ../src/tmpfiles/tmpfiles.c:2628:29: error: implicit declaration of function ‘prefix_root’; did you mean ‘prefix_roota’? [-Werror=implicit-function-declaration]
    archlinux_systemd_ci:                          p = prefix_root(arg_root, i.argument);
    archlinux_systemd_ci:                              ^~~~~~~~~~~
    archlinux_systemd_ci:                              prefix_roota
    archlinux_systemd_ci: ../src/tmpfiles/tmpfiles.c:2628:29: error: nested extern declaration of ‘prefix_root’ [-Werror=nested-externs]
    archlinux_systemd_ci: ../src/tmpfiles/tmpfiles.c:2628:27: error: assignment to ‘char *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
    archlinux_systemd_ci:                          p = prefix_root(arg_root, i.argument);
    archlinux_systemd_ci:                            ^
    archlinux_systemd_ci: cc1: all warnings being treated as errors
    archlinux_systemd_ci: [884/2685] Linking target systemd-udevd.
```

The systemd-networkd fail looks like a flake, cc @yuwata

**Comment by mrc0mmand** [comment]
Hm, seeing that fail in other runs as well, it almost looks like a legit fail. @yuwata here are the logs in case you'd like to investigate it further:
https://ci.centos.org/job/systemd-pr-build/7317/artifact//systemd-centos-ci/artifacts_fwjp8M/testsuite-logs-upstream.1M9/systemd-networkd-tests.py_FAIL.log
https://ci.centos.org/job/systemd-ci-build/717/artifact//artifacts_all/artifacts_60EPO9/testsuite-logs-upstream.mgG/systemd-networkd-tests.py_FAIL.log

**Comment by yuwata** [comment]
> Hm, seeing that fail in other runs as well, it almost looks like a legit fail. @yuwata here are the logs in case you'd like to investigate it further:
> https://ci.centos.org/job/systemd-pr-build/7317/artifact//systemd-centos-ci/artifacts_fwjp8M/testsuite-logs-upstream.1M9/systemd-networkd-tests.py_FAIL.log
> https://ci.centos.org/job/systemd-ci-build/717/artifact//artifacts_all/artifacts_60EPO9/testsuite-logs-upstream.mgG/systemd-networkd-tests.py_FAIL.log

Thanks. I will take a look.

**Pull request merged**
