### PR TITLE
meson: add 'pam' install_tag to pam modules

### PR DESCRIPTION
**Pull request by floppym**

### CODE REVIEW

**Comment by floppym** [comment]
cc @bluca

**Comment by udeved** [comment]
@floppym 

Seeing you add install tags, a question.

I made a patch that lets you install udev, tmpfiles and sysusers via tags.
Are you interested to have this on gentoo? 

` hwdb.d/meson.build      | 10 ++++++++++
 meson.build             | 13 +++++++++++++
 meson_options.txt       |  4 ++++
 rules.d/meson.build     |  3 +++
 src/libudev/meson.build |  7 ++++++-
 src/udev/meson.build    | 11 +++++++++++
 sysusers.d/meson.build  |  3 ++-
 tmpfiles.d/meson.build  |  8 +++++++-
 8 files changed, 56 insertions(+), 3 deletions(-)

diff --git a/hwdb.d/meson.build b/hwdb.d/meson.build
index 90b71916b7..41073a1bd6 100644
--- a/hwdb.d/meson.build
+++ b/hwdb.d/meson.build
@@ -43,10 +43,12 @@ if conf.get('ENABLE_HWDB') == 1
                 command : make_autosuspend_rules_py,
                 capture : true,
                 install : true,
+                install_tag : 'udev',
                 install_dir: udevhwdbdir)
 
         install_data(hwdb_files_notest,
                      hwdb_files_test,
+                     install_tag : 'udev',
                      install_dir : udevhwdbdir)
 
         if install_sysconfdir
@@ -57,6 +59,14 @@ if conf.get('ENABLE_HWDB') == 1
                                          'test -n "$DESTDIR" || @0@/systemd-hwdb update'.format(rootbindir))
         endif
 
+        if install_udev_standalone
+                install_emptydir(sysconfdir / 'udev/hwdb.d',
+                        install_tag : 'udev')
+
+                meson.add_install_script('sh', '-c',
+                                         'test -n "$DESTDIR" || @0@/systemd-hwdb update'.format(rootbindir))
+        endif
+
         if want_tests != 'false'
                 parse_hwdb_py = find_program('parse_hwdb.py')
                 test('parse-hwdb',
diff --git a/meson.build b/meson.build
index 60e646ec9f..c8d7b7e74e 100644
--- a/meson.build
+++ b/meson.build
@@ -149,6 +149,8 @@ endif
 
 install_sysconfdir = get_option('install-sysconfdir') != 'false'
 install_sysconfdir_samples = get_option('install-sysconfdir') == 'true'
+install_udev_standalone = get_option('install-udev-standalone')
+install_tmpfiles_standalone = get_option('install-tmpfiles-standalone')
 # Dirs of external packages
 pkgconfigdatadir = get_option('pkgconfigdatadir') != '' ? get_option('pkgconfigdatadir') : datadir / 'pkgconfig'
 pkgconfiglibdir = get_option('pkgconfiglibdir') != '' ? get_option('pkgconfiglibdir') : libdir / 'pkgconfig'
@@ -3462,6 +3464,7 @@ if enable_sysusers
                                      libbasic_gcrypt,
                                      libsystemd_static],
                         install : true,
+                        install_tag : 'sysusers',
                         install_dir : rootbindir)
                 public_programs += exe
 
@@ -3505,6 +3508,7 @@ if conf.get('ENABLE_TMPFILES') == 1
                                      libsystemd_static],
                         dependencies : [libacl],
                         install : true,
+                        install_tag : 'tmpfiles',
                         install_dir : rootbindir)
                 public_programs += exe
 
@@ -3525,6 +3529,7 @@ if conf.get('ENABLE_HWDB') == 1
                 link_with : udev_link_with,
                 install_rpath : udev_rpath,
                 install : true,
+                install_tag : 'udev',
                 install_dir : rootbindir)
         public_programs += systemd_hwdb
 
@@ -3571,9 +3576,17 @@ udevadm = executable(
                         libblkid],
         install_rpath : udev_rpath,
         install : true,
+        install_tag : 'udev',
         install_dir : rootbindir)
 public_programs += udevadm
 
+if install_udev_standalone
+        install_symlink('udevd',
+                        install_dir : rootbindir,
+                        pointing_to : rootbindir / 'udevadm',
+                        install_tag : 'udev')
+endif
+
 if conf.get('ENABLE_REPART') == 1
         exe = executable(
                 'systemd-repart',
diff --git a/meson_options.txt b/meson_options.txt
index 26d1170c50..2926887d0c 100644
--- a/meson_options.txt
+++ b/meson_options.txt
@@ -203,6 +203,10 @@ option('docdir', type : 'string',
        description : 'documentation directory')
 option('install-sysconfdir', type : 'combo', choices : ['true', 'no-samples', 'false'], value : 'true',
        description : 'install configuration files and directories to $sysconfdir')
+option('install-udev-standalone', type : 'boolean', value : false,
+       description : 'install udev configuration files and directories')
+option('install-tmpfiles-standalone', type : 'boolean', value : false,
+       description : 'install tmpfiles configuration files and directories')
 
 option('fallback-hostname', type : 'string', value : 'localhost',
        description : 'the hostname used if none configured')
diff --git a/rules.d/meson.build b/rules.d/meson.build
index a582e4e922..8376da17e8 100644
--- a/rules.d/meson.build
+++ b/rules.d/meson.build
@@ -2,6 +2,7 @@
 
 install_data(
         'README',
+        install_tag : 'udev',
         install_dir : udevrulesdir)
 
 rules = [
@@ -42,6 +43,7 @@ all_rules = []
 foreach tuple : rules
         if tuple.length() == 1 or tuple[1]
                 install_data(tuple[0],
+                             install_tag : 'udev',
                              install_dir : udevrulesdir)
                 all_rules += tuple[0]
         endif
@@ -68,6 +70,7 @@ foreach tuple : rules_in
                 output: tuple[0],
                 command : [jinja2_cmdline, '@INPUT@', '@OUTPUT@'],
                 install : want,
+                install_tag : 'udev',
                 install_dir : udevrulesdir)
 
         if want
diff --git a/src/libudev/meson.build b/src/libudev/meson.build
index 343fac6945..3e4af8d183 100644
--- a/src/libudev/meson.build
+++ b/src/libudev/meson.build
@@ -24,6 +24,11 @@ libudev_sym_path = meson.current_source_dir() / 'libudev.sym'
 install_headers('libudev.h')
 libudev_h_path = meson.current_source_dir() / 'libudev.h'
 
+if install_udev_standalone
+        libudev_h_path = meson.current_source_dir() / 'libudev.h'
+        install_data(libudev_h_path, install_dir: includedir, install_tag: 'udev-devel')
+endif
+
 libudev_basic = static_library(
         'udev-basic',
         libudev_sources,
@@ -40,7 +45,7 @@ custom_target(
         output : 'libudev.pc',
         command : [jinja2_cmdline, '@INPUT@', '@OUTPUT@'],
         install : pkgconfiglibdir != 'no',
-        install_tag : 'devel',
+        install_tag : 'udev-devel',
         install_dir : pkgconfiglibdir)
 
 ############################################################
diff --git a/src/udev/meson.build b/src/udev/meson.build
index 79964a7d8e..22be8ce172 100644
--- a/src/udev/meson.build
+++ b/src/udev/meson.build
@@ -152,6 +152,7 @@ foreach prog : udev_progs
                 link_with : udev_link_with,
                 install_rpath : udev_rpath,
                 install : true,
+                install_tag : 'udev',
                 install_dir : udevlibexecdir)
 
         udev_prog_paths += {name : exe}
@@ -162,12 +163,22 @@ if install_sysconfdir_samples
                      install_dir : sysconfdir / 'udev')
 endif
 
+if install_udev_standalone
+        install_data('udev.conf',
+                     install_tag : 'udev',
+                     install_dir : sysconfdir / 'udev')
+
+        install_emptydir(sysconfdir / 'udev/rules.d',
+                        install_tag : 'udev')
+endif
+
 custom_target(
         'udev.pc',
         input : 'udev.pc.in',
         output : 'udev.pc',
         command : [jinja2_cmdline, '@INPUT@', '@OUTPUT@'],
         install : pkgconfigdatadir != 'no',
+        install_tag : 'udev-devel',
         install_dir : pkgconfigdatadir)
 
 if install_sysconfdir
diff --git a/sysusers.d/meson.build b/sysusers.d/meson.build
index 608c4b744a..687544da58 100644
--- a/sysusers.d/meson.build
+++ b/sysusers.d/meson.build
@@ -8,7 +8,7 @@ foreach pair : files
         if not enable_sysusers
                 # do nothing
         elif pair[1] == '' or conf.get(pair[1]) == 1
-                install_data(pair[0], install_dir : sysusersdir)
+                install_data(pair[0], install_tag : 'sysusers', install_dir : sysusersdir)
         else
                 message('Not installing sysusers.d/@0@ because @1@ is @2@'
                         .format(pair[0], pair[1], conf.get(pair[1], 0)))
@@ -35,5 +35,6 @@ foreach tuple : in_files
                 output: file,
                 command : [jinja2_cmdline, '@INPUT@', '@OUTPUT@'],
                 install : tuple[1],
+                install_tag : 'sysusers',
                 install_dir : sysusersdir)
 endforeach
diff --git a/tmpfiles.d/meson.build b/tmpfiles.d/meson.build
index 4546169694..17607b6c8b 100644
--- a/tmpfiles.d/meson.build
+++ b/tmpfiles.d/meson.build
@@ -20,7 +20,7 @@ foreach pair : files
         if not enable_tmpfiles
                 # do nothing
         elif pair[1] == '' or conf.get(pair[1]) == 1
-                install_data(pair[0], install_dir : tmpfilesdir)
+                install_data(pair[0], install_tag : 'tmpfiles', install_dir : tmpfilesdir)
         else
                 message('Not installing tmpfiles.d/@0@ because @1@ is @2@'
                         .format(pair[0], pair[1], conf.get(pair[1], 0)))
@@ -44,6 +44,7 @@ foreach pair : in_files
                         output: pair[0],
                         command : [jinja2_cmdline, '@INPUT@', '@OUTPUT@'],
                         install : enable_tmpfiles,
+                        install_tag : 'tmpfiles',
                         install_dir : tmpfilesdir)
         else
                 message('Not installing tmpfiles.d/@0@ because @1@ is @2@'
@@ -55,3 +56,8 @@ if enable_tmpfiles and install_sysconfdir
         meson.add_install_script(
                 'sh', '-c', mkdir_p.format(sysconfdir / 'tmpfiles.d'))
 endif
+
+if enable_tmpfiles and install_tmpfiles_standalone
+        install_emptydir(sysconfdir / 'tmpfiles.d',
+                        install_tag : 'tmpfiles')
+endif
`

It is not perfect, man pages on todo, but does the job with 251-rc3 plus you latest devel tag commit.
I changed btw the libudev devel to libudev-devel to separate it from libsystemd.
If there is interest, I can do a PR when it is finished.

**Comment by udeved** [comment]
@floppym 

I thought so, that we are on same mission, regardless of ebuild or PKGBUILD.

I managed to shorten it to just meson install calls with the tags.
We build (lib)udev, sysusers and tmpfiles. You probably would have to add for boot, since we don't use it.
I just made the udevadm symlink for udev configurable, the posted patch had it hardcoded for our needs.
Sadly, the install_headers() doesn't support install_tag (yet?), so install_data() has to do for the header.
Will keep you updated. :)

**Review by bluca — APPROVED** [review]

**Comment by udeved** [comment]
@floppym 

Here is an updated patch.
A couple of things to do eventually.
Should I tie the udevd install options and the /etc/udev/ creation to standalone-binaries flag? Or keep the flags in the patch?

```
-Dinstall-udev-standalone=true
-Dinstall-tmpfiles-standalone=true
-Ddefault-udevd-symlink='udevd'
-Ddefault-udevd-path='/usr/bin'
```

https://gitea.artixlinux.org/artix/dev-scripts/src/branch/master/systemd-meson-install-tags.patch

**Pull request merged**
