### PR TITLE
treewide: treatment of errno and other cleanups

### PR DESCRIPTION
**Pull request by michich**
This series results from an audit of how we check for errors returned by functions.

### CODE REVIEW

**Comment by zonque** [comment]
Except for the one I commented on, this looks all correct to me, nice collection of fixes!

**Comment by poettering** [comment]
Yeah, I agree with @zonque the (void) casting and returning sounds less than ideal to me. I think it's fine to make things terse, but I doubt this specific ase helps legibility...

**Comment by poettering** [comment]
The rest looks excellent! Any chance @michich you can repost without that one patch? Is good to merge then.

**Comment by michich** [comment]
Of course. I'll get to it during the evening.

**Comment by michich** [comment]
v2 posted as PR #1820

**Pull request closed without merging**
