### PR TITLE
Revert "networkctl cleanups and improvements"

### PR DESCRIPTION
**Pull request by evverx**
Reverts systemd/systemd#13201

### CODE REVIEW

**Comment by evverx** [comment]
I'm not sure why PRs where CI clearly fails keep getting merged.

**Comment by poettering** [comment]
Hmm? That pr shows no failed ci?

**Comment by evverx** [comment]
Looks like you pressed the "view details" button there. It just shows the state the PR was in when it got merged. If you scroll up a little bit, you'll find https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/i386/s/systemd-upstream/20190729_202007_20fcb@/log.gz.

**Comment by keszybz** [comment]
... or even https://github.com/systemd/systemd/pull/13201#issuecomment-515887047. I guess we'll need to merge this, unless we can find the failure quickly.

**Comment by evverx** [comment]
Judging by "Command '['networkctl', 'status', 'test_eth42']' died with <Signals.SIGABRT: 6>", `networkctl` seems to crash after it receives SIGABRT. It's hard to tell what exactly is going on without coredumps though.

**Comment by keszybz** [comment]
Yep, this is what makes me optimistic. It should be pretty easy to figure out. Probably some assert gone wrong or something.

**Comment by evverx** [comment]
Well, Ubuntu CI (which rebases PRs on top of master) tends to get stuck due to jobs piling up there when tests fail and if I recall correctly the only person who can unclog it was at a conference a few days ago so I wouldn't wait too long.

**Comment by keszybz** [comment]
OK, so we know that reverting #13221 works. Let's hope that #13224 is enough to fix the issue.

**Comment by evverx** [comment]
In #13224 `bionic-i386` hasn't finished yet. Moreover, judging by the logs it's at least the second attempt to run it there, which usually isn't a good sign.

**Pull request closed without merging**
