### PR TITLE
import-creds: don't import creds from SMBIOS/qemu in confidential VMs

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by bluca** [comment]
I think @berrange was working on this too? Esp. in terms of testing on actual confidential VMs

**Comment by berrange** [comment]
> I think @berrange was working on this too? Esp. in terms of testing on actual confidential VMs

That's fine, this is essentially identical to a patch I have locally, pending testing.

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
@berrange did you have time to check this?

**Comment by berrange** [comment]
> @berrange did you have time to check this?

It looks to be working fine to me, so I'd say this is OK to merge

**Pull request merged**
