### PR TITLE
code-of-conduct file rename

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by yuwata** [comment]
Unfortunately, still the CoC field in https://github.com/systemd/systemd/community is not green. Is it a github issue?

**Comment by evverx** [comment]
According to https://help.github.com/articles/about-community-profiles-for-public-repositories/, the community profile checklist checks to see if a project includes recommended community health files, such as README, CODE_OF_CONDUCT, LICENSE, or CONTRIBUTING, _in the root of the repository_, so, technically, it's not an issue, but it kind of contradicts what's written at https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/ regarding `docs/`. Probably, the easiest way to make it green is to move the file to the root directory.

**Comment by keszybz** [comment]
In that case, let's just ignore this. We don't need the checkbox to be checked that much.

**Comment by evverx** [comment]
I reported this to the GitHub support yesterday. I suppose all we have to do is just wait and see.

**Comment by poettering** [comment]
Interestingly, if you post a new issue using https://github.com/systemd/systemd/issues/new?template=Bug_report.md then in the lower right it actually does show the correct link to the code of conduct, so it did actually discover the file... It appears though as if that "community" link looks elsewhere...

**Comment by evverx** [comment]
Here's the response I received today:

Currently, the tool will check for code of conduct files that we recognize, instead of for the existence of a CODE_OF_CONDUCT.md. This was an intentional choice made to avoid giving folks a checkmark if they've got a file full of content that is not actually a code of conduct.

We do have an issue open about improving this behaviour and I've added your report there.

In the meantime, if you'd like the code of conduct to show, switching to one we provide via our code of conduct tool should do the trick:

https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/#adding-a-code-of-conduct-using-a-template

**Comment by evverx** [comment]
To be honest, I find it reasonable to kind of ignore codes of conducts that haven't been approved.

Anyway, since we've been discussing the code of conduct here and since apparently there's no way to ask questions about it anywhere else without reporting anyone, I'm trying to figure out whether calling people trolls somewhat indirectly by adding the "troll" label is a personal attack or not. @keszybz @davidstrauss what do you think? Could we get rid of this label?

(I'd have CCed Ekaterina if I'd known the handle).

**Comment by mbiebl** [comment]
@evverx we could use the invalid label from now on?

**Comment by vcaputo** [comment]
The abrupt closing of such issues/PRs is effectively saying "troll" without feeding them.

But the label probably has historical value, e.g. in future discussions regarding the prevalence of such attacks on the project; simply filter by label="troll".

**Comment by davidstrauss** [comment]
> Anyway, since we've been discussing the code of conduct here and since apparently there's no way to ask questions about it anywhere else without reporting anyone,

I think the CoC is fairly clear that you don't have to report a specific person in order to email the group:

"Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at <email>."

I also don't see any problem with raising issues like this (i.e. not a complaint about an individual) publicly, as you've done here.

> I'm trying to figure out whether calling people trolls somewhat indirectly by adding the "troll" label is a personal attack or not. @keszybz @davidstrauss what do you think? Could we get rid of this label?

I don't intrinsically see the "troll" label as a personal attack, as we apply it to the posted issue, not the user. However, I also support clarifying that. Changing the name to "trolling" sounds like a good first step. It's probably even better if we can adopt something less polarizing, but I'm not sure "invalid" quite captures it. Maybe "unproductive"?

**Comment by evverx** [comment]
> I think the CoC is fairly clear that you don't have to report a specific person in order to email the group

As a non-native speaker of English, I wouldn't say that that sentence is clear enough because, well, I understand it literally in the sense that the word "instance" means a particular example of something where particular people are involved and so on and so forth and it has nothing to do with general questions/suggestions, as I see it. Plus, it's in the "enforcement" section, which, in theory, shouldn't be relevant at all when I'm not trying to enforce anything.
 
Regarding the name of the label, "unproductive" sounds much better to me, though, frankly, I'm not sure why such issues should be labeled. Lately, such issues seem to have been reported to the GitHub support and removed soon afterwards.

**Comment by evverx** [comment]
Another thing I'm not sure about (and which still isn't clear to me after I read the code of conduct) is using expletives such as "fuck", "fucking dns", "somebody must be fucking with us" (the first two are from PRs and the last is from the source code). To judge from what I've been reading lately, it's totally fine to use them to express frustration at least. Just out of curiosity, does that mean that everybody is OK with this?

**Comment by keszybz** [comment]
> Regarding the name of the label, "unproductive" sounds much better to me, though

I like that too. Since we all seem to be fine with it, I'll go ahead and rename the troll label to that.

> there's no way to ask questions about it anywhere else without reporting anyone,

I think that's a feature. Essentially, we do *not* want to use the private e-mail list for discussions about the rules, team membership, or anything else which doesn't require privacy. So yeah, I'd say that communication to  systemd-conduct@ should be about instances of behaviour or specific people.

> "fuck", "fucking dns", "somebody must be fucking with us" 

Those are all common swearwords in general use. As long as the sentiment is not directed at a specific person, I don't see an issue with it.

**Comment by evverx** [comment]
@keszybz although I personally wouldn't say that I approve of swearing, I have to admit that sometimes it's probably kind of a natural way to say something :-), but could we at least agree not to use swear words in the source code and documentation? I believe commits like https://github.com/systemd/systemd/commit/a2917d3d2a3ce926f74b63aa60a47f838a8e1f83 are great (plus, I learnt what "hoge" is :-)).

**Comment by davidstrauss** [comment]
@evverx said:
> could we at least agree not to use swear words in the source code and documentation?

I see this as two questions:

- Does the CoC require systemd's source code to not use swear words?
- Should we remove swear words from the source code and documentation?

Regarding the first question, I agree with @keszybz ; I don't see the policy directly prohibiting it. However, I'm also concerned that it's where we're starting the conversation. Our CoC isn't designed to define the line between good and bad behavior. Our CoC is designed to provide a process for handling particularly bad and difficult behavior (with some guidelines for staying far from such bad behavior).

Regarding the second question, just because something's tolerated by the CoC doesn't mean it has to be the norm. Also, because our CoC isn't a definition of all that's good or bad, we shouldn't need to amend the CoC to prohibit everything we don't like, especially when our standard collaboration tools (GitHub, mailing list, IRC) provide a way.

I encourage you to submit a pull request to remove the swear words from the source code and documentation. The project can still choose to accept the change without our CoC requiring it.

@keszybz said:
> I think that's a feature. Essentially, we do not want to use the private e-mail list for discussions about the rules, team membership, or anything else which doesn't require privacy.

I think we're in agreement that the CoC isn't the best starting place for the vast majority of topics.

**Comment by evverx** [comment]
> Our CoC is designed to provide a process for handling particularly bad and difficult behavior

As I wrote elsewhere, just sending a complaint to strangers and waiting for a reply without understanding how it's going to be handled isn't exactly a process of handling particularly bad behavior. Anyway, I always thought that codes of conduct are also supposed to communicate standards and expectations for how to engage in a community. Does that mean that the code of conduct that has been adopted wasn't designed for that?

> with some guidelines for staying far from such bad behavior

The problem with the guidelines is that they're too vague to be meaningful. For example, my idea of respectful place (which the guidelines are presumably supposed to provide for everybody) excludes swearing altogether. And, hypothetically, if I were about to report something like this as a concerned parent who obviously didn't want my children to participate in a project whose members are totally fine with it, after reading this thread, I'd never do that.

> I encourage you to submit a pull request to remove the swear words from the source code and documentation. 

Sorry, but I think it's futile when everybody else thinks that there's nothing inherently wrong with swear words in the code and documentation.

**Comment by davidstrauss** [comment]
> Anyway, I always thought that codes of conduct are also supposed to communicate standards and expectations for how to engage in a community. Does that mean that the code of conduct that has been adopted wasn't designed for that?

I believe our CoC does communicate some basic standards and expectations for collaboration. I'm only saying that it's not an _exhaustive_ list of every good or bad behavior (nor should it be, in my opinion).

> The problem with the guidelines is that they're too vague to be meaningful.

I think there's a difference between the guidelines being vague versus narrow. I find our guidelines narrow, and it seems like you desire them to be more expansive. However, the fact that the CoC doesn't prohibit something you think it should prohibit isn't evidence of vagueness. I don't think there's confusion over whether the CoC prohibits swearing in general.

> For example, my idea of respectful place (which the guidelines are presumably supposed to provide for everybody) excludes swearing altogether.

I understand that the rules don't require every practice you find necessary for respect, and I'm not trying to trivialize that. However, I don't think there's any set of rules for swear words that will please everyone. Attempting to define what counts as a swear word would be almost impossible to do across cultures and countries. Even if we attempted a list, we would offend people through excluding certain words and including others. Certain swear words have completely different levels of offense associated with them by region, too.

> Sorry, but I think it's futile when everybody else thinks that there's nothing inherently wrong with swear words in the code and documentation.

While I wasn't planning to directly merge your pull request, I was planning to give it a +1. I'm disappointed that you want the change enforced through the CoC before attempting the change through the normal process. We've committed replacements for swear words before; you linked to the commit.

**Comment by evverx** [comment]
@davidstrauss guidelines like https://developers.google.com/style/tone don't even mention swear words because everything else there seems to make it obvious that they shouldn't be used. Anyway, I understand and respect your point of view and appreciate your patience in clarifying it, but I'm afraid I disagree with it. I don't think this conversation is going to change my opinion, or anyone else's for that matter, so it's probably would be best to leave it at that. I can live with the code of conduct that doesn't change anything in how the code and documentation are written and how people in the community communicate with each other.

**Pull request merged**
