### PR TITLE
detect-virt: also detect "microsoft" and WSL

### PR DESCRIPTION
**Pull request by keszybz**
Follow-up for #11932.

### CODE REVIEW

**Comment by poettering** [comment]
lgtm, but I think there's a `)` missing.

**Comment by keszybz** [comment]
Arrgh. I decided to refactor the `if` before pushing. Should be OK now.
Note: this is fully untested, since I don't have the means to do that. But it seems trivial enough.

**Comment by keszybz** [comment]
semaphore ci: `E: Sub-process /usr/bin/dpkg returned an error code (1)`, unrelated.

bionic-arm64: `test-watchdog                           TIMEOUT 30.02 s `, unrelated.

centos ci (arch in kvm): `13:40:03 TEST-47-ISSUE-14566`, unrelated.

**Comment by bluca** [comment]
FYI at some point in the near future the WSL substring will appear in WSL2's /proc/sys/kernel/osrelease - see https://github.com/Microsoft/WSL/issues/423#issuecomment-611086412

**Pull request merged**
