### PR TITLE
test-bpf: configure and use appropriate path to PING

### PR DESCRIPTION
**Pull request by xnox**
Fixes: #7267

### CODE REVIEW

**Comment by poettering** [comment]
where is ping installed on Debian/Ubuntu?

**Comment by mbiebl** [comment]
> where is ping installed on Debian/Ubuntu?

```
$ dpkg -S /bin/ping
iputils-ping: /bin/ping
```

**Comment by poettering** [comment]
good, then let's hardcode that path. I figure that should be safe, given that at least other major distros tend to implement merged /usr

**Comment by xnox** [comment]
@poettering I pushed a version which uses `/bin/ping` as the default / fallback path.

**Comment by poettering** [comment]
well, i am basically suggesting to not make the path dynamic, but always use debian's path. Most modern distros use the /usr merge, hence the path doesn't matter. It's a pity that Debian still split that out, but it doesn't matter, we can just use their path, and all should be good.

**Comment by xnox** [comment]
@poettering ack, done. Simply using /bin/ping now, without any mesonfication.

**Comment by poettering** [comment]
lgtm, let's see if CI likes it too.

**Pull request merged**
