### PR TITLE
Revert "bus-message: immediately reject messages with invalid type"

### LINKED ISSUE #16193: Breaking change in sd_bus_message_new() in v245.6
**systemd version the issue has been seen with**
> 245.6

**Used distribution**
 > ArchLinux

**Expected behaviour you didn't see**
 > `sd_bus_message_new()` should be able to create and return a D-Bus message of type `_SD_BUS_MESSAGE_TYPE_INVALID`. This expected behavior is exhibited by all other sd-bus versions until 245.6. But 245.6 changed this behavior in a backwards-incompatible way.

**Unexpected behaviour you saw**
 > `sd_bus_message_new()` invoked with `_SD_BUS_MESSAGE_TYPE_INVALID` fails, returns invalid value error. This breaks `sdbus-c++` library, since one of its core concepts is based on plain sd-bus messages used only for storing/reading serialized data.

**Steps to reproduce the problem**
> Just call `sd_bus_message_new()` with `_SD_BUS_MESSAGE_TYPE_INVALID` type.

Suspicious commit that brought this change: a2dd99

### PR DESCRIPTION
**Pull request by keszybz**
This reverts commit a2dd991d0fde59dc0574bd4d0c1438f01dc0b8ff.
Creation of such messages is evidently useful, and at least sdbus-c++ test
suite depends on that.

Fixes #16193.

### CODE REVIEW

**Comment by poettering** [comment]
Maybe add a comment, so that this doesn't get undone again?

**Comment by keszybz** [comment]
Updated with the requested comment and a fix for a test case that the CI found.

**Comment by keszybz** [comment]
I'll set the label again. If is a revert after all, and if the tests pass, we should be no worse off than before the reverted patch.

**Comment by keszybz** [comment]
bionic-amd64 fails with a timeout in some other fuzzers and test-event. Looks like a general machine overload, unrelated to this PR.

**Pull request merged**
