### PR TITLE
meson: re-enable -Wmaybe-uninitialized

### PR DESCRIPTION
**Pull request by keszybz**
It was disabled in 8794164fed5f0142c34358613f92f4f761af4edd to avoid
false positives. But it is useful in finding errors, even if it sometimes
results in untrue warnings (c.f. https://github.com/systemd/systemd/pull/19168,
and the mtime patch in this series).

After #19168, #19169, and #19175, there are no warnings with
-Dbuildtype=debug-optimized and gcc-11.0.1-0.3.fc34.x86_64. Let's reenable the
warnings.

### CODE REVIEW

**Comment by bluca** [comment]
Looks like one more crept in:

```
../src/shared/base-filesystem.c: In function ‘base_filesystem_create’:
../src/shared/base-filesystem.c:107:20: error: ‘r’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  107 |                 if (r < 0) {
```

**Comment by keszybz** [comment]
I don't see this one here. But it's the same pattern, gcc doesn't understand that `RUN_WITH_UMASK` body is always executed. I tried in the past to make `RUN_WITH_UMASK` be different, so that the compiler sees that the use is safe, but it's not easy. I'll try again, maybe wrapping `umask()` will help.

**Review by yuwata — APPROVED** [review]
LGTM.

**Comment by bluca** [comment]
On Arch:

```
16:39:27     archlinux_systemd_ci: ../build/src/basic/os-util.c: In function ‘open_extension_release’:
16:39:27     archlinux_systemd_ci: ../build/src/basic/os-util.c:81:12: error: ‘r’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
16:39:27     archlinux_systemd_ci:    81 |         if (r < 0)
16:39:27     archlinux_systemd_ci:       |            ^
16:39:27     archlinux_systemd_ci: cc1: all warnings
```

**Comment by keszybz** [comment]
Updated. The last three commits are new or modified, the rest is unchanged.

**Comment by keszybz** [comment]
bionic-amd64 timed out in upstream tests... This means that the compilation passed, and is probably unrelated.

**Pull request merged**
