### PR TITLE
9p is a network filesystem

### PR DESCRIPTION
**Pull request by YmrDtnJu**
Its probably hardly ever used over a network but maybe over its virtio transport. So lets treat it as a network filesystem.

### CODE REVIEW

**Comment by keszybz** [comment]
The important part is whether this fs can be used for local mounts (in the sense of the kernel directly creating a mountpoint from a block device). If yes, then we shouldn't mark it as a network filesystem automatically, because this would break boot for people who use 9p to mount stuff in early boot.

I don't know how 9p is used. Wikipedia only talks about remote uses. If that is true, then the patch is OK, but the commit message needs adapting. Right now it implies that is mostly used locally, in which case the patch would be inappropriate.

**Comment by arvidjaar** [comment]
> I don't know how 9p is used

I use it to mount host directories in QEMU guests. It certainly does not need any network. I do not understand where assumption virtio == network comes from.

**Comment by YmrDtnJu** [comment]
@arvidjaar How do you mount it?

**Comment by arvidjaar** [comment]
> How do you mount it?

```
$ grep home /etc/fstab
home	/host/home	9p	noauto,users,trans=virtio,version=9p2000.L	0	0
```

and yes, it works with `auto` too.

> `systemd-mount` tries to create an absolute path from the mount_tag

Then fix `systemd-mount`. May be systemd needs global list of virtual filesystems that do not require real block device.

**Comment by YmrDtnJu** [comment]
@arvidjaar I am happy to provide such a change if that is what upstream would like to have and as soon as we have agreed on the name of such a function.

**Comment by poettering** [comment]
maybe call this fstype_is_blockdev_backed() or so and put it together from `!fstype_is_api_vfs()` and `!fstype_is_network()` plus manually listed items like this one.

**Pull request merged**
