### PR TITLE
syscall: disable epoll_pwait2() for now on 32bit

### PR DESCRIPTION
**Pull request by yuwata**
Alternative to #18973.

### CODE REVIEW

**Comment by yuwata** [comment]
Minor change from #18975. It seems fedora build environment does not allow `#pragma message`.

**Comment by poettering** [comment]
lgtm

**Comment by yuwata** [comment]
Sorry, `#pragma message` was not an issue... Still test fails.

**Comment by yuwata** [comment]
Unfortunately, this does not fix the issue. Closing.

**Comment by eworm-de** [comment]
Where is this tracked now?
(I think #19052 should handle the firewall issue only.)

**Comment by eworm-de** [comment]
Ah, looks like we have  #19073 now...

**Comment by yuwata** [comment]
Yes. Sorry, I should mention that in the previous message.

**Pull request closed without merging**
