### PR TITLE
refuse to carry out suspend/sleep/shutdown operations when a blocking inhibitor is installed

### PR DESCRIPTION
**Pull request by nerdmaennchen**
as the description sais

### CODE REVIEW

**Comment by poettering** [comment]
what is this supposed to fix?

**Comment by nerdmaennchen** [comment]
I issue a suspend command from an application and expected that operation to fail if a blocking inhibitor is installed (e.g., by any other application). 
I saw this check  be performed within systemctl suspend, however, there it is racy agains applications that install a blocking inhibitor after the check, but before systemctl actually issues the command.

IMO there is only one race-condition free location where this check is meaningful; which I recon is there.

cheers!

**Comment by poettering** [comment]
we check the inibitors from logind anyway. 

note however, that priv clients are not subjected to inhibitors though. Which is tracked in #949, #9356, #16215, …

**Comment by nerdmaennchen** [comment]
I think I see the problem: an unpriviledged user could prevent the system from suspending/halting/etc. ...
gotta think about this a little more.

thank you though!
Also kudos to you for having the code in a fashion that's fairly easy to navigate!

**Comment by poettering** [comment]
OK, let's close this then. I figure the actual issue is the fact that we ignore inhibitors when privileged. Which is already tracked as an issue elswehere. Or maybe I am misunderstanding things? either way I figure we already are covered anyway as logind checks inhibitors anyway.

Closing. Hope that's OK.

**Pull request closed without merging**
