### PR TITLE
zsh/_networkctl: remove duplicated argument for completion

### PR DESCRIPTION
**Pull request by HIDE-r**
It is unnecessary, which will mess the completion.

I found this issue, when I used fzf-tab in zsh  and tried to complete the interface for networkctl command. 
```
networkctl reconfigure eno1:\ \ 2\ eno1\ \ \ \ \ \ \ \ \ \ \ ether\ \ \ \ no-carrier\ configured
```
After read the zsh's Documents, I think this argument is redundant, which introduced at this merged https://github.com/systemd/systemd/pull/27725

```
_describe [-12JVx] [ -oO | -t tag ] descr name1 [ name2 ] [ opt ... ]
          [ -- name1 [ name2 ] [ opt ... ] ... ]
This function associates completions with descriptions. Multiple groups separated by -- can be supplied, potentially with different completion options opts.

The descr is taken as a string to display above the matches if the format style for the descriptions tag is set. This is followed by one or two names of arrays followed by options to pass to compadd. The array name1 contains the possible completions with their descriptions in the form ‘completion:description’. Any literal colons in completion must be quoted with a backslash. If a name2 is given, it should have the same number of elements as name1; in this case the corresponding elements are added as possible completions instead of the completion strings from name1. The completion list will retain the descriptions from name1. Finally, a set of completion options can appear.

If the option ‘-o’ appears before the first argument, the matches added will be treated as names of command options (N.B. not shell options), typically following a ‘-’, ‘--’ or ‘+’ on the command line. In this case _describe uses the prefix-hidden, prefix-needed and verbose styles to find out if the strings should be added as completions and if the descriptions should be shown. Without the ‘-o’ option, only the verbose style is used to decide how descriptions are shown. If ‘-O’ is used instead of ‘-o’, command options are completed as above but _describe will not handle the prefix-needed style.

With the -t option a tag can be specified. The default is ‘values’ or, if the -o option is given, ‘options’.

The options -1, -2, -J, -V, -x are passed to _next_label.

If selected by the list-grouped style, strings with the same description will appear together in the list.

_describe uses the _all_labels function to generate the matches, so it does not need to appear inside a loop over tag labels.
```

Ref: https://zsh.sourceforge.io/Doc/Release/Completion-System.html

### CODE REVIEW

**Comment by rpigott** [comment]
https://github.com/systemd/systemd/pull/27725#discussion_r1199835573

**Comment by HIDE-r** [comment]
> [#27725 (comment)](https://github.com/systemd/systemd/pull/27725#discussion_r1199835573)

yep, I had seen that comment. But I also can not realize why must pass `_links` twice, I think the second array name is optional, And it can work well in my workspace even if I delete it.
```
_describe [-12JVx] [ -oO | -t tag ] descr name1 [ name2 ] [ opt ... ]
          [ -- name1 [ name2 ] [ opt ... ] ... ]
```

**Comment by rpigott** [comment]
Does removing this argument change the behavior for you?

**Comment by HIDE-r** [comment]
Emm... I think you are right. In theory, These two should behave the same with or without this argument. But after removing this argument, my fzf-tab tool can work normally. But I don't know which part caused this issue. So I also create a issue for fzf-tab.[[BUG] completion is mess when _describe use alternative array #424](https://github.com/Aloxaf/fzf-tab/issues/424)

**Comment by bluca** [comment]
What's the status here?

**Comment by rpigott** [comment]
IIUC:

1. This current invocation of _describe is unusual and apparently unnecessary, so it could be removed
2. There is a bug somewhere? Either in the referenced fzf plugin or in zsh that interacts with fzf under certain conditions to give garbled output in the fzf custom completion widget.

I don't see the harm in dropping it. PR should be rebased to drop that merge commit though.

**Pull request merged**
