### PR TITLE
po: specify a glib preset

### PR DESCRIPTION
**Pull request by piotrdrag**
It gives us a list of standard arguments passed to gettext,
see <http://mesonbuild.com/i18n-module.html#i18ngettext>.

### CODE REVIEW

**Comment by keszybz** [comment]
I believe you that this is the right thing to do ;)

**Comment by evverx** [comment]
The CI seems to be failing to build `systemd`
```
[215/1833] 'msgfmt' '--xml' '--template' '../src/login/org.freedesktop.login1.policy.in' '-d' '/data/adttmp/autopkgtest-lxc.hcc3_s8c/downtmp/build.Wof/debian/po' '-o' 'src/login/org.freedesktop.login1.policy'
FAILED: src/login/org.freedesktop.login1.policy 
'msgfmt' '--xml' '--template' '../src/login/org.freedesktop.login1.policy.in' '-d' '/data/adttmp/autopkgtest-lxc.hcc3_s8c/downtmp/build.Wof/debian/po' '-o' 'src/login/org.freedesktop.login1.policy'
msgfmt: cannot locate ITS rules for ../src/login/org.freedesktop.login1.policy.in
ninja: build stopped: subcommand failed.
```
though it has started failing since https://github.com/systemd/systemd/pull/7313 was merged.

**Comment by TingPing** [comment]
Since you don't actually use glib it probably specifies a few unnecessary keywords but that is harmless.

**Comment by keszybz** [comment]
Before it was failing on `zipl` import. I thought #7313 failed like that too, so either I forgot to check, or somebody restarted CI after fixing the repos.

The real issue is this:
```
Get:16 http://ppa.launchpad.net/pitti/systemd-semaphore/ubuntu xenial/main s390x meson all 0.40.0-1~xenial [172 kB]
...
WARNING: Unknown keyword arguments in target org.freedesktop.systemd1.policy_merge: data_dirs
```

That's not what the docs say ;) Apparently it was added in 0.40.1-11-g82492f5d76.

@martinpitt can we can an upgrade of meson?

**Comment by keszybz** [comment]
Anyway, let's merge this, since Fedora and Semaphore pass.

**Comment by keszybz** [comment]
Oh, the docs are right, they say 0.41.1. I look at the wrong option.

**Comment by martinpitt** [comment]
@kesbyz: I backported meson 0.42 to the PPA: https://launchpad.net/~pitti/+archive/ubuntu/systemd-semaphore/+packages

I retried PR #7337, and I also triggered a run on Ubuntu 17.10/s390x (artful), to see how it behaves there. I think 16.04 is getting a bit old and requires more and more backports, so moving to a current release would be easier. That will also test against a recent kernel.

**Comment by martinpitt** [comment]
Note that the build failed again with meson 0.42, still on `msgfmt: cannot locate ITS rules for ../src/login/org.freedesktop.login1.policy.in`.

**Comment by piotrdrag** [comment]
FWIW, extracting strings on https://l10n.gnome.org/module/systemd/ is now fixed.

**Comment by keszybz** [comment]
@martinpitt thanks! `--datadirs=` is now passed correctly to msgfmthelper. The log does not show if that is passed on to `msgformat`. So two possibilities: 1) it is not, 2) `msgformat` does not handle it properly. 2) is more likely, in which case we'd need a newer gettext. I'll try to figure out what is happening here.

**Comment by keszybz** [comment]
@martinpitt It builds fine with gettext-0.19.8.1-1ubuntu2 from zesty. Any chance you could add that also to your ppa?

**Comment by martinpitt** [comment]
@keszybz: Uploaded, [building now](https://launchpad.net/~pitti/+archive/ubuntu/systemd-semaphore/+packages?field.name_filter=gettext&field.status_filter=published&field.series_filter=xenial,). Or we just generally flip CI to artful. In the long run this seems easier than piling up more backports?

**Comment by keszybz** [comment]
Thanks.

I'd be happy with artful.

**Comment by martinpitt** [comment]
@kesbyz: I flipped s390x and i386 to artful, kept amd64 at xenial. xenial now should also work with the gettext backport, but if everything works, I'll switch everything to artful. Triggering PR #7337 again. (Note: if you do this, also adjust your retry-gh-systemd-test script correspondingly)

**Pull request merged**
