### PR TITLE
mount: load /proc/self/mountinfo unconditionally when SIGCHLD received

### LINKED ISSUE #23796: systemd: mount units fail with "Mount process finished, but there is no mount."
**systemd version the issue has been seen with**
 > [root@fedora ~]# systemctl --version
systemd 250 (v250.3-8.fc36)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS 
+FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

**Used distribution**
 > Fedora release 36 (Thirty Six)

**Linux kernel version used** (`uname -a`)

 > [root@fedora ~]# uname -a
Linux fedora 5.17.5-300.fc36.x86_64 #1 SMP PREEMPT Thu Apr 28 15:51:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > mounts work

**Unexpected behaviour you saw**
 > 
 Mounting units fail with "Mount process finished, but there is no mount.". 
It's hard to reproduce with 'systemctl daemon-reload' after https://github.com/systemd/systemd/issues/10872 , but it's easy to reproduce with 'systemctl daemon-reexec'.
```
× root-test.mount - mount unit for test
     Loaded: loaded (/proc/self/mountinfo; static)
     Active: failed (Result: protocol) since Tue 2022-06-21 08:38:28 EDT; 4s ago
      Where: /root/test
       What: /dev/loop0
        CPU: 3ms

Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Child 3065 belongs to root-test.mount.
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Mount process exited, code=exited, status=0/SUCCESS (success)
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Mount process finished, but there is no mount.
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Failed with result 'protocol'.
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Changed mounting -> failed
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Failed to delete cgroup entry from LSM BPF map: No such file or directory
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Job 2039 root-test.mount/start finished, result=failed
Jun 21 08:38:28 fedora systemd[1]: Failed to mount root-test.mount - mount unit for test.
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Unit entered failed state.
Jun 21 08:38:28 fedora systemd[1]: root-test.mount: Consumed 3ms CPU time.
```

**Steps to reproduce the problem**
 > 
1. dd if=/dev/zero of=device_file.img bs=1024 count=20000
2. mkfs.ext4 device_file.img;mkdir -p /root/test
3. add test.sh and root-test.mount 
4. systemd-analyze set-log-level debug
5. run test.sh
```
[root@fedora ~]# cat test.sh 
#!/bin/bash
random_sleep() {
    local long
    long="${1-2}"
    sleep $(bc <<< "scale=4; $long*$RANDOM/327670")
    #    echo $(bc <<< "scale=4; $long*$RANDOM/327670")
}

while true
do
    systemctl start root-test.mount & random_sleep
    systemctl daemon-reexec
    sleep 5
    systemctl status root-test.mount >> /root/mount.log
    grep "but there is no mount" /root/mount.log
    if [ $? -eq 0 ]; then
           break
    fi
    systemctl stop root-test.mount
    sleep 2
done
[root@fedora ~]#
[root@fedora ~]# cat /etc/systemd/system/root-test.mount 
[Unit]
Description=mount unit for test
[Mount]
What=/root/device_file.img
Where=/root/test
Type=ext4
Options=nodev
[root@fedora ~]#
```

### PR DESCRIPTION
**Pull request by lclgo**
Fixes #23796.
Replaces #23803.

### CODE REVIEW

**Comment by Geass-LL** [comment]
> Have you tested this?
Yes.
> I guess, it is enough to add a tiny test in test/units/testsuite-64.sh.
I'm not sure, testsuite-64.sh contains many udev storage testcases, this PR has nothing to do with udevd.

**Comment by Geass-LL** [comment]
Tested by using the original scripts, the problem is gone. Then I tried to add a new testcase:

```shell
# testsuite-74.service
[Unit]
Description=TEST-74-REEXEC-MOUNT

[Service]
ExecStartPre=rm -f /failed /testok
ExecStart=/usr/lib/systemd/tests/testdata/units/%N.sh
Type=oneshot
TimeoutSec=0
```

```shell
# testsuite-74.sh
#!/usr/bin/env bash
# SPDX-License-Identifier: LGPL-2.1-or-later
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh
set -u
set -o pipefail

cat > /etc/systemd/system/tmp-tempb.mount << EOF
[Mount]
What=tmpfs
Where=/tmp/tempb
Options=bind
EOF

i=0
while true;
do
        systemctl start tmp-tempb.mount &
        sleep $(awk "BEGIN {print $RANDOM / 65536}")
        systemctl daemon-reexec
        res=$(systemctl is-failed tmp-tempb.mount);
        if [[ "$res" = "failed" ]]; then
                echo Failed > /testfailed;
                break;
        fi
        systemctl stop tmp-tempb.mount
        if [[ $? -ge 200 ]]; then
                echo OK > /testok;
                break;
        else
                i=$(( $i + 1 ));
        fi
done
exit 0
```

But it seems that after running `systemctl daemon-reexec`, systemd will mistakely think testsuite-xx.service has started, and then start `end.service` to kill all processes (including this testsuite-xx.sh). So the testcase dosn't work well for me. I think it should be another problem or maybe systemd doesn't support `daemon-reexec` in a systemd-container.

**Comment by yuwata** [comment]
> But it seems that after running `systemctl daemon-reexec`, systemd will mistakely think testsuite-xx.service has started, and then start `end.service` to kill all processes (including this testsuite-xx.sh). So the testcase dosn't work well for me. I think it should be another problem or maybe systemd doesn't support `daemon-reexec` in a systemd-container.

@mrc0mmand Do you have any idea?

**Comment by mrc0mmand** [comment]
> > But it seems that after running `systemctl daemon-reexec`, systemd will mistakely think testsuite-xx.service has started, and then start `end.service` to kill all processes (including this testsuite-xx.sh). So the testcase dosn't work well for me. I think it should be another problem or maybe systemd doesn't support `daemon-reexec` in a systemd-container.
> 
> @mrc0mmand Do you have any idea?

I'll take a look.

**Comment by mrc0mmand** [comment]
Interesting, looks like this happens only in nspawn, and further debugging suggests that `systemctl daemon-reexec` in nspawn drop the 'Wants=` dependency on `testsuite-XX.service` from `testsuite.target` specified via `systemd.wants=` on the kernel cmdline:

Reproducer:
```bash
set -eux
set -o pipefail

while :; do
    systemctl list-jobs --before testsuite.target
    systemctl daemon-reexec
    systemctl list-jobs --before testsuite.target
    sleep 99
done
```

QEMU:
```
[    2.701930] testsuite-74.sh[574]: + set -o pipefail
[    2.703070] testsuite-74.sh[574]: + :
[    2.703638] testsuite-74.sh[574]: + systemctl list-jobs --before testsuite.target
[    2.716773] testsuite-74.sh[576]: JOB UNIT                                           TYPE  STATE
[    2.718202] testsuite-74.sh[576]: 142 testsuite.target                               start waiting
[    2.719747] testsuite-74.sh[576]: └─  	blocking job 143 (multi-user.target/start)    -     -
[    2.721036] testsuite-74.sh[576]: └─  	blocking job 221 (testsuite-74.service/start) -     -
[    2.722222] testsuite-74.sh[576]: 1 jobs listed.
[    2.723047] testsuite-74.sh[574]: + systemctl daemon-reexec
[    2.891723] testsuite-74.sh[574]: + systemctl list-jobs --before testsuite.target
[    2.902733] testsuite-74.sh[595]: JOB UNIT                                           TYPE  STATE
[    2.903656] testsuite-74.sh[595]: 142 testsuite.target                               start waiting
[    2.904466] testsuite-74.sh[595]: └─  	blocking job 143 (multi-user.target/start)    -     -
[    2.905208] testsuite-74.sh[595]: └─  	blocking job 221 (testsuite-74.service/start) -     -
[    2.906127] testsuite-74.sh[595]: 1 jobs listed.
[    2.906672] testsuite-74.sh[574]: + sleep 99
```

nspawn:
```
Jul 01 13:22:11 H testsuite-74.sh[31]: + systemctl list-jobs --before testsuite.target
Jul 01 13:22:11 H testsuite-74.sh[33]: JOB UNIT                                          TYPE  STATE
Jul 01 13:22:11 H testsuite-74.sh[33]: 1   testsuite.target                              start waiting
Jul 01 13:22:11 H testsuite-74.sh[33]: └─          blocking job 2 (multi-user.target/start)     -     -
Jul 01 13:22:11 H testsuite-74.sh[33]: └─          blocking job 78 (testsuite-74.service/start) -     -
Jul 01 13:22:11 H testsuite-74.sh[33]: 1 jobs listed.
Jul 01 13:22:11 H testsuite-74.sh[31]: + systemctl daemon-reexec
Jul 01 13:22:11 H testsuite-74.sh[31]: + systemctl list-jobs --before testsuite.target
Jul 01 13:22:11 H testsuite-74.sh[48]: JOB UNIT                                      TYPE  STATE
Jul 01 13:22:11 H testsuite-74.sh[48]: 1   testsuite.target                          start waiting
Jul 01 13:22:11 H testsuite-74.sh[48]: └─          blocking job 2 (multi-user.target/start) -     -
Jul 01 13:22:11 H testsuite-74.sh[48]: 1 jobs listed.
Jul 01 13:22:11 H testsuite-74.sh[31]: + sleep 99
```

@yuwata is that expected? Since it feels a bit wrong.

As for the testsuite script itself I cleaned it up a bit:

```diff
diff --git a/test/TEST-74-REEXEC-MOUNT/Makefile b/test/TEST-74-REEXEC-MOUNT/Makefile
new file mode 120000
index 0000000000..e9f93b1104
--- /dev/null
+++ b/test/TEST-74-REEXEC-MOUNT/Makefile
@@ -0,0 +1 @@
+../TEST-01-BASIC/Makefile
\ No newline at end of file
diff --git a/test/TEST-74-REEXEC-MOUNT/test.sh b/test/TEST-74-REEXEC-MOUNT/test.sh
new file mode 100755
index 0000000000..e0e803fda1
--- /dev/null
+++ b/test/TEST-74-REEXEC-MOUNT/test.sh
@@ -0,0 +1,10 @@
+#!/usr/bin/env bash
+# SPDX-License-Identifier: LGPL-2.1-or-later
+set -e
+
+TEST_DESCRIPTION="TODO"
+
+# shellcheck source=test/test-functions
+. "${TEST_BASE_DIR:?}/test-functions"
+
+do_test "$@"
diff --git a/test/units/testsuite-74.service b/test/units/testsuite-74.service
new file mode 100644
index 0000000000..1d36566775
--- /dev/null
+++ b/test/units/testsuite-74.service
@@ -0,0 +1,8 @@
+# SPDX-License-Identifier: LGPL-2.1-or-later
+[Unit]
+Description=TEST-74-REEXEC-MOUNT
+
+[Service]
+ExecStartPre=rm -f /failed /testok
+ExecStart=/usr/lib/systemd/tests/testdata/units/%N.sh
+Type=oneshot
diff --git a/test/units/testsuite-74.sh b/test/units/testsuite-74.sh
new file mode 100755
index 0000000000..731270ddad
--- /dev/null
+++ b/test/units/testsuite-74.sh
@@ -0,0 +1,33 @@
+#!/usr/bin/env bash
+# SPDX-License-Identifier: LGPL-2.1-or-later
+
+set -eux
+set -o pipefail
+
+cat >/etc/systemd/system/tmp-tempb.mount <<EOF
+[Mount]
+What=tmpfs
+Where=/tmp/tempb
+Options=bind
+EOF
+
+for ((i = 0; i < 100; i++)); do
+        systemctl start tmp-tempb.mount &
+        sleep ".$RANDOM"
+        systemctl list-jobs
+        systemctl daemon-reexec
+        systemctl list-jobs
+
+        if [[ "$(systemctl is-failed tmp-tempb.mount)" == "failed" ]] || \
+           journalctl -u tmp-tempb.mount -q --grep "but there is no mount"; then
+                echo failed > /failed
+                exit 1
+        fi
+
+        systemctl stop tmp-tempb.mount || echo $?
+
+done
+
+echo OK > /testok
+
+exit 0
```

but I still can't reproduce the original issue. But I'm not sure how reproducible it is, so maybe it's expected?

**Comment by Geass-LL** [comment]
Can you reproduce it on a clean VM? I mean not run the scripts under systemd‘s test framework.
The reproduce probability is low. And the sleep time is also important,it should be less than 1 second, but maybe more than 0.5s.

**Comment by yuwata** [comment]
@mrc0mmand Thank you for the suggestion and debugging.

> but I still can't reproduce the original issue. But I'm not sure how reproducible it is, so maybe it's expected?

Not sure, but I guess `systemctl start tmp-tempb.mount` is a blocking method, hence we need to use `--no-block` here.
Also, I think it is better to introduce a custom mount wrapper to insert a short sleep before the actual mount process is done.

I will take a look about the dependency issue on nspawn.

**Comment by mrc0mmand** [comment]
>  Also, I think it is better to introduce a custom mount wrapper to insert a short sleep before the actual mount process is done.

Brilliant, that did the trick, thanks!

```bash
#!/usr/bin/env bash
# SPDX-License-Identifier: LGPL-2.1-or-later

set -eux
set -o pipefail

cat >/etc/systemd/system/tmp-tempb.mount <<EOF
[Mount]
What=tmpfs
Where=/tmp/tempb
Options=bind
EOF

mv /bin/mount /bin/mount.orig
cat >/bin/mount <<\EOF
#!/bin/bash

sleep ".$RANDOM"
exec -- /bin/mount.orig "$@"
EOF
chmod +x /bin/mount

for ((i = 0; i < 50; i++)); do
        systemctl --no-block start tmp-tempb.mount
        sleep ".$RANDOM"
        systemctl daemon-reexec

        if [[ "$(systemctl is-failed tmp-tempb.mount)" == "failed" ]] || \
           journalctl -u tmp-tempb.mount -q --grep "but there is no mount"; then
                echo failed > /failed
                exit 1
        fi

        systemctl stop tmp-tempb.mount
done

mv -f /bin/mount.orig /bin/mount

echo OK > /testok

exit 0
```

With current main:
```
[    3.367538] testsuite-74.sh[574]: + systemctl daemon-reexec
...
[    3.389824] systemd[1]: Reexecuting.
...
[    3.592323] systemd[1]: Child 585 (mount.orig) died (code=exited, status=0/SUCCESS)
[    3.592380] systemd[1]: tmp-tempb.mount: Child 585 belongs to tmp-tempb.mount.
[    3.592447] systemd[1]: tmp-tempb.mount: Mount process exited, code=exited, status=0/SUCCESS (success)
[    3.592517] systemd[1]: tmp-tempb.mount: Mount process finished, but there is no mount.
[    3.592582] systemd[1]: tmp-tempb.mount: Failed with result 'protocol'.
[    3.592645] systemd[1]: tmp-tempb.mount: Changed mounting -> failed
[    3.592704] systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=338 reply_cookie=0 signa>
[    3.592771] systemd[1]: tmp-tempb.mount: Job 237 tmp-tempb.mount/start finished, result=failed
[    3.592839] systemd[1]: Failed to mount tmp-tempb.mount.
```

With this PR:
```
[   30.785392] testsuite-74.sh[1680]: ++ systemctl is-failed tmp-tempb.mount
[   30.801703] testsuite-74.sh[577]: + [[ active == \f\a\i\l\e\d ]]
[   30.801800] testsuite-74.sh[577]: + journalctl -u tmp-tempb.mount -q --grep 'but there is no mount'
[   30.811084] testsuite-74.sh[577]: + systemctl stop tmp-tempb.mount
[   30.825364] testsuite-74.sh[577]: + (( i++ ))
[   30.825463] testsuite-74.sh[577]: + (( i < 50 ))
[   30.825823] testsuite-74.sh[577]: + mv -f /bin/mount.orig /bin/mount
[   30.826797] testsuite-74.sh[577]: + echo OK
[   30.826873] testsuite-74.sh[577]: + exit 0
[   30.976028] reboot: Power down
```

**Comment by yuwata** [comment]
> But it seems that after running `systemctl daemon-reexec`, systemd will mistakely think testsuite-xx.service has started, and then start `end.service` to kill all processes (including this testsuite-xx.sh). So the testcase dosn't work well for me. I think it should be another problem or maybe systemd doesn't support `daemon-reexec` in a systemd-container.

@Geass-LL Fix is waiting in #23883.

**Comment by Geass-LL** [comment]
Testcase added based on @mrc0mmand 's commit. Please take a look.

**Comment by yuwata** [comment]
@Geass-LL The first commit actually fixes the issue. But it introduces unnecessary read of /proc/self/mountinfo, in most cases the file is now read twice per mount/umount. That's quite inefficient.

I opened PR #23893, which hopefully catches the root of the issue. PTAL.

**Comment by keszybz** [comment]
#23893 was merged.

**Pull request closed without merging**
