### PR TITLE
Revert "meson: drop rootprefix option"

### PR DESCRIPTION
**Pull request by keszybz**
This reverts commit ee4bfa21f62dbf4d8f2be27d3c763c3c16743bfd.

Also add comment so that this doesn't get deleted again by mistake.

Replaces #7461.

### CODE REVIEW

**Comment by poettering** [comment]
I don't find the usecase too convincing I must say. see my comments on the original PR...

Can we at least add a big fat warning that things are weird if people use any root prefix that is not /usr?

**Comment by keszybz** [comment]
> I don't find the usecase too convincing I must say. see my comments on the original PR

The way I understand this, files are supposed to live an alternate path, but symlinks are provided for all the expected names. So this is different than $DESTDIR, which is used to divert files during package building.

> Can we at least add a big fat warning that things are weird if people use any root prefix that is not /usr?

See new commit.

**Comment by poettering** [comment]
oh, i was thinking a warning that is actually seen, i.e. that shows during the build process

**Comment by keszybz** [comment]
Updated.

**Pull request merged**
