### PR TITLE
NEWS: mention systemd-tmpfiles --user

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by ayekat** [comment]
Is it systemd-wide standard to put logs into `$XDG_CONFIG_HOME/logs`? I'm asking this because I believe that logs should not be mixed with configuration (applications that store changing data into configuration directories are often a nuisance for tracking personal user configuration e.g. with git).

I personally set a (admittedly non-standard) `XDG_LOG_HOME` and make applications on my system put their user-specific log files in there where possible. Then again I do realise such an approach is not realistic for systemd, so couldn't we go with something like `$XDG_DATA_HOME/logs` as a "compromise" (for the shortcomings of the XDG basedir spec)?

**Comment by keszybz** [comment]
I don't really know. I hope nothing much does any logging to traditional files because such logs are not rotated properly. Maybe for some installation logs that's OK, but pretty much all "live" logs should go the user journal.

**Comment by poettering** [comment]
the XDG spec knows no explicit logs directory, hence we have to make up our own. But I think below XDG_CONFIG_HOME is still better than under XDG_DATA_HOME, since the latter should be considered static, immutable resources during runtime. That's at least the interpreation we documented here once upon a time:

https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#Home%20Directory

**Comment by poettering** [comment]
lgtm

**Comment by ayekat** [comment]
I agree that logs should probably go into the user journal anyway, so it's probably not a big deal. But I don't agree with using `XDG_CONFIG_HOME` as a place for variable application data&mdash;following the description in the [specification][xdgspecvars], I would have expected `XDG_DATA_HOME` to be the user's equivalent of `/var/lib`, and no real user's equivalent for "static, immutable data" (i.e. `/usr/share` and/or `/usr/local/share`, despite its name), as the files are generally generated by applications at runtime anyway.

But given that there is already that document for how to interpret the XDG basedir variables, I guess it's a bit late to launch a debate on that matter now ^^'

[xdgspecvars]: https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html

**Comment by keszybz** [comment]
Setting good-to-merge/waiting-for-ci doesn't make much sense for anything that only touches NEWS or other text files. Anything that touches man/ is also fine to merge after semaphore passes. All the additional CI runs don't provide any additional testing.

Let's merge this since @poettering approved.

**Pull request merged**
