### PR TITLE
cgroup: skip unwritable cgroups

### LINKED ISSUE #6408: lxc: Failed to activate service 'org.freedesktop.systemd1': timed out after update to 233.75-3 from 232-8
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 233.75-3

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> systemd starts up all services at boot

### In case of bug report: Unexpected behaviour you saw

> systemd seems to freeze after update and fails to start any services at reboot.  I'm seeing the following output from journalctl ...

```
Jul 19 21:00:43 subsonic dbus[21]: [system] Reloaded configuration
Jul 19 21:00:43 subsonic dbus[21]: [system] Reloaded configuration
Jul 19 21:00:43 subsonic systemd[1]: Reexecuting.
Jul 19 21:00:43 subsonic systemd[1]: systemd 233 running in system mode. (+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid)
Jul 19 21:00:43 subsonic systemd[1]: Detected virtualization lxc.
Jul 19 21:00:43 subsonic systemd[1]: Detected architecture x86-64.
Jul 19 21:00:43 subsonic systemd[1]: Failed to create /init.scope control group: Permission denied
Jul 19 21:00:43 subsonic systemd[1]: Failed to allocate manager object: Permission denied
Jul 19 21:00:43 subsonic systemd[1]: Freezing execution.
Jul 19 21:01:08 subsonic dbus[21]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out
```

### In case of bug report: Steps to reproduce the problem

> I am seeing this issue when updating an lxc container on my server.  The server itself has updated to 233.75-3 without a problem.  The lxc container is unprivileged.  Although root starts the container all the processes running in the container run effectively as nobody from the host machine point of view.  Perhaps the latest systemd update does not support this setup?  Any ideas?

### PR DESCRIPTION
**Pull request by brauner**
When systemd is running inside a container employing user
namespaces it currently mounts the unified cgroup hierarchy
without being able to write to it. This causes systemd to
freeze during boot.
This patch checks whether the unified cgroup hierarchy
is writable. If it is not it will not mount it.

This solution is based on a patch by Evgeny Vereshchagin.

Closes #6408.
Closes lxc/lxc#1678 .

//cc @poettering, @evverx
I've added two additional patches that skip non-fatal additional
cgroup mounts: pure unified cgroup hierarchy and the named systemd
controller. The latter is useful for running user namespace containers
on a host that runs a traditional sysvinit system.

### CODE REVIEW

**Comment by brauner** [comment]
If the additional patches are not suitable I can just drop them. The first patch is just an implementation what we discussed in #7401:

>> /sys/fs/cgroup/unified is likely to be owned by nobody:nogroup, but it really depends on a few different factors.
>>
> If so, then that's what I'd prefer. (But W_OK would be much better even)

**Comment by evverx** [comment]
@brauner, thank you. I think that the first additional commit makes sense, but I'm not sure about the second, mainly because I can't imagine the situation when `name=systemd` can be mounted, but it is not writable.

**Comment by brauner** [comment]
@evverx, I was thinking about a scenario where the `name=systemd` cgroup is not created on the host. If you are in a non-init cgroup namespace (e.g. in a container) than you are not allowed to mount additional cgroups. Because new controllers can only be created in the init cgroup namespace. But maybe this should be handled somewhere else.

**Comment by brauner** [comment]
I should mention that I tested this and this patch makes systemd work in user namespace containers.

**Comment by brauner** [comment]
> @brauner, thank you. I think that the first additional commit makes sense, but I'm not sure about the second, mainly because I can't imagine the situation when name=systemd can be mounted, but it is not writable.

That can happen when you decide not to delegate the `name=systemd` cgroup to an unprivileged user on the host.

**Comment by evverx** [comment]
`TEST-19-DELEGATE` has failed because of https://github.com/systemd/systemd/issues/7425. This has nothing to do with this PR.

**Comment by evverx** [comment]
@brauner, I'm a bit puzzled about what happens after that step is skipped. As far as I understand, in this case `systemd` will fail to boot a little bit later when it tries to create a directory.

**Comment by brauner** [comment]
On Wed, Nov 22, 2017 at 11:13:23PM +0000, Evgeny Vereshchagin wrote:
> @brauner, I'm a bit puzzled about what happens after that step is skipped. As far as I understand, in this case `systemd` will fail to boot a little bit later when it tries to create a directory.

Yeah, I'm not sure if systemd would boot without the name=systemd cgroup being
mounted/writable. That's why I split this into a separate commit. I'm happy to
drop it right now if you want me too.

**Comment by evverx** [comment]
I think it'd be simpler to review the last commit separately, so I'd prefer it if it could be dropped for now. The other commits looks good to me.

**Comment by brauner** [comment]
On Wed, Nov 22, 2017 at 11:59:49PM +0000, Evgeny Vereshchagin wrote:
> I think it'd be simpler to review the last commit separately, so I'd prefer it if it could be dropped for now. The other commits looks good to me.

Dropped the last commit.

**Comment by evverx** [comment]
With this patch applied, `systemd` gracefully got around almost all the traps I carefully had set (except those where `access(W_OK)` is not sufficient :-))
```sh
...
00:54:39.213391 mount("cgroup", "/sys/fs/cgroup", "cgroup2", MS_NOSUID|MS_NODEV|MS_NOEXEC, "nsdelegate") = 0 <0.000058>
00:54:39.213505 access("/sys/fs/cgroup", W_OK) = -1 EACCES (Permission denied) <0.000037>
00:54:39.213592 umount2("/sys/fs/cgroup", 0) = 0 <0.015873>
...
00:54:39.244101 mount("cgroup", "/sys/fs/cgroup", "cgroup2", MS_NOSUID|MS_NODEV|MS_NOEXEC, NULL) = 0 <0.000215>
00:54:39.244550 access("/sys/fs/cgroup", W_OK) = -1 EACCES (Permission denied) <0.000188>
00:54:39.244967 umount2("/sys/fs/cgroup", 0) = 0 <0.015812>
...
00:54:39.276503 mount("cgroup", "/sys/fs/cgroup/unified", "cgroup2", MS_NOSUID|MS_NODEV|MS_NOEXEC, "nsdelegate") = 0 <0.000064>
00:54:39.276635 access("/sys/fs/cgroup/unified", W_OK) = -1 EACCES (Permission denied) <0.000045>
00:54:39.276735 umount2("/sys/fs/cgroup/unified", 0) = 0 <0.015303>
...
00:54:39.300618 mount("cgroup", "/sys/fs/cgroup/unified", "cgroup2", MS_NOSUID|MS_NODEV|MS_NOEXEC, NULL) = 0 <0.000140>
00:54:39.300913 access("/sys/fs/cgroup/unified", W_OK) = -1 EACCES (Permission denied) <0.000099>
00:54:39.301161 umount2("/sys/fs/cgroup/unified", 0) = 0 <0.015526>
...
```
@poettering, I'm merging because you said that `access(W_OK)` seems to be OK to you. If I have misunderstood anything, please let me know, so that I can sort it out.

**Comment by poettering** [comment]
Hmm, so what I had in mind was actually do add the access() check to cg_unified_update()…

But I guess this approach works too. But I think it would be nicer if we'd also try to remove the mount point after unmounting the hierarchy that doesn't work again. After all in hybrid mode /sys/fs/cgroup/ is a tmpfs, and i think it would be good if it didn't show any empty dirs...

**Comment by brauner** [comment]
On Fri, Nov 24, 2017 at 12:38:50PM +0000, Lennart Poettering wrote:
> Hmm, so what I had in mind was actually do add the access() check to cg_unified_update()…
> 
> But I guess this approach works too. But I think it would be nicer if we'd also try to remove the mount point after unmounting the hierarchy that doesn't work again. After all in hybrid mode /sys/fs/cgroup/ is a tmpfs, and i think it would be good if it didn't show any empty dirs...

Just sent a pr that does

(void) rmdir(p->where);

when the cgroup is unwritable.

**Comment by evverx** [comment]
In theory `MNT_CHECK_WRITABLE` could be used not only to mount `cgroups`, but to mount everything else, so I'm not sure that `mount_one` should go as far as to remove anything.

**Comment by brauner** [comment]
Let's move this discussion over to the new PR. This is otherwise a little confusing. :) @evverx, I'm answering you over there.

**Pull request merged**
