### PR TITLE
network: fix assertion in assigning dhcp6 delegated prefix

### LINKED ISSUE #16365: systemd-networkd asserts on restart or DHCPv6 PD lease renewal when AssignAcquiredDelegatedPrefixAddress=yes
**systemd version the issue has been seen with**
> git HEAD

**Used distribution**
 > Ubuntu

**Expected behaviour you didn't see**
 > systemd-networkd does not crash when renewing DHCPv6 PD

**Unexpected behaviour you saw**
 > systemd-networkd crashes when renewing DHCPv6 PD

**Steps to reproduce the problem**
Set up DHCPv6 PD, preferably with a short lease time, start networkd, and wait until the lease is renewed.  It will crash with "systemd-networkd[1322]: Assertion 'IN_SET(link->state, LINK_STATE_CONFIGURING, LINK_STATE_FAILED, LINK_STATE_LINGER)' failed at src/network/networkd-link.c:1195, function address_handler(). Aborting.".  Setting the new option AssignAcquiredDelegatedPrefixAddress to "no" prevents the crash.

I'm going to reproduce this again tomorrow in a test environment so I can post a full debug log of the crash occurring.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #16365.

Replaces #16366.

### CODE REVIEW

**Comment by yuwata** [comment]
BTW, I noticed we need to refactor to set `link->dhcp6_configured` flag, as it is set before netlink callback is called. But Let's do that in another PR.

**Comment by ssahani** [comment]
It just ignores the race as I pointed out here. https://github.com/systemd/systemd/issues/16365#issuecomment-654374753 . But the race is still there.

**Comment by yuwata** [comment]
> It just ignores the race as I pointed out here. [#16365 (comment)](https://github.com/systemd/systemd/issues/16365#issuecomment-654374753) . 

Right.

> But the race is still there. 

Why? Could you elaborate more? @mamarley reports this fixes his issue.

> the `message` part is ignored.

Yeah, let's improve that in a later PR.

**Comment by ssahani** [comment]
> > But the race is still there.
> 
> Why? Could you elaborate more? @mamarley reports this fixes his issue.

https://github.com/systemd/systemd/pull/16379/commits/b96c6e4d06ed51e77f427547a052337585dc1298#diff-30d862b9251b785c8ee19db9d7a0321aR1106 we set `link_set_state(link, LINK_STATE_CONFIGURING);` but you removed the assert of `LINK_STATE_CONFIGURING` hence there is no more assert.  The callback function should set the part configured but which part made is configured ?

> 
> > the `message` part is ignored.
> 
> Yeah, let's improve that in a later PR.

What happens if you add the `message` part. I think it wont assert . Since you removed the assert. in the callback.

**Comment by keszybz** [comment]
@yuwata I think it'd be good to fix the rest of the logic in this PR too: it's hard to see the big picture if some unresolved issues are left for later. Also needs a rebase.

**Comment by keszybz** [comment]
I rebased this now. This fixes the issue to some extent, at least there's no crash as reported by OP. So let's merge this as a quick fix for v246-rc1, and then hopefully we'll have a full fix later.

**Comment by ssahani** [comment]
Adding the address message will not crash too. So let's add that part too.

**Comment by yuwata** [comment]
Full fix will be posted within few days.

**Pull request merged**
