### PR TITLE
Fix #2637

### LINKED ISSUE #2637: Regression: broken specifiers in v229
According to man page, the specifier %% translates to a single % in unit files, and it worked fine before. Starting with v229 this:
`ExecStart=/bin/touch /tmp/%%Uanything`
will touch `/tmp/1000anything` instead of `/tmp/%Uanything`
You need to repeat the percent signs twice to workaround this bug:
`ExecStart=/bin/touch /tmp/%%%%Uanything`
will touch `/tmp/%Uanything`

### PR DESCRIPTION
**Pull request by evverx**
Fixes https://github.com/systemd/systemd/issues/2637

### CODE REVIEW

**Comment by keszybz** [comment]
Can you add justification what is wrong with the reverted commit?

**Comment by evverx** [comment]
Updated: https://github.com/evverx/systemd/commit/bd1b973fb326e9b7587494fd6108e5ded46e9163

**Comment by evverx** [comment]
Actually, there is another resgression:

https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines

> The command line accepts "%" specifiers as described in systemd.unit(5). Note that the first argument of the command line (i.e. the program to execute) may not include specifiers.

But:

```
bash-4.3# systemctl cat hola
# /etc/systemd/system/hola.service
[Service]
Type=oneshot
ExecStart=/tmp/%m

bash-4.3# systemctl start hola
Job for hola.service failed because the control process exited with error code.
See "systemctl status hola.service" and "journalct -xe" for details.

bash-4.3# journalctl -b -u hola
...
Feb 18 12:19:33 systemd-testsuite systemd[1]: hola.service: Forked /tmp/2b5923eaf31f4ca0af77346abc44e870 as 35
...
```

**Comment by evverx** [comment]
@martinpitt 

```
FAIL: test_bash_crash (__main__.CoredumpTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/adt-run.OXSqGe/build.IcX/systemd/debian/tests/boot-and-services", line 447, in test_bash_crash
    self.assertRegex(journal, b'Process.*bash.*dumped core')
AssertionError: Regex didn't match: b'Process.*bash.*dumped core' not found in b'-- Logs begin at Thu 2016-02-18 13:56:01 UTC, end at Thu 2016-02-18 13:56:15 UTC. --\nFeb 18 13:56:12 adt systemd-coredump[918]: Process 866 (unity-settings-) of user 114 dumped core.\n 
```

Try [`journalctl --sync`](https://www.freedesktop.org/software/systemd/man/journalctl.html#--sync).
Something like this:

```
            --> subprocess.call(['journalctl', '--sync']) <--
            journal = subprocess.check_output(['journalctl', '/lib/systemd/systemd-coredump'])
```

**Comment by martinpitt** [comment]
@evverx : Ah, thanks! I committed an increased timeout (5 to 50s) half an hour ago, but `--sync` sounds great too. I'll test that locally (just to make sure) and commit.

**Comment by martinpitt** [comment]
@evverx : Done in http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=388a7e76 , thanks! I already restarted the test a while ago.

**Comment by keszybz** [comment]
I don't think expansion in command name is a regression. It was always "forbidden" because of some SELinux interaction, but it probably wasn't ever enforced. I just tried with systemd-222 from F23 and it gets expanded.

**Comment by keszybz** [comment]
OK, it looks straightforward enough.

So we now have two issues:
- [ ] systemctl shows not resolved specifier on "Process:" field.
  
    @walyong can you look into this?
- [ ] specifiers are not correctly disallowed in argv[0]
  
    Maybe it would be possible to allow specifiers in argv[0]? Some of the SELinux checks were removed, so maybe the original justification for not allowing them is no more. Also, we could simply expand some of the specifiers before doing any SELinux checks.

**Comment by evverx** [comment]
>  I just tried with systemd-222 from F23 and it gets expanded.

Hm, do you mean

```
About to execute: /tmp/f457dec2d6284e4790728437bba9f22a
```

message?

```
[vagrant@localhost tests]$ hostnamectl
   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: f457dec2d6284e4790728437bba9f22a
           Boot ID: 17b2a1adee5a41d7a96eb431f8a53aa1
    Virtualization: oracle
  Operating System: Fedora 23 (Twenty Three)
       CPE OS Name: cpe:/o:fedoraproject:fedora:23
            Kernel: Linux 4.3.5-300.fc23.x86_64
      Architecture: x86-64

[vagrant@localhost tests]$ /lib/systemd/systemd --version
systemd 222
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

[vagrant@localhost tests]$ systemctl cat hola
# /etc/systemd/system/hola.service
[Service]
Type=oneshot
ExecStart=/tmp/%m

[vagrant@localhost tests]$ cat /tmp/f457dec2d6284e4790728437bba9f22a
#!/bin/sh

echo HOLA

[vagrant@localhost tests]$ ls -l !$
ls -l /tmp/f457dec2d6284e4790728437bba9f22a
-rwxrwxr-x. 1 vagrant vagrant 21 Feb 18 15:16 /tmp/f457dec2d6284e4790728437bba9f22a

[vagrant@localhost tests]$ sudo systemctl start hola
Job for hola.service failed because the control process exited with error code. See "systemctl status hola.service" and "journalctl -xe" for details.

[vagrant@localhost tests]$ sudo journalctl -u hola -b
Feb 18 15:21:43 localhost.localdomain systemd[1]: hola.service: Trying to enqueue job hola.service/start/replace
Feb 18 15:21:43 localhost.localdomain systemd[1]: hola.service: Installed new job hola.service/start as 3626
Feb 18 15:21:43 localhost.localdomain systemd[1]: hola.service: Enqueued job hola.service/start as 3626
Feb 18 15:21:43 localhost.localdomain systemd[1]: hola.service: About to execute: /tmp/f457dec2d6284e4790728437bba9f22a
Feb 18 15:21:43 localhost.localdomain systemd[1]: hola.service: Forked /tmp/%m as 19093
Feb 18 15:21:43 localhost.localdomain systemd[1]: hola.service: Changed failed -> start
Feb 18 15:21:43 localhost.localdomain systemd[1]: Starting hola.service...
Feb 18 15:21:43 localhost.localdomain systemd[1]: hola.service: Child 19093 belongs to hola.service
```

**Comment by poettering** [comment]
Hmm, I wonder, shouldn't we rather keep the unit_full_printf() invocation in the ExecXYZ parser, and drop it from service_spawn()? It appears a bit wrong in service_spawn(), in all other cases we resolve this in the parser calls after all. Hence I'd say @walyong's patch was actually right, and instead we should drop the invocation in service_spawn() instead...

Can anyone see a reason why we should keep this in service_spawn()?

The benefit of doing expansion of this stuff in the parser is that we expose the properly resolved strings when people query things on the bus.

**Comment by poettering** [comment]
Also note that none of the specifiers actually resolve to variable values, hence there's really no reason to delay the resolving.

**Pull request merged**
