### PR TITLE
units: add Conflicts=shutdown.target in systemd-udevd.service

### PR DESCRIPTION
**Pull request by yuwata**
Partially solves #14140.

Though, I am not sure it is safe or not...

### CODE REVIEW

**Comment by anitazha** [comment]
Probably fine since the `DefaultDependencies=no` line was added to account for early boot and not late system shutdown.....?

**Comment by poettering** [comment]
Hmm, can you explain why this is necessary? I mean, udevd doesn't really need to write anything to disk, and shouldn't keep anything busy that shouldn't be busy, hence there's not really the need to shut it down. Or is there? can you explain?

**Comment by yuwata** [comment]
> shouldn't keep anything busy that shouldn't be busy

sd-hwdb opens hwdb.bin. So, if /etc or /usr is in another partition, then the partition cannot be unmounted.

Also, as discussed in #14140, `TimeoutStopSec=` does not work for udevd on shutdown.

**Comment by yuwata** [comment]
If /etc is on another partition, then we can confirm that by using the following:
```
# cat /etc/systemd/system/lsof.service
[Unit]
Before=etc.mount
Conflicts=shutdown.target
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=true
ExecStop=lsof /etc
StandardOutput=tty
StandardError=tty
RemainAfterExit=yes

[Install]
WantedBy=etc.mount
```
Then,
```
# shutdown -h now
(snip)
[FAILED] Failed unmounting /etc.
(snip)
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
systemd-u 2470 root  mem    REG 179,10  9491904   18 /etc/udev/hwdb.bin
systemd-u 2470 root   12r   REG 179,10  9491904   18 /etc/udev/hwdb.bin
[  269.619885] systemd-shutdown[1]: 30 output lines suppressed due to ratelimiting
[  269.648878] systemd-shutdown[1]: Syncing filesystems and block devices.
[  269.653222] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[  269.666954] systemd-journald[1793]: Received SIGTERM from PID 1 (systemd-shutdow).
[  269.703245] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[  269.715200] systemd-shutdown[1]: Unmounting file systems.
[  269.720692] [2688]: Remounting '/etc' read-only in with options '(null)'.
[  269.735146] EXT4-fs (mmcblk0p10): re-mounted. Opts: (null)
[  269.741114] [2689]: Unmounting '/etc'.
[  269.763654] systemd-shutdown[1]: All filesystems unmounted.
(snip)
```

**Comment by yuwata** [comment]
(If this is approved, I will add the explanation in the commit message.)

**Comment by poettering** [comment]
We consider /etc and /usr "intrinsic", i.e. not something we would unmount if they are indeed mounts. these are dirs that we run ourselves off and thence we explicitly don't support them to be unmounted during the regular PID1's lifetime, exactly like the root dir itself.

**Comment by yuwata** [comment]
OK. Thanks.

What about "TimeoutStopSec=" thing? Should we revert bfde9421af1458e18999d787b1ab46a6a33e8bb6?

**Comment by fbuihuu** [comment]
> Hmm, can you explain why this is necessary? I mean, udevd doesn't really need to write anything to disk, and shouldn't keep anything busy that shouldn't be busy, hence there's not really the need to shut it down. Or is there? can you explain?

Well I think the justification should be provided for "why do we need to run udevd until the very end ?" instead.

I mean generally all services should be terminated  by systemd unless there're good reasons to not do so and here it's not clear whether udevd would need to handle kernel events after switching to initramfs during shutdow...

**Comment by mbiebl** [comment]
@fbuihuu Are we sure stuff like LVM/cryptsetup/ etc does not need udev during shutdown for e.g. a successful disassemble?

**Comment by fbuihuu** [comment]
I don't know but I think this should be clarified so the absence of Conflicts=shutdown.target is justified and documented in the unit file.

**Comment by mwilck** [comment]
Wrt LVM, I've debugged a related issue lately. LVM needs libudev calls to succeed during pvscan, while it's assembling VGs during boot, in order to recognize RAID or multipath members. That doesn't require systemd-udevd to be running, it just requires an udev data base (/run/udev/data). I don't think LVM calls libudev during disassembly.

**Comment by fbuihuu** [comment]
BTW if any service relies on udevd on shutdown, isn't it supposed to have After=systemd-udevd.service in its unit file ?

Or is the fact that udevd is running until all services with the default deps are stopped documented somewhere ?

**Comment by yuwata** [comment]
> BTW if any service relies on udevd on shutdown, isn't it supposed to have After=systemd-udevd.service in its unit file ?

Right.

> Or is the fact that udevd is running until all services with the default deps are stopped documented somewhere ?

No, I do not think so.

**Comment by poettering** [comment]
> Well I think the justification should be provided for "why do we need to run udevd until the very end ?" instead.

there might be stuff that wants to order itself Before=foo.device, and thus during shutdown wants to be terminated only after a device disappeared (the device could be something synthetic, such as a loopback device or LVM or so). Thus we want to make sure we keep watching udev until the very end so that we notice devices going and so that systemd will make device units go down again if they go away...

**Comment by poettering** [comment]
So, can we close this? https://github.com/systemd/systemd/pull/14160 got merged after all?

**Comment by yuwata** [comment]
Thanks. That makes sense to me.

**Pull request closed without merging**
