### PR TITLE
Revert "tree-wide: Mount file descriptors via /proc/<pid>/fd"

### PR DESCRIPTION
**Pull request by poettering**
Reverts systemd/systemd#28829

As per #29137

### CODE REVIEW

**Comment by poettering** [comment]
(This can be readded with a more focussed approach, just on the DDI mounting case.)

**Comment by poettering** [comment]
(THis is just a placeholder, @DaanDeMeyer feel free to take over)

**Comment by DaanDeMeyer** [comment]
I would just revert, I don't have need for this fix anymore. We can just revert to the previous behavior until we can fix probably (using your suggestions in https://github.com/systemd/systemd/issues/28831

**Review by DaanDeMeyer — APPROVED** [review]

**Review by bluca — APPROVED** [review]
I'll prep stable releases

**Pull request merged**
