### PR TITLE
Test suite updates

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by anitazha** [comment]
Changes look fine but the CI is oddly red. Can you take a look or push again?

**Comment by yuwata** [comment]
Still many CIs are in red...

**Comment by keszybz** [comment]
I dropped the commit for TEST-52-*. I have no idea why it's failing, and it needs a bigger cleanup anyway.

**Comment by keszybz** [comment]
bionic-i386 timed out in test-path, looks unrelated.

**Pull request merged**
