### PR TITLE
fstab-generator: enable fsck for block device mounts specified in sys…

### PR DESCRIPTION
**Pull request by yuwata**
…temd.mount-extra=

Like we do for root= or so.

Another possible option is adding support of fifth (sixth?) field in systemd.mount-extra=. But that may be overkill, hence let's do that later if someone request that.

Fixes fsck part of issue #28541.

### CODE REVIEW

**Comment by yuwata** [comment]
@bmr-cymru @drckeefe Could you test this?
I hope the following should work fine.
```
root=/dev/fedora/root-snap rw rd.lvm.lv=fedora/root-snap fstab=no systemd.mount-extra=/dev/vda2:/boot:ext4:defaults systemd.mount-extra=/dev/fedora/var-snap:/var:ext4:defaults systemd.mount-extra=/dev/fedora/home-snap:/home:ext4:defaults
```
The difference from https://github.com/systemd/systemd/pull/28518#issuecomment-1652228998 is 
- ro -> rw
- systemd.mount-extra= for "/" is dropped (strictly speaking, it is not necessary to drop, as it should be ignored anyway when you specify `root=`, but shows unwanted error message).

**Comment by yuwata** [comment]
@bluca I set v254 milestone, but feel free to drop it. I think we can backport the patch after the release. I do not want to delay the release because of this PR.

**Review by keszybz — APPROVED** [review]
LGTM.

**Comment by bmr-cymru** [comment]
> @bmr-cymru @drckeefe Could you test this? I hope the following should work fine.
> ```
> root=/dev/fedora/root-snap rw rd.lvm.lv=fedora/root-snap fstab=no systemd.mount-extra=/dev/vda2:/boot:ext4:defaults systemd.mount-extra=/dev/fedora/var-snap:/var:ext4:defaults systemd.mount-extra=/dev/fedora/home-snap:/home:ext4:defaults
> ```

This is working well for me with yesterday's build, thanks! I will pull the fsck change for systemd.mount-extra into my build and test that next.

**Comment by bmr-cymru** [comment]
Testing with the patch in this PR and `systemd.mount-extra=/dev/fedora/root-snap:/` works and I see the fsck before the sysroot mount:

```
Jul 28 14:27:26 fedora systemd[1]: Starting systemd-fsck-root.service - File System Check on /dev/fedora/root-snap...
Jul 28 14:27:26 fedora systemd-fsck[522]: /dev/mapper/fedora-root--snap: clean, 38533/589824 files, 349436/2359296 blocks
Jul 28 14:27:26 fedora systemd[1]: Finished systemd-fsck-root.service - File System Check on /dev/fedora/root-snap.
Jul 28 14:27:26 fedora systemd[1]: Mounting sysroot.mount - /sysroot...
Jul 28 14:27:26 fedora kernel: EXT4-fs (dm-3): mounted filesystem 9e2f7c99-9fa7-4dce-9c8f-f54b901a7948 r/w with ordered data mode. Quota mode: none.
Jul 28 14:27:26 fedora systemd[1]: Mounted sysroot.mount - /sysroot.
```

**Pull request merged**
