### PR TITLE
  meson: use partial_dependency() to get include directory

### PR DESCRIPTION
**Pull request by kanavin**
Getting the variable directly from pkg-config (without
adding the sysroot prefix) is prone to host contamination
when building in sysroots as the compiler starts looking for the
headers on the host in addition to the sysroot.

### CODE REVIEW

**Comment by kanavin** [comment]
> Now it will break if some -I flags are added. We use pkg-config everywhere for a reason. This really sounds like a problem in your build system. pkg-config supports both redefining the prefix and passing a sysroot, so it sounds like if you are using it manually you should do that?

Was this addressed to me or to systemd maintainers? Yes, systemd's meson.build has a problem - it takes a variable directly from pg-config without prefixing it with the sysroot. But in this case, it's just the standard /usr/include (or whatever is passed to gcc via --sysroot option), gcc ought to look there without explicitly being told to, and the code is simply unnecessary.

**Comment by kanavin** [comment]
> The original patch was added because opensuse does **not** install the file in the default search path: http://rpm.pbone.net/info_idpl_54482653_distro_opensuseleap15_com_libxkbcommon-devel-0.8.3-lp151.3.1.x86_64.rpm.html:
> 
> ```
> Content of RPM :
> ...
> /usr/include/libxkbcommon/xkbcommon/xkbcommon.h
> ...
> ```
> 
> The problem is that we want to get the include path but not the lib.
> 
> It seems that https://mesonbuild.com/Reference-manual_returned_dep.html#deppartial_dependency is what we're looking for.
> 
> @kanavin: any chance you could rework the patch to use partial_dependency() ?

Wait, this really starts to look like a suse-specific workaround, that I think needs to be patched via suse .spec. Why is it placing headers somewhere else?

**Comment by kanavin** [comment]
> 
> There is nothing wrong with meson, and there is nothing wrong with opensuse, and there is nothing wrong the pkgconfig. The only issue is with our meson script which only worked as long as the headers were in the default include path. Since they are not always there, we want to add the include path specified by pkgconf.

This does not explain why it should be fixed for this particular usage of pkg-conf, but left as-is for every other usage of pkg-conf, where the problem of headers not in the default path is exactly same.  Which means meson does have a problem.

**Comment by kanavin** [comment]
> We want the include directories but not the libraries because the library is dlopen()ed at runtime. Hence it shouldn't be linked to. But we still need the headers to compile.
> 
> There is nothing wrong with meson, and there is nothing wrong with opensuse, and there is nothing wrong the pkgconfig. The only issue is with our meson script which only worked as long as the headers were in the default include path. Since they are not always there, we want to add the include path specified by pkgconf.

Let me try partial_dependency() then. I'm still unsure why full dependency() doesn't work for headers in a custom location though - shouldn't it?

**Comment by keszybz** [comment]
When use do
```
x = dependency('libx')
y = exe(dependencies: x)
```
then `y` is linked to libx. We do not want this.
Thus we want to do
```
xh = x.partial_dependency(includes: True)
```
to get just the include dirs and not the link args.

**Comment by kanavin** [comment]
> When use do
> 
> ```
> x = dependency('libx')
> y = exe(dependencies: x)
> ```
> 
> then `y` is linked to libx. We do not want this. Thus we want to do
> 
> ```
> xh = x.partial_dependency(includes: True)
> ```
> 
> to get just the include dirs and not the link args.

Now I get it, thanks. I didn't realize libxkbcommon was not actually added as a dependency, and only checked for existence. I adjusted the patch and the PR, please take a look.

**Comment by aafeijoo-suse** [comment]
> Looks reasonable. If it actually works as expected, than it's good to go.
> 
> @aafeijoo-suse could you please check that this also works for you.

Yes, this patch also adds the correct header path and compiles without error.

**Pull request merged**
