### PR TITLE
travis: show the output of the tests run by the ASan & UBSan job

### PR DESCRIPTION
**Pull request by evverx**
In theory, it should help to find the cause of https://github.com/systemd/systemd/issues/10696.

### CODE REVIEW

**Comment by evverx** [comment]
Judging by https://travis-ci.org/systemd/systemd/jobs/452745411, the culprit seems to be `test-execute`.

**Comment by evverx** [comment]
I think it's just a variation of https://github.com/systemd/systemd/issues/10337 but I haven't managed to capture the output of `test-execute` when it's stuck. Currently I'm just restarting the job and waiting for it to fail.

**Comment by mrc0mmand** [comment]
@evverx I ran it in a loop and finally managed to hit it https://api.travis-ci.org/v3/job/452777016/log.txt (https://github.com/mrc0mmand/systemd/commit/17ec6d6aa2cfe64c4734a9107aaf266b39d75ddd)

**Comment by evverx** [comment]
And it doesn't seem to explain why something was stuck for more than 10 minutes in https://travis-ci.org/systemd/systemd/jobs/452702153. I guess there are at least two different issues here both of which are luckily hard to reproduce :-)

**Comment by evverx** [comment]
I don't think it makes much sense to keep this PR open.

**Pull request closed without merging**
