### PR TITLE
repart: Support setting verity block sizes from environment

### LINKED ISSUE #28223: systemd-repart: Support changing verity block and hash sizes using an environment variable
### Component

systemd-repart

### Is your feature request related to a problem? Please describe

Currently the block size and hash size for a generated verity partition is set based on the `--sector-size` argument or the detected sector size. A larger block size is useful to reduce the total size of the generated verity partition. For a 15GB partition this can drop the size from around 1GB using 512 byte sectors to ~115MB using 4K byte sectors.

### Describe the solution you'd like

An environment variable `SYSTEMD_REPART_VERITY_SECTOR_SIZE` or something similar that overrides the block and hash sizes. Perhaps two variables makes sense and whatever name is decided on really doesn't matter that much.

### Describe alternatives you've considered

Changing the sector size for the entire generated image. This does work but FAT 32 images do not like 4K sectors. There's also a bug currently (#28225) when using a larger sector size and deferred partitions.

### The systemd version you checked that didn't have the feature you are asking for

commit 6cc0fd0044f3a6247f80388b653fc1b09784805d (253)

### PR DESCRIPTION
**Pull request by mcassaniti**
This change supports setting the verity hash and data block sizes from the environment variable `SYSTEMD_REPART_VERITY_BLOCK_SIZE`. This fixes #28223.

My C abilities aren't the best so my (mis)use of pointers is likely showing. At least the code seems to do what I intended it to do.

Before someone asks, there is value in having the verity block size and the sector size(s) be different. A generated image could have a sector size of 512 while the verity block size is 4096. The verity partition would be much smaller as a result.

### CODE REVIEW

**Comment by mcassaniti** [comment]
Can I suggest whoever reviews this PR to consider if the default verity block size should be 4096 if a value is not specified for the sector size at all? This would create much smaller default verity partitions.

**Comment by DaanDeMeyer** [comment]
I realize this woud be much more work but ly idea was to add new config sections for verity, luks and all the filesystems to allow configuring all the knobs for them. I don't think we should go for the quick solution in this case.

**Comment by mcassaniti** [comment]
So you want to add more options under the `[Partition]` section of repart.d files? Define what you want and I'll see what I can do.

Should we support both?

**Comment by DaanDeMeyer** [comment]
I was thinking we would have [Verity], [Luks], [Btrfs], [XFS], ... and you could configure a bunch of different things under those sections.

**Comment by mcassaniti** [comment]
There's two sides to using those sections. If repart supports global options across all defined partitions then these make sense, otherwise I'd keep things simple.

By global options I mean having an [XFS] section (for example) in the first file found and defining the `mkfs.xfs` options for every encountered XFS file system.

If these sections are defined then it means also defining what those options are for each and every file system which comes as a maintenance cost. I'm hoping it's a small cost. I don't know how many tuning knobs btrfs has for FS creation and I also don't know how many repart should support. It's certainly a bit easier to define only these options below under the current partition section, even if it means some duplication:

* `MkfsAdditionalOptions` with the environment variables taking precedence
* `LogicalSectorSize` for this file system only. Why you'd want to override this per file system I don't know but here it is.
* `VerityBlockSize` and `VerityHashSize`

Any thoughts also on changing the default verity block/hash sizes?

**Comment by DaanDeMeyer** [comment]
I would not do these as global options, but rather per partition options. The issue with `MkfsAdditionalOptions` is that the interface just plain sucks. You don't have to worry about that though, we can start by just adding a `Verity` section with a few verity options.

**Comment by mcassaniti** [comment]
Continuing this in #28790 as requested above.

**Pull request closed without merging**
