### PR TITLE
TEST-58-REPART: Set zlib as compression algorithm for erofs

### PR DESCRIPTION
**Pull request by daandemeyer**
Let's see if this helps with the flakyness

### CODE REVIEW

**Comment by hsiangkao** [comment]
hi @DaanDeMeyer, is there something wrong with the original lz4hc?

**Comment by DaanDeMeyer** [comment]
> hi @DaanDeMeyer, is there something wrong with the original lz4hc?

It times out every so often

**Comment by hsiangkao** [comment]
> > hi @DaanDeMeyer, is there something wrong with the original lz4hc?
> 
> It times out every so often

Could you share some report links?

**Comment by hsiangkao** [comment]
https://github.com/systemd/systemd/actions/runs/11112926354/job/30876080600
I found one, but it seems it was tested in a QEMU environment, which kernel in the QEMU is using?
And I don't find detailed info of the QEMU inside, not quite sure what happened.

**Comment by hsiangkao** [comment]
No need to switch to `lzma` or other algorithms though.
If it was stuck in the mkfs process and erofs-utils version is 1.8.1, I think it's the regression I mentioned out of multi-threaded mkfs anyway.

**Pull request closed without merging**
