### PR TITLE
Add a fuzzer for sd-ndisc and a reproducer for an infinite loop in ndisc_handle_datagram

### PR DESCRIPTION
**Pull request by evverx**
I added the "dont-merge" label because the infinite loop should be fixed before the PR is merged. Otherwise, the test will start to fail. Alternatively, we could just merge the fuzzer and then wait for ClusterFuzz to open an issue as usual.

### CODE REVIEW

**Comment by evverx** [comment]
Ubuntu CI is green too. @xnox could you add `-Dslow-tests=true` to `debian/rules` so that it would be able to catch regressions?

It's actually a bummer the only CI where the regressions tests are run is the one with the oldest version of `ASan`.

**Comment by yuwata** [comment]
I've pushed a fix for the infinite loop. @evverx Thank you for implementing the new fuzzer. If you or someone confirm the fix, then let's merge this!

**Comment by evverx** [comment]
@yuwata thank you. As far as I can tell, `meson` no longer crashes on Semaphore CI when running the test, which means that the infinite loop is gone. But you've also fixed another infinite loop. Give me an hour. I'll add a test for it.

**Comment by evverx** [comment]
I've just pushed the test. @yuwata I also changed the commit message of your commit a bit so that it would be clear that it actually fixes two different infinite loops.

**Comment by yuwata** [comment]
Thank you for adding another test case!

**Comment by evverx** [comment]
No problem! Thank you for fixing the issues uncovered by the fuzzer. I would have spent much more time staring at backtraces without your help :-)

**Comment by keszybz** [comment]
I tested this locally and @yuwata's patch fixes the infinite loop.

**Comment by evverx** [comment]
I'm going to monitor the status at https://oss-fuzz-build-logs.storage.googleapis.com/index.html. If something goes wrong, I'll fix it next week.

@keszybz what about evergreen Fedora CI? Is it possible to pass `-Dslow-tests=true` to `meson` there?

**Pull request merged**
