### PR TITLE
test: extend the sanity coverage a bit

### PR DESCRIPTION
**Pull request by mrc0mmand**
This is the first of many PRs to attempt to cover missing areas in systemd coverage.

I'm opening this PR a bit earlier than I wanted, as it already found a memory leak when running TEST-26 locally with sanitizers:

```
=================================================================
==1==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7efdae8b9711 in __interceptor_reallocarray (/lib64/libasan.so.8+0xb9711)
    #1 0x7efdabfbdf42 in install_changes_add ../src/shared/install.c:293
    #2 0x7efdabfc48b0 in remove_marked_symlinks_fd ../src/shared/install.c:716
    #3 0x7efdabfc3cd9 in remove_marked_symlinks_fd ../src/shared/install.c:648
    #4 0x7efdabfc500e in remove_marked_symlinks ../src/shared/install.c:765
    #5 0x7efdabfdc930 in do_unit_file_disable ../src/shared/install.c:2808
    #6 0x7efdabfdcc21 in unit_file_disable ../src/shared/install.c:2834
    #7 0x7efdadaddb4b in method_get_unit_file_links ../src/core/dbus-manager.c:2649
    #8 0x7efdac3da4b6 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:406
    #9 0x7efdac3e3dbb in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1319
    #10 0x7efdac3e546a in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1439
    #11 0x7efdac444e5c in process_message ../src/libsystemd/sd-bus/sd-bus.c:2962
    #12 0x7efdac445373 in process_running ../src/libsystemd/sd-bus/sd-bus.c:3004
    #13 0x7efdac4481ac in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3224
    #14 0x7efdac448346 in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3251
    #15 0x7efdac44ba57 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3599
    #16 0x7efdac609e76 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3662
    #17 0x7efdac6126dd in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4246
    #18 0x7efdac6137e8 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4307
    #19 0x7efdadc82051 in manager_loop ../src/core/manager.c:3062
    #20 0x41c2c6 in invoke_main_loop ../src/core/main.c:1916
    #21 0x424ea6 in main ../src/core/main.c:3001
    #22 0x7efdaa82954f in __libc_start_call_main (/lib64/libc.so.6+0x2954f)

Indirect leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7efdae87243b in strdup (/lib64/libasan.so.8+0x7243b)
    #1 0x7efdabfbdff7 in install_changes_add ../src/shared/install.c:299
    #2 0x7efdabfc48b0 in remove_marked_symlinks_fd ../src/shared/install.c:716
    #3 0x7efdabfc3cd9 in remove_marked_symlinks_fd ../src/shared/install.c:648
    #4 0x7efdabfc500e in remove_marked_symlinks ../src/shared/install.c:765
    #5 0x7efdabfdc930 in do_unit_file_disable ../src/shared/install.c:2808
    #6 0x7efdabfdcc21 in unit_file_disable ../src/shared/install.c:2834
    #7 0x7efdadaddb4b in method_get_unit_file_links ../src/core/dbus-manager.c:2649
    #8 0x7efdac3da4b6 in method_callbacks_run ../src/libsystemd/sd-bus/bus-objects.c:406
    #9 0x7efdac3e3dbb in object_find_and_run ../src/libsystemd/sd-bus/bus-objects.c:1319
    #10 0x7efdac3e546a in bus_process_object ../src/libsystemd/sd-bus/bus-objects.c:1439
    #11 0x7efdac444e5c in process_message ../src/libsystemd/sd-bus/sd-bus.c:2962
    #12 0x7efdac445373 in process_running ../src/libsystemd/sd-bus/sd-bus.c:3004
    #13 0x7efdac4481ac in bus_process_internal ../src/libsystemd/sd-bus/sd-bus.c:3224
    #14 0x7efdac448346 in sd_bus_process ../src/libsystemd/sd-bus/sd-bus.c:3251
    #15 0x7efdac44ba57 in io_callback ../src/libsystemd/sd-bus/sd-bus.c:3599
    #16 0x7efdac609e76 in source_dispatch ../src/libsystemd/sd-event/sd-event.c:3662
    #17 0x7efdac6126dd in sd_event_dispatch ../src/libsystemd/sd-event/sd-event.c:4246
    #18 0x7efdac6137e8 in sd_event_run ../src/libsystemd/sd-event/sd-event.c:4307
    #19 0x7efdadc82051 in manager_loop ../src/core/manager.c:3062
    #20 0x41c2c6 in invoke_main_loop ../src/core/main.c:1916
    #21 0x424ea6 in main ../src/core/main.c:3001
    #22 0x7efdaa82954f in __libc_start_call_main (/lib64/libc.so.6+0x2954f)

SUMMARY: AddressSanitizer: 96 byte(s) leaked in 2 allocation(s).
```

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
The failure in CentOS CI (Arch) is unrelated and should be fixed by #25230.

**Review by yuwata — APPROVED** [review]

**Comment by yuwata** [comment]
I expected that the CentOS CI with sanitizer failed with the above memleaks. Why they are not detected??

**Comment by mrc0mmand** [comment]
> I expected that the CentOS CI with sanitizer failed with the above memleaks. Why they are not detected??

TEST-26 is not yet part of the ASan run (as the test list there needs to be manually updated). I'll fix that once this PR is merged.

**Comment by yuwata** [comment]
> > I expected that the CentOS CI with sanitizer failed with the above memleaks. Why they are not detected??
> 
> TEST-26 is not yet part of the ASan run (as the test list there needs to be manually updated). I'll fix that once this PR is merged.

Ah, I see. Thanks.

**Comment by mrc0mmand** [comment]
Looks like Coveralls approves as well:

image

**Pull request merged**
