### PR TITLE
umount: Don't use options from fstab on remount

### PR DESCRIPTION
**Pull request by aszlig**
The `fstab` entry may contain comment/application-specific options, like for example `x-systemd.automount` or `x-initrd.mount`.

With the recent switch to `libmount`, the mount options during remount are now gathered via `mnt_fs_get_options()`, which merges the `fstab` options with the effective options in `mountinfo`.

Unfortunately if one of these application-specific options are set in `fstab`, the remount will fail with `-EINVAL`.

In systemd 238:

> Remounting '/test-x-initrd-mount' read-only in with options 'errors=continue,user_xattr,acl'.

In systemd 239:

> Remounting '/test-x-initrd-mount' read-only in with options 'errors=continue,user_xattr,acl,x-initrd.mount'.
> Failed to remount '/test-x-initrd-mount' read-only: Invalid argument

So instead of using `mnt_fs_get_options()`, we're now using `mnt_fs_get_fs_options()`, which boils down to the same behaviour as we had in systemd 238, mainly reading just the file system specific options
from `mountinfo`.

### CODE REVIEW

**Comment by keszybz** [comment]
Looks reasonable.

**Comment by keszybz** [comment]
Hmm, so `mnt_fs_set_options` uses `mnt_split_optstr` to seperate options to  VFS, FS, and userspace mount options. We don't want the last group, but I think we want the first and the second. Your patch only takes the second. @karelzak?

**Comment by aszlig** [comment]
@keszybz: I thought about that in the first place as well, but the implementation in systemd 238 was using only the [11th field of `mountinfo`](https://github.com/systemd/systemd/blob/738ab7502afb7663d9aacdd73e79025aa7cd0a9b/src/core/umount.c#L102) and it has been so for a long time (since version 231) so I'd assume this has already been widely tested.

**Comment by aszlig** [comment]
@keszybz: Hm, I think however what you're saying sounds more correct. I believe the remount has had the same options so far mainly because of this (from `mount(2)`):

> Since  Linux  3.17,  if none of MS_NOATIME, MS_NODIRATIME, MS_RELATIME, or MS_STRICTATIME is specified in mountflags, then the remount operation preserves the existing values of these flags (rather than defaulting to MS_RELATIME).

**Comment by aszlig** [comment]
When looking at [this comment](https://github.com/systemd/systemd/blob/5664144bd39b116c81d0a67eb82b893a19d20d48/src/core/umount.c#L129-L132) I wonder whether getting the mount options is really necessary here, because when reading the manpage of `mount(2)` more carefully, it shouldn't be necessary:

> The mountflags and data arguments should match the values used in the original mount() call, except for those parameters that are being deliberately changed. Another exception is that **MS_BIND has a different meaning for remount**, and it should be included only if explicitly desired.
> ...
> **Since Linux 2.6.26**, this flag can be used with MS_BIND to modify only the per-mount-point flags. This is particularly useful for setting or clearing the "read-only" flag on a  mount  point  without  changing  the  underlying filesystem.  Specifying mountflags as:
>
>  MS_REMOUNT | MS_BIND | MS_RDONLY
>
> will make access through this mountpoint read-only, **without affecting other mount points**.

I think the last sentence should say `mount options` instead of `mount points`, because when reading the kernel source, it seems to do exactly what we want:

  * [fs/namespace.c:2359 -> do_remount](https://github.com/torvalds/linux/blob/2ad0d52699700a91660a406a4046017a2d7f246a/fs/namespace.c#L2359)
  * [fs/namespace.c -> change_mount_flags](https://github.com/torvalds/linux/blob/2ad0d52699700a91660a406a4046017a2d7f246a/fs/namespace.c#L2291-L2306)

So given that systemd requires [at least kernel 3.13](https://github.com/systemd/systemd/blob/a9e241dcb31f7752fb43299207072442e9bf33d2/README#L35) I think we can safely use `MS_REMOUNT | MS_BIND | MS_READONLY` and remove all the code responsible for reconstructing the options.

@keszybz: What do you think?

**Comment by karelzak** [comment]
The question is how it's expected that the code will work with VFS options like noexec,nosuid, etc. The patch makes these options invisible for the code -- it's strange because for example mount_option_mangle() assumes VFS flags.

It  would be probably better to use mnt_fs_get_fs_options() as well as mnt_fs_get_vfs_options() -- and for example merge all the options to the one string. 

The another more effective possibility is to call  mount_option_mangle() only for VFS options and later append options from mnt_fs_get_fs_options() to the final remount_options. In this case you will not call mount_option_mangle() for FS specific options as this functions does nothing with them.

**Comment by aszlig** [comment]
@karelzak: Did you read my latest comment? Because we should be able to get rid of the flag parsing stuff altogether with `MS_REMOUNT | MS_BIND | MS_RDONLY`.

**Comment by karelzak** [comment]
See kernel do_remount() more carefully. The MS_REMOUNT | MS_BIND operation is not restricted to MS_RDONLY. After change_mout_flags() there is 
```
if (!err) {
		lock_mount_hash();
		mnt_flags |= mnt->mnt.mnt_flags & ~MNT_USER_SETTABLE_MASK;
		mnt->mnt.mnt_flags = mnt_flags;
		touch_mnt_namespace(mnt->mnt_ns);
		unlock_mount_hash();
}
```
So, it updates mnt->mnt.mnt_flags, it means that you can for example do  MS_REMOUNT | MS_BIND |MS_NOSUID. 

(For example the old version of libmount has been restricted to MS_RDONLY in this case, but since https://github.com/karelzak/util-linux/issues/637 it's usable for all VFS flags.)

**Comment by aszlig** [comment]
@karelzak: Ah, you're right:

```cpp
#define MNT_USER_SETTABLE_MASK  (MNT_NOSUID | MNT_NODEV | MNT_NOEXEC \
                 | MNT_NOATIME | MNT_NODIRATIME | MNT_RELATIME \
                 | MNT_READONLY)
```

**Comment by karelzak** [comment]
You can try it easily:
```
# mount /dev/sdc1 /mnt/A
# mount --bind /mnt/A /mnt/B

# strace -e mount mount --bind -oremount,nosuid,noexec /mnt/B
mount("/dev/sdc1", "/mnt/B", 0x55e50f683e50, MS_NOSUID|MS_NOEXEC|MS_REMOUNT|MS_BIND|MS_RELATIME, "stripe=512") = 0
+++ exited with 0 +++

# findmnt /dev/sdc1 -oTARGET,SOURCE,FS-OPTIONS,VFS-OPTIONS
TARGET SOURCE    FS-OPTIONS    VFS-OPTIONS
/mnt/A /dev/sdc1 rw,stripe=512 rw,relatime
/mnt/B /dev/sdc1 rw,stripe=512 rw,nosuid,noexec,relatime

```

**Comment by aszlig** [comment]
@karelzak: Yeah, thanks, already tested this, heading for the `mnt_fs_get_fs_options` + `mnt_fs_get_vfs_options` approach.

**Comment by aszlig** [comment]
@keszybz, @karelzak: Changed accordingly and also ran all NixOS tests.

**Comment by keszybz** [comment]
LGTM.

**Comment by karelzak** [comment]
Looks good to me ;-) 

According to the comment I guess you have tested it with 'ro' VFS node and 'rw' superblock.

**Comment by aszlig** [comment]
@karelzak: No, not that specific case when the VFS options contain `ro` and FS options contain `rw` for example. If that's the case it shouldn't matter much anyway because the worst that could happen in this case is that a file system that's already mounted read-only will again be remounted read-only.

If it's the other way around and the VFS options contain `rw` while the FS options contain `ro`, then the read-only remount is *not* done before unmounting, which might be a problem.

So let's say we want to address this: We have conflicting options here, so which one should prevail? The one in the VFS options or the one in FS options?

Also, I don't think something like that is very common, but I could be wrong. Under which circumstances does this happen?

**Comment by keszybz** [comment]
> We have conflicting options here, so which one should prevail?

IIUC, this shouldn't happen unless the code which divides the options is buggy.

Patch looks good, let's merge.

**Comment by Mic92** [comment]
As this is a regression, it probably make sense to cherry-pick this to https://github.com/systemd/systemd-stable as well, cc @keszybz

**Comment by aszlig** [comment]
@keszybz: I don't think this is needed for version 238, because back then the mount options were read directly off `mountinfo` by systemd. Of course it didn't take into account both FS and VFS options, but it didn't include application-specific options either, so the original bug wasn't there yet.

**Comment by Mic92** [comment]
So there will be no `v239-stable` then?

**Comment by keszybz** [comment]
Ah, right, I forgot that we released v239 already ;). Pushed as https://github.com/systemd/systemd-stable/commit/c38499d476026d999558a7eee9c95ca2fa41e115.

**Pull request merged**
