### PR TITLE
man: document implicit dependency on systemd-journald.socket

### PR DESCRIPTION
**Pull request by arvidjaar**

### CODE REVIEW

**Comment by zonque** [comment]
@arvidjaar ping?

**Comment by arvidjaar** [comment]
@zonque Sorry I am still unclear in what direction to change it.

**Comment by poettering** [comment]
As it turns out this is actually documented pretty explicitly in the "Automatic Dependencies" section of the man page at hand. (Though incorrectly, it talks of "journald.socket", not "systemd-journald.socket", will prep a fix for that)

Closing hence.

**Comment by poettering** [comment]
The promised fixes for the man page are waiting in #3124.

**Pull request closed without merging**
