### PR TITLE
udev: open control and netlink sockets before daemonization

### PR DESCRIPTION
**Pull request by keszybz**
@mbiebl your bisect was super helpful, thanks!
This isn't tested at all.

### CODE REVIEW

**Comment by evverx** [comment]
This pull request **introduces 1 alert** when merging 16c60e4c7c61fa7ad1b8acdc682dabca9976bc5e into 82d9ac23fd5ab2befe2a95187640a8d38799dd64 - [view on LGTM.com](https://lgtm.com/projects/g/systemd/systemd/rev/pr-bd42471fd603ce39db3db6218f56bcc41266ea5c)

**new alerts:**

* 1 for FIXME comment

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by keszybz** [comment]
```
Loading, please wait...
Starting version 240
Begin: Loading essential drivers ... done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... [    1.332012] raid6: sse2x1   gen()  6315 MB/s
[    1.380009] raid6: sse2x1   xor()  5923 MB/s
[    1.428009] raid6: sse2x2   gen() 12590 MB/s
[    1.476007] raid6: sse2x2   xor()  8068 MB/s
[    1.524010] raid6: sse2x4   gen() 13022 MB/s
[    1.572009] raid6: sse2x4   xor()  7331 MB/s
[    1.620007] raid6: avx2x1   gen() 14669 MB/s
[    1.668007] raid6: avx2x1   xor() 10522 MB/s
[    1.716009] raid6: avx2x2   gen() 19649 MB/s
[    1.764009] raid6: avx2x2   xor() 11493 MB/s
[    1.812008] raid6: avx2x4   gen() 19914 MB/s
[    1.860008] raid6: avx2x4   xor() 10260 MB/s
[    1.860628] raid6: using algorithm avx2x4 gen() 19914 MB/s
[    1.861403] raid6: .... xor() 10260 MB/s, rmw enabled
[    1.862103] raid6: using avx2x2 recovery algorithm
[    1.865052] xor: automatically using best checksumming function   avx       
[    1.881244] Btrfs loaded, crc32c=crc32c-intel
Scanning for Btrfs filesystems
done.
[    1.952083] tsc: Refined TSC clocksource calibration: 2395.498 MHz
[    1.952995] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x22879ad4d4f, max_idle_ns: 440795309157 ns
Begin: Waiting for root file system ... Begin: Running /scripts/local-block ... done.
done.
Gave up waiting for root file system device.  Common problems:
 - Boot args (cat /proc/cmdline)
   - Check rootdelay= (did the system wait long enough?)
 - Missing modules (cat /proc/modules; ls /dev)
ALERT!  UUID=e5f48a6d-a4fe-4fce-b02b-f0abd6c1c28b does not exist.  Dropping to a shell!


BusyBox v1.27.2 (Ubuntu 1:1.27.2-2ubuntu3) built-in shell (ash)
Enter 'help' for a list of built-in commands.

(initramfs) [6n
---------------------------------------------------
<VirtSubproc>: failure: Timed out on waiting for ssh connection
autopkgtest [06:19:20]: ERROR: testbed failure: cannot send to testbed: [Errno 32] Broken pipe
```

```
Loading, please wait...
Starting version 240
Begin: Loading essential drivers ... done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... [    4.048045] raid6: mmxx1    gen()  1278 MB/s
[    4.096042] raid6: mmxx2    gen()  2207 MB/s
[    4.144054] raid6: sse1x1   gen()  1117 MB/s
[    4.192049] raid6: sse1x2   gen()  1766 MB/s
[    4.240068] raid6: sse2x1   gen()  1991 MB/s
[    4.288039] raid6: sse2x1   xor()  1070 MB/s
[    4.336025] raid6: sse2x2   gen()  3276 MB/s
[    4.384025] raid6: sse2x2   xor()  2013 MB/s
[    4.385831] raid6: using algorithm sse2x2 gen() 3276 MB/s
[    4.388023] raid6: .... xor() 2013 MB/s, rmw enabled
[    4.390043] raid6: using ssse3x1 recovery algorithm
[    4.406475] xor: automatically using best checksumming function   avx       
[    4.471948] Btrfs loaded, crc32c=crc32c-intel
Scanning for Btrfs filesystems
done.
Begin: Waiting for root file system ... Begin: Running /scripts/local-block ... done.
done.
Gave up waiting for root file system device.  Common problems:
 - Boot args (cat /proc/cmdline)
   - Check rootdelay= (did the system wait long enough?)
 - Missing modules (cat /proc/modules; ls /dev)
ALERT!  UUID=c20645e4-1dd3-43a5-8589-677aae6ee3d1 does not exist.  Dropping to a shell!


BusyBox v1.27.2 (Ubuntu 1:1.27.2-2ubuntu3) built-in shell (ash)
Enter 'help' for a list of built-in commands.

(initramfs) [6n
---------------------------------------------------
<VirtSubproc>: failure: Timed out on waiting for ssh connection
autopkgtest [07:05:13]: ERROR: testbed failure: cannot send to testbed: [Errno 32] Broken pipe
```

This looks pretty bad. But looking at the commits again, they look fine. I'll restart the CI in case it was some temporary issue.

**Comment by mbiebl** [comment]
This seems to break `--daemon` completely. After executing `/lib/systemd/systemd-udevd --daemon` there is no running `systemd-udevd` process afterwards.

**Comment by mbiebl** [comment]
output of `strace -s500 -f /lib/systemd/systemd-daemon --daemon`  attached.
[strace.txt](https://github.com/systemd/systemd/files/2742454/strace.txt)

**Comment by yuwata** [comment]
Ouch. https://github.com/systemd/systemd/blob/a685c049c04036e12371a05702f5570d74340d55/src/libsystemd/sd-event/sd-event.c#L345-L346

So, we need to initialize sockets before `fork()`, but set `sd_event` after `fork()`.

**Comment by keszybz** [comment]
Thanks!

**Pull request closed without merging**
