### PR TITLE
core: support SystemCallErrorNumber=0

### LINKED ISSUE #7169: Support ignoring specific system calls using SystemCallFilter.
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 235

### Used distribution

> Debian

### Description

It would be quite useful if one could return a zero/ignore `errno` on specific syscalls using the `SystemCallFilter` framework. A usecase is to block out sync/fsync calls for specific processes that call them unnecessarily (in a specific context). It looks quite feasible by using `SCMP_ACT_ERRNO` in libseccomp.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #7169.

### CODE REVIEW

**Comment by tixxdz** [comment]
Thanks @yuwata  for the patch

However before, as I see it your error overwriting will apply to all syscalls that are in the filter ? the original reporter has only a use case for sync to disc cases. In a long term I am not sure if this as it is will be really used or it may add some confusions... hmm  more importantly it may return "0" for getuid() calls or whatever other call that deal with privileges, and this can be dangerous, so we should really avoid this playing such games.

Something like SystemCallFilterOverwriteError="sync:0" as an example can solve this case, it may apply on specific system calls. Since seccomp rules are stacked, this should be documented as a first rule to use before other SystemCallFilter= argument and then maybe it needs a better naming too...

This needs more feedback, thanks!

**Comment by yuwata** [comment]
@tixxdz Thank you for your comment.
> Something like SystemCallFilterOverwriteError="sync:0" as an example can solve this case,

It sounds good for me. I'll propose it later if possible.

**Comment by yuwata** [comment]
Anyway, rebased.

**Comment by tixxdz** [comment]
@yuwata after some thoughts, returning blindly 0 is really unsafe , and maybe it is not even systemd business to fix this unless abstracted in a safe way... 

Thanks!

**Comment by yuwata** [comment]
@tixxdz OK. I added the dont-merge label to this PR. Thanks.

**Comment by keszybz** [comment]
This will not apply anymore after #7178 is merged. But before updating, let's first decide if we want this.

I'm fine with adding this functionality. I think a fat warning in the man page would be in order, but apart from that I don't see this somehow fundamentally different than making syscalls return e.g. ENOSYS. Caveat emptor, etc.

**Comment by tixxdz** [comment]
@keszybz I guess I argued since this will apply to *all* syscalls and groups which is not ok. Returning 0 kind of defeat seccomp and expose us... expanding to support other non zero numbers as in https://github.com/systemd/systemd/pull/7178  can be acceptable, however not 0 and not for all syscalls, specifying the filter with "syscallname:errorcode" per field as in that PR is already enough for all these cases IMO, and we should be consistent, it will make it easy later when we change introduce new code to not think about all these exotic scenarios...

**Comment by yuwata** [comment]
Now #7178 is merged. In that PR, `SystemCallErrorNumber=0` is prohibited, as @tixxdz worried to set 0. Moreover, the original request by @tfheen is just set 0 to sync/fsync, and there are no requests to set 0 to all listed syscalls. So, lets's close this. Thank you all for the discussion.

**Pull request closed without merging**
