### PR TITLE
Third DNSSEC patch series

### PR DESCRIPTION
**Pull request by poettering**
This adds code to acquire the necessary DNSKEY/DS RRs to validate RRsets, among other stuff. Proof-of-non-existance and Proof-of-unsigned-zones is not implemented yet.

### CODE REVIEW

**Comment by teg** [comment]
Had some minor inline comments, but overall looks good.

**Comment by poettering** [comment]
OK, @teg, fixed the things you found, rebased on @zonque's most recent work, added two more patches and force pushed. Please have a look and merge!

**Comment by poettering** [comment]
oh shit, i fucked this one up... "81" wasn't supposed to be there...

**Comment by poettering** [comment]
OK, this time all should be good. Please review+merge!

**Pull request merged**
