### PR TITLE
analyze: fix build on non-seccomp builds

### PR DESCRIPTION
**Pull request by poettering**
Follow-up for #22585

See: https://github.com/systemd/systemd/pull/22585#issuecomment-1047658990

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
We really need some coverage of this combination in the CI

**Comment by evverx** [comment]
@mrc0mmand https://github.com/systemd/systemd/pull/22591 :-)

**Comment by mrc0mmand** [comment]
> @mrc0mmand #22591 :-)

Nice! That was quick :-)

**Comment by poettering** [comment]
The three CI issues appear unrelated. Merging.

**Pull request merged**
