### PR TITLE
allow transient mounts and automounts

### PR DESCRIPTION
**Pull request by michaelolbrich**

### CODE REVIEW

**Comment by keszybz** [comment]
I'll set the needs-rework flag, I think the missing drop-in-writing needs adding. Also, we need more commit messages... it'll make review easier.

**Comment by michaelolbrich** [comment]
I've pushed a new version of the patches. And now the old comments seem to be gone :-/
There are a few changes:
- With the latest changes for transient unit, using unit_load_fragment_and_dropin_optional() is ok now, so I dropped that hunk.
- Writing drop-ins for mount units, makes the rest just work, so patch 2 is optional now, but imho still a good cleanup

**Comment by michaelolbrich** [comment]
Can someone look at this please? I've made the requested changes and the test failures are imho unrelated.

**Comment by poettering** [comment]
sorry this took so long, patch looks good!

**Comment by poettering** [comment]
@michaelolbrich i prepped a small client-side tool for this now in #3909. Please have a look!

**Pull request merged**
