### PR TITLE
resolve: fixes two issues

### LINKED ISSUE #22477: Assertion 'q->bus_request' failed at src/resolve/resolved-bus.c:65, function reply_query_state()
**systemd version the issue has been seen with**
```
$ git describe
v250-840-g4ba5594390
```

```sh
# resolvectl service _xmpp-server._tcp gmail.com
Resolve call failed: DNSSEC validation failed: failed-auxiliary

# resolvectl revert eth0

# resolvectl
Global
           Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=allow-downgrade/supported
    resolv.conf mode: stub
Fallback DNS Servers: 1.1.1.1#cloudflare-dns.com 8.8.8.8#dns.google 1.0.0.1#cloudflare-dns.com 8.8.4.4#dns.google 2606:4700:4700::1111#cloudflare-dns.com 2001:4860:4860::8888#dns.google
                      2606:4700:4700::1001#cloudflare-dns.com 2001:4860:4860::8844#dns.google

Link 2 (eth0)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=allow-downgrade/supported

# resolvectl service _xmpp-server._tcp gmail.com
```

```sh
Added positive unauthenticated non-confidential cache entry for _xmpp-server._tcp.gmail.com IN SRV 900s on eth0/INET/1.1.1.1
Added positive unauthenticated non-confidential cache entry for _xmpp-server._tcp.gmail.com IN SRV 900s on eth0/INET/1.1.1.1
Added positive unauthenticated non-confidential cache entry for _xmpp-server._tcp.gmail.com IN SRV 900s on eth0/INET/1.1.1.1
Added positive unauthenticated non-confidential cache entry for _xmpp-server._tcp.gmail.com IN SRV 900s on eth0/INET/1.1.1.1
Added positive unauthenticated non-confidential cache entry for _xmpp-server._tcp.gmail.com IN SRV 900s on eth0/INET/1.1.1.1
Regular transaction 35985 for <_xmpp-server._tcp.gmail.com IN SRV> on scope dns on */* now complete with <success> from network (unsigned; non-confidential).
Freeing transaction 62013.
Looking up RR for alt1.xmpp-server.l.google.com IN A.
Looking up RR for alt1.xmpp-server.l.google.com IN AAAA.
Looking up RR for xmpp-server.l.google.com IN A.
Looking up RR for xmpp-server.l.google.com IN AAAA.
Looking up RR for alt3.xmpp-server.l.google.com IN A.
Looking up RR for alt3.xmpp-server.l.google.com IN AAAA.
Looking up RR for alt2.xmpp-server.l.google.com IN A.
Looking up RR for alt2.xmpp-server.l.google.com IN AAAA.
Looking up RR for alt4.xmpp-server.l.google.com IN A.
Looking up RR for alt4.xmpp-server.l.google.com IN AAAA.
Assertion 'q->bus_request' failed at src/resolve/resolved-bus.c:65, function reply_query_state(). Aborting.

Program received signal SIGABRT, Aborted.
0x00007ffff47ff84c in __pthread_kill_implementation () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install audit-libs-3.0.7-1.fc35.x86_64 glibc-2.34-11.fc35.x86_64 gmp-6.2.0-7.fc35.x86_64 gnutls-3.7.2-2.fc35.x86_64 iptables-legacy-libs-1.8.7-13.fc35.x86_64 kmod-libs-29-4.fc35.x86_64 libacl-2.3.1-2.fc35.x86_64 libasan-11.2.1-7.fc35.x86_64 libattr-2.5.1-3.fc35.x86_64 libblkid-2.37.2-1.fc35.x86_64 libcap-2.48-3.fc35.x86_64 libcap-ng-0.8.2-8.fc35.x86_64 libeconf-0.4.0-2.fc35.x86_64 libffi-3.1-29.fc35.x86_64 libgcc-11.2.1-7.fc35.x86_64 libgcrypt-1.9.4-1.fc35.x86_64 libgpg-error-1.43-1.fc35.x86_64 libibverbs-38.1-2.fc35.x86_64 libidn2-2.3.2-3.fc35.x86_64 libmount-2.37.2-1.fc35.x86_64 libseccomp-2.5.3-1.fc35.x86_64 libselinux-3.3-1.fc35.x86_64 libstdc++-11.2.1-7.fc35.x86_64 libtasn1-4.16.0-6.fc35.x86_64 libubsan-11.2.1-7.fc35.x86_64 libunistring-0.9.10-14.fc35.x86_64 libxcrypt-4.4.27-2.fc35.x86_64 libzstd-1.5.2-1.fc35.x86_64 lz4-libs-1.9.3-3.fc35.x86_64 openssl-libs-1.1.1l-2.fc35.x86_64 pcre2-10.39-1.fc35.x86_64 sssd-client-2.6.1-1.fc35.x86_64 xz-libs-5.2.5-7.fc35.x86_64 zlib-1.2.11-30.fc35.x86_64
(gdb) bt
#0  0x00007ffff47ff84c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff47b26a6 in raise () from /lib64/libc.so.6
#2  0x00007ffff479c7d3 in abort () from /lib64/libc.so.6
#3  0x00007ffff64e9951 in log_assert_failed (text=0x5bcb60 "q->bus_request", file=0x5bc903 "src/resolve/resolved-bus.c", line=65, func=0x5c1f40 <__PRETTY_FUNCTION__.61> "reply_query_state")
    at ../src/basic/log.c:866
#4  0x000000000040e0fe in reply_query_state (q=0x61200008bfc0) at ../src/resolve/resolved-bus.c:65
#5  0x0000000000419ae3 in resolve_service_all_complete (query=0x612000084340) at ../src/resolve/resolved-bus.c:1014
#6  0x000000000041ce70 in bus_method_resolve_service_complete (query=0x612000084340) at ../src/resolve/resolved-bus.c:1237
#7  0x000000000044483e in dns_query_complete (q=0x612000084340, state=DNS_TRANSACTION_SUCCESS) at ../src/resolve/resolved-dns-query.c:591
#8  0x0000000000449f2d in dns_query_accept (q=0x612000084340, c=0x6070000303e0) at ../src/resolve/resolved-dns-query.c:950
#9  0x000000000044a2e7 in dns_query_ready (q=0x612000084340) at ../src/resolve/resolved-dns-query.c:983
#10 0x000000000043f6a8 in dns_query_candidate_notify (c=0x6070000303e0) at ../src/resolve/resolved-dns-query.c:339
#11 0x00000000004a9c5d in dns_transaction_complete (t=0x612000084640, state=DNS_TRANSACTION_SUCCESS) at ../src/resolve/resolved-dns-transaction.c:437
#12 0x00000000004b1c01 in dns_transaction_process_dnssec (t=0x612000084640) at ../src/resolve/resolved-dns-transaction.c:979
#13 0x00000000004c3f51 in dns_transaction_notify (t=0x612000084640, source=0x612000085540) at ../src/resolve/resolved-dns-transaction.c:2632
#14 0x00000000004aa621 in dns_transaction_complete (t=0x612000085540, state=DNS_TRANSACTION_SUCCESS) at ../src/resolve/resolved-dns-transaction.c:447
#15 0x00000000004b1c01 in dns_transaction_process_dnssec (t=0x612000085540) at ../src/resolve/resolved-dns-transaction.c:979
#16 0x00000000004c3f51 in dns_transaction_notify (t=0x612000085540, source=0x61200008ac40) at ../src/resolve/resolved-dns-transaction.c:2632
#17 0x00000000004aa621 in dns_transaction_complete (t=0x61200008ac40, state=DNS_TRANSACTION_SUCCESS) at ../src/resolve/resolved-dns-transaction.c:447
#18 0x00000000004b1c01 in dns_transaction_process_dnssec (t=0x61200008ac40) at ../src/resolve/resolved-dns-transaction.c:979
#19 0x00000000004c3f51 in dns_transaction_notify (t=0x61200008ac40, source=0x61200008b0c0) at ../src/resolve/resolved-dns-transaction.c:2632
#20 0x00000000004aa621 in dns_transaction_complete (t=0x61200008b0c0, state=DNS_TRANSACTION_SUCCESS) at ../src/resolve/resolved-dns-transaction.c:447
#21 0x00000000004b1c01 in dns_transaction_process_dnssec (t=0x61200008b0c0) at ../src/resolve/resolved-dns-transaction.c:979
#22 0x00000000004c3f51 in dns_transaction_notify (t=0x61200008b0c0, source=0x61200008b540) at ../src/resolve/resolved-dns-transaction.c:2632
#23 0x00000000004aa621 in dns_transaction_complete (t=0x61200008b540, state=DNS_TRANSACTION_SUCCESS) at ../src/resolve/resolved-dns-transaction.c:447
#24 0x00000000004b1c01 in dns_transaction_process_dnssec (t=0x61200008b540) at ../src/resolve/resolved-dns-transaction.c:979
#25 0x00000000004c3f51 in dns_transaction_notify (t=0x61200008b540, source=0x61200008b9c0) at ../src/resolve/resolved-dns-transaction.c:2632
#26 0x00000000004aa621 in dns_transaction_complete (t=0x61200008b9c0, state=DNS_TRANSACTION_SUCCESS) at ../src/resolve/resolved-dns-transaction.c:447
#27 0x00000000004b1c01 in dns_transaction_process_dnssec (t=0x61200008b9c0) at ../src/resolve/resolved-dns-transaction.c:979
#28 0x00000000004b5aae in dns_transaction_process_reply (t=0x61200008b9c0, p=0x62100005f100, encrypted=false) at ../src/resolve/resolved-dns-transaction.c:1405
#29 0x00000000004b6594 in on_dns_packet (s=0x61200008bb40, fd=22, revents=1, userdata=0x61200008b9c0) at ../src/resolve/resolved-dns-transaction.c:1462
#30 0x00007ffff689be69 in source_dispatch (s=0x61200008bb40) at ../src/libsystemd/sd-event/sd-event.c:3598
#31 0x00007ffff68a4683 in sd_event_dispatch (e=0x617000091f00) at ../src/libsystemd/sd-event/sd-event.c:4183
#32 0x00007ffff68a57f8 in sd_event_run (e=0x617000091f00, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:4244
#33 0x00007ffff68a5b79 in sd_event_loop (e=0x617000091f00) at ../src/libsystemd/sd-event/sd-event.c:4265
#34 0x000000000054fa0e in run (argc=1, argv=0x7fffffffe608) at ../src/resolve/resolved.c:92
#35 0x000000000054fca8 in main (argc=1, argv=0x7fffffffe608) at ../src/resolve/resolved.c:99
```

### LINKED ISSUE #22480: Assertion 'IN_SET(family, AF_INET, AF_INET6)' failed at src/basic/in-addr-util.h:114
**systemd version the issue has been seen with**
```sh
$ git describe
v250-842-ga38f3ceeda
```

```sh
$ printf '
{
  "method": "io.systemd.Resolve.ResolveAddress",
  "parameters": {
    "address": [
      127,
      0,
      0,
      1
    ],
    "flags": 0,
    "ifindex": 1000000,
    "family": 0
  }
}\0\0' | nc -U /run/systemd/resolve/io.systemd.Resolve
```

```sh
varlink: New incoming connection.
varlink: Connections of user 1000: 0 (of 576 max)
varlink-21: Setting state idle-server
varlink-21: New incoming message: {"method":"io.systemd.Resolve.ResolveAddress","parameters":{"address":[127,0,0,1],"flags":0,"ifindex":1000000,"family":0}}
varlink-21: Changing state idle-server → processing-method
Assertion 'IN_SET(family, AF_INET, AF_INET6)' failed at src/basic/in-addr-util.h:114, function FAMILY_ADDRESS_SIZE(). Aborting.

Program received signal SIGABRT, Aborted.
0x00007ffff468088c in __pthread_kill_implementation () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install audit-libs-3.0.7-1.fc35.x86_64 glibc-2.34-25.fc35.x86_64 iptables-legacy-libs-1.8.7-13.fc35.x86_64 kmod-libs-29-4.fc35.x86_64 libacl-2.3.1-2.fc35.x86_64 libasan-11.2.1-7.fc35.x86_64 libattr-2.5.1-3.fc35.x86_64 libblkid-2.37.3-1.fc35.x86_64 libcap-2.48-3.fc35.x86_64 libcap-ng-0.8.2-8.fc35.x86_64 libeconf-0.4.0-2.fc35.x86_64 libffi-3.1-29.fc35.x86_64 libgcc-11.2.1-7.fc35.x86_64 libgcrypt-1.9.4-1.fc35.x86_64 libgpg-error-1.43-1.fc35.x86_64 libibverbs-38.1-2.fc35.x86_64 libmount-2.37.3-1.fc35.x86_64 libnl3-3.5.0-8.fc35.x86_64 libseccomp-2.5.3-1.fc35.x86_64 libselinux-3.3-1.fc35.x86_64 libstdc++-11.2.1-7.fc35.x86_64 libubsan-11.2.1-7.fc35.x86_64 libxcrypt-4.4.28-1.fc35.x86_64 libzstd-1.5.2-1.fc35.x86_64 lz4-libs-1.9.3-3.fc35.x86_64 openssl-libs-1.1.1l-2.fc35.x86_64 pcre2-10.39-1.fc35.x86_64 xz-libs-5.2.5-7.fc35.x86_64 zlib-1.2.11-30.fc35.x86_64
(gdb) bt
#0  0x00007ffff468088c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff46336a6 in raise () from /lib64/libc.so.6
#2  0x00007ffff461d7d3 in abort () from /lib64/libc.so.6
#3  0x00007ffff64e6951 in log_assert_failed (text=0x62c140 "IN_SET(family, AF_INET, AF_INET6)", file=0x62c103 "src/basic/in-addr-util.h", line=114,
    func=0x62d840 <__PRETTY_FUNCTION__.24> "FAMILY_ADDRESS_SIZE") at ../src/basic/log.c:866
#4  0x0000000000543668 in FAMILY_ADDRESS_SIZE (family=0) at ../src/basic/in-addr-util.h:114
#5  0x0000000000549c71 in vl_method_resolve_address (link=0x611000039e80, parameters=0x61100003a2e0, flags=0, userdata=0x0) at ../src/resolve/resolved-varlink.c:490
#6  0x00007ffff6400119 in varlink_dispatch_method (v=0x611000039e80) at ../src/shared/varlink.c:872
#7  0x00007ffff6400af1 in varlink_process (v=0x611000039e80) at ../src/shared/varlink.c:947
#8  0x00007ffff640e00a in defer_callback (s=0x61200001b940, userdata=0x611000039e80) at ../src/shared/varlink.c:1862
#9  0x00007ffff6899788 in source_dispatch (s=0x61200001b940) at ../src/libsystemd/sd-event/sd-event.c:3630
#10 0x00007ffff68a169b in sd_event_dispatch (e=0x617000007080) at ../src/libsystemd/sd-event/sd-event.c:4183
#11 0x00007ffff68a2810 in sd_event_run (e=0x617000007080, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:4244
#12 0x00007ffff68a2b91 in sd_event_loop (e=0x617000007080) at ../src/libsystemd/sd-event/sd-event.c:4265
#13 0x0000000000552cc9 in run (argc=1, argv=0x7fffffffe538) at ../src/resolve/resolved.c:92
#14 0x0000000000552f63 in main (argc=1, argv=0x7fffffffe538) at ../src/resolve/resolved.c:99
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #22477.
Fixes #22480.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx

**Comment by evverx** [comment]
@yuwata thanks! Looking at the PR I think both issues should be gone but just to be sure I'll test it and report back.

FWIW judging by https://coveralls.io/builds/46403520/source?filename=src%2Fresolve%2Fresolved-varlink.c it isn't covered by any tests and I think it partly explains why it took me about 2 second to crash resolved with `printf` and `nc`. I think it would make sense to cover that eventually.

**Review by evverx — APPROVED** [review]
LGTM! Thanks. I can confirm that both issues are gone.

@mrc0mmand looks like CentOS CI failed due to some. Could you trigger it once again just in case?

**Comment by poettering** [comment]
Hmm, the first commit doesn't look right, because we'd then reply to the dbus message not just for the main query but for all auxiliary queries too, and thus the querier will get many answers, not just one

**Comment by poettering** [comment]
second commit looks perfect

**Comment by evverx** [comment]
> That code isn't tested either

Just to clarify, `resolve_service_hostname` isn't tested but it seems that https://coveralls.io/builds/46446458/source?filename=src%2Fresolve%2Fresolved-bus.c looks suspiciously red considering that `resolved` is included in the networkd suite. @mrc0mmand could it be that the coverage gets lost somewhere?

**Comment by evverx** [comment]
@mrc0mmand I've just taken a look at that test and it seems the bus is used there to set/get various configuration settings so it could be that that the coverage report is correct and that code isn't actually covered :-(

**Comment by yuwata** [comment]
> Hmm, the first commit doesn't look right, because we'd then reply to the dbus message not just for the main query but for all auxiliary queries too, and thus the querier will get many answers, not just one

Sorry, I cannot understand the comment. Could you elaborate more?
`resolve_service_all_complete()` is called several times, but produces a reply only once when all transaction is finished, and after an reply is sent, `goto finish;` and the main query and sub queries are freed.

Or, @evverx do you observe multiple replies with the first commit?

**Comment by evverx** [comment]
> Or, @evverx do you observe multiple replies with the first commit?

@yuwata I just ran a script poking various event sources and it confirmed that resolved no longer crashed in those particular places. It didn't try to figure out whether it worked correctly :-) I think if you didn't receive multiple replies while testing the patch I don't think I can receive them either.

**Comment by evverx** [comment]
as far as I can see with this patch applied resolved sends one reply:
```sh
$ SYSTEMD_LOG_LEVEL=debug ./build/busctl call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager ResolveService "isssit" 0 "" "_xmpp-server._tcp" "gmail.com" 0 0
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.2967 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveService cookie=2 reply_cookie=0 signature=isssit error-name=n/a error-message=n/a
Got message type=method_return sender=:1.2874 destination=:1.2967 path=n/a interface=n/a member=n/a cookie=439 reply_cookie=2 signature=a(qqqsa(iiay)s)aayssst error-name=n/a error-message=n/a
a(qqqsa(iiay)s)aayssst 5 5 0 5269 "xmpp-server.l.google.com" 1 2 2 4 173 194 222 125 "xmpp-server.l.google.com" 20 0 5269 "alt3.xmpp-server.l.google.com" 1 2 2 4 142 250 142 125 "alt3.xmpp-server.l.google.com" 20 0 5269 "alt2.xmpp-server.l.google.com" 1 2 2 4 173 194 202 125 "alt2.xmpp-server.l.google.com" 20 0 5269 "alt4.xmpp-server.l.google.com" 1 2 2 4 142 250 141 125 "alt4.xmpp-server.l.google.com" 20 0 5269 "alt1.xmpp-server.l.google.com" 1 2 2 4 142 250 157 125 "alt1.xmpp-server.l.google.com" 0 "" "_xmpp-server._tcp" "gmail.com" 1048577
Bus n/a: changing state RUNNING → CLOSED
```
```sh
$ SYSTEMD_LOG_LEVEL=debug ./build/resolvectl service _xmpp-server._tcp gmail.com
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → AUTHENTICATING
Resolving service type _xmpp-server._tcp of gmail.com (family *, interface *).
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.2970 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveService cookie=2 reply_cookie=0 signature=isssit error-name=n/a error-message=n/a
Got message type=method_return sender=:1.2874 destination=:1.2970 path=n/a interface=n/a member=n/a cookie=454 reply_cookie=2 signature=a(qqqsa(iiay)s)aayssst error-name=n/a error-message=n/a
_xmpp-server._tcp/gmail.com: alt2.xmpp-server.l.google.com:5269 [priority=20, weight=0]
                             173.194.202.125                -- link: eth0
                             alt4.xmpp-server.l.google.com:5269 [priority=20, weight=0]
                             142.250.141.125                -- link: eth0
                             xmpp-server.l.google.com:5269 [priority=5, weight=0]
                             173.194.222.125                -- link: eth0
                             alt1.xmpp-server.l.google.com:5269 [priority=20, weight=0]
                             142.250.157.125                -- link: eth0
                             alt3.xmpp-server.l.google.com:5269 [priority=20, weight=0]
                             142.250.142.125                -- link: eth0

-- Information acquired via protocol DNS in 10.6ms.
```
```
Looking up RR for alt3.xmpp-server.l.google.com IN A.
Looking up RR for alt3.xmpp-server.l.google.com IN AAAA.
Positive cache hit for alt3.xmpp-server.l.google.com IN A
Regular transaction 16715 for <alt3.xmpp-server.l.google.com IN A> on scope dns on eth0/* now complete with <success> from cache (unsigned; non-confidential).
NODATA cache hit for alt3.xmpp-server.l.google.com IN AAAA
Regular transaction 7807 for <alt3.xmpp-server.l.google.com IN AAAA> on scope dns on eth0/* now complete with <success> from cache (unsigned; non-confidential).
Freeing transaction 16715.
Freeing transaction 7807.
Sent message type=method_return sender=n/a destination=:1.2970 path=n/a interface=n/a member=n/a cookie=454 reply_cookie=2 signature=a(qqqsa(iiay)s)aayssst error-name=n/a error-message=n/a
```

**Comment by yuwata** [comment]
@poettering Could you re-review this or elaborate the previous your comment more?

**Comment by keszybz** [comment]
The change LGTM, but let's wait for @poettering.

**Comment by poettering** [comment]
I cherry picked the second commit directly into git main. 

So some of the error codepaths might cause us to reply multiple times onto the bus message, I think. i.e. when something fails in reply_query_state(), then we'll go to the "finish" label, and then send a second reply there. Now, I am not sure one can actually trigger that, so your patch is probably OK, but I still think we should be more careful here: given that we issue replies to a D-Bus message at various different places here and when operating on different DnsQuery objects, I think we should be more careful and automatically invalidate the request message object once we sent the first reply, so that we don't send another reply under any circumstances. (Sending two replies is ugly but not a big issue btw, since dbus-daemon tracks method calls and will close method call "windows" when the first reply comes in, and thus drop any further replies).

I prepped a patch doing that now in #22546. I think it's a much safer approach as we can be sure that each request will at max receive one reply, no more, regardless which codepaths we go through.

I hope that approach makes sense?

Given I cherry-picked your second commit now, let's close this PR, if that's OK, and continue #22546 for the other issue.

**Pull request closed without merging**
