### PR TITLE
logs-show: skip non-utf8 name entries

### PR DESCRIPTION
**Pull request by yuwata**
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25353.

### CODE REVIEW

**Comment by keszybz** [comment]
We have a bit of a cognitive dissonance here. The original [journal format description](https://www.freedesktop.org/wiki/Software/systemd/journal-files/) description makes no mention of unicode or really put any constraints on the field name. Nevertheless, our code pretty much assumes printable field names everywhere... Formats like "verbose" will output garbage to the screen, and "json" doesn't even want to print entries with non-unicode strings.

This patch makes such fields "invisible" by omitting them from json output. But I wonder whether we shouldn't go further along this direction and simply assume input field names are always utf8, and always reject non-printable unit names. @poettering, wdyt?

<details>

```console
$ SYSTEMD_LOG_LEVEL=debug SYSTEMD_FUZZ_OUTPUT=1 build/fuzz-journal-remote test/fuzz/fuzz-journal-remote/oss-fuzz-25353
test/fuzz/fuzz-journal-remote/oss-fuzz-25353... Journal effective settings seal=no keyed_hash=yes compress=no compress_threshold_bytes=512B
Fixed min_use=16.0M max_use=391.1M max_size=48.8M min_size=512.0K keep_free=195.5M n_max_files=100
Reserving 333 entries in field hash table.
Reserving 89016 entries in data hash table.
Opened output file /tmp/fuzz-journal-remote.O5Tbzb.journal
Creating source for fd:3 (fuzz-data)
Falling back to sd_event_add_defer for fd:3 (fuzz-data)
Received: �= (binary)
Received empty line, event is ready
Received full event from source@0x9af650 fd:3 (fuzz-data)
EOF reached with source fuzz-data (fd=3)
Closing fuzz-data (fd=3)
Writer ref count 1
Closing journal file /tmp/fuzz-journal-remote.O5Tbzb.journal.
0 active sources remaining
Journal effective settings seal=no keyed_hash=yes compress=no compress_threshold_bytes=8B
File /tmp/fuzz-journal-remote.O5Tbzb.journal added.
/* short */
Skipping message without MESSAGE= field.
/* short-full */
Skipping message without MESSAGE= field.
/* short-iso */
Skipping message without MESSAGE= field.
/* short-iso-precise */
Skipping message without MESSAGE= field.
/* short-precise */
Skipping message without MESSAGE= field.
/* short-monotonic */
Skipping message without MESSAGE= field.
/* short-unix */
Skipping message without MESSAGE= field.
/* verbose */
Source realtime timestamp not found
Thu 1970-01-01 01:00:00.000001 CET [s=e40675544d8c4d809a12ea914fecffdc;i=1;b=00000000000000000000000000000000;m=0;t=1;x=b24936d0fdcc05ca]
    �=[10B blob data]
/* export */
__CURSOR=s=e40675544d8c4d809a12ea914fecffdc;i=1;b=00000000000000000000000000000000;m=0;t=1;x=b24936d0fdcc05ca
__REALTIME_TIMESTAMP=1
__MONOTONIC_TIMESTAMP=0
_BOOT_ID=00000000000000000000000000000000
�

          

/* json */
Failed to allocate JSON name variant: Structure needs cleaning
Assertion 'r >= 0' failed at src/fuzz/fuzz-journal-remote.c:68, function LLVMFuzzerTestOneInput(). Aborting.
```
</details>

**Comment by poettering** [comment]
i'd go further, and reject control characters too.

i.e. probably validate journal field names following the same logic we validate env vars with, i.e. add a `#define journal_field_name_valid(x) env_name_is_valid(x)` or so, and then use that everywhere?

**Comment by poettering** [comment]
Hmm, actually we already have journal_field_valid() for this purpose. We should consider all journal files with fields not matching that name as invalid and generate an error.

i.e. let's make this test stricter, let's use journal_field_valid() and let's make it fatal I think.

**Comment by yuwata** [comment]
@poettering Thank you for the suggestion. Updated. Now, writer and reader both check the field with `journal_filed_valid()`. PTAL.

**Comment by keszybz** [comment]
LGTM.

**Pull request merged**
