### PR TITLE
Use --no-variables in systemd-boot-system-token.service to write random-seed

### PR DESCRIPTION
**Pull request by Sarisan**

### CODE REVIEW

**Comment by bluca** [comment]
> bootctl stucks when you try to write random-seed on device with locked nvram, it results in unstoppable high CPU usage until you kill bootctl

Isn't this a platform-specific issue? Are we really sure it's the right thing to disable it globally? You can have platform-specific overrides with something like:

/usr/lib/systemd/system/systemd-boot-system-token.service.d/disable-efivars.conf
```
[Service]
ExecStart=
ExecStart=bootctl random-seed --no-variables --graceful
```

**Comment by poettering** [comment]
> bootctl stucks when you try to write random-seed on device with locked nvram, it results in unstoppable high CPU usage until you kill bootctl

Hmm? what is "locked nvram"?

This really smells like a bug in the firmware, and should be worked around in the kernel if at all.

**Comment by Sarisan** [comment]
> 

Locked nvram is when it has read-only access rights. It's not possible to write EFI variables directly to nvram, UEFI can only detect them on FAT partition as .efi files.

**Comment by bluca** [comment]
> > 
> 
> Locked nvram is when it has read-only access rights. It's not possible to write EFI variables directly to nvram, UEFI can only detect them on FAT partition as .efi files.

That's a particular, platform-dependent case though. It's not appropriate to change the default for that. As mentioned, you can override locally.

**Comment by Sarisan** [comment]
> > > 
> > 
> > 
> > Locked nvram is when it has read-only access rights. It's not possible to write EFI variables directly to nvram, UEFI can only detect them on FAT partition as .efi files.
> 
> That's a particular, platform-dependent case though. It's not appropriate to change the default for that. As mentioned, you can override locally.

Okay, but why is it default there?
https://github.com/systemd/systemd/blob/017228934833d8618774353dcccbc5ec9f78ce98/units/systemd-boot-update.service#L21

**Comment by bluca** [comment]
> > > > 
> > > 
> > > 
> > > Locked nvram is when it has read-only access rights. It's not possible to write EFI variables directly to nvram, UEFI can only detect them on FAT partition as .efi files.
> > 
> > 
> > That's a particular, platform-dependent case though. It's not appropriate to change the default for that. As mentioned, you can override locally.
> 
> Okay, but why is it default there?
> 
> https://github.com/systemd/systemd/blob/017228934833d8618774353dcccbc5ec9f78ce98/units/systemd-boot-update.service#L21

Because on most systems it is writable

**Comment by medhefgo** [comment]
Does the kernel force efivarfs to be read-only on such systems? If not, it probably should…

But it sounds like bootctl is running in an uncontrolled loop, which shouldn't really happen. You should run the command under debug logging and strace to see what's really going on.

**Comment by poettering** [comment]
> > 
> 
> Locked nvram is when it has read-only access rights. It's not possible to write EFI variables directly to nvram, UEFI can only detect them on FAT partition as .efi files.

But why would bootctl hang on that? Are you saying it is looping on something in userspace? If so thats a bug we should fix. Or is the efivarfs code in kernelspace hanging? If so, then thats something to fix in kernel. The posted PR you posted here doesnt look right either way you look it though

**Comment by poettering** [comment]
Anyway, I'd merge a patch that makes us handle the case where efivarfs returns EROFS gracefully.

**Comment by Sarisan** [comment]
> Does the kernel force efivarfs to be read-only on such systems? If not, it probably should…
> 
> But it sounds like bootctl is running in an uncontrolled loop, which shouldn't really happen. You should run the command under debug logging and strace to see what's really going on.

This is what appears in dmesg when I run `bootctl random-seed --graceful`

```
[  199.672283] ------------[ cut here ]------------
[  199.672292] [Firmware Bug]: Page fault caused by firmware at PA: 0x6792e7f0
[  199.672298] WARNING: CPU: 1 PID: 68 at arch/x86/platform/efi/quirks.c:735 efi_crash_gracefully_on_page_fault+0x49/0xd0
[  199.672310] Modules linked in: rfcomm cmac algif_hash algif_skcipher af_alg bnep vfat fat snd_sof_pci_intel_apl snd_sof_intel_hda_common soundwire_intel soundwire_generic_allocation soundwire_cadence snd_sof_intel_hda snd_sof_pci snd_sof_xtensa_dsp snd_sof soundwire_bus snd_soc_skl snd_soc_hdac_hda snd_hda_ext_core snd_soc_sst_ipc snd_soc_sst_dsp snd_soc_acpi_intel_match snd_soc_acpi snd_hda_codec_hdmi intel_pmc_bxt uvcvideo snd_soc_core intel_telemetry_pltdrv iwlmvm intel_punit_ipc snd_ctl_led intel_telemetry_core snd_compress snd_hda_codec_realtek ac97_bus videobuf2_vmalloc snd_pcm_dmaengine videobuf2_memops snd_hda_codec_generic x86_pkg_temp_thermal mac80211 videobuf2_v4l2 intel_powerclamp ledtrig_audio coretemp videobuf2_common videodev libarc4 kvm_intel snd_hda_intel snd_intel_dspcfg mc snd_intel_sdw_acpi kvm btusb snd_hda_codec i915 btrtl iwlwifi snd_hda_core irqbypass wacom btbcm snd_hwdep mousedev joydev snd_pcm btintel crct10dif_pclmul intel_spi_platform crc32_pclmul intel_spi
[  199.672384]  snd_timer ghash_clmulni_intel bluetooth r8169 spi_nor cfg80211 mei_pxp snd mei_hdcp aesni_intel hp_wmi mtd at24 sparse_keymap soundcore processor_thermal_device_pci_legacy ecdh_generic platform_profile realtek processor_thermal_device ttm crypto_simd rfkill mdio_devres intel_rapl_msr cryptd processor_thermal_rfim libphy intel_gtt wmi_bmof i2c_i801 processor_thermal_mbox rapl mei_me processor_thermal_rapl intel_cstate intel_xhci_usb_role_switch intel_rapl_common mei roles i2c_smbus int340x_thermal_zone psmouse lpc_ich intel_soc_dts_iosf tpm_crb pcspkr wdat_wdt tpm_tis tpm_tis_core mac_hid tpm int3400_thermal acpi_thermal_rel int3406_thermal rng_core wireless_hotkey wmi video dptf_power crypto_user fuse bpf_preload ip_tables x_tables ext4 crc32c_generic crc16 mbcache jbd2 usbhid uas usb_storage serio_raw atkbd libps2 xhci_pci i8042 xhci_pci_renesas crc32c_intel serio
[  199.672465] CPU: 1 PID: 68 Comm: kworker/u8:2 Not tainted 5.16.16-arch1-1 #1 ea44c25f01916b44dd68de6a90ee2f4c9e51dcb4
[  199.672469] Hardware name: HP HP 250 G6 Notebook PC/832E, BIOS F.68 07/22/2021
[  199.672472] Workqueue: efi_rts_wq efi_call_rts
[  199.672478] RIP: 0010:efi_crash_gracefully_on_page_fault+0x49/0xd0
[  199.672483] Code: 48 89 fd e8 79 ab 02 00 48 81 fd ff 0f 00 00 76 08 48 3d b0 58 f2 b7 74 02 5d c3 48 89 ee 48 c7 c7 c8 bd e7 b6 e8 5c da a8 00 <0f> 0b 83 3d 9e f7 49 02 0a 0f 84 7b d5 a8 00 e8 d3 1a 00 00 48 8b
[  199.672485] RSP: 0018:ffffbeb880647b38 EFLAGS: 00010082
[  199.672488] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000027
[  199.672490] RDX: ffff9f0e37ca0728 RSI: 0000000000000001 RDI: ffff9f0e37ca0720
[  199.672491] RBP: 000000006792e7f0 R08: 0000000000000000 R09: ffffbeb880647968
[  199.672493] R10: ffffbeb880647960 R11: ffffffffb76cb9c8 R12: 0000000000000000
[  199.672495] R13: ffffbeb880647bf8 R14: 0000000000000000 R15: 0000000000000000
[  199.672497] FS:  0000000000000000(0000) GS:ffff9f0e37c80000(0000) knlGS:0000000000000000
[  199.672499] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  199.672501] CR2: 000000006792e7f0 CR3: 0000000100202000 CR4: 00000000003506e0
[  199.672503] Call Trace:
[  199.672507]  <TASK>
[  199.672512]  page_fault_oops+0x71/0x2f0
[  199.672518]  exc_page_fault+0x72/0x170
[  199.672524]  asm_exc_page_fault+0x1e/0x30
[  199.672529] RIP: 0010:0xfffffffefb052d58
[  199.672532] Code: cb 48 8b c1 48 83 c4 20 5b c3 48 8b d1 b9 04 00 00 00 e9 b7 ff ff ff cc cc cc 48 83 ec 28 48 8b 05 15 4b 00 00 4c 8d 44 24 40 <ff> 50 40 48 8b 4c 24 40 33 d2 48 85 c0 48 0f 48 ca 48 8b c1 48 83
[  199.672534] RSP: 0018:ffffbeb880647ca0 EFLAGS: 00010086
[  199.672536] RAX: 000000006792e7b0 RBX: 0000000000000002 RCX: 0000000000000004
[  199.672538] RDX: 0000000000000002 RSI: 0000000000000000 RDI: 0000000000000002
[  199.672540] RBP: ffffbeb880647d70 R08: ffffbeb880647ce0 R09: ffffbeb880647dd0
[  199.672541] R10: 0000000000000000 R11: 000000000000000b R12: 0000000000000000
[  199.672543] R13: 0000000000084fb0 R14: ffffbeb880647dd0 R15: ffffbeb880647dd8
[  199.672548]  ? update_load_avg+0x7e/0x610
[  199.672555]  ? __efi_call+0x28/0x30
[  199.672559]  ? efi_call_rts+0x414/0x7f0
[  199.672563]  ? process_one_work+0x1e8/0x3c0
[  199.672567]  ? worker_thread+0x50/0x3b0
[  199.672569]  ? rescuer_thread+0x3a0/0x3a0
[  199.672572]  ? kthread+0x15c/0x180
[  199.672575]  ? set_kthread_struct+0x40/0x40
[  199.672578]  ? ret_from_fork+0x22/0x30
[  199.672584]  </TASK>
[  199.672585] ---[ end trace f3e65c4bac52b4dc ]---
[  199.672596] efi: Froze efi_rts_wq and disabled EFI Runtime Services
[  199.672717] efi: EFI Runtime Services are disabled!
```

**Comment by poettering** [comment]
uh, if you get can trigger a page fault through this, then that's a kernel issue really. i mean, the kernel message says its a firmware issue, but the usual place to work around those are in kernelspace.

i.e. paging faults like that should *not* be triggarable that easily by userspace. And avoiding the writes from userspace here is a hack around this.

please work with kernel folks from your distro or upstream on this. this must be dealt with by the kernel, not worked around in userpsace.

Sorry of that's disappointing. But let's close hence.

**Pull request closed without merging**
