### PR TITLE
systemd-stdio-bridge: add manpage

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by medhefgo** [comment]
As someone who doesn't know what this prog does: this manpage is not enlightening at all. Maybe an example section would help?

**Comment by bluca** [comment]
Would be nice, problem is, I don't know either besides what's written here XD

**Comment by mbiebl** [comment]
See #4784

**Comment by bluca** [comment]
If it has a `--help` it can have a manpage - I think it's fine to start with a minimal one and then expand it later if we can

**Comment by yuwata** [comment]
At least, this is a good start point. Let's improve it later if necessary. Merging.

**Pull request merged**
