### PR TITLE
The best kind of changes are whitespace changes.

### PR DESCRIPTION
**Pull request by xnox**
For CI

### CODE REVIEW

**Comment by poettering** [comment]
was about to write all is green again, but i see now the ubuntu CI just vanished...

**Comment by xnox** [comment]
@iainlane looks good.

@poettering i don't know about all of bionic-*, but bionic-s390x got triggered and is green. Did somebody remove other bionic-* triggers? At the moment we are expecting all of them to be back to green, so please retrigger bionic-* checks in all the places?

**Comment by evverx** [comment]
> Did somebody remove other bionic- triggers?

Given that Ubuntu CI has been broken for about five days, as far as I can tell, it would have certainly made sense to turn it off, but no it was up. I took a look at the logs of the webhook triggering i386 and GitHub says that "We couldn’t deliver this payload: Service Timeout". All the subsequent requests were successful.

**Comment by evverx** [comment]
I did turn the webhook triggering arm64 about a month ago though due to https://github.com/systemd/systemd/issues/11104. It would be great if someone took a look and tried to figure out what is going on there.

**Comment by xnox** [comment]
@evverx at the moment Laney and I are only concerned about none of the tests even being attempted since Thursday, which is now fixed. Hence we are trying to get back to the "same old" scenario.

**Comment by evverx** [comment]
So I'd say that if the test won't be fixed anytime soon (as it usually happens) it would make sense to turn off the webhooks triggering i386 and amd64 so as not to bother contributors.

**Comment by evverx** [comment]
> Those are the main architectures (at least amd64 is), so that would be quite drastic.

It's not as drastic as merging PRs that breaks Travis CI and CentOS CI just because everybody is used to Ubuntu CI failing more often than not.

>  You could instead ask pitti to disable it for CI.

I've been waiting for a reply for 28 days in https://github.com/systemd/systemd/pull/11252#discussion_r244277847 so no thank you I don't think it's an option I'd consider this option.

**Comment by evverx** [comment]
Just to be clear, I have no problem with Ubuntu CI. What I'm trying to say that in its current form it isn't suitable for running the tests when PRs are opened mainly because it doesn't look like it's actively maintained. Maybe it would be better to run the tests once a day (as suggested in https://github.com/systemd/systemd/issues/11195) or before a release. Anyway, it's just my opinion and everybody else might think otherwise. After all, it's not that hard to keep ignoring it (which is the "same old scenario" as far as I know) even when it's turned on.

**Comment by xnox** [comment]
@evverx I think test-bpf is simply broken no, and should be removed from the tests. It is skipped everywhere (needs root, or skipped on travis). Not sure how come it works on s390x (will check if it gets skipped there). But running

```
for i in {1..100}; do sudo ./test-bpf >&OUT-$i &  done;
```

Fails for me.

```
OUT-36:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-47:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-51:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-54:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-62:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-69:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-75:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-82:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-85:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-87:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-88:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-89:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-90:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-92:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-94:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
OUT-98:Assertion 'manager_new(UNIT_FILE_USER, MANAGER_TEST_RUN_BASIC, &m) >= 0' failed at ../src/test/test-bpf.c:69, function main(). Aborting.
```

Which indicates that the test / systemd code / kernel is flakey here, rather than the CI being flakey. And it's fully in upstream power to make test-bpf exit SKIP instead of FAIL until we fully resolve. I'll make a proposal to mark test-bpf as flakey for now.

**Comment by evverx** [comment]
> I think test-bpf is simply broken 

Judging by https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/amd64/s/systemd-upstream/20190117_152804_9abc6@/log.gz, the test passed 6 days ago, so it wasn't broken then. I'm not sure what happened next. What I'm sure about is that the assertions you showed have nothing to do with the failure we're talking about.

> Dude.... many people are afk on 28th of December cause it's between christmas & new year, hence notifications go missing.

That's correct and I can't argue with that. Though, there are PRs where I've been waiting for replies for half a year or so. Besides, I thought that @martinpitt no longer maintains Ubuntu CI. If my understanding is incorrect, let's change https://www.freedesktop.org/wiki/Software/systemd/autopkgtest/ again.

> Hey, I'm confused by that comment you link to. For ubuntu-ci we use bionic series, not xenial. Why are you asking for backports to xenial?

It was more about me not wanting to bother @martinpitt over and over again because once again it's my understanding that @martinpitt has more important things to do.

**Comment by martinpitt** [comment]
Sorry for the lag. This is Brno team meetings/devconf.cz week..

@evverx: https://www.freedesktop.org/wiki/Software/systemd/autopkgtest/ didn't actually mention a point of contact, but it's a good idea to do so indeed. I added that now, suggesting to notify @iainlane. Is there another person, too?

@xnox: That sounds like a good idea. I created a new [upstream-systemd-ci team](https://launchpad.net/~upstream-systemd-ci) with you, @mbiebl, and me, and copied the backports to a new [team PPA](https://launchpad.net/~upstream-systemd-ci/+archive/ubuntu/systemd-ci/+packages). I updated the webhooks and semaphore config to use this new PPA now.

Please let me know if anything broke due to this!

**Comment by evverx** [comment]
@martinpitt thank you!

> Is there another person, too?

According https://github.com/systemd/systemd/pull/10775#issuecomment-438745761, there are two people who we can notify if something goes wrong. Though, it might have changed.

Regarding semaphoreci, could you also delete "sudo add-apt-repository -y 'deb http://archive.ubuntu.com/ubuntu artful main'"  there? If I recall correctly, it was added a long time ago because one of the dependencies (not sure which one) wasn't available there but as far as I know, it's no longer necessary.

**Comment by evverx** [comment]
@martinpitt `add-apt-repository` seems to be complaining about [`ppa:upstream-systemd-ci/systemd-ci`](https://semaphoreci.com/systemd/systemd/branches/pull-request-11545/builds/1):
```
gpg: keyring `/tmp/tmpf_ozrb1i/secring.gpg' created
gpg: keyring `/tmp/tmpf_ozrb1i/pubring.gpg' created
gpg: requesting key 317A360E from hkp server keyserver.ubuntu.com
gpgkeys: key 602DA2D8F03FED90D4ED3090E4A8EEB6317A360E not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: key not found
gpg: keyserver communications error: bad public key
gpg: keyserver receive failed: bad public key
Failed to add key.
```

**Comment by martinpitt** [comment]
@xnox: Fixed

**Comment by evverx** [comment]
@martinpitt now that the artful repository was removed, `systemd` seems to be failing to compile because [`libmount-dev` is too old there](https://semaphoreci.com/systemd/systemd/branches/master/builds/6068):
```
Native dependency mount found: NO found '2.27.0' but need: '>= 2.30'

meson.build:891:0: ERROR:  Invalid version of dependency, need 'mount' ['>= 2.30'] found '2.27.0'.
```
which is exactly what I got around with the kludge I mentioned in https://github.com/systemd/systemd/pull/11252#discussion_r244277847.

**Comment by martinpitt** [comment]
@evverx: This seems to be fixed now, with the util-linux 2.30 backport in the PPA, right?

**Comment by evverx** [comment]
@martinpitt yes, @xnox backported [4 packages](https://launchpad.net/~upstream-systemd-ci/+archive/ubuntu/systemd-ci/+packages?field.name_filter=&field.status_filter=published&field.series_filter=xenial) and semaphoreci seems to be happy now.

But something fishy is going on with Ubuntu CI: https://github.com/systemd/systemd/pull/11545#issuecomment-457831872.

**Comment by xnox** [comment]
Hmmmm I see lots of runs hanging and taking 5h+ to complete and then getting killed.

**Comment by xnox** [comment]
@evverx I get get access to those logs during normal working hours only.

I do question many of the new upstream tests that were added. I.e. the TEST-24-UNIT-TESTS doesn't relaly make sense to run on the autopkgtest infrastructure at all, as we are already running the tests as root in the root-unittest test case. Starting a nested qemu VM, and running them again, when executed by system systemd unit doesn't make the test results any better or easier to debug. Imho on the autopkgtest infra I'd rather blacklist TEST-24-UNIT-TESTS as a whole.

**Comment by evverx** [comment]
> @evverx I get get access to those logs during normal working hours only.

OK. I'll turn off all the ubuntu ci webhooks shortly because it doesn't seem to make any sense to trigger Ubuntu CI now. Let me know when we can get closer to what is going there.

>  I.e. the TEST-24-UNIT-TESTS doesn't relaly make sense to run on the autopkgtest infrastructure at all

TEST-24-UNIT-TESTS is supposed to run the unit tests in VMs, privileged and unprivileged containers, which, in my opinion, is very useful; more precisely, 3 times more useful than `root-unittests`. If you think it shouldn't be run on Ubuntu CI, the choice is yours.

**Comment by evverx** [comment]
All the ubuntu ci webhooks are now inactive.

**Comment by xnox** [comment]
@evverx 

"TEST-24-UNIT-TESTS is supposed to run the unit tests in VMs, privileged and unprivileged containers" does that actually pass? If we know that test-bpf does not pass in containers still?

IMHO, at least on Ubuntu-autopkgtests there is no need to do the VMs portion, as one can just run them with root already as one is in a VM. And it seems to me that the artificially constrained nested VM is not helpful here at all (nor is the target environment for the test).

@evverx can the webhooks still be on, but like not report failures, as if in a skipping mode? Or do I need to change things on our side to report "neutral" instead of "failure"? Also I wonder if we can start reporting "timed out", "canceled", "action required" states.

My primary concern with disabling CI, is that v240 is failing the tests in the Distribution across 3 out of 6 arches (we test across all 6 in the distro), hence I still cannot release v240 into Ubuntu development series. Which is also kind of blocking cherrypicking fixes to stable releases.

**Comment by evverx** [comment]
Just to be clear, I'm not a villain who wants to turn Ubuntu CI off once and for all. In fact, I think it would be great to run the tests on as many architectures as possible. And to get there it would probably make sense to turn the "upstream" test off altogether (because it's flaky and it's going to be run on CentOS and Arch anyway) and fix Ubuntu-specific issues like https://github.com/systemd/systemd/issues/11104 first. Once Ubuntu CI is green and stable and can somehow report its status in a way that wouldn't involve bothering everyone who maintains it (that is really ready to be used as CI), it shouldn't be a problem to bring it back

**Comment by evverx** [comment]
Regarding semaphoreci, I've just taken a look at the logs to see how many times it failed due to `apt-get-repository` failing to add the new repository. It failed twice on January 27. Should we wait a little bit more for the key to propagate properly or is it time to add kludges to the semaphoreci config as @xnox suggested in https://github.com/systemd/systemd/issues/9666#issuecomment-457769875?

**Comment by evverx** [comment]
Turns out, the key for the new repository hasn't been propagated properly yet and Travis CI fails much more often than I expected. @xnox @martinpitt is it possible to make `add-apt-repository ppa:upstream-systemd-ci/systemd-ci -y` work or would it be better to just start using the kludge I removed in https://github.com/systemd/systemd/pull/11582 again?

**Comment by evverx** [comment]
@martinpitt @xnox @iainlane it seems that Ubuntu CI has been in a really weird state for at least about 10 days (and effectively kind of broken for about a month). I let @xnox know every time I saw anything suspicious as in https://github.com/systemd/systemd/pull/11686#issuecomment-462194092 and even tried to suggest some kludges to make it easier to figure out what's going on https://github.com/systemd/systemd/pull/11743#issuecomment-464637797. But it seems to me that it's kind of futile and is unlikely to help to fix the underlying issue. Should it be reported on https://launchpad.net/ so that it would be tracked properly? Or could you recommend a better way to proceed?

**Comment by martinpitt** [comment]
@evverx : I was looking at a few recent PRs, and CI by and large seems to work. There were some recent regressions and bugs which I fixed in PR #11784 and #11792. There's still an occasional boot-smoke failure, but this also isn't infra related, but a bug somewhere (I saw it locally, too).

The two PRs you referenced to fail in the `make check` unit tests (test-path). If this is really an infra problem, then I can't help I'm afraid. (But maybe it was an actual bug and fixed in master recently?)

**Comment by evverx** [comment]
> The two PRs you referenced to fail in the `make check` unit tests (test-path).

That's correct that test-path failed but it failed in https://github.com/systemd/systemd/pull/11685 while Ubuntu CI reported it in https://github.com/systemd/systemd/pull/11686 (that is, in https://github.com/systemd/systemd/pull/11686 in the logs for some reason UPSTREAM_PULL_REQUEST is 11685 instead of 11686 and something like that has happened often lately).

In https://github.com/systemd/systemd/pull/11743#issuecomment-464637797, the issue is that Ubuntu CI showed the results for the first version of the PR (where there was a bug) and it didn't run the tests against the latest version. But in that case it's hard to tell because there is no way to figure out what exactly Ubuntu CI tested. That's why I asked @xnox to add `git describe` to https://salsa.debian.org/systemd-team/systemd/blob/master/debian/extra/checkout-upstream so that by looking at UPSTREAM_PULL_REQUEST and the output of `git describe` it would be possible to find out what Ubuntu CI reports.

**Comment by evverx** [comment]
I've just opened https://bugs.launchpad.net/ubuntu/+source/autopkgtest/+bug/1817344. I hope we'll find someone who can help to find people who can fix it.

**Comment by martinpitt** [comment]
> That's why I asked @xnox to add git describe 

This is already contained in the logs: They show the GitHub `statuses_url` which is the topmost git SHA that corresponds to the current PR. E. g. PR #11804 refers to [this wrong amd64 log](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/amd64/s/systemd-upstream/20190222_161608_7fe1f@/log.gz), which really is for PR# 11802. #11802 refers to the *same* log, but there it's actually correct. The SHA in the log corresponds to reality in #11802.

**Comment by poettering** [comment]
Can we close this one? anything left on this one?

**Comment by martinpitt** [comment]
Right, I think this has served its due purpose.

**Pull request closed without merging**
