### PR TITLE
hashmap/prioq: handle NULL keys in core

### PR DESCRIPTION
**Pull request by teg**
Our hash_ops don't handle NULL pointers, so let's do this in the hashmap/prioq to avoid ever getting into trouble.

### CODE REVIEW

**Comment by poettering** [comment]
Not sure how I feel about this... We have many users of Sets/Hashmap that store non-ptr keys and values in it. In those cases a NULL might actually be a valid value you might want to add.

One of the more prominent examples there are cases where we store UIDs as key, where UID=0 is completely valid. Now, in the current codebase we never convert uid_t to pointers directly, but always add 1 to it while doing so (using UID_TO_PTR()), in order to avoid the ambuguity, but that only really works in this specific case, as we declare (uid_t) -1 as invalid anyway (because if we +1 every uid then uid -1 would become 0, if -1 was valid...).

I figure the least we need to do is make sure that all cases where we store non-ptr values in hashmaps/sets, we do a similar +1 shift. That means going through the current uses of Hashmap/Set and verify that.

Also, if we enforce this, then we should return EINVAL if a NULL key or value is attempted to be added to the Set/Hashmap.

**Comment by poettering** [comment]
Also, as @michich knows the hashmap/set best, I wodner if you have an opinion about this?

**Comment by teg** [comment]
Note that this does accept NULL pointers just fine (see the new test cases), but it just hardcodes them to be the smallest element. You are right that this could indeed be problematic if you are storing signed values as pointers...

**Comment by michich** [comment]
Hashmaps/Sets do not care which key is the smallest one, because hash_ops->compare() is called only to test for equality. So nothing should break there.
That said, I don't find it very useful to allow a string-to-value hashmap (with string_hash_ops) to accept a NULL key. The motivation for the patch is to "avoid ever getting into trouble", but by accepting the NULL key it might as well cover up a bug instead of exploding immediately. Or do you already have a need to do this?

**Comment by teg** [comment]
@michich the problem (if any) would be with prioq as that uses the comparison too. The motivation for the patch is to be defensive, so either add asserts everywhere where NULL makes no sense, or make it silently work (under the assumption that it may be useful to allow NULL keys, though I'm not aware of such a case). Currently we would just segfault, which is not that nice.

**Comment by poettering** [comment]
As discussed with @teg we should find a different solution for this, for example do the NULL check inside of the hash functions.

**Pull request closed without merging**
