### PR TITLE
Resolved generic packet

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by yuwata** [comment]
(The first commit is a duplicate of #7922.)

**Comment by poettering** [comment]
lgtm

**Comment by keszybz** [comment]
```
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.162 80]
```

**Comment by evverx** [comment]
The last commit message should probably contain the string "'Credit to OSS-Fuzz'".

**Comment by xnox** [comment]
zesty is end of life, and thus removed from the mirrrors.

Please use artful (current stable), bionic (current development, to become LTS release with 5 years of support), or xenial (current LTS release, a bit dated, maybe with hwe packages) as appropriate.

Do I need to file a separate ticket for this?

**Comment by xnox** [comment]
If you wish to stay on zesty, you could use old-releases.ubuntu.com were latest zesty snapshot should be published indefinitely.

**Comment by keszybz** [comment]
I'm trying with artful now, but semaphore is being slow.

**Comment by keszybz** [comment]
Since our CI is passing, FWIW, let's merge this.

**Pull request merged**
