### PR TITLE
unit: update initrd-network-generator.service

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by poettering** [comment]
hmm, but why only run this in the initrd phase? also makes sense during regular boot, no? i.e. why not allow configuration of IP networking via the kernel cmdline in initrd-less systems, too?

**Comment by yuwata** [comment]
@poettering Thank you for the comments. Initially I thought the tool is for initrd, especially dracut. But actually this can be used initrd-less systems. In the revised version, the unit is simply ordered before network-pre.target. And may be installed to that target. PTAL.

**Comment by poettering** [comment]
Hmm @yuwata any chance you can rebase this on top of #13224, so that the CI can pass?

**Comment by keszybz** [comment]
Nah, I merged #13224 and I'll just restart `bionic-i386`.

**Comment by mrc0mmand** [comment]
The CentOS CI fail is unrelated, the SSH session died somewhat unexpectedly, although all tests passed.

**Comment by keszybz** [comment]
@mrc0mmand could you restart it?

**Comment by mrc0mmand** [comment]
@keszybz sure, done

**Comment by yuwata** [comment]
Thanks.

**Comment by poettering** [comment]
bionic i386 CI is still failed?

**Comment by keszybz** [comment]
```
# fix paths in manpages; manually check the remaining /usr occurrences
# occasionally, with filtering out paths which are known to be in /usr:
# grep -r /usr debian/install/deb/usr/share/man/|egrep -v '/usr/local|os.*release|factory|zoneinfo|tmpfiles|kernel|foo|machines|sysctl|dbus|include|binfmt'
find debian/install/deb/usr/share/man/ -type f | xargs sed -ri 's_/usr(/lib/systemd/system|/lib/systemd/network|/lib/udev|/lib[^/]|/lib/[^a-z])_\1_g'
find: ‘debian/install/deb/usr/share/man/’: No such file or directory
sed: no input files
debian/rules:185: recipe for target 'override_dh_auto_install' failed
```
This is most likely because man pages are not installed. `-Dman=true` is not used. Though it's unclear to me why this would start failing now.

@xnox ?

**Comment by keszybz** [comment]
OK, let's merge. We won't be able to fix packaging issues quickly.

**Pull request merged**
