### PR TITLE
sd-dhcp6-lease: Ignore invalid bytes at the end of the packet

### PR DESCRIPTION
**Pull request by pkern**
Oracle Cloud sends malformed DHCPv6 replies that end in a DHCP option 0 containing a NoPrefixAvail status message (and thus should probably be an IA_PD) option and an additional null byte that does not parse as an option code.

networkd currently can cope with the invalid option (it is ignored), but the whole packet is ignored altogether because of the additional null at the end.

It's better to be liberal in what we accept and actually assign an address, given that the reply contains a valid IA_NA.

(Technically this is a glorified `if 1 < 2` check. But it's checking for the condition that will yield `-EBADMSG` from `dhcp6_option_parse`.)

### CODE REVIEW

**Comment by keszybz** [comment]
Looks reasonble, but I wonder how liberal we should be:
1. only ignore the trailing bytes if they are 0
2. ignore anything that is shorter than `DHCP6Option` header
3. ignore all errors from dhcp6_option_parse

The patch does 2., but I'm not sure what the most correct thing to do is. @yuwata comments?

**Review by yuwata — COMMENTED** [review]
LGTM, if it works.
Could you provide the dumped packet (feel free to hide privacy data if you'd like) and add a test based on the packet?

**Comment by pkern** [comment]
Is there an existing test harness to put this in? I only saw an integration test that runs a DHCPv6 server.

The packet looks like this:

```
0000   02 00 17 07 d8 be 00 00 17 4e 8b fb 86 dd 60 00
0010   00 00 00 82 11 40 fe 80 00 00 00 00 00 00 02 00
0020   17 ff fe 4e 8b fb fe 80 00 00 00 00 00 00 00 00
0030   17 ff fe 07 d8 be 02 23 02 22 00 82 91 1c 07 01
0040   9f d6 00 02 00 0a 00 03 00 01 00 00 17 4e 8b fb
0050   00 01 00 0e 00 02 00 00 ab 11 23 bb 0b 9a 28 b8
0060   29 b8 00 0e 00 00 00 03 00 28 80 c0 db 71 00 00
0070   a8 c0 00 00 fd 20 00 05 00 18 26 03 c0 20 80 16
0080   44 00 6b 3b 60 bd 17 a0 40 c7 00 01 51 80 00 01
0090   5f 90 00 00 00 21 00 00 00 00 00 00 00 00 00 00
00a0   00 00 00 0d 00 11 00 06 4e 6f 50 72 65 66 69 78
00b0   41 76 61 69 6c 61 63 00
```

**Comment by yuwata** [comment]
Please update src/libsystemd-network/test-dhcp6-client.c, e.g. copy TEST(client_parse_message_issue_24002) and modify the packet binary based on what you paste.

**Comment by yuwata** [comment]
Added a brief test about that, and worked fine for me. Setting the green label.

**Review by bluca — APPROVED** [review]

**Comment by pkern** [comment]
Thank you, @yuwata and @bluca!

**Pull request merged**
