### PR TITLE
Make homed/userdbd/repart services installable (to allow uninstalling)

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by mrc0mmand** [comment]
`TEST-46-HOMED` no likey:

```
Got message type=signal sender=org.freedesktop.DBus destination=org.freedesktop.systemd1 path=/org/freedesktop/DBus interface=org.freedesktop.systemd1.Activator member=ActivationRequest cookie=7 reply_cookie=0 signature=s error-name=n/a error-message=n/a
dbus-org.freedesktop.home1.service: Failed to load configuration: No such file or directory
dbus-org.freedesktop.home1.service: Trying to enqueue job dbus-org.freedesktop.home1.service/start/replace
D-Bus activation failed for dbus-org.freedesktop.home1.service: Unit dbus-org.freedesktop.home1.service not found.
Sent message type=signal sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Activator member=ActivationFailure cookie=8 reply_cookie=0 signature=sss error-name=n/a error-message=n/a
dbus-org.freedesktop.home1.service: Collecting.
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitNew cookie=9 reply_cookie=0 signature=so error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=UnitRemoved cookie=10 reply_cookie=0 signature=so error-name=n/a error-message=n/a
testsuite.service: Got notification message from PID 69 (ERRNO=2)
[ 1132.916389] bash[69]: Failed to create user home: Unit dbus-org.freedesktop.home1.service not found.
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/testsuite_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=11 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/testsuite_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=12 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a cookie=8 reply_cookie=5 signature=u error-name=n/a error-message=n/a
Successfully acquired requested service name.
Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a cookie=9 reply_cookie=6 signature=n/a error-name=n/a error-message=n/a
Match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.1' successfully installed.
systemd-journald.service: Received EPOLLHUP on stored fd 34 (stored), closing.
Received SIGCHLD from PID 63 (bash).
Child 63 (bash) died (code=exited, status=1/FAILURE)
testsuite.service: Failed to read oom_kill field of memory.events cgroup attribute: No such file or directory
testsuite.service: Child 63 belongs to testsuite.service.
testsuite.service: Main process exited, code=exited, status=1/FAILURE
testsuite.service: Failed with result 'exit-code'.
``

**Comment by keszybz** [comment]
We have three levels of enablement: disabled, dbus symlink present to allow activation, both dbus symlink and multi-user.target.wants/ symlink present. The middle option would also solve the issue with the failing test, but after thinking about this a bit, I decided to simply enable homed in TEST-46-*, and keep the patch as it was (install neither of the symlinks). I'm not sure why systemd-homed is enabled by default, maybe it would be enough to have it dbus activated. But if we make such a change, we still want the change in this PR, so users can fully disable the service even if it is compiled in.

**Comment by keszybz** [comment]
Hmm, ```
17:25:32 Failed to enable unit, unit systemd-homed.service does not exist.
17:25:32 make: *** [setup] Error 1
```
@mrc0mmand any idea why it's still failing like that? Is it possible that it ran the wrong commit?

**Comment by mrc0mmand** [comment]
@keszybz if you mean the error in the CentOS 7 job then that's expected, since there we compile systemd with `-Dhomed=false` (due to ancient OpenSSL), thus the unit is indeed not present.

**Comment by keszybz** [comment]
See the latest commit — I added `|| :` so it should not fail at that point. But I think this might have been a temporary issue, the dot is now yellow. It seems that for some reason the job did not trigger immediately when the other ones did and was still displaying the status from the outdated build.

**Comment by keszybz** [comment]
So... I think the ubuntuautopkg ci is not going to return any useful results soon. It seems to be broken over the last three days or so.

I would prefer to have a review from someone before merging this.

**Comment by keszybz** [comment]
I force-pushed with the a change to add the issue number to the commit message and squash two commits together. Maybe the ubuntu ci will pass now.

**Comment by keszybz** [comment]
Updated.

**Comment by keszybz** [comment]
@anitazha acked this, and CI (mostly) passes. Let's merge.

**Comment by poettering** [comment]
uh oh, why make repart configurable, it doesn't do anything if there are no drop-ins. it's something that should just work. let's not do that. It's like sysctl.d/ or tmpfiles.d/ or sysusers.d/ support: it has no effect if there are no drop-ins and the way to make it do something is by dropping in a config file. Please revert this part!

userdb should just be there, too, if the distro turned it on during compilation. It just sits in the bg and doesn#t do a thing. it shouldn#t be something anyone explicitly enabled. i.e. it's in the category of logind or timedated: stuff that is there if it's built and part of the OS, and not something people enable or disable. Or if they really want to disable it, then with "systemctl mask"...

homed might be something to disable, dunno. but the other two, and in particular repart is not of that kind...

**Comment by andreyv** [comment]
> It just sits in the bg and doesn#t do a thing

Many people will find this problematic. If it doesn't do anything, it shouldn't run. A better approach would be to run it on demand.

**Comment by poettering** [comment]
> Many people will find this problematic. If it doesn't do anything, it shouldn't run. A better approach would be to run it on demand.

well, then use "systemctl mask", or disable it at build time. The question is not whether to have ways to enable/disable it (we do, two prominent ones), but how user-facing to make it. THe most user-facing way to enable/disable something is "systemctl enable" and "systemctl disable", and no i don't think that repart or userdb really qualify for that. It's not something a regular admin should every fiddle with.

**Comment by andreyv** [comment]
Why are `systemd-timedated`, `systemd-localed`, `systemd-hostnamed` etc. able to run on demand, but not `systemd-userdbd`?

**Comment by keszybz** [comment]
It's still enabled by default. The motivation to make it installable is that in various circumstances people do not want the code to run at all. For example: they have a strict MAC policy, and even a no-op invocation would require some support in the policy. Or they're running this on a tiny board and would like to use presets to make as few things run as required.

> disable it at build time

This doesn't work well with distro-provided images. Saying "do it at compile time" is not useful when people are not rebuilding everything all the time, and thankfully, nowadays they mostly aren't.

> `systemctl mask`

Masking is not suitable for this, because it's expressing a different operation: masking is saying "I don't want to run this ever", and we need "I don't want this to start on normal boot". In particular, masking breaks every dependency that has Requires= and makes noise in other circumstances too.

Having so many levels at which services can be enabled and disabled does make things complex, but otoh, when the same level of configurability is present for all services, we get a certain simplicity from consistency. It's fairly obvious that various people want/need to make use of enabling and disabling at different levels.

**Comment by poettering** [comment]
> Why are `systemd-timedated`, `systemd-localed`, `systemd-hostnamed` etc. able to run on demand, but not `systemd-userdbd`?

it is. it is socket activated by systemd-userdbd.socket. It's activated whenever some client connects to its socket.

**Comment by poettering** [comment]
> It's still enabled by default. The motivation to make it installable is that in various circumstances people do not want the code to run at all. For example: they have a strict MAC policy, and even a no-op invocation would require some support in the policy. Or they're running this on a tiny board and would like to use presets to make as few things run as required.

you can make the very same arguments for tmpfiles.d/sysusers.d/sysctl.d/binfmt.d/ as for repart.d/. And they don't really apply there as much as they apply for repart.d

If you have a strict MAC policy, then you are an OS vendor, and shouldn't package the stuff you don't want.

we generally don't do enable/disable stuff for the initrd, you are introducing something here we never did so far. repart is after all an initrd feature primarily.

i mean, by all means add ConditionXYZ= stuff like for systemd-binfmt.service to systemd-repart.service, but enable/disable is the *wrong* approach, sorry.

**Comment by keszybz** [comment]
> you can make the very same arguments for tmpfiles.d/sysusers.d/sysctl.d/binfmt.d/

Yeah, and we could make them enable-able using presets too. Esp. if somebody asks for it.

>  by all means add ConditionXYZ= stuff like for systemd-binfmt.service to systemd-repart.service

OK, that'd be another good approach. But I think we should have a mechanism to express the full range of search paths in one line, without repeating them in every unit file. That is just too cumbersome. Something like `ConditionDirectoryNotEmpty=CONF_PATHS(binfmt.d)`.

**Comment by poettering** [comment]
> Yeah, and we could make them enable-able using presets too. Esp. if somebody asks for it.

No, let's *not* do that. enable/disable is for OS *payload*, not for the OS itself. let's not get overboard with that.

ConditionDirectoryNotEmpty= currently insists on absolute paths. maybe if the paths are relative we automatically expeand with conf prefixes.

**Comment by keszybz** [comment]
> ConditionDirectoryNotEmpty= currently insists on absolute paths. maybe if the paths are relative we automatically expeand with conf prefixes.

I think that'd be too much magic, and wouldn't work if we want to a different search path for something similar later.

What about ConditionConfigSearchPathNotEmpty= ? (And then we could define ConditionBinarySearchPathNotEmpty= later on or something.)

**Comment by poettering** [comment]
> I think that'd be too much magic, and wouldn't work if we want to a different search path for something similar later.

Do you have any in mind? I don't see any coming...

I mean, people can always spell it out if they want something else...

**Pull request merged**
