### PR TITLE
some fixes to the scope unit type

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by keszybz** [comment]
Looks all good. I'll give this a spin and then I'm happy to merge.

**Comment by keszybz** [comment]
`autopkgtest [01:58:53]: ERROR: "mkdir -p /tmp/autopkgtest.BXbTTH" failed with stderr "sudo: unable to resolve host testgreen`

I'll restart amd64 on artful.

**Comment by keszybz** [comment]
Seems to work fine ;)

**Comment by poettering** [comment]
```
autopkgtest [01:58:53]: ERROR: "mkdir -p /tmp/autopkgtest.BXbTTH" failed with stderr "sudo: unable to resolve host testgreen
```

**Comment by poettering** [comment]
Hmm, both CIs that failed are due to some ubuntu infrastructure issues. Merging.

**Pull request merged**
