### PR TITLE
build-sys: use itstool instead of intltool

### PR DESCRIPTION
**Pull request by jsynacek**

### CODE REVIEW

**Comment by keszybz** [comment]
I didn't check it it works..., but those new Make rules look a bit iffy:
- silent compilation should be done properly with AM_V_*, see e.g. AM_V_M4 for an example
- patsubst is overkill, $(_po_files:.po=.mo) should be enough

**Comment by filbranden** [comment]
I'll try to review this commit tomorrow... Thanks!

**Comment by mbiebl** [comment]
With intltool we had a po/Makefile, where you could run "make -C po update-po", which created a systemd.pot and updated the existing .po files. Shouldn't we add similar functionality when using itstool?

**Comment by zonque** [comment]
`itstool` is now in the list of packages Semaphore will install, so the build shouldn't fail due to that anymore.

**Comment by jsynacek** [comment]
> With intltool we had a po/Makefile, where you could run "make -C po update-po", which created a >systemd.pot and updated the existing .po files. Shouldn't we add similar functionality when using >itstool?

Yep. I totally forgot about that part. Also, without that Makefile, translations are not installed on `make install`.

**Comment by jsynacek** [comment]
I ran into a pretty big issue...

The proper way to create the po/Makefile{,.in,.in.in} files is to run `gettextize` in a similar fashion as the `intltoolize` script was run. However, for some reason, `gettextize` is _interactive_ and requires the caller to press Return everytime it's run. And it reads /dev/tty directly, so it can't be used from non-interactive tools. This basically means that we would have to bundle at least Makefile.in.in and probably some m4 scripts.

Any ideas?

**Comment by poettering** [comment]
@jsynacek a bit of googling reveals this:

https://lists.gnu.org/archive/html/bug-gettext/2011-12/msg00001.html

maybe "autopoint" is the tool to use here?

**Comment by jsynacek** [comment]
v2: https://github.com/systemd/systemd/pull/1576

**Pull request closed without merging**
