### PR TITLE
Udev vs tmpfiles

### LINKED ISSUE #28588: Wrong permissions for /dev/vfio/vfio
### systemd version the issue has been seen with

systemd v254

### Used distribution

Debian sid

### Linux kernel version used

kernel-6.4-9

### CPU architectures issue was seen on

x86_64

### Component

systemd-tmpfiles, systemd-udevd

### Expected behaviour you didn't see

Correct permissions set for "/dev/vfio/vfio" with mode=0666

### Unexpected behaviour you saw

Permissions for "/dev/vfio/vfio" are mode=0600

### Steps to reproduce the problem

Upgrade from 253.5-1 to 254-1 and reboot

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[    1.747028] systemd-tmpfiles[317]: Entry "/dev/vfio/vfio" matches include prefix "/dev".
[    1.751287] systemd-tmpfiles[317]: Running create action for entry c /dev/vfio/vfio
[    1.751307] systemd-tmpfiles[317]: Created char device node "/dev/vfio/vfio" 1:128.
[    1.830822] systemd-udevd[328]: Setting permissions /dev/vfio/vfio, uid=0, gid=0, mode=0666
[    2.167485] (udev-worker)[374]: vfio: Preserve permissions of /dev/vfio/vfio, uid=0, gid=0, mode=0666
[    2.167505] (udev-worker)[374]: vfio: Successfully created symlink '/dev/char/10:196' to '/dev/vfio/vfio'
[    2.878296] systemd-tmpfiles[659]: Running remove action for entry c /dev/vfio/vfio
[    2.883837] systemd-tmpfiles[659]: Running create action for entry c /dev/vfio/vfio
[    2.883855] systemd-tmpfiles[659]: Found existing char device node "/dev/vfio/vfio" 1:128.
[    2.883857] systemd-tmpfiles[659]: Changing "/dev/vfio/vfio" to mode 600.
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #28588 and #28653.

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Review by mrc0mmand — COMMENTED** [review]
Belated LGTM, thank you!

**Comment by floppym** [comment]
I think this is insufficient because `systemd-tmpfiles-setup.service` no longer passes `--exclude-prefix=/dev` to `systemd-tmpfiles`. That means the udev permissions may be overwritten again.

**Comment by floppym** [comment]
We also had a user report that this did not resolve #28588.

https://bugs.gentoo.org/911723#c6

**Comment by yuwata** [comment]
@floppym The tmpfiles entry will back in #28724.
Though, the issue should be user or distro misconfiguration. I guess there exists tmpfiles entry for vfio with conflicting mode with udev rules. Please check which tmpfile config creates or change permission for vfio.

**Comment by floppym** [comment]
> Please check which tmpfile config creates or change permission for vfio.

I assume it is `kmod static-nodes`.
```
% grep vfio /run/tmpfiles.d/static-nodes.conf
d /dev/vfio 0755 - - -
c! /dev/vfio/vfio 0600 - - - 10:196
```

**Comment by yuwata** [comment]
Oh, I did not know tmpfiles config is dynamically generated on boot. Interesting.

**Comment by yuwata** [comment]
(Please do not backport the first commit, or also backport #28724.)

**Comment by floppym** [comment]
> Oh, I did not know tmpfiles config is dynamically generated on boot. Interesting.

Yup, see https://github.com/systemd/systemd/blob/v254/units/kmod-static-nodes.service.in.

**Comment by mrc0mmand** [comment]
> Oh, I did not know tmpfiles config is dynamically generated on boot. Interesting.

Yeah, I should've probably been a bit more clear in the [original commit](https://github.com/yuwata/systemd/commit/a3d610998ad3b4c88224fe89a048a84dbceb652b), but *c'est la vie*.

**Comment by yuwata** [comment]
No no, that's my mistake. I completely overlooked about that's dynamically generated in both the commit message and comment in the tmpfiles conf. Ugh.

Anyway, #28724 should work fine. Please push the approval and set the green label.

**Pull request merged**
