### PR TITLE
units: remove ldconfig.service

### PR DESCRIPTION
**Pull request by msekletar**
If ldconfig.service is run before we have mounted all file systems hence
some symlinks in loader library search path maybe dangling at that
time. ldconfig -X will remove dangling symlinks. This may cause problems
for applications which are started later.

Also ldconfig.service is workaround for broken packaging and gains us
very little in comparison to problems it may cause.

Suggested-by: Carlos O'Donell codonell@redhat.com

### CODE REVIEW

**Comment by keszybz** [comment]
ldconfig.service has two reasons for existence:
- "broken packaging"
- "empty /etc"
  I agree that the first is reason is bogus, and we shouldn't run ldconfig as a work-around when whatever installs the libraries should do it. (And in fact this is done pretty reliably by rpm, so I'm pretty sure we're just re-running it needlessly).

But the second reason is valid. Even if empty-/etc support isn't quite there yet, we're slowly moving in this direction.

I'd propose to drop `ConditionNeedsUpdate=|/etc`, and only keep `ConditionFileNotEmpty=!/etc/ld.so.cache` so the the service only get's run when somebody cleans out /etc.

Also, it should get a dependency `After=local-fs.target`. `systemd-update-done.service` already has that, and seems to be just an oversight that `ldconfig.service` doesn't.

**Comment by msekletar** [comment]
> Also, it should get a dependency After=local-fs.target. systemd-update-done.service already has that, and seems to be just an oversight that ldconfig.service doesn't.

It should even read `After=remote-fs.target`, because our users have reported problems with this service and 3rd party software installed on remote file system mounted under `/opt`.

**Comment by keszybz** [comment]
`update-done.service` is `Before=sysinit.target`. I don't think it'd be good to delay `ldconfig.service` (and thus effectively `update-done.service`) until after `remote-fs.target`. The use case of having libraries in `/opt` mounted on a remote fs is special. If we remove the first trigger from `ldconfig.service`, then people will not have a problem as long as they do not remove the ldconfig cache.

**Comment by msekletar** [comment]
-> #2859

**Pull request closed without merging**
