### PR TITLE
(DO NOT MERGE YET) Delete .travis.yml 

### PR DESCRIPTION
**Pull request by szb512**
Merge this when  #18128 gets merged.

### CODE REVIEW

**Comment by szb512** [comment]
Marked this as draft because  #18128 needs to merge first.

**Comment by szb512** [comment]
Ok never mind, once all jobs on travis have been moved, this will be marked as ready for review.

**Comment by evverx** [comment]
Given that `.travis.yml` isn't the only file that should be removed in the process, I think it would be better to let @mrc0mmand replace Travis with GitHub Actions and finish what was started in https://github.com/systemd/systemd/pull/18128 and https://github.com/systemd/systemd/pull/18174).

**Comment by evverx** [comment]
Closing this in favor of https://github.com/systemd/systemd/pull/18174

**Pull request closed without merging**
