### PR TITLE
README.md: add repology badge

### PR DESCRIPTION
**Pull request by topimiettinen**

### CODE REVIEW

**Comment by evverx** [comment]
I'm not sure I understand why it would be useful to keep that badge there. Could you expand on that?

**Comment by evverx** [comment]
Just to clarify, I think it would be better to add the badge to https://www.freedesktop.org/wiki/Software/systemd/ (more specifically, to the "Package repositories of the various distributions" section) or at least separate it from the other badges (which unlike the repology badge all have something to do with CI).

**Comment by topimiettinen** [comment]
I don't mind any other location, or dropping the PR if this is useless. Isn't systemd.io replacing the freedesktop.org site?

**Comment by keszybz** [comment]
I think it is useful to have this information on the github repo page. We could add it also on fd.o, but there's no harm to having it in both places. Possibly even also on systemd.io, since it's useful information to users.

Though I see one issue: repology thinks that our stable releases are invalid (shown in brown). Maybe we could fix that somehow? It's probably confused by the fact that stable releases live in systemd-stable repo. OTOH, there were plans to merge both repos to reuse the CI, so maybe we should finally do it.

**Pull request merged**
