### PR TITLE
networkd: split sources into subdirectories

### PR DESCRIPTION
**Pull request by teg**
Try to make the networkd sources a bit more manageable by splitting out some into separate subdirectories. Also clean up the headerfiles a bit.

This should not introduce any functional changes.

### CODE REVIEW

**Comment by keszybz** [comment]
Welcome back @teg!

**Comment by teg** [comment]
@keszybz thanks! This has now been replaced by #4665 (missed a hunk).

**Comment by martinpitt** [comment]
@teg: FYI, these days it's better to just force-push. GitHub supports that very well now (old comments don't get lost), and  discussion stays in one place.

**Comment by teg** [comment]
Ah, neat. Thanks!

**Pull request closed without merging**
