### PR TITLE
Kernel 3.10 compat

### PR DESCRIPTION
**Pull request by hbakken**
Add structs and defines to missing.h in order to compile with 3.10 kernels.  This kernel version is still used by quite a lot of hardware vendors and also in various android NDKs, so it's very useful.  These changes are fairly unobtrusive.

### CODE REVIEW

**Comment by poettering** [comment]
The commit msgs regarding the added PR_ defines are mixed up

**Comment by poettering** [comment]
Well, if you run such old kernels you'l likely run into other issues.

That said, patch looks OK to go in, but please fix the commit msgs, two commits have practically the same text there but they aren't right...

**Comment by hbakken** [comment]
Will fix.

**Comment by poettering** [comment]
no need to close the bug and open a new one these days. Just force push the new version over the old branch.

**Comment by poettering** [comment]
New version in #7687

**Comment by hbakken** [comment]
Ah, ha.  Will keep that in mind for the next time, thanks.

**Pull request closed without merging**
