### PR TITLE
Post-merge tweaks to the functional tests

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
Also https://salsa.debian.org/systemd-team/systemd/-/merge_requests/80.

**Comment by mrc0mmand** [comment]
Just a dumb question, given we're on the *tweaking the testsuite* topic - what about *copying* the cached image instead of symliking it?

https://github.com/systemd/systemd/blob/73abf7ae06a8699e8104cc7d97b5980245ecf04d/test/test-functions#L2004-L2007

That should help with the problematic concurrent access to the cached image without too much overhead (as copying the default ~512M image shouldn't take much time). 

On the other hand, this *feature* would be useful only when running the tests in parallel, since copying the image during sequential run is pretty much pointless.

**Comment by mrc0mmand** [comment]
As for the `TEST-13-NSPAWN-SMOKE`, I've seen this fail several times already and the VM simply gives up and does nothing until it's killed by `timeout`. It can be seen [here](https://ci.centos.org/job/systemd-pr-build-vagrant/6332/artifact//systemd-centos-ci/index.html) as well (and with appropriate journals).

Not sure what's going on, but it looks like the level of abstraction here (bare -> KVM -> KVM -> nspawn) is just too much.

**Comment by keszybz** [comment]
> Just a dumb question, given we're on the tweaking the testsuite topic - what about copying the cached image instead of symliking it?

That's actually a fairly good option. Also, I was thinking about the images like the selinux image, which just have some additions on top of the default — it would be faster to not build it from scratch, but start from a copy of the default image.

**Comment by keszybz** [comment]
I'll take the liberty to merge this too. It seems nobody wants to review my testsuite PRs ;)

**Comment by mrc0mmand** [comment]
> I'll take the liberty to merge this too. It seems nobody wants to review my testsuite PRs ;)

Ah, I thought you were going to add the stuff around image copying, mea culpa :-). Anyway, this indeed LGTM, I'll just play around with it in https://github.com/systemd/systemd-centos-ci/pull/235 since the merged journal breaks certain things in CentOS CI.

(Offtopic note related to the CentOS CI PR: is there any particular reason why `coredumpctl` doesn't support `--file` but only `-D` to specify journal location?)

**Pull request merged**
