### PR TITLE
test: add a sanity test for #19976

### PR DESCRIPTION
**Pull request by mrc0mmand**
which should ensure we can use nspawn containers with SELinux context set via
the `--selinux-context=` and `--selinux-apifs-context=` options.

### CODE REVIEW

**Review by bluca — APPROVED** [review]
lgtm

**Comment by yuwata** [comment]
Several upstream tests on Ubuntu CI (amd64) failed. Are they related? Maybe it is better to restart the test.

**Comment by mrc0mmand** [comment]
> Several upstream tests on Ubuntu CI (amd64) failed. Are they related? Maybe it is better to restart the test.

From a quick glance they don't seem related:

```
^M[  *** ] A start job is running for TEST-17-UDEV (12min 5s / no limit)
^M[   ***] A start job is running for TEST-17-UDEV (12min 6s / no limit)
^M[    **] A start job is running for TEST-17-UDEV (12min 6s / no limit)
^M[     *] A start job is running for TEST-17-UDEV (12min 7s / no limit)
qemu-system-x86_64: terminating on signal 15 from pid 27735 (timeout)
E: Test timed out after 800s
```

```
^M[     *] (3 of 3) A start job is running for…-foo.service (1min 34s / 1min 44s)
^M[    **] (1 of 3) A start job is running for app0.service (1min 27s / 1min 39s)
^M[   ***] (1 of 3) A start job is running for app0.service (1min 28s / 1min 39s)
^M[  *** ] (1 of 3) A start job is running for app0.service (1min 28s / 1min 39s)
^M[ ***  ] (2 of 3) A start job is running for…-29-PORTABLE (3min 20s / no limit)
^M[FAILED] Failed to start app0-foo.service.
See 'systemctl status app0-foo.service' for details.
[FAILED] Failed to start app0.service.
See 'systemctl status app0.service' for details.
[FAILED] Failed to start TEST-29-PORTABLE.
See 'systemctl status testsuite-29.service' for details.
```

```
^M[**    ] A start job is running for TEST-30-ONCLOCKCHANGE (3min 5s / no limit)
dev-ttyS7.device: Changed dead -> plugged
sys-devices-platform-serial8250-tty-ttyS7.device: Changed dead -> plugged
Received SIGCHLD from PID 273 (bash).
Child 273 (bash) died (code=exited, status=1/FAILURE)
testsuite-30.service: Child 273 belongs to testsuite-30.service.
testsuite-30.service: Main process exited, code=exited, status=1/FAILURE
testsuite-30.service: Failed with result 'exit-code'.
testsuite-30.service: Service will not restart (restart setting)
testsuite-30.service: Changed start -> failed
testsuite-30.service: Job 73 testsuite-30.service/start finished, result=failed
^M[FAILED] Failed to start TEST-30-ONCLOCKCHANGE.
See 'systemctl status testsuite-30.service' for details.
```

The common denominator in all of the fails seems to be:
```
[  180.085020] systemd[1]: Timed out waiting for device /dev/ttyS0.
[  182.941695] systemd[1]: Dependency failed for Serial Getty on ttyS0.
[  211.194954] kernel: print_req_error: I/O error, dev fd0, sector 0
```

**Comment by bluca** [comment]
restarted

**Pull request merged**
