### PR TITLE
xdg-autostart-service: handle gnome autostart phase better on other desktops

### PR DESCRIPTION
**Pull request by davidedmundson**
Autostart files which contain the line gnome-autostart-phase are currently completely skipped by systemd. This is because these are handled internally by gnome startup through other means.

The problem is a number of desktop files that need to run on kde too have this flag set. Ideally they should just create systemd user units, but we're not at this point universally yet.

A challenge is that gnome derived distributions also check this flag even thought their XDG_CURRENT_DESKTOP is not gnome. Hence the explicit "kde" check.

This patch creates a special path that if the flag is set, instead of skipping the file completely we change it to behave like "OnlyShowIn=kde". We now get the services to run, gnome will skip it like before. As a slight optimization if we would get conflicting OnlyShowIn lines we still skip the file completely.

Fixed https://github.com/systemd/systemd/issues/18791

### CODE REVIEW

**Comment by davidedmundson** [comment]
@benzea

**Comment by benzea** [comment]
Hmm, wouldn't it be easier to just add

`gnome` into `not_show_in`, i.e. something like:
```
if (service->gnome_autostart_phase) {
    if (strv_contains(service->only_show_in, "gnome")) {
        strv_remove(&service->only_show_in, "gnome");

        if (strv_isempty(service->only_show_in))
            return 0;
    }
    strv_extend(&service->not_show_in, "gnome");
}
```

Obviously, that means we might get into conflicts, if "gnome" is both in OnlyShowIn and NotShowIn

**Comment by davidedmundson** [comment]
>Hmm, wouldn't it be easier to just add gnome into not_show_in, i.e. something like:

It would have been far easier, but I was under the impression that we had some problem that Cinammon and co. are not technically gnome but still don't want these units, so I needed this more invasive blacklist-everything-else policy. 

However, now I can't find any mention of it on the original issue nor in our private chats. 
If this isn't an issue, I'm more than happy to go for that simpler approach.

**Comment by benzea** [comment]
Hmm, would that be a bug in Cinnamon? The $XDG_CURRENT_DESKTOP environment variable is allowed to contain multiple identifiers. So, if you copy the GNOME behaviour, should probably just leave 'gnome' in there and prefix your own new identifier, i.e. `cinnamon:gnome`, which means this *should* work just fine.

Now, no idea if everyone is getting it right, but maybe we should just try and see?

**Comment by davidedmundson** [comment]
> but maybe we should just try and see?

works for me. I'll make a new PR

**Pull request closed without merging**
