### PR TITLE
test: cover initrd->sysroot transition in TEST-24

### PR DESCRIPTION
**Pull request by mrc0mmand**
This should cover cases regarding devices with `OPTIONS+="db_persist"`
during initrd->sysroot transition.

See:
  * https://github.com/systemd/systemd/issues/23429
  * https://github.com/systemd/systemd/pull/23218
  * https://github.com/systemd/systemd/pull/23489
  * https://bugzilla.redhat.com/show_bug.cgi?id=2087225

---

On latest main this fails with:

```
# grep -E '(deadbeef|Switching root)' log.txt 
+ /bin/qemu-kvm -smp 8 -net none -m 512M -nographic -kernel /boot/vmlinuz-5.16.15-201.fc35.x86_64 -drive format=raw,cache=unsafe,file=/var/tmp/systemd-test.KkDt8V/cryptsetup.img -initrd /boot/initramfs'
[    0.000000] Command line: root=LABEL=systemd_boot rw raid=noautodetect rd.luks=0 loglevel=2 init=/usr/lib/systemd/systemd console=ttyS0 SYSTEMD_UNIT_PATH=/usr/lib/systemd/tests/testdata/testsuite-24t
[    0.016997] Kernel command line: root=LABEL=systemd_boot rw raid=noautodetect rd.luks=0 loglevel=2 init=/usr/lib/systemd/systemd console=ttyS0 SYSTEMD_UNIT_PATH=/usr/lib/systemd/tests/testdata/testst
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Installed new job dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device/start as 36
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Changed dead -> plugged
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Job 36 dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device/start finished, result=done
systemd-cryptsetup@test24_varcrypt.service: About to execute /usr/lib/systemd/systemd-cryptsetup attach test24_varcrypt /dev/disk/by-uuid/deadbeef-dead-dead-beef-000000000000 /run/systemd/cryptsetup/ke 
systemd-cryptsetup@test24_varcrypt.service: Executing: /usr/lib/systemd/systemd-cryptsetup attach test24_varcrypt /dev/disk/by-uuid/deadbeef-dead-dead-beef-000000000000 /run/systemd/cryptsetup/keydev-t 
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Installed new job dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device/nop as 69
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Job 69 dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device/nop finished, result=done
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Changed dead -> plugged
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Changed dead -> plugged
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Changed dead -> plugged
Switching root.
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Installed new job dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device/start as 165
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Collecting job.
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Job 165 dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device/start finished, result=collected
Unnecessary job was removed for dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device.
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Collecting.
systemd-cryptsetup@test24_varcrypt.service: Unit is stopped because bound to inactive unit dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device.
```

but with @mwilck's patches from https://github.com/systemd/systemd/pull/23489 the machine boots successfully:

```
# grep -E '(deadbeef|Switching root)' log.txt 
+ /bin/qemu-kvm -smp 8 -net none -m 512M -nographic -kernel /boot/vmlinuz-5.16.15-201.fc35.x86_64 -drive format=raw,cache=unsafe,file=/var/tmp/systemd-test.WYh5b1/cryptsetup.img -initrd /boot/initramfs'
[    0.000000] Command line: root=LABEL=systemd_boot rw raid=noautodetect rd.luks=0 loglevel=2 init=/usr/lib/systemd/systemd console=ttyS0 SYSTEMD_UNIT_PATH=/usr/lib/systemd/tests/testdata/testsuite-24t
[    0.016879] Kernel command line: root=LABEL=systemd_boot rw raid=noautodetect rd.luks=0 loglevel=2 init=/usr/lib/systemd/systemd console=ttyS0 SYSTEMD_UNIT_PATH=/usr/lib/systemd/tests/testdata/testst
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Installed new job dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device/start as 17
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Changed dead -> plugged
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Job 17 dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device/start finished, result=done
systemd-cryptsetup@test24_varcrypt.service: About to execute /usr/lib/systemd/systemd-cryptsetup attach test24_varcrypt /dev/disk/by-uuid/deadbeef-dead-dead-beef-000000000000 /run/systemd/cryptsetup/ke 
systemd-cryptsetup@test24_varcrypt.service: Executing: /usr/lib/systemd/systemd-cryptsetup attach test24_varcrypt /dev/disk/by-uuid/deadbeef-dead-dead-beef-000000000000 /run/systemd/cryptsetup/keydev-t 
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Installed new job dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device/nop as 70
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Job 70 dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device/nop finished, result=done
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Changed dead -> plugged
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Changed dead -> plugged
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Changed dead -> plugged
Switching root.
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Changed dead -> tentative
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Changed dead -> tentative
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Installed new job dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device/start as 159
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Collecting job.
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Job 159 dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device/start finished, result=collected
Unnecessary job was removed for dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device.
[    5.175361] systemd-udevd[624]: dm-0: /usr/lib/udev/rules.d/13-dm-disk.rules:18 LINK 'disk/by-id/dm-uuid-CRYPT-LUKS2-deadbeefdeaddeadbeef000000000000-test24_varcrypt'
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Changed tentative -> plugged
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Installed new job dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef0003
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Job 273 dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\e
dev-disk-by\x2duuid-deadbeef\x2ddead\x2ddead\x2dbeef\x2d000000000000.device: Changed tentative -> plugged
[   10.866797] systemd-udevd[624]: dm-0: /run/udev/links/disk\x2fby-id\x2fdm-uuid-CRYPT-LUKS2-deadbeefdeaddeadbeef000000000000-test24_varcrypt is modified, but its timestamp is not changed, updating ti.
[   11.144853] systemd-udevd[624]: dm-0: /run/udev/links/disk\x2fby-id\x2fdm-uuid-CRYPT-LUKS2-deadbeefdeaddeadbeef000000000000-test24_varcrypt is modified, but its timestamp is not changed, updating ti.
[   11.409157] systemd-udevd[624]: dm-0: /run/udev/links/disk\x2fby-id\x2fdm-uuid-CRYPT-LUKS2-deadbeefdeaddeadbeef000000000000-test24_varcrypt is modified, but its timestamp is not changed, updating ti.
[   11.673097] systemd-udevd[624]: dm-0: /run/udev/links/disk\x2fby-id\x2fdm-uuid-CRYPT-LUKS2-deadbeefdeaddeadbeef000000000000-test24_varcrypt is modified, but its timestamp is not changed, updating ti.
[   11.865447] systemd-udevd[624]: dm-0: /run/udev/links/disk\x2fby-id\x2fdm-uuid-CRYPT-LUKS2-deadbeefdeaddeadbeef000000000000-test24_varcrypt is modified, but its timestamp is not changed, updating ti.
[   11.990702] systemd-udevd[624]: dm-0: /run/udev/links/disk\x2fby-id\x2fdm-uuid-CRYPT-LUKS2-deadbeefdeaddeadbeef000000000000-test24_varcrypt is modified, but its timestamp is not changed, updating ti.
[   12.111854] systemd-udevd[624]: dm-0: /run/udev/links/disk\x2fby-id\x2fdm-uuid-CRYPT-LUKS2-deadbeefdeaddeadbeef000000000000-test24_varcrypt is modified, but its timestamp is not changed, updating ti.
[   12.264858] systemd-udevd[624]: dm-0: /run/udev/links/disk\x2fby-id\x2fdm-uuid-CRYPT-LUKS2-deadbeefdeaddeadbeef000000000000-test24_varcrypt is modified, but its timestamp is not changed, updating ti.
[   12.384919] systemd-udevd[624]: dm-0: /run/udev/links/disk\x2fby-id\x2fdm-uuid-CRYPT-LUKS2-deadbeefdeaddeadbeef000000000000-test24_varcrypt is modified, but its timestamp is not changed, updating ti.
[   12.418037] systemd-udevd[627]: sda2: /usr/lib/udev/rules.d/60-persistent-storage.rules:113 LINK 'disk/by-uuid/deadbeef-dead-dead-beef-000000000000'
[   12.487533] systemd-udevd[627]: sda2: /run/udev/links/disk\x2fby-uuid\x2fdeadbeef-dead-dead-beef-000000000000 is modified, but its timestamp is not changed, updating timestamp after 10ms.
[   12.516847] systemd-udevd[624]: dm-0: /usr/lib/udev/rules.d/13-dm-disk.rules:18 LINK 'disk/by-id/dm-uuid-CRYPT-LUKS2-deadbeefdeaddeadbeef000000000000-test24_varcrypt'
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Installed new job dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef0006
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Collecting job.
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Job 366 dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\d
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2ddisk_2dby_5cx2did_2ddm_5cx2duuid_5cx2dCRYPT_5cx2dLUKS2_5cx2ddeadbeefdeaddeadbeef000000000000_5cx2dtest24_5fa
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2ddisk_2dby_5cx2did_2ddm_5cx2duuid_5cx2dCRYPT_5cx2dLUKS2_5cx2ddeadbeefdeaddeadbeef000000000000_5cx2dtest24_5fa
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2ddisk_2dby_5cx2did_2ddm_5cx2duuid_5cx2dCRYPT_5cx2dLUKS2_5cx2ddeadbeefdeaddeadbeef000000000000_5cx2dtest24_5fa
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2ddisk_2dby_5cx2did_2ddm_5cx2duuid_5cx2dCRYPT_5cx2dLUKS2_5cx2ddeadbeefdeaddeadbeef000000000000_5cx2dtest24_5fa
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Installed new job dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef0008
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Collecting job.
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Job 468 dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\d
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2ddisk_2dby_5cx2did_2ddm_5cx2duuid_5cx2dCRYPT_5cx2dLUKS2_5cx2ddeadbeefdeaddeadbeef000000000000_5cx2dtest24_5fa
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2ddisk_2dby_5cx2did_2ddm_5cx2duuid_5cx2dCRYPT_5cx2dLUKS2_5cx2ddeadbeefdeaddeadbeef000000000000_5cx2dtest24_5fa
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2ddisk_2dby_5cx2did_2ddm_5cx2duuid_5cx2dCRYPT_5cx2dLUKS2_5cx2ddeadbeefdeaddeadbeef000000000000_5cx2dtest24_5fa
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/dev_2ddisk_2dby_5cx2did_2ddm_5cx2duuid_5cx2dCRYPT_5cx2dLUKS2_5cx2ddeadbeefdeaddeadbeef000000000000_5cx2dtest24_5fa
[   14.555330] systemd-udevd[708]: dm-0: No reference left for '/dev/disk/by-id/dm-uuid-CRYPT-LUKS2-deadbeefdeaddeadbeef000000000000-test24_varcrypt', removing
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Changed plugged -> dead
dev-disk-by\x2did-dm\x2duuid\x2dCRYPT\x2dLUKS2\x2ddeadbeefdeaddeadbeef000000000000\x2dtest24_varcrypt.device: Collecting.

```

/cc @yuwata

### CODE REVIEW

**Comment by yuwata** [comment]
Maybe this works only when initrd has dm-crypt?? Are there any way to build initrd rather than reusing the host's initrd?

**Comment by mrc0mmand** [comment]
> Maybe this works only when initrd has dm-crypt?? Are there any way to build initrd rather than reusing the host's initrd?

Ugh, that's unfortunate. I wonder what would be the best way to resolve it. In my opinion, generating a custom initrd in the setup phase of `TEST-24` if `$INITRD` is not set would be a way to go (so we would still respect any "external" INITRDs if set).

The issue with any scenario involving generating initrds is that we would either have to set an explicit dependency on `dracut` (at least for `TEST-24`), or write a helper that would deal with all initrd generator flavors here (`dracut`, `mkinitcpio`, `update-initramfs`, ...). 

Another option would be to expect the testbed initrd has all necessary modules (but we'd still need a way to check if the modules are there, to potentially skip the test altogether, which means using the initrd tools like `lsinitrd`, `lsinitcpio`, `lsinitramfs`, ...).

**Comment by mrc0mmand** [comment]
>E: Missing 'cryptsetup-initramfs' package for dm-crypt support in initrd

@bluca Can I haz `cryptsetup-initramfs` in Ubuntu CI please?

**Comment by bluca** [comment]
> > E: Missing 'cryptsetup-initramfs' package for dm-crypt support in initrd
> 
> @bluca Can I haz `cryptsetup-initramfs` in Ubuntu CI please?

your wish is my command: https://salsa.debian.org/systemd-team/systemd/-/commit/6c01f47fc6fae532dec8c8c9e27da68a03786c1f

**Comment by mrc0mmand** [comment]
Looks like Ubuntu CI is now content as well, sweet. @yuwata, feel free to merge this PR with #23489, I've used this one mainly to verify CIs.

**Comment by yuwata** [comment]
@mrc0mmand Thank you. It seems everything works as expected. Is it OK to merge this PR?

**Comment by bluca** [comment]
the amd64 test is not done yet

**Comment by yuwata** [comment]
> the amd64 test is not done yet

Yesh, let's wait for one more arch. Now, the test passes on ppc64:
```
I: Generating a custom initrd with dm-crypt support in '/var/tmp/systemd-test.icw28l/initrd.img'
(snip)
TEST-24-CRYPTSETUP RUN: cryptsetup systemd setup
+ timeout --foreground 1200 /bin/qemu-system-ppc64 -smp 1 -net none -m 512M -nographic -kernel /boot/vmlinux-5.4.0-113-generic -drive format=raw,cache=unsafe,file=/var/tmp/systemd-test.icw28l/cryptsetup.img -drive format=raw,cache=unsafe,file=/tmp/autopkgtest.WocLe4/build.5rW/systemd/test/TEST-24-CRYPTSETUP/keydev.img -initrd /var/tmp/systemd-test.icw28l/initrd.img -append 'root=LABEL=systemd_boot rw raid=noautodetect rd.luks=0 loglevel=2 init=/lib/systemd/systemd console=hvc0 SYSTEMD_UNIT_PATH=/usr/lib/systemd/tests/testdata/testsuite-24.units:/usr/lib/systemd/tests/testdata/units: systemd.unit=testsuite.target systemd.wants=testsuite-24.service systemd.wants=end.service rd.luks=1 luks.name=deadbeef-dead-dead-beef-000000000000=test24_varcrypt luks.key=deadbeef-dead-dead-beef-000000000000=/keyfile:LABEL=varcrypt_keydev'
(snip)
TEST-24-CRYPTSETUP RUN: cryptsetup systemd setup [OK]
make: Leaving directory '/tmp/autopkgtest.WocLe4/build.5rW/systemd/test/TEST-24-CRYPTSETUP'
[16:54:24] --x-- Result of TEST-24-CRYPTSETUP: 0 --x--
```

**Review by yuwata — APPROVED** [review]

**Comment by yuwata** [comment]
focal-amd64 failed but TEST-24 passes.

**Comment by mwilck** [comment]
@mrc0mmand, @yuwata — thanks a lot!!

**Comment by keszybz** [comment]
This was backported to v251.2, but not to v250-stable or earlier. I think we don't need it there, because those patches were filed in response to regressions reported with 251.

**Comment by yuwata** [comment]
https://github.com/systemd/systemd/issues/13775#issuecomment-1211271191 requests 4fc69e8a0949c2537019466f839d9b7aee5628c9 to be backported. Setting the backport label.

**Comment by keszybz** [comment]
Queued up for v250.9.

**Pull request merged**
