### PR TITLE
test: fix a syntax error in test-ukify

### LINKED ISSUE #28464: test: test-ukify fails with TypeError
### systemd version the issue has been seen with

HEAD

### Used distribution

Fedora 38

```
$ meson test -v test-ukify
ninja: no work to do.
ninja: Entering directory `/var/build'
[1/767] Generating version.h with a custom command
1/1 systemd / test-ukify RUNNING       
>>> PATH=/var/build:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/watanabe/bin SYSTEMD_LANGUAGE_FALLBACK_MAP=/home/watanabe/git/systemd/src/locale/language-fallback-map EFI_ADDON=/var/build/src/boot/efi/addonx64.efi.stub PROJECT_BUILD_ROOT=/var/build MALLOC_PERTURB_=52 /home/watanabe/git/systemd/src/ukify/test/test_ukify.py -v --flakes
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-7.2.2, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/watanabe/git/systemd/src/ukify/test
plugins: flakes-4.0.5
collecting ... collected 25 items

../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::flake-8 SKIPPED [  4%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_guess_efi_arch PASSED [  8%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_shell_join PASSED [ 12%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_round_up PASSED [ 16%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_namespace_creation PASSED [ 20%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_config_example PASSED [ 24%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_apply_config PASSED [ 28%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_parse_args_minimal PASSED [ 32%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_parse_args_many_deprecated PASSED [ 36%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_parse_args_many PASSED [ 40%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_parse_sections PASSED [ 44%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_config_priority PASSED [ 48%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_help PASSED [ 52%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_help_error_deprecated PASSED [ 56%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_help_error PASSED [ 60%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_check_splash PASSED [ 64%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_basic_operation PASSED [ 68%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_sections PASSED [ 72%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_addon PASSED [ 76%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_uname_scraping PASSED [ 80%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_efi_signing_sbsign SKIPPED [ 84%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_efi_signing_pesign SKIPPED [ 88%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_pcr_signing FAILED [ 92%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_pcr_signing2 PASSED [ 96%]
../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_key_cert_generation PASSED [100%]

=================================== FAILURES ===================================
_______________________________ test_pcr_signing _______________________________

kernel_initrd = ['--linux', '/boot/af1ad4213fa64709b7f68ade7f5c7577/6.3.6-200.fc38.x86_64/linux', '--initrd', '/boot/af1ad4213fa64709b7f68ade7f5c7577/6.3.6-200.fc38.x86_64/initrd']
tmpdir = local('/tmp/pytest-of-watanabe/pytest-4/test_pcr_signing0')

    def test_pcr_signing(kernel_initrd, tmpdir):
        if kernel_initrd is None:
            pytest.skip('linux+initrd not found')
    
        ourdir = pathlib.Path(__file__).parent
        pub = unbase64(ourdir / 'example.tpm2-pcr-public.pem.base64')
        priv = unbase64(ourdir / 'example.tpm2-pcr-private.pem.base64')
    
        output = f'{tmpdir}/signed.efi'
        opts = ukify.parse_args([
            'build',
            *kernel_initrd,
            f'--output={output}',
            '--uname=1.2.3',
            '--cmdline=ARG1 ARG2 ARG3',
            '--os-release=ID=foobar\n',
            '--pcr-banks=sha1',   # use sha1 because it doesn't really matter
            f'--pcr-private-key={priv.name}',
        ])
    
        # If the public key is not explicitly specified, it is derived automatically. Let's make sure everything
        # works as expected both when the public keys is specified explicitly and when it is derived from the
        # private key.
        for extra in ([f'--pcrpkey={pub.name}', f'--pcr-public-key={pub.name}'], []):
            try:
>               ukify.check_inputs(opts + extra)
E               TypeError: unsupported operand type(s) for +: 'Namespace' and 'list'

/home/watanabe/git/systemd/src/ukify/test/test_ukify.py:620: TypeError
----------------------------- Captured stdout call -----------------------------
Host arch 'x86_64', EFI arch 'x64'
=========================== short test summary info ============================
FAILED ../../home/watanabe/git/systemd/src/ukify/test/test_ukify.py::test_pcr_signing
=================== 1 failed, 21 passed, 3 skipped in 2.36s ====================
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
1/1 systemd / test-ukify FAIL            2.64s   exit status 1


Summary of Failures:

1/1 systemd / test-ukify FAIL            2.64s   exit status 1

Ok:                 0   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0
```

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for d7d36252e5fdc345b110f824031e20f41ee75e86.

Fixes #28464.

### CODE REVIEW

**Comment by yuwata** [comment]
@mrc0mmand I have no idea why our CIs did not detect such error... The test never runs on CIs?

**Comment by mrc0mmand** [comment]
```

================================== 480/1552 ==================================
test:         systemd / test-ukify
start time:   06:00:19
duration:     1.30s
result:       exit status 0
command:      PROJECT_BUILD_ROOT=/systemd-meson-build SYSTEMD_LANGUAGE_FALLBACK_MAP=/build/src/locale/language-fallback-map PATH=/systemd-meson-build:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl EFI_ADDON=/systemd-meson-build/src/boot/efi/addonx64.efi.stub MALLOC_PERTURB_=222 /build/src/ukify/test/test_ukify.py -v
----------------------------------- stdout -----------------------------------
============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-7.4.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /build/src/ukify/test
collecting ... collected 24 items

../build/src/ukify/test/test_ukify.py::test_guess_efi_arch PASSED        [  4%]
../build/src/ukify/test/test_ukify.py::test_shell_join PASSED            [  8%]
../build/src/ukify/test/test_ukify.py::test_round_up PASSED              [ 12%]
../build/src/ukify/test/test_ukify.py::test_namespace_creation PASSED    [ 16%]
../build/src/ukify/test/test_ukify.py::test_config_example PASSED        [ 20%]
../build/src/ukify/test/test_ukify.py::test_apply_config PASSED          [ 25%]
../build/src/ukify/test/test_ukify.py::test_parse_args_minimal PASSED    [ 29%]
../build/src/ukify/test/test_ukify.py::test_parse_args_many_deprecated PASSED [ 33%]
../build/src/ukify/test/test_ukify.py::test_parse_args_many PASSED       [ 37%]
../build/src/ukify/test/test_ukify.py::test_parse_sections PASSED        [ 41%]
../build/src/ukify/test/test_ukify.py::test_config_priority PASSED       [ 45%]
../build/src/ukify/test/test_ukify.py::test_help PASSED                  [ 50%]
../build/src/ukify/test/test_ukify.py::test_help_error_deprecated PASSED [ 54%]
../build/src/ukify/test/test_ukify.py::test_help_error PASSED            [ 58%]
../build/src/ukify/test/test_ukify.py::test_check_splash SKIPPED (PI...) [ 62%]
../build/src/ukify/test/test_ukify.py::test_basic_operation SKIPPED      [ 66%]
../build/src/ukify/test/test_ukify.py::test_sections SKIPPED (linux+...) [ 70%]
../build/src/ukify/test/test_ukify.py::test_addon PASSED                 [ 75%]
../build/src/ukify/test/test_ukify.py::test_uname_scraping SKIPPED (...) [ 79%]
../build/src/ukify/test/test_ukify.py::test_efi_signing_sbsign SKIPPED   [ 83%]
../build/src/ukify/test/test_ukify.py::test_efi_signing_pesign SKIPPED   [ 87%]

../build/src/ukify/test/test_ukify.py::test_pcr_signing SKIPPED (lin...) [ 91%]
../build/src/ukify/test/test_ukify.py::test_pcr_signing2 SKIPPED (li...) [ 95%]

../build/src/ukify/test/test_ukify.py::test_key_cert_generation PASSED   [100%]

======================== 16 passed, 8 skipped in 0.65s =========================
````

It looks half of the tests are skipped (at least in the Arch Linux job).

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by DaanDeMeyer** [comment]
No need to wait for CI I guess since the test isn't running anywhere

**Comment by mrc0mmand** [comment]
> ...
> It looks like half of the tests are skipped (at least in the Arch Linux job).

I'll upgrade the Arch Linux VMs from BIOS to GPT/UEFI, to hopefully address this.

**Pull request merged**
