### PR TITLE
test: add fuzzer regression testing

### PR DESCRIPTION
**Pull request by titanous**
This adds a script, `test/run-fuzz-regression-tests.sh` that can be used to ensure that bugs found by the fuzzers do not regress after they are fixed.

In order to implement this, the Semaphore CI config will need to be modified after this is merged by someone with access:

- Before the step where the `zesty` repo is added, add the following (it could potentially be merged with other apt-get steps)
  - `curl -s https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -`
  - `add-apt-repository -y 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'`
  - `add-apt-repository -y ppa:ubuntu-toolchain-r/test`
  - `apt-get update`
  - `apt-get install -y clang-6.0`
- Add a new step at the end: `CC=clang-6.0 CXX=clang-6.0 test/run-fuzz-regression-tests.sh`

### CODE REVIEW

**Comment by keszybz** [comment]
Thanks. We can update semaphore config, it's no problem.

But I think that we need a different approach to integrate this into testing. IIUC, we don't actually need clang to compile this. So those checks can be removed. Also, it'd be much better to integrate this as normal meson tests. Instead of a separate meson+ninja step with special configuration and then a special target that needs to be invoked, I'd like to see additional meson `custom_target`s that would compile the fuzzers with the right sanitizer, and additional meson `test`s for the cases in fuzz-regressions. Those targets might need to be conditionalized on presence of the sanitizer libraries. Doing this will also require hardcoding the sanitizer definitions for those targets in our meson config, and we'll not be able to reuse meson's b_sanitize, which is unfortunate, but it's worth the trouble. We already have too many ways to run tests and integrating this in the standard meson build is a significant simplification for the user.

**Comment by titanous** [comment]
I think clang is required. While GCC does support ASAN, it doesn't support MSAN and it has different flags for UBSAN. Additionally, the version packaged with whatever old version of GCC is in use will not match the version that is in use on OSS-Fuzz so some regression tests may false negative in the future.

I'm happy to re-architect if it makes sense, but I think having a recent version of clang/LLVM is a hard requirement so that we don't false negative.

**Comment by keszybz** [comment]
OK, makes sense. But that just means there should be a check if the compiler is clang and if it is new enough. If not, the test should be skipped. Then we'll just install a new-enough clang through the CI config you provided.

**Comment by keszybz** [comment]
Yeah, a separate build directory is required. See my attempt at hooking this into meson tests in #7933.

**Pull request closed without merging**
