### PR TITLE
executor: apply LogLevelMax earlier

### PR DESCRIPTION
**Pull request by bluca**
SELinux logs before we have a chance to apply it, move it up as it breaks TEST-04-JOURNAL:

```
[  408.578624] testsuite-04.sh[11463]: ++ journalctl -b -q -u silent-success.service
[  408.578743] testsuite-04.sh[11098]: + [[ -z Dec 03 13:38:41 H systemd-executor[11459]: SELinux enabled state cached to: disabled ]]
```

Follow-up for: bb5232b6a3b8a

### CODE REVIEW

**Review by mrc0mmand — APPROVED** [review]
Thank you! I had this on my overly long TODO list, glad that somebody beat me to it.

**Review by yuwata — APPROVED** [review]

**Comment by mrc0mmand** [comment]
Hmpf, one of the tonight's cron jobs failed with:

```
[ 2031.505743] testsuite-04.sh[11156]: + systemctl start silent-success
[ 2031.594147] testsuite-04.sh[11156]: + journalctl --sync
[ 2031.616978] testsuite-04.sh[11515]: ++ journalctl -b -q -u silent-success.service
[ 2031.637841] testsuite-04.sh[11156]: + [[ -z Dec 13 00:54:57 H systemd-executor[11511]: SELinux enabled state cached to: disabled ]]
[ 2031.638222] testsuite-04.sh[42]: + echo 'Subtest /usr/lib/systemd/tests/testdata/units/testsuite-04.journal.sh failed'
[ 2031.638222] testsuite-04.sh[42]: Subtest /usr/lib/systemd/tests/testdata/units/testsuite-04.journal.sh failed
[ 2031.638696] testsuite-04.sh[42]: + return 1
[ 2031.638696] testsuite-04.sh[42]: + journalctl --rotate --vacuum-size=20M
```

So it looks like there's still some way that allows that message to sneak it.

**Comment by bluca** [comment]
That's at log_trace now, is the nightly job built with trace level enabled?

**Comment by mrc0mmand** [comment]
> That's at log_trace now, is the nightly job built with trace level enabled?

Yup, it's built with `-Dlog-trace=true`. I thought that with this PR this shouldn't matter, since the unit in question has `LogLevelMax=notice`.

**Comment by bluca** [comment]
Is there any indication in the log as to where it's coming from? Setting the max level is done as the very first real action after deserializing, so the only thing left would be to set pid1 itself to notice level before the test, so that it's used from the moment it starts. But the unit option necessarily comes through serialization, so it can be applied only after deserialization. But it's weird as I can't see anything that would trigger a selinux check before exec_invoke is called

**Comment by mrc0mmand** [comment]
```
$ journalctl -o short-monotonic --no-hostname --file system.journal _SYSTEMD_UNIT=silent-success.service 
[ 2031.597177] systemd-executor[11511]: SELinux enabled state cached to: disabled
```
```
$ journalctl -o short-monotonic --no-hostname --file system.journal _SYSTEMD_UNIT=silent-success.service -o export
__CURSOR=s=74b84d05dc674b9387d11b0a184b88b1;i=10bd;b=a49f5bb061ff4bbe9f81e959edfc2f13;m=7917b679;t=60c599db674d1;x=6f8a7b35850b03ad
__REALTIME_TIMESTAMP=1702428897866961
__MONOTONIC_TIMESTAMP=2031597177
_BOOT_ID=a49f5bb061ff4bbe9f81e959edfc2f13
PRIORITY=7
SYSLOG_FACILITY=3
_TRANSPORT=journal
_MACHINE_ID=0d86f37af22041bb81c266b7fd15fde8
_HOSTNAME=H
_RUNTIME_SCOPE=system
CODE_FILE=src/shared/selinux-util.c
CODE_LINE=79
CODE_FUNC=mac_selinux_use
SYSLOG_IDENTIFIER=systemd-executor
MESSAGE=SELinux enabled state cached to: disabled
_UID=0
_GID=0
_SYSTEMD_SLICE=system.slice
_COMM=3
_CAP_EFFECTIVE=fdecafff
TID=11511
_PID=11511
_SYSTEMD_CGROUP=/system.slice/silent-success.service
_SYSTEMD_UNIT=silent-success.service
_SOURCE_REALTIME_TIMESTAMP=1702428897821687
```

**Comment by bluca** [comment]
I can't reproduce this on a debian test mkosi image - I see the selinux message with LogLevelMax=debug but not with =notice running `systemd-run -p LogLevelMax=notice --unit test.service true`

**Comment by mrc0mmand** [comment]
I saw this happen only once, so I guess it's a race somewhere.

**Comment by bluca** [comment]
ran it 4.4k times in a row, still no luck - is there some specific configuration in the image? Some top-level drop-ins that enable some option, perhaps?

**Comment by mrc0mmand** [comment]
This particular fail was from a coverage run (i.e. built with `-Db_coverage=true` + the accompanying shenanigans the shell spaghetti do when running with coverage).

**Comment by mrc0mmand** [comment]
It looks like this happens in regular runs as well - this is from an s390x Ubuntu CI job:

```
3302s [  433.993482] testsuite-04.sh[11492]: ++ journalctl -b -o cat -t 319ad7d9dcec4854a5ac8ac4ae87f639 --output-fields=MESSAGE
3302s [  433.993868] testsuite-04.sh[11493]: ++ grep -Pc '^(This will|usually fail|and be truncated)$'
3302s [  433.996942] testsuite-04.sh[11134]: + [[ 3 -eq 3 ]]
3302s [  433.996993] testsuite-04.sh[11134]: + systemctl start silent-success
3302s [  434.006333] testsuite-04.sh[11134]: + journalctl --sync
3302s [  434.015283] testsuite-04.sh[11499]: ++ journalctl -b -q -u silent-success.service
3302s [  434.019511] testsuite-04.sh[11134]: + [[ -z Dec 22 20:49:39 H systemd-executor[11495]: SELinux enabled state cached to: disabled ]]
3302s [  434.019552] testsuite-04.sh[46]: + echo 'Subtest /usr/lib/systemd/tests/testdata/units/testsuite-04.journal.sh failed'
3302s [  434.019552] testsuite-04.sh[46]: Subtest /usr/lib/systemd/tests/testdata/units/testsuite-04.journal.sh failed
3302s [  434.019552] testsuite-04.sh[46]: + return 1
3302s [  434.019552] testsuite-04.sh[46]: + journalctl --rotate --vacuum-size=20M
3302s [  434.028745] journalctl[11500]: Vacuuming done, freed 0B of archived journals from /var/log/journal.
3302s [  434.028979] journalctl[11500]: Vacuuming done, freed 0B of archived journals from /run/log/journal.
3302s [  434.029071] journalctl[11500]: Vacuuming done, freed 0B of archived journals from /var/log/journal/0e5a0df02c594aa597dc80cb3140d7b1.
3302s [  434.031096] systemd[1]: testsuite-04.service: Failed with result 'exit-code'.
3302s [  434.031183] systemd[1]: Failed to start TEST-04-JOURNAL.
3302s [  434.067164] systemd[1]: end.service: Main process exited, code=killed, status=15/TERM
3302s [  434.067457] systemd[1]: end.service: Failed with result 'signal'.
```

Full log: https://autopkgtest.ubuntu.com/results/autopkgtest-jammy-upstream-systemd-ci-systemd-ci/jammy/amd64/s/systemd-upstream/20231222_214856_dc046@/log.gz

**Pull request merged**
