### PR TITLE
build-sys: use -Wextra if available

### PR DESCRIPTION
**Pull request by keszybz**
C.f. #6284.

### CODE REVIEW

**Comment by fsateler** [comment]
The PR message doesn't really match the patch...

(I forgot I could change that myself... sorry for the noise)

**Comment by keszybz** [comment]
I force-pushed soon after submitting, with a different change, different commit message, and then I edited the PR title and description. I should've probably create a new PR ;)

**Comment by benjarobin** [comment]
@keszybz I did compare configure.ac and meson.build, there are still some difference, it missing in meson.build :
```
-Wall
-Wno-format-signedness
-Wno-missing-field-initializers
-Wno-unused-parameter
-Wno-unused-result
```

**Comment by keszybz** [comment]
'-Wall' is added by meson automatically. The other ones are detected and added, just in a special way https://github.com/systemd/systemd/blob/master/meson.build#L275.

**Comment by tixxdz** [comment]
Hi @keszybz,

I still don't know meson I guess there is a way to check the final CFLAGS that were auto added ?

Patch looks good merging, thanks!

**Comment by keszybz** [comment]
> a way to check the final CFLAGS that were auto added

If you mean to check what the final command line is, then just `-v` is enough: it makes ninja print the actual command line.

**Pull request merged**
