### PR TITLE
Only show loaded units from list-units, unless with --state.

### PR DESCRIPTION
**Pull request by chaoren**
$ systemctl --help | grep list-units
  list-units [PATTERN...]         List loaded units

### CODE REVIEW

**Comment by chaoren** [comment]
The --help output is actually a bit contradictory:

```
     --state=STATE    List units with particular *LOAD* or SUB or ACTIVE state

  -a --all            Show all *loaded* units/properties, including dead/empty
                      ones. To list all units installed on the system, use
                      the 'list-unit-files' command instead.

  list-units [PATTERN...]         List *loaded* units
```

Should this be loaded only, unless specifically asked for with --state?

**Comment by arvidjaar** [comment]
This makes `--all` noop.

You should rather fix documentation. Here we have unfortunately confusion between strict internal unit state "loaded" (meaning - unit definition was found on disk and read) and the fact, that "list-units" only shows units that are currently known to systemd. Those units may not be "loaded" yet, but still they are referenced and so exist internally.

Rereading above, I am sure this does not make it any more clear :)

May be manual should put it "Show all units, currently _known_ to systemd".

**Comment by chaoren** [comment]
> This makes `--all` noop.

`--all` would still be meaningful for loaded but inactive units.

**Comment by arvidjaar** [comment]
`arg_states` is empty by default so your condition is always true unless unit state is "loaded". But that is moot, because patch is based on misinterpretation as I explained earlier.

**Comment by chaoren** [comment]
> `arg_states` is empty by default so your condition is always true unless unit state is "loaded".

Well, yeah. `load_state` has to be `"loaded"`, but `active_state` and `sub_state` could be anything.

> But that is moot, because patch is based on misinterpretation as I explained earlier.

Please help me understand the misinterpretation.

> strict internal unit state "loaded" (meaning - unit definition was found on disk and read)

Yes. This seems to be the definition of `load_state` being `"loaded"`. Are you saying that this is _not_ what's meant by the documentation? What does the loaded in the documentation mean then?

There only 5 other load states: `stub`, `not-found`, `error`, `merged`, `masked`. None of them seem to fit the description:

> Those units may not be "loaded" yet, but still they are referenced and so exist internally.

**Comment by arvidjaar** [comment]
> Are you saying that this is not what's meant by the documentation?

What I say is that text you quoted does not refer to unit `load_state` in narrow sense but to the fact that unit is known to systemd.

> None of them seem to fit the description

Sorry? How can systemd show unit if systemd does not know about it? When unit is first referenced, stub is created for it. From this point on unit can be shown in unit list with `load_state` being `stub`. No definition was yet seen but unit is already known and "exists internally". Later this stub transitions to either `loaded` state or `not-found` state. And `masked` is obvious valid `load_state`. Not sure when `merged` happens.

**Comment by keszybz** [comment]
@chaoren Consider a masked but failed service:

```
$ systemctl list-units|grep foobar
● foobar.service   masked failed failed   foobar.service
```

We want to show failed services in the list, this is very important for diagnosing issues, so foobar.service should be shown. But with your patch the fact that it is masked would take higher priority.

Instead, like @arvidjaar said (https://github.com/systemd/systemd/pull/3967#issuecomment-239996340) help or man should be fixed instead.

**Comment by chaoren** [comment]
The reason I noticed this is because `systemctl list-units --state inactive,failed` is returning a bunch of `not-found` units that's only pulled in due to `Before` and `After` rules, and it's messing up [shell completion](https://github.com/systemd/systemd/blob/master/shell-completion/bash/systemctl.in#L61).

Would it make sense to check against `not-found` instead of checking for `loaded`, and change documentation to say "list found units" instead of "list loaded units"?

**Comment by arvidjaar** [comment]
> Would it make sense to check against not-found instead of checking for loaded

No. If this messes up completion, you should fix completion. E.g. by explicitly using `--state loaded` or by adding support for `--state !not-found` (I have not looked at what completion does and which values are appropriate).

**Comment by chaoren** [comment]
> E.g. by explicitly using --state loaded or by adding support for --state !not-found (I have not looked at what completion does and which values are appropriate).

`systemctl list-units --state inactive,failed,loaded` shows `inactive` OR `failed` OR `loaded` so it would include everything.
Adding logical operators like `and` or `not` seems overkill.

**Comment by chaoren** [comment]
> No. If this messes up completion, you should fix completion.

But it's more than that. I don't think `--all` should be listing units that are only referenced, but don't actually exist.

**Comment by arvidjaar** [comment]
>  it's messing up shell completion

Shell completion already filters by CanStart which returns false if unit is not loaded.

**Comment by keszybz** [comment]
If shell completion cannot be super precise and offers too many completions, that's not nice, but unfortunately it happens quite often and we just have to live with that. Fast and simple completion is more important than getting it right every time.

`--all` should list all "known" units. There are only two levels: the default and `--all`, and the latter should just show all units that we have state for.

**Comment by chaoren** [comment]
> Shell completion already filters by CanStart which returns false if unit is not loaded.

It's not working correctly apparently.

> If shell completion cannot be super precise and offers too many completions, that's not nice, but unfortunately it happens quite often and we just have to live with that.

The problem is not just incorrect completion. I can live with that.
The problem is the obnoxious error message due to `not-found` units, like this:

```
systemctl start <TAB>
Unit auditd.service could not be found.
```

**Comment by keszybz** [comment]
> systemctl start <TAB>
> Unit auditd.service could not be found.

Oh, that's fallout from recent changes to give better error messages for not-founds units. See #3856.

**Comment by chaoren** [comment]
Alright, I guess I will close this change and file two separate issues instead:
1. For confusing documentation referring to a different kind of `loaded` units.
2. For the completion bug due to the error message for `not-found` units.

Since I don't think I can succinctly explain the mess between the different loaded states that are in use, and the completion problem is apparently different from what I thought was the case.

**Comment by arvidjaar** [comment]
> It's not working correctly apparently.

I just tried it on openSUSE Tumbleweed that is using 228 (I am not sure what exactly is backported additionally) and completion for `systemctl start` does not include `not-found` units. Unfortunately you never mentioned your version of systemd.

**Comment by chaoren** [comment]
> Unfortunately you never mentioned your version of systemd.

It's in the issues I filed. It's a recent bug.

**Pull request closed without merging**
