### PR TITLE
chase: refuse CHASE_MKDIR_0755 without CHASE_NONEXISTENT or CHASE_PARENT

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Review by DaanDeMeyer — CHANGES_REQUESTED** [review]
So what I was going for with `CHASE_MKDIR_0755` is that it creates all directories up to the final component but never the final component of the path. To create the final component as well, you'd have to use `chase_and_openat()` with `O_CREAT`. I don't think the behavior of `CHASE_MKDIR_0755` should be affected by `CHASE_PARENT`. `CHASE_PARENT` should only affect which file descriptor is returned by chaseat(). Does that make sense?

**Comment by yuwata** [comment]
Currently, CHASE_PARENT (or CHASE_NONEXISTENT) needs to be set with CHASE_MKDIR_0755. Then, that means the flag _is_ affected by `CHASE_PARENT` in an inverse direction of this PR.
So, CHASE_MKDIR_0755 and CHASE_PARENT cannot be independent even the current behavior is kept.

**Comment by yuwata** [comment]
If you want to keep the current behavior, then I'd like to extend the comment and add the following assertion:
```c
assert(!FLAGS_SET(flags, CHASE_MKDIR_0755) || (flags & (CHASE_PARENT | CHASE_NONEXISTENT)));
```

**Comment by yuwata** [comment]
(BTW, I am working on `mkdir()` variants with `chase()`. I'd like to drop recursion in `mkdir_p_root()`.)

**Comment by DaanDeMeyer** [comment]
I would go for the assert() and extending the comment. Note that you can use `CHASE_MDKIR_0755` without either of the flags with chase_at_and_openat(), but only because that functions adds `CHASE_PARENT` itself when calling chaseat().

**Comment by yuwata** [comment]
> I would go for the assert() and extending the comment. Note that you can use `CHASE_MDKIR_0755` without either of the flags with chase_at_and_openat(), but only because that functions adds `CHASE_PARENT` itself when calling chaseat().

OK. Let's take this way. Updated. PTAL.

**Review by DaanDeMeyer — APPROVED** [review]

**Pull request merged**
