### PR TITLE
network: fix hardware address handling

### LINKED ISSUE #23546: dhcpv6client can not get the prefix
**systemd version the issue has been seen with**
 systemd 251.1  …

**Used distribution**
Archlinux …

**Linux kernel version used** (`uname -a`)

5.15.43-1-lts   `…`

**CPU architecture issue was seen on**
 > …

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
/etc/systemd/network/ppp0.network
[Match]
Type=ppp
[Network]
DHCP=ipv6
IPv6DuplicateAddressDetection=1
IPv6PrivacyExtensions=yes
[IPv6AcceptRA]
DHCPv6Client=always

/etc/systemd/network/lan0.network
[Match]
MACAddress=00: xxxxxxxx
[Network]
Address = 192.168.3.1/24
DHCPServer = yes
IPMasquerade=ipv4
IPv6SendRA=yes
DHCPPrefixDelegation=yes
IPv6DuplicateAddressDetection=1
IPv6PrivacyExtensions=yes
LinkLocalAddressing=ipv6
MulticastDNS=true
[DHCPServer]
PoolOffset = 100
PoolSize = 40
SendOption=26:uint16:1492
[DHCPPrefixDelegation]
SubnetId=0x1
[IPv6SendRA]
RouterLifetimeSec=3600
Managed=true
OtherInformation=true
EmitDNS=true
DNS=2400:3200::1
DNSLifetimeSec=1800





May 28 21:21:13 gabox systemd-networkd[14877]: rtnl: received address for link '14' we don't know about, ignoring.
May 28 21:21:13 gabox systemd-networkd[14877]: rtnl: received route message for link (14) we do not know about, ignoring
May 28 21:21:13 gabox systemd-networkd[14877]: rtnl: received route message for link (14) we do not know about, ignoring
May 28 21:21:13 gabox systemd-networkd[14877]: rtnl: received address for link '14' we don't know about, ignoring.
May 28 21:21:13 gabox systemd-networkd[14877]: rtnl: received route message for link (14) we do not know about, ignoring
May 28 21:21:13 gabox systemd-networkd[14877]: rtnl: received route message for link (14) we do not know about, ignoring
May 28 21:21:13 gabox systemd-networkd[14877]: rtnl: received route message for link (14) we do not know about, ignoring
…
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #23546.

### CODE REVIEW

**Comment by yuwata** [comment]
@freswa Thank you for testing this PR. I forgot to revert one more commit. Hopefully, now it works. Please test again!

**Comment by freswa** [comment]
@yuwata Unfortunately no. Still no PD.

**Comment by yuwata** [comment]
Hmm, please provide the debugging log of networkd...

**Comment by yuwata** [comment]
Thanks. Now NDisc and DHCPv6 client running on the ppp interface, yay! But unfortunately DHCPv6 client got an error.

Could you try to dump the DHCPv6 packet?

**Comment by yuwata** [comment]
Also, could you try to add the following to .network file for the ppp interface?
```
[DHCPv6]
UseAddress=no
```

**Comment by freswa** [comment]
Request:
```
Frame 5: 173 bytes on wire (1384 bits), 173 bytes captured (1384 bits)
    Encapsulation type: Linux cooked-mode capture v1 (25)
    Arrival Time: Jul 14, 2022 00:50:23.166458000 CEST
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1657752623.166458000 seconds
    [Time delta from previous captured frame: 1.043610000 seconds]
    [Time delta from previous displayed frame: 1.043610000 seconds]
    [Time since reference or first frame: 8.414498000 seconds]
    Frame Number: 5
    Frame Length: 173 bytes (1384 bits)
    Capture Length: 173 bytes (1384 bits)
    [Frame is marked: True]
    [Frame is ignored: False]
    [Protocols in frame: sll:ethertype:ipv6:udp:dhcpv6]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Linux cooked capture v1
Internet Protocol Version 6, Src: fe80::9de3:9e8a:b89:ffba, Dst: ff02::1:2
    0110 .... = Version: 6
    .... 0000 0000 .... .... .... .... .... = Traffic Class: 0x00 (DSCP: CS0, ECN: Not-ECT)
    .... 1100 0001 1100 1010 0101 = Flow Label: 0xc1ca5
    Payload Length: 117
    Next Header: UDP (17)
    Hop Limit: 1
    Source Address: fe80::9de3:9e8a:b89:ffba
    Destination Address: ff02::1:2
User Datagram Protocol, Src Port: 546, Dst Port: 547
    Source Port: 546
    Destination Port: 547
    Length: 117
    Checksum: 0xb3bd [unverified]
    [Checksum Status: Unverified]
    [Stream index: 0]
    [Timestamps]
    UDP payload (109 bytes)
DHCPv6
    Message type: Solicit (1)
    Transaction ID: 0xf2ee4a
    Rapid Commit
        Option: Rapid Commit (14)
        Length: 0
    Identity Association for Non-temporary Address
        Option: Identity Association for Non-temporary Address (3)
        Length: 12
        IAID: 59e41b4a
        T1: 0
        T2: 0
    Identity Association for Prefix Delegation
        Option: Identity Association for Prefix Delegation (25)
        Length: 41
        IAID: 59e41b4a
        T1: 0
        T2: 0
        IA Prefix
            Option: IA Prefix (26)
            Length: 25
            Preferred lifetime: 0
            Valid lifetime: 0
            Prefix length: 56
            Prefix address: ::
    Client Fully Qualified Domain Name
        Option: Client Fully Qualified Domain Name (39)
        Length: 6
        Flags: 0x01  [CLIENT wants SERVER to update both its AAAA and PTR RRs]
        Partial domain name: loki
    Option Request
        Option: Option Request (6)
        Length: 2
        Requested Option code: SOL_MAX_RT (82)
    Client Identifier
        Option: Client Identifier (1)
        Length: 14
        DUID: 00020000ab115abde43347c29141
        DUID Type: assigned by vendor based on Enterprise number (2)
        Enterprise ID: Tom Gundersen (systemd) (43793)
        Identifier: 5abde43347c29141
    Elapsed time
        Option: Elapsed time (8)
        Length: 2
        Elapsed time: 1050ms

```
Reply:
```
Frame 6: 228 bytes on wire (1824 bits), 228 bytes captured (1824 bits)
    Encapsulation type: Linux cooked-mode capture v1 (25)
    Arrival Time: Jul 14, 2022 00:50:23.171126000 CEST
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1657752623.171126000 seconds
    [Time delta from previous captured frame: 0.004668000 seconds]
    [Time delta from previous displayed frame: 0.004668000 seconds]
    [Time since reference or first frame: 8.419166000 seconds]
    Frame Number: 6
    Frame Length: 228 bytes (1824 bits)
    Capture Length: 228 bytes (1824 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: sll:ethertype:ipv6:udp:dhcpv6]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Linux cooked capture v1
Internet Protocol Version 6, Src: fe80::e86:10ff:fef6:ae19, Dst: fe80::9de3:9e8a:b89:ffba
    0110 .... = Version: 6
    .... 1100 0000 .... .... .... .... .... = Traffic Class: 0xc0 (DSCP: CS6, ECN: Not-ECT)
    .... 0000 0000 0000 0000 0000 = Flow Label: 0x00000
    Payload Length: 172
    Next Header: UDP (17)
    Hop Limit: 64
    Source Address: fe80::e86:10ff:fef6:ae19
    Destination Address: fe80::9de3:9e8a:b89:ffba
    [Source SLAAC MAC: JuniperN_f6:ae:19 (0c:86:10:f6:ae:19)]
User Datagram Protocol, Src Port: 547, Dst Port: 546
    Source Port: 547
    Destination Port: 546
    Length: 172
    Checksum: 0xedf0 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 1]
    [Timestamps]
    UDP payload (164 bytes)
DHCPv6
    Message type: Reply (7)
    Transaction ID: 0xf2ee4a
    Client Identifier
        Option: Client Identifier (1)
        Length: 14
        DUID: 00020000ab115abde43347c29141
        DUID Type: assigned by vendor based on Enterprise number (2)
        Enterprise ID: Tom Gundersen (systemd) (43793)
        Identifier: 5abde43347c29141
    Server Identifier
        Option: Server Identifier (2)
        Length: 26
        DUID: 00020000058330633a38363a31303a66363a62333a6330000000
        DUID Type: assigned by vendor based on Enterprise number (2)
        Enterprise ID: Juniper Networks/Funk Software (1411)
        Identifier: 30633a38363a31303a66363a62333a6330000000
    Identity Association for Non-temporary Address
        Option: Identity Association for Non-temporary Address (3)
        Length: 59
        IAID: 59e41b4a
        T1: 0
        T2: 0
        Status code
            Option: Status code (13)
            Length: 43
            Status Code: NoAddrAvail (2)
            Status Message: No addresses have been assigned for IA_NA
    Identity Association for Prefix Delegation
        Option: Identity Association for Prefix Delegation (25)
        Length: 41
        IAID: 59e41b4a
        T1: 900
        T2: 1440
        IA Prefix
            Option: IA Prefix (26)
            Length: 25
            Preferred lifetime: 1800
            Valid lifetime: 14400
            Prefix length: 56
            Prefix address: aaaa:bbbb:cccc:f000::
    Rapid Commit
        Option: Rapid Commit (14)
        Length: 0
```

**Comment by freswa** [comment]
> Also, could you try to add the following to .network file for the ppp interface?

```
[DHCPv6]
UseAddress=no
```
Doesn't fix it. The error is a bit shorter though:
```
Jul 14 00:58:26 loki systemd-networkd[906]: ppp42: DHCPv6 client: Sent Solicit
Jul 14 00:58:26 loki systemd-networkd[906]: ppp42: DHCPv6 client: Next retransmission in 15s
Jul 14 00:58:26 loki systemd-networkd[906]: ppp42: DHCPv6 client: Failed to process received Reply message, ignoring: Bad message
```

**Comment by yuwata** [comment]
What's the dumped packet in that case?

**Comment by freswa** [comment]
Request:
```
Frame 1: 157 bytes on wire (1256 bits), 157 bytes captured (1256 bits)
    Encapsulation type: Linux cooked-mode capture v1 (25)
    Arrival Time: Jul 14, 2022 01:08:30.276426000 CEST
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1657753710.276426000 seconds
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 157 bytes (1256 bits)
    Capture Length: 157 bytes (1256 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: sll:ethertype:ipv6:udp:dhcpv6]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Linux cooked capture v1
Internet Protocol Version 6, Src: fe80::9de3:9e8a:b89:ffba, Dst: ff02::1:2
    0110 .... = Version: 6
    .... 0000 0000 .... .... .... .... .... = Traffic Class: 0x00 (DSCP: CS0, ECN: Not-ECT)
    .... 1100 0001 1100 1010 0101 = Flow Label: 0xc1ca5
    Payload Length: 101
    Next Header: UDP (17)
    Hop Limit: 1
    Source Address: fe80::9de3:9e8a:b89:ffba
    Destination Address: ff02::1:2
User Datagram Protocol, Src Port: 546, Dst Port: 547
    Source Port: 546
    Destination Port: 547
    Length: 101
    Checksum: 0x3795 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 0]
    [Timestamps]
    UDP payload (93 bytes)
DHCPv6
    Message type: Solicit (1)
    Transaction ID: 0xb75e09
    Rapid Commit
        Option: Rapid Commit (14)
        Length: 0
    Identity Association for Prefix Delegation
        Option: Identity Association for Prefix Delegation (25)
        Length: 41
        IAID: 59e41b4a
        T1: 0
        T2: 0
        IA Prefix
            Option: IA Prefix (26)
            Length: 25
            Preferred lifetime: 0
            Valid lifetime: 0
            Prefix length: 56
            Prefix address: ::
    Client Fully Qualified Domain Name
        Option: Client Fully Qualified Domain Name (39)
        Length: 6
        Flags: 0x01  [CLIENT wants SERVER to update both its AAAA and PTR RRs]
        Partial domain name: loki
    Option Request
        Option: Option Request (6)
        Length: 2
        Requested Option code: SOL_MAX_RT (82)
    Client Identifier
        Option: Client Identifier (1)
        Length: 14
        DUID: 00020000ab115abde43347c29141
        DUID Type: assigned by vendor based on Enterprise number (2)
        Enterprise ID: Tom Gundersen (systemd) (43793)
        Identifier: 5abde43347c29141
    Elapsed time
        Option: Elapsed time (8)
        Length: 2
        Elapsed time: 7470ms
```
Reply:
```
Frame 2: 165 bytes on wire (1320 bits), 165 bytes captured (1320 bits)
    Encapsulation type: Linux cooked-mode capture v1 (25)
    Arrival Time: Jul 14, 2022 01:08:30.281298000 CEST
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1657753710.281298000 seconds
    [Time delta from previous captured frame: 0.004872000 seconds]
    [Time delta from previous displayed frame: 0.004872000 seconds]
    [Time since reference or first frame: 0.004872000 seconds]
    Frame Number: 2
    Frame Length: 165 bytes (1320 bits)
    Capture Length: 165 bytes (1320 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: sll:ethertype:ipv6:udp:dhcpv6]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Linux cooked capture v1
Internet Protocol Version 6, Src: fe80::e86:10ff:fef6:ae19, Dst: fe80::9de3:9e8a:b89:ffba
    0110 .... = Version: 6
    .... 1100 0000 .... .... .... .... .... = Traffic Class: 0xc0 (DSCP: CS6, ECN: Not-ECT)
    .... 0000 0000 0000 0000 0000 = Flow Label: 0x00000
    Payload Length: 109
    Next Header: UDP (17)
    Hop Limit: 64
    Source Address: fe80::e86:10ff:fef6:ae19
    Destination Address: fe80::9de3:9e8a:b89:ffba
    [Source SLAAC MAC: JuniperN_f6:ae:19 (0c:86:10:f6:ae:19)]
User Datagram Protocol, Src Port: 547, Dst Port: 546
    Source Port: 547
    Destination Port: 546
    Length: 109
    Checksum: 0xa377 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 1]
    [Timestamps]
    UDP payload (101 bytes)
DHCPv6
    Message type: Reply (7)
    Transaction ID: 0xb75e09
    Client Identifier
        Option: Client Identifier (1)
        Length: 14
        DUID: 00020000ab115abde43347c29141
        DUID Type: assigned by vendor based on Enterprise number (2)
        Enterprise ID: Tom Gundersen (systemd) (43793)
        Identifier: 5abde43347c29141
    Server Identifier
        Option: Server Identifier (2)
        Length: 26
        DUID: 00020000058330633a38363a31303a66363a62333a6330000000
        DUID Type: assigned by vendor based on Enterprise number (2)
        Enterprise ID: Juniper Networks/Funk Software (1411)
        Identifier: 30633a38363a31303a66363a62333a6330000000
    Identity Association for Prefix Delegation
        Option: Identity Association for Prefix Delegation (25)
        Length: 41
        IAID: 59e41b4a
        T1: 900
        T2: 1440
        IA Prefix
            Option: IA Prefix (26)
            Length: 25
            Preferred lifetime: 1800
            Valid lifetime: 14400
            Prefix length: 56
            Prefix address: aaaa:bbbb:cccc:f000::
    Rapid Commit
        Option: Rapid Commit (14)
        Length: 0
````

**Comment by yuwata** [comment]
Thanks. Will take a look.

**Comment by yuwata** [comment]
@freswa I added one commit which produces more debugging logs. Could you try again?

**Comment by freswa** [comment]
```
Jul 14 01:51:20 loki systemd-networkd[346]: ppp42: DHCPv6 client: Sent Solicit
Jul 14 01:51:20 loki systemd-networkd[346]: ppp42: DHCPv6 client: Next retransmission in 58s
Jul 14 01:51:20 loki systemd-networkd[346]: ppp42: DHCPv6 client: Failed to parse option header at offset 93 of total length 97, ignoring remaining message: Bad message
Jul 14 01:51:20 loki systemd-networkd[346]: ppp42: DHCPv6 client: Received reply message without rapid commit flag, ignoring.
```

**Comment by yuwata** [comment]
Thank you! I found the root of the issue. PTAL!

**Comment by freswa** [comment]
Awesome work!
Though, the patch doesn't compile:
```
../systemd-stable/src/libsystemd-network/sd-dhcp6-lease.c: In function ‘dhcp6_lease_parse_message’:
../systemd-stable/src/libsystemd-network/sd-dhcp6-lease.c:472:55: error: expected ‘)’ before ‘offset’
  472 |                                                       offset, len);
      |                                                       ^~~~~~
../systemd-stable/src/shared/log-link.h:9:132: note: in definition of macro ‘log_interface_full_errno_zerook’
    9 |                 _ifname ? log_object_internal(level, error, PROJECT_FILE, __LINE__, __func__, "INTERFACE=", _ifname, NULL, NULL, ##__VA_ARGS__) : \
      |                                                                                                                                    ^~~~~~~~~~~
```

**Comment by yuwata** [comment]
Sorry, I already force-pushed fixed version.

**Comment by freswa** [comment]
Lol
Patch lgtm

**Comment by yuwata** [comment]
@freswa Thank you for testing this PR so many times. Your help is much appreciated.

**Review by bluca — APPROVED** [review]

**Comment by jbg** [comment]
I think this issue is causing DHCPv6 to be broken in Google Cloud; will this make it into a stable 251.4 some time soon?

**Comment by keszybz** [comment]
It'll be soon.

**Pull request merged**
