### PR TITLE
ndisc and dhcpv6

### PR DESCRIPTION
**Pull request by teg**
Move router discovery from the kernel to userspace, and improve the ndisc/dhcpv6 interaction.

### CODE REVIEW

**Comment by teg** [comment]
@pfl looks good to you? @thom311 might be of interest?

**Comment by teg** [comment]
Semaphore fails due to old kernel headers, will update.

**Comment by pfl** [comment]
Looks fine to me. Any other comments?

Please update the semaphore thing.

**Comment by thom311** [comment]
Interesting, LGTM too.

**Pull request merged**
