### PR TITLE
Hwdb optional resolution

### PR DESCRIPTION
**Pull request by whot**
This is somewhat of a hack, allowing evdev hwdb entries to be optional. It's specifically targeted at the Elantech touchpads (may be useful for ALPS too, I don't know yet) where firmware detection is not straightforward in userspace (different combination of EV_KEY/INPUT_PROP bits can signal the firmware version).

So the optional approach here allows a single entry for all elantech touchpads without having to worry about overriding the resolution when we actually get it from the kernel (for v4 devices).

### CODE REVIEW

**Comment by poettering** [comment]
@kaysievers can you comment on this please?

**Comment by whot** [comment]
I'd appreciate a ack/nak but pull this just yet please (or at least only the first one). I've sent a patch to linux-input to have this set in the kernel for elantech touchpads and they're the only users at this point. If this gets in the kernel, we can definitely drop the second patch and may never need the first part of it.

**Comment by dvdhrm** [comment]
@whot So the elantech people produced a new revision of their device that provides this data, but they did not change the PID? Nor did they change the version?

I don't mind your patches, but I'd really like to know why it is exactly needed. I mean, it might solve one problem now, but who prevents them producing a new revision of the same device with wrong values? What do we do then? I'd much prefer extending the match-rules over more logic in the hwdb.

**Comment by whot** [comment]
yeah. the devices are serial, so there's no VID/PID to speak of and the only touchpad driver that uses the version field is the alps one. so we really don't know which version a touchpad is, but we do know that v1-v3 don't provide the resolution, and v4 provides it. elantech told us that v1-v3 are all 800dpi (31 u/mm). so that's what this patch does - if we don't have resolution we know it's 800dpi, otherwise we use the one from the firmware. I doubt that a future v5 will lack the resolution, pretty sure Win8 certification requires it now.

I don't have a git tree at hand right now but note that v4 is already one or two years old at the very least, so this would only affect old devices anyway.

As for the match rules: http://lists.freedesktop.org/archives/wayland-devel/2015-June/023086.html is the closest I came up with so far and it's wrong. I doubt you'd want that in the hwdb matching :)

**Comment by dvdhrm** [comment]
So, yeah, what I really don't want is any extended logic in the lookup path, which departs from non-trivial comparisons. But all this patch does is extend the keyboard-builtin. Hence, I think I'm fine with it.

It still feels weird to introduce this just for one device.. but eh.. that's life.

**Comment by dvdhrm** [comment]
On the other hand, this kinda defers from the "hardware _database_" logic. It no longer stores information, but code.. We no longer can figure out device information without actually having the device (as we cannot know what value the device has set).

Gnah! (still torn.. as you might notice)

To me, this kinda sounds like a fixup the Elantech driver should carry.

**Comment by dvdhrm** [comment]
@whot, can you explain why we cannot do this in the kernel:

```
diff --git a/drivers/input/mouse/elantech.c b/drivers/input/mouse/elantech.c
index ce3d400..db94555 100644
--- a/drivers/input/mouse/elantech.c
+++ b/drivers/input/mouse/elantech.c
@@ -1197,6 +1197,8 @@ static int elantech_set_input_params(struct psmouse *psmouse)
                }
                input_set_abs_params(dev, ABS_X, x_min, x_max, 0, 0);
                input_set_abs_params(dev, ABS_Y, y_min, y_max, 0, 0);
+               input_abs_set_res(dev, ABS_X, 31);
+               input_abs_set_res(dev, ABS_Y, 31);
                break;

        case 2:
@@ -1208,6 +1210,8 @@ static int elantech_set_input_params(struct psmouse *psmouse)
                        elantech_set_buttonpad_prop(psmouse);
                input_set_abs_params(dev, ABS_X, x_min, x_max, 0, 0);
                input_set_abs_params(dev, ABS_Y, y_min, y_max, 0, 0);
+               input_abs_set_res(dev, ABS_X, 31);
+               input_abs_set_res(dev, ABS_Y, 31);
                if (etd->reports_pressure) {
                        input_set_abs_params(dev, ABS_PRESSURE, ETP_PMIN_V2,
                                             ETP_PMAX_V2, 0, 0);
@@ -1217,6 +1221,8 @@ static int elantech_set_input_params(struct psmouse *psmouse)
                input_mt_init_slots(dev, 2, 0);
                input_set_abs_params(dev, ABS_MT_POSITION_X, x_min, x_max, 0, 0);
                input_set_abs_params(dev, ABS_MT_POSITION_Y, y_min, y_max, 0, 0);
+               input_abs_set_res(dev, ABS_MT_POSITION_X, 31);
+               input_abs_set_res(dev, ABS_MT_POSITION_Y, 31);
                break;

        case 4:
```

**Comment by whot** [comment]
yeah, this patch is already on the linux-input list, waiting for dmitry's ack. see my earlier comment here. if you want me to close this pull request and re-open if the kernel approach fails that's fine with me.

**Comment by dvdhrm** [comment]
Sorry, didn't read carefully enough!

I reviewed the kernel patch now. Looks good to me. I'll follow it, and in case Dmitry rejects it with a reasonable argument, I'll reconsider merging this. But until then, I'd really like to avoid this (having talked with the other guys once more).

**Comment by dvdhrm** [comment]
Was merged upstream. Ill close this now. Feel free to reopen if it comes up again.

Thanks!

**Pull request closed without merging**
