### PR TITLE
networkd fixes

### PR DESCRIPTION
**Pull request by teg**

### CODE REVIEW

**Comment by zonque** [comment]
@martinpitt, are your test cases happy now?

**Comment by martinpitt** [comment]
This MP seems unrelated to issue #1866 . I can still reproduce the IPv6 missing DHCP address after a few iterations, and IPv4 tests are still failing on eternally staying on `configuring`. Sorry, didn't have time to look into that today.

**Comment by poettering** [comment]
(@martinpitt, when you say "MP", do you mean "PR"?)

**Comment by poettering** [comment]
Looks fine to me in general.

**Comment by martinpitt** [comment]
> @martinpitt, when you say "MP", do you mean "PR"?

Err, yes, sorry. "MP" == "merge proposal", which is Launchpad's term for essentially the same thing as a PR; it's too deeply engraved in my brain..

**Comment by teg** [comment]
@poettering, changed the commit with your comment (now only call dhcp6_configure() once, though the behavior is the same), and force-pushed. Also added two more fixes on top. Still see @martinpitt's tests failing, but these fixes are needed regardless.

**Comment by teg** [comment]
@pfl care to have a look at the patch where DHCPv6 is bound to the link-local address?

**Comment by poettering** [comment]
hmm, the semaphore build failed, something is wrong with the tests... Tesing an ifindex >= -1 sounds pretty weird, no?

**Comment by teg** [comment]
Gah, forgot to commit the updated tests. The ifindex >= -1 is unrelated and unchanged, but probably not the right thing to do, yeah.

**Comment by pfl** [comment]
So 6506063 adds a forgotten SO_REUSEADDR, and c601ebf sets sin6_scope_id. Looks plausible. These two patches could be squashed together as they both modify the 'if(local_address)' and both deal with binding to addresses on the same host, right?

**Comment by teg** [comment]
@pfl sure, they belong together (but separate is also ok I think). Incidentally, this took me a lot longer than expected as setting sin6_address to a LL address without setting sin6_scope_id returns -EINVAL and not -ENODEV as the manpage indicates...

**Comment by martinpitt** [comment]
I can't honestly verify the "sd-dhcp6-client: bind to link-local address" commit, but the others look fine to me. No test regressions either, so :+1: from me.

**Pull request merged**
