### PR TITLE
sysusers: Ensure basic.conf entries have high priority

### LINKED ISSUE #21155: Ensure sysusers.d/basic.conf has high priority
**Is your feature request related to a problem? Please describe.**
[basic.conf](https://github.com/systemd/systemd/blob/main/sysusers.d/basic.conf.in) contains fixed IDs for the most fundamental system users and groups. Since `systemd-sysusers` prefers entries defined earlier in lexicographically sorted conf files, a conflicting entry defined in a conf file such as `/usr/lib/sysusers.d/apackage.conf` will override the entry in `basic.conf`. Packages will very likely not use fixed IDs in their entries since it wouldn't be possible to choose one suitable for generic downstream usage.

The background here is that at Endless we want to start making use of sysusers. Since the OS is shipped statically with ostree, we need to ensure that IDs are allocated statically for any paths in the ostree commit. Otherwise an upgrading user may have a user or group locally with one ID while the tree contains paths intended to be owned by that user or group but using a different ID. Since `basic.conf` defines most of these users, we really want to make sure it takes precedence over a random package that might define a conflicting entry without a fixed ID.

 **Describe the solution you'd like**
Change the installed name for `basic.conf` to ensure it has high priority when `systemd-sysusers` resolves conflicting entries. I suggest `00-basic.conf`. An admin can always override entries with an equivalently named file in `/etc/sysusers.d`, but a distributor would want to ensure that these fixed entries normally take priority. Possibly `10-basic.conf` would be better to still leave a little space for `00-overrides.conf` and the like.

**Describe alternatives you've considered**
Do it at the distributor level. This is where you know what conflicts you're trying to resolve. However, I can see this being an issue for many distributors, so I'd prefer to solve it once upstream.

**The systemd version you checked that didn't have the feature you are asking for**
v249-1687-geef5ebec97

### PR DESCRIPTION
**Pull request by dbnicholson**
`basic.conf` contains fixed IDs for the most fundamental system users and
groups. Since `systemd-sysusers` prefers entries defined earlier in
lexicographically sorted conf files, a conflicting entry defined in a conf file
such as `/usr/lib/sysusers.d/apackage.conf` will override the entry in
basic.conf. Packages will very likely not use fixed IDs in their entries since
it wouldn't be possible to choose one suitable for generic downstream usage.

Rename `basic.conf` to `10-basic.conf` to ensure it lexicographically sorts
early and hence has higher priority than almost any other conf file. This still
leaving some space for other higher priority configuration such as
`00-overrides.conf`.

Fixes #21155.

### CODE REVIEW

**Comment by keszybz** [comment]
I think it's reasonable to rename `basic.conf` — it is a special case. But I don't think we should make this a general principle — so far we followed the rule that each file is named after the package, and it wasn't much of a problem. Based on this, I think we shouldn't rename the other two files (`systemd.conf` and `systemd-remote.conf`).

I'd propose the following instead: rename `basic.conf` to `_basic.conf`, add a note in NEWS that it is renamed so that groups defined there are available to other files.

**Comment by keszybz** [comment]
@poettering, @dbnicholson, comments on the last comment?

**Comment by dbnicholson** [comment]
I think either way works. Numbering is clearer to me since it creates a much clearer ordering, but I also think only `basic.conf` is likely to suffer from this issue since it's generated. In the other cases, a distributor can change the default by patching or seeding the desired value in `basic.conf`. It's unlikely that 2 upstream are going to provide conflicting user definitions that would be want to be reliably ordered.

**Comment by dbnicholson** [comment]
Another option is to switch to numbered prefixes and have sysusers print a warning for any conf files it finds without a numerical prefix. It won't fix the potential problems but at least it would nudge everyone to move in the right direction. That could exacerbate the problem, though, since any upstreams following that advice would introduce more potential issues on older systemd without the numbered `basic.conf`.

**Comment by bluca** [comment]
> Another option is to switch to numbered prefixes and have sysusers print a warning for any conf files it finds without a numerical prefix. It won't fix the potential problems but at least it would nudge everyone to move in the right direction. That could exacerbate the problem, though, since any upstreams following that advice would introduce more potential issues on older systemd without the numbered `basic.conf`.

I'm not sure, personally I'd rather we keep consistency across all components w.r.t. config files naming, parsing, etc

**Comment by poettering** [comment]
isn't `_` after `A` int ascii table? we do byte value ordering, right?

**Comment by poettering** [comment]
NEWS story about this would be absolute minimum.

**Comment by poettering** [comment]
I wonder what the real effective benefit of `_` really would be. `10-basic.conf` is ordered before `basic.conf` aleady, hence both prefixes have same effect regarding ordering.

I think ordering matters in particular for generic user names, not so much for specific ones I guess. Thus if we really go for renaming basic.conf I think renaming systemd.conf and systemd-remote.conf should be done too, it's the less problematic set of files over `basic.conf` i think.

The main problem i see is that people might have placed their stuff as aaa.conf under the assumption that this would be ordered before basic.target. But if they did that, then suddenly renaming things to `10-basic.conf` or `_basic.conf` would mean their file `aaa.conf` is suddenly ordered *after* not *before* our file, and that's quite a change...

**Comment by poettering** [comment]
but dunno, maybe the aaa.conf issue is just a theoretic issue, not a real-life one. dunno.

might be something to ask our on the mailing list, and see if anyone raises their hand.

besides the ordering issue I mentioned there's also the issue that people might have masked basic.conf, and by renaming the file we'd magically "unmask" it on existing installations. This might be something solvable via a packaging scriptlet though, much easier than the ordering thing...

**Comment by poettering** [comment]
maybe we should rename and then tell distros that if they are concerned about the ordering and masking issue, that they should inside a packaging script create a symlink `/usr/lib/sysusers.d/10-basic.conf` → `/etc/sysusers.d/basic.conf` + a masking symlink `/dev/null` → `/etc/sysusers.d/10-basic.conf`.

With such an approach they basically undo the renaming on upgraded machines but things are cleaned up for new installs. 

Of course, it would be up to the distros to actually implement this or ignore the issue (which might be workable too)

**Comment by poettering** [comment]
yeah, I am leaning towards that: it would mean our upstream sources are entirely clean and we'd push the issue down to downstreams. The NEWS file should give them a hand what to do though to retain full compat as I proposed with the symlinks, and then they can make their own decision.

Does this make sense?

**Comment by dbnicholson** [comment]
> maybe we should rename and then tell distros that if they are concerned about the ordering and masking issue, that they should inside a packaging script create a symlink `/usr/lib/sysusers.d/10-basic.conf` → `/etc/sysusers.d/basic.conf` + a masking symlink `/dev/null` → `/etc/sysusers.d/10-basic.conf`.

I'm confused by this. Doesn't symlinking `/usr/lib/sysusers.d/10-basic.conf` → `/etc/sysusers.d/basic.conf` just overwrite systemd's version? I think the masking symlink being created conditionally if `/etc/sysusers.d/basic.conf` exists would cover the issue that the admin has a `basic.conf` override already. However, wouldn't simply renaming `/etc/sysusers.d/basic.conf` to `/etc/sysusers.d/10-basic.conf` on upgrade handle this?

**Comment by dbnicholson** [comment]
But, generally, yes I think this kind of transition can really only be handled during the install, which typically means distros. Of course, if you're using an image based OS you'd need something else. Either way, I think putting something prominent in `NEWS` for downstreams/integrators to handle is the best you can do.

**Comment by keszybz** [comment]
> isn't `_` after `A` int ascii table? we do byte value ordering, right?

Doesn't seem so. `systemd-analyze cat-config sysusers.d` shows `_basic.conf` before the other files.

--

Looking at this again after a while, I'm convinced that adding the numerical prefixes is a bad idea. If we do it for even one file, people will assume that this is the right thing to do and we'll have numerical prefixes for various files. But so far the convention was that files are named after the package, and we have a bunch of those. I don't want to have a mess where some files are numbered and others are not.

So please just change the patch to use `_basic.conf` and let's get this merged.

**Comment by mbiebl** [comment]
Is this actually a real issue we are trying to solve here? 
I.e. are there packages/users out there who overwrite system users from basic.conf this way?
This feels like whack-a-mole. If users want to do that, that prevents them from doing __myfoo.conf?

**Comment by mbiebl** [comment]
I quickly checked the Debian archive. We don't have any conflicting entries in .conf files shipped by packages.

**Comment by keszybz** [comment]
basic.conf defines some basic groups. And if you want to refer to those groups in other config, they should be defined first.

**Comment by mbiebl** [comment]
> basic.conf defines some basic groups. And if you want to refer to those groups in other config, they should be defined first.

do you have a real world use case?

**Comment by johannbg** [comment]
numerical prefixes as originally proposed is what people expect and use in the wild, naming things after package names makes little sense since downstream name the same upstream component differently and upstreams have no control over how downstream chose to name the packages for the components ( apache vs httpd is a good example ).

using an `_` will just add more confusion for no benefits. 

Propably the cleanest approach is to split the basic conf into individual user/group files and name those files after the user/group in question ( adm.conf,wheel.conf etc ) as was recently done with systemd's own users in PR #20056

**Comment by dbnicholson** [comment]
> > basic.conf defines some basic groups. And if you want to refer to those groups in other config, they should be defined first.
> 
> do you have a real world use case?

We haven't actually run into this problem yet, but here's what we're trying to accomplish for Endless. Since the OS is distributed essentially as an image (via OSTree), we need to be very careful about the actual IDs used for system users and groups. The IDs get generated and distributed in the OS, not locally on the users system. Therefore, any user or group that creates files needs to have their ID persisted globally across all Endless releases. We can't have the ID change or we risk some service no longer working because it can no longer access the files it's created in a previous version. For example, the `polkitd` user will now and forevermore have UID 105 on Endless OS. Otherwise it wouldn't be able to read existing rules in `/etc/polkit-1/rules.d` after an upgrade. There are some subtleties in there, but you get the idea.

The way we've handled this until now is adding the users and groups with persistent IDs for all services that are included in the OS to base-passwd, which forms basic.conf. Until now we haven't used sysusers.d, but now we'd really like to for various reasons. If we can't guarantee that basic.conf has higher precedence than some package, then we might inadvertently add a package to the OS who drops in a sysusers config file that has higher precedence than basic.conf and breaks this setup.

We can workaround all of this stuff downstream, but I thought it would be generally useful that your OS defined users and groups should have higher precedence than packages. We obviously can't put an enforcing policy in place here, but I'm a lot more interested in a package that begins with the letter a innocently adding a definition to sysusers.d than I am with someone forcefully trying to override the OS definitions by adding several underscores to the beginning of the conf file. The whack-a-mole game your describing can't be won. What I'd like to do is prevent inadvertent issues.

**Comment by mbiebl** [comment]
> If we can't guarantee that basic.conf has higher precedence than some package, then we might inadvertently add a package to the OS who drops in a sysusers config file that has higher precedence than basic.conf and breaks this setup.

This is what I don't understand. Do you really expect that packages overwrite the basic system users provided by basic.conf?

I would consider this a bug in the package tbh. 
Otherwise, I see no problem with a file apackage.conf being lexically before basic.conf.

**Comment by dbnicholson** [comment]
In the typical case, no I wouldn't. In the Endless case where we have to define persistent IDs for all users and don't want to patch upstream's sysusers conf file, yes.

In general, though, how would upstream know what's defined in basic.conf? If I'm the developer for apackage and I create apackage.conf, how would I know whether I would be creating an issue for downstream? Go query every distro to see what they define? What if I find a conflict? Is that a bug in my package or in the distro? I think you're implying that these names should all be pretty standard across distros, but I'm pretty sure most distros don't define an `irc` user like Debian does. Is it a bug in `apackage.conf` if I define an `irc` user?

Or reverse the relationship and every distro can monitor every conf file to ensure it doesn't conflict with their definitions. Again, Endless can vigilently monitor this space and fix any issues downstream, but why not fix it one time here?

**Comment by dbnicholson** [comment]
> > isn't `_` after `A` int ascii table? we do byte value ordering, right?
> 
> Doesn't seem so. `systemd-analyze cat-config sysusers.d` shows `_basic.conf` before the other files.

Are you sure about that?

```
$ systemd-analyze cat-config sysusers.d
# /usr/lib/sysusers.d/A.conf
# A.conf

# /usr/lib/sysusers.d/_basic.conf
# _basic.conf
```

`_` is after the upper case characters in ASCII.

**Comment by keszybz** [comment]
You are right: `_` sorts before `a`, but after `A`.

I misunderstood what is hapenning here. I thought that the problem that you're trying to solve is that you have a configuration like this (sorted in the way that sysusers sorts it):
```
# a.conf
m admin wheel
# basic.conf
g wheel 99
```
and then sysusers would create the `wheel` group with some random gid and ignore the 99 specified later. But this is not what happens: sysusers will correctly parse all the input data, and create `wheel` with GID 99.

And in fact, if you specify conflicting entries, or even overlapping entires, sysusers will completely complain:
```
Two or more conflicting lines for testgroup configured, ignoring.
```

I'll submit a PR to add `--dry-run` to sysusers to make it easier to explore configuration.

--

As described above, I misunderstood the problem. I _assumed_ that you are worried about the sysusers doing the wrong thing because of ordering of entries, but this does not happen, as described above. You seem to be worried about conflicting configuration delivered by packages. Sorry, but this cannot be fixed at this level. Even if we were to name the files `00-00-00-______this_must_be_first.conf`, a package can trivially add one underscore and still be first. More likely, a confused package will provide a file in `/etc` and fully replace some other config file in `/usr`. If you want to prevent that, add linters to the build pipeline. I don't think we want to rename things here, since this will cannot really work anyway.

**Comment by dbnicholson** [comment]
You made your choice and it's not a big deal, but the point that I was making to @mbiebl is that of course anyone can try to force themselves to get priority by artificially sorting earlier. You can't win that game. What you can do is make it so that people not trying to win the priority game don't accidentally win it.

**Pull request closed without merging**
