### PR TITLE
docs/HACKING.md: clarify some portions

### PR DESCRIPTION
**Pull request by williamcroberts**
Clarify portions of HACKING.md so folks don't spend as much time as I did on it.

Signed-off-by: William Roberts <william.c.roberts@intel.com>

### CODE REVIEW

**Comment by williamcroberts** [comment]
@malikabhi05 FYI this has some more details on setup and you want mkoisi master, I used v13 and bumped into this issue https://github.com/systemd/mkosi/pull/1241 and it looks like that fix is targeted for v14 based on the label.

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
For next time, note that we don't do DCO, so no need for --signed-off

**Comment by williamcroberts** [comment]
> For next time, note that we don't do DCO, so no need for --signed-off

Does it hurt to have it?

**Comment by bluca** [comment]
it does not, just doesn't have meaning associated with it in this repository

**Comment by keszybz** [comment]
Actually, it does hurt. It creates a false impression to people reading the commits. Also, if we ever were to actually start using DCO, the meaning of older DCOs would be unclear: do those people retroactively agree to what we just decided?

**Pull request merged**
