### PR TITLE
units: don't order mount units against blockdev@.target in {fstab,gpt…

### PR DESCRIPTION
**Pull request by fbuihuu**
…}-generator

An implicit After=blockdev@.target dependency is already generated for all
mounts.

But more importantly, the implicit dependency is created based on the data from
/proc/self/mountinfo, which should be the actual device node, with all symlinks
resolved. OTOH the dep created by the generators was based on the content of
fstab hence the device path used for mounting the devices may be different from
the expected device node of the backing service.

This patch drops the ordering dep created by the generators and only keeps the
implicit one created for all mounts. It partially reverts commit
a7e885587949b6793ccf389505f3c436315fa653.

### CODE REVIEW

**Comment by fbuihuu** [comment]
I'm a bit confused at that point as I'm not sure to understand why blockdev@.target was introduced... the implicit ordering dependency added to all mounts could have done against `systemd-cryptsetup@xxx.service` directly, no ?

**Comment by keszybz** [comment]
What is the goal here? Just simplification of the code, or a fix / change in behaviour?

**Comment by fbuihuu** [comment]
It's simplifcation only.

I noticed that some mount units backed by LUKS devices have ordering constraint against `blockdev@dev-disk-by-uuid-xxx.target`:

```
# systemctl show -pAfter mnt.mount
After=systemd-journald.socket local-fs-pre.target "blockdev@dev-disk-by\\x2duuid-83b2ca8a\\x2d496f\\x2d47b4\\x2d8f04\\x2dd5b96b124f13.target" [...]
```
In my understanding the instance name of `blockdev@.target` is supposed to be the actual device node path so both `systemd-cryptsetup@.service` and the relevant mount unit can order themself on the same target.

**Comment by poettering** [comment]
Hmm, I am not sure I grok why dropping this would bring any benefits? I'd rather have too much ordering on this, then too little. 

The thing is that device nodes have many names, and we never know which is the main name and which one appears in /proc/self/mountinfo. For example, DM devices main device node is typically `/dev/dm-0`, `/dev/dm-1`, … but they generally appear in /proc/self/mountinfo as `/dev/mapper/foo` and friends, which is a symlink, except when they don't. 

The neat thing is that blockdev@.target ordering deps don't cost much: we can place them, in the the hope they help, but they generally don't hurt even if they don't help. Hence, we should set them as early as possible, i.e. as we know them. For stuff mounted via /etc/fstab this might

**Comment by fbuihuu** [comment]
I don't think consumers and providers can refer to devices via any kind of names.

There're various ways providers can specify the device paths (by-uuid, by-path, by-id, ...) and I don't think consumer can cope with that. The only possibility is that consumers and providers refer to the same path which means that they should use the canonical path of the device only.

**Comment by poettering** [comment]
> I don't think consumers and providers can refer to devices via any kind of names.

Well, but again, for the cryptsetup case the /dev/mapper/ names matter, and they are *not* the primary names of the device, but symlinks. But for other cases other names might matter, we never know in the fstab generators, which ones it will be, hence let's generate them all, and then we have a high chance we use the right names for the consumers used.

> There're various ways providers can specify the device paths (by-uuid, by-path, by-id, ...) and I don't think consumer can cope with that. The only possibility is that consumers and providers refer to the same path which means that they should use the canonical path of the device only.

Well, as mentioned that's not what happens for cryptsetup case. there we use a symlink name all the way. The canonical device nodes /dev/md-0 are never used...

**Comment by fbuihuu** [comment]
> But for other cases other names might matter, we never know in the fstab generators, which ones it will be, hence let's generate them all, and then we have a high chance we use the right names for the consumers used.

Let's take an example: on one of my setup, /dev/vda1 have the following symlinks:
```
/dev/disk/by-id:
lrwxrwxrwx 1 root root 10 Jan 25 15:30 virtio-0000-part1 -> ../../vda1

/dev/disk/by-partuuid:
lrwxrwxrwx 1 root root 10 Jan 25 15:30 eaa7340d-01 -> ../../vda1

/dev/disk/by-path:
lrwxrwxrwx 1 root root 10 Jan 25 15:30 pci-0000:00:05.0-part1 -> ../../vda1
lrwxrwxrwx 1 root root 10 Jan 25 15:30 virtio-pci-0000:00:05.0-part1 -> ../../vda1

/dev/disk/by-uuid:
lrwxrwxrwx 1 root root 10 Jan 25 15:30 88b22de3-1b5d-46f3-a619-7d79b60547f4 -> ../../vda1
```

and the list of blockdev@.target for this device is:
```
blockdev@dev-vda1.target
blockdev@dev-disk-by\x2duuid-88b22de3\x2d1b5d\x2d46f3\x2da619\x2d7d79b60547f4.target
```

As you can see only 2 blockdev@.target are generated for /dev/vda1: the one specified in fstab and the one specified in /proc/self/mountinfo so many of  the blockdev@.target ordering deps are missing.

Furthermore the one created by fstab-generator is arbitrary and can even be changed by the user so I can't really see how a consumer can make use of that.

We might be able to create all ordering deps for a given device but that doesn't seem right, at least for the moment where the only use case is the cryptsetup one.

**Comment by fbuihuu** [comment]
Also for the common case, ie  cryptsetup devices are attached during the boot process, all these devices are attached in initrd and therefore they should be detached in initrd during shutdown too.

So the cryptsetup-generator should detect this case and should omit `Conflicts=umount.target` most of the time, hence the ordering issue during shutdown between mount units and systemd-crypsetup@.service ones is solved (for the common case).

**Pull request closed without merging**
