### PR TITLE
A third suggested fix for the getttyname_r() thing

### PR DESCRIPTION
**Pull request by poettering**
This approach has two benefits:

1. doesn't use realloc() (because we don't need realloc()'s most noble property: that it copies the old data into the newly allocated block; and if we don't need that free() and malloc() is probably better).

2. Doesn't allocate PATH_MAX on the stack, but only a buffer we actually need, and returns just that. In the common codepaths (i.e. short string) we'll only do a single malloc(), and just use that buffer for everything...

I also added a test case, to ensure this all works.

### CODE REVIEW

**Comment by poettering** [comment]
This is all an alternative to both #12043 and #12044 if that's not clear.

**Comment by vcaputo** [comment]
Seems reasonable to me, I'll close my PR - any of these is probably fine just get rid of the VLA :)

**Comment by keszybz** [comment]
I don't think allocating 2k on the stack for the duration of a single function (which is nonrecursive and doesn't do any deeply nested calls), is bad. The "allocation" is just moving of a pointer, and in the case we fail to find the path, it is more efficient then the alternatives.

Anyway, `getttyname_malloc` has two users:
In execute.c:
```
                if (getttyname_malloc(STDIN_FILENO, &q) >= 0)
                        tty = strjoina("/dev/", q);
```
and
```C
       if (!origin_tty) {
                getttyname_harder(STDIN_FILENO, &stdin_tty);
                origin_tty = stdin_tty;
        }

        if (asprintf(&text,
                     "\a\r\n"
                     "Broadcast message from %s@%s%s%s (%s):\r\n\r\n"
                     "%s\r\n\r\n",
                     un ?: username, hn,
                     origin_tty ? " on " : "", strempty(origin_tty),
                     format_timestamp(date, sizeof(date), now(CLOCK_REALTIME)),
                     message) < 0)
                return -ENOMEM;
```
So in both cases we use the path in a context where overly long paths are risky. Once in a stack allocation, and second time in a tty message. Hence, I think my approach to limit the path to PATH_MAX is quite reasonable. In particular allowing unbounded strings here and using it directly in alloca does not seems like a good idea.

**Comment by poettering** [comment]
I guess it doesn't really matter to have that long a discussion about this... So I am fine with merging your version, but could you cherry pick this test into your PR?

**Comment by keszybz** [comment]
I cherry-picked your second commit.

**Pull request closed without merging**
