### PR TITLE
bpf: do not use structured initialization for bpf_attr

### PR DESCRIPTION
**Pull request by bluca**
It looks like zero'ing the struct is not enough, and with some level
of optimizations there is still non-zero padding left over.
Switch to member-by-member initialization. Also convert all remaining
bpf_attr variables in other files.

### CODE REVIEW

**Comment by yuwata** [comment]
Maybe, `union bpf_attr attr = {};` also works fine. I fixed similar issue in sd-resolve in the past.

**Comment by bluca** [comment]
> Maybe, `union bpf_attr attr = {};` also works fine. I fixed similar issue in sd-resolve in the past.

The libbpf maintainer explicitly suggested memset, so I'd prefer to follow that guidance if it's ok. In the end it's an ugly deviation from our coding standard either way, which I hope can be reverted one day.

**Comment by yuwata** [comment]
> > Maybe, `union bpf_attr attr = {};` also works fine. I fixed similar issue in sd-resolve in the past.
> 
> The libbpf maintainer explicitly suggested memset, so I'd prefer to follow that guidance if it's ok. In the end it's an ugly deviation from our coding standard either way, which I hope can be reverted one day.

I see. Thanks. My previous comment doesn't mean to drop `zero()`, but just a note.

**Comment by evverx** [comment]
@bluca thanks! As far as I can remember, @mrc0mmand added `--optimization=1` to get around an ASan bug causing some tests to time out. I'd wait for @mrc0mmand to weigh in on this.

Could you temporarily apply the following patch to make sure both `gcc` and `clang` can handle this with different optimization levels?
```diff
diff --git a/.github/workflows/ubuntu-build-check.sh b/.github/workflows/ubuntu-build-check.sh
index c652280bc3..6be15b2e41 100755
--- a/.github/workflows/ubuntu-build-check.sh
+++ b/.github/workflows/ubuntu-build-check.sh
@@ -8,6 +8,7 @@ success() { echo >&2 -e "\033[32;1m$1\033[0m"; }

 ARGS=(
     "--optimization=0"
+    "--optimization=1"
     "--optimization=2"
     "--optimization=s"
     "--optimization=3 -Db_lto=true"
@@ -113,6 +114,10 @@ for args in "${ARGS[@]}"; do
         fatal "ninja failed with $args"
     fi

+    if ! ./build/test-bpf-firewall; then
+        fatal "test-bpf-firewall failed with $args"
+    fi
+
     git clean -dxf

     success "Build with $args passed in $SECONDS seconds"
```

**Comment by evverx** [comment]
It seems to be working. LGTM. Thanks!

**Comment by mrc0mmand** [comment]
> @bluca thanks! As far as I can remember, @mrc0mmand added `--optimization=1` to get around an ASan bug causing some tests to time out. I'd wait for @mrc0mmand to weigh in on this.

The `--optimization=1` flag was introduced in response to https://github.com/systemd/systemd/pull/15886#issuecomment-632754535 and https://github.com/systemd/systemd-centos-ci/pull/144 - basically it does what the ASan documentation recommends:

>  To get a reasonable performance add -O1 or higher. To get nicer stack traces in error messages add -fno-omit-frame-pointer. To get perfect stack traces you may need to disable inlining (just use -O1) and tail call elimination (-fno-optimize-sibling-calls).

(taken from https://clang.llvm.org/docs/AddressSanitizer.html#usage)

So if it doesn't interfere with something, I'd leave the option there. That way it won't bite us again, as it already did a couple of times :-)

**Comment by bluca** [comment]
> > @bluca thanks! As far as I can remember, @mrc0mmand added `--optimization=1` to get around an ASan bug causing some tests to time out. I'd wait for @mrc0mmand to weigh in on this.
> 
> The `--optimization=1` flag was introduced in response to [#15886 (comment)](https://github.com/systemd/systemd/pull/15886#issuecomment-632754535) and [systemd/systemd-centos-ci#144](https://github.com/systemd/systemd-centos-ci/pull/144) - basically it does what the ASan documentation recommends:
> 
> > To get a reasonable performance add -O1 or higher. To get nicer stack traces in error messages add -fno-omit-frame-pointer. To get perfect stack traces you may need to disable inlining (just use -O1) and tail call elimination (-fno-optimize-sibling-calls).
> 
> (taken from https://clang.llvm.org/docs/AddressSanitizer.html#usage)
> 
> So if it doesn't interfere with something, I'd leave the option there. That way it won't bite us again, as it already did a couple of times :-)

Ok I've left it in for the ASAN builds - but still removed for the normal ones, since it seems to mask libbpf errors that we want to catch. Is that ok?

**Comment by mrc0mmand** [comment]
> Ok I've left it in for the ASAN builds - but still removed for the normal ones, since it seems to mask libbpf errors that we want to catch. Is that ok?

Perfect, thanks!

**Pull request merged**
