### PR TITLE
resolved: add EDNS0 support

### PR DESCRIPTION
**Pull request by teg**
This adds EDNS0 support to resolved. In particular this means that we can handle larger UDP packets and that we can request DNSSEC resource records (which usually requires the former). It does not mean that we actually do anything with the received resource records however.

The main part of this PR is handling error cases where the server (or the path between the server and client) cannot handle the features we request and does not fall back gracefully. To handle this, we employ a fallback scheme inspired by BIND [0](https://kb.isc.org/article/AA-00708/0/Why-does-BIND-log-messages-about-disabling-EDNS-or-reducing-the-advertised-packet-size.html), where we will retry a couple of times with a certain feature set, before dropping a feature and try again.

The algorithm can likely be tweaked, as we risk falling back either too aggressively (when packets are lost for unrelated reasons) or not aggressively enough (taking unreasonably long before reaching a working feature set).

### CODE REVIEW

**Comment by teg** [comment]
@keszybz, @poettering, @dvdhrm opinions?

**Comment by dvdhrm** [comment]
"resloved"? (commit message patch #3)

**Comment by poettering** [comment]
Hmm, patch set is weird... b45c0a7bdfff80248ebc54bb12bd7fa12bd333fb being the first commit in the set, introduces a new value to an enum that is introduced in 08544fa926e0c8dda1bc2597cb18e028634aae38 which is supposedly later?

**Comment by zonque** [comment]
Hmm, no. 08544fa is the parent of b45c0a7. It appears in GitHub, the oldest commit is the uppermost one.

**Comment by poettering** [comment]
Hmm, you are saying that github orders the commits by time rather than order?

**Comment by poettering** [comment]
Nah, I am totally confused. Both the last and the first commit in the list above add fields to an enum introduced in the second-to-last commit... Also, 08544fa introduces string mappings for enum fields added in later commits only...

**Comment by grawity** [comment]
In that case review the PR locally, by fetching refs/pull/508/head from GitHub.

```
git config --add remote.origin.fetch "+refs/pull/*/head:refs/remotes/pull/*"
git fetch origin
tig ..pull/508
```

Oddly neither --date-order nor --author-date-order matches whatever weird sorting GitHub uses...

**Comment by zonque** [comment]
@grawity yeah, I tried the exact same thing just now. Really confusing. Not sure yet what they're doing ...

**Comment by zonque** [comment]
I contacted GitHub support on that ordering thing. Let's hear what they say.

**Comment by poettering** [comment]
Reviewed all patches now, good work!

**Comment by teg** [comment]
I accidentally messed this up by force-push. At any rate, it has now been obsoleted by #543.

**Pull request closed without merging**
