### PR TITLE
Fix Priority= parsing in .swap units

### PR DESCRIPTION
**Pull request by poettering**
A fix for #14524

/cc @topimiettinen

### CODE REVIEW

**Comment by topimiettinen** [comment]
Where did you find the restriction that priority less than -1 is for kernel only? I'm using a swap device with priority -2 with no problems.

**Comment by poettering** [comment]
Man page for starters...

Combine this info:

http://man7.org/linux/man-pages/man8/swapon.8.html

With this info:

http://man7.org/linux/man-pages/man2/swapon.2.html

**Comment by poettering** [comment]
Also, look at how swapon() and its parameters are used by swapon.c:

https://github.com/karelzak/util-linux/blob/master/sys-utils/swapon.c#L617

You see that only priorities >= 0 are actually included in the flags parameters.

Hence the logic appears to be: kernel assigns negative prios when prios are not specified by userspace. Userspace may only specify positive prios.

Thus, when parsing user settings we only accept 0…0x7fff (because that's the whole range we can encode in the flags parameter of swapon()), but when parsing the data in /proc/swaps we must accept INT_MIN…INT_MAX.

And as a special magic feature we treat "-1" specified by the user as "no priority set", for compat with /sbin/swapon which does that.

**Comment by topimiettinen** [comment]
I read those as well. From the binary arithmetic one could assume that there's some signed->unsigned conversion going on and -2 could become for example 32766 if there was no special handling, but this is not the case.

Experimenting with swap flags values it seems that maximum is indeed 32767 and anything below zero or unset is changed to -2 (lucky me choosing that number..). The manual page claims that priority for unset case should be -1.

**Comment by topimiettinen** [comment]
Maybe -2 is actually a strange feature (bug?) of how `/proc/swaps` shows the priority:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/mm/swapfile.c#n2430

**Comment by topimiettinen** [comment]
By switching between two swap files with no priority, I got the priority shown by `/proc/swaps` pushed down to -4. I suppose that after 2^31 such operations, the priority could be accidentally positive. Maybe that could have some security implications. It's rather theoretical case due to number of operations needed and because CAP_SYS_ADMIN is involved.

**Comment by topimiettinen** [comment]
Anyway, the limits you listed for unit files and reading `/proc/swaps` now look right to me.

**Comment by topimiettinen** [comment]
Regarding `/proc/swaps`: It does not work the way I thought I saw, everything is fine.

**Comment by topimiettinen** [comment]
CI failure is not related:
```
Err:1 http://ftpmaster.internal/ubuntu bionic-updates/main i386 libgnutls30 i386 3.5.18-1ubuntu1.2
  Could not connect to ftpmaster.internal:80 (91.189.89.99), connection timed out
E: Failed to fetch http://ftpmaster.internal/ubuntu/pool/main/g/gnutls28/libgnutls30_3.5.18-1ubuntu1.2_i386.deb  Could not connect to ftpmaster.internal:80 (91.189.89.99), connection timed out
```

**Comment by poettering** [comment]
(hehe, the lgtm label is a reference to lgtm.com, not actually to your opinion on the code. if you like the code, just write lgtm as comment)

**Comment by poettering** [comment]
OK, @topimiettinen liked this, let's merge.

**Pull request merged**
