### PR TITLE
sd-dhcp-server: refuse too large packet to send

### PR DESCRIPTION
**Pull request by yuwata**
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44134.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx

**Review by bluca — APPROVED** [review]

**Comment by evverx** [comment]
@yuwata thanks! I agree packets like this should be rejected but I'm not sure they should even reach that point. I wonder if it would be better to reject them earlier somewhere?

**Comment by yuwata** [comment]
The function is called in various path. I think the current place of the check is the simplest and safest.

**Comment by evverx** [comment]
Fair enough. Thanks!

**Pull request merged**
