### PR TITLE
networkd: FIONREAD is not reliable on some sockets

### PR DESCRIPTION
**Pull request by poettering**
Fixes: #2457

### CODE REVIEW

**Comment by poettering** [comment]
Before this is merged, let's wait for @gdamjan to report back if the patch actually fixes his problem.

**Comment by gdamjan** [comment]
seems to work

**Comment by zonque** [comment]
Semaphore doesn't like this PR because the DHCP tests are failing. I already restarted them, but the error is reproducible.

**Comment by poettering** [comment]
force pushed a new version that hopefully fixes things on semaphore. @gdamjan any chance you could give this one a whirl, too?

**Comment by poettering** [comment]
nice, semaphore likes it now too.

**Comment by gdamjan** [comment]
it does work for me

**Pull request merged**
