### PR TITLE
systemctl: set-property returns ERANGE if CPUShares or blkio_weight set to -1

### PR DESCRIPTION
**Pull request by jrybar-rh**
Proposed by Michal Sekletar.

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, but setting this to "-1" is a bit strange, no? Why should we support such a syntax? Did we document that to work anywhere? It appears so unnecessarily technical to me

**Comment by msekletar** [comment]
Well, we were under the impression that this used to work before. We received bug for RHEL were customer was complaining that after upgrade (actually it was filed by support on customer's behalf) reset via ```systemctl set-property <service> CPUShares=-1``` no longer works.

We noticed that in upstream this doesn't work either. But if that is by design and -1 was never supposed to reset the value then we can drop this. Also, this would imply that customer is either lying or was doing something wrong. We need to go back and test the old version (systemd-208).

**Comment by poettering** [comment]
I am pretty sure this never worked (and definitely not documented), and am I now convinced we should make it work

**Comment by msekletar** [comment]
Seems like the main source of confusion is commit message from this commit,
https://github.com/systemd/systemd/commit/d53d94743c5e5e3a4a668b0c707826a90a08949

It reads,

```
When parsing the weight/shares settings from unit files accept the empty
string as a way to reset the weight/shares value. When getting it via
the bus, uniformly map (uint64_t) -1 to unset.
```

**Comment by msekletar** [comment]
This commit confused support rep and that is why he filled bugzilla requesting backport of that commit. However, even after backport -1 doesn't reset the value. That is why I told Jan to fix this.

**Comment by poettering** [comment]
the -1 thing is actually never exposed to the user really. It's an internal way to denote "no limit", and is actually not even -1, but UINT64_MAX, just written in a weird way

**Comment by msekletar** [comment]
> the -1 thing is actually never exposed to the user really. It's an internal way to denote "no limit", and is actually not even -1, but UINT64_MAX, just written in a weird way

Thanks for the clarification.  I think we can close this PR.

**Pull request closed without merging**
