### PR TITLE
networkd: use socket activation when starting networkd

### PR DESCRIPTION
**Pull request by mbiebl**
Add After=systemd-networkd.socket to avoid a race condition and networkd
falling back to the non-socket activation code.

Also add Wants=systemd-networkd.socket, so the socket is started when
networkd is started via `systemctl start systemd-networkd.service`.
A Requires is not strictly necessary, as networkd still ships the
non-socket activation code. Should this code be removed one day, the
Wants should be bumped to Requires accordingly.

See also 5544ee85163733eaa50f598fcf3bd9421d4a42f9.

Fixes: #16809

### CODE REVIEW

**Comment by yuwata** [comment]
The change itself looks good to me. But tests need to be updated.

**Comment by mbiebl** [comment]
@yuwata It's not clear to me, why this change breaks the test suite. Can you help here?

**Comment by mbiebl** [comment]
```
======================================================================
ERROR: test_bridge_port_priority (__main__.BridgeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest-lxc.fkkqmmkh/downtmp/build.HlK/src/systemd-stable-246.2/test/networkd-test.py", line 238, in test_bridge_port_priority
    self.assertEqual(self.read_attr('port1', 'brport/priority'), '32')
  File "/tmp/autopkgtest-lxc.fkkqmmkh/downtmp/build.HlK/src/systemd-stable-246.2/test/networkd-test.py", line 145, in read_attr
    with open(os.path.join('/sys/class/net', link, attribute)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/net/port1/brport/priority'

======================================================================
ERROR: test_bridge_port_priority_set_zero (__main__.BridgeTest)
It should be possible to set the bridge port priority to 0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest-lxc.fkkqmmkh/downtmp/build.HlK/src/systemd-stable-246.2/test/networkd-test.py", line 249, in test_bridge_port_priority_set_zero
    self.assertEqual(self.read_attr('port2', 'brport/priority'), '32')
  File "/tmp/autopkgtest-lxc.fkkqmmkh/downtmp/build.HlK/src/systemd-stable-246.2/test/networkd-test.py", line 145, in read_attr
    with open(os.path.join('/sys/class/net', link, attribute)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/net/port2/brport/priority'

======================================================================
ERROR: test_bridge_port_property (__main__.BridgeTest)
Test the "[Bridge]" section keys
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest-lxc.fkkqmmkh/downtmp/build.HlK/src/systemd-stable-246.2/test/networkd-test.py", line 259, in test_bridge_port_property
    self.assertEqual(self.read_attr('port2', 'brport/priority'), '32')
  File "/tmp/autopkgtest-lxc.fkkqmmkh/downtmp/build.HlK/src/systemd-stable-246.2/test/networkd-test.py", line 145, in read_attr
    with open(os.path.join('/sys/class/net', link, attribute)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/net/port2/brport/priority'

----------------------------------------------------------------------
```
Odd:
```
# ls -la /sys/class/net/port2/brport/priority /sys/class/net/port1/brport/priority
-rw-r--r-- 1 root root 4096 27. Aug 12:34 /sys/class/net/port1/brport/priority
-rw-r--r-- 1 root root 4096 27. Aug 12:38 /sys/class/net/port2/brport/priority
```

**Comment by poettering** [comment]
patch looks good to me, but tests need to be fixed

**Comment by mbiebl** [comment]
Hm, seems I missed `test/test-network/systemd-networkd-tests.py`. Will update that test as well.
Is there a reason why we have `test/test-network/systemd-networkd-tests.py` *and* `test/networkd-test.py` as separate tests?

**Comment by mbiebl** [comment]
Since both @yuwata and @poettering acked the change and the tests have been fixed, I take the liberty to hit the merge button.

**Comment by yuwata** [comment]
Yes. LGTM.

**Pull request merged**
