### PR TITLE
architecture: Add support for the RISC-V architecture.

### PR DESCRIPTION
**Pull request by poettering**
Signed-off-by: Richard W.M. Jones rjones@redhat.com

### CODE REVIEW

**Comment by poettering** [comment]
BTW, we don't use S-o-b on systemd, that's a kernel thing. (But this is not a blocking issue, we just prefer patches without).

**Comment by poettering** [comment]
(This was generated from a patch sent to the ML: https://lists.freedesktop.org/archives/systemd-devel/2016-September/037521.html )

I comented on some issues by mail already:

https://lists.freedesktop.org/archives/systemd-devel/2016-October/037533.html

**Comment by zonque** [comment]
LGTM. @poettering, what is it that needs rework in your opinion?

**Comment by poettering** [comment]
See mailing list mail: I asked for the cover letter to be included in the patch' own commit msg, and would prefer to exclude the 128bit flavour in the patch since that's apparently just a paper excercise so far.

**Comment by rwmjones** [comment]
It seems to be impossible to update a pull request, or I don't know how.  So I opened a new one: https://github.com/systemd/systemd/pull/4305

**Comment by poettering** [comment]
To update a PR simply force push over the branch you submitted, and it will be updated correctly. However, that only works if you filed the initial PR yourself, afaiu. But since I created the github PR from your ML patch that wasn't you in this case. Or in other words: you did the right thing by filing a new PR.

Thanks!

**Pull request closed without merging**
