### PR TITLE
mkosi: update to latest

### PR DESCRIPTION
**Pull request by mrc0mmand**
To make Fedora builds happy again.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Note that opensuse will become rather flaky with this update because their https mirror fails with an HTTP/2 error all the time

**Comment by mrc0mmand** [comment]
> Note that opensuse will become rather flaky with this update because their https mirror fails with an HTTP/2 error all the time

Looks like we just can't never win.

**Comment by mrc0mmand** [comment]
And now Ubuntu and Debian builds fail as well, *sigh*...

**Comment by DaanDeMeyer** [comment]
> And now Ubuntu and Debian builds fail as well, sigh...

That's expected, I'll figure that out since it's caused by my recent changes

**Comment by mrc0mmand** [comment]
Superseded by https://github.com/systemd/systemd/pull/27329.

**Pull request closed without merging**
