### PR TITLE
Fix build of efi stuff in Fedora rawhide

### LINKED ISSUE #14762: build failure on rawhide
```
❯ make                                                                                                                                                                                     ─╯
ninja -C build
ninja: Entering directory `build'
[33/939] Generating systemd_boot.so with a custom command.
FAILED: src/boot/efi/systemd_boot.so 
/usr/bin/ld -o src/boot/efi/systemd_boot.so -T /usr/lib64/gnuefi/elf_x86_64_efi.lds -shared -Bsymbolic -nostdlib -znocombreloc -L /usr/lib64 /usr/lib64/gnuefi/crt0-efi-x86_64.o src/boot/efi/disk.c.o src/boot/efi/graphics.c.o src/boot/efi/measure.c.o src/boot/efi/pe.c.o src/boot/efi/util.c.o src/boot/efi/boot.c.o src/boot/efi/console.c.o src/boot/efi/crc32.c.o src/boot/efi/random-seed.c.o src/boot/efi/sha256.c.o src/boot/efi/shim.c.o -lefi -lgnuefi /usr/lib/gcc/x86_64-redhat-linux/10/libgcc.a
/usr/bin/ld: cannot find -lefi
/usr/bin/ld: cannot find -lgnuefi
[35/939] Generating stub.c.o with a custom command.
ninja: build stopped: subcommand failed.
make: *** [Makefile:2: all] Error 1
```

### PR DESCRIPTION
**Pull request by keszybz**
Fixes #14762.

### CODE REVIEW

**Comment by yuwata** [comment]
Hmm, not sure, but the CI failure may be related to this PR.

**Comment by keszybz** [comment]
It seems that the package is build with -Defi=true on arches which doesn't support uefi, and bootctl is packaged. I dropped the first patch to make this work again.

**Comment by keszybz** [comment]
semaphoreci failed with:
```
+ sudo lxc-create -n buster-amd64 -t download -- -d debian -r buster -a amd64 --keyserver hkp://keyserver.ubuntu.com:80
Setting up the GPG keyring
Downloading the image index
ERROR: Invalid signature for /tmp/tmp.be3s1I3eNF/index.asc
lxc-create: buster-amd64: lxccontainer.c: create_run_template: 1617 Failed to create container from template
lxc-create: buster-amd64: tools/lxc_create.c: main: 327 Failed to create container buster-amd64
```
Looks unrelated.

**Comment by ssahani** [comment]
I am hit by this

**Comment by keszybz** [comment]
centos ci (arch in kvm w/ sanitizers) failed with
```
 Command '['/build/build/systemd-networkd-wait-online', '--timeout=20s', '--interface=dummy98:degraded']'  returned non-zero exit status 1.
```
Looks unrelated.

@mrc0mmand

**Comment by mrc0mmand** [comment]
@keszybz yup, that's unrelated, tracked in #14764.

**Pull request merged**
