### PR TITLE
udevd: use extended synthetic uevent interface

### PR DESCRIPTION
**Pull request by prajnoha**
Kernel version 4.13 and higher supports extended synthetic uevent
interface which allows us to pass extra KEY=VALUE pairs, see also:

  https://github.com/torvalds/linux/blob/master/Documentation/ABI/testing/sysfs-uevent

Use this new interface to mark all uevents synthesized by udevd.
Currently, these are synthesized uevents to support the OPTIONS+="watch"
rule which are generated after a device open in write mode is closed.
This makes it much easier to identify such uevents among other uevents
back in userspace.

### CODE REVIEW

**Comment by poettering** [comment]
uh, kernel version checks? that's ugly, and something we generally avoid. You never know what kind of patched, backported kernel people run. Anything like this doesn't fly with RHEL or "stabilized" kernels like it. Please find a different way. If the kernel APIs aren't properly feature discoverable, then they should be fixed to be.

**Comment by prajnoha** [comment]
Yeah, I understand the aversion to kernel version checks... but unfortunately in this case, we'd need to create a new file in sysfs whose existence would indicate the /sys/.../uevent interface extension is there (not sure if kernel folks would like this, I wouldn't like it either). And we don't have something like kernel "feature flags" yet or "versioned sysfs files".

Another option is to try to generate a dummy synthetic uevent with extended format and check if it's received back in userspace or not (or check kernel log for particular error message) - this is even worse than checking the kernel version, so not a viable option either.

**Comment by poettering** [comment]
what happens if you generate one of these new events on the old kernel? does the kernel accept that? and if so, what does it do with it? if it refuses it it should be fairly simple to just try it first, and then fall back to the traditional way, and maybe cache this information to not bother the next time

**Comment by arvidjaar** [comment]
Before 4.13 kernel compared full input to action keyword and so if you supplied extra arguments it should have failed with `-EINVAL`. Starting with 4.13 kernel splits input on whitespace and compares just the first word.

So checking for `-EINVAL` when we supply multiple arguments should be fairly robust to detect old kernel.

**Comment by prajnoha** [comment]
> So checking for `-EINVAL` when we supply multiple arguments should be fairly robust to detect old kernel.

Unfortunately, this doesn't work because the kernel's sysfs store function responsible for writing the `uevent` file always returns the whole size of the buffer that was originally passed in - so practically, it doesn't return negative errors for indicating any error, it's always "success". Don't ask me why it was done this way - I don't know (and I don't like it), but it's there since day one, it seems.

There are two possibilities we can do here:

  **A)** We propose a kernel patch which will cause errors to get properly propagated on `uevent` file write operation failure. But then this is a change in behavior of something that was there for years and someone may rely on this behavior?

  **B)** We propose a patch for kernel to add a file that we can check for supported features, for example `/sys/kernel/core_features` (or `/sys/kernel/uevent_features` if we need to be less generic) and adding a line like `uevent_synth_args` there that we can check for (...this is already used throughout kernel, for example the `/sys/kernel/cgroup/features` file).

Honestly, I don't like any of A or B, but B seems to be more like it could be accepted.

**Comment by prajnoha** [comment]
The patch which fixes the `/sys/.../uevent` error code after a write failure is now in linux-next (scheduled for 4.21). Thinking of that, I'm not quite bothered anymore whether anyone has relied on the incorrect behavior where the write always returned "success", because udevd is the user of this interface in 99%. So we're OK here.

However, even with that patch, we still have the old kernels that we need to identify (we'd get "success" on old kernels still even if we passed incorrect string to the `uevent` file). In addition to that, when we're at it, it's good to have the `/sys/kernel/uevent_features` file to list the capabilities in the future. And this is something that's already used already, so it's not new (e.g. `/sys/cgroup/features`, `/sys/kernel/debug/sched_features`).

**Comment by prajnoha** [comment]
I've opened new pull request systemd/system#13881 which has broader coverage than just ``udevd``, so I'm closing this one, let's move the discussion to the new one please.

**Pull request closed without merging**
