### PR TITLE
resolved-dns-query: remove dns_query_candidate_is_routable

### LINKED ISSUE #5782: resolved does not honor v6 and v4 gateways on different interfaces
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### Background

I'm using systemd-networkd and systemd-resolved on a machine that has different interface for v4 and v6. The v4 interface (eth0) connects to ISP, and the v6 interface connects to HE.net Tunnelbroker. Here is the relevant networkd configuration:

```
$ cat default.network 
[Match]
Name=eth0

[Network]
Address=v4.addr/24
Gateway=v4.gateway
DNS=8.8.8.8
DNS=8.8.4.4
Tunnel=he-ipv6

$ cat heipv6.netdev 
[Match]

[NetDev]
Name=he-ipv6
Kind=sit
MTUBytes=1480

[Tunnel]
Local=v4.addr
Remote=he.remote.addr
TTL=255

$ cat heipv6.network 
[Match]
Name=he-ipv6

[Network]
Address=v6::addr/64
Gateway=v6::gateway
DNS=2001:470:20::2
DNS=74.82.42.42
IPForward=ipv6
```

And this line in `/etc/nsswitch.conf`:
```
hosts: files mymachines resolve [!UNAVAIL=return] dns myhostname
```

When it's up and running:
```
$ networkctl status
●        State: routable
       Address: v4.addr on eth0
                v6::addr on he-ipv6
                fe80::xxxxx on eth0
                fe80::xxxxx on he-ipv6
       Gateway: v4.gateway on eth0
                v6::gateway on he-ipv6
           DNS: 2001:470:20::2
                74.82.42.42
                8.8.8.8
                8.8.4.4
```

### Problem

Under this configuration, if the domain to be resolved only has A record (no AAAA), the resolution fails.

```
$ getent -s resolve ahosts www.twitter.com
$ # no output
```

Not a DNS expert but from my point of view, queries concerning AAAA and A should go to different DNS servers, and in this case it shouldn't fail.

### LINKED ISSUE #5915: systemd-resolved doesn't resolve AAAA records sometimes
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 232
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +ID

### Used distribution

> Arch Linux with stock 4.10.13-1-ARCH kernel

### In case of bug report: Expected behaviour you didn't see

> User applications (like curl/ping) resolve domain names with AAAA record only successfully without any special options specified.

### In case of bug report: Unexpected behaviour you saw

> Sometimes curl/ping cannot resolve domain names with AAAA record only without `-6` option.

### In case of bug report: Steps to reproduce the problem

Backgroud: I have an ethernet interface ens3 managed by systemd-networkd and a Tinc VPN interface. ens3 has a private IP on it and is routable to IPv4 network. As for Tinc VPN, I assigned an IPv6 unique local address and an IPv4 link-local address on it and is routable to corresponding private network.

```
$ networkctl status
●        State: routable
       Address: 10.0.199.19 on ens3
                169.254.248.36 on cvnet0
                fd38:dd3b:b524:80d5:fc25:70ff:fec9:19f5 on cvnet0
                fe80::f816:3eff:fe73:149a on ens3
                fe80::fc25:70ff:fec9:19f5 on cvnet0
       Gateway: 10.0.199.1 on ens3
           DNS: 114.114.114.114
                202.38.64.7
```

I create AAAA records which resolve IPv6 unique local address for my Tinc network:

```
$ dig +short AAAA loong.tinc.i-yu.me
fd38:dd3b:b524:80d5:fc86:8aff:fe7d:1f2b
```

But sometimes systemd-resolved won't resolve these address unless application ask for IPv6 address explicitly:

```
$ ping lace.tinc.i-yu.me
ping: lace.tinc.i-yu.me: Name or service not known
$ ping -6 -c1 lace.tinc.i-yu.me
PING lace.tinc.i-yu.me(fd38:dd3b:b524:80d5:fcec:efff:fede:c398 (fd38:dd3b:b524:80d5:fcec:efff:fede:c398)) 56 data bytes
......
```

And outputs of `systemd-resolve`:
```
$ systemd-resolve lace.tinc.i-yu.me
lace.tinc.i-yu.me: resolve call failed: 'lace.tinc.i-yu.me' does not have any RR of the requested type
$ systemd-resolve -6 lace.tinc.i-yu.me
lace.tinc.i-yu.me: fd38:dd3b:b524:80d5:fcec:efff:fede:c398

-- Information acquired via protocol DNS in 924us.
-- Data is authenticated: no
```

I say sometimes because sometimes it does work as expected (test at the same time, but another domain name).
```
$ systemd-resolve loong.tinc.i-yu.me
loong.tinc.i-yu.me: fd38:dd3b:b524:80d5:fc86:8aff:fe7d:1f2b

-- Information acquired via protocol DNS in 1.1ms.
-- Data is authenticated: no
```

I've read #5782,  poettering says "if you do not specify the address type you are looking for then we'll suppress answers for protocols we consider "unroutable" on the local system". I'm sure that both IPv6 address is routeable:

```
$ ip r get fd38:dd3b:b524:80d5:fc86:8aff:fe7d:1f2b
fd38:dd3b:b524:80d5:fc86:8aff:fe7d:1f2b from :: dev cvnet0 proto kernel src fd38:dd3b:b524:80d5:fcd3:1aff:fe9d:649 metric 256  pref medium
$ ip r get fd38:dd3b:b524:80d5:fcec:efff:fede:c398
fd38:dd3b:b524:80d5:fcec:efff:fede:c398 from :: dev cvnet0 proto kernel src fd38:dd3b:b524:80d5:fcd3:1aff:fe9d:649 metric 256  pref medium
```

Not sure how to debug it. Any ideas? I'd like to help diagnose the bug.

### LINKED ISSUE #8017: nss_resolve makes getaddrinfo(3) fail resolution of ipv4 only hostnames if also connected via ipv6
### Submission type
 - Bug report

### systemd version the issue has been seen with
systemd         234-2ubuntu1

### Used distribution
kubuntu.
Local modifications: using only systemd-nertworkd and systemd-resolved.
I removed both dnsmasq and network-manager last year.

### Bug description
I am experimenting with IPv6, and have a working dual IP stack: connection can go both through IPv4 and IPv6.
IPv6 is through a 6in4 tunnel with he.net, the local endpoint of the tunnel is on the same machine where nss_resolve in argument is failing.
```
$ cat /etc/systemd/network/he-tunnel.netdev
        [Match]
        
        [NetDev]
        Name=he-ipv6
        Kind=sit
        MTUBytes=1480
        
        [Tunnel]
        Local=192.168.xx.xx
        Remote=216.66.xx.xx
        TTL=255
        
$ cat /etc/systemd/network/he-tunnel.network
        [Match]
        Name=he-ipv6
        
        [Network]
        Address=2001:470:xxxx:xxxx::2/64
        Gateway=2001:470:xxxx:xxxx::1
        DNS=2001:470:20::2
        DNS=74.82.42.42
```
When the machine has this in /etc/nsswitch.conf:
```
# /etc/nsswitch.conf
...
hosts:          files resolve [!UNAVAIL=return] dns
... 
```
and in WHEN THE TUNNEL IS UP, that is when both IPv4 and IPv6 connection are available, nss_resolve returns nothing if the name to resolve has **only A records in the DNS** and resolution is invoked through **`getaddrinfo(3)`**. It works if invoked through `gethostbyname2(3)`.
serverfault.com is just one of such hosts today; an innocent involved because happened to be the first whose name resolution failed on me.
The difference between hosts and ahosts in getent, from getent(1) man page: ahosts uses getaddrinfo(3), hosts uses gethostbyname2(3).

### In case of bug report: Unexpected behaviour you saw,  exhibited from libnss_resolve
```
$ getent ahosts serverfault.com
        # No results!
$ getent hosts serverfault.com
        151.101.193.69  serverfault.com
        151.101.129.69  serverfault.com
        151.101.65.69   serverfault.com
        151.101.1.69    serverfault.com
```
### In case of bug report: Expected behaviour, exhibited from libnss_dns
To get correct behavior, removed nss_resolve from /etc/nsswitch.conf
```
# /etc/nsswitch.conf
...
hosts:          files dns
... 
```
and now name resolution works as expected:
```
$ getent ahosts serverfault.com
        151.101.193.69  STREAM serverfault.com
        151.101.193.69  DGRAM  
        151.101.193.69  RAW    
        151.101.129.69  STREAM 
        151.101.129.69  DGRAM  
        151.101.129.69  RAW    
        151.101.65.69   STREAM 
        151.101.65.69   DGRAM  
        151.101.65.69   RAW    
        151.101.1.69    STREAM 
        151.101.1.69    DGRAM  
        151.101.1.69    RAW   
$ getent hosts serverfault.com 
        151.101.193.69  serverfault.com
        151.101.129.69  serverfault.com
        151.101.65.69   serverfault.com
        151.101.1.69    serverfault.com
```
libnss_dns is using the stub resolver provided by systemd-resolved on 127.0.0.53, and returns the A records also to getaddrinfo(3).

### PR DESCRIPTION
**Pull request by flokli**
Resolved can't reliably determine on whether "it makes sense" to query
AAAA records when not explicitly specifying it in the request, so we
shouldn't remove them.

After having done the resolving, applications can use RFC6724 to
determine whether that address is reachable.

We can't know whether an address is reachable before having resolved it
and inspecting the routing table, and not resolving AAAA just because
there's no IPv6 default route on the main interface link them breaks
various setups, including IPv6-providing wireguard tunnels on a
non-dualstacked environment.

Fixes #5782
Fixes #5915
Fixes #8017

cc @poettering @ssahani @andir @Mic92 @petabyteboy @fpletz

### CODE REVIEW

**Comment by flokli** [comment]
After that, `resolvectl query google.com` returns A and AAAA` records, even on a not-dualstacked network, and `ping -6 google.com` works with the "IPv6 provided via wireguard" setup.

**Comment by flokli** [comment]
ping @yuwata

**Comment by flokli** [comment]
Is there anything preventing this from getting merged?

**Comment by pemensik** [comment]
This is removing in my opinion useful feature, because that feature had implementation error. I think the problem with it was it checked only routes on interface associated with the queried server. Instead, it should have checked global routes and if there were ANY not link-local route, then it should have enabled AAAA. Just one route to VPN should enable AAAA queries or A queries. If that have been fixed instead, it would behave correctly.

**Pull request merged**
