### PR TITLE
homed: remove PAM_USER_UNKNOWN test in pam_sm_acct_mgmt

### PR DESCRIPTION
**Pull request by chandradeepdey**
Addresses #16906

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, any chance you can extend the commit message a bit, i.e. a brief summary why this change is necessary, and what the recommended handling of the error should be within the PAM stack?

**Comment by chandradeepdey** [comment]
Done @poettering

**Comment by poettering** [comment]
So, should we update the example stack from the pam_systemd_home man page in any way? As I understand it's probably OK the way it is, as on PAM_SUCCESS we are done now, and on PAM_USER_UNKNOWN we'd proceed with pam_unix.so. Did I get this right?

**Comment by chandradeepdey** [comment]
I can add that example from the issue if you want. The two have different trade-offs, the manpage one stops malicious actors from knowing how exactly the stack failed, the issues one allows users to know when to contact admin about expired account and when they are just timed out.

**Pull request merged**
