### PR TITLE
bootchart: Account CPU time spent in non-main threads of the process

### PR DESCRIPTION
**Pull request by gmacario**
This is aimed at fixing Bug https://github.com/systemd/systemd/issues/139

### CODE REVIEW

**Comment by teg** [comment]
Overall seems reasonable, though have a look through CODINGSTYLE and see the inline comments.

**Comment by gmacario** [comment]
Hello @teg,

Thanks for your comments - do you want me to submit another Pull Request, or would it be OK if I update the branch and do git push --force here?

**Comment by zonque** [comment]
No, please file a new PR, and close this one.

**Comment by gmacario** [comment]
Hello,

I submitted a new PR as https://github.com/systemd/systemd/pull/334

Hopefully the new PR should address all reviewers comments.

Thanks,
Gianpaolo

**Pull request closed without merging**
