### PR TITLE
Revert "analyze: extend the dump command to accept patterns"

### PR DESCRIPTION
**Pull request by poettering**
Reverts systemd/systemd#24659

This is not ready to be merged.

Generally, i think it's a useless feature. it's not that hard to use the search feature in your pager instead.

But at the very least the bus method should be named better i.e. "DumpByUnitPattern()". And it should return a memfd, not a string, because this is bulk data, and just repeats the mistake of Dump().

Also, it's a bit late to merge API altering, not thought to the end stuff like is in an rc1

### CODE REVIEW

**Comment by fbuihuu** [comment]
> Generally, i think it's a useless feature. it's not that hard to use the search feature in your pager instead.

I would still be interested to know how this search feature in your pager could be as easy as grepping  after limiting the output of the dump. I had to do this repeatedly during the same debug session and I can't see how this could be achieved.

> But at the very least the bus method should be named better i.e. "DumpByUnitPattern()". And it should return a memfd, not a string, because this is bulk data, and just repeats the mistake of Dump().

FWIW, fine by me even though I assumed that if the size of the data returned by `Dump()` was initially acceptable (until `DumpByFileDescriptor()` was introduced) then limiting the dump to a couple units shouldn't cause issue in practice.

**Comment by keszybz** [comment]
Sorry, but this arguments for revert are very weak. As described and explained by multiple people, it is *useful*. Maybe not to everybody, but that is OK. We have many features which are useful to some people and not to others. This is very much a convenience feature that may be used by 0.01% of users, and that is still OK, it doesn't hurt or even inconvenience others in any way.

About the name: `DumpUnitsByPatterns` is probably better (or maybe even `DumpUnitsMatchingPatterns`?).

About memfd: it's a bit of a judgement call. I asked for remote operation for consistency with other tools. It *is* possible that this will not see much use, but in general consistency is nice and has a lot of value on its own. The approach with memfds seems overkill for the intended use. My example with `"*"` was intended partially as a joke. In that scenario, you'd use DumpByMemfd, i.e. `systemd-analyze dump` with no arguments, instead.

**Comment by poettering** [comment]
I think is feature is useless, but sure, if you really think stuff all kind of arbitrary debug garbage into PID 1 for some borderline debugging usecase makes sense, then fine.

Either drop the pattern stuff or switch this to work like DumpByFileDescriptor and return an fd. And drop the string version.

**Comment by keszybz** [comment]
I submitted a PR to rename the method.

Regarding the fd vs. string: ideally, we'd have two methods: one that returns an fd so that very large dumps work, and one that returns a string so that remote operations also work, and implement a fallback between the methods. If we have one or the either, we do some tradeoff between what works. Neither the case of remote operations or the case of very large dumps is important in practice. This method is *designed* to filter the units, so we realistically expect short outputs. The limit for dbus messages is 128MB, so while it is theoretically possible to exceed it, it doesn't seem likely, and in particular not with this interface. On my system with 2k units the full dump is 1.8 MB, so one would need a system with 130k unit *and* they'd need to out of their way to filter with a non-filter to get all units. I think the issue is bogus.

**Comment by poettering** [comment]
> Regarding the fd vs. string: ideally, we'd have two methods: one that returns an fd so that very large dumps work, and one that returns a string so that remote operations also work, and implement a fallback between the methods.

I don't think we should bother with remote support for this. It's a redundant interface, it's debugging, it really doesn't have to cover everything.

>  If we have one or the either, we do some tradeoff between what works. Neither the case of remote operations or the case of very large dumps is important in practice. This method is _designed_ to filter the units, so we realistically expect short outputs. The limit for dbus messages is 128MB, so while it is theoretically possible to exceed it, it doesn't seem likely, and in particular not with this interface. On my system with 2k units the full dump is 1.8 MB, so one would need a system with 130k unit _and_ they'd need to out of their way to filter with a non-filter to get all units. I think the issue is bogus.

Don't transport bulk data via D-Bus.

I'd be less annoyed by this if this wouldn't take a unit name pattern, i.e. can match any unit. Either drop supports for patterns, and just accept a single unit name, or just use memfds.

**Comment by poettering** [comment]
(even if the broke limit is 128M it's just terrible to actually rely on that and bounce that much data off the broker... it's terribly bad at this, and makes things slow, and still counts to PID1's transfer budget, which we shouldn#t waste like that. Really, this has to be memfds.)

**Comment by keszybz** [comment]
It's a **debugging interface**. Who cares that it it counts towards the budget? Nobody cares about the budget. You make a call and then spend 10 minutes looking at the output. It just works as advertised without any problems whatsoever.

**Comment by poettering** [comment]
dbus broker cares, and will kick off pid 1 because it spams the bus, sooner or later. If you send bulk data over thus bus this means you get pid 1 kicked off the bus... let's not even risk this, as clients typically cannot safely recover if we leave the bus and come back. And you certainly don't want to trigger this when debugging.

**Comment by dtardon** [comment]
If extending the dump capabilities is really desirable, wouldn't it be better to add dump by a machine-readable format (json?) and do any postprocessing/filtering in `systemd-analyze`? That would allow to extend the filtering even on saved dumps (provided they were created by the same systemd version). Or filtering by other properties could be added. There is already at least one debugging tool with json output (`busctl monitor`), so `systemd-analyze dump` wouldn't be the first and only one...

**Comment by keszybz** [comment]
> If extending the dump capabilities is really desirable, wouldn't it be better to add dump by a machine-readable format (json?) and do any postprocessing/filtering in `systemd-analyze`?

Hmm, maybe. I think this is an interesting idea, but this is a fairly big project that we can consider for the future. If that happens, I think we should redo the serialization for daemon-reload and daemon-reexec to use this. I.e. replace the custom (and buggy) serialization logic with a generic json serialization-deserialization protocol, and then also use to exfiltrate internal state from the manager.

> dbus broker cares, and will kick off pid 1 because it spams the bus, sooner or later. 

Are there some docs for this? I tried to get dbus-broker to kick pid1 off, but I couldn't get it to do that. @dvdhrm ptal.

```sh
for i in {0..10000}; do echo -n "$i " && systemd-analyze dump '*' | wc -c || break; done
```

(Anyway, this sounds sketchy. Because if pid1 could be kicked for sending too many messages, something like daemon-reload with a bunch of unit status signals being sent could trigger this. So if something like that was in place, we'd probably need to remove it.)

**Comment by dnicolodi** [comment]
I was going to suggest more or less what @dtardon suggested. If that is seen as a better solution, maybe `DumpUnitsMatchingPatterns` DBus method should not be included in the next release, as everything is released becomes de-facto API and cannot be (easily) removed. I don't think the serialization rework @keszybz mentions in his comment is necessary to make `systemd-analyze` consume a dump in a machine readable format.

**Comment by keszybz** [comment]
No, this is backwards. The current method works just fine and in practice has no shortcomings, except for the name. With this trivial PR merged, it's all ready for release. If we were to add an fd-based method, it would be an *addition* — i.e. we would use the fd-based method for local connections and fall back to the existing method for remote connections. So even if we were to do this, it's fine to do it later, since it's a backwards-compatible addition.

That said, as discussed and demonstrated above, it seems that this would be just busywork, because the current method is fit for the intended purpose and works just fine. If you want to do the busywork, please go ahead. Just please don't ask other people to do it without a good reason.

**Comment by dvdhrm** [comment]
> > dbus broker cares, and will kick off pid 1 because it spams the bus, sooner or later.
> 
> Are there some docs for this? I tried to get dbus-broker to kick pid1 off, but I couldn't get it to do that. @dvdhrm ptal.

dbus-daemon will actively refuse message transmission if you exceed the global resource limits of a user. This means a pending debug-message can cause *any* other message of that sender to be discarded. This is really annoying for replies or signals, cause you do not expect them to get an error-return from the broker.

dbus-broker accounts resources differently, and in case of replies it will account them on the receiver. Thus, you cannot get pid1 kicked this way unless the receiver shares a UID with PID1.

Dumping large chunks of data on a control-channel-optimized IPC is strongly discouraged. In case of D-Bus, you will block the bus for the time it takes to copy the data, you will incur huge buffers in the broker because D-Bus requires message payloads to be read in full, and you put lots of strain on the resource quotas of the UIDs involved. Even if the operation involved is considered a debug operation, it will have negative effects on the running system. Best case, it just stalls message transactions for a bit, but worst case you will cause other transactions to fail because the UIDs involved exceeded their quota.

Details on the resource accounting strategy of dbus-broker are explained in its [docs](https://github.com/bus1/dbus-broker/wiki/Accounting).

> (Anyway, this sounds sketchy. Because if pid1 could be kicked for sending too many messages, something like daemon-reload with a bunch of unit status signals being sent could trigger this. So if something like that was in place, we'd probably need to remove it.)

Yes, daemon-reload is a highly resource intensive operation and without proper care can cause disruption. The resource-accounting model of dbus-broker exists because of such issues and the inability of dbus-daemon to distinguish actors in its accounting-scheme.

However, be aware that sending a memfd does not magically rid you of any accounting issues. On the contrary, you suddenly lose control over it. For debug messages, IMO, it is the right call, though.

**Pull request closed without merging**
