### PR TITLE
A few unrelated fixes

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
@mrc0mmand ptal.

**Comment by keszybz** [comment]
LGTM.

**Comment by keszybz** [comment]
I see that msan is run with -Dvalgrind=true in tests anyway. So the last commit will not "fix" anything, but it still seems to be the right thing to do.

**Comment by mrc0mmand** [comment]
Thank you! LGTM, will rebase the MSan PR a sort out the rest of the fails once this is merged.

**Pull request merged**
