### PR TITLE
libudev: remove check for root user sender

### PR DESCRIPTION
**Pull request by akvadrako**
I am running some apps in a user namespace, created with `unshare -U`. They use libudev to listen for hardware changes, but this doesn't work with current systemd, version 245.r1852.gf49bead3b0. This is because libudev filters out events that aren't from uid=0 and in a user namespace the real uid=0 is mapped to uid=65534.

The check for sender uid=0 is unnecessary because:
1. Events from the kernel always have nl_pid=0, which libudev checks.
2. Root is the only user allowed to send messages to a mulitcast group. According to **netlink(7)**
> Only processes with an  effective UID  of  0  or the CAP_NET_ADMIN capability may send or listen to a netlink multicast group.
> ...
> As  at  Linux  3.0,  the  NETLINK_KOBJECT_UEVENT,  NETLINK_GENERIC,  NETLINK_ROUTE, and NETLINK_SELINUX groups allow other users to receive messages.  No groups allow other users to send messages.
3. libudev checks that all messages were either from a trusted sender or sent to a group.

This patch removes the check for sender uid=0, which allows libudev to work inside user namespaces. It would be very helpful if this patch was accepted upstream.

### CODE REVIEW

**Comment by poettering** [comment]
what happens to nl_pid if a process in a different PID namespace sends a message?

**Comment by poettering** [comment]
So the patch is definitely incomplete. If we really don#t have to check the sender anymore, then you need to drop a lot more, i.e. te buffer this is read on, or the fact that we enable stuff.

Quite frankly though I am pretty sure your namespace is just badly set up: map uid 0 to uid 0... That's the correct fix...

I am not convinced this is a good idea, in particular as this behaviour has changed in the various historic kernels.

At the very least, please track down when these checks were first added, I figure the commits have some explanations.

**Comment by akvadrako** [comment]
> what happens to nl_pid if a process in a different PID namespace sends a message?

There is no translation for `sender.nl_pid`; since this is a port ID and might not match a process. I tested this and they are unique across pid namespaces. Where you thinking we could check this instead? That would at least unify the unicast and multicast security checks.

Acccoriding to *pid_namespaces(7)* it is mapped for SCM_CREDENTIALS on unix sockets:

       When a process ID is passed over a UNIX domain socket to a process in
       a different PID namespace (see the description of SCM_CREDENTIALS in
       unix(7)), it is translated into the corresponding PID value in the
       receiving process's PID namespace.

However, my testing shows this isn't the case for netlink; ucred.pid=1 in a pidns shows up as ucred.pid=1 in the outer namespace.

> So the patch is definitely incomplete. If we really don't have to check the sender anymore, then you need to drop a lot more, i.e. te buffer this is read on, or the fact that we enable stuff.

I was thinking we still check the sender in the case of a unicast messages, but of course that uses nl_pid instead. So indeed if this change is acceptable I'll remove the extra stuff.

> Quite frankly though I am pretty sure your namespace is just badly set up: map uid 0 to uid 0... That's the correct fix...

That will often go against the standard usage of unprivileged user namespaces, which is to pretend to be root; this is the method tools like *bubblewrap* and *unshare* support. Being able to map 0->0 requires configuring `/etc/subuid` for each user, so needs root privilages, and complicates more complex cases where you'll map a range of outer UIDs (like 10000-11000) to inner UIDs (0-1000).

> I am not convinced this is a good idea, in particular as this behaviour has changed in the various historic kernels.

It would be good to have a guarantee, though I suppose the general kernel policy of not breaking userspace by opening new security holes is sufficient.

> At the very least, please track down when these checks were first added, I figure the commits have some explanations.

This check was always there, added in this commit by @yuwata:

commit b1c097af8df58a94cba031a347061b7cb9b62d9b
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Mon Oct 8 22:45:52 2018 +0900

    sd-device: introduce sd_device_monitor

**Comment by yuwata** [comment]
> This check was always there, added in this commit by @yuwata:
> 
> commit [b1c097a](https://github.com/systemd/systemd/commit/b1c097af8df58a94cba031a347061b7cb9b62d9b)
> Author: Yu Watanabe [watanabe.yu+github@gmail.com](mailto:watanabe.yu+github@gmail.com)
> Date: Mon Oct 8 22:45:52 2018 +0900
> 
> ```
> sd-device: introduce sd_device_monitor
> ```

The check has existed since the function was introduced as `udev_monitor_get_device()`. See ba6929f6690a72485ac3c6b7610ffbd5ab319be7.

**Comment by akvadrako** [comment]
I just realized the opposite issue with uid mapping exists too → if I'm running `udevadm monitor` in a userns with uid 1000 mapped to uid 0, then it accepts messages from the outer namespace with ucred.uid set to 1000.

**Comment by akvadrako** [comment]
OK, I have removed the extra code around receiving credentials.

Do you also want me to add a check for nl_pid? If init doesn't use it, it could be hard-coded to 1. Otherwise, we could write to `/run/udev/nl_pid`. This could also be used by udev children - unifying the access checks.

If there is still some doubt that these user namespace are properly setup, I would like to point out it's also how flatpak does it; root is mapped to nobody.

**Comment by poettering** [comment]
Hmm, revisiting this. I am still not convinced dropping the check is actually a good idea,  checking that the source is trusted *within the current namespace* does make a lot of sense to me.

You mention bubblewrap, does bubblewrap not map 0:0? @alexlarsson, how does bubblewrap currently deal with hw events/libudev/netlink? does it care at all to make this work?

**Comment by alexlarsson** [comment]
> Hmm, revisiting this. I am still not convinced dropping the check is actually a good idea, checking that the source is trusted _within the current namespace_ does make a lot of sense to me.
> 
> You mention bubblewrap, does bubblewrap not map 0:0? @alexlarsson, how does bubblewrap currently deal with hw events/libudev/netlink? does it care at all to make this work?

Bubblewrap has options to define the mapping. You generally map the calling uid to itself or 0, but can really specify anything. However, (since its unpriv) all other uids map to the overflow uid (nfsnobody or whatever). In flatpak, we map user-uid to user uid.

As for udev, I asked on the systemd mailing list many years ago about the ABI stability of the udev protocol and was told that there was none (i.e. libudev must match udevd version), so flatpak doesn't currently expose any udev sockets or databases in the sandbox. At least by default, I guess apps can ask for exposing specific areas.

Of course, this isn't necessarily ideal. If we had a way to expose udev that would be nice...

**Comment by poettering** [comment]
> As for udev, I asked on the systemd mailing list many years ago about the ABI stability of the udev protocol and was told that there was none (i.e. libudev must match udevd version), so flatpak doesn't currently expose any udev sockets or databases in the sandbox. At least by default, I guess apps can ask for exposing specific areas.

Yeah, that still applies. I mean, effectively the protocol has been pretty stable, besides that bind/ubind mess, but philosophically we want the freedom to change stuff...

**Comment by poettering** [comment]
@akvadrako compromise would be to accept packets coming from 0 and our own uid. That feels reasonably safe, and should mostly address your issue, no? I mean, it still means we won't accept from the overflow UID, but i think that's inherently a good thing: we should not accept stuff from sources so untrusted they don't even have a sane mapping in the local userns.

**Comment by akvadrako** [comment]
> @akvadrako compromise would be to accept packets coming from 0 and our own uid. That feels reasonably safe, and should mostly address your issue, no? I mean, it still means we won't accept from the overflow UID, but i think that's inherently a good thing: we should not accept stuff from sources so untrusted they don't even have a sane mapping in the local userns.

How would that help? The external root user isn't mapped to my user id.

**Comment by poettering** [comment]
> How would that help? The external root user isn't mapped to my user id.

Well, but in that case we really shouldn't trust it.

> 
> What I am doing with containers I would also like to be able to do with flatpak. I realize the libudev versions need to match, but that's an acceptable limitation for now.

As @alexlarsson suggested flatpak seems to map root to either root or the user itself, hence this should just work? What am I missing?

**Comment by akvadrako** [comment]
> > How would that help? The external root user isn't mapped to my user id.
> 
> Well, but in that case we really shouldn't trust it.

We can trust it because only root can send such messages. For an extra check I proposed using the same mechanism as used by udev children, which is to check the `nl_pid` is what the master process is using, perhaps hard-coding it to 1.

> As @alexlarsson suggested flatpak seems to map root to either root or the user itself, hence this should just work? What am I missing?

flatpak always (I think) maps *real root* to *nobody*. bubblewrap normally maps *real current-uid* to the same id or *real current-uid* to *root*, not the other way around.

**Comment by akvadrako** [comment]
Actually, I think allowing messages from the current uid would be acceptable if it was possible to send netlink messages from normal users. Then one could run a udev proxy which, like a dbus proxy, provides a stable API to sandboxed apps.

Since that isn't possible, maybe the best option is to fork libudev that presents the same (stable) API to apps but accepts messages in a standardized format from an external proxy.

**Comment by bluca** [comment]
@akvadrako @alexlarsson is this still relevant? Been a while (sorry)

**Comment by akvadrako** [comment]
@bluca I still maintain a patched libudev because otherwise it's not possible to receive udev events inside a user namespace like those created by bubblewrap. So for me it's still relevant.

**Comment by yuwata** [comment]
I opened a replacement #24587.

**Comment by poettering** [comment]
Let's close this in favour of #24587

**Pull request closed without merging**
