### PR TITLE
Tests for DnsQuestion functions

### PR DESCRIPTION
**Pull request by jcoglan**
This is James from @neighbourhoodie, I have been working on the STF milestone M1 to improve test coverage, focussing on `resolved`. We have written a lot of tests for this module and we are splitting the work into a number of PRs, one for each test file we've added. Each new test file usually corresponds to a single source file, and exercises the functions in that source file directly.

This PR includes tests for `resolved-dns-question.c`, providing coverage of functions relating to `DnsQuestion` objects.

### CODE REVIEW

**Comment by jcoglan** [comment]
I believe I have fixed all the issues with the files in this PR -- asan/ubsan problems, gcc/clang differences, linter checks, etc. and the remaining failing CI tasks are failing for reasons other than the changes here. If that's incorrect and there are other things I still need to change, do let me know what else I need to do.

**Comment by bluca** [comment]
As per the other PR, please add asserts around calls that allocate memory/objects

**Comment by jcoglan** [comment]
@bluca I have now put null checks after all the calls that allocate in this PR.

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
merged manually to solve trivial merge conflict

**Pull request closed without merging**
