### PR TITLE
Add a few `struct timespec`-related types to `test-sizeof`

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
(btw, if we want to speed up building, I think we might want to switch to Meson eventually)

**Comment by keszybz** [comment]
It requires out-of-tree builds. If you're fine with that, meson would be worth checking out.

**Comment by poettering** [comment]
oot builds appear desirable even I think.

**Comment by mbiebl** [comment]
To get more familiar with meson, I've test-converted systemd-bootchart (without the man page generation yet) a couple of days ago. This was rather straightforward and I liked what I saw. 

That it enforces ootb I consider positive as well.

systemd is of course an entirely different beast then systemd-bootchart, so support for meson will most likely be non-trivial and a significant amount of work. That said, I'd be interested to see such a meson port happen.

My only concern (from meson still being quite young and possibly in flux) is that this might make bootstrapping on new architectures a bit harder as you need python3 for meson.

**Comment by keszybz** [comment]
I wouldn't worry about that portability. Python (and in particular Python3) should be pretty widely available. Although http://buildbot.python.org/all/grid is less diverse than I remember it.

**Comment by poettering** [comment]
yeah, I have the suspicion that python is actually more portable than systemd by a long shot, and hence I am not too concerned... Moreover we already have a (vague) python dep anyway, through our tests and stuff, so this doesn't make things much worse dep-wise either...

**Pull request merged**
