### PR TITLE
test-execute: drop capabilities when testing with user manager

### PR DESCRIPTION
**Pull request by yuwata**
This also adds simple tests for LoadCredential= and SetCredential=.

### CODE REVIEW

**Review by keszybz — COMMENTED** [review]
I didn't follow all the test changes in detail, but if they pass, then it seems OK to merge. The tests at least correctly describe current behaviour.

**Comment by bluca** [comment]
The ubuntu CI is hosed, please wait a day or so for that go get back in shape as this changes this test quite extensively, so that we can be sure there are no issues on that platform

**Comment by bluca** [comment]
> The ubuntu CI is hosed, please wait a day or so for that go get back in shape as this changes this test quite extensively, so that we can be sure there are no issues on that platform

outage is still not solved, so let's keep this for the next release, distros will already have tested rc3 in their build systems so better to be safe than sorry

**Comment by yuwata** [comment]
> > The ubuntu CI is hosed, please wait a day or so for that go get back in shape as this changes this test quite extensively, so that we can be sure there are no issues on that platform
> 
> outage is still not solved, so let's keep this for the next release, distros will already have tested rc3 in their build systems so better to be safe than sorry

Sure, no problem.

**Comment by poettering** [comment]
hmm, this breaks "test-execute" when run as root currently in main. I am puzzled why this wasn't noticed in CI?

**Pull request merged**
