### PR TITLE
network: add an option to control announcement of delegated prefix

### LINKED ISSUE #17353: networkd: Cannot disable RAs when IPv6 prefix delegation is enabled
**Is your feature request related to a problem? Please describe.**

systemd-networkd is able to assign an IPv6 address/prefix it receives from an upstream interface via DHCPv6-PD to local interfaces. Right now systemd-networkd handles that case through this configuration:

```
[Network] 
IPv6PrefixDelegation=dhcpv6

[DHCPv6PrefixDelegation] 
Assign=yes
```

The issue with this is that systemd-networkd assumes that it should always announce the delegated prefix through a RA on that interface. However there are environments where the announcement of the prefix is unwanted. These include environments where other tools, such as radvd or dnsmasq are used to announce the prefix – both tools provide many more options (which are out of the scope of networkd).

The current behavior kind of violates the usage patterns for many scenarios, where systemd-networkd is used for managing interface addresses, but not for providing services such as DHCP or RA.

**Describe the solution you'd like**

There should be an option for disabling RA sending for delegated prefixes. Possible config:

```
[DHCPv6PrefixDelegation] 
Assign=yes
Annouce=no    # should default to "yes" in order to keep compatibility with existing setups
```

**Describe alternatives you've considered**

There are no alternatives other than disabling systemd-networkd completely and configuring interfaces in the old-fashioned way (which is super annoying in environments with DHCPv6-PD).

### PR DESCRIPTION
**Pull request by yuwata**
Closes #17353.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @klada

**Comment by yuwata** [comment]
The CentOS CI (CentOS7) failure is not related.

**Comment by bartelsielski** [comment]
I don't think it makes sense to add an option related to router advertisements to the `[IPv6PrefixDelegation]` section.

The issue in #17353 seems to be regarding the horribly named `IPv6PrefixDelegation` setting in the `[Network]` section:

```
IPv6PrefixDelegation=
    Whether to enable or disable Router Advertisement sending on a link. ...
```

Wouldn't it make more sense to deprecate the `IPv6PrefixDelegation` setting in the `[Network]` section in favor of a better named one (`IPv6SendRA` maybe to mimic the `IPv6AcceptRA` setting). And allow the `[IPv6PrefixDelegation]` section to be configured independently (I don't know if they are/aren't inter dependent at the moment).

**Comment by klada** [comment]
First of all I would like to express huge thanks to @yuwata for coming up with a solution for this issue so quickly. This is awesome. :+1: 

@bartelsielski It's not just the setting which is horribly named. #17353 is legit, you simply cannot assign interface addresses from a delegated prefix without networkd also announcing the very same prefix at the same time. That's what the issue is about. See the man page entry for the `[DHCPv6PrefixDelegation]` section. And obviously coupling these two things (address assignment and prefix announcements) does not always make sense. So this PR actually fixes the issue.

However I do agree that the entire configuration of prefix delegation is quite clumsy at the moment. To be honest I never understood why there are different sections for `[IPv6PrefixDelegation]`, `[DHCPv6PrefixDelegation]` and `[IPv6Prefix]`. I know they partly do different things, but couldn't this still be handled through the same section? They are all related to prefixes. In an ideal world as a network admin I would actually expect a completely different config approach, something like this:

```
[Network]
# No specific network config for IPv6 if only prefix delegation should be used

[IPv6Prefix]
# Define that we want to configure a prefix which was delegated from another interface
Prefix=delegated
# The upstream interface which provides the prefix. Right now networkd guesses this, which could lead to undesired behavior when multiple upstream interfaces with DHCPv6-PD are enabled
PrefixDelegationInterface=ppp0
# Old config value: SubnetId
PrefixDelegationSubnetId=99
Assign=true
AssignToken=::1
Announce=true
# All the other options from [IPv6PrefixDelegation] and [IPv6Prefix] should be available as well, such as:
Managed=, OtherInformation=
RouterLifetimeSec=
RouterPreference=
# Right now it's also not possible to set these options for delegated prefixes, which could also be fixed by this approach
PreferredLifetimeSec=, ValidLifetimeSec=
```

In the end IMHO this would be much more explicit and more transparent for the user. But yeah, this would be a huge change which would probably break setups. I don't know if it's worth it. The solution from @yuwata seems much simpler and keeps compatibility with existing setups.

So my guess is that reworking the entire `[IPv6Prefix]` section (or whatever you want to name it) is actually a different issue. I don't know if the networkd folks want to do this at all, as it's probably a lot of work as it requires deprecation policies (and code) for the old settings.

**Comment by yuwata** [comment]
@bartelsielski and @klada Thank you for the suggestions. I will rework this.

**Comment by yuwata** [comment]
@bartelsielski and @klada, how about the following:
- Rename `IPv6PrefixDelegation=` and `[IPv6PrefixDelegation]` to `IPv6SendRA=` and `[IPv6SendRA]`.
- Make `IPv6SendRA=` take only boolean (Currently, `IPv6PrefixDelegation=` also takes `static` and `dhcpv6`.).
- Add `AnnounceDelegatedPrefix=` boolean setting in `[IPv6SendRA]` section, and make it enabled by default.
- Add new `DHCPv6PrefixDelegation=` boolean setting in `[Network]` section.
- Add `UpstreamInterface=` in `[DHCPv6PrefixDelegation]` section.

With this change, the old setting is mapped to the following:
- `IPv6PrefixDelegation=yes` -> `IPv6SendRA=yes` + `DHCPv6PrefixDelegation=yes` + `AnnounceDelegatedPrefix=yes`
- `IPv6PrefixDelegation=no` -> `IPv6SendRA=no` + `DHCPv6PrefixDelegation=no` (`AnnounceDelegatedPrefix=` is ignored)
- `IPv6PrefixDelegation=static` -> `IPv6SendRA=yes` + `DHCPv6PrefixDelegation=no` (`AnnounceDelegatedPrefix=` is ignored)
- `IPv6PrefixDelegation=dhcpv6` -> `IPv6SendRA=yes` + `DHCPv6PrefixDelegation=yes` + `AnnounceDelegatedPrefix=yes`

As you can see in the above, previously we cannot enable DHCPv6 PD without sending RA. But now we can set that intuitively.

I will update this PR in this way. Of course, any further suggestions and comments are always welcome.

**Comment by yuwata** [comment]
Force-pushed a WIP version.

**Comment by klada** [comment]
Thanks a lot for working on this. I think your suggested change clarifies the usage quite a bit.

A few questions/comments about this:

* `IPv6SendRA=true` still only refers to sending RAs of delegated prefixes, right? IMHO semantically this is still a bit unfortunate. Imagine a config which has `IPv6SendRA=false` and at least one  `[IPv6Prefix]` section. Will those static prefixes be anounced or not? What if I do not want to announce the delegated prefix, but all other static prefixes from `[IPv6Prefix]` sections (or vice versa)?
* After thinking about this for a bit I think it might be better if we could decide for each prefix (delegated and statically configured through `[IPv6Prefix]` ) whether we want to announce and/or assign it or not.
* I really like the fact that you have made the upstream interface configurable. This makes things much more explicit and understandable. I am pretty sure that this will tempt people to delegate prefixes from multiple upstream interfaces in the future. I am thinking of multi-wan environments with a wired and a wireless uplink which use the wireless uplink for failover. This could be implemented by sending RAs from the wired uplink with a higher priority than the RAs from the wireless uplink. And while this is completely out of scope of the original issue it might be wise to consider this usecase when touching the config format. Of course this does not need to be implemented yet, but when changing the config format it might be nice to consider whether the new format allows for more flexibility in the future.

That's actually the reason why I suggested to configure all prefix-related options in one (repeatable) section, such as `[IPv6Prefix]`. But yeah, that's a hard break and I don't know how you feel about that.

And I am sorry that such a small issue such as #17353 actually leads to such a big amount of work. Originally I did not think of changing the config format/options in such a radical way. And in fact no radical changes are required for your first approch (which is still legit, I think). But when you are actually thinking of changing the format, it's worth at least considering these other use-cases.

BTW: If you think that multi-WAN with DHVPv6-PD is out of scope of networkd this is also fine for me :smile:

**Comment by flo-wer** [comment]
So all the IPv6-Prefix/DHCPv6 config handling is indeed fucked up both semantically  and functionally. I think it is best to first get some clarification into the protocols. The following features are relevant in the IPv6 world:

1. Router Advertisement (via ICMPv6/Neighbor Discovery Protocol): includes information about the **router** (Managed, OtherInformation, Lifetime, DNS), **routes** (Prefix, Lifetime) and **prefixes** (Prefix, Autoconfiguration, OnLink, Lifetime)
2. DHCPv6: can be used for **stateful client configuration** (Address, Lifetime) if Router Advertisement Managed is on, **stateless client configuration** (DNS, ...) if Router Advertisement OtherInformation is on and **router configuration** (Prefix, Lifetime) for Prefix Delegation (if either M order O is, c.f. [RFC7084](https://tools.ietf.org/html/rfc7084) WPD-4)

Then there is the "official" terminology:
1. Everything that uses ICMPv6/Neighbor Discovery Protocol for configuration is either called `Router Advertisement` ([RFC4861 4.2](https://tools.ietf.org/html/rfc4861#section-4.2)) or `IPv6 Router Advertisement` (e.g. [RFC5175](https://tools.ietf.org/html/rfc5175), [RFC8106](https://tools.ietf.org/html/rfc8106)) depending on the context.
2. DHCP for IPv6 that configures clients is called plainly `DHCPv6` ([RFC8415](https://tools.ietf.org/html/rfc8415)).
3. The extension of DHCPv6 for delegating prefixes has no real distinct name. It was called `IPv6 Prefix Options for Dynamic Host Configuration Protocol` ([RFC3633](https://tools.ietf.org/html/rfc3633)) and now is `DHCP for Prefix Delegation` ([RFC8415 6.3](https://tools.ietf.org/html/rfc8415#section-6.3)), but usually used as `DHCPv6 Prefix Delegation` or `DHCPv6-PD`.

And as a desired feature for networkd to be "feature complete" (c.f. [RFC7084](https://tools.ietf.org/html/rfc7084)) is to have all the possible information (Prefix(es), DNS, ...) to be dynamically obtained from "upstream" and distributed "downstream".

From this explanation it is hopefully clear that all of `[Network].IPv6PrefixDelegation=`, `[DHCPv6PrefixDelegation]`, `[IPv6PrefixDelegation]`, `[IPv6Prefix]` and `[IPv6RoutePrefix]` have either the wrong name, messed up or duplicated functionality. The names of `[Network].IPv6AcceptRA=` and `[IPv6AcceptRA]` might also be slightly misleading, but are ok in their concept at least. So for organizing all the dynamic address protocols and for cleaning up the sections I propose the following schema:
```
[DHCPv4]
DHCPv4 client, keep as is
[DHCPv6]
DHCPv6 client + prefix delegation client, keep as is
[IPv6AcceptRA]
Router Advertisement client, keep as is

[DHCPServer]
DHCPv4 server for clients, keep as is
[DHCPv6Server]
DHCPv6 server for clients (**stateful/stateless client configuration**), not (yet) supported, TBD

[DHCPv6ServerPrefixDelegation]
DHCPv6 server extension for prefix delegation (**router configuration**), not (yet) supported, TBD

[IPv6RouterAdvertisement]
Router Advertisement for **router**, currently in [IPv6PrefixDelegation]
[IPv6RouterAdvertisementPrefix]
Router Advertisement for **prefixes**, currently in [IPv6Prefix]
[IPv6RouterAdvertisementRoute]
Router Advertisement for **routes**, currently in [IPv6RoutePrefix]
```

For `[DHCPv6ServerPrefixDelegation]` I would have preferred `[DHCPv6PrefixDelegation]`, but that would conflict with the current section that has this name, but not the corresponding config.

Now let's do the actual problematic `[DHCPv6PrefixDelegation]`: the proposed way to merge static and dynamic management of prefixes in the same section is the best solution, because they share the same config options except the source of the prefix (e.g. `[IPv6Prefix]` has `Assign=`, but not `Token=`). I would extend the example only with `PrefixDelegationSubnetId=` to support all the old config options (the same syntax could also be used in a future DHCPv6 server):
```
Prefix=delegated
PrefixDelegationInterface=ppp0
PrefixDelegationSubnetId=0x42
```
For compatibility it should be doable to map `[DHCPv6PrefixDelegation].{SubnetId=,Assign=,Token=}` to `[IPv6RouterAdvertisementPrefix].{PrefixDelegationSubnetId=,Assign=,Token=}` and have `Prefix=delegated` automatically set and `PrefixDelegationInterface=` optional with the current logic of determining the upstream interface automatically .

From my point `[Network].IPv6PrefixDelegation=` is redundant and can be removed, as it is clear that Router Advertisements should be used if the section is used, and if it is not used, there is nothing to advertise.

To the original use-case from #17353: there could be a setting `[IPv6RouterAdvertisement].Announce=false` for this special case though I have doubts about this. The described use case of an external Router Advertisement daemon picking up the prefix from the interface has several problems: the advertisement contains more information than just the prefix (lifetime), which is lost during this process. You don't know how long the prefix is valid and if it changes, you either have to swap it immediately (which violates the standards) or build some custom scripts to keep it for some time in a deprecated state (you also have to announce it that way). This is why I hope for networkd to gain all the desired functionality, so every dynamic state is handled internally without scripts and according to the standards (lifetime, prefix deprecation, route handling, etc.).

@klada Multi-WAN is something that should be easily doable with support for all protocols in place. There is even a nice proposal in #14659 for making some aspects of this automated.

**Comment by yuwata** [comment]
@klada, @bartelsielski and @flo-wer At first, I'd like to thank again for many comments and suggestions! I may not respond or take into account all of your suggestions in this PR, but I really want to clean-up the current messy situation in the RA support of networkd in this PR and/or other later PRs.

@klada
> `IPv6SendRA=true` still only refers to sending RAs of delegated prefixes, right? IMHO semantically this is still a bit unfortunate. Imagine a config which has `IPv6SendRA=false` and at least one  `[IPv6Prefix]` section. Will those static prefixes be anounced or not? What if I do not want to announce the delegated prefix, but all other static prefixes from `[IPv6Prefix]` sections (or vice versa)?

When `IPv6SendRA=` is enabled, then all static prefixes are announced, and by default delegated prefixes are also announced, but the announcement of the delegated prefixes can be disabled by setting `Announce=` in `[DHCPv6PrefixDelegation]`.

> I really like the fact that you have made the upstream interface configurable.

Yeah, I agree with that.

**Comment by yuwata** [comment]
Force-pushed a new version.
- The setting to specify an upstream interface is not implemented yet, I'd like to do that in another PR.
- `[DHCPv6PrefixDelegation]` is not merged to `[IPv6Prefix]`, and the section is kept as is. `[DHCPv6PrefixDelegation]` section is for DHCPv6-PD, and `[IPv6Prefix]` is for RA. The targeted protocols are different. Moreover, though it may be technical, but `[IPv6Prefix]` can be specified more than once, and each section specifies different prefix. Merging the two sections introduces unwanted code complexity.

PTAL. Any further suggestions, comments, and discussions are welcome. Thank you!

**Comment by poettering** [comment]
codewise lgtm, but I must admit that I don#t fully grok the implications of all of this, I trust @yuwata though on this. if the others agree too, looks goot to commit to me

**Comment by klada** [comment]
@yuwata 
> > What if I do not want to announce the delegated prefix, but all other static prefixes from `[IPv6Prefix]` sections (or vice versa)?
> 
> What is the use case for this? `[IPv6Prefix]` section without announcing it sounds almost meaningless for me...

You are right, I cannot think of a real-world usecase for this. If I don't want to announce a static prefix, then I just don't need to configure it. :smile: 

It would just help when you want to unify static and delegated prefix configuration in one universal `[IPv6Prefix]` section. If you don't want to go that way, then it's not needed. I am fine with either approach.

**Comment by yuwata** [comment]
OK. Let's merge this.

@klada, @bartelsielski and @flo-wer, if you have any further suggestions, please feel free to open a new issue page.

**Pull request merged**
