### PR TITLE
network: update address when static address was already configured by DHCP

### LINKED ISSUE #11458: Changing from DHCP to static address with systemd-networkd doesn't work until after reboot
**systemd version the issue has been seen with**
> systemd-networkd 240

**Used distribution**
 > archlinux 2019.01.01

**Expected behaviour you didn't see**
 > Changing an interface from DHCP to static addressing doesn't make the address static until after a reboot.

**Unexpected behaviour you saw**
 > Interface lost address after the DHCP timeout, even after DHCP was disabled

Configure an interface to use DHCP using systemd-networkd. Then statically configure the interface to use that address, and restart systemd-networkd. After this observe that the valid_lft and preferred_lft of the address on the interface is finite, and once these lifetimes expire, the address is lost.

There are 2 workarounds I've found: either reboot the node, or manually set the valid_lft and preferred_lft to forever after bouncing systemd-networkd. IMO, systemd-networkd should be modifying the lifetimes itself.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #11458.

~~(I will try to add a test case later.)~~ done.

### CODE REVIEW

**Comment by ssahani** [comment]
This does not look right. We have ```CriticalConnection=``` for this. By allowing a DHCP IP to be configured as static breaks the whole idea of DHCP itself. This will make a ruckus in the network.  After lifetime expired the client should renew the address. The address could be something else .What if this  static address is assigned to some other host ?

**Comment by yuwata** [comment]
I imagine the following usecase(?)
- want to stop DHCP server for a while for some reason, e.g. maintenance
- but want clients to keep addresses.
- so, write current address to .network file.

Of course, this is a so bad way, and provides many problems. But, that is user's fault.

When we besides reusing addresses provided by DHCP, we can statically asign addresses in the range DHCP server use, and there are no way(is it true? at least I do not know) clients to know what range is used by DHCP server.
So, I think it is not so bad for networkd side to set static addresses currently assigned by DHCP.

**Comment by yuwata** [comment]
But, the time when we restart networkd, DHCP server may not exist any more in the network. Of course, that is a very bad situation. But even so, why we need to refuse that?

**Comment by ssahani** [comment]
>But, the time when we restart networkd, DHCP server may not exist any more in the network. 

It's a Plain network issue. The Admin need to fix the server.

>Of course, that is a very bad situation. But even so, why we need to refuse that?

If we configure any static ip will not that work with ?

**Comment by bswartz** [comment]
@yuwata I can confirm this PR fixes my problem.

@ssahani In my case I'm just using DHCP as a bootstrap mechanism to give cloned VMs an identity until I configure them permanently. It's my responsibility to make sure the static IPs don't conflict with the DHCP IPs. This is a relatively common practice in engineering lab settings.

**Comment by ssahani** [comment]
This idea is fundamentally wrong. I don't think networkd should come around this .

**Comment by bswartz** [comment]
At issue is whether systemd-should respect the wishes of the user or the wishes of the DHCP admin. It's insane to think that I could configure a static IP and systemd would decide I don't get one because it happens to know that a DHCP server exists which serves the same address.

Note that after a reboot or an address flush, systemd does what I want.

**Comment by ssahani** [comment]
>At issue is whether systemd-should respect the wishes of the user or the wishes of the DHCP admin. It's insane to think that I could configure a static IP and systemd would decide I don't get one because it happens to know that a DHCP server exists which serves the same address.

This  idea is broken and defeats the purpose of DHCP altogether.

>Note that after a reboot or an address flush, systemd does what I want.

Why not add another IP ? This works because you are able to add this as static address first and the DHCP takes a few seconds. And you getting lucky that DHCP offering you the same IP and not some other IP.

**Comment by yuwata** [comment]
I completely agree @ssahani's comments, except for the final direction `networkd` takes: permit or reject such a dangerous, at least unusual I must say, configurations.

> This idea is broken and defeats the purpose of DHCP altogether

Yes. I agree.

> `CriticalConnection=` .

Yes. I also recommend that option for such usecases.

But, even if it is dangerous and easily breaks not only the connectivity of the system but whole network which belongs to, I think we should permit that. If it causes some trouble, that is none of our responsibility, simply user's fault.

For example, people may mistakenly configure a static address in DHCP pool. Then, `networkd` does not (cannot?) check whether the requested address is in the pool or not, and simply assigns it.
Of course, this example is different from the original issue. But, I think the direction we should take is the same.

@poettering and @keszybz, what do you think?

**Comment by bswartz** [comment]
> Why not add another IP ? This works because you are able to add this as static address first and the DHCP takes a few seconds. And you getting lucky that DHCP offering you the same IP and not some other IP.

@ssahani I think you misunderstand my use case. I'm running the DHCP server myself expressly so I can bootstrap cloned VMs. I've set up static MAC address to IP mappings so I can control what IP the VM is given using the MAC address set in the VM spec. These's no chance of collisions in my configuration because DHCP is serving statically mapped addresses.

**Comment by ssahani** [comment]
> > Why not add another IP ? This works because you are able to add this as static address first and the DHCP takes a few seconds. And you getting lucky that DHCP offering you the same IP and not some other IP.
> 
> @ssahani I think you misunderstand my use case. I'm running the DHCP server myself expressly so I can bootstrap cloned VMs. I've set up static MAC address to IP mappings so I can control what IP the VM is given using the MAC address set in the VM spec. These's no chance of collisions in my configuration because DHCP is serving statically mapped addresses.

@bswartz Does not makes sense to me . Can you guarantee of other's conf ? We can do mistakes unknowingly . Why do we do purposefully. 

You have not answered my basic question . Did you tried to investigate why your DHCP server is not renewing addresses ? And why can''t issue solved with the suggestion I gave you critical connection ?

**Comment by yuwata** [comment]
@bswartz I have an almost similar setup of clustering machines. Then, I use `CriticalConnection=true` and `DHCP=ipv4`. Everything works fine for me... I cannot understand why you assign provided addresses statically.

**Comment by poettering** [comment]
hmm, i am not sure I grok this fully. The patch leaks roughly OK, but I'd normally assume that creating a new IP address would always be better than updating an existing one when we switch from dhcp to static or back, simply because new attributes for addresses might be added late ron, and we better rest them all when we don't know them.

Hence, where's the precise difference of the status quo ante and status quo afterwards?

**Comment by ssahani** [comment]
> hmm, i am not sure I grok this fully. The patch leaks roughly OK, but I'd normally assume that creating a new IP address would always be better than updating an existing one when we switch from dhcp to static or back, simply because new attributes for addresses might be added late ron, and we better rest them all when we don't know them.
> 
> Hence, where's the precise difference of the status quo ante and status quo afterwards?

Well the use case is not right. User is relying on the DHCP to provide a address and then user assumes that's it's permanent addresses which totally breaks the DHCP behaviour. So I really do not figure why use DHCP at all. why not manually inventory. 

After the life time gets expired the DHCP server can assign this address to someone else that could lead to a conflict in the network.

**Pull request merged**
