### PR TITLE
networkd: add support to configure IPv6 DAD

### PR DESCRIPTION
**Pull request by ssahani**

### CODE REVIEW

**Comment by teg** [comment]
Hm, do we really want to make this configurable? What is the usecase?

**Comment by bjoe2k4** [comment]
Maybe to workaround issue #650, but the same can be done also easily via sysctl settings.

**Comment by teg** [comment]
@bjoe2k4 no, this we need to just fix properly (I have a fix in the works).

**Comment by ssahani** [comment]
@teg Addressing the issue  #969

**Comment by teg** [comment]
@ssahani ok, but we need a proper argument for each of these features. This does not look like something that should be tweakable imho, but I might be wrong...

**Comment by ssahani** [comment]
I am sorry but dint not understand "proper argument"  :)

**Comment by poettering** [comment]
@teg?

**Comment by teg** [comment]
I looked into this. This configuration option is mandated by RFC 4861 section 5.1. Moreover, I see this as being useful in order to switch DAD off completely on trusted links (e.g. containers on the same host), or potentially to increase the retries on a known unreliable link (though that seems very hacky indeed).

No objections from me then. Merging.

**Pull request merged**
