### PR TITLE
basic/user-util: De-duplicate code

### PR DESCRIPTION
**Pull request by alejandro-colomar**

### CODE REVIEW

**Comment by yuwata** [comment]
This is a kind of duplicate of #35226. Closing.

**Comment by alejandro-colomar** [comment]
I think that PR is bad.  I plan to do some other commits after this one, refactoring the function step-by-step, to make the changes easy to audit.

Please reopen.

**Comment by alejandro-colomar** [comment]
@yuwata 

I think that PR is bad.  I plan to do some other commits after this one, refactoring the function step-by-step, to make the changes easy to audit.

Please reopen.

FTR, I've been working in a similar refactor in code surrounding getgroups(3) in shadow utils:
<https://github.com/shadow-maint/shadow/pull/1123>

**Comment by yuwata** [comment]
I cannot find any effective difference between the two PRs. In what sense #35226 is bad, and this is better?

**Comment by alejandro-colomar** [comment]
The commit message in that PR doesn't explain anything, other than saying it's modernising.  What's modern?

The diff does a lot of things, and results in being unreadable.  Instead, my patch is quite clear on what it does.


I have instead a set of 4 commits, which clearly state what they do, and limit themselves to one clearly delimited change per commit.

```diff
$ git log -p main..agetgroups 
commit f2ba30e3e05b59679d42146b6a282aab78d349e2 (HEAD -> agetgroups)
Author: Alejandro Colomar <alx@kernel.org>
Date:   Thu Nov 21 01:30:15 2024 +0100

    basic/user-util: Fix bug
    
    If getgroups(2) reports zero groups, our wrapper getgroups_allow() had
    erratic behavior:
    
    -  If we succeed in the first iteration.
    
            If we succeed in the first iteration, we correctly allocate a
            buffer, leave it unused (since getgroups(2) fills zero entries),
            set *gids to the allocated memory, and return 0.
    
    -  If we need to iterate.
    
            If we fail in the first iteration, we do NOT set *gids, and
            return 'false'.  This is bogus in so many ways.
    
            First of all, 'false' is a boolean and makes absolutely no sense
            here where we're returning a number of elements or an error
            code.
    
            Secondly, and most importantly, we're not setting *gid, so if
            the caller tried to free(3) it, we'll have a big problem.
    
    See an excerpt of the code responsible for the bug:
    
             int getgroups_alloc(gid_t** gids) {
                    ...
                     int ngroups = 8;
                    ...
    
                     for (;;) {
                            ...
                             ngroups = getgroups(ngroups, p);
                             if (ngroups >= 0)
                                     break;
                            ...
                             ngroups = getgroups(0, NULL);
                            ...
            -                if (ngroups == 0)
            -                        return false;
                     }
    
                     *gids = TAKE_PTR(p);
                     return ngroups;
             }
    
    By removing the special case, we handle zero just like any other
    non-negative value, which is just fine.
    
    Signed-off-by: Alejandro Colomar <alx@kernel.org>

diff --git a/src/basic/user-util.c b/src/basic/user-util.c
index 974c4fa604..71a202fa29 100644
--- a/src/basic/user-util.c
+++ b/src/basic/user-util.c
@@ -554,8 +554,6 @@ int getgroups_alloc(gid_t** gids) {
                 ngroups = getgroups(0, NULL);
                 if (ngroups < 0)
                         return -errno;
-                if (ngroups == 0)
-                        return false;
         }
 
         *gids = TAKE_PTR(p);

commit ac1171af7b4956cb4514877b83f5090f0e048595
Author: Alejandro Colomar <alx@kernel.org>
Date:   Thu Nov 21 01:26:52 2024 +0100

    basic/user-util: Remove redundant variable
    
    Signed-off-by: Alejandro Colomar <alx@kernel.org>

diff --git a/src/basic/user-util.c b/src/basic/user-util.c
index 308503a8b1..974c4fa604 100644
--- a/src/basic/user-util.c
+++ b/src/basic/user-util.c
@@ -527,21 +527,20 @@ int merge_gid_lists(const gid_t *list1, size_t size1, const gid_t *list2, size_t
 }
 
 int getgroups_alloc(gid_t** gids) {
-        gid_t *allocated;
         _cleanup_free_  gid_t *p = NULL;
         int ngroups = 8;
         unsigned attempt = 0;
 
         for (;;) {
-                p = allocated = new(gid_t, ngroups);
-                if (!allocated)
+                p = new(gid_t, ngroups);
+                if (!p)
                         return -ENOMEM;
 
                 ngroups = getgroups(ngroups, p);
                 if (ngroups >= 0)
                         break;
 
-                free(allocated);
+                free(p);
 
                 if (errno != EINVAL)
                         return -errno;

commit 1e8a8e8aa10fb3c6d1b9a5c7603b3a684c9f8335
Author: Alejandro Colomar <alx@kernel.org>
Date:   Thu Nov 21 01:13:58 2024 +0100

    basic/user-util: Fix memory leak
    
    Signed-off-by: Alejandro Colomar <alx@kernel.org>

diff --git a/src/basic/user-util.c b/src/basic/user-util.c
index 3450276894..308503a8b1 100644
--- a/src/basic/user-util.c
+++ b/src/basic/user-util.c
@@ -540,6 +540,9 @@ int getgroups_alloc(gid_t** gids) {
                 ngroups = getgroups(ngroups, p);
                 if (ngroups >= 0)
                         break;
+
+                free(allocated);
+
                 if (errno != EINVAL)
                         return -errno;
 
@@ -554,8 +557,6 @@ int getgroups_alloc(gid_t** gids) {
                         return -errno;
                 if (ngroups == 0)
                         return false;
-
-                free(allocated);
         }
 
         *gids = TAKE_PTR(p);

commit bc68dcdcb71fbd0f6f4ea9af51c06bb7bd276169 (gh/agetgroups)
Author: Alejandro Colomar <alx@kernel.org>
Date:   Thu Nov 21 00:54:20 2024 +0100

    basic/user-util: De-duplicate code
    
    Signed-off-by: Alejandro Colomar <alx@kernel.org>

diff --git a/src/basic/user-util.c b/src/basic/user-util.c
index 2b7c923b5e..3450276894 100644
--- a/src/basic/user-util.c
+++ b/src/basic/user-util.c
@@ -532,12 +532,11 @@ int getgroups_alloc(gid_t** gids) {
         int ngroups = 8;
         unsigned attempt = 0;
 
-        allocated = new(gid_t, ngroups);
-        if (!allocated)
-                return -ENOMEM;
-        p = allocated;
-
         for (;;) {
+                p = allocated = new(gid_t, ngroups);
+                if (!allocated)
+                        return -ENOMEM;
+
                 ngroups = getgroups(ngroups, p);
                 if (ngroups >= 0)
                         break;
@@ -557,10 +556,6 @@ int getgroups_alloc(gid_t** gids) {
                         return false;
 
                 free(allocated);
-
-                p = allocated = new(gid_t, ngroups);
-                if (!allocated)
-                        return -ENOMEM;
         }
 
         *gids = TAKE_PTR(p);
```

If you reopen the PR, I'll push all the 4 patches.

**Comment by YHNdnzj** [comment]
> The commit message in that PR doesn't explain anything, other than saying it's modernising.  What's modern?

Reduce var scope, utilize scope bound resource management more effectively and such. Generally bring it closer to the latest coding style. We have a bunch of commits doing such stuff.

> The diff does a lot of things, and results in being unreadable.  Instead, my patch is quite clear on what it does.

It doesn't seem necessary to me to split this into multiple parts frankly. The function is short enough.

> I have instead a set of 4 commits, which clearly state what they do, and limit themselves to one clearly delimited change per commit.
> 
> ```diff
> $ git log -p main..agetgroups 
> commit f2ba30e3e05b59679d42146b6a282aab78d349e2 (HEAD -> agetgroups)
> Author: Alejandro Colomar <alx@kernel.org>
> Date:   Thu Nov 21 01:30:15 2024 +0100
> 
>     basic/user-util: Fix bug
>     
>     If getgroups(2) reports zero groups, our wrapper getgroups_allow() had
>     erratic behavior:
>     
>     -  If we succeed in the first iteration.
>     
>             If we succeed in the first iteration, we correctly allocate a
>             buffer, leave it unused (since getgroups(2) fills zero entries),
>             set *gids to the allocated memory, and return 0.
>     
>     -  If we need to iterate.
>     
>             If we fail in the first iteration, we do NOT set *gids, and
>             return 'false'.  This is bogus in so many ways.
>     
>             First of all, 'false' is a boolean and makes absolutely no sense
>             here where we're returning a number of elements or an error
>             code.
>     
>             Secondly, and most importantly, we're not setting *gid, so if
>             the caller tried to free(3) it, we'll have a big problem.
>     
>     See an excerpt of the code responsible for the bug:
>     
>              int getgroups_alloc(gid_t** gids) {
>                     ...
>                      int ngroups = 8;
>                     ...
>     
>                      for (;;) {
>                             ...
>                              ngroups = getgroups(ngroups, p);
>                              if (ngroups >= 0)
>                                      break;
>                             ...
>                              ngroups = getgroups(0, NULL);
>                             ...
>             -                if (ngroups == 0)
>             -                        return false;
>                      }
>     
>                      *gids = TAKE_PTR(p);
>                      return ngroups;
>              }
>     
>     By removing the special case, we handle zero just like any other
>     non-negative value, which is just fine.
>     
>     Signed-off-by: Alejandro Colomar <alx@kernel.org>
> 
> diff --git a/src/basic/user-util.c b/src/basic/user-util.c
> index 974c4fa604..71a202fa29 100644
> --- a/src/basic/user-util.c
> +++ b/src/basic/user-util.c
> @@ -554,8 +554,6 @@ int getgroups_alloc(gid_t** gids) {
>                  ngroups = getgroups(0, NULL);
>                  if (ngroups < 0)
>                          return -errno;
> -                if (ngroups == 0)
> -                        return false;
>          }
>  
>          *gids = TAKE_PTR(p);
> 
> commit ac1171af7b4956cb4514877b83f5090f0e048595
> Author: Alejandro Colomar <alx@kernel.org>
> Date:   Thu Nov 21 01:26:52 2024 +0100
> 
>     basic/user-util: Remove redundant variable
>     
>     Signed-off-by: Alejandro Colomar <alx@kernel.org>
> 
> diff --git a/src/basic/user-util.c b/src/basic/user-util.c
> index 308503a8b1..974c4fa604 100644
> --- a/src/basic/user-util.c
> +++ b/src/basic/user-util.c
> @@ -527,21 +527,20 @@ int merge_gid_lists(const gid_t *list1, size_t size1, const gid_t *list2, size_t
>  }
>  
>  int getgroups_alloc(gid_t** gids) {
> -        gid_t *allocated;
>          _cleanup_free_  gid_t *p = NULL;
>          int ngroups = 8;
>          unsigned attempt = 0;
>  
>          for (;;) {
> -                p = allocated = new(gid_t, ngroups);
> -                if (!allocated)
> +                p = new(gid_t, ngroups);
> +                if (!p)
>                          return -ENOMEM;
>  
>                  ngroups = getgroups(ngroups, p);
>                  if (ngroups >= 0)
>                          break;
>  
> -                free(allocated);
> +                free(p);
>  

Now, if we return in the error check below, `p` gets double free'd here.

>                  if (errno != EINVAL)
>                          return -errno;
> 
> commit 1e8a8e8aa10fb3c6d1b9a5c7603b3a684c9f8335
> Author: Alejandro Colomar <alx@kernel.org>
> Date:   Thu Nov 21 01:13:58 2024 +0100
> 
>     basic/user-util: Fix memory leak
>     
>     Signed-off-by: Alejandro Colomar <alx@kernel.org>
> 
> diff --git a/src/basic/user-util.c b/src/basic/user-util.c
> index 3450276894..308503a8b1 100644
> --- a/src/basic/user-util.c
> +++ b/src/basic/user-util.c
> @@ -540,6 +540,9 @@ int getgroups_alloc(gid_t** gids) {
>                  ngroups = getgroups(ngroups, p);
>                  if (ngroups >= 0)
>                          break;
> +
> +                free(allocated);
> +
>                  if (errno != EINVAL)
>                          return -errno;
>  
> @@ -554,8 +557,6 @@ int getgroups_alloc(gid_t** gids) {
>                          return -errno;
>                  if (ngroups == 0)
>                          return false;
> -
> -                free(allocated);
>          }
>  
>          *gids = TAKE_PTR(p);
> 
> commit bc68dcdcb71fbd0f6f4ea9af51c06bb7bd276169 (gh/agetgroups)
> Author: Alejandro Colomar <alx@kernel.org>
> Date:   Thu Nov 21 00:54:20 2024 +0100
> 
>     basic/user-util: De-duplicate code
>     
>     Signed-off-by: Alejandro Colomar <alx@kernel.org>
> 
> diff --git a/src/basic/user-util.c b/src/basic/user-util.c
> index 2b7c923b5e..3450276894 100644
> --- a/src/basic/user-util.c
> +++ b/src/basic/user-util.c
> @@ -532,12 +532,11 @@ int getgroups_alloc(gid_t** gids) {
>          int ngroups = 8;
>          unsigned attempt = 0;
>  
> -        allocated = new(gid_t, ngroups);
> -        if (!allocated)
> -                return -ENOMEM;
> -        p = allocated;
> -
>          for (;;) {
> +                p = allocated = new(gid_t, ngroups);
> +                if (!allocated)
> +                        return -ENOMEM;
> +
>                  ngroups = getgroups(ngroups, p);
>                  if (ngroups >= 0)
>                          break;
> @@ -557,10 +556,6 @@ int getgroups_alloc(gid_t** gids) {
>                          return false;
>  
>                  free(allocated);
> -
> -                p = allocated = new(gid_t, ngroups);
> -                if (!allocated)
> -                        return -ENOMEM;
>          }
>  
>          *gids = TAKE_PTR(p);
> ```
> 
> If you reopen the PR, I'll push all the 4 patches.
> 
> Initially, I only pushed one of the commits, to test the waters.

**Comment by YHNdnzj** [comment]
So based on what I commented above I'm not particularly convinced...

**Pull request closed without merging**
