### PR TITLE
ci: run build test with clang-12 as well

### PR DESCRIPTION
**Pull request by mrc0mmand**
Ubuntu repositories for clang 12 are finally up, so let's use it
in our CI.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
The build currently fails with:
```
../src/shared/dissect-image.c:2218:39: error: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Werror,-Wstring-concatenation]
                                      "/usr/lib/os-release\0",
                                      ^
../src/shared/dissect-image.c:2217:39: note: place parentheses around the string literal to silence warning
                [META_OS_RELEASE]   = "/etc/os-release\0"
                                      ^
1 error generated.
```

which looks like a false positive. Let's wait a bit until the rough edges of clang-12 are sorted out.

**Comment by mrc0mmand** [comment]
> The build currently fails with:
> 
> ```
> ../src/shared/dissect-image.c:2218:39: error: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Werror,-Wstring-concatenation]
>                                       "/usr/lib/os-release\0",
>                                       ^
> ../src/shared/dissect-image.c:2217:39: note: place parentheses around the string literal to silence warning
>                 [META_OS_RELEASE]   = "/etc/os-release\0"
>                                       ^
> 1 error generated.
> ```
> 
> which looks like a false positive. Let's wait a bit until the rough edges of clang-12 are smoothed out.

**Comment by mrc0mmand** [comment]
Given the patch discussion in https://reviews.llvm.org/D85545 and follow-up on Telegram the warning seems to be legit. The second commit adds the suggested parentheses around the two occurrences of the warning, with it the build seems to finally pass with clang-12 as well.

**Review by bluca — APPROVED** [review]
LGTM

**Comment by bluca** [comment]
@mrc0mmand is this good to merge now?

**Comment by mrc0mmand** [comment]
> @mrc0mmand is this good to merge now?

It should be ready to go!

**Pull request merged**
