### PR TITLE
document precedence of dropin files

### PR DESCRIPTION
**Pull request by snakeroot**
Documents precedence of dropin files per @poettering comment in Issue #2103

### CODE REVIEW

**Comment by poettering** [comment]
The second patch looks like an artifact of a borked git merge? Please rebase the patch and drop that part. Thanks!

**Comment by snakeroot** [comment]
Revised per @poettering above

**Comment by poettering** [comment]
Nope, the git commit is really borked. Please use "git fetch && git rebase -i origin/master" to rebase your patch on top of current git, and drop all patches that aren't yours.

**Comment by poettering** [comment]
still not right. You added two more commits. Please rebase and reduce this to one commit with the actual changes you want to make.

**Comment by poettering** [comment]
Also, please note that github unfortunately doesn't inform us about updated branches, hence please always also write a comment here, if you added a new commit, so that we notice this. Thanks

**Comment by zonque** [comment]
@snakeroot You seem to be stuck in your git workflow. I know how it feels, we've all been there once :)

My advise for you would be to go back to your master branch (`git checkout master`), bring it up to date with the upstream repository (`git pull origin`), create a new branch from there (`git checkout -b dropin-doc-2` or somthing like that) and cherry-pick the latest version of your commit (`git cherry-pick 7d53a83`). This will make this new branch to only contain one commit on top of the current master. Then make local changes, amend the commit with `git add -u; git commit --amend` and when ready, push it again and open a new PR.

I'm closing this one for now for more clarity. Thanks!

**Pull request closed without merging**
