### PR TITLE
core/service: a few improvements for main pid handling

### PR DESCRIPTION
**Pull request by YHNdnzj**
~~cc @DaanDeMeyer: I thought I only need to fixup main pid handling, but it turned out that the whole approach has to be reverted. Sorry, but I think being correct is more important than forward compat.~~

### CODE REVIEW

**Comment by yuwata** [comment]
Setting kind of `important` flags here, to make not break such fundamental features. Though, I have not followed the commits and @YHNdnzj's claim about the previous PR.

**Comment by DaanDeMeyer** [comment]
In that case we'll need a toggle to disable use of pidfd at build time. I cannot release the new version without being able to downgrade to the previous version.

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by bluca** [comment]
> After reconsidering this, I don't think this is the right approach.
Our pidref requires the pid field to be valid. I.e. after deserialization,
the process must be alive if we want to reattach pidref to service,
otherwise pidref_set_pid(fd) would return error, because new pidfd
can't be opened/pidfd returns -1 for pid.
>
> Before the patch, we always get pidfd, so if the previous
process has died, pidref would never be set and the unit
deactivates normally. After the patch, if the process we're
supposed to monitor has exited and the pid got reused,
after deserialization we spuriously start monitoring
the new process with same pid, rendering pidfd useless.

I'm not convinced by this. This is supposed to be best effort - this is no different than running a pre-pidref version, where we just passed around pids. If the process had exited and was recycled in the time during the reexec, the same would have happened. So this doesn't introduce any new issue when downgrading.

**Comment by DaanDeMeyer** [comment]
> > After reconsidering this, I don't think this is the right approach.
> > Our pidref requires the pid field to be valid. I.e. after deserialization,
> > the process must be alive if we want to reattach pidref to service,
> > otherwise pidref_set_pid(fd) would return error, because new pidfd
> > can't be opened/pidfd returns -1 for pid.
> > Before the patch, we always get pidfd, so if the previous
> > process has died, pidref would never be set and the unit
> > deactivates normally. After the patch, if the process we're
> > supposed to monitor has exited and the pid got reused,
> > after deserialization we spuriously start monitoring
> > the new process with same pid, rendering pidfd useless.
> 
> I'm not convinced by this. This is supposed to be best effort - this is no different than running a pre-pidref version, where we just passed around pids. If the process had exited and was recycled in the time during the reexec, the same would have happened. So this doesn't introduce any new issue when downgrading.

Yes but this is about upgrading, switch-root or anything else where we serialize where the same issue applies. So this regresses in those cases which means we should revert.

**Comment by YHNdnzj** [comment]
Yeah, this is a generic issue that gets triggered every time we deserialize state...

**Comment by bluca** [comment]
Right, but for upgrades we can detect when that situation happens and work around it, no?

**Comment by DaanDeMeyer** [comment]
I guess if we keep track of whether we've already seen a pidfd when deserializing and refuse to use the pid if that's the case, that could work. @YHNdnzj That should fix the issue no?

**Comment by DaanDeMeyer** [comment]
To be clear I am fine with https://github.com/systemd/systemd/pull/32116 as well. I just need something that allows me to upgrade from without pidfd to with pidfd, and then it doesn't matter anymore.

**Comment by bluca** [comment]
> I guess if we keep track of whether we've already seen a pidfd when deserializing and refuse to use the pid if that's the case, that could work. @YHNdnzj That should fix the issue no?
> 
> Except for scopes doing that tracking is rather annoying. I guess you could use a variable to keep track of whether a single pidfd was ever gotten and ignore all regular pids if that's the case.

Yeah exactly, requires a bit of effort, but seems worth it. I cannot ship packages in Debian that would break the system so spectacularly on downgrades. It's fine to be best-effort and lose features and whatnot, but active service tracking is really essential.

**Comment by YHNdnzj** [comment]
I really don't want to do that in this PR. The fact is that the commit introduced a regression, and that's enough reason to revert it. 

> I cannot ship packages in Debian that would break the system so spectacularly on downgrades

v255 is already shipped? Plus, I don't think I have seen a single report on upstream bug tracker about this. Do you have a real bug report on Debian's side, that people actually do this?

**Comment by YHNdnzj** [comment]
Also, honestly I think giving people a way to diable pidfd wholly is probably good. But maybe the option should be a runtime one.

**Comment by bluca** [comment]
> I really don't want to do that in this PR. The fact is that the commit, which focuses only on forward compat, introduced a regression, and that's enough reason to revert it.

That's fair and yes the regression should be patched immediately

Daan are you ok with working on this separately? I'd really prefer not to have another meson option, as we should really just enable pidref everywhere

> > I cannot ship packages in Debian that would break the system so spectacularly on downgrades
> 
> v255 is already shipped? Plus, I don't think I have seen a single report on upstream bug tracker about this. Do you have a real bug report on Debian's side, that people actually do this?

Not in a stable release, and it's not in backports either (yet). Especially the stable <-> backports story worries me, as it's not that uncommon to try things from backports and then go back. Stable has 252 and backports 254.

**Comment by DaanDeMeyer** [comment]
I'm preparing a patch

**Comment by YHNdnzj** [comment]
I'll rebase this once #32118 lands.

**Comment by YHNdnzj** [comment]
Given that #32118 would need bigger rework, I've rebased and dropped the first revert commit. Setting the green label, as already reviewed by @DaanDeMeyer.

**Review by bluca — APPROVED** [review]

**Pull request merged**
