### PR TITLE
Various unrelated small patches

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
lgtm

**Comment by poettering** [comment]
hmm, any chance you can rebase this PR on current git and force push? The CI was broken with git until just now, and this was fixed a few moments ago with another commit. To make sure we don't break it right-away again, it would be great if you could rebase this PR and force push so that the CI runs over this again?

**Comment by keszybz** [comment]
PRs are rebased on top of master anyway in the autopkgtests, so it's enough to kick the two failed tests for rebuild.

**Comment by poettering** [comment]
hmm, it appears the CI failed for some reason that is not related to the PR. I figure we should restart the CI for this?

**Pull request merged**
