### PR TITLE
HACKING: update qemu-kvm instructions

### LINKED ISSUE #6131: Update HACKING - qemu-kvm isn't a separate binary anymore.
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> …

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Gentoo Linux

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> …

Update `qemu-kvm` to `qemu-system-x86_64 -enable-kvm` as it is not a separate binary anymore, in https://github.com/systemd/systemd/blob/master/HACKING, line number 33.

### PR DESCRIPTION
**Pull request by AsciiWolf**
Fixes #6131.

### CODE REVIEW

**Comment by keszybz** [comment]
Hm, who came up with this idea? "qemu-kvm" is already pretty long, and there's no way I'm going to remember an option name. Was this announced somewhere?

**Comment by bl33pbl0p** [comment]
Blog Post:
http://blog.vmsplice.net/2012/12/qemu-kvmgit-has-unforked-back-into.html
Related Mailing list thread:
https://lists.gnu.org/archive/html/qemu-devel/2013-10/msg01466.html

The `qemu-kvm` project has been gone for long.

Some distributions still provide a wrapper script, and some users have aliases, but it is not what most major distributions do anymore. I can speak for Arch and Gentoo at least. The `qemu-system-x86_64` binary otoh works everywhere, and KVM support can be enabled by passing `-enable-kvm`.

**Comment by tixxdz** [comment]
lgtm, thanks!

**Comment by poettering** [comment]
OK, if this is the new syntax, who am I to say no?

**Pull request merged**
