### PR TITLE
Update uk.po

### PR DESCRIPTION
**Pull request by MikhailKasimov**
"Аутентифікація" (uk) is more specific and recognizable word instead of "Засвідчення", which has more wide context.
"Одиниця" (uk) has also wide context, but in systemd-specific terms "unit files" can be translated as 1:1.

All changes should be re-checked by uk-translators.

### CODE REVIEW

**Comment by MikhailKasimov** [comment]
cc @dankor

**Comment by dankor** [comment]
Hey, @MikhailKasimov, thanks for the attention.

As for me, Neither "Аутентифікація" nor "Засвідчення" is really well-recognizable. "Аутентифікація" is rather a transliteration then a translation. That's why I preferred "Засвідчення".
Do you mean to keep "unit" as "unit" in translations? Well. What's the purpose of the systemd translation after all? :)

I'll update the whole uk file after your arguments.

**Comment by MikhailKasimov** [comment]
Hello, @dankor ! Thanks for clarifying!

My arguments:
1) "Аутентифікація" word explicitly means, that user must put some password of root-user to get privilege's increase to make his action(-s) complete. It is information security specific term (e.g. ```two-factors authentication```).
2) "Засвідчення" -- is more common-sensed word. "Засвідчення в коханні", for example.

That's why "Аутентифікація" is applicable here instead of "Засвідчення".

> Do you mean to keep "unit" as "unit" in translations?

No. Here transliteration is suitable: ```юніт```: e.g. ```юніт-файли```. That's like as in Counter-Strike game, when ```frag``` is transliterating like ```фраг```. :)

While systemd operates with unit-files and these unit-files are different (target, service. mount, etc), term ```одиниці``` also gives very common sense, not specific. And also keeping to be specific is preferable here.

> What's the purpose of the systemd translation after all? :)

To have perfect uk-translation and simultaneously to keep IT/IS and, in particular, systemd specific terms. :) Hope, you agree here on my arguments.

Thanks!

**Comment by dankor** [comment]
@MikhailKasimov:
> "Аутентифікація" word explicitly means, that user must put some password of root-user to get privilege's increase to make his action(-s) complete. It is information security specific term (e.g. two-factors authentication).

[Authentication — to establish the authenticity of; prove genuine](https://www.thefreedictionary.com/authentication). 
[Засвідчувати — повідомляючи про щось, підтверджувати правдивість, правильність чого-небудь](http://sum.in.ua/s/zasvidchuvaty). 
They are really close in the meanings in my opinion.
> "Засвідчення" -- is more common-sensed word. "Засвідчення в коханні", for example.

LOL. You are cofusing it with "[Освідчення](http://sum.in.ua/s/osvidchuvatysja)". :D 
> No. Here transliteration is suitable: юніт: e.g. юніт-файли. That's like as in Counter-Strike game, when frag is transliterating like фраг. :)

That's a bad argument. I'm not sure if the Counter-Strike game translator does it. Moreover, we shouldn't translate "bike", "bug", "feature", "soft", etc as "байк", "бага","фіча","софт", etc. I'm trying to stick to the official terminology as much as possible.
> While systemd operates with unit-files and these unit-files are different (target, service. mount, etc), term одиниці also gives very common sense, not specific. And also keeping to be specific is preferable here.

I agree that "Одиниця" could be not the best fit. Nonetheless, I'm strongly agaist "Юніт". It's not widely used and just a transliteration.

**Comment by MikhailKasimov** [comment]
@dankor 

> LOL. You are cofusing it with "Освідчення". :D

You're right. My bad here. :D

**Deal**:

>Authentication — to establish the authenticity of; prove genuine.
>Засвідчувати — повідомляючи про щось, підтверджувати правдивість, правильність чого-небудь.
>They are really close in the meanings in my opinion.

Sounds yes, but here is a nuance: user should define his system role (Authentication) to approve (Засвідчення) his actions. So, first step is Authentication anyway, which is provided by putting password. Approving (Засвідчення) is secondary here.

> That's a bad argument... I'm trying to stick to the official terminology as much as possible.

That's a good point and I agree here, but sometimes there are term, that really hard to translate without loosing their initial sense.

But ok, let's try out such variant: ``` "Потрібна аутентифікація, щоб керувати системними службами й юніт-файлами."``` --> ```"Потрібна аутентифікація, щоб керувати системними службами й одиницями systemd."``` One word longer, but saving initial sense. M?

**Comment by dankor** [comment]
@MikhailKasimov : 

> Sounds yes, but here is a nuance: user should define his system role (Authentication) to approve (Засвідчення) his actions. So, first step is Authentication anyway, which is provided by putting password. Approving (Засвідчення) is secondary here.

Where did you get these steps? I'm sorry, but it seems like you are looking for an artificial difference on purpose. Honestly, it doesn't convince me at all.

> But ok, let's try out such variant: "Потрібна аутентифікація, щоб керувати системними службами й юніт-файлами." --> "Потрібна аутентифікація, щоб керувати системними службами та одиницями systemd." One word longer, but saving initial sense. M?

Yeah, It sounds more reasonable. But I don't like "аутентифікація" here anyway. :)

**Comment by MikhailKasimov** [comment]
@dankor 

Even [Автентифікація](https://uk.wikipedia.org/wiki/%D0%90%D0%B2%D1%82%D0%B5%D0%BD%D1%82%D0%B8%D1%84%D1%96%D0%BA%D0%B0%D1%86%D1%96%D1%8F) : 

```
З позицій інформаційної безпеки Автентифікація є частиною процедури надання доступу для роботи в інформаційній системі, наступною після ідентифікації і передує авторизації
```
> ...but it seems like you are looking for an artificial difference on purpose.

Unfortunately, no.

[Law](http://zakon5.rada.gov.ua/laws/show/373-2006-%D0%BF):

```
автентифікація -     процедура     встановлення    належності 
користувачеві   інформації   в   системі   (далі   -   користувач) 
пред'явленого ним ідентифікатора;
```

In our case user must have an access to fulfill his actions in system. It's the same to case on putting ```su\sudo``` (user substitution to increase privileges for further successful work: to get UID=0 (root) instead UID=1000 (user)).

Sorry, but no way here -- ```Аутентифікація``` or even ```Автентифікація``` (more modern transliteration).

**Comment by dankor** [comment]
Okay. What about "[Розпізнавання](https://l10n.kde.org/dictionary/search-translations.php?package=&filename=&teamcode=uk&search=Authentication&submitted=Search)"? KDE l10n have to be the respectful source.

**Comment by MikhailKasimov** [comment]
@dankor 

I have no doubts on "KDE l10n have to be the respectful source", but let's also take an **attentive** look on here:
```
Authentication support

Original : | Developer (I/O library, Authentication support)
-- | --
Розробник (бібліотека В/В, підтримка автентифікації)
```

Also, please, take a look on this snippet (I even have made a screenshot on here):
kde_localization_-_search_a_string_in_translations_-_2018-05-11_22 20 30

I think, everything is clear here. But, to be full of sense, let's describe steps of general authentication process:

1. System asks user to put password for some further actions, which are doable for root only.
2. User puts password to complete 1.
3. System reads password from 2.
4. System calculates hash of password from 2.
5. System compares hash from 4 with hash, which is stored in some its internal system database.
6. If hash of password = hash, that stored, then 'Authentication successful. Access granted'.
7. If hash of password != hash, that stored, then 'Authentication failed. Access denied'.

Steps 5-6-7 are ```Розпізнавання```, yes. But entire process 1-7 is ```Автентифікація```.

So, ```Розпізнавання``` is **only part** of ```Автентифікація```.  And, to do some actions, which need root access, we need to fulfill ```Автентифікація``` as the **entire process**.

Hence, uk-translation of KDE l10n resource also should be fixed onto ```Authentication --> Автентифікація```.

Hope, this will help. Thanks!

**Comment by dankor** [comment]
Okay, I'm giving up to follow up this discussion. End-users should be skillful enough to understand what it means anyway.
[The following commit ](https://github.com/dankor/systemd/commit/8c2949642766aef95f909dc833ac9876eb03871e) is going to be acceptable for you?

**Comment by MikhailKasimov** [comment]
> End-users should be skillful enough to understand what it means anyway.

"Учиться... Учиться... Учиться" (с).

> The following commit is going to be acceptable for you?

msgstr "Потрібна автентифікація, щоб зарєструвати службу DNS-SD" --> зареєструвати

Other staff is OK.

Thank you for cooperation!

**Comment by dankor** [comment]
Thank you too.

**Comment by keszybz** [comment]
Superseded by #8973.

**Pull request closed without merging**
