### PR TITLE
Revert "rules: move input_id rule to a separate file"

### LINKED ISSUE #6219: lightdm crashes and cannot start graphical session
### Submission type

 - Bug report

### systemd version the issue has been seen with

f62c9e50b (#6099). Its parent f9ce1a4a41b293d4a8e17794265490c9bdb3ace9 works fine.

### Used distribution

fedora 26 x86_64

### In case of bug report: Expected behaviour you didn't see

lightdm works fine and user can login graphically.

### In case of bug report: Unexpected behaviour you saw

lightdm starts but no keyboard input is accepted, mouse cursor ~~is not shown~~ does not move. So, I cannot change console neither shutdown system by mouse.

### In case of bug report: Steps to reproduce the problem

Boot the system with lightdm.

### PR DESCRIPTION
**Pull request by yuwata**
This reverts commit 38887d1bd5eb037a532279b2b75d6a87ce381419.

Fixes #6219.

### CODE REVIEW

**Comment by yuwata** [comment]
I do not know why the commit 38887d1bd5eb037a532279b2b75d6a87ce381419 breaks lightdm (or any graphical session?). Neither I do not know what the commit intend to. But, anyway, this fixes #6219.

**Comment by keszybz** [comment]
No need for knee-jerk reactions ;) It seems that 38887d1 does not install the new file properly. I'll send out a PR for that shortly.

How do you install — meson or autotools?

**Comment by yuwata** [comment]
@keszybz I've created a custom RPM based on http://pkgs.fedoraproject.org/cgit/rpms/systemd.git/commit/?id=3fb4a15096f7a4a47124cfdd75771e41c1f11393 which uses meson.

**Comment by yuwata** [comment]
> It seems that 38887d1 does not install the new file properly. I'll send out a PR for that shortly.

Oh. I have not been aware that. I've concentrated to the udev rules changes.

**Pull request closed without merging**
