### PR TITLE
load-fragment: fix a typo

### PR DESCRIPTION
**Pull request by ExtinctFire**
Correct the typo of “priority” in log message

### CODE REVIEW

**Comment by evverx** [comment]
Interestingly, I can't seem to find this typo in https://fossies.org/linux/test/systemd-master.tar.gz/codespell.html. @jschleus I wonder if it was skipped somehow?

**Comment by jschleus** [comment]
Nobody is perfect: That pattern is still missing in the used dictionaries. At least in the Fossies "extra" dictionary, containing some otherwise unused spelling errors, it is now added `pririty->priority,privity`.

**Comment by evverx** [comment]
@jschleus thank you! I have to admit I had to look 'privity' up. It's not every day that I see this word :-)

I wonder if there is a badge like [Language Grade: C/C++](https://lgtm.com/projects/g/systemd/systemd/context:cpp) that we could embed in README and point to the Fossies report so that it would be easier to find it? Another option would be to just add a link to the report to https://systemd.io/CODE_QUALITY/.

**Comment by jschleus** [comment]
Yes, I found 'privity' only if I checked whether 'pririty` could possibly be a valid English word.
  
The spelling quality badge idea is interesting but I think it cannot currently be implemented seriously (at least not by Fossies) mainly since the algorithm to determine the rating grade isn't yet sophisticated enough.

By the way, the calculated score points used to determine the rating grade are visible as tooltip if the mouse is over such a rating grade. And clicking on a rating grade leads to the page https://fossies.org/codespell_rating.html that explains a little bit the used algorithm.

Quoting from that page:
>The Fossies source code spelling error grade assignment is more a gimmick instead of a serious    rating tool. As only a very rough indicator it's not well suited to compare different projects but it may  be a motivating reference point within the possibly troublesome spelling correction process.

Naturally you can link to some according Fossies information but unfortunately no comprehensive page regarding the Fossies codespell feature is existing. Currently the "best" descriptive link would be https://fossies.org/features.html#codespell or you may use just the systemd master codespell report page https://fossies.org/linux/test/systemd-master.tar.gz/codespell.html.

**Comment by evverx** [comment]
> the algorithm to determine the rating grade isn't yet sophisticated enough.

As long as the grade is A+ I have absolutely no problem with the algorithm :-) Seriously though, I probably shouldn't have used LGTM as an example because it indeed compares projects and for the most part that comparison makes sense. What I was trying to ask is whether there were official Fossies badges that could dynamically get grades via an API of some kind provided by Fossies. It's always possible to generate static badges like  [Codespell report](https://fossies.org/linux/test/systemd-master.tar.gz/codespell.html) should the need arise.

> Naturally you can link to some according Fossies information

I opened https://github.com/systemd/systemd/pull/15873 where I added both those links to docs/QUALITY_TOOLS.md

As an aside, I've just realized that Fossies also provides cloc reports that might come in handy as well: https://fossies.org/linux/test/systemd-master.d0192e9.200521.tar.gz/cloc.html.

**Comment by jschleus** [comment]
Probably the extreme values like A+ or E- may have also a limited "absolute" significance.
  
Your example Fossies badge (even using the "Fossies green") is really motivating. Maybe I will take a closer look at the topic and the generation of such badges. Perhaps it would make sense, if at all, to offer still both variants (without and with rating grade) then a project can decide for itself if applicable.

@QUALITY_TOOLS.md: I just want point out that the basic work of the Fossies reports is done by the tool  [codespell](https://github.com/codespell-project/codespell).

And yes, the cloc reports are generated since many years.

Although I like them there is much more work now behind the still experimental Doxygen source code documentation reports (with an intensive collaboration with one of the main developers). Since such reports may be very ressource hungry they are only generated for main releases, e.g.
&nbsp;&nbsp;[systemd: Main Page - doxygen documentation | Fossies Dox](https://fossies.org/dox/systemd).
But although the reports may have hopefully a real benefit they have a "natural" weakness: Fossies tries to analyze the source code and to do some according project specific Doxygen configuration adaptions but that is mostly not sufficient for an optimal result (and naturally many projects haven't Doxygen optimized source code). But at least such reports could motivate some FOSS projects - that are using supported languages - to deploy Doxygen itself to generate nice source code documentation.

**Comment by jschleus** [comment]
If there is still some interest in Fossies codespell report badges, I have played a little bit (using the tool "anybadge") and although I'm still not completely convinced and although I haven't fully understood the badges conventions here is the result:

&nbsp; [fossies_codespell_report_badges](https://fossies.org/warix/fossies_codespell_report_badges/)

This Fossies page is not yet linked (mainly since it uses in the examples real `systemd` related Fossies codespell links what you may not like).

**Comment by evverx** [comment]
@jschleus looks great! Thank you!

I've just opened https://github.com/systemd/systemd/pull/15969. Could you take a look?

> mainly since it uses in the examples real systemd related Fossies codespell links what you may not like

It's totally fine by me :-)

**Comment by evverx** [comment]
@jschleus at https://fossies.org/warix/fossies_codespell_report_badges/ where an example of what a badge could look like I'd replace `https://fossies.org/linux/misc/foobar/codespell.svg` with `https://fossies.org/linux/test/foobar/codespell.svg`. Though if the "misc" link will point somewhere eventually it probably should be left as is.

**Comment by jschleus** [comment]
#15969 looks ok  for me.

Hmm, if I understand your second comment correctly you mean that Fossies shouldn't show the according special information page (explaining the assumed problem) but just the standard output ("File not found" with HTTP status code 404) as e.g. for`https://fossies.org/linux/test/foobar/codespell.gif`. Ok, I will realize that soon (may be later I will replace it eventually by a combination of both).

**Comment by evverx** [comment]
What I was trying to say is that on that page in once place it seems "test" should be used instead of "misc". Hope the following screenshot helps:

Screenshot 2020-05-29 at 18 29 30

**Comment by jschleus** [comment]
Ah, grrh, as I edited that file I had have a kind of "error"-feeling ;-) Thanks, now corrected.

Nevertheless I will probably try to improve the badge error information pages (generating it dynamically to be able to add some project specific information).

**Pull request merged**
