### PR TITLE
lgtm: ignore certain cleanup functions

### PR DESCRIPTION
**Pull request by mrc0mmand**
This is a quick follow-up to 863bff75488d33f519deea6390988f3d9d72e6de to suppress following LGTM alert:

https://lgtm.com/projects/g/systemd/systemd/snapshot/3c4ed28f77052fd129d615da838c715e6c7599b1/files/src/shared/ask-password-api.c?sort=name&dir=ASC&mode=list#xbec5c7aaeb039689:1

this one is clearly bogus, since `c` is stack-allocated. I couldn't think of any scenarios where having an uninitialized stack-allocated variable with a cleanup handler would cause issues, so after [some experiments](https://github.com/mrc0mmand/codeql-sandbox) I tweaked the query to check only pointers.

### CODE REVIEW

**Comment by medhefgo** [comment]
> this one is clearly bogus, since `c` is stack-allocated. I couldn't think of any scenarios where having an uninitialized stack-allocated variable with a cleanup handler would cause issues, so after [some experiments](https://github.com/mrc0mmand/codeql-sandbox) I tweaked the query to check only pointers.

If I understand this correctly, it would break this:
https://github.com/systemd/systemd/blob/a2887ec370b2f46356f410b282d7b06e52fc9297/src/boot/efi/boot.c#L2400

**Comment by mrc0mmand** [comment]
> > this one is clearly bogus, since `c` is stack-allocated. I couldn't think of any scenarios where having an uninitialized stack-allocated variable with a cleanup handler would cause issues, so after [some experiments](https://github.com/mrc0mmand/codeql-sandbox) I tweaked the query to check only pointers.
> 
> If I understand this correctly, it would break this (as in, it would not detect the missing {}, which may end up freeing uninitialized struct members):
> 
> https://github.com/systemd/systemd/blob/a2887ec370b2f46356f410b282d7b06e52fc9297/src/boot/efi/boot.c#L2400

I see, that's the feedback I was looking for, thanks! I'll tweak the query further, then.

**Comment by medhefgo** [comment]
I wonder... can you query the attributes of the cleanup function itself? If it's decorated with `__attribute__ ((access (write_only, 1)))` and is called with a pointer to stack allocated (primitive) data it should be fine...

**Comment by mrc0mmand** [comment]
> I wonder... can you query the attributes of the cleanup function itself? If it's decorated with `__attribute__ ((access (write_only, 1)))` and is called with a pointer to stack allocated (primitive) data it should be fine...

You definitely can, so this might be a way to go. I'll play around with it for a bit.

**Comment by mrc0mmand** [comment]
> I wonder... can you query the attributes of the cleanup function itself? If it's decorated with `__attribute__ ((access (write_only, 1)))` and is called with a pointer to stack allocated (primitive) data it should be fine...

If I understand this correctly - we would have to decorate all such functions explicitly, since it's not done by default, right?

Another way would be to use a ~~black~~deny list with specific cleanup functions to ignore. Not sure which one is better.

**Comment by mrc0mmand** [comment]
I committed the deny-list approach, but in case we'd want to go the `access(write_only,...)` way I have a matching predicate more-or-less ready as well.

**Comment by mrc0mmand** [comment]
Also, Jan's comments nudged me into writing [more tests](https://github.com/mrc0mmand/codeql-sandbox/blob/master/cpp/UninitializedVariableWithCleanup/test.c) which uncovered another issue where the current query ignores stack-allocated structures with cleanup handlers, which might cause issues  (as mentioned in https://github.com/systemd/systemd/pull/21621#issuecomment-986207229). Should be fixed by the second commit.

**Comment by medhefgo** [comment]
> If I understand this correctly - we would have to decorate all such functions explicitly, since it's not done by default, right?

So far, only this one has crept up, right? It's trivial to tag it and probably even a good thing to do anyway as a hint to the compiler.

Personally, I'd prefer the cleaner approach by checking if the cleanup function is write_only, but you should await some other opinions, I guess.

One question I have: how does this (currently) behaves with code like the following. Is p here treated as uninitialized?
```c
_cleanup_free_ void *p;
...
p = malloc(...);
```

And in particular this one (which should/must be an error):
```c
_cleanup_free_ void *p;
...
if (...)
        return;
...
p = malloc(...);
```

**Comment by mrc0mmand** [comment]
> > If I understand this correctly - we would have to decorate all such functions explicitly, since it's not done by default, right?
> 
> So far, only this one has crept up, right? It's trivial to tag it and probably even a good thing to do anyway as a hint to the compiler.
> 
> Personally, I'd prefer the cleaner approach by checking if the cleanup function is write_only, but you should await some other opinions, I guess.

Agreed. Either approach is fine with me, so let's wait for more feedback.

> 
> One question I have: how does this (currently) behaves with code like the following. Is p here treated as uninitialized?
> 
> ```c
> _cleanup_free_ void *p;
> ...
> p = malloc(...);
> ```
> 
> And in particular this one (which should/must be an error):
> 
> ```c
> _cleanup_free_ void *p;
> ...
> if (...)
>         return;
> ...
> p = malloc(...);
> ```

Not well, actually, it won't detect the second case as "invalid". I'll look into that.

**Comment by medhefgo** [comment]
> Not well, actually, it won't detect the second case as "invalid". I'll look into that.

Honestly, I'm more inclined to argue that maybe uninitialized cleanup should never be allowed even in the trivial case were it's assigned a few lines down...

**Comment by mrc0mmand** [comment]
> > Not well, actually, it won't detect the second case as "invalid". I'll look into that.
> 
> Honestly, I'm more inclined to argue that maybe uninitialized cleanup should never be allowed even in the trivial case were it's assigned a few lines down...
> 
> (They can easily be found with `git grep -E "_cleanup_\w+_ [^=]+;"` and `git grep -E "_cleanup_\(\w+\) [^=]+;"` and the majority of them are in unit tests. Of these 95 only 3 are not in unit tests. I'd argue in favor of changing all those and keep things clean and simple...)

That would be ideal, but it is what it is. In the meantime I addressed https://github.com/systemd/systemd/pull/21621#issuecomment-986269991, so now the query checks if there's a `return` in between the variable declaration and its initialization; if so, treat the variable as uninitialized.

**Comment by keszybz** [comment]
Looks reasonable.

**Pull request merged**
