### PR TITLE
systemd-run can launch units with SyslogLevel and SyslogFacility

### PR DESCRIPTION
**Pull request by evverx**

### CODE REVIEW

**Comment by keszybz** [comment]
Please also do the equivalent shell completion changes for zsh. It should very similar.

Looks good.

**Comment by evverx** [comment]
@keszybz , thanks for the review. I'll take a look into the `zsh`-completion.
But looks like `_systemd-run` couldn't complete the properties names (or maybe I miss something:))

**Comment by poettering** [comment]
hmm, this should take ints too, and the client side should parse the strings to ints. See other commit.

**Comment by evverx** [comment]
@poettering , this works fine.
- strings

```
# systemd-run --remain-after-exit --property SyslogFacility=kern --property SyslogLevel=emerg true
Running as unit run-68.service.

# systemctl show -p SyslogFacility,SyslogLevel run-68
SyslogLevel=0
SyslogFacility=0
```
- numbers

```
# systemd-run --remain-after-exit --property SyslogFacility=0 --property SyslogLevel=0 true
Running as unit run-73.service.

# systemctl show -p SyslogFacility,SyslogLevel run-73
SyslogLevel=0
SyslogFacility=0
```
- mix

```
# systemd-run --remain-after-exit --property SyslogFacility=kern --property SyslogLevel=0 true
Running as unit run-78.service.

# systemctl show -p SyslogFacility,SyslogLevel run-78
SyslogLevel=0
SyslogFacility=0
```

**Comment by keszybz** [comment]
It seems to return 0 always... So that doesn't work.

The systemctl interface should take either a number or a string. For an added bonus, you can try converting the number back to a string in print_property().

**Comment by evverx** [comment]
> It seems to return 0 always... So that doesn't work

```
# systemd-run --remain-after-exit --property SyslogFacility=daemon --property SyslogLevel=debug true
Running as unit run-41.service.

# systemctl show -p SyslogFacility,SyslogLevel,SyslogPriority run-41
SyslogPriority=31
SyslogLevel=7
SyslogFacility=3
```

```
# systemd-run --remain-after-exit --property SyslogFacility=10 --property SyslogLevel=6 true
Running as unit run-46.service.

# systemctl show -p SyslogFacility,SyslogLevel,SyslogPriority run-46
SyslogPriority=86
SyslogLevel=6
SyslogFacility=10
```

**Comment by evverx** [comment]
> The systemctl interface should take either a number or a string.

Hm, I can create a unit:

```
[Service]
SyslogLevel=debug
...
```

or

```
[Service]
SyslogLevel=7
...
```

Why I can't pass a number or a string to `systemd-run`?

**Comment by poettering** [comment]
Again, we expose the facility/level as number on the service bus objects, hence they should also transmitted as a number over the bus when we create transient units with the props set. It's not OK to pass them as number at one place, but as a string enum at another.

**Comment by evverx** [comment]
oh, I understand:)

but can I pass a number or a string to `systemd-run`? (i.e. `--property LogLevel=debug` or `--property LogLevel=7`)

**Comment by keszybz** [comment]
Yes, you should be able to pass both. log_level_from_string() supports both, so this should already work.

**Comment by evverx** [comment]
@keszybz , @poettering , done.

**Pull request merged**
