### PR TITLE
basic: handle template globs correctly

### PR DESCRIPTION
**Pull request by jsynacek**
Original bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1288851

### CODE REVIEW

**Comment by poettering** [comment]
As discussed on telegram, this seems wrong to me. I think UNIT_NAME_GLOB should be fixed to allow the necessary globs to go through, and no new UNIT_NAME_TEMPLATE should be added.

**Comment by poettering** [comment]
Also, please add test cases for the extended validity checking!

**Comment by jsynacek** [comment]
I have rechecked this again and I believe this patch is correct. The real problem isn't the globs, they go through as expected.

Let's say I want to cat all runlevel*.target units.

`$ systemctl cat runlevel*.target`
No output.

However, I want to cat all services beginning with "systemd-".
`$ systemctl cat systemd\*.service`
The relevant output is displayed.

The code path is
systemctl.c: `cat()` -> `expand_names()` -> `unit_name_mangle_with_suffix()`
There in the last procedure, at its end, the call to `unit_name_to_type()` fails and the default ".service" suffix is appended. It fails, because a call to `unit_name_is_valid()` fails, because at that point, a unit name with "*" in it is considered invalid. There are two places where validity of a unit name is checked, this is one of them and IMHO is incorrect. That is what the patch fixes.

I hope this makes sense.

**Comment by poettering** [comment]
I am pretty sure we shouldn't mangle globs at all, and expect them to be pre-mangled...

**Comment by poettering** [comment]
The current globbing code doesn't consider non-primary names btw, hence `systemctl cat runlevel*.target` won't work anyway, since the template names are just symlinks, which PID 1 doesn't even know about...

**Comment by poettering** [comment]
I prepped a patch for this in #2445 now.

**Pull request closed without merging**
