### PR TITLE
WIP: json: add a "safe" variant of integer serializers that fall back to s…

### PR DESCRIPTION
**Pull request by poettering**
…trings

Our JSON implementation supports the full INT64_MIN…UINT64_MAX range for integers. Various other implementaions only support INT64_MIN…INT64_MAX, or in fact even less, i.e. -2^53…+2^53 (for example JavaScript itself). We'd really like to serialize the full uint64_t range however. Hence do what various people do: format those as strings.

This is in line with what the JSON-I spec says, see RFC 7493 section 2.2.

This only adds the basic concept, it's not used anywhere so far.

### CODE REVIEW

**Comment by poettering** [comment]
So I think we should doing this sooner or later to make it easier for other languages to work with this. For now nothing uses this and there are no tests.

Main reason I posted this is as discussion item with @AdrianVovk

**Comment by AdrianVovk** [comment]
I think I'm leaning slightly against this.

Languages that cannot represent uint64 (i.e. Javascript) aren't really suitable for dealing with userdb things, no? You need uint64 to do it correctly. Javascript has a lot of strange limitations, including its numbers, and I-JSON reflects these limitations. On the host system, however, I'm not very convinced its so important to be I-JSON compliant. There are only so many systems programming languages, and realistically I expect only system software to be parsing userdb entires

Languages that can represent uint64 (i.e. C, Rust) seem to have JSON parser libraries that can deal with uint64. Sure, not all libraries support it (i.e. json-glib), but those that do support it exist.

Some libraries also support transparently parsing a string as int, if requested, but not all do. This means that consumers of the JSON will need to do an annoying dance to get the data, which sometimes makes idiomatic use of a library impossible (i.e. an automatic serialization/deserialization library like Rust's `serde_json` may fail to do the conversion, or Go's `encoding/json`). 

Here's the libraries I checked:

|Library|Language|Supports u64|Promotes String to u64|
|---|---|---|---|
|sd-json|C| :+1: | :x: |
|json-glib|C (+ GObject)| :x: | :x: |
| json-c | C | :+1: | :+1: |
| json | Rust | :+1:  | :+1:  |
| serde_json | Rust | :+1: | :x: |
| encoding/json | Go | :+1: | :x: |

**Comment by poettering** [comment]
> Languages that cannot represent uint64 (i.e. Javascript) aren't really suitable for dealing with userdb things, no?

Well, in theory people can work around this, i.e. you could emulate a proper uint64_t range if you use two doubles and always store the upper 32bit in one and the lower 32bit in another, and then make sure you are careful with the various arithmetic operations. But I don't think many people will do that. However, what I think matters is that people can at least pass through and store user records reasonably safely in JS, without having to fear the record will be corrupted by that. 

or to say this differently:

1. I think there's value in supporting languages that support 64bit signed integers in json and unsigned 64bit integers natively (such as C with json-glib), so that they can fully operate.
2. I think there's also value in supporting languages that support 53bit signed integers only (JS…), so that they can at least store, load and transfer JSON objects we generate.

**Comment by AdrianVovk** [comment]
My concern is that the value of supporting json-glib and JavaScript is relatively smaller than the value of being able to conveniently parse and deal with the JSON data in the languages that people actually use for systems programming: Rust, Go, Python, etc. All those languages don't have any awareness that sometimes a string might be a number, and will need manual intervention from the programmer.

Examples:

- For Rust's serde_json, callers will need to create a trait that can parse the values into u64. Then they need to implement that trait for strings (parse the string into u64) and for u64 itself (just return its own value). Then wherever they want read one of these safe integer fields (into a structure, because that's how serde_json works), they'll need to annotate the field in the structure w/ an annotation that tells Serde that it needs to call this special trait method you've defined to transform the value. You'll need to duplicate this work for i64 as well, since JS can't represent those either. How error handling will be done is a bit unclear to me :shrug: 
- For Python's json library, you'll just need to wrap every access of the safe integer fields with `int`
- For Go's encoding/json library, which is part of the Go stdlib, you'll be unable to parse the JSON into a struct with type information. You'll need the safe integer fields to be of type `interface{}`, and then whenever you access them you'll need to write a switch statement that matches based on the type of the field to parse out the number.
- For json-glib, you'd need to get a reference to the JSON value there, then get its type. If its a string, you'll need to parse it, otherwise you need to get the integer value. This is a lot like the Go situation. Error handling is needed here too!

My point is most programming languages, especially those that do type inference or dynamic typing, do not know about I-JSON and will require programmer intervention to parse the things correctly. Sometimes the intervention is quite easy (i.e. in Python), but other times it gets really hard to get right (Go/C).

I would like that if this is done, it's done as a secondary option. So you can get a user record, or you can get a I-JSON variant of the user record. This would just need an extra method in the homed dbus API, and userdbd varlink API. API-wise, that means the user of the JSON library will deal in the standard uint64/int64, but you'd have a `json_variant_dump` (for normal JSON) and `json_variant_dump_ijson` (for I-JSON, where large numbers are conditionally turned into strings)

**Comment by poettering** [comment]
I prepped #29907 now, which is a more conservative, focussed approach, and only looks at dispatching, not at anything else. Specifically not at generating.

**Comment by yuwata** [comment]
Superseded by #29907.

**Pull request closed without merging**
