### PR TITLE
sd-dhcp: use CMSG_FIND_AND_COPY_DATA to avoid build failures on x32 architectures

### PR DESCRIPTION
**Pull request by bluca**
On architectures where timeval is 64bit but size_t is 32bit we have to use CMSG_FIND_AND_COPY_DATA. This affects x32 and riscv32.

Follow-up for 905d0ea7b0080dd

### CODE REVIEW

**Comment by yuwata** [comment]
> On architectures where timeval is 64bit but size_t is 32bit we have to use CMSG_FIND_AND_COPY_DATA. This affects x32 and riscv32.

Hm? I cannot follow why the current form does not work, but `CMSG_FIND_AND_COPY_DATA()` is fine... Could you elaborate more?

**Comment by bluca** [comment]
```
In file included from ../src/fundamental/macro-fundamental.h:5,
                 from ../src/basic/macro.h:13,
                 from ../src/basic/alloc-util.h:10,
                 from ../src/libsystemd-network/sd-dhcp-client.c:16:
../src/libsystemd-network/sd-dhcp-client.c: In function ‘client_receive_message_raw’:
../src/fundamental/macro-fundamental.h:145:25: error: static assertion failed: "alignof(struct timeval) <= alignof(struct cmsghdr)"
  145 | #define assert_cc(expr) static_assert(expr, #expr)
      |                         ^~~~~~~~~~~~~
../src/basic/socket-util.h:211:17: note: in expansion of macro ‘assert_cc’
  211 |                 assert_cc(alignof(type) <= alignof(struct cmsghdr));    \
      |                 ^~~~~~~~~
../src/libsystemd-network/sd-dhcp-client.c:2240:46: note: in expansion of macro ‘CMSG_TYPED_DATA’
 2240 |                         struct timeval *tv = CMSG_TYPED_DATA(cmsg, struct timeval);
      |                                              ^~~~~~~~~~~~~~~
```

https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=x32&ver=255%7Erc2-1&stamp=1700079289&raw=0

See 79dec6f5cc0b72d43dfb0469fa68b5cd023fbaf9

**Review by yuwata — CHANGES_REQUESTED** [review]
Ah, I did similar change in #27241. I completely forgot that.
Could you follow the same way as 789f5c6f706383442d85a9aedc6396a1a7877057, rather than running loop for cmsg data twice?
That is, please replace `CMSG_TYPED_DATA()` with `memcpy()`.

**Comment by bluca** [comment]
We should stop doing this manually, it's too much of a footgun, and given it affects exotic architectures it's really hard to detect. I can't imagine there would be enough cmsg to make it matter whether it runs once or twice.

**Comment by yuwata** [comment]
> We should stop doing this manually, it's too much of a footgun, and given it affects exotic architectures it's really hard to detect. I can't imagine there would be enough cmsg to make it matter whether it runs once or twice.

OK.

**Review by yuwata — APPROVED** [review]

**Pull request merged**
