### PR TITLE
Link executor statically

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=119945210 has a koji scratch build.

**Comment by YHNdnzj** [comment]
TBH, I think this is a pragmatic way out for now. https://github.com/systemd/systemd/pull/33279#issuecomment-2165528510 might sound good, but that approach won't fully fix the problem. Aside from the already-mentioned time window, our internal state changes would not be reflected as jobs, e.g. if service sends `READY=1` and we try to spawn `ExecStartPost=`, but executor is gone. We need to introduce another pool for such events to _partially workaround_ the issue, which seems awkward and creates a lot of churn. If certain distros are encountering such problem, statically link sd-executor to libshared + libcore is currently the simplest yet effective workaround.

**Review by bluca — APPROVED** [review]
The default is the status quo (shared), right? If so this sounds fine to me

**Comment by keszybz** [comment]
OK, let's merge this then. The feature is opt-in so this should be fairly safe.

**Pull request merged**
