### PR TITLE
actively say that .include is obsolete

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by poettering** [comment]
simply add a symlink /etc/systemd/system/netctl@my-profile.service.d/foobar.conf pointing to /usr/lib/systemd/system/netctl@.service (I'd really rename that file though, but it doesn't matter)

**Comment by joukewitteveen** [comment]
That surprises me. I expected to have to add the overrides to such a file and symlink the included file to `multi-user.target.wants/`. Whould that work as well? What are the reasons to choose one method over the other? At least the precedence is different between the two methods.

**Comment by joukewitteveen** [comment]
Let me try to wrap my head around this without wasting your time.

**Current Situation**
- /etc/systemd/system/netctl@my-profile.service:
```
.include  /usr/lib/systemd/system/netctl@.service

[Unit]
Description=my-description
BindsTo=sys-subsystem-my-device.device
After=sys-subsystem-my-device.device
```
- `ln -s /etc/systemd/system/netctl@my-profile.service /etc/systemd/system/multi-user.target.wants/`

**Your Proposal**
- /etc/systemd/system/netctl@my-profile.service:
```
[Unit]
Description=my-description
BindsTo=sys-subsystem-my-device.device
After=sys-subsystem-my-device.device
```
- `ln -s /usr/lib/systemd/system/netctl@.service /etc/systemd/system/netctl@my-profile.service.d/foobar.conf`
- `ln -s /etc/systemd/system/netctl@my-profile.service /etc/systemd/system/multi-user.target.wants/`

Here, the options in netctl@.service override those in the instantiated unit, right?

**Possible Alternative**
- /etc/systemd/system/netctl@my-profile.service.d/quux.conf:
```
[Unit]
Description=my-description
BindsTo=sys-subsystem-my-device.device
After=sys-subsystem-my-device.device
```
- `ln -s /usr/lib/systemd/system/netctl@.service /etc/systemd/system/multi-user.target.wants/netctl@my-profile.service`

Is this canonical? If it works, I reckon options in quux.conf now override those in netctl@.service.

**Comment by poettering** [comment]
yeah, all correct, and yes the quux option is the prettiest one

**Pull request merged**
