### PR TITLE
tmp.mount.hm4: After swap.target

### PR DESCRIPTION
**Pull request by frankheckenbach**
fix issue #2930

### CODE REVIEW

**Comment by mbiebl** [comment]
Hm, shouldn't we also add this to tmp.mount units that are generated via /etc/fstab to be consistent?

**Comment by keszybz** [comment]
> Hm, shouldn't we also add this to tmp.mount units that are generated via /etc/fstab to be consistent?

Dunno. We could, but after all, the point of adding `/tmp` to `/etc/fstab` is to override the settings. It'll either be non-tmpfs-based, or you can still add `x-systemd.requires=swap.target`.

**Comment by poettering** [comment]
I agree with @keszybz i must say.

**Comment by mbiebl** [comment]
my main concern is, that most users probably won't add x-systemd.requires=swap.target simply because they don't know, they should. Can we at least fix this with better documentation (somewhere) then?

**Comment by keszybz** [comment]
OTOH, adding Requires makes things more prone to error (most systems will run just fine without swap.target, so Wants, as added in this PR, is much more appropriate). So I'd first add support for x-systemd.wants= in the fstab, and then add a recommendation to use x-systemd.wants=swap.target.

**Comment by poettering** [comment]
@mbiebl I don't think that "most" users really should add that. People generally add an fstab entry for /tmp to make it a physical disk. But in that case it doesn't matter whether it is unmounted before or after the swap is torn down.

I mean, if you want /tmp to be on tmpfs, then you use our defaults. You only would add an fstab entry for /tmp, if you really don't want our defaults.

**Comment by poettering** [comment]
@keszybz i don't think that either Wants= or Requires= is right here. After= is fully sufficient. Whether swap is enabled or not, should be an admin decision, but not a requirement of mounting /tmp!

**Comment by keszybz** [comment]
Right, After is even better. But we only provide x.systemd-requires=. Maybe we should add x.systemd-{wants,after,before}=.

**Pull request merged**
