### PR TITLE
po: update Polish translation 190325

### PR DESCRIPTION
**Pull request by piotrdrag**
I’m not sure I understand the original message, though.

### CODE REVIEW

**Comment by keszybz** [comment]
Yeah, the original message is pretty bad. So maybe let's fix the original message first.

**Comment by keszybz** [comment]
#12100 ?

**Comment by piotrdrag** [comment]
It’s definitely an improvement. :)

**Comment by keszybz** [comment]
So this needs a rebase/rewrite now that #12100 has been merged.

**Pull request merged**
