### PR TITLE
shell-completion: systemd-run: add missing options

### LINKED ISSUE #19044: 'systemd-run --slice-inherit' missing bash/zsh completion
systemd-248rc2

Minor wart: systemd-run has shell completion for `--slice` but is missing autocompletion for `--slice-inherit` which seems to have been forgotten in https://github.com/systemd/systemd/commit/2c7039b3169d736a98ca1cb1e03129f12c2ab6ed.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #19044.

### CODE REVIEW

**Comment by yuwata** [comment]
(I do not use zsh. Please test it.)

**Comment by mcatanzaro** [comment]
I don't use zsh either :)

**Review by bluca — APPROVED** [review]
I do not use zsh either, but changes look good to me. I think we can consider shell completion as a form of documentation, and thus merge it now for 248.

**Comment by keszybz** [comment]
LGTM.
With zsh, we're not completing the positional argument correctly (files are suggested, instead of executables in $PATH). But that part is not touched by this PR.

**Pull request merged**
