### PR TITLE
missing: separate missing.h more

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by yuwata** [comment]
@evverx I've tested this on Fedora 28 with /usr/include/linux from CentOS7. But, if possible, could you test this on centos before this is merged?

**Comment by evverx** [comment]
@yuwata ping me when `semaphoreci` is green. I'll spin up a VM shortly afterwards.

**Comment by yuwata** [comment]
@evverx semaphoreci and travis-ci are now green.

**Comment by evverx** [comment]
I've just successfully built `systemd` on CentOS CI so in a way CentOS CI seems to be green too.

**Comment by yuwata** [comment]
@evverx Thank you so much!

**Comment by evverx** [comment]
No problem. I didn't run the tests though :-) @mrc0mmand could you trigger a full CI build just in case?

**Comment by mrc0mmand** [comment]
Full CentOS build passes as well:

```
TEST SUMMARY:
-------------
PASSED: 30
FAILED: 0
TOTAL:  30
```

**Comment by yuwata** [comment]
@mrc0mmand Thanks a lot!!

**Pull request merged**
