### PR TITLE
test-network: use dnsmasq with --dhcp-alternate-port option to test DHCP.ListenPort=

### LINKED ISSUE #11675: test: intermittent failure in `test_dhcp_client_listen_port` (`systemd-networkd-tests.py`)
**systemd version the issue has been seen with**
> latest master

**Used distribution**
 > CentOS 7.6

After re-enabling `test/test-network/systemd-networkd-tests.py` (https://github.com/systemd/systemd-centos-ci/pull/66) and observing the results for a few days, another intermittent issue surfaced (happened twice in the last ~20 runs):

```
======================================================================
FAIL: test_dhcp_client_listen_port (__main__.NetworkdNetworkDHCPClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 1218, in test_dhcp_client_listen_port
    self.assertRegex(str(port), '5555')
AssertionError: Regex didn't match: '5555' not found in '68'

----------------------------------------------------------------------
Ran 69 tests in 744.624s
```

Index: https://ci.centos.org/job/systemd-pr-build/4664/artifact/systemd-centos-ci/index.html
Full log: https://ci.centos.org/job/systemd-pr-build/4664/artifact/systemd-centos-ci/artifacts_2s_UPO/testsuite-logs.pE9/systemd-networkd-tests.py_FAIL.log

cc @yuwata, @ssahani

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #11675.

cc @mrc0mmand and @ssahani.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
LGTM, thanks! 

CI likes it as well:
```
test_dhcp_client_listen_port (__main__.NetworkdNetworkDHCPClientTests) ... 
111: veth99@veth-peer: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 192.168.5.181/24 brd 192.168.5.255 scope global dynamic veth99
       valid_lft 3596sec preferred_lft 3596sec
ok
```

**Comment by yuwata** [comment]
The failure in semaphoreci is unrelated. @evverx What happens to semaphoreci?

**Comment by ssahani** [comment]
LGTM please merge.

**Comment by evverx** [comment]
@yuwata SemaphoreCI and TravisCI were pointed to a repository `add-apt-repository` has trouble with from time to time (a little background can be found in https://github.com/systemd/systemd/pull/11531#issuecomment-457248030). I notified the maintainers in https://github.com/systemd/systemd/pull/11531#issuecomment-460023474 and "fixed" TravisCI in https://github.com/systemd/systemd/pull/11639. Now I'm just kind of hoping that the repository will be fixed one day.

**Pull request merged**
