### PR TITLE
VRF documentation, parameter renames & parsing of RT names

### PR DESCRIPTION
**Pull request by andir**
Since in most parts of the code it is referred to a `Table` (e.g. `Route.Table=` or `DHCP.RouteTable=`) it probably makes sense to rename the field in the VRF code. Additionally I finally added some (more) documentation to `systemd.netdev(5)` and switched to parsing routing tables names in addition to just plain numbers.

The last commit in this PR removes the old `TableId` field. I am not sure about the adoption out there but it probably wouldn't hurt having some kind of deprecation/migration phase?

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, I wonder how many people use this. Usually we keep compat in, but don't document it if we make changes, but then again, if there aren't many users we might just want to drop this. Dunno...

Slightly leaning towards keeping the old name for now... But could you add a comment saying that it's an obsolete legacy name there?

Patch looks great otherwise

**Comment by andir** [comment]
I dropped the commit that removes the `VRF.TableId` Option and added some deprecation documentation about the same.

**Comment by poettering** [comment]
oh, no, no deprecation comments in the docs please. Deprecated stuff we generally remove entirely from the docs. But in the code we add a comment, that the stuff is deprecated, that's all. Hence, please add a code comment, but do not add it to the docs...

**Comment by andir** [comment]
I added a `/* deprecated */` comment to the parameter and removed the documentation commit.

**Comment by poettering** [comment]
lgtm

**Pull request merged**
