### PR TITLE
 boot: use efi_memcpy inplace of memcpy

### PR DESCRIPTION
**Pull request by sshedi**
Fixes: CID#1489876

### CODE REVIEW

**Comment by yuwata** [comment]
It seems the issue is false positive. As memcpy(), which is an alias of efi_memcpy(), accepts NULL.

Maybe, explicitly (and unconditionally) calling efi_memcpy() is better.

cc @medhefgo

**Comment by sshedi** [comment]
I think in this case, it's using __builtin_memcpy but agree we can use `efi_memcpy` directly instead of doing null check.

**Comment by medhefgo** [comment]
I think it might be better to hoist the NULL checks out of efi_ mem functions and put them into the #define. Otherwise we end up playing whack-a-mole with these.

**Comment by medhefgo** [comment]
Or maybe do as @yuwata suggested before and keep the definitions of mem* to the standard and use assert…

**Comment by medhefgo** [comment]
I think in the end I prefer calling `efi_memcpy` unconditionally here. xstrndup8/16 already does the same.

**Comment by sshedi** [comment]
Agree, will update the PR. Thanks for the inputs.

**Review by yuwata — APPROVED** [review]
LGTM too.

**Pull request merged**
