### PR TITLE
sd-dhcp-client: gracefully handle invalid ether type client ID

### LINKED ISSUE #25984: `networkctl status <iface>` fails to parse leases where client ids start with `\x01` and don't contain exactly 7 bytes
While tracking down some other issue I noticed that when dhcp clients send client ids like `\x01a` `networkctl status <iface>` (and `networkctl status --all`) start failing on the machine where the dhcp server handing over those leases is run with
```
Failed to parse bus message: Invalid argument
```
The "Leases" property `networkctl` fails to parse looks like
```
busctl get-property org.freedesktop.network1 /org/freedesktop/network1/link/_35 org.freedesktop.network1.DHCPServer Leases
a(uayayayayt) 2 2 2 1 97 4 192 168 123 184 4 0 0 0 0 16 122 117 23 188 172 203 0 0 0 0 0 0 0 0 0 0 103404099704 2 11 0 104 101 108 108 111 119 111 114 108 100 4 192 168 123 182 4 0 0 0 0 16 122 117 23 188 172 203 0 0 0 0 0 0 0 0 0 0 102412938078
```
As far as I can tell those client ids get rejected by `sd_dhcp_client_id_to_string` called by `dump_dhcp_leases`: https://github.com/systemd/systemd/blob/a3310012e876873a72c0f54600d772455f9ef6ea/src/libsystemd-network/sd-dhcp-client.c#L196-L197

### PR DESCRIPTION
**Pull request by yuwata**
Currently, sd-dhcp-server accepts spurious client IDs, then the leases exposed by networkd may be invalid. Let's make networkctl gracefully show such leases.

Fixes #25984.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx

**Comment by evverx** [comment]
Thanks!

Looking at https://github.com/systemd/systemd/issues/25984 it seems I didn't mention anywhere that bogus client ids like `\xffa` break `networkctl` as well. Sorry about that. They get rejected in
https://github.com/systemd/systemd/blob/a3310012e876873a72c0f54600d772455f9ef6ea/src/libsystemd-network/sd-dhcp-client.c#L210-L212

Also I think it would be better if instead of just `DATA` or `ETHER ` it also added hexdumps of those bogus client ids to make it easier to track them down but it wouldn't be backward-compatible unfortunately as far as I understand in the sense that it can probably break some parsers expecting only `DATA` without any hexdumps.

**Comment by yuwata** [comment]
@evverx Invalid IAID/DUID is also now handled gracefully. Thank you for pointing out that.

> Also I think it would be better if instead of just `DATA` or `ETHER ` it also added hexdumps of those bogus client ids to make it easier to track them down but it wouldn't be backward-compatible unfortunately as far as I understand in the sense that it can probably break some parsers expecting only `DATA` without any hexdumps.

The string is now only provided by `networkctl`, and we usually does not care about backward compatibility of human readable outputs. Hence, the change should be acceptable.

**Comment by evverx** [comment]
> The string is now only provided by networkctl, and we usually does not care about backward compatibility of human readable outputs. 

Those files are also copied by other projects like NM and I'm not sure what exactly they do with them so probably it should be fine to leave it as is. If all else fails client ids can always be extracted via DBus anyway.

As usual I think it would be great if it could be covered by some tests to prevent regressions when, say, "TODO" is addressed by starting returning -EINVAL there and breaking networkctl again but apparently PRs should be merged in a hurry with no tests for whatever reason these days.

**Comment by yuwata** [comment]
Note, IIRC, NM does not use libsystemd-network anymore.

**Comment by evverx** [comment]
I don't know but I saw https://github.com/systemd/systemd/pull/25636 recently and kind of assumed NM still used libsystemd-network. I might be wrong of course.

**Comment by evverx** [comment]
@yuwata FWIW you're right. NM dropped the dhcp4 client last year and the lldp client was removed 3 months ago. The dhcp6 client is still there though.

**Pull request merged**
