### PR TITLE
core: when applying io/blkio per-device rules, don't remove them if t…

### PR DESCRIPTION
**Pull request by poettering**
…hey fail

These devices might show up later, hence leave the rules as they are.
Applying the limits should not alter configuration.

### CODE REVIEW

**Comment by htejun** [comment]
LGTM FWIW.

**Comment by poettering** [comment]
thanks for the review!

**Comment by keszybz** [comment]
Yeah, that old code is quite surprising. Patch looks good.

**Comment by keszybz** [comment]
```
Jun 12 19:28:42 autopkgtest systemd-udevd[1113]: Error resolving group 'render': Connection timed out
Jun 12 19:29:07 autopkgtest systemd-udevd[1113]: Error resolving group 'kvm': Connection timed out
Jun 12 19:29:42 autopkgtest systemd-udevd[1113]: Error resolving group 'render': Connection timed out
Jun 12 19:30:07 autopkgtest systemd-udevd[1113]: Error resolving group 'kvm': Connection timed out
Jun 12 19:28:42 autopkgtest systemd-udevd[1113]: Error resolving group 'render': Connection timed out
Jun 12 19:29:07 autopkgtest systemd-udevd[1113]: Error resolving group 'kvm': Connection timed out
Jun 12 19:29:42 autopkgtest systemd-udevd[1113]: Error resolving group 'render': Connection timed out
Jun 12 19:30:07 autopkgtest systemd-udevd[1113]: Error resolving group 'kvm': Connection timed out
```

**Pull request merged**
