### PR TITLE
networkd: remote checksum offload for vxlan

### PR DESCRIPTION
**Pull request by ssahani**
…load

This patch adds support to remote checksum checksum offload
to VXLAN. This patch adds RemoteCheckSumTx and  RemoteCheckSumRx vxlan
configuration to enable remote checksum offload for transmit
and receive on the VXLAN tunnel.

### CODE REVIEW

**Comment by zonque** [comment]
The Cent OS CI failure is unrelated, btw. Ignore it this time please.

**Comment by ssahani** [comment]
rebased on pushed.

**Comment by poettering** [comment]
I am pretty sure "CheckSum" should be "Checksum" as the english language appears to recognize this as one word, at least judging by the use in wikipedia:

https://en.wikipedia.org/wiki/Checksum

Any hance you can prep a patch that renames the two optins to RemoteChecksumTx= and RemoteChecksumRx=?

**Comment by poettering** [comment]
filed #4307 and marked it for the 232 release, so that we don't forget to fix this

**Pull request merged**
