### PR TITLE
Make elf2efi work with clang-18

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Review by DaanDeMeyer — CHANGES_REQUESTED** [review]
Should we require that .got is empty? It seems to have to do with relocations which this script deals but it does not handle .got directly yet so if we suddenly get a .got section we should probably fail until someone can verify that the script still does the right thing if there's a non-empty .got section.

**Comment by DaanDeMeyer** [comment]
cc @MaskRay (who introduced .relro_padding), any chance you can check the last commit to see if what we're doing here makes sense? (We also worked together on cquery for a while a long time ago)

**Comment by MaskRay** [comment]
> cc @MaskRay (who introduced .relro_padding), any chance you can check the last commit to see if what we're doing here makes sense? (We also worked together on cquery for a while a long time ago)

Hi, long time no see!

> clang-18 does the section setup differently than older versions. There is a bunch of ordering chagnes, but it also inserts the following:

You want to change it to lld 18. clang and lld are different packages.

lld defaults to RELRO, which can be disabled with `-z norelro`. If you do want to support RELRO executables, ignoring `.relro_padding` LGTM. Ignoring empty `.got` also LG.

**Comment by MaskRay** [comment]
BTW, on the Clang side, there is a UEFI toolchain proposal: https://discourse.llvm.org/t/rfc-uefi-driver-support-uefi-target/73261 The idea is for Clang to emit a PE/COFF object file, which can be linked with lld-link, instead of requiring an ELF conversion.

**Comment by keszybz** [comment]
@MaskRay thank you for the review.

I changed the clang→lld in the description and added the check that Daan requested. Empty .got sections and skipped, and non-empty are refused with an error.

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by DaanDeMeyer** [comment]
```

**Comment by keszybz** [comment]
Fedora too. I prolly should have used your latest magick to build an rpm.

**Comment by keszybz** [comment]
I downgraded the check for non-empty .got sections to a warning. This isn't really relevant to this PR: they were already present with earlier versions of clang/lld. I think we can merge this PR to get clang-18 unblocked.

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by keszybz** [comment]
noble-s390x failed in TEST-46-HOMED, unrelated.

**Pull request merged**
