### PR TITLE
glyph-util: introduce special_glyph_enabled() and disable it when booted with nomodeset

### LINKED ISSUE #32301: weird square chars in systemd console messages
### systemd version the issue has been seen with

252

### Used distribution

debian12

### Linux kernel version used

6.1.0-18-amd64

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

i see these weird square characters in systemd console log/output when on vga 80x25 mode

is this a bug or intentional beviour (abbreviation mechanism) ? if the latter, what's the purpose ?

grafik

### Steps to reproduce the problem

boot a debian 12 VM with "nomodeset" to avoid switching console to higher resolution

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Hopefully fixes #32301.

### CODE REVIEW

**Comment by YHNdnzj** [comment]
Hmm, what's special about nomodeset? It should not have any impact on the console font? Or, do you expect people to set this during debugging?

**Comment by poettering** [comment]
hmm, i find the check regarding nomodeset a bit unnecessary. It's 2024. I really don't think we need to provide explicit support for anything like that. I think people who whave such retro terminals should just add SYSTEMD_UTF8=0 to their kernel cmdline (which then sets that as an env var for PID 1), which we already honour then and turn off utf8 output.

I don't think we need any further support. This really doesn't have to be automatic, it's a legacy corner case noone really complained about in a decade, no time to handle this any nicer yet.

**Comment by poettering** [comment]
i guess the first two are already merged by now. The third one I really don't like. The "nomodeset" thing is too specific, and it this point in time I think if people still insist on some retro terminal without any reasonable UTF-8 support they should just turn off utf8 explicitly by telling us so.

**Comment by poettering** [comment]
also, iirc even without modesetting I think the vga tty layer has place for a charse of 512 glyphs, and hence could actually provide … if the right font is chosen?

**Comment by YHNdnzj** [comment]
> also, iirc even without modesetting I think the vga tty layer has place for a charse of 512 glyphs, and hence could actually provide … if the right font is chosen?

Yeah. As I mentioned, kernel modesetting or not should not have any effect on Linux tty console except for resolution maybe - either simpledrm/amdgpudrmfb/... i.e. fbdev backed by drm devices or traditional efifb/vesafb provided by firmware is used. Both support loading external consolefonts.

**Comment by yuwata** [comment]
OK. I thought that nomodeset also disables to use kind of special glyph. But if not, this is meaningless. Let's close. The first commit is already merged by another PR. Thanks.

**Pull request closed without merging**
