### PR TITLE
hwdb: Allow end-users root-less access to TL866 EPROM readers

### PR DESCRIPTION
**Pull request by hadess**
As is currently done in the upstream minipro tool:
https://gitlab.com/DavidGriffith/minipro/-/tree/master/udev

### CODE REVIEW

**Comment by hadess** [comment]
The failure looks like it was caused by a Python update:
```
/home/runner/work/systemd/systemd/hwdb.d/parse_hwdb.py:178: UserWarning: warn_multiple_tokens_in_named_alternation: setting results name 'VALUE' on Or expression will return a list of all parsed tokens in an And alternative, in prior versions only the first token was returned; enclosecontained argument in Group
  ('!' ^ (Optional('!') - Word(alphanums + '_')))('VALUE')
```

@keszybz ?

**Comment by keszybz** [comment]
The change LGTM.

I'll take a stab at fixing the test later.

**Comment by hadess** [comment]
I repushed your changes with my commit last...

**Comment by hadess** [comment]
Can't remember the number of times I've been bitten by that case problem...

**Pull request merged**
