### PR TITLE
udev: net_id – handle Hyper-V synthetic NICs

### LINKED ISSUE #8652: udev: Hyper-V network adapters are mapped to a different interface name (eth) on every boot
### Submission type

 - Bug report

### systemd version the issue has been seen with
215

> …

### Used distribution
Debian

> …

### In case of bug report: Expected behaviour you didn't see
Expect that one NIC is always mapped to a persistent device name.

> …

### In case of bug report: Unexpected behaviour you saw
On every new boot, NICs seems to be randomly mapped to device names

> …

### In case of bug report: Steps to reproduce the problem
Add more than one NIC to the Hyper-V VM (I can consistently reproduce with 3 NICs - I have tried only with synthetic NICs, not legacy).
Reboot the server and check that the interface MACs are switched - apparently in a random order.

The issue reproduced on both Hyper-V 2008 R2 and Hyper-V 2012 R2.
I haven't tried Hyper-V 2016 yet.

Also, this has been previously reported to Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810247

Their conclusion is that it is a systemd udev bug and recommended to report upstream.

Also, they suggested that the issue is similar to the one fixed by:
https://github.com/systemd/systemd/commit/a24d03b8ee2ca62cd1273e27cf4e79ddcc0fbb1c#diff-d1ebe3fa7fae7feeba8f0d448bc1171e

Although that fix didn't cover NIC devices.

> …

### PR DESCRIPTION
**Pull request by filbranden**
Hyper-V has an abstract bus, which gets renumbered on guest startup. So let's use the device GUIDs, which can be retrieved from the 'device_id' sysfs attribute.

In order to fit the network interface name length limit of 15 characters, let's use only the last part of the GUID, which has length 12, added to the "enh" prefix to get to the maximum of 15.

**NOTE:** I'm not sure that this is a safe assumption, that the GUID is consistent and unique and will be preserved across all changes... Also, is it safe to just take the last part of it? Is this better than using the MAC address? Anyways, if this is not 100% correct, I'd hope this can be used as a starting point for that...

Fixes #8652

Tested:
- udevadm test-builtin net_id /sys/class/net/eth1
- Booted a VM on Azure. (eth1 was renamed properly, eth0 went to enhXXX and then back to eth0 but that can be explained by netplan.)

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM. Can you also write up a NEWS entry for this?

**Comment by filbranden** [comment]
> LGTM. Can you also write up a NEWS entry for this?

Yes will do.

**Comment by filbranden** [comment]
@shemminger I happened to work on this patch for naming Hyper-V network interfaces in a consistent way and I noticed you're working on related patches...

Does this patch make sense to you? It makes assumptions about the GUID, in particular that the last 12 characters will be unique on the same machine...

Let me know if you think this is not OK for some reason.

(Though there's a limitation of 15 characters for network interface names, so if last 12 characters in GUID is not OK, then what would be a good way to consistently name an interface that is preserved across boots, migrations and other operations?)

**Comment by flo-wer** [comment]
Looking at [sysfs-bus-vmbus](https://github.com/torvalds/linux/blob/master/Documentation/ABI/stable/sysfs-bus-vmbus), there seems to be a subchannel_id. If this value is stable and unique per interface (by itself or together with a channel id) it could be used like the pci bus number. To truncate the GUID seems rather useless, as judging from https://github.com/systemd/systemd/issues/8652#issuecomment-379398820, the MAC address is stable and has the same length. I also found https://blogs.msdn.microsoft.com/oldnewthing/20080627-00/?p=21823, which says truncating a GUID is a bad idea.

**Comment by shemminger** [comment]
On Sat, 07 Apr 2018 08:34:57 -0700
Filipe Brandenburger <notifications@github.com> wrote:

> @shemminger I happened to work on this patch for naming Hyper-V network interfaces in a consistent way and I noticed you're working on related patches...
> 
> Does this patch make sense to you? It makes assumptions about the GUID, in particular that the last 12 characters will be unique on the same machine...
> 
> Let me know if you think this is not OK for some reason.
> 
> (Though there's a limitation of 15 characters for network interface names, so if last 12 characters in GUID is not OK, then what would be a good way to consistently name an interface that is preserved across boots, migrations and other operations?)
> 
> 

The key attributes of consistent naming are:
	* same name on every boot
	* same name on every VM
	* same name when hotplugged

In my experience, the GUID value is persistent but not the same on all
VM's. Therefore it won't work.

Subchannel Id's are assigned sequentially so they don't work as a
persistent value when different VM's have different numbers of  CPU's or
other devices.

There is also a serial number field (not easily visible in sysfs) which
has been discussed, but it has similar problems.

Another option in Hyper-V which could help is device name being forwarded
from host environment. Linux doesn't handle this now but it could.

Lastly, names really need to be shorter. Even current MAC based naming
on USB sucks. Users want to add .VLAN on the end of device; and that
doesn't work for VLAN 4096.

**Comment by shemminger** [comment]
On Sun, 08 Apr 2018 00:59:02 +0000 (UTC)
Florian Werner <notifications@github.com> wrote:

> Looking at [sysfs-bus-vmbus](https://github.com/torvalds/linux/blob/master/Documentation/ABI/stable/sysfs-bus-vmbus), there seems to be a subchannel_id. If this value is stable and unique per interface (by itself or together with a channel id) it could be used like the pci bus number. To truncate the GUID seems rather useless, as judging from https://github.com/systemd/systemd/issues/8652#issuecomment-379398820, the MAC address is stable and has the same length. I also found https://blogs.msdn.microsoft.com/oldnewthing/20080627-00/?p=21823, which says truncating a GUID is a bad idea.
> 

MAC address fails for scaling deployment.  You want  every VM to have same device names.
Subchannel_id is assigned sequentially, so it breaks if you add storage devices; or in
case of hotplug.

**Comment by poettering** [comment]
patch looks fine code-wise to me, but if @shemminger suggests the data used isn't really stable then I figure this is problematic...

**Comment by keszybz** [comment]
> The key attributes of consistent naming are:
> * same name on every boot
> * same name on every VM
> * same name when hotplugged

It seems that the current patch is OK on characteristic one and three, and it's just characteristic two which is problematic.

I think characteristic two is desirable, but not really a requirement. For example, on real hardware, I'll get unpredicatable `enp0s*` names, the same as here. And if the virtualization environment does not preserve the UUID identifiers of network devices, that's a limitation of that environment or its configuration. If I take my libvirt config and copy the machine and remove slot configuration from the `<interface type='network>` section, I'll lose the predictability of network interfaces naming too, as expected.

>  To truncate the GUID seems rather useless, as judging from #8652 (comment)

I don't think that the comments in #8652 support that conclusion.

> the MAC address is stable and has the same length

Using MAC addresses for this is not particularly useful. If somebody want to do that, they can use NamePolicy=mac already.

> https://blogs.msdn.microsoft.com/oldnewthing/20080627-00/?p=21823

It's old and not relevant, since it talks about GUIDs that are created by serially incrementing some number. A quick look at the UIDs in https://github.com/systemd/systemd/issues/8652#issuecomment-379398820 shows that they don't use this pattern.

**Comment by shemminger** [comment]
On Mon, 09 Apr 2018 07:13:58 -0700
Zbigniew Jędrzejewski-Szmek <notifications@github.com> wrote:

> > The key attributes of consistent naming are:
> > * same name on every boot
> > * same name on every VM
> > * same name when hotplugged  
> 
> It seems that the current patch is OK on characteristic one and three, and it's just characteristic two which is problematic.
> 
> I think characteristic two is desirable, but not really a requirement. For example, on real hardware, I'll get unpredicatable `enp0s*` names, the same as here. And if the virtualization environment does not preserve the UUID identifiers of network devices, that's a limitation of that environment or its configuration. If I take my libvirt config and copy the machine and remove slot configuration from the `<interface type='network>` section, I'll lose the predictability of network interfaces naming too, as expected.

It is a requiremnt.  Distro's and cloudinit rely on the same name on every VM.
That is one of the reasons, it hasn't changed.

> >  To truncate the GUID seems rather useless, as judging from #8652 (comment)  
> 
> I don't think that the comments in #8652 support that conclusion.
> 
> > the MAC address is stable and has the same length  
> 
> Using MAC addresses for this is not particularly useful. If somebody want to do that, they can use NamePolicy=mac already.
> 
> > https://blogs.msdn.microsoft.com/oldnewthing/20080627-00/?p=21823  
> 
> It's old and not relevant, since it talks about GUIDs that are created by serially incrementing some number. A quick look at the UIDs in https://github.com/systemd/systemd/issues/8652#issuecomment-379398820 shows that they don't use this pattern.
>

**Comment by keszybz** [comment]
> It is a requiremnt. Distro's and cloudinit rely on the same name on every VM. That is one of the reasons, it hasn't changed.

OK. But where does this UUID come from? Is it part of the hyper-v guest description? Is it set somewhere, generated randomly?

**Comment by shemminger** [comment]
On Mon, 09 Apr 2018 08:35:43 -0700
Zbigniew Jędrzejewski-Szmek <notifications@github.com> wrote:

> > It is a requiremnt. Distro's and cloudinit rely on the same name on every VM. That is one of the reasons, it hasn't changed.  
> 
> OK. But where does this UUID come from? Is it part of the hyper-v guest description? Is it set somewhere, generated randomly?
> 

It is generated by the host.

**Comment by shemminger** [comment]
On Tue, 10 Apr 2018 17:20:29 +0000 (UTC)
Filipe Brandenburger <notifications@github.com> wrote:

> @shemminger 
> 
> > It is a requiremnt.  Distro's and cloudinit rely on the same name on every VM.
> > That is one of the reasons, it hasn't changed.  
> 
> But I think right now it's broken, names are kept at ethX assigned by kernel and on every boot they may come in a different order. At least that's what #8652 claims (but it's possible this was a bug in older kernels like 3.16 that was fixed since.)

I have not heard of any customers with naming issues (yet).
Most likely vmbus discovery is single threaded the names are repeatable right now on Azure/Hyper-V.

> 
> But I believe when you're talking about cloudinit you're focusing on Azure, where I believe cloudinit is pushing some .link files to fix eth0, eth1, etc. by MAC address, correct?

Yes. Cloudinit get some meta-data from system.

> 
> > The key attributes of consistent naming are:
> > * same name on every boot
> > * same name on every VM
> > * same name when hotplugged  
> 
> Let me ask some rhetorical questions...
> 
> If these were legacy interfaces (PCI simulated), would you be able to achieve the consistent naming attributes above? If so, how? If that's possible, can similar attributes be found in vmbus (or added to vmbus) to match those?

I remember dealing with hardware vendors where this worked.
As long as they had the same motherboard and slots, it would get same naming on every boot.
Then they could ship one configuration in a consumer device (router etc).

This should be doable with VM's as well.

> 
> Otherwise, can you add more information (perhaps about resource groups, etc.) from the host side, that you then expose in sysfs, so you could achieve the consistent naming attributes above?
> 
> How can we make some progress here?
> 
> Cheers,
> Filipe
> 
>

**Comment by shemminger** [comment]
On Tue, 10 Apr 2018 17:20:29 +0000 (UTC)
Filipe Brandenburger <notifications@github.com> wrote:

> @shemminger 
> 
> > It is a requiremnt.  Distro's and cloudinit rely on the same name on every VM.
> > That is one of the reasons, it hasn't changed.  
> 
> But I think right now it's broken, names are kept at ethX assigned by kernel and on every boot they may come in a different order. At least that's what #8652 claims (but it's possible this was a bug in older kernels like 3.16 that was fixed since.)
> 
> But I believe when you're talking about cloudinit you're focusing on Azure, where I believe cloudinit is pushing some .link files to fix eth0, eth1, etc. by MAC address, correct?
> 
> > The key attributes of consistent naming are:
> > * same name on every boot
> > * same name on every VM
> > * same name when hotplugged  
> 
> Let me ask some rhetorical questions...
> 
> If these were legacy interfaces (PCI simulated), would you be able to achieve the consistent naming attributes above? If so, how? If that's possible, can similar attributes be found in vmbus (or added to vmbus) to match those?
> 
> Otherwise, can you add more information (perhaps about resource groups, etc.) from the host side, that you then expose in sysfs, so you could achieve the consistent naming attributes above?
> 
> How can we make some progress here?
> 
> Cheers,
> Filipe

If these were legacy interfaces, it would work only because the hypervisor
puts the devices at the same address. That is why KVM always gets ens4 by default.

It would be great to get a good stable solution to this. Relying on kernel and hypervisor
ordering is not a long term solution.

**Comment by filbranden** [comment]
> It would be great to get a good stable solution to this. Relying on kernel and hypervisor
ordering is not a long term solution.

Agreed, and the stability/consistency on the three vectors you described (every boot, every VM, hotplug) would be excellent.

But it seems nothing exported by the Hyper-V drivers on sysfs currently fits that model...

Can you propose something that will? (Or, if necessary, discuss this with Hyper-V developers, so that they can come up with a usable ID and then export that?)

Thanks!
Filipe

**Comment by shemminger** [comment]
On Thu, 12 Apr 2018 10:01:32 -0700
Filipe Brandenburger <notifications@github.com> wrote:

> > It would be great to get a good stable solution to this. Relying on kernel and hypervisor  
> ordering is not a long term solution.
> 
> Agreed, and the stability/consistency on the three vectors you described (every boot, every VM, hotplug) would be excellent.
> 
> But it seems nothing exported by the Hyper-V drivers on sysfs currently fits that model...
> 
> Can you propose something that will? (Or, if necessary, discuss this with Hyper-V developers, so that they can come up with a usable ID and then export that?)
> 
> Thanks!
> Filipe
> 
> 

I plan to discuss with the Hyper-V vswitch team to see what they recommend.

**Comment by filbranden** [comment]
Awesome, thanks @shemminger !

I'm happy to update this PR to do whatever you decide is best. (Or feel free to send one yourself, I can close this one.)

Cheers,
Filipe

**Comment by shemminger** [comment]
On Thu, 12 Apr 2018 17:12:53 +0000 (UTC)
Filipe Brandenburger <notifications@github.com> wrote:

> Awesome, thanks @shemminger !
> 
> I'm happy to update this PR to do whatever you decide is best. (Or feel free to send one yourself, I can close this one.)
> 
> Cheers,
> Filipe
> 
> 

If we could get the same information used for Windows consistent network naming
from host, it would be ideal.

https://www.altaro.com/hyper-v/device-naming-network-adapters/

It appears to be some RNDIS property, not sure where it is yet.

**Comment by shemminger** [comment]
On Thu, 12 Apr 2018 17:12:53 +0000 (UTC)
Filipe Brandenburger <notifications@github.com> wrote:

> Awesome, thanks @shemminger !
> 
> I'm happy to update this PR to do whatever you decide is best. (Or feel free to send one yourself, I can close this one.)
> 
> Cheers,
> Filipe
> 
> 

I did put this into kernel (in net-next), it doesn't solve the device naming issue you raised, but it helps
the human side.
   https://www.spinics.net/lists/netdev/msg496154.html

**Comment by filbranden** [comment]
Sounds good, thanks @shemminger .

Is that exported in sysfs somewhere? Will this already show up in udev?

**Comment by shemminger** [comment]
On Fri, 20 Apr 2018 11:04:09 -0700
Filipe Brandenburger <notifications@github.com> wrote:

> Sounds good, thanks @shemminger .
> 
> Is that exported in sysfs somewhere? Will this already show up in udev?
> 
> 

It is in /sys/class/net/ethN/ifalias

But it is a free form long string, which is useful for SNMP and maybe udev, but not as device name.

**Comment by shemminger** [comment]
On Fri, 20 Apr 2018 18:19:43 +0000 (UTC)
Filipe Brandenburger <notifications@github.com> wrote:

> > But it is a free form long string, which is useful for SNMP and maybe udev, but not as device name.  
> 
> Well, the host admins could still set it to something like `sv16g2` (like in the example from https://www.altaro.com/hyper-v/device-naming-network-adapters/ right?)
> 
> I mean, it might not be *always* what we want, but it might be sometimes what we want...
> 
> If you have other ideas of how to push something from the host, I think that's probably a good approach. As long as you can export that all the way to sysfs/udev, it shouldn't be hard to get this code here to do the automatic interface naming use it.
> 
> 

Usually the host admin sets something like: "Backbone network"

See: https://www.altaro.com/hyper-v/device-naming-network-adapters/
     https://www.petri.com/network-device-naming-windows-server-2016-hyper-v

Also not sure how this couldwork on Azure

**Comment by shemminger** [comment]
On Thu, 12 Apr 2018 17:12:53 +0000 (UTC)
Filipe Brandenburger <notifications@github.com> wrote:

> Awesome, thanks @shemminger !
> 
> I'm happy to update this PR to do whatever you decide is best. (Or feel free to send one yourself, I can close this one.)
> 
> Cheers,
> Filipe

I have not found an device id with the necessary properties.
There are several that act like MAC which is repeatable on reboot but none that behave like
PCI slot number (on VMBus).

**Comment by filbranden** [comment]
This PR has been stale and it's clear this is not the best approach (still unclear what would be the best approach here.)

In any case, I'll close the PR.

If we end up finding a better solution here, we can open a new one to implement it.

Cheers,
Filipe

**Pull request closed without merging**
