### PR TITLE
hwdb + syscall database updates for 249

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by bluca** [comment]
test_event timed out in semaphore - probably a fluke even though I don't remember seeing it before, re-triggered

**Review by bluca — APPROVED** [review]
LGTM (totally read the whole diff, pinky swear)

**Comment by keszybz** [comment]
LGTM.

> LGTM (totally read the whole diff, pinky swear)

In the hwdb changes, we only need to look at `hwdb.d/*.hwdb`. There should be mostly additions, and some cleanups and changes. A big removal of entries would mean that something went wrong somewhere.  The text and html source files are there as backup so we can figure out the history if the upstream sources ever go away.

**Comment by bluca** [comment]
> LGTM.
> 
> > LGTM (totally read the whole diff, pinky swear)
> 
> In the hwdb changes, we only need to look at `hwdb.d/*.hwdb`. There should be mostly additions, and some cleanups and changes. A big removal of entries would mean that something went wrong somewhere. The text and html source files are there as backup so we can figure out the history if the upstream sources ever go away.

Thanks for the clarification, how about:

```
--- a/docs/RELEASE.md
+++ b/docs/RELEASE.md
@@ -9,7 +9,7 @@ layout: default
 1. Add all items to NEWS
 2. Update the contributors list in NEWS (`meson compile -C build git-contrib`)
 3. Update the time and place in NEWS
-4. Update hwb (`meson compile -C build update-hwdb update-hwdb-autosuspend`)
+4. Update hwb (`meson compile -C build update-hwdb update-hwdb-autosuspend`) - should result in mostly additions, a big removal of entries should be a red flag to investigate manually.
 5. [RC1] Update version and library numbers in `meson.build`
 6. Check dbus docs with `meson compile -C build update-dbus-docs`
 7. Tag the release: `version=vXXX-rcY && git tag -s "${version}" -m "systemd ${version}"`
 ```

**Pull request merged**
