### PR TITLE
dhcp6: do not set T1 and T2 in IA_PD option or friends

### LINKED ISSUE #18090: DHCPv6 renew breaks IPv6 connectivity
**systemd version the issue has been seen with**
 > 246.6

**Used distribution**
 > NixOS

**Linux kernel version used** (`uname -a`)
 > Linux router 5.4.83 #1-NixOS SMP Fri Dec 11 12:23:33 UTC 2020 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > DHCPv6 IA_PD renews should work. 

**Unexpected behaviour you saw**
 > Upon the first renew 900s into the connection setup the first renew happens. The remote seems to terminate the lease after that and stops forwarding.

```
# journalctl -u systemd-networkd -e
[...]
router systemd-networkd[14117]: DHCPv6 CLIENT: Timeout T1
router systemd-networkd[14117]: DHCPv6 CLIENT: Sent RENEW
router systemd-networkd[14117]: DHCPv6 CLIENT: Next retransmission in 9s
router systemd-networkd[14117]: DHCPv6 CLIENT: Valid lifetieme of a PD prefix is zero or preferred lifetime 0 > valid lifetime 0
router systemd-networkd[14117]: DHCPv6 CLIENT: Computed IA PD T1 0s and T2 0s as both were zero
router systemd-networkd[14117]: DHCPv6 CLIENT: IA status No addresses available
router systemd-networkd[14117]: ppp0: DHCPv6 error: No message of desired type
[...]
```

**Steps to reproduce the problem**
 > Renew a DHCPv6 IA_PD lease against a Juniper platform.

Please see the pcap of a working renew (from dhcpcd) and the broken one (from networkd).

https://shells.darmstadt.ccc.de/~hexa/dhcpv6/dhcpv6-networkd.pcap
https://shells.darmstadt.ccc.de/~hexa/dhcpv6/dhcpv6-dhcpcd.pcap

The primary difference that I spotted was that dhcpcd set T1 and T2 to zero in the renew request, while networkd sets them to 900 (renew) and 1440 (rebind).

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #18090.

### CODE REVIEW

**Comment by bluca** [comment]
unit tests are failing and it looks related:

```
/* test_client_verify_request */
Assertion '!memcmp(optval + 4, &val, sizeof(val))' failed at src/libsystemd-network/test-dhcp6-client.c:654, function test_client_verify_request(). Aborting.
```

**Comment by yuwata** [comment]
Updated. One more commit is added to fix parsing received address or prefix. PTAL.

**Comment by keszybz** [comment]
bionic-i386: test-logind: "closing lid did not cause suspend"

**Comment by keszybz** [comment]
LGTM.

**Pull request merged**
