### PR TITLE
network: make route_update() accept NULL 

### LINKED ISSUE #8960: networkd: Assertion 'gw' failed at ../networkd-route.c:366, function route_update()
**systemd version the issue has been seen with**
> 238.76

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > systemd-networkd assigning IPs to all managed interfaces and adding routes and advertising IPv6 prefixes (static and delegated)
eno1 and eno2 are internal interfaces (dhcpd for IPv4 for clients), enp7s0f0 is internet facing and receives an IPv4 per DHCP and an IPv6 address and prefix per RA/DHCPv6
`ISP router (DHCPd) => enp7s0f0 (DHCPv4/6 client) this machine - Server for eno1/2 (ISC-DHCPDv4, RA per networkd prefix delegation) => LAN-clients`
On enp7s0f0 IPv6 address and routes are assigned, but IPv4 address and route aren't.

**Unexpected behaviour you saw**
> networkd is in failed state: systemctl --failed
  UNIT                                 LOAD   ACTIVE SUB    DESCRIPTION
● systemd-networkd-wait-online.service loaded failed failed Wait for Network to be Configured
● systemd-networkd.service             loaded failed failed Network Service
● systemd-networkd.socket              loaded failed failed Network Service Netlink Socket

> `Assertion 'gw' failed at ../systemd/src/network/networkd-route.c:366, function route_update(). Aborting.`

> Sorry, I haven't been successful in building with debug symbols, here's the backtrace anyway:
#0  0x00007ffff783486b in raise () from /usr/lib/libc.so.6
#1  0x00007ffff781f40e in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7475e5c in log_assert_failed_realm () from /usr/lib/systemd/libsystemd-shared-238.so
#3  0x000055555559c3ee in ?? ()
#4  0x00005555555a4b90 in ?? ()
#5  0x00007ffff7470c20 in ?? () from /usr/lib/systemd/libsystemd-shared-238.so
#6  0x00007ffff7470ebb in sd_event_dispatch () from /usr/lib/systemd/libsystemd-shared-238.so
#7  0x00007ffff74724a0 in sd_event_run () from /usr/lib/systemd/libsystemd-shared-238.so
#8  0x00007ffff74726ec in sd_event_loop () from /usr/lib/systemd/libsystemd-shared-238.so
#9  0x0000555555564081 in ?? ()
#10 0x00007ffff782106b in __libc_start_main () from /usr/lib/libc.so.6
#11 0x000055555556425a in ?? ()

> In systemd/src/network/networkd-dhcp6.c is called `route_update(route, &prefix, pd_prefix_len, NULL, NULL, 0, 0, RTN_UNREACHABLE);`
But in systemd/src/network/networkd-route.c route_update asserts gw and prefsrc (NULL)

**Steps to reproduce the problem**
> Start systemd-networkd.service (either with systemctl or manually)
Disabling enp7s0f0 let's systemd-networkd start up normally.

[journal-systemd-networkd.log](https://github.com/systemd/systemd/files/1992832/journal-systemd-networkd.log)
[eno1.network.txt](https://github.com/systemd/systemd/files/1992839/eno1.network.txt)
[enp7s0f0.network.txt](https://github.com/systemd/systemd/files/1992840/enp7s0f0.network.txt)

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #8960.

cc @ssahani

### CODE REVIEW

**Comment by yuwata** [comment]
@Just4GH Updated. But I have not tested this. Could you test this? Thank you.

**Comment by yuwata** [comment]
@Just4GH Updated. Please test this. Thank you.

**Comment by yuwata** [comment]
As reported in the issue page of #8960, @Just4GH has confirmed that this fixes the assertion failure.

**Comment by chauser123** [comment]
Thanks

**Pull request merged**
