### PR TITLE
build-sys: allow references to adm group to be omitted

### PR DESCRIPTION
**Pull request by fbuihuu**

### CODE REVIEW

**Comment by poettering** [comment]
I really don't like the proliferation of these configuration options like this one. But could you at least make sure that by default both groups are applied from a single tmpfiles line, as before?

**Comment by fbuihuu** [comment]
I don't know the m4 macros stuff but doing what you requested would uglify the systemd.conf.m4 file, no ?

BTW what's wrong to split it into two lines ?

**Comment by poettering** [comment]
I am pretty sure it's nor hard coming up with a nice way to make this not too ugly...

I think these configuration files really should be easy to grok for users, that's kind the primary goal here, and splitting these things up into two lines won't help users in that regard.

**Comment by fbuihuu** [comment]
> I am pretty sure it's nor hard coming up with a nice way to make this not too ugly...

I guess I could do something like:

if ENABLE_ADM && ENABLE_WHEEL; then
...
elif ENABLE_ADM
...
else // ENABLE_WHEEL
...
fi

is this what you're thinking of or am I missing something ?

**Comment by poettering** [comment]
sure, that would work.

**Comment by fbuihuu** [comment]
but it's ugly from a developer's point of view :)

Ok, let's put the burden on the maintainer side ;)

BTW isnt "sysusers.d/basic.conf.in" missing some ADM/WHEEL conditionals too ?

**Comment by poettering** [comment]
@fbuihuu sure, if you feel like it, add this for sysuers too.

**Comment by fbuihuu** [comment]
@poettering commit updated. Please double check, I'm really not confident with m4 thing.

**Comment by keszybz** [comment]
Yeah, it's not pretty. But it works. If both are disabled, there's an extra empty line. Meh.

**Pull request merged**
