### PR TITLE
journalctl: honour --output-fields= in -o cat mode

### PR DESCRIPTION
**Pull request by poettering**
A fix for #15621

### CODE REVIEW

**Comment by keszybz** [comment]
```console
$ build/journalctl --grep metadata -o cat --output-fields=MESSAGE,_TRANSPORT -n 1000
Assertion 'highlight[1] <= l' failed at src/shared/logs-show.c:1056, function output_cat_field(). Aborting.
```

**Comment by poettering** [comment]
pushed a new version with the assert fixed. ptal!

**Comment by evverx** [comment]
If [[nonull] had been on](https://github.com/systemd/systemd/pull/15704), it would have failed to compile with
```
../src/shared/logs-show.c:624:25: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
                        print_multiline(f, 4 + fieldlen + 1, 0, OUTPUT_FULL_WIDTH, 0, false,
                        ^
../src/shared/logs-show.c:161:24: note: callee declares array parameter as static here
                size_t highlight[static 2]) {
                       ^        ~~~~~~~~~~
../src/shared/logs-show.c:1239:21: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
                r = show_journal_entry(f, j, mode, n_columns, flags, NULL, NULL, ellipsized);
                    ^                                                      ~~~~
../src/shared/logs-show.c:1133:30: note: callee declares array parameter as static here
                const size_t highlight[static 2],
                             ^        ~~~~~~~~~~
2 warnings generated.
```

**Comment by keszybz** [comment]
travis failed with "too many requests" for github.com.
semaphore failed with "ERROR: Invalid signature for /tmp/tmp.43M9nvUlah/index.asc".
cifuzz failed, but "We are currently unable to download the log. Please try again later.".

**Comment by e3dio** [comment]
So was this reverted and never made it in? It's not working on Ubuntu 20.04, but is very important feature and needs to work. Website mentions this feature: https://www.freedesktop.org/software/systemd/man/journalctl.html#cat

But `man journalctl` and `journalctl -h` don't mention this feature

**Pull request merged**
