### PR TITLE
meson: bump minimum required version to 0.46

### PR DESCRIPTION
**Pull request by yuwata**
Also, this bumps the minimum required version of python to 3.5.

Below is the current meson version of each distribution.
\====================
Ubuntu artful (EOL date: July 2018): [0.42.1](https://packages.ubuntu.com/artful/meson)
Ubuntu bionic (EOL date: April 2023): [0.45.1](https://packages.ubuntu.com/bionic/meson)
Ubuntu cosmic: [0.46.0](https://packages.ubuntu.com/cosmic/meson)

Debian stretch-backports: [0.46.1](https://packages.debian.org/source/stretch-backports/meson)
Debian buster: [0.47.1](https://packages.debian.org/buster/meson)
Debian sid: [0.47.1](https://packages.debian.org/sid/meson)

Fedora 27,28,rawhide: [0.47.1](https://koji.fedoraproject.org/koji/packageinfo?packageID=19835)

RHEL 7 with EPEL (End of full support: Q4 of 2019): [0.47.1](https://koji.fedoraproject.org/koji/packageinfo?packageID=19835)

Arch: [0.47.1](https://www.archlinux.org/packages/extra/any/meson/)

openSUSE: [0.46.0](https://software.opensuse.org/package/meson)
\====================

python-3.5 support
\====================
Ubuntu artful: [3.6.3](https://packages.ubuntu.com/artful/python3)
Ubuntu bionic: [3.6.5](https://packages.ubuntu.com/bionic/python3)
Ubuntu cosmic: [3.6.5](https://packages.ubuntu.com/cosmic/python3)

Debian stretch: [3.5.3](https://packages.debian.org/source/stretch/python3.5)
Debian buster: [3.6.6](https://packages.debian.org/source/buster/python3.6)
Debian sid: [3.6.6](https://packages.debian.org/source/sid/python3.6)

Fedora 27,28,rawhide: [3.6.5](https://koji.fedoraproject.org/koji/packageinfo?packageID=9781)

RHEL7 with EPEL: [3.4.8](https://koji.fedoraproject.org/koji/packageinfo?packageID=20542), [3.6.3](https://koji.fedoraproject.org/koji/packageinfo?packageID=23597)

### CODE REVIEW

**Comment by keszybz** [comment]
Looks great. But I don't think we should merge this, as long as Ubuntu has not caught up. This is unfortunate, and I personally prefer to always run the latest versions, but toolchain version bumps like this are complex for our downstreams. So let's keep this around and wait.

**Comment by davide125** [comment]
This will make backporting systemd to CentOS 7 a lot harder, as meson 0.46 requires python 3.5, and EPEL only ships with 3.4 (there's 3.6 too but none of the modules are packaged for it afaik).

**Comment by yuwata** [comment]
I found that Ubuntu cosmetic (18.10) has 0.46.0.
Also, RHEL7 will be EOL at the end of this year.
So, I expect this will be merged in the next year.

**Comment by yuwata** [comment]
Note that python-3.5 is required since meson-0.45.0.
https://github.com/mesonbuild/meson/commit/0538009d30c02aba7f3b0e2fb22589c55fbe0fd0
So, I think we can merge some commits when we drop Ubuntu artful support.

**Comment by yuwata** [comment]
Also note that the recent snapshot of mesa requires meson-0.44.1.
https://cgit.freedesktop.org/mesa/mesa/tree/meson.build

**Comment by Conan-Kudo** [comment]
> Also, RHEL7 will be EOL at the end of this year.

Uh, no? RHEL 6 is EOL on November 2020. RHEL 7 is EOL June 2024.

**Comment by yuwata** [comment]
I mean EOL here for RHEL is 'end of full support'.

**Comment by yuwata** [comment]
meson-0.46.1 is available on EPEL7 testing repository.

**Comment by keszybz** [comment]
If EPEL7 is supported, the only thing that remains is artful, which is EOL now, and bionic, which will be supported so long that we can't wait for it. I'd be inclined to merge this now. meson-0.46 has a bunch of new features and it'd be nice to use them.

I changed our semaphoreci config to install 0.46.1, let's see if that works.

@mbiebl, @martinpitt, @xnox What's your opinion on this? Could we update the ubunut autopkgtests to use 0.46.1 so that we can see if CI passes?

**Comment by mbiebl** [comment]
I have no strong opinion from the Debian POV. As @yuwata already pointed out, we have a recent enough python version in stretch and meson via stretch-backports. So this would not be a blocker for us.
Concerning the CI, @martinpitt has a private repo where he could provide a newer meson version. So I don't think it would be a blocker for CI as well. Such an upload should happen first though.

**Comment by keszybz** [comment]
I also had to bump the "platform" to Ubuntu 16.04 and adjust the package installation. But it seems to work now.

@evverx could you check why LGTM fails?

**Comment by ignatenkobrain** [comment]
EPEL7 contains 0.47.1

**Comment by evverx** [comment]
@keszybz that particular build failed due to https://discuss.lgtm.com/t/lgtm-has-been-failing-to-get-packages-from-archive-ubuntu-com-since-yesterday/1112. I've just pressed the "retry analysis" button.

**Comment by evverx** [comment]
Judging by the build logs,
```sh
[2018-07-23 12:57:20] [build] Version: 0.45.1
[2018-07-23 12:57:20] [build] Source dir: /opt/src
[2018-07-23 12:57:20] [build] Build dir: /opt/src/build
[2018-07-23 12:57:20] [build] Build type: native build
[2018-07-23 12:57:20] [build] meson.build:3:0: ERROR: Meson version is 0.45.1 but project requires >= 0.46.
[2018-07-23 12:57:20] [build] A full log can be found at /opt/src/build/meson-logs/meson-log.txt
```
 `meson-0.46` doesn't seem to be available as a package, so we probably need to install `meson` via `pip3`. @samlanning could you recommend a way to do it? Would `lgtm.yaml` containing something like
```
extraction:
  cpp:
    prepare:
      packages:
        - pip3
    after_prepare:
      - pip3 install meson
```
suffice to get `meson` installed?

**Comment by chrisgavin** [comment]
Hi @evverx,

I believe this `lgtm.yml` file should get a new enough version of Meson installed and working for you.

```
extraction:
  cpp:
    prepare:
      packages:
        - python3-pip
        - python3-setuptools
        - python3-wheel
    after_prepare:
      - pip3 install meson
      - export PATH="$HOME/.local/bin/:$PATH"
```

Thanks,
Chris and the @lgtmhq team.

**Comment by evverx** [comment]
@chrisgavin thank you very much! `python3-pip` is much better than `pip3` I suggested :-) FWIW, at https://lgtm.com/help/lgtm/lgtm.yml-configuration-file#example-lgtm.yml-file I read that the file should be named `LGTM.yml`, but it probably doesn't matter.

@yuwata could you add it to the root directory to see how it goes?

**Comment by samlanning** [comment]
@evverx ah, that capitalization is a typo in the documentation, thanks for pointing that out, I'll have the docs team correct it. It does indeed need to be lower-case.

**Comment by yuwata** [comment]
@evverx I've added `.lgtm.yml`.

**Comment by evverx** [comment]
@yuwata thank you! The build is green as can be seen at https://lgtm.com/projects/g/systemd/systemd/logs/rev/pr-d3eafb57990972dc2ad7275ddc2470dfbb279340/lang:cpp/stage:Build%20merge%20(8a8d5cd).

**Comment by martinpitt** [comment]
I backported meson 0.47.1 to the [systemd CI PPA](https://launchpad.net/~pitti/+archive/ubuntu/systemd-semaphore/+packages) and restarted the tests.

**Comment by keszybz** [comment]
6 out of 7 and 1 stuck, let's merge.

**Comment by martinpitt** [comment]
@keszybz : I retried a few minutes ago due to failures in the upstream and boot-smoke tests. But indeed it's unlikely that this build system change triggered that.

**Comment by samlanning** [comment]
@evverx thanks for pointing out the capitalisation issue in our docs, they've been updated now.

**Pull request merged**
