### PR TITLE
journald: don't lose facility of log streams on journald restart

### PR DESCRIPTION
**Pull request by poettering**
Fixes: #19019

### CODE REVIEW

**Review by bluca — APPROVED** [review]
LGTM - is this a regression? ie, should we merge it in 248?

**Comment by yuwata** [comment]
LGTM.

**Comment by poettering** [comment]
A bug yes, not a regression. Might be something to merge before 248, but let's wait until we get positive test feedback, and it doesn#t really matter too much to hurry this too much.

**Comment by poettering** [comment]
OK, @fancy-rabbit responded over on #19019 and reported this as good. Let's merge.

**Pull request merged**
