### PR TITLE
udev: link_setup: do not set a general MAC address policy

### PR DESCRIPTION
**Pull request by tomty89**
as it does not make sense; see https://github.com/systemd/systemd/issues/3374#issuecomment-288882355
also see https://github.com/systemd/systemd/blob/v240/src/udev/net/link-config.c#L467

### CODE REVIEW

**Comment by poettering** [comment]
not sure i follow the logic. Can you elaborate?

I mean, this is intended to be used in particular for embedded devices that have no mac address in the eeprom (well, usually no eeprom at all), but ideally should still have stable mac addresses... with your patch all that goes down the drain? what am i missing?

**Comment by tomty89** [comment]
Well first of all, I wasn't really sure if there are physical devices that don't have MAC addresses. I don't have much experiences with different kinds of hardware.

I [asked](https://github.com/systemd/systemd/issues/3374#issuecomment-288882355) about the intention/purpose of this more than a year ago and I didn't get any response, and I keep seeing people complaining that "it's still broken" (and saying "your workaround works") from time to time, even after you said ["Bugs don't fix themselves"](https://github.com/systemd/systemd/issues/3374#issuecomment-314216250). So I just made the workaround a PR.

Luckily it seem to have caught some attention from @keszybz and he seem to have come up with a better approach (#11382).

I haven't take a deep look into it but as long as it can close #3374, it's fine by me (personally I don't concern much about the issue anymore).

But your comment did "brainstormed" me a bit, while you said:

> this is intended to be used in particular for embedded devices

The configuration itself doesn't exactly carry that "intention". Instead, as I've [said](https://github.com/systemd/systemd/issues/3374#issuecomment-288882355), it's something that simply gets applied to every network devices, regardless of their types or whether it is managed by networkd. So I would say that's what you were missing.

While #11382 probably "works" (as in, avoids the error), I am not sure if logically speaking, it's right / necessary to "Allow MACAddressPolicy=persistent for all virtual devices". Shouldn't whoever with "embedded devices that doesn't have MAC address" write a link file (with appropriate [Match]) for them, if they want to have persistent MAC addresses of them (or any of them)?

**Comment by keszybz** [comment]
> Shouldn't whoever with "embedded devices that don't have MAC addresses" write a link file (with appropriate [Match]) for them, if they want to have persistent MAC addresses for them (or any of them)?

We're trying to have defaults such that they work for as many cases as possible. Of course we could require people to investigate what devices they have and apply the necessary manual steps (that's what people did in the 90's), but if we can do better, we try to. In this particular case, we assume that a stable MAC is almost always wanted, hence we make this the default. At the same time, having a default that generates a warning for other people is bad. But the fix is make the code cover both cases, not to back out and require people to apply manual work-arounds.

**Comment by tomty89** [comment]
To me it isn't ever about whether "a stable MAC is almost always wanted" (or "stable vs random"), it's about whether we should even care.

It's just like we don't do a survey on whether most users do DHCP instead of static then decide whether we should ship a .network with DHCP=yes. The reason we don't ship that is not because we think "most people do not use DHCP", but "by default we do nothing, just configure it to what you desire".

What does not make sense to me is not "most people want stable MAC", but "we just ship a conf file that try to cover most people's need and blacklist whatever doesn't work with it in our code".

**Pull request closed without merging**
