### PR TITLE
Added Chuwi HiBook accelerometer into hwdb

### PR DESCRIPTION
**Pull request by Split7fire**
Tested on Fedora 27.

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

/cc @jwrdegoede just in case

**Comment by jwrdegoede** [comment]
Hi,

@keszybz thank you for the Cc. Normally I would say merging quirks like these is fine, but this one actually is a bit troublesome:

sensor:modalias:acpi:BOSC0200*:dmi:*svnDefaultstring:pnDefaultstring:*

Note the DefaultString for both sys_vendor and product_name, that us way to generic I've at least 2 different devices also matching this.

No need to revert, we should be able to fix this up with a follow up commit.

@Split7fire can you modify the rule to be less generic, do:

cat /sys/class/dmi/id/modalias

And look for non generic bits in there, or if everything is generic, just take the whole string and put it after the dmi: the whole string also contains the build-date and version of the BIOS, so it should be reasonably unique even if the separate bits are not.

Regards,

Hans

**Comment by Split7fire** [comment]
@jwrdegoede here is cat modalias:
`dmi:bvnAmericanMegatrendsInc.:bvr5.11:bd05/07/2016:svnDefaultstring:pnDefaultstring:pvrDefaultstring:rvnHampoo:rnCherryTrailCR:rvrDefaultstring:cvnDefaultstring:ct3:cvrDefaultstring:`

Any further suggestions about modifying quirk?

**Comment by jwrdegoede** [comment]
@Split7fire that is quite a generic dmi string, so lets just go for a match on the whole modalias, can you try changing the hwdb entry to this:

sensor:modalias:acpi:BOSC0200*:dmi:bvnAmericanMegatrendsInc.:bvr5.11:bd05/07/2016:svnDefaultstring:pnDefaultstring:pvrDefaultstring:rvnHampoo:rnCherryTrailCR:rvrDefaultstring:cvnDefaultstring:ct3:cvrDefaultstring:
  ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 1

And if that works submit a new pullreq with a commit making this change?

**Comment by jwrdegoede** [comment]
p.s.

The Point of View TAB-P800W entry has a comment above it like this, you probably want to add a similar comment to the modified Chuwi Hibook entry:

"# The Point of View TAB-P800W does not have its product name filled, so we"
"# match the entire dmi-alias, assuming that the use of a BMA250E +"
"# bios-version + bios-date combo is unique"

Note the "" should not be there in the 60-sensor.hwdb file, without them github turns the # signs into meaning that the text should be bold.

**Comment by Split7fire** [comment]
@jwrdegoede if you think it's worth adding such a comment - fine. I will add it. But I think that in that case hwdb file will be full of these "comments" in no time.

**Comment by keszybz** [comment]
> But I think that in that case hwdb file will be full of these "comments" in no time.

That's no problem.

**Comment by keszybz** [comment]
Fixup in #7473.

**Pull request merged**
