### PR TITLE
pid1: improve logging when we encounter a path that is too long to be converted into a mount unit name

### PR DESCRIPTION
**Pull request by poettering**
Prompted-by: #15221 #14294

### CODE REVIEW

**Comment by yuwata** [comment]
LGTM.

**Comment by rdxmb** [comment]
Hello,

on which systemd-version will this be released? 

I am using kubernetes in ubuntu 20.04 with `systemd 245 (245.4-4ubuntu3)` and I am getting hundreds of those warnings `Failed to set up mount unit: Invalid argument`. It would be interesting to which units they belong to ...

**Comment by keszybz** [comment]
@rdxmb if you follow the link to https://github.com/systemd/systemd/commit/fac729f811d37b8216aa33d67815d953f1190d63, you'll see that that commit is present in      v247-rc2 v247-rc1 v246 v246-rc2 v246-rc1 .

**Comment by rdxmb** [comment]
@keszybz I see, thanks!

**Pull request merged**
