### PR TITLE
tree-wide: remove unused functions

### PR DESCRIPTION
**Pull request by phomes**
These functions all look like dead code to me.

### CODE REVIEW

**Comment by keszybz** [comment]
mac_selinux_access_free, unit_add_dependency_by_name_inverse, unit_add_two_dependencies_by_name_inverse, unit_drop_in_file, unit_remove_drop_in, bus_match_to_string, bus_message_map_properties_changed, util_get_sys_core_link_value, util_resolve_sys_link  can go.

bus_type_is_valid_in_signature too, it was never used.

@teg What about tlv_packet_append_u32, tlv_packet_append_string, is there a plan to expose those as a public interace?

dns_question_is_superset, dns_question_contains, dns_question_is_equal — this part of the code is under development, maybe leave them for now?

**Comment by poettering** [comment]
`bus_match_to_string()` really should stay, as it is really useful for debugging. `bus_message_map_properties_changed()` should probably stay too, as we wanted to turn something like this into a proper sd-bus API too.

The others can go as far as I can think. @teg and @zonque might have an opinion on the network and resolving related calls though?

Otherwise, I'd probably just kill this, the git history will keep a copy of it anyway.

**Comment by ssahani** [comment]
@keszybz  These will be used when we do the TX part of the LLDP. Which is I am working on.

**Comment by keszybz** [comment]
@phomes Can you remove the removal of bus__, tlv__, dns_*? We can always nuke them later on.

**Pull request closed without merging**
