### PR TITLE
Udev warnings

### PR DESCRIPTION
**Pull request by keszybz**
Some patches that I wrote while debugging udevd.

### CODE REVIEW

**Comment by yuwata** [comment]
LGTM.

**Comment by MilhouseVH** [comment]
Given [99-vmware-scsi-udev.rules ](https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/udev/99-vmware-scsi-udev.rules) which is now generating the following `invalid substitution type` messages:
```
Sep 23 18:48:52 LibreELEC systemd-udevd[378]: /usr/lib/udev/rules.d/99-vmware-scsi-udev.rules:5 Invalid value "/bin/sh -c 'echo 180 >/sys$DEVPATH/device/timeout'" for RUN (char 27: invalid substitution type), ignoring, but please fix it.
Sep 23 18:48:52 LibreELEC systemd-udevd[378]: /usr/lib/udev/rules.d/99-vmware-scsi-udev.rules:6 Invalid value "/bin/sh -c 'echo 180 >/sys$DEVPATH/device/timeout'" for RUN (char 27: invalid substitution type), ignoring, but please fix it.
```
is it possible to explain how it should be fixed - what is wrong with the `$DEVPATH` usage?

**Comment by keszybz** [comment]
The problem is `$DEVPATH`. Something like this should work:
`"/bin/sh -c 'echo 180 >/sys$env{DEVPATH}/device/timeout'"

**Comment by MilhouseVH** [comment]
Thanks, that's certainly silenced the warnings - I'll send the suggestion upstream.

**Pull request merged**
