### PR TITLE
network: explicitly enable ipv6 if any ipv6 addresses are requested

### PR DESCRIPTION
**Pull request by yuwata**
We read the value and it is cached. The previous logic was simply broken.

~~Moreover, even if the configuration does not contain any IPv6 setting,
we should not set `disable_ipv6` sysctl value, as users may want to configure
IPv6 addresses after `networkd` initializes the link.~~

Replaces #13283 and #13382.

### CODE REVIEW

**Comment by ssahani** [comment]
Can you come up with a use case when precisely this is useful ? I think this is no use case at all.  you mean user does not know that it has IPv6 . This logic is completely broken .

**Comment by yuwata** [comment]
I do not oppose to control disable_ipv6 sysctl value, but oppose to silently modify the value, like currently we do. Maybe, adding `EnableIPv6=yes|no` or `IPv6Support=yes|no` is better when we want to control the sysctl value.

**Comment by ssahani** [comment]
No it does not modify silently is logs it out.  I think `EnableIPv6=yes|no` the settings of the interfaces leads the behaviour of sysctl.

**Comment by keszybz** [comment]
I don't like this patch. IIUC, we would ignore explicit configuration that enabled e.g. DHCP6, if the sysctl happens to have disabled value when systemd-networkd is started. This is very user unfriendly, because the failure to start DHCP6 and other IPv6 settings, e.g. after changing from a different network management mechanism, would be hard to diagnose. systemd-networkd might work fine after machine restart, but not when updating preexisting configuration.

I agree with @ssahani here: the configuration specified in .network file should determine the configuration of the network interface. We have interfaces which we don't manage, and we have interfaces that we manage, and we don't need a third state where we leave some of the settings on the interface unchanged.

> users may want to configure IPv6 addresses after networkd initializes the link.

That's OK. If users want to do this, they have to take care of setting the sysctl. That is what *we* do when adding IPv6 addresses, and that's what they would have to do to.

**Comment by yuwata** [comment]
My stand point of the current code is that the default value of the sysctl value is `0`, that is, ipv6 is enabled. That may need to be updated. But,,, why should we disable ipv6 when no IPv6 setting? Now is 2019, and ipv6 is not an exotic feature any more. I think writing `0` to the sysctl value is ok if .network file contains any IPv6 setting, but I do not agree to write `1` implicitly.

**Comment by keszybz** [comment]
> I think writing 0 to the sysctl value is ok if .network file contains any IPv6 setting, but I do not agree to write 1 implicitly.

Yes, that makes sense. We can update to code to write only write `0`.

**Comment by yuwata** [comment]
I will update this in that direction later.

**Comment by ssahani** [comment]
> > I think writing 0 to the sysctl value is ok if .network file contains any IPv6 setting, but I do not agree to write 1 implicitly.
> 
> Yes, that makes sense. We can update to code to write only write `0`.

There are still use cases where user disable IPv6 themselves since it's not supported by their application. Like they write to sysctl `1`. Since the user have not configured on that interface any IPV6.  networkd determines (current behaviour) and disables it . When the user needs and network figure that out it again enables its. So @keszybz Is right on this. We don;'t need a third state. That again might lead to misconfiguration.

**Comment by yuwata** [comment]
@keszybz and @ssahani Updated. PTAL.

**Comment by yuwata** [comment]
@keszybz I added a comment in the source, and added a testcase. I hope now the code is clear.

**Comment by keszybz** [comment]
Hmm, this still seems overly complex. The comment says
> /* This must be called before any call of link_sysctl_ipv6_enabled() */

This sounds like the code is structured wrong. If we know that we want ipv6, then we simply shouldn't look at the sysctl value, and just make sure to set the sysctl value at some point.

**Comment by yuwata** [comment]
OK. #13382 is better.

**Pull request closed without merging**
