### PR TITLE
repart: Re-open file descriptor to partition target after mkfs

### PR DESCRIPTION
**Pull request by daandemeyer**
The mkfs binary might unlink the path we give it and replace it with a new file so let's make sure that our fd points to any new file rather than the old deleted file.

Specifically this fixes erofs partition generation.

### CODE REVIEW

**Comment by poettering** [comment]
lgtm

**Comment by mrc0mmand** [comment]
Huh, the Ubuntu CIs fail with:

```
3932s [  487.068156] testsuite-04.sh[11099]: + systemd-cat echo yo
3932s [  487.070727] echo[11645]: yo
3932s [  487.071361] testsuite-04.sh[11099]: + journalctl --sync
3932s [  487.075624] testsuite-04.sh[11650]: ++ journalctl -o export -n 1
3932s [  487.077874] testsuite-04.sh[11652]: ++ cut -d= -f2
3932s [  487.078020] testsuite-04.sh[11651]: ++ grep -Ea '^__SEQNUM='
3932s [  487.078138] journalctl[11650]: Journal file /var/log/journal/8408624ccee5486fbdffc46873fbfcca/system.journal is truncated, ignoring file.
3932s [  487.078957] testsuite-04.sh[11099]: + SEQNUM2=118957
3932s [  487.079048] testsuite-04.sh[11099]: + test 118957 -gt 119261
3932s [  487.079284] testsuite-04.sh[48]: + echo 'Subtest /usr/lib/systemd/tests/testdata/units/testsuite-04.journal.sh failed'
3932s [  487.079284] testsuite-04.sh[48]: Subtest /usr/lib/systemd/tests/testdata/units/testsuite-04.journal.sh failed
3932s [  487.079438] testsuite-04.sh[48]: + return 1
3932s [  487.079438] testsuite-04.sh[48]: + journalctl --rotate --vacuum-size=20M
```

And they seem to fail this way only in this PR. But I have no idea how that could be related to this change...

**Comment by mrc0mmand** [comment]
@DaanDeMeyer could you do a force-push here to restart the CIs here, just in case?

**Comment by yuwata** [comment]
Ubuntu CI seems to be broken. Ignoring.

**Pull request merged**
