### PR TITLE
shutdown: Don't limit unmount attempts prematurely

### PR DESCRIPTION
**Pull request by medhefgo**
Once upon a time shutdown.c didn't have the logic to check whether any
unmount attempts succeeded or not. So instead it kept looping for
a fixed amount and hoped all was right. Nowadays, we do know if we
changed anything during a iteration and also stop looping then, but
we still limit ourselves to FINALIZE_ATTEMPTS.

But, theoretically, we could have such a complicated and nested
setup that would survive that limit, leaving stuff around we
might actually be able to unmount. Aand we could also end up in a
situation where the extra loop with raised unmount error level could
be skipped too.

So let's just drop the retries logic and rely fully on the changed
flag.

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

**Comment by poettering** [comment]
Hmm, somehow I get the feeling this will bite us one of those days, i.e. maybe something else that manipulates the mount table racing against us or so... I must say it feels much safer to have a strict boundary on loops like this, which are potentially unbounded in their runtime, if some unexpected condition happens...  I mean, it's fine bumping the max loop counter to something much higher, but dropping it entirely? I'd have stayed away from that...

**Comment by keszybz** [comment]
Dunno. Your call. We can revert this and just bump the limit to something higher.

**Comment by poettering** [comment]
dunno either, your call. I just have this feeling...

**Comment by keszybz** [comment]
Yeah. @medhefgo sorry, what about reverting this and just bumping the limit to 3000 or something? Any kind of hang in late boot is terrible, so it's better to have this extra safeguard in place.

**Comment by medhefgo** [comment]
Mmmh... how about only incrementing the counter if nothing changed?

**Comment by keszybz** [comment]
We are worried about the case where something *does* change, but we still spin endlessly.

**Comment by medhefgo** [comment]
Would be nice if there were a way to prevent any new mounts from happening I guess...

**Pull request merged**
