### PR TITLE
cryptsetup: unset an unlock path on each unlock retry

### PR DESCRIPTION
**Pull request by poettering**
cryptsetup: unset an unlock path on each unlock retry
    
If we couldn't unlock a device with the chosen unlock path, let's not fall back to the lowest one right away, but only flush out one path, and try the next.
    
Fixes: #30425
Follow-up-for: #30185
Alternative-to: #33183

### CODE REVIEW

**Comment by bluca** [comment]
Have you seen https://github.com/systemd/systemd/pull/33183 ?

**Comment by poettering** [comment]
> Have you seen #33183 ?

Yes, I have. That's what made me post this alternative ;-)

**Comment by bluca** [comment]
> > Have you seen #33183 ?
> 
> Yes, I have. That's what made me post this alternative ;-)

ok

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
> This doesn't work for me (on top of 255.7). In #33183, @bluca checks the password field too, here you aren't, is there a reason you omitted it?

Did you test #33183 as well by any chance? I did test it, and it did fix the issue as reported

**Comment by poettering** [comment]
I force pushed a new version which add some minor debug logging. Please retry this with debug logging on (i.e. systemd.log_level=debug on the kerne cmdline), and paste the relevant logs here.

**Comment by poettering** [comment]
(did you rebuild your initrd btw, after dropping in the patched systemd-cryptsetup?)

**Comment by SoapGentoo** [comment]
#33183 also didn't work for me (swap and root both encrypted with the same passphrase)

**Comment by bluca** [comment]
> #33183 also didn't work for me (swap and root both encrypted with the same passphrase) yes, always rebuilt the initrd

How do you configure your system? Including which distribution you are using

**Comment by SoapGentoo** [comment]
Still not working
Logs with debug (this is with the patch on top of 255.7 on Gentoo):
[kernel-log.txt.gz](https://github.com/user-attachments/files/15565298/kernel-log.txt.gz)

**Comment by SoapGentoo** [comment]
I can test with your branch, but you need to rebase it on `HEAD` to fix the compilation error from #33201

**Comment by bluca** [comment]
> I can test with your branch, but you need to rebase it on `HEAD` to fix the compilation error from #33201

updated

**Comment by SoapGentoo** [comment]
Nope, still broken: 
[kernel-log.txt.gz](https://github.com/user-attachments/files/15569727/kernel-log.txt.gz)

1. I first need to enter the passphrase for `root`
2. then the boot continues
3. and before `gdm` can start up, I am prompted again to enter the (same) passphrase as `root` for `swap`

**Comment by bluca** [comment]
@SoapGentoo please try the latest push, it fixes the issue for me

**Comment by SoapGentoo** [comment]
@bluca thanks a lot, yes, it works now with your latest push

**Comment by SoapGentoo** [comment]
@bluca I have now `systemd-cryptenroll`d both LUKS volumes with

    systemd-cryptenroll --tpm2-device=auto --tpm2-with-pin=true /dev/nvme0n1p2
    systemd-cryptenroll --tpm2-device=auto --tpm2-with-pin=true /dev/nvme0n1p3

with the same TPM2 pin, is it indeed for it to ask twice for the same PIN?

**Comment by poettering** [comment]
lgtm

**Pull request merged**
