### PR TITLE
Clean up various meson constructs

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by yuwata** [comment]
hm? what's the difference from #23383?

**Comment by keszybz** [comment]
It's only the first half of it.

**Comment by yuwata** [comment]
#23383 is the exactly same as this...

**Comment by yuwata** [comment]
Sorry, I did not mention that, but #23391 has all commits in #23383.

**Comment by bluca** [comment]
I think the confusion might be because there are 3 PRs?

this one
https://github.com/systemd/systemd/pull/23391
https://github.com/systemd/systemd/pull/23383

**Comment by keszybz** [comment]
Indeed.

**Pull request closed without merging**
