### PR TITLE
DEBUG: run CI with candidate btrfs fix

### PR DESCRIPTION
**Pull request by eworm-de**

### CODE REVIEW

**Comment by eworm-de** [comment]
BTW... The repository with files is still in place. Do we want to use that for now to unbreak CI?

**Comment by DaanDeMeyer** [comment]
> BTW... The repository with files is still in place. Do we want to use that for now to unbreak CI?

Can you backport the patch to the arch official kernel package?

**Comment by eworm-de** [comment]
The commit will be included as soon as it shows up in Linus' tree I guess.

**Comment by DaanDeMeyer** [comment]
We'll just wait for that then

**Comment by eworm-de** [comment]
Available in `linux-next` now...

[btrfs: improve the warning and error message for btrfs_remove_qgroup()](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=4eca32d8d9e69a396f09d599732b7b64ea683dc8)

**Pull request closed without merging**
