### PR TITLE
nspawn:  add support for --network-veth=foo:bar

### PR DESCRIPTION
**Pull request by ssahani**
This patch make veth name configurable
- make nspawn's --network-veth switch more powerful:  
  http://lists.freedesktop.org/archives/systemd-devel/2015-June/033121.html  
  I guess this is what we are looking for .

### CODE REVIEW

**Comment by ssahani** [comment]
How do we give multiple argument is it like --network-veth=aaa:bbb 123:456 789:999 or
--network-veth=aaa:bbb  --network-veth=123:456 -network-veth=789:999

**Comment by poettering** [comment]
@ssahani: the latter. You have to specify the argument name each time again.

**Comment by ssahani** [comment]
updated with WIP patch  thanks @poettering

**Comment by ssahani** [comment]
Updated . Sorry for the delay.

**Comment by ssahani** [comment]
closing to open a fresh #1678

**Pull request closed without merging**
