### PR TITLE
calendarspec UTC support

### PR DESCRIPTION
**Pull request by hvenev**
My daily 03:17 backup won't run on 2016-03-27 because I live in Eastern Europe and we don't have such a time here. Enough ranting about DST.

This would be solved easily if systemd timers supported UTC.

### CODE REVIEW

**Comment by hvenev** [comment]
It seems that semaphore has not reported that the build has finished.

**Comment by evverx** [comment]
@mustrumr , thanks. Can you update the [manpage](https://github.com/systemd/systemd/blob/master/man/systemd.time.xml#L120) too?

**Comment by poettering** [comment]
I wonder what happened to semaphore on this one, btw...

**Comment by hvenev** [comment]
So... What should +5days do with DST? "tomorrow UTC" sounds nice. I should rework the calendarspec patch to support this. Should I move `mktime_or_timegm` and `localtime_or_gmtime_r` to `src/basic/time-util.[ch]`?

**Comment by poettering** [comment]
"+5days" is currently read as 432000s from now according to CLOCK_REALTIME, hence it ignores any timezones, and I think that's a good idea.

"tomorrow UTC" probably makes sense to support, yes.

And I figure since we need the mktime_or_timegm() for parse_timestamp() too it should be moved to that file, yeah.

**Comment by hvenev** [comment]
"now UTC", "+/-n UTC" and "n ago/left UTC" don't make sense and parse_timestamp should return `-EINVAL`. Also, it annoyed me that "now" was about 500 ms ago so I implemented fraction support for `parse_timestamp`. Should I add that to calendarspec as well?

**Comment by hvenev** [comment]
Yay, it worked. `git rebase` can actually do miracles. Commit A adds lines x,y,z. Commit B removes x,y,z, adds u,v,w. `git rebase` moves B before A without complaining.

**Comment by poettering** [comment]
BTW, we generally prefer if you open a new PR for new versions of patchsets, and close the old one (rather than force push over the existing branch), so that we don't lose history on the PRs.

**Comment by hvenev** [comment]
goto #1569;

**Pull request closed without merging**
