### PR TITLE
Handle new capabilities gracefully

### PR DESCRIPTION
**Pull request by keszybz**
Updated version of #16420.

### CODE REVIEW

**Comment by keszybz** [comment]
bionic-amd64 failed in TEST-17-UDEV-WANTS, seems unrelated.

**Comment by flokli** [comment]
Can this be backported to 24{5,6}-stable?

**Comment by andersk** [comment]
@flokli This was already in master before 246-stable was branched. The 245-stable commit is systemd/systemd-stable@5325d280ab8468b981014c700d1d6cc1f01a3c02.

**Comment by flokli** [comment]
Okay, so it's fixed in 245.7. Thanks for the quick reply!

**Pull request merged**
