### PR TITLE
mkosi: fix UKI addons test 

### PR DESCRIPTION
**Pull request by mrc0mmand**
The test hasn't been working for a while, since there's no /efi or /boot
in $DESTDIR.

Resolves: https://github.com/systemd/systemd/issues/31618

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
CentOS Stream has `pesign` which ukify can also use to sign stuff, maybe that's an option?

**Comment by mrc0mmand** [comment]
> CentOS Stream has `pesign` which ukify can also use to sign stuff, maybe that's an option?

Currently ukify complains when you try to do that though:

```
$ ukify build --signtool=pesign --secureboot-private-key mkosi.key --secureboot-certificate mkosi.crt --cmdline this_should_be_here -o foo.addon.efi
Traceback (most recent call last):
  File "/usr/bin/ukify", line 1660, in <module>
    main()
  File "/usr/bin/ukify", line 1646, in main
    opts = parse_args()
           ^^^^^^^^^^^^
  File "/usr/bin/ukify", line 1641, in parse_args
    finalize_options(opts)
  File "/usr/bin/ukify", line 1609, in finalize_options
    raise ValueError(f'Cannot provide --signtool={opts.signtool} with --secureboot-private-key= and --secureboot-certificate=')
ValueError: Cannot provide --signtool=pesign with --secureboot-private-key= and --secureboot-certificate=

```

**Comment by mrc0mmand** [comment]
So, this seems now work as expected - a signed addon is properly loaded and an unsigned one is rejected. Not sure what to do about the CentOS Stream situation, though. ukify currently doesn't support signing with pesign, probably because it's more annoying, as it needs a PKCS#12 file in the pesign DB for signing, instead of just passing a PEM keypair.

**Comment by DaanDeMeyer** [comment]
In mkosi we have logic to convert the secure boot key and certificate to the format that's wanted by pesign but it seems like ukify doesn't do this transformation.

**Review by bluca — APPROVED** [review]
Thanks for fixing this - getting coverage on other OSes seems worth it even if CentOS needs more work, as it's unrelated to this feature

**Comment by keszybz** [comment]
This is nice.

**Pull request merged**
