### PR TITLE
move dns code from resolve to shared and use it for validating dhcp dns domain

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by poettering** [comment]
Generally looks good to me, modulo the dns_name_is_valid() issue I just commented on.

**Comment by poettering** [comment]
Please file a new PR with an updated patch. Thanks.

**Comment by mischief** [comment]
@mezcalero you want me to close this pr and make a new one with the revisions?

**Comment by poettering** [comment]
Yes, no force pushing of branches please, please create a new PR obsoleting this one instead.

**Pull request closed without merging**
