### PR TITLE
udev: path-id: fibre channel NPIV - use fc_vport's port_name

### PR DESCRIPTION
**Pull request by mfoliveira**
This patch merges the 2 proposals submitted upstream, addressing
some problems with both:
- #2500 (don't replace the fc_rport's port_name with fc_vport's)
- #2665 (don't add a fc_host/fc_vport's port_name if not needed)

With the patch, /dev/disk/by-path symlinks are created correctly,
and are unique, backward-compatible with the physical port case:
- physical port (no vport field)
- virtual ports (w/ vport field)

Symlinks:

```
# ls -l /dev/disk/by-path | grep 0001:09:00.0
<...> pci-0001:09:00.0-fc-0x500507680b2255fe-lun-0 -> ../../sdh
<...> pci-0001:09:00.0-fc-0x500507680b2255ff-lun-0 -> ../../sdi
<...> pci-0001:09:00.0-vport-0x5001a4aaf00a6785-fc-0x500507680b2255fe-lun-0 -> ../../sde
<...> pci-0001:09:00.0-vport-0x5001a4aaf00a6785-fc-0x500507680b2255ff-lun-0 -> ../../sdd
<...> pci-0001:09:00.0-vport-0x5001a4ad99d8c2de-fc-0x500507680b2255fe-lun-0 -> ../../sdc
<...> pci-0001:09:00.0-vport-0x5001a4ad99d8c2de-fc-0x500507680b2255ff-lun-0 -> ../../sdb
```

Accordingly w/ sysfs:

```
# ls -ld /sys/block/sd* | grep host1
<...> /sys/block/sdb -> ../devices/pci0001:00/<...>/0001:09:00.0/host1/vport-1:0-0/host3/rport-3:0-1/target3:0:0/3:0:0:0/block/sdb
<...> /sys/block/sdc -> ../devices/pci0001:00/<...>/0001:09:00.0/host1/vport-1:0-0/host3/rport-3:0-2/target3:0:1/3:0:1:0/block/sdc
<...> /sys/block/sdd -> ../devices/pci0001:00/<...>/0001:09:00.0/host1/vport-1:0-2/host5/rport-5:0-1/target5:0:0/5:0:0:0/block/sdd
<...> /sys/block/sde -> ../devices/pci0001:00/<...>/0001:09:00.0/host1/vport-1:0-2/host5/rport-5:0-2/target5:0:1/5:0:1:0/block/sde
<...> /sys/block/sdh -> ../devices/pci0001:00/<...>/0001:09:00.0/host1/rport-1:0-3/target1:0:0/1:0:0:0/block/sdh
<...> /sys/block/sdi -> ../devices/pci0001:00/<...>/0001:09:00.0/host1/rport-1:0-4/target1:0:1/1:0:1:0/block/sdi
```

The symlinks still include the fc_remote_port's (target) port_name:

```
# grep . /sys/class/fc_remote_ports/rport-{3:0-{1,2},5:0-{1,2},1:0-{3,4}}/port_name
/sys/class/fc_remote_ports/rport-3:0-1/port_name:0x500507680b2255ff
/sys/class/fc_remote_ports/rport-3:0-2/port_name:0x500507680b2255fe
/sys/class/fc_remote_ports/rport-5:0-1/port_name:0x500507680b2255ff
/sys/class/fc_remote_ports/rport-5:0-2/port_name:0x500507680b2255fe
/sys/class/fc_remote_ports/rport-1:0-3/port_name:0x500507680b2255fe
/sys/class/fc_remote_ports/rport-1:0-4/port_name:0x500507680b2255ff
```

And now include the fc_vport's (virtual host) port_name _if_ it's from a fc_vport:

```
# grep . /sys/class/fc_host/host1/port_name /sys/class/fc_vports/vport-1:0-{0,2}/port_name
/sys/class/fc_host/host1/port_name:0x10000090fa8f0ebc
/sys/class/fc_vports/vport-1:0-0/port_name:0x5001a4ad99d8c2de
/sys/class/fc_vports/vport-1:0-2/port_name:0x5001a4aaf00a6785
```

### CODE REVIEW

**Comment by mfoliveira** [comment]
@poettering I'm submitting this only for documentation purposes, I do realize per the previous discussions that this kind of change is not going to make upstream; sorry for the noise.

**Comment by mfoliveira** [comment]
@arvidjaar I believe this address your comment on #2665 (keep physical port case as is, and only change the vport case)

**Comment by maurizio-lombardi** [comment]
@mfoliveira You are right, this patch should be preferred over both #2665 and #2500

**Comment by mfoliveira** [comment]
@maurizio-lombardi cool, thanks for the review.

**Comment by poettering** [comment]
Closing, because this really should move into some other package. See #2665 and #2500 for more information

**Pull request closed without merging**
