### PR TITLE
id128: add --no-pager, --no-legend, --json=/-j switches to systemd-id128 tool

### PR DESCRIPTION
**Pull request by poettering**
Just filling some gaps, adding some options we exose on various other tools also on systemd-id128.

### CODE REVIEW

**Review by bluca — CHANGES_REQUESTED** [review]
Please add these to bash completion and basic usage in `test/units/testsuite-74.id128.sh` just to ensure sanitizers coverage

**Comment by poettering** [comment]
added, as requested. ptal

**Comment by bluca** [comment]
shell completion is still missing?

**Comment by poettering** [comment]
sorry, i am not the person to write shell completion stuff. don't make me. i never did.

**Comment by mrc0mmand** [comment]
I pushed a commit which updates at least bash completions.

> sorry, i am not the person to write shell completion stuff. don't make me. i never did.

I don't understand why, it has such a beautiful syntax!

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
> I pushed a commit which updates at least bash completions.

thanks!

> > sorry, i am not the person to write shell completion stuff. don't make me. i never did.
> 
> I don't understand why, it has such a beautiful syntax!

i think back in the day david zeuthen played around (or maybe even added to the gdbus tool) some infra so that shells could query the binary for proposed completions, so that the bash completion code was entirely generic and simple and the heavy lifting and information about parameters would be implemented in the tools themselves. i.e. only one source of truth, and always up-to-date completion.

I have the suspicion we should came up with a simple logic one day. i.e. have some infra that maintains tables of getopt switches and verbs and then uses that both to generate automatic --help texts as well as automatic shell completion. That would be super nice.

(does python have something like this?)

**Review by yuwata — APPROVED** [review]

**Pull request merged**
