### PR TITLE
networkd-test fix/improvement

### PR DESCRIPTION
**Pull request by martinpitt**
Found while debugging PR #11814

### CODE REVIEW

**Comment by martinpitt** [comment]
unit-config test fails due to PR #11827 , the rest passed now.

**Comment by martinpitt** [comment]
I added another commit that ignores the above issue for test runs in containers. I filed the details as issue #11848. It's better to run all the other networkd tests in containers than skipping this completely.

**Comment by martinpitt** [comment]
The boot-smoke test still keeps failing, even tough the `render` group does exist. So this is a real bug in udev somewhere. networkd tests succeeded, so this is ready for  review.

**Comment by yuwata** [comment]
Is it possible to retrieve the full log of boot-smoke test?

**Comment by martinpitt** [comment]
@yuwata: I can change the test to create an artifact with the journal, sure.

**Comment by martinpitt** [comment]
@yuwata : Done in  https://salsa.debian.org/systemd-team/systemd/commit/6a9a7ec2bf3fe1 . So we can take a closer look at the next test run that fails.

**Comment by yuwata** [comment]
Thank you!

**Pull request merged**
