### PR TITLE
Remove FOREACH_WORD_QUOTED

### PR DESCRIPTION
**Pull request by keszybz**
Post v232 material.

### CODE REVIEW

**Comment by martinpitt** [comment]
Seems this currently wreaks havoc (see test output), so marking as failure for now.

**Comment by poettering** [comment]
OH! This lis lovely! thanks for doing this! This has been long on the TODO list! Excellent work!

Patch looks good to me, but there is a chance of this breaking some unit files, hence doing this for post-v232 sounds like a good idea.

And yeah, there appear to be some CI failures on this too

**Comment by keszybz** [comment]
Updated. There was an error in the third patch.

**Comment by martinpitt** [comment]
LGTM too, and CI is happy now. Let's land this early in the 233 cycle so that this gets some field testing. Thanks!

**Comment by evverx** [comment]
54ac349445341503b1 introduced #4684

**Pull request merged**
