### PR TITLE
network, timesync, resolve: check bus is ready before emitting property change or signal

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by poettering** [comment]
hmm, this doesn't look right. the sd_bus_set_watch_bind() stuff should suffice.

The problem with ordering things after dbus.socket is that dbus.service is a late-boot service, thus you make all these services semi-late-boot too.

**Comment by poettering** [comment]
the rhbz thing suggests a permission problem, given the error. I'd like to understand that... maybe some selinux problem?

**Comment by yuwata** [comment]
Hm, indeed... The commit adds `After=` and `Wants=dbus.socket` is dropped.

**Comment by poettering** [comment]
Hmm, so this looks OK, but this is mostly about reducing irritating debug output, right? i mean, control flow isn't actually changed that much: before the signal emission would fail and we'd go on and now we skip the signal submisson. Did I get this right?

**Pull request merged**
