### PR TITLE
Revert hostname-setup leave the terminator byte alone

### PR DESCRIPTION
**Pull request by syyhao1994**
https://github.com/systemd/systemd/issues/20309

### CODE REVIEW

**Comment by poettering** [comment]
I don't follow? Are you saying HOST_NAME_MAX  is wrong?

**Comment by poettering** [comment]
Note that this only touches a single call of gethostname() even though we have plenty like this. 

Anyway, please explain.

**Comment by syyhao1994** [comment]
> Note that this only touches a single call of gethostname() even though we have plenty like this.
> 
> Anyway, please explain.

I am not mean HOST_NAME_MAX is wrong. I made a test as i supposed HOST_NAME_MAX is 64. So the **char buf[HOST_NAME_MAX + 1]** is same as **char buf[65]**. I can only get the 64 7-bit ASCII lower-case alphanumeric characters hostname with  **gethostname(buf, sizeof(buf)(which is equal 65))** rather than **gethostname(buf, sizeof(buf) - 1(which is equal 64))** that introduced in commit https://github.com/systemd/systemd/commit/39ede7cc377dcb057411c80509e5fde8901f20fb.
So i think we should revert that commit.
I grep the code that there are only two places use the syscall gethostname.
@keszybz Could you please take a look at this commit to make sure if we need to revert your modification?

**Comment by poettering** [comment]
A more comprehensive fix was now merged in #20418, closing.

**Pull request closed without merging**
