### PR TITLE
Revert "logind: become the controlling terminal process before restor…

### LINKED ISSUE #11269: Since v240, exiting sway (wayland compositor) closes the logind session
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > arch linux + [sway](https://github.com/swaywm/sway) from master

**Expected behaviour you didn't see**
 > sway is a lightweight wayland compositor. I start it from a tty. When I exit the compositor I expect it goes back to the tty, without closing my current logind session. That was the behaviour on systemd 239

**Unexpected behaviour you saw**
 > When closing sway, logind decides to close my user session.

**Steps to reproduce the problem**
Start and exit sway (or maybe any other wayland compositor) from a tty.

Here is a piece of logind logs:

> Dec 25 11:50:23 riemann systemd-logind[31666]: Sent message type=method_return sender=n/a destination=:1.284 path=n/a interface=n/a member=n/a cookie=127 reply_cookie=56 signature=n/a error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd-logind[31666]: Got message type=method_call sender=:1.284 destination=org.freedesktop.login1 path=/org/freedesktop/login1/session/_315 interface=org.freedesktop.login1.Session member=ReleaseControl cookie=57 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd-logind[31666]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=128 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd-logind[31666]: Successfully forked off '(logind)' as PID 32180.
Dec 25 11:50:23 riemann [32180]: PR_SET_MM_ARG_START failed, attempting PR_SET_MM_ARG_END hack: Operation not permitted
Dec 25 11:50:23 riemann [32180]: PR_SET_MM_ARG_END hack failed, proceeding without: Operation not permitted
Dec 25 11:50:23 riemann systemd-logind[31666]: (logind) succeeded.
Dec 25 11:50:23 riemann systemd-logind[31666]: Sent message type=method_return sender=n/a destination=:1.284 path=n/a interface=n/a member=n/a cookie=129 reply_cookie=57 signature=n/a error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann login[31692]: pam_unix(login:session): session closed for user abdo
Dec 25 11:50:23 riemann systemd-logind[31666]: Got message type=method_call sender=:1.286 destination=org.freedesktop.login1 path=/org/freedesktop/login1 interface=org.freedesktop.login1.Manager member=ReleaseSession cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd-logind[31666]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=130 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd-logind[31666]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.280 path=n/a interface=n/a member=n/a cookie=15 reply_cookie=130 signature=u error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd-logind[31666]: Sent message type=method_return sender=n/a destination=:1.286 path=n/a interface=n/a member=n/a cookie=131 reply_cookie=2 signature=n/a error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann login[31692]: pam_succeed_if(login:session): requirement "uid = 1000" was met by user "abdo"
Dec 25 11:50:23 riemann systemd-logind[31666]: Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/session_2d15_2escope interface=org.freedesktop.systemd1.Scope member=Abandon cookie=132 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd[1]: getty@tty2.service: Succeeded.
Dec 25 11:50:23 riemann audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=getty@tty2 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 25 11:50:23 riemann systemd[1]: getty@tty2.service: Consumed 24ms CPU time, no IP traffic.
Dec 25 11:50:23 riemann systemd[1]: session-15.scope: Succeeded.
Dec 25 11:50:23 riemann systemd[1]: session-15.scope: Consumed 2.242s CPU time, no IP traffic.
Dec 25 11:50:23 riemann systemd[1]: getty@tty2.service: Service has no hold-off time (RestartSec=0), scheduling restart.
Dec 25 11:50:23 riemann systemd[1]: getty@tty2.service: Scheduled restart job, restart counter is at 10.
Dec 25 11:50:23 riemann systemd[1]: Stopped Getty on tty2.

The logind forking piece suggests that @fbuihuu commit  ad96887a1205bad9656d280c5681f482e6d04838 might have something to do with it.

### PR DESCRIPTION
**Pull request by fbuihuu**
…ing VT"

This reverts commit ad96887a1205bad9656d280c5681f482e6d04838.

Commit adb8688 alone should be enough to fix issue #9754.

Fixes #11269

### CODE REVIEW

**Comment by keszybz** [comment]
Thanks.

**Comment by keszybz** [comment]
```
Jan 10 12:37:55 autopkgtest systemd-udevd[1265]: Failed to resolve group 'render': Connection timed out
Jan 10 12:38:20 autopkgtest systemd-udevd[1265]: Failed to resolve group 'render': Connection timed out
```
```
Jan 10 13:54:13 autopkgtest systemd-udevd[248]: Error resolving group 'render': Connection timed out
Jan 10 13:54:38 autopkgtest systemd-udevd[248]: Error resolving group 'render': Connection timed out
```

**Comment by fbuihuu** [comment]
Hmm I don't see how this could be related.

**Comment by keszybz** [comment]
Yeah, let's merge.

**Pull request merged**
