### PR TITLE
networkd: create "kernel" setting for IPForwarding

### PR DESCRIPTION
**Pull request by mischief**
In 5a8bcb674f71a20e95df55319b34c556638378ce, IPForwarding was introduced
to set forwarding flags on interfaces in .network files. networkd sets
forwarding options regardless of the previous setting, even if it was
set by e.g. sysctl. This commit creates a new option for IPForwarding,
"kernel", that preserves the sysctl settings rather than always setting
them. It also introduces a compile-time option to set the default value
of IPForwarding to "kernel" instead of "no".

See https://bugs.freedesktop.org/show_bug.cgi?id=89509 for the initial
bug report.

### CODE REVIEW

**Comment by mischief** [comment]
if the compile-time flag and the ifdef is not desireable, we can probably maintain it as a seperate patch.

**Comment by mischief** [comment]
@teg woops, forgot about the manual.

**Comment by mischief** [comment]
@teg ok. ill rework this change so it just adds `IPForward=kernel`.

**Comment by mischief** [comment]
hi @teg, PTAL

**Comment by marineam** [comment]
Looks good :)

**Comment by poettering** [comment]
I am not sure I like the commit that was pushed. So far the enum was kind of a bit field. Where bit 0 was ipv4, bit 1 was ipv6, both on were "yes", and both off were "no".

But now it's really something where the _value_ "4" is special... I am pretty sure it should at least be the _mask_ 4 however that should be checked for. i.e. instead of this:

if (link->network->ip_forward == ADDRESS_FAMILY_KERNEL)

we should check:

if (link->network->ip_forward & ADDRESS_FAMILY_KERNEL)

That all said, I am pretty sure there should _not_ be any enum for this thing at all. Instead we should use value _ADDRESS_FAMILY_INVALID for this, and have a parser function that maps "kernel" to _ADDRESS_FAMILY_INVALID that is used for the forwarder settings.

Moreovever, the AddressFamilyBoolean is used in other places too, for example for the DHCP logic. The way you changed AddressFamilyBoolean you now accept the "kernel" setting for that too. But what is that supposed to mean?

This patch hence should be reverted and be redone.

**Comment by marineam** [comment]
@mezcalero we noted that it was used as both an enum value (the ip_forward case) and the a bit field (the DHCP case). So the code was already quite confusing on what the nature of the value was and went with it as-is, intending to follow up with some cleanup that split the two use cases into two different data types.

**Comment by poettering** [comment]
@marineam I have now posted PR #113 that makes sure we always use it as the mask that it is.

**Comment by mischief** [comment]
@mezcalero i can't see how it's possible to use `_ADDRESS_FAMILY_BOOLEAN_INVALID` as `kernel`. `DEFINE_CONFIG_PARSE_ENUM` will fail if the `*from_string` function returns <0, and `_ADDRESS_FAMILY_BOOLEAN_INVALID` is -1.

**Comment by poettering** [comment]
Don#t modify the xyz_from_string() or xyz_to_string() stuff at all. Simply add a new call config_parse_address_family_boolean_with_kernel() that checks if the rvalue is "kernel". If so, then it sets the variable to _ADDRESS_FAMILY_BOOLEAN_INVALID, but otherwise it just calls the normal config_parse_address_family_boolean(). That we we have to parsing routines for address family stuff: one that understands the special "kernel" value, and maps it to _A_F_B_I, the other that does not understand it. The former we use for the ip forwarding settings, the latter for the dhcp settings as we already do.

**Comment by poettering** [comment]
Locking this one now, please move all further discussions about the general concepts to #109.

**Pull request merged**
