### PR TITLE
more v236 news improvements

### PR DESCRIPTION
**Pull request by poettering**
Let's get this thing released.

### CODE REVIEW

**Comment by keszybz** [comment]
All good, but I guess we shouldn't merge this until right before the release. I'll look at other PRs first.

**Comment by poettering** [comment]
i think it should be ok to merge this now, i figure we need to go through more revisions regarding NEWS anyway (since more stuff got merged in the meantime that is relevant to mentioned, and i figure we'll have one or two more things too), and i'd rather see these NEWS additions added as PR on top, then updating this PR...

**Comment by keszybz** [comment]
Yeah, but the version numbers? If something unexpected turns up and we don't release quickly, this will be confusing. I'll just merge the first three commits for now, and then the last commit can go in later when the release is actually imminent.

**Comment by poettering** [comment]
force pushed a new, rebased version, that adds one more NEWS item and prepares things for a release tomorrow.

**Comment by keszybz** [comment]
LGTM.

**Pull request merged**
