### PR TITLE
test: test journalctl with corrupted journals

### PR DESCRIPTION
**Pull request by mrc0mmand**
Last month I monkey-patched journald to produce a small (64K) but valid
journal and used that as an input to four AFL fuzzers. After a month it
generated quite a nice corpora (4738 test cases) and after filtering
and minimizing it I was left with 619 unique journals with various
levels of corruption that probe the journal code.

It seems to detect past issues like systemd/systemd#26567, etc.

### CODE REVIEW

**Comment by bluca** [comment]
Just to double check, is the zstd compressed with the maximum compression?

**Comment by bluca** [comment]
Not for this pr, but we should think about moving these binary test assets to LFS, as we'll keep adding them forever and increasing the repo size forever

**Comment by mrc0mmand** [comment]
> Just to double check, is the zstd compressed with the maximum compression?

Now it should be compressed with `-19`.

**Review by bluca — APPROVED** [review]
75 KB savings, nice :-)

**Comment by mrc0mmand** [comment]
Dropping the green label until #27459 is resolved.

**Comment by yuwata** [comment]
@mrc0mmand Fix for #27459 is pushed. PTAL.

**Review by yuwata — APPROVED** [review]
The test part by @mrc0mmand LGTM.

**Comment by evverx** [comment]
>  I was left with 619 unique journals with various levels of corruption that probe the journal code

I wonder if it would make sense to create a separate job building `journaltcl` with `AFL` and fuzz `journalctl` for a couple of minutes. This way this test would more likely reach code introduced/changed in PRs. Some changes can somewhat invalidate the corpus but assuming this code doesn't change drastically it should more or less work.

**Comment by evverx** [comment]
On second thought I'd just wait for https://github.com/google/oss-fuzz/issues/8818 to be able to run this stuff continuously and update the corpus on the OSS-Fuzz side. Until then I think this PR should more or less cover journaltcl (but I'd keep an eye on its coverage though :-))

**Comment by mrc0mmand** [comment]
> On second thought I'd just wait for [google/oss-fuzz#8818](https://github.com/google/oss-fuzz/issues/8818) to be able to run this stuff continuously and update the corpus on the OSS-Fuzz side. Until then I think this PR should more or less cover journaltcl (but I'd keep an eye on its coverage though :-))

I've already restarted the fuzzers with the new corpora, but this time without sanitizers to speed things up and cover as much code as possible (without sanitizers it's ~10x faster). I'll give it another month or so and then update the corpora tarball again.

**Comment by evverx** [comment]
> I've already restarted the fuzzers with the new corpora

I think if they are run in the cloud somewhere it should be possible to keep the corpus there and download it when the test is run. Apart from keeping the test up-to-date automagically it can save some space in the repository. One downside would be that the test wouldn't be reproducible though. Anyway as long as it gets updated from time to time it should be fine I think.

**Comment by evverx** [comment]
For the record this test covers https://github.com/systemd/systemd/issues/26822 too.

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by DaanDeMeyer** [comment]
The journal fixes by @yuwata LGTM

**Comment by mrc0mmand** [comment]
Just updated the tarball with the journal from #27470.

**Comment by yuwata** [comment]
I will submit some of them if they are necessary and possible.

**Comment by keszybz** [comment]
@yuwata please either submit a backport or clear the label.

**Comment by yuwata** [comment]
Sorry for late response. Clearing the label. Let's backport some of them only when requested.

**Pull request merged**
