### PR TITLE
nspawn: support custom container service name

### PR DESCRIPTION
**Pull request by iaguis**
We were hardcoding "systemd-nspawn" as the value of the $container env
variable and "nspawn" as the service string in machined registration.

This commit allows the user to configure it by setting the $container
env variable when calling systemd-nspawn.

If $container is not set, we use the string "systemd-nspawn" for both,
fixing the previous inconsistency.

Also, add rkt to detect-virt.

### CODE REVIEW

**Comment by evverx** [comment]
Why are you using an environment variable? I think, `SYSTEMD_NSPAWN_CONTAINER` looks better.
Maybe, a command line option instead of an environment variable?

**Comment by evverx** [comment]
I mean, `container` is the `PID1`'s thing:

> To allow systemd (and other code) to identify that it is executed within a container, please set the $container= environment variable for PID 1 in the container to a short lowercase string identifying your implementation.

I think, we shouldn't break a user environment with this new var. I've found `export container=some-path` in the`~/.bashrc`

**Comment by iaguis** [comment]
Since this is not an option that should be exposed to the user, I don't think a command line option makes sense.

Regarding `container` vs. `SYSTEMD_NSPAWN_CONTAINER`, I thought it made sense to use the same var that `PID1` is expecting. But you're right, `container` is a very common word and it might be better to choose something like `SYSTEMD_NSPAWN_CONTAINER` while still using `container` for the container environment.

**Comment by evverx** [comment]
> Since this is not an option that should be exposed to the user, I don't think a command line option makes sense.

I agree.

Looks like all magic variables have all-caps-long-length format. For example [`SYSTEMCTL_INSTALL_CLIENT_SIDE`](https://github.com/systemd/systemd/commit/b41b9d2ae9d1139a3d4d5eb7a)

**Comment by iaguis** [comment]
I'm leaning toward `CONTAINER_SERVICE_NAME`. Or maybe we need to namespace it with `NSPAWN` or `SYSTEMD_NSPAWN`?

**Comment by poettering** [comment]
patch looks good me now, but I see @evverx's point in that people might use `$container` for other purposes... hence yeah, let's better namespace the var and call it $SYSTEMD_NSPAWN_CONTAINER_SERVICE= or so?

**Comment by poettering** [comment]
And yes, I agree with @iaguis: this is really not a user setting and hence shouldn't get a command line switch. I think we should be careful to only expose user-facing switches on the command line, and look for other ways of exposing options when it's supposed to be an API facing towards other software, not user. An env var can be a good candidate for that.

**Comment by iaguis** [comment]
v3: https://github.com/systemd/systemd/pull/1817

**Pull request closed without merging**
