### PR TITLE
macro: fix ALIGN_TO() to use ULLONG_MAX instead of ULONGLONG_MAX

### PR DESCRIPTION
**Pull request by thom311**
`<limits.h>` calls this `ULLONG_MAX`. It's not clear to me where `ULONGLONG_MAX`
can be found. This seems to be just a mistake.

Fixes: c7ed7187203c ('macro: handle overflow in ALIGN_TO() somewhat reasonably')

### CODE REVIEW

**Comment by medhefgo** [comment]
Can't we just get rid of the #ifdefs and call the ll variant, relying on integer promotion? I doubt align_to needs that kind of micro-optimization and I would be surprised if the compiler cannot optimize this ([Compiler Explorer would suggest so](https://godbolt.org/z/9sYejPrxY)).

**Comment by poettering** [comment]
Or well, maybe not. The code for popcountl + popcountll are identical. which isn't too surprising given that on x86-64 long == long long.

But the code for popcount actually is different slightly compared to the two others.

If you switch to llvm the difference is even starker.

**Comment by medhefgo** [comment]
There's another way by using __builtin_types_compatible_p. Would have the benefit of always syntax checking the branches not taken. And the assert seems to be optimized away too: https://godbolt.org/z/K84bG18nj

**Comment by medhefgo** [comment]
> But the code for popcount actually is different slightly compared to the two others.

This testcase seems more correct: https://godbolt.org/z/z1Ma5nfqs
Here the cases where there is uint promotion emit the same code.

**Comment by keszybz** [comment]
Let's merge the current patch. The other proposed variants would be nice, but the current form should be "good enough".

**Pull request merged**
