### PR TITLE
tree-wide: adjust fall through comments so that gcc is happy

### PR DESCRIPTION
**Pull request by shawnl**
Distcc and ccache remove comments, making the comment silencing
not work. gperf is still loud when using distcc, but that is seperate.

I know there was a decision against a macro in commit
ec251fe7d5bc24b5d38b0853bc5969f3a0ba06e2

### CODE REVIEW

**Comment by keszybz** [comment]
I'm not against the patch, but I don't think the statement in the commit message is correct. I have gcc-7.2.1-2.fc27.x86_64 and ccache, and I don't get the warnings. I removed some of the "fall through" comments for testing, and then I get the warning (*). So at least ccache doesn't seem to interfere with them. Not sure about distcc. So maybe there's a different reason why you're seeing the warnings?

(*) Only after I add -Wimplicit-fallthrough=3 to $CFLAGS. It seems gcc removed this warning from -Wextra some time between ec251fe and now. We should add it to the list of warnings we request, but that's a separate issue.

**Comment by poettering** [comment]
patch makes sense to me. To be frank this gcc idea of parsing comments I find a really really strange idea anyway... doing this explicitly appears much preferable to me. 

Hmm, maybe we should switch to `-Wimplicit-fallthrough=5` along with this patch btw? Otherwise this is likely to regress again, and I think the explicit fall through logic is prefereably anyway?

**Comment by keszybz** [comment]
I tried that, and I don't think we're ready for that yet:

gperf generates switch statements with `/*FALLTHROUGH*/`:
```
[337/1831] Compiling C object 'src/shared/systemd-shared-235@sha/.._basic_af-list.c.o'.
In file included from ../src/basic/af-list.c:29:0:
src/basic/af-from-name.gperf: In function ‘hash_af_name’:
src/basic/af-from-name.gperf:95:14: warning: this statement may fall through [-Wimplicit-fallthrough=]
src/basic/af-from-name.gperf:97:7: note: here
src/basic/af-from-name.gperf:99:14: warning: this statement may fall through [-Wimplicit-fallthrough=]
src/basic/af-from-name.gperf:101:7: note: here
```

What's more interesting, doing that finds a place this PR missed:
```
../src/shared/machine-image.c: In function ‘image_remove’:
../src/shared/machine-image.c:513:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
                 if (path_startswith(i->path, "/dev"))
                    ^
../src/shared/machine-image.c:518:9: note: here
         case IMAGE_RAW:
         ^~~~
```

FTR, my patch is at https://github.com/keszybz/systemd/tree/pr/7389, but like I said, I don't think we should merge it until gperf is fixed.

**Comment by poettering** [comment]
i figure we could place the same gcc `_Pragma` stuff the murmurhash code got into the relevant gperf headers?

i.e. make sure the `%{` … `}%` bits in all `*.gperf` files should carry:
```c
%{
…
#if __GNUC__ >= 7
_Pragma("GCC diagnostic ignored \"-Wimplicit-fallthrough\"")
#endif
}%
```

**Comment by shawnl** [comment]
I made a style decision here to always put the null statement right above the label that is being fallen into.

**Comment by poettering** [comment]
Ah, I didn't notice that @keszybz opined against the macro last time. @keszybz what's your opinion now? do you still prefer the comment? to me it appears wrong to make the compiler parse comments...

**Comment by poettering** [comment]
@shawnl your patch does not bump -Wimplicit-fallthrough thing to 5 yet, or did I miss something? Given that you added the gperf glue this should work fine now, right? why not add it right-away in the same commit?

**Comment by keszybz** [comment]
I'm fine with the macro.  (I thought it's not worth the effort, but if somebody else did the work... ;))

**Comment by keszybz** [comment]
I pushed my old patch to bump to '5' on top.

**Comment by poettering** [comment]
lgtm

**Comment by evverx** [comment]
I can see a lot of warnings in https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20171122_065417_13c8a@/log.gz which look like the following:
```
'src/basic/basic@sta/siphash24.c.o' -c ../src/basic/siphash24.c
../src/basic/siphash24.c: In function ‘siphash24_compress’:
../src/basic/siphash24.c:130:25: warning: empty declaration
                         _fallthrough_;
                         ^
In file included from ../src/basic/siphash24.c:22:0:
../src/basic/macro.h:51:23: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define _fallthrough_ __attribute__((fallthrough))
                       ^
../src/basic/siphash24.c:130:25: note: in expansion of macro ‘_fallthrough_’
                         _fallthrough_;
                         ^
../src/basic/siphash24.c:133:25: warning: empty declaration
                         _fallthrough_;
                         ^
In file included from ../src/basic/siphash24.c:22:0:
../src/basic/macro.h:51:23: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define _fallthrough_ __attribute__((fallthrough))
                       ^
```
They can be silenced by reverting 4831981d89c62860, but I was wondering if there was another way to fix it.

**Comment by shawnl** [comment]
what version of gcc  are you using?

**Comment by evverx** [comment]
That was `gcc-5 amd64 5.4.0-6ubuntu1~16.04.5`.

By the way, all the information can be found in https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20171122_065417_13c8a@/log.gz.

**Comment by shawnl** [comment]
@evverx Sorry on asking for information I could get myself. You were clear.

**Comment by evverx** [comment]
@shawnl, no problem at all. I've just seen https://github.com/systemd/systemd/pull/7448 and it seems that those warnings should be gone. Thank you for fixing this.

**Comment by poettering** [comment]
> They can be silenced by reverting 4831981, but I was wondering if there was another way to fix it.

As I understand gcc complains about a stand-alone `;` with nothing before it, right? If so, maybe go the way we do for other macros too, and just declare a useless struct as part of the macro. Grep for `__useless_struct_to_allow_trailing_semicolon__` in the sources

**Pull request merged**
