### PR TITLE
resolved: implement edns0 support and other fixes

### PR DESCRIPTION
**Pull request by teg**
This replaces PR #601.

### CODE REVIEW

**Comment by crrodriguez** [comment]
``` text
Jul 20 00:44:56 xps15z systemd-resolved[17193]: ASAN:SIGSEGV
Jul 20 00:44:56 xps15z systemd-resolved[17193]: =================================================================
Jul 20 00:44:56 xps15z systemd-resolved[17193]: ==17193==ERROR: AddressSanitizer: SEGV on unknown address 0x00011fff8002 (pc 0x560b31a58bfa bp 0x7fff8e029340 sp 0x7fff8e029320 T0)
Jul 20 00:44:56 xps15z systemd-resolved[17193]: #0 0x560b31a58bf9 in link_find_dns_server src/resolve/resolved-link.c:309
Jul 20 00:44:56 xps15z systemd-resolved[17193]: #1 0x560b31a58e75 in link_update_dns_servers src/resolve/resolved-link.c:177
Jul 20 00:44:56 xps15z systemd-resolved[17193]: #2 0x560b31a5b8ee in link_update_monitor src/resolve/resolved-link.c:255
Jul 20 00:44:56 xps15z systemd-resolved[17193]: #3 0x560b31a4e40d in manager_process_link src/resolve/resolved-manager.c:80
Jul 20 00:44:56 xps15z systemd-resolved[17193]: #4 0x560b31a4ecab in manager_rtnl_listen src/resolve/resolved-manager.c:237
Jul 20 00:44:56 xps15z systemd-resolved[17193]: #5 0x560b31a543c9 in manager_new src/resolve/resolved-manager.c:439
Jul 20 00:44:56 xps15z systemd-resolved[17193]: #6 0x560b31a4d8e2 in main src/resolve/resolved.c:76
Jul 20 00:44:56 xps15z systemd-resolved[17193]: #7 0x7f7c0294a5bf in __libc_start_main (/lib64/libc.so.6+0x205bf)
Jul 20 00:44:56 xps15z systemd-resolved[17193]: #8 0x560b31a4d4b8 in _start (/usr/lib/systemd/systemd-resolved+0x724b8)
Jul 20 00:44:56 xps15z systemd-resolved[17193]: AddressSanitizer can not provide additional info.
Jul 20 00:44:56 xps15z systemd-resolved[17193]: SUMMARY: AddressSanitizer: SEGV src/resolve/resolved-link.c:309 link_find_dns_server
Jul 20 00:44:56 xps15z systemd-resolved[17193]: ==17193==ABORTING
```

**Comment by crrodriguez** [comment]
Discard last crash trace, forgot to run make clean before testing.

**Comment by poettering** [comment]
OK, reviewed it all. Looks pretty good, but see comments!

**Comment by teg** [comment]
Addressed all inline comments and will push a new version of this PR.

**Pull request closed without merging**
