### PR TITLE
Hashmap avoid compiler warning

### PR DESCRIPTION
**Pull request by thom311**
Avoid a (false) gcc compiler warning about uninitialized variable.

Happens when compiling with LTO and `-O2` in NetworkManager (which contains a fork of this code).

### CODE REVIEW

**Comment by poettering** [comment]
hmm, we generally have so far ignored compiler warnings altogether when LTO was on, since they were so bogus... I wonder if it's really desirable to make these false warnings go away like this? might hide stuff later, when LTO is fixed in this regard?

**Comment by thom311** [comment]
We just fixed LTO build for NetworkManager and it resulted in 5 new warnings -- with the particular configuration I tested (Fedora 28, gcc 8.2, -O2). All warnings  were false-positives of type maybe-uninitialized. At this point there are few enough warnings that it is simpler to just workaround them.

In this case, the "maybe-uninitalized" false warnings were all avoided by just initializing the variable. Contrast to kernel's `uninitialized_var(x)` macro (which self-initializes the variable), this seems unlikely to hide a bug in the future.

Anyway, I don't really mind either way.

**Comment by keszybz** [comment]
> We just fixed LTO build for NetworkManager

Hmm, can you say what that entailed? systemd currently does not build with lto at all. I looked into it, but the errors are rather cryptic.

I'll go ahead and merge this. The second commit looks reasonable (the interface simply doesn't work well for this case, we should consider adding a second accessor function that has two output arguments). And the first commit is trivial enough.

**Comment by thom311** [comment]
> Hmm, can you say what that entailed?

LTO build was *almost* working for quite some time. I don't remember anything special there except fixing a few new compiler warnings. The thing that didn't work was our use of 
```
    __asm__(".symver func2, func@symbol")
```
to add versioned symbols. But I see, systemd doesn't use that.

That seems to be [fixed](https://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=e6cf4213a774020cfcc27983354c81b3e92caa9e) now by using `-flto -flto-partition=none` and `__attribute__((__externally_visible__))` for these versioned symbols.

I noticed, clang doesn't support `externally_visible` attribute, so it may not work with clang. I didn't investigate that further.

**Comment by keszybz** [comment]
@thom311 thanks. I tried an LTO build with latest GCC and everything seems to work. It gives us ~10% savings on size of the main binaries, so it's definitely worth the trouble.

**Pull request merged**
