### PR TITLE
tree-wide: Workaround -Wnonnull GCC bug

### PR DESCRIPTION
**Pull request by benjarobin**
As requested by @evverx in https://github.com/systemd/systemd/issues/6119#issuecomment-624830013
See issue #6119

### CODE REVIEW

**Comment by evverx** [comment]
@benjarobin could you temporarily apply https://github.com/systemd/systemd/pull/15725/commits/4e70bd7c6a19c88521fabcff1f676bb45e9068b5 just to make sure the issue is gone?

**Comment by evverx** [comment]
Another option would be to enclose those with `DISABLE_WARNING_NONNULL` .. `REENABLE_WARNING` (which I think in a way would make it a bit easier to figure out what's going on here :-)

**Comment by keszybz** [comment]
This isn't too intrusive. If it is enough to avoid the problem, then let's merge.

**Comment by evverx** [comment]
According to https://travis-ci.org/github/systemd/systemd/jobs/683980681, systemd was built successfully with -O3. @benjarobin could you drop the second commit? It served its purpose.

**Comment by benjarobin** [comment]
> @benjarobin could you drop the second commit? It served its purpose.

Done

**Pull request merged**
