### PR TITLE
oss-fuzz: include generated corpora in the final zip file

### PR DESCRIPTION
**Pull request by mrc0mmand**
Since the files with generated directives are now automatically generated during build, they're now under the respective build directory which the current oss-fuzz CI script didn't account for.

Follow-up to: #24958
Resolves: #25859

---

/cc @evverx 

```
$ meson build-fuzz
$ ninja -C build-fuzz fuzzers
$ OUT=.
$ build=build-fuzz
$ ls -l $build/test/fuzz
total 60
-rw-rw-r--. 1 fsumsal fsumsal 1730 Jan  7 09:44 fuzz-link-parser_directives.link
-rw-rw-r--. 1 fsumsal fsumsal 3351 Jan  7 09:44 fuzz-netdev-parser_directives.netdev
-rw-rw-r--. 1 fsumsal fsumsal 7842 Jan  7 09:44 fuzz-network-parser_directives
-rw-rw-r--. 1 fsumsal fsumsal   75 Jan  7 09:44 fuzz-unit-file_directives.automount
-rw-rw-r--. 1 fsumsal fsumsal 3477 Jan  7 09:44 fuzz-unit-file_directives.mount
-rw-rw-r--. 1 fsumsal fsumsal  167 Jan  7 09:44 fuzz-unit-file_directives.path
-rw-rw-r--. 1 fsumsal fsumsal 1139 Jan  7 09:44 fuzz-unit-file_directives.scope
-rw-rw-r--. 1 fsumsal fsumsal 6291 Jan  7 09:44 fuzz-unit-file_directives.service
-rw-rw-r--. 1 fsumsal fsumsal  971 Jan  7 09:44 fuzz-unit-file_directives.slice
-rw-rw-r--. 1 fsumsal fsumsal 4244 Jan  7 09:44 fuzz-unit-file_directives.socket
-rw-rw-r--. 1 fsumsal fsumsal 3400 Jan  7 09:44 fuzz-unit-file_directives.swap
-rw-rw-r--. 1 fsumsal fsumsal  234 Jan  7 09:44 fuzz-unit-file_directives.timer
$ for d in test/fuzz/fuzz-* "$build"/test/fuzz; do
    fname="$(basename "$d")"                                                                                           
    [[ "$fname" == "fuzz" ]] && fname="fuzz-generated-directives"                                                                
    zip -jqr "$OUT/${fname}_seed_corpus.zip" "$d"
done
$ ls -l *.zip
-rw-rw-r--. 1 fsumsal fsumsal  3367 Jan  7 09:56 fuzz-bootspec_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal   627 Jan  7 09:56 fuzz-bus-match_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  6174 Jan  7 09:56 fuzz-bus-message_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  1309 Jan  7 09:56 fuzz-calendarspec_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  5197 Jan  7 09:56 fuzz-catalog_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  3863 Jan  7 09:56 fuzz-dhcp6-client_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal   575 Jan  7 09:56 fuzz-dhcp-client_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  2153 Jan  7 09:56 fuzz-dhcp-server-relay_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  2100 Jan  7 09:56 fuzz-dhcp-server_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal 10467 Jan  7 09:56 fuzz-dns-packet_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal   256 Jan  7 09:56 fuzz-env-file_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  2612 Jan  7 09:56 fuzz-etc-hosts_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal   697 Jan  7 09:56 fuzz-fido-id-desc_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal 14764 Jan  7 09:56 fuzz-generated-directives_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal   688 Jan  7 09:56 fuzz-journald-audit_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  2765 Jan  7 09:56 fuzz-journald-kmsg_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal   191 Jan  7 09:56 fuzz-journald-native-fd_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal   173 Jan  7 09:56 fuzz-journald-stream_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal   677 Jan  7 09:56 fuzz-journald-syslog_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  7406 Jan  7 09:56 fuzz-journal-remote_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  1471 Jan  7 09:56 fuzz-json_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  1900 Jan  7 09:56 fuzz-link-parser_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal   601 Jan  7 09:56 fuzz-lldp-rx_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal   436 Jan  7 09:56 fuzz-ndisc-rs_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal 13915 Jan  7 09:56 fuzz-netdev-parser_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal 28361 Jan  7 09:56 fuzz-network-parser_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  1789 Jan  7 09:56 fuzz-nspawn-oci_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  1052 Jan  7 09:56 fuzz-nspawn-settings_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  1390 Jan  7 09:56 fuzz-resource-record_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  2086 Jan  7 09:56 fuzz-systemctl-parse-argv_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  4359 Jan  7 09:56 fuzz-udev-database_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal 17146 Jan  7 09:56 fuzz-udev-rules_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal 43309 Jan  7 09:56 fuzz-unit-file_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  2568 Jan  7 09:56 fuzz-varlink_seed_corpus.zip
-rw-rw-r--. 1 fsumsal fsumsal  2555 Jan  7 09:56 fuzz-xdg-desktop_seed_corpus.zip
$ unzip -l fuzz-generated-directives_seed_corpus.zip 
Archive:  fuzz-generated-directives_seed_corpus.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     3351  01-07-2023 09:44   fuzz-netdev-parser_directives.netdev
     7842  01-07-2023 09:44   fuzz-network-parser_directives
     1139  01-07-2023 09:44   fuzz-unit-file_directives.scope
     1730  01-07-2023 09:44   fuzz-link-parser_directives.link
       75  01-07-2023 09:44   fuzz-unit-file_directives.automount
     3477  01-07-2023 09:44   fuzz-unit-file_directives.mount
      167  01-07-2023 09:44   fuzz-unit-file_directives.path
     6291  01-07-2023 09:44   fuzz-unit-file_directives.service
      971  01-07-2023 09:44   fuzz-unit-file_directives.slice
     3400  01-07-2023 09:44   fuzz-unit-file_directives.swap
     4244  01-07-2023 09:44   fuzz-unit-file_directives.socket
      234  01-07-2023 09:44   fuzz-unit-file_directives.timer
---------                     -------
    32921                     12 files
```

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Ugh, nevermind, this might be not as easy as I thought, I just completely forgot how the original layout looked, so this might need a bit more work.

**Comment by mrc0mmand** [comment]
Now it looks much better:

```
$ unzip -l fuzz-unit-file_seed_corpus.zip 
Archive:  fuzz-unit-file_seed_corpus.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      216  04-25-2022 13:12   dev-mapper-fedora_krowka\x2dswap.swap
       14  04-25-2022 13:12   empty.scope
       61  04-25-2022 13:12   github-19178
      459  04-25-2022 13:12   machine.slice
<...snip...>
      717  04-25-2022 13:12   systemd-ask-password-console.path
      858  04-25-2022 13:12   systemd-tmpfiles-clean.timer
      460  04-25-2022 13:12   timers.target
      529  04-25-2022 13:12   var-lib-machines.mount
      748  09-20-2022 10:35   proc-sys-fs-binfmt_misc.automount
     1692  09-20-2022 10:35   systemd-machined.service
     1680  09-20-2022 10:35   systemd-resolved.service
    15070  01-02-2023 09:33   directives-all.service
     1139  01-07-2023 09:44   fuzz-unit-file_directives.scope
       75  01-07-2023 09:44   fuzz-unit-file_directives.automount
     3477  01-07-2023 09:44   fuzz-unit-file_directives.mount
      167  01-07-2023 09:44   fuzz-unit-file_directives.path
     6291  01-07-2023 09:44   fuzz-unit-file_directives.service
      971  01-07-2023 09:44   fuzz-unit-file_directives.slice
     3400  01-07-2023 09:44   fuzz-unit-file_directives.swap
     4244  01-07-2023 09:44   fuzz-unit-file_directives.socket
      234  01-07-2023 09:44   fuzz-unit-file_directives.timer
---------                     -------
  4213178                     41 files

$ unzip -l fuzz-network-parser_seed_corpus.zip
Archive:  fuzz-network-parser_seed_corpus.zip 
  Length      Date    Time    Name                   
---------  ---------- -----   ----              
       85  04-25-2022 13:12   github-10639           
       65  04-25-2022 13:12   github-13938         
      222  04-25-2022 13:12   github-15885                                                                             
       33  04-25-2022 13:12   github-15951             
<...snip...>
       49  09-20-2022 10:35   vti6                                             
       44  09-20-2022 10:35   vxlan                                            
     7842  01-07-2023 09:44   fuzz-network-parser_directives                                                                                                   
---------                     -------                                          
   963116                     75 files 

$ unzip -l fuzz-netdev-parser_seed_corpus.zip 
Archive:  fuzz-netdev-parser_seed_corpus.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
       31  04-25-2022 13:12   11-dummy.netdev
       33  04-25-2022 13:12   12-dummy.netdev
       37  04-25-2022 13:12   21-macvlan.netdev
       37  04-25-2022 13:12   21-macvtap.netdev
<...snip...>
       59  09-20-2022 10:35   25-bond-backup.netdev
      120  09-20-2022 10:35   25-ipip-tunnel2.netdev
       74  09-20-2022 10:35   crash-null-address
     3351  01-07-2023 09:44   fuzz-netdev-parser_directives.netdev
---------                     -------
    56843                     52 files

$ unzip -l fuzz-link-parser_seed_corpus.zip 
Archive:  fuzz-link-parser_seed_corpus.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      425  04-25-2022 13:12   99-default.link
       26  04-25-2022 13:12   advertise-segv.link
      123  04-25-2022 13:12   condition-memleak.link
       55  04-25-2022 13:12   oss-fuzz-13878
     2015  04-25-2022 13:12   oss-fuzz-13882
     1730  01-07-2023 09:44   fuzz-link-parser_directives.link
---------                     -------
     4374                     6 files

```

**Comment by evverx** [comment]
> $ ls -l $build/test/fuzz
total 60

Nice catch! I didn't notice they all went there.

I think `${generated[@]+"${generated[@]}"}` can be replaced with `"${generated[@]}"`. As far as I understand `bash` should expand it correctly even when `generated` is empty (but I'm not 100% sure). LGTM. Thanks!

**Comment by mrc0mmand** [comment]
> I think `${generated[@]+"${generated[@]}"}` can be replaced with `"${generated[@]}"`. As far as I understand `bash` should expand it correctly even when `generated` is empty (but I'm not 100% sure). LGTM. Thanks!

Ah, indeed, I keep forgetting this is needed only for bash < 4.4 when `set -u` is used, dropped.

**Review by bluca — APPROVED** [review]

**Pull request merged**
