### PR TITLE
core: allow 'SetUnitProperties()' to run on inactive units too

### PR DESCRIPTION
**Pull request by fbuihuu**
'set-property' has been primarly designed to change some properties of
_active_ units.

However it can easily work on inactive units as well. In that case
changes are only saved in a drop-in for futur uses and changes will be
effective when unit will be started.

Actually it already works on inactive units but that was not
documented and not fully supported. Indeed the inactive units had to
be known by the manager otherwise it was reported as not loaded:

```
 $ systemctl status my-test.service
 * my-test.service - My Testing Unit
    Loaded: loaded (/etc/systemd/system/my-test.service; static; vendor preset: disabled)
   Drop-In: /etc/systemd/system/my-test.service.d
    Active: inactive (dead)

 $ systemctl set-property my-test.service MemoryLimit=1000000
 Failed to set unit properties on my-test.service: Unit my-test.service is not loaded.
```

[ Note: that the unit load state reported by the 'status' command
  might be confusing since it claimed the unit as loaded but
  'set-property' reported the contrary. ]

One can possibily workaround this by making the unit a dependency of
another active unit so the manager will keep it around:

```
 $ systemctl add-wants multi-user.target my-test.service
 Created symlink from /etc/systemd/system/multi-user.target.wants/my-test.service to /etc/systemd/system/my-test.service.

 $ systemctl set-property my-test.service MemoryLimit=1000000

 $ systemctl status my-test.service
 * my-test.service - My Testing Unit
    Loaded: loaded (/etc/systemd/system/my-test.service; enabled; vendor preset: disabled)
   Drop-In: /etc/systemd/system/my-test.service.d
            `-50-MemoryLimit.conf
    Active: inactive (dead)
```

This patch simply forces 'SetUnitProperties()' to load the unit if
it's not already the case.

It also documents the fact that 'set-property' can be used on inactive
units.

### CODE REVIEW

**Comment by evverx** [comment]
@fbuihuu , does it break the conception of the `daemon-reload`?
See https://bugzilla.redhat.com/show_bug.cgi?id=615527#c4

**Comment by poettering** [comment]
Patch makes sense to me, except that I'd like a stricter load state check.

**Comment by fbuihuu** [comment]
> does it break the conception of the daemon-reload?

@evverx, sorry but I'm not sure to understand. 'daemon-reload' isn't needed by 'set-property' if this is what you were asking for.

**Comment by fbuihuu** [comment]
> We really should also return an error for UNIT_ERROR and UNIT_MASKED.

@poettering, I initially considered to handle UNIT_ERROR differently that is returning an error in this case. But I couldn't see why we should do that at the end, specially if the 'set-property' command is going to overwrite the broken part of the unit.

Regarding UNIT_MASKED, I don't know so I'll follow you suggestion.

**Comment by poettering** [comment]
@fbuihuu i'd think it would be quite surprising for users if the call would work on units we failed to load... Hence, really, I'd refuse things for != UNIT_LOADED. Sounds simplest and safest, and the least surprising.

**Comment by fbuihuu** [comment]
@poettering , not sure if you got a notification when I updated my branch according to your recommendations so here it is.

**Comment by poettering** [comment]
Looks fine otherwise.

**Comment by poettering** [comment]
(and no, i didn't get the notifications, sorry. not sure how to make github notify me in that case. just to be sure, please mention explicitly when you update the branch...)

**Comment by fbuihuu** [comment]
@poettering , I have updated the branch according to your comments. Thanks.

**Comment by fbuihuu** [comment]
@poettering branch updated. Since load_error is not set when UNIT_MASKED, I think we have to black list this case. I also blacklisted UNIT_NOT_FOUND separately because returning BUS_ERROR_NO_SUCH_UNIT is better than the generic "file not found" error.

I replied that where you commented my previous pull request but got no answer from you so again I wasn't sure you read my answer.... hence this new pull request that may not make you happy yet.

**Comment by poettering** [comment]
Looks good now!

**Pull request merged**
