### PR TITLE
memdup_suffix0_multiply fix

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Now the error *slightly* changed, but it's still there:

```
$ git log --oneline -2
2dc66a6417 (HEAD -> poettering-memdup-suffix0-multiply-fixo) test: modernize test-alloc-util.c test a bit
7d025debfa alloc-util: drop _alloc_(2, 3) decorator from memdup_suffix0_multiply()
$ meson build --werror -Dc_args='-g -O1 -fno-omit-frame-pointer -ftrapv' -Dslow-tests=false -Dtests=unsafe -Dinstall-tests=false -Dman=false -Db_sanitize=address,undefined
$ ninja -C build
$ export ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1
$ export UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_error=1

$ build/test-alloc-util
../src/test/test-alloc-util.c:69:9: runtime error: load of address 0x60200000003c with insufficient space for an object of type 'uint8_t'
0x60200000003c: note: pointer points here
  03 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
              ^ 
    #0 0x40241b in test_memdup_multiply_and_greedy_realloc ../src/test/test-alloc-util.c:69
    #1 0x40241b in main ../src/test/test-alloc-util.c:155
    #2 0x7fc6b99c0f32 in __libc_start_main (/lib64/libc.so.6+0x23f32)
    #3 0x40129d in _start (/home/fsumsal/repos/systemd/build/test-alloc-util+0x40129d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/test/test-alloc-util.c:69:9 in 

```

**Comment by keszybz** [comment]
I don't understand this report.
```
03 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
            ^ 
```
This show that we're looking at the correct place. `03 00 00 00` is 3 in little-endian, and the following `00` is our terminating byte.

**Comment by keszybz** [comment]
I think we should merge this PR, since it seems to fix *some* issues and seems correct on its own, and then debug the issue further.

**Comment by poettering** [comment]
I think I fixed the new issue out too now, see #13045.

**Pull request merged**
