### PR TITLE
some manager fixes

### LINKED ISSUE #7932: core: hardware watchdog ping blocked by manager_dispatch_sigchld / manager_dispatch_run_queue
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

running on v225, v230, checking code master

### Used distribution

embedded

### Situation

We are facing a problem that the hardware watchdog /dev/watchdog ping is blocked several seconds which could cause a watchdog timeout.

The problem was originally reported on v225, we also checked on v230 and checked the probably fix in systemd upstream master.

(All log starts with "SO" are added locally)

1.
Sometimes manager_dispatch_sigchld takes several seconds:
`[ 39.372622] systemd[1]: SO: sd 'manager-signal' here`
`[ 39.465293] systemd[1]: Received SIGCHLD from PID 1026 (sleep).`
`[ 39.577935] systemd[1]: Child 1026 (sleep) died (code=exited, status=0/SUCCESS)`
`[ 40.404686] systemd[1]: SO: invoke: ifup.service.`
`[ 40.657905] systemd[1]: Child 1051 (ifconfig) died (code=exited, status=0/SUCCESS)`
`[ 43.582020] systemd[1]: SO: invoke: ifup.service.`
`[ 43.630135] systemd[1]: SO: delta_t=4301.852000`

The patch #3634 "Only invoke a single sigchld per unit within a cleanup cycle" has already solved the issue the multiply times invoked for ifup-eth0.service.
However, it seems multiply times invoke for different services are still possible after the fix. This might lead to the problem, the hardware watchdog ping is blocked:

`[   42.564130] systemd[1]: SO: sd 'manager-signal' here`
`[   42.607821] systemd[1]: Received SIGCHLD from PID 1549 (mkdir).`
`[   42.625604] systemd[1]: Child 1549 (mkdir) died (code=exited, status=0/SUCCESS)`
`[   42.634989] systemd[1]: phone.service: Child 1549 belongs to phone.service`
`...`
`[   42.903391] systemd[1]: Child 1556 (dump_o) died (code=exited, status=0/SUCCESS)`
`[   42.918475] systemd[1]: err.service: Child 1556 belongs to err.service`
`...`
`[   43.265386] systemd[1]: Child 1559 (mkdir) died (code=exited, status=0/SUCCESS)`
`[   43.327031] systemd[1]: a_once.service: Child 1559 belongs to a_once.service`
`...`
`[   43.727794] systemd[1]: Child 1573 (chown) died (code=exited, status=0/SUCCESS)`
`[   43.787893] systemd[1]: phone.service: Child 1573 belongs to phone.service`
`...`
`[   44.337163] systemd[1]: Child 1597 (a_once) died (code=exited, status=0/SUCCESS)`
`[   44.361186] systemd[1]: a_once.service: Child 1597 belongs to a_once.service`
`...`
`[   45.014195] systemd[1]: Child 1624 (chmod) died (code=exited, status=0/SUCCESS)`
`[   45.040382] systemd[1]: phone.service: Child 1624 belongs to phone.service`
`...`
`[   45.757349] systemd[1]: SO: delta_t=3260.015000`

I checked a patch #1707 (drop tight loop in manager_dispatch_notify_fd) for has fix a problem in "manager-notify". Before that patch, manager-notify could also blocks the watchdog_ping.

I wonder if a similar thing could be done in manager_dispatch_sigchld.

2.
manager_dispatch_run_queue sometimes also takes several seconds:
`systemd[1]: SO: sd 'manager-run-queue' here`
`systemd[1]: SO: delta_t=4247.675000`

This probably because we have several dynamic units during startup, which the dependencies were not known by systemd at the beginning.

`[   59.668675] systemd[1]: SO: sd 'manager-run-queue' here`
`[   59.727529] systemd[1]: Failed to set cpu.cfs_period_us on /system.slice: No such file or directory`
`[   59.729821] systemd[1]: Failed to set cpu.cfs_quota_us on /system.slice: No such file or directory`
`[   59.767398] systemd[1]: Failed to set cpu.cfs_period_us on /system.slice/service1.service: No such file or directory`
`[   59.769905] systemd[1]: Failed to set cpu.cfs_quota_us on /system.slice/service1.service: No such file or directory`
`[   59.796815] systemd[1]: service1.service: About to execute: service1.out`
`[   59.798937] systemd[1]: service1.service: Forked service1.out as 1701`
`[   59.814593] systemd[1]: service1.service: Changed dead -> running`
`[   59.815896] systemd[1]: service1.service: Job service1.service/start finished, result=done`
`[   59.817317] systemd[1]: Started service1.`
`[   59.845357] systemd[1]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=573 reply_cookie=0 error=n/a`
`[   59.846889] systemd[1]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=574 reply_cookie=0 error=n/a`
`[   59.850998] systemd[1]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.0 object=n/a interface=n/a member=n/a cookie=206 reply_cookie=574 error=n/a`
`[   59.906540] systemd[1]: Failed to set cpu.cfs_period_us on /system.slice/service2.service: No such file or directory`
`[   59.907474] systemd[1]: Failed to set cpu.cfs_quota_us on /system.slice/service2.service: No such file or directory`
`[   59.918617] systemd[1]: service2.service: About to execute: service2.out`
`[   59.921189] systemd[1]: service2.service: Forked service2.out as 1702`
`[   59.937375] systemd[1]: service2.service: Changed dead -> running`
`[   59.950531] systemd[1]: service2.service: Job service2.service/start finished, result=done`
`[   59.958488] systemd[1]: Started service2.`
`[   59.994481] systemd[1]: Sent message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=575 reply_cookie=0 error=n/a`
`[   59.997061] systemd[1]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus object=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=576 reply_cookie=0 error=n/a`
`[   60.001442] systemd[1]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.0 object=n/a interface=n/a member=n/a cookie=207 reply_cookie=576 error=n/a`
`[   60.011746] systemd[1]: service3.service: ConditionFileIsExecutable=service3.out succeeded.`
`[   60.070924] systemd[1]: Failed to set cpu.cfs_period_us on /system.slice/service3.service: No such file or directory`
`[   60.072130] systemd[1]: Failed to set cpu.cfs_quota_us on /system.slice/service3.service: No such file or directory`
`[   60.080223] systemd[1]: service3: About to execute: service3.out`
`[   60.082906] systemd[1]: service3: Forked service3.out as 1710`
`[   60.136088] systemd[1]: service3: Changed dead -> running`
`[   60.138927] systemd[1]: service3: Job service3.service/start finished, result=done`
`[   60.139563] systemd[1]: Started service3.`
...
More services in-between
...
`[   63.917762] systemd[1]: SO: delta_t=4247.675000`

I have current no idea if an improvement in this part is possible.

Overall, sometimes systemd cannot ping hardware watchdog within the time defined in /etc/systemd/system.conf
#1707 and #3634 partially solved the overall problem, maybe further improvement might me possible.

This is a strange problem we faced. Above are my first analysis, still checking if something similar as #1707 would help.

### PR DESCRIPTION
**Pull request by poettering**
the only really relevant bit is the signal dispatch rework.

This fixes #7932, and possibly #7966 too

### CODE REVIEW

**Comment by yuwata** [comment]
lgtm.

**Comment by sourcejedi** [comment]
I'm not getting very far looking at this on github.  But reading the commit message on it's own, I don't understand it.

> This introduces a new "defer" event source "sigchld_event". It's enabled
> as soon as we see SIGCHLD, and disabled as soon as waitid() reported no
> further children pending. It's running at a relatively high priority,
> one step higher than signal handling itself, but lower than
> /proc/self/mountinfo event handling, so that the latter always takes
> precedence.

Don't we want signal handling to run at the same or higher priority as "sigchld_event"?  It sounds like signal handling is lower priority than /proc/self/mountinfo handling, which we don't want?

**Comment by sourcejedi** [comment]
> I'm not getting very far looking at this on github. But reading the commit message on it's own, I don't understand it.

Disregard, I think I'm too tired now :).  I'll see if I can understand the rest of the patch tommorow.

**Comment by sourcejedi** [comment]
In the mean time, I bisected a problem which points to that last commit.

**Comment by poettering** [comment]
hmm, @sourcejedi which problem?

**Comment by sourcejedi** [comment]
#7985

**Pull request merged**
