### PR TITLE
Update scsi_id.c

### PR DESCRIPTION
**Pull request by szb512**
I don't want to be stupid........ but I'm trying again at fixing LGTM errors.
@mrc0mmand does this PR show any errors (ex. recursions) that need addressing?

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Apart from the compilation errors, I'm not sure if it's worth digging into. I've attempted to fix these issues back in 2019 (see https://github.com/systemd/systemd/pull/12102), but as @poettering stated there, the `scsi_id` stuff is about to be replaced by https://github.com/systemd/systemd/pull/7594 (and followups). Given that, I'd leave the final decision to @poettering who knows more about it.

**Comment by dnicolodi** [comment]
I think the minimum requirements for a patch to be considered are no compilation errors introduced and a meaningful commit message. First, you should setup a development environment in which you can compile and ideally test your changes. Then, you should strive to write precise and complete commit messages. There are many articles around that explain how to achieve this. "Update $filename" is redundant (the file name you are modifying is already encoded in the patch) and does not tell anything about the reasons for the change you are proposing.

**Comment by szb512** [comment]
*yawn*

**Comment by szb512** [comment]
Aight im back, sorry for long inactivity.

**Comment by poettering** [comment]
so @mrc0mmand is right, we'd rather see this go.

It's really old code, badly maintained that we don't understand, given that we aren't scsi people. I'd very much prefer if this split into scsi-tools or so, i.e. #7594, but that effort unfortunately appears stalled...

i mean, if #7594 never materializes we can look into improving this code, but it should happen carefully, i.e. in many individual steps, since at least I personally don't have suitable hw to test this, so we can only hope things work.

**Pull request closed without merging**
