### PR TITLE
cryptsetup: Support specifying a file system with tmp= option

### PR DESCRIPTION
**Pull request by medhefgo**

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, what's the usecase for this? Why doesn't the x-systemd.mkfs mount option we already have suffice?

I mean, this issue is really not specific to cryptsetup, is it? Formatting a file system before mounting it is useful in all cases, hence having it as a per-mount option makes a lot more sense than a per-crypttab option, no?

I think we should probably deprecate the crypttab "tmp" option. i.e. continue to support it in code, but drop it from the man page, and instead point people towards using x-systemd.mkfs... Moreover, we should probably rework it to actually use systemd-mkfs@.service instead of calling mkfs directly....

**Comment by medhefgo** [comment]
This is for #952. I just felt like implementing it :D

Don't merge this one yet, cause I realized there's a parsing bug I need to fix.

**Comment by poettering** [comment]
Ah, eh. that bug is pretty old. I think we should have closed it when we merged the support for systemd.mkfs, as I am very sure that's a much nicer, more universal approach...

**Comment by medhefgo** [comment]
I fixed the parsing bug, so it may be pushed now.

Now, I don't think we can use systemd-mkfs@.service here, because I can see people relying on systemd-cryptsetup@.service to already provide the device and file system in one go and might have units depending on it. People do crazy things after all. But I did replace mkfs with systemd-makefs binary to make it more safe.

Also, if cryptsetup-generator creates a systemd-makefs@.service instance, we don't know where it would be mounted, so we cannot order the mount unit appropriately, right? fstab-generator could always add one for /dev/mapper units, but that isn't strictly correct either since they aren't necessarily from cryptsetup-generator...

**Pull request closed without merging**
