### PR TITLE
travis: use double the normal timeout in the ASan & UBSan stage

### PR DESCRIPTION
**Pull request by evverx**
This should somewhat address https://github.com/systemd/systemd/issues/10696.

cc @mrc0mmand

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Even though it could fix the timeout issue in Travis, there's definitely something fishy going on - the `test-execute` usually takes ~10 seconds to complete, so the 10m+ delay is somewhat worrisome. In my opinion, when the issue occurs once again, and the test is indeed *stuck*, it will just prolong the time until the job is killed by the global timeout (90 or 120 mins, not sure here).

**Comment by evverx** [comment]
That's true that `test-execute` should be fixed and I opened a PR to figure out what is going on there: https://github.com/systemd/systemd/pull/10697. No luck so far.

> In my opinion, when the issue occurs once again, and the test is indeed stuck, it will just prolong the time until the job is killed by the global timeout

This PR will help to find out whether this assumption is correct. I hope it isn't but who knows :-)

**Comment by mrc0mmand** [comment]
> This PR will help to find out whether this assumption is correct. I hope it isn't but who knows :-)

I, too, hope I'm wrong - that was just my previous experience with Travis speaking.

Anyway, what's the next step now? Just merge it and wait until it happens again or are we going to smash the *Restart build* button again?

**Comment by evverx** [comment]
My plan is to merge it to see what happens. I hope the issue will magically disappear or, at least, the test will have enough time to fail properly so that we can see the logs instead of error messages from Travis CI, but if it won't, we'll learn that 20 minutes isn't enough for the test to complete.

**Pull request merged**
