### PR TITLE
shared/install: several fixes for change reporting

### PR DESCRIPTION
**Pull request by YHNdnzj**
Fixes https://github.com/systemd/systemd/issues/33411

### CODE REVIEW

**Comment by poettering** [comment]
lgtm

**Comment by eworm-de** [comment]
Hmm, this did not make it into a stable release. Was it missed intentionally? @bluca

**Comment by bluca** [comment]
There are too many unrelated changes and merge conflicts so it doesn't backport cleanly

**Comment by eworm-de** [comment]
But is it still intended for backport? We should drop the label otherwise.

**Comment by YHNdnzj** [comment]
> There are too many unrelated changes and merge conflicts so it doesn't backport cleanly

Hmm? Only the first commit is unrelated, and it's trivial, no?

**Comment by bluca** [comment]
The second one too? At least it doesn't say it fixes any bug - but anyway, feel free to prepare a backport and open a PR

**Pull request merged**
