### PR TITLE
networkd: add dbus API for IP address query/notification

### PR DESCRIPTION
**Pull request by aragua**
We made these changes in order to be notified when ip address changes.

### CODE REVIEW

**Comment by poettering** [comment]
hmm, I am pretty sure the addresses should be exposed in binary form, i.e. as "a(iay)", i.e. an array of address family plus address binary data, that's how resolved nad machined expose IP addresses for example

**Comment by poettering** [comment]
i am bit concerned though: on Linux configured IP addreses can have all kinds of attributes. If we don't do this comprehensively, wouldn't it be better to just rely on the info made available through rtnetlink for now?

**Comment by aragua** [comment]
Hi
We can change the format to make it more consistent.

Our need is to be notified that address change via DBUS. I don't think rtnetlink provides such a mechanism.
Do you think we should return rtnetlink information using the dbus property we add or just notify that address changes and let the client application  get information by itself?

Thanks

**Comment by poettering** [comment]
> Our need is to be notified that address change via DBUS. I don't think rtnetlink provides such a mechanism.

it does, it notifies you about all address changes. It's messy to use, but is reliable, and independent of any networking management solution. if I was you I'd probably focus on that instead...

There are a couple of libraries that make working with rtnetlink more digestable, you might consider looking into one of those.

**Comment by keszybz** [comment]
Yeah, I think netlink is the way to go. Let's close this.

**Pull request closed without merging**
