### PR TITLE
network: dhcp: add 6rd support

### LINKED ISSUE #19152: Support for DHCP option 212 (sixrd)
**Is your feature request related to a problem? Please describe.**
It's related to the fact that when ISP gives the 6RD details though DHCPv4 and the border gateway may change without a notice.

**Describe the solution you'd like**
I would want it to automatically be configured or the details should be outputted to log or have a scriptable way to generate the config from those details.

**Describe alternatives you've considered**
I have tried NetworkManager, but it also does not have support for it.

**The systemd version you checked that didn't have the feature you are asking for**
247.2-r4 on Gentoo

RFC link: https://tools.ietf.org/html/rfc5969#section-7.1.1

### PR DESCRIPTION
**Pull request by yuwata**
Closes #19152.

### CODE REVIEW

**Comment by yuwata** [comment]
@mrc0mmand Not sure that the CentOS CIs should support that, but I noticed that .network (maybe also .link) files in [network/](https://github.com/systemd/systemd/tree/main/network) are not installed to the testing environment. So, the last commit is necessary to pass the networkd test.

**Comment by mrc0mmand** [comment]
> @mrc0mmand Not sure that the CentOS CIs should support that, but I noticed that .network (maybe also .link) files in [network/](https://github.com/systemd/systemd/tree/main/network) are not installed to the testing environment. So, the last commit is necessary to pass the networkd test.

This is mostly true in the sanitizer runs (https://github.com/systemd/systemd-centos-ci/blob/c2ac85c17f39993d91c2b1b815b22cb22a166249/vagrant/bootstrap_scripts/arch-sanitizers-clang.sh#L97-L105), regular runs should have them installed (since it does ninja -C build install and then reboots the machine).

**Comment by yuwata** [comment]
> > @mrc0mmand Not sure that the CentOS CIs should support that, but I noticed that .network (maybe also .link) files in [network/](https://github.com/systemd/systemd/tree/main/network) are not installed to the testing environment. So, the last commit is necessary to pass the networkd test.
> 
> This is mostly true in the sanitizer runs (https://github.com/systemd/systemd-centos-ci/blob/c2ac85c17f39993d91c2b1b815b22cb22a166249/vagrant/bootstrap_scripts/arch-sanitizers-clang.sh#L97-L105), regular runs should have them installed (since it does ninja -C build install and then reboots the machine).

Thank you for the explanation!

**Comment by yuwata** [comment]
Several commits are split out into smaller PRs.

**Comment by yuwata** [comment]
All cleanup commits are merged through the separate PRs. PTAL.

This changes the existing section name [DHCPv6PrefixDelegation] -> [DHCPPrefixDelegation], and changes the json string, which is a kind of API. So, I'd like to include this PR in v250.

**Comment by keszybz** [comment]
LGTM (superficially). I didn't check all the implementation details… I hope the test would catch any issues. @samip5, please test -rc1 when it comes out.

**Comment by samip5** [comment]
@yuwata This is really misleading... How do I get it to output the actual masks /etc that it used to generate it? Also, I don't think it should use "recieved PD" when using 6rd. It should reference that it's 6rd, not DHCPv6-PD per se.

```
Dec 16 14:48:16 GenPi64 systemd-networkd[183]: eth0: Gained carrier
Dec 16 14:48:17 GenPi64 systemd-networkd[183]: eth0: DHCP: received PD Prefix 2001:2003:f1f8:a900::/56
Dec 16 14:48:17 GenPi64 systemd-networkd[183]: eth0: DHCP-PD address 2001:2003:f1f8:a910:dea6:32ff:fe63:41a6/64 (valid for 29min 59s, preferred for 29min 59s)
Dec 16 14:48:17 GenPi64 systemd-networkd[183]: eth0: DHCPv4 address 80.221.248.169/20, gateway 80.221.240.1 acquired from 10.14.9.54
Dec 16 18:04:00 GenPi64 systemd-networkd[183]: sit0: Failed to configure DHCPv4 client: Invalid argument
Dec 16 18:04:00 GenPi64 systemd-networkd[183]: sit0: Failed
Dec 16 18:04:00 GenPi64 systemd-networkd[183]: 6rd-qLgxGVvSMW: Link UP
Dec 16 18:04:00 GenPi64 systemd-networkd[183]: 6rd-qLgxGVvSMW: Gained carrier
Dec 16 18:04:00 GenPi64 systemd-networkd[183]: 6rd-qLgxGVvSMW: DHCP-PD address 2001:2003:f1f8:a900:46dc:b656:775f:b797/56 (valid for 29min 59s, preferred for 29min 59s)
Dec 16 18:04:00 GenPi64 systemd-networkd[183]: eth0: Gained IPv6LL
Dec 16 18:05:55 GenPi64 systemd-networkd[183]: wg0: Failed to configure DHCPv4 client: Invalid argument
Dec 16 18:05:55 GenPi64 systemd-networkd[183]: wg0: Failed
Dec 16 18:05:55 GenPi64 systemd-networkd[183]: wg0: Link UP
Dec 16 18:05:55 GenPi64 systemd-networkd[183]: wg0: Gained carrier
```

```
# ip -6 r s
::1 dev lo proto kernel metric 256 pref medium
::/96 dev 6rd-qLgxGVvSMW proto kernel metric 256 pref medium
2001:2003:f1f8:a910::/64 dev eth0 proto kernel metric 256 expires 42966sec pref medium
2001:2003:f1f8:a900::/56 dev 6rd-qLgxGVvSMW proto kernel metric 256 expires 42966sec pref medium
unreachable 2001:2003:f1f8:a900::/56 dev lo proto dhcp metric 1024 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev wg0 metric 1024 pref medium
default via ::80.223.255.254 dev 6rd-qLgxGVvSMW proto dhcp metric 1024 expires 4
```

**Comment by yuwata** [comment]
@samip5 Thank you for testing this feature. Update for log message is waiting in #21798.

BTW, why do you enable DHCPv4 client on sit0 or wg0??
I guess a .network file you use does not have enough `[Match]` section.

**Comment by samip5** [comment]
> @samip5 Thank you for testing this feature. Update for log message is waiting in #21798.
> 
> BTW, why do you enable DHCPv4 client on sit0 or wg0?? I guess a .network file you use does not have enough `[Match]` section.

Because the match block I use is all interfaces, so that I don't have to know which name the interface gets from kernel.

**Comment by samip5** [comment]
Can I somehow influence the naming the 6rd tunnel interface gets?

I would like it to be like 6rd-<specified-name in config>, but it's not a big deal.
I also noticed that after ~30 minutes, the lease expired and it was unable to renew it? At least it's not answering on the same IPv6 nor IPv4 address anymore so I cannot check right now what happened.

**Pull request merged**
