### PR TITLE
nsresourced: fix type of bpf_rdonly_cast

### PR DESCRIPTION
**Pull request by lnussel**
https://github.com/libbpf/libbpf/blob/46eafba62ee380a1f8230e2d5e81f65e0e030f15/src/bpf_core_read.h#L328

### CODE REVIEW

**Comment by bluca** [comment]
```
396s libbpf: extern weak function bpf_rdonly_cast is unsupported
396s Error: failed to open BPF object file: Operation not supported
```

**Comment by lnussel** [comment]
Are there different libbpf APIs around? Tumbleweed has 1.4.0 and without the fix fails with

```
FAILED: src/nsresourced/bpf/userns_restrict/userns-restrict.bpf.unstripped.o 
/usr/lib64/ccache/clang -std=gnu11 -Wno-compare-distinct-pointer-types -fno-stack-protector -O2 -target bpf -g -c -D__x86_64__ -I. -isystem /usr/include/x86_64-suse-linux -idirafter /usr/include ../src/nsresourced/bpf/userns_restrict/userns-restrict.bpf.c -o src/nsresourced/bpf/userns_restrict/userns-restrict.bpf.unstripped.o -I/run/host/home/ln/git/systemd/x86_64-suse-linux
../src/nsresourced/bpf/userns_restrict/userns-restrict.bpf.c:23:7: error: conflicting types for 'bpf_rdonly_cast'
   23 | void *bpf_rdonly_cast(void *, __u32) __ksym;
      |       ^
/usr/include/bpf/bpf_core_read.h:328:14: note: previous declaration is here
  328 | extern void *bpf_rdonly_cast(const void *obj, __u32 btf_id) __ksym __weak;
      |              ^
1 error generated.
```

**Comment by bluca** [comment]
Yes, they broke API/ABI at some point

**Comment by lnussel** [comment]
ok. different approach. Note, I don't the first thing about this. Just trying to fix the build :)

**Review by bluca — APPROVED** [review]

**Pull request merged**
