### PR TITLE
tmpfiles: split tmp.conf out

### PR DESCRIPTION
**Pull request by fbuihuu**
tmp.conf was dealing with 2 different kind of paths: one dealing with general
temporary paths such as /var/tmp and /tmp and the other one dealing with
temporary directories owned by systemd.

If for example a user wants to adjust the age argument of the general paths
only, he had to overload the whole file which is cumbersome and error prone
since any future changes in tmp.conf shipped by systemd will be lost.

So this patch splits out tmp.conf so the systemd directories are dealt
separately in a dedicated conf file. It's named "systemd-tmp.conf" based on the
naming recommendation made in tmpfiles.d man page.

In practice it shouldn't cause any regression since it's very unlikely that
users override systemd owned paths.

### CODE REVIEW

**Comment by fbuihuu** [comment]
Actually a similar split was done a long time ago with commit f08fce88206f7315cff24678590cd73cd5e75f95 but commit e4ac004c12f9f45e8f2a222879dbf59a86dfcf7d brought new entries and defeated the purpose of the split.

**Comment by fbuihuu** [comment]
I'm wondering if we could prevent such undesirable changes in the future...

**Comment by fbuihuu** [comment]
This also probably means that people who overrode tmp.conf (at the time it was only containing entries for /var/tmp and /tmp) have never benefited from the later additions (the ones dealing with systemd temproary directories)...

**Comment by keszybz** [comment]
I guess this makes sense. With the split, `tmp.conf` has only two lines so it's quite easy to override in full, and the times and modes for `/tmp` or `/var/tmp` is something that people are most likely to override.

**Pull request merged**
