### PR TITLE
Some fixes for xkb -> console keyboard layout conversion

### PR DESCRIPTION
**Pull request by AdamWill**
These changes are intended to improve xkb -> console layout guessing in some specific cases.

Reasoning about this code is kinda hard because it's fundamentally doing something impossible in a fairly odd way (the `kbd-model-map` data was never really *meant* to be used for this, it was meant to be just a menu of choices). But I think these changes are defensible.

The first change - giving a match bonus when the X context variant is empty and the column in the table is just a dash - is I think obviously "correct", and fixes a clear bug (converting `bg,us` with no variant to `bg_pho-utf8` instead of `bg_bds-utf8`).

The second change is a bit less clear-cut, especially since there's an existing test that asserts the contrary to what this PR proposes. But I think it's correct. I think in general the "native" console layouts for the "XX,us" rows are a better match when the X config is "us,XX" than just "us". In fact, most of them are *exact* matches - for instance, the console "ru" layout defaults to entering *Latin* characters and must be switched to enter Cyrillic characters, so it is in fact a *more precise* match for `us,ru` than it is for `ru,us`.

As mentioned in the commit, the problem we have here is that the `kbd-model-map` data was lightly converted from the very old RH/Fedora system-config-keyboard data, which dates back to before [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1039185). Back in the system-config-keyboard days, if you chose the UI option that corresponded to this row in the data, you'd get exactly "ru" as your console layout and "ru,us" as your X config.

However, back in that 1039185 bug report (which came *after* the days of s-c-k, when this table was already moved to systemd/localed), multiple users of these layouts (not just Russian, but others too) told us that what native users *expect* in the X config is the other ordering - "us,(native)" - because typically on boot they need to enter usernames and/or passwords, which are usually entered in Latin characters. So ever since that bug report, anaconda (the RH installer) has set the X configuration as "us,native", not "native,us". However, the kbd-model-map data was never changed.

Also as mentioned in the commit, I actually noticed and [reported a few years ago](https://bugzilla.redhat.com/show_bug.cgi?id=1912609) that this was causing us to get the wrong console layout, but unfortunately instead of doing something like this PR, we "fixed" it with a rather problematic bodge in anaconda that causes some other problems. I now want to fix the problem properly (here in systemd) and drop the bodge in anaconda to avoid the other problems it causes.

### CODE REVIEW

**Comment by AdamWill** [comment]
Oh, forgot to mention - tweaking the "match" scores is a bit sensitive, but I *think* this should achieve all desired outcomes without requiring us to bump them up by 2x or 10x. We don't, I think, ever want the "bonus" scores to bump us from one "category" of matches to the next, so the match "categories" must be more than 3 apart. And we don't want a bonus-bumped single-layout match to exceed the cutoff for skipping the "The best match is only the first part of the X11 keymap. Check if we have a converted map which matches just the first layout" check.

So I think this is OK. We use 9 as the base value for the 'inverted' match, drop the cutoff for skipping the check to 9, and leave everything else the same. In theory an inverted match with bonus points could outscore a non-inverted match without bonus points, but I can't see why we'd ever introduce lines to the table that could actually cause that to happen, so it doesn't really seem like an issue. The maximum a single-layout match can score with bonuses is 8 (5+1+1+1) so it still can't reach the cutoff. I think it's fine (and correct) for inverted matches to skip that check, though.

**Comment by AdamWill** [comment]
The codeql and "pull request labeler" failures appear to be due to API rate limiting, nothing to do with this PR itself.

**Comment by AdamWill** [comment]
Longer term I think there's an argument for re-designing how this works and moving the backing data into [langtable](https://github.com/mike-fabian/langtable), this ancient magic table based on a long-forgotten, RH-specific tool doesn't make...a *whole* bunch of sense. But this at least produces better results for important cases now.

**Review by keszybz — APPROVED** [review]
LGTM.

**Comment by AdamWill** [comment]
I've backported this to Rawhide as I'd like to work on the anaconda change too. I'd like to backport it to F39 too, but probably best to do it on Rawhide first.

**Comment by AdamWill** [comment]
sigh, I think this also needs a follow-up to also give the variant match bonus if the column is "-" and the context variant specifier is just commas...working on that.

**Pull request merged**
