### PR TITLE
tree-wide: reorder various structures to make them smaller and use fe…

### PR DESCRIPTION
**Pull request by poettering**
…wer cache lines

Some "pahole" spelunking.

No change of behaviour, just some rearrangements inside of structures

### CODE REVIEW

**Comment by evverx** [comment]
This pull request **introduces 1 alert** when merging 3f231169b54fa6ecb906a6b465a376bf4767dc98 into 49bd196d693efe0acfc8d56c4e3d8f7ba9f91b5d - [view on LGTM.com](https://lgtm.com/projects/g/systemd/systemd/rev/pr-581f1f11e4a9a4be19bb0d8d17f5b47d74a0195d)

**new alerts:**

* 1 for Ambiguously signed bit\-field member

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by evverx** [comment]
I'm wondering why the LGTM alert was ignored. @keszybz are you planning to fix it later or do you think it's a false positive?

**Comment by keszybz** [comment]
I don't think the warning makes much sense. The rule talks about portability, but I don't see any context in which the signedness of the variable matters. But I guess we should change this to 'unsigned' to avoid the warning.

**Comment by poettering** [comment]
@evverx #12129 

(for some reason github ate my longer comment here... weird. anyway, lgtm is right, the signedness of `int` bit fields is not defined, and ABIs can pick anyhting there. Which is something I wasn't aware of, since non-bit-field `int` is unconditionally and always signed. Hence, LGTM was right to complain; it knew the C standard better than I ;-). So yeah, I initially thought it was a false positive, but LGTM was right.)

**Pull request merged**
