### PR TITLE
dissect-image: use correct path variable when reading verity signatures, do not refuse verity GPT without /usr partition

### PR DESCRIPTION
**Pull request by bluca**
Copypasta slipped in via https://github.com/systemd/systemd/pull/17101

Fixes https://github.com/systemd/systemd/issues/17123

### CODE REVIEW

**Comment by bluca** [comment]
Missed this while reviewing - but the question is, why didn't all the testsuites fail? Are the various Ubuntu jobs no longer running TEST-50-DISSECT?

**Comment by mrc0mmand** [comment]
> Missed this while reviewing - but the question is, why didn't all the testsuites fail? Are the various Ubuntu jobs no longer running TEST-50-DISSECT?

```
========== START: TEST-50-DISSECT ==========
make: Entering directory '/tmp/autopkgtest.Jkdsml/build.gwl/systemd/test/TEST-50-DISSECT'
make: Leaving directory '/tmp/autopkgtest.Jkdsml/build.gwl/systemd/test/TEST-50-DISSECT'

make: Entering directory '/tmp/autopkgtest.Jkdsml/build.gwl/systemd/test/TEST-50-DISSECT'
make: Leaving directory '/tmp/autopkgtest.Jkdsml/build.gwl/systemd/test/TEST-50-DISSECT'
========== END: TEST-50-DISSECT ==========
```

Looks like the test is skipped due to some missing dependencies (mksquashfs/veritysetup/sfdisk).

/cc @xnox @ddstreet

**Comment by bluca** [comment]
On Ubuntu that means the packages cryptsetup-bin squashfs-tools fdisk - how can we get them installed?

**Comment by bluca** [comment]
Now this is failing: https://github.com/systemd/systemd/blob/master/test/units/testsuite-50.sh#L120

systemd-dissect --json=short --root-hash ${roothash} ${image}.gpt | grep -q '{"rw":"ro","designator":"root","partition_uuid":"'$ROOT_UUID'","fstype":"squashfs","architecture":"x86-64","verity":"yes","node":'

Sep 22 13:49:59 systemd-testsuite testsuite-50.sh[675]: No root partition for specified root hash found in '/tmp/tmp.B6qJ6B/minimal.gpt'

**Comment by bluca** [comment]
> Now this is failing: https://github.com/systemd/systemd/blob/master/test/units/testsuite-50.sh#L120
> 
> systemd-dissect --json=short --root-hash ${roothash} ${image}.gpt | grep -q '{"rw":"ro","designator":"root","partition_uuid":"'$ROOT_UUID'","fstype":"squashfs","architecture":"x86-64","verity":"yes","node":'
> 
> Sep 22 13:49:59 systemd-testsuite testsuite-50.sh[675]: No root partition for specified root hash found in '/tmp/tmp.B6qJ6B/minimal.gpt'

Pushed another commit to fix this

**Comment by poettering** [comment]
ouch!
thanks for the fixes!

**Comment by bluca** [comment]
semaphoreci has a linker issue, seems unrelated

**Comment by keszybz** [comment]
LGTM.

**Comment by bluca** [comment]
> > Missed this while reviewing - but the question is, why didn't all the testsuites fail? Are the various Ubuntu jobs no longer running TEST-50-DISSECT?
> 
> ```
> ========== START: TEST-50-DISSECT ==========
> make: Entering directory '/tmp/autopkgtest.Jkdsml/build.gwl/systemd/test/TEST-50-DISSECT'
> make: Leaving directory '/tmp/autopkgtest.Jkdsml/build.gwl/systemd/test/TEST-50-DISSECT'
> 
> make: Entering directory '/tmp/autopkgtest.Jkdsml/build.gwl/systemd/test/TEST-50-DISSECT'
> make: Leaving directory '/tmp/autopkgtest.Jkdsml/build.gwl/systemd/test/TEST-50-DISSECT'
> ========== END: TEST-50-DISSECT ==========
> ```
> 
> Looks like the test is skipped due to some missing dependencies (mksquashfs/veritysetup/sfdisk).

FYI @mrc0mmand - found out how to install new dependencies for the Ubuntu autopkgtest CI - it's taking the list from the Salsa (Debian) git repository, see this PR for example: https://salsa.debian.org/systemd-team/systemd/-/merge_requests/105

**Pull request merged**
