### PR TITLE
meson: check whether C.UTF-8 exists or not and use it if exists

### LINKED ISSUE #11259: What are the "clear indications" of C.UTF-8 existing soon upstream?
v240 NEWS mentions that systemd now depends on C.UTF-8 "clear indications that upstream
glibc is going to make it available too." I'd like to understand what those indications are, because it's entirely non-obvious to me.

The last time I see this discussed on [libc-alpha](https://sourceware.org/ml/libc-alpha/2015-02/msg00293.html) is 2015. Similarly, there's a proposal on the [glibc wiki](https://sourceware.org/glibc/wiki/Proposals/C.UTF-8) which was added in 2015, but there's been no updates/followup since then.

The wiki page for the glibc 2.29 [release](https://sourceware.org/glibc/wiki/Release/2.29) makes no mention of this new locale, but does mention that glibc is about a month away (Feb 1 2019) from a release. I'd expect that given multiple distros have invented their own C.UTF-8 and that the indications of its upstream inclusion are now clear, that this would be mention-worthy. Cloning the glibc git repo yields no evidence that such a locale has been added.

Indeed, what have I missed in the intervening 3 years? IMO, the news item should have linked to the obvious indicator that this will be coming in a future release of glibc. Otherwise, this just looks like a losing bet to me.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #11259.

cc @falconindy and @poettering.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Looking at the CentOS CI fail - could it be caused by missing `C.UTF-8` locale on CentOS?

CentOS
```
$ localectl list-locales | grep -i "C.UTF8"
es_EC.utf8
```

Fedora 28
```
# localectl list-locales | grep -i "C.UTF8"
C.utf8
en_SC.utf8
es_EC.utf8
```

**Comment by mrc0mmand** [comment]
@yuwata It looks like meson doesn't like the output of `locale -a` (the 1071st byte is `�`, which causes the exception)

```
$ localectl -a
...
bo_IN
bo_IN.utf8
bokmal
bokm�l  <<< 
br_FR
br_FR@euro
...

**Comment by yuwata** [comment]
Updated. Now CentOS CI is green. Now meson chooses the default locale in the following way.
- First try to use C.utf8.
- If it does not exist, then try to use en_US.utf8.
- Both does not exist, then use C.

**Comment by Scimmia22** [comment]
Sounds like CIs need to be fixed, not code

**Comment by yuwata** [comment]
@falconindy and @mbiebl Updated. PTAL. Sorry, the previous comments are disappeared, as they are on the commit instead of this PR...

**Comment by keszybz** [comment]
LGTM. Effectively, this gives us C.UTF-8 if supported, which covers most recent systems, and some reasonable fallbacks otherwise.

**Pull request merged**
