### PR TITLE
Add Schneider SCT101CTM to sensor hwdb

### PR DESCRIPTION
**Pull request by dgatf**
Hello,

Please add Schneider SCT101CTM to sensor hwdb to fix screen orientation

Regards,
Daniel

### CODE REVIEW

**Comment by keszybz** [comment]
```
Traceback (most recent call last):
  File "./agent-control.py", line 388, in <module>
    node, ssid = ac.allocate_node(args.version, args.arch)
  File "./agent-control.py", line 104, in allocate_node
    host = jroot["hosts"][0]
UnboundLocalError: local variable 'jroot' referenced before assignment
Traceback (most recent call last):
  File "./agent-control.py", line 466, in <module>
    ac.free_session(ssid)
NameError: name 'ssid' is not defined
```
@mrc0mmand ?

**Comment by mrc0mmand** [comment]
@keszybz CentOS CI had some intermittent machine pool outages, it should be, hopefully, fixed now.

**Comment by keszybz** [comment]
I meant the other thing: there seem to be various undefined variables in the script (in the error path?).

**Comment by mrc0mmand** [comment]
Ah, now I see it, will fix it asap, thanks!

**Pull request merged**
