### PR TITLE
Tmpfiles special files

### PR DESCRIPTION
**Pull request by keszybz**
For https://github.com/systemd/systemd/issues/181.

### CODE REVIEW

**Comment by kaysievers** [comment]
Instead of adding these magic filesystem-specific files to the C code, can't they move somehow to a config file with a blacklist that we ship? This does not look like the proper maintenance of these exceptions.

**Comment by mbiebl** [comment]
@keszybz I don't think we want to clean lost+found as I mentioned in #181. Imho this directory should be ignored completely

**Comment by keszybz** [comment]
@mbiebl can you provide the justification? As I wrote in https://github.com/systemd/systemd/issues/181#issuecomment-111740770, I don't think we should treat contents of lost+found as special

@kaysievers those special exceptions apply only on mountpoint... We don't have syntax for expressing this in the configuration. We could work on adding more config options and making this configurable, but I don't see why we should. This list of exceptions has been stable since the introduction of that code in 2010.

**Comment by mbiebl** [comment]
@keszybz: if we are going to remove the contents of lost+found during boot for partitions which have been fscked, the user has no chance to recover any data.

**Comment by poettering** [comment]
See my comment on cleaning up lost+found on https://github.com/systemd/systemd/issues/181#issuecomment-111878433

**Comment by poettering** [comment]
First patch looks good, second patch I strongly disagree with. 

I agree with @kaysievers that it would be great to move the lost+found exclusion out of the tool and into the tmpfiles snippets themselves though. But that's something for a separate patch I guess...

**Pull request closed without merging**
