### PR TITLE
README: add a Fossies codespell badge

### PR DESCRIPTION
**Pull request by evverx**
I keep forgetting where the report is. Hopefully the badge will
make it easier to find it. I also fixed several typos codespell
found along the way.

### CODE REVIEW

**Comment by evverx** [comment]
As an aside, Fossies also provides cloc reports. I wonder if a link to https://fossies.org/linux/test/systemd-master.4737345.200529.tar.gz/cloc.html was added somewhere would it help to avoid sensational headlines?
```
github.com/AlDanial/cloc v 1.86  T=2.08 s (1174.4 files/s, 377013.2 lines/s)
--------------------------------------------------------------------------------
Language           files     blank   comment      code    scale   3rd gen. equiv
--------------------------------------------------------------------------------
C                    1015    116295     24566    398520 x   0.77 =      306860.40
XML                   387     18325      2008     81605 x   1.90 =      155049.50
C/C++ Header          699     10648     13482     37663 x   1.00 =       37663.00
Python                 26      1460      6546     17107 x   4.20 =       71849.40
PO File                29      4136      4522     12438 x   1.50 =       18657.00
NAnt script            54      1075         0      9345 x   1.90 =       17755.50
Markdown               38      1415         0      6204 x   1.00 =        6204.00
Bourne Shell          141      1257       552      4621 x   3.81 =       17606.01
HTML                    7       103         3      3058 x   1.90 =        5810.20
Bourne Again Shell      8       337       318      1983 x   3.81 =        7555.23
Perl                    2        69        40      1772 x   4.00 =        7088.00
m4                     13        66         0       893 x   1.00 =         893.00
CSS                     1        15         7       325 x   1.00 =         325.00
XSLT                    2        37        54       266 x   1.90 =         505.40
diff                    1       100       201       201 x   1.00 =         201.00
JSON                    2        13         0       138 x   2.50 =         345.00
awk                     9         0         0        93 x   3.81 =         354.33
YAML                    2         5         2        17 x   0.90 =          15.30
Dockerfile              1         9        12        16 x   2.00 =          32.00
SVG                     2         0         0        16 x   1.00 =          16.00
make                    2         3         0         8 x   2.50 =          20.00
sed                     1         0         0         1 x   4.00 =           4.00
--------------------------------------------------------------------------------
SUM:                2442    155368     52313    576290 x   1.14 =      654809.27
--------------------------------------------------------------------------------
```

**Comment by poettering** [comment]
Hmm, what you mean by sensational headlines?

**Comment by evverx** [comment]
"systemd has 1.5 million lines of code" or something like that :-)

**Comment by poettering** [comment]
sure, we can add a link, but somehow I have my doubts people who want to make sensational headlines would bother to click it ;-)

**Pull request merged**
