### PR TITLE
networkd - keep configuration across shutdown/reboot cycles

### PR DESCRIPTION
**Pull request by cherusk**
This stream is about allowing dhcp leases to be kept in place over system recycles(reboot, shutdown etc.)

It's about amending what was done in:
https://github.com/systemd/systemd/issues/10820

### CODE REVIEW

**Comment by cherusk** [comment]
@yuwata @ssahani backing off from halting the systemd dhcpv4 clients is not enough to prevent leases to be purged over reboots. I've tested that based on latest v245.

In other words, reworking parts coming in with https://github.com/systemd/systemd/pull/12463 is not enough.

Could you give me cues as of why?

**Comment by cherusk** [comment]
Could imagine storing leases state in 

`networkd-link.c:int link_save(Link *link) {`

**Comment by Karlson2k** [comment]
Could you extend the patch to support keeping of non-expired IP for sleep-wakeup cycle?
For me it's even more obvious that IP must be kept in this situation.

**Comment by poettering** [comment]
I don#t get this, and I wonder if this is really desirable.

The thing is /var is generally only available during later boot and might go away early on during shutdown, hence using it for storage for data that is supposed to be used during early boot and late shutdown is problematic. I mean, networkd is a service typically already run in the initrd, hence this sounds not pretty to me at all

**Comment by cherusk** [comment]
@poettering 

> I don#t get this, and I wonder if this is really desirable.

That is a statement as to this PR specifically or to the overarching discussion around it, please?

> 
> The thing is /var is generally only available during later boot and might go away early on during shutdown, hence using it for
 storage for data that is supposed to be used during early boot and late shutdown is problematic. I mean, networkd is a service typically already run in the initrd, hence this sounds not pretty to me at all

Please notice this is in draft and yes, I was staggering when it comes to choosing the right reside. Feel engaged to come forth with better suggestions as to the placing, that is only drafting and not set in stone from my end.

> hence using it for storage for data that is supposed to be used during early boot and late shutdown is problematic. I mean, networkd is a service typically already run in the initrd, hence this sounds not pretty to me at all

Is it, thought it's mostly acting in later stages of the boot process actually. Looking at its unit, am excerpting:

> 
> After=systemd-networkd.socket systemd-udevd.service network-pre.target systemd-sysusers.service systemd-sysctl.service
> Before=network.target multi-user.target shutdown.target
> 

Are you mixing it up with the network-pre.target maybe?

**Comment by cherusk** [comment]
@Karlson2k 

> Could you extend the patch to support keeping of non-expired IP for sleep-wakeup cycle?
> For me it's even more obvious that IP must be kept in this situation.

Title might me misnomer. Am perceiving that if the shutdown cycle is patched to do what I suggest, your case would be covered equally alike.

**Comment by cherusk** [comment]
@poettering 

NB: this patch has not been proven tested working sufficiently yet and is impure. Yet, it sketches the essentially necessary and complements in the explanation of the discussion issue I've created (https://github.com/systemd/systemd/issues/16924)

**Comment by poettering** [comment]
So, doing this might make sense, but it should probably work differently and be an option only. I think in most cases it is better to always start afresh. Specifically, I figure we could have a small helper service that can be enabled on top of networkd, if this is desired. it would be scheduled so that it runs After=var.mount. It's job would be to copy the dhcp lease files from /run to /var during shutdown, and from /var to /run at boot. This needs to be done carefully though, to not accumulate unbounded lease files, and there needs to be a clean way how to ensure networkd rereads the lease files at boot.

Also, given that networkd can run in initrd and early boot (where /var is not accessible) there needs to be a clear logic in place to deal with that, i.e. the saved/restored leases should only be used for interfaces configured later than /var. There probably should be a .network setting to enable this behaviour for a specific interface, which would have the effect of delaying configuration of any matching interface until /var is around.

This would remotely resemble systemd-journald.service vs. systemd-journal-flush.service. The former runs during initrd/early boot, long before /var is around, the latter runs once /var is started, and its job is to tell journald about it.

**Comment by cherusk** [comment]
Let's IPv6 take care of that conundrum eventually. ;)

**Comment by Karlson2k** [comment]
IPv6 is not so widely used as it seems to be.
I know many locations where it's not a problem to find home internet service provider which will offer 1Gbps, but no one provides IPv6. No single ISP.
There are a lot of private networks which will use IPv4-only for decades. 

So it will not be handled by IPv6. IPv6 is not a universal answer.

**Comment by cherusk** [comment]
@Karlson2k there are many transitioning techniques available which you can apply on your perimeter. Staying with IPv4 on the perimeter until ISPs available shouldn't be an issue.

Everything internal to your network can be handled by IPv6. In this context of static leases, SLAAC with its various control variants based on MACs should be universal enough for anyone.

**Comment by Karlson2k** [comment]
@cherusk Yes, everything could be handled by IPv6.
However, if all external connections provide IPv4-only, it makes sense to use IPv4 for internal networks.
It requires much less resource in terms of setup and maintenance. 
So IPv4 will be used for decades just because it's much simpler for many use-cases. You cannot rely on IPv6 ubiquitous availability.

**Pull request closed without merging**
