### PR TITLE
ukify: Only run systemd-measure after adding all sections

### PR DESCRIPTION
**Pull request by daandemeyer**
We were running systemd-measure before adding the sbat section, let's fix that.

### CODE REVIEW

**Comment by medhefgo** [comment]
I will not pretend I understand the measurement stuff, but previously, the .linux section was (deliberately) measured separately while now it would be measured as part of the stub, no?

**Comment by AdrianVovk** [comment]
`--linux` does get passed in twice now:

`+ /usr/lib/systemd/systemd-measure sign --linux=/tmp/linux-signedduj01x9r --osrel=/work/os-release --cmdline=/tmp/tmp.cmdlinekanht1vh --uname=/tmp/tmp.unamez12febyy --pcrpkey=/unit-keys/pubkey.pem --initrd=/tmp/tmp.initrdxz0ukjfp --sbat=/tmp/tmp.sbat1dpv7zj1 --linux=/tmp/linux-signedduj01x9r --private-key=/unit-keys/privkey.pem --public-key=/unit-keys/pubkey.pem --phase=enter-initrd`

**Comment by medhefgo** [comment]
> I see no reason why `--linux` is special-cased in the invocation of systemd-measure. AFAIK the order of arguments doesn't matter. So, I think that can just be dropped, and let `--linux` be added from the section
> 
> Otherwise, the PR _does_ work

I got confused there. This is just the assembly of the section list. The actual appending to the PE stub is still after taking the measurements.

Afaik, .linux is special cased here because it's the only mandatory option (when not building an addon). In fact, I don't think the addon machinery has not been integrated with measurements yet?

**Comment by DaanDeMeyer** [comment]
I pushed an update to make .linux not special, since there doesn't seem to be any particular reason we need to give it custom treatment.

**Review by medhefgo — APPROVED** [review]

**Comment by DaanDeMeyer** [comment]
@bluca Can you bless this as well since you added the sbat stuff?

**Comment by bluca** [comment]
> I pushed an update to make .linux not special, since there doesn't seem to be any particular reason we need to give it custom treatment.

Are we really sure there was no reason for that to be treated differently? Is there anything in the git log/PR that added it to explain that?

**Comment by DaanDeMeyer** [comment]
Turns out there was a good reason, the linux section needs to be the last one so we need to measure and add pcrsig before we add the linux section.

So instead I modified the PR to make sure we add the sbat section before we call systemd-measure.

**Comment by bluca** [comment]
> Turns out there was a good reason, the linux section needs to be the last one so we need to measure and add pcrsig before we add the linux section.
> 
> So instead I modified the PR to make sure we add the sbat section before we call systemd-measure.

thanks for checking, could you please write this down in a comment above the line, so that we are not confused again in 3 months time

**Comment by medhefgo** [comment]
> Turns out there was a good reason, the linux section needs to be the last one so we need to measure and add pcrsig before we add the linux section.

I'm confused. UKI.add_section just puts the sections into a list which is then used by call_systemd_measure to assembly a cmdline. Whether we have linux be part of that list or added manually has no bearing, no?

**Comment by DaanDeMeyer** [comment]
> I'm confused. UKI.add_section just puts the sections into a list which is then used by call_systemd_measure to assemble a sd-measure cmdline. Whether we have linux be part of that list or added manually has no bearing, no?

Not on the measurement no, but it does have an effect when we loop over `uki.sections` in `pe_add_sections()`. If we add the linux section before we call call_systemd_measure(), the pcrsig section is added to the list after the linux section, so the linux section won't be last.

**Comment by medhefgo** [comment]
> Not on the measurement no, but it does have an effect when we loop over `uki.sections` in `pe_add_sections()`. If we add the linux section before we call call_systemd_measure(), the pcrsig section is added to the list after the linux section, so the linux section won't be last.

I see. Maybe the comment should mention that the call will add sections. Or maybe pe_add_sections ought to enforce a section order to remove any brittleness…

**Comment by DaanDeMeyer** [comment]
> I see. Maybe the comment should mention that the call will add sections. Or maybe pe_add_sections (or UKI.add_section) ought to enforce a section order to remove any brittleness…

I'm happy to review improvements, but let's do that in another PR, so that this stays small and easy to backport.

**Pull request merged**
