### PR TITLE
Fix segfault in prioq_remove() with empty Prioq object

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by poettering** [comment]
CI doesn't like this:

330/466 test-prioq                              FAIL     0.12 s (killed by signal 6 SIGABRT)

**Comment by yuwata** [comment]
Added one more fix.

**Comment by poettering** [comment]
CI still doesn't like it:

330/466 test-prioq                              FAIL     0.11 s (killed by signal 6 SIGABRT)

**Comment by yuwata** [comment]
Ugh...

**Comment by yuwata** [comment]
Added one more fix...

**Comment by yuwata** [comment]
BTW, interestingly, the assertion only occurs in ubuntu CIs. On semaphoreCI and my local environment it is not triggered.

**Comment by yuwata** [comment]
Added one more explicit testcase.

**Pull request merged**
