### PR TITLE
Drop kdbus-dependent code

### PR DESCRIPTION
**Pull request by keszybz**
Whatever happens, kdbus is unlikely to come back. Let's drop code which depends on kdbus and is now essentially dead.

### CODE REVIEW

**Comment by yuwata** [comment]
I've created systemd rpms with this PR for fedora (the spec file can be obtained from [here](https://github.com/yuwata/systemd-fedora/tree/custom)). Updating with them causes system crash. After force-poweroff and booting, the system works fine.  Some reexecuting hook are required?
```
Jul 28 17:11:20 sudo[31489]: watanabe : TTY=pts/2 ; PWD=/home/watanabe ; USER=root ; COMMAND=/bin/dnf update
Jul 28 17:11:20 sudo[31489]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 28 17:11:38 dbus-daemon[735]: [session uid=1000 pid=735] Reloaded configuration
Jul 28 17:11:38 dbus-daemon[488]: [system] Reloaded configuration
Jul 28 17:11:38 dbus-daemon[488]: [system] Reloaded configuration
Jul 28 17:11:38 dbus-daemon[488]: [system] Reloaded configuration
Jul 28 17:11:38 polkitd[517]: Reloading rules
Jul 28 17:11:38 polkitd[517]: Collecting garbage unconditionally...
Jul 28 17:11:38 polkitd[517]: Loading rules from directory /etc/polkit-1/rules.d
Jul 28 17:11:38 polkitd[517]: Loading rules from directory /usr/share/polkit-1/rules.d
Jul 28 17:11:38 polkitd[517]: Finished loading, compiling and executing 4 rules
Jul 28 17:11:38 polkitd[517]: Reloading rules
Jul 28 17:11:38 polkitd[517]: Collecting garbage unconditionally...
Jul 28 17:11:38 polkitd[517]: Loading rules from directory /etc/polkit-1/rules.d
Jul 28 17:11:38 polkitd[517]: Loading rules from directory /usr/share/polkit-1/rules.d
Jul 28 17:11:38 polkitd[517]: Finished loading, compiling and executing 4 rules
Jul 28 17:11:38 systemd[1]: Reexecuting.
Jul 28 17:11:39 systemd[1]: systemd 234 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid)
Jul 28 17:11:39 systemd[1]: Detected architecture x86-64.
Jul 28 17:11:40 dbus-daemon[488]: [system] Reloaded configuration
Jul 28 17:11:40 dbus-daemon[488]: [system] Reloaded configuration
Jul 28 17:12:05 dbus-daemon[488]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
Jul 28 17:12:30 dbus-daemon[488]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
Jul 28 17:12:55 dbus-daemon[488]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
Jul 28 17:13:21 dbus-daemon[488]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
Jul 28 17:13:46 dbus-daemon[488]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
Jul 28 17:14:14 dbus-daemon[488]: [system] Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=25000ms)
```

**Comment by keszybz** [comment]
Hmm, my systemd on my laptop crashed too (in the sense that it stopped responding to dbus requests), but I was trying too many other things at the same time to be sure if that was the reason (and other machines seems to work fine...). So yeah, it seems there's some issue with upgrades. Maybe something in the coldplugging / deserialization code?

**Comment by mbiebl** [comment]
Since this PR is now merged, the crash should imho be tracked in a separate bug report and marked as a blocker for v235

**Comment by keszybz** [comment]
Fix waiting in #6476.

**Pull request merged**
