### PR TITLE
Introduce FDPOLL=0 and use it for logind session devices

### LINKED ISSUE #14825: systemd wakes up on mouse movement, wasting CPU
**systemd version the issue has been seen with**

systemd 244 (244.1-1-arch)

**Used distribution**

Arch Linux

**Expected behaviour you didn't see**

init should not wake on mouse input

**Unexpected behaviour you saw**

init consistently uses 0.7-1.3% CPU as during mouse movement when a Wayland compositor is running.

**Steps to reproduce the problem**

1. Use a low-power system, like my i7-8550U (an XPS 13)
2. Run a base Arch install
3. Launch weston or sway
4. Monitor /bin/init in htop
5. Continously wiggle the cursor.

Note that you will also likely see systemd-login waking up, even more than /bin/init. This is due to default `Handle*` configuration of logind, which leads to logind attempting to listen for system buttons on your mouse event device.

Logind event device polling can be disabled by adding the following to logind.conf:
```
HandlePowerKey=ignore
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore
HandleLidSwitchDocked=ignore
```

**More info**

When I attached a debugger I didn't really see systemd doing anything other than waking up from its poll and going back to sleep *a lot*, suggesting it's polling the mouse event device for some reason.

However, extended debugging leads to a dead init and thus a panic for me, so I didn't get that far with the debugging.

### PR DESCRIPTION
**Pull request by kennylevinsen**
This allows services to control whether or not PID1 attempts to poll fd's for automatic removal. Default behavior remains polling.

This allows us to avoid polling of logind's session devices, which in some cases has a non-negligible cost of polling, as logind handles removal of these by itself.

Fixes #14825.

### CODE REVIEW

**Comment by poettering** [comment]
Hmpf. Devices (in particular input) are hotpluggable these days. We poll on the fds to get a POLLERR event if that happens. I'd prefer if we could keep that, because otherwise we'll reference devices that no longer exist for possibly forever.

Isn't this something to fix in the kernel instead? We make very clear that we are not interested in POLLIN nor POLLOUT, hence the kernel should grok that it should never wake up for us except if the device disappears...

**Comment by kennylevinsen** [comment]
Logind already needs to take care of hotplugging, so any issue there would already be a logind bug we'd need to fix for session devices to work right. Unless I misunderstood something, of course.

From the kernel perspective, it's not *that* simple: We are waiting for EPOLLERR and EPOLLHUP, which are entirely regular events with no special meaning, so we're at the mercy of the various driver poll implementations (in this case specifically, evdev).

I'm still looking at the kernel-side (first attempts did not work out, but I do have a new idea). However, no amount of optimization can ever beat doing nothing at all, which is what this PR is about.

**Comment by kennylevinsen** [comment]
I seem to have had success on the kernel side, so I'm trying to push patches through there. We'll see how that goes.

**Comment by kkdwivedi** [comment]
@kennylevinsen, the FDPOLL=0 patch is useful on its own, any chance you can propose that in a separate PR? Sometimes, there are cases where the the pipe has data buffered in it, we store the read end in the manager, and the last write fd is closed. In that case, systemd shouldn't really close the descriptor on POLLHUP, as a future read call on it still allows retrieval of remaining data in the pipe buffer.

**Comment by poettering** [comment]
i think the FDPOLL=0 thing does have merit and sounds like something we probably should have. I just disagreed with the specific usecase in logind...

So if you split this out i'd be happy to review it.

**Comment by kennylevinsen** [comment]
Sure thing. https://github.com/systemd/systemd/pull/15592 contains just the FDPOLL=0 addition, without use in logind. It's also rebased for good measure.

**Pull request closed without merging**
