### PR TITLE
Include and internal struct member fixes.

### PR DESCRIPTION
**Pull request by nwmcsween**
Include and internal struct member fixes. Maybe it should be documented that internal members shouldn't be touched unless there is no other way to do it?

### CODE REVIEW

**Comment by nwmcsween** [comment]
I have no idea why changing direct access to through a macro would cause a build failure, this makes no sense, either I'm missing something or ubunu-ci is broken.

**Comment by zonque** [comment]
Yes, we're still in the process of testing the ubuntu-ci tests. It's likely they'll produce more false positives in near future.

Patch looks sane, thought. Merging.

**Comment by poettering** [comment]
Humm. What's this about precisely? Why would we want to include sys/file.h? We try to keep this minimal, and why would we pull that file in if it's not needed?

**Comment by nwmcsween** [comment]
sys/file.h is needed due to using LOCK_\* uses.

**Comment by poettering** [comment]
Well, but why does it build without it fine?

**Comment by nwmcsween** [comment]
It does because glibc leaks includes e.g. file/sys.h is included in one of the other headers used.

**Pull request merged**
