### PR TITLE
timesync: on network event do not establish connection when NTP servers are not changed

### LINKED ISSUE #8603: systemd-timesyncd executes timesyncs when creating and destroying a Docker container
### Submission type

 - Bug report

I could not find a bugreport here to continue this one https://github.com/coreos/bugs/issues/1707
### systemd version the issue has been seen with

> systemd-238-2-omv2015.0.x86_64

### Used distribution

> OpenMandriva LX and CoreOS

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> each time a docker starts or stops a systemd-timesyncd is restarted

Mar 28 14:03:50 abf.openmandriva.org dockerd[5098]: time="2018-03-28T14:03:50.353923158Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Mar 28 14:03:50 abf.openmandriva.org kernel: veth2de3015: renamed from eth0
Mar 28 14:03:50 abf.openmandriva.org systemd-networkd[1283]: vethbbc1789: Lost carrier
Mar 28 14:03:50 abf.openmandriva.org kernel: docker0: port 16(vethbbc1789) entered disabled state
Mar 28 14:03:50 abf.openmandriva.org systemd-timesyncd[3407]: Network configuration changed, trying to establish connection.
Mar 28 14:03:50 abf.openmandriva.org systemd-timesyncd[3407]: Synchronized to time server 91.224.149.41:123 (2.openmandriva.pool.ntp.org).
Mar 28 14:03:50 abf.openmandriva.org systemd-timesyncd[3407]: Network configuration changed, trying to establish connection.
Mar 28 14:03:50 abf.openmandriva.org systemd-timesyncd[3407]: Synchronized to time server 91.224.149.41:123 (2.openmandriva.pool.ntp.org).
Mar 28 14:03:50 abf.openmandriva.org systemd-timesyncd[3407]: Network configuration changed, trying to establish connection.
Mar 28 14:03:50 abf.openmandriva.org kernel: docker0: port 16(vethbbc1789) entered disabled state
Mar 28 14:03:50 abf.openmandriva.org kernel: device vethbbc1789 left promiscuous mode
Mar 28 14:03:50 abf.openmandriva.org kernel: docker0: port 16(vethbbc1789) entered disabled state
Mar 28 14:03:50 abf.openmandriva.org systemd-timesyncd[3407]: Synchronized to time server 91.224.149.41:123 (2.openmandriva.pool.ntp.org).

### In case of bug report: Steps to reproduce the problem

> …

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #8603.

### CODE REVIEW

**Comment by yuwata** [comment]
I am not sure this is a right way to fix the issue... Please give me a comments.

**Comment by yuwata** [comment]
This may also fix #3888.

**Comment by poettering** [comment]
I like the approach.

**Comment by sitsofe** [comment]
@yuwata @poettering You probably want to reconnect periodically (e.g. if you renew a lease and it's a day or more since you last sync'd NTP) but only doing it once per boot for a stable lease could lead to huge drifts that will never be corrected...

**Comment by yuwata** [comment]
@sitsofe I may misunderstand your comment, but timesyncd sends a request after an interval. I do not think this makes timesyncd do 'it once per boot'.

**Comment by sitsofe** [comment]
@yuwata No you understood perfectly and the misunderstanding was mine! You're entirely correct and your patch does indeed look fine :-).

**Comment by yuwata** [comment]
I am happy to hear that :-)

**Pull request merged**
