### PR TITLE
meson: bump required version

### PR DESCRIPTION
**Pull request by yuwata**
- Fedora
  - Fedora 35: ~~0.62.2 (https://bodhi.fedoraproject.org/updates/FEDORA-2022-6db1b2d367)~~ EOL
  - Fedora 36: 0.62.2 (https://bodhi.fedoraproject.org/updates/FEDORA-2022-6f0e3f2c82)
  - Fedora 37+: 1.0.0

- CentOS
  - 8 with PowerTools repo: 0.58.2 (https://centos.pkgs.org/8-stream/centos-powertools-x86_64/meson-0.58.2-2.el8.noarch.rpm.html)
  - 9 with CRB repo: 0.58.2 (https://centos.pkgs.org/9-stream/centos-crb-x86_64/meson-0.58.2-1.el9.noarch.rpm.html)

- Ubuntu: https://packages.ubuntu.com/search?keywords=meson
  - focal (20.04LTS): 0.53.2-2ubuntu2
  - impish (21.10): 0.57.0+really0.56.2-0.1ubuntu1
  - jammy (22.04LTS): 0.61.2-1

- Debian: https://packages.debian.org/search?keywords=meson
  - bullseye (stable): 0.56.2-1
  - bullseye-backports: 1.0.0-1.1~bpo11+1
  - bookworm (testing): 1.0.0-1.1
  - sid (unstable): 1.0.1-4

### CODE REVIEW

**Comment by bluca** [comment]
This cuts off Focal, for which we are not ready yet, there are seccomp issues on Jammy that need to be investigated. Also Bullseye has 0.56.2, so that's the ceiling till at least mid of next year when Bookworm is released.

**Comment by yuwata** [comment]
> there are seccomp issues on Jammy that need to be investigated.

Is it filed somewhere?

> Also Bullseye has 0.56.2,

I am not familiar, but bullseye-backports cannot be used??

**Comment by bluca** [comment]
> > there are seccomp issues on Jammy that need to be investigated.
> 
> Is it filed somewhere?

Not yet, results are in this PR where I trigger them manually https://github.com/systemd/systemd/pull/23213 need to go back to it at some point

> > Also Bullseye has 0.56.2,
> 
> I am not familiar, but bullseye-backports cannot be used??

That's not enabled by default, we should not add gratuitous friction without a strong reason, as it will trip users and reporters - while these are very nice cleanups to have, there doesn't seem to be anything super-urgent or non-working?

**Comment by keszybz** [comment]
I submitted the first few commits that don't bump the required version as https://github.com/systemd/systemd/pull/23399. Those are nice, and I think we should merge them if nothing breaks.

As for bumping the required version: let's wait until 0.60 is widely available.

**Comment by evverx** [comment]
> let's wait until 0.60 is widely available

@keszybz It's widely available on systems where the latest systemd is usually built. More generally I'm not sure I understand why distributions with outdated dependencies seem to somehow decide what should be used upstream and bring their kludges here along the way. If this stance is "official" it would be great if it was documented somewhere.

**Comment by medhefgo** [comment]
Might as well deal with `FIXME: Use fs.stem() with meson >= 0.54.0` in the main meson file too. :P

I am for bumping the minimum too. Asking bug reporters and other self-compilers that run on older distros to do a `pip install meson` doesn't sound like too much to ask to me. And it's "just" a build-time dependency. It would be a different matter if some library had to be bumped, as that can have runtime issues.

**Comment by bluca** [comment]
> I am for bumping the minimum too. Asking bug reporters and other self-compilers that run on older distros to do a `pip install meson` doesn't sound like too much to ask to me.

It is, though. Apart from the small issue of pip being choke full of malware (https://lwn.net/Articles/834078/) and really best avoided, any and all friction added for newcomers (and backporters) has tangible detrimental effects, so the gains have to be likewise tangible. It seems to me the gains so far are limited to removing some minor and completely inconsequential warnings, that can just be ignored. Or is there some interesting feature you are looking for?

**Comment by eli-schwartz** [comment]
I think it makes sense to have an explicit policy on what you want to support, and if that is "must be able to build on the most recent stable release of Debian without backports" then that's fair and should also apply to non-Meson dependencies, and if that is "must build on any LTS distro from the past X years" then likewise.

And if not, then there's no need to argue about which version to set as a minimum, you can just point to a policy and say "upgrading as per policy, nothing to see here".

**Comment by keszybz** [comment]
→ https://github.com/systemd/systemd/pull/23403

**Comment by evverx** [comment]
@keszybz thanks! That policy doesn't make it clear how to deal with PRs like https://github.com/systemd/systemd/pull/23204 where features are introduced regardless of whether they are supported by the build system or not. It somehow still allows bringing stuff like that without any compatibility layers.

**Comment by yuwata** [comment]
@medhefgo 
> Might as well deal with `FIXME: Use fs.stem() with meson >= 0.54.0` in the main meson file too. :P

Thanks. Addressed.

**Comment by yuwata** [comment]
> > > Also Bullseye has 0.56.2,
> > 
> > I am not familiar, but bullseye-backports cannot be used??
> 
> That's not enabled by default, we should not add gratuitous friction without a strong reason, as it will trip users and reporters - while these are very nice cleanups to have, there doesn't seem to be anything super-urgent or non-working?

But, bullseye does not provide the latest systemd package (currently v247). So, I think we can/should request developers who use Debian bullseye to enable the bullseye-backports repository.
The situation looks I guess similar to CentOS. Packages in CentOS are typically old, and we usually need to enable EPEL repository to build programs from upstream.
The release cycle of Debian is quite slow. We cannot wait for new Debian release to introduce new features.

**Comment by yuwata** [comment]
According to the suggested policy in #23403, we can cut off Ubuntu focal (after #23213), but Ubuntu impish (21.10) needs to be supported...

BTW, what the meaning of the version "0.57.0+really0.56.2-0.1ubuntu1" ???

**Comment by bluca** [comment]
> @bluca
> 
> > > > Also Bullseye has 0.56.2,
> > > 
> > > 
> > > I am not familiar, but bullseye-backports cannot be used??
> > 
> > 
> > That's not enabled by default, we should not add gratuitous friction without a strong reason, as it will trip users and reporters - while these are very nice cleanups to have, there doesn't seem to be anything super-urgent or non-working?
> 
> But, bullseye does not provide the latest systemd package (currently v247). So, I think we can/should request developers who use Debian bullseye to enable the bullseye-backports repository. The situation looks I guess similar to CentOS. Packages in CentOS are typically old, and we usually need to enable EPEL repository to build programs from upstream. The release cycle of Debian is quite slow. We cannot wait for new Debian release to introduce new features.
> 
> Also, meson is just required for building systemd. Not a runtime requirement. Hence, I think we can request an additional repository to develop.

Which feature would you like to introduce?

> According to the suggested policy in #23403, we can cut off Ubuntu focal (after #23213), but Ubuntu impish (21.10) needs to be supported...
> 
> BTW, what the meaning of the version "0.57.0+really0.56.2-0.1ubuntu1" ???

It means something went very wrong and a rollback had to happen, so the second one is the actual version

**Comment by eli-schwartz** [comment]
I think this happens because Debian doesn't have the concept of an epoch or something, so if they upgrade from version 1 to version 2 and then decide that they really need to return to version 1, they call it "2+really1".

**Comment by bluca** [comment]
> I think this happens because Debian doesn't have the concept of an epoch or something, so if they upgrade from version 1 to version 2 and then decide that they really need to return to version 1, they call it "2+really1".

There are epochs, but they are one-way only (can never be removed), so temporary rollbacks use the X+reallyY format to let upgrades work as expected

**Comment by eli-schwartz** [comment]
That is literally the point of an epoch though.

**Comment by bluca** [comment]
For irreversible/permanent changes, yes. Not for reversible/temporary ones. See section 5.6.12.1 of Policy: https://www.debian.org/doc/debian-policy/ch-controlfields.html#epochs-should-be-used-sparingly

**Comment by yuwata** [comment]
> > @bluca
> > > > > Also Bullseye has 0.56.2,
> > > > 
> > > > 
> > > > I am not familiar, but bullseye-backports cannot be used??
> > > 
> > > 
> > > That's not enabled by default, we should not add gratuitous friction without a strong reason, as it will trip users and reporters - while these are very nice cleanups to have, there doesn't seem to be anything super-urgent or non-working?
> > 
> > 
> > But, bullseye does not provide the latest systemd package (currently v247). So, I think we can/should request developers who use Debian bullseye to enable the bullseye-backports repository. The situation looks I guess similar to CentOS. Packages in CentOS are typically old, and we usually need to enable EPEL repository to build programs from upstream. The release cycle of Debian is quite slow. We cannot wait for new Debian release to introduce new features.
> > Also, meson is just required for building systemd. Not a runtime requirement. Hence, I think we can request an additional repository to develop.
> 
> Which feature would you like to introduce?

That's a general argument. Nothing introduced in this PR.

**Comment by keszybz** [comment]
I think the PR is fine, but we can't merge it now or in the near future.

**Comment by yuwata** [comment]
@bluca and @mrc0mmand Is it possible to enable bullseye-backports repository for Semaphore CI??

**Comment by bluca** [comment]
> @bluca and @mrc0mmand Is it possible to enable bullseye-backports repository for Semaphore CI??

Sure, for what purpose? What do you need from it?

**Comment by yuwata** [comment]
> > @bluca and @mrc0mmand Is it possible to enable bullseye-backports repository for Semaphore CI??
> 
> Sure, for what purpose? What do you need from it?

As I said in the previous, the release cycle of Debian is quite slow. I think we should support the Debian stable branch only with stable-backport branch. I am not familiar with the policy of Debian, but I guess the situation is similar for CentOS with EPEL.

**Comment by Conan-Kudo** [comment]
The CentOS Hyperscale SIG builds the latest systemd on CentOS Stream 8 and CentOS Stream 9, so it'd be nice to make sure we can build there too...

**Comment by evverx** [comment]
> The CentOS Hyperscale SIG builds the latest systemd on CentOS Stream 8 and CentOS Stream 9, so it'd be nice to make sure we can build there too...

As far as I understand the policy covers them explicitly so I think they should be fine. It also started covering some architectures explicitly so I guess issues like https://github.com/systemd/systemd/issues/23486 are no longer irrelevant.

**Comment by eli-schwartz** [comment]
> any and all friction added for newcomers (and backporters) has tangible detrimental effects, so the gains have to be likewise tangible. It seems to me the gains so far are limited to removing some minor and completely inconsequential warnings, that can just be ignored. Or is there some interesting feature you are looking for?

I would like to bump to at least 0.54.1 to unblock #24134, which fixes bugs where systemd's meson.build disagrees with the Meson documentation, but in ways that Meson accidentally allows.

**Comment by eli-schwartz** [comment]
Since the only holdup here is CI on focal, and focal is not covered by the support policy in the `README` file, IMHO it makes sense to do like this comment: https://github.com/systemd/systemd/pull/24134#issuecomment-1196434480
> CI is indeed still using Focal. We could backport meson though for CI as we've done in the past via https://launchpad.net/~upstream-systemd-ci

OpenSUSE Leap 15.4 has Meson 0.59, and Leap 15.3 is deprecated and will be EOL in November. If systemd cares about it (my reading of the policy is that 15.3 is NOT supported), that "only" has Meson 0.54.2.

Everywhere else has at least 0.56.2.

I propose to backport 0.56.2 for the focal CI and set that as the minimum version of Meson. Thoughts?

(Again, I only need 0.54.2 for my bugfix PR.)

**Comment by medhefgo** [comment]
#24175 would benefit from 0.60.0 so that the old options can be transparently translated to new ones as well as for feature.require().

**Comment by bluca** [comment]
0.61.2 to be precise

**Comment by yuwata** [comment]
Rebased. PTAL.

**Comment by yuwata** [comment]
I'd like to merge this before -rc1. Setting rc-blocker tag.

**Comment by yuwata** [comment]
(Note, after #27999 is merged, I'd like to replace tools/meson-make-symlink.sh with `install_symlink()`.)

**Comment by yuwata** [comment]
@mrc0mmand Is it possible to upgrade meson on CentOS8 ? On mkosi(CentOS 8) and CentOS CI (CentOS Stream 8),
```
meson.build:3:0: ERROR: Meson version is 0.58.2 but project requires >= 0.60.0
```

**Comment by yuwata** [comment]
Hmm... Also on Debian semaphoreci
```
../meson.build:3:0: ERROR: Meson version is 0.56.2 but project requires >= 0.60.0
```

**Comment by mrc0mmand** [comment]
> @mrc0mmand Is it possible to upgrade meson on CentOS8 ? On mkosi(CentOS 8) and CentOS CI (CentOS Stream 8),
> 
> ```
> meson.build:3:0: ERROR: Meson version is 0.58.2 but project requires >= 0.60.0
> ```

I'm working on update for the CentOS CI C8S job, not sure what to do with the mkosi one, I guess we'd have to use the Hyperscale SIG repo there with meson 0.63.3 (https://sigs.centos.org/hyperscale/content/repositories/main/).

**Comment by mrc0mmand** [comment]
> Hmm... Also on Debian semaphoreci
> 
> ```
> ../meson.build:3:0: ERROR: Meson version is 0.56.2 but project requires >= 0.60.0
> ```

This should be an easy fix, just bump the Debian release from bullseye to bookworm in the runner script:

https://github.com/systemd/systemd/blob/cf4dbd84ac31bbfcab905bc02bf03f67acca7413/.semaphore/semaphore-runner.sh#L9

**Comment by mrc0mmand** [comment]
And just for the record: the CentOS CI's C8S job should now have meson 0.61.3.

**Comment by bluca** [comment]
> > Hmm... Also on Debian semaphoreci
> > ```
> > ../meson.build:3:0: ERROR: Meson version is 0.56.2 but project requires >= 0.60.0
> > ```
> 
> This should be an easy fix, just bump the Debian release from bullseye to bookworm in the runner script:
> 
> https://github.com/systemd/systemd/blob/cf4dbd84ac31bbfcab905bc02bf03f67acca7413/.semaphore/semaphore-runner.sh#L9

yes please change that to bookworm now that it's shipped - meant to do it, and forgot

**Comment by medhefgo** [comment]
> I'm working on update for the CentOS CI C8S job, not sure what to do with the mkosi one, I guess we'd have to use the Hyperscale SIG repo there with meson 0.61.3 (https://sigs.centos.org/hyperscale/content/repositories/main/).

All meson versions can be installed using pip. In fact, I'm wondering if we should force the minimum supported meson version in the build check ci as the meson newer-features warnings don't catch everything.

**Review by bluca — APPROVED** [review]

**Comment by yuwata** [comment]
> > I'm working on update for the CentOS CI C8S job, not sure what to do with the mkosi one, I guess we'd have to use the Hyperscale SIG repo there with meson 0.61.3 (https://sigs.centos.org/hyperscale/content/repositories/main/).
> 
> All meson versions can be installed using pip. In fact, I'm wondering if we should force the minimum supported meson version in the build check ci as the meson newer-features warnings don't catch everything.

If meson does not emit such warnings, then that should be fixed in meson side.

**Comment by yuwata** [comment]
```
dpkg-buildpackage: info: source package systemd 00:50
dpkg-buildpackage: info: source version 253.2909.g5ffa8b5459.0 00:50
dpkg-buildpackage: info: source distribution UNRELEASED 00:50
dpkg-buildpackage: info: source changed by systemd test <pkg-systemd-maintainers@lists.alioth.debian.org> 00:50
 dpkg-source --before-build . 00:50
dpkg-buildpackage: info: host architecture amd64 00:50
dpkg-checkbuilddeps: error: Unmet build dependencies: python3-pyparsing:native 00:50
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting 00:50
dpkg-buildpackage: warning: (Use -d flag to override.) 00:50
blame: ../systemd_253.2909.g5ffa8b5459.0.dsc 00:50
badpkg: rules build failed with exit code 3 00:51
autopkgtest [13:12:24]: ERROR: erroneous package: rules build failed with exit code 3
```

**Comment by bluca** [comment]
> semaphoreci is still red... @bluca @mrc0mmand could you help?
> 
> ```
> dpkg-buildpackage: info: source package systemd 00:50
> dpkg-buildpackage: info: source version 253.2909.g5ffa8b5459.0 00:50
> dpkg-buildpackage: info: source distribution UNRELEASED 00:50
> dpkg-buildpackage: info: source changed by systemd test <pkg-systemd-maintainers@lists.alioth.debian.org> 00:50
>  dpkg-source --before-build . 00:50
> dpkg-buildpackage: info: host architecture amd64 00:50
> dpkg-checkbuilddeps: error: Unmet build dependencies: python3-pyparsing:native 00:50
> dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting 00:50
> dpkg-buildpackage: warning: (Use -d flag to override.) 00:50
> blame: ../systemd_253.2909.g5ffa8b5459.0.dsc 00:50
> badpkg: rules build failed with exit code 3 00:51
> autopkgtest [13:12:24]: ERROR: erroneous package: rules build failed with exit code 3
> ```

that's weird

**Comment by mrc0mmand** [comment]
> > semaphoreci is still red... @bluca @mrc0mmand could you help?
> > ```
> > dpkg-buildpackage: info: source package systemd 00:50
> > dpkg-buildpackage: info: source version 253.2909.g5ffa8b5459.0 00:50
> > dpkg-buildpackage: info: source distribution UNRELEASED 00:50
> > dpkg-buildpackage: info: source changed by systemd test <pkg-systemd-maintainers@lists.alioth.debian.org> 00:50
> >  dpkg-source --before-build . 00:50
> > dpkg-buildpackage: info: host architecture amd64 00:50
> > dpkg-checkbuilddeps: error: Unmet build dependencies: python3-pyparsing:native 00:50
> > dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting 00:50
> > dpkg-buildpackage: warning: (Use -d flag to override.) 00:50
> > blame: ../systemd_253.2909.g5ffa8b5459.0.dsc 00:50
> > badpkg: rules build failed with exit code 3 00:51
> > autopkgtest [13:12:24]: ERROR: erroneous package: rules build failed with exit code 3
> > ```
> 
> that's weird

I think that's https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023442, because https://salsa.debian.org/systemd-team/systemd/-/commit/b7d780064dfee3b42bc11b093a40633b94fd538d is missing from the `upstream-ci` branch that we check out in the test.

**Comment by bluca** [comment]
Ahah the deja-vu was driving me crazy, thanks for finding the connection

**Comment by bluca** [comment]
```
======================================================================
ERROR: test_resolved_domain_restricted_dns (__main__.DnsmasqClientTest.test_resolved_domain_restricted_dns)
resolved: domain-restricted DNS servers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest-lxc.7usn0qco/downtmp/build.9Zf/src/test/networkd-test.py", line 680, in test_resolved_domain_restricted_dns
    out = subprocess.check_output(['resolvectl', 'query', 'math.lab'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['resolvectl', 'query', 'math.lab']' returned non-zero exit status 1.

======================================================================
ERROR: test_resolved_etc_hosts (__main__.DnsmasqClientTest.test_resolved_etc_hosts)
resolved queries to /etc/hosts
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest-lxc.7usn0qco/downtmp/build.9Zf/src/test/networkd-test.py", line 752, in test_resolved_etc_hosts
    out = subprocess.check_output(['resolvectl', 'query', '--type=MX', 'example.com'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['resolvectl', 'query', '--type=MX', 'example.com']' returned non-zero exit status 1.
```

**Comment by bluca** [comment]
> Hmpf, for some reason the Semaphore job is now ~2.5x slower after switching to bookworm, so it's timing out...

semaphore was struggling to even open web pages and load logs earlier when I restarted after fixing the debian branch, so probably just a coincidence

**Comment by bluca** [comment]
> ```
> Jun 15 15:53:38 autopkgtest-lxc-cerudb systemd[1]: Starting Accounts Service...
> Jun 15 15:53:38 autopkgtest-lxc-cerudb (s-daemon)[95]: accounts-daemon.service: Failed to set up mount namespacing: /run/systemd/mount-rootfs/usr/share/accountsservice/interfaces: No such file or directory
> Jun 15 15:53:38 autopkgtest-lxc-cerudb (s-daemon)[95]: accounts-daemon.service: Failed at step NAMESPACE spawning /usr/libexec/accounts-daemon: No such file or directory
> Jun 15 15:53:38 autopkgtest-lxc-cerudb systemd[1]: accounts-daemon.service: Main process exited, code=exited, status=226/NAMESPACE
> Jun 15 15:53:38 autopkgtest-lxc-cerudb systemd[1]: accounts-daemon.service: Failed with result 'exit-code'.
> Jun 15 15:53:38 autopkgtest-lxc-cerudb systemd[1]: Failed to start Accounts Service.
> ```

this one probably needs test changes, the unit changed massively:

https://sources.debian.org/src/accountsservice/0.6.55-3/data/accounts-daemon.service.in/
https://sources.debian.org/src/accountsservice/22.08.8-6/data/accounts-daemon.service.in/

**Comment by yuwata** [comment]
> > ```
> > Jun 15 15:53:38 autopkgtest-lxc-cerudb systemd[1]: Starting Accounts Service...
> > Jun 15 15:53:38 autopkgtest-lxc-cerudb (s-daemon)[95]: accounts-daemon.service: Failed to set up mount namespacing: /run/systemd/mount-rootfs/usr/share/accountsservice/interfaces: No such file or directory
> > Jun 15 15:53:38 autopkgtest-lxc-cerudb (s-daemon)[95]: accounts-daemon.service: Failed at step NAMESPACE spawning /usr/libexec/accounts-daemon: No such file or directory
> > Jun 15 15:53:38 autopkgtest-lxc-cerudb systemd[1]: accounts-daemon.service: Main process exited, code=exited, status=226/NAMESPACE
> > Jun 15 15:53:38 autopkgtest-lxc-cerudb systemd[1]: accounts-daemon.service: Failed with result 'exit-code'.
> > Jun 15 15:53:38 autopkgtest-lxc-cerudb systemd[1]: Failed to start Accounts Service.
> > ```
> 
> this one probably needs test changes, the unit changed massively:
> 
> https://sources.debian.org/src/accountsservice/0.6.55-3/data/accounts-daemon.service.in/ https://sources.debian.org/src/accountsservice/22.08.8-6/data/accounts-daemon.service.in/

@bluca I opened https://salsa.debian.org/systemd-team/systemd/-/merge_requests/198. PTAL.

**Comment by yuwata** [comment]
Finally, semaphoreci is green now! PTAL. The last four commits touches the networkd-test.

**Review by mrc0mmand — APPROVED** [review]

**Pull request merged**
