### PR TITLE
timesync: update to use new-style sd-bus macros

### PR DESCRIPTION
**Pull request by cerebro1**
Hi @bluca , Here is the PR to my short task for Outreachy Contribution. I have build, compiled and run test after making changes by following the HACKING guide. Since this is my first contribution to any open source project, please guide me if this needs any change.

### CODE REVIEW

**Review by yuwata — APPROVED** [review]
LGTM.

**Comment by cerebro1** [comment]
mkosi/ ci failed due to following error :
`Retrieving package gawk-5.1.1-3.6.x86_64 (160/268),   1.4 MiB (  3.6 MiB unpacked)
Retrieving: gawk-5.1.1-3.6.x86_64.rpm [.error]
Download (curl) error for 'http://download.opensuse.org/tumbleweed/repo/oss/x86_64/gawk-5.1.1-3.6.x86_64.rpm':
Error code: HTTP response: 500
Error message: The requested URL returned error: 500 Internal Server Error

Abort, retry, ignore? [a/r/i/...? shows all options] (a): a`

Is there a way i can retry this because i tried downloading via this URL and it's working so probably the error came because download failed somehow when ci was running.

**Comment by cerebro1** [comment]
CentOS CI failed here : 
`
09:51:59 [0;38;5;245mtestsuite-46.service: Job 166 testsuite-46.service/start finished, result=failed[0m
09:51:59 M
[K[[0;1;31mFAILED[0m] Failed to start [0;1;39mTEST-46-HOMED[0m.
09:51:59 [KSee 'systemctl status testsuite-46.service' for details.`

If it is something that my changes are trigerring, is there a way i can login and check further details on how testsuite-46.service failed. 
Since i am really new to all this and just relying on my debugging skill to understand/ask question. i do not intend to make unecessary noise. So one or two line explanation or guide to where to look next will help. Thanks!

**Comment by mrc0mmand** [comment]
> CentOS CI failed here : ` 09:51:59 �[0;38;5;245mtestsuite-46.service: Job 166 testsuite-46.service/start finished, result=failed�[0m 09:51:59 �M �[K[�[0;1;31mFAILED�[0m] Failed to start �[0;1;39mTEST-46-HOMED�[0m. 09:51:59 �[KSee 'systemctl status testsuite-46.service' for details.`
> 
> If it is something that my changes are trigerring, is there a way i can login and check further details on how testsuite-46.service failed. Since i am really new to all this and just relying on my debugging skill to understand/ask question. i do not intend to make unecessary noise. So one or two line explanation or guide to where to look next will help. Thanks!

Hey, don't worry about that one, it's a known issue (and already being worked on). I've restarted the job to, hopefully, make it all green.

**Comment by mrc0mmand** [comment]
> mkosi/ ci failed due to following error : `Retrieving package gawk-5.1.1-3.6.x86_64 (160/268), 1.4 MiB ( 3.6 MiB unpacked) Retrieving: gawk-5.1.1-3.6.x86_64.rpm [.error] Download (curl) error for 'http://download.opensuse.org/tumbleweed/repo/oss/x86_64/gawk-5.1.1-3.6.x86_64.rpm': Error code: HTTP response: 500 Error message: The requested URL returned error: 500 Internal Server Error
> 
> Abort, retry, ignore? [a/r/i/...? shows all options] (a): a`
> 
> Is there a way i can retry this because i tried downloading via this URL and it's working so probably the error came because download failed somehow when ci was running.

Also restarted this one.

**Comment by cerebro1** [comment]
Adding @bluca @anitazha as this PR is for contribution to Outreachy. Thanks!

**Pull request merged**
