### PR TITLE
network: tc: introduce more FQ settings

### PR DESCRIPTION
**Pull request by yuwata**
cc @ssahani.

### CODE REVIEW

**Comment by ssahani** [comment]
I think you need to update the fuzzer
```
543/803 check-help-networkctl                   OK       0.08 s 
5454544/803 check-directives                        FAIL     0.13 s (exit status 1)
5455545/803 fuzz-bus-message:crash-26bba7182dedc8848939931d9fcefcb7922f2e56:address  OK 
```

**Comment by yuwata** [comment]
Ouch!

**Comment by yuwata** [comment]
@ssahani Fixed. PTAL.

**Comment by yuwata** [comment]
@evverx Azure CI fails consistently...

**Comment by yuwata** [comment]
@ssahani ping?

**Comment by ssahani** [comment]
Sorry I am pto. I think it's look good

**Comment by yuwata** [comment]
@ssahani Thanks.

**Pull request merged**
