### PR TITLE
test: do not set default ACL but set ACL for test results

### LINKED ISSUE #19519: TEST-29-PORTABLE fails due to setfacl on testdir
I've bisected the failure in TEST-29-PORTABLE, and (very weirdly) it looks like it was introduced by PR https://github.com/systemd/systemd/pull/19382 or more precisely by this line:

```
setfacl -d -m "user:${SUDO_USER:?}:r-X" "${TESTDIR:?}"
```

https://github.com/systemd/systemd/blob/main/test/test-functions#L2474

The preceding setfacl doesn't seem to cause any issues. Commenting that one line however, is enough to make the test reliably pass, while it is reliably failing right now. Quite bizzarre.

@keszybz any clue what could be going on? Does the test pass for you as well if that line is removed?

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #19519.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @bluca, @keszybz and @mrc0mmand.

**Comment by keszybz** [comment]
LGTM.

**Review by bluca — APPROVED** [review]
Lgtm - thanks for the fix!

**Review by mrc0mmand — APPROVED** [review]
Jumping on the LGTM bandwagon - thanks!

**Comment by keszybz** [comment]
I verified locally that the test passes with the patch.

**Pull request merged**
