### PR TITLE
Allow device tree devices to make use of 60-evdev.rules

### PR DESCRIPTION
**Pull request by agx**
Device tree devices currently have some issues using hwdb since they can't use `dmi/id`. The corresponding thing in DT is the `compatible` of the root node. Add a udev rule to make use of this and as example add the Librem 5's wakup keys to ignore (so this depends on #32261 .

I've split this out as the to get feedback on adding match by device tree compatible. This could be useful for lots of things that so far needed DT changes to export properties relevant for userspace only.

### CODE REVIEW

**Comment by poettering** [comment]
lgtm, but the test suite needs some updating:

```
Failed to parse: 'WAKEUP_KEY_114=0'
Failed to parse: 'WAKEUP_KEY_115=0'
```

**Comment by agx** [comment]
Thanks for having a look. Tests will pass once #32261 landed. I'll rebase then.

**Comment by poettering** [comment]
hmm, i'd prefer if this is merged with at least one matching entry in in hwdb. 

I think it might make sense to just add this as an additional commit to #32261 and merge it together.

**Comment by agx** [comment]
I couldn't make an entry up that is really needed atm but without this 60-evdev.rules is about impossible to use on DT based devices. Having that in would allow us to explore #32261 further out of tree and then come up with more use cases.

**Comment by whot** [comment]
> I couldn't make an entry up that is really needed atm but without this 60-evdev.rules is about impossible to use on DT based devices. Having that in would allow us to explore https://github.com/systemd/systemd/pull/32261 further out of tree and then come up with more use cases.

In https://github.com/systemd/systemd/pull/32261#discussion_r1575804557 I mentioned that rules and hwdb have a "contract" and for your case that is basically down to the hwdb lookup method. So you can have this:

```
$ cat /etc/udev/rules.d/99-wakeup.rules
ACTION=="remove", GOTO="wakeup_end"
KERNEL!="event*", GOTO="wakeup_end"

# Device matching the input device name and device tree compatible
KERNELS=="input*", \
  IMPORT{builtin}="hwdb 'wakeup:name:$attr{name}:dt:$attr{[devicetree/base]compatible}'", \
  ENV{.HAVE_HWDB_PROPERTIES}="1"

# Device matching the modalias string (bustype, vendor, product, version, other properties)
IMPORT{builtin}="hwdb --subsystem=input --lookup-prefix=wakeup:", \
    ENV{.HAVE_HWDB_PROPERTIES}="1"

LABEL="wakeup_end"
```
(Apologies for any typos :smile:)

So basically: have a udev rule (which can be a near-duplicate of 60-evdev.rules) that does things the way you want to. In this case I just renamed `evdev` to `wakeup` for demonstration, your matching hwdb entries the need to have that same prefix:
```
wakeup:atkbd:dmi:bvn*:bvr*:svnPurism:pnLibrem11:*
  BLAH=1
```

Really, neither udev nor the hwdb care about the *content* of the match string or how it's composed, it's a simple "build this string" and "lookup this string as key" with the only special behaviour being the `*` and other wildcards.

If you want a udev rule that calls `date` and then uses the day of the week as hwdb lookup prefix then that is possible (don't ask me for the exact syntax though... but oh, the use-cases!).


So while the addition to `60-evdev.rules` looks correct I agree with @poettering that without a hwdb entry this is just dead weight. And for your current use-case you don't need it added to `60-evdev.rules` (and indeed if the hwdb is outside 60-evdev.hwdb arguably it should have its own rules file anyway).

**Pull request closed without merging**
