### PR TITLE
Revert "Add systemd-resolve backwards compatibility section to resolvectl docs"

### PR DESCRIPTION
**Pull request by poettering**
Reverts systemd/systemd#20064

### CODE REVIEW

**Comment by poettering** [comment]
See https://github.com/systemd/systemd/pull/20064#issuecomment-871566092 for an explanation why I think this should go.

**Comment by ddstreet** [comment]
> See [#20064 (comment)](https://github.com/systemd/systemd/pull/20064#issuecomment-871566092) for an explanation why I think this should go.

I'm fine with reverting it, I just wanted to offer the patch as it's more of an issue for distros where people do tend to be far behind upstream; for example ubuntu has an open bug complaining that there's no manpage for systemd-resolve:
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1894622

and that's not even the oldest long-term supported release for ubuntu, so it will be a couple more years until some people upgrade to that version, and first see 'resolvectl' :)

Honestly I think it would be better to *remove* the backwards compatibility with systemd-resolve at some point, maybe now is the right time?

**Comment by poettering** [comment]
we are pretty agressive with dropping docs for stuff we want to go. We are a lot more conservative with actually dropping compat. Dropping the docs I think is good, as it reduces confusion, and doesn't break stuff. (It admittedly also creates confusion with old timers, but I think it's better to pay that price instead of confusing newcomers).

Isn't the right way for Ubuntu to address this via release notes?

I mean, this is how we handle this: make a big announcement in NEWS. Ideally that should be good enough to ensure google picks it up, so that people looking for it find it. I mean, that's kinda key here, it doesn't really matter where it is documented for people looking for it: as long as google can tell them what happened it's OK I think.

**Comment by poettering** [comment]
I'd probably say we should keep old compat stuff for 5y api-wise (unless it's totally totally broken). we have not reached that point yet with systemd-resolve.

**Comment by ddstreet** [comment]
> we are pretty agressive with dropping docs for stuff we want to go. We are a lot more conservative with actually dropping compat. Dropping the docs I think is good, as it reduces confusion, and doesn't break stuff. (It admittedly also creates confusion with old timers, but I think it's better to pay that price instead of confusing newcomers).
> 
> Isn't the right way for Ubuntu to address this via release notes?
> 
> I mean, this is how we handle this: make a big announcement in NEWS. Ideally that should be good enough to ensure google picks it up, so that people looking for it find it. I mean, that's kinda key here, it doesn't really matter _where_ it is documented for people looking for it: as long as google can tell them what happened it's OK I think.

release notes are ok, but honestly I don't think many end users actually read them. They probably would be able to eventually figure things out by googling 'how to use systemd-resolve' but I think it's also totally reasonable for distros to include deprecation info in man pages, while upstream elides those docs.

@mbiebl indicated in the original pr he'll drop the symlink in Debian soon, so I think it's probably enough for me to simply add this man page symlink and deprecation notice in the older Ubuntu releases, without needing it to be included here upstream or even in Debian.

**Comment by keszybz** [comment]
FWIW, an explanation like this "systemd-resolve is a compat interface, blah blah" cannot cause confusion. It actually helps people who see `systemd-resolve` used in some script, and are unsure what it does. Also, is it just an alias for `resolvectl`? No, it takes different args, etc.

I don't feel very strongly about this, and I wouldn't bother to write such docs myself, but if somebody else does that... why not leave it in.

**Comment by mbiebl** [comment]
Just wanted to add, that the tactic to remove man pages for deprecated/obsolete interfaces doesn't really help in my experience. As long as the tool exists, people will still use it. Case in point: Since I filed the systemd-resolve bugs 5 months ago, I found a new package today which started using it in the mean time.
The only thing that really helps is to actually remove it.

**Comment by poettering** [comment]
I am not arguing that it helps stopping people use it. I just think it helps reducing confusion in newcomers, since browsing the docs will not point them to obsolete interfaces.

**Comment by mbiebl** [comment]
> I am not arguing that it helps stopping people use it. I just think it helps reducing confusion in newcomers, since browsing the docs will not point them to obsolete interfaces

I'm not convinced that shipping no documentation helps to reduce confusion. A typical newcomer most likely uses google, finds a stackoverflow or blog post from 2017, reads some outdated pages about a systemd-resolve tool and starts using. Maybe he then wants to learn more,  checks if there is a man page and will be confused that there is none.

A short man page, saying unambigously that this tool is deprecated/obsolete with some documentation what the replacement is, would help here actually.
I do agree though, that we shouldn't cross-reference the obsolete API/tool from other man pages.

**Comment by keszybz** [comment]
Yeah. The removed text says "`All current and new use should call the binary as <literal>resolvectl</literal>`". I don't see how this can do anything except **reduce** confusion.

**Comment by poettering** [comment]
Let's merge this. I still think we should try to keep our docs free of too much legacy stuff.

i mean, I'd be more comfortable with keeping this, if it at least was a man page of its own, so that only people see it who explicitly look at the man page. But I'd not add noise to the "good" stuff unnecessarily.

**Pull request merged**
