### PR TITLE
Coalesce nearby ftruncate() calls

### PR DESCRIPTION
**Pull request by vcaputo**
My measurements show the ftruncate() per log append to be of significant cost, it doesn't make sense to be performing these on every single journal append.

### CODE REVIEW

**Comment by michich** [comment]
Would you share your measurement results?

**Comment by poettering** [comment]
Broken build...

**Comment by vcaputo** [comment]
@poettering woops, was doing all manual testing and hadn't fixed up all the test cases where function signature changes (also needed to sleep, but wanted to get this PR up regardless so we could get on the same page).

@michich A simple strace of journald while piping logs into it will show the significance ftruncate (strace -c is useful as well), I've also been using some instrumentation of sd-event for measuring distribution of latencies affecting the event loop in journald, you can see the results of this coalesce-ftruncates change alone at the bottom of this gist: 
https://gist.github.com/vcaputo/4291a2b8a6c2f91bd96f

I just put up a PR of the instrumentation changes for sd-event in case you guys are interested in merging it in some form here: https://github.com/systemd/systemd/pull/2147

**Comment by zonque** [comment]
> @michich A simple strace of journald while piping logs into it will show the significance ftruncate (strace -c is useful as well), I've also been using some instrumentation of sd-event for measuring distribution of latencies affecting the event loop in journald, you can see the results of this coalesce-ftruncates change alone at the bottom of this gist:
> https://gist.github.com/vcaputo/4291a2b8a6c2f91bd96f

The content of that gist (or at least an excerpt thereof) should really go into the commit log, so it can be found later.

**Comment by poettering** [comment]
Hmmm, so thinking about this once more: do we actually really need the callback stuff at all? I think it would be sufficient:
1. provide a way to disable the automatic ftruncate() invocation after each write in JournalFile, a simple bool that is added to JournalFile, and defaults to on, but can also be set to off, if the caller wants to post the ftruncate() events on his own.
2. after each invocation of journal_file_append_entry() simply schedule the ftruncate() on our own, by invoking journal_file_post_change() from some timer event. This would mean in write_to_journal() we'd start and manage the timer source directly, without any indirection through callbacks.
3. the timer even source should be stored as "sd_event_source" directly in JournalFile*. The code of sd-journal is linked into the same lib as sd-event anyway, hence trying to isolate sd-event and sd-journal fully is pretty unnecessary. That way, the event source can be easily freed when the JournalFile is destroyed, too.

Let's not forget that journal_file_post_change() is anyway just the last call that is made in journal_file_append_entry(), hence intead of allowing it to be replaced by a callback it's sufficient to optionally just not do it at all, and do it in the caller after the function returned...

I think this would make everything much simpler! Does this make sense?

**Comment by vcaputo** [comment]
Makes sense, I'll put it together.   Though I'm not entirely clear on what you expect for the quiesce_fn in journal_file_rotate(), but I can just migrate quiesce_journal_timer() to journal-file.c and make the rotate call that on the sd_event_source embedded in the JournalFile...  we'll see what it looks like.  At the moment it feels awful dirty.

I guess the quiesce could just be called before rotating.

It just gets dirty in journal_file_rotate() because without having all this state in the constructor, it's not automatically transferred to the replacement JournalFile \* in the course of rotating.  Now we're in the business of copying the members which weren't set via the journal_file_open() that need to be carried across to the new file.

I'm not terribly pleased with this approach.

**Comment by vcaputo** [comment]
closing in favor of https://github.com/systemd/systemd/pull/2318 based on feedback here

**Pull request closed without merging**
