### PR TITLE
Fix delegation in the unified hierarchy + more cgroup work

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Comment by keszybz** [comment]
Looks nice, but no workee ;(

```console
$ cat /etc/systemd/system/user@.service.d/override.conf
[Service]
Delegate=no
Delegate=io pids
$ cat /sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service/cgroup.controllers
io pids
$ ls -l /sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service/cgroup.subtree_control
-rw-r--r--. 1 guest guest 0 Nov 19 13:49 /sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service/cgroup.subtree_control
# so far all good
$ sudo systemd-run --slice=user-1001.slice -p MemoryHigh=20M sleep infinity
$ cat /sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service/cgroup.controllers
io memory pids
```
→ Delegate does not limit the controllers.

**Comment by poettering** [comment]
It's not supposed to limit the controllers, really. It's supposed to configure what's necessary, that's all. or in other words, it's purely additive, not subtractive...

This isn't even a systemd thing, it's a cgroups thing: if you enable a controller for a subtree, then it will be available for *all* its children, not just the one you actually want it for. This means, yes, the controllers will always "propagate" to siblings: if you enable it for a child of user-1001.slice, then it will be on, for *all* children of user-1001.slice, which is what you see here.

This is done because cgroups generally doesn't want to have differently powerful objects immediately below the same cgroup. That has two effects: cgroupsv2 doesn't allow processes and subgroups on the same level, and cgroupsv2 doesn't allow subgroups on the same level that are differently featured, i.e. with different controllers enabled.

This is ultimately why cgroupsv2 has this "subtree_control" thing in place: instead of enabling/disabling a controller for a cgroup itself, it instead enables/disables its dor all immediate children.

Or in other words: what you are seeing shows that everything works as it should. (Or I am totally missing the point you are making?)

**Comment by keszybz** [comment]
So we understood Delegate= differently. I assumed that Delegate is a way to limit privileges of the delegate service, and if e.g. `io` and `cpu` are delegated, the service can use those, and only those controllers on its children. Any other controllers are outside of the control of the service, and all processes in that part of the tree compete against each other.

We *could* achieve that effect by inserting another intermediate cgroup, like I described in https://github.com/systemd/systemd/issues/7355#issue-274316777. OTOH, there is a question of whether limiting available controllers is useful at all. Having extra controllers does give any extra resources to the process, it just allows it to manage them differently. So maybe it's enough to tweak the docs a bit to say that extra controllers might be available above what is listed in Delegate=.

**Comment by poettering** [comment]
Force pushed a new version now. I rebased it, and added another commit, to clarify the Delegate= behaviour as suggested. PTAL.

**Comment by keszybz** [comment]
I'll restart xenial-amd64.

**Pull request merged**
