### PR TITLE
don't reopen socket fds when reloading the daemon

### PR DESCRIPTION
**Pull request by poettering**
Fix for #3171.

### CODE REVIEW

**Comment by zonque** [comment]
I'm afraid warning about the fact is not sufficient, because it requires manual interaction by someone actually reading the log files.

What's the reason for not triggering that `SOCKET_CHOWN` logic implicitly?

**Comment by poettering** [comment]
@zonque well, it requires that anyway. If people change configuration of any unit most settings are left without effect until a restart of that unit, simply because mayn settings cannot be applied at any other time than when starting things. This is particular the case for service units where a ton of settings are only applied at the time we fork off the service. And I think people generally understand that settings such as the command line or environment block are something that only takes effect at the time of starting a service. And for socket units is kinda the same: The various ListenStream=, ListenDatagram= stanzas and suchlike really won't take effect until the socket is actually started, I think people can generally understand that.

hence, conceptually I think the new behaviour is completely OK and understandable. But to make this easier to discover, we also print a warning about this specific case now.

So far, we said that "systemctl daemon-reload" is not supposed to change state of units, but only their configuration. And I think this is a generally good rule. Hence I am pretty sure we shouldn't transition through CHOWN because of the daemon-reload.

Hope this makes sense?

**Comment by evverx** [comment]
> we said that "systemctl daemon-reload" is not supposed to change state of units

We don't change a state, but we change a behaviour:
(note `echo B | nc -U /run/test.socket # Connection refused`. This works fine on current master)

```
bash-4.3# cat <<'EOL' >/run/systemd/system/test.socket
[Unit]
Description=Test socket
[Socket]
Accept=yes
ListenStream=/run/test.socket
SocketGroup=adm
SocketMode=0660
EOL

bash-4.3# cat <<'EOL' > /run/systemd/system/test@.service
[Unit]
Description=Test service
[Service]
StandardInput=socket
ExecStart=/bin/sh -x -c cat
EOL

bash-4.3# systemctl start test.socket

bash-4.3# echo A | nc -U /run/test.socket
+ cat
A

bash-4.3# rm /run/systemd/system/test.socket

bash-4.3# systemctl daemon-reload

bash-4.3# echo B | nc -U /run/test.socket
nc: unix connect failed: Connection refused
```

**Comment by poettering** [comment]
@evverx i am pretty sure it's to be expected that if you remove the unix socket node, that you have to restart the socke tunit to get it back...

**Comment by evverx** [comment]
> note `echo B | nc -U /run/test.socket # Connection refused`. This works fine on current master

Oh, sorry. I was wrong. This doesn't work on current master too.

> i am pretty sure it's to be expected that if you remove the unix socket node, that you have to restart the socke tunit to get it back

I remove the socket unit (`/run/systemd/system/test.socket`), the socket node (`/run/test.socket`) stays there.
I think `systemctl daemon-reload` should recreate the state of the old socket unit. I run `systemctl restart` to apply new settings.

**Comment by poettering** [comment]
@evverx well, but that's not really possible, the old sokcet is really gone if you unlink the file, we cannot recreate its node in the file system, UNIX really doesn't allow this. And I am very sure we shouldn't restart automatically (this creating a completely new, independent socket) since this would hide bugs, and also is a bit weird as any activated app would still have the old socket as fd, but not the new one...

**Comment by martinpitt** [comment]
Indeed the underlying and real bug is that the package in question did not stop the `*.socket` unit upon removal. So from my POV warnings are fine as that's what catches the eye in our role as developers who look at these bug reports. It previously was not at all clear what happened, all of a sudden the socket had the wrong permissions and that was it. Thanks!

**Comment by evverx** [comment]
> but that's not really possible, the old sokcet is really gone if you unlink the file, we cannot recreate its node in the file system

Yeah. But we have all these dbus-properties (`systemctl show test.socket`).
Anyway, seems my question unrelated to this patch:) Sorry for the noise.

**Comment by evverx** [comment]
> The socket unit is not functional until restarted.

How can I determine this automatically?

I have:

```
$ sudo ../../journalctl --directory /var/tmp/systemd-test.2IWyoz/journal/59487c1bc20c44e5b19e5d36242cbf56/ -u testsuite --no-hostname
-- Logs begin at Fri 2016-05-06 15:50:47 UTC, end at Fri 2016-05-06 15:50:48 UTC. --
May 06 15:50:47 systemd[1]: Starting Testsuite service...
May 06 15:50:47 test-socket-group.sh[33]: + set -e
May 06 15:50:47 test-socket-group.sh[33]: + set -o pipefail
May 06 15:50:47 test-socket-group.sh[33]: + U=/run/systemd/system/test.socket
May 06 15:50:47 test-socket-group.sh[33]: + cat
May 06 15:50:47 test-socket-group.sh[33]: + cat
May 06 15:50:47 test-socket-group.sh[33]: + systemctl start test.socket
May 06 15:50:47 test-socket-group.sh[33]: + systemctl is-active test.socket
May 06 15:50:47 test-socket-group.sh[33]: active
May 06 15:50:47 test-socket-group.sh[33]: ++ stat --format=%G /run/test.socket
May 06 15:50:47 test-socket-group.sh[33]: + [[ adm == adm ]]
May 06 15:50:47 test-socket-group.sh[33]: + echo A
May 06 15:50:47 test-socket-group.sh[33]: + nc -U /run/test.socket
May 06 15:50:47 test-socket-group.sh[33]: + cat
May 06 15:50:47 test-socket-group.sh[33]: A
May 06 15:50:47 test-socket-group.sh[33]: + mv /run/systemd/system/test.socket /run/systemd/system/test.socket.disabled
May 06 15:50:47 test-socket-group.sh[33]: + systemctl daemon-reload
May 06 15:50:47 test-socket-group.sh[33]: + systemctl is-active test.socket
May 06 15:50:47 test-socket-group.sh[33]: active
May 06 15:50:47 test-socket-group.sh[33]: ++ stat --format=%G /run/test.socket
May 06 15:50:47 test-socket-group.sh[33]: + [[ adm == adm ]]
May 06 15:50:47 test-socket-group.sh[33]: + nc -U /run/test.socket
May 06 15:50:47 test-socket-group.sh[33]: nc: unix connect failed: Connection refused
May 06 15:50:47 test-socket-group.sh[33]: + echo B
May 06 15:50:47 test-socket-group.sh[33]: /test-socket-group.sh: line 34: echo: write error: Broken pipe
May 06 15:50:47 test-socket-group.sh[33]: + mv /run/systemd/system/test.socket.disabled /run/systemd/system/test.socket
May 06 15:50:47 test-socket-group.sh[33]: + systemctl daemon-reload
May 06 15:50:47 test-socket-group.sh[33]: + systemctl is-active test.socket
May 06 15:50:47 test-socket-group.sh[33]: active
May 06 15:50:47 test-socket-group.sh[33]: + nc -U /run/test.socket
May 06 15:50:47 test-socket-group.sh[33]: nc: unix connect failed: Connection refused
May 06 15:50:47 test-socket-group.sh[33]: + echo C
May 06 15:50:47 test-socket-group.sh[33]: /test-socket-group.sh: line 39: echo: write error: Broken pipe
May 06 15:50:47 test-socket-group.sh[33]: ++ stat --format=%G /run/test.socket
May 06 15:50:47 test-socket-group.sh[33]: + [[ adm == adm ]]
May 06 15:50:47 test-socket-group.sh[33]: + systemctl restart test.socket
May 06 15:50:47 test-socket-group.sh[33]: + systemctl is-active test.socket
May 06 15:50:47 test-socket-group.sh[33]: active
May 06 15:50:47 test-socket-group.sh[33]: + nc -U /run/test.socket
May 06 15:50:47 test-socket-group.sh[33]: + echo D
May 06 15:50:47 test-socket-group.sh[33]: + cat
May 06 15:50:47 test-socket-group.sh[33]: D
May 06 15:50:47 test-socket-group.sh[33]: ++ stat --format=%G /run/test.socket
May 06 15:50:47 test-socket-group.sh[33]: + [[ adm == adm ]]
```

**Comment by poettering** [comment]
> > The socket unit is not functional until restarted.
> 
> How can I determine this automatically?

That's a very good question, and I thought about adding a bus property for that (which we could also show in "systemctl status" output), and even started working on that. However, the thing is that we have tons of options on all types of units that take no immediate effect on a "systemctl daemon-reload", and if we wanted to do this we really should do this properly, and expose a new property on all units that indicates whether there are config changes detected due to a "systemctl daemon-reload" that have not taken effect because the unit was not restarted yet. But that's a lot of work, as that really requires comparing the old config with the new config to determine whether there was any chance. And that requires keeping the old config around in some way (or at least a hash of it). And requires particular care to make this handle settings being added in later versions of systemd nicely.

THis is doable, for example, we could add a new function unit_config_checksum() that generates a checksum of the currently loaded configuration of a specific unit (simply by hashing all the parsed out fields in some way). We'd then store this in the state serializatin across a daemon reload, and after coming back from a reload we'd calculate the checksum again for each unit. If it differs from what we read from the serialization we could mark the unit as requiring a restart.

But I figure that's material for a later PR.

**Comment by evverx** [comment]
> But I figure that's material for a later PR.

OK.

Well, I've created a test: https://github.com/systemd/systemd/pull/3206/files#diff-f45caeea56b3a45a7596b40fc714e651

Test passed!

**Comment by keszybz** [comment]
LGTM. Anyone has any issues with merging?

**Comment by martinpitt** [comment]
LGTM too, and works very nicely. Thanks @poettering!

**Pull request merged**
