### PR TITLE
journal-verfiy: add a couple of missing le64toh() calls

### PR DESCRIPTION
**Pull request by poettering**
Apparently BE users don't verify their journals...

Noticed as result of #6887

### CODE REVIEW

**Comment by rantala** [comment]
This one also?
```
@@ -1109,7 +1110,7 @@ int journal_file_verify(
 
                                 debug(p, "Checking tag %"PRIu64"...", le64toh(o->tag.seqnum));
 
-                                rt = f->fss_start_usec + o->tag.epoch * f->fss_interval_usec;
+                                rt = f->fss_start_usec + le64toh(o->tag.epoch) * f->fss_interval_usec;
                                 if (entry_realtime_set && entry_realtime >= rt + f->fss_interval_usec) {
                                         error(p, "tag/entry realtime timestamp out of synchronization");
                                         r = -EBADMSG;
```

**Comment by keszybz** [comment]
Looks like it.

I tested this on a ppc64be machine, and `journalctl --verify` shows one error before this PR, with this PR, and with this PR + proposed patch. There's always an error on `system.journal`, but this might be because the file is open and being written to. I'm a bit surprised that this PR makes no difference, but it look correct with the proposed patch.

Looks like we really should grow a unit tests where some journal files are generated with `journal-remote-upload` and `journalctl --verify` is run over them.

**Comment by keszybz** [comment]
Yeah, `journalctl --verify` for that file also fails when it is transferred to an le system.

**Comment by poettering** [comment]
Force pushed a new version now, with the one missing conversion added. @rantala thanks for the pointer!

**Comment by keszybz** [comment]
I tested this already before, on BE/LE, and everything seems OK, so let's merge.

**Pull request merged**
