### PR TITLE
Revert "audit-util: return -ENODATA from audit_{session|loginuid}_from_pid() …"

### PR DESCRIPTION
**Pull request by bluca**
Reverts systemd/systemd#35072

Test fails and causes build failures

Fixes https://github.com/systemd/systemd/issues/35249

Alternative to https://github.com/systemd/systemd/pull/35188

### CODE REVIEW

**Comment by bluca** [comment]
The test can be changed, or the entire change can be reverted, I have no opinion on which one is better, am fine with either option, or any other fix anybody else can provide.

**Comment by poettering** [comment]
let's maybe figure out what's actually ongoing instead of some kneejerk revert?

what CI is that? is that a relevant CI platform?

**Comment by bluca** [comment]
> let's maybe figure out what's actually ongoing instead of some kneejerk revert?

https://github.com/systemd/systemd/pull/35250#issuecomment-2488139170

> what CI is that? is that a relevant CI platform?

https://github.com/systemd/systemd/issues/35249

**Comment by yuwata** [comment]
The original issue is fixed by #35306. Closing.

**Pull request closed without merging**
