### PR TITLE
udev-util: add generic device_get_{vendor,model}_string() helpers

### PR DESCRIPTION
**Pull request by poettering**
We chck the same props in various places, add a single implementation of a call to inquire this.

### CODE REVIEW

**Comment by poettering** [comment]
THis is the 2nd commit split out of #29980 in attempt to track down what causes the weird mold issue

**Comment by poettering** [comment]
So this is the commit that seems to be triggering some mold issue.

I am a a bit puzzled by this.

Do we really need to care for mold btw? is anyone actually using this?

**Comment by mrc0mmand** [comment]
Yeah, there's some issue with a combination of clang-15 and mold together with LTO and -O3. This combination works with clang-14 and clang-16 so I wouldn't put all the blame on mold. 

Anyway, since this doesn't seem to be an issue on our side, can you just swap it with `bfd` from the clang-14 job? I.e. this should make CIs happy again (or at least locally it does):

```diff
diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
index c37cdce609..f91ac03066 100644
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -27,8 +27,8 @@ jobs:
         env:
           - { COMPILER: "gcc",   COMPILER_VERSION: "11", LINKER: "bfd",  CRYPTOLIB: "gcrypt"  }
           - { COMPILER: "gcc",   COMPILER_VERSION: "13", LINKER: "mold", CRYPTOLIB: "openssl" }
-          - { COMPILER: "clang", COMPILER_VERSION: "14", LINKER: "bfd",  CRYPTOLIB: "gcrypt"  }
-          - { COMPILER: "clang", COMPILER_VERSION: "15", LINKER: "mold", CRYPTOLIB: "openssl" }
+          - { COMPILER: "clang", COMPILER_VERSION: "14", LINKER: "mold", CRYPTOLIB: "gcrypt"  }
+          - { COMPILER: "clang", COMPILER_VERSION: "15", LINKER: "bfd",  CRYPTOLIB: "openssl" }
           - { COMPILER: "clang", COMPILER_VERSION: "17", LINKER: "lld",  CRYPTOLIB: "auto"    }
     env: ${{ matrix.env }}
     steps:
```

**Review by yuwata — APPROVED** [review]

**Comment by mrc0mmand** [comment]
The CI fail is unrelated (#TEST-29).

**Pull request merged**
