### PR TITLE
network: make link enter failed state when a configuration fails

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by yuwata** [comment]
CI failure is unrelated.
```
TEST SUMMARY:
-------------
PASSED: 34
FAILED: 1
TOTAL:  35

FAILED TASKS:
-------------
TEST-26-SETENV
```

**Comment by ssahani** [comment]
Why this happened any clue ?

**Comment by ssahani** [comment]
cc @keszybz

**Comment by yuwata** [comment]
Some path of configuring address, route or etc., go to failed state, but some do not. E.g., failure in address configuration which is provided by DHCPv4 goes to failed state, but static address does not.
This PR is just for consistency. This should not change anything if everything is fine.

**Comment by ssahani** [comment]
looks nice to me thanks.

**Comment by yuwata** [comment]
> looks nice to me thanks.

@ssahani Thanks. Setting the green label.

**Pull request merged**
