### PR TITLE
Chrooted test fixes

### PR DESCRIPTION
**Pull request by keszybz**
This makes the test pass in mock (on amd64) for me.

I'm also running it on other arches available in Fedora:
https://koji.fedoraproject.org/koji/taskinfo?taskID=19787751.

### CODE REVIEW

**Comment by keszybz** [comment]
`× xenial-amd64`: autopkgtest [01:35:16]: ERROR: erroneous package: Test dependencies are unsatisfiable.
`× xenial-s390x`: the same
`× xenial-i386`: the same

**Comment by keszybz** [comment]
Builds OK in koji:
    buildArch (systemd-233-4.gitf002375.fc27.src.rpm, x86_64)
    buildArch (systemd-233-4.gitf002375.fc27.src.rpm, ppc64le)
    buildArch (systemd-233-4.gitf002375.fc27.src.rpm, aarch64)
    buildArch (systemd-233-4.gitf002375.fc27.src.rpm, ppc64)
    buildArch (systemd-233-4.gitf002375.fc27.src.rpm, i686)
    buildArch (systemd-233-4.gitf002375.fc27.src.rpm, s390x)
    buildArch (systemd-233-4.gitf002375.fc27.src.rpm, armv7hl)

**Comment by yuwata** [comment]
test-login still fails on fedora {25,26,rawhide} mock environment.
```
--- stderr ---
/* Information printed is from the live system */
sd_pid_get_unit(0, …) → "n/a"
sd_pid_get_user_unit(0, …) → "n/a"
sd_pid_get_slice(0, …) → "-.slice"
sd_pid_get_session(0, …): No data available
Seems we are not running in a session, skipping some tests.
Assertion 'r >= 0' failed at ../src/libsystemd/sd-login/test-login.c:209, function test_login(). Aborting.
-------
```

**Comment by yuwata** [comment]
Please see full build.log and rpm spec file.
https://gist.github.com/yuwata/ea0c155a66ad813d6566e03f21054a20

**Comment by martinpitt** [comment]
@kesbyz: Fallout from recent meson related backports; should be fixed now, I retried the tests.

**Comment by keszybz** [comment]
@yuwata Should be fixed by last commit.

**Comment by yuwata** [comment]
@keszybz I've made the almost same patch here.
https://github.com/yuwata/systemd/commit/e9567cdd151e6b040e13245836fa7ba37d647800
The differences are that it also fixes `sd_get_uids()`, and the functions checks that the input parameter is non-NULL as `sd_get_machine_names()` does. These changes are consistent to the man page.

**Comment by keszybz** [comment]
Hmmmm… So it's a bit of a grey area. sd_get_uids would just return the number of users if the output param was NULL. This wasn't documented, but we had tests for it, so we should keep this behaviour (and make `sd_get_machine_names` do that, in a separate commit). It's a quick was to check if there are any users/machines/etc defined, without bothering to deallocate the answer. `get_files_in_directory` already DTRT, so it's only the wrappers in `sd-login.c` that we're adding that should be modified to handle a NULL arg.

**Comment by keszybz** [comment]
Yeah, this seems like the right thing to do. Can you amend you commit to do that?

**Comment by yuwata** [comment]
Updated at https://github.com/yuwata/systemd/commits/test-fix.
I do not know how to push my commits to this PR. Please pick them from the branch.

**Comment by keszybz** [comment]
I changed your commit a bit to return the right value (the size of the filtered array that would be returned, not just the number of files in the directory). Now it's a nice small change. Let's see what the CI thinks.

**Comment by yuwata** [comment]
Thanks, the tests pass on both mock and local environment.

**Pull request merged**
