### PR TITLE
coredump: set ProtectHome to read-only

### PR DESCRIPTION
**Pull request by Ecordonnier**
In https://github.com/systemd/systemd/pull/5283/commits/924453c22599cc246746a0233b2f52a27ade0819 ProtectHome was set to true for systemd-coredump in order to reduce risk, since an attacker could craft a malicious binary in order to compromise systemd-coredump. At that point the object analysis was done in the main systemd-coredump process. Because of this systemd-coredump is unable to product symbolicated call-stacks for binaries running under /home ("n/a" is shown instead of function names).

However, later in https://github.com/systemd/systemd/commit/61aea456c12c54f49c4a76259af130e576130ce9 systemd-coredump was changed to do the object analysis in a forked process, covering those security concerns.

Let's set ProtectHome to read-only so that systemd-coredump produces symbolicated call-stacks for processes running under /home.

### CODE REVIEW

**Comment by Ecordonnier** [comment]
Note that there is a similar situation for binaries running under /tmp, because of "PrivateTmp=yes". However I'm not sure whether you would accept to change this as well.

**Comment by poettering** [comment]
guess we can try this.

**Comment by poettering** [comment]
> Note that there is a similar situation for binaries running under /tmp, because of "PrivateTmp=yes". However I'm not sure whether you would accept to change this as well.

uh, binaries in /tmp/? that's just weird. i doubt we should support thta.

**Comment by Ecordonnier** [comment]
> > Note that there is a similar situation for binaries running under /tmp, because of "PrivateTmp=yes". However I'm not sure whether you would accept to change this as well.
> 
> uh, binaries in /tmp/? that's just weird. i doubt we should support thta.

I work mostly on embedded systems, where /tmp is the only directory which is not read-only. This is why we very often test binaries in /tmp during debugging, and how I noticed the issue.
For desktop distributions however I agree it is not a common use-case.

**Pull request merged**
