### PR TITLE
udev: path-id - include fc_host's port_name in device persistent path

### PR DESCRIPTION
**Pull request by mfoliveira**
With the Fibre Channel NPIV (N_Port ID Virtualization) feature,
a single physical N_Port (e.g., PCI address) can have multiple
N_Port IDs (e.g., different fc_host nodes) - which can connect
to the same target LUN (e.g., fc_remote_port's port_name and
LUN number).

Thus, in order to be unique, the device persistent path should
include the fc_host's port_name (in addition to the already in
use PCI address, fc_remote_port's port_name and LUN number).

The patch adds the analogous logic to that used for targetdev/
fcdev/port, now for hostdev/fchostdev/hostport, then includes
"fc-hostport" in the path string.

Built, checked, tested on RHEL Server 7.1 with no regressions.

Example (non-unique links for PCI address/port_name/lun-number):

  # for sd in /dev/sd...; do
      udevadm info $sd | grep ^S: | grep by-path
    done
  S: disk/by-path/pci-0001:09:00.0-fc-0x500507680b2255fe-lun-0
  S: disk/by-path/pci-0001:09:00.0-fc-0x500507680b2255ff-lun-0
  S: disk/by-path/pci-0001:09:00.0-fc-0x500507680b2255ff-lun-0
  S: disk/by-path/pci-0001:09:00.0-fc-0x500507680b2255fe-lun-0

  # ... | sort -u
  S: disk/by-path/pci-0001:09:00.0-fc-0x500507680b2255fe-lun-0
  S: disk/by-path/pci-0001:09:00.0-fc-0x500507680b2255ff-lun-0

Example (with patch, unique links include fc_host's port_name):

  # for sd in /dev/sd...; do
      udevadm info $sd | grep ^S: | grep by-path
    done
  S: disk/by-path/pci-0001:09:00.0-fc-0x5001a4aaf00a6785-fc-0x500507680b2255fe-lun-0
  S: disk/by-path/pci-0001:09:00.0-fc-0x5001a4aaf00a6785-fc-0x500507680b2255ff-lun-0
  S: disk/by-path/pci-0001:09:00.0-fc-0x5001a4ad99d8c2de-fc-0x500507680b2255ff-lun-0
  S: disk/by-path/pci-0001:09:00.0-fc-0x5001a4ad99d8c2de-fc-0x500507680b2255fe-lun-0

  # cat /sys/class/fc_host/host{8,9}/port_name
  0x5001a4aaf00a6785
  0x5001a4ad99d8c2de

Signed-off-by: Mauricio Faria de Oliveira mauricfo@linux.vnet.ibm.com

### CODE REVIEW

**Comment by poettering** [comment]
Please see #2500.

Please find a place for this in some package maintained by storage people, we cannot maintain this upstream, we have no understanding of this stuff.

**Comment by mfoliveira** [comment]
Hi @poettering

Sure, that's certainly understandable.

Wondering if @hreinecke can review/comment, as he's mentioned in the header, if that helps with any reassurance.

Thanks

**Comment by hreinecke** [comment]
And you propose ... what?
Remove path_id from udev/systemd package?

**Comment by hreinecke** [comment]
'tis a bit odd, seeing that udev is the sole consumer of the path_id program.

**Comment by arvidjaar** [comment]
This patch invalidates "by-path" design for physical HBA. Before this patch replacing one FC HBA with another would still produce the same by-path alias because physical connection point did not change. After this patch replacing FC HBA will change by-path alias. "By-path" aliases are intended to describe topology, not property of individual components.

This probably should leave physical by-path aliases as is, and only create additional label for true vports, may be using "vport" prefix to clearly mark them. I.e. 

```
disk/by-path/pci-0001:09:00.0-fc-0x500507680b2255fe-lun-0
disk/by-path/pci-0001:09:00.0-vport-0x5001a4ad99d8c2de-fc-0x500507680b2255ff-lun-0
```

At lease with Emulex^WAvago you always need WWNN/WWPN to create new vport, so WWPN persistently identifies vport.

**Comment by msekletar** [comment]
FWIW, in RHEL/CentOS we merged patch for `path_id` proposed in #2500. We should probably close this PR as duplicate of the former.

**Comment by hreinecke** [comment]
Yep; this is a better solution than a wholesale change.
Which we cannot do, as the links are meant to be _persistent_, so we cannot change existing ones.

**Comment by kaysievers** [comment]
The tools scsi_id, ata_id, , cdr_id, the storage part of path_id are all in maintenance mode and will not get any features merged. Only obvious bugs will be applied, nothing that changes any naming or extends functionality.

Someone with knowlegde in that area should move them to a _separate_ package that can be maintained outside of systemd/udev. Hannes worked on moving parts of scsi_id to sg3_utils, finishing that would be the first step I assume.

Closing this pull request, for the above mentioned reasons.

**Comment by mfoliveira** [comment]
@arvidjaar 

Got it; thanks for the explanation.

@msekletar

Nice to know; that'd be enough for me at this time.

@hreinecke 

Thanks for the review.

**Pull request closed without merging**
