### PR TITLE
cpu-set-util: use %d-%d format in  cpu_set_to_range_string() only for actual ranges

### PR DESCRIPTION
**Pull request by msekletar**

### CODE REVIEW

**Comment by msekletar** [comment]
I noticed that we produce "0-0" range for a ```CPUSet``` with single cpu in set. IIRC @poettering explicitly didn't want that.

**Comment by keszybz** [comment]
That *was* on purpose: this makes it possible to clearly distinguish e.g. `CPUAffinity=11` (cpus `#1` and `#0` set in the old syntax), from CPUAffinity=11-11 (cpu `#11` set in the new syntax).

**Comment by msekletar** [comment]
With old output the array was printed byte-by-byte, hence for cpu ```#0``` and cpu``` #1``` would would be something like ```CPUAffinity=300000000000000000000000000000000``` (probably a lot more zeroes, on BE machine it would be in reverse).

Moreover output string was *always* extremely long (much much longer than CPUAffinity=8191 which is currently the longest you can get for single CPU, given that kernel supports only 8k cpus at max).

To be quite honest we already changed how all this works too much so IMHO we should stop pretending to care about backward compat (*in this specific case*) and make thinks actually usable.

**Comment by keszybz** [comment]
OK, you have a point. That's easy enough to distinguish in practice.

**Pull request merged**
