### PR TITLE
analyze: fix segfault when malloc() fails

### LINKED ISSUE #21872: systemd-analyze: segfault when malloc() fails
**systemd version the issue has been seen with**
 > latest main

**Used distribution**
 > F34

The same scenario as in #21867.

```
...
Out of memory.                                                                                                                                                                                                   
Out of memory                                                                                           
/usr/lib/systemd/system/sshd.service:4: Failed to add dependency on network.target, ignoring: Cannot allocate memory                                                                                             
./run_command.sh: line 47:   583 Segmentation fault      (core dumped) LD_PRELOAD=build/libtest_malloc_fail.so "$@"                                                                                              
Command '/home/fsumsal/repos/@systemd/systemd/build/systemd-analyze verify sshd.service' failed with MALLOC_FAIL_AT=2617                                                                                         
Reproducer: MALLOC_FAIL_AT=2617 LD_PRELOAD=build/libtest_malloc_fail.so /home/fsumsal/repos/@systemd/systemd/build/systemd-analyze verify sshd.service   

$ MALLOC_FAIL_AT=2617 LD_PRELOAD=build/libtest_malloc_fail.so /home/fsumsal/repos/@systemd/systemd/build/systemd-analyze verify sshd.service                                                                     
/usr/lib/systemd/system/sshd.service:4: Failed to add dependency on network.target, ignoring: Cannot allocate memory                                                                                             
Segmentation fault (core dumped)      
```

```
Core was generated by `/home/fsumsal/repos/@systemd/systemd/build/systemd-analyze verify sshd.service'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f277a5fb9b7 in hash_key (h=0xffffffffffffffff) at ../src/basic/hashmap.c:331
331	        return h->has_indirect ? h->indirect.hash_key
```
```gdb
(gdb) bt full
#0  0x00007f277a5fb9b7 in hash_key (h=0xffffffffffffffff) at ../src/basic/hashmap.c:331
No locals.
#1  0x00007f277a5fba00 in base_bucket_hash (h=0xffffffffffffffff, p=0x1507860) at ../src/basic/hashmap.c:339
        state = {v0 = 0, v1 = 0, v2 = 2055337440, v3 = 22045272, padding = 140721615142912, inlen = 0}
        hash = 0
#2  0x00007f277a5fe1d3 in _hashmap_contains (h=0xffffffffffffffff, key=0x1507860) at ../src/basic/hashmap.c:1384
        hash = 32551
#3  0x00007f277a5fb7ea in set_contains (s=0xffffffffffffffff, key=0x1507860) at ../src/basic/set.h:43
No locals.
#4  0x00007f277a5ff668 in _set_put_strdup_full (s=0x7ffc4de25950, hash_ops=0x623600 <string_hash_ops_free@SD_SHARED>, p=0x1507860 "sshd.service") at ../src/basic/hashmap.c:1855
        c = 0x151e860 "/usr/lib/systemd/system/sshd.service"
        r = 0
        __PRETTY_FUNCTION__ = "_set_put_strdup_full"
#5  0x000000000042ee01 in log_syntax_callback (unit=0x1507860 "sshd.service", level=4, userdata=0x7ffc4de25950) at ../src/analyze/analyze-verify.c:29
        s = 0x7ffc4de25950
        r = 32551
        __PRETTY_FUNCTION__ = "log_syntax_callback"
#6  0x00007f277a60de80 in log_syntax_internal (unit=0x1507860 "sshd.service", level=4, config_file=0x151e860 "/usr/lib/systemd/system/sshd.service", config_line=4, error=-12, file=0x5b8d96 "src/core/load-fragment.c", line=286, func=0x5bc190 <__func__.206> "config_parse_unit_deps", format=0x5b9438 "Failed to add dependency on %s, ignoring: %m") at ../src/basic/log.c:1369
        _saved_errno_ = 12
        buffer = "Failed to add dependency on network.target, ignoring: Cannot allocate memory\000\000\000\000\000\020\000\000\000\000\000\000\020H\342M\374\177\000\000@\\P\001\000\000\000\000\337\061\203z'\177\000\000\226\304xz'\177\000\000\000\020\000\000\000\000\000\000P6P\001\000\000\000\000@\\P\001\000\000\000\000\027\000\000\000\000\000\000\000\215\213\031z'\177\000\000#\000\000\000\000\000\000\000\300\003\000\000\000\000\000\000\001\000\000\000\000\000\000\000\264\201", '\000' <repeats 22 times>...
        ap = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffc4de25080, reg_save_area = 0x7ffc4de24f90}}
        unit_fmt = 0x7f277a788ed3 "USER_UNIT=%s"
#7  0x0000000000476462 in config_parse_unit_deps (unit=0x1507860 "sshd.service", filename=0x151e860 "/usr/lib/systemd/system/sshd.service", line=4, section=0x1539ab0 "Unit", section_line=1, lvalue=0x1538a50 "After", ltype=15, rvalue=0x1538a56 "network.target sshd-keygen.target", data=0x1508000, userdata=0x1508000) at ../src/core/load-fragment.c:286
        _level = 4
        _e = -12
        word = 0x1539ad0 "sshd-keygen.target"
        k = 0x1539c30 "sshd-keygen.target"
        r = -12
        p = 0x0
        d = UNIT_AFTER
        u = 0x1508000
        __PRETTY_FUNCTION__ = "config_parse_unit_deps"
        __func__ = "config_parse_unit_deps"
#8  0x00007f277a4c270c in next_assignment (unit=0x1507860 "sshd.service", filename=0x151e860 "/usr/lib/systemd/system/sshd.service", line=4, lookup=0x7f277a4c2154 <config_item_perf_lookup>, table=0x51c391 <load_fragment_gperf_lookup>, section=0x1539ab0 "Unit", section_line=1, lvalue=0x1538a50 "After", rvalue=0x1538a56 "network.target sshd-keygen.target", flags=0, userdata=0x1508000) at ../src/shared/conf-parser.c:137
        func = 0x47601a <config_parse_unit_deps>
        ltype = 15
        data = 0x1508000
        r = 1
        __PRETTY_FUNCTION__ = "next_assignment"
        __func__ = "next_assignment"
#9  0x00007f277a4c2fad in parse_line (unit=0x1507860 "sshd.service", filename=0x151e860 "/usr/lib/systemd/system/sshd.service", line=4, sections=0x5c8cea "Unit", lookup=0x7f277a4c2154 <config_item_perf_lookup>, table=0x51c391 <load_fragment_gperf_lookup>, flags=0, section=0x7ffc4de253f0, section_line=0x7ffc4de25390, section_ignored=0x7ffc4de2538d, l=0x1538a50 "After", userdata=0x1508000) at ../src/shared/conf-parser.c:244
        e = 0x1538a56 "network.target sshd-keygen.target"
        __PRETTY_FUNCTION__ = "parse_line"
        __func__ = "parse_line"
#10 0x00007f277a4c3987 in config_parse (unit=0x1507860 "sshd.service", filename=0x151e860 "/usr/lib/systemd/system/sshd.service", f=0x1503650, sections=0x5c8cea "Unit", lookup=0x7f277a4c2154 <config_item_perf_lookup>, table=0x51c391 <load_fragment_gperf_lookup>, flags=0, userdata=0x1508000, ret_stat=0x0) at ../src/shared/conf-parser.c:387
        buf = 0x1538a50 "After"
        escaped = false
        e = 0x1538a77 ""
        l = 0x1538a50 "After"
        p = 0x1538a50 "After"
        section = 0x1539ab0 "Unit"
        continuation = 0x0
        ours = 0x0
        line = 4
        section_line = 1
        section_ignored = false
        bom_seen = false
        st = {st_dev = 35, st_ino = 1058528, st_nlink = 1, st_mode = 33188, st_uid = 0, st_gid = 0, __pad0 = 0, st_rdev = 0, st_size = 372, st_blksize = 4096, st_blocks = 8, st_atim = {tv_sec = 1640201257, tv_nsec = 889145207}, st_mtim = {tv_sec = 1632921772, tv_nsec = 0}, st_ctim = {tv_sec = 1635441847, tv_nsec = 705714030}, __glibc_reserved = {0, 0, 0}}
        r = 40
        fd = 6
        __PRETTY_FUNCTION__ = "config_parse"
        __func__ = "config_parse"
#11 0x0000000000490584 in unit_load_fragment (u=0x1508000) at ../src/core/load-fragment.c:6118
        f = 0x1503650
        st = {st_dev = 35, st_ino = 1058528, st_nlink = 1, st_mode = 33188, st_uid = 0, st_gid = 0, __pad0 = 0, st_rdev = 0, st_size = 372, st_blksize = 4096, st_blocks = 8, st_atim = {tv_sec = 1640201257, tv_nsec = 889145207}, st_mtim = {tv_sec = 1632921772, tv_nsec = 0}, st_ctim = {tv_sec = 1635441847, tv_nsec = 705714030}, __glibc_reserved = {0, 0, 0}}
        fragment = 0x151e860 "/usr/lib/systemd/system/sshd.service"
        names = 0x1506220
        r = 1
        __PRETTY_FUNCTION__ = "unit_load_fragment"
        __func__ = "unit_load_fragment"
        id = 0x1508000 "\260SP\001"
        free_id = 0x44e3c5 <numa_policy_reset+84> "H\213E\370", <incomplete sequence \307>
        merged = 0x1503650
#12 0x0000000000505475 in unit_load_fragment_and_dropin (u=0x1508000, fragment_required=true) at ../src/core/unit.c:1398
        r = 0
        __PRETTY_FUNCTION__ = "unit_load_fragment_and_dropin"
#13 0x00000000004bc44c in service_load (u=0x1508000) at ../src/core/service.c:792
        s = 0x1508000
        r = 0
#14 0x0000000000506334 in unit_load (u=0x1508000) at ../src/core/unit.c:1624
        r = 32
        __PRETTY_FUNCTION__ = "unit_load"
        __func__ = "unit_load"
#15 0x000000000049b983 in manager_dispatch_load_queue (m=0x15053b0) at ../src/core/manager.c:2051
        u = 0x1508000
        n = 0
        __PRETTY_FUNCTION__ = "manager_dispatch_load_queue"
#16 0x000000000049be4a in manager_load_unit (m=0x15053b0, name=0x0, path=0x15074f0 "/home/fsumsal/repos/test-malloc-fail/sshd.service", e=0x7ffc4de25870, _ret=0x7ffc4de25868) at ../src/core/manager.c:2181
        r = 0
        __PRETTY_FUNCTION__ = "manager_load_unit"
#17 0x000000000049bec5 in manager_load_startable_unit_or_warn (m=0x15053b0, name=0x0, path=0x15074f0 "/home/fsumsal/repos/test-malloc-fail/sshd.service", ret=0x7ffc4de258b0) at ../src/core/manager.c:2199
        error = {name = 0x0, message = 0x0, _need_free = 0}
        unit = 0x1508000
        r = 0
        __PRETTY_FUNCTION__ = "manager_load_startable_unit_or_warn"
        __func__ = "manager_load_startable_unit_or_warn"
#18 0x0000000000430648 in verify_units (filenames=0x1504f80, scope=UNIT_FILE_SYSTEM, check_man=true, run_generators=false, recursive_errors=RECURSIVE_ERRORS_YES, root=0x0) at ../src/analyze/analyze-verify.c:302
        prepared = 0x15074f0 "/home/fsumsal/repos/test-malloc-fail/sshd.service"
        flags = 5
        m = 0x15053b0
        s = 0xffffffffffffffff
        dummy = {_empty = 0x7ffc4de25984}
        units = {0x7ffc4de259b0}
        var = 0x1504f40 ".::"
        r = 0
        k = 0
        i = 32764
        count = 0
        filename = 0x1504f80
        __PRETTY_FUNCTION__ = "verify_units"
        __func__ = "verify_units"
#19 0x000000000042addd in do_verify (argc=2, argv=0x7ffc4de25ca0, userdata=0x0) at ../src/analyze/analyze.c:2386
        filenames = 0x1504f80
        tempdir = 0x1505110 "/tmp/systemd-analyze-Atgkgf"
        r = 0
        __PRETTY_FUNCTION__ = "do_verify"
        __func__ = "do_verify"
#20 0x00007f277a5c1f74 in dispatch_verb (argc=3, argv=0x7ffc4de25ca0, verbs=0x5a7d20 <verbs>, userdata=0x0) at ../src/shared/verbs.c:103
        verb = 0x5a7fe0 <verbs+704>
        name = 0x7ffc4de270f4 "verify"
        left = 2
        __PRETTY_FUNCTION__ = "dispatch_verb"
        __func__ = "dispatch_verb"
#21 0x000000000042cd7a in run (argc=3, argv=0x7ffc4de25c98) at ../src/analyze/analyze.c:2883
        loop_device = 0x0
        decrypted_image = 0x0
        unlink_dir = 0x0
        verbs = {{verb = 0x5a5d12 "help", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x42b27c <help>}, {verb = 0x5a438a "time", min_args = 4294967295, max_args = 1, flags = VERB_DEFAULT, dispatch = 0x425184 <analyze_time>}, {verb = 0x5a7c30 "blame", min_args = 4294967295, max_args = 1, flags = 0, dispatch = 0x424dd9 <analyze_blame>}, {verb = 0x5a7c36 "critical-chain", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x424b6a <analyze_critical_chain>}, {verb = 0x5a7c45 "plot", min_args = 4294967295, max_args = 1, flags = 0, dispatch = 0x422343 <analyze_plot>}, {verb = 0x5a5f1e "dot", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x4259e0 <dot>}, {verb = 0x5a7c4a "log-level", min_args = 4294967295, max_args = 2, flags = 0, 
            dispatch = 0x4267a4 <verb_log_control>}, {verb = 0x5a7c54 "log-target", min_args = 4294967295, max_args = 2, flags = 0, dispatch = 0x4267a4 <verb_log_control>}, {verb = 0x5a7c5f "set-log-level", min_args = 2, max_args = 2, flags = 0, dispatch = 0x4267a4 <verb_log_control>}, {verb = 0x5a7c6d "get-log-level", min_args = 4294967295, max_args = 1, flags = 0, dispatch = 0x4267a4 <verb_log_control>}, {verb = 0x5a7c7b "set-log-target", min_args = 2, max_args = 2, flags = 0, dispatch = 0x4267a4 <verb_log_control>}, {verb = 0x5a7c8a "get-log-target", min_args = 4294967295, max_args = 1, flags = 0, dispatch = 0x4267a4 <verb_log_control>}, {verb = 0x5a7c99 "service-watchdogs", min_args = 4294967295, max_args = 2, flags = 0, dispatch = 0x42a7b8 <service_watchdogs>}, {verb = 0x5a7cab "dump", min_args = 4294967295, 
            max_args = 1, flags = 0, dispatch = 0x4262b4 <dump>}, {verb = 0x5a5f7d "cat-config", min_args = 2, max_args = 4294967295, flags = 0, dispatch = 0x4265d0 <cat_config>}, {verb = 0x5a7cb0 "unit-files", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x4268f4 <do_unit_files>}, {verb = 0x5a5f22 "unit-paths", min_args = 1, max_args = 1, flags = 0, dispatch = 0x426d2f <dump_unit_paths>}, {verb = 0x5a7cbb "exit-status", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x426ecd <dump_exit_status>}, {verb = 0x5a7cc7 "syscall-filter", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x427e2b <dump_syscall_filters>}, {verb = 0x5a7cd6 "capability", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x42741d <dump_capabilities>}, {
            verb = 0x5a7ce1 "filesystems", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x428991 <dump_filesystems>}, {verb = 0x5a6002 "condition", min_args = 4294967295, max_args = 4294967295, flags = 0, dispatch = 0x42aba1 <do_condition>}, {verb = 0x5a5f2d "verify", min_args = 2, max_args = 4294967295, flags = 0, dispatch = 0x42abf9 <do_verify>}, {verb = 0x5a7ced "calendar", min_args = 2, max_args = 4294967295, flags = 0, dispatch = 0x42a6fd <test_calendar>}, {verb = 0x5a7cf6 "timestamp", min_args = 2, max_args = 4294967295, flags = 0, dispatch = 0x4298cd <test_timestamp>}, {verb = 0x5a7d00 "timespan", min_args = 2, max_args = 4294967295, flags = 0, dispatch = 0x428c13 <dump_timespan>}, {verb = 0x5a41bb "security", min_args = 4294967295, max_args = 4294967295, flags = 0, 
            dispatch = 0x42ae13 <do_security>}, {verb = 0x5a5e94 "inspect-elf", min_args = 2, max_args = 4294967295, flags = 0, dispatch = 0x42b234 <do_elf_inspection>}, {verb = 0x0, min_args = 0, max_args = 0, flags = 0, dispatch = 0x0}}
        r = 1
        __PRETTY_FUNCTION__ = "run"
        __func__ = "run"
#22 0x000000000042cded in main (argc=3, argv=0x7ffc4de25c98) at ../src/analyze/analyze.c:2886
        r = 0
```

/cc @bluca

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #21872.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @bluca and @mrc0mmand

**Review by mrc0mmand — APPROVED** [review]
Can't reproduce the issue anymore, LGTM, thanks!

**Review by bluca — APPROVED** [review]
That was really quick, thanks!

**Comment by keszybz** [comment]
I don't understand this. Why is `*s == POINTER_MAX` ?

**Comment by bluca** [comment]
In case the set_strdup after the check fails I guess

**Comment by keszybz** [comment]
Ah, OK, that functions sets is itself. It would be nice to have that as part of the commit message.

**Pull request merged**
