### PR TITLE
semaphore: pass allow-releaseinfo-change to apt-get

### PR DESCRIPTION
**Pull request by evverx**
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929248

### CODE REVIEW

**Comment by evverx** [comment]
@mbiebl now that Debian Buster has been released, could you change the script so that it would point to the right branch as suggested in 21f0c55a2c26f06b01005?

**Comment by evverx** [comment]
`apt-get` no longer fails so it seems to be working. I'll go ahead and merge the PR to unbreak Semaphore.

**Comment by evverx** [comment]
Interestingly, Ubuntu CI wasn't triggered. I took a look at the "webhooks" page and it says "We couldn’t deliver this payload: Service Timeout". As far as I can tell, https://github.com/systemd/systemd/pull/12977 is the first PR where it happened and it's been failing for at least four hours. @iainlane, @ddstreet could you take a look?

**Comment by iainlane** [comment]
Already being worked on, but thanks.

**Comment by iainlane** [comment]
The requests are there, but I don't know what has to be done to make Github see that.

**Comment by evverx** [comment]
@iainlane got it. Thank you. Just to be sure I've just manually triggered amd64 in https://github.com/systemd/systemd/pull/12979 and it's in progress as far as I can tell. I'll send the rest of the failed requests manually. New PRs should trigger Ubuntu CI as usual.

**Comment by evverx** [comment]
@mbiebl regarding the "experimental" branch, apparently Ubuntu CI currently uses it as well. It can't be switched to the "master" branch though because https://salsa.debian.org/systemd-team/systemd/commit/acabce1ac077a64230df963a454eb21d9906442f and https://salsa.debian.org/systemd-team/systemd/commit/a223575e533a686d26518549dcd48e98ad99a531 aren't there yet. I'm wondering what the plan is in the sense how long it usually takes for "experimental" commits to make it to the "master" branch and, more generally, if there is a way to avoid switching branches everywhere manually.

**Comment by mbiebl** [comment]
when we make the switch back to master, we'll let you know.

**Comment by evverx** [comment]
I thought it was easier to keep track of branches on the Debian side so I was kind of hoping there was a branch named "development" or something like that always pointing to the "active" branch we could use in the Semaphore script and in the Ubuntu CI webhooks to avoid switching branches manually.

Anyway, the name of the branch isn't the only thing that should be kept up to date. The script currently downloads Debian Buster even though the comment above says it defaults to Debian testing. Is it possible to point it to Debian testing without mentioning codenames?

By the way, @mbiebl I've just invited you to the systemd organization on Semaphore just in case.

**Comment by mbiebl** [comment]
If you are talking about tracking testing in apt, you can use `testing` in `/etc/apt/sources.list` like this:
```
deb http://ftp.debian.org/debian/ testing main
```

**Comment by evverx** [comment]
The script runs `lxc-create -n $CONTAINER -t download -- -d $DISTRO -r $RELEASE -a $ARCH` where RELEASE currently refers to Buster. I was wondering if there is a way to somehow get rid of that and use something like "debing:testing" as we do on Travis CI to download docker images.

**Comment by evverx** [comment]
FWIW this morning Semaphore seems to have started failing sporadically with
```
autopkgtest [11:47:03]: test timedated: preparing testbed
autopkgtest [11:47:13]: @@@@@@@@@@@@@@@@@@@@ test bed setup
Hit:1 http://deb.debian.org/debian buster InRelease
Reading package lists...
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
blame: ../systemd_242-1181-g05fa41e62a-0.dsc
badpkg: testbed setup commands failed with status 100
autopkgtest [11:47:15]: ERROR: erroneous package: testbed setup commands failed with status 100
+ '[' 12 -eq 2 ']'
```
I suppose it can be fixed by retrying or by turning off periodic processes trying to install packages but I'm not completely sure. I'll wait for a week for it to go away and turn it off if it keeps failing.

**Comment by mbiebl** [comment]
> I'm wondering what the plan is in the sense how long it usually takes for "experimental" commits to make it to the "master" branch and, more generally, if there is a way to avoid switching branches everywhere manually.

Personally, my plan was to keep v241 in unstable up until the first buster point release, which should be in about a month. Any fixes that are uploaded to unstable during that time are basically targetted fixes that should be suitable for a buster point release of systemd. This way we can more easily battle-test those changes and it should be easier to get the buster-pu request unblocked.
After the first point release, I would then merge what's in experimental to master and all the CIs should point at debian master again.

I will have to coordinate that with my co-maintainers though. Maybe the want to see v242 quicker in unstable. @martinpitt and @fsateler

**Comment by evverx** [comment]
@mbiebl just to clarify, I'm not in a hurry and my comments were mostly about trying to decouple "upstream" testing from the Debian release process. If at this point it's not something that can be done relatively easily, I have absolutely no problem with that.

In the meantime, the tests keep failing on Semaphore with
```
+ /home/runner/systemd/.semaphore-cache/autopkgtest/runner/autopkgtest --apt-upgrade --env DEB_BUILD_OPTIONS=noudeb --env TEST_UPSTREAM=1 ../systemd_242-1182-g30d5977908-0.dsc -o /tmp/artifacts -- lxc -s buster-amd64
autopkgtest [13:01:01]: git checkout: 579d25a Merge branch 'new-openstack-fixes' into 'master'
autopkgtest [13:01:01]: host semaphore-light-1902; command line: /home/runner/systemd/.semaphore-cache/autopkgtest/runner/autopkgtest --apt-upgrade --env DEB_BUILD_OPTIONS=noudeb --env TEST_UPSTREAM=1 ../systemd_242-1182-g30d5977908-0.dsc -o /tmp/artifacts -- lxc -s buster-amd64
autopkgtest [13:01:09]: @@@@@@@@@@@@@@@@@@@@ test bed setup
Hit:1 http://deb.debian.org/debian buster InRelease
Reading package lists...
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
autopkgtest [13:01:11]: ERROR: erroneous package: testbed setup commands failed with status 100
blame: 
badpkg: testbed setup commands failed with status 100
+ '[' 12 -eq 2 ']'
```
Could we maybe borrow something from the Debian testing infrastructure (where everything seems to be fine) to address that?

**Comment by fsateler** [comment]
> Personally, my plan was to keep v241 in unstable up until the first buster point release, which should be in about a month.
> <snip>
> I will have to coordinate that with my co-maintainers though. Maybe they want to see v242 quicker in unstable.

I'm good with this plan. Given the timeframes we are talking about, I believe using unstable as staging for stable sounds very good to me.

**Comment by evverx** [comment]
On second thought, given that the tests have failed 18 times today on Semaphore I don't think it makes much sense to keep running them. I'll go ahead and turn them off.

As I mentioned in https://github.com/systemd/systemd/issues/12932#issuecomment-509737152, I found the code dealing with retries on Ubuntu CI but I'm not sure which part should be borrowed to make it more reliable.

**Pull request merged**
