### PR TITLE
socket-util: add additional cmsg buffer for 64bit timeval or timespec

### LINKED ISSUE #20482: systemd-timesyncd fails to sync time from NTP server with IPv6 address
**systemd version the issue has been seen with**
systemd v249 and main branch

**Used distribution**
 > OpenBMC

**Linux kernel version used** (`uname -a`)

 > `5.10.53`

**CPU architecture issue was seen on**
 > ARM

**Expected behaviour you didn't see**
 > systemd-timesyncd should be able to sync time from NTP server with IPv6 address

**Unexpected behaviour you saw**
 > It fails to sync time and get error message as below.

**Steps to reproduce the problem**
- Config the NTP server with IPv6 address
- Start systemd-timesyncd

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
systemd-timesyncd[534]: Error receiving message, disconnecting: Exchange full
```

### LINKED ISSUE #20564: DHCP6 broken on armhf (and probably other 32 bit arches)
**systemd version the issue has been seen with**
 > 248.3

The code looks the same in main though.

**Used distribution**
 > Ubuntu 21.10

**Linux kernel version used** (`uname -a`)
 > `Linux impish 5.4.0-1028-raspi #31-Ubuntu SMP PREEMPT Wed Jan 20 11:30:45 UTC 2021 armv8l armv8l armv8l GNU/Linux`

But it's also important that this all happens when glibc is built on a system with kernel before 5.1

**CPU architecture issue was seen on**
 > armhf

**Expected behaviour you didn't see**
 > python3 networkd-test.py passing

**Unexpected behaviour you saw**
 > test_coldplug_dhcp_ip6 failed with "timed out waiting for IPv6 configuration"

**Steps to reproduce the problem**
 > It's a bit complicated but https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1940635/comments/8 has the details

**Additional program output to the terminal or log subsystem illustrating the issue**

If you crank up networkd's log level you get this in the output:

```
Aug 27 14:28:29 autopkgtest systemd-networkd[939]: NDISC: Unexpected error while reading from ICMPv6, ignoring: Exchange full
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #20482.
Fixes #20564.

### CODE REVIEW

**Comment by poettering** [comment]
patch makes sense, just would suggest to let the compiler figure out the struct size more instead of doing the calculation ourselves, and i would start going tougher on size mismatches in cmsg

**Comment by yuwata** [comment]
@poettering Thank you for the comments. All suggestions are applied. PTAL.

> timespace → timespec
> 
> But are you saying that glibc ensures _both_ a 32 bit _and_ a 64bit timespec are synthetically appended to recvmsg on such platforms?

Yes. `__convert_scm_timestamps()` in glibc appends 64bit version of timeval/timespec. So, we need additional buffer.

> 
> That's so weird.
> 
> Maybe define a herlper struct and let the compiler do the calculations:
> 
> ```c
> /* Define a version of timeval/timespec that uses 64bit inegers in any case, even on 32bit userspace */
> struct timeval_large {
>         uint64_t tvl_sec, tvl_usec; 
> };
> struct timespec_large {
>         uint64_t tvl_sec, tvl_nsec;
> };
> 
> /* glibc duplicates timespec/timeval on certain 32bit archs, once in 32bit and once in 64bit */
> #define CMSG_SPACE_TIMEVAL (sizeof(struct timeval_large) == sizeof(struct timeval) ? CMSG_SPACE(sizeof(struct timeval)) : CMSG_SPACE(sizeof(struct timeval))  + CMSG_SPACE(sizeof(struct timeval_large))
> …
> ```

Done.


> actually, I wonder if we should make the size check an assert. i.e. this probably shouldn't be something to skip/ignore if the size doesn#t matter.
> 
> I mean, it's a "portability" bug after all: and that's a programming error, hence an asser sounds right to me

Done.

**Comment by poettering** [comment]
@mwhudson @leiyu-bytedance any chance you can give this PR a whirl, and verify it does the right thing for you in its current iteration?

**Comment by yuwata** [comment]
( @leiyu-bytedance already confirmed this works fine. See https://github.com/systemd/systemd/issues/20482#issuecomment-907992711 )

**Comment by poettering** [comment]
@yuwata but i think that was a slightly older version of the patch, no?

**Comment by yuwata** [comment]
Right.

**Comment by mwhudson** [comment]
> @mwhudson @leiyu-bytedance any chance you can give this PR a whirl, and verify it does the right thing for you in its current iteration?

I too tested an earlier version of the patch and it passed (we are having [some other fun with test-oomd-util](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1942113) but I assume that's unrelated to all this). I'll test the current version too and report back.

**Comment by mwhudson** [comment]
The current version of the test passes tests in our environment too.

**Comment by yuwata** [comment]
@mwhudson Thank you!

**Pull request merged**
