### PR TITLE
meson: Create /usr/lib/credstore directory

### PR DESCRIPTION
**Pull request by daandemeyer**

### CODE REVIEW

**Comment by poettering** [comment]
rationale?

**Comment by poettering** [comment]
and if we create that, why not /etc/ too?

maybe make it 0700 btw, dunno?

**Comment by keszybz** [comment]
I guess we might as well do this. We look for files there, and it makes things a bit more discoverable for users if the directory exists. It also reduces the chance of somebody reusing the name for something else.

But please add some rationale to the patch.

**Comment by poettering** [comment]
would till prefer if this would create /etc/credstore at the same time. as long as we install config files we should also install dirs like this, in particular given this one should have the locked down access mode.

**Comment by keszybz** [comment]
> maybe make it 0700 btw, dunno?

Non-readable files under `/usr/lib` are annoying: when packaged, it doesn't make sense to "protect" stuff that is available for download from the distro. It also breaks `rpm --verify` for users, etc. OTOH, it doesn't really buy anything, because it's the individual files that are put there that should be protected. Not all files need/should be protected. So I think we should just use normal permissions for this. People can override in specific cases where this make sense.

**Comment by poettering** [comment]
i can accept that. but for /etc/credstore we still should do 0700

**Comment by DaanDeMeyer** [comment]
Updated as suggested

**Comment by poettering** [comment]
Hmm, so what I missed earlier: we have tmpfiles.d/credstore.conf already, and it carries different access mode. we should probably do something about that.

**Comment by poettering** [comment]
See: b6033b706028a64e9affb79050ced1ad9a4f5b43

**Pull request merged**
