### PR TITLE
Revert "ci: turn off the "upstream-systemd-ci" ppa"

### PR DESCRIPTION
**Pull request by evverx**
Reverts systemd/systemd#16460

### CODE REVIEW

**Comment by evverx** [comment]
@ddstreet looks like it didn't help much. The "build test" checks seem to be failing with the ppa enabled with
```
2020-07-14T21:52:23.9202688Z The following packages have unmet dependencies:
2020-07-14T21:52:23.9806123Z  kbd : Depends: console-setup but it is not going to be installed or
2020-07-14T21:52:23.9807841Z                 console-setup-mini but it is not going to be installed
2020-07-14T21:52:24.0272165Z E: Unable to correct problems, you have held broken packages.
2020-07-14T21:52:24.0310286Z ##[error]Process completed with exit code 100.
2020-07-14T21:52:24.0327675Z Cleaning up orphan processes
```

**Comment by evverx** [comment]
Let me restart it. It could be the packages were cached somewhere.

**Comment by evverx** [comment]
It seems systemd is compiling there now so it's probably safe to say that the issue is gone. I'd wait for Ubuntu CI to finish though.

**Comment by ddstreet** [comment]
apologies again for the breakage, i'll be sure to do full testing before adding packages to the ppa again.

**Pull request merged**
