### PR TITLE
meson: skip to search clang, llvm-string, and bpftool, if libbpf not found

### PR DESCRIPTION
**Pull request by yuwata**
Prompted by https://github.com/systemd/systemd/pull/22093#issuecomment-1016254914.

### CODE REVIEW

**Comment by evverx** [comment]
LGTM but it seems LGTM isn't triggered automatically when the C code is intact so just to be sure I'll trigger it manually on LGTM.

**Comment by yuwata** [comment]
@evverx Thank you!

**Comment by evverx** [comment]
I've triggered it and once "build merge" is green at https://lgtm.com/projects/g/systemd/systemd/logs/rev/pr-239435fb00e8add89676f679c267610de379baa3/lang:cpp/stage:Build%20merge_eb2a252f5843b16230bb1aabf3cd9451ce38f27e I think it should be safe to say that LGTM is happy

**Comment by yuwata** [comment]
@evverx LGTM analysis in this PR is still red. But the referenced commit hash is different from the commit of this PR. So, is it ok to ignore the failure? And can I set the green label?

**Comment by yuwata** [comment]
I see. Thanks.

**Comment by evverx** [comment]
Looking at Ubuntu CI and CentOS CI (where systemd was built succesfully) I think this PR should be good to go. I'll go ahead and merge it to let LGTM analyze new PRs instead of failing. Thanks!

**Comment by yuwata** [comment]
@evverx Thank you for your help!

**Pull request merged**
