### PR TITLE
vmspawn: fix journal forwarding

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for 258d26940fb6bfa1b5b8acf03cc4a37f2657e4ac.
Fixes https://github.com/systemd/systemd/pull/31218#discussion_r1596168449.

### CODE REVIEW

**Comment by evverx** [comment]
@yuwata I think it should help but I haven't figured out how to make it work. One machine has been running for several hours and I can't see any logs in the directory. It could be I'm holding it wrong.

**Review by bluca — APPROVED** [review]

**Comment by evverx** [comment]
Either way I can't make it work. I'm guessing I shouldn't have run it all under ASan (both on the host and in the vm). It goes sideways.

**Comment by evverx** [comment]
For the record without ASan I got it to work. It spams the journal with stuff like
```sh
systemd-journal-remote[387256]: read(8, ..., 16384): Connection reset by peer
systemd-journal-remote[387397]: read(8, ..., 16384): Connection reset by peer
```
and goes down with
```sh
==387055== Command: /home/vagrant/systemd-valgrind/build/systemd-journal-remote --output /home/vagrant/systemd-asan/JOURNAL --split-mode host
==387055==
For SplitMode=host, output must be a directory.
==387055==
==387055== FILE DESCRIPTORS: 5 open (3 std) at exit.
...
machine-16555771290521275006-system-forward-journal.service: Start request repeated too quickly.
machine-16555771290521275006-system-forward-journal.service: Failed with result 'exit-code'.
```
when the directory doesn't exist. On the bright side it's possible to create the directory and restart the socket without restarting the VM.

Either way without ASan it seems to work.

**Comment by evverx** [comment]
`machine-*-system-forward-journal.service` is totally unsandboxed in the sense that there don't seem to be anything other than `ExecStart` there. It's kind of weird given that it receives random logs from inside VMs.

**Pull request merged**
