### PR TITLE
Some small fixes to make it easier to run tests and fix failure in TEST-{02,08}

### PR DESCRIPTION
**Pull request by keszybz**
In TEST-02-CRYPT there's still an error during shutdown, which does not cause the test to fail, but is a sign of a problem: systemd tries to umount /var while systemd-journald is still using it. There is no dependency between system-journald and /var/log/journal. During boot that is OK, because we have systemd-journal-flush.service to notify systemd-journald when /var becomes available. But not during shutdown. We don't have a nice way to express this dependency currently.

### CODE REVIEW

**Comment by keszybz** [comment]
@martinpitt, @zonque with this all tests in test/ pass for me.

**Comment by evverx** [comment]
> systemd tries to umount /var while systemd-journald is still using it

This is a known issue: https://github.com/systemd/systemd/issues/867#issuecomment-148349919

> tests: specify format=raw for qemu to avoid warning
> tests: allow root to login with empty password to test images

👍 
Thanks!

> tests: enable logging for pid1, disable for other systemd services

This commit fixes another problem.

```
sudo make clean setup run QEMU_BIN=/some/non/existance/path
...
run systemd_nspawn (log_level=info, not debug)
```

> TEST-08: make sure / is remounted rw

My bad. I forgot a `systemd-remount-fs.service`.
(but (thanks to the `ro`-root) I found https://github.com/systemd/systemd/issues/3166 :))

Anyway, I get:

```
-bash-4.3# systemctl --state=failed --no-pager --no-legend
systemd-remount-fs.service    loaded failed failed systemd-remount-fs.service
systemd-timesyncd.service     loaded failed failed Network Time Synchronization
systemd-tmpfiles-setup.service loaded failed failed Create Volatile Files and Dir

-bash-4.3# journalctl -b | grep remount
...
May 09 01:14:22 systemd-testsuite systemd[140]: systemd-remount-fs.service: Executing: /usr/bin/systemctl reload /
May 09 01:14:22 systemd-testsuite systemd[140]: systemd-remount-fs.service: Failed at step EXEC spawning /usr/bin/systemctl: No such file or directory

-bash-4.3# type -p systemctl
/bin/systemctl
```

So, I think we should change `ExecStart=/usr/bin/systemctl ...` to `ExecStart=/bin/sh -x -c 'systemctl ...'` 

Looks good otherwise. Thanks!

**Comment by keszybz** [comment]
> So, I think we should change ExecStart=/usr/bin/systemctl ... to ExecStart=/bin/sh -x -c 'systemctl ...'

I think it should be enough to use /bin/systemctl always. I'll force push with this change.

**Comment by keszybz** [comment]
> My bad. I forgot a systemd-remount-fs.service.
> (but (thanks to the ro-root) I found #3166 :))

I thought about using `rw`, instead of a remount service. But `rw` is the most common solution nowadays and it's good to introduce some variability and uncommon setups in the tests, so I like doing `ro` and remounting in this test.

**Pull request merged**
