### PR TITLE
home/user-record-util: do not use compound literal macro in JSON macros

### LINKED ISSUE #20501: Possible stack-use-after-scope in json/userdb utils
**systemd version the issue has been seen with**
 > latest master

**Used distribution**
 > Arch Linux (gcc + ASan/UBSan)

The gcc + ASan/UBSan cron job found a possible issue in json/userdb utils:

```
Aug 21 05:01:45 H systemd[60]: systemd-homed.service: Executing: /usr/lib/systemd/systemd-homed
Aug 21 05:01:45 H systemd-homed[60]: Generating key pair for signing local user identity records.
Aug 21 05:01:45 H systemd-homed[60]: Successfully created Ed25519 key pair.
Aug 21 05:01:45 H systemd-homed[60]: test-user: changing state absent â†’ creating
Aug 21 05:01:46 H systemd-homed[60]: test-user: changing state creating â†’ inactive
Aug 21 05:01:46 H systemd-homed[60]: =================================================================
Aug 21 05:01:46 H systemd-homed[60]: ==60==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f3c16c3dcc0 at pc 0x7f3c1ce7d72b bp 0x7ffdac50db70 sp 0x7ffdac50d318
Aug 21 05:01:46 H systemd-homed[60]: READ of size 33 at 0x7f3c16c3dcc0 thread T0
Aug 21 05:01:46 H systemd-homed[60]:     #0 0x7f3c1ce7d72a in __interceptor_strlen /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:389
Aug 21 05:01:46 H systemd-homed[60]:     #1 0x7f3c1c0d633b in json_variant_new_stringn ../build/src/shared/json.c:400
Aug 21 05:01:46 H systemd-homed[60]:     #2 0x7f3c1c0ed83d in json_variant_new_string ../build/src/shared/json.h:74
Aug 21 05:01:46 H systemd-homed[60]:     #3 0x7f3c1c0ed83d in json_buildv ../build/src/shared/json.c:3771
Aug 21 05:01:46 H systemd-homed[60]:     #4 0x7f3c1c0ee2fb in json_build ../build/src/shared/json.c:3851
Aug 21 05:01:46 H systemd-homed[60]:     #5 0x55660eb749be in group_record_synthesize ../build/src/home/user-record-util.c:142
Aug 21 05:01:46 H systemd-homed[60]:     #6 0x55660eb6d1ca in build_group_json ../build/src/home/homed-varlink.c:164
Aug 21 05:01:46 H systemd-homed[60]:     #7 0x55660eb6eb03 in vl_method_get_group_record ../build/src/home/homed-varlink.c:252
Aug 21 05:01:46 H systemd-homed[60]:     #8 0x7f3c1c1c27e5 in varlink_dispatch_method ../build/src/shared/varlink.c:872
Aug 21 05:01:46 H systemd-homed[60]:     #9 0x7f3c1c1c2fcf in varlink_process ../build/src/shared/varlink.c:947
Aug 21 05:01:46 H systemd-homed[60]:     #10 0x7f3c1c1c4bdf in defer_callback ../build/src/shared/varlink.c:1862
Aug 21 05:01:46 H systemd-homed[60]:     #11 0x7f3c1c500810 in source_dispatch ../build/src/libsystemd/sd-event/sd-event.c:3536
Aug 21 05:01:46 H systemd-homed[60]:     #12 0x7f3c1c50197e in sd_event_dispatch ../build/src/libsystemd/sd-event/sd-event.c:4078
Aug 21 05:01:46 H systemd-homed[60]:     #13 0x7f3c1c50222b in sd_event_run ../build/src/libsystemd/sd-event/sd-event.c:4139
Aug 21 05:01:46 H systemd-homed[60]:     #14 0x7f3c1c5023c0 in sd_event_loop ../build/src/libsystemd/sd-event/sd-event.c:4160
Aug 21 05:01:46 H systemd-homed[60]:     #15 0x55660eb70450 in run ../build/src/home/homed.c:44
Aug 21 05:01:46 H systemd-homed[60]:     #16 0x55660eb7085a in main ../build/src/home/homed.c:51
Aug 21 05:01:46 H systemd-homed[60]:     #17 0x7f3c1a92fb24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
Aug 21 05:01:46 H systemd-homed[60]:     #18 0x55660eb316fd in _start (/usr/lib/systemd/systemd-homed+0x616fd)
Aug 21 05:01:46 H systemd-homed[60]: Address 0x7f3c16c3dcc0 is located in stack of thread T0 at offset 192 in frame
Aug 21 05:01:46 H systemd-homed[60]:     #0 0x55660eb742ac in group_record_synthesize ../build/src/home/user-record-util.c:109
Aug 21 05:01:46 H systemd-homed[60]:   This frame has 7 object(s):
Aug 21 05:01:46 H systemd-homed[60]:     [32, 40) 'un' (line 110)
Aug 21 05:01:46 H systemd-homed[60]:     [64, 72) 'rr' (line 110)
Aug 21 05:01:46 H systemd-homed[60]:     [96, 104) 'group_name_and_realm' (line 110)
Aug 21 05:01:46 H systemd-homed[60]:     [128, 136) 'description' (line 110)
Aug 21 05:01:46 H systemd-homed[60]:     [160, 176) 'mid' (line 111)
Aug 21 05:01:46 H systemd-homed[60]:     [192, 225) '<unknown>' <== Memory access at offset 192 is inside this variable
Aug 21 05:01:46 H systemd-homed[60]:     [272, 305) '<unknown>'
Aug 21 05:01:46 H systemd-homed[60]: HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
Aug 21 05:01:46 H systemd-homed[60]:       (longjmp and C++ exceptions *are* supported)
Aug 21 05:01:46 H systemd-homed[60]: SUMMARY: AddressSanitizer: stack-use-after-scope /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:389 in __interceptor_strlen
Aug 21 05:01:46 H systemd-homed[60]: Shadow bytes around the buggy address:
Aug 21 05:01:46 H systemd-homed[60]:   0x0fe802d7fb40: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Aug 21 05:01:46 H systemd-homed[60]:   0x0fe802d7fb50: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Aug 21 05:01:46 H systemd-homed[60]:   0x0fe802d7fb60: f5 f5 f5 f5 00 00 00 00 00 00 00 00 00 00 00 00
Aug 21 05:01:46 H systemd-homed[60]:   0x0fe802d7fb70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Aug 21 05:01:46 H systemd-homed[60]:   0x0fe802d7fb80: f1 f1 f1 f1 00 f2 f2 f2 00 f2 f2 f2 00 f2 f2 f2
Aug 21 05:01:46 H systemd-homed[60]: =>0x0fe802d7fb90: 00 f2 f2 f2 00 00 f2 f2[f8]f8 f8 f8 f8 f2 f2 f2
Aug 21 05:01:46 H systemd-homed[60]:   0x0fe802d7fba0: f2 f2 f8 f8 f8 f8 f8 f3 f3 f3 f3 f3 00 00 00 00
Aug 21 05:01:46 H systemd-homed[60]:   0x0fe802d7fbb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Aug 21 05:01:46 H systemd-homed[60]:   0x0fe802d7fbc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Aug 21 05:01:46 H systemd-homed[60]:   0x0fe802d7fbd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Aug 21 05:01:46 H systemd-homed[60]:   0x0fe802d7fbe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Aug 21 05:01:46 H systemd-homed[60]: Shadow byte legend (one shadow byte represents 8 application bytes):
Aug 21 05:01:46 H systemd-homed[60]:   Addressable:           00
Aug 21 05:01:46 H systemd-homed[60]:   Partially addressable: 01 02 03 04 05 06 07
Aug 21 05:01:46 H systemd-homed[60]:   Heap left redzone:       fa
Aug 21 05:01:46 H systemd-homed[60]:   Freed heap region:       fd
Aug 21 05:01:46 H systemd-homed[60]:   Stack left redzone:      f1
Aug 21 05:01:46 H systemd-homed[60]:   Stack mid redzone:       f2
Aug 21 05:01:46 H systemd-homed[60]:   Stack right redzone:     f3
Aug 21 05:01:46 H systemd-homed[60]:   Stack after return:      f5
Aug 21 05:01:46 H systemd-homed[60]:   Stack use after scope:   f8
Aug 21 05:01:46 H systemd-homed[60]:   Global redzone:          f9
Aug 21 05:01:46 H systemd-homed[60]:   Global init order:       f6
Aug 21 05:01:46 H systemd-homed[60]:   Poisoned by user:        f7
Aug 21 05:01:46 H systemd-homed[60]:   Container overflow:      fc
Aug 21 05:01:46 H systemd-homed[60]:   Array cookie:            ac
Aug 21 05:01:46 H systemd-homed[60]:   Intra object redzone:    bb
Aug 21 05:01:46 H systemd-homed[60]:   ASan internal:           fe
Aug 21 05:01:46 H systemd-homed[60]:   Left alloca redzone:     ca
Aug 21 05:01:46 H systemd-homed[60]:   Right alloca redzone:    cb
Aug 21 05:01:46 H systemd-homed[60]:   Shadow gap:              cc
Aug 21 05:01:46 H systemd-homed[60]: Command: /usr/lib/systemd/systemd-homed
Aug 21 05:01:46 H systemd-homed[60]: ==60==ABORTING
```
Full job: https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-cron-build/335/artifact//systemd-centos-ci/index.html

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #20501.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @mrc0mmand and @poettering.

**Comment by mrc0mmand** [comment]
Thank you! I'll run it manually with the cron job to test it.

**Comment by mrc0mmand** [comment]
Yep, can [confirm](https://jenkins-systemd.apps.ocp.ci.centos.org/job/ci-build/673/artifact//index.html) this fixes the issue.

**Comment by yuwata** [comment]
@mrc0mmand Thank you!

**Comment by poettering** [comment]
I found a different approach, converting json.h's macro to use compound literals too, which removes the issue from that angle. Lemme post a PR in a bit

**Comment by yuwata** [comment]
> I found a different approach, converting json.h's macro to use compound literals too, which removes the issue from that angle. Lemme post a PR in a bit

Ah, that sounds better.

**Comment by poettering** [comment]
I justed posted #20517 which fixes this in json.h. I am pretty sure it works, but probably deserves a closer inspection

**Comment by bluca** [comment]
Closing in favour of https://github.com/systemd/systemd/pull/20517

**Pull request closed without merging**
