### PR TITLE
journal-file: Fix return value in bump_entry_array()

### PR DESCRIPTION
**Pull request by daandemeyer**

### CODE REVIEW

**Comment by poettering** [comment]
yikes

**Comment by vcaputo** [comment]
oh man...

So since v251 yeah?  What's the actual consequence of this, journal corruption?  backports needed?

**Review by bluca — APPROVED** [review]
big oof, could use some testing coverage improvements

**Comment by vcaputo** [comment]
Maybe this particular bug could have been detected with more strict implicit type conversion warning compilation flags?

It returned le64toh() as an int after all, that's not really something we intentionally do is it?  Those static inlines all return uint$size_t types, this seems like something the compiler could at least be shouting at us about.

**Pull request merged**
