### PR TITLE
core: don't bind varlink socket if running in test mode

### PR DESCRIPTION
**Pull request by poettering**
Fixes: #15748

### CODE REVIEW

**Comment by poettering** [comment]
This is an alternative to #15763. I didn't test this thoroughly though.

**Comment by keszybz** [comment]
LGTM.

**Comment by DaanDeMeyer** [comment]
Yeah, this looks like a good fix. I checked out your branch and got a failure in test-fs-util when running mkosi. I think that's unrelated to this PR though. test-execute completed in 3s so that's working now.

```

The output from the failed tests:

292/496 test-fs-util                              FAIL           0.53s (killed by signal 6 SIGABRT)

--- command ---
16:53:01 SYSTEMD_KBD_MODEL_MAP='/root/src/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/root/src/src/locale/language-fallback-map' PATH='/root/build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' /root/build/test-fs-util
--- stderr ---
/* test_chase_symlinks */
/* test_unlink_noerrno */
/* test_readlink_and_make_absolute */
/* test_var_tmp */
/* test_dot_or_dot_dot */
/* test_access_fd */
/* test_touch_file */
/* test_unlinkat_deallocate */
/* test_fsync_directory_of_file */
/* test_rename_noreplace */
/* test_chmod_and_chown */
/* test_chmod_and_chown_unsafe */
/* test_path_is_encrypted */
Assertion 'r >= 0' failed at src/test/test-fs-util.c:853, function test_path_is_encrypted_one(). Aborting.
-------
```

**Comment by poettering** [comment]
@DaanDeMeyer hmmm, i tried to reproduce the test-fs-util issue, but it passes fine here. I am really wondering what goes wrong there...

(btw you can add -T to the mkosi cmdline to bypass running of the tests.)

**Comment by DaanDeMeyer** [comment]
I'll look into it when I have more time. I think we can treat it as a different issue.

**Pull request merged**
