### PR TITLE
core: on switching root do not emit device state change based on enumeration results

### LINKED ISSUE #11997: During switchroot, devices transition plugged -> dead -> plugged
**systemd version the issue has been seen with**
v240 and v241

**Used distribution**
 Fedora

**Unexpected behaviour you saw**
 With systemd 240 and 241, at switch root time, all devices change plugged -> dead -> plugged. (I tested fedora 29 + v239, v240, and v241, and it was a v239 -> v240 regression.)

In some cases, this might be mostly harmless, but see https://pagure.io/fedora-silverblue/issue/8 for a problem that it causes.

**Steps to reproduce the problem**
* Install Fedora 30 nightly in a VM
* Boot with `systemd.log-level=debug printk.devkmsg=on log_buf_len=1M` on the kernel command line
 * Search for `plugged -> dead` in the logs

**Notes**

With some poking and debug message insertion, I determined that the initial call to device_enumerate() after re-exec is not finding any devices - which is what I think is causing the problem - I couldn't easily find the cause in the v239 ... v240 diff.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #11997.

### CODE REVIEW

**Comment by yuwata** [comment]
A test for the issue is added. I confirm that the test fails without the third commit.

**Comment by keszybz** [comment]
LGTM. @poettering?

**Comment by owtaylor** [comment]
Thanks for working on this @yuwata!

I rebuilt the Fedora 30 v241 packages with this patch set on top and:

 - I no longer see 'plugged -> dead -> plugged' for devices in the logs
 - It fixes the intermittent boot failures I was seeing before (worked 5 times in a row - was previously failing around 50% of the time)
 - My system apparently works fine otherwise

**Comment by yuwata** [comment]
@owtaylor Thank you for testing this PR.

**Comment by poettering** [comment]
So I am not sure about this one. I think we actually do the right thing here currently in systemd, as we make sure the .device unit state stays in sync with the udev db. The problem though is that the udev db is flushed out during the transition (`initrd-udevadm-cleanup-db.service` does that), though I really wonder why we do that, we really shouldn't...

**Comment by keszybz** [comment]
After a process of elimination, it seems that this PR is the one to merge. I grok the fact that we might get some stale device information if the device is unplugged at the wrong time during boot, but this seems to be mostly a theoretical problem. Let's merge this, and maybe we can come up with some solution for this potential problem later.

**Comment by poettering** [comment]
urks, i wished this wasn't merge. This is racy... if pid1 is reloaded between the switch root and udev being started up everything is still fucked...

**Comment by keszybz** [comment]
Well, the state before this patch was broken (failed boots on Fedora Silverblue), and there were three proposed PRs, two of which broke boot with LVM. With this patch, we at least boot to login prompt. I'd be very happy to merge a more "proper" solution, once its proposed.

Dunno, maybe we should revert both this, and the preceding changes that caused the problem, and start from scratch.

**Comment by fbuihuu** [comment]
> Dunno, maybe we should revert both this, and the preceding changes that caused the problem, and start from scratch.

Definitively, especially since it's still broken : see https://bugzilla.suse.com/show_bug.cgi?id=1137373.

And I'm not sure why it was reworked  in the first place (in commit 66f3fdbb073d8263b34bd6) but it's broken since then :-/

**Pull request merged**
