### PR TITLE
man: Add a missing space in machinectl(1)

### PR DESCRIPTION
**Pull request by pwithnall**
Signed-off-by: Philip Withnall <withnall@endlessm.com>

### CODE REVIEW

**Comment by mrc0mmand** [comment]
@evverx @ddstreet do you have any idea what's going on in semaphore? I've, unfortunately, never used autopkgtest, so I have no idea what's broken:

```
+ dpkg-buildpackage -S -I -I.semaphore-cache -d -us -uc -nc
dpkg-buildpackage: source package systemd
dpkg-buildpackage: source version 243-139-g245be52b79-0
dpkg-buildpackage: source distribution UNRELEASED
dpkg-buildpackage: source changed by systemd test <pkg-systemd-maintainers@lists.alioth.debian.org>
 dpkg-source -I -I.semaphore-cache --before-build systemd
dpkg-source: warning: unknown information field 'Rules-Requires-Root' in input data in general section of control info file
dpkg-buildpackage: warning: building a source package without cleaning up as you asked; it might contain undesired files
 dpkg-source -I -I.semaphore-cache -b systemd
dpkg-source: warning: unknown information field 'Rules-Requires-Root' in input data in general section of control info file
dpkg-source: info: using source format '1.0'
dpkg-source: warning: source directory 'systemd' is not <sourcepackage>-<upstreamversion> 'systemd-243-139-g245be52b79'
dpkg-source: info: building systemd in systemd_243-139-g245be52b79-0.tar.gz
dpkg-source: info: building systemd in systemd_243-139-g245be52b79-0.dsc
 dpkg-genchanges -S >../systemd_243-139-g245be52b79-0_source.changes
dpkg-genchanges: warning: unknown information field 'Rules-Requires-Root' in input data in general section of control info file
dpkg-genchanges: including full source code in upload
 dpkg-source -I -I.semaphore-cache --after-build systemd
dpkg-source: warning: unknown information field 'Rules-Requires-Root' in input data in general section of control info file
dpkg-buildpackage: source-only upload: Debian-native package
+ rm -rf /tmp/artifacts
+ /home/runner/systemd/.semaphore-cache/autopkgtest/runner/autopkgtest --env DEB_BUILD_OPTIONS=noudeb --env TEST_UPSTREAM=1 ../systemd_243-139-g245be52b79-0.dsc -o /tmp/artifacts -- lxc -s buster-amd64
autopkgtest [15:10:16]: git checkout: 579d25a Merge branch 'new-openstack-fixes' into 'master'
autopkgtest [15:10:16]: host semaphore-light-1902; command line: /home/runner/systemd/.semaphore-cache/autopkgtest/runner/autopkgtest --env DEB_BUILD_OPTIONS=noudeb --env TEST_UPSTREAM=1 ../systemd_243-139-g245be52b79-0.dsc -o /tmp/artifacts -- lxc -s buster-amd64
autopkgtest-virt-lxc [15:11:21]: ERROR: WARNING: Cannot kill timed out process ['sudo', 'lxc-attach', '--name', 'autopkgtest-lxc-amudil', '--', 'sh', '-ec', '[ ! -d /run/systemd/system ] || systemctl start network-online.target']: [Errno 1] Operation not permitted
Unexpected error:
Traceback (most recent call last):
  File "/home/runner/systemd/.semaphore-cache/autopkgtest/lib/VirtSubproc.py", line 738, in mainloop
    command()
  File "/home/runner/systemd/.semaphore-cache/autopkgtest/lib/VirtSubproc.py", line 667, in command
    r = f(c, ce)
  File "/home/runner/systemd/.semaphore-cache/autopkgtest/lib/VirtSubproc.py", line 258, in cmd_open
    caller.hook_open()
  File "/home/runner/systemd/.semaphore-cache/autopkgtest/virt/autopkgtest-virt-lxc", line 239, in hook_open
    wait_booted(lxc_container_name)
  File "/home/runner/systemd/.semaphore-cache/autopkgtest/virt/autopkgtest-virt-lxc", line 128, in wait_booted
    VirtSubproc.check_exec(sudoify(['lxc-attach', '--name', lxc_name, '--', 'sh', '-ec', '[ ! -d /run/systemd/system ] || systemctl start network-online.target']), timeout=60)
  File "/home/runner/systemd/.semaphore-cache/autopkgtest/lib/VirtSubproc.py", line 183, in check_exec
    stdout=stdout, stderr=subprocess.PIPE)
  File "/home/runner/systemd/.semaphore-cache/autopkgtest/lib/VirtSubproc.py", line 144, in execute_timeout
    (out, err) = sp.communicate(instr)
  File "/usr/lib/python3.5/subprocess.py", line 1062, in communicate
    stderr = self.stderr.read()
  File "/home/runner/systemd/.semaphore-cache/autopkgtest/lib/VirtSubproc.py", line 64, in alarm_handler
    raise Timeout()
VirtSubproc.Timeout
autopkgtest [15:11:22]: ERROR: testbed failure: testbed gave exit status 16 after quit
+ '[' 16 -eq 2 ']'
```

**Comment by filbranden** [comment]
@mrc0mmand:

> @evverx @ddstreet do you have any idea what's going on in semaphore? I've, unfortunately, never used autopkgtest, so I have no idea what's broken

autopkgtest is timing out waiting for network to be online in the LXC container.

More specifically, it's running `systemctl start network-online.target` with a timeout of 1 minute.

This is coming from [this line of code](https://salsa.debian.org/ci-team/autopkgtest/blob/b36fcfdf3f586f1628fb5dd79206ad36bc855ddd/virt/autopkgtest-virt-lxc#L128)

The exception is because the timeout tries to `kill` the command running, but what is running is `sudo` (so it's root) so `kill` doesn't have permissions to do so, hence the exception.

But the problem is the timeout bringing the network to online inside that LXC container...

Not really sure which recent change might have caused this issue to start being more frequent recently... ?

**Comment by evverx** [comment]
I "fixed" it in https://github.com/systemd/systemd/pull/13648. Currently it's compiling systemd in the container so it looks like it got past `systemctl start network-online.target`.

**Comment by keszybz** [comment]
@cdown: please use "rebase and merge" if there's just one commit… No need to a merge commit in that case.

**Pull request merged**
