### PR TITLE
rules: ubi mtd - add link to named partitions

### PR DESCRIPTION
**Pull request by mgrzeschik**
Signed-off-by: Michael Grzeschik <m.grzeschik@pengutronix.de>

### CODE REVIEW

**Comment by poettering** [comment]
you based your PR on a git version from 2015! could you rebase on current git, so that the CIs can do their work properly? thanks!

**Comment by poettering** [comment]
i have no idea about UBI, but this looks acceptable to me, with my little knowledge...

**Comment by poettering** [comment]
(btw, we don't use Signed-off-by: in systemd, that's a kernel thing)

**Comment by poettering** [comment]
please rebase on current git, and I'll merge it.

**Comment by keszybz** [comment]
Rebased.

**Comment by keszybz** [comment]
We didn't do a very good job reviewing this one. Not only was it broken, but also the naming scheme didn't make much sense. Oh, well. At least nobody noticed for almost four years ;)

**Pull request merged**
