### PR TITLE
Load dropins only for the main unit name

### PR DESCRIPTION
**Pull request by keszybz**
This seems like a fairly big change in semantics, but I think the practical impact is not very big. On my Fedora system, I don't have any configuration done through aliases (apart from the case I added to reproduce the issue), so this change has no effect.

An alternative would be to scan all directories and load any symlinks to proactively discover any aliases. This would mean reading a few directories, but we wouldn't have to load any files, just symlinks, so the cost would be rather small. While writing the patch, I couldn't quite convince myself that it is a good idea, but I couldn't completely discard it either.

### CODE REVIEW

**Comment by boucman** [comment]
just to be sure, this only applies to drop-ins, not .wants and .requires directories ? those are quite usefull to hook up to a service that has multiple implementations...

**Comment by keszybz** [comment]
> just  to be sure, this only applies to drop-ins, not .wants and .requires  directories ? those are quite usefull to hook up to a service that has  multiple implementations...

It'd apply to both. I didn't actually test that this is true, though. Loading of the .wants/.requires deps suffers from a similar problem as the dropin dirs.

**Comment by boucman** [comment]
yeah, but there is a real use-case for WantedBy=<an alias> in particular we don't know if dropber or openssh (for example) provides the ssh server. Alias are a standard way to go around that. There might be a couple units that depends on default.target and that would break with this change.

I think that worth discussing a little...

**Comment by poettering** [comment]
I have the suspicion this will break debian quite badly, since iirc they rename all kinds of services and try to make things work by aliasing them back. At least we get a ton of issues with alias names always coming to us from their general direction, hence I figure this is going to break them too.

**Comment by keszybz** [comment]
I'll prepare a PR implementing the other approach (to scan for aliases).

**Pull request closed without merging**
