### PR TITLE
Measure the kernel and the initrds from systemd-boot on PCR#9

### PR DESCRIPTION
**Pull request by aplanas**
In a measured boot system, the firmware will measure all the EFI binaries
loaded by LoadImage.  This is usually done in PCR#4 (but the specification
allows PCR#0 and PCR#2 depending on the deployment).

The measurement is done of the EFI executable, excluding the checksum and the
certificate table (a Python script that calculates the hash:
https://github.com/systemd/systemd/pull/29965#issuecomment-1804246698)

If UKI (unified kernel image) are used, the EFI stub will measure the payload
of the different sections, like the kernel, initrd and the command line(among
others), making it very easy to predict.

When systemd-boot is unsed, only the kernel command line and the loader.conf
file are explicitly measured by the boot loader, delegating to the firmware the
partial measurement of the image (kernel or UKI), but missing the measurements
of the initrds.

This commit will include a new helper method, tpm_log_image, that will measure
any given file, and will be used to measure the image in PCR#9.

In that way we will measure the Linux kernel or the UKI (including the stub) in
a specific PCR register, more easy to find and in a more predictable order.

### CODE REVIEW

**Comment by aplanas** [comment]
> The actual digest measured is the PE authenticode of the EFI executable, nothing else.

That is my first incursion in EFI binaries. Is the PE authenticode a section of the EFI binary? So in only partially measured?

**Comment by polarina** [comment]
> That is my first incursion in EFI binaries. Is the PE authenticode a section of the EFI binary? So in only partially measured?

It is a hash of the entire executable, excluding the checksum and the certificate table. Here's a little Python snippet to precompute the PCR4 digest:

```python3
import hashlib
import pefile
import sys


with pefile.PE(sys.argv[1], fast_load=True) as exe:
	security_directory = exe.OPTIONAL_HEADER.DATA_DIRECTORY[pefile.DIRECTORY_ENTRY['IMAGE_DIRECTORY_ENTRY_SECURITY']]

	checksum_offset = exe.OPTIONAL_HEADER.dump_dict()['CheckSum']['FileOffset']
	checksum_size = 4

	certificate_table_offset = security_directory.dump_dict()['VirtualAddress']['FileOffset']
	certificate_table_size = 8

	certificate_virtual_addr = security_directory.VirtualAddress

	raw = exe.__data__

	# Skip checksum, certificate table "pointer", and the certificate
	h = hashlib.sha256()
	h.update(raw[:checksum_offset])
	h.update(raw[checksum_offset+checksum_size:certificate_table_offset])
	h.update(raw[certificate_table_offset+certificate_table_size:certificate_virtual_addr])
	h.update(raw[certificate_virtual_addr+security_directory.Size:])

	digest = h.digest()


print(digest.hex())
```

```
[gabriel@kotek ~]$ sudo python pcr4.py /boot/efi/EFI/BOOT/BOOTX64.EFI
2d78d880ab1b08b8757b5bdd52104ae1fc38421e22b1e7a18d84e3c6000dc305
[gabriel@kotek ~]$ sudo tpm2_eventlog /sys/kernel/security/tpm0/binary_bios_measurements | grep 2d78d880ab1b08b8757b5bdd52104ae1fc38421e22b1e7a18d84e3c6000dc305
    Digest: "2d78d880ab1b08b8757b5bdd52104ae1fc38421e22b1e7a18d84e3c6000dc305"
```

**Comment by poettering** [comment]
Are you saying "systemd-pcrlock lock-uki" cannot properly predict the measurement for you?

It works perfectly here.

**Comment by aplanas** [comment]
> It is a hash of the entire executable, excluding the checksum and the certificate table. Here's a little Python snippet to precompute the PCR4 digest:

I understand now. Thanks!

**Comment by aplanas** [comment]
> Are you saying "systemd-pcrlock lock-uki" cannot properly predict the measurement for you?

I did not used sd-pcrlock, I am sure that it will work for pcr#4 after checking https://github.com/systemd/systemd/pull/29965#issuecomment-1804246698

**Comment by aplanas** [comment]
I updated the commit and the PR description to amend the PCR#4 mistake.

We can drop the second (and maybe the first commit) to delegate the image measurement only PCR#4, but I still find more easy to find it in PCR#9 for normal use (there is some appeal on matching the sha256sum output of the file), as the order is easy to predict and there is an associated description.

The inirtds measurement (commit 3) seems useful to me.

**Comment by poettering** [comment]
I really don't understand why this is necessary? The kernel/initrd is already measured:

1. By firmware into PCR 4 (the UKI as a whole)
2. By sd-stub into PCR 11 (the individual components of the UKI)
3. By the kernel's own boot code into PCR 9 (initrd + cmdline only)

Why do we need even more? I don't get this?

**Comment by aplanas** [comment]
> I really don't understand why this is necessary? The kernel/initrd is already measured:
> 
>     1. By firmware into PCR 4 (the UKI as a whole)

Yes. That part can be dropped (commits 1 and 2). They are there because the simplicity of having the same measurement of the kernel via sha256sum in a different (less used) PCR, with an attached description. If this is not providing value, lets drop then.

>     2. By sd-stub into PCR 11 (the individual components of the UKI)

We are not using UKIs, and we will be not be able to use them for a while. Sadly we need a (maybe long) period of transition where we will need the traditional kernel + initrd approach, to help us to coexist with a different bootloader.  We are moving to sd-boot in certain scenario, but not for all.

>     3. By the kernel's own boot code into PCR 9 (initrd + cmdline only)

> Why do we need even more? I don't get this?

My understanding of the LoadFile2 protocol and the LINUX_EFI_INITRD_MEDIA_GUID device path, is that the kernel EFI stub will search for the "initrd=..." parameter from the command line, and will itself load and measure (PCR 9) the initrd. Is that correct?

If so there is a measurement gap when using the initrd key in the boot loader entry, and the commit 3 is closing it.

**Comment by aplanas** [comment]
Uhmm ... Ok ... I think that I see some of my wrong assumptions about initrd.

Indeed this PR is not providing value. I will close it, and thanks for the reviews, it help me a lot.

**Pull request closed without merging**
