### PR TITLE
sd-bus: Add sd_bus_set/is_monitor docs

### PR DESCRIPTION
**Pull request by daandemeyer**
Can I mention the busctl source code as a good example of how to use BecomeMonitor? It seems overkill to come up with a separate example when we already have an almost perfect example of how to use BecomeMonitor with sd-bus.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
After thinking this through, it would probably still make sense to deprecate `sd_bus_set_monitor` and add `sd_bus_become_monitor` that does everything `sd_bus_set_monitor` does and on top of that calls `BecomeMonitor`. It would take a list of matches and a callback that is invoked for each matched message. I'll leave that for another PR though (if it's a good idea).

**Comment by keszybz** [comment]
LGTM, but I don't know much about the monitoring stuff, so let's also wait for @poettering's review.

We generally don't bother with rewrapping text separately, esp. in the case where just some new paragraphs are being added or a few paragraphs are being modified. In those cases, it is enough to simply wrap any new paragraphs and any that were otherwise touched. I'd rewrap the whole file mostly before doing many small changes all over the place, when combining the indentation changes with the other changes would make it hard to verify the other changes.

**Comment by DaanDeMeyer** [comment]
Ack, should I merge these commits then or just apply this the next time I rewrap something?

**Comment by keszybz** [comment]
> Ack, should I merge these commits then or just apply this the next time I rewrap something?

Next time.

**Comment by keszybz** [comment]
Looks good.
As for the example: sure, maybe link to
https://github.com/systemd/systemd/blob/v245/src/busctl/busctl.c#L80-L96 and 
https://github.com/systemd/systemd/blob/v245/src/busctl/busctl.c#L1237-L1243 ?

**Pull request merged**
