### PR TITLE
test: use flock when calling mkfs.btrfs

### PR DESCRIPTION
**Pull request by mrc0mmand**
As stated in https://github.com/systemd/systemd/issues/21819#issuecomment-1064377645
`mkfs.btrfs` doesn't hold the lock for the whole duration of
`mkfs.btrfs`, thus causing unexpected & test fails. Let's wrap the
`mkfs.btrfs` calls in an flock wrapper to mitigate this.

Hopefully fixes: #21819

---

Marking as a draft as I'd like to test this thoroughly on the CentOS CI side.

### CODE REVIEW

**Comment by bluca** [comment]
Just in case it can be useful, here's some evil bashiness I do in some script - locking:

```
exec {DEV_FD}>"${DEV_PATH}"
flock "${DEV_FD}"
```

unlocking:

```
flock -u "${DEV_FD}"
exec {DEV_FD}>&-
```

This gets a file descriptor from the /dev/bla node and keeps it in a shell variable

**Comment by mrc0mmand** [comment]
Oh well, `flock` didn't help :(

```
[    7.096336] testsuite-64.sh[269]: Single device: default settings
[    7.096336] testsuite-64.sh[269]: + uuid=deadbeef-dead-dead-beef-000000000000
[    7.096336] testsuite-64.sh[269]: + label=btrfs_root
[    7.096336] testsuite-64.sh[269]: + helper_generate_flock_cmdline flock_cmd /dev/disk/by-id/ata-foobar_deadbeefbtrfs0
[    7.096336] testsuite-64.sh[269]: + local -n cmd_array=flock_cmd
[    7.096336] testsuite-64.sh[269]: + shift
[    7.096336] testsuite-64.sh[269]: + [[ 1 -eq 0 ]]
[    7.096336] testsuite-64.sh[269]: + cmd_array=()
[    7.096336] testsuite-64.sh[269]: + for dev in "$@"
[    7.096336] testsuite-64.sh[269]: + cmd_array+=("flock" "-x" "$dev")
[    7.096336] testsuite-64.sh[269]: + flock -x /dev/disk/by-id/ata-foobar_deadbeefbtrfs0 mkfs.btrfs -L btrfs_root -U deadbeef-dead-dead-beef-000000000000 /dev/disk/by-id/ata-foobar_deadbeefbtrfs0
[    7.342084] kernel: floppy0: disk absent or changed during operation
[    7.342091] kernel: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
[    7.342560] kernel: floppy0: disk absent or changed during operation
[    7.342600] kernel: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    7.342604] kernel: Buffer I/O error on dev fd0, logical block 0, async page read
[    7.333804] systemd-udevd[245]: sda: Inotify event: 8 for /dev/sda
[    7.333941] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/power/uevent" does not exist.
[    7.334030] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/holders/uevent" does not exist.
[    7.334085] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/uevent" does not exist.
[    7.334162] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/uevent" does not exist.
[    7.334214] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/cpu3/uevent" does not exist.
[    7.334272] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/cpu1/uevent" does not exist.
[    7.334326] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/cpu2/uevent" does not exist.
[    7.334375] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/cpu0/uevent" does not exist.
[    7.334425] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/uevent" does not exist.
[    7.334475] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/iosched/uevent" does not exist.
[    7.334531] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/integrity/uevent" does not exist.
[    7.334647] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/trace/uevent" does not exist.
[    7.334775] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/slaves/uevent" does not exist.
[    7.334835] systemd-udevd[245]: sda: device is closed, synthesising 'change' on /sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda
[    7.335343] systemd-udevd[245]: sda: Device is queued (SEQNUM=2280, ACTION=change)
[    7.335427] systemd-udevd[245]: sda: Device ready for processing (SEQNUM=2280, ACTION=change)
[    7.337027] systemd-udevd[245]: Successfully forked off 'n/a' as PID 353.
[    7.337112] systemd-udevd[245]: sda: Worker [353] is forked for processing SEQNUM=2280.
[    7.337170] systemd-udevd[353]: sda: Processing device (SEQNUM=2280, ACTION=change)
[    7.337421] systemd-udevd[353]: sda: Failed to flock(/dev/sda): Resource temporarily unavailable
[    7.337497] systemd-udevd[353]: sda: Block device is currently locked, installing watch to wait until the lock is released.
[    7.337554] systemd-udevd[353]: sda: Adding watch on '/dev/sda'
[    7.337611] systemd-udevd[353]: sda: Failed to flock(/dev/sda): Resource temporarily unavailable
[    7.337667] systemd-udevd[353]: sda: Device currently locked, not processing.
[    7.378475] systemd-udevd[245]: sda: Inotify event: 8 for /dev/sda
[    7.378682] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/power/uevent" does not exist.
[    7.378858] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/holders/uevent" does not exist.
[    7.378964] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/uevent" does not exist.
[    7.379057] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/uevent" does not exist.
[    7.379204] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/cpu3/uevent" does not exist.
[    7.379271] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/cpu1/uevent" does not exist.
[    7.380994] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/cpu2/uevent" does not exist.
[    7.381123] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/cpu0/uevent" does not exist.
[    7.381249] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/uevent" does not exist.
[    7.381356] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/iosched/uevent" does not exist.
[    7.381464] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/integrity/uevent" does not exist.
[    7.381565] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/trace/uevent" does not exist.
[    7.381787] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/slaves/uevent" does not exist.
[    7.381920] systemd-udevd[245]: sda: device is closed, synthesising 'change' on /sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda
[    7.382803] systemd-udevd[245]: sda: Device is queued (SEQNUM=2281, ACTION=change)
[    7.383070] systemd-udevd[245]: sda: Device ready for processing (SEQNUM=2281, ACTION=change)
[    7.383174] systemd-udevd[245]: sda: sd-device-monitor: Passed 258 byte to netlink monitor
[    7.383286] systemd-udevd[353]: sda: Processing device (SEQNUM=2281, ACTION=change)
[    7.383407] systemd-udevd[353]: sda: Failed to flock(/dev/sda): Resource temporarily unavailable
[    7.383503] systemd-udevd[353]: sda: Block device is currently locked, installing watch to wait until the lock is released.
[    7.383603] systemd-udevd[353]: sda: Adding watch on '/dev/sda'
[    7.383706] systemd-udevd[353]: sda: Failed to flock(/dev/sda): Resource temporarily unavailable
[    7.384476] systemd-udevd[353]: sda: Device currently locked, not processing.
[    7.401529] systemd-udevd[245]: sda: Inotify event: 8 for /dev/sda
[    7.401789] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/power/uevent" does not exist.
[    7.401901] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/holders/uevent" does not exist.
[    7.402040] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/uevent" does not exist.
[    7.402178] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/uevent" does not exist.
[    7.402290] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/cpu3/uevent" does not exist.
[    7.402380] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/cpu1/uevent" does not exist.
[    7.402504] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/cpu2/uevent" does not exist.
[    7.402603] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/mq/0/cpu0/uevent" does not exist.
[    7.402700] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/uevent" does not exist.
[    7.402796] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/iosched/uevent" does not exist.
[    7.402893] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/integrity/uevent" does not exist.
[    7.402990] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/trace/uevent" does not exist.
[    7.403075] systemd-udevd[245]: sd-device: the uevent file "/sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda/slaves/uevent" does not exist.
[    7.403160] systemd-udevd[245]: sda: device is closed, synthesising 'change' on /sys/devices/pci0000:00/0000:00:03.0/ata1/host0/target0:0:0/0:0:0:0/block/sda
[    7.403258] systemd-udevd[245]: sda: Device is queued (SEQNUM=2282, ACTION=change)
[    7.403345] systemd-udevd[245]: sda: Device ready for processing (SEQNUM=2282, ACTION=change)
[    7.403432] systemd-udevd[245]: sda: sd-device-monitor: Passed 258 byte to netlink monitor
[    7.403522] systemd-udevd[353]: sda: Processing device (SEQNUM=2282, ACTION=change)
[    7.403605] systemd-udevd[353]: sda: Failed to flock(/dev/sda): Resource temporarily unavailable
[    7.403718] systemd-udevd[353]: sda: Block device is currently locked, installing watch to wait until the lock is released.
[    7.403811] systemd-udevd[353]: sda: Adding watch on '/dev/sda'
[    7.403900] systemd-udevd[353]: sda: Failed to flock(/dev/sda): Resource temporarily unavailable
[    7.404008] systemd-udevd[353]: sda: Device currently locked, not processing.
[    7.419455] systemd-udevd[245]: raid6_pq: Device is queued (SEQNUM=2283, ACTION=add)
[    7.419543] systemd-udevd[245]: raid6_pq: Device ready for processing (SEQNUM=2283, ACTION=add)
[    7.419619] systemd-udevd[245]: raid6_pq: sd-device-monitor: Passed 130 byte to netlink monitor
[    7.419675] systemd-udevd[353]: raid6_pq: Processing device (SEQNUM=2283, ACTION=add)
[    7.419728] systemd-udevd[353]: raid6_pq: Device processed (SEQNUM=2283, ACTION=add)
[    7.419778] systemd-udevd[353]: raid6_pq: sd-device-monitor: Passed 130 byte to netlink monitor
[    7.542017] kernel: raid6: skip pq benchmark and using algorithm sse2x4
[    7.542023] kernel: raid6: using ssse3x2 recovery algorithm
[    7.425592] systemd-udevd[245]: xor: Device is queued (SEQNUM=2284, ACTION=add)
[    7.425714] systemd-udevd[245]: xor: Device ready for processing (SEQNUM=2284, ACTION=add)
[    7.425818] systemd-udevd[245]: xor: sd-device-monitor: Passed 125 byte to netlink monitor
[    7.425919] systemd-udevd[353]: xor: Processing device (SEQNUM=2284, ACTION=add)
[    7.426066] systemd-udevd[353]: xor: Device processed (SEQNUM=2284, ACTION=add)
[    7.426201] systemd-udevd[353]: xor: sd-device-monitor: Passed 125 byte to netlink monitor
[    7.548787] kernel: xor: automatically using best checksumming function   avx       
[    7.433328] systemd-udevd[245]: libcrc32c: Device is queued (SEQNUM=2285, ACTION=add)
[    7.433448] systemd-udevd[245]: libcrc32c: Device ready for processing (SEQNUM=2285, ACTION=add)
[    7.433520] systemd-udevd[245]: libcrc32c: sd-device-monitor: Passed 131 byte to netlink monitor
[    7.433584] systemd-udevd[353]: libcrc32c: Processing device (SEQNUM=2285, ACTION=add)
[    7.433672] systemd-udevd[353]: libcrc32c: Device processed (SEQNUM=2285, ACTION=add)
[    7.433732] systemd-udevd[353]: libcrc32c: sd-device-monitor: Passed 131 byte to netlink monitor
[    7.444165] systemd-udevd[245]: blake2b_generic: Device is queued (SEQNUM=2286, ACTION=add)
[    7.444330] systemd-udevd[245]: blake2b_generic: Device ready for processing (SEQNUM=2286, ACTION=add)
[    7.444441] systemd-udevd[245]: blake2b_generic: sd-device-monitor: Passed 137 byte to netlink monitor
[    7.445428] systemd-udevd[353]: blake2b_generic: Processing device (SEQNUM=2286, ACTION=add)
[    7.446034] systemd-udevd[353]: blake2b_generic: Device processed (SEQNUM=2286, ACTION=add)
[    7.446141] systemd-udevd[353]: blake2b_generic: sd-device-monitor: Passed 137 byte to netlink monitor
[    7.683530] systemd-udevd[245]: btrfs-control: Device is queued (SEQNUM=2287, ACTION=add)
[    7.683669] systemd-udevd[245]: btrfs-control: Device ready for processing (SEQNUM=2287, ACTION=add)
[    7.683737] systemd-udevd[245]: btrfs-control: sd-device-monitor: Passed 193 byte to netlink monitor
[    7.683810] systemd-udevd[353]: btrfs-control: Processing device (SEQNUM=2287, ACTION=add)
[    7.683865] systemd-udevd[353]: btrfs-control: Failed to get watch handle, ignoring: No such file or directory
[    7.683921] systemd-udevd[353]: btrfs-control: /usr/lib/udev/rules.d/50-udev-default.rules:81 GROUP 995
[    7.683987] systemd-udevd[353]: sd-device: the uevent file "/sys/devices/virtual/misc/uevent" does not exist.
[    7.684053] systemd-udevd[353]: sd-device: the uevent file "/sys/devices/virtual/uevent" does not exist.
[    7.684107] systemd-udevd[353]: sd-device: the uevent file "/sys/devices/uevent" does not exist.
[    7.684157] systemd-udevd[353]: btrfs-control: Setting permissions /dev/btrfs-control, uid=0, gid=995, mode=0660
[    7.684218] systemd-udevd[353]: btrfs-control: Handling device node '/dev/btrfs-control', devnum=c10:234
[    7.684294] systemd-udevd[353]: btrfs-control: sd-device: Created empty file '/run/udev/data/c10:234' for '/devices/virtual/misc/btrfs-control'
[    7.684356] systemd-udevd[353]: btrfs-control: Failed to get watch handle, ignoring: No such file or directory
[    7.684411] systemd-udevd[353]: btrfs-control: Device processed (SEQNUM=2287, ACTION=add)
[    7.684462] systemd-udevd[353]: btrfs-control: sd-device-monitor: Passed 193 byte to netlink monitor
[    7.684520] systemd-udevd[245]: btrfs: Device is queued (SEQNUM=2288, ACTION=add)
[    7.684574] systemd-udevd[245]: btrfs: Device ready for processing (SEQNUM=2288, ACTION=add)
[    7.684626] systemd-udevd[245]: btrfs: sd-device-monitor: Passed 127 byte to netlink monitor
[    7.684677] systemd-udevd[353]: btrfs: Processing device (SEQNUM=2288, ACTION=add)
[    7.684728] systemd-udevd[353]: btrfs: Device processed (SEQNUM=2288, ACTION=add)
[    7.684779] systemd-udevd[353]: btrfs: sd-device-monitor: Passed 127 byte to netlink monitor
[    7.807795] kernel: Btrfs loaded, crc32c=crc32c-intel, zoned=yes, fsverity=yes
[    7.687330] testsuite-64.sh[352]: btrfs-progs v5.16.2
[    7.687330] testsuite-64.sh[352]: See http://btrfs.wiki.kernel.org for more information.
[    7.687330] testsuite-64.sh[352]: Performing full device TRIM /dev/disk/by-id/ata-foobar_deadbeefbtrfs0 (350.00MiB) ...
[    7.687330] testsuite-64.sh[352]: NOTE: several default settings have changed in version 5.15, please make sure
[    7.687330] testsuite-64.sh[352]:       this does not affect your deployments:
[    7.687330] testsuite-64.sh[352]:       - DUP for metadata (-m dup)
[    7.687330] testsuite-64.sh[352]:       - enabled no-holes (-O no-holes)
[    7.687330] testsuite-64.sh[352]:       - enabled free-space-tree (-R free-space-tree)
[    7.687330] testsuite-64.sh[352]: Label:              btrfs_root
[    7.687330] testsuite-64.sh[352]: UUID:               deadbeef-dead-dead-beef-000000000000
[    7.687330] testsuite-64.sh[352]: Node size:          16384
[    7.687330] testsuite-64.sh[352]: Sector size:        4096
[    7.687330] testsuite-64.sh[352]: Filesystem size:    350.00MiB
[    7.687330] testsuite-64.sh[352]: Block group profiles:
[    7.687330] testsuite-64.sh[352]:   Data:             single            8.00MiB
[    7.687330] testsuite-64.sh[352]:   Metadata:         DUP              32.00MiB
[    7.687330] testsuite-64.sh[352]:   System:           DUP               8.00MiB
[    7.687330] testsuite-64.sh[352]: SSD detected:       no
[    7.687330] testsuite-64.sh[352]: Zoned device:       no
[    7.687330] testsuite-64.sh[352]: Incompat features:  extref, skinny-metadata, no-holes
[    7.687330] testsuite-64.sh[352]: Runtime features:   free-space-tree
[    7.687330] testsuite-64.sh[352]: Checksum:           crc32c
[    7.687330] testsuite-64.sh[352]: Number of devices:  1
[    7.687330] testsuite-64.sh[352]: Devices:
[    7.687330] testsuite-64.sh[352]:    ID        SIZE  PATH
[    7.687330] testsuite-64.sh[352]:     1   350.00MiB  /dev/disk/by-id/ata-foobar_deadbeefbtrfs0
[    7.810703] kernel: BTRFS: device label btrfs_root devid 1 transid 6 /dev/disk/by-id/ata-foobar_deadbeefbtrfs0 scanned by mkfs.btrfs (352)
[    7.898217] kernel: floppy0: disk absent or changed during operation
[    7.898222] kernel: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
[    7.898378] kernel: floppy0: disk absent or changed during operation
[    7.898381] kernel: I/O error, dev fd0, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    7.898384] kernel: Buffer I/O error on dev fd0, logical block 0, async page read
[    7.833478] systemd-udevd[245]: Received udev control message (PING)
[    7.833741] testsuite-64.sh[269]: + udevadm settle
[    7.833741] testsuite-64.sh[269]: + btrfs filesystem show
[    7.873698] testsuite-64.sh[360]: Label: 'btrfs_root'  uuid: deadbeef-dead-dead-beef-000000000000
[    7.873698] testsuite-64.sh[360]:         Total devices 1 FS bytes used 144.00KiB
[    7.873698] testsuite-64.sh[360]:         devid    1 size 350.00MiB used 88.00MiB path /dev/sda
[    7.891858] testsuite-64.sh[269]: + test -e /dev/disk/by-uuid/deadbeef-dead-dead-beef-000000000000
[    7.898248] systemd[1]: systemd-journald.service: Received EPOLLHUP on stored fd 58 (stored), closing.
[    7.908257] systemd[1]: Received SIGCHLD from PID 269 (bash).
[    7.908462] systemd[1]: Child 269 (bash) died (code=exited, status=1/FAILURE)
[    7.908658] audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=testsuite-64 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
[    7.908770] systemd[1]: testsuite-64.service: Child 269 belongs to testsuite-64.service.
[    7.908919] systemd[1]: testsuite-64.service: Main process exited, code=exited, status=1/FAILURE
[    7.909037] systemd[1]: testsuite-64.service: Failed with result 'exit-code'.
```

The `flock` definitely does what it should:
```
[    7.403605] systemd-udevd[353]: sda: Failed to flock(/dev/sda): Resource temporarily unavailable
[    7.403718] systemd-udevd[353]: sda: Block device is currently locked, installing watch to wait until the lock is released.
[    7.403811] systemd-udevd[353]: sda: Adding watch on '/dev/sda'
```

but looks like the issue is somewhere else...

/cc @yuwata, @poettering

**Comment by yuwata** [comment]
After mkfs, `udevadm settle` is called before udevd detecting the device close. How about to insert a small delay before the settle or use a loop to check the devlink (IIRC, you already introduced a helper function for that)?

**Comment by yuwata** [comment]
Hm, still failed... Not sure, but I hope #22717 helps the current situation.

**Comment by mrc0mmand** [comment]
Closing this one in favor of https://github.com/systemd/systemd/pull/22717 (which includes both commits already).

**Pull request closed without merging**
