### PR TITLE
do not expose enum types in public headers

### PR DESCRIPTION
**Pull request by poettering**
They are problematic, since we can never extend them since that might widen their width.

In all actually public headers we hence use strings for this, let's do for a few headers that are supposed to be made public eventually, but currently aren't. Let's fix this before it's too late.

With this merged there are no enum types in public or future public headers left.

### CODE REVIEW

**Comment by vcaputo** [comment]
Why not just make the public API using these enum types `int` instead of the enum?

It seem silly to require mapping strings back to numeric types at the API boundary because hypothetically these types might grow larger.  You've already thrown out compile-time type checking of the enum by switching to strings, so why not just use int so you're at least not incurring the overhead of mapping strings to ints at every public API call?

For the public header just replace the enum with a list of defines.  You can use an X-Macro pattern to produce the enum on internal usage and list of defines for public usage from a single source.  I presume we want to preserve enum usage as much as possible for systemd callers, for the debugging and compile-time checking niceties.

**Comment by keszybz** [comment]
> They are problematic, since we can never extend them since that might widen their width.

Yep, this is a bug we need to fix.

> Why not just make the public API using these enum types `int` instead of the enum type?

Or even uint64_t if  there's any likelyhood of ever needing so many flags. We do want to have enums, so the compiler can nicely describe the values for the debugger, but in function signatures, a fixed type should be used.

There's also a question of consistency. Various headers use the enum-in-declaration+int-in-function pattern. It'd be nice to keep all headers from the same project in a similar style.

**Comment by poettering** [comment]
You need to define the enums with all their values twice then, once anonymously in the public header, and then another time with a type name internally. And then you *also* need the string table anyway (because we do need that for everything else). These three table of essentially the same stuff suck, because they get out of sync. With this patch we only need the string tables and the internal definition, the public one goes away. Which I prefer I must say.

I wished there was a way to force enum width in a type.

**Comment by poettering** [comment]
i wished there was a gcc extension with an attribute or so that forces the width of an enum to be something we specify...

**Comment by poettering** [comment]
we could of course hack around this and define a macro like this:

```c
#define __SD_FORCE_ENUM_S64(uniq) \
UNIQ_T(bottom, q) = INT64_MIN, \
UNIQ_T(top, q) = INT64_MAX

#define _SD_FORCE_ENUM_S64 __SD_FORCE_ENUM_S64(UNIQ)
```

Then we can define any enum like this:

```c
typedef sd_foo_enum {
        SD_FOO_XYZ,
        SD_FOO_ABC,
        _SD_FORCE_ENUM_S64,
} sd_foo_enum;
```

I wonder where that is placed on the ugliness scala

**Comment by keszybz** [comment]
> You need to define the enums with all their values twice then, once anonymously in the public header, and then another time with a type name internally.

No, not really. If I say that MYCONSTANT=5, I'm not saying anything about the width of the variable where it will be stored (except that it needs to be at 3 bits). I don't think there's any issues with stuff defined as enums, like for example `SD_JOURNAL_OS_ROOT` in sd-journal.h. It is some number, and the user may store it in `unsigned`, or `uint64_t`, etc. The *value* (or storage needs) for `SD_JOURNAL_OS_ROOT` will never change. The only thing that we can do while keeping backwards compatibility is add `SD_JOURNAL_FOO` that has more bits. That's why the type of the storage variable should not "fixed", and the enum type should not be used for it. sd_journal_open() dtrt. (Though unsigned would be nicer...).

**Comment by poettering** [comment]
> You need to define the enums with all their values twice then, once anonymously in the public header, and then another time with a type name internally.

But if you systematically use only uint64_t for the enums, then the compiler and gdb won't be able to take benefit of the extra semantics enums offer. i.e. gdb can't decode things for you, gdb won't be able to give you hints about packing or missing items in switches and so on. it's no better than a bunch of `#define`s then.

With this patch you can debug things nicely across the whole codebase (i.e. the external stuff sees a friendly string in gdb, the internal stuff a friendly enum). And gcc can do its things with the internal enum. Only thing missing is that the external stuff won't get all the gdb goodness with verifying enum typesafety.

**Comment by poettering** [comment]
Closing, since obsoleted by the recently merged #18557

**Pull request closed without merging**
