### PR TITLE
shortcut credential querying of the "org.freedesktop.DBus" bus driver pseudo-service

### PR DESCRIPTION
**Pull request by poettering**
A fix for #6120.

### CODE REVIEW

**Comment by smcv** [comment]
The outline of these changes makes a lot of sense to me, although I don't know sd-bus well enough to do a real review.

I assume these functions are only called when connected to a message bus (dbus-daemon or a reimplementation of dbus-daemon), and not for direct D-Bus connections (whatever is the sd-bus equivalent of DBusServer)? Using them on direct D-Bus connections would be wrong.

**Comment by smcv** [comment]
> When only a single credential field is queried we will still use the old
> calls

I would personally not have bothered with this optimization - it seems like more code for only a small benefit.

> which we'll also use if the new call isn't implemented

FYI, to help make an informed decision about the extent to which this code path is needed: GetConnectionCredentials was new in dbus 1.8 (2013). In Debian and Ubuntu, there are a few branches still supported where dbus is older than that, but they are very much superseded (Debian 7, Ubuntu 12.04 LTS, Ubuntu 14.04 LTS) - current Debian stable and current Ubuntu LTS have dbus 1.10, and even Debian oldstable has 1.8. I suspect the situation in RPM-land is similar. However, popular CI service travis-ci.org is still stuck on Ubuntu 14.04 LTS, if that's something you care about.

**Comment by poettering** [comment]
> I assume these functions are only called when connected to a message bus (dbus-daemon or a reimplementation of dbus-daemon), and not for direct D-Bus connections (whatever is the sd-bus equivalent of DBusServer)? Using them on direct D-Bus connections would be wrong.

correct.

**Comment by poettering** [comment]
> I would personally not have bothered with this optimization - it seems like more code for only a small benefit.

yeah, i was wondering whether to bother, but after all the code already existed, and I assumed I had to keep it for compat, and this way it gets regularly tested at least...

**Comment by keszybz** [comment]
LGTM.

**Pull request merged**
