### PR TITLE
add a new Korean translation

### PR DESCRIPTION
**Pull request by darkcircle**
this is a first commit for the Korean translation.

Thank you.

### CODE REVIEW

**Comment by zonque** [comment]
Nice, thanks!

**Comment by darkcircle** [comment]
@dongsupark  Thank you for your good suggestion. I totally agree about it.

**Comment by darkcircle** [comment]
@dongsupark then ... how would you think about committing yourself?

just you can add your "realname" &lt;email@address&gt;, and translation year. 
onto the header description, first.

and 

also you can edit/modify as you want, by using editor such as poedit, gtranslator, babel, and so on. because I agree all about it, and I love your contribution with your credit.

then, Last-translator might be changed. That's no problem, because our history is being in the header description.

Thanks.

**Comment by zonque** [comment]
Yes, please file new PRs for such improvements.

**Comment by dongsupark** [comment]
@darkcircle @zonque Yes, thanks for the feedback. I'll make new PRs.

**Pull request merged**
