### PR TITLE
efi-api: check the EFI_TCG2_FINAL_EVENTS_TABLE in efi_has_tpm2()

### PR DESCRIPTION
**Pull request by jiazhang0**
The EFI firmware may provide the TPM2 event log using EFI_TCG2_FINAL_EVENTS_TABLE stored in EFI configuration table, instead of the ACPI Table TPM2.

If the ACPI Table TPM2 doesn't exist, try to check whether EFI_TCG2_FINAL_EVENTS_TABLE is available or not.

Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>

### CODE REVIEW

**Comment by poettering** [comment]
hmm, why check for the ACPI table at all though?

Since which kernel version does /sys/kernel/security/tpm0/binary_bios_measurements exist?

**Comment by poettering** [comment]
that sysfs file, that requires explicit support in the kernel, while the original check just checked for firmware support, no?

**Comment by jiazhang0** [comment]
> hmm, why check for the ACPI table at all though?
> 
> Since which kernel version does /sys/kernel/security/tpm0/binary_bios_measurements exist?

I think efi_has_tpm2() is just used to confirm whether the UEFI firmware uses tpm2 chip to do the necessary measurements for the so-called measured/trusted boot and thus the generated eventlog can be deemed as the proof of measurements in OS. This is what TPM2_SUPPORT_SUBSYSTEM is trying to claim. So the check to the proof can be done using either ACPI TPM2 table or /sys/kernel/security/tpm0/binary_bios_measurements enumerated by EFI config table. In the newer kernel implementation, either ACPI table or EFI config table can be equally used to return tpm2 eventlog. Please see https://elixir.bootlin.com/linux/v5.19.17/source/drivers/char/tpm/eventlog/common.c#L74 for a reference.  

The interface to access to /sys/kernel/security/tpm0/binary_bios_measurements is available since Linux kernel 3.7. This interface initially was implemented in tpm_eventlog.c and only depends on ACPI support in kernel (see https://elixir.bootlin.com/linux/v3.7-rc1/source/drivers/char/tpm/Makefile), and in the newer kernel it is implemented in eventlog/efi.c or eventlog/acpi.c and depends on EFI/ACPI support in kernel (see https://elixir.bootlin.com/linux/v5.19.17/source/drivers/char/tpm/Makefile). Therefore, current efi_has_tpm2() requires to support the check to tpm2 eventlog through EFI config table.

**Comment by jiazhang0** [comment]
> that sysfs file, that requires explicit support in the kernel, while the original check just checked for firmware support, no?

I think the new sysfs path /sys/kernel/security/tpm0/binary_bios_measurements also checks the firmware support just from another path. The original check uses ACPI TPM2 table, and the new check uses EFI config table.

The workflow of TPM2 eventlog from EFI config table is:
- https://elixir.bootlin.com/linux/v5.19.17/source/drivers/firmware/efi/efi.c#L522: match_config_table() detects the TPMEventLog from raw EFI config table.
- https://elixir.bootlin.com/linux/v5.19.17/source/drivers/firmware/efi/tpm.c#L39: calculate the size of eventlog table in the raw EFI config table.
- https://elixir.bootlin.com/linux/v5.19.17/source/drivers/char/tpm/eventlog/efi.c#L16: read the eventlog through /sys/kernel/security/tpm0/binary_bios_measurements if the eventlog table is not empty.

**Pull request merged**
