### PR TITLE
build: install /etc/systemd/{system,user}-generators

### PR DESCRIPTION
**Pull request by topimiettinen**
Manual page `systemd.generators` refers to `/etc/systemd/{system,user}-generators`,
but the paths do not exist, so let's install them.

### CODE REVIEW

**Comment by yuwata** [comment]
BTW, not related to this change, and not a strong opinion, how about also creating e.g. `/etc/systemd/resolved.conf.d` or `/etc/systemd/networkd.conf.d`?

**Comment by keszybz** [comment]
> BTW, not related to this change, and not a strong opinion, how about also creating e.g. /etc/systemd/resolved.conf.d or /etc/systemd/networkd.conf.d?

I think the "official" way is to simply use `systemctl edit`, which will create those directories automatically. I don't think we should precreate .d directories for units, esp. considering that there'd be quite a few of them, making things very noisy.

**Comment by boucman** [comment]
@keszybz  IIUC these are the configuration directories for networkd/resolved, not the unit configuration directories...

**Comment by poettering** [comment]
Urks, I must say I am really not fond of this I must say. Let's keep /etc simple, and the generators stuff is already exotic enough to not show up in /etc at all. People who are capable of writing their own generators should be able to create these dirs on their own. I see no reason why we would confuse users with this.

In particular as generators are scripts, and scripts have no place in /etc anyway, and hence are a pretty bad fit to even advertise as such. 

hence, I'd really prefer to revert this one

**Comment by keszybz** [comment]
> hence, I'd really prefer to revert this one

Fine with me. I don't feel strongly either way.

**Comment by topimiettinen** [comment]
I'm not using /etc for generator scripts but to mask systemd-rc-local-generator and systemd-sysv-generator, which are useless in my system.

**Comment by topimiettinen** [comment]
`systemctl mask systemd-sysv-generator` tries to find a service called `systemd-sysv-generator.service`:
```
Unit systemd-sysv-generator.service does not exist, proceeding anyway.
Failed to mask unit: File /etc/systemd/system/systemd-sysv-generator.service: Read-only file system
```

**Comment by keszybz** [comment]
This is a bug in `systemd-sysv-generator`. It should not emit any error in case the sysv stuff is not installed.

**Comment by poettering** [comment]
> This is a bug in `systemd-sysv-generator`. It should not emit any error in case the sysv stuff is not installed.

Nope. the generator is not a unit. Using "systemctl mask" only works on units. 

generators are a lot more manual. You have to create the symlinsk for them yourself, systemctl won't help you for that, and you might need to create a subdir for that yourself

**Comment by keszybz** [comment]
Oh, I misread @topimiettinen's comment. I thought that this is the output from the generator, not from systemctl. My point was that those generators should be silent if their source of configuration is missing. I looked over the code of `systemd-sysv-generator` and `systemd-rc-local-generator` and they exit pretty quickly in that case, with at most some debug logging. There is no particular reason to mask them, they are two very small binaries and having them run and exit does not cause a measurable delay to boot.

**Comment by topimiettinen** [comment]
@keszybz They are still useless in my system and I like to keep it as lean as possible.

**Comment by boucman** [comment]
I though sysV support was a systemd compile-time option... maybe you want to play with that...

**Pull request merged**
