### PR TITLE
Add extra parameters from systemd cryptenroll

### PR DESCRIPTION
**Pull request by aplanas**
Based on https://github.com/systemd/systemd/pull/23556, this commit add support to parameters like:

--tpm2-pcrs=1:sha256:meson.build+3:2b54daa87eec627bb4d16a3c91c993307c190912bb1173d45dae843b71952018

Currently there are some limitations:

* If a bank is selected, should be the same (or empty) for all the PCR
* If a file is selected, SHA256 should be used to the all the digests
* If a PCR digest is set, all the PCR should also have a digest (this can be fixed using `sym_Esys_PCR_Read`)

Also, documentation and tests are not still done.

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, so there's #24351 which will cause major merge conflicts once merged.

**Comment by aplanas** [comment]
> Hmm, so there's #24351 which will cause major merge conflicts once merged.

Ah ... indeed. I will take an eye on it, thanks!

**Comment by poettering** [comment]
(btw, I think it would be great to have a new verb in the new systemd-measure tool that can resolve such PCR expressions, i.e. hash the specified files and then return the PCR expression with the literal hashes instead of the filenames)

**Comment by poettering** [comment]
https://github.com/systemd/systemd/pull/24351 has been merged now. Can you rebase before I review this, please?

**Comment by poettering** [comment]
ping @aplanas?

**Comment by poettering** [comment]
BTW, this should carry "Fixes #19204" somewhere.

(for some reason github refuses to allow me to link that issue here via "development", no idea what's going on.)

**Comment by poettering** [comment]
ping, btw? would love to see this land sooner or later!

**Comment by aplanas** [comment]
> ping, btw? would love to see this land sooner or later!

ack! I will push it harder

**Comment by ddstreet** [comment]
@aplanas fyi I opened https://github.com/systemd/systemd/pull/26027 which is only of limited benefit without this PR (i.e. being able to specify expected PCR values). You might find it useful to patch on top of my patch series, as I left it fairly easy to handle expected values if provided to tpm2_seal().

**Comment by poettering** [comment]
is there still interest in this?

**Comment by aplanas** [comment]
I think that the correct action here is to close it

**Pull request closed without merging**
