### PR TITLE
mount: fix mount command race with mountinfo

### PR DESCRIPTION
**Pull request by omidtboe**
Partial revert of commit 006aabbd052c 'mount: mountinfo event is supposed to always arrive before SIGCHLD'

I found this while working on an embedded system with systemd v240 and getting errors like:

systemd[1]: data.mount: Mount process finished, but there is no mount.
systemd[1]: data.mount: Failed with result 'protocol'.
systemd[1]: Failed to mount /data.

The assumption that new mountinfo is loaded before before processing SIGCHLD is not correct and during testing I verified the file system was indeed mounted using statvfs.

### CODE REVIEW

**Comment by poettering** [comment]
hmm, the question though is how can this happen, the sigchld handlers have a higher sd-event prio than the mountinfo ones, hence, this should always happen in order. before we manage any fix like that, we should figure out what's going in really here, otherwise it's just fixup up symptoms, but not the core of the problem

**Comment by omidtboe** [comment]
I understand. I'm new to the systemd code, but have tried to look into how this works.
If I understand correctly both the sigchld and mountinfo events is handled using a sigle epoll instance through sd_event_run. This assumes that the always kernel delivers the mountinfo event before the sigchld event. Is this verified?
What is the reason for needing to check both success of the mount command and that mountinfo has been updated?

**Comment by omidtboe** [comment]
I believe there are two things that affect this behaviour. One is the waitid call in manager_dispatch_sigchld. The waitid call returns child processes by time of creation (PID order), not time of completion. So the order of a PIDs SIGCHLD compared to other events cannot really be relied upon and we can get sequences like this:

> Mount A is forked
Process B is forked (PID A < PID B)
Process B process finishes
manager_dispatch_signal_fd is called (PID B)
manager_dispatch_sigchld is called 
(Mountinfo is updated for mount A, but not yet read by systemd)
Mount A process finishes
Waitid in manager_dispatch_sigchld returns PID A
error: Mount process finished, but there is no mount.

It is made more likely to occur since manager_dispatch_sigchld handles all waiting children before sd_event_run/sd_event_wait fetches new events.

**Comment by karelzak** [comment]
Sounds like issue #10872.

**Comment by poettering** [comment]
> It is made more likely to occur since manager_dispatch_sigchld handles all waiting children before sd_event_run/sd_event_wait fetches new events.

It doesn't. Not in any recent systemd at least. When we get a SIGCHLD we don't do much, we just enable a "defer event source" and return to the event loop. That defer event handler, each time it is called processes exactly one process, returning back to the event loop. The handler is left enabled after each process that is processed. Which means it's likely called on the next event loop iteration again. Only when waitid() finally responds that there are no further processes waiting the defer event handler is turned off again. Until another SIGCHLD is seen, at which point the defer event handler is turned on again.

Now, that defer event handler runs at event loop priority NORMAL-7. (lower numeric prios are run first, higher numer prios last). The /proc/self/mountinfo event handler runs at event loop priority NORMAL-10 (i.e is run before that mentioned deferred child process event handler). 

This hence means: /proc/self/mountinfo events should be processed first, always, and there's no tight loop around waitid(). Instead control is always returned back to the event loop, and thus mountinfo checked events should be seen again.

**Comment by poettering** [comment]
ah, hmm, i take that back. i see the race now, @msekletar made me understand...

**Comment by poettering** [comment]
I prepped a different PR to fix this here: #13097. It goes a different way to fix this. PTAL.

**Comment by keszybz** [comment]
Closing in favour of #13097.

**Pull request closed without merging**
