### PR TITLE
core: factor root_directory application out of apply_working_directory

### PR DESCRIPTION
**Pull request by behrmann**
Ok, in response to #12498 I split out the application of the root directory out of `apply_working_directory`. It has received cursory testing in so far, that I dropped the patch into the patch queue for the systemd Debian package (currently 242-2 from experimental) and built that package for buster. The buster machine booted successfully and did not catch fire, also both
```
# /etc/systemd/system/chrootdebug.service
[Unit]
Description=Debug chroot

[Service]
Type=oneshot
User=daemon
# AmbientCapabilities=CAP_SYS_CHROOT 
RootDirectory=/srv/stretch-chroot
ExecStart=/bin/bash -c 'echo hello world from $(id -u) and $(id -ru) at $(pwd)'
```
and
```
# /etc/systemd/system/chdirdebug.service
[Unit]
Description=Test service to debug chdir

[Service]
Type=oneshot
User=behrmann
ExecStart=/bin/bash -c "echo $(pwd)"
WorkingDirectory=/home/behrmann
```
printed `hello world from 1 and 1 at /` and `/home/behrmann` respectively.

Fixes: #12498

### CODE REVIEW

**Comment by yuwata** [comment]
`test-execute` fails.

**Comment by behrmann** [comment]
OK, I'll have a look at this on Monday.

**Comment by behrmann** [comment]
I've just had a look and the `test-execute` fails for the parent commit (and seems to fail in the same way) as well, which might explain why applying the patch to stable worked for me.

Tomorrow I'll try rebasing against master and if that doesn't work I'll look further.

**Comment by behrmann** [comment]
@yuwata I rebased against current master, where it applied cleanly and ran the tests. I am a bit puzzled. On my Arch machine `test-execute` passes, whereas on my Debian buster machine it doesn't. I guess it's fine though, as the CI now passes as well and the patch cleanly applied on stable and worked.

**Comment by yuwata** [comment]
> On my Arch machine `test-execute` passes, whereas on my Debian buster machine it doesn't.

Which test in `test-execute` fails on Debian?

@evverx Are there no debian CIs now? What distribution used in travis-ci or systemd.systemd?

**Comment by behrmann** [comment]
[Here a gist](https://gist.github.com/behrmann/d53f9e7215731c2cb8b9f1de0f75aa8e) with the `testlog.txt` on my Debian buster machine.

**Comment by yuwata** [comment]
> Test timeout when testing exec-dynamicuser-statedir.service

It looks unrelated.

**Pull request merged**
