### PR TITLE
shutdown: use MNT_FORCE after initial failure.

### PR DESCRIPTION
**Pull request by neilbrown**
If umount_all() finds that nothing can be unmounted,
switch to using MNT_FORCE to cause requet to non-responsive
servers to abort.  This allows processes that are blocking on those
mounts to abort, and then the mounts become free to be unmounted.

This will not help much while there is an earlier synchronous
sync() call, as mounts from non-responsive servers can block there
if there is any dirty data.

### CODE REVIEW

**Comment by sourcejedi** [comment]
Thanks for the clarification about what MNT_FORCE does!  I like that comment.

The "extra" code v.s. what we used to do is mainly to print if the MNT_FORCE was needed or not, right?  It sounds like a good idea, but it should only happen when there is some process still using the FS.  We already tried to terminate the process, but it was stuck in uninterruptible IO state.  If we want warnings, maybe it would be more general, if we add a warning earlier when SIGTERM times out and we have to resort to SIGKILL.  (And skip the "Sending SIGKILL to remaining processes" if there were no processes left.  `broadcast_signal()` could change to return 0 on timeout, 1 on success).

I think that would help us, by avoiding extra complexity in the unmount code.  That code is already complex to read and has at least one obscure oversight.

**Comment by neilbrown** [comment]
> The "extra" code v.s. what we used to do is mainly to print if the MNT_FORCE was needed or not, right?
Another change against the pre-2013 code is that it doesn't try MNT_FORCE until it is clear that not using MNT_FORCE doesn't make progress, so the code is a little more cautious.  I don't know how important that caution is, but it seemed safest.

**Comment by sourcejedi** [comment]
Thanks, I'd wrongly assumed the MNT_FORCE change was much more recent than 2013.

I have a last confusion which I can't answer from the comments about systemd-shutdown.  We have three different ways we can block or poll on pending NFS writes.

1. sync
2. remount read-only
3. unmount without MNT_FORCE

The comments I'm reading say that 1) and 2) can hang forever if the network is down.  It's therefore argued it's problematic that we block on sync().  And that we shouldn't bother remounting read-only (for NFS).  But this PR says method 3) is safe, and doesn't block.

Have I missed something else, or is that what this PR relies on?  Is this guaranteed as a documented or undocumented kernel API?  If so, can we make this distinction clearer in the revised systemd-shutdown code?

**Comment by sourcejedi** [comment]
> Another change against the pre-2013 code is that it doesn't try MNT_FORCE until it is clear that not using MNT_FORCE doesn't make progress, so the code is a little more cautious. I don't know how important that caution is, but it seemed safest.

If we learned that the caution was super important, we would want to hoist this to the loop one level up, in `shutdown.c`.  It sounds easy enough.

OTOH, if we hypothetically had assurances that the classic usage is to be "un"cautious, and that's always supposed to be safe, then we could push the retry down so it's immediately around the `umount()` call.  (Which ideally should be equivalent to always using MNT_FORCE, modulo how we log about it.  But I happily defer to your judgement if you don't like to trust that).

Reading this version of the code is confusing; it doesn't explain why the retry wants to be where it is.

**Comment by neilbrown** [comment]
You ask about a documented kernel API.  That would be nice, wouldn't it! NFS has a long history of behaving slightly differently to what you might expect of other filesystems, and I suspect other networked filesystems tend to follow suit. Some of these API changes have been documented post-hoc, but not all.
There have been some discussions recently over on the linux-nfs email list about MNT_FORCE and what to do when a sever goes away.  As yet there is nothing really conclusive, just a few different concerns pulling in different directions.
My currently leaning is that I'd like some interface other than MNT_FORCE.  I don't think using MNT_FORCE in a container is likely to be a good idea.  It should be say when shutting down the whole system, but otherwise I wouldn't using it automatically (a sysadmin might still want to use it manually).
I'm MNT_DETACH has a lot going for it, if only we could still interact with the unmounted filesystem, e.g. to encourage it to 'sync' and to see if it has.  In a container I would probably MNT_DETACH everything for shutdown.  Outside a container ... I'm not sure yet.

My suggestion to use MNT_FORCE (for non-container shutdown at least) is based on a fairly intimate knowledge of the implementation (bugs and all).  I think it would improve reliability over the current code, but not completely.

**Comment by neilbrown** [comment]
> Reading this version of the code is confusing; it doesn't explain why the retry wants to be where it is.

I thought it was fairly clear that it retries until it doesn't make progress, then it retries with MNT_FORCE until it doesn't make progress.  I guess I could make that a bit clearer.  I want to change it to avoid using MNT_FORCE for containers so I might try to make the code more transparent then.

**Comment by sourcejedi** [comment]
> I thought it was fairly clear that it retries until it doesn't make progress, then it retries with MNT_FORCE until it doesn't make progress.

_what_ retries until it doesn't make progress?

Answer: `unmount_all()`.  But `unmount_all()` is itself retried until it makes progress, at a higher level in `shutdown.c`.

So you are asserting that it makes sense to retry with MNT_FORCE after unmounting has not made any progress, and we do not need to wait until after we have tried to tear down all the loopback mounts, for example, as well.

I don't understand what basis you have for making that assertion.

**Comment by sourcejedi** [comment]
Apologies if my second comment about unmount v.s. remount is a bit of a de-rail.

Thanks to the comments and documentation you worked to add, I think I understand why it's useful to add MNT_FORCE.  Certainly outside of containers, anyway.

What confuses me is the assertion it's safe to first try unmount _without_ MNT_FORCE.  That this is not expected to hang even if the server is unavailable and there are pending writes.  Instead it's asserted to return failure (due to open files on the mount).  When the remounting read-only is not considered safe.

I sympathize this might not be documented, or due to obscure bugs, whatever.  But if we want to avoid problems being re-introduced, I think we want to tell the reader of this code about the constraint that shaped it.

E.g.

    -                    If the filesystem is a network fs, also skip the
    -                    remount.  It brings no value (we cannot leave
    -                    a "dirty fs") and could hang if the network is down.

    +                    If the filesystem is a network fs, also skip the
    +                    remount.  It brings no value (we cannot leave
    +                    a "dirty fs").  But it could hang if the network is down.
    +                    Note unmount is safer, it does not hang in the same cases.
    +                    This is not due to the use of MNT_FORCE, it's just

a bug with kernel network filesystems?

a complex interaction of some network filesystem semantics which this margin is too small to contain?

    +                    - @neilbrown 2017.

Or it might be able to use a bug report as a citation.  So long as it points to a not-too-long story (or summarizes it) that shows the constraint and where it was discovered, and without the reader having to `git checkout` the code at the time of the bug to understand it.

**Comment by sourcejedi** [comment]
@neilbrown 

I came across a bug report that I believe explicitly shows `umount()` for NFS - not `mount(MS_REMOUNT)` - hanging for 30 minutes (and retrying in the kernel):  https://github.com/systemd/systemd/pull/5688

This seems to contradict your claims that umount of NFS would never hang.

If no-one, including you, verify the compromise in this PR, then the simplest resolution is to restore the original code, always using MNT_FORCE, and include that great comment about what MNT_FORCE means.

I can well imagine that the original use of MNT_FORCE here was for roughly the right reason.  E.g. someone looking at Debian init scripts which use `umount -f` for linux <= 2.4.10 (and above that, `umount -f -l`, heh).  But that the addition of remounting _all_ filesystems read-only, which was not traditionally done in system V init, had the implication of a hang which was overlooked.  I'd love to think that that's the whole story, and the only other thing we need to worry about is the `sync()` we added.

---

If retrying with MNT_FORCE avoids _some_ hang, but it wouldn't be "cautious" enough if we used MNT_FORCE right away, then we need a comment with some citation for this compromise.

As above, I would still consider "in 2017 Neil Brown gave us the best known procedure to unmount NFS, based on various experience which has not been written up" a pretty useful citation.  But if the comment makes a broader assertion than can be justified, leaving it contradicted by some public example, then it's not necessarily going to help the reader.

**Comment by neilbrown** [comment]
> This seems to contradict your claims that umount of NFS would never hang.

It does seem to, but it is hard to be sure exactly what is happening.
Firstly we see that the attempt by systemd to stop the "mnt.mount" unit blocks for at least 30 minutes.  This is because /sbin/mount.nfs was trying to 'lstat()' the mountpoint, and this does hang.
This issue was addressed in commt 83897d5470190a9818df50026cf38cd97114f77d together with a change in util-linux.
Then we see "Remounting '/mnt' read-only with options..." and "Unmounting /mnt." where the second appears to block.
what is particularly strange here is that options listed in the Remounting line include "hard".  When a hard mount is in used, the error reported by the kernel is "server XXX not responding, still trying", but the error seen here is "server XXX not responding, timed out", which suggests a "soft" mount.  I'm not sure what this means.  I think there are cases where a "soft" request is used in connection with a "hard" mount, possibly when checking with rpcbind to see if the port number has changed ... or something.
The fact that "Remounting" didn't hang is peculiar.  mount(MNT_REMOUNT) performs an operation very similar to "lstat", and so is expected to hang if the server is not available.  Only umount() is careful to avoid that. The reported didn't identify the kernel they were running, so I cannot dig more deeply.
If the kernel is older than v3.12, that would explain way umount() could hang, but doesn't explain why remount didn't hang.

The separate observation that "mount(MS_REMOUNT|MS_RDONLY)" was seen to hang is, as I said, expected.  I did sent a patch for the a few months ago, but there was no response and i haven't pursued it.

**Comment by sourcejedi** [comment]
Thanks, that makes sense.  The part that confused me most was the difference between `/bin/umount` / `umount.nfs` and bare `umount()`.

Sorry for ranting again.  After touching systemd-shutdown recently, I want to keep understanding it.  My conclusion:

1. Why not move the retry either to the lowest level inside `mount_points_list_umount()`, or to the top level in `shutdown.c` ?

2. Would you extend the remount comment with something like

   > But it could hang if the network is down. umount() will be safer, it has had more attention paid to it.  E.g. umount() on NFS avoids waiting for the server (even without MNT_FORCE). Where mount() with MS_REMOUNT|MS_READONLY does not take such care.

    I think reading the code without looking at your explanation, still leaves me asking "are you sure?" or "why?".  If you put the comments for remount and unmount together, they implicitly answer "trust me".  I'm hoping we can do a bit better.  Avoid having to trust that two specific comments were written with reference to one another.  And be more explicit about what it's asking me to trust, which simply looking in the manpage doesn't explain.

    The first sentence suggests a "why".  I.e. most uses either manually or in shutdown scripts saw no reason to remount read-only.

**Comment by neilbrown** [comment]
Thanks for your observations about the multiple levels of retry, I hadn't noticed that.  It does make it awkward to find the "right" place to retry.  This has caused by to go back to the start and ask what I'm am trying to achieve with the current retry handling.
The benefit of using MNT_FORCE is that some pending requests will fail so some blocked processes might be able to continue and then exit, thus allowing the filesystem to be unmounted.
The benefit of NOT using MNT_FORCE is that it allows unwritten data to ultimately be written (if the server ever responds) and processes in the middle of a task to complete.
As we have just called "sync" (and at least waited a while) there shouldn't be any unwritten data that we can do anything useful with, and as we are in shutdown and have sent SIGKILL to any remaining processes, we shouldn't expect them to be generating new data or doing anything useful.
So I think I've convinced my self to go back to the original (pre-2013) code and always use MNT_FORCE.  If anything is still mounted this late in shutdown, then something is wrong and we should try as hard as we can to make progress.
I'll force-push an alternate patch which just adds MNT_FORCE and adds some comments.

**Comment by sourcejedi** [comment]
Thanks for working with us and generally sharing your experience :).

**Comment by poettering** [comment]
OK, let's merge this. I trust you are right on all of this @neilbrown. Let's see how this works out.

**Pull request merged**
