### PR TITLE
meson: fix build error of test-dnssec-complex

### LINKED ISSUE #19065: missing file on build
**systemd version the issue has been seen with**
 > 248-rc4

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux leda 5.11.7-arch1-1 #1 SMP PREEMPT Wed, 17 Mar 2021 16:59:58 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > build succeeds

**Unexpected behaviour you saw**
 > build fails with missing file

**Steps to reproduce the problem**
 > build with a stripped down set of features
```
meson setup --prefix /usr --libexecdir lib --sbindir bin --buildtype plain --auto-features enabled --wrap-mode nodownload -D b_lto=true -D b_pie=true ~/version_control/systemd systemd-build --libexecdir /usr/lib32 --libdir /usr/lib32 -Dversion-tag=248rc4-1-arch -Dmode=release -Daudit=false -Dblkid=false -Dgnu-efi=false -Dima=false -Dkmod=false -Dlibcryptsetup=false -Dlibidn2=true -Dlibiptc=false -Dlz4=false -Dmicrohttpd=false -Dpam=false -Dpython=false -Dseccomp=false -Dutmp=false -Dhibernate=false -Dldconfig=false -Dresolve=false -Defi=false -Dtpm=false -Denvironment-d=false -Dbinfmt=false -Drepart=false -Dcoredump=false -Dpstore=false -Doomd=false -Dlogind=false -Dhostnamed=false -Dlocaled=false -Dmachined=false -Dportabled=false -Dsysext=false -Duserdb=false -Dhomed=false -Dnetworkd=false -Dtimedated=false -Dtimesyncd=false -Dremote=false -Dcreate-log-dirs=false -Dnss-myhostname=false -Dnss-mymachines=false -Dnss-resolve=false -Dnss-systemd=false -Dfirstboot=false -Drandomseed=false -Dbacklight=false -Dvconsole=false -Dquotacheck=false -Dsysusers=false -Dtmpfiles=false -Dimportd=false -Dhwdb=false -Drfkill=false -Dxdg-autostart=false -Dman=false -Dhtml=false -Dtranslations=false -Ddbuspolicydir=/usr/share/dbus-1/system.d -Ddefault-hierarchy=unified -Ddefault-kill-user-processes=false -Ddefault-locale=C -Dfallback-hostname=archlinux -Dnologin-path=/usr/bin/nologin -Dntp-servers="0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org" -Ddns-servers="1.1.1.1 9.9.9.10 8.8.8.8 2606:4700:4700::1111 2620:fe::10 2001:4860:4860::8888" -Drpmmacrosdir=no -Dsysvinit-path= -Dsysvrcnd-path=
```

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
[789/1303] Generating dns_type-from-name.h with a custom command (wrapped by meson to capture output)
[790/1303] Compiling C object test-verify.p/src_analyze_test-verify.c.o
[791/1303] Compiling C object test-login-tables.p/src_login_test-login-tables.c.o
[792/1303] Compiling C object test-resolve-tables.p/src_resolve_test-resolve-tables.c.o
[793/1303] Compiling C object test-resolved-packet.p/src_resolve_test-resolved-packet.c.o
[794/1303] Compiling C object test-dnssec-complex.p/src_resolve_dns-type.c.o
FAILED: test-dnssec-complex.p/src_resolve_dns-type.c.o 
gcc -m32 -Itest-dnssec-complex.p -I. -I../systemd-stable -Isrc/basic -I../systemd-stable/src/basic -Isrc/fundamental -I../systemd-stable/src/fundamental -Isrc/systemd -I../systemd-stable/src/systemd -I../systemd-stable/src/libsystemd/sd-bus -I../systemd-stable/src/libsystemd/sd-device -I../systemd-stable/src/libsystemd/sd-event -I../systemd-stable/src/libsystemd/sd-hwdb -I../systemd-stable/src/libsystemd/sd-id128 -I../systemd-stable/src/libsystemd/sd-journal -I../systemd-stable/src/libsystemd/sd-netlink -I../systemd-stable/src/libsystemd/sd-network -I../systemd-stable/src/libsystemd/sd-resolve -Isrc/shared -I../systemd-stable/src/shared -flto=auto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -ffunction-sections -fdata-sections -Werror=shadow -include config.h -march=x86-64 -mtune=generic -O2 -fno-plt -D_FORTIFY_SOURCE=2 -fPIE -MD -MQ test-dnssec-complex.p/src_resolve_dns-type.c.o -MF test-dnssec-complex.p/src_resolve_dns-type.c.o.d -o test-dnssec-complex.p/src_resolve_dns-type.c.o -c ../systemd-stable/src/resolve/dns-type.c
../systemd-stable/src/resolve/dns-type.c:18:10: fatal error: dns_type-from-name.h: No such file or directory
   18 | #include "dns_type-from-name.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #19065.

### CODE REVIEW

**Review by bluca — APPROVED** [review]
Lgtm

**Comment by keszybz** [comment]
Hmm, the commit changes how the test is invoked, but the justification is that if fixes a compilation failure. Can you explain what is going on in the the commit message?

**Comment by bluca** [comment]
> Hmm, the commit changes how the test is invoked, but the justification is that if fixes a compilation failure. Can you explain what is going on in the the commit message?

Isn't this changing the linkage of the test binary?

**Comment by keszybz** [comment]
Oh, indeed. I misread the diff.

Yeah, this looks OK.

**Pull request merged**
