### PR TITLE
various nss module/resolved fixes

### PR DESCRIPTION
**Pull request by poettering**
Mostly follow-ups for #4164

### CODE REVIEW

**Comment by poettering** [comment]
@martinpitt please have a look!

**Comment by poettering** [comment]
will fix

**Comment by keszybz** [comment]
LGTM.

**Comment by keszybz** [comment]
I thoought you wanted to wait for the commit message to be fixed.

**Comment by martinpitt** [comment]
Argh, sorry; I wanted to indeed, but for some reason I thought this morning it was corrected.

**Comment by keszybz** [comment]
FWIW, I find it useful to add such comments in the merge commit. Sometimes asking for an updated version is not worth the trouble (and potential confusion ;)).

**Pull request merged**
