### PR TITLE
udev: Add media/by-path symlinks

### PR DESCRIPTION
**Pull request by ghost**
Currently, Video4Linux `/dev/video*` devices have udev rules in `60-persistent-v4l.rules` to create persistent symlinks in `/dev/v4l/*`, but for the related media controller devices, there is no such thing. Just like for other devices, it's useful to have persistent symlinks, so here is a suggestion for adding by-path symlinks for `/dev/media*` devices.

I'm not sure what the best approach is though:

1. Should a rule for media controller devices become a part of the existing `60-persistent-v4l.rules` file, or should it reside in its own file?
2. Should the symlinks for `media*` be created next to the symlinks for `video*` in `/dev/v4l/`, or should they be grouped separately under `/dev/media/`?

Either way, I would appreciate if you considered including persistent paths for `/dev/media*` in systemd's udev rule library.

Thank you!

### CODE REVIEW

**Comment by poettering** [comment]
patch looks superficially good to me. i have no idea of the media subsystem though.

maybe we can get one of the subsystem maintainers to comment on this:

@pinchartl @mchehab any chance you can comment on this, and in particular @mstaudt-g's questions above?

**Review by poettering — APPROVED** [review]

**Comment by poettering** [comment]
@yuwata should comment on this too i guess, before we merge this.

**Comment by pinchartl** [comment]
For cameras, I don't foresee libcamera making use of this feature. Other camera frameworks or applications may have a use for it, and I can imaging it being useful for other type of media devices too. This being said, I don't have good visibility on the use cases, so an explanation in the commit message would be nice.

**Review by yuwata — APPROVED** [review]
LGTM superficially.

**Comment by mchehab** [comment]
> > This being said, I don't have good visibility on the use cases, so an explanation in the commit message would be nice.
> 
> Persistent links are a handy tool to make scripts self-documenting during development or in tests, as well as less error prone in case of devices changing enumeration order. For media controllers, one can alternatively scan through all of them and look for a matching `bus_info` in their `struct media_device_info`, but the links are much handier when drafting something by hand.
> 
> Do you consider this a valid reason for the udev rule?
> 
> > 1. Should a rule for media controller devices become a part of the existing `60-persistent-v4l.rules` file, or should it reside in its own file?
> > 2. Should the symlinks for `media*` be created next to the symlinks for `video*` in `/dev/v4l/`, or should they be grouped separately under `/dev/media/`?
> 
> Do you have a preference concerning these questions?

Answering @poettering question, I like with the idea of having persistent symlinks for the APIs that are part of the media subsystem.

With regards to (1), I would prefer to have a single persistent rules file covering all APIs for the media subsystem on a single file, named after the subsystem's name - so, rename 60-persistent-v4l.rules to 60-persistent-media.rules and place there rules for all 5 uAPIs (see https://www.kernel.org/doc/html/latest/userspace-api/media/index.html) at the same place:
- V4L2
- Digital TV (DTV)
- media controller
- remote controller
- hdmi CEC.
 
From the above, devices that use V4L2 and Digital TV API are more demanding for persistence: cameras may physically be located on different rooms; DTV devices are physically connected to different satellite dishes and/or to an anntena or  cable TV network(s). So, multiple board arrangements are typically using different sources of signal. The other media devices typically don't demand persistence.

With regards to (2) I would prefer to have the media controller nodes mapped as /dev/media-controller.

 ---

While we are here, perhaps you could also propose some persistent rules for DVB devices. IMO, such rule should get the device name via [DVB frontend API's FE_GET_INFO ioctl]( https://www.kernel.org/doc/html/latest/userspace-api/media/dvb/fe-get-info.html#fe-get-info). This is not enough, as multiple devices of the same model may be present. So, PCI BUS or USB port needs to be combined to provide an unique namespace.

**Comment by pinchartl** [comment]
> Persistent links are a handy tool to make scripts self-documenting during development or in tests, as well as less error prone in case of devices changing enumeration order. For media controllers, one can alternatively scan through all of them and look for a matching `bus_info` in their `struct media_device_info`, but the links are much handier when drafting something by hand.
> 
> Do you consider this a valid reason for the udev rule?

It's at least valid enough to not make me push back :-)

> > 1. Should a rule for media controller devices become a part of the existing `60-persistent-v4l.rules` file, or should it reside in its own file?
> > 2. Should the symlinks for `media*` be created next to the symlinks for `video*` in `/dev/v4l/`, or should they be grouped separately under `/dev/media/`?

In `/dev/media/` please, or at least not in `/dev/v4l/`. The MC API is not limited to V4L2.

**Comment by poettering** [comment]
> While we are here, perhaps you could also propose some persistent rules for DVB devices. IMO, such rule should get the device name via [DVB frontend API's FE_GET_INFO ioctl](https://www.kernel.org/doc/html/latest/userspace-api/media/dvb/fe-get-info.html#fe-get-info). This is not enough, as multiple devices of the same model may be present. So, PCI BUS or USB port needs to be combined to provide an unique namespace.

So we have various "xyz_id" plugins for udev in our tree that can issue ioctls to specific devices to get some subsystem specific metadata to include in symlinks. But generally we really want to avoid that, and much prefer if the data is instead exported via sysfs. Or in other words: we'd much prefer if the naming logic can be implemented exclusively via udev rules, without having to resort to C code to get the data out of the kernel.

As you might know one of these plugins is "v4l_id", which issues ioctls on the v4l devices. I'd really prefer if for newer media stuff (and in fact *any* new subsystem) we could settle on using sysfs attrs as the primary place to acquire the info though if at all possible.

**Comment by poettering** [comment]
> With regards to (1), I would prefer to have a single persistent rules file covering all APIs for the media subsystem on a single file, named after the subsystem's name - so, rename 60-persistent-v4l.rules to 60-persistent-media.rules and place there rules for all 5 uAPIs (see https://www.kernel.org/doc/html/latest/userspace-api/media/index.html) at the same place:
> 
>     * V4L2
> 
>     * Digital TV (DTV)
> 
>     * media controller
> 
>     * remote controller
> 
>     * hdmi CEC.

While moving files around is certainly possible, we are a bit conservative with this. That's because we generally tell people that to override or disable the upstream naming rules (that are shipped in /usr/lib/udev/rules.d/) people should create equally named rules file in /etc/udev/rules.d/, which will then take precedence. Each time we rename rules files upstream this hence has the chance of breaking some people's setups, because suddenly *both* their local rules (under the old filename) and the new upstream rules (under the new filename) are applied.

I am not totally opposed in renaming things (for example, to deprecate stuff, or fix some fundamental issues), but if it's just about appearing prettier/cleanier I am not too convinced.

looking into the current v4l rules they appear very v4l specific, hence I think we can just keep them as they are, but for the other stuff create a new "media" related file? not perfect, but still somewhat clean?

**Comment by poettering** [comment]
it appears to me that the proposed PR is close enough to what @mchehab asked for. hence to me it appears ok to merge? 

symlinks for other media device types we can then add to the same rules file later?

**Comment by pinchartl** [comment]
I don't foresee a situation where a given hardware device would register multiple media devices. The whole point of the media controller API is to gather multiple hardware devices under a single umbrella. This may be relevant in this context, we're actually looking at ways to create a media device without a parent, or at least without a predictable parent, when multiple instances of the same hardware device type need to be bundled in a single media device and none of the hardware devices can be considered as a primary device.

**Comment by mchehab** [comment]
> it appears to me that the proposed PR is close enough to what @mchehab asked for. hence to me it appears ok to merge?
> 
> symlinks for other media device types we can then add to the same rules file later?

Yeah, it is close enough. I would add a comment before the media-controller ruleset before the first line of the media controller part, e. g.:

```
# Media controller rules
ACTION=="remove", GOTO="persistent_media_ctl_end"
...
```

And maybe rename the namespace from "/dev/media/" to "dev/media-ctl/" (or /dev/media-controller/) to be clearer that what it is inside that directory is media controller devices, instead of all media devs.

**Comment by pinchartl** [comment]
Given that the device nodes are called `/dev/media*`, I think naming the directory `/dev/media/` would be clearer for users. I don't care too much though. `/dev/mc/` could also be a candidate.

**Comment by mchehab** [comment]
> Given that the device nodes are called `/dev/media*`, I think naming the directory `/dev/media/` would be clearer for users. I don't care too much though. `/dev/mc/` could also be a candidate.
`/dev/mc/` works for me.

**Comment by mchehab** [comment]
@poettering 
> So we have various "xyz_id" plugins for udev in our tree that can issue ioctls to specific devices to get some subsystem specific metadata to include in symlinks. But generally we really want to avoid that, and much prefer if the data is instead exported via sysfs.

To avoid polluting this review with DTV discussions, I opted to create a separate issue for it: #31406

**Comment by poettering** [comment]
Sorry, but I think the "mc" thing is too cryptic, noone knows what that might be just by looking at it. I kinda liked "media" tbh, it gives a clear hind what this is related to. Can we change that back please?

**Comment by poettering** [comment]
i mean, the subsystem is called "media" in the kernel, isn't it? i am pretty sure we should stick to that, and not come up with new names. 

Or to say this differently: if you want us to use "mc" in userspace, please rename the subsystem in the kernel "mc" too?

**Comment by pinchartl** [comment]
The subsystem is named "media", but the `/dev/media*` devices exposes the "media controller" API, which is a subset of the whole media subsystem (the subsystem also defines the V4L2 and DVB APIs). "Media controller" is often abbreviated "mc" as it's a long name. This being said, given that the device nodes are currently named `/dev/media*`, my preference is `/dev/media/`.

**Comment by mchehab** [comment]
@poettering:

> i mean, the subsystem is called "media" in the kernel, isn't it? i am pretty sure we should stick to that, and not come up with new names.
> 
> Or to say this differently: if you want us to use "mc" in userspace, please rename the subsystem in the kernel "mc" too?

No. /dev/media0 is not named after the subsystem. It is a shortcut for "media controller". Btw, that's exactly the kind of misunderstanding I want to avoid by not having a directory called "/dev/media/" with just media controller devnodes on it.

As @pinchartl  mentioned, the subsystem "media" covers a wide range of different device types and APIs, not only for cameras, but also for TV, radio, remote controllers, HDMI consumer electronics (CEC) and others. The media controller API was designed to cover the need of changing internal wiring on cameras used on embedded hardware, so it covers only a subset of the media subsystem. Also, all developers and advanced users that may require such API need to be familiar with the "mc" term and how it actually works, as the media controller API is all about controlling devices' internal wiring.

> I think it may be useful to consider whether:
> 
> * the kernel may emit other, future events under the "media" subsystem umbrella, and/or

This is needed. As I mentioned before, the major usage for persistent nodes on media are:

- video surveillance systems that have lots of cameras connected on different V4L2 devnodes;
- digital TV, where each TV frontend may be connected to different signal sources.

As @pinchartl mentioned earlier, while having persistent names for media controller devnodes may help someone writing simple scripts to get the right hardware, applications usually don't require such persistent names, as one of the goals of the media controller API is exactly to describe the media hardware at sub-devices level with the corresponding input/output pads/interfaces on a persistent way. So, applications and libraries designed to use media controller API like libcamera typically don't need any udev persistent rules.

> * whether other device files should be grouped together under `/media/` (or whether media-controllers should have their own directory).

If we do a change like that, it would make sense for me only if we also place what's currently on /dev/v4l also there, e. g.:
```
/dev/media/
├── by-id
│   ├── usb-Chicony_Electronics_Co._Ltd._HP_HD_Camera_200901010001-video-index0 -> ../../video2
│   ├── usb-Chicony_Electronics_Co._Ltd._HP_HD_Camera_200901010001-video-index1 -> ../../video1
│   ├── usb-Chicony_Electronics_Co._Ltd._HP_HD_Camera_200901010001-mc -> ../../media0
│   ├── usb-MACROSILICON_USB_Video-video-mc -> ../../media1
│   ├── usb-MACROSILICON_USB_Video-video-index0 -> ../../video4
│   └── usb-MACROSILICON_USB_Video-video-index1 -> ../../video5
...
```
 
As the two API media controller device nodes for those two USB cameras will be mapped together with the V4L2 nodes that are actually used to control the hardware [^1].

The problem with that is that it would require moving /dev/v4l2 to /dev/media, as it doesn't make sense otherwise. So, a link will need to be created at /dev: ```v4l -> media``` to prevent backward compatible issues, as some apps like camorama depend on /dev/v4l.

A change like that works for me.

[^1]: On USB video class cameras (UVC), the media controller API is optional and ignored by most apps. The device control is done via V4L2 API.

**Comment by poettering** [comment]
naming is hard... ;-)

**Pull request merged**
