### PR TITLE
user-sessions: make sure /run/nologin has correct SELinux label

### PR DESCRIPTION
**Pull request by msekletar**

### CODE REVIEW

**Comment by ghost** [comment]
I don't know why I am still providing feedback but why? What is the rationale. I see no need for this.

**Comment by ghost** [comment]
The only regular files either systemd-logind, or systemd-user-sessions ever creates in /run are nologin.\* files. So this should not need built-in awareness. Since in policy it can just be specified that:

`"if processes associated with "logind", or "user-sessions" selinux type identifiers create "regular files" in directories associated with the "runtime" selinux type identifier, then create the "regular file" with an automatic type transition from the "runtime" selinux type identifier to the "nologin" selinux type identifier."`

AFAIK this is redundant

**Comment by msekletar** [comment]
This change was meant to address this bug report.

https://bugzilla.redhat.com/show_bug.cgi?id=1287592

Pretty much the same patch is in RHEL/CentOS7. IIRC, change was Acked-by SELinux folks, but if you think this can be addressed in policy then I am happy to withdraw this PR. Maybe @mgrepl can help us out here.

**Comment by ghost** [comment]
Yes, unless I am overlooking something (which I do not think is the case if this was based on that bug report) then this is just redundant.

I have systemd fully confined and working, and I never encountered any requirement such as this one. One should be careful with these built-in awareness changes since they may just be hiding bugs in policy, or the appearant need for this awareness may just indicate that there is a bug in the policy. 

Its as easy as i stated above. Any regular files created by logind or user-sessions in /run should be created with an auto type transition from the runtime to the nologin type. That then should be backed-up by proper file context specs. Then it should work fine but it should be tested thoroughly since these files get renamed. But yes in my policy it just works without any other requirements.

**Comment by ghost** [comment]
Just to be clear. I think this is just a bug in the policy, and with that this just proves the point i made above: `"or the appearant need for this awareness may just indicate that there is a bug in the policy."`

**Comment by poettering** [comment]
OK, makes sense. The "atomic" way we write these files is something that doesn't fit in the SELinux concept, as the name is not guessable then.

**Comment by ghost** [comment]
The name does not have to be guessable since it can apply to any regular file, but fine it is clear that reason does not seem to matter.

**Comment by mgrepl** [comment]
Thanks for applying patch also in Fedora. 

The point here is we wanted to avoid a generic transition in this case. Once we have a fully confined systemd and tested in Fedora/RHEL we can review it.

**Comment by ghost** [comment]
If this was "Fedora" then I would not care the least but I this is "upstream" so I care.

**Comment by ghost** [comment]
That is just the whole problem. Some people think that just because RH by default enforces their policy on their customers assets, theyre the only ones using SELinux MAC. This is a inaccurate assumption. Other distro's also provides their users with SELinux MAC, they just decided that it may not be a good idea to enforce their policy on their customers assets by default. Since they might know that depending on the customers treat model, their policy may be ineffective and inefficient.

So RH does not have a patent on this stuff... RH is not the only distr vendor using SELinux. RH is the only distr vendor that thinks it is in a position to make security decisions for their customers.

What RH does in its distros is their business. This is upstream and this affects everyone. RH should not force its will on others by using its influence to shape upstream. It is bad practice and it is counterproductive

**Comment by mgrepl** [comment]
I don't see fully confined systemd by SELinux also in upstream policy. You have a special case with your local policy. If you have a patch with working upstream policy with a generic transition then I have no problem to say "We don't need this change and it is a bug in the policy" and will ask systemd folks to revoke this patch which is pretty easy.

**Comment by ghost** [comment]
Yes, but no matter what "upstream" policy does. That still does not warrant any changes upstream that makes assumptions, and that goes into any specific direction, unless that is unavoidable. SELinux is customizable. The policy is separate from the framework. That means that changes affecting the framework should not be policy specific at all, unless this is unavoidable. So wether its refpolicy or redhat selinux-policy it does not really matter. If it makes assumptions, then it should not affect the framework unless unavoidable. We should keep SELinux a flexible MAC because that is what defines it as opposed to for example SMACK. if you remove the flexibility and customizability from SELinux then it will become irrelevant. It loses its identity. It no longer defines it self.

**Comment by ghost** [comment]
And please do not bring "reference policy" into this. They weren't the ones sending this PR.
I do not hold any grudges. This is not a crusade to discredit anything or anyone. This is pure passion for the technology. What is best for SELinux is best for everyone in the longer run. Also i am not passionate about SELinux in systemd. SELinux awareness in systemd is pure necessity. I would rather not be involved with systemd at all but this affects SELinux, and thus me. I have little choice.

**Comment by ghost** [comment]
@mgrepl: If you care so much about reference policy then why did you did not coordinate this with them or even get as little as an ACK from them for this change?

**Comment by ghost** [comment]
This has nothing to do with "my policy". As a matter of fact this whole PR is pretty insiginicant. It can easily be overriden in policy. That is not the point. It is the idea behind this way of thinking. Today it is something as insignificant as this PR. Yesterday it was something that made SELinux systems inconsistent, and potentially vulnerable. What is it going to be tomorrow?

**Comment by mgrepl** [comment]
That's a point. It is about a policy. It is still under a policy control.

**Comment by ghost** [comment]
Yes but now systemd-user-sessions requests all kinds of extra permissions to become selinux aware, and that is just not needed.

**Comment by mgrepl** [comment]
There is ongoing conversation on SELinux upstream about systemd-user-sessions and I would keep it on this list for now if possible. 

Thank you.

**Comment by ghost** [comment]
Sure, I must have overlooked that thread. Care to share the URL?

**Comment by mgrepl** [comment]
Could we think to place nologin under /run/<something> directory instead of having it directly in /run?

Ongoing conversations is here

https://bugzilla.redhat.com/show_bug.cgi?id=1285019

**Comment by ghost** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Sun, Dec 20, 2015 at 02:54:32AM -0800, Miroslav Grepl wrote:

> Could we think to place nologin under /run/<something> directory instead of having it directly in /run?
> 
> Ongoing conversations is here
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=1285019

I suppose but why? Have you tried confining systemd-user-sessions? AFAIK
it should work fine if you just target logind and user-sessions.

Upstream refpolicy confined systemd-user-sessions, because upstream wants
these "systemd helpers" out of init_t.

Why not just try the simplest thing first and just, then if it turns out
that it is not desired one can always rethink it.

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/systemd/systemd/pull/2100#issuecomment-166109808

---

02DFF788
4D30 903A 1CF3 B756 FB48  1514 3148 83A2 02DF F788
https://sks-keyservers.net/pks/lookup?op=get&search=0x314883A202DFF788
Dominick Grift
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQGcBAEBCgAGBQJWdoqZAAoJENAR6kfG5xmcsEML/AssLvLdv6XpH8RxAijq4RmU
q6OqVQQkXQIu77SYsUDB73xsAqSfnpsVSGW4pFkgIbi39Tkky/0WqLEGjLlTPv7w
6xmTfRVDz+B7ca4ogOoUuspbpXv0BD3qe+i3qpwQyBXs7zq9wBFYytxTgRnn5zDI
Y/EHVeWPjs6twx7F/yMlxNGzL2qrM2LR1HO7RZ1eakmYpZPMnpQ5SpjVxfxNplc+
T5OJYPoKhRg6kGUkkndZxOF73oAPFiRTeLXhKRU8TrIceujmol+8ZLsHaod0RUGm
7k9t7CYyS5aGsXTNu+PH82dJD3HRl1dNJ2U/ZLMbQjVDw4WZrEXWz6MbB5d6RAgm
qYot3Hq30SDv+2tb4/6OHAxfNwkwxfL8Gk3DCZQJ1QRBiTaWK+iAj2EHKYIZSaf/
uX6RIGUlE/mkepiLCR2fa1AaCaHt1hUQkVKi+iVcOLYtyfvZzDSvPnDbhsDVB0oW
TmrDWoBt6NTnmI2YxBm/K5iAwJOMRPj9KwZQ/EcHZQ==
=Jiwe
-----END PGP SIGNATURE-----

**Comment by mgrepl** [comment]
system_u:system_r:systemd_logind_t:s0 root 892     1  0 07:45 ?        00:00:00 /usr/lib/systemd/systemd-logind

is confined. It is about generic transitions even for confined domains vs. specific transitions.

**Comment by ghost** [comment]
I am talking about systemd-user-sessions.

SELinux most of the time is flexible enough to deal with these issues without bothering other components. SELinux should be transparent to the extend possible.
1. confine systemd-user-sessions
2. if applicable confine systemd-shutdownd
3. allow systemd-user-sessions, systemd-shutdownd, and systemd-logind to create regular files in /run with a auto type transition from var_run_t to whatever type you have associated with /run/nologin.

**Pull request merged**
