### PR TITLE
Add zh_TW translation.

### PR DESCRIPTION
**Pull request by s8321414**
I add new zh_TW translation, please review it.

### CODE REVIEW

**Comment by zonque** [comment]
Also, you forgot to add the new files to Makefile.am and po/LINGUAS. See 917c03718c9 for an example. While at it, you can also squash the two commits into one.

**Comment by s8321414** [comment]
@zonque OK, I will modify my commit log above first.

**Comment by s8321414** [comment]
I need a beautiful solution :S......

**Comment by s8321414** [comment]
so can it be merged now? or must I do a squash commit?

**Comment by ronnychevalier** [comment]
@s8321414 Please fixup to only have one commit adding the zh_TW translation. In your case having multiple commits don't add any value, with one commit it simplifies reverting, bisecting, reviewing, or even reading the git log.

**Comment by s8321414** [comment]
@ronnychevalier OK,I will do it later.

**Comment by s8321414** [comment]
OK done now.

**Pull request merged**
