### PR TITLE
meson: drop implicit libudev link dependencies

### PR DESCRIPTION
**Pull request by mbiebl**
Executables which link against libshared do not need an explicit
dependency on libudev, as libshared will make sure that those symbols
are available.

A side-effect of this change is, that it remains an implementation detail of libshared whether it links against libudev dynamically or includes the libudev sources statically.

### CODE REVIEW

**Comment by keszybz** [comment]
> @keszybz intentionally added those in 826472c to prevent errors if mesonbuild/meson#1545 is merged. Now the build will fail again with that meson patch. Has this been considered?

Ah, crap. I'm getting lost in all the conflicting verions and PRs. 
Well, since this got merged, let's just wait and see. If the build breaks at some point in the future, we can always add the libs back.

**Comment by martinpitt** [comment]
Indeed the xenial-s390x build (i. e. with meson) now fails with
```
FAILED: test-dhcp-client 
cc  -o test-dhcp-client 'test-dhcp-client@exe/src_libsystemd-network_test-dhcp-client.c.o' '-Wl,--no-undefined' '-Wl,--as-needed' '-Wl,-z,relro' '-Wl,-z,now' '-pie' '-Wl,--gc-sections' '-g' '-O2' '-fstack-protector-strong' '-Wformat' '-Werror=format-security' '-Wl,-Bsymbolic-functions' '-Wl,-z,relro' 'src/shared/libsystemd-shared-233.so' 'src/libudev/libudev.so.1.6.6' 'src/basic/libbasic.a' 'src/libsystemd/libsystemd.a' 'src/basic/libbasic.a' 'src/basic/libbasic.a' 'src/libsystemd-network/libsystemd-network.a' '-Wl,-rpath,/data/adttmp/autopkgtest-virt-lxc.shared.bt2_okfo/downtmp/build.xOe/debian/build-deb/src/shared:/data/adttmp/autopkgtest-virt-lxc.shared.bt2_okfo/downtmp/build.xOe/debian/build-deb/src/libudev'  
/usr/bin/ld: src/libsystemd-network/libsystemd-network.a(dhcp-identifier.c.o): undefined reference to symbol 'udev_device_unref@@LIBUDEV_183'
src/libudev/libudev.so.1.6.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by mbiebl** [comment]
tbh, we could just add libudev_sources to libshared. It doesn't seem to have any effect on the installed size (actually, it's a tiny bit smaller, which is surprising)

**Comment by mbiebl** [comment]
> tbh, we could just add libudev_sources to libshared. It doesn't seem to have any effect on the installed size (actually, it's a tiny bit smaller, which is surprising)

It would be closer to what's used in autotools, as well

**Comment by mbiebl** [comment]
> tbh, we could just add libudev_sources to libshared. It doesn't seem to have any effect on the installed size (actually, it's a tiny bit smaller, which is surprising)

Building with this patch:
```
diff --git a/src/shared/meson.build b/src/shared/meson.build
index 0747f7664..f1d73d1b3 100644
--- a/src/shared/meson.build
+++ b/src/shared/meson.build
@@ -127,10 +127,10 @@ libshared = shared_library(
         basic_sources,
         journal_internal_sources,
         libsystemd_internal_sources,
+        libudev_sources,
         include_directories : includes,
         link_args : ['-shared'],
         c_args : ['-fvisibility=default'],
-        link_with : [libudev],
         dependencies : [threads,
                         librt,
                         libcap,
```
results in an installed size which is 40K less. Can anyone confirm that?

**Comment by keszybz** [comment]
Yeah, I can confirm that:
51120	/var/tmp/inst-before-patch
51032	/var/tmp/inst-after-patch

Let's do this then...

**Comment by mbiebl** [comment]
> Yeah, I can confirm that:
> 51120	/var/tmp/inst-before-patch
> 51032	/var/tmp/inst-after-patch
> 
> Let's do this then...

Thanks for the confirmation @keszybz . I've posted a PR at #5850

**Pull request merged**
