### PR TITLE
fd-util: make path_is_root_at() compare with "/"

### LINKED ISSUE #29559: [zfs incompatibility] chase: assertion 'path_is_absolute(p)' failed at src/basic/chase.c:528
### systemd version the issue has been seen with

254.3

### Used distribution

NixOS unstable

### Linux kernel version used

6.1.47

### CPU architectures issue was seen on

x86_64

### Component

systemd-journald

### Expected behaviour you didn't see

I would expect this to fail but a better error message would be nice.

### Unexpected behaviour you saw

When systemd-journald started the following assertion happened:
```
Assertion 'path_is_absolute(p)' failed at src/basic/chase.c:528, function chase(). Aborting.
```
then systemd-coredump triggered

### Steps to reproduce the problem

The issue happened because multiple zpools mounted different datasets at `/`. After removing the duplicated mounts for `/` the issue went away. We could boot the system by adding single to the grub boot options.

I don't have access to the system right now but `zfs list` look similar to my mock:

```
 ➜ zfs list
NAME              USED  AVAIL     REFER  MOUNTPOINT
rpool             800G   900G       96K  /
rpool/nixos       800G   900G      600G  none
rpool/nixos/data  800G   900G      600G  legacy
rpool/nixos/nix   200G   900G      200G  /nix
ppool             800G   900G       96K  /
ppool/nixos       800G   900G      600G  none
ppool/nixos/data  200G   000G      200G  legacy
```

So I think to reproduce the following condition must be met:
Mount multiple file systems early at boot to / and confuse the chase code which fails to start systemd-journald.

### Additional program output to the terminal or log subsystem illustrating the issue

image

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #29559.
Replaces #29842.

### CODE REVIEW

**Comment by YHNdnzj** [comment]
Uh, generally I still don't like this kind of workarounds, but I'm not against this PR implementation-wise.

**Comment by YHNdnzj** [comment]
Can we generate some debug message when such spurious setup is detected? Maybe through log_once.

**Comment by yuwata** [comment]
> Uh, generally I still don't like this kind of workarounds, but I'm not against this PR implementation-wise.

That's expected reaction 😁
Yeah, this is a workaround, and may just hide the issues, and may reveal or introduce other issues on such spurious setups.
But, at least now, I don't have any other ideas to fix the original issue.

**Comment by yuwata** [comment]
> Can we generate some debug message when such spurious setup is detected? Maybe through log_once.

Done.

**Review by YHNdnzj — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
Testing this in a similar fashion as in the original issue would require me bricking a system which I would like to skip if possible 😅

**Comment by yuwata** [comment]
@aep Could you test this PR?

**Comment by aep** [comment]
hmm idk.
this change seems to attempt fixing the crash and boot systemd anyway,
which makes it harder to detect the misconfiguration.

should i see [this warning](https://github.com/systemd/systemd/pull/30179/files#diff-b0bb02e0d63faad5a61407a195fa961d7988fec772cecfeba53f530a609e3370R995)  in journalctl?  because i dont.


instead systemd now boots just fine, but the udev unit exits with 226/NAMESPACE and no log output,
so the system is still broken.

I don't think its worth attempting to make a system like this work. This is a misconfiguration and probably causes subtle issues elsewhere

```sh
mount | grep '/ '
zroot/arch on / type zfs (rw, relatime,xattr,noactl)
zroot/arch2 on / type zfs (rw, relatime,xattr,noactl)
```

However, your fix is pretty good to get the system to boot into a state where you can easily fix it.
I just wish the warning message was somewhere very visible. probably emergency dmesg.

**Comment by YHNdnzj** [comment]
> should i see [this warning](https://github.com/systemd/systemd/pull/30179/files#diff-b0bb02e0d63faad5a61407a195fa961d7988fec772cecfeba53f530a609e3370R995) in journalctl? because i dont.

Hmm, maybe `journald` also failed to start? pid1 should log to kmsg in that case.

**Comment by aep** [comment]
nah its fine

2023-11-24-164901_1136x834_scrot


maybe its a timing thing. zfs initrd hooks on archlinux only mount the single correct root, then start systemd, then there's a unit that mounts the rest.

**Comment by yuwata** [comment]
So, it seems that when PID1 calls the function the spurious mount does not exist (or PID1 has not called it yet). But it may be called when creating a mount namespace by a forked process of PID1 (or sd-executor nowadays), and failed to start services.
Let's unconditionally warn about the setup. Hopefully, admin can notice their failure.

**Comment by yuwata** [comment]
@aep Thank you for testing the patch. Could you test again ? Hopefully, you can find log message.

**Comment by aep** [comment]
still nothing. am i holding it wrong?

`systemctl --version` says g44d0607 , so thats the expected hash i think?

`journalctl -b | grep bind-mount` is not showing it.

**Comment by yuwata** [comment]
Hm... all binaries, especially systemd-executor, are updated? Rather than only PID1.

**Comment by aep** [comment]
> Hm... all binaries, especially systemd-executor, are updated? Rather than only PID1.

did a fresh build just to rule out any caching issues
```
git clean -fxd
./configure --prefix /
make -j
make install
```

also i added a printf here 

https://github.com/systemd/systemd/pull/30179/commits/44d0607358e72d89035866b041c87052c9b0a533#diff-b0bb02e0d63faad5a61407a195fa961d7988fec772cecfeba53f530a609e3370R989   

and that does indeed print
so the check just isnt working

**Comment by YHNdnzj** [comment]
> and that does indeed print
> so the check just isnt working

No. For a normal setup, the first `dir_fd_is_root_one` should return 1. It actually correctly identifies the spurious setup.

(I'm wondering whether `log_once` is to blame here. We have little coverage for that in our codebase...)

**Comment by aep** [comment]
> I'm wondering whether `log_once` is to blame here.

2023-11-24-181103_960x324_scrot


sorry for the screenshots. the test system is of course broken so i cant really get a console.


2023-11-24-180939_903x171_scrot

**Comment by yuwata** [comment]
So, the fallback logic used in the previous version never worked on ZFS system.
In the revised version, the fallback logic is dropped. That is, always compare with only "/".

I think it is better to provide more descriptive error message when failed to create a mount namespace (reported as udevd failure in the above) on multi-root ZFS setup, but that's out of scope of the original issue and this PR.

@aep Thank you for testing multiple times. Could you test one more time? The behavior should not be changed. So, still many services, especially udevd will fail, but hopefully PID1 does not trigger the assertion.

**Comment by yuwata** [comment]
Hm... I have no idea, but this does not work on CentOS 8...

**Comment by aep** [comment]
85f1ad5 works exactly as you described. systemd keeps booting just fine, but udev fails.
unfortunately this completely removes any useful error message, which would have been what i wanted.

**Comment by YHNdnzj** [comment]
Yeah, I think this is probably worse than status quo if we can't provide any useful message...

**Comment by yuwata** [comment]
OK. At least, this is not a good way, as this makes harder to find the root of the issue. Closing.

**Pull request closed without merging**
