### PR TITLE
WIP: test PR to verify changes to Ubuntu CI, please ignore

### PR DESCRIPTION
**Pull request by ddstreet**
This is just a test PR to force Ubuntu CI run after changing some
of the Ubuntu CI infrastructure (packages in the ppa and/or the
Debian upstream-ci branch)

### CODE REVIEW

**Comment by ddstreet** [comment]
well, the semaphoreci test appears to be failing as it can't find debhelper 13:

> Broken autopkgtest-satdep:amd64 Depends on debhelper-compat:amd64 < none @un H > (= 13)
>   Removing autopkgtest-satdep:amd64 because I can't find debhelper-compat:amd64
> 

but I did add that to the ubuntu ci ppa:
https://launchpad.net/~upstream-systemd-ci/+archive/ubuntu/systemd-ci/+packages?field.name_filter=debhelper&field.status_filter=published&field.series_filter=bionic

maybe semaphoreci isn't using that ppa?

**Comment by ddstreet** [comment]
@evverx @mrc0mmand i may have temporarily broken semaphoreci :(

guess i should start discussing ubuntu ci changes on the mailing list.

**Comment by ddstreet** [comment]
I set the debhelper version back down to 11 in the Debian upstream-ci branch, so new PR should work again without debhelper 13, but I'd like to get semaphoreci updated with debhelper 13.

**Comment by evverx** [comment]
> I'd like to get semaphoreci updated with debhelper 13

Could you try pointing it to `bullseye` instead of [`buster`](https://github.com/systemd/systemd/blob/3bb412626298006bfdb38a2eaec025cc2e181f01/semaphoreci/semaphore-runner.sh#L7)? As far as I know debhelper is relatively new there.

**Comment by mbiebl** [comment]
Or add buster-backports, which has debhelper 13

**Comment by ddstreet** [comment]
Thanks! I opened #16545 to update it to bullseye, which I hope will get semaphoreci passing :)

**Pull request closed without merging**
