### PR TITLE
repart: copy denylist fixes

### PR DESCRIPTION
**Pull request by daandemeyer**

### CODE REVIEW

**Comment by bluca** [comment]
Coincidence?

`93/93 systemd:integration-tests / TEST-58-REPART                                                TIMEOUT        1800.20s   killed by signal 15 SIGTERM`

**Comment by DaanDeMeyer** [comment]
No that's a flaky test that I need to fix but this is known see #34494

**Review by bluca — APPROVED** [review]
Then it was a coincidence :-P

**Comment by NekkoDroid** [comment]
`file_is_denylisted` seems to be unable to handle when `arg_copy_source` is empty (e.g. reparting a live system to a new device). Specifically `if (stat(arg_copy_source, &rst) < 0)` seems to fail with "Bad address".

**Pull request merged**
