### PR TITLE
Fix for initrd-switch-root failing and causing emergency.target to be started

### PR DESCRIPTION
**Pull request by keszybz**
This is for https://bugzilla.redhat.com/show_bug.cgi?id=1414904.

@msoltyspl for the vconsole part.

### CODE REVIEW

**Comment by AdamWill** [comment]
Is it possible this *may* be a bit overbroad? There seem to be other uses of `switch_root`, which is presumably why the original version had the `in_initrd` check. I'm just wondering if possibly this isn't the right thing for *all* of them, though it will clearly help the case we're trying to fix here.

**Comment by keszybz** [comment]
I don't think it's overbroad. This function always does the same thing — it tells pid1 to initiate the switch-root sequence — and systemctl is always subject to being killed during that, *unless* it protects itself.

**Comment by fsateler** [comment]
Tiny nit: the commit message for `units: restore Before dependencies for systemd-vconsole-setup.service` says `Before=shutdown.tuarget`

**Comment by keszybz** [comment]
Oh, in the description. I'll let it stay. I noticed another typo in one of the earlier commits too, but it doesn't seem worth to wait for CI.

**Comment by AdamWill** [comment]
this is looking good in my testing so far, seems to be fixing the issue.

**Comment by keszybz** [comment]
Let's merge then.

**Pull request merged**
