### PR TITLE
Add process madvise to seccomp filters

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
hmm, kernel 5.10 is not released yet, iirc. the past tense in the commit msg is a bit surprising ;-)

**Comment by poettering** [comment]
Hmm, I wonder if the syscall wouldn't be best grouped with process_vm_readv(), which we so far consider part of `@ipc`. It's a memory op very similar to reading, no? not sure?

src/shared/syscall-names.text does not list this syscall yet. It's weird to have it in a group already then?

**Comment by poettering** [comment]
just wondering, where did this come up? is any sw already using this new syscall?

**Comment by keszybz** [comment]
> src/shared/syscall-names.text does not list this syscall yet. It's weird to have it in a group already then?

There are two commits, the first one adds the name. (I kept them separate because I wasn't sure if we want the second part.)

**Comment by keszybz** [comment]
> hmm, kernel 5.10 is not released yet, iirc. the past tense in the commit msg is a bit surprising ;-)

Yeah, we can wait until 5.10 is released with this.

**Comment by poettering** [comment]
oops, i missed the other commit somehow. it's indeed in there, sorry for the confusion

**Comment by poettering** [comment]
i am fine with merging this ahead of time, if it's already in an rc kernel, I just think the commit msg should probably not use past tense for this, given that the indicated kernel doesn't exist yet. my comment was more asking for the commit msg to be tweaked then for the whole thing to be delyed.

**Comment by keszybz** [comment]
I reworded the commit message to clarify that it's just in 5.10-rc1. I dropped the second commit: I don't think we need to push it into any group (except `@known`). `@ipc` doesen't seem to be a right fit at all, since this has nothing to do with IPC. I guess `@debug` isn't really good either. Since this syscall is rather specialized, I think it's fine if people who need this just list manually. If we get reports that it's being used more widely, we can add it to a group then.

**Pull request merged**
