### PR TITLE
resolved: fix single-label resolution over DNS

### PR DESCRIPTION
**Pull request by jacekmigacz**

### CODE REVIEW

**Comment by poettering** [comment]
Hmm? You are aware of `ResolveUnicastSingleLabel=`?

**Comment by jacekmigacz** [comment]
@poettering I'm, but I observed, that, when LLMNR claims itself authoritative for single-labeled domains, DNS scope is not even submitted as a candidate; LLMNR's `DNS_SCOPE_YES_BASE + 1` beats DNS' `DNS_SCOPE_MAYBE`.
Thus, even with `ResolveUnicastSingleLabel=yes` it is not possible to resolve TLD's root like `org.`.

**Comment by jacekmigacz** [comment]
...also it resolves #23494, #13763 and couple others.

**Comment by jacekmigacz** [comment]
That should do the trick.

Also, @poettering I wonder what is the meaning of `Unicast` in `ResolveUnicastSingleLabel`?
Is it suppose to be opposite to multicast? Is it about routing methodology or something else?
I'd reduce it to `ResolveSingleLabel` or change it to `ResolveNonMulticastSingleLabel`.

**Comment by poettering** [comment]
We distuingish between "multicast" DNS (i.e. llmnr and mdns) and "unicast DNS" (i.e. classic port 53 DNS), hence the name.

**Comment by jacekmigacz** [comment]
I'm asking, because if it is a routing term, then I find a bit awkward, because for classic DNS it is usually Anycast routing methodology, not Unicast (like Cloudflare[1.1.1.1] or Google[8.8.8.8]). Thus, unless a context is different it might be a bit confusing.

**Comment by poettering** [comment]
Well, the fact that it's unicast or anycast is not relevant for the protocol, it's really just an implementation detail of the server side. But the fact that it is multicast matters a lot for the protocol, and changes almost everything about it.

**Comment by jacekmigacz** [comment]
Fine then. Thanks for a merge!

**Pull request merged**
