### PR TITLE
Fix WorkDir=~ with empty User=

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, it sounds relly strange setting LOGNAME=root for all system services...
I am fine with relaxing this for root's --user instance, but for system services?

**Comment by keszybz** [comment]
$LOGNAME is just an alias for $USER. So the question really is if it makes sense to set $USER for root processes. I don't see why not. You can always not use it, but at least in scripting languages it's just easier to have it unconditionally.

**Comment by keszybz** [comment]
```
:: [  BEGIN   ] :: Running 'userdel -r systemdtester'
userdel: user systemdtester is currently used by process 4247
:: [   FAIL   ] :: Command 'userdel -r systemdtester' (Expected 0, got 8)
```
I have no idea.

**Comment by poettering** [comment]
hmm, ok.

**Comment by martinpitt** [comment]
seccomp test failure on i386 was just due to my botching of ignoring the failure on that architecture (fixed in git now), so landing.

**Comment by evverx** [comment]
This commit breaks https://github.com/systemd/systemd-centos-ci/blob/master/slave/tests/loginctl/runtest.sh#L125

@blaskovic, any idea what does that test really test? And how does this PR break it?

**Comment by blaskovic** [comment]
Looks like `pkill -u $USER` did not kill all user's processes (there should be 3 ssh connections).

This could be caused by something blocking the signal or it's maybe just a timing - ssh processes did not quit properly before `userdel` was called.

Can you tell if this commit can be related to the first scenario?

**Comment by blaskovic** [comment]
And I rescheduled the tests if can hit it again reliably: https://ci.centos.org/job/systemd-pr-build/2134/ (results will be soon)

**Comment by evverx** [comment]
@blaskovic , thanks! Test failed.

Shouldn't we revert this PR? See https://github.com/systemd/systemd/issues/5246

**Comment by poettering** [comment]
well, I'd like to understand what#s going on first, before we revert stuff. I for one don't understand what precisely this is supposed to have broken...

**Comment by evverx** [comment]
> I for one don't understand what precisely this is supposed to have broken...

So, why did we merge this?

**Comment by poettering** [comment]
Well, I did understand what #5223 fixed, and how it did so. What I don't understand is what precisely it broke though.

**Comment by evverx** [comment]
@poettering , sorry, I mean I don't understand too. But I guess `try to understand/merge if it's ok` is better then `merge/try to understand if it's ok`

**Comment by poettering** [comment]
well, the CI didn't show any issues I assumed to be relevant with the PR, and looking at the code I didn't see any either...

Of course, if it had been obvious to me that this created a problem I wouldn't have merged it. But at this point in time, it's too late, but before we revert it I'd rather understand the issue first.

**Comment by ht990332** [comment]
@poettering I reported the bug about the regression. The only thing I knew how to attach was the output of 'journalctl -b'. If you have a moment, would you instruct me how to get more informative logs or details about what exactly broke?
Thank you very much in advance.

**Comment by evverx** [comment]
@poettering , OK.

@hussamT , let's move this discussion to #5246

**Pull request merged**
