### PR TITLE
core: memory map reading fragments.

### PR DESCRIPTION
**Pull request by xnox**
Related to systemd/systemd#211

### CODE REVIEW

**Comment by zonque** [comment]
Could you give some background of the rationale here? Why is that done, do you see any performance benefit or such? We need to be able to track such changes in the future, often years after the commit happened.

**Comment by poettering** [comment]
Yeah, this deserves some explanation about the speed-up this is supposed to provide... Somehow I doubt that page faulting things into memory would be any faster that reading it via read(), as long as we only read these files in a linear stream as we do for these files...

**Comment by crrodriguez** [comment]
memory mapping fragments probably does more harm than good..as units are smaller than a page (which is 4k or more)..this optimization is indeed profitable but for bigger files..

**Comment by crrodriguez** [comment]
This same argument applies here: https://sourceware.org/ml/libc-alpha/2006-11/msg00061.html btw.

**Comment by zonque** [comment]
I'm closing this for now. If you still think it is needed, please open a new PR with a detailed explanation that justifies that change.

**Pull request closed without merging**
