### PR TITLE
resolved: when restarting a transaction make sure to not touch it any…

### PR DESCRIPTION
**Pull request by poettering**
…more

dns_transaction_maybe_restart() is supposed to return 1 if the the transaction
has been restarted and 0 otherwise. dns_transaction_process_dnssec() relies on
this behaviour. Before this change in case of restart we'd call
dns_transaction_go() when restarting the lookup, returning its return value
unmodified. This is wrong however, as that function returns 1 if the
transaction is pending, and 0 if it completed immediately, which is a very
different set of return values. Fix this, by always returning 1 on redirection.

The wrong return value resulted in all kinds of bad memory accesses as we might
continue processing a transaction that was redirected and completed immediately
(and thus freed).

This patch also adds comments to the two functions to clarify the return values
for the future.

Most likely fixes: #2942 #3475 #3484

### CODE REVIEW

**Comment by poettering** [comment]
So I am pretty sure this fixes all three of #2942 #3475 #3484 (which I think are actually just duplicates of each other). But it's hard to know since this is a memory corruption bug and there might be more such bugs lurking somewhere. Would be good if the reports of these bugs could give this a spin and check if this fixes things for them?

(This PR should be merged in any case though, as it definitely fixes an important bug, the only question is though whether it's the bug described by those three issues...)

**Comment by martinpitt** [comment]
This indeed fixes the crashes indeed (at least the ~ three expressions of it that I've seen), thanks!

There is still an oddity here that the _first_ time I do `systemd-resolve www.facebook.com` after this patch it says:

```
www.facebook.com: resolve call failed: DNSSEC validation failed: failed-auxiliary
```

and from the second time on it works (with "Data is authenticated: no"). That's with the default `DNSSEC=allow-downgrade`. But this is presumably unrelated.

**Comment by poettering** [comment]
@martinpitt ubuntu CI failed badly on this one? seems unrelated though...

**Comment by martinpitt** [comment]
@poettering: sorry, I fat-fingered the packaging adjustment for PR #3516, and these tests ran before the fix. Restarted.

**Pull request merged**
