### PR TITLE
units: set NoNewPrivileges= for all long-running services

### PR DESCRIPTION
**Pull request by poettering**
Previously, setting this option by default was problematic due to
SELinux (as this would also prohibit the transition from PID1's label to
the service's label). However, this restriction has since been lifted,
hence let's start making use of this universally in our services.

On SELinux system this change should be synchronized with a policy
update that ensures that NNP-ful transitions from init_t to service
labels is permitted.

An while we are at it: sort the settings in the unit files this touches.
This might increase the size of the change in this case, but hopefully
should result in stabler patches later on.

Fixes: #1219

### CODE REVIEW

**Comment by keszybz** [comment]
> This might increase the size of the change in this case, but hopefully
should result in stabler patches later on.

Please don't do "while we are at it" like this, because it makes backporting or reverting the patch about 10 times more work. (If reverting, we want to keep the sort. If backporting, the context of the patch will likely be changed, leading to numerous pointless conflicts.)

**Comment by yuwata** [comment]
I did not imagine the revertability, but it was hard to review for me :-)

**Comment by keszybz** [comment]
Yep, sounds like an addition to NEWS would be good.

**Comment by filbranden** [comment]
SELinux policy for systemd-journald really looks to be missing...

I just sent PR https://github.com/fedora-selinux/selinux-policy/pull/234 to try to address that.

cc @wrabcak

(We still need to get this in NEWS though, that's still pending.)

**Pull request merged**
