### PR TITLE
udev: silence warning about PROGRAM+= or IMPORT+= rules

### LINKED ISSUE #14062: udev (incorrectly) complains about valid udev rules
**systemd version the issue has been seen with**

v243

**Used distribution**

Debian sid
Filed as downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944917
See also the discussion at https://lists.freedesktop.org/archives/systemd-devel/2019-November/043711.html

Since the upgrade to v243, I see udev complaining about a lot of udev rules files.

As an example:
```
Nov 17 23:44:05 pluto systemd-udevd[328]: /lib/udev/rules.d/56-lvm.rules:40 Invalid value for OPTIONS key, ignoring: 'event_timeout=180'
Nov 17 23:44:05 pluto systemd-udevd[328]: /lib/udev/rules.d/56-lvm.rules:40 The line takes no effect, ignoring.
Nov 17 23:44:05 pluto systemd-udevd[328]: /lib/udev/rules.d/90-libgpod.rules:19 IMPORT key takes '==' or '!=' operator, assuming '==', but please fix it.
Nov 17 23:44:05 pluto systemd-udevd[328]: /lib/udev/rules.d/90-libgpod.rules:23 IMPORT key takes '==' or '!=' operator, assuming '==', but please fix it.
```

Looking at e.g. 90-libgpod.rules, the rules look fine
```
ACTION=="add|change", ENV{USBMUX_SUPPORTED}=="1", IMPORT{program}+="/lib/udev/iphone-set-info", GOTO="libgpod_end"

ACTION=="add|change", SUBSYSTEM=="usb", ATTR{idVendor}=="05ac",
ATTR{idProduct}=="129[0-9a]", IMPORT{program}+="/lib/udev/iphone-set-info"
```

The recommendation to replace `+=` with `==` is bogus afaics and the existing udev rules are valid.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #14062.

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

**Comment by poettering** [comment]
Hmm, I actually like the behaviour to warn about this. It's nice to push people toward fixing this stuff, no? It#s just a warning and doesn't break anything?

**Comment by yuwata** [comment]
> It#s just a warning and doesn't break anything?

Right.

**Comment by keszybz** [comment]
We want to push people to fix such things, but this one is pretty inconsequential, and we ourselves weren't very clear which version should be used. I think the warning at the debug level is good enough.  Right now the warning causes more confusion than it is worth.

**Pull request merged**
