### PR TITLE
Some fixes/improvements for OpenFile=

### PR DESCRIPTION
**Pull request by YHNdnzj**
Fixes https://github.com/systemd/systemd/issues/32179

### CODE REVIEW

**Review by yuwata — APPROVED** [review]
LGTM. But could you add an explicit test case for the original issue?

**Comment by YHNdnzj** [comment]
Reworked/simplified the whole test and merged TEST-77 into TEST-23, PTAL.

**Comment by YHNdnzj** [comment]
Please backport the 4th commit to stable.

**Comment by YHNdnzj** [comment]
@mrc0mmand Hmm, I'm not sure what to do with the ASan failure:

```
testsuite-23-openfile-child.sh[1617]: ==1617==ASan runtime does not come first in initial library list; you should either link runtime to your application or ma>
```

**Comment by mrc0mmand** [comment]
> @mrc0mmand Hmm, I'm not sure what to do with the ASan failure:
> 
> ```
> testsuite-23-openfile-child.sh[1617]: ==1617==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
> ```

```diff
diff --git a/test/units/testsuite-23.openfile.sh b/test/units/testsuite-23.openfile.sh
index 823ba39b1d..2ed6994491 100755
--- a/test/units/testsuite-23.openfile.sh
+++ b/test/units/testsuite-23.openfile.sh
@@ -26,6 +26,7 @@ systemd-run -p DynamicUser=yes \
             -p OpenFile='/tmp/test-open-file/open.txt::read-only' \
             -p OpenFile='/tmp/test-open-file/file\x3Acolon.txt:colon' \
             -p RemainAfterExit=yes \
+            -p EnvironmentFile=-/usr/lib/systemd/systemd-asan-env \
             --unit=test-23-openfile-existing.service \
             --service-type=oneshot \
             /usr/lib/systemd/tests/testdata/units/testsuite-23-openfile-child.sh 2 "open.txt:colon" "Open" "File"
```

should (hopefully) take care of that.

**Review by bluca — APPROVED** [review]

**Pull request merged**
