### PR TITLE
test-network: add/update module check

### PR DESCRIPTION
**Pull request by yuwata**
For https://github.com/systemd/systemd-centos-ci/pull/517.

### CODE REVIEW

**Review by mrc0mmand — APPROVED** [review]
LGTM, thank you!

With this change + systemd/systemd-centos-ci#517 + tweaking `ServerAliveInteval=` from `2` to `30` seconds the test suite now finally passes on EC2 machines as well:

```
----------------------------------------------------------------------
Ran 153 tests in 1580.008s

OK (skipped=1, expected failures=25)
```

**Comment by mrc0mmand** [comment]
Oh well, the *old* infra doesn't like the change:

```
test_l2tp_udp (__main__.NetworkdL2TPTests) ... â— 162: test1                    
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /run/systemd/network/25-l2tp-dummy.network
                          Type: ether
                          Kind: dummy
                         State: routable (configured)
                  Online state: online
                        Driver: dummy
              Hardware Address: ba:37:47:39:aa:3c
                           MTU: 1500
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
      Number of Queues (Tx/Rx): 1/1
                       Address: 192.168.30.100
                                fe80::b837:47ff:fe39:aa3c
             Activation Policy: up
           Required For Online: yes


Found link 162
Found link 129
Found link 19
Found link 18
Found link 16
Found link 15
Found link 14
Found link 11
Found link 10
Found link 9
Found link 8
Found link 7
Found link 6
Found link 5
Found link 4
Found link 3
Found link 2
Found link 1
still waiting for l2tp-ses1
still waiting for l2tp-ses1
still waiting for l2tp-ses1
still waiting for l2tp-ses1
still waiting for l2tp-ses1
still waiting for l2tp-ses1
Timeout occurred while waiting for network connectivity.
...

Aug 16 20:17:59 n3.dusty.ci.centos.org systemd-networkd[137276]: test1: Addresses set
Aug 16 20:17:59 n3.dusty.ci.centos.org systemd-networkd[137276]: test1: State changed: configuring -> configured
Aug 16 20:17:59 n3.dusty.ci.centos.org systemd-networkd[137276]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_3162 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=25 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Aug 16 20:17:59 n3.dusty.ci.centos.org systemd-networkd[137276]: l2tp99: L2TP tunnel is created
Aug 16 20:17:59 n3.dusty.ci.centos.org systemd-networkd[137276]: l2tp99: L2TP session l2tp-ses1 could not be created: Protocol not supported
Aug 16 20:17:59 n3.dusty.ci.centos.org systemd-networkd[137276]: l2tp99: L2TP session l2tp-ses2 could not be created: Protocol not supported
```

```
test_l2tp_ip (__main__.NetworkdL2TPTests) ... â— 161: test1                    
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /run/systemd/network/25-l2tp-dummy.network
                          Type: ether
                          Kind: dummy
                         State: routable (configured)
                  Online state: online
                        Driver: dummy
              Hardware Address: ba:37:47:39:aa:3c
                           MTU: 1500
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
      Number of Queues (Tx/Rx): 1/1
                       Address: 192.168.30.100
                                fe80::b837:47ff:fe39:aa3c
             Activation Policy: up
           Required For Online: yes


Found link 161
Found link 129
Found link 19
Found link 18
Found link 16
Found link 15
Found link 14
Found link 11
Found link 10
Found link 9
Found link 8
Found link 7
Found link 6
Found link 5
Found link 4
Found link 3
Found link 2
Found link 1
still waiting for l2tp-ses3
still waiting for l2tp-ses3
still waiting for l2tp-ses3
still waiting for l2tp-ses3
still waiting for l2tp-ses3
still waiting for l2tp-ses3
Timeout occurred while waiting for network connectivity.
...
Aug 16 20:17:39 n3.dusty.ci.centos.org systemd-networkd[135350]: test1: Addresses set
Aug 16 20:17:39 n3.dusty.ci.centos.org systemd-networkd[135350]: test1: State changed: configuring -> configured
Aug 16 20:17:39 n3.dusty.ci.centos.org systemd-networkd[135350]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_3161 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=28 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Aug 16 20:17:39 n3.dusty.ci.centos.org systemd-networkd[135350]: l2tp99: netdev could not be created: Protocol not supported
```

**Comment by yuwata** [comment]
@mrc0mmand Could you test again?

**Comment by mrc0mmand** [comment]
> @mrc0mmand Could you test again?

Thank you! The EC2 run passed once again and the Arch Linux fail is unrelated (#23866). Hopefully the "old" C8S run will be content as well.

**Comment by yuwata** [comment]
@mrc0mmand Sorry, the previous version fails on CentOS. Now all green. Please test again on the new infra.

**Comment by mrc0mmand** [comment]
Both the *old* and the *new* infra appears to be happy with this patch, thank you!

**Pull request merged**
