### PR TITLE
test: add test coverage for AccessContainer=

### PR DESCRIPTION
**Pull request by msekletar**

### CODE REVIEW

**Comment by msekletar** [comment]
@poettering Btw, I am also working on #34130 but I wanted to add test case first.

**Comment by msekletar** [comment]
@mrc0mmand Do you have any idea if `inst_binary gcc` is going to work?

**Comment by bluca** [comment]
Is there a specific reason to have a custom program rather than just `kill -11 $$` or so?

**Comment by msekletar** [comment]
> Is there a specific reason to have a custom program rather than just `kill -11 $$` or so?

Point of the custom program is to have predictable stack trace, i.e. baz() bar() foo().

**Comment by bluca** [comment]
Ok, makes sense - installing seems to work, but the test is just skipped because it doesn't run in a VM:

`[ 1625.512962] TEST-74-AUX-UTILS.sh[299]: Running in a container, skipping the systemd-coredump test...`

I guess this test never ran, which is, er, not great - I guess it needs to be moved into a standalone test that runs in qemu, as TEST-74 is a bit of a kitchen sink so we don't want to run the whole thing in a VM, as it would make it a lot slower

**Comment by msekletar** [comment]
This will be part of #34333.

**Comment by dtardon** [comment]
> > Is there a specific reason to have a custom program rather than just `kill -11 $$` or so?
> 
> Point of the custom program is to have predictable stack trace, i.e. baz() bar() foo().

But we don't actually need to know _what_ is in the stack trace, do we? Just that it's as good as if the program were running outside of any namespace. Therefore the following should work too: take a "reference" stack trace of `something`. Then take another one when `something` is running inside a container. Finally, check that the two stack traces are equal.

**Comment by msekletar** [comment]
> But we don't actually need to know _what_ is in the stack trace, do we? Just that it's as good as if the program were running outside of any namespace. Therefore the following should work too: take a "reference" stack trace of `something`. Then take another one when `something` is running inside a container. Finally, check that the two stack traces are equal.

Sure, but parsing stacktraces (and you have to do that because libraries are mapped to different addresses every time) seemed like too much work. However, if gcc dependency is a problem for whatever reason I can rework it.

**Comment by msekletar** [comment]
On top of that because I am compiling with `-g` I am guaranteed to have sensible output. On distro w/o (mini)debuginfo ( you would get bunch of n/a entries in both cases.

**Comment by dtardon** [comment]
> On top of that because I am compiling with `-g` I am guaranteed to have sensible output. On distro w/o (mini)debuginfo ( you would get bunch of n/a entries in both cases. I guess I take back that I can rework it.

Hm, right, I didn't think of that either.

Another possibility is to put the test source to the tree somewhere (`src/coredump/test-stack-trace.c`?) and let it be built in advance. That way, you'd still have a full control over compiler flags, but wouldn't have to put the compiler itself to the test image.

**Pull request closed without merging**
