### PR TITLE
networkd: routes - support a few more options

### PR DESCRIPTION
**Pull request by teg**
We now add support for 'onlink' routes and use this for DHCPv4. Moreover, we add support for dropping packets through 'blackhole', 'prohibited' and 'unreachable' routes.

### CODE REVIEW

**Comment by poettering** [comment]
looks pretty OK, but I think we should log in case of OOM in that one case...

**Comment by martinpitt** [comment]
@teg, I suppose you're aware of the assertion crash that is exhibited by `tests/test-networkd.py`? (see ubuntu-ci test log):

```
Feb 24 18:25:33 adt systemd-networkd[22065]: test_eth42: Could not set DHCPv4 route: Invalid argument
Feb 24 18:25:33 adt systemd-networkd[22065]: test_eth42: Failed
Feb 24 18:25:33 adt systemd-networkd[22065]: Assertion 'link->state == LINK_STATE_SETTING_ROUTES' failed at ../src/network/networkd-link.c:618, function link_enter_configured(). Aborting.
```

**Comment by zonque** [comment]
ping?

**Comment by teg** [comment]
This needs to be reworked as blackhole and friends needs support for link-independent routes, which we currently don't have. Also, 'onlink' routes appears to have issues with older kernels.

**Pull request closed without merging**
