### PR TITLE
hwdb - add Acer Aspire Switch 10 to hwdb sensor config.

### PR DESCRIPTION
**Pull request by cedel1**
Adds accelerometer sensor orientation info for Acer Aspire Switch 10 FHD, pn SW5-012.

### CODE REVIEW

**Comment by hadess** [comment]
Could you please fix the commit message to match that of other similar changes to the same file?
Something like:
```
hwdb: Add ACCEL_MOUNT_MATRIX for the Acer Aspire Switch 10 convertible (#7394)
```
should do.

**Comment by cedel1** [comment]
@hadess - Sorry, I'm a bit confused.. Is it OK like this or how do I do that?

**Comment by hadess** [comment]
Use `git rebase -i` to get rid of the "Merge branch master" bit. There should be only one commit on top of the original sources in your master branch.

**Comment by cedel1** [comment]
Better? Before you answered, I figured out I could reset my local branch, ammend commit locally and force push to github.

**Pull request merged**
