### PR TITLE
analyze: split out each verb into its own .c/.h pair

### PR DESCRIPTION
**Pull request by poettering**
This is just some refactoring, modelled after what we did for systemctl: split one humongous .c file into multiple smaller ones, relatively systematically with one for each verb.

### CODE REVIEW

**Comment by medhefgo** [comment]
I always wondered: Why bother with the `$toolname-` prefix in these splits? It seems unnecessary to me, considering they reside in the `$toolname` folder.

**Comment by bluca** [comment]
Quite a large diff - are there any code changes (besides the last two commits) or is it a plain cut/paste?

**Comment by poettering** [comment]
> I always wondered: Why bother with the `$toolname-` prefix in these splits? It seems unnecessary to me, considering they reside in the `$toolname` folder.

Mostly because most editors only show filenames not dirs when you have multiple buffers open. If you have verbs like "dump" or "time" or "verify" then the chance is really high you'll have other files dump.c/time.c/verify.c all over the place.

Also, why not name it like that? it's not that you actually have to type in the names in full, given completion everywhere?

**Comment by poettering** [comment]
> Quite a large diff - are there any code changes (besides the last two commits) or is it a plain cut/paste?

Yes, I should have mentioned that. The commits whose name start with "split out" are all just that: split outs, i.e. no actual code changes, just copy/paste into new files.

**Comment by keszybz** [comment]
> Mostly because most editors only show filenames not dirs when you have multiple buffers open

FWIW, I configure my emacs to append unique directory suffix, so I get e.g. `file.c/dir1` and `file.c/dir2`. This works better than trying to keep filenames unique, because it also supports the case where you have the same project in two versions, e.g. with two git workdirs. (This is not the default emacs config… By having a suffix that looks like a part of the path it is also easy to switch between the files by name and it doesn't involve any characters that would be annoying to input from the keyboard.)

I guess we can keep the file names unique. Even if isn't really necessary for the editor, it might help us avoid somebody editing the wrong file by mistake.

**Comment by keszybz** [comment]
LGTM.

**Comment by keszybz** [comment]
Thinking about this a bit more: those long names actually *interfere* with bash completion, at least for me. E.g. in `src/resolve/` most files the prefixes `resolved-`, but there's also `resolvectl` and `resolvconf-`, so `re<TAB><letter><TAB><letter><TAB><TAB><letter>` is needed to complete a file name. If we dropped `resolved-`, there would be many more unique prefixes.

But that's a discussion for another time.

**Comment by evverx** [comment]
Looks like it's failing to compile:
```
../src/analyze/analyze-syscall-filter.c:188:5: error: no previous prototype for function 'dump_syscall_filters' [-Werror,-Wmissing-prototypes]
int dump_syscall_filters(int argc, char *argv[], void *userdata) {
    ^
../src/analyze/analyze-syscall-filter.c:188:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
int dump_syscall_filters(int argc, char *argv[], void *userdata) {
^
static
1 error generated.
```

**Comment by poettering** [comment]
ah, seems i fucked up the non-seccomp builds. lemme fix.

**Comment by poettering** [comment]
> ah, seems i fucked up the non-seccomp builds. lemme fix.

See #22594

**Pull request merged**
