### PR TITLE
core: add {Runtime,State,Cache,Logs,Configuration}Directory{User,Group}= option

### PR DESCRIPTION
**Pull request by yuwata**
This introduces {Runtime,State,Cache,Logs,Configuration}Directory{User,Group}= options that specify the owner of the corresponding directories. On top of the options, networkd, resolved, and timesyncd drop the capabilities in the following commits, which are inspired by the commits in PR #6393 by @Siosm.

### CODE REVIEW

**Comment by poettering** [comment]
Oh, I don't think we should have specific User/Group settings for all those dirs. Instead, we should use the values specified in User=/Group= for the ownership of those directories. And if you then want to run the program specified with ExecStart= as root, use the "+" prefix or so?

**Comment by yuwata** [comment]
If my understanding is correct, "+" prefix makes ExecStart ignore not only user and group but all privilege settings. So, I think the way to use the prefix is not suitable in this case.

**Comment by poettering** [comment]
Ah, true, so maybe we need to add a new switch '!' for that I figure... Adding that should be really easy though

**Comment by yuwata** [comment]
@poettering Yeah, but instead of adding new prefix, how abot adding, say `AmbientFallback=` or something for the case that if we cannot set the ambient capabilities then add capabilities to the set specified in `CapabilitiesBoundingSet=` and the process is run by root (for the services run by PID=1). If my understanding is correct, then `AmbientCapabilities=` is set to intend to run the services by non-root users with some capabilities. And if the kernel does not support ambient capabilities, the services are need to run by root, and the services need to drop the privileges and capabilities after the process are started. In such a situation, the services need more capabilities such that CAP_SETUID, CAP_SETGID, and CAP_SETPCAP. The option is used to specifies such options. What do you think about?

**Comment by yuwata** [comment]
@poettering I create a new PR #6433 based on my last comment.

**Pull request closed without merging**
