### PR TITLE
test-mountpoint-util: support running on a mount namespace with another mount on /proc

### LINKED ISSUE #11505: test-mountpoint-util fails when run in a mount/pid namepace
**systemd version the issue has been seen with**
240

**Used distribution**
Gentoo
https://bugs.gentoo.org/674458

**Summary**
Gentoo's Portage package manager runs builds in a separate pid namespace. It also creates a separate mount namespace to allow /proc to be over-mounted with a new proc instance.

When run in such an environment, `test-mountpoint-util` fails as below.
```
--- command ---
SYSTEMD_KBD_MODEL_MAP='/x/portage/sys-apps/systemd-240-r2/work/systemd-240/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/x/portage/sys-apps/systemd-240-r2/work/systemd-240/src/locale/language-fallback-map' PATH='/x/portage/sys-apps/systemd-240-r2/work/systemd-240-abi_x86_64.amd64:/x/portage/sys-apps/systemd-240-r2/temp/python3.7/bin:/usr/lib/ccache/bin:/home/floppym/src/portage/bin/ebuild-helpers/xattr:/home/floppym/src/portage/bin/ebuild-helpers:/usr/lib/llvm/7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin' /x/portage/sys-apps/systemd-240-r2/work/systemd-240-abi_x86_64.amd64/test-mountpoint-util
--- stderr ---
Found container virtualization none.
/* test_mount_propagation_flags(shared) */
/* test_mount_propagation_flags(slave) */
/* test_mount_propagation_flags(private) */
/* test_mount_propagation_flags((null)) */
/* test_mount_propagation_flags() */
/* test_mount_propagation_flags(xxxx) */
/* test_mount_propagation_flags( ) */
/* test_mnt_id */
mountinfo: / → 464
mountinfo: /sys → 465
mountinfo: /sys/fs/cgroup → 466
mountinfo: /sys/fs/cgroup/unified → 467
mountinfo: /sys/fs/cgroup/systemd → 468
mountinfo: /sys/fs/cgroup/perf_event → 469
mountinfo: /sys/fs/cgroup/pids → 470
mountinfo: /sys/fs/cgroup/cpu,cpuacct → 471
mountinfo: /sys/fs/cgroup/net_cls,net_prio → 472
mountinfo: /sys/fs/cgroup/cpuset → 473
mountinfo: /sys/fs/cgroup/blkio → 474
mountinfo: /sys/fs/cgroup/memory → 475
mountinfo: /sys/fs/cgroup/devices → 476
mountinfo: /sys/fs/cgroup/freezer → 477
mountinfo: /sys/fs/cgroup/hugetlb → 478
mountinfo: /sys/fs/bpf → 479
mountinfo: /sys/kernel/debug → 480
mountinfo: /sys/fs/fuse/connections → 481
mountinfo: /dev → 482
mountinfo: /dev/shm → 483
mountinfo: /dev/pts → 484
mountinfo: /dev/mqueue → 485
mountinfo: /dev/hugepages → 486
mountinfo: /run → 487
mountinfo: /run/user/10000 → 488
mountinfo: /run/user/0 → 489
mountinfo: /proc → 490
mountinfo: /proc/sys/fs/binfmt_misc → 491
mountinfo: /proc/sys/fs/binfmt_misc → 492
mountinfo: /tmp → 493
mountinfo: /x → 494
mountinfo: /mnt/data1 → 495
mountinfo: /var/cache/distfiles → 496
mountinfo: /home → 497
mountinfo: /home/floppym/tmp → 498
mountinfo: /var/cache/packages → 499
mountinfo: /boot → 500
mountinfo: /proc → 503
mnt ids of /run are 487, 487
mnt ids of /var/cache/packages are 499, 499
mnt ids of /boot are 500, 500
mnt ids of /sys/fs/cgroup/cpuset are 473, 473
mnt ids of /dev/shm are 483, 483
mnt ids of /run/user/0 are 489, 489
mnt ids of /proc/sys/fs/binfmt_misc are 491, 503
the other path for mnt id 503 is /proc
Assertion 'path_equal(p, t)' failed at ../systemd-240/src/test/test-mountpoint-util.c:86, function test_mnt_id(). Aborting.
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #11505.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @floppym

**Comment by yuwata** [comment]
@keszybz With this, I guess we can drop the patch https://src.fedoraproject.org/rpms/systemd/blob/rawhide/f/f58b96d3e8d1cb0dd3666bc74fa673918b586612.patch

**Comment by floppym** [comment]
With this patch applied, I get a different assert failure:
```
================================== 479/1064 ==================================
test:         systemd / test-mountpoint-util
start time:   20:08:20
duration:     0.09s
result:       killed by signal 6 SIGABRT
command:      SYSTEMD_LANGUAGE_FALLBACK_MAP=/x/portage/sys-apps/systemd-251.4/work/systemd-stable-251.4/src/locale/language-fallback-map MALLOC_PERTURB_=219 PATH=/x/portage/sys-apps/systemd-251.4/work/systemd-stable-251.4-abi_x86_64.amd64:/x/portage/sys-apps/systemd-251.4/temp/python3.11/bin:/usr/lib/ccache/bin:/home/floppym/src/portage/bin/ebuild-helpers/xattr:/home/floppym/src/portage/bin/ebuild-helpers:/usr/local/sbin:/usr/sbin:/sbin:/bin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/15/bin:/usr/lib/llvm/14/bin:/usr/lib/llvm/13/bin /x/portage/sys-apps/systemd-251.4/work/systemd-stable-251.4-abi_x86_64.amd64/test-mountpoint-util
----------------------------------- stderr -----------------------------------
Lacking privilege to create separate mount namespace, proceeding in originating mount namespace.
/* test_fd_is_mount_point */
/* test_path_is_mount_point */
Assertion '!strstr("Skipping bind mount file test: %m", "%m")' failed at src/test/test-mountpoint-util.c:275, function test_path_is_mount_point(). Aborting.
==============================================================================
```

**Comment by yuwata** [comment]
@floppym Ouch. Should be fixed now. PTAL

**Comment by floppym** [comment]
That fixed it, thanks.

**Comment by mrc0mmand** [comment]
*sigh*, this conflicts with the Fedora downstream patch for test-mountpoint-util: https://src.fedoraproject.org/rpms/systemd/blob/rawhide/f/f58b96d3e8d1cb0dd3666bc74fa673918b586612.patch. I really wish we could finally get rid of it.

**Comment by poettering** [comment]
Hmm, looking at this again, isn't this actually just a matter of always storing info about the last entry for any given path in /proc/self/mountinfo, instead of the first, like we do now?

iiuc /proc/self/mountinfo puts newer mounts at the bottom and older mounts at the top.

A simple way to implement the test would then be to just maintain the mount table as an array or linked list, and then for any mount go from back to front to find the accessible mount. A simple path_startswith() should be enough.

**Comment by yuwata** [comment]
> Hmm, looking at this again, isn't this actually just a matter of always storing info about the last entry for any given path in /proc/self/mountinfo, instead of the first, like we do now?
> 
> iiuc /proc/self/mountinfo puts newer mounts at the bottom and older mounts at the top.
> 
> A simple way to implement the test would then be to just maintain the mount table as an array or linked list, and then for any mount go from back to front to find the accessible mount. A simple path_startswith() should be enough.

Yeah, that should also work. But, this is just a test for `path_get_mnt_id()`, not used code. I do not think it is necessary to overhaul the test. I will re-implement it in that way if you really want, but do you really request that?

**Comment by keszybz** [comment]
Yep, this looks like it should DTRT. Let's merge.

**Pull request merged**
