### PR TITLE
linux: import more headers from kernel-5.0

### LINKED ISSUE #12300: systemd-242 unable to build with kernel 3.14 (L2TP_ATTR_UDP_ZERO_CSUM6_TX missing)
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > LibreELEC

**Expected behaviour you didn't see**
 > systemd-242 can build against kernel 3.14, as systemd [claims to support](https://github.com/systemd/systemd/blob/v242/README#L35) >= 3.13.

**Unexpected behaviour you saw**
 >systemd-242 fails to build against 3.14.29 due to missing `L2TP_ATTR_UDP_ZERO_CSUM6_TX` and `L2TP_ATTR_UDP_ZERO_CSUM6_RX` support - this first appeared in 3.16.0.

**Steps to reproduce the problem**

Build systemd-242 against kernel 3.14.y (or even 3.15.y), basically against any pre-3.16.0 kernel.

Also, this build failure occurs despite systemd-242 being built with `-Dnetworkd=false`.

### PR DESCRIPTION
**Pull request by yuwata**
This imports in.h, in6.h and l2tp.h from kernel-5.0.

Fixes #12300.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
OK, hit a bit of a snag building systemd master.

systemd d90a044f49d7c7238c6423b970949b11fb6e1528 (tip of master) isn't currently building at all, not with kernel 5.0.7 or 3.14, with or without #12305.

It fails as follows (kernel 5.0.7, without #12305):
```
[324/693] Compiling C object 'src/shared/5afaae1@@systemd-shared-242@sta/enable-mempool.c.o'.
[325/693] Compiling C object 'src/shared/5afaae1@@systemd-shared-242@sta/efivars.c.o'.
[326/693] Compiling C object 'src/shared/5afaae1@@systemd-shared-242@sta/bootspec.c.o'.
FAILED: src/shared/5afaae1@@systemd-shared-242@sta/bootspec.c.o 
/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.1-devel/toolchain/bin/armv7ve-libreelec-linux-gnueabi-gcc -Isrc/shared/5afaae1@@systemd-shared-242@sta -Isrc/shared -I../src/shared -Isrc/basic -I../src/basic -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/udev -I../src/udev -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -Isrc/shutdown -I../src/shutdown -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I../ -I/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.1-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include -I/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.1-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/libmount -I/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.1-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/blkid -I/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.1-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/uuid -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=gnu99 -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -ffunction-sections -fdata-sections -Werror=shadow -include config.h -fPIC -pthread -fvisibility=default -march=armv7ve -mtune=cortex-a7 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=cortex-a7 -mfloat-abi=hard -mfpu=neon-vfpv4 -fomit-frame-pointer -Wall -pipe -Os -fno-schedule-insns -fno-schedule-insns2 -Wno-format-truncation -MD -MQ 'src/shared/5afaae1@@systemd-shared-242@sta/bootspec.c.o' -MF 'src/shared/5afaae1@@systemd-shared-242@sta/bootspec.c.o.d' -o 'src/shared/5afaae1@@systemd-shared-242@sta/bootspec.c.o' -c ../src/shared/bootspec.c
../src/shared/bootspec.c: In function 'boot_entries_augment_from_loader':
../src/shared/bootspec.c:779:21: error: implicit declaration of function 'efi_variable_path' [-Werror=implicit-function-declaration]
                 p = efi_variable_path(EFI_VENDOR_LOADER, "LoaderEntries");
                     ^~~~~~~~~~~~~~~~~
../src/shared/bootspec.c:779:21: warning: nested extern declaration of 'efi_variable_path' [-Wnested-externs]
../src/shared/bootspec.c:779:19: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
                 p = efi_variable_path(EFI_VENDOR_LOADER, "LoaderEntries");
                   ^
cc1: some warnings being treated as errors
[327/693] Compiling C object 'src/shared/5afaae1@@systemd-shared-242@sta/exit-status.c.o'.
[328/693] Compiling C object 'src/shared/5afaae1@@systemd-shared-242@sta/condition.c.o'.
[329/693] Compiling C object 'src/shared/5afaae1@@systemd-shared-242@sta/conf-parser.c.o'.
[330/693] Compiling C object 'src/shared/5afaae1@@systemd-shared-242@sta/fdset.c.o'.
[331/693] Compiling C object 'src/shared/5afaae1@@systemd-shared-242@sta/fileio-label.c.o'.
[332/693] Compiling C object 'src/shared/5afaae1@@systemd-shared-242@sta/dissect-image.c.o'.
[333/693] Compiling C object 'systemd-nspawn@exe/src_nspawn_nspawn.c.o'.
ninja: build stopped: subcommand failed.
```
Full build log: http://ix.io/1G5J (d90a044f49d7c7238c6423b970949b11fb6e1528 *without* #12305, against kernel 5.0.7).

#12219 seems to introduce this new failure - I'll post the relevant details on that PR.

The last commit that does build is 1e5d2d656420d0e755dbcf72aeba3c3aba54e956, which is not immediately compatible with #12305 as this PR has a dependency on #12269.

I tried building 1e5d2d656420d0e755dbcf72aeba3c3aba54e956 (last buildable commit before #12219) with #12269 and with/without #12305 against various kernels, results below:

1e5d2d656420d0e755dbcf72aeba3c3aba54e956+#12269 without #12305 against kernel 5.0.7 => success
1e5d2d656420d0e755dbcf72aeba3c3aba54e956+#12269 WITH #12305 against kernel 5.0.7 => success

1e5d2d656420d0e755dbcf72aeba3c3aba54e956+#12269 without #12305 against kernel 5.1-rc4 => success
1e5d2d656420d0e755dbcf72aeba3c3aba54e956+#12269 WITH #12305 against kernel 5.1-rc4 => success

1e5d2d656420d0e755dbcf72aeba3c3aba54e956+#12269 without #12305 against kernel 3.14.29 => FAIL (L2TP_ATTR_UDP_ZERO_CSUM6_TX missing)
1e5d2d656420d0e755dbcf72aeba3c3aba54e956+#12269 WITH #12305 against kernel 3.14.29 => success

So this change looks good (it builds against 3.14 now, not yet run-time tested) and a systemd-242 backport would be much appreciated (I can test that for you too!)

**Comment by yuwata** [comment]
Wow! Thank you for testing so many variations.

**Comment by yuwata** [comment]
@MilhouseVH Another round of tests with #12307 is welcome :-)

**Comment by MilhouseVH** [comment]
Thanks - d90a044f49d7c7238c6423b970949b11fb6e1528 with #12307 and this PR now builds successfully against kernels 3.14.29, 5.07 and 5.1-rc4!

**Comment by yuwata** [comment]
Thanks a lot!

**Pull request merged**
