### PR TITLE
turn off fuzzit

### PR DESCRIPTION
**Pull request by evverx**
It seems it went down yesterday and it's not clear how long it will
take to bring it back.

cc @yevgenypats

### CODE REVIEW

**Comment by evverx** [comment]
I'll go ahead and merge it to make Travis green and prevent it from sending all those notifications to contributors. I'll bring Fuzzit back once it's up and running.

**Comment by evverx** [comment]
I reverted this commit in https://github.com/systemd/systemd/pull/16099 and also introduced a memory leak to see how Fuzzit would react to it. According to https://app.fuzzit.dev/orgs/systemd/targets/fuzz-unit-file-asan-ubsan/Uv1RXERr5S9fJLY8YfMV, the fuzz target crashed but Fuzzit couldn't get the logs:
Screenshot 2020-06-09 at 04 20 12

@yevgenypats could you take a look?

Other than that it seems Fuzzit neither sent an email notification nor reported the issue on the dashboard. I think before turning it on it would make sense to wait until those issues are fixed.

**Comment by evverx** [comment]
To judge from https://app.fuzzit.dev/orgs/systemd/targets/fuzz-unit-file-asan-ubsan/dusqXY75FoWWZuVSu7wg, the logs are back to normal. The memory leak hasn't been reported by Fuzzit yet though.

**Comment by evverx** [comment]
@yevgenypats congratulations on joining GitLab!

In light of the announcement I turned off Fuzzit completely in https://github.com/systemd/systemd/pull/16154 but I can't seem to remove the systemd organization to free up the resources. I'd appreciate it if you could remove it (and also my account from there) so as not to waste the CPUs.

**Comment by evverx** [comment]
On the bright side, now that Fuzzit is gone (along with UBsan and MSan) it seems I'll finally get around to https://github.com/google/oss-fuzz/issues/3421. The patch to OSS-Fuzz is being tested in https://github.com/systemd/systemd/pull/16150

**Comment by evverx** [comment]
@mrc0mmand I wonder if you have access to https://www.freedesktop.org/wiki/Software/systemd/? Could you remove `fuzzit` (mentioned next to OSS-Fuzz) from there?

**Comment by mrc0mmand** [comment]
> @mrc0mmand I wonder if you have access to https://www.freedesktop.org/wiki/Software/systemd/? Could you remove `fuzzit` (mentioned next to OSS-Fuzz) from there?

Unfortunately no. I guess this will have to go through @keszybz.

**Comment by evverx** [comment]
I'm not sure how important this is but since we no longer use fuzzit, I've just asked to remove the logo from the "trusted by" section at https://fuzzit.dev/.

In the meantime, I opened https://github.com/google/oss-fuzz/pull/3969. Once it's reviewed and merged we will be able to bring both MSan and UBsan. With 5 parallel jobs when PRs are opened we should probably start thinking about canceling jobs. Though I wouldn't worry about that until it's clear it's an issue.

**Comment by yevgenypats** [comment]
Hi Evgeniy, thank you very much. sure thing, I'll take care of it.

**Comment by keszybz** [comment]
On Thu, Jun 11, 2020 at 03:43:33PM -0700, Evgeny Vereshchagin wrote:
> @mrc0mmand I wonder if you have access to https://www.freedesktop.org/wiki/Software/systemd/? Could you remove `fuzzit` (mentioned next to OSS-Fuzz) from there?

Done.

**Pull request merged**
