### PR TITLE
man: reorder/add sections to systemd.exec(5)

### PR DESCRIPTION
**Pull request by poettering**
The long long list of settings is getting too confusing, let's add some
sections and reorder things in them.

This makes no changes regarding contents, it only reorders things,
sometimes reindents them, and adds sections that made sense to me to
some degree.

Within each sections the settings are ordered by relevance (at least
according to how relevant I personally find them), and not
alphabetically.

### CODE REVIEW

**Comment by keszybz** [comment]
<strike>Can we reconsider the split into systemd.exec and systemd.resource-control? It is motivated by the implementation details, but for users the purpose of the settings not the implementation is more important. E.g. LimitCPU= and CPUWeight= should be in the same document.</strike>

CapabilityBoundingSet, AmbientCapabilities, NoNewPrivileges, SecureBits don't seem to belong in Credentials. Credentials == identifying information. Maybe they should be moved to Sandboxing?

Process Properties and Scheduling sections should be next to each other, because the boundary between them is fluid. Environment section is well defined, so it can go after them. I'd also move Sandboxing and System Call Filtering sections right after PP and Scheduling, since the boundaries between all four sections are pretty arbitrary:

    <title>Paths</title>
    <title>Credentials</title>
    <title>Mandatory Access Control</title>      (a type of credentials too)
    <title>Process Properties</title>
    <title>Scheduling</title>
    <title>Sandboxing</title>
    <title>System Call Filtering</title>
    <title>Environment</title>
    <title>Logging and Standard Input/Output</title>
    <title>System V Compatibility</title>
?

**Comment by poettering** [comment]
well, systemd.exec and systemd.resource-control is split because the former applies to all units that fork off processes while the latter also to do those which just contain processes. the latter is a superset of the former: service, mount, swap, socket are in the first group, and the second group adds slice and scope on top. 

I think it would become quite awkward if the scope and slice documentation could not sensibly share the cgroup documentation with the service/mount/swap/socket documentation...

**Comment by poettering** [comment]
Note that there's also systemd.kill which applies to service/mount/swap/socket as well as scope, but not slice...

**Comment by keszybz** [comment]
Ah, right, I forgot about this.

**Comment by keszybz** [comment]
@poettering what about other comments?

**Comment by poettering** [comment]
I force pushed a new version now, addressing your points. However, I split out the caps stuff into its own section "Capabilities", and gave NNP and Securebits its own section "Security". I hope that makes sense. PTAL

**Comment by keszybz** [comment]
Thanks, lgtm.

**Pull request merged**
