### PR TITLE
mount: compare mountinfo entries against current list of mounts to no reprocess a known mount continuously

### PR DESCRIPTION
**Pull request by rmetrich**
With current code, every time /proc/1/mountinfo is processed, the device and mount units for all entries is updated.
On heavily used systems, such as OpenShift nodes, we see a huge amount of mount notifications, typically because new containers are spawned regularly. This creates a huge load on systemd.

The optimization consists is checking whether a mount entry has already been processed in the past, and preventing from continuously updating the device unit and mount unit which didn't change at all, saving tremendous CPU cycles.

As an example, with a system having 200 mounts, performing 100 remounts (with no option change at all) of 1 file system shows 523396 syscalls being processed by systemd, whereas with the optimization only 3902 syscalls are processed (99% saving).

**Reproducer**:

1. Set up a system with 200 mount points on a "data" volume group

    ~~~
    # vgcreate data /dev/sdb
    # for i in $(seq 1 200); do lvcreate -n lv$i -L 10M data; mkfs.ext4 /dev/data/lv$i; echo "/dev/mapper/data-lv$i /data/lv$i ext4 defaults 0 0" >> /etc/fstab; mkdir -p /data/lv$i; done
    # systemctl daemon-reload
    # mount -a
    ~~~

2. strace systemd while performing 100 remounts of /data/lv1

    - In a terminal:

        ~~~
        # timeout 1m strace -ttTvyy -o /tmp/systemd.strace -s 128 -p 1
        ~~~

     - In another terminal:
        ~~~
        # for i in $(seq 1 100); do mount -o remount /data/lv1; sleep 0.1; done
        ~~~

3. Count the number of syscalls

    ~~~
    # wc -l /tmp/systemd.strace
    ~~~

    - Without this PR:

        **523396**

    - With this PR: (99% saving)

       **3902**

See also Red Hat BZ https://bugzilla.redhat.com/show_bug.cgi?id=1884262

### CODE REVIEW

**Comment by raven-au** [comment]
Hi Renaud,

Your implementation looks fine to me and should be quite effective but I don't have enough systemd coding experience yet to offer a review.

Based on what I have seen recently though there area couple of things I think are worth considering.

I think your underestimating the load with only 200 remounts.

I also think your underestimating the impact of the sheer number of notifications which IMHO we don't have a way to manage yet.

There is an attempt at an implementation to help with the rate of notifications at https://github.com/systemd/systemd/pull/17274
and earlier in https://github.com/systemd/systemd/pull/16537 but I fear that will not give sufficient improvement under very heavy load but it's a start and it does give fairly good improvement up to around 5000 mounts.

Together with this PR I think it will be somewhat more effective, there may still be room (maybe a need/opportunity) for further improvement on that rate limiting PR implementation in time.

I'll get around to stress testing this with a heavier load when I get time.

Another thought is related to the libmount usage.

I know that with the current libmount implementation you don't really need to check the return from it's get functions.

But those returns should always be checked, even now when it's not strictly needed, in case the libmount implementation changes. New code in areas that use libmount should add these checks in the areas it's changing to safe guard against this. It's not hard to do and is good coding practice anyway.

For example, the recent attempt to implement a new kernel API for mount information (which ultimately didn't get merged) would have made it possible for invalid returns from the get functions if the mount in question went away before the field in question had actually been retrieved. So a return value check and ignore/continue would have been needed in that case.

Ian

**Comment by rmetrich** [comment]
Hi Ian,
I'm aware I'm underestimating the number of things done with as little as 200 mounts. I have cases where it's even worse but here I'm just showing an example of the improvement we can have here.

Regarding the return values, I understand the code is weak. It appears that I created this code on RHEL8 base first and found out most of the return values were removed from Upstream now, I didn't check who "simplified" the code.

I think restoring back return values should be another PR, since not only mount units are affected, but also device units.

**Comment by raven-au** [comment]
> I think restoring back return values should be another PR, since not only mount units are affected, but also device units.

Yes, that's probably the more sensible thing to do.

**Comment by rmetrich** [comment]
After think about all this again during night, I came to conclusion that a Hash needs to be implemented to have the algorithm in O(n), which would make a big difference with high number of mounts.
I will hence rewrite the code, closing for now.

**Comment by rmetrich** [comment]
@raven-au New PR here: https://github.com/systemd/systemd/pull/17321

**Pull request closed without merging**
