### PR TITLE
semaphore: keep build settings in the repository

### PR DESCRIPTION
**Pull request by evverx**
It should make it easier to tweak them without having access to
SemaphoreCI itself (I'm glad I'm an admin there now but it shouldn't
be necessary to be an admin to add a couple of kludges :-)). More
importantly, changes to the settings will go through review and
be tested before they're applied globally potentially breaking
Semaphore as it happened two days ago.

I'll point Semaphore CI to these scripts once the PR is merged.

### CODE REVIEW

**Comment by evverx** [comment]
I've been looking at the "build" and "compilation" stages for a while and I have to admit that I don't understand the idea behind having both. I think it would be better to join the scripts together. I'm adding the "need-discussion" label because it could be that I'm missing something obvious and both stages are somehow important.

**Comment by evverx** [comment]
One important thing to consider is whether anyone is going to use "secrets" like keys and tokens there. As far as I can tell, SemaphoreCI doesn't provide a way to protect them in PRs sent from forks as TravisCI [does](https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions) so if it's important the PR shouldn't be merged. Having said that, nobody seems to have ever used anything like that there and newer projects in the systemd organizations like [mkosi](https://github.com/systemd/mkosi/tree/master/ci) apparently have no problem with this approach.

**Comment by keszybz** [comment]
I like this. The lack of version control of the semaphore config has been bothering me since forever. Let's merge this, and then work on getting the semaphore config updated.

**Comment by evverx** [comment]
I've just pointed SemaphoreCI to the scripts. I also started to use "+refs/pull/$PULL_REQUEST_NUMBER/merge" there (as we do on TravisCI and CentOS CI) to make the transition as painless as possible. Now, among other things, PRs where 841e1049016de8368644ffbe704752f1ba8d603c is missing don't have to be rebased on top of `master` manually.

**Pull request merged**
