### PR TITLE
units/systemd-udevd: allow bpf() syscall

### PR DESCRIPTION
**Pull request by bboozzoo**
Programs run by udev triggers may need to execute the bpf() syscall. Even more
so, since on a cgroup v2 system, the only way to set up device access filtering
is to install a BPF program on the cgroup in question and one way of passing
data to such program is through BPF maps, which can only be access using the
bpf() syscall. One such use case was identified in RHBZ#2025264 related to
snap-device-helper, and led to RHBZ#2027627 being filed.

Unfortunately there is no finer grained control over what gets passed in the
syscall, so just enable bpf() and leave fine grained mediation to other
security layers (eg. SELinux).

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2027627

### CODE REVIEW

**Comment by yuwata** [comment]
Why not the package which provides snap-device-helper and the related udev rules also provides a drop-in config for systemd-udevd.service which makes `bpf` to be allowed? E.g.
```
# /usr/lib/systemd/system/systemd-udevd.service.d/50-allow-bpf.conf
[Service]
SystemCallFilter=bpf
```

**Comment by bboozzoo** [comment]
> Why not the package which provides snap-device-helper and the related udev rules also provides a drop-in config for systemd-udevd.service which makes `bpf` to be allowed? E.g.
> 
> ```
> # /usr/lib/systemd/system/systemd-udevd.service.d/50-allow-bpf.conf
> [Service]
> SystemCallFilter=bpf
> ```

Yes, that's one solution. On the other hand, udevd is a pretty central service and distros tend to have opinions on how those should work, thus a random package providing a drop in that affects the said service may be a no go. It is also true that helpers triggered by udev already inherit a wide set of permissions anyway, just the bpf() bit is missing.

Please advise on what would be the best way to approach this.

**Comment by poettering** [comment]
Can you elaborate what this is about precisely? udev rules should invoke simple, short-running stuff, and nothing more. i.e. extract some info about the device, and that's it. Why would that involve bpf and things?

usually if you need something like this, it looks as if you are using udev rules for something that it should not be used for, i.e. spawning "heavy" stuff, long-runnng stuff, stuff that actually has non-trivial complexity, and is ore "workload" than "control", and as such is a bad for for udev rules.

(i don't intend to tell you what to put in udev rules or not, but it still makes me weary, i.e. we shouldn't do stuff in upstream for downstream that is does something that is not using the stuff we the way we think this should be used like, after all, there's an easy way to extend the policy that comes from upstream).

hence, can you please explain what this is about?

**Comment by bboozzoo** [comment]
> Can you elaborate what this is about precisely? udev rules should invoke simple, short-running stuff, and nothing more. i.e. extract some info about the device, and that's it. Why would that involve bpf and things?

Sure. It is short running stuff. Our use case is dynamically controlling device access for a specific snap application. Snapd installs udev rules that tag specific devices. When a snap starts, those devices may not be present in the system. however when they appear we expect snap-device-helper to be triggered by udev, which then updates device access rules. On a host using cgorup v1 this would be equivalent to `echo '<class> major:minor rwm' > /sysfs/cgroup/devices/<snap.specific.group>/devices.allow`. With cgroup v2, when the snap starts, we attach a BPF_CGROUP_DEVICE program to scope that we requested from systemd. The program uses a map pinned at `/sys/fs/bpf/snap/<some-snap>` which contains the list of allowed devices. The helpers role is to obtain fd to the map (`bpf(BPF_OBJ_GET, ..`), and add a suitable entry there (`bpf(BPF_MAP_UPDATE_ELEM, ...)`).

**Comment by keszybz** [comment]
OK, let's just do this, as per the last comment.

**Comment by bboozzoo** [comment]
Thank you!

**Pull request merged**
