### PR TITLE
resolved iteration fix

### PR DESCRIPTION
**Pull request by poettering**
Fixes: #2676.

### CODE REVIEW

**Comment by poettering** [comment]
I have now force pushed a new version of this, that is rebased on current git master, so that #2700 is fixed.

**Comment by poettering** [comment]
@keszybz hmm, but it was char before, and uint8_t shouldn't be worse in any way there?

**Comment by keszybz** [comment]
No, `char` is special.

I cannot find an equivalent reference for C, but I think C++ is the same in this regard. C++11 § 3.10:
"If a program attempts to access the stored value of an object through a glvalue of other than one of the following types the behavior is undefined:
- the dynamic type of the object,
- a [qualified] version of the dynamic type of the object,
- an aggregate or union type that includes on of the aforementioned types ...
- a char or unsigned char type.
  "
  So `char` is _the_ type to say "just a sequence of bytes".

**Comment by keszybz** [comment]
http://stackoverflow.com/questions/98650/what-is-the-strict-aliasing-rule has the text for C.

**Comment by poettering** [comment]
well, but "uint8_t" is just an unsigned char anyway, hence this should be good.

**Comment by keszybz** [comment]
You're right, `uint8_t` must be the same as unsigned integer type with one byte, which must be `unsigned char`. I don't fancy the change from `char *` to `void *` because I think it's always better to avoid casts. But it is correct and preferring one over the other would be bike-shedding.

**Pull request merged**
