### PR TITLE
CI test -- don't merge!

### PR DESCRIPTION
**Pull request by martinpitt**
This PR will be used for testing the new autopkgtest CI integration. Please don't merge this yet and keep it open, so that @zonque and I can use this for testing the github webhooks integration.

(FTR, if this gets merged it won't hurt, it's just a grammar and stylistic fix in NEWS)

### CODE REVIEW

**Comment by martinpitt** [comment]
This triggered a first run, but it failed during build already:

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-xenial-pitti-systemd-semaphore/xenial/amd64/s/systemd-upstream/20160217_092934@/log.gz

```
libtool: link: gcc -pipe -Wall -Wextra -Wundef -Wformat=2 -Wformat-security -Wformat-nonliteral -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Werror=overflow -Wdate-time -Wnested-externs -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong -fPIE --param=ssp-buffer-size=4 -Werror=shadow -flto -ffunction-sections -fdata-sections -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wl,--gc-sections -Wl,--no-undefined -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -Wl,-fuse-ld=gold -Wl,-Bsymbolic-functions -Wl,-z -Wl,relro -o test-dns-packet  -Wl,--as-needed
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/Scrt1.o:function _start: error: undefined reference to 'main'
```

**Comment by martinpitt** [comment]
A first full round worked, with manually calling curl for the status updates. Doing the latter from the production environment is blocked on some firewall issue. I sent a ticket and now need to wait for  the Canonical admins to fix this.

**Comment by evverx** [comment]
> This PR will be used for testing the new autopkgtest CI integration. 

:+1: 

I'm reading [Getting the test into Ubuntu](http://packaging.ubuntu.com/html/auto-pkg-test.html#getting-the-test-into-ubuntu)

> commit your changes, push them to Launchpad, propose a merge and get it reviewed just like any other improvement in a source package.

Is there any other way?

**Comment by martinpitt** [comment]
@evverx: The tests are currently maintained in the Debian packaging git, as most of them are heavily specific on having systemd "properly" installed and packaged in the distro: http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/tree/debian/tests

A few of them work for a plain upstream "make install", such as the networkd one. This indeed landed upstream in 229, so I'll adjust the test metadata to use `test/networkd-test.py` instead of `debian/tests/networkd` (which should now be identical). So those can be maintained upstream, for the others please send me git-formatted patches or clone the tree somewhere.

**Comment by martinpitt** [comment]
The infrastructure by and large works now, so I'm closing this to stop cluttering the PR list. I can reopen if/once I need it.

**Comment by evverx** [comment]
I'm trying to reproduce those tests locally.

```
$ hostnamectl
   Static hostname: ubuntu
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 787c77208091721858ef1b9556ad84c9
           Boot ID: 0da9831a9e25473dac237e8b2b271103
    Virtualization: oracle
  Operating System: Ubuntu 16.04
            Kernel: Linux 4.3.0-7-generic
      Architecture: x86-64

$ debcheckout systemd

$ sudo apt-get install -y autopkgtest qemu-system qemu-utils genisoimage python-distro-info

$ adt-buildvm-ubuntu-cloud -v -s 1G -r trusty

$ adt-run --debug \
    --setup-commands 'if grep -q trusty /etc/lsb-release; then apt-get install -y build-essential; fi' \
    --setup-commands 'apt-key adv --keyserver keyserver.ubuntu.com --recv-key FB322597BBC86D52FEE950E299B656EA8683D8A2' \
    --setup-commands 'REL=$(sed -rn "/^(deb|deb-src) .*(ubuntu.com|ftpmaster)/ { s/^[^ ]+ +(\[
.*\] *)?[^ ]* +([^ -]+) +.*$/\2/p; q }" /etc/apt/sources.list); echo "deb http://ppa.launchpad.net/pitti/systemd-semaphore/ubuntu $REL main" > /etc/apt/sources.list.d/autopkgtest-pitti-systemd-semaphore.l
ist; echo "deb-src http://ppa.launchpad.net/pitti/systemd-semaphore/ubuntu $REL main" >> /etc/apt/sources.list.d/autopkgtest-pitti-systemd-semaphore.list; ' \
    --apt-upgrade \
    systemd// \
    --env=CFLAGS=-O0 \
    --env=DEB_BUILD_PROFILES=noudeb \
    --- qemu ./adt-trusty-amd64-cloud.img

...
adt-run: DBG: testbed command exited with code 0
adt-run: DBG: testbed command ['dpkg', '--status', 'adt-satdep'], kind short, sout pipe, serr pipe, env []
adt-run: DBG: testbed command exited with code 1
adt-run: DBG: BadPackageError Test dependencies are unsatisfiable. A common reason is that your testbed is out of date with respect to the archive, and you need to use a current testbed or run apt-get upd
ate or use -U.
adt-run: DBG: testbed stop
adt-run: DBG: testbed close, scratch=/tmp/adt-run.bwXXl9
adt-run: DBG: sending command to testbed: close
qemu-system-x86_64: terminating on signal 15 from pid 10667
adt-run: DBG: got reply from testbed: ok
adt-run: DBG: sending command to testbed: quit
blame: systemd//
badpkg: Test dependencies are unsatisfiable. A common reason is that your testbed is out of date with respect to the archive, and you need to use a current testbed or run apt-get update or use -U.
```

Looks like your `/home/ubuntu/autopkgtest/setup-commands/setup-testbed` contains some useful commands. Or, maybe, I'm missing something:)
How can I reproduce tests locally?

**Comment by martinpitt** [comment]
Trusty doesn't have recent enough dependencies for the current systemd package. Build a "xenial" VM and it should work much better. You also don't need most of these funny commands, this is enough:

```
adt-run --env=TEST_UPSTREAM=1 --env=CFLAGS=-O0 --apt-upgrade systemd// --- qemu adt-xenial-amd64-cloud.img
```

Assuming that `./systemd/` is a checkout of current master.

**Comment by evverx** [comment]
Oh, "trusty" is my copy/paste error:)
Thanks! 

BTW:

```
$ adt-run -d  --env=CFLAGS=-O0  ./systemd// --- qemu ./adt-xenial-amd64-cloud.img -d
...
adt-virt-qemu: DBG: setup_shell(): there already is a shell on ttyS1
adt-virt-qemu: DBG: expect: "#"
adt-virt-qemu: DBG: expect: found ""b'#'""
adt-virt-qemu: DBG: expect: "#"
adt-virt-qemu: DBG: expect: found ""b'#'""
adt-virt-qemu: DBG: Copying host timezone America/New_York to VM
adt-virt-qemu: DBG: expect: "#"
adt-virt-qemu: DBG: expect: found ""b'#'""
adt-virt-qemu: DBG: expect: "/python"
adt-virt-qemu: DBG: expect: found ""b'/python'""
adt-virt-qemu: DBG: expect: "# "
adt-virt-qemu: DBG: expect: found ""b'# '""
adt-virt-qemu: DBG: expect: "# "
adt-virt-qemu: DBG: expect: found ""b'# '""
adt-virt-qemu: DBG: execute-timeout: /tmp/adt-virt-qemu.s7gqd62m/runcmd runlevel
adt-virt-qemu: DBG: runlevel: exit 1, out "unknown
", err "None"
qemu-system-x86_64: terminating on signal 15 from pid 2139
```

So, I use a workaround:

```
--- /usr/bin/adt-virt-qemu  2016-01-21 12:12:51.000000000 -0500
+++ adt-virt-qemu   2016-02-19 18:16:08.047916010 -0500
@@ -381,7 +381,7 @@
         None, 5, VirtSubproc.auxverb + ['runlevel'],
         stdout=subprocess.PIPE)
     adtlog.debug('runlevel: exit %i, out "%s", err "%s"' % (status, out, err))
-    if status == 0 and out.split()[-1] in ['2', '3', '4', '5']:
+    if status == 0 and out.split()[-1] in ['2', '3', '4', '5'] or status == 1 and out and 'unknown' in out:
         adtlog.debug('can connect to autopkgtest sh in VM')
     else:
         VirtSubproc.bomb('failed to connect to VM')
```

**Comment by martinpitt** [comment]
Can you run with `qemu --show-boot adt-xenial-amd64-cloud.img`? Obviously the VM isn't booting correctly for you.

**Comment by evverx** [comment]
Sadly but I can't reproduce this.

> Obviously the VM isn't booting correctly for you.

It's not so obvious:)

```
$ runlevel
N 5

$ rm /var/run/utmp

$ runlevel
unknown

$ systemctl is-active multi-user.target
active
```

**Comment by evverx** [comment]
Oh, I've reproduced.
It's a race between `runlevel` and `systemd-update-utmp-runlevel.service`.

```
adt-virt-qemu: DBG: execute-timeout: /tmp/adt-virt-qemu.ho1x651r/runcmd runlevel
adt-virt-qemu: DBG: runlevel: exit 1, out "unknown
", err "None"
adt-virt-qemu: DBG: execute-timeout: /tmp/adt-virt-qemu.ho1x651r/runcmd systemctl status systemd-update-utmp-runlevel
adt-virt-qemu: DBG: systemctl status systemd-update-utmp-runlevel: exit 3, out "● systemd-update-utmp-runlevel.service - Update UTMP about System Runlevel Changes
   Loaded: loaded (/lib/systemd/system/systemd-update-utmp-runlevel.service; static; vendor preset: enabled)
   Active: inactive (dead) since Sat 2016-03-05 11:40:15 UTC; 488ms ago
     Docs: man:systemd-update-utmp.service(8)
           man:utmp(5)
  Process: 1191 ExecStart=/lib/systemd/systemd-update-utmp runlevel (code=exited, status=0/SUCCESS)
 Main PID: 1191 (code=exited, status=0/SUCCESS)

Mar 05 11:40:14 autopkgtest systemd[1]: Starting Update UTMP about System Runlevel Changes...
Mar 05 11:40:15 autopkgtest systemd[1]: Started Update UTMP about System Runlevel Changes.
", err "None"
adt-virt-qemu: DBG: execute-timeout: /tmp/adt-virt-qemu.ho1x651r/runcmd systemctl is-active graphical.target multi-user.target
adt-virt-qemu: DBG: systemctl is-active graphical.target multi-user.target: exit 0, out "active
active
", err "None"
adt-virt-qemu: DBG: execute-timeout: /tmp/adt-virt-qemu.ho1x651r/runcmd runlevel
adt-virt-qemu: DBG: runlevel: exit 0, out "N 5
", err "None"
qemu-system-x86_64: terminating on signal 15 from pid 9990
adt-virt-qemu: DBG: cleanup...
<VirtSubproc>: failure: failed to connect to VM
```

~~I'll prep a patch.~~ [patch](https://gist.github.com/evverx/0bfaa6fa4f48d7c2f7f1)

**Comment by martinpitt** [comment]
@evverx: That patch works around the race, but it certainly does not _fix_ it. I thought about this some more, and that race is indeed real (although I didn't run into it myself) -- `adt-virt-qemu` waits until the getty (`login:` prompt) appears on the console, but this happens before `default.target` is fully reached. The `runlevel` test is not really needed at this point (mostly just a leftover from previous code), so I changed it like this now: http://anonscm.debian.org/cgit/autopkgtest/autopkgtest.git/commit/?id=745c3017

Thanks!

**Comment by evverx** [comment]
> That patch works around the race, but it certainly does not fix it.

Indeed:)

> so I changed it like this now: http://anonscm.debian.org/cgit/autopkgtest/autopkgtest.git/commit/?id=745c3017

Looks good. Thanks!

**Pull request closed without merging**
