### PR TITLE
github/labeler: set needs-review label when PR is created or updated

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by bluca** [comment]
Can you do a force-push to confirm it works?

**Comment by yuwata** [comment]
Hmm, I thought it works without any force-push, but it does not...

**Comment by yuwata** [comment]
Hmm? `**/*` does not match the file prefixed with a dot?

**Comment by yuwata** [comment]
Unfortunately, it does not work... Closing.

**Comment by mrc0mmand** [comment]
> Unfortunately, it does not work... Closing.

https://github.community/t/using-container-checkout-doesnt-checkout-hidden-files/18429/2

This is... interesting (and somewhat dumb tbh).

**Pull request closed without merging**
