### PR TITLE
Improvements to documentation

### PR DESCRIPTION
**Pull request by jengelh**
A set of five independent suggested changes.

### CODE REVIEW

**Comment by poettering** [comment]
Looks OK besides the issues I raise.

**Comment by zonque** [comment]
@jengelh are you still working on this?

**Comment by jengelh** [comment]
Not at this time. I would have expected that you pick the ones that had no objections.

**Comment by zonque** [comment]
Ok then. I've removed the controversial parts and merged manually. Thanks for the patches!

**Pull request closed without merging**
