### PR TITLE
test-network: add tests for #5430 and GatewayOnLink=

### LINKED ISSUE #5430: (Possibly undocumented?) systemd-networkd reverse route ordering
**TL;DR - Routes defined in a networkd .network file seems to be applied in reverse-order, leading to errors relating to dependent routes.**

> Edit 2019-11-20 for [future travellers](https://xkcd.com/979/): The specific use case below is solved by the addition of the `GatewayOnLink` directive

---

### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

231 (also 219, so not a regression)

### Used distribution

Fedora Server 25 (w/ systemd-231-10.fc25)

### In case of bug report: Expected behaviour you didn't see

Gateway configured in a .network file should appear in the routing table.

### In case of bug report: Unexpected behaviour you saw

The journal shows the errors similar to

```
Feb 23 05:08:19 localhost.localdomain systemd[1]: Started Network Service.
Feb 23 05:08:19 localhost.localdomain systemd-networkd[955]: ens192: Could not set route: Network is unreachable
Feb 23 05:08:32 localhost.localdomain systemd-networkd[955]: ens192: Configured
```

### In case of bug report: Steps to reproduce the problem

1. Optional - Flush the routing table for a clean slate

2. Create a network configuration file with static routes that have dependencies between them - in my case this is the bare minimum configuration that errors (IPs partially redacted);

    ```
    [Match]
    Name=ens192

    [Address]
    Address=149.x.124.58/28

    [Route]
    Destination=149.x.124.64
    Scope=link

    [Route]
    Gateway=149.x.124.64
    ```

3. Restart systemd-networkd

4. See that the routing table contains only the route defined by the `Address` and the first static route.

    ```
    # ip route
    149.x.124.48/28 dev ens192  proto kernel  scope link  src 149.x.124.58 
    149.x.124.64 dev ens192  proto static  scope link
    ````

    The journal will show the error - `ens192: Could not set route: Network is unreachable`.

---

Executed sequentially, the routes are valid. I can't find anything in the networkd docs to suggest any kind of ordering for route configuration. 

**The error does not seem to occur when the order of the two `[Route]` sections are swapped**, which seems counterintuitive.

Is this intended functionality, but undocumented?

### PR DESCRIPTION
**Pull request by yuwata**
~~Fixes #5430~~.

@ssahani Could you review this?

### CODE REVIEW

**Comment by yuwata** [comment]
Updated. I noticed that the issue cannot be reproducible. So, I've dropped the first commit. The tests are updated based on @ssahani's suggestion. PTAL.

**Comment by ssahani** [comment]
Looks good. Yes that issue can't be reproducible. With ```GatewayOnlink``` it works.

**Comment by yuwata** [comment]
@ssahani Thanks a lot!

**Comment by poettering** [comment]
Looks excellent, thanks @ssahani for the reviewing!

**Pull request merged**
