### PR TITLE
Define 'microcode' file type for the kernel-install staging area.

### PR DESCRIPTION
**Pull request by cvlc12**
This allows microcode to be referenced first for UKIs and loader entries.

Simpler alternative to https://github.com/systemd/systemd/pull/27111, without the microcode detection script, which can be left for distributions for now. 

This was what the other PR originally was, before it became too complicated. I thought it better to open a new one for clarity.

### CODE REVIEW

**Comment by poettering** [comment]
umm, so for type2 entries (i.e. ukis) i'd really prefer if we'd treat microcode not just as "some initrd that needs to be placed first", but as a first class object we place in a special PE section, named `.microcode` and that sd-stub when booting then pastes together in the right order. This is in particular as sooner or later we want to cover bootconfig stuff too, which iirc is also just a special initrd that requires a special order to pasted.

now, that's type2, and here you care about type1 which is of course a different story. But this kinda suggests we should do similar handling here, mirroring the type1 logic. or in other words, I think we should have kernel-install spit out the microcode in a type1 .conf in a new stanza `microcode`, and we should have sd-boot honout it an merge if necessary.

**Comment by poettering** [comment]
so i think we can do this, but please rename the concept from "early-cpio" to just "microcode", because that paves the ground for later when we have a proper PE section for this. And it makes clear what this is for. It also allows us to later add "bootconfig" the same way, once the time comes without creating ambigituies what "early" now means.

Would love @keszybz's take on this though.

**Comment by behrmann** [comment]
This already went through some discussion in #27111 from which this is split out, some more context including from @keszybz  can be had there.

**Comment by poettering** [comment]
> I actually think it would be better to further differentiate microcode and initrd in loader entries:

Yeah, that would make a ton of sense to me. Are you volunteering? ;-)

**Comment by poettering** [comment]
this PR looks good to me. I think we should extend the type 1 spec with a "microcode" stanza, but that can happen in a different PR.

Before we merge this, I'd like input from @keszybz.

I genuinely believe that distinguishing microcode, from regular initrds, from bootconfig initrd makes a ton of sense, and we should follow this through in the entire stack. The kernel afterall distinguishes these three too.

**Comment by poettering** [comment]
actually this should come with docs, i.e. some addition to the kernel-install man page. 

admittedly the existing logic with looking for "initrd" in the staging dir isn't documented either anyway, but we should fix that at the same time. just add a short setence about this where 90-loaderentry.install is documented.

(btw, @keszybz the man page also lacks a description of 60-ukify.install where the other drop-ins we ship are described)

**Comment by keszybz** [comment]
We should add a test for this… But since this patch has no test, the CI is unlikely to tell us anything interesting, so I'll just merge this.

> I am unsure about how to check the output of the xml docs

Try `build/man/man kernel-install`

**Comment by behrmann** [comment]
> Shellcheck doesn't complain but I think this is how it should be.

Shellcheck doesn't complain because you're doing the good thing (in its eyes) of preventing unexpected expansion, which here is actually quite expected :) This should indeed be
```diff
-for initrd in "${KERNEL_INSTALL_STAGING_AREA}/microcode*" "${@}" "${KERNEL_INSTALL_STAGING_AREA}/initrd*"; do
+for initrd in "${KERNEL_INSTALL_STAGING_AREA}"/microcode* "${@}" "${KERNEL_INSTALL_STAGING_AREA}"/initrd*; do
```

**Pull request merged**
