### PR TITLE
Unified cgroups

### PR DESCRIPTION
**Pull request by xnox**
Implement basic unified cgroups support with cgroups.populated.

### CODE REVIEW

**Comment by teg** [comment]
Rather than making this a config option, would it not be better to make it behave the same everywhere and rather do a kernel cmdline switch to opt in/out?

**Comment by xnox** [comment]
Yes. I also dislike the behaviour I proposed above. Let me close this proposal and do another one a fresh, which will be much smaller.

**Comment by poettering** [comment]
Yes, I agree with @teg. This should not be a compile-time thing, this should be a runtime thing: we should use the unified hierarchy if this is enabled on the kernel cmdline with a new "systemd.unified-cgroup=1" switch or so. (I am open to making the default for this kerne cmdline switch configurable with a ./configure switch though).

**Comment by xnox** [comment]
i think systemd.unified-cgroup should accept optional arguments as to which controllers to be mounted as unified... since at the moment realistically only "name=systemd" and "mem" controllers can work on unified hieracrhy. The rest of controllers do not appear to have fields implementations for the unified hierarchy in the kernel. "old" fields are exposed on unified hierarchy only if a kernel cmdline option is present to do so "cgroup__DEVEL__legacy_files_on_dfl". I'm not sure if we should trigger on that when considering systemd.unified-cgroup.

**Comment by poettering** [comment]
@xnox the controllers shouldn't be configurable on the cmdline. Instead, we should only enable the controllers we need for each cgroup. (in fact that's kind what we do already in the classic hierarchy). That means unless people configure something specifically no controller will be used at all.

According to Tejun Heo the unified stuff is pretty much complete for all controllers now.

**Pull request closed without merging**
