### PR TITLE
network: add setting to support RA without DHCPv6 client

### LINKED ISSUE #13991: network: accept RA without DHCPv6 client
**systemd version the issue has been seen with**
> systemd 243 (243-4)
> systemd 241 (241)

**Used distribution**
 > Debian Sid (unsable) with systemd 243
 > Debian Buster 10.1 (stable) with systemd 241

**Expected behaviour you didn't see**
 > If explicitly disabled, DHCPv6 client should not start, even if some RA with MANAGED flag received.

**Unexpected behaviour you saw**
 > DHCPv6 client start 

**Steps to reproduce the problem**

```
[Match]
Name=ens18

[Network]
DHCP=no
```
```
Nov 10 15:01:43 networkd02 systemd-networkd[260]: NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 1800 sec
Nov 10 15:01:43 networkd02 systemd-networkd[260]: NDISC: Invoking callback for 'router' event.
Nov 10 15:01:43 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Started in Managed mode
Nov 10 15:01:43 networkd02 systemd-networkd[260]: ens18: Acquiring DHCPv6 lease on NDisc request
Nov 10 15:01:43 networkd02 systemd-networkd[260]: ens18: Configuring route: dst: n/a, src: n/a, gw: fe80::ce7:e6ff:feea:b6ad, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Nov 10 15:01:43 networkd02 systemd-networkd[260]: rtnl: received non-static neighbor, ignoring.
Nov 10 15:01:43 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Sent SOLICIT
Nov 10 15:01:43 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Next retransmission in 1s
Nov 10 15:01:43 networkd02 systemd-networkd[260]: ens18: Updating remembered route: dst: n/a, src: n/a, gw: fe80::ce7:e6ff:feea:b6ad, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Nov 10 15:01:43 networkd02 systemd-timesyncd[271]: Network configuration changed, trying to establish connection.
Nov 10 15:01:45 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Sent SOLICIT
Nov 10 15:01:45 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Next retransmission in 2s
Nov 10 15:01:47 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Sent SOLICIT
Nov 10 15:01:47 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Next retransmission in 4s
Nov 10 15:01:51 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Sent SOLICIT
Nov 10 15:01:51 networkd02 systemd-networkd[260]: DHCPv6 CLIENT: Next retransmission in 8s
```

Seems the same issue reported in #12324 
Currently, the DHCPv6 client of systemd-networkd still have some problematic issues, and we should be able to disable it completely (to be able to use an other DHCPv6 client)

### PR DESCRIPTION
**Pull request by yuwata**
Closes #13991.

### CODE REVIEW

**Comment by ssahani** [comment]
@yuwata if you interested working on issues please open the prs. You making conflicting prs which I want to avoid. Please don't do this further again m

**Comment by yuwata** [comment]
Oops. Sorry for that.

**Comment by ssahani** [comment]
The Rfc says that if we respect the ra then without m or O bit DHCPv6 should not start. I failed to understand why we should violate the rfc at all. The DHCPv6 client can Start on ores own.

**Comment by yuwata** [comment]
> The Rfc says that if we respect the ra then without m or O bit DHCPv6 should not start.

Right.

> I failed to understand why we should violate the rfc at all.

This PR does not violate the rfc.

**Comment by ssahani** [comment]
Then why we need the flags at all.

**Comment by yuwata** [comment]
We already have several `IPv6AcceptRA.UseXYZ=`. The setting introduced by this PR is a kind of such already existing settings. If it is true (the default), the managed or other information flag is honored and DHCPv6 client will start. If it is false, the flags are ignored.

**Comment by ssahani** [comment]
No when why even care about RA

**Comment by fluboi** [comment]
This new `IPv6AcceptRA.DHCPv6Client` settings is usefull: it provide the ability to use an other and independent DHCPv6 client (as dhclient or dibbler)

>No when why even care about RA

Because we need to learn the default route.

**Comment by ssahani** [comment]
> This new `IPv6AcceptRA.DHCPv6Client` settings is usefull: it provide the ability to use an other and independent DHCPv6 client (as dhclient or dibbler)
> 
> > No when why even care about RA
> 
> Because we need to learn the default route.

Yes right but without instructing managed flag we are starting the client .

**Comment by yuwata** [comment]
@ssahani What the final opinion about the PR? Can I set the green label?

**Comment by ssahani** [comment]
Yes please

**Comment by yuwata** [comment]
Thanks.

**Pull request merged**
