### PR TITLE
Retval fixes

### PR DESCRIPTION
**Pull request by sshedi**

### CODE REVIEW

**Comment by sshedi** [comment]
@yuwata Can you please help me with this simple PR? Are the CI/CD errors related to this change?

**Comment by mrc0mmand** [comment]
> @yuwata Can you please help me with this simple PR? Are the CI/CD errors related to this change?

Don't worry, neither of the CI errors are due to this change, Ubuntu/Debian based CI are now borked (see https://github.com/systemd/systemd/pull/23621#issuecomment-1146590591 and https://github.com/systemd/systemd/issues/23630).

**Comment by mrc0mmand** [comment]
@sshedi if you force-push this PR it should, hopefully, make all CIs green, as a fix has been merged (https://github.com/systemd/systemd/pull/23633).

**Comment by sshedi** [comment]
Thanks @mrc0mmand, I will rebase my change.

**Pull request merged**
