### PR TITLE
RLIMIT_MEMLOCK fixes

### PR DESCRIPTION
**Pull request by poettering**
An attempt to address #11386. It's not clear to me if this is all that's needed to fix the issue, but this change certainly is more correct that the status quo ante.

### CODE REVIEW

**Comment by tomty89** [comment]
@poettering unfortunately it doesn't fix #11386. Actually it kind of makes it worse. qemu still can't be started with vfio, now *both* jackd and mpv gives `cannot lock down memory for jackd (Cannot allocate memory)` when being started, and jackd gives two more of `JACK: unable to mlock() port buffers: Cannot allocate memory`.

**Comment by poettering** [comment]
@tomty89 are you sure pam_limit is in the PAM stack for systemd-user? i.e. that the "systemd --user" instances actually are invoked with the bumped limits?

With this patch systemd takes care that whatever rlimits are set when systemd --user is invoked is also what is passed on to user services. If those user services don't have things properly set up, then this now means that what systemd --user got passed in wasn't right either...

**Comment by poettering** [comment]
oh, hmm, i think i have an idea what might be going on, will prep a new version for you to test

**Comment by poettering** [comment]
I force pushed a new version. @tomty89 can you give this a whirl, please?

**Comment by tomty89** [comment]
@poettering same as your first push, unfortunately

**Comment by poettering** [comment]
@tomty89 then please provide the exacty contents of /etc/pam.d/systemd-user snippet you are using (please resolve the "include" lines in that, too if there are any). Please provide your /etc/security/limits.conf. Please also provide /proc/1/limits, as well as /proc/<systemd --user's PID>/limits. Finally provide "ulimit -aH" and "ulimit -aS" from a shell run as "systemd-run -t /bin/bash"  and from a shell run as "systemd-run -t --user /bin/bash".

**Comment by tomty89** [comment]
Files requested:
```
[tom@archlinux ~]$ cat /etc/pam.d/systemd-user 
# Used by systemd --user instances.

account  include system-login
session  required pam_loginuid.so
session  include system-login
[tom@archlinux ~]$ cat /etc/pam.d/system-login 
#%PAM-1.0

auth       required   pam_tally.so         onerr=succeed file=/var/log/faillog
auth       required   pam_shells.so
auth       requisite  pam_nologin.so
auth       include    system-auth

account    required   pam_access.so
account    required   pam_nologin.so
account    include    system-auth

password   include    system-auth

session    optional   pam_loginuid.so
session    optional   pam_keyinit.so       force revoke
session    include    system-auth
session    optional   pam_motd.so          motd=/etc/motd
session    optional   pam_mail.so          dir=/var/spool/mail standard quiet
-session   optional   pam_systemd.so
session    required   pam_env.so
[tom@archlinux ~]$ cat /etc/pam.d/system-auth 
#%PAM-1.0

auth      required  pam_unix.so     try_first_pass nullok
auth      optional  pam_permit.so
auth      required  pam_env.so

account   required  pam_unix.so
account   optional  pam_permit.so
account   required  pam_time.so

password  required  pam_unix.so     try_first_pass nullok sha512 shadow
password  optional  pam_permit.so

session   required  pam_limits.so
session   required  pam_unix.so
session   optional  pam_permit.so
[tom@archlinux ~]$ grep -v -E "^#|^$" /etc/security/limits.conf
[tom@archlinux ~]$ ls -A /etc/security/limits.d/
tom.conf
[tom@archlinux ~]$ cat /etc/security/limits.d/tom.conf 
tom - rtprio 99
tom - memlock unlimited
[tom@archlinux ~]$ 
```
Output requested (with second push of this PR):
```
[tom@archlinux ~]$ cat /proc/1/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             63312                63312                processes 
Max open files            1073741816           1073741816           files     
Max locked memory         67108864             67108864             bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       63312                63312                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
[tom@archlinux ~]$ pgrep -a -f 'systemd --user'
483 /usr/lib/systemd/systemd --user
[tom@archlinux ~]$ cat /proc/483/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             63312                63312                processes 
Max open files            524288               524288               files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       63312                63312                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     99                   99                   
Max realtime timeout      unlimited            unlimited            us        
[tom@archlinux ~]$ systemd-run -t /bin/bash
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
Authentication is required to manage system services or other units.
Authenticating as: tom
Password: 
==== AUTHENTICATION COMPLETE ====
Running as unit: run-u68.service
Press ^] three times within 1s to disconnect TTY.
[root@archlinux /]# ulimit -aH
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63312
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63312
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[root@archlinux /]# ulimit -aS
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63312
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63312
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[root@archlinux /]# Error on PTY forwarding logic: Operation canceled

[tom@archlinux ~]$ systemd-run -t --user /bin/bash
Running as unit: run-u11.service
Press ^] three times within 1s to disconnect TTY.
[tom@archlinux ~]$ ulimit -aH
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63312
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 99
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63312
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[tom@archlinux ~]$ ulimit -aS
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63312
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 99
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63312
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[tom@archlinux ~]$ Error on PTY forwarding logic: Operation canceled

[tom@archlinux ~]$ 
```
Output requested (fb4986f with a17c171 reverted):
```
[tom@archlinux ~]$ cat /proc/1/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             63312                63312                processes 
Max open files            1073741816           1073741816           files     
Max locked memory         67108864             67108864             bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       63312                63312                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
[tom@archlinux ~]$ pgrep -a -f 'systemd --user'
482 /usr/lib/systemd/systemd --user
[tom@archlinux ~]$ cat /proc/482/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             63312                63312                processes 
Max open files            1024                 524288               files     
Max locked memory         unlimited            unlimited            bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       63312                63312                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     99                   99                   
Max realtime timeout      unlimited            unlimited            us        
[tom@archlinux ~]$ systemd-run -t /bin/bash
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
Authentication is required to manage system services or other units.
Authenticating as: tom
Password: 
==== AUTHENTICATION COMPLETE ====
Running as unit: run-u32.service
Press ^] three times within 1s to disconnect TTY.
[root@archlinux /]# ulimit -aH
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63312
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63312
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[root@archlinux /]# ulimit -aS
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63312
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63312
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[root@archlinux /]# Error on PTY forwarding logic: Operation canceled

[tom@archlinux ~]$ systemd-run -t --user /bin/bash
Running as unit: run-u9.service
Press ^] three times within 1s to disconnect TTY.
[tom@archlinux ~]$ ulimit -aH
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63312
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 99
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63312
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[tom@archlinux ~]$ ulimit -aS
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63312
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 99
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63312
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[tom@archlinux ~]$ Error on PTY forwarding logic: Operation canceled

[tom@archlinux ~]$ 
```
[files.txt](https://github.com/systemd/systemd/files/2765712/files.txt)
[limits_secondpush.txt](https://github.com/systemd/systemd/files/2765714/limits_secondpush.txt)
[limits_nopush_reverted.txt](https://github.com/systemd/systemd/files/2765715/limits_nopush_reverted.txt)

**Comment by poettering** [comment]
I think I figured it out now. Our execution code calls into PAM first, and bumps the rlimits configured in systemd later, that's the key of the problem, as this means any rlimits configured through systemd trump those done via PAM.

**Comment by poettering** [comment]
@tomty89 i force pushed a new version now. Pretty confident this one works for you. Could you test?

**Comment by tomty89** [comment]
@poettering yes this one works, thanks a lot! :-D

**Comment by poettering** [comment]
Excellent, thanks!

**Comment by keszybz** [comment]
Looks all nice, even though I can't pretend to understand all the implications on other tools. But @tomty89 says it fixes the issue. Let's merge.

**Pull request merged**
