### PR TITLE
journald: bump log message buffer size to 64K

### PR DESCRIPTION
**Pull request by 4z3**
Fixes:

https://bugs.freedesktop.org/show_bug.cgi?id=86465

### CODE REVIEW

**Comment by poettering** [comment]
Well, I am fine with bumping the buffer size, but if we do that we should really do the same for all transports, and that means server_process_datagram() should probably use the same limit as we use for the streams.

Also, I am not a fan of unnecessary abbreviations. Please name this BUFFER_SIZE, not BUFSIZ.

**Comment by poettering** [comment]
hmm, the other thing i don't like is that allocating 64K just like that for each stream sounds quite wasteful. 4K was already a lot, but 64K sounds way to much to just allocate for each stream, as we may have many of those in parallel, and we are unlikely to ever use that much.

Hence, I figure the buffer should grow dynamically, and the 64K limit should just be a limit. GREEDY_REALLOC() makes it easier to have dynamically growing buffers.

**Comment by poettering** [comment]
Please grow the per-stream buffers dynamically using GREEDY_REALLOC, so that we don't waste such a large buffer for each stream

**Comment by vcaputo** [comment]
This is not a good idea given how journald is currently implemented.

The buffer size essentially sets the time-slice upper bound a given log stream event may consume, this isn't just about copying larger buffers at a time.

For every newline in the buffer, journald does a whole mountain of pointlessly redundant work interrogating the process metadata in /proc.  Even today, with the relatively tiny LINE_MAX buffer size, if you do something as minor as  `perl -e 'print("a\n"x2048)' | systemd-cat` on an otherwise idle system you'll see `systemd-journald` pin a CPU for a visible-in-top amount of time - that time is being spent in processing that buffer without running the event loop.

Imagine if the buffer were 64KiB in size.  A regular user would be able to produce disproportionate swaths of what's essentially an atomic chunk of work for journald depriving all other loggers from getting anything in for undesirable periods of time, essentially a DoS, with very little effort.

The metadata caching proposed in https://github.com/systemd/systemd/pull/2280 changed this to acquire the metadata on a per-buffer basis.

I wouldn't increase the buffer size until the amount of work done on behalf of the buffer no longer depends so greatly on its newline density.

**Comment by jerome-laforge** [comment]
> hmm, the other thing i don't like is that allocating 64K just like that for each stream sounds quite wasteful. 4K was already a lot, but 64K sounds way to much to just allocate for each stream, as we may have many of those in parallel, and we are unlikely to ever use that much.

According to you, is it possible to let the user configure this value into `/etc/systemd/journald.conf`?
And let the default value to 2K, 4K or something else.

**Comment by izzyblues** [comment]
I have the same issue. Long java log lines are split. Set a configuration parameter in `journald.conf` would be great.

**Comment by keszybz** [comment]
> I wouldn't increase the buffer size until the amount of work done on behalf of the buffer no longer depends so greatly on its newline density.

Agreed. journald is slow anyway, fixing this would help even non-malicious users.

**Comment by towolf** [comment]
It's terrible that this is still unsolved.

Same with the journal race and /proc spamming.

**Comment by keszybz** [comment]
Somebody needs to work through the problem and prep a patch ;)

**Comment by poettering** [comment]
I have prepared a patch now implemented the suggested logic and more. Let's close this PR and follow up in #6838.

**Pull request closed without merging**
