### PR TITLE
sysusers: flush nscd's caches whenever /etc/{passwd,group} are modified

### PR DESCRIPTION
**Pull request by fbuihuu**

### CODE REVIEW

**Comment by floppym** [comment]
The nscd man page says that nscd will do this automatically.

**Comment by poettering** [comment]
Yeah, that's what the nscd man page says. I guess we can just close this, no?

**Comment by fbuihuu** [comment]
Well did you read the "NOTES" section ?

**Comment by fbuihuu** [comment]
Also the inotify mechanism seems racy since I don't think there's any guaranty that nscd will be notified before if a request comes rgith after the database has been changed by systemd-sysusers.

**Comment by fbuihuu** [comment]
BTW at least the patch helped here to make the following test case work:

`./systemd-sysusers --inline 'u foo - "foo daemon"'; getent passwd foo; getent group foo`

**Comment by floppym** [comment]
That test works fine without this patch on my system, though I suppose it might be racy.

It is probably pointless to flush the cache if the account is being added in an alternate root (`systemd-sysusers --root=/foo`).

**Comment by poettering** [comment]
so the command line @fbuihuu is something that probably should work, and given how minimal the patch is it is probably OK to go in (even though nscd is apparently in the process of being obsoleted upstream, fedora already has a feature for that). But @floppym is right, this should be conditionalized on arg_root/arg_image being NULL

**Comment by fbuihuu** [comment]
Patch updated so it only flushes the cache when --root=/--image are not passed.

**Comment by yuwata** [comment]
LGTM.

**Pull request merged**
