### PR TITLE
three image dissection fixes

### PR DESCRIPTION
**Pull request by poettering**
This fixes nspawn's --volatile=yes logic

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

**Review by bluca — APPROVED** [review]
lgtm too

**Comment by bluca** [comment]
I'll review the other dissect PR today, after I finish some firefighting

**Comment by keszybz** [comment]
bionic-i386: `TEST-17-UDEV:                       FAIL     (184 s)`. Probably unrelated.

**Pull request merged**
