### PR TITLE
Using lz4 frame api for coredump files

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
Looks great otherwise. Though I wonder if we shouldn't be more drastic here, and stop supporting the old format, after all it was never really supported and the big distros didn't enable it anyway, and I am not sure we should keep the cruft around for good... In particular as crashdumps are not the most precious of data, and we age them away using tmpfiles aging anyway... Hence, if people lose access to old coredumps once when we make the switch, or only after 3d (after which tmpfiles deletes them anyway) isn't that big of a difference.

**Comment by keszybz** [comment]
> use "log_debug()" followed by a "return -EFBIG", instead of a log_debug_errno().

Fixed. I found another bug with error handling in the old code.

> MMAP_FAILED

That's embarrassing. Fixed.

> Though I wonder if we shouldn't be more drastic here, and stop supporting the old format, after all it was never really supported and the big distros didn't enable it anyway, and I am not sure we should keep the cruft around for good...

I think it can be useful for people supporting both versions, especially when trying to debug failures with the version switch... What about removing it after one release? I'd prepare the pull request now and leave it to a merged later.

**Comment by keszybz** [comment]
Also, after this gets some more testing, it would be nice to switch to lz4 being the default. Should give a nice boost to journal efficiency.

**Comment by poettering** [comment]
> I think it can be useful for people supporting both versions, especially when trying to debug failures with the version switch... What about removing it after one release? I'd prepare the pull request now and leave it to a merged later.

Sounds like a fair compromise.

> Also, after this gets some more testing, it would be nice to switch to lz4 being the default. Should give a nice boost to journal efficiency.

I'd be fine with switching this over right-away.

**Comment by keszybz** [comment]
OK, so let's not merge this yet. I'll add the switch.

**Pull request merged**
