### PR TITLE
macro: introduce FOREACH_ARRAY() macro

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by yuwata** [comment]
@YHNdnzj After reconsidering the foreach macro you are trying to introduce in edit-util, I introduced more generic `FOREACH_ARRAY()` macro. If you'd like, please take a look.

**Comment by yuwata** [comment]
The packit failures are unrelated.

**Comment by YHNdnzj** [comment]
This is nice to have, thanks!

**Comment by keszybz** [comment]
Looks reasonable.

**Pull request merged**
