### PR TITLE
Enable some more debug logging for transaction building

### PR DESCRIPTION
**Pull request by bl33pbl0p**
This uncomments some stuff, and makes it unit specific.

### CODE REVIEW

**Comment by poettering** [comment]
doesn't compile...

also, is this really necessary? this was commented but left in the code because it makes debug logging a bit too chatty for the average debugging admin...

**Comment by bl33pbl0p** [comment]
It helped a bit pinning down #11440 and #11338 but I only enabled one of these for them. Looks like enabling all makes for a case where the job object gets freed but it tries to log about, causing a segfault.

I can look into where that happens, but if this isn't desirable at all, then I'll close this.

**Comment by poettering** [comment]
i think merging a fix that makes these lines when commented in not segfault would certainly make a ton of sense. but actually uncommenting them I am not so sure.

**Comment by bl33pbl0p** [comment]
It now compiles and works correctly on my local test setup. Let's see what CI says.

**Comment by keszybz** [comment]
Please make this `log_trace`. It can then be enabled during compilation with `-Dlog-trace=true`.

**Comment by bl33pbl0p** [comment]
Done.

**Pull request merged**
