### PR TITLE
units: do not perform m4 if not necessary

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by mbiebl** [comment]
This will need a corresponding change in Makefile.am or is it already settled that autotools will be dropped for v235?

/cc @keszybz , @poettering

**Comment by mbiebl** [comment]
While looking at it: is there a reason why console-getty.service.m4.in and container-getty@.service.m4.in are .in files? We don't do any variable substitutions in those...

**Comment by keszybz** [comment]
@mbiebl it's already gone, see #6266.

LGTM.

**Comment by keszybz** [comment]
If we have further cleanups, let's do them in separate patches.

(I'd actually consider replacing our m4 and sed pipeline with a more modern template engine that would do both things in one step and use a less cryptic syntax.)

**Comment by mbiebl** [comment]
> @mbiebl it's already gone, see #6266.

Oops, somehow I completely missed that this already landed. Sorry for the noise then.

+1 on the idea to replace m4+sed! I guess this would be python based?

**Pull request merged**
