### PR TITLE
elf-util: don't double parse binaries with no package metadata.

### PR DESCRIPTION
**Pull request by Romain-Geissler-1A**
This is a preliminary change forseeing a future of the elf parsing logic around the package metadata retrieval. The idea is to accept binaries with no package metadata at all if we would correctly parse them without ignoring error, so there is no need to call any fallback mechanism to try to parse it and resulting in an unnecessary double parse of binaries.

cc @bluca

My goal is that in a follow pull request (unless you want me to do this in this pull request, either in one or two commit) to invert the parsing logic for the package metadata retrieval. Indeed I would like to first look in the (potentially incomplete) elf/program headers found only in the core dump, then only fallback to using libelfutils to retrieve the module binary and try to fetch it. Why ? Because by using libelfutils first, it tries to access the filesystem and potentially do remote HTTP calls (if some debuginfod urls are set), cf https://sourceware.org/pipermail/elfutils-devel/2023q2/006256.html, while according to https://systemd.io/ELF_PACKAGE_METADATA/ the whole point of this section is to avoid network access as much as possible. I have also the hope that this may parse cores a bit faster if considering only the core file itself if possible.

Doing some tests (which two additional log_notice added for debugging) on my reproducer from #28093 I have this result:

```
[root@d2426cc17274 systemd]# rm -rf /var/lib/systemd/coredump/* && journalctl --flush --rotate && journalctl --vacuum-time=1s && cat the-core | build/systemd-coredump $$ 0 0 11 1687360485 1000000000000000 localhost && journalctl
Vacuuming done, freed 0B of archived journals from /run/log/journal.
Vacuuming done, freed 0B of archived journals from /var/log/journal.
Deleted archived journal /var/log/journal/023dff7f5ff0462aae79588e46763ce8/system@db47e225115d4148ad1f6c987a6a3e7c-000000000000120e-0005feb4a41be92d.journal (3.5M).
Vacuuming done, freed 3.5M of archived journals from /var/log/journal/023dff7f5ff0462aae79588e46763ce8.
Jun 22 09:43:26 d2426cc17274 systemd-journald[24]: System Journal (/var/log/journal/023dff7f5ff0462aae79588e46763ce8) is 16.0M, max 2.3G, 2.3G free.
Jun 22 09:43:26 d2426cc17274 systemd-coredump[7664]: Due to PID 1 having crashed coredump collection will now be turned off.
Jun 22 09:43:26 d2426cc17274 (sd-parse-elf)[7665]: parse_package_metadata for object /usr/bin/sleep from libelf library: 1
Jun 22 09:43:26 d2426cc17274 (sd-parse-elf)[7665]: parse_package_metadata for object /usr/lib64/libtinfo.so.6.3 extracted from the core itself: 1
Jun 22 09:43:26 d2426cc17274 (sd-parse-elf)[7665]: parse_package_metadata for object /usr/lib64/libc.so.6 extracted from the core itself: 1
Jun 22 09:43:26 d2426cc17274 (sd-parse-elf)[7665]: parse_package_metadata for object /usr/lib64/libreadline.so.8.2 extracted from the core itself: 1
Jun 22 09:43:26 d2426cc17274 (sd-parse-elf)[7665]: parse_package_metadata for object /usr/lib64/ld-linux-x86-64.so.2 extracted from the core itself: 1
Jun 22 09:43:26 d2426cc17274 (sd-parse-elf)[7665]: parse_package_metadata for object linux-vdso.so.1 from libelf library: 1
Jun 22 09:43:26 d2426cc17274 systemd-coredump[7664]: [🡕] Process 59 (bash) of user 0 dumped core.
                                                     
                                                     Module /usr/bin/sleep from rpm bash-5.2.15-3.fc38.x86_64
                                                     Module /usr/lib64/libtinfo.so.6.3 from rpm ncurses-6.3-5.20220501.fc37.x86_64
                                                     Module /usr/lib64/libreadline.so.8.2 from rpm readline-8.2-2.fc37.x86_64
```

### CODE REVIEW

**Comment by bluca** [comment]
> This is a preliminary change forseeing a future of the elf parsing logic around the package metadata retrieval. The idea is to accept binaries with no package metadata at all if we would correctly parse them without ignoring error, so there is no need to call any fallback mechanism to try to parse it and resulting in an unnecessary double parse of binaries.

The binary might have changed and lost the metadata, but the core file might still have it, so we should check the core even if a binary is found

**Comment by bluca** [comment]
> > The binary might have changed and lost the metadata, but the core file might still have it, so we should check the core even if a binary is found
> 
> And if in the same commit I also invert the parsing logic (first checking the core, then checking the binary itself), should I also consider that if the core doesn't have it (ie we could find all notes and none of them were .note.package), then maybe the binary has it, or we can assume for sure the binary also doesn't have it ?

I'm not sure how the core creation failure modes look like - if it is possible that the kernel creates a partial/truncated core that is missing those sections, but still partially usable as a core file

**Comment by Romain-Geissler-1A** [comment]
My understanding (but I may be wrong) is that the kernel will always dump the very first page (even if not modified) of any file-backed mapping. And on the other side, linkers try their best to fit the elf headers + program headers + note sections in the first page of the elf file as much as possible. Exactly so that in most scenarios, the core file alone is enough to uniquely identify all binaries participating in the process as it crashed, and the debugger doesn't have to "guess" just based on filesystem paths.

However you seemed to imply in your first message that the elf file mapped in memory might actually be different from the one returned by libelfutils (ie in one case it would have a .note.package section, while in the other case it might not have it). In this proposal in its current shape, I don't consider this is possible. And I considered that if we could properly parse the elf file , looking for all notes, and didn't see any .note.package section and didn't have to error while iterating program header/notes, then we assume the binary has no package metadata (we are sure of it), and thus there is no need to try to use a fallback method.

I propose this as for example most C/C++ binaries in our company don't have .note.package section, we use only buildids for now and that is enough for us. In this case if we are sure there is no .note.package section during the first attempt, there is no need to try a fallback method.

**Comment by bluca** [comment]
the binary might change in the time the core is being picked up to be processed, so it needs to be robust against that scenario

**Comment by Romain-Geissler-1A** [comment]
Ok, in that case this whole proposed change makes no sense (maybe except the first change consisting in returning 1 if this module was already visited). I will decline this pull request (and directly propose another one inverting the elf parsing logic)

**Pull request closed without merging**
