### PR TITLE
chase-symlinks fixes

### PR DESCRIPTION
**Pull request by daandemeyer**

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
Sorry for being late. Some notes:

> - Whether we should return an absolute path or not is irrelevant
> to whether CHASE_AT_RESOLVE_IN_ROOT is set. We should only return
> an absolute path if we are provided one and the directory file
> descriptor is AT_FDCWD

Hmm, not sure I follow? Originally chase_symlinks() started as a more generic reimplementation of canonicalize_file_name(). Among other things it is able to convert relative paths to absolute ones, based on the cwd. As I understand the above you are departing from that now? 

I would assume we use chase_symlinks() at places to canonicalize relative paths. Are you sure we never do that?

**Comment by DaanDeMeyer** [comment]
> Hmm, not sure I follow? Originally chase_symlinks() started as a more generic reimplementation of canonicalize_file_name(). Among other things it is able to convert relative paths to absolute ones, based on the cwd. As I understand the above you are departing from that now?

In chase_symlinks(), we always return an absolute path. In chase_symlinks_at(), we don't because if we're working on a directory fd because in most cases it won't make sense since all openat() like functions will ignore the directory fd if an absolute path is passed.

> I must admit I don't grok chase_symlinks() anymore. For example, what am I missing, if i have a directory hierarchy whose top-level dir i have in "root_fd", and a directory inode somewhere inside it, called "dir_fd", and now i want to use dir_fd as basis for resolving a path "foo/bar", but never leave "root_fd", how would i do that?

This isn't exactly trivial to achieve, which is probably why openat2() doesn't support it either. The current version of chase_symlinks() is more or less a copy of the openat2() API. We could add support for separate dir_fd and root_fd, but it would mean adding logic to check if one dir_fd is inside another. If we have that, we could keep a stat of the root fd around and compare against that to check if we've reached the top I suppose.

**Comment by poettering** [comment]
hmm, so we never so far had a usecase for a separate dir_fd/root_fd? (i mean, if we don't i'll accept that and we shouldn't complicate things)

**Comment by DaanDeMeyer** [comment]
> hmm, so we never so far had a usecase for a separate dir_fd/root_fd? (i mean, if we don't i'll accept that and we shouldn't complicate things)

We haven't so far but if we really want to lean into directory fds we might want it I guess. I'll see how hard it is to add it.

**Pull request merged**
