### PR TITLE
clang-format all test source files

### PR DESCRIPTION
**Pull request by igo95862**
Makes it easier to develop new tests as running clang format
on newly developed test won't cause other parts of file get
reformatted.

If some parts are not supposed to be formatted it is possible to add `/* clang-format off */` `/* clang-format on */` comments to disable formatting for certain areas.

See #23703

### CODE REVIEW

**Comment by evverx** [comment]
I think the following comment
https://github.com/systemd/systemd/blob/5932c870004fbcb3c25ca3fceb92b640f3406c88/.clang-format#L1-L5
was included in `.clang-format` for a reason.

Other than that as discussed back in 2018 in https://github.com/systemd/systemd/pull/11254#issuecomment-450481407 I don't think it makes much sense to keep it unless it can be safely applied automatically. I'm not sure why `.clang-format` was added in the first place. Judging by the state of the codebase it doesn't seem to be used at all.

**Comment by igo95862** [comment]
I feel like test source are more of the write once and forget so auto formatting would be more appropriate.

The reason why I created this PR is #23702 . I usually write some code out of style and when press auto-format. But because the files would be reformatted far beyond where I added code it would force me to use `git add --patch` and spend a lot more time.

**Comment by evverx** [comment]
> I feel like test sources are more of the write once and forget so auto formatting would be more appropriate.

The tests get updated to cover new features, to make sure that old bugs can't make it to the repository again and so on. If they were formatted with `.clang-format` they wouldn't be consistent with the rest of the codebase and I don't think it's ideal given that the idea behind auto-formatting in general is to make code consistent and to make it easier for everyone (including CI) to follow style guides automatically.

> The reason why I created this PR is https://github.com/systemd/systemd/pull/23702 . I usually write some code out of style and when press auto-format. But because the files would be reformatted far beyond where I added code it would force me to use git add --patch and spend a lot more time.

I agree it would be great if it was possible to auto-format the code but unfortunately `.clang-format` in its current form can't be used for that.

Just to clarify I'm not opposed to the idea in general and I think it makes sense to use tools like that when it's possible (for example I don't think I have ever seen rust or go projects that haven't been auto-formatted or where the standard guidelines haven't been imposed by their CI). It's just that `systemd` can't be covered by `.clang-format` and maybe it would make sense to remove it so as not to confuse contributors. As far as I understand it isn't actually used.

**Comment by igo95862** [comment]
> in its current form can't be used for that.

Is there a list of issues with clang format?

For example, I found that clang format wants to sort imports but some systemd headers depend on custom order. I made a pull request to disable include sorting: #23891

**Comment by evverx** [comment]
> Is there a list of issues with clang format?

I'm not sure. I think some of them might have probably been mentioned in the PR where `.clang-format` was introduced (along with that comment).

I think the easiest way would be to try to reformat `systemd` and compare the result with "CODING_STYLE".

**Comment by evverx** [comment]
@keszybz looking at https://github.com/systemd/systemd/commit/f3a604e4cf84f00a595aceca6c3e78fd03de652d I still have no idea why it was merged. If it should be kept for some reason I wonder if it would make sense to move it to `tools` (as was suggested in https://github.com/systemd/systemd/issues/15415#issuecomment-613418940) so that editors wouldn't pick it up automatically?

**Comment by igo95862** [comment]
> > I feel like test sources are more of the write once and forget so auto formatting would be more appropriate.
> 
> No, not at all.

The reason why I thought that is because there was a big lack of comments and poor variable names in the test files. (at least in the files that I worked with)

**Comment by igo95862** [comment]
@keszybz I think I will close it for now.

Once the #23702 gets resolved. I think I will revisit formatting the file that I worked on. Maybe look in to improving the clang format file to better fit the project formatting code. (the #23891 already has the clang format improvements)

**Pull request closed without merging**
