### PR TITLE
build-system: build the fuzz targets with both ASan and UBSan

### PR DESCRIPTION
**Pull request by evverx**
This is supposed to be a follow-up to https://github.com/systemd/systemd/pull/15860

### CODE REVIEW

**Comment by evverx** [comment]
Judging by https://travis-ci.org/github/systemd/systemd/jobs/689173150, Travis CI was able to catch https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19446 so it seems to be working:
```
--- command ---
09:52:23 UBSAN_OPTIONS='print_stacktrace=1:print_summary=1:halt_on_error=1' /usr/bin/env /build/build/fuzz-bus-message:address,undefined /build/test/fuzz/fuzz-bus-message/oss-fuzz-19446
--- stdout ---
/build/test/fuzz/fuzz-bus-message/oss-fuzz-19446... 
--- stderr ---
Found container virtualization docker.
open("/sys/firmware/efi/efivars/SystemdOptions-8cf2644b-4b0b-428f-9387-6d876050dc67") failed: No such file or directory
../../../../src/libsystemd/sd-bus/bus-message.c:3086:35: runtime error: addition of unsigned offset to 0x603000000050 overflowed to 0x60300000004f
    #0 0x7f19ca6255e8 in buffer_peek /build/build/test/fuzz/sanitize-address-undefined-fuzzers/../../../../src/libsystemd/sd-bus/bus-message.c:3086:35
    #1 0x7f19ca60fed3 in message_peek_fields /build/build/test/fuzz/sanitize-address-undefined-fuzzers/../../../../src/libsystemd/sd-bus/bus-message.c:4850:16
    #2 0x7f19ca5b88c5 in bus_message_parse_fields /build/build/test/fuzz/sanitize-address-undefined-fuzzers/../../../../src/libsystemd/sd-bus/bus-message.c:5212:29
    #3 0x7f19ca5b6c8f in bus_message_from_malloc /build/build/test/fuzz/sanitize-address-undefined-fuzzers/../../../../src/libsystemd/sd-bus/bus-message.c:571:13
    #4 0x4c5ead in LLVMFuzzerTestOneInput /build/build/test/fuzz/sanitize-address-undefined-fuzzers/../../../../src/fuzz/fuzz-bus-message.c:30:13
    #5 0x4c6bcd in main /build/build/test/fuzz/sanitize-address-undefined-fuzzers/../../../../src/fuzz/fuzz-main.c:39:29
    #6 0x7f19c961ae0a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26e0a)
    #7 0x41e409 in _start (/build/build/test/fuzz/sanitize-address-undefined-fuzzers/fuzz-bus-message+0x41e409)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../../../src/libsystemd/sd-bus/bus-message.c:3086:35 in 
------
```

**Comment by mrc0mmand** [comment]
I wonder why it doesn't crash with gcc's UBsan (like in the *Arch in KVM* job and Travis' gcc one):
```
513/760 fuzz-bus-message:oss-fuzz-19446:address,undefined                                           OK             0.13s

--- command ---
10:31:03 UBSAN_OPTIONS='print_stacktrace=1:print_summary=1:halt_on_error=1' /usr/bin/env /systemd-meson-build/fuzz-bus-message:address,undefined /build/test/fuzz/fuzz-bus-message/oss-fuzz-19446
--- stdout ---
/build/test/fuzz/fuzz-bus-message/oss-fuzz-19446... ok
--- stderr ---
Found container virtualization none.
open("/sys/firmware/efi/efivars/SystemdOptions-8cf2644b-4b0b-428f-9387-6d876050dc67") failed: No such file or directory
```

(Also, this change effectively disables regression fuzzers on CentOS 7, since its gcc doesn't support UBsan, but that's not a big deal, I guess)

**Comment by evverx** [comment]
`gcc` usually lags behind `clang` when it comes to the sanitizers. Looking at https://gcc.gnu.org/bugzilla//show_bug.cgi?id=80998, I suspect `gcc` simply doesn't instrument something that `clang` instruments.

> this change effectively disables regression fuzzers on CentOS 7, since its gcc doesn't support UBsan, but that's not a big deal, I guess

Another option would be to build the fuzz targets with UBsan as an additional step or maybe fall back to just ASan if UBsan isn't supported. It's doable but I'm not sure it's worth it.

**Comment by keszybz** [comment]
This should be OK to merge (maybe as "squash-and-rebase" to get rid of the first commit).

**Comment by evverx** [comment]
I rebased the branch on top of master and added one more commit where I turned on the pointer overflow on Fuzzit.

**Comment by mrc0mmand** [comment]
@evverx I wouldn't bother, to be honest, other CIs handle the coverage much better already.

**Comment by mrc0mmand** [comment]
I filed the gcc issue from https://github.com/systemd/systemd/pull/15865#issuecomment-631434623 as https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95279 (cc @evverx).

**Pull request merged**
