### PR TITLE
udev: inherit mac address for bridge or vlan interface from physical interface

### PR DESCRIPTION
**Pull request by yuwata**
Closes https://bugzilla.suse.com/show_bug.cgi?id=1136600.

### CODE REVIEW

**Comment by yuwata** [comment]
For bridge or vlan, `NamePolicy=` setting seems not necessary. I will rework on this.

**Comment by keszybz** [comment]
Oh, I wrote a long comment, but it got lost because of a network issue. I hate when that happens.

As you say, vlan devices are not affected by this change. We already ignore devices where the MAC address is set based on another device. For a vlan device:
```console
$ SYSTEMD_LOG_LEVEL=debug udevadm test-builtin net_setup_link /sys/class/net/br1.1
...
br1.1: Failed to query name_assign_type: Invalid argument
br1.1: Policies didn't yield a name and Name= is not given, not renaming.
br1.1: Device has addr_assign_type=2
br1.1: MAC on the device already set based on another device
...
```

So this is just about devices which enslave other devices but can/are created without any enslaved devices. The change in behaviour is that before those devices would first get a random MAC address, and then it would be changed by the kernel to the MAC address of the first enslaved device, now they get a stable MAC address that does not change. This new behaviour is much better than the old. It solves two problems: the first is that the config of the bridge device was tied to specific enslaved devices and removing or replacing those enslaved devices would sometimes change the bridge config. The second is that using the first enslaved device is inherently racy. We probe and enslave devices in parallel. People like to think about bootup as a fixed sequence, but it's not. So after looking at this, I'm pretty sure that we want to keep current behaviour.

I understand that the bug reporter was surprised by the change. But it was announced in NEWS. They are running a rolling distribution, so they need to be prepared for occasional changes when major components are upgraded. My proposal is to close this as NOTABUG, and to recommend the approach in your patch to those people who want to configure previous behaviour locally. We should also retroactively add a more verbose explanation of this issue to NEWS.

**Comment by yuwata** [comment]
@keszybz Thank you for your comment. That make sense for me. Now I dropped the new .link file and add a HINT in NEWS file. PTAL.

**Comment by keszybz** [comment]
Yup, thanks!

**Pull request merged**
