### PR TITLE
networkd-dhcp6: DHCPv6 starting fixes

### PR DESCRIPTION
**Pull request by tomty89**
Rewriting dhcp6_request_address() a bit to make DHCPv6 starting/triggering more proper and general. It should make implementing #3399 easier.

### CODE REVIEW

**Comment by tomty89** [comment]
@teg, Adding a patch with the DHCPv6 start code for NDISC timeout removed.

Btw, please be noted that this PR is NOT changing any policy/behavior in networkd on how it deals with DHCPv6 (well except this change in the NDISC timeout case that has just been added).

It is the CURRENT behavior that networkd will start DHCPv6 in stateless mode when explicitly enabled and will restart in stateful mode (or not) as per the RA flags. This behavior is maintained and I have no intention to change it unless we've come to a decent conclusion in #3399 (even when you mentioned that we should not let the RA flags interfere when DHCPv6 is enabled explicitly).

It is more of a follow-up PR inspired by #3304.

**Comment by teg** [comment]
Overall looks good. Though, not sure we want to switch the the requst type back and forth in case we receive inconsistent RAs. That would be a configuartion error, but I think we would be better off handling this by something like: if at least one RA with the M flag set, always request an address, otherwise only request the info. So we can "upgrade" from info to lease, but not the other way. Does that make sense?

Any idea what is up with the ubuntu tests?

**Comment by teg** [comment]
Gah, you already addressed that in your comment. Yeah, it is fine to keep this behavior for now, we can change it separately. So once the CI is happy we can merge this.

**Comment by martinpitt** [comment]
@teg: "Any idea what is up with the ubuntu tests?" → yes, this was fallout from a different PR that got merged with regressions. I did the necessary updates and retried all other PRs (just retried this one, it's the last one)

**Pull request merged**
