### PR TITLE
{core, login}: respect install_sysconfdir_samples in meson file

### PR DESCRIPTION
**Pull request by andir**
The refactoring done in e11a25cadbe caused the configuration files to be
installed into the pkgsysconfdir regardless of the state of the
install_sysconfdir_samples boolean that indicates whether or not the
sample files should be installed.

### CODE REVIEW

**Comment by andir** [comment]
@keszybz / @yuwata any chance you could have a look at this?

**Review by keszybz — COMMENTED** [review]
In general, we always define targets, even if they are not needed, so that a) we verify the dependencies even if something is not built, b) we can build a file "on demand", by invoking the appropriate ninja command. Please just fold this into the `install:` setting in the target.

**Comment by keszybz** [comment]
CentOS CI (Arch Linux) failed, but I don't see why. If the others pass, let's merge.

**Comment by andir** [comment]
> CentOS CI (Arch Linux) failed, but I don't see why. If the others pass, let's merge.

Looks good now. That might have been because I initially pushed a revision with a typo and the force-pushed a fixed version. Perhaps some of the CI systems don't cancel running builds / don't discard the old state when the PR updates (immediately)?

**Pull request merged**
