### PR TITLE
Protect clock

### PR DESCRIPTION
**Pull request by kkuehlz**

### CODE REVIEW

**Comment by yuwata** [comment]
Please also update docs/TRANSIENT-SETTINGS.md.

**Comment by poettering** [comment]
Excellent! Tried hard to find something to complain about, but couldn't find anything. @keur, awesome work!

**Comment by keur** [comment]
Thanks! We can add tests for this, but I'll add them after https://github.com/systemd/systemd/issues/14548 is worked out.

**Comment by poettering** [comment]
A test would be great. And so would be a follow-up patch that turns this option on for all our long-running services where that makes sense!

**Pull request merged**
