### PR TITLE
units: don't install dbus-org.freedesktop.oom1.service alias

### PR DESCRIPTION
**Pull request by mbiebl**
The systemd-oomd.service unit contains
```
[Install]
WantedBy=multi-user.target
Alias=dbus-org.freedesktop.oom1.service
```
which means the symlink is supposed to be created dynamically when the
service is enabled.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Hmm, this goes against the original PR https://github.com/systemd/systemd/pull/19276 - I wonder which one is the correct one in this case.

**Comment by mbiebl** [comment]
> Hmm, this goes against the original PR #19276 - I wonder which one is the correct one in this case.

If systemd-oomd is supposed to be a service which can be enabled/disabled (which judging by the `[Install]` section, it is), then I think this PR is correct.
Maybe #18469 could be fixed by running `systemctl enable systemd-oomd.service` if it needs D-Bus activation?

**Comment by mbiebl** [comment]
```
diff --git a/test/units/testsuite-55.sh b/test/units/testsuite-55.sh
index 379ea9e..d1e740a 100755
--- a/test/units/testsuite-55.sh
+++ b/test/units/testsuite-55.sh
@@ -29,6 +29,10 @@ echo -e "[Service]\nEnvironment=SYSTEMD_LOG_LEVEL=debug" >/etc/systemd/system/sy
 
 systemctl daemon-reload
 
+# enable the service to ensure dbus-org.freedesktop.oom1.service exists
+# and D-Bus activation works
+systemctl enable systemd-oomd.service
+
 # if oomd is already running for some reasons, then restart it to make sure the above settings to be applied
 if systemctl is-active systemd-oomd.service; then
     systemctl restart systemd-oomd.service
```
@mrc0mmand , @anitazha WDYT?

**Review by yuwata — APPROVED** [review]
LGTM.

**Review by mrc0mmand — APPROVED** [review]
LGTM too.

**Review by bluca — APPROVED** [review]

**Comment by keszybz** [comment]
LGTM too.

**Pull request merged**
