### PR TITLE
networkd: consider any uevent other than "remove" sufficient for the …

### PR DESCRIPTION
**Pull request by poettering**
…network device to be ready

### CODE REVIEW

**Comment by poettering** [comment]
Split out of #11138.

**Review by yuwata — COMMENTED** [review]
Could you also update the debug log message at line 233?
`Ignoring udev ADD event for device` -> `Ignoring udev %s event for device`

**Comment by mrc0mmand** [comment]
The CentOS CI fail is https://github.com/systemd/systemd/issues/16858.

**Comment by poettering** [comment]
Force pushed a new version, with the requested change! PTAL!

**Comment by yuwata** [comment]
Thanks. LGTM.

**Comment by keszybz** [comment]
centosci (arch in kvm with sanitizers) failed with
```
17:32:09 242/786 test-repart                                                                                 FAIL           1.66s (exit status 1)
```
This is tracked elsewhere.

**Pull request merged**
