### PR TITLE
Add accel mount matrix for BayTrail-based tablets by DEXP

### PR DESCRIPTION
**Pull request by RussianNeuroMancer**
This commit adds accel mount matrix for DEXP Ursus 10XW and Z110/Z110i tablets. In current state (svn and pn fields) it will apply to many (if not almost all) BayTrail-based tablets with Windows by DEXP (with same DMI strings) but this expected to cause no (or very little) harm as this devices is mostly very similar with slight differences.

However, if correction of this quirk becomes necessary in the future, BIOS Release Date (all other fields from dmidecode output is too generic or not filled) could be used to distinguish this two tablets from other tablets by DEXP.

DEXP Ursus 10XW: 12/26/2014 (https://pastebin.com/z50q2Zx8)
DEXP Ursus Z110i Apollo: 03/14/2015 (https://pastebin.com/SbnY4j7e)

(As you can see, only useful field here is BIOS Release Date.)

### CODE REVIEW

**Comment by poettering** [comment]
hmm, referencing pastebin.com urls in the commit msg isn't a good idea given that they tend to go away quickly. Any chance you just paste the relevant bits into the commit msg instead?

**Comment by RussianNeuroMancer** [comment]
> Any chance you just paste the relevant bits into the commit msg instead?

Sure, I corrected this. Please check new commit dsecription.

**Comment by poettering** [comment]
Hmm, any chance you can add the string in /sys/class/dmi/id/uevent in full in the commit msg? It's just one string but contains the all data one might ever want to know

**Comment by RussianNeuroMancer** [comment]
> Hmm, any chance you can add the string in /sys/class/dmi/id/uevent in full in the commit msg? It's just one string but contains the all data one might ever want to know

Good idea! I included it in commit description.

**Pull request merged**
