### PR TITLE
core: use the right job modes when queueing shutdown jobs on SIGRTMIN+X

### PR DESCRIPTION
**Pull request by poettering**
When shutting down we need to use JOB_REPLACE_IRREVERSABLY. We do that
pretty much everywhere else, hence let's do the same for SIGRTMIN+X
handling as well.

Also add brief explanations for the precise job modes picked.

Fixes: #6484

### CODE REVIEW

**Comment by sourcejedi** [comment]
FWIW I had a <del>similar patch written</del> patch in progress which included similar changes, among others.  My only criticism of this one, is how it justifies in comments, something that IMO needs to be surfaced in the docs.

I favoured isolate for default.target only because it was simpler than

1. showing the difference in the docs between SIGRTMIN+0 and +1/2, in a way which the eye will not simply skip over
2. answering the question "Why does SIGRTMIN+0 behave differently to `systemctl default`?".

```
diff a/man/systemd.xml b/man/systemd.xml
--- a/man/systemd.xml
+++ b/man/systemd.xml
@@ -634,7 +635,7 @@
 
         <listitem><para>Enters default mode, starts the
         <filename>default.target</filename> unit. This is mostly
-        equivalent to <command>systemctl start
+        equivalent to <command>systemctl isolate
         default.target</command>.</para></listitem>
       </varlistentry>
 
@@ -661,8 +662,9 @@
 
         <listitem><para>Halts the machine, starts the
         <filename>halt.target</filename> unit. This is mostly
-        equivalent to <command>systemctl start
-        halt.target</command>.</para></listitem>
+        equivalent to <command>systemctl start halt.target
+        --job-mode=replace-irreversible</command>.</para>
+        </listitem>
       </varlistentry>
 
       <varlistentry>
@@ -670,8 +672,9 @@
 
         <listitem><para>Powers off the machine, starts the
         <filename>poweroff.target</filename> unit. This is mostly
-        equivalent to <command>systemctl start
-        poweroff.target</command>.</para></listitem>
+        equivalent to <command>systemctl start poweroff.target
+        --job-mode=replace-irreversible</command>.</para>
+        </listitem>
       </varlistentry>
 
       <varlistentry>
@@ -679,8 +682,9 @@
 
         <listitem><para>Reboots the machine, starts the
         <filename>reboot.target</filename> unit. This is mostly
-        equivalent to <command>systemctl start
-        reboot.target</command>.</para></listitem>
+        equivalent to <command>systemctl start reboot.target
+        --job-mode=replace-irreversible</command>.</para>
+        </listitem>
       </varlistentry>
 
       <varlistentry>
@@ -688,8 +692,9 @@
 
         <listitem><para>Reboots the machine via kexec, starts the
         <filename>kexec.target</filename> unit. This is mostly
-        equivalent to <command>systemctl start
-        kexec.target</command>.</para></listitem>
+        equivalent to <command>systemctl start kexec.target
+        --job-mode=replace-irreversible</command>.</para>
+        </listitem>
       </varlistentry>
 
       <varlistentry>
diff a/src/core/manager.c b/src/core/manager.c
@@ -2119,14 +2121,17 @@ static int manager_dispatch_signal_fd(sd_event_source *source, int fd, uint32_t
                 default: {
 
                         /* Starting SIGRTMIN+0 */
-                        static const char * const target_table[] = {
-                                [0] = SPECIAL_DEFAULT_TARGET,
-                                [1] = SPECIAL_RESCUE_TARGET,
-                                [2] = SPECIAL_EMERGENCY_TARGET,
-                                [3] = SPECIAL_HALT_TARGET,
-                                [4] = SPECIAL_POWEROFF_TARGET,
-                                [5] = SPECIAL_REBOOT_TARGET,
-                                [6] = SPECIAL_KEXEC_TARGET
+                        static const struct {
+                                const char *target;
+                                JobMode mode;
+                        } target_table[] = {
+                                [0] = { SPECIAL_DEFAULT_TARGET,   JOB_ISOLATE },
+                                [1] = { SPECIAL_RESCUE_TARGET,    JOB_ISOLATE },
+                                [2] = { SPECIAL_EMERGENCY_TARGET, JOB_ISOLATE },
+                                [3] = { SPECIAL_HALT_TARGET,      JOB_REPLACE_IRREVERSIBLY },
+                                [4] = { SPECIAL_POWEROFF_TARGET,  JOB_REPLACE_IRREVERSIBLY },
+                                [5] = { SPECIAL_REBOOT_TARGET,    JOB_REPLACE_IRREVERSIBLY },
+                                [6] = { SPECIAL_KEXEC_TARGET,     JOB_REPLACE_IRREVERSIBLY }
                         };
 
                         /* Starting SIGRTMIN+13, so that target halt and system halt are 10 apart */
```

**Comment by poettering** [comment]
I figure I like your patch better in fact. Any chance you can post it as PR?

**Comment by sourcejedi** [comment]
I got a bit hung up on what to do with `sigpwr.target`, I think it gets a bit awkward.  I'll look at sending a PR for this diff & anything else I can get happy with, then we can at least consider this thread resolved.

**Comment by poettering** [comment]
Closing this one in favour of #6715

**Pull request closed without merging**
