### PR TITLE
Move various files that don't need to be in basic/ to shared/ 

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by poettering** [comment]
Uh, not grokking this at all. The split between src/shared and src/basic was so far defined along the lines of "needs our own public APIs" vs. "doesn't need our own public APIs. i.e. sd-id128, sd-bus, … using stuff would be in src/shared and everything else in src/basic.

This is how it is documented in docs/CODING_STYLE even.

But with change what becomes the new line of distinction? "used be everything" vs." used slightly less often"?

**Comment by keszybz** [comment]
You're right, I forgot that this is described in `CODING_STYLE`. I pushed more patches to adjust `CODING_STYLE`. See the descriptions of patches for (lengthy) justifications.

I think we might want to split the sources for `libjournal-client.a` into a separate directory. Right now it's quite confusing to see what is part of journald and what is not. But this PR does not do this.

**Comment by keszybz** [comment]
```console
$ rpi3 ~/systemd (master)$ time ninja -C build libnss_systemd.so.2
ninja: Entering directory `build'
[172/172] Linking target libnss_systemd.so.2.

real	1m28.049s
user	4m28.707s
sys	0m58.424s
$ rpi3 ~/systemd (pr/10831)$ time ninja -C build libnss_systemd.so.2
ninja: Entering directory `build'
[150/150] Linking target libnss_systemd.so.2.

real	1m19.790s
user	4m7.346s
sys	0m50.207s
```

**Comment by yuwata** [comment]
LGTM, but needs to be rabased.

**Comment by keszybz** [comment]
Rebased.

**Pull request merged**
