### PR TITLE
core/scope: Adding oom-kill status for scope units

### PR DESCRIPTION
**Pull request by gtwang01**
From this [issue](https://github.com/systemd/systemd/issues/23557)

Changes:
Added new ScopeResult for oom-kills.
Added function for oom-kills based on respective function from service units.
Updated scope vtable with new function.

### CODE REVIEW

**Comment by gtwang01** [comment]
Please make sure the switch correctly sorts each state correctly. I wasn't entirely sure about that part.

**Review by anitazha — COMMENTED** [review]
initial comments:

- please squash the 2 commits. i don't see any particular reason why they should be split up this way. and your first commit implies they should be all one commit. we also prefer to have one thesis per commit. force push the changes in order to update the PR.
- please update the commit title from `https://github.com/systemd/systemd/issues/23557` to something more descriptive (such as the title you are using in the PR).
- you can add `Closes #23557` so that GitHub will auto close the issue when the PR is merged

**Comment by poettering** [comment]
lgtm.

**Comment by yuwata** [comment]
Please relabel the commit message from "systemd-oomd" to "core/scope", as you can see by which file is changed by the commit.

**Comment by poettering** [comment]
@anitazha does this look good to you as well?

**Review by anitazha — APPROVED** [review]
lgtm

**Pull request merged**
