### PR TITLE
treewide: fix typos and then/that use

### PR DESCRIPTION
**Pull request by torstehu**

### CODE REVIEW

**Comment by poettering** [comment]
looks ok, besides the one issue i found…

**Comment by zonque** [comment]
I'm not a native speaker either, but yes, I'm fairly sure the way the verb 'broadcast' is used here is correct.

**Comment by torstehu** [comment]
Thanks for the quick review!

No problem, my mistake, non-native speaker here too. :)

Should I force push a fixed commit?

**Comment by zonque** [comment]
Yes please.

**Comment by poettering** [comment]
lgtm now.

**Pull request merged**
