### PR TITLE
Extend hostnamed DMI firmware properties

### PR DESCRIPTION
**Pull request by jelly**
In Cockpit we currently show some hardware information based the available `/sys/class/dmi/id/*` files. Almost everything we require is exposed by hostnamed's dbus properties except firmware date / firmware vendor. So this PR does exactly that, add the two missing fields we require in Cockpit. (Also us switching to hostnamed's API should take hwdb modifications into account which is a nice benefit)

I didn't add the new properties to the output of `hostnamectl` as that information might not relevant enough to be displayed by default. But happy to add them there as well.

This is how the Cockpit integration looks like at the moment:
image

### CODE REVIEW

**Review by yuwata — APPROVED** [review]

**Comment by poettering** [comment]
So yes, I checked the kernel actually exposes parsed information there. We definitely should not expose this as a string like this. THis should be parsed and then passed through as UNIX time in UTC.

Yes, DMI only exposes day granularity and no timezone, but that's fine I think and shouldn't stop us to expose as UNIX time. (in fact, to stay true to our usual rule of exposing everything in µs UNIX time we should do so here too).

The stuff hostnamed exposes here really should be somewhat abstract from the backing source: DMI. i.e. just because the lInux kernel exposes this in DD/MM/YYYY format we shouldn't necessarily do that, and there might be other firmwares who have finer granularity.

Hence, can you please rework this to return this as uint64_t, generated by timegm() filling in the three separate values from the DMI field. This will give you a time_t, i.e. seconds. then multiply by USEC_PER_SEC and return the result.

clients can then do the inverse. via gmtime()

**Comment by poettering** [comment]
Also, could you add these fields to hostnamectl output, we really should at least superficially consume this ourselves.

**Comment by jelly** [comment]
Agreed that exposing a timestamp is a lot nicer, I wasn't sure if the kernel guarranteed to expose it as "DD/MM/YYYY". I'll work on a new PR tomorow.

**Comment by poettering** [comment]
ping?

**Comment by jelly** [comment]
> ping?

Sorry, the end of the year busyness got to me and I haven't managed to dedicate some time for it.

**Pull request merged**
