### PR TITLE
hwdb: Add support for Teclast F6 Pro base sensor

### PR DESCRIPTION
**Pull request by ljmf00**
Reference to [this](https://lore.kernel.org/patchwork/patch/1057409/) kernel patch: to prevent breaking users configurations, this should be added before merging the patch. @jwrdegoede

### CODE REVIEW

**Comment by poettering** [comment]
CI fails:
```
/build/hwdb/60-input-id.hwdb: 3 match groups, 3 matches, 4 properties
/build/hwdb/70-mouse.hwdb: 103 match groups, 118 matches, 120 properties
/build/hwdb/70-touchpad.hwdb: 4 match groups, 7 matches, 4 properties
/build/hwdb/60-keyboard.hwdb: 167 match groups, 249 matches, 852 properties
/build/hwdb/70-pointingstick.hwdb: 8 match groups, 24 matches, 11 properties
/build/hwdb/60-evdev.hwdb: 69 match groups, 91 matches, 250 properties
/build/hwdb/70-joystick.hwdb: 2 match groups, 3 matches, 2 properties
/build/hwdb/60-sensor.hwdb: 90 match groups, 100 matches, 92 properties
Failed to parse: 'ACCEL_LOCATION=display'
Failed to parse: 'ACCEL_LOCATION=base'
```
Please always make sure "ninja -C build test" passes before submitting a PR.

**Comment by ljmf00** [comment]
> ninja -C build test

weird:
```
472/517 parse-hwdb                              OK       1.74 s 

--- command ---
/home/luis/Workspace/Programming/Forked/systemd/systemd/hwdb/parse_hwdb.py
--- stdout ---
/home/luis/Workspace/Programming/Forked/systemd/systemd/hwdb/60-input-id.hwdb: 3 match groups, 0 matches, 0 properties
/home/luis/Workspace/Programming/Forked/systemd/systemd/hwdb/70-joystick.hwdb: 2 match groups, 0 matches, 0 properties
/home/luis/Workspace/Programming/Forked/systemd/systemd/hwdb/70-mouse.hwdb: 103 match groups, 0 matches, 0 properties
/home/luis/Workspace/Programming/Forked/systemd/systemd/hwdb/70-touchpad.hwdb: 4 match groups, 0 matches, 0 properties
/home/luis/Workspace/Programming/Forked/systemd/systemd/hwdb/60-evdev.hwdb: 69 match groups, 0 matches, 0 properties
/home/luis/Workspace/Programming/Forked/systemd/systemd/hwdb/60-keyboard.hwdb: 167 match groups, 0 matches, 0 properties
/home/luis/Workspace/Programming/Forked/systemd/systemd/hwdb/70-pointingstick.hwdb: 8 match groups, 0 matches, 0 properties
/home/luis/Workspace/Programming/Forked/systemd/systemd/hwdb/60-sensor.hwdb: 90 match groups, 0 matches, 0 properties
-------
```

**Comment by ljmf00** [comment]
@poettering am I missing something? Running `python3 ./parse_hwdb.py` inside `hwdb/` and `groups = parse(fname)` appears to be an empty list.
I'm running `Python 3.7.3` on Arch Linux `Linux deimos 5.0.9-arch1-1-ARCH #1 SMP PREEMPT Sun Apr 28 01:59:14 WEST 2019 x86_64 GNU/Linux`.

**Comment by ljmf00** [comment]
@poettering the problem seems fixed. I hope it's ready to merge now. ( I still don't know why test cases didn't work on my specific environment)

**Comment by MadhiasM** [comment]
I see the correct mount matrix in 60-sensor.hwdb:
grafik
But despite the fact, I see in iio that the mount matrix is initialized different for both modules:
grafik
This results in the screen orientation and tablet mode not working properly. Any idea why the mount matrix vom 60-sensor.hwdb is not correctly passed through iio-sensor-proxy?

I am running Zorin OS 17.2 Kernel 6.8.0-48 on F6 Pro
grafik

**Comment by jwrdegoede** [comment]
> But despite the fact, I see in iio that the mount matrix is initialized as identity matrix for both modules:
grafik

The udev hwdb specified mount-matrix should override the kernel provided mount-matrix. The kernel one is read from ACPI if available and otherwise the default identity matrix is used.  The hwdb quirks are there to override this if the kernel provided one is not correct.

Are you sure you have the Teclast F6 Pro ?

What is the output of:

```
cat /sys/class/dmi/id/sys_vendor
cat /sys/class/dmi/id/product_name
```

?

**Comment by MadhiasM** [comment]
Hi, 
yes I have the F6 Pro:
grafik

udev hwdb is empty so the kernel db should be used. In the meantime I found out that issue could somehow arise from Mutter/Wayland as reported in this issue:
https://github.com/systemd/systemd/issues/24727

**Comment by MadhiasM** [comment]
So after switching back to X11 instead of Xorg the issue still persists. What could be a reason why the mount matrix is not found despite being declared? Something in the device declaration in ACPI or the wrong I2C bus being used for looking for the devices is what I found as possible reasons. The display accelerometer is on i2c-2 while the base accelerometer is on i2c-1 so I am wondering if something could go wrong here (similarly reported [here](https://www.linuxquestions.org/questions/linux-kernel-70/invensense-mpu6050-and-device-trees-4175728278/)

**Comment by jwrdegoede** [comment]
The hwdb matching is done on both the modalias of the sensor as well as the DMI info. The DMI info looks good, so what does:

```
cat `readlink -f /sys/bus/iio/devices/iio\:device0`/../modalias
cat `readlink -f /sys/bus/iio/devices/iio\:device1`/../modalias
```

output ?

Also if you do `udevadm info -e > udevdb` and then look up the iio:device0 entry in there, does it contain the "ACCEL_MOUNT_MATRIX" line from the hwdb ?

**Comment by MadhiasM** [comment]
`mathias@mathias-F6-Pro:~$ cat `readlink -f /sys/bus/iio/devices/iio\:device0`/../modalias
cat `readlink -f /sys/bus/iio/devices/iio\:device1`/../modalias
acpi:KIOX020A:KIOX020A:
acpi:KIOX010A:KIOX010A:
`

udevb contains ACCEL_MOUNT_MATRIX for both device0 and device1: 
`P: /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-KIOX020A:00/iio:device0
N: iio:device0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-KIOX020A:00/iio:device0
E: SUBSYSTEM=iio
E: DEVNAME=/dev/iio:device0
E: DEVTYPE=iio_device
E: MAJOR=237
E: MINOR=0
E: USEC_INITIALIZED=10522221
E: ACCEL_LOCATION=base
E: ACCEL_MOUNT_MATRIX=0, 1, 0; 1, 0, 0; 0, 0, 1
E: IIO_SENSOR_PROXY_TYPE=iio-poll-accel iio-buffer-accel
E: SYSTEMD_WANTS=iio-sensor-proxy.service
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:`

`P: /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-KIOX010A:00/iio:device1
N: iio:device1
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-KIOX010A:00/iio:device1
E: SUBSYSTEM=iio
E: DEVNAME=/dev/iio:device1
E: DEVTYPE=iio_device
E: MAJOR=237
E: MINOR=1
E: USEC_INITIALIZED=10564027
E: ACCEL_LOCATION=display
E: ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, -1, 0; 0, 0, -1
E: IIO_SENSOR_PROXY_TYPE=iio-poll-accel iio-buffer-accel
E: SYSTEMD_WANTS=iio-sensor-proxy.service
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:`

So this looks ok, right?

**Pull request merged**
