### PR TITLE
l10n: update Czech translation

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
@martinpitt Nothing went wrong, I just changed the metadata. If I'm not mistaken, these metadata have to be correct, otherwise the translation is not correctly applied. I have updated it according to the updated Polish version (https://github.com/systemd/systemd/pull/4290).

**Comment by keszybz** [comment]
It's not necessary (the comments are only informative). OTOH, we'd update them sooner or later, so we can just do it now.

**Comment by piotrdrag** [comment]
FWIW, .po files are automatically updated during build, so there is absolutely no need to update them manually if no source strings or translations have changed.

**Comment by keszybz** [comment]
Are you sure? We keep the .po files under version control.

**Comment by piotrdrag** [comment]
That's how at least it's supposed to work. Otherwise we would end up with no translations every single release. :)

**Comment by keszybz** [comment]
Hm, maybe I'm confused how this all works, but I thought that the comments in the po file are only regenerated using some magic po-update command, and those comments are information for the translators, and aren't by anything.

**Pull request merged**
