### PR TITLE
udev: when processing uevent failed, retry it

### PR DESCRIPTION
**Pull request by gaoyi1988**
Fixes: https://github.com/systemd/systemd/issues/19220

### CODE REVIEW

**Comment by yuwata** [comment]
In stead of adding such feature, I think we should investigate the root of the issue #14862.

**Comment by gaoyi1988** [comment]
@yuwata 
For this feature, I think the advantages overweigh the disadvantages, as follow:
1. If happened, the device may not be available. It's a serious problem.
2. https://github.com/systemd/systemd/issues/14862 is a problem, And manbe  there are other problems that can be solved by retrying.
3. This only works when uevent handling failed. The impact on the system is small enough.

For https://github.com/systemd/systemd/issues/14862, 
1. Only core file generated，and we can just find that realloc err because of smallbin verify failed.
2. It's hard to repeat. It's only happened twice so far, and half a year apart.
3. We're keeping track of this issue. But we don't know when the problem occured next time, and what informations we can get.

The feature can improve the robustness. And it does not affect the tracking of this problem.

**Comment by poettering** [comment]
This doesn't look right. We don't know what failed, and whether it's even safe to run the rules again. Also, why would it even work better the next time?

I also don't see how this addresses the original memory corruption issue.

I'd really like to track down the memory corruption issue first. Chasing a bug with no understanding what causes it precisely doesn't work. We need to figure that out first, and *then* find a fix. Just keeping retrying is an attempt to tape over a bug we don't understand.

**Comment by poettering** [comment]
So, let's close this, I don't think it's safe to blindly retry udev. we should log (as we do) and ignore the device (as we do). Let's close.

I think we should focus on tracking down the memory corruption instead.

**Pull request closed without merging**
