### PR TITLE
Introduce a timer-delayed target triggered 1min after boot

### PR DESCRIPTION
**Pull request by boucman**
This target is to allow persistant, long running services to trigger after
the main boot transaction and not during that transaction

There is a recurring problem we see on the systemd IRC channel: People complaining about very long 
boot time (systemd-analyze reports more than 30s) where systemd-analyze plot does not report anything
happening. 

After some detective work, what happens is that the user has a long-running, oneshot,  service
(stuff like offline backups or man page database) that is triggered at boot time by a Persistant timer. The service is run during the timer's startup, which in turns blocks timers.target from starting and thus the boot. 

In one instance, the system was an embedded board with no RTC. The long-running job was run at every boot, because it was triggered before NTP had a chance to sync the clock

This commit introduces a new target which will be triggered 1min after the boot is completed for 
timers that trigger long-running jobs. Timers that need to be started at every boot, but not during the boot itself should attach to that target

### CODE REVIEW

**Comment by fsateler** [comment]
> The service is run during the timer's startup, which in turns blocks timers.target from starting and thus the boot.

Are you sure about this? This doesn't make much sense to me, unless the target service is itself ordered `Before=timers.target`. The `timers.target` unit should not be blocked by any of the timer services being run.

> In one instance, the system was an embedded board with no RTC. The long-running job was run at every boot, because it was triggered before NTP had a chance to sync the clock.

It sounds like there is a need for a `timers-pre.target` or something like that so that timers can be delayed until the clock is set to a reasonable value before being scheduled.

This target would be empty on normal systems, but you could hook your ntp client there if you needed that.

**Comment by boucman** [comment]
According to the doc (havn't checked myself) timers have an implicit dependency Before=timers.target (but not a Wants, of course)

As or your second remark, it's possible, but a bit tricky. Timers are set pretty early and NTP might not be available yet. Also, that would solve the RTC problem but not the long boot time problem...

**Comment by keszybz** [comment]
I think there's some confusion here between a timer and the service it starts. Timer units are ordered before timers.target, but the service they start are not ordered. So long-running services do not delay the boot (except by consuming resources).

I can't say I like `timers-delayed.target`. Doing it at a fixed time is a hack. It seems that they long-running services should simply have an ordering of their own, e.g. After=default.target.

**Comment by boucman** [comment]
Ok, so I just tested with a recent git (just before 235 release) the following combination

```
[Timer]
OnCalendar=*:2/3
Persistent=true
[Install]
WantedBy=default.target
```
and
```
[Unit]
After=default.target

[Service]
ExecStart=/usr/bin/sleep 60
```
Will cause a very slow boot as reported by systemd-analyze

During the wait phase, default.target is reported as active, but systemd-analyze will report that the boot is still in progress and systemctl is-system-running will report "starting"

after the wait, systemd-analyze will report that the boot took 1min+ but systemd-analyze critical-chain report that multi-user.target is started after a couple of seconds

systemd-analyze plot will generate a svg that ends at 1+ min, but only has stuff happening for the first couple of seconds...

Ok, so i'm not sure that my fix is correct anymore. Maybe it's a bad understanding of how start-time is accounted for in systemd, but there is something fishy around here. 

I'd gladly take clues on how to fix that, is that the end-of-starting detection that is incorrect ? is taht a feature for start-up ordering that I don't understand ?

I have to admit that the global state of systemd (reported by systemctl status without a unit) is a bit confusing to me...

**Comment by poettering** [comment]
I figure we should just bite the bullet here, and redefine when we consider the systemd to have "finished" booting. Currently we do that when there are no jobs anymore. And I think we should change that to do so when the target we are supposed to boot into is reached. 

The time when the system becomes "idle" for the first time is something we should continue to track though, hence we should add another timestamp for this, and hence not entirely drop the current definition.

Does that make sense?

**Comment by keszybz** [comment]
https://github.com/systemd/systemd/pull/7383 almost does that. After reading this again, I'm starting to think that #7383 should be reworked to do https://github.com/systemd/systemd/pull/7023#issuecomment-345776459 and rework the text print
> Startup finished in xxs (firmware) + xxs (loader) + xxs (kernel) + xxs (initrd) + xxs (userspace) = xxs
> System manager became idle xxxxs later.

or

> System manager never became idle (n jobs active)

**Comment by poettering** [comment]
> #7383 almost does that. After reading this again, I'm starting to think that #7383 should be reworked to do #7023 (comment) and rework the text print

Hmm, but I also think this should be visible in the system state that "systemctl status" shows when invoked without further parameter

**Comment by boucman** [comment]
ok I am also the author of #7383 so i'm fine with reworking it inwhichever way you like, let's continue the discussion there.

**Comment by poettering** [comment]
urks, github was a bit to eager, when it closed this PR... my commit msg triggered it but really shouldn't have... Anyway, @boucman if you are fine of continuing discussion in #7383 then I guess we can leave this closed...

sorry for the fuckup though, i should have been more careful when putting together the commit msg not to use github's magic words...

**Comment by boucman** [comment]
sure, I still think that having an official hook for "some time after boot" would be nice, but that's orthogonal to improving systemd time, and both solve my original problem.

**Pull request closed without merging**
