### PR TITLE
test-sigbus: use posix_fallocate rather than fallocate

### LINKED ISSUE #5833: test-sigbus fails on /tmp being mounted as ext3, as ext3 doesn't support fallocate()
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

git master

### Used distribution

Debian sid

Running the test-suite on a Debian armel portebox fails:

```
 54/227 test-sigbus                             FAIL     0.04 s

--- command ---
SYSTEMD_LANGUAGE_FALLBACK_MAP='/home/biebl/build/systemd/src/locale/language-fallback-map' PATH='/home/biebl/build/systemd/build-deb:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games' SYSTEMD_KBD_MODEL_MAP='/home/biebl/build/systemd/src/locale/kbd-model-map' /home/biebl/build/systemd/build-deb/test-sigbus
--- stderr ---
Assertion 'fallocate(fd, 0, 0, page_size() * 8) >= 0' failed at ../src/test/test-sigbus.c:41, function main(). Aborting.
```

### PR DESCRIPTION
**Pull request by evverx**
Some filesystems do not support `fallocate`, so we need to fall back on
something like `posix_fallocate`.

Closes #5833

### CODE REVIEW

**Comment by poettering** [comment]
oh, are you saying that posix_fallocat() already has the necessary fallback in place that raw fallocate() does not? that's cool

**Comment by poettering** [comment]
lgtm

**Comment by poettering** [comment]
ubuntu CI failure appears to be cused by ubuntu server issues. @martinpitt?

**Comment by keszybz** [comment]
`× xenial-i386` seems unrelated:
```
E: Package 'haveged' has no installation candidate
```

**Comment by evverx** [comment]
> oh, are you saying that posix_fallocat() already has the necessary fallback in place that raw fallocate() does not? that's cool


@poettering , yes, the glibc implementation looks like this
```c
int
posix_fallocate (int fd, __off_t offset, __off_t len)
{
  INTERNAL_SYSCALL_DECL (err);
  int res = INTERNAL_SYSCALL_CALL (fallocate, err, fd, 0,
                                   SYSCALL_LL (offset), SYSCALL_LL (len));
  if (! INTERNAL_SYSCALL_ERROR_P (res, err))
    return 0;
  if (INTERNAL_SYSCALL_ERRNO (res, err) != EOPNOTSUPP)
    return INTERNAL_SYSCALL_ERRNO (res, err);
  return internal_fallocate (fd, offset, len);
}
```
There are some limitations, but I think they do not matter here.

**Comment by poettering** [comment]
> @poettering , yes, the glibc implementation looks like this

excellent!

**Comment by evverx** [comment]
> × xenial-i386 seems unrelated

@keszybz , I retriggered the tests some time ago. `xenial-i386` is happy now. The others are still hanging.

**Comment by evverx** [comment]
> running jobs after remaining timeout -1: 306 rtkit-daemon.service start running

I think that is not related to the patch.

**Pull request merged**
