### PR TITLE
network: skip processing netdev if it is already detached

### PR DESCRIPTION
**Pull request by yuwata**
split-out of #34909.

### CODE REVIEW

**Comment by yuwata** [comment]
@DaanDeMeyer Why squashed on merge?

**Comment by DaanDeMeyer** [comment]
> @DaanDeMeyer Why squashed on merge?

Apologies, I must have fat fingered the wrong option when selecting the method. I didn't intend to squash.

**Comment by yuwata** [comment]
> > @DaanDeMeyer Why squashed on merge?
> 
> Apologies, I must have fat fingered the wrong option when selecting the method. I didn't intend to squash.

No problem.

**Comment by yuwata** [comment]
@DaanDeMeyer I noticed you did NOT squash the commits, but the commit message of the merge commit has been changed since the last meeting, and I confused. Sorry for the noise.

**Pull request merged**
