### PR TITLE
journal-remote: decrease microhttpd memory limit

### PR DESCRIPTION
**Pull request by chaloulo**
Set the MHD_OPTION_CONNECTION_MEMORY_LIMIT to 128KB. The precious value was DATA_SIZE_MAX, which was defined as 1024_1024_768. This caused journal-remote to allocate 756MB for each journal-upload connection, thus exhausting the available memory.

The MHD_OPTION_CONNECTION_MEMORY_LIMIT is set to 128Kb according to guideline in [link](https://www.gnu.org/software/libmicrohttpd/manual/html_node/microhttpd_002dconst.html). 
This PR is an amendment of [commit](https://github.com/systemd/systemd/commit/5e3efccfc97c521107057ab088f58acfae8a8956). The 128KB should be sufficient for use cases, if not we can increase the 128KB value.

### CODE REVIEW

**Comment by vcaputo** [comment]
@kayrus @mischief this all looks familiar, isn't this related to https://github.com/coreos/bugs/issues/962?

**Comment by kayrus** [comment]
@vcaputo nope, looks like it's related to this bugfix https://github.com/systemd/systemd/pull/1729

**Comment by kayrus** [comment]
@chaloulo agree, 128k should be enough (https://gnunet.org/bugs/view.php?id=4007#c9753)

**Comment by johannbg** [comment]
Has that value be confirmed to work from some of the embedded consumers of systemd since 
"32k is deliberately chosen small as MHD is for small, embedded systems" ?

**Comment by kayrus** [comment]
@johannbg I suppose it will not work with HTTPS, even with embedded systems. probably we have set 64k for HTTPS and 32K for HTTP.

**Comment by poettering** [comment]
I merged that now. But I'd be happy about a patch that turns this into a #defined value, and adds a comment why 128K is a good choice, with a link to the library docs where that's said!

**Comment by johannbg** [comment]
Why did you not take a lower value like 64k for http/https which is probably better suited for IoT, raspberry pi's and the likes and increase it to 128k if that for whatever reason becomes necessary?

Are you intentionally not going to support small embedded devices?

**Comment by chaloulo** [comment]
Maybe we should make this configurable? If I have time I'll try to write a patch that takes this as a configuration value from journal-remote.conf. But this will be a new PR.

**Comment by poettering** [comment]
@chaloulo I am not a fan of unnecessary configuration of tunables. Unless there's a strong reason to make this configurable (which I cannot see) I'd rather leave that is it is now.

**Comment by chaloulo** [comment]
@poettering: Well, in this thread there have been mentions of various values, like 128K, 64K, 32K. Especially the comment from johannbg, which requests a smaller value to run on small embedded devices. This is why I thought that it should be configurable.

**Comment by johannbg** [comment]
@poettering if you dont want this as an configuration tunable why did you accept such a high value to begin with when MHD upstream specifically states "32k is deliberately chosen small as MHD is for small, embedded systems". If the intent is to support embedded devices then those devices become the lowest denominator on which upstream should cater to and default on, not containers,servers or full blown desktop distribution.

Just clarify which target systemd consumer you are basing your upstream defaults on since there are no coherence or consistency in which you seem to be basing the defaults on, so those can be fixed properly and made consistent.

**Pull request merged**
