### PR TITLE
Respect ro bootparam

### PR DESCRIPTION
**Pull request by tblume**
systemd-remount-fs should mount system root readonly when the bootparameter: 'ro' is given

### CODE REVIEW

**Comment by grawity** [comment]
Not sure if that makes any sense.

I mean, _the whole point_ of systemd-remount-fs is to make the rootfs writable when booting with `ro`, no?

(Many older or just initramfs-lacking distros first mount the rootfs read-only according to `ro` from bootparam, then fsck it, then remount it as writable according to `rw` from /etc/fstab. IIRC.)

**Comment by tblume** [comment]
Hm, and what if you explicitely want to have system root readonly?
For example in single user mode to fix some filesystem problems?

**Comment by grawity** [comment]
I'd say you fix them from the initramfs, e.g. boot with `break=premount`. (If the fs has gotten to the point where it _needs_ manual fixing, I'm not sure if it's wise to do that while the same fs is mounted, read-only or not.) Or explicitly `systemd.mask=` the remount service.

**Comment by martinpitt** [comment]
Mounting a (potentially already writable) partition "ro" again is wrong, and prone to fail. This only really works if you have a r/o root to begin with, as is the case for usual initrds. I. e. initrd mounts it r/o, then you do fsck, rescue, and what not, and after pivoting `systemd-remount-fs.service` mounts it r/w.

I do see why we want to respect `ro` on the kernel command line, but IMHO this should be done by adding `ConditionKernelCommandLine=!ro` to that .service.

Also, this PR contains a second unrelated commit, please file separate PRs for separate issues. I'm closing this PR now, due to the issues above. Please file new one(s).

Thanks!

**Comment by arvidjaar** [comment]
> I do see why we want to respect ro on the kernel command line, but IMHO this should be done by
> adding ConditionKernelCommandLine=!ro to that .service.

Then please use different parameter for it. "ro" historically was used to mount root read-only only initially. By default grub adds "ro" parameter when generating grub.cfg. Interpreting "ro" as "leave root read-only forever" will break every second system out there.

**Comment by martinpitt** [comment]
Ah, true that, thanks @arvidjaar for pointing out.

**Pull request closed without merging**
