### PR TITLE
Updated Debian config for mkosi

### PR DESCRIPTION
**Pull request by AsciiWolf**
Fix build failure because of missing _xz_ binary, fix _test-acl-util_ and _test-compress_ unit tests, add support for running _make check_ during build.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
The Debian mkosi image now builds successfully, but _journalctl_ and _systemd-journal-flush.service_ don't work in the booted image. They can be fixed by installing _libqrencode3_ package; _systemd-journal-catalog-update.service_ also doesn't seem to work because "_ConditionNeedsUpdate=/etc was not met_".

Here is a mkosi log file: [mkosi_log.txt](https://github.com/systemd/systemd/files/667722/mkosi_log.txt)

**Comment by poettering** [comment]
@AsciiWolf hmm, if libqrencode is needed during runtime, can you add it to Packages= in the file?

**Comment by poettering** [comment]
And the catalog thing we can probably fix by a "touch /etc" invocation in mkosi.postinst, but I figure we can do that in a separate commit

**Comment by AsciiWolf** [comment]
@poettering I have [tried](https://github.com/systemd/systemd/pull/4948) adding it to "BuildPackages=" which resulted into libqrencode3 being added only during the build but not to the final image. I will try adding it to "Packages=" when I get home.

**Comment by AsciiWolf** [comment]
I have added the needed packages to "Packages=" and both _journalctl_ and _systemd-journal-flush.service_ are now working correctly. Thanks!

The _systemd-journal-catalog-update.service_ still doesn't work because of the "ConditionNeedsUpdate=/etc" not being met, but, as you said, it will probably be better to fix this issue in a separate commit.

There is a "Failed to install release agent, ignoring: No such file or directory" warning being shown when starting the container, but it appears to be harmless.

By the way, what is the default root password of the mkosi generated image? I'm changing the password every time I generate a new image by running the image first without a "-b" switch, then "passwd", it's not a big issue, but it still would be great if I could skip this step. :-)

**Pull request merged**
