### PR TITLE
Add support for naming fds for socket activation and more

### PR DESCRIPTION
**Pull request by poettering**
This is primarily a heavily updated version of #1247, but also contains other fixes.

### CODE REVIEW

**Comment by grooverdan** [comment]
thank you.

**Comment by poettering** [comment]
ah, already merged, will push directly then.

**Comment by zonque** [comment]
Alright. The rest looked good to me.

**Comment by poettering** [comment]
Thanks for the review! I am prettying another PR with fixes.

**Comment by poettering** [comment]
@zonque those promised fixes are now in #1469. Thanks!

**Pull request merged**
