### PR TITLE
util: Support ranges in parse_cpu_set

### PR DESCRIPTION
**Pull request by filbranden**
This PR also contains the commit from #1383, so if both are good you can merge this one only.

Thanks!
Filipe

### CODE REVIEW

**Comment by poettering** [comment]
Looks pretty OK, but I wonder if we shouldn't go extract_first_word() all the way here...

**Comment by filbranden** [comment]
Good point, I'll resubmit with updates to `systemd.exec(5)` as well. Thanks!

**Comment by poettering** [comment]
I might have broken your patchset, because i moved the cpu set stuff into its own cpu-set-util.[ch] files... Sorry for that!

**Comment by filbranden** [comment]
No worries... I'm planning to address the lack of updates to manpages and also planning to introduce a new `parse_range()` or similar to use `extract_first_word()` as you suggested... Will most likely push an update over the weekend. Cheers!

**Comment by filbranden** [comment]
Superceded by #1550.

**Pull request closed without merging**
