### PR TITLE
network: address-pool: also check conflicts with foreign addresses

### PR DESCRIPTION
**Pull request by yuwata**
Fixes CI issue found in https://github.com/systemd/systemd-centos-ci/pull/334.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @mrc0mmand.

**Comment by mrc0mmand** [comment]
Thanks!

**Comment by mrc0mmand** [comment]
I tried the patch with my "reproducer" in https://github.com/systemd/systemd-centos-ci/pull/334 and it seems to be working :tada:

**Review by bluca — APPROVED** [review]
lgtm and confirmed to fix the issue, merging

**Pull request merged**
