### PR TITLE
minor follow-up fixes for #3685

### PR DESCRIPTION
**Pull request by poettering**
@alepuccetti please have a look

### CODE REVIEW

**Comment by alepuccetti** [comment]
Did not know about `SD_BUS_VTABLE_HIDDEN`.

LGTM

**Comment by poettering** [comment]
> Did not know about SD_BUS_VTABLE_HIDDEN.

Yeah, I forgot about it too while reviewing your patches... ;-)

**Comment by poettering** [comment]
ok, let's wait for the CI to be green, and merge it then. thanks for the review!

**Comment by alepuccetti** [comment]
> ok, let's wait for the CI to be green, and merge it then. thanks for the review!

Achievement unlocked: First review

**Pull request merged**
