### PR TITLE
Update dbus docs, make developer mode default

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by yuwata** [comment]
LGTM.

**Comment by yuwata** [comment]
CentOS CI (CentOS 7) fails with
```
428/477 dbus-docs-fresh                         FAIL     0.12 s (exit status 1)

--- command ---
/root/systemd/tools/update-dbus-docs.py --build-dir=/root/systemd/build --test /root/systemd/build/../man/org.freedesktop.LogControl1.xml /root/systemd/build/../man/org.freedesktop.hostname1.xml /root/systemd/build/../man/org.freedesktop.import1.xml /root/systemd/build/../man/org.freedesktop.locale1.xml /root/systemd/build/../man/org.freedesktop.login1.xml /root/systemd/build/../man/org.freedesktop.machine1.xml /root/systemd/build/../man/org.freedesktop.resolve1.xml /root/systemd/build/../man/org.freedesktop.systemd1.xml /root/systemd/build/../man/org.freedesktop.timedate1.xml
--- stderr ---
Traceback (most recent call last):
  File "/root/systemd/tools/update-dbus-docs.py", line 11, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
-------
```
Not checked ubuntu CIs, but I guess they fails in the same way.

**Comment by keszybz** [comment]
The test is now skipped if the module cannot be imported.

**Comment by keszybz** [comment]
```
Traceback (most recent call last):
  File "/tmp/autopkgtest.cZSCZY/build.mvc/systemd/tools/update-dbus-docs.py", line 303, in <module>
    stats = {page.split('/')[-1] : process(page) for page in opts.pages}
  File "/tmp/autopkgtest.cZSCZY/build.mvc/systemd/tools/update-dbus-docs.py", line 303, in <dictcomp>
    stats = {page.split('/')[-1] : process(page) for page in opts.pages}
  File "/tmp/autopkgtest.cZSCZY/build.mvc/systemd/tools/update-dbus-docs.py", line 268, in process
    subst_output(xml, pl, stats)
  File "/tmp/autopkgtest.cZSCZY/build.mvc/systemd/tools/update-dbus-docs.py", line 186, in subst_output
    print(f'COMMAND: {shlex.join(argv)}')
AttributeError: module 'shlex' has no attribute 'join'
```
Arrggh.

**Pull request merged**
