### PR TITLE
resolve: do not try to send varlink error more than once

### PR DESCRIPTION
**Pull request by yuwata**
After d2ebf5cc1d59e29139f06efaa3a9b2c184cdaa25, `sd_varlink_error()` and friends return negative errno.

Fixes https://github.com/systemd/systemd/pull/34946#discussion_r1823703636.

### CODE REVIEW

**Comment by poettering** [comment]
Thanks for the quick fix!

**Comment by evverx** [comment]
Dunno. `systemd` itself seems to emit those messages
```sh
varlink-26-26: Setting state idle-server
varlink-26-26: Received message: {"method":"io.systemd.UserDatabase.GetUserRecord","parameters":{"service":""}}
varlink-26-26: Changing state idle-server → processing-method
varlink-26-26: Sending message: {"error":"io.systemd.UserDatabase.BadService","parameters":{}}
varlink-26-26: Changing state processing-method → processed-method
varlink-26-26: Callback for io.systemd.UserDatabase.GetUserRecord returned error: Invalid request descriptor
varlink-26-26: Changing state processed-method → idle-server
varlink-26-26: Got POLLHUP from socket.
```
The log level is debug as far as I can see though. Either way I'd take a look at all the callers probably.

**Comment by yuwata** [comment]
@evverx -> #34971

**Comment by evverx** [comment]
That was quick. I haven't followed all the links to the other PRs to figure out where those errors came from so I can't say I understand what's going on there :-)

**Pull request merged**
