### PR TITLE
packit: temporarily build systemd without BPF stuff

### PR DESCRIPTION
**Pull request by mrc0mmand**
The kernel-tools meta-package was retired in Rawhide, but its replacement has not landed, yet. Until that happens, let's build without the bpf-framework stuff.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
@bluca it looks like the Rawhide CIs uncovered a bug, after I used some dark magic to make them work without the bpftool package.

If I run `test-path` as an unprivileged user, on a system that supports pidfd_spawn, it fails to spawn the sd-executor:

```
[vagrant@linux systemd]$ meson test -C build -v test-path
ninja: Entering directory `/root/systemd/build'
[1/17] Generating version.h with a custom command
1/1 systemd:core / test-path RUNNING       
>>> PATH=/root/systemd/build:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin PROJECT_BUILD_ROOT=/root/systemd/build MALLOC_PERTURB_=49 LD_LIBRARY_PATH=/root/systemd/build/src/core:/root/systemd/build/src/shared UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 EFI_ADDON=/root/systemd/build/src/boot/efi/addonx64.efi.stub SYSTEMD_LANGUAGE_FALLBACK_MAP=/root/systemd/src/locale/language-fallback-map ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 /root/systemd/build/test-path
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Failed to start transient scope unit: Interactive authentication required.
Couldn't allocate a scope unit for this test, proceeding without.
line 150: path-exists.path: state = running; result = success (left: 29999749)
line 150: path-exists.service: state = dead; result = success
line 150: path-exists.path: state = running; result = success (left: 29999721)
line 150: path-exists.service: state = dead; result = success
line 150: path-exists.path: state = running; result = success (left: 29999702)
line 150: path-exists.service: state = dead; result = success
-.slice: Failed to enable/disable controllers on cgroup /user.slice/user-1000.slice/session-1.scope, ignoring: Permission denied
app.slice: Failed to create cgroup /user.slice/user-1000.slice/session-1.scope/app.slice: Permission denied
-.slice: Failed to enable/disable controllers on cgroup /user.slice/user-1000.slice/session-1.scope, ignoring: Permission denied
app.slice: Failed to create cgroup /user.slice/user-1000.slice/session-1.scope/app.slice: Permission denied
posix_spawn_wrapper: path=/proc/self/fd/8; argv[0]=/root/systemd/build/systemd-executor; cgroup=/user.slice/user-1000.slice/session-1.scope/app.slice/path-exists.service
posix_spawn_wrapper: open(/sys/fs/cgroup/user.slice/user-1000.slice/session-1.scope/app.slice/path-exists.service) returned -1
path-exists.service: Failed to spawn executor: No such file or directory
path-exists.service: Failed to spawn 'start' task: No such file or directory
path-exists.service: Failed with result 'resources'.
```

**Comment by bluca** [comment]
Interesting, I wonder why the Arch job didn't show that

**Comment by mrc0mmand** [comment]
> Interesting, I wonder why the Arch job didn't show that

We mostly likely don't test this scenario. IIRC we run the unit tests in an unprivileged nspawn container, but that's apparently not enough, since I can reproduce the issue on a fresh Arch VM with the same reproducer as above.

**Comment by YHNdnzj** [comment]
Hmm, is this actually a bug? The cgroup didn't exist, so the executor will error out in `cg_attach_everywhere` later after all?

**Comment by mrc0mmand** [comment]
> Hmm, is this actually a bug? The cgroup didn't exist, so the executor will error out in `cg_attach_everywhere` later after all?

The test fails gracefully if the service exits with `EXIT_CGROUP` - fcb7138ca7c5649aa3c0fe780db20ebae08b2cde.

**Comment by bluca** [comment]
https://github.com/systemd/systemd/pull/31228 should fix it

**Review by bluca — APPROVED** [review]

**Pull request merged**
