### PR TITLE
build-sys: regenerate %.m4 -> % on reconfigure

### PR DESCRIPTION
**Pull request by evverx**
Fixes:

``` bash
$ ./configure ... --enable-resolved
$ make
$ cat tmpfiles.d/etc.conf
...
L! /etc/resolv.conf - - - - ../run/systemd/resolve/resolv.conf
...


$ ./configure ... --disable-resolved
$ make
$ cat tmpfiles.d/etc.conf
...
L! /etc/resolv.conf - - - - ../run/systemd/resolve/resolv.conf
...
```

### CODE REVIEW

**Comment by evverx** [comment]
Very handy for debugging https://github.com/systemd/systemd/pull/2086 :)

**Comment by zonque** [comment]
Hm, that might be a stupid question, but is config.status something we can rely on? I've never seen this file being used as dependency in Makefiles.

**Comment by filbranden** [comment]
autoconf recommendations (for the standalone use, without automake) actually use a dependency on `config.status` to decide when to regenerate `Makefile`, etc.
http://www.gnu.org/software/autoconf/manual/autoconf.html#Automatic-Remaking

I'm not sure this is recommended in general though... I think when using automake, the preferred way to accomplish that would be to add the generated files to `BUILT_SOURCES` instead.
https://www.gnu.org/software/automake/manual/html_node/Sources.html

But I haven't really stopped to test that it fixes the reported issue, or to look at the other implications of using `BUILT_SOURCES` for this purpose here...

@evverx What do you think?

**Comment by evverx** [comment]
> is config.status something we can rely on?
> 
> autoconf recommendations (for the standalone use, without automake) actually use a dependency on config.status to decide when to regenerate Makefile, etc

Automake generates this (see `Makefile.in`):

```
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
    ...

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
    ...
```

Also, Automake generates:

```
config.h: stamp-h1
    ...

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
    ...

all: $(BUILT_SOURCES) config.h
    ...
```

[`M4_DEFINES`](https://github.com/evverx/systemd/blob/regenerate-m4-on-reconfigure/Makefile.am#L5977) for `*.m4` is something like `config.h` for `*.c`. I mean, `config.status` generates new `M4_DEFINES` on reconfigure.

`BUILT_SOURCES` doesn't work here: there is no info about "`M4_DEFINES` depends on `config.status`"

**Comment by evverx** [comment]
Actually, `BUILT_SOURCES` contains `src/core/load-fragment-gperf.c`:

```
$ make print-BUILT_SOURCES
src/core/load-fragment-gperf.c src/core/load-fragment-gperf-nulstr.c ...
```

`src/core/load-fragment-gperf.c` depends on `src/core/load-fragment-gperf.gperf.m4`:

```
$ make -n src/core/load-fragment-gperf.c
/bin/mkdir -p src/core/
echo "  M4      " src/core/load-fragment-gperf.gperf;/usr/bin/m4 -P -DHAVE_SECCOMP -DHAVE_SELINUX -DHAVE_APPARMOR -DHAVE_PAM -DHAVE_ACL -DHAVE_SMACK -DHAVE_MICROHTTPD -DHAVE_LIBCURL -DENABLE_TIMESYNCD -DENABLE_RESOLVED -DENABLE_NETWORKD -DENABLE_KDBUS -DHAVE_SYSV_COMPAT < src/core/load-fragment-gperf.gperf.m4 > src/core/load-fragment-gperf.gperf
/bin/mkdir -p src/core/
echo "  GPERF   " src/core/load-fragment-gperf.c;gperf < src/core/load-fragment-gperf.gperf > src/core/load-fragment-gperf.c
```

But

```
$ make all
$ ./configure ... --disable-pam
$ make -n src/core/load-fragment-gperf.c
make: 'src/core/load-fragment-gperf.c' is up to date.
$ grep PAM !$
grep PAM src/core/load-fragment-gperf.c
      {"Swap.PAMName",                     config_parse_unit_string_printf,    0,                             offsetof(Swap, exec_context.pam_name)},
      {"Mount.PAMName",                     config_parse_unit_string_printf,    0,                             offsetof(Mount, exec_context.pam_name)},
      {"Socket.PAMName",                     config_parse_unit_string_printf,    0,                             offsetof(Socket, exec_context.pam_name)},
      {"Service.PAMName",                     config_parse_unit_string_printf,    0,                             offsetof(Service, exec_context.pam_name)},
```

**Comment by evverx** [comment]
> is config.status something we can rely on?

[config.status Invocation](http://www.gnu.org/software/autoconf/manual/autoconf.html#config_002estatus-Invocation) says:

> You can use ./config.status in your makefiles.

@filbranden , thanks for the links!

**Comment by zonque** [comment]
Ok, we did conclude this is safe to do, right?

**Comment by poettering** [comment]
So, we used to rebuild a lot of files whenever the makefile changed, but that was nasty because super-slow, and is something we hence turned off again. But I figure if configure.ac changes then we could still rebuild these things indeed, as rerunning configure is a pretty expensive thing anyway.

**Pull request merged**
