### PR TITLE
Enhance matching of TAG keys

### PR DESCRIPTION
**Pull request by franciozzy**
This PR includes two patches. The first patch enhances the logic which tests matching TAGs to consider inequalities. The second patch enables the use of wildcards to match TAGs.

### CODE REVIEW

**Comment by kaysievers** [comment]
I am not convinced, that we want such magic for tags. They are really static assignments and not so much strings to match. Tags are not meant to be used like variables. What is the use case?

**Comment by franciozzy** [comment]
Hi Kay, thanks for the quick response.

The inequality test (eb344d0) is an inexpensive addition to allow rules to test if a tag is not already present in a device. The glob patch (2ec943d) takes into consideration `token->key.glob`, which is already set when udev parses the rules. If nothing fancy (e.g. a wildcard) is used, it falls back to `streq()`, so it doesn't make it more expensive either.

We would like to use udev's transactional approach and database to mark (tag) devices in use by certain components in our system. This would be done by adding a tag using a specific prefix (e.g. "inuse_by_x"), but only if no other "inuse_by_*" tag already exists.

Looking forward to your views on this.

**Comment by kaysievers** [comment]
The != sounds ok. Tags should stay tags, not become strings, so no globs.

**Comment by franciozzy** [comment]
Hi Kay, thanks for the reply. Are you able to merge just eb344d0 or would you like me to open a new PR?

**Comment by zonque** [comment]
Just force-push a new branch that just contains the commit you want.

**Comment by franciozzy** [comment]
Done! I've force-pushed to franciozzy:tagenhance in order to automatically update this PR, but kept a copy of the original patches in franciozzy:tagglob just in case.

(That had the unfortunate downside of changing the commit ids, making the history of this PR a bit strange...)

**Pull request merged**
