### PR TITLE
hostnamectl, firstboot, networkd: ignore dot at end of fqdn, be case-insensitive, case preserving

### PR DESCRIPTION
**Pull request by keszybz**
This is v2 of #730.

Implementation changed a bit following @poettering's suggestion to add relax parameter to hostname_is_valid. This is done patch one as preparation, and tests are augmented.

In various places where we accept hostnames from the user, preserve case, and ignore a trailing dot if the name is a fqdn. This makes the behaviour for "foobar.org." and "foobar.org" the same. This is done firstboot, networkd config file parsing, and hostnamectl, since those are places where we get the hostname straight from the user.

Also, do not lowercase the hostname in hostnamectl, and ignore case when checking if name is localhost.

```
$ ./hostnamectl set-hostname Foobar.
$ ./hostnamectl
   Static hostname: Foobar
   Pretty hostname: Foobar.
$ ./hostnamectl set-hostname Foobar.org.
$ ./hostnamectl
   Static hostname: Foobar.org
$ ./hostnamectl set-hostname Foobar.org..
$ ./hostnamectl
   Static hostname: Foobar.org
   Pretty hostname: Foobar.org..
```

### CODE REVIEW

**Comment by keszybz** [comment]
@poettering @teg any comments?

**Comment by teg** [comment]
I'll defer to Lennart on this (I don't have a clear picture of what is the right amount of pixiedust to apply to these things). However, the last example should be -EINVAL, no? At least not set the static hostname, as the given hostname contains an empty non-terminal label, which is not valid (so the given and set static hostnames are not equivalent).

**Comment by keszybz** [comment]
> However, the last example should be -EINVAL, no? At least not set the static hostname, as the given hostname contains an empty non-terminal label, which is not valid (so the given and set static hostnames are not equivalent).

Well, that's another thing to discuss. This behaviour is unchanged from current code, which is: convert pretty hostname to a valid fqdn by removing invalid characters and duplicate dots.

**Comment by poettering** [comment]
We should probably add a comment to hostname_is_valid() and clarify that this doesn't due full DNS validation, but a validation that is both more and less strict than DNS (because it enforces Linux' size limit on hostnames, which DNS doesn't have...). Also it should point people to dns_name_is_valid() for the full RFC conforming DNS validation.

**Comment by poettering** [comment]
Looks pretty OK otherwise.

**Comment by keszybz** [comment]
Thanks for the review. I'll prepare an update.

**Comment by johannbg** [comment]
This is still doing the wrong thing as in updating the pretty hostname value with a guessing games of the end user intent ( as is clearly shown with ./hostnamectl set-hostname Foobar.org.. example ) in that example it should have _only_ updated the pretty field not the static hostname entry or simply error out since the entry did not pass as a valid static hostname. 

Can someone explain why you are insisting on keeping this broken behaviour and or where can I find the discussion that showed the justification that allowed this to be added in the first place?

**Comment by keszybz** [comment]
@johannbg I agree with what you are saying. But that's a separate issue, worthy of a separate pull request and discussion.

**Comment by keszybz** [comment]
Merged as 73974f6768.

**Comment by poettering** [comment]
@johannbg Well, I think we should make sure we keep the names in sync, so that the pretty and static names are always similar, but the later reduced to classic hostname-like syntax. Specifically, if you chose "My Teddy Bear's Name is Waldo" as hostname and don't specify what you mean by that, then we should make sure that that it is used unmodified as pretty name, and reduced to something like "my-teddy-bears-name-is-waldo" for the static hostname. Behaviour like this is pretty common, for example mDNS/DNS-SD suggest that explicitly, and it is implemented like this on MacOS for example.

if you want the pretty and the static name to diverge, then go ahead and specify what you actually want to change via "hostnamectl set-hostname --pretty" or "hostnamectl set-hostname --static" and so on. But if you don't specify which of the hostnames you want to change, then we should apply the name, and propagate it to all fields, possibly reduced to the expressivity of the specific type of hostname.

On top of this rule, as one special optimization we unset the pretty hostname if it is redundant, since the user only ever specified a classic internet-style hostname anyway. This we do since we acknowledge that a pretty hostname is a concept from end-user devices, and server folks don't need it, and if they don't make use of it, then we should suppress it. That's all.

**Comment by johannbg** [comment]
@poettering the implementation on OS-X is more complex and is doing quite few more things behind the scenes to ensure things work, things we are not doing afaik but you are saying that you are doing this for one of all of the following 
Multicast DNS (mDNS)
DNS based Service Discovery (DNS-SD)
Link Local Multicast Name Resolution (LLMNR)
Peer Name Resolution Protocol (PNRP)

What are we doing to avoid name collation when using one or all of these?
What are we doing to prevent application when using any of the above from sending those query's to classic DNS?
Why aren't we ending in any of the SUDN when pretty name is modified to a static name?
etc etc. 

And the bigger question why is not avahi just let handled this ( by manipulating the static and pretty hostname separately as well doing all the other stuff needed for this to work properly for all of which I mentioned above or just the mDNS and DNS-SD if you prefer ) just like most of this complexity resides in bonjour in OS-X and we dont play this stupid guessing games of translating pretty hostname to FQDN when set-hostname is used without any additional switches which undoubtedly will end up with the the domain administrators forming a lynch mob, beat us with spiked clubs and burn us on the stakes. . .

**Comment by keszybz** [comment]
> "My Teddy Bear's Name is Waldo" → "my-teddy-bears-name-is-waldo"

The problem is that we change "That is Waldo. My Teddy" to ThatisWaldo.MyTeddy.
If the name doesn't pass staticity rules, we should make it into a single component ("That-is-Waldo-My-Teddy"), and never into something that looks like a FQDN.

**Comment by johannbg** [comment]
You do realize right that you cannot apply a single statistic rule to this right? 
There are different naming rules ( and other needed changes ) depending on which of the following you are using  mDNS,DNS-SD, LLMNP, PNRP so bigger question here is where do you want the complexity to implement the support for this being handled.  

If the answer is we want to handle that complexity in hostnamectl or elsewhere. that means no more half assing and the code needs to be adjusted to accommodate that properly. 

If the answer to that is no we dont want to do that, then drop that conversion and only update the static hostname as long as set-hostname is provided with fqdn otherwise treat the supplied entry strictly as an pretty name and let the rest be handled by applications like Avahi or the likes

**Pull request closed without merging**
