### PR TITLE
udev-util: add generic device_get_{vendor,model}_string() helpers (mold compat)

### PR DESCRIPTION
**Pull request by poettering**
We chck the same props in various places, add a single implementation of a call to inquire this.

### CODE REVIEW

**Comment by poettering** [comment]
This is the same as #30003, except that it drops the networkd changes. Let's see if this works around the mold issue.

**Comment by poettering** [comment]
So this passed the "mold" test now. so weird.

**Comment by poettering** [comment]
set dont-merge as @mrc0mmand found supposedly found a solution over on #30003, so we might go for that if it checks out.

**Comment by yuwata** [comment]
superseded by #30003. closing.

**Pull request closed without merging**
