### PR TITLE
hwdb: disallow acceleration matrices with trivial rows

### PR DESCRIPTION
**Pull request by keszybz**
All zeros means that we cannot detect acceleration in that direction.

Related to #6430.

@hadess This adds the test, but I have no idea what to do with the failing entries:
```console
$ hwdb/parse_hwdb.py hwdb/60-sensor.hwdb
hwdb/60-sensor.hwdb: 21 match groups, 22 matches, 21 properties
Mount matrix is all zero in z row: 'ACCEL_MOUNT_MATRIX=0, 1, 0; 1, 0, 0; 0, 0, 0'
Mount matrix is all zero in z row: 'ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 0'
```

### CODE REVIEW

**Comment by hadess** [comment]
That sounds good. I'd disable both of those. One of them is mine, but the machine is currently "in the shop". The other one is from https://github.com/systemd/systemd/pull/5177 which we'd reopen.

**Comment by keszybz** [comment]
Updated with patches (two separate, to make it easy to revert later on), to remove those entries.

**Comment by poettering** [comment]
shall we merge this now? @hadess?

**Comment by hadess** [comment]
Sure, don't forget to reopen the pull request that'll be broken by this as well.

**Comment by poettering** [comment]
@hadess hmm, PRs can't be reopened on github... will add a comment there

**Pull request merged**
