### PR TITLE
install: follow unit file symlinks in /usr, but not /etc when looking for [Install] data and more

### PR DESCRIPTION
**Pull request by poettering**
This replaces #1375, and adds quite a number of other fixes to the installation logic.

@msekletar please have a look, and check if this does what's necessary.

### CODE REVIEW

**Comment by msekletar** [comment]
From a quick test it seems like new implementation doesn't handle all necessary cases. Here is a log from my test script. Let me know if you want me to share the script. 

```
:: [   PASS   ] :: Command 'systemctl enable a' (Expected 0, got 0)
:: [   FAIL   ] :: Command 'systemctl is-enabled a' (Expected 0, got 1)
:: [   PASS   ] :: Command 'systemctl disable a' (Expected 0, got 0)
:: [   PASS   ] :: Command 'systemctl is-enabled a' (Expected 1, got 1)
:: [   PASS   ] :: Command 'systemctl reenable a' (Expected 0, got 0)
:: [   FAIL   ] :: Command 'systemctl is-enabled a' (Expected 0, got 1)
:: [   PASS   ] :: Command 'systemctl disable a' (Expected 0, got 0)
:: [   PASS   ] :: Command 'systemctl enable b' (Expected 0, got 0)
:: [   FAIL   ] :: Command 'systemctl is-enabled b' (Expected 0, got 1)
:: [   PASS   ] :: Command 'systemctl disable b' (Expected 0, got 0)
:: [   PASS   ] :: Command 'systemctl is-enabled b' (Expected 1, got 1)
:: [   PASS   ] :: Command 'systemctl reenable b' (Expected 0, got 0)
:: [   FAIL   ] :: Command 'systemctl is-enabled b' (Expected 0, got 1)
:: [   PASS   ] :: Command 'systemctl disable b' (Expected 0, got 0)
:: [   FAIL   ] :: Command 'systemctl enable  foo@tty4.service 2>&1 | grep -q Created' (Expected 0, got 1)
:: [   FAIL   ] :: Command 'systemctl is-enabled foo@tty4.service 2>&1 | grep -q enabled' (Expected 0, got 1)
:: [   FAIL   ] :: Command 'systemctl disable  foo@tty4.service 2>&1 | grep -q Removed' (Expected 0, got 1)
:: [   PASS   ] :: Command 'systemctl is-enabled foo@tty4.service' (Expected 1, got 1)
:: [   FAIL   ] :: Command 'systemctl reenable  foo@tty4.service 2>&1 | grep -q Created' (Expected 0, got 1)
:: [   FAIL   ] :: Command 'systemctl is-enabled foo@tty4.service' (Expected 0, got 1)
:: [   FAIL   ] :: Command 'systemctl disable foo@tty4.service 2>&1 | grep -q Removed' (Expected 0, got 1)
:: [   PASS   ] :: Command 'mount --bind / /mnt' (Expected 0, got 0)
:: [   PASS   ] :: Command 'systemctl --root=/mnt enable a' (Expected 0, got 0)
:: [   FAIL   ] :: Command 'systemctl --root=/mnt is-enabled a' (Expected 0, got 1)
:: [   PASS   ] :: Command 'systemctl --root=/mnt disable a' (Expected 0, got 0)
:: [   PASS   ] :: Command 'systemctl --root=/mnt is-enabled a' (Expected 1, got 1)
:: [   PASS   ] :: Command 'systemctl --root=/mnt reenable a' (Expected 0, got 0)
:: [   FAIL   ] :: Command 'systemctl --root=/mnt is-enabled a' (Expected 0, got 1)
:: [   PASS   ] :: Command 'systemctl --root=/mnt disable a' (Expected 0, got 0)
:: [   FAIL   ] :: Command 'systemctl --root=/mnt enable b' (Expected 0, got 1)
:: [   FAIL   ] :: Command 'systemctl --root=/mnt is-enabled b' (Expected 0, got 1)
:: [   PASS   ] :: Command 'systemctl --root=/mnt disable b' (Expected 0, got 0)
:: [   PASS   ] :: Command 'systemctl --root=/mnt is-enabled b' (Expected 1, got 1)
:: [   FAIL   ] :: Command 'systemctl --root=/mnt reenable b' (Expected 0, got 1)
:: [   FAIL   ] :: Command 'systemctl --root=/mnt is-enabled b' (Expected 0, got 1)
:: [   FAIL   ] :: Command 'systemctl --root=/mnt enable  foo@tty4.service 2>&1 | grep -q Created' (Expected 0, got 1)
:: [   FAIL   ] :: Command 'systemctl --root=/mnt is-enabled foo@tty4.service 2>&1 | grep -q enabled' (Expected 0, got 1)
:: [   FAIL   ] :: Command 'systemctl --root=/mnt disable  foo@tty4.service 2>&1 | grep -q Removed' (Expected 0, got 1)
:: [   PASS   ] :: Command 'systemctl --root=/mnt is-enabled foo@tty4.service' (Expected 1, got 1)
:: [   FAIL   ] :: Command 'systemctl --root=/mnt reenable  foo@tty4.service 2>&1 | grep -q 'Created symlink'' (Expected 0, got 1)
:: [   FAIL   ] :: Command 'systemctl --root=/mnt is-enabled foo@tty4.service' (Expected 0, got 1)
:: [   LOG    ] :: Duration: 2s
:: [   LOG    ] :: Assertions: 20 good, 21 bad
:: [   FAIL   ] :: RESULT: Enable unit in /usr via symlink


```

**Comment by poettering** [comment]
What are "all necessary cases"? Can you please write down what happens what should not happen or what doesn't happen that should happen? Something I can reproduce easily...

**Comment by msekletar** [comment]
Just from top of my head here is the list of things I deem are necessary to implement correctly,
- `enable` must work for symlink which is absolute (`/usr/lib/systemd/system/mdns.service -> /usr/lib/systemd/system/avahi-daemon.service`)
- `enable`must work for relative symlink (`/usr/lib/systemd/system/mdns-relative.service -> avahi-daemon.service`)
- it must be possible to enable instance via symlink to template (`foo@.service -> getty@.service`)
- `is-enabled` must return correct status for all cases
-  `disable` must do the right thing for all cases
- all verbs must work correctly when code is invoked from `systemctl --root`
- code should be robust to handle misconfiguration, e.g.

```
foobar.service
[Install]
WantedBy=multi-user.target
Also=baz.service
```

and `baz.service -> foobar.service`
systemd must not enter some busy loop or crash

**Comment by poettering** [comment]
I force-pushed a new version now. Note that it's based on #1737, which is hence included in this PR, but please ignore this here, and look at #1737 for that. That PR should be merged before this one. 

@msekletar I think I fixed everything you pointed out now. I also added a proper test that tests all that, so that we can verify that all is good. Please check out if everything works for you now, and if not, let me know specifically which is missing so that we can add testcases for that too.

**Comment by msekletar** [comment]
@poettering If you enable instance via symlink then you can't disable it. There is no error but systemd doesn't do anything. Looks OK, otherwise.

```
-bash-4.3# systemctl enable foo@tty4.service
Created symlink from /etc/systemd/system/getty.target.wants/getty@tty4.service to /usr/lib/systemd/system/getty@.service.
-bash-4.3# systemctl disable foo@tty4.service
-bash-4.3#
```

**Comment by poettering** [comment]
OK, I force-pushed a new version. One that hopefully is liked by semaphore too. It fixes the disable issue you pointed out, too, @msekletar.

If semaphore likes it, I'd really like to see this one commited, before we do any further fixing on it. With the tests this includes we have a verification that it does what it is supposed to do better than we ever had...

**Comment by poettering** [comment]
Nice, semaphore likes it too now. Yay!

**Comment by zonque** [comment]
Ok, this has been around for a while and it looks all sane to me, so I'll just merge it now. @msekletar, if you spot any other things, please open a new PR and also extend the test suite along with the fix :)

**Comment by poettering** [comment]
AWESOME! Thanks for merging!

@msekletar yes, please give this a whirl. If you find anything, would be cool to prep some new tests for test-install-root that fail, but which should not, and pass those to me, and I'll look into them. For me it's much easier if whatever is left now we can just fix as it comes up, and always immediately stabilize things with tests.

**Comment by msekletar** [comment]
@poettering everything seems to work as expected.

**Comment by poettering** [comment]
Excellent! Thanks for testing! And thanks for prepping the initial patches. In the end adding this turned out to be a much more complex job than I initially thought, hence I hope it's OK I took this over.

**Comment by msekletar** [comment]
Your help with this was much appreciated. Thanks!

**Pull request merged**
