### PR TITLE
meson: make user $PATH configurable

### LINKED ISSUE #13469: Make bin-sbin flipping optional and configurable
as per comments on https://github.com/systemd/systemd/pull/13406

### PR DESCRIPTION
**Pull request by keszybz**
This partially reverts db11487d1062655f17db54c4d710653f16c87313 (the logic to
calculate the correct value is removed, we always use the same setting as for
the system manager). Distributions have an easy mechanism to override this if
they wish.

I think making this configurable is better, because different distros clearly
want different defaults here, and making this configurable is nice and clean.
If we don't make it configurable, distros which either have to carry patches,
or what would be worse, rely on some other configuration mechanism, like
/etc/profile. Those other solutions do not apply everywhere (they usually
require the shell to be used at some point), so it is better if we provide
a nice way to override the default.

Fixes  #13469.

### CODE REVIEW

**Comment by poettering** [comment]
Ci doesn#t like this... 

(still think we are supporting this too well, we should just kill this off in all distros, but ok)

Can we maybe add a taint flag for this too though? i.e. just do an streq() on the two paths and then expose this as another taint flag

**Comment by keszybz** [comment]
> Ci doesn#t like this...

Seems to be the ternary operator thing in old meson again.
I'll repush shortly.

> Can we maybe add a taint flag for this too though? i.e. just do an streq() on the two paths and then expose this as another taint flag

But why do we care? It doesn't matter for anything that systemd does, and only makes a difference for user services. If the distro sets this option, then they clearly do it on purpose. The man page already says that the order should not be relied on, and maintainers generally get that this is not recommended, but need this because of legacy stuff.

**Comment by poettering** [comment]
CI doesn't like it...

the taint thing is psychological trick: it looks ugly thus pushing people towards cleaning this up.

**Comment by keszybz** [comment]
> the taint thing is psychological trick: it looks ugly thus pushing people towards cleaning this up.

Sorry, I don't think it brings any value.

**Comment by keszybz** [comment]
I'll go ahead and merge this. The technical side of the patch is simple enough, and if it builds, it must work.

**Pull request merged**
