### PR TITLE
networkd: ship a default network file that matches all VRFs

### LINKED ISSUE #4308: VRF devices added, but not brought up
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu
### In case of bug report: Expected behaviour you didn't see

> …
### In case of bug report: Unexpected behaviour you saw

> vrf1: <NOARP,MASTER> mtu 65536 qdisc noop state DOWN mode DEFAULT group default qlen 1000
### In case of bug report: Steps to reproduce the problem

> Add a VRF device and try to pass traffic thru.

### PR DESCRIPTION
**Pull request by andir**
This fixes #4308

### CODE REVIEW

**Comment by poettering** [comment]
Hmm, this would mean networkd would by default manage all VRF devices. Is this really something we should do by default? People might want to create/manage VRF devices outside of the networkd scope too, no?

So far we didn't ship much default configuration with networkd (with some minor and very specific exceptions), following the logic, that in order to make networkd manage something the user first should tell it so, but by default we stay away. Can you elaborate why it would make sense to depart from that for VRF devices?

**Comment by andir** [comment]
The real issue, for me at least, here is there doesn't seem to be a
generic approach in managing link-state within systemd yet. If there
would be a setting allowing people to explicitly set
`State=Up`/`State=Down` or similar we could probably fix the whole issue
by documenting an example that also covers the link state.

On a side note: People can and also might want to add IPs on the VRF
interface - to manage VRF internal loopback addresses - which will also
set the interface up.

On 01:46 31.08.17, Lennart Poettering wrote:
> Hmm, this would mean networkd would by default manage all VRF devices. Is this really something we should do by default? People might want to create/manage VRF devices outside of the networkd scope too, no?

That is an issue that spans more then just VRFs IMO. A `[Match]` block
that matches networkd managed links/netdevs could potentially be handy
here?.

On 01:46 31.08.17, Lennart Poettering wrote:
> So far we didn't ship much default configuration with networkd (with some minor and very specific exceptions), following the logic, that in order to make networkd manage something the user first should tell it so, but by default we stay away. Can you elaborate why it would make sense to depart from that for VRF devices?

I am also not in favor of shipping more default configuration. Should
There be a generic way to handle interface state then? People might want
to explicitly disable a specific interface - since they are just
preparing a new customer service or whatever that can't be active yet.

An issue with the proposed change is that networkd will try to do DHCP
on the VRF interface? So setting `DHCP=no`, `AcceptRA=no` would be sane if
this PR is to be merged?

**Comment by poettering** [comment]
> That is an issue that spans more then just VRFs IMO. A `[Match]` block that matches networkd managed links/netdevs could potentially be handy here?.

Well, the idea is that hvaing a [Match] section somewhere that matches an iface is what makes it managed.  Hence having a match in [match] section that checks if something is managed is recursive ;-)

**Comment by poettering** [comment]
Note that my understanding of VRF is very limited, but I have the suspicion that people who drop in a .netdev for a VRF device should also drop in a .network at the same time,to make sure it is up...

Basically, anything that has a matching .network file will be put up by networkd, and everything that hasn't is left untouched

**Comment by andir** [comment]
It is probably just about convenience then. So some documentation should be the right approach here.
In all non-toy cases that I can come up with you'll want to put either
- static routes on a VRFs routing table, which you can by using a `systemd.network(5)` file that matches the VRF (and currently, redundantly specifying the table)
- or have IP-Addresses on an VRF (and potentially an external routing daemon taking care routes in the VRF).

I know of at least @flokli and @dsahern that might have opinions on this topic. Maybe they can comment on this?

**Comment by flokli** [comment]
Automatically bringing the VRF interface up - either by configuring routes statically or via a routing daemon seems to be a sensible behaviour for me.

Doing this by shipping such .network file with systemd is actually what I suggested to @andir yesterday ;-)
It's much cleaner than doing it hard-coded, and if somebody still wants to keep the interface down (for reasons I currently can't think of), it's as easy as dropping in a . network file which gets matched before. Configuring static routes doesn't hurt either, as user's rules get most likely matched before too.

Actually, it's the same way things are done for systemd-nspawn containers.

Of course, this needs to be documented, and DHCP and IPv6AcceptRA disabled.

**Comment by poettering** [comment]
> Doing this by shipping such .network file with systemd is actually what I suggested to @andir yesterday

Well, the issue I have with this is not that I wouldn't want to make it easy for people, but simply that so far we don't do blanket configuration by default (and such a .network file would be that), but instead say that whatever isn't explicitly managed by networkd is not managed by it, so that people can run networkd and NetworkManager or whatever else they want in parallel if they feel like it. And unless you actually configured networkd to control one specific interface it won't control it. But if we install a .network file that matches all VRF interfaces, then this would mean we'd also manage foreign VRF interfaces, i.e. something people might have created via NetworkManager and want to manage with NetworkManager and not networkd. 

It appears to me that this is mostly a documentation issue, and we shouldn't ship anything by default there...

**Comment by ssahani** [comment]
I agree with @poettering  here.

**Pull request closed without merging**
