### PR TITLE
RFC: Use dbus 1.10.0 user bus when kdbus is unavailable

### PR DESCRIPTION
**Pull request by heftig**
These two commits make the minimum amount of changes needed to run GNOME 3.16 with dbus 1.10.0's user bus.

I don't actually expect this to get merged, since it breaks the legacy session bus setup. Still, I would like to know whether support for a dbus-daemon user bus is desired or if it is going to be neglected in favor of focusing on delivering a kdbus user bus.

### CODE REVIEW

**Comment by teg** [comment]
Without looking at the patches: any chance this can be made to pick nicely between the session and user bus, depending on how the dbus-daemon was compiled? In that case it should be really unintrusive...

**Comment by heftig** [comment]
I'm not sure how to do that at the moment. I guess `export_legacy_dbus_address` would have to return early if `dbus.socket` is not running, similar to what it did when kdbus is unavailable.

Can pam_systemd talk to the user manager?

**Comment by heftig** [comment]
Oh, and all `--enable-user-session` does is install `dbus.socket` and `dbus.service` and statically enable the former.

**Comment by dvdhrm** [comment]
Much appreciated! I also planned doing this, but haven't come around, yet. Please have a look at [1], @smcv commented on exactly this issue. Apparently, you don't need `DBUS_SESSION_BUS_ADDRESS` at all, it's tried by default. The bigger issue is, `gdm` and friends spawn a session-bus if this variable is not set. So I think the proper fix would be to make gdm run `access("/run/user/uid/bus", F_OK)`.

I'm not sure who else spawns dbus-daemon, but there might be some more (like gnome-session, et. al.). So I wonder whether pam_systemd should just do `access(...)` on the user-bus and then explicitly set `DBUS_SESSION_BUS_ADDRESS` if available. Something like this:

``` c
_cleanup_free_ char *userbus = NULL;

userbus = strjoin(runtime, "/bus", NULL);
if (!userbus) {
        pam_syslog(handle, LOG_ERR, "Out of memory");
        return PAM_BUF_ERR;
}

if (is_kdbus_available())
        r = asprintf(&s, KERNEL_USER_BUS_ADDRESS_FMT ";" UNIX_USER_BUS_ADDRESS_FMT, uid, runtime);
else if (access(userbus, F_OK) >= 0)
        r = asprintf(&s, UNIX_USER_BUS_ADDRESS_FMT, runtime);
else
        return PAM_SUCCESS; /* skip export for legacy session-bus */

if (r < 0) {
        pam_syslog(handle, LOG_ERR, "Failed to set bus variable.");
        return PAM_BUF_ERR;
}
```

[1] http://thread.gmane.org/gmane.comp.sysutils.systemd.devel/33853/focus=33862

**Comment by dvdhrm** [comment]
Revised diff:

``` c
diff --git a/src/login/pam_systemd.c b/src/login/pam_systemd.c
index f83d18b..b1388ac 100644
--- a/src/login/pam_systemd.c
+++ b/src/login/pam_systemd.c
@@ -179,24 +179,33 @@ static int export_legacy_dbus_address(
                 const char *runtime) {

         _cleanup_free_ char *s = NULL;
-        int r;
+        int r = PAM_BUF_ERR;

-        /* skip export if kdbus is not active */
-        if (!is_kdbus_available())
-                return PAM_SUCCESS;
+        if (is_kdbus_available()) {
+                if (asprintf(&s, KERNEL_USER_BUS_ADDRESS_FMT ";" UNIX_USER_BUS_ADDRESS_FMT, uid, runtime) < 0)
+                        goto error;
+        } else {
+                s = strjoin(runtime, "/bus", NULL);
+                if (!s)
+                        goto error;
+
+                if (access(s, F_OK) < 0)
+                        return PAM_SUCCESS;

-        if (asprintf(&s, KERNEL_USER_BUS_ADDRESS_FMT ";" UNIX_USER_BUS_ADDRESS_FMT, uid, runtime) < 0) {
-                pam_syslog(handle, LOG_ERR, "Failed to set bus variable.");
-                return PAM_BUF_ERR;
+                s = mfree(s);
+                if (asprintf(&s, UNIX_USER_BUS_ADDRESS_FMT, runtime) < 0)
+                        goto error;
         }

         r = pam_misc_setenv(handle, "DBUS_SESSION_BUS_ADDRESS", s, 0);
-        if (r != PAM_SUCCESS) {
-                pam_syslog(handle, LOG_ERR, "Failed to set bus variable.");
-                return r;
-        }
+        if (r != PAM_SUCCESS)
+                goto error;

         return PAM_SUCCESS;
+
+error:
+        pam_syslog(handle, LOG_ERR, "Failed to set bus variable.");
+        return r;
 }

 _public_ PAM_EXTERN int pam_sm_open_session(
```

**Comment by dvdhrm** [comment]
Pushed with my modifications. Thanks a lot! 3df49c2877757d41e8b00adf697735837b8f6c07

**Pull request closed without merging**
