### PR TITLE
A couple of performance tweaks for TEST-64 under QEMU

### PR DESCRIPTION
**Pull request by mrc0mmand**
Today I noticed that the LVM-related test cases from TEST-64 are being skipped in the C8S job, since the AWS machines don't have LVM tools installed by default. However, after installing the necessary packages, `testcase_lvm_basic` takes an ungodly amount of time to finish (almost half an hour).

I also noticed that the whole TEST-64 now takes twice as much time as it used to (~29 minutes vs ~15 minutes). This all boils down to 9c126b2c92c220fb7e87591d10a4f87e1d2d6f12 as each `check_device_units()` takes around 45 seconds (on an unaccelerated machine) and we do quite a lot of them (via `helper_check_device_units`). I tested a couple of tweaks and the most noticeable one - dropping `dev-tty*.device` units from the device list - drop the runtime of `check_device_units()` to ~25 seconds, which should help with the runtime of all test cases that call this helper.

The other commits reduce the runtime of the `testcase_lvm_basic` even further, .e.g:
 - current main: ~27 minutes
 - \+ ac856adc5d11681c5ceeb09ed5c6657c7e94121e: ~17 minutes
 - \+ c665d4bb15cd6c4e48175d5c27a07f40848012de: ~13 minutes
 - \+ 5e7e26247f6bf8e0dd96c32ac15b5686bb1621a5: ~12.5 minutes

Dropping the `helper_check_device_units` calls completely drops the runtime all the way down to ~7.5 minutes, but I wouldn't go that way, since the helper is quite useful, and the performance hit is present only without acceleration. I still naively hope AWS will one day support nested virt like the other bigger cloud providers.

Once this is merged I'll install LVM tools in the C8S job and test it further, if the overall test runtime is in some reasonable bounds, before unleashing it into the production.

/cc @yuwata

### CODE REVIEW

**Review by yuwata — APPROVED** [review]
LGTM.

**Comment by yuwata** [comment]
(BTW, I noticed TEST-64 is not running with the sanitizer now. IIRC previously it was, no?)

**Comment by mrc0mmand** [comment]
> (BTW, I noticed TEST-64 is not running with the sanitizer now. IIRC previously it was, no?)

I thought that as well, interesting. I'll look into adding it back (or adding it there at all, looks like it managed to slip my mind).

**Comment by mrc0mmand** [comment]
And just a side-note - TEST-64 with lvm-related tests enabled runs for about 50 minutes (without KVM), but after applying https://github.com/systemd/systemd-centos-ci/pull/556 the runtime of the whole job is actually 5 - 10 minutes shorter (thanks, parallelization!), so I don't think it's necessary to dig into performance tweaks any further, at least for now.

**Pull request merged**
