### PR TITLE
test: tape over weird debian build/test system

### PR DESCRIPTION
**Pull request by poettering**
This is something Debian should really address in their test system, not us. But not sure, apparently some people think asking them to fix this is not a workable approach.

Hence, let's work around this, simply disable the test case in such an environment, as the results would not be useful anyway.

### CODE REVIEW

**Review by bluca — CHANGES_REQUESTED** [review]
Unfortunately, this doesn't work. I tried it already, but the test still ran and failed:

https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=amd64&ver=257%7Erc2-2&stamp=1731722898&raw=0

Can you think of any other condition that this test expects from the runtime environment, that could be checked instead?

**Comment by poettering** [comment]
we do have ci_environment() to detect certain CI environments and work around them. But frankly I am not convinced we should add use that here, given this is no a CI environment, and apparently there's no appetite in Debian to hook their test environments up with upstream. Hence, if they don't invest the resources, we don't need to special case their systems...

**Comment by DaanDeMeyer** [comment]
Can we please just merge https://github.com/systemd/systemd/pull/35256 so that those logs will just tell us what error is actually being returned? So much ado when we have a trivial way to get a better error message from the assertion

**Comment by poettering** [comment]
but anyway, if the chroot dtection is not working, then apparently my analysis from the distance is wrong. I have no idea what they are doing then? it's impossible for anyone but you to determine details on this i fear.

**Comment by bluca** [comment]
> but anyway, if the chroot dtection is not working, then apparently my analysis from the distance is wrong. I have no idea what they are doing then? it's impossible for anyone but you to determine details on this i fear.

Once again: it is not possible for me either! I cannot access these systems. We are in the same boat. Hence why I am asking you, who did the full change: are you aware of any other specific environmental condition that this test requires in order to run successfully, that we could check for instead? Some kernel capability, something at runtime - does it need logind running? Does it need systemd running? Does it need the kernel configured in some specific way? A specific kernel version (these build systems run on very very old ELTS kernels, this is probably 4.19 or 5.4)? Is there anything at all that you can think of?

**Comment by bluca** [comment]
> > but anyway, if the chroot dtection is not working, then apparently my analysis from the distance is wrong. I have no idea what they are doing then? it's impossible for anyone but you to determine details on this i fear.
> 
> Once again: it is not possible for me either! I cannot access these systems. We are in the same boat. Hence why I am asking you, who did the full change: are you aware of any other specific environmental condition that this test requires in order to run successfully, that we could check for instead? Some kernel capability, something at runtime - does it need logind running? Does it need systemd running? Does it need the kernel configured in some specific way? A specific kernel version (these build systems run on very very old ELTS kernels, this is probably 4.19 or 5.4)? Is there anything at all that you can think of?

So let's try and speed along this analysis. As per the log attached to https://github.com/systemd/systemd/issues/35249

```
/* test_audit_loginuid_from_pid */
self audit session id: 11
Assertion 'audit_session_from_pid(&pid1, &sessionid) == -ENODATA' failed at src/test/test-audit-util.c:31, function test_audit_loginuid_from_pid(). Aborting.
```

That means we are _not_ getting the output from this message:

https://github.com/systemd/systemd/blob/52b0351a154e9ad3f6a62c5de61198e454d86ecb/src/test/test-audit-util.c#L14-L17

Which means we don't have a valid loginuid.

Then it asserts that pid1 does not have a loginuid, and this passes, so it doesn't.

https://github.com/systemd/systemd/blob/52b0351a154e9ad3f6a62c5de61198e454d86ecb/src/test/test-audit-util.c#L19

We are getting this one though:

https://github.com/systemd/systemd/blob/52b0351a154e9ad3f6a62c5de61198e454d86ecb/src/test/test-audit-util.c#L22-L25

which means the unit test process has a valid sessionid, right?

Then the assert is hit:

https://github.com/systemd/systemd/blob/52b0351a154e9ad3f6a62c5de61198e454d86ecb/src/test/test-audit-util.c#L27

Why does this unit test ran at build time expect pid1 in the build system shouldn't have a sessionid? This could be a stub init from an unknown and unspecified container manager. Is it reasonable to universally expect this not to be the case, on all package build systems in the world? And what is the purpose of such an assertion? What is it testing? Can it be tested in a different way? Or is it expecting systemd to be pid1? If so, it should mark the test case with the existing `.sd_booted = true` to automatically skip when not ran in a systemd system

**Comment by bluca** [comment]
> > That means we are _not_ getting the output from this message:
> > https://github.com/systemd/systemd/blob/52b0351a154e9ad3f6a62c5de61198e454d86ecb/src/test/test-audit-util.c#L14-L17
> 
> That's a wrong analysis. That's the output we _do_ get.

Where?

```
/* test_audit_loginuid_from_pid */
self audit session id: 11
Assertion 'audit_session_from_pid(&pid1, &sessionid) == -ENODATA' failed at src/test/test-audit-util.c:31, function test_audit_loginuid_from_pid(). Aborting.
```

It's the "session id" one, not the "login uid" one? Where do you see the "login uid" message in that log?

**Comment by poettering** [comment]
> Why does this unit test ran at build time expect pid1 in the build system shouldn't have a sessionid? 

Container managers generally reset the audit if they can so that it doesn't leak into the containers. If you are entirely unpriv you cannot do that however, hence the PR this is all triggered by looks for a container env, and if so just ignores the audit stuff.

That doesn't work inside your frankenbuildsystem however apparently, it doesn't let us know it's in a container.

hence we just don't know and cannot know that the audit id is garbage.

So I think https://salsa.debian.org/debian/sbuild/-/blob/main/bin/sbuild-usernsexec is their own container manager in perl that causes this. It's not resetting audit and is not recognizable by us, hence the test fails. You suggest that sbuild-usernsexec is *not* what they are using though, but it certainly would fit the pattern.

(I originally wasn't prepared for the fact that ubuntu reimplemented their own container runtime in perl, that sounded too crazy too me, but I tink now I was wrong on that)

**Comment by bluca** [comment]
> (I originally wasn't prepared for the fact that ubuntu reimplemented their own container runtime in perl, that sounded too crazy too me, but I tink now I was wrong on that)

Well you might want to sit down before reading any further then: _there are multiple ones_ actually

**Comment by bluca** [comment]
> Container managers generally reset the audit if they can so that it doesn't leak into the containers. If you are entirely unpriv you cannot do that however, hence the PR this is all triggered by looks for a container env, and if so just ignores the audit stuff.
> 
> That doesn't work inside your frankenbuildsystem however apparently, it doesn't let us know it's in a container.
> 
> hence we just don't know and cannot know that the audit id is garbage.

We cannot expect random systems to do anything. You can make some reasonable assumptions if systemd is being booted, or if any of the systemd-specific protocols like $container are used, because at that point you can set some rules. But this stuff is not mandatory, people can or cannot use it and there is absolutely nothing anybody can do about it. So asserting on such state is not the right thing to do in a unit test. The purpose of the unit test is not to test the environment, it's to tes the code that was just built. It would be like asserting that it has privileges to create new namespaces or something - it might be possible, or it might not.

**Comment by poettering** [comment]
Closing, since this supposedly doesn't work, and the ns inode check seems like the much better fix.

**Pull request closed without merging**
