### PR TITLE
Various test/test-functions fixes/improvements

### PR DESCRIPTION
**Pull request by mrc0mmand**
Follow up for discussion in #12861. Thanks a lot to @evverx for the pointers and explanations.

### CODE REVIEW

**Comment by evverx** [comment]
What I don't understand though is what happens when a binary is installed into `/lib` with `ninja install` while a unit file refers to `/usr/lib` and `find_binary` can find `/usr/lib/binary` on the host (assuming `/lib` and `/usr/lib` aren't the same).

**Comment by mrc0mmand** [comment]
> What I don't understand though is what happens when a binary is installed into `/lib` with `ninja install` while a unit file refers to `/usr/lib` and `find_binary` can find `/usr/lib/binary` on the host (assuming `/lib` and `/usr/lib` aren't the same).

In that case the check from 3cdb93d would fail and so would the rest of the checks. But I'm not sure if we should expect the meson/ninja is correctly configured on a system with split /usr or fix it on our side (e.g. by adding the paths from the image to the `PATH` and then trying to find the binary using only its name). I'd say the former.

**Comment by evverx** [comment]
I agree the script shouldn't try to fix it. I think it should fail loudly if `meson install` and the unit files aren't in sync (which is what happened in #12861 as far as I can tell).

Anyway, talking to imagine that weirdly specific scenario I forgot to say that the PR looks good to me.

**Comment by keszybz** [comment]
Yep, a nice cleanup. Thank you for the detailed comments on commits.

**Pull request merged**
