### PR TITLE
ci: move the Coverity job to GitHub Actions

### PR DESCRIPTION
**Pull request by mrc0mmand**
Note: this branch was intentionally created directly in the upstream repo, otherwise I wouldn't have access to the Actions secrets to test this properly.

### CODE REVIEW

**Comment by bluca** [comment]
Looks like it's completing successfully? Nice!

**Comment by evverx** [comment]
I wonder what happened to Travis? :-) Wouldn't it be enough to get rid of docker there?

Also, should it be guarded somehow to protect the systemd organization on Coverity from forks  (where GitHub actions are usually turned on by default) sending their builds at the same time?

**Comment by bluca** [comment]
> I wonder what happened to Travis? :-) Wouldn't it be enough to get rid of docker there?
> 
> Also, should it be guarded somehow to protect the systemd organization on Coverity from forks (where GitHub actions are usually turned on by default) sending their builds at the same time?

There's the change coming for OSS projects where you have to get credits and things like that, so there was consensus to move to actions to avoid the hassle

**Comment by evverx** [comment]
Thanks! I didn't know that.

I'd probably add a kludge like https://github.com/systemd/systemd/pull/15842/files just in case.

**Comment by mrc0mmand** [comment]
> I'd probably add a kludge like https://github.com/systemd/systemd/pull/15842/files just in case.

Good point, added!

**Comment by mrc0mmand** [comment]
> > I'd probably add a kludge like https://github.com/systemd/systemd/pull/15842/files just in case.

Good point, added!

> Also, should it be guarded somehow to protect the systemd organization on Coverity from forks (where GitHub actions are usually turned on by default) sending their builds at the same time?

This (hopefully) shouldn't happen, since the forks don't have access to the repo secrets (where the token is kept). But the *kludge* is definitely a good idea, just in case.

**Comment by evverx** [comment]
@mrc0mmand could you also delete the travis badge from README and all the leftover scripts from `travis-ci/`?

**Comment by bluca** [comment]
needs a rebase

**Comment by mrc0mmand** [comment]
> needs a rebase

Ahhh, thanks, I accidentally pushed the rebase to the wrong remote, *sigh*.

**Pull request merged**
