### PR TITLE
travis: make the ASan & UBsan job a little bit stricter

### PR DESCRIPTION
**Pull request by evverx**
This should be merged after https://github.com/systemd/systemd/pull/10798.

### CODE REVIEW

**Comment by poettering** [comment]
i guess this can be merged now? or dou you want to rebase first?

**Comment by evverx** [comment]
@poettering for some unknown reason TravisCI has stopped showing the build log. I'm trying to figure out what's going on. Apart from that, `test-journal-match` is failing with
```
Found container virtualization none.
Considering root directory '/run/log/journal'.
Considering root directory '/var/log/journal'.
Root directory /var/log/journal added.
Considering directory '/var/log/journal/c50f1e752cffc76e8fe7da1e58afe936'.
Directory /var/log/journal/c50f1e752cffc76e8fe7da1e58afe936 added.
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
File /var/log/journal/c50f1e752cffc76e8fe7da1e58afe936/system.journal added.
Considering root directory '/var/log/journal/remote'.
Assertion 'match_is_valid(data, size)' failed at ../src/journal/sd-journal.c:252, function sd_journal_add_match(). Ignoring.
Assertion 'match_is_valid(data, size)' failed at ../src/journal/sd-journal.c:252, function sd_journal_add_match(). Ignoring.
Assertion 'match_is_valid(data, size)' failed at ../src/journal/sd-journal.c:252, function sd_journal_add_match(). Ignoring.
Assertion 'match_is_valid(data, size)' failed at ../src/journal/sd-journal.c:252, function sd_journal_add_match(). Ignoring.
Assertion 'match_is_valid(data, size)' failed at ../src/journal/sd-journal.c:252, function sd_journal_add_match(). Ignoring.
=================================================================
==21551==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fccd32000a4 at pc 0x7fccdcab5769 bp 0x7ffc04cc46c0 sp 0x7ffc04cc3e68
READ of size 5 at 0x7fccd32000a4 thread T0
    #0 0x7fccdcab5768  (/lib64/libasan.so.4+0x5a768)
    #1 0x7fccdc011ea8 in startswith ../src/basic/string-util.h:63
    #2 0x7fccdc0134de in match_is_valid ../src/journal/sd-journal.c:164
    #3 0x7fccdc01441a in sd_journal_add_match ../src/journal/sd-journal.c:252
    #4 0x55ee65f346f6 in main ../src/journal/test-journal-match.c:27
    #5 0x7fccda37ffe9 in __libc_start_main (/lib64/libc.so.6+0x20fe9)
    #6 0x55ee65f34049 in _start (/build/build/test-journal-match+0x2049)

Address 0x7fccd32000a4 is located in stack of thread T0 at offset 164 in frame
    #0 0x55ee65f34232 in main ../src/journal/test-journal-match.c:14

  This frame has 4 object(s):
    [32, 40) 'j'
    [96, 104) 't'
    [160, 164) '<unknown>' <== Memory access at offset 164 overflows this variable
    [224, 229) '<unknown>'
```

**Comment by poettering** [comment]
> @poettering for some unknown reason TravisCI has stopped showing the build log. I'm trying to figure out what's going on. Apart from that, `test-journal-match` is failing with

Can't reproduce this here when building with asan?

**Comment by evverx** [comment]
@poettering regarding `test-journal-match`, that was built with an ancient version of ASan and can safely be ignored.

**Pull request merged**
