### PR TITLE
Test CentOS CI & systemd-networkd under sanitizers

### PR DESCRIPTION
**Pull request by mrc0mmand**
Reference: https://github.com/systemd/systemd-centos-ci/pull/117

cc @evverx

### CODE REVIEW

**Comment by evverx** [comment]
Looks like it works in the sense that all the issues were caught but (and maybe it's just me) I think it's somewhat hard to find the log to look at at https://ci.centos.org/job/systemd-pr-build-vagrant-sanitizers/928/artifact//systemd-centos-ci/index.html. Would it be possible to get Clippy to provide links (or are those links at the end only)? Another option would be to extract backtraces and show them at https://ci.centos.org/job/systemd-pr-build-vagrant-sanitizers/928/console.

@yuwata could you take a look?

**Comment by mrc0mmand** [comment]
@evverx I told myself the same thing and I'd like to do both - extract the errors and tell the user where the errors were extracted from.

**Comment by evverx** [comment]
```
/ Found   3 sanitizer errors (  0 ASan,   3  \
| UBSan,   0 MSan). Looks like you need to   |
\ look at the log                            /
 --------------------------------------------
 \
  \
     __
    /  \
    |  |
    @  @
    |  |
    || |/
    || ||
    |\_/|
    \___/
```
Looks like it's working :-)

**Comment by mrc0mmand** [comment]
> ```
> / Found   3 sanitizer errors (  0 ASan,   3  \
> | UBSan,   0 MSan). Looks like you need to   |
> \ look at the log                            /
>  --------------------------------------------
>  \
>   \
>      __
>     /  \
>     |  |
>     @  @
>     |  |
>     || |/
>     || ||
>     |\_/|
>     \___/
> ```
> 
> Looks like it's working :-)

Perfect, let's close this one then :-)

**Pull request closed without merging**
