### PR TITLE
journal: support forwarding to syslog without CAP_SETUID and CAP_SETGID

### PR DESCRIPTION
**Pull request by cmtm**
Journald can forward messages to syslog when CAP_SYS_ADMIN is missing,
but not when CAP_SETUID or CAP_SETGID are missing. Prevent journald from
forging UNIX credentials at all when the first forwarding attempt fails.
This allows forwarding to work when journald has none of [CAP_SYS_ADMIN,
CAP_SETUID, CAP_SETGID].

### CODE REVIEW

**Comment by cmtm** [comment]
Tested with rsyslog.

I'm not aware of a situation where having the forged uid and gid while having the wrong forged pid would be useful to a syslog daemon. If someone knows of a such a situation, this change will have to be revisited.

**Comment by poettering** [comment]
rsyslog can take the sending uid/gid into account, afaik. We shouldn't drop that.

I mean, it's not that we pass fake data on here. We either pass the full data on, or the full data minus the PID, and even in that case we set a PID that is our own, which isn#t entirely wrong hence.

Moreover the systemd-journald.service unit file actually lists the necessary caps, so why this all?

**Comment by cmtm** [comment]
I'm trying to run journald with more restricted permissions. This isn't something that would be applicable to most systemd users. As you mentioned, journald should be running with all appropriate permissions.

I figured upstream might be interested in this change because I find it a bit inconsistent to support forwarding without CAP_SYS_ADMIN, but not without CAP_SET{U,G}ID. If some of expected caps are missing, it's more likely that others are too.

I could always change the patch to remove the ucred struct only after the second sendmsg fails with EPERM again, but I think that would be a bit overkill for handling a case that shouldn't happen on normally configured systems.

**Comment by cmtm** [comment]
Also, note that when journald doesn't send ucred, syslog can still read journald's credentials from the message since the kernel adds them when the sender doesn't explicitly add them.

**Comment by poettering** [comment]
Adding the second fallback sounds OK to me, if you want to prep a patch for that. You could even cache this and then no bother again.

I am pretty sure we shouldn't corrupt the ucreds needlessly though and pass along as much correct ucreds as we can.

(Note that the forwarding logic is probably not the way anyway to do a journal-to-classic-syslog gateway anymore btw. I know debian does that, but at least on fedora it's handled differently: there rsyslog pulls the data directly from the journal and thus can take benefit from authenticated metadata and early boot logging correctly)

**Comment by cmtm** [comment]
I thinking of explicitly checking capabilities, caching them, and sending what we can based on that. This would be cleaner without the "try again" pattern that we're using. The issue with this is that code comment mentions that sendmsg might error if the sender process vanished. I couldn't find a code path where ESRCH would be returned, and I couldn't reproduce it when logging from a process that exits immediately. Do you have any context on this?

**Comment by poettering** [comment]
> I thinking of explicitly checking capabilities, caching them, and sending what we can based on that. This would be cleaner without the "try again" pattern that we're using. The issue with this is that code comment mentions that sendmsg might error if the sender process vanished. I couldn't find a code path where ESRCH would be returned, and I couldn't reproduce it when logging from a process that exits immediately. Do you have any context on this?

last time i checked using SCM_CREDENTIALS on sendmsg() and filling in a bogus PID (i.e. a non-existing one) will result in ESRCH. is that now what you are seeing?

**Comment by cmtm** [comment]
I went and checked again and you're right. I don't know how I missed it before.
In order to implement the check I was suggesting, I'd need to link journald against libcap. Is this something we think is worth doing for such a small edge case?

If we don't link against libcap, things would be a bit complicated, because when we get EPERM, we don't know which subset of {CAP_SYS_ADMIN, CAP_SETUID, CAP_SETGID} we're missing. Sending all allowable data would at worse require trying all 8 possible subsets. Though we can cache the result and so only execute the test once, it, still seems overly complicated.

**Comment by poettering** [comment]
> I went and checked again and you're right. I don't know how I missed it before.
> In order to implement the check I was suggesting, I'd need to link journald against libcap. Is this something we think is worth doing for such a small edge case?

yeah, libcap is fine, we link against it from plenty tools already. it's pretty much part of the base OS

**Comment by poettering** [comment]
that said, why not do sendmsg() and if it doesn't work due to perms try again without? i.e. instead of second guess the kernel with the caps, let the kernel figure out everything on its own, and just fallback gracefully. wouldn't that suffice?

**Comment by cmtm** [comment]
Perhaps I'm misunderstanding you, but retrying upon failure leads to the problem I mentioned above:

> things would be a bit complicated, because when we get EPERM, we don't know which subset of {CAP_SYS_ADMIN, CAP_SETUID, CAP_SETGID} we're missing. Sending all allowable data would at worse require trying all 8 possible subsets. Though we can cache the result and so only execute the test once, it, still seems overly complicated.

This arises due to the requirement you mentioned:
> I am pretty sure we shouldn't corrupt the ucreds needlessly though and pass along as much correct ucreds as we can.

**Comment by poettering** [comment]
urks, maybe i should read things properly when coming back to this PR after a while... sorry ;-)

BTW: we already have a helper have_effective_cap() in around which should make the patch simple. i'd suggest to send with the full ucred data first, then on failure check the three relevant caps and suppress the data these caps indicate can't be send (and cache that) and try again.

**Comment by poettering** [comment]
If there's still interest in this, I think a patch that keeps the UID/GID sending in for the regular case would be OK to merge, with the UID/GID dropping only if that doesn't work either. Let's close for now however. If you are still interested, please rebase, rework and force push and we can open the PR.

**Pull request closed without merging**
