### PR TITLE
kernel-install: export BOOT_ROOT instead of hacking it in hooks, note KERNEL_INSTALL_* ABI

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Draft because on top of #21624 (first commit), otherwise should be okay

Extracted and adapted from #19006

### CODE REVIEW

**Review by keszybz — COMMENTED** [review]
Looks reasonable.

**Comment by nabijaczleweli** [comment]
Rebased, should be g2g

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by AdamWill** [comment]
If I'm reading this right, it changed behaviour. The previous code "preferred" `/boot/loader/entries` to `/boot/efi/$MACHINE_ID`; it checked for `/boot/loader/entries` first and dropped out of the check loop, with settings appropriate to `/boot/loader/entries`, if it found it. The new code "prefers" `/boot/efi/$MACHINE_ID`; it checks for that location first, and if it finds it, drops out of the check loop with setting appropriate to *that* location.

I think this is why my Fedora Rawhide install suddenly started dumping kernel files in `/boot/efi` and bls snippets in `/boot/efi/loader/entries`, where the grub config does not know to look for them (and where my system does not really have room for them, because `/boot/efi` is only 200MB big). I don't know why I have a `/boot/efi/$MACHINE_ID` - I can't yet find any trace of what created it - but I do appear to have one, and it's messing things up.

**Comment by AdamWill** [comment]
This new code combined with https://github.com/systemd/systemd/pull/19006 also has some pretty odd behaviour. For instance, if `/boot/efi/loader/entries` exists but `/boot/efi/$MACHINE_ID` does not, it will still use `/boot/efi` as `BOOT_ROOT` and `/boot/efi/$MACHINE_ID/$KERNEL_VERSION` as `ENTRY_DIR_ABS`. It then seems to write a config snippet to `/boot/efi/loader/entries` that expects the kernel and initrd file to be under `/boot/efi/$MACHINE_ID/$KERNEL_VERSION`, but - because `/boot/efi/$MACHINE_ID` doesn't exist, so the code from #19006 decides the layout is 'other' not 'bls' - doesn't actually create that directory or put any files in it.

**Comment by keszybz** [comment]
I hope that with #22024 we now have sensible behaviour.

**Pull request merged**
