### PR TITLE
v256 batch up to bf34d642bc8daab4e970f83f99ff3a16eebde86a

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by bluca** [comment]
> v256 batch up to bf34d642bc8daab4e970f83f99ff3a16eebde86a

sometimes it's hard to know where to pick up again for the next batch, so I'd like to propose to follow this pattern and note the last main commit inspected when creating a new batch of backports

**Comment by DaanDeMeyer** [comment]
LGTM except the seccomp sandbox commit, I don't think that is backport material.

**Comment by bluca** [comment]
It was requested by the landlock maintainer: https://github.com/systemd/systemd/pull/34552#issuecomment-2383041882

**Comment by DaanDeMeyer** [comment]
OK reasoning from the PR makes sense to me, let's do this then

**Comment by bluca** [comment]
forgot a few commits that were tagged with the label

**Review by DaanDeMeyer — APPROVED** [review]

**Pull request merged**
