### PR TITLE
test-fileio: cast EOF to (char) before comparing with char explicitly

### PR DESCRIPTION
**Pull request by poettering**
EOF is defined to -1, hence on platforms that have "char" unsigned we
can't compare it as-is, except if we accept an implicit cast. let's make
it an explicit cast, acknowledging the issue.

Fixes: #14118

### CODE REVIEW

**Comment by keszybz** [comment]
Yeah, this fixes the warning (tested on arm64). But the test fails:
```
Assertion 'c == chars[i]' failed at src/test/test-fileio.c:644, function void test_fgetc(void)(). Aborting.
Aborted (core dumped)
```

**Comment by keszybz** [comment]
Yeah, the test passes before that commit. Strange.

**Comment by poettering** [comment]
Seems to have passed ARM64 now. The bionic ones timed out for some reason (unrelated I figure)

**Comment by keszybz** [comment]
It's `safe_fgetc()` that is busted.

Oh man, the libc interface is so incredibly bad it's not even funny anymore.

**Comment by mrc0mmand** [comment]
Gave it a try in #13785 and the compilation finished successfully on all mentioned architectures (x86_64, ppc64le, s390x, and aarch64), thanks!

**Comment by poettering** [comment]
@keszybz hmm, safe_fgetc() is busted you say? in which way? it was supposed to be the wrapper around fgetc() that fixes its bad behaviours...

**Comment by keszybz** [comment]
Sorry, I was confused by the fact that by the line `c == EOF || safe_fgetc(f, &c) == 1` — sometimes we'd call ungetc() but skip the matching `safe_getc()` call. Everything seems fnie.

**Pull request merged**
