### PR TITLE
man: Specify when sd_bus_message_read_basic returns 0

### PR DESCRIPTION
**Pull request by igo95862**
The code path that is responsible is here: https://github.com/systemd/systemd/blob/9642983a51c6c866d11092c1e1e2ab9bc3c0df5a/src/libsystemd/sd-bus/bus-message.c#L3372

### CODE REVIEW

**Comment by igo95862** [comment]
I just realized its an incomplete sentence now.

**Comment by igo95862** [comment]
`On success, <function>sd_bus_message_read_basic()</function> a positive integer.`

Do you want me to submit a new PR?

**Comment by keszybz** [comment]
Oops, indeed. Please do.

**Comment by igo95862** [comment]
Done

#17724

**Pull request merged**
