### PR TITLE
network: downgrade log level in conf parsers

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by poettering** [comment]
wow, this is long. but looks good to me.

**Comment by keszybz** [comment]
centos ci (arch in kvm with sanitizers):
```
08:54:37 ======================================================================
08:54:37 ERROR: test_altname (__main__.NetworkctlTests)
08:54:37 ----------------------------------------------------------------------
08:54:37 Traceback (most recent call last):
08:54:37   File "test/test-network/systemd-networkd-tests.py", line 598, in test_altname
08:54:37     self.wait_online(['dummy98:degraded'])
08:54:37   File "test/test-network/systemd-networkd-tests.py", line 545, in wait_online
08:54:37     check_output(*args, env=env)
08:54:37   File "test/test-network/systemd-networkd-tests.py", line 49, in check_output
08:54:37     return subprocess.check_output(command, universal_newlines=True, **kwargs).rstrip()
08:54:37   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
08:54:37     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
08:54:37   File "/usr/lib/python3.8/subprocess.py", line 512, in run
08:54:37     raise CalledProcessError(retcode, process.args,
08:54:37 subprocess.CalledProcessError: Command '['/systemd-meson-build/systemd-networkd-wait-online', '--timeout=20s', '--interface=dummy98:degraded']' returned non-zero exit status 1.
```

**Comment by keszybz** [comment]
I would suspect #16396, but the tests there passed fine. Strange.

**Comment by yuwata** [comment]
I found a mistake. I hope now it is fixed.

**Pull request merged**
