### PR TITLE
G9/G9x change to default resolutions

### PR DESCRIPTION
**Pull request by NoXPhasma**
As @phomes told me, in the hwdb should be only the manufacturer default resolutions, instead of all available. This PR will change it that way.

### CODE REVIEW

**Comment by dvdhrm** [comment]
@phomes, @zonque, can somebody elaborate on this? `70-mouse.hwdb` does not state anything like this. What's the rationale here? It'd be nice if someone can push an explanation to `70-mouse.hwdb`.

**Comment by dvdhrm** [comment]
Oh, and `32000@1000`? Is this real or is this a typo?

(also adding @whot to clarify)

**Comment by NoXPhasma** [comment]
`3200@1000` is real, the G9x can go up to `5700@1000`. That are the default values which are set when I create a new profile on the Logitech Gaming Software, that are also the manufacturer default values.

The DPI values which mouse-dpi-tool of livevdev gives out are not very accurate. It only gives out values from 200 - 2400 in 200 DPI steps. But the G9x goes from 200-5700 in 50 DPI steps.

Here is a screenshot of the LGS: http://i.imgur.com/cq6CJO1.png

**Comment by dvdhrm** [comment]
@NoXPhasma, I see, so someone added additional profiles with more DPI values. Ok, then the patch looks good, except for the `32000` typo. You wrote `32,000` instead of `3,200`. I'll fix this up, if you confirm that this was indeed a typo.

**Comment by NoXPhasma** [comment]
Ohh, yes, that's a typo, my bad. I haven't even recognised it in your post ...

**Comment by dvdhrm** [comment]
No problem! Fixed in 0ac58d849fac9ebe4c17eee4987d37371ebb1c2e.

**Comment by phomes** [comment]
@dvdhrm We use the value in libinput to scale the mice to all have a similar sensitivity roughly equivalent of 1000 DPI. We can only fix the default setting of the mouse, so that it at least works reasonably out of the box.  If the user has manually configured the mouse via software like LGS or libratbag then we should not try to "fix" the mouse for them. I will let @whot update the description so that I do not accidentally write something completely crazy :)

@NoXPhasma I suspect that mouse-dpi-tool is accurate and that the 50 DPI steps claimed by LGS is bogus. Or perhaps the 50 step is achieved in combination of actually changing what the mouse sends back and how the driver on the OS deals with it. Just a guess of course.

**Comment by whot** [comment]
@phomes you're spot-on, we only set the default values for out-of-the-box behaviour. Anything other would require reading the device dynamically (libratbag) or a user-specific configuration with a local hwdb override. I thought I had added the comment to the file, but if not feel free to add it. 
I'm on holidays atm, so I'm a bit slow to reply.

**Comment by dvdhrm** [comment]
Yeah, the comment in 70-mouse.hwdb should be sufficient. I just wasn't sure what "all available resolutions" in this commit-msg meant. But as explained, it referred to configured resolutions.

I'm fine with it the way it is. Sorry for the noise and thanks for the explanations!

**Pull request merged**
