### PR TITLE
Udev vs tmpfiles take 2

### LINKED ISSUE #28653: permissions issues with openzfs
### systemd version the issue has been seen with

254

### Used distribution

Endeavouros

### Linux kernel version used

6.1.39, 6.1.42, 6.4.7

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Excecuting `zpool status` as a normal user generates correct output like 
```
# zpool status zstore
  pool: zstore
 state: ONLINE
  scan: scrub repaired 0B in 06:50:11 with 0 errors on Sat Jul  1 14:27:21 2023
config:

	NAME                       STATE     READ WRITE CKSUM
	zstore                     ONLINE       0     0     0
	  mirror-0                 ONLINE       0     0     0
	    WD40EFRX-WCCaaaa       ONLINE       0     0     0
	    WD40EFRX-WCCbbbb       ONLINE       0     0     0
	  mirror-1                 ONLINE       0     0     0
	    WD40EFRX-WCCcccc       ONLINE       0     0     0
	    WD40EFRX-WCCdddd       ONLINE       0     0     0

errors: No known data errors

```

### Unexpected behaviour you saw

Excecuting `zpool status` as a regular users gives an error message: 
`Permission denied the ZFS utilities must be run as root`

### Steps to reproduce the problem

Upgrading from 253.7-1 -> 254-1 introduces the issue.
Downgrading from 254-1 -> 253.7-1 fixes the issue

See also: https://github.com/openzfs/zfs/issues/15146

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #28653.
Replaces #28681.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @floppym @mrc0mmand @keszybz

**Comment by keszybz** [comment]
LGTM. Let's try this ;)

**Comment by floppym** [comment]
I think systemd-tmpfiles-setup-dev.service also needs to be ordered against systemd-udevd.service, unless I'm missing some indirect relationship.

**Comment by floppym** [comment]
> I think systemd-tmpfiles-setup-dev.service also needs to be ordered against systemd-udevd.service, unless I'm missing some indirect relationship.

Oh, it looks like systemd-tmpfiles-dev.service already has `Before=systemd-udevd.service`.

**Comment by poettering** [comment]
so this pr looks ok to me. but in general, what's our story anyway regarding udev and tmpfiles managing the same device node access modes?

i mean, ideally it would be a good idea if we could run systemd-tmpfiles anytime from the shell and it wouldn't fuck things up. So i guess we really should make sure that whatever is declared in static-nodes-permissions.conf matches what might be listed in any udev rule we ship, so that the order doesn't matter too much in which we run this. Are we there yet?

And secondarily, if people locally configure conflicting access modes I figure the udev one should win, and not be fucked up if people manually run tmpfiles. maybe we should make tmpfiles step away from the mode whenever the inodes already exist, no? i.e. prefix the access mode in static-nodes-permissions.conf with `:`, so that it is only used when creating the inodes initially, but otherwise udev wins?

does that make sense?

**Comment by floppym** [comment]
> i mean, ideally it would be a good idea if we could run systemd-tmpfiles anytime from the shell and it wouldn't fuck things up.

/run/tmpfiles.d/static-nodes.conf seems to consistently use type "c!". The exclamation mark means "only process with systemd-tmpfiles --boot". I would not expect users to call "systemd-tmpfiles --boot" manually.

So long as other any snippets affecting /dev also use the exclamation mark, I think nothing will get "fucked up" under normal usage.

**Comment by poettering** [comment]
good point. but maybe we should still use the `:` prefix on the access mode so that udev/tmpfiles order doesn't matter that much?

**Comment by mrc0mmand** [comment]
> good point. but maybe we should still use the `:` prefix on the access mode so that udev/tmpfiles order doesn't matter that much?

Ah, that's nifty, didn't know about the `:` prefix, neat!

**Comment by floppym** [comment]
Although, that raises another point: the mode specified by `kmod static-nodes --format=tmpfiles` is rather conservative (0600), so we probably _want_ to replace that with something more permissive in many cases.

**Comment by poettering** [comment]
@keszybz @yuwata any opinion on the `:` idea?

**Comment by yuwata** [comment]
@poettering 

> @keszybz @yuwata any opinion on the `:` idea?

That sounds not bad for me. But, may be overkill, as it has `--boot` and we refuse to restart the service.
If you are worried about that systemd-tmpfiles-setup.service may be slow, then splitting the service into two, for /dev and non-/dev may be sufficient.
Another idea is to generate tmpfiles conf from udev rules. Unless if you like the idea or not, I'd like to implement `udevadm dump` or to dump the parsed rules for debugging. Adding `--format=tmpfiles` switch to the command may achieve the idea.

**Pull request merged**
