### PR TITLE
Ensure not-null path pointer before basename() call.

### PR DESCRIPTION
**Pull request by comio**
This fix help to compile with GCC 7.1.

### CODE REVIEW

**Comment by tixxdz** [comment]
Hi thanks for the patch.

I thought that basename() will return the current working dir "." if path is NULL ? is this a custom gcc build ? 

Also this changes the code semantics name used to be set now it will be NULL.

**Comment by comio** [comment]
We have "assert(name || path)" before the invocation of basename().  Then when name will be null then path cannot be null on basename() call.

**Comment by poettering** [comment]
This has been reported before. And is a compiler bug that already has been fixed upstream and in fedoras version of gcc. Please ask your distro to backport thr necessary patches.

**Comment by keszybz** [comment]
Seems like you should carry the patch locally until the compiler is fixed.

**Comment by comio** [comment]
Yes. I'm trying my gentoo with 7.1 in order to discover issues.

Cheers

**Pull request closed without merging**
