### PR TITLE
unit: prioritize module devices

### LINKED ISSUE #23850: sys-module-configfs.device has increased boot time
### systemd version the issue has been seen with

251

### Used distribution

Manjaro 21.3.1 Ruah

### Linux kernel version used

5.10.124-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

I reported the same in another ticket: https://github.com/systemd/systemd/issues/23629#issuecomment-1153250281

The issue has started to appears since I updated to systemd 251;
with systemd 250 my system used to boot quite fast:

```
Startup finished in 1.123s (kernel) + 595ms (initrd) + 558ms (userspace) = 2.277s 
graphical.target reached after 558ms in userspace
```

Now with systemd 251:

```
Startup finished in 1.125s (kernel) + 584ms (initrd) + 1.509s (userspace) = 3.219s 
graphical.target reached after 1.506s in userspace.
```

Output of `systemd-analyze blame`:

https://pastebin.com/Luw1MCM5

The culprit seems to be `sys-module-configfs.device`

Please ask if more info are needed.

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

_No response_

### PR DESCRIPTION
**Pull request by yuwata**
Also, prioritize tty and network devices.

Follow-up for 2336bde96420475ccb054326f27290fa0228f27d

Fixes #23850.

### CODE REVIEW

**Comment by yuwata** [comment]
The reporter of #23850 confirmed that this improves the boot performance, though it still slower than v250, but that's expected.

**Comment by keszybz** [comment]
Looks reasonable.

**Comment by MR-Diamond** [comment]
> The reporter of #23850 confirmed that this improves the boot performance, though it still slower than v250, but that's expected.

Unfortunately i don't confirm: the last boot is as follow:

```
Startup finished in 1.170s (kernel) + 591ms (initrd) + 1.489s (userspace) = 3.252s 
graphical.target reached after 1.486s in userspace.
```

**Comment by MR-Diamond** [comment]
Update: ATM I'm on Systemd v. 256.9, the boot time is even worse:

```
Startup finished in 1.411s (kernel) + 1.310s (initrd) + 3.435s (userspace) = 6.157s 
graphical.target reached after 3.174s in userspace.
```

In the past the boot time was around 2 seconds.

**Pull request merged**
