### PR TITLE
units: remove LogsDirectory specifiers from the default journal namespace service unit

### PR DESCRIPTION
**Pull request by Meulengracht**
It is not necessary to by default specify the LogsDirectory/LogsDirectoryMode and actually breaks (non-)persistent logging.

When set to their current non-empty value (journal/%m.%i), it *always* creates the /var/log/journal/%m.%i path as a part of `setup_exec_directory` in `src/core/execute.c`, no matter what kind of storage mode is requested for the namespaces, which breaks the 'Storage=auto' modifier.

That means removing /var/log/journal, and then starting a process with a log namespace, will automatically create the entire path for that namespace, and make having the following journal namespace config for that namespace useless:

```
[Journal]
Storage=auto
```

since /var/log/journal will always exists, and this makes the logic in `server_init` in `src/journal/journald-server.c` redundant. This should not introduce any side-effects as the default path is already being set in `server_init` if LogsDirectory is not set.

This is only a problem for log namespaces, and not for the default journal, which does not have LogsDirectory/LogsDirectoryMode set by default.

I hope I have gone correctly about this (also adding a test), and not left out any details.

### CODE REVIEW

**Comment by poettering** [comment]
It appears to me you should simply add a drop-in locally, that sets LogDirectory= to the empty string, to disable the default. But your specific way to run this sounds wrong as a default otherwise.

Note the only reason we don't set LogDirectory= for the main journald service is that we allow the journal to run before /var is up. But we don't allow that for the namespaced stuff, so it's a non-issue here.

Sorry, but I am pretty sure we should just close this.

**Comment by Meulengracht** [comment]
> Uh, I am not convinced this is desirable. By specifing LogDirectory= we get clean-up logic via "systemctl clean" and so on, and sooner or later we want quota for that.
> 
> Why does this matter? having an empty dir there, isn't really a problem?

It matters - because as I mentioned this will stop 'Storage=auto' from functioning the intended way (and makes logging from namespaces always persistent which has this setting).

Anyway I can see your points about the rest, I might have been to naive here - I just feel like it's an odd default behaviour to have.

**Comment by poettering** [comment]
Creating the dir in /var/ even when it is not used shouldn't hurt. Also note that we default to Storage=persistent for namespaced journald instance, which is in line I gues with the default value of LogDirectory=.

I guess it might make sense to add a note to journald.conf(5) to say that if Storage= is changed to something else it might make sense to add a drop-in to disable LogDirectory= too.

**Comment by Meulengracht** [comment]
I agree about the note to journald.conf(5) - I think it makes a lot of sense to add this in, to atleast inform people that if they expect their namespaces to log persistant only if /var/log/journal doesn't exist, then it won't work without changing LogsDirectory=.

It feels like wrong to me that systemd is by default interfering with the storage behaviour of the journals. Especially because journald has it's own logic for handling storage creation and cleanup. Also wouldn't introducing quotas (I'm assuming storage quotas?) for journal paths also interfere with the storage mechanisms of the journal? The journals already have settings for controlling size and rates.

You mentioned that it would interfere with the storage cleanup and dependencies for systemd if we set LogsDirectory= to empty by default, couldn't this be solved by making LogsDirectory point to /var/log instead? This would then not interfere with journald storage logic.

**Comment by poettering** [comment]
> It feels wrong to me that systemd is by default interfering with the storage behaviour of the journals. 

In general we want the service manager (i.e the conceptually more privileged component) to enforce limits on service (i.e. the conceptually less privileged component) resources, so that daemons cannot misbehave. Sooner or later this also means we intend to add some basic quota management, so that pid 1 can set the limits, and journald then has to live within them.

> Especially because journald has it's own logic for handling storage creation and cleanup. Also wouldn't introducing quotas (I'm assuming storage quotas?) for journal paths also interfere with the storage mechanisms of the journal? The journals already have settings for controlling size and rates.

The journal logic can already deal with EDQUOT errors mostly OK. Quotes can always be in effect, for example per-container quotas and such, hence we need to be able to deal with them anyway.

> You mentioned that it would interfere with the storage cleanup and dependencies for systemd if we set LogsDirectory= to empty by default, couldn't this be solved by making LogsDirectory point to /var/log instead? This would then not interfere with journald storage logic.

Not sure I follow? LogsDirectory= specify a suffix to append to /var/log already?

**Comment by poettering** [comment]
I posted  #24821 which addresses this as a documentation issue, as I suggested earlier. Let's continue discussion there.

**Pull request closed without merging**
