### PR TITLE
Smack v08: set only the default smack process label if the command path has no execute label

### PR DESCRIPTION
**Pull request by walyong**
- util: add getxattr helper apis
- smack-util: revise smack-util apis and add read smack attr apis
- core: set default process label only exec label is none

### CODE REVIEW

**Comment by poettering** [comment]
The other two patches look ready to merge.

**Comment by keszybz** [comment]
This first patch looks much worse than before. Where is l initialized? Also, the kernel tells us the current size, so there's no need to multiply the buffer by 2. Simply try with the size specified by the kernel +1. Also better to use realloc() instead of free() + new().

**Comment by poettering** [comment]
Oh yes, @keszybz is right, l needs to be initialized, and yes, we can use the returned value for the next loop iteration.

However, @keszybz i think free()+new() is actually more appropriate here, since realloc() will copy memory if necessary, which is something we aren't interested in in this case. Use realloc() if you want to make sure the old data remains in the newly memory block, but since we invoke getxattr() fully new here, it doesn't matter, and free()+new() should be quicker... (not that it would matter much though)

**Comment by walyong** [comment]
Thanks @keszybz. Maybe I'm tired. 3:30 AM in Korea. :)

**Comment by keszybz** [comment]
On Mon, Jul 27, 2015 at 11:29:30AM -0700, Lennart Poettering wrote:

> Oh yes, @keszybz is right, l needs to be initialized, and yes, we can use the returned value for the next loop iteration.
> 
> However, @keszybz i think free()+new() is actually more appropriate here, since realloc() will copy memory if necessary, which is something we aren't interested in in this case. Use realloc() if you want to make sure the old data remains in the newly memory block, but since we invoke getxattr() fully new here, it doesn't matter, and free()+new() should be quicker... (not that it would matter much though)

Ack.

**Comment by zonque** [comment]
Closing in favor of #745

**Pull request closed without merging**
