### PR TITLE
Add support for Alienware graphics amplifier

### PR DESCRIPTION
**Pull request by superm1**
This is in reference to https://github.com/systemd/systemd/issues/78 and https://bugs.freedesktop.org/show_bug.cgi?id=90689

### CODE REVIEW

**Comment by teg** [comment]
No comments on the patch itself, but something seems wrong with this pull request. I think you intended only to have one commit, not the merge commit as well? You probably want to rebase your one commit on top of origin/master and push that instead.

**Comment by poettering** [comment]
The merge commit looks wrong, please rebase and send as one commit only.

Assigning to @martinpitt

**Comment by zonque** [comment]
The failed build on Semaphore is my fault, I fixed the config. If you rebase and pull again, the test bot should be triggered again and run just fine. Sorry.

**Comment by dvdhrm** [comment]
The atkbd match looks wrong. You match only on "svnAlienware" which will end up applying to _all_ Alienware devices with those ideas. Can you please add a more specific match there? I don't have the device so I cannot tell which identifiers you should use. Feel free to post the udev device information here in case you cannot figure it out.

**Comment by superm1** [comment]
@zonque, @teg I've rebased and pushed it again.  Hopefully that is correct now.

@dvdhrm, actually that's what my intention was.  These keycodes are documented in the BIOS specifications for Alienware.  

They haven't been used for any previous devices but are in use in the current Alienware laptops and will be used for upcoming Alienware Desktop and Laptops.  I didn't want to have to list out every model that has explicitly added support for them, as the list will continue to grow as more laptops and desktops are released.  If you would prefer that though, the list should be 4 machines long currently and I can get the DMI information for each of these.

**Comment by dvdhrm** [comment]
So Alienware/Dell explicitly states that those keycodes will not be used by normal Alienware keyboards? In that case, I'm fine with the match. But please add a comment ala "# These keycodes are reserved on all Alienware BIOSes for gfx-accelerators".

Sorry for the nit-picking, but I want to make sure we still understand those entries in 5 years. With that comment added, I'm fine with the patch.

**Comment by dvdhrm** [comment]
Ok, I did this myself now. No need to resend.

Merged, thanks!

**Pull request closed without merging**
