### PR TITLE
Tpm2 measure use calculate

### PR DESCRIPTION
**Pull request by ddstreet**
Use calculation instead of an actual tpm session.

On top of #27517

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Awesome! I was just complaining today that I needed this for mkosi

**Comment by ddstreet** [comment]
switching to draft waiting on #27517

**Comment by ddstreet** [comment]
@bluca @poettering @DaanDeMeyer @yuwata assuming #27517 doesn't need any more changes, this is ready for review

**Comment by ddstreet** [comment]
The jammy-ppc64el failure here is interesting and i saw it before:
[  125.474172] testsuite-70.sh[2061]: Password from environment variable $PASSWORD did not work: Operation not permitted

I don't think this failure is related, as the pw-based unlocking doesn't use the tpm2 code at all, but it would be good to figure out why this is (intermittently) happening

**Comment by ddstreet** [comment]
> > The jammy-ppc64el failure here is interesting and i saw it before: [ 125.474172] testsuite-70.sh[2061]: Password from environment variable $PASSWORD did not work: Operation not permitted
> > I don't think this failure is related, as the pw-based unlocking doesn't use the tpm2 code at all, but it would be good to figure out why this is (intermittently) happening
> 
> #27716

Interesting, though that's actually a different failure.

**Comment by poettering** [comment]
there's only one addition commit in here, right?

lgtm, should be good to merge once https://github.com/systemd/systemd/pull/27517 is merged, and this one is rebased on top of it.

**Comment by ddstreet** [comment]
> there's only one addition commit in here, right?

yep

> 
> lgtm, should be good to merge once #27517 is merged, and this one is rebased on top of it.

rebased on the latest from #27517

**Comment by bluca** [comment]
needs rebase

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
yeah, please make the options a NOP that when used prints a warning, and hide it from --help and man page

**Pull request merged**
