### PR TITLE
More assert macros

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
It seems opensuse has troubles again:
```
Cloning into 'pkg/opensuse'...
fatal: unable to read tree (69820e26e94ba0792c8f08678f7f8df2d9bb7a224b77f174944a8f6a75598254)
‣ "/work/sync final" returned non-zero exit code 128.
```

**Review by bluca — APPROVED** [review]

**Comment by keszybz** [comment]
BTW, note that the use of those macros isn't free:
```console
$ size build/test-condition{.old,}   
   text	   data	    bss	    dec	    hex	filename
  76520	   1204	     64	  77788	  12fdc	build/test-condition.old
 161971	   1228	     64	 163263	  27dbf	build/test-condition
```
With an optimized and stripped build:
```console

size build/test-condition{,.1.opt}
   text	   data	    bss	    dec	    hex	filename
  56162	   1200	     48	  57410	   e042	build/test-condition.old
  96582	   1224	     48	  97854	  17e3e	build/test-condition
```

`test-condition` is an extreme case, it does a bazillion checks. The difference for other programs will be smaller.

Overall, since this is for test binaries that are split off into a subpackage, I think the benefit of better messages outweighs the cost.

**Comment by bluca** [comment]
Yeah for test binaries it shouldn't matter too much

**Comment by DaanDeMeyer** [comment]
> BTW, note that the use of those macros isn't free:
> 
> ```
> $ size build/test-condition{.old,}   
>    text	   data	    bss	    dec	    hex	filename
>   76520	   1204	     64	  77788	  12fdc	build/test-condition.old
>  161971	   1228	     64	 163263	  27dbf	build/test-condition
> ```
> 
> With an optimized and stripped build:
> 
> ```
> $ size build/test-condition{,.1.opt}
>    text	   data	    bss	    dec	    hex	filename
>   56162	   1200	     48	  57410	   e042	build/test-condition.old
>   96582	   1224	     48	  97854	  17e3e	build/test-condition
> ```
> 
> `test-condition` is an extreme case, it does a bazillion checks. The difference for other programs will be smaller.
> 
> Overall, since this is for test binaries that are split off into a subpackage, I think the benefit of better messages outweighs the cost.

Good to know, I was considering moving the macros into shared code and replacing non test code with them as well, but we may want to avoid doing that if the size increase is non-trivial.

**Pull request merged**
