### PR TITLE
network: fix the case DHCP=no|ipv4 and IPv6AcceptRA.UseDNS=no

### LINKED ISSUE #12917: systemd-networkd: [IPv6AcceptRA] UseDNS=no has no effect.
**systemd version the issue has been seen with**
> systemd 242 (242.32-1-arch)

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > systemd-networkd should not configure systemd-resolved to use IPv6RA advertised RDNSS for managed interface when UseDNS=no is set under [IPv6AcceptRA] in the .network file.

**Unexpected behaviour you saw**
 > UseDNS=no under [IPv6AcceptRA] has no effect and networkd still configures the advertised RDNSS to be used.

#5071 seems to reference fixing this issue in #5040 but I still see the described behavior.

I did see the blurb about DHCPv6 under DHCP= in systemd.network(5), but shouldn't IPv6AcceptRA.UseDNS still apply? If this behavior is intended, is there any way for me to get a IPv6 address and _not_ use the advertised DNS?

### PR DESCRIPTION
**Pull request by yuwata**
DHCPv6 lient is started even if DHCPv6 is disabled. So, the check is necessary.

Closes #12917.

cc @ssahani and @RPigott.

### CODE REVIEW

**Comment by ssahani** [comment]
hmmm this patch is not right according to the RFC. Please see M and O bit . https://community.arubanetworks.com/t5/Controller-Based-WLANs/Explain-the-M-and-O-bit-in-IPv6-DHCP-server-configuration-What/ta-p/177442

**Comment by yuwata** [comment]
@ssahani Thank you for the quick review and the reference.

> So the Router needs to disable the M or O bit . Networkd should not interfere.

So, your opinion sounds that clients should always take all the provided information, in this case, DNS servers. But I think, M or O bit just say what kind of information are provided by Router, and we can ignore some information. We already have UseDNS= or similar flags for DHCP and RA, and if they are disabled, then `networkd` already ignores part of provided information.

So, my question is why do you think 'Networkd should not interfere' for DNS servers?

**Comment by ssahani** [comment]
>DHCPv6 lient is started even if DHCPv6 is disabled. So, the check is necessary.

>So, your opinion sounds that clients should always take all the provided information, in this case, DNS servers. But I think, M or O bit just say what kind of information are provided by Router, and we can ignore some information. We already have UseDNS= or similar flags for DHCP and RA, and if they are disabled, then networkd already ignores part of provided information.

Is not it confusing what is the commit says and what you explaining.  

>So, your opinion sounds that clients should always take all the provided information, in this case, DNS servers. But I think, M or O bit just say what kind of information are provided by Router,

No the router suggests that the client needs to start the DHCP6 client to get the IP  not the DNS and the Domain .

**Comment by RPigott** [comment]
This patch, to me, does not seem to be in direct conflict with [rfc4861#4.2](https://tools.ietf.org/html/rfc4861#section-4.2)

>       M              1-bit "Managed address configuration" flag.  When
>                      set, it indicates that addresses are available via
>                      Dynamic Host Configuration Protocol [DHCPv6].
> 
>                      If the M flag is set, the O flag is redundant and
>                      can be ignored because DHCPv6 will return all
>                      available configuration information.
> 
>       O              1-bit "Other configuration" flag.  When set, it
>                      indicates that other configuration information is
>                      available via DHCPv6.  Examples of such information
>                      are DNS-related information or information on other
>                      servers within the network.

[rfc4862#5.6](https://tools.ietf.org/html/rfc4862#section-5.6) even allows the DHCPv6 and RA optional info to differ, though it is discouraged:

> It is also possible that the values of other configuration parameters, such as MTU size and hop limit, will be learned from both Router Advertisements and DHCPv6.  If the same configuration information is provided by multiple sources, the value of this information should be consistent.  However, it is not considered a fatal error if information received from multiple sources is inconsistent.

Which indicates to me that the client could choose to ignore some DHCPv6 information when explicitly configured so, as networkd can already be configured to do with DHCP and RA.

Though this patch fixes my issue, I still have concerns:

In accordance with rfc4681, networkd starts DHCPv6 client when router has either 'M' or 'O' set. If the client does not wish to use the DHCPv6 advertised DNS, I see 4 options:

1) Use Unamanaged interface (the status quo)
networkd does not currently allow the user to ignore DHCPv6 advertised DNS by any method I know, so the user must use an Unmanaged interface in order to allow resolvectl or another utility to remove the configured nameserver. This seems undesirable.

2) Use the value of Network.DHCP to decide when to use DHCPv6 advertised nameserver (implemented in this patch)

3) Use the value of IPv6AcceptRA.UseDNS to decide when to use DHCPv6 advertised nameserver (my expectation based on the `systemd.network(5)` documentation)

4) Add a new configuration field, DHCPV6 or similar to allow for DHCPV6.UseDNS flag or similar.
This has the added advantage of allowing users who choose to explicitly start DHCPv6 client via Network.DHCP=yes|ipv6 the ability to ignore advertised nameservers. This is maybe not a common configuration, but still worth considering nonetheless.

As I said, for my purpose this patch is good, and I believe respects rfcs. These are just some other ideas to consider. Which do you think we should use?

**Comment by yuwata** [comment]
> > DHCPv6 lient is started even if DHCPv6 is disabled. So, the check is necessary.
> 
> > So, your opinion sounds that clients should always take all the provided information, in this case, DNS servers. But I think, M or O bit just say what kind of information are provided by Router, and we can ignore some information. We already have UseDNS= or similar flags for DHCP and RA, and if they are disabled, then networkd already ignores part of provided information.
> 
> Is not it confusing what is the commit says and what you explaining.

Maybe, the commit message is misleading. I will try to update.

> > So, your opinion sounds that clients should always take all the provided information, in this case, DNS servers. But I think, M or O bit just say what kind of information are provided by Router,
> 
> No the router suggests that the client needs to start the DHCP6 client to get the IP not the DNS and the Domain .

Yeah, so we can ignore provided DNS servers.

**Comment by yuwata** [comment]
On top of the fix, I've extend `UseDNS=` to take `ipv4` or `ipv6`. PTAL.

**Comment by yuwata** [comment]
Ah, apparently I understand @ssahani's point, I hope so.
Now, DNS servers are used when `(DHCP.UseDNS=yes && DHCP=yes|ipv6) || (IPv6AcceptRA.UseDNS=yes && IPv6AcceptRA=yes)`. So, @RPigott's case, the DNS servers obtained by the DHCPv6 client is ignored.

PTAL.

**Comment by yuwata** [comment]
BTW, I noticed that `IPv6AcceptRA.UseDomains=` does not work. If the approach to fix `UseDNS=` here is accepted, then I will also fix that in the same way.

**Comment by ssahani** [comment]
I think we should have a separate section for DHCPv6 ```[DHCPv6]``` and use same options as ```[IPv6AcceptRA]``` and ```[DHCP]```. That will make more clearer approach.

**Comment by ssahani** [comment]
@RPigott yes the client can ignore . I got confused because of the commit message. Now it's fixed.

**Comment by yuwata** [comment]
> I think we should have a separate section for DHCPv6 `[DHCPv6]` and use same options as `[IPv6AcceptRA]` and `[DHCP]`. That will make more clearer approach.

OK. I will rework this in that direction.

**Comment by ssahani** [comment]
Thanks @yuwata

**Comment by yuwata** [comment]
> > I think we should have a separate section for DHCPv6 `[DHCPv6]` and use same options as `[IPv6AcceptRA]` and `[DHCP]`. That will make more clearer approach.
> 
> OK. I will rework this in that direction.

But in another later PR. Now this PR contains only fix for the issue, and testcases for the fix. PTAL.

**Comment by RPigott** [comment]
Patch works as advertised for me. Thanks @yuwata !

**Comment by ssahani** [comment]
Sorry for the delay . I opened https://github.com/systemd/systemd/pull/12994 top of it which is separates the DHCPv6 options.

**Pull request closed without merging**
