### PR TITLE
rules: block: add support for pmem devices

### PR DESCRIPTION
**Pull request by bgbhpe**
Signed-off-by: Brian Boylston brian.boylston@hpe.com

### CODE REVIEW

**Comment by poettering** [comment]
hmm, what is this about precisely? Can you mention at least briefly what "pmem" actually is, and why we should handle it with blkid? (i.e. do these devices actually contain a partition table/file system usually?)

The commit message is really way too short on this one...

BTW, we don't do S-o-b in systemd, that's a kernel thing.

**Comment by bgbhpe** [comment]
Sorry about that, I've updated the commit message.

Yes, we expect /dev/pmemN and /dev/pmemNs to contain file systems.  They can be partitioned, but I don't think that will be common.

**Comment by bgbhpe** [comment]
When I was trying to get this working, I first updated 60-block.rules.  This change caused the events to fire after mkfs, but did not cause the symlink to be populated under /dev/disk/by-uuid/.  For that, I had to update 60-persistent-storage.rules.  So it seems as though both whitelists had to be updated in order for mkfs to trigger /dev/disk/by-uuid/ population.  However, the two whitelists do not otherwise contain the same devices.  Why do some devices appear in one but not the other?

**Comment by poettering** [comment]
@bgbhpe well, the metadata to generate the by-xyz symlinks needs to be available for them to work. There's some support for generically getting this from the kernel, and explicit support for USB, ATA and SCSI via scsi_id/usb_id/ata_id and so on. Hence, if the symlinks shall work, then your block device must be compatible with any of these schemes.

**Pull request merged**
