### PR TITLE
core/execute: do not trigger mount event on loading credential or stopping service

### LINKED ISSUE #25527: Umount failure in mkosi and integration test CI
### systemd version the issue has been seen with

main

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

_No response_

### Component

systemd-tmpfiles

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

_No response_

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[  365.166858] umount[63]: umount: /run/credentials/systemd-tmpfiles-setup.service: no mount point specified.
run-credentials-systemd\x2dfirstboot.service.mount: Deactivated successfully.
[  OK  ] Unmounted /run/credentials/systemd-firstboot.service.
run-credentials-systemd\x2dsysusers.service.mount: Deactivated successfully.
[  OK  ] Unmounted /run/credentials/systemd-sysusers.service.
run-credentials-systemd\x2dtmpfiles\x2dsetup.service.mount: Mount process exited, code=exited, status=32/n/a
run-credentials-systemd\x2dtmpfiles\x2dsetup.service.mount: Failed with result 'exit-code'.
```
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #25527.

### CODE REVIEW

**Comment by yuwata** [comment]
(Will extend the commit message.)

**Comment by DaanDeMeyer** [comment]
@yuwata What's the status of this? It would be nice to fix this issue

**Comment by poettering** [comment]
don't grok this one, it mostly deletes the logic?

this really is a dependency issue. if creds might be used for a service, and namespaces are not enabled then we should add an After= dep from the uservice to the expected mount for the creds

**Comment by poettering** [comment]
Let's close this one now that https://github.com/systemd/systemd/issues/25527 has already been closed.

**Pull request closed without merging**
