### PR TITLE
loop-util: reopen device node if we shortcut loop device creation

### PR DESCRIPTION
**Pull request by poettering**
The LoopDevice object supports a shortcut: if the backing fd refers to a
block device anyway then we'll use it as is if we can – instead of
actually setting a loopback device up for it that would be pretty much
the same as it already ist.

Previously, when doing this we'd just dup() the original backing fd and
use that. But that's problematic in case O_DIRECT was set on the fd,
since we'll keep that flag set on our copy too, which means we can't do
simple, regular IO on it anymore.

Thus, let's reopen the inode in this case with the exacty access flags
we'd apply if we'd actually open a loopback device.

Fixes: #21176

### CODE REVIEW

**Comment by poettering** [comment]
@topimiettinen i think this should fix #21176 for you. Could you verify please?

**Comment by topimiettinen** [comment]
This also fixes the issue and it's much simpler!

**Comment by DaanDeMeyer** [comment]
One GA CI timed out so restarting the jobs just to be sure

**Comment by topimiettinen** [comment]
GCC CI fails to timeout in test-repart, probably not relevant since other compilers are fine. Not sure what's the problem with focal-amd64 but since other focal CIs are successful, I think CI failures appear unrelated.

**Review by topimiettinen — APPROVED** [review]

**Comment by topimiettinen** [comment]
Rerunning GCC job was also successful, let's merge.

**Pull request merged**
