### PR TITLE
cryptenroll: don't try to use pcrlock in combination with signed PCR policy if both are available, because we don't actually support that right now

### PR DESCRIPTION
**Pull request by poettering**
Fixes: #32565

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Review by DaanDeMeyer — APPROVED** [review]

**Comment by bluca** [comment]
TEST-70 looks very sad

**Comment by DaanDeMeyer** [comment]
We really need `LogForwardToConsole=` so you can see the journal errors in the test unit output.

**Comment by mrc0mmand** [comment]
The failing CIs seem to be caused by https://github.com/systemd/systemd/pull/32500 which was merged with TEST-70 failing, so now it fails everywhere.

**Comment by bluca** [comment]
> The failing CIs seem to be caused by #32500 which was merged with TEST-70 failing, so now it fails everywhere.

lol I thought it was a failing test, fixed by this PR

**Comment by bluca** [comment]
pushed commit to hopefully fix it

**Comment by bluca** [comment]
Still fails here but works with the standalone workaround https://github.com/systemd/systemd/pull/32636 so there's still some issue with this PR

**Comment by poettering** [comment]
Here's another try. Let's see.

**Review by bluca — APPROVED** [review]
Tests look happier, let's wait for ubuntu ones too

**Pull request merged**
