### PR TITLE
Journalctl fields -- rebased

### PR DESCRIPTION
**Pull request by kaarposoft**
resolved: ENABLE_DEBUG_HASHMAP needs pthread.h
utf8: add utf8_escape_non_printable_newline

loginctl: gained --fields option

**loginctl --fields:**
- print field names (with number of entries and number of values)
- with --fields --fields print field values
- with --fields=<FIELD> print values for this field

### CODE REVIEW

**Comment by kaarposoft** [comment]
This is a fixed and rebased version of:
https://github.com/systemd/systemd/pull/2159

**Comment by evverx** [comment]
There are three unrelated changes here, right?
I've cherry-picked (and changed a commit-message) https://github.com/kaarposoft/systemd/commit/dc50e60ce5c0ec435a9f40ca5638ae48ea904402
See https://github.com/systemd/systemd/pull/2172/commits

**Comment by kaarposoft** [comment]
Well, it is really only two unreleated changes.
The first is just a small correction, which you have already cherry-picked.
The second is the addition of the --fields option to journalctl:
e28e7ae is the main commit, but it requires 58d0e71 (utf8), and the fix in  38b1d63.

**Comment by evverx** [comment]
> Well, it is really only two unreleated changes.

ok

> The second is the addition of the --fields option to journalctl

But the commit message contains:

> loginctl: gained --fields option
> loginctl --fields

**Comment by kaarposoft** [comment]
Whoops. I must have been sleeping when writing the commit message! Sorry.
I will create another pull request tonight.
Should I just make ONE commit with all three of e28e7ae (main) and 58d0e71 (utf8) and 38b1d63 (fix)?

**Comment by evverx** [comment]
I think, two commits are ok: `utf8`, `main + build`
@zonque , what do you think?

But https://github.com/systemd/systemd/commit/38b1d63b66be614aaba2813632a4e33f4c33cd9f contains changes from https://github.com/evverx/systemd/commit/5433c3e1a381c446764969afa2acf3efac546ea2

**Pull request closed without merging**
