### PR TITLE
build-sys: make RPM macros installation path configurable

### PR DESCRIPTION
**Pull request by steelman**

### CODE REVIEW

**Comment by keszybz** [comment]
I'd merge such a patch, but it cannot break existing setups:
```
...
        RPM macros dir:                    /usr/lib64/rpm/macros.d
```
Unfortunately that's wrong, the right dir is `/usr/lib/rpm/macros.d`.

**Comment by steelman** [comment]
Amended. Does it work?

**Comment by keszybz** [comment]
`$(prefix)/lib/rpm/macros.d → ${prefix}/lib/rpm/macros.d`, looks like this should work. But it doesn't:
```
        RPM macros dir:                    NONE/lib/rpm/macros.d
```
:(

**Comment by keszybz** [comment]
```diff
-        [], [with_rpmmacrosdir=${prefix}/lib/rpm/macros.d])
+        [], [with_rpmmacrosdir=\${prefix}/lib/rpm/macros.d])
```
Crazy, I know ;)

**Comment by keszybz** [comment]
I pushed the abovementioned diff to your branch. Let's see if this passes CI.

**Comment by steelman** [comment]
WAT‽ What is the difference between `${prefix}` and `${datadir}` in `AC_ARG_WITH([dbuspolicydir], …)`?

**Comment by keszybz** [comment]
If you look at the generated configure, a path is assigned to `dbuspolicydir`, and prefix is not assigned directly like that, instead prefix=NONE. See this part:
```
# Installation directory options.
# These are left unexpanded so users can "make install exec_prefix=/foo"
# and all the variables that are supposed to be based on exec_prefix
# by default will actually change.
# Use braces instead of parens because sh, perl, etc. also accept them.
# (The list follows the same order as the GNU Coding Standards.)
bindir='${exec_prefix}/bin'
sbindir='${exec_prefix}/sbin'
...
```
Adding the backslash does effectively the same thing.

**Comment by keszybz** [comment]
Right, and then `Makefile` is written in a way that `prefix = /usr` is assigned there, but that assignment has lower priority than a user-set variable.

**Comment by keszybz** [comment]
OK, so both not specifying `--with-rpmmacrosdir` and specifying `--with-rpmmacrosdir=no` work correctly, and CI  passes.

**Comment by poettering** [comment]
@steelman hmm, what's the rationale behind this PR btw?

**Comment by steelman** [comment]
Tizen keeps the file in a different directory and Debian doesn't use rpm macros at all. IMHO it is better to configure build system properly than fiddle with rm or other commands [[1](https://review.tizen.org/git/?p=platform/upstream/systemd.git;a=blob;f=packaging/systemd.spec;h=1faad7bd0e692645c5fc3b499cfca910b95435d2;hb=refs/heads/tizen#l273)][[2](https://anonscm.debian.org/git/pkg-systemd/systemd.git/tree/debian/rules?h=debian/232-22&id=3bbc6cc4b1febba64a36dadd4438487cc94d8650#n257)] during the install stage.

**Pull request merged**
