### PR TITLE
Make systemd-boot compliant with the Linux Boot / EFI Handover Protocol

### PR DESCRIPTION
**Pull request by c0d3z3r0**
The current implementation copied the *complete* header to boot_params,
thus making the kernel ignore many of the fields.

As mentioned in the code comment for the sentinel variable in
bootparam.h a bootloader should only copy the setup_header, set some
fields in boot_params and zero out anything else.

This change makes systemd-boot (mostly) compliant with the Linux Boot
Protocol and the EFI Handover Protocol described in bootparam.h and
Documentation/boot.txt to fix various issues:

- Secure boot not being detected corretly by Linux (#11717)
- tboot error message / warning on boot (#11717)
- Strange purple text color when booting in qemu with OVMF
- Hopefully even more ...

### CODE REVIEW

**Comment by poettering** [comment]
This fails in the CI:

```
cc -c ../src/boot/efi/linux.c -o src/boot/efi/linux.c.o -Wall -Wextra -std=gnu90 -nostdinc -ggdb -O0 -fpic -fshort-wchar -ffreestanding -fno-strict-aliasing -fno-stack-protector -Wsign-compare -Wno-missing-field-initializers -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -isystem /usr/include -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI
../src/boot/efi/linux.c:5:27: fatal error: asm/bootparam.h: No such file or directory
 #include <asm/bootparam.h>
                           ^
compilation terminated.
```

I am not sure this is really the way to go: so far we have been very careful not to mix EFI headers with regular headers. I am not sure we should start now. I think doing a minimized copy of the relevant struct, with all types used "uefi'fied" is the better approach, since otherwise you mix two worlds which smells like something that might break all over the place...

I mean, it's bad enough that the kernel's u64 type is already differently defined from glibc's uint64_t (one being long the other being long long on x64-64), but this kind of problem probably amplifies if we start mixing kernel and uefi headers like this). Hence please, let's keep this separate, even if this means duplicating a struct or two, and uefi'fying it.

**Comment by c0d3z3r0** [comment]
> I am not sure this is really the way to go: so far we have been very careful not to mix EFI headers with regular headers. I am not sure we should start now. I think doing a minimized copy of the relevant struct, with all types used "uefi'fied" is the better approach, since otherwise you mix two worlds which smells like something that might break all over the place...
> 
> I mean, it's bad enough that the kernel's u64 type is already differently defined from glibc's uint64_t (one being long the other being long long on x64-64), but this kind of problem probably amplifies if we start mixing kernel and uefi headers like this). Hence please, let's keep this separate, even if this means duplicating a struct or two, and uefi'fying it.

I wasn't sure, too but hoped for this sort of feedback. Fixed now

**Comment by c0d3z3r0** [comment]
Hmm, not sure if the autopkgtest fails are really caused by my patch...

**Comment by poettering** [comment]
ubuntu ci is currently borked, ignore

**Pull request merged**
