### PR TITLE
units: apply plymouth warning fix to in rescue mode as well (#5528)

### PR DESCRIPTION
**Pull request by danimo**

### CODE REVIEW

**Comment by keszybz** [comment]
```
+ /usr/bin/qemu-system-x86_64 -smp 1 -net none -m 512M -nographic -kernel /boot/vmlinuz-4.4.0-66-generic -drive format=raw,cache=unsafe,file=/var/tmp/systemd-test.lm0iTX/rootdisk.img -initrd /boot/initrd.img-4.4.0-66-generic -machine accel=kvm -enable-kvm -cpu host -append 'root=/dev/sda1 raid=noautodetect loglevel=2 init=/lib/systemd/systemd ro console=ttyS0 selinux=0   '
KVM: entry failed, hardware error 0x0
EAX=00000000 EBX=00000000 ECX=00000000 EDX=000206c1
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=0000fff0 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 0000ffff 00009300
CS =f000 ffff0000 0000ffff 00009b00
SS =0000 00000000 0000ffff 00009300
DS =0000 00000000 0000ffff 00009300
FS =0000 00000000 0000ffff 00009300
GS =0000 00000000 0000ffff 00009300
LDT=0000 00000000 0000ffff 00008200
TR =0000 00000000 0000ffff 00008b00
GDT=     00000000 0000ffff
IDT=     00000000 0000ffff
CR0=60000010 CR2=00000000 CR3=00000000 CR4=00000000
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000000
Code=ff ff 66 5b 66 83 c4 08 66 5b 66 5e 66 c3 b0 20 e6 20 66 c3 <ea> 5b e0 00 f0 30 36 2f 32 33 2f 39 39 00 fc 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

**Comment by poettering** [comment]
I really don't like the inflation of shell usage here... Also see #5674.

**Comment by keszybz** [comment]
hi it's kid. OK?

**Comment by keszybz** [comment]
We already have shell invocations in this unit file, so I thought this doesn't much either way. Making ExecStart=- ignore ENOENT silently is an option, but I'm not convinced it should just be turned on like that. Maybe with a new ExecFailureIgnore=ENOENT option.

**Comment by keszybz** [comment]
(BTW, please ignore previous comment ;))

**Pull request merged**
