### PR TITLE
systemctl: indicate if services generated from sysv init scripts are …

### PR DESCRIPTION
**Pull request by jsynacek**
…enabled

Make it visible from 'systemctl status' as with other units.

NOTE: I'm using `sysv_status == NULL` explicitly, because it's a pointer to a bool and it gets super confusing when you see `if (!sysv_status)`...

### CODE REVIEW

**Comment by poettering** [comment]
Humpf, I am really not convinced we want to add more sysv compat kludges. I'd much rather prefer if we'd reduce the number of kompat kludges.

I really don#t think there's anything wrong with saying that the relevant services are "generated". We shozuldn't try to claim that sysv services where really like native services, and there are already commands for figuring out whether a sysv service is enabled or not via update-rc.d or chkconfig.

I am sorry, but I really don't like this. Where's this coming from anyway?

**Comment by lnykryn** [comment]
Well this does not add any additional "kludge", we already use the code for systemctl is-enabled. And the current behavior is a bit confusing for the ordinary users, since they don't get any clue where they can obtain the information.

**Comment by swadeley** [comment]
Hello Lennart, I raised this issue initially as I felt the `systemctl status` command output was inconsistent when compared to a service enabled by a systemctl command. I work in docs not development, so I probably pay more attention to user experience when testing things.

I became aware of this when trying to find out why a Jenkins service did not start up properly after a reboot. The command output `Loaded: loaded (/etc/rc.d/init.d/jenkins)` with no information following to say if it was enabled to start at system start was "suboptimal" to me.

Maybe for you "Loaded: loaded (/etc/rc.d/init.d/jenkins)" means "this was loaded by /etc/rc.d/init.d/jenkins" and so you do not expect to see any further info.

If you do not already know the history and relationship between SysV and systemd then you might not think that command output is acceptable.

Thank you

**Comment by poettering** [comment]
again, the goal must be to reduce the sysv hackery we do, not pile more on top. If people want to manager sysv services they should use sysv tools.

**Comment by swadeley** [comment]
This is not about managing, this is about discovering, how does a newbie reading that command output know that they should switch to SysV tools at this point. I will not argue further, I understand you want to draw a line somewhere.

The command mentions Docs: man:systemd-sysv-generator(8), if the read that they would get a hint.

**Comment by poettering** [comment]
My recommendation for newbies: just port the relevant service over to a native systemd unit, that would be a lot more helpful in the long run...

Note that we prefix the description of LSB and SYSV services with "LSB:" and "SYSV:", to clarify that that's where they are from...

**Comment by jsynacek** [comment]
> I really don't think there's anything wrong with saying that the relevant services are "generated"

Me neither, I didn't remove it. I added to it. It now says "generated; enabled" if it is enabled and that's it.

> I'd much rather prefer if we'd reduce the number of kompat kludges.

Yes, I agree. But since the code is already there and is already ugly, I just used it to add a tiny bit of user friendliness. And I don't think that the code is going away any time soon, since that would mean you simply don't support sysv scripts anymore...

Anyway, I have to strong feelings about this one.

**Comment by poettering** [comment]
Anyway, it this point, let's close this, I don't think we want that really, for the reasons explained above. Let's not add more new sysv compat on top anymore at this point

**Pull request closed without merging**
