### PR TITLE
mount-util.c fixes regarding name_to_handle_at()

### PR DESCRIPTION
**Pull request by poettering**
A follow-up for #7395.

Fixes for #7431 and #7082.

### CODE REVIEW

**Comment by poettering** [comment]
Rebased on top of #7434, which is hopefully everything to make the amd64 ubuntu CI pass again.

**Comment by poettering** [comment]
and with this one we really should wait until the amd64 ubuntu CI passed too! please don't merge without 5/5 CIs green

**Comment by keszybz** [comment]
LGTM.

**Comment by poettering** [comment]
urks:

```
KVM: entry failed, hardware error 0x0
EAX=00000000 EBX=00000000 ECX=00000000 EDX=000306a9
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=0000fff0 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 0000ffff 00009300
CS =f000 ffff0000 0000ffff 00009b00
SS =0000 00000000 0000ffff 00009300
DS =0000 00000000 0000ffff 00009300
FS =0000 00000000 0000ffff 00009300
GS =0000 00000000 0000ffff 00009300
LDT=0000 00000000 0000ffff 00008200
TR =0000 00000000 0000ffff 00008b00
GDT=     00000000 0000ffff
IDT=     00000000 0000ffff
CR0=60000010 CR2=00000000 CR3=00000000 CR4=00000000
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000000
Code=ff ff 66 5b 66 83 c4 08 66 5b 66 5e 66 c3 b0 20 e6 20 66 c3 <ea> 5b e0 00 f0 30 36 2f 32 33 2f 39 39 00 fc 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

:-(

And now?

**Comment by poettering** [comment]
Will merge now, let's get this in. It's a pity that kvm threw a hissy fit on this one, but given that this is likely the main culprit for all other PRs to fail, and @keszybz and @yuwata already liked it, let's get this in.

**Pull request merged**
