### PR TITLE
tree-wide: fput[cs]() → fput[cs]_unlocked() wherever that makes sense

### PR DESCRIPTION
**Pull request by poettering**
As a follow-up for db3f45e2d2586d78f942a43e661415bc50716d11 let's do the
same for all other cases where we create a FILE* with local scope and
know that no other threads hence can have access to it.

For most cases this shouldn't change much really, but this should speed
dbus introspection and calender time formatting up a bit.

### CODE REVIEW

**Comment by vcaputo** [comment]
lgtm

**Comment by poettering** [comment]
@vcaputo hey, i took the liberty to invite you to the systemd github team! if you like a PR please go ahead and merge it. I hope that's OK? 

One positive review is sufficient for merging. Please use your new powers wisely. Please do a "squash" github merge if the PR consists of a single commit only, and a regular github merge otherwise! if you like a commit but CI hasn't finished yet, please set the "looks-good/waiting-for-ci" label and the next one coming by will merge it. and feel free to merge any PR you think is OK, regardless which area of systemd it touches, we try to avoid specific kingdoms!

**Comment by vcaputo** [comment]
@poettering That's fine with me, but please be aware my participation level will be quite variable.  These past few months have been spent exceptionally cooped up indoors with computers as I've been visiting family in a hot & humid climate.  I'm returning to California shortly, where significantly less time will be spent at a computer.

**Comment by poettering** [comment]
Yeah, no worries. Getting the privs doesn't imply you have to actually make us of them. It's just that you may now, whenever you want to, and you are very welcome if you do.

**Comment by vcaputo** [comment]
Ok, thank you.

**Pull request merged**
