### PR TITLE
Allow relative paths in `machinectl copy-{from,to}`

### LINKED ISSUE #325: machinectl copy-to should understand relative path arguments
Apparently, currently only this works:

```
machinectl copy-to machine /full/path/to/file1 /full/path/to/file2
```

In analogy to `cp`, the current working directory (at least on the source) and a destination ending in a directory should also be supported, e.g.

```
machinectl copy-to machine file1 /full/path/to/
# should be same as
machinectl copy-to machine $(pwd)/file1 /full/path/to/file1
```

### PR DESCRIPTION
**Pull request by richardmaw-codethink**
This should fix #325

### CODE REVIEW

**Comment by poettering** [comment]
Hmpf, I am not too happy with the normalize call, since /waldi/foo/../bar is not the same as /waldi/bar if /foo is a symlink. Why precisely do we need the normalize? Can't we just make the stuff accept the non-normalized paths?

**Comment by poettering** [comment]
(the only normalize function we have so far is path_kill_slashes() btw, which strips duplicate slashes. We could probably improve it to also strip "/./" but certainly not "/../")

**Comment by richardmaw-codethink** [comment]
machined (https://github.com/systemd/systemd/blob/master/src/machine/machine-dbus.c#L828) calls `path_is_safe()` (https://github.com/systemd/systemd/blob/master/src/basic/util.c#L4202).
I'm not sure why paths with `../` in are deemed unsafe for this call. If that's deemed overzealous, I'll submit a v2 without the check.

Also, I'm not sure why semaphore has failed it. That test worked locally. I'll fix it if we result in keeping the call to normalize().

**Comment by zonque** [comment]
> Also, I'm not sure why semaphore has failed it. That test worked locally. I'll fix it if we result in keeping the call to normalize().

It seems there is a memory corruption somewhere. Semaphore builds with address-sanitizer, and that dripped up. You might wanna check that test with valgrind or something.

**Comment by poettering** [comment]
Yeah, sounds OK to drop the path_is_safe() check for this.

**Comment by richardmaw-codethink** [comment]
#855 sent as version 2

**Pull request closed without merging**
