### PR TITLE
udev-rule: fix negative match

### LINKED ISSUE #27396: udev rule token "SYMLINK" is weird when the operator is "!="
### systemd version the issue has been seen with

253

### Used distribution

centos stream 9

### Linux kernel version used

5.14.0-163.el9.x86_64

### CPU architectures issue was seen on

aarch64

### Component

systemd-udevd, udev rule files

### Expected behaviour you didn't see

NA

### Unexpected behaviour you saw

NA

### Steps to reproduce the problem

Assume there is a block device `/dev/sdb` in the system.

Place the following rule file, naming it as `test.rules`, under /etc/udev/rules.d:
```
SYMLINK!="notest", RUN+="/bin/echo hello"
```

Reload udevd and trigger `/dev/sdb`. The first rule line does not match the condition and `/bin/echo hello` is not executed.

As far as I see, the rule token `SYMLINK!="notest"` should be true because there is no symlink `/dev/notest` for `sdb` absolutely.

According to the [man page](https://man7.org/linux/man-pages/man7/udev.7.html) , `SYMLINK` token only provides usage on match oeprator `==` and returns true if any one symlink matches. But the man page does not provides usage when the operator is `!=`. 

I reviewed the source code in `udev-rules.c` and found it repeatedly check `token->op==OP_MATCH` or `token->op==OP_NOMATCH` , which is already checked in previous called function `token_match_string`.
https://github.com/systemd/systemd/blob/3cd60148b44e9947de9557c93c2dd93a2f6978a9/src/udev/udev-rules.c#L1900

I am wondering whether this code is a potential bug. Because `SYMLINK!="xxx"` is rarely used, this problem is never discovered.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
NA
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #27396.

### CODE REVIEW

**Comment by jiayi0118** [comment]
Maybe you should update the man page, add an usage like
```
If the operator is `!=`, the token returns the true only if there is no symlink or tag matched.
```

**Comment by keszybz** [comment]
Yeah, I think a documentation update would be great. This isn't obvious at all.

**Comment by yuwata** [comment]
man page is updated. PTAL.

**Comment by jiayi0118** [comment]
lgtm

**Review by keszybz — APPROVED** [review]

**Pull request merged**
