### PR TITLE
ci: migrate to Semaphore CI 2.0

### PR DESCRIPTION
**Pull request by mrc0mmand**

### CODE REVIEW

**Comment by bluca** [comment]
What's the difference for us? I hope it's more reliable, there's so many compiler segfaults on v1...

**Comment by mrc0mmand** [comment]
> What's the difference for us? I hope it's more reliable, there's so many compiler segfaults on v1...

Classic Semaphore is in the maintenance mode, the v2 version is under active development, so _theoretically_ it should be more stable (that's actually the reason I even started the migration). So, let's hope it indeed is :-)

Once this is merged I'll enable the v2 Semaphore globally and disable the old job.

**Comment by bluca** [comment]
> The build failed on Semaphore.

lolz

**Comment by bluca** [comment]
> > The build failed on Semaphore.
> 
> lolz

Ah it's not a compiler segfault this time, never mind :-)

**Comment by bluca** [comment]
is this the old one still running?

> -bash: ./semaphoreci/semaphore-runner.sh: No such file or directory

**Comment by DaanDeMeyer** [comment]
Out of curiosity, why do we use Semaphore? Does it have any benefits over the other CIs?

**Comment by mrc0mmand** [comment]
> > > The build failed on Semaphore.
> > 
> > 
> > lolz
> 
> Ah it's not a compiler segfault this time, never mind :-)

That's thankfully the old webhook, the new one (`ci/semaphoreci/pr: Debian autopkgtest (LXC) `) is still running :-)

**Comment by mrc0mmand** [comment]
> Out of curiosity, why do we use Semaphore? Does it have any benefits over the other CIs?

I don't think there's any particular benefit for us over other CIs, it's mostly just the "don't put all your eggs in one basket" thing.

**Review by bluca — APPROVED** [review]
lgtm

**Pull request merged**
