### PR TITLE
network: fixes related to setting MTU

### LINKED ISSUE #9831: systemd-networkd does not start DHCP ipv4 if MTUBytes is specified
**systemd version the issue has been seen with**
> 239.0 (works with 238.51)

**Used distribution**
> Arch LInux

**Expected behaviour you didn't see**
 > systemd-networkd uses DHCP to obtain IP address

**Unexpected behaviour you saw**
 > no IP address is assigned via DHCP. It seems, that DHCP module event do not start

**Steps to reproduce the problem**
1. Create network file for your interface containing
```
[Match]
Name=eth0

[Network]
DHCP=ipv4

[Link]
MTUBytes=1500
```

2. run `SYSTEMD_LOG_LEVEL=debug /lib/systemd/systemd-networkd`
3. with MTUBytes option set the following statements are missing in the log
```
DHCP CLIENT (0xa348ec41): STARTED on ifindex 80
DHCP CLIENT (0xa348ec41): REQUEST (init-reboot)
DHCP CLIENT (0xa348ec41): ACK
DHCP CLIENT (0xa348ec41): lease expires in 59min 57s
DHCP CLIENT (0xa348ec41): T2 expires in 52min 28s
DHCP CLIENT (0xa348ec41): T1 expires in 29min 57s
eth0: DHCPv4 address 10.222.0.40/24 via 10.222.0.1
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #9831.

@ssahani Could you review this?

### CODE REVIEW

**Comment by yuwata** [comment]
> There was a bug when we try to set the MTU the HW restarts and the DHCP requests gets into a loop and eventually DHCP server treats this like a attack. Please make sure you test in that environment. Looks OK to me

@ssahani Thank you for the comment. I will try to set up an environment and test the situation. But it may take a time. So, I am happy if you or someone test the case.

**Comment by yuwata** [comment]
Hmm, I noticed that this makes MTU not reset when DHCP leases are lost...

**Comment by keszybz** [comment]
I think we need to add a count and terminate the loop after some time. Just accept the fact that we cannot settle the MTU, stick to the lower version.

**Comment by ssahani** [comment]
I think https://github.com/systemd/systemd/pull/9832/commits/7169cdc8b971485751e4d92a1cae2d706293ecf9 makes sense. We should allow only one.

**Comment by yuwata** [comment]
@ssahani Thank you for the comment.

**Pull request merged**
