### PR TITLE
kernel-install: fix create MACHINE_ID_DIR

### PR DESCRIPTION
**Pull request by tpgxyz**
This fixes the script.

### CODE REVIEW

**Comment by yuwata** [comment]
Please read the comment in the script.
```
# If the boot dir exists (e.g. $ESP/<machine-id>),
# create the entry directory ($ESP/<machine-id>/<kernel-version>).
# This is the only function of this plugin.
```
At least, the current behavior matches with the comment. Why do you want to change the behavior? If you change it, then please also update the comment.

**Comment by tpgxyz** [comment]
@yuwata i read that description.
Problem is that when you run for the first time kernel-install and $ESP<machine-id>/ does not exist it never creates that dir and copy needed files. Something needs to bootstrap these, right?

**Comment by poettering** [comment]
Hmm, see 31e57550b552e113bd3d44355b237c41e42beb58 and 341890d

I guess we should figure out what we want here. Either bootctl or kernel-install should probably create the dir.

/cc @DaanDeMeyer

**Comment by DaanDeMeyer** [comment]
This PR looks like the way to go for me. We could do it in bootctl as well but I don't really see the benefit as kernel-install could always be run before sd-boot is installed. So just having kernel-install do it seems OK to me.

**Comment by poettering** [comment]
Hmm, see my comments on #19006, maybe let's continue discussion there?

**Comment by tpgxyz** [comment]
Mine PR is older thb.
Anyways i am about to improve these kernel-install scripts a lot :)

**Pull request closed without merging**
