### PR TITLE
build-sys: use itstool instead of intltool

### PR DESCRIPTION
**Pull request by jsynacek**

### CODE REVIEW

**Comment by poettering** [comment]
Doesn't build.

**Comment by jsynacek** [comment]
Right, it looks like intltool automagically extracted strings from C/XML and it didn't care if it was C or XML. xgettext cares, it works only on C in this case. itstool cares too, it seems to work only with XML. I'm not sure how to proceed.

**Comment by jsynacek** [comment]
I see that itstool support is coming to the next version of gettext: http://git.savannah.gnu.org/cgit/gettext.git/commit/?h=wip/ueno/its2&id=7a17583f. I'll probably postpone working on this patch until the next gettext is released.

**Comment by poettering** [comment]
Ah, yeah, let's wait for the next gettext version then, if it will support this natively. Let's skip porting to itstool, if gettext will eventually support this directly. Closing hence.

**Comment by jsynacek** [comment]
The required functionality has been implemented in gettext-0.19.7. I'll get back to this Real Soon (tm).

**Pull request closed without merging**
