### PR TITLE
Add more doc pages, adjust links, add explanatory headers to examples and relax license to CC-0

### PR DESCRIPTION
**Pull request by keszybz**
If this is accepted, it'd be reasonable to do a similar change e.g. for sysusers.d and tmpfiles.d snippets.

@teg, @elmarco, @poettering, @yuwata please give your ack for the relicensing of `.network`/`.link` files.

### CODE REVIEW

**Comment by elmarco** [comment]
sure, for the relicensing of .network/.link files:
Acked-by: Marc-André Lureau <marcandre.lureau@redhat.com>

**Review by bluca — APPROVED** [review]
Please add a line to mention that examples under network/ are also CC 1.0 here: https://github.com/systemd/systemd/blob/main/LICENSES/README.md?plain=1#L50

**Comment by yuwata** [comment]
ACK.

**Review by yuwata — APPROVED** [review]

**Review by teg — APPROVED** [review]
No problem at all!

**Comment by keszybz** [comment]
Thank you for the acks.
The CI passed in the previous version, and this one only differs by one line in a README, I merged it without waiting.

**Pull request merged**
