### PR TITLE
Revert "pid1: when reloading configuration, forget old settings"

### LINKED ISSUE #12778: core: cannot start service with valgrind
The current v242 stable 7a6d834 works fine. However, recent git snapshot, e.g. 3681d63, pid1 cannot start valgrind service.
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Restart=no
ExecStart=
ExecStart=!!valgrind --track-origins=yes --leak-check=full --show-leak-kinds=all /var/build/systemd-networkd
PrivateTmp=yes
Environment=SYSTEMD_LOG_LEVEL=debug SYSTEMD_MEMPOOL=0
MemoryDenyWriteExecute=no
```
Then, 
```
Jun 12 15:59:05 systemd[1]: Starting Network Service...
Jun 12 15:59:05 valgrind[2860]: valgrind: m_libcfile.c:68 (vgPlain_safe_fd): Assertion 'newfd >= VG_(fd_hard_limit)' failed.
Jun 12 15:59:05 kernel: memcheck-amd64-: vmalloc: allocation failure: 8589934592 bytes, mode:0x7000c0(GFP_KERNEL_ACCOUNT), nodemask=(null),cpuset=/,mems_allowed=0
Jun 12 15:59:05 kernel: CPU: 1 PID: 2860 Comm: memcheck-amd64- Not tainted 5.0.20-200.fc29.x86_64 #1
Jun 12 15:59:05 kernel: Hardware name: Sony Corporation SVP1121A1J/VAIO, BIOS R1045V7 05/19/2015
Jun 12 15:59:05 kernel: Call Trace:
Jun 12 15:59:05 kernel:  dump_stack+0x5c/0x80
Jun 12 15:59:05 kernel:  warn_alloc.cold.125+0x7b/0xfb
Jun 12 15:59:05 kernel:  __vmalloc_node_range+0x1a2/0x270
Jun 12 15:59:05 kernel:  ? __kmalloc_node+0x218/0x2b0
Jun 12 15:59:05 kernel:  __vmalloc_node_flags_caller+0x43/0x50
Jun 12 15:59:05 kernel:  ? alloc_fdtable+0x6e/0x100
Jun 12 15:59:05 kernel:  alloc_fdtable+0x6e/0x100
Jun 12 15:59:05 kernel:  expand_files.part.12+0x65/0x200
Jun 12 15:59:05 kernel:  ? __seccomp_filter+0x6d/0x610
Jun 12 15:59:05 kernel:  __alloc_fd+0x3d/0x140
Jun 12 15:59:05 kernel:  f_dupfd+0x44/0x74
Jun 12 15:59:05 kernel:  do_fcntl+0x4a9/0x610
Jun 12 15:59:05 kernel:  ? syscall_trace_enter+0x192/0x2b0
Jun 12 15:59:05 kernel:  __x64_sys_fcntl+0x8b/0xb0
Jun 12 15:59:05 kernel:  do_syscall_64+0x5b/0x160
Jun 12 15:59:05 kernel:  entry_SYSCALL_64_after_hwframe+0x44/0xa9
Jun 12 15:59:05 kernel: RIP: 0033:0x5805edb9
Jun 12 15:59:05 kernel: Code: 00 e8 0b a7 fe ff 66 2e 0f 1f 84 00 00 00 00 00 90 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <c3> 66 0f 1f 44 00 00 f3 0f 1e fa 8d 87 ff 0f 00 00 89 fa 89 ff 3d
Jun 12 15:59:05 kernel: RSP: 002b:0000000059c8e8b8 EFLAGS: 00000202 ORIG_RAX: 0000000000000048
Jun 12 15:59:05 kernel: RAX: ffffffffffffffda RBX: 0000000000000004 RCX: 000000005805edb9
Jun 12 15:59:05 kernel: RDX: 000000003fffffec RSI: 0000000000000000 RDI: 0000000000000004
Jun 12 15:59:05 kernel: RBP: 0000000059c8ea90 R08: 0000000000000000 R09: 0000000000000000
Jun 12 15:59:05 kernel: R10: 0000000000000000 R11: 0000000000000202 R12: 0000000059c8e970
Jun 12 15:59:05 kernel: R13: 0000000000000003 R14: 0000000000000000 R15: 0000000059c8e9e0
Jun 12 15:59:05 kernel: Mem-Info:
Jun 12 15:59:05 kernel: active_anon:62258 inactive_anon:808 isolated_anon:0
                         active_file:47612 inactive_file:51828 isolated_file:0
                         unevictable:9491 dirty:118 writeback:0 unstable:0
                         slab_reclaimable:10973 slab_unreclaimable:14637
                         mapped:46004 shmem:10455 pagetables:1545 bounce:0
                         free:765429 free_pcp:1476 free_cma:0
Jun 12 15:59:05 kernel: Node 0 active_anon:249032kB inactive_anon:3232kB active_file:190448kB inactive_file:207312kB unevictable:37964kB isolated(anon):0kB isolated(file):0kB mapped:184016kB dirty:472kB writeback:0kB shmem:41820kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
Jun 12 15:59:05 kernel: Node 0 DMA free:15900kB min:272kB low:340kB high:408kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15984kB managed:15900kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
Jun 12 15:59:05 kernel: lowmem_reserve[]: 0 3367 3811 3811 3811
Jun 12 15:59:05 kernel: Node 0 DMA32 free:3017608kB min:59460kB low:74324kB high:89188kB active_anon:185120kB inactive_anon:2832kB active_file:77004kB inactive_file:106656kB unevictable:28752kB writepending:452kB present:3560716kB managed:3470624kB mlocked:32kB kernel_stack:2596kB pagetables:4452kB bounce:0kB free_pcp:4504kB local_pcp:1320kB free_cma:0kB
Jun 12 15:59:05 kernel: lowmem_reserve[]: 0 0 444 444 444
Jun 12 15:59:05 kernel: Node 0 Normal free:28208kB min:20136kB low:22096kB high:24056kB active_anon:64180kB inactive_anon:400kB active_file:113444kB inactive_file:100692kB unevictable:9212kB writepending:92kB present:522240kB managed:455160kB mlocked:0kB kernel_stack:3048kB pagetables:1728kB bounce:0kB free_pcp:1400kB local_pcp:204kB free_cma:0kB
Jun 12 15:59:05 kernel: lowmem_reserve[]: 0 0 0 0 0
Jun 12 15:59:05 kernel: Node 0 DMA: 1*4kB (U) 1*8kB (U) 1*16kB (U) 2*32kB (U) 3*64kB (U) 2*128kB (U) 0*256kB 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15900kB
Jun 12 15:59:05 kernel: Node 0 DMA32: 1126*4kB (UME) 322*8kB (UME) 212*16kB (UME) 138*32kB (UME) 92*64kB (UME) 50*128kB (UME) 22*256kB (UME) 16*512kB (UME) 9*1024kB (UME) 3*2048kB (E) 723*4096kB (ME) = 3017768kB
Jun 12 15:59:05 kernel: Node 0 Normal: 2*4kB (U) 7*8kB (UM) 191*16kB (UME) 183*32kB (UME) 93*64kB (UME) 44*128kB (ME) 8*256kB (ME) 3*512kB (E) 2*1024kB (E) 1*2048kB (E) 0*4096kB = 28240kB
Jun 12 15:59:05 kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
Jun 12 15:59:05 kernel: Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
Jun 12 15:59:05 kernel: 109903 total pagecache pages
Jun 12 15:59:05 kernel: 0 pages in swap cache
Jun 12 15:59:05 kernel: Swap cache stats: add 0, delete 0, find 0/0
Jun 12 15:59:05 kernel: Free swap  = 4064252kB
Jun 12 15:59:05 kernel: Total swap = 4064252kB
Jun 12 15:59:05 kernel: 1024735 pages RAM
Jun 12 15:59:05 kernel: 0 pages HighMem/MovableOnly
Jun 12 15:59:05 kernel: 39314 pages reserved
Jun 12 15:59:05 kernel: 0 pages cma reserved
Jun 12 15:59:05 kernel: 0 pages hwpoisoned
Jun 12 15:59:05 kernel: memcheck-amd64-[2860]: segfault at 1c14 ip 000000005805f668 sp 0000000059c8e3e8 error 4 in memcheck-amd64-linux[58001000+1ed000]
Jun 12 15:59:05 kernel: Code: 00 00 f3 0f 1e fa 8b 35 d6 cd aa 01 83 fe 01 76 67 48 8b 0d c2 cd aa 01 b8 01 00 00 00 48 8d 91 14 1c 00 00 66 0f 1f 44 00 00 <44> 8b 02 45 85 c0 74 08 3b ba 2c 1b 00 00 74 46 83 c0 01 48 81 c2
Jun 12 15:59:05 systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Jun 12 15:59:05 systemd[1]: Started Process Core Dump (PID 2861/UID 0).
Jun 12 15:59:06 systemd[1]: systemd-networkd.service: Main process exited, code=dumped, status=11/SEGV
Jun 12 15:59:06 systemd[1]: systemd-networkd.service: Failed with result 'core-dump'.
Jun 12 15:59:06 systemd[1]: Failed to start Network Service.
Jun 12 15:59:06 sudo[2850]: pam_unix(sudo:session): session closed for user root
Jun 12 15:59:06 systemd-coredump[2862]: Process 2860 (memcheck-amd64-) of user 192 dumped core.
                                        
                                        Stack trace of thread 2860:
                                        #0  0x000000005805f668 vgPlain_lwpid_to_vgtid (/usr/libexec/valgrind/memcheck-amd64-linux)
                                        #1  0x000000005804922a show_sched_status_wrk (/usr/libexec/valgrind/memcheck-amd64-linux)
                                        #2  0x0000000058049438 report_and_quit (/usr/libexec/valgrind/memcheck-amd64-linux)
                                        #3  0x00000000580495de vgPlain_assert_fail (/usr/libexec/valgrind/memcheck-amd64-linux)
                                        #4  0x00000000580499dd vgPlain_safe_fd (/usr/libexec/valgrind/memcheck-amd64-linux)
                                        #5  0x00000000580bd828 setup_file_descriptors (/usr/libexec/valgrind/memcheck-amd64-linux)
                                        #6  0x00000000580c21ae _start_in_C_linux (/usr/libexec/valgrind/memcheck-amd64-linux)
                                        #7  0x00000000580bc241 .annobin_m_main.c (/usr/libexec/valgrind/memcheck-amd64-linux)
Jun 12 15:59:06 systemd[1]: systemd-coredump@0-2861-0.service: Succeeded.
```

### PR DESCRIPTION
**Pull request by yuwata**
This reverts commit fb39af4ce42d7ef9af63009f271f404038703704.

Fixes #12778.

### CODE REVIEW

**Comment by keszybz** [comment]
Well, are you saying that fb39af4 is buggy, or that valgrind is buggy, or is this just a test commit?

**Comment by yuwata** [comment]
I am not sure which valgrind or the commit is buggy. But, at least one of them.

**Comment by yuwata** [comment]
Note. I noticed the issue happens only after `systemctl daemon-reload` is done. That is, a service originally configured with valgrind works fine until we call `daemon-reload`.

**Comment by yuwata** [comment]
Not sure, but I hope this is replaced by #13012.

**Comment by yuwata** [comment]
Yeah, the issue is fixed by #13012. Closing.

**Pull request closed without merging**
