### PR TITLE
Configure vendor-specific USB-NICs to LinkLocal+DHCPv4 address automatically.

### PR DESCRIPTION
**Pull request by sujithshankar**
To configure vendor-specific usb-nics automatically to Link local IPv4 address with DHCP set.

### CODE REVIEW

**Comment by sujithshankar** [comment]
As discussed in Pull Request#1728, created a new udev property "ID_NET_AUTO_LL" and a new Match field "AutoLL" which has to be equal to "autoip" to set the interface with Link local ipv4 address from DHCP.
https://github.com/systemd/systemd/pull/1728

Currently, tested by using the existing Dell-idrac entries in hwdb. 

Addition of any new such interfaces can be done by making suitable entries in hwdb along with ID_NET_AUTO_LL=autoip

**Comment by zonque** [comment]
This is not how a pull request should look like. Please add proper commit log messages to each of your patches which give a justification for each change.

Also, give the patch a descriptive title, other than "Update [filename]". It's obvious which file you touched, so you don't need to mention it. The question is _why_ you did that, and _what_ is the intended change in behavior.

While at it, please also squash some of the commits, so they become logically grouped. Without that, the patch set cannot be reviewed, sorry.

**Comment by zonque** [comment]
Please craft a new PR, I'm closing this one.

**Comment by sujithshankar** [comment]
Sorry, I am new to sending PRs through github.
I will make suitable changes and send it again.
Thanks.

**Pull request closed without merging**
