### PR TITLE
sd-event: instrument sd_event_run() for profiling delays

### PR DESCRIPTION
**Pull request by vcaputo**

### CODE REVIEW

**Comment by vcaputo** [comment]
This change has been useful in measuring latencies affecting journald and possibilities for improvement:
https://gist.github.com/vcaputo/4291a2b8a6c2f91bd96f

There are some TODO items sprinkled around, not expecting to land as-is, but if there's interest most of those items are surrounding systemd-ifying the code I hadn't spent time digging through the systemd code to find the established practices in the codebase to do the same things.

This is a very fast-and-nasty instrumentation, but the methodology is quite useful.

**Comment by vcaputo** [comment]
Updated (forgive the force push) applying everyone's input, but kept as a simple global profile.  I'd just land the simpler form now, we can always make it more elaborate.

Thanks.

**Comment by vcaputo** [comment]
Updated, cheers.

**Comment by poettering** [comment]
Still LOG_INFO rather than LOG_DEBUG... But I figure this doesn't matter too much, if semaphore likes it, this should be merged.

**Comment by poettering** [comment]
done, thanks!

**Comment by vcaputo** [comment]
dang, I just noticed event_log_delays() int i, o; should be unsigned...

**Comment by vcaputo** [comment]
fixups posted in https://github.com/systemd/systemd/pull/2310

**Pull request merged**
