### PR TITLE
Private PIDs namespacing (WIP)

### PR DESCRIPTION
**Pull request by topimiettinen**
Basic functionality works, stub PID 1 gets installed and the process is started in a new PID namespace. A new instance of `/proc` is mounted.

Using both `PrivatePIDs=yes` and `PrivateUsers=yes` fails with error:
`Failed to set up user namespacing: Operation not permitted`

Proxying of `sd_notify()` is not implemented. 

PIDFiles will not be very useful with `PrivatePIDs=yes`, so maybe they should not be allowed.

Please comment.

### CODE REVIEW

**Comment by poettering** [comment]
So the reason I never implemented this was that this creates too much of a world separate of the host. i.e. it renumbers all PIDs and introduces a fake intermediary pseudo PID 1. While I very much see the benefit of locking down the process tree I was really hoping to see Djalal's work to take off eventually, i.e. this patch set:

https://lkml.org/lkml/2017/1/16/299

This appears much nicer to me as it means we just lock down what processes can see, we do not create a new world, no renumbering pids, not fake PID 1 or so. Alas that patch set never made it upstream. (That said, @tixxdz any update on the patch set?)

**Comment by poettering** [comment]
(that said, if the hidepid= thing never materializes I figure the next best thing would be to expose pidns, even though I really don't like that. Hence let's see what @tixxdz says, maybe this PR is the way to go if hidepid= is not an option)

**Comment by poettering** [comment]
hmm, so if we do this I figure the virt.c stuff (that detects whether we live in a container) might need some love, since /proc/1/environ is used for some checks, and /proc/1/sched for others. In particular the latter is kinda problematic here, since in your patch set the stub init originates in the host namespace...

**Comment by poettering** [comment]
(I figure /proc/1/sched check can probably be removed nowadays anyway tough, since I think it stopped working on the most recent kernels anyway)

**Comment by topimiettinen** [comment]
@tixxdz's kernel patches looks indeed better. Then there would be no need to proxy MAINPID and it would be OK for PIDFiles to be exposed. But it seems that sadly the patches were NAKed by Andy Lutomirski and he wanted much deeper changes to procfs.

Perhaps a generic FUSE proxy for /proc and /sys could be implemented instead? Though it could be fragile and full of TOCTOU problems.

**Comment by poettering** [comment]
> @tixxdz's kernel patches looks indeed better. Then there would be no need to proxy MAINPID and it would be OK for PIDFiles to be exposed. But it seems that sadly the patches were NAKed by Andy Lutomirski and he wanted much deeper changes to procfs.

iirc he posted follow-up patches for that, and reposted them a couple of times, but al viro never bothered to review them, so they languished. @tixxdz?

**Comment by poettering** [comment]
> Perhaps a generic FUSE proxy for /proc and /sys could be implemented instead? Though it could be fragile and full of TOCTOU problems.

uh, fuse sounds like a method of increasing the attack surface, not one to lock things down. let's please not go down this route.

**Comment by topimiettinen** [comment]
@poettering I think [this](http://do-db2.lkml.org/lkml/2018/4/13/65) is the latest set of patches from @tixxdz . It looks like there were only some small issues remaining, but in general the overlords of the kernel were positive. Alexey Gladkov (@legionus) said he could follow up, perhaps he could also comment?

**Comment by legionus** [comment]
As far as I know Djalal Harouni cannot continue working on the patches. I had to postpone work on the patch for a while due to workload, but if you found it necessary, I will try to modify it as soon as possible. As far as I remember the patch requires rebase and documentation. I am talking about the [patchset](https://lkml.org/lkml/2018/5/11/155).

@topimiettinen but I have never been involved in creating the [patch](https://lkml.org/lkml/2017/1/16/299). Although this patch seems to me sane.

**Comment by poettering** [comment]
@legionus it would be excellent if the kernel patch could be cleaned up and merged! I'd be very thankful for that!

**Comment by bl33pbl0p** [comment]
@poettering but blocking /proc access is orthogonal to this, right? If you don't put the process in a PID namespace, you still can't stop it from signalling tasks it can reach from its active namespace and has the permission to (similar for ptrace and other APIs). I think that justifies some uses of this PR.

**Comment by bl33pbl0p** [comment]
As for proxying, a translation API is planned for inclusion that would allow you to translate a namespace PID to your own, which solve the proxying problem (and it would be kernel enforced).

**Comment by topimiettinen** [comment]
@bl33pbl0p I think the best would be some kind of new restricted visibility namespace for PIDs, but for all operations (incl. signals) and not just /proc, without PID remapping (or do it optionally, or with disjoint PID namespaces). This should apply in a cgroup so that its members could not signal or examine any processes outside of the cgroup through any means.

Remapping causes extra effort due to translations and there could be still PID leakages (PIDFiles, protocols) and conflicts between namespaces. Instead, there could be some security value if the PID namespaces were completely disjoint (e.g. main namespace starting at 1 up to 2^22-1, first subspace starting at 2^22+1 etc) with no possibility of overlap, enforced by kernel. This could need 64 bit PIDs for enough space.

**Comment by bl33pbl0p** [comment]
I think PID namespaces already cover everything you note. They even have granularity to partition the view inside a cgroup. I am not aware of what conflicts there might exist due to namespacing and remapping.

Translation is not really an issue when communication happens over a kernel boundary (FUSE, Unix sockets, signals, etc), and if you're passing around the PID by value you already suffer from other major issues (like reuse). Moreover, having a single namespace (even as big as 64-bit) and having to partition them across all namespaces created on the system fairly will sadly at one point restrict you to a farily small set such that PID reuse becomes even a bigger problem, which userspace already has trouble to deal with.

For PIDFiles, I think you want to discourage their use as much as possible, they're the wrong model for process supervision to begin with. Maybe the incentive to sandbox a service will have buy in from daemon authors to add a --foreground option to their thing ;-).

**Comment by flokli** [comment]
@legionus Has there been some development outside the LKML thread? Private per-unit PIDs would be really nice :-)

**Comment by topimiettinen** [comment]
@legionus I attempted to make a summary of changes needed (+rebasing, if any):

[[PATCH v5 1/7]](https://lkml.org/lkml/2018/5/11/156) proc: add proc_fs_info struct to store proc information
- need to implement Jann Horn's [suggested change](https://lkml.org/lkml/2018/5/15/684)

[[PATCH v5 2/7]](https://lkml.org/lkml/2018/5/11/157) proc: move /proc/{self|thread-self} dentries to proc_fs_info
- OK

[[PATCH v5 3/7]](https://lkml.org/lkml/2018/5/11/158) proc: add helpers to set and get proc hidepid and gid mount options
- fix build error, probably simply by changing `extern kgid_t proc_fs_pid_gid(struct proc_fs_info *fs_info)` to `static inline`

[[PATCH v5 4/7]](https://lkml.org/lkml/2018/5/11/159) proc: support mounting private procfs instances inside same pid namespace
- OK

[[PATCH v5 5/7]](https://lkml.org/lkml/2018/5/11/160) proc: instantiate only pids that we can ptrace on 'limit_pids=1' mount option
- do Linus Torvalds' [comments](https://lkml.org/lkml/2018/5/11/505) need any changes?
- add documentation for the new option `limit_pids` (maybe rather in 4/7 which introduces it)

[[PATCH v5 6/7]](https://lkml.org/lkml/2018/5/11/161) proc: flush task dcache entries from all procfs instances
- OK

[[PATCH v5 7/7]](https://lkml.org/lkml/2018/5/11/162) proc: add option to mount only a pids subset
- OK (or does [this](https://lkml.org/lkml/2018/5/14/780) need addressing?)
- probably also documentation should be added for the new option `pidonly`

I'd be happy to help with the simple stuff.

**Comment by legionus** [comment]
@flokli, @topimiettinen Thing is that my patch (v5) is no longer applicable to the linux kernel. I need to adapt it for recent changes in procfs. That was bad news. The good news is that I have already started to do this and I hope to finish it soon. I have received feedback from Eric W. Biederman and I'm going to ask him about review.

**Comment by legionus** [comment]
> @flokli, @topimiettinen Thing is that my patch (v5) is no longer applicable to the linux kernel. I need to adapt it for recent changes in procfs. That was bad news. The good news is that I have already started to do this and I hope to finish it soon. I have received feedback from Eric W. Biederman and I'm going to ask him about review.

For the record: https://lkml.org/lkml/2019/12/25/102

**Comment by poettering** [comment]
So, given that the procfs rework has since been merged:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0fb5ce62c5920b6e0a8a061f2fe80e0403281e10

I think we can close this PR. I am sure making use of the new procfs features is a much nicer approach for us, since it hides processes without renumbering everything. And since service mgmt is in the territory of just minimizing the attack surface and not in the territory of synthesizing new machines I think it's a much better fit.

Let's close this now. Would love to merge/review a patch that makes use of the new kernel API.  Should probably be a new option ProtectProcesses= or so that effectively takes the arguments hidepid= now accepts. (We probably should only accept the new textual strings though, not the old numbers. In particular as that allows us to detect if things work, since the old kernels where procfs was a per-pidns singleton don't accept the textual strings)

**Comment by poettering** [comment]
(Oh, this got merged for 5.8, i.e. it's in master but not in any distro yet)

**Comment by poettering** [comment]
(it's in fedora rawhide)

**Comment by topimiettinen** [comment]
Great news, thanks to @legionus for his persistence!

**Pull request closed without merging**
