### PR TITLE
Insert custom .so file as "dlopen plugin" for libraries we want to load dynamically

### PR DESCRIPTION
**Pull request by keszybz**
/cc @poettering, @mbiebl, @guillemj, @bluca, @pmatilai

### CODE REVIEW

**Comment by poettering** [comment]
I am not convinced: this adds so much complexity and boilerplate glue just to work around limiations of dpkg/rpm package .so resolvers. It's just frickin ugly, to add an indirection everywhere. shared libary symbol resolving is not quick anyway, but duplicating it all twice is really the wrong approach.

Noone else does it this way, it's a pipe dream that this was the approach to take. It's a dead end. Either we do it like everyone else, i.e. dlopen() the lib itself, or maybe we can just drop the whole excercise, i.e. make everything hard deps, and blame glibc/dpkg people for it, and just accept that distro people are stuck in 1990 in this regard, if there's no attempt made to make dlopen() workable.

Please, let's not do this. Trying to get right of shared libs by duplicating the number of .so's we use is just a wrong approach, I am sorry. In particular if this is just because dh-shlibs is stuck in the last century.

**Comment by poettering** [comment]
I mean, let's not forget, this is an artificial problem if it is just about symbol versioning. the libs we use via dlopen() that define symbol versioning never defined more than a single version afaik. Hence why the complexity if it's a completely theoretic problem? Let's fix problems that exist IRL, but not adopt terrible solutions for problem that do only exist in theory.

**Comment by poettering** [comment]
the first 4 commits look great and should be uncontroversial. Can you split them out? We can merge them quickly then.

**Comment by keszybz** [comment]
OK. So let's take this one slowly. I have a slightly different approach in mind that you might like more. We can release v247-rc1 or even v247 without this, and ask distros to patch in the deps manually. It's not a big deal.

**Comment by guillemj** [comment]
@keszybz Hey, thanks for trying to implement a more technically correct solution to this! I think while the current PR is slightly better than the current status, it's still a missed opportunity and more complex than needed. If the bulk of the logic inside the functions, after the calls to `dlopen()` and `dlsym_*()`, would get moved into the plugin, then no header parsing would be needed, and that would simplify the build system and the code itself as only a single function would need to be dlsym_*()ed, and it would make it more future-proof and easier to maintain as the symbols used from the external shared libraries would not need to be explicitly loaded and kept in sync anymore when a new one starts to get used. This also seems easily doable as most of the helper and utility code in systemd resides in its private shared library!

**Comment by poettering** [comment]
Would be great to split the first 3 commits out and get merged

**Comment by keszybz** [comment]
> Would be great to split the first 3 commits out and get merged

You mean the first two? They have already been merged as  #17454.

**Comment by poettering** [comment]
ah, yes, sorry for the confusion. all good

**Comment by poettering** [comment]
Let's close this one. Given we have those ELF dlopen annotations these days I am pretty sure we can let this approach go.

**Pull request closed without merging**
