### PR TITLE
systemd-resolve: allow easy querying of caa records

### PR DESCRIPTION
**Pull request by stefan-it**
This PR adds the possibility to easily query CAA (see [RFC 6844](https://tools.ietf.org/html/rfc6844)) records:

```bash
$ systemd-resolve --caa fedoraproject.org
fedoraproject.org IN CAA 0 issue "letsencrypt.org"
fedoraproject.org IN CAA 0 issuewild "digicert.com"
fedoraproject.org IN CAA 0 issue "digicert.com"

-- Information acquired via protocol DNS in 50.1ms.
```

The popular [Qualys SSL Labs Server Test](https://www.ssllabs.com/ssltest/) page recently added the [detection of CAA records](https://blog.qualys.com/ssllabs/2017/01/13/whats-new-ssl-labs-1-26-5).

### CODE REVIEW

**Comment by keszybz** [comment]
Hm, why do we need a separate option for this? This is not the same as TLSA records, for which some specialized formatting is used. The output of `-t caa` would be the same:
```
zbyszek@fedora ~/src/systemd (git)-[pr/5637] % ./systemd-resolve -t caa fedoraproject.org
fedoraproject.org IN CAA 0 issue "letsencrypt.org"
fedoraproject.org IN CAA 0 issue "digicert.com"
fedoraproject.org IN CAA 0 issuewild "digicert.com"

-- Information acquired via protocol DNS in 66.2ms.
-- Data is authenticated: yes
zbyszek@fedora ~/src/systemd (git)-[pr/5637] % ./systemd-resolve --caa fedoraproject.org
fedoraproject.org IN CAA 0 issuewild "digicert.com"
fedoraproject.org IN CAA 0 issue "digicert.com"
fedoraproject.org IN CAA 0 issue "letsencrypt.org"

-- Information acquired via protocol DNS in 1.9ms.
-- Data is authenticated: yes
```
?

**Comment by stefan-it** [comment]
I thought this would complete the command line switches for dns types (which needs authentication) for widely-used and popular dns records :)

**Comment by keszybz** [comment]
We *could* add such options for any type, but I don't think it gives advantage to the user. Extra complexity has its cost too. So far, we only added "helpers" for records which require some preprocessing (e.g. example.com:443 → _443._tcp.example.com for tlsa), and it just happened that was often true for cryptography-related records. For the cases where no such preprocessing is needed, I think the generic interface with `-t` is better. It too has the advantage that it's familiar to any user of `dig` or `host`.

**Comment by stefan-it** [comment]
Ok, I understand :) Thanks for your explanation, I'll close the PR then!

**Comment by poettering** [comment]
Yeah, I agree: we should add special per-resource-type options only where that actually brings us a real benefit over simply "-t rrtype", i.e. does something more than just req the RR and dump it.

**Pull request closed without merging**
