### PR TITLE
RFC: systemctl: do not use underline as item separator

### PR DESCRIPTION
**Pull request by grawity**
A small UI improvement I had as a local patch...

Underline as used in this context is problematic:

 1) confusing – many people assume the item is underlined because it is
    somehow special (as the underline is applied to the text, rather
    than being perfectly in between the two lines);

 2) not universally supported – Linux console shows it as coloured text
    and some other terminals interpret it as italics, both resulting in
    even more confusion.

 3) looks bad if the system does not have `less` installed.

### CODE REVIEW

**Comment by poettering** [comment]
@keszybz opinion on this?

we probably should draw a unicode line though, i.e. special_glyph() should gain a new HORIZONTAL_LINE parameter or so, that returns a proper line character instead of dashes...

or we could go fancy and draw a pretty unicode dotted line: `┄┄┄┄┄┄┄┄┄┄`...

**Comment by jwilk** [comment]
> we could go fancy and draw a pretty unicode dotted line: `┄┄┄┄┄┄┄┄┄┄`...

Virtual console fonts are unlikely to have a glyph for this character (mine certainly doesn't have one), so I wouldn't do that.

**Comment by keszybz** [comment]
Indeed, this looks pretty funny on a tty. But I don't think this is that much of an issue. Dunno, I like that the current underlining is very space-efficient. With the patch we would have more lines. The reasons against are pretty weak imho: not having less installed is pretty fringe, I don't think it's confusing — once you get accustomed at least. The strongest reason would be that it doesn't work on a tty.

Maybe we could go for a middle option: use a separate line when we detect TERM=linux or less is not installed, and keep current code otherwise? Dunno, I like current behaviour, but I don't feel too strongly either way.

**Comment by poettering** [comment]
humm, i think it's one thing to add ANSI color stuff if we detect a capable tty, it's another one drawing completely different things if we detect one or none... i figure we can turn off the underlining if TERM=linux is detected, and then not replace it with anything else. But switching to output with a different number of lines appears wrong to me...

**Comment by poettering** [comment]
So, my proposal to fix the issue that underlines don't work on the Linux kernel is simply not to use it. I have prepped a patch for that in #6778. Please have a look.

**Comment by poettering** [comment]
Since #6778 got merged now I think we can close this one now.

**Pull request closed without merging**
