### PR TITLE
core: add valgrind helper for daemon-reexec

### PR DESCRIPTION
**Pull request by evverx**
Inspired by https://github.com/systemd/systemd/issues/2187#issuecomment-165587140

### CODE REVIEW

**Comment by evverx** [comment]
BTW:

```
bash-4.3# cat /proc/cmdline
root=/dev/sda1 systemd.log_level=debug raid=noautodetect loglevel=2 init=/lib/systemd/systemd-under-valgrind rw console=ttyS0 apparmor=0 selinux=0 systemd.unit=rescue.target

bash-4.3# systemctl poweroff
[  443.538033] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000000
[  443.538033]
[  443.540489] CPU: 0 PID: 1 Comm: systemd Not tainted 4.2.0-18-generic #22-Ubuntu
[  443.540489] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS Ubuntu-1.8.2-1ubuntu1 04/01/2014
[  443.540489]  0000000000000000 00000000cdc36043 ffff88003daf3e08 ffffffff817e8c09
[  443.540489]  0000000000000000 ffffffff81a990c8 ffff88003daf3e88 ffffffff817e5f9b
[  443.540489]  ffff880000000010 ffff88003daf3e98 ffff88003daf3e38 00000000cdc36043
[  443.540489] Call Trace:
[  443.540489]  [<ffffffff817e8c09>] dump_stack+0x45/0x57
[  443.540489]  [<ffffffff817e5f9b>] panic+0xce/0x206
[  443.540489]  [<ffffffff8107e2d7>] do_exit+0xb07/0xb10
[  443.540489]  [<ffffffff8107e373>] do_group_exit+0x43/0xb0
[  443.540489]  [<ffffffff8107e3f4>] SyS_exit_group+0x14/0x20
[  443.540489]  [<ffffffff817ef9f2>] entry_SYSCALL_64_fastpath+0x16/0x75
[  443.540489] Kernel Offset: disabled
[  443.540489] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000000
[  443.540489]
```

But

```
bash-4.3# cat /proc/cmdline
root=/dev/sda1 systemd.log_level=debug raid=noautodetect loglevel=2 init=/lib/systemd/systemd-under-valgrind rw console=ttyS0 apparmor=0 selinux=0 systemd.unit=rescue.target

bash-4.3# systemctl daemon-reexec

bash-4.3# journalctl | grep 'valgrind helper'
Jan 19 15:35:38 systemd-testsuite systemd[1]: Spawned valgrind helper as PID 344.

bash-4.3# grep '^==344==' /valgrind.out
==344==
==344== HEAP SUMMARY:
==344==     in use at exit: 66,216 bytes in 7 blocks
==344==   total heap usage: 52,797 allocs, 52,790 frees, 19,701,544 bytes allocated
==344==
==344== LEAK SUMMARY:
==344==    definitely lost: 0 bytes in 0 blocks
==344==    indirectly lost: 0 bytes in 0 blocks
==344==      possibly lost: 0 bytes in 0 blocks
==344==    still reachable: 66,216 bytes in 7 blocks
==344==         suppressed: 0 bytes in 0 blocks
==344== Reachable blocks (those to which a pointer was found) are not shown.
==344== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==344==
==344== For counts of detected and suppressed errors, rerun with: -v
==344== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

bash-4.3# systemctl poweroff
...
[   71.352111] reboot: Power down
```

**Comment by zonque** [comment]
Very cool. Thanks a lot for working on this!

**Comment by evverx** [comment]
> any chance we can improve the comment about this a bit?

Done.

> Also, I'd really like to reduce the number of #ifdefs in the main program, hence I'd like to see this moved into a function of its own, in process-util.c or so, and maybe called "show_valgrind_summary()" or "finalize_valgrind()", or "valgrind_summary_barrier()", or "valgrind_summary_hack()" or so..

Makes sense. Done.

([the review](https://github.com/evverx/systemd/commit/69aafc5e38a19e6bf4c798365c3fa95cb0447e81#commitcomment-15561223))

**Comment by zonque** [comment]
lgtm

**Pull request merged**
