### PR TITLE
sd-bus: Add offset member for vtable methods

### LINKED ISSUE #577: sd_bus vtable methods do not have offset member
If you use `_SD_BUS_VTABLE_METHOD` you have no way to pass a custom `userdata` per handler.

With a property (e.g. `_SD_BUS_VTABLE_PROPERTY`) you have the `offset` member; but methods have nothing.

### PR DESCRIPTION
**Pull request by daurnimator**
Fixes #577

### CODE REVIEW

**Comment by daurnimator** [comment]
btw, just noticed that the name @poettering suggested (`SD_BUS_VTABLE_METHOD_WITH_OFFSET`) doesn't match the others.
Do you want a follow up commit that removes the `_VTABLE` portion?

**Comment by poettering** [comment]
Oh, yes, please!

**Comment by daurnimator** [comment]
though... there's also `SD_BUS_VTABLE_START` and `SD_BUS_VTABLE_END`...
Perhaps they should all be fixed?
==> Would you rather that it has the `_VTABLE` or not?

**Comment by poettering** [comment]
No, start and end should keep the "_VTABLE" in there, since a "method" and a "property" are clear as a term on their own, but "start" and "end" are very very generic, and thus should carry the VTABLE qualifier.

**Comment by poettering** [comment]
Also, this is API, we cannot rename these things anymore, after they have been part of a stable release.

**Pull request merged**
