### PR TITLE
core: set NoNewPrivileges for seccomp if we don't have CAP_SYS_ADMIN

### PR DESCRIPTION
**Pull request by ronnychevalier**

### CODE REVIEW

**Comment by zonque** [comment]
Makes sense to me, thanks!

**Comment by evverx** [comment]
```
50f130c286c4a4cb87a94a0fc419a4462a98a7a1 is the first bad commit
commit 50f130c286c4a4cb87a94a0fc419a4462a98a7a1
Author: Ronny Chevalier <chevalier.ronny@gmail.com>
Date:   Sun Feb 28 15:00:18 2016 +0100

    test-execute: add nfsnobody alternative as a nobody user
```

```
exec-runtimedirectory-owner.service
        UMask: 0022
        WorkingDirectory: /home/ubuntu
        RootDirectory: /
        NonBlocking: no
        PrivateTmp: no
        PrivateNetwork: no
        PrivateDevices: no
        ProtectHome: no
        ProtectSystem: no
        IgnoreSIGPIPE: yes
        RuntimeDirectoryMode: 0755
        RuntimeDirectory: test-exec_runtimedirectory-owner
        StandardInput: null
        StandardOutput: inherit
        StandardError: inherit
        User: root
        Group: nobody
exec-runtimedirectory-owner.service: Failed at step GROUP spawning /bin/sh: No such process
exec-runtimedirectory-owner.service: Main process exited, code=exited, status=216/GROUP
exec-runtimedirectory-owner.service: Unit entered failed state.
exec-runtimedirectory-owner.service: Failed with result 'exit-code'.
        PID: 27971
        Start Timestamp: Mon 2016-03-21 17:22:10 UTC
        Exit Timestamp: Mon 2016-03-21 17:22:10 UTC
        Exit Code: exited
        Exit Status: 216
Assertion 'service->main_exec_status.status == status_expected' failed at src/test/test-execute.c:65, function check(). Aborting.
bisect run failed:
exit code 134 from '/bin/bash -c make && sudo ./test-execute' is < 0 or >= 128
```

@ronnychevalier , please, have a look.

**Comment by ronnychevalier** [comment]
On 21/03/2016 18:27, Evgeny Vereshchagin wrote:

> ```
> 50f130c286c4a4cb87a94a0fc419a4462a98a7a1 is the first bad commit
> commit 50f130c286c4a4cb87a94a0fc419a4462a98a7a1
> Author: Ronny Chevalier <chevalier.ronny@gmail.com>
> Date:   Sun Feb 28 15:00:18 2016 +0100
> 
>     test-execute: add nfsnobody alternative as a nobody user
> ```
> 
> ```
> exec-runtimedirectory-owner.service
>         UMask: 0022
>         WorkingDirectory: /home/ubuntu
>         RootDirectory: /
>         NonBlocking: no
>         PrivateTmp: no
>         PrivateNetwork: no
>         PrivateDevices: no
>         ProtectHome: no
>         ProtectSystem: no
>         IgnoreSIGPIPE: yes
>         RuntimeDirectoryMode: 0755
>         RuntimeDirectory: test-exec_runtimedirectory-owner
>         StandardInput: null
>         StandardOutput: inherit
>         StandardError: inherit
>         User: root
>         Group: nobody
> exec-runtimedirectory-owner.service: Failed at step GROUP spawning /bin/sh: No such process
> exec-runtimedirectory-owner.service: Main process exited, code=exited, status=216/GROUP
> exec-runtimedirectory-owner.service: Unit entered failed state.
> exec-runtimedirectory-owner.service: Failed with result 'exit-code'.
>         PID: 27971
>         Start Timestamp: Mon 2016-03-21 17:22:10 UTC
>         Exit Timestamp: Mon 2016-03-21 17:22:10 UTC
>         Exit Code: exited
>         Exit Status: 216
> Assertion 'service->main_exec_status.status == status_expected' failed at src/test/test-execute.c:65, function check(). Aborting.
> bisect run failed:
> exit code 134 from '/bin/bash -c make && sudo ./test-execute' is < 0 or >= 128
> ```
> 
> @ronnychevalier , please, have a look.

I see the problem, it is just the wrong test which is executed. I will
send a patch to fix that.

Thanks for the report!

**Comment by ronnychevalier** [comment]
@evverx See #2879

**Pull request merged**
