### PR TITLE
systemctl: fix edit when EDITOR contains arguments

### PR DESCRIPTION
**Pull request by jsynacek**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1231949.

### CODE REVIEW

**Comment by zonque** [comment]
This patch needs a commit log.

**Comment by jsynacek** [comment]
I have fixed the commit per above notes. Am I supposed to force push now, or commit to a different branch and create a new pull request?

**Comment by zonque** [comment]
Open a new one please, and reference this one.

**Comment by poettering** [comment]
Closing this one as it is obsoleted by #283

**Pull request closed without merging**
