### PR TITLE
Set theme jekyll-theme-primer

### PR DESCRIPTION
**Pull request by mbiebl**
This theme uses anchorjs to provide mouse-over anchor links.

Closes: #10418

### CODE REVIEW

**Comment by poettering** [comment]
Is this really that easy? I mean how does github find the theme? This isn't one of the default themes github offers unless I missed something, hence is it really that easy?

**Comment by mbiebl** [comment]
The readme at https://github.com/pages-themes/primer suggests that it is that easy.
We could just merge and see what happens? If things fall apart, a revert is trivial...

**Comment by poettering** [comment]
merged, but nothing happened afaics

**Comment by kirbyfan64** [comment]
It looks like it worked now, though I noticed the theme doesn't allow you to link to top-level headers for some reason, which makes anchors [useless in the portable services page](https://systemd.io/PORTABLE_SERVICES.html).

**Comment by mbiebl** [comment]
hm, indeed. This could be easily fixed though by using '##' and making '#' something like the page title which is only used at the beginning of the document.

**Comment by mbiebl** [comment]
I also notice that https://systemd.io/CODE_OF_CONDUCT.md seems broken. Dunno if this was already the case before the theme switch...

**Comment by mbiebl** [comment]
> It looks like it worked now, though I noticed the theme doesn't allow you to link to top-level headers for some reason, which makes anchors [useless in the portable services page](https://systemd.io/PORTABLE_SERVICES.html).

https://systemd.io/TRANSLATORS.html has the same problem. The other pages look fine.

**Pull request merged**
