### PR TITLE
Varlink json fix and two cleanups

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by yuwata** [comment]
I think 8688c29b5aece49805a244676cba5bba0196f509 should be reverted. If you agree, then please revert it.

**Comment by keszybz** [comment]
Done.

**Comment by yuwata** [comment]
Thanks.

**Comment by keszybz** [comment]
I added some more commits based on coverity report.

**Comment by yuwata** [comment]
LGTM.

**Pull request merged**
