### PR TITLE
network: do not enter failed state when received an invalid RA

### PR DESCRIPTION
**Pull request by yuwata**
Fixes the issue reported at https://github.com/systemd/systemd/issues/25891#issuecomment-1368509262.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx

**Review by bluca — APPROVED** [review]

**Comment by evverx** [comment]
@yuwata thanks! I haven't pulled this PR yet. I guess I'll just combine it with https://github.com/systemd/systemd/pull/26075 (which I haven't pulled yet either) next week hopefully.

I think now that packets like that are basically ignored log messages should probably be downgraded a bit (they are still prominently red in the journal as far as I understand) and something like ", ignoring" should probably be added.

**Comment by evverx** [comment]
I've just seen
```sh
host0: Requesting NDisc route (configuring,configured): dst: n/a, src: n/a, gw:>
host0: Failed to get DNSSL addresses: Bad message
host0: Setting SLAAC addresses and router.
host0: Configuring NDisc route (requesting,configuring,configured): dst: n/a, s>
host0: NDISC: Received Router Advertisement: flags none preference medium lifet>
host0: NDISC: Invoking callback for 'router' event.
host0: Requesting NDisc route (configuring,configured): dst: n/a, src: n/a, gw:>
host0: Failed to get DNSSL addresses: Invalid argument
host0: Failed
host0: State changed: configured -> failed
```
so it seems EINVAL can still sneak in somehow and https://github.com/systemd/systemd/issues/25891#issuecomment-1368509262 hasn't been fully fixed. I'll try to figure out what it was.

**Comment by evverx** [comment]
@yuwata I'll try to open an issue once I've figured out where it comes from. I saw the same thing with the encrypted DNS RA option in https://github.com/systemd/systemd/pull/30952 too. Looks like some functions from `src/shared/dns-domain.*` parsing domain names return EINVAL while `ndisc_router_process_options` expects `EBADMSG` but I'm not 100% sure.

**Comment by evverx** [comment]
-> https://github.com/systemd/systemd/issues/31168

**Pull request merged**
