### PR TITLE
missing: define several syscall numbers for MIPS arch

### LINKED ISSUE #17591: FTBFS on mipse*el:  ../src/basic/macro.h:415:9: error: static assertion failed: "__NR_close_range == systemd_NR_close_range"
Version: 247-rc2

systemd in experimental FTBFS on mipsel and mips64el
https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=mips64el&ver=247%7Erc2-1&stamp=1605223087&raw=0
https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=mipsel&ver=247%7Erc2-1&stamp=1605222663&raw=0

```
[56/2002] cc -Isrc/basic/libbasic.a.p -Isrc/basic -I../src/basic -Isrc/boot -I../src/boot -Isrc/core -I../src/core -Isrc/home -I../src/home -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/libsystemd-network -I../src/libsystemd-network -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -Isrc/libudev -I../src/libudev -Isrc/login -I../src/login -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/shared -I../src/shared -Isrc/shutdown -I../src/shutdown -Isrc/systemd -I../src/systemd -I../src/time-wait-sync -Isrc/timesync -I../src/timesync -Isrc/udev -I../src/udev -I../src/xdg-autostart-generator -I. -I.. -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -ffunction-sections -fdata-sections -Werror=shadow -include config.h -g -O2 '-fdebug-prefix-map=/<<PKGBUILDDIR>>=.' -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -pthread -fvisibility=default -MD -MQ src/basic/libbasic.a.p/fd-util.c.o -MF src/basic/libbasic.a.p/fd-util.c.o.d -o src/basic/libbasic.a.p/fd-util.c.o -c ../src/basic/fd-util.c
FAILED: src/basic/libbasic.a.p/fd-util.c.o
cc -Isrc/basic/libbasic.a.p -Isrc/basic -I../src/basic -Isrc/boot -I../src/boot -Isrc/core -I../src/core -Isrc/home -I../src/home -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/libsystemd-network -I../src/libsystemd-network -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -Isrc/libudev -I../src/libudev -Isrc/login -I../src/login -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/shared -I../src/shared -Isrc/shutdown -I../src/shutdown -Isrc/systemd -I../src/systemd -I../src/time-wait-sync -Isrc/timesync -I../src/timesync -Isrc/udev -I../src/udev -I../src/xdg-autostart-generator -I. -I.. -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -ffunction-sections -fdata-sections -Werror=shadow -include config.h -g -O2 '-fdebug-prefix-map=/<<PKGBUILDDIR>>=.' -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -pthread -fvisibility=default -MD -MQ src/basic/libbasic.a.p/fd-util.c.o -MF src/basic/libbasic.a.p/fd-util.c.o.d -o src/basic/libbasic.a.p/fd-util.c.o -c ../src/basic/fd-util.c
In file included from ../src/basic/fd-util.c:19:
../src/basic/missing_syscall.h:190:4: warning: #warning "name_to_handle_at number is not defined" [-Wcpp]
  190 | #  warning "name_to_handle_at number is not defined"
      |    ^~~~~~~
../src/basic/missing_syscall.h:243:4: warning: #warning "setns() syscall number unknown for your architecture" [-Wcpp]
  243 | #  warning "setns() syscall number unknown for your architecture"
      |    ^~~~~~~
In file included from ../src/basic/fd-util.c:19:
../src/basic/missing_syscall.h:409:4: warning: #warning "copy_file_range() syscall number unknown for your architecture" [-Wcpp]
  409 | #  warning "copy_file_range() syscall number unknown for your architecture"
      |    ^~~~~~~
../src/basic/missing_syscall.h:461:4: warning: #warning "bpf() syscall number unknown for your architecture" [-Wcpp]
  461 | #  warning "bpf() syscall number unknown for your architecture"
      |    ^~~~~~~
../src/basic/missing_syscall.h:554:4: warning: #warning "statx() syscall number unknown for your architecture" [-Wcpp]
  554 | #  warning "statx() syscall number unknown for your architecture"
      |    ^~~~~~~
In file included from ../src/basic/macro.h:4,
                 from ../src/basic/alloc-util.h:9,
                 from ../src/basic/fd-util.c:9:
../src/basic/macro.h:415:9: error: static assertion failed: "__NR_close_range == systemd_NR_close_range"
  415 |         static_assert(expr, #expr)
      |         ^~~~~~~~~~~~~
../src/basic/missing_syscall.h:745:1: note: in expansion of macro ‘assert_cc’
  745 | assert_cc(__NR_close_range == systemd_NR_close_range);
      | ^~~~~~~~~
[57/2002] cc -Isrc/basic/libbasic.a.p -Isrc/basic -I../src/basic -Isrc/boot -I../src/boot -Isrc/core -I../src/core -Isrc/home -I../src/home -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/libsystemd-network -I../src/libsystemd-network -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -Isrc/libudev -I../src/libudev -Isrc/login -I../src/login -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/shared -I../src/shared -Isrc/shutdown -I../src/shutdown -Isrc/systemd -I../src/systemd -I../src/time-wait-sync -Isrc/timesync -I../src/timesync -Isrc/udev -I../src/udev -I../src/xdg-autostart-generator -I. -I.. -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -ffunction-sections -fdata-sections -Werror=shadow -include config.h -g -O2 '-fdebug-prefix-map=/<<PKGBUILDDIR>>=.' -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -pthread -fvisibility=default -MD -MQ src/basic/libbasic.a.p/cgroup-util.c.o -MF src/basic/libbasic.a.p/cgroup-util.c.o.d -o src/basic/libbasic.a.p/cgroup-util.c.o -c ../src/basic/cgroup-util.c
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #17591.

### CODE REVIEW

**Comment by mbiebl** [comment]
Hi @yuwata, thanks for the patch and the effort to unify/simplify the defines.
It seems to fix the build on mips64el but on mipsel I now get:
```
In file included from ../src/basic/fd-util.c:19:
../src/basic/missing_syscall.h:34:6: error: #error "Unknown MIPS ABI"
   34 | #    error "Unknown MIPS ABI"
      |      ^~~~~
[12/1932] Compiling C object src/libsystemd/libsystemd_static.a.p/sd-bus_bus-message.c.o
```
There is this resource: https://wiki.debian.org/ArchitectureSpecificsMemo. I hope this is helpful.
@brauner you provided the last mips related fix, maybe you can chime in here. I don't really feel qualified to review that PR.

**Comment by yuwata** [comment]
@mbiebl Thank you for testing. I hope now the error is fixed. PTAL.

**Comment by mbiebl** [comment]
@yuwata looking better now. Build and `meson test` both passes on mipsel and mips64el.

**Comment by yuwata** [comment]
@mbiebl Thank you!

**Comment by mbiebl** [comment]
Looking good so far
https://buildd.debian.org/status/package.php?p=systemd&suite=experimental

The mipsel build failure is https://github.com/systemd/systemd/pull/17604

**Comment by mbiebl** [comment]
Thanks again @yuwata . Good to merge from my side

**Pull request merged**
