### PR TITLE
kernel-install: remove depmod script

### PR DESCRIPTION
**Pull request by lnussel**
The kernel-install script does not actually install the kernel and it's modules into the system. The script's purpose is to make the system boot the specified kernel, ie make the bootloader aware of it.

Calling depmod is not part of that job. It's actually counterproductive esp on removal as removing a kernel just means removing it from the bootloader, not deleting associated files from the system itself. That's particularly important when dealing with snaphots. In that case a kernel would only be removed from the ESP when the reference count drops to zero. So shouldn't remove modules from the current system.

### CODE REVIEW

**Comment by keszybz** [comment]
You have a point. depmod needs to be called whenever we add or remove module files in `/lib/modules`, and that could be separate from `kernel-install` `add`/`remove`. We put the call to depmod here purely for convenience of packaging of kernels in traditional package-based systems. But if we drop it, we need to figure out some replacement. A wrinkle that needs to be taken into account is that the depmod needs to happen before `kernel-install add`. I think we could move `depmod` to a `%transfiletrigger`. I tried to figure out how `%transfiletrigger` is ordered wrt. `%posttrans` that the kernel rpm uses to call `kernel-install`, and I couldn't figure this out. `rpm` docs are breadcrumbs scattered by the wind.

**Comment by lnussel** [comment]
Ah, that comes from Fedora then? In openSUSE the kernel scriptlets  do their magic independent of any bootloader stuff. Nowadays that should be moved file triggers though.

Anyway they way depmod works is rather screwed IMO and doesn't fit into a world of ro /usr. Those generated files do not belong to /usr as they are a composition of stuff that might be configured in /etc even. So can't be verified by rpm either. A bigger solution would probably move the depmod generated files to /var plus make modprobe work without (or generate the cache on demand).

**Comment by yuwata** [comment]
As the first step, how about to move the script to fedora rpm repository?

**Review by yuwata — APPROVED** [review]

**Comment by poettering** [comment]
> The kernel-install script does not actually install the kernel and it's modules into the system. The script's purpose is to make the system boot the specified kernel, ie make the bootloader aware of it.

Is that so?

The script's job is to register the newly installed kernel with all subsystems that need to be aware of it. Those traditionally are initrd builder, depmod stuff, boot loader. But could be anything else really.

While the primary case where the script is called automatically is when a kernel RPM is installed it's not exclusive to that. You might also want to call it whenever you install additional RPMs that carry kmods. because in that case you again want to run depmod, initrd and boot loader registration. 

> Calling depmod is not part of that job. It's actually counterproductive esp on removal as removing a kernel just means removing it from the bootloader, not deleting associated files from the system itself. That's particularly important when dealing with snaphots. In that case a kernel would only be removed from the ESP when the reference count drops to zero. So shouldn't remove modules from the current system.

This seems to be a local thing of your distro, but not a general rule that would apply to all distros. We need a generic hook system for rebuilding initrd/kmod/kernel registration when RPM based kmods modules are installed, so that the resulting registration encompasses all inputs. And we need a generic way to remove all generated data again.

Shipping pre-built depmod info certainly makes sense, but in that case kernel-install is kinda pointless anyway, as it is primarily about the non-prebuilt stuff...

**Comment by lnussel** [comment]
Lennart Poettering wrote:
>     The kernel-install script does not actually install the kernel and
>     it's modules into the system. The script's purpose is to make the
>     system boot the specified kernel, ie make the bootloader aware of it.
> 
> Is that so?
> 
> The script's job is to register the newly installed kernel with all 
> subsystems that need to be aware of it. Those traditionally are initrd 
> builder, depmod stuff, boot loader. But could be anything else really.
> 
> While the primary case where the script is called automatically is when 
> a kernel RPM is installed it's not exclusive to that. You might also 
> want to call it whenever you install additional RPMs that carry kmods. 
> because in that case you again want to run depmod, initrd and boot 
> loader registration.

It also needs to be called when creating or removing snapshots.

Calling depmod is inconsistent for two reasons IMO. Firstly the command 
line interface of kernel-install takes the kernel image from 
/some/random/specified/location. There is no relation to 
/lib/modules/$kernelversion. And secondly kernel-install does not 
actually install the kernel modules. So how do they end up in 
/lib/modules so that the depmod hook script can find them there?
IOW to be consistent kernel-install would either have to also copy 
modules or assume that whatever copies modules also knows that it's 
required to call depmod so those installed modules can actually be used.

>     Calling depmod is not part of that job. It's actually
>     counterproductive esp on removal as removing a kernel just means
>     removing it from the bootloader, not deleting associated files from
>     the system itself. That's particularly important when dealing with
>     snaphots. In that case a kernel would only be removed from the ESP
>     when the reference count drops to zero. So shouldn't remove modules
>     from the current system.
> 
> This seems to be a local thing of your distro, but not a general rule 
> that would apply to all distros. We need a generic hook system for 
> rebuilding initrd/kmod/kernel registration when RPM based kmods modules 
> are installed, so that the resulting registration encompasses all 
> inputs. And we need a generic way to remove all generated data again.

Yes, I agree about the hook system and that kernel-install should remove 
generated data in the efi partition. Removing generated data from /usr 
is the job of e.g. rpm though.
What files depmod generates exactly is not for this systemd script to 
know either. So even if a distro wants to call depmod via 
kernel-install, the place to install that script would be where depmod 
is, ie the kmod package IMO.

Also, how is this meant to be work with an A/B /usr? So far I assumed 
that one would call kernel-install to register the kernel of the 
to-be-booted volume, resp deregister the one of the old volume. This 
depmod script always operates on the currently mounted /usr though...

> Shipping pre-built depmod info certainly makes sense, but in that case 
> kernel-install is kinda pointless anyway, as it is primarily about the 
> non-prebuilt stuff...

Maybe our mental models are off. Even if kernel and initrd are static 
(or an UKI), they still needs to end up in the ESP somehow?

**Comment by poettering** [comment]
On Mi, 19.04.23 02:58, Ludwig Nussel ***@***.***) wrote:

> Lennart Poettering wrote:
> >     The kernel-install script does not actually install the kernel and
> >     it's modules into the system. The script's purpose is to make the
> >     system boot the specified kernel, ie make the bootloader aware of it.
> >
> > Is that so?
> >
> > The script's job is to register the newly installed kernel with all
> > subsystems that need to be aware of it. Those traditionally are initrd
> > builder, depmod stuff, boot loader. But could be anything else really.
> >
> > While the primary case where the script is called automatically is when
> > a kernel RPM is installed it's not exclusive to that. You might also
> > want to call it whenever you install additional RPMs that carry kmods.
> > because in that case you again want to run depmod, initrd and boot
> > loader registration.
>
> It also needs to be called when creating or removing snapshots.
>
> Calling depmod is inconsistent for two reasons IMO. Firstly the command
> line interface of kernel-install takes the kernel image from
> /some/random/specified/location. There is no relation to
> /lib/modules/$kernelversion.

On Fedora the kernel binary is installed into /usr/lib/modules/`uname
-r`/vmlinuz actually by RPM, and kernel-install then copies it into the
ESP/XBOOTLDR. Distros didn't agree on the RPM owned dir though, hence
this takes an absolute path.

We might want to update the kernel-install interface a bit, and imply
the path fedora uses if only a kernel version is specified on the
command line, or something like that.

> And secondly kernel-install does not actually install the kernel
> modules. So how do they end up in /lib/modules so that the depmod
> hook script can find them there?

rpm? unlike the kernel image itself the module paths are standardized
among distros.

> IOW to be consistent kernel-install would either have to also copy
> modules or assume that whatever copies modules also knows that it's
> required to call depmod so those installed modules can actually be
> used.

The model is: rpm drops everything into /usr/, and kernel-install then
copies it into ESP/XBOOTLDR/wherever else, and does other stuff.

> >     Calling depmod is not part of that job. It's actually
> >     counterproductive esp on removal as removing a kernel just means
> >     removing it from the bootloader, not deleting associated files from
> >     the system itself. That's particularly important when dealing with
> >     snaphots. In that case a kernel would only be removed from the ESP
> >     when the reference count drops to zero. So shouldn't remove modules
> >     from the current system.
> >
> > This seems to be a local thing of your distro, but not a general rule
> > that would apply to all distros. We need a generic hook system for
> > rebuilding initrd/kmod/kernel registration when RPM based kmods modules
> > are installed, so that the resulting registration encompasses all
> > inputs. And we need a generic way to remove all generated data again.
>
> Yes, I agree about the hook system and that kernel-install should remove
> generated data in the efi partition. Removing generated data from /usr
> is the job of e.g. rpm though.

Dunno. While rpms by default invoke kernel-install add when installing
an rpm and kernel-install remove when removing it, i see no reason why
users shouldn't be able to call this on their own if they like,
i.e. if they want to unregister a kernel from everything, or
re-register it.

> What files depmod generates exactly is not for this systemd script to
> know either. So even if a distro wants to call depmod via
> kernel-install, the place to install that script would be where depmod
> is, ie the kmod package IMO.

That is certainly true. The script would be a good candidate to be
mantained by kmod package, not by us.

> Also, how is this meant to be work with an A/B /usr? So far I assumed
> that one would call kernel-install to register the kernel of the
> to-be-booted volume, resp deregister the one of the old volume. This
> depmod script always operates on the currently mounted /usr
> though...

Option a: don't bother with kernel-install

Option b: pre-build your depmod stuff, and make /usr/ read-only. the
script already is skipped when /usr/ is read-only. A certain Ludwig
Nussel supplied the patch for that. ;-)

Immutable /usr/ generally implies a pre-built depmod I'd assume, and
thus not allow additional packages that carry kmods.

That said, if you can somehow convince kmod upstream that it should be
able to drop its output in /etc/ rather than /usr/ under certain
conditions you could have the best of both worlds: have an immutable
/usr/ without a pre-built depmod and thus allow combining external
kmods with kernel supplied knods.

> > Shipping pre-built depmod info certainly makes sense, but in that case
> > kernel-install is kinda pointless anyway, as it is primarily about the
> > non-prebuilt stuff...
>
> Maybe our mental models are off. Even if kernel and initrd are static
> (or an UKI), they still needs to end up in the ESP somehow?

But I am not sure kernel-install is necessarily the right appraoch
then. if everything is just simple pre-built files, and nothing needs
to get rebuilt/regnerated/signed/… then kernel-install is kinda
unnecessary.

In my own model built are type2 unified kernels systemd-sysupdate
would drop those files in. no kernel-install is called.

I mean, I think I understand where you are coming from, i.e. a model
where type1 .conf files are still generated. So in that case, you have
a bit of a hybrid: while much of your OS comes pre-built some final
bits are generated locally. So I guess for your case kernel-install
might be an option, but that sounds as if we should simply
automatically skip the steps that don't apply to you, and you ship
pre-build. Your "test -w /usr/lib/" patch sounds completely
appropriate to cover that then.

Lennart

--
Lennart Poettering, Berlin

**Comment by lnussel** [comment]
Lennart Poettering wrote:
> On Mi, 19.04.23 02:58, Ludwig Nussel ***@***.***) wrote:
> 
>  > Lennart Poettering wrote:
>  > > The kernel-install script does not actually install the kernel and
>  > > it's modules into the system. The script's purpose is to make the
>  > > system boot the specified kernel, ie make the bootloader aware of it.
>  > >
>  > > Is that so?
>  > >
>  > > The script's job is to register the newly installed kernel with all
>  > > subsystems that need to be aware of it. Those traditionally are initrd
>  > > builder, depmod stuff, boot loader. But could be anything else really.
>  > >
>  > > While the primary case where the script is called automatically is when
>  > > a kernel RPM is installed it's not exclusive to that. You might also
>  > > want to call it whenever you install additional RPMs that carry kmods.
>  > > because in that case you again want to run depmod, initrd and boot
>  > > loader registration.
>  >
>  > It also needs to be called when creating or removing snapshots.
>  >
>  > Calling depmod is inconsistent for two reasons IMO. Firstly the command
>  > line interface of kernel-install takes the kernel image from
>  > /some/random/specified/location. There is no relation to
>  > /lib/modules/$kernelversion.
> 
> On Fedora the kernel binary is installed into /usr/lib/modules/`uname
> -r`/vmlinuz actually by RPM, and kernel-install then copies it into the
> ESP/XBOOTLDR. Distros didn't agree on the RPM owned dir though, hence
> this takes an absolute path.

Even though there was no formal agreement, we've moved the kernel image 
to the same location meanwhile. The name is still arch dependent though 
AFAIK.

> We might want to update the kernel-install interface a bit, and imply
> the path fedora uses if only a kernel version is specified on the
> command line, or something like that.

Or to accept a relative path. That in combination with a --root option 
would also make sense IMO.

>  > > Calling depmod is not part of that job. It's actually
>  > > counterproductive esp on removal as removing a kernel just means
>  > > removing it from the bootloader, not deleting associated files from
>  > > the system itself. That's particularly important when dealing with
>  > > snaphots. In that case a kernel would only be removed from the ESP
>  > > when the reference count drops to zero. So shouldn't remove modules
>  > > from the current system.
>  > >
>  > > This seems to be a local thing of your distro, but not a general rule
>  > > that would apply to all distros. We need a generic hook system for
>  > > rebuilding initrd/kmod/kernel registration when RPM based kmods modules
>  > > are installed, so that the resulting registration encompasses all
>  > > inputs. And we need a generic way to remove all generated data again.
>  >
>  > Yes, I agree about the hook system and that kernel-install should remove
>  > generated data in the efi partition. Removing generated data from /usr
>  > is the job of e.g. rpm though.
> 
> Dunno. While rpms by default invoke kernel-install add when installing
> an rpm and kernel-install remove when removing it, i see no reason why
> users shouldn't be able to call this on their own if they like,
> i.e. if they want to unregister a kernel from everything, or
> re-register it.

Absolutely. Actually wrote some toy tool with that purpose in mind
https://github.com/lnussel/sdbootmenu

>  > What files depmod generates exactly is not for this systemd script to
>  > know either. So even if a distro wants to call depmod via
>  > kernel-install, the place to install that script would be where depmod
>  > is, ie the kmod package IMO.
> 
> That is certainly true. The script would be a good candidate to be
> mantained by kmod package, not by us.

So we agree to drop it here? :-)

>  > Also, how is this meant to be work with an A/B /usr? So far I assumed
>  > that one would call kernel-install to register the kernel of the
>  > to-be-booted volume, resp deregister the one of the old volume. This
>  > depmod script always operates on the currently mounted /usr
>  > though...
> 
> Option a: don't bother with kernel-install
> 
> Option b: pre-build your depmod stuff, and make /usr/ read-only. the
> script already is skipped when /usr/ is read-only. A certain Ludwig
> Nussel supplied the patch for that. ;-)

Yeah but now I'm fooling around with systemd-boot on a traditional rw 
system and end up with broken boot every other reboot because removing 
snapshots removes depmod files because of kernel-install :-)

> Immutable /usr/ generally implies a pre-built depmod I'd assume, and
> thus not allow additional packages that carry kmods.
> 
> That said, if you can somehow convince kmod upstream that it should be
> able to drop its output in /etc/ rather than /usr/ under certain
> conditions you could have the best of both worlds: have an immutable
> /usr/ without a pre-built depmod and thus allow combining external
> kmods with kernel supplied knods.

That would be the goal, yes.

>  > > Shipping pre-built depmod info certainly makes sense, but in that case
>  > > kernel-install is kinda pointless anyway, as it is primarily about the
>  > > non-prebuilt stuff...
>  >
>  > Maybe our mental models are off. Even if kernel and initrd are static
>  > (or an UKI), they still needs to end up in the ESP somehow?
> 
> But I am not sure kernel-install is necessarily the right appraoch
> then. if everything is just simple pre-built files, and nothing needs
> to get rebuilt/regnerated/signed/… then kernel-install is kinda
> unnecessary.
> 
> In my own model built are type2 unified kernels systemd-sysupdate
> would drop those files in. no kernel-install is called.

Ic. So you are assuming that that a UKI is shipped separately from the 
system. 90-uki-copy.install seems to suggest that there are use cases 
for having the UKI part of the system and then copied to ESP via 
kernel-install though.

cu
Ludwig

-- 
  (o_   Ludwig Nussel
  //\
  V_/_  http://www.suse.com/
SUSE Software Solutions Germany GmbH, GF: Ivo Totev
HRB 36809 (AG Nürnberg)

**Comment by keszybz** [comment]
> While the primary case where the script is called automatically is when a kernel RPM is installed it's not exclusive to that. You might also want to call it whenever you install additional RPMs that carry kmods. because in that case you again want to run depmod, initrd and boot loader registration.

For me, this is the crux of the problem. Depmod needs to be called whenever modules are added or removed under `/lib/modules/<uname>/`. We don't ship it pre-built because the modules are often split between multiple packages, and also because people do external modules. But this should step is logically separate from the step of taking a kernel and modules and copying it from `/usr` to `/boot` to be available for the boot loader.

Typing `depmod` to kernel install doesn't work in many cases:
- the example @poettering gave above: user does `kernel-install remove` on a kernel. The kernel is removed from `/boot`, but not from `/usr/lib/<uname>/`. The modules are also not touched. The depmod data should be present until they are removed.
- the example @lnussel gave above: partitions A and B share `/boot`. Removal of kernel and modules from partition A or B is independent of the presence of that kernel in `/boot`. 
- a VM uses direct kernel boot, and the kernel is never installed on the file system. But modules must be present and depmod info too.
- a system root image is built and contains a kernel + modules. After the image has been built, we want the depmod info to be present on the image. After the image is installed, `kernel-install` is used to copy the kernel to some appropriate location, but the image remains read-only.
- a special variant of this last case is `mkosi-initrd`: we want a bunch of kernel modules, but the kernel remains external.

>  You might also want to call it whenever you install additional RPMs that carry kmods. because in that case you again want to run depmod, initrd and boot loader registration.

This is not what happens. In Fedora, but I assume in other distros too: `kernel-install add` is only called when `kernel-core` is installed. If a user adds `kernel-modules-extra` or other module package at a later point, `depmod` is called. But the initrd is not regenerated, and the boot loader stuff is not touched.

> The model is: rpm drops everything into /usr/, and kernel-install then copies it into ESP/XBOOTLDR/wherever else, and does other stuff.

Yes, exactly! So let's let rpm scriptlets call `depmod` **once**. (In Fedora, scriptlets already call `depmod`, somewhat chaotically, at different points, and the via `kernel-install add` once again. So it'd be a matter of cleaning this all up.)  And then let `kernel-install` deal with the logically separate step of consuming this depmod info, and the kernel binary, to install them where appropriate. `kernel-install add` would still be called from the package that provides the kernel, but it would not touch `/usr` at all.

Similarly, depmod files should be removed when the last package that provides modules under `/lib/modules/<uname>` is removed. This should be totally independent of `kernel remove`.

Unless I'm missing something, this would cover all the cases we discussed here.

**Comment by poettering** [comment]
> > While the primary case where the script is called automatically is when a kernel RPM is installed it's not exclusive to that. You might also want to call it whenever you install additional RPMs that carry kmods. because in that case you again want to run depmod, initrd and boot loader registration.
> 
> For me, this is the crux of the problem. Depmod needs to be called whenever modules are added or removed under `/lib/modules/<uname>/`. We don't ship it pre-built because the modules are often split between multiple packages, and also because people do external modules. But this should step is logically separate from the step of taking a kernel and modules and copying it from `/usr` to `/boot` to be available for the boot loader.
> 
> Typing `depmod` to kernel install doesn't work in many cases:

You mean to ay "tying", I presume?

>     * the example @poettering gave above: user does `kernel-install remove` on a kernel. The kernel is removed from `/boot`, but not from `/usr/lib/<uname>/`. The modules are also not touched. The depmod data should be present until they are removed.

I am not convinced? It's not bootable, hence there's little point in having it. The data needs to be there when booting into it, it's redundant, unnecessary data otherwise.

>     * the example @lnussel gave above: partitions A and B share `/boot`. Removal of kernel and modules from partition A or B is independent of the presence of that kernel in `/boot`.

I am not following? I think we can safely say that if the RPM installing a kernel to a partition A goes away it's associated data should all be removed.

i.e. the RPM should contain the static, pre-generated data exclusively in /usr/, and kernel-install should generate the dynamic, local data, both in /usr/ and in the ESP/XBOOTLDR to actually make a kernel bootable. This could be depmod, dracut, ukify, "cp", or anything else really.

>     * a VM uses direct kernel boot, and the kernel is never installed on the file system. But modules must be present and depmod info too.

I am not sure this is a relevant case: we should just always make the installed kernels available in /usr/lib/modules/, no matter what, as primary source of the data, and so that things are comprehensively self-describing. The data outside of /usr/ should be redundant/generated, and it doesn't matter if that "outside" is the ESP or some VM-manager's local fs.

>     * a system root image is built and contains a kernel + modules. After the image has been built, we want the depmod info to be present on the image. After the image is installed, `kernel-install` is used to copy the kernel to some appropriate location, but the image remains read-only.

We cover this nicely: the depmod invocation is skipped when /usr/ is read-only, under the assumption the image builder took care of it.

> 
>     * a special variant of this last case is `mkosi-initrd`: we want a bunch of kernel modules, but the kernel remains external.
> 
> 
> > You might also want to call it whenever you install additional RPMs that carry kmods. because in that case you again want to run depmod, initrd and boot loader registration.
> 
> This is not what happens. In Fedora, but I assume in other distros too: `kernel-install add` is only called when `kernel-core` is installed. If a user adds `kernel-modules-extra` or other module package at a later point, `depmod` is called. But the initrd is not regenerated, and the boot loader stuff is not touched.
> 
> > The model is: rpm drops everything into /usr/, and kernel-install then copies it into ESP/XBOOTLDR/wherever else, and does other stuff.
> 
> Yes, exactly! So let's let rpm scriptlets call `depmod` **once**. (In Fedora, scriptlets already call `depmod`, somewhat chaotically, at different points, and the via `kernel-install add` once again. So it'd be a matter of cleaning this all up.) And then let `kernel-install` deal with the logically separate step of consuming this depmod info, and the kernel binary, to install them where appropriate. `kernel-install add` would still be called from the package that provides the kernel, but it would not touch `/usr` at all.
> 
> Similarly, depmod files should be removed when the last package that provides modules under `/lib/modules/<uname>` is removed. This should be totally independent of `kernel remove`.
> 
> Unless I'm missing something, this would cover all the cases we discussed here.

**Comment by poettering** [comment]
> That is certainly true. The script would be a good candidate to be mantained by kmod package, not by us.
> So we agree to drop it here? :-)

So well, you have a point. The only reason I'd not move it right now is mostly that it's still in flux, i.e. we have discussions like this one. I figure we should ask the kmod maintainers if they want it only if we all came to a clear agreement that covers the big picture comprehensively both for immutable distros and classic ones in a reasonably well.

**Comment by poettering** [comment]
> Yeah but now I'm fooling around with systemd-boot on a traditional rw system and end up with broken boot every other reboot because removing snapshots removes depmod files because of kernel-install :-)

This sounds like a very specific issue with snapshot-based OSes with writable /usr/. But not sure I follow why this even is a problem at all? I mean, if kernel-install for snapshot X is only invoked from an environment based on X then things should be fine, because the depmod removal would not propagate to snapshot Y. If it does, it seems you do "cross-namespace removals"? But that's a bit icky, no?

Anyway, it appears to me that this is coming from a background that is different from what kernel-install was originally designed for. Which is entirely fine and we can look into accomodating this scenario too, but just deleting the depmod thing outright seems very drastic and wrong to me then.

Anyway, I am sure we can find a different way, but not sure I even grok the original problem here, i.e. why one snapshot here would affect the other. please elaborate

**Comment by lnussel** [comment]
Lennart Poettering wrote:
>     Yeah but now I'm fooling around with systemd-boot on a traditional
>     rw system and end up with broken boot every other reboot because
>     removing snapshots removes depmod files because of kernel-install :-)
> 
> This sounds like a very specific issue with snapshot-based OSes with 
> writable /usr/. But not sure I follow why this even is a problem at all? 
> I mean, if kernel-install for snapshot X is only invoked from an 
> environment based on X then things should be fine, because the depmod 
> removal would not propagate to snapshot Y. If it does, it seems you do 
> "cross-namespace removals"? But that's a bit icky, no?
> 
> Anyway, it appears to me that this is coming from a background that is 
> different from what kernel-install was originally designed for. Which is 
> entirely fine and we can look into accomodating this scenario too, but 
> just deleting the depmod thing outright seems very drastic and wrong to 
> me then.

Well, it got the discussion started to figure out what kernel-install is 
designed for :-)

So far I've used it like this:

	for k in "/.snapshots/$num"/snapshot/usr/lib/modules/*/vmlinuz; do
		v="${k%/*}"
		v="${v##*/}"
		/usr/bin/kernel-install add "$v" "$k"
	done

Ie pass a snapshot number and kernel-install does whatever is needed to 
make the snapshot appear in the sd-boot menu (or remove it). In a RO 
system kernel-install would be called only by snapper when new versions 
of the OS are created (or old ones removed). Ie unrelated to /. Same in 
a traditional system but kernel-install would in addition also be called 
by rpm file triggers when kernels are added or removed to/from /.

That works fine as long as scripts only do stuff with the ESP resp 
staging area. When a script like depmod operates on the actual / things 
fall apart.

So I see three way to accommodate that use case

- don't have scripts that mess with / resp /usr
- add a --root option so kernel-install can take files from a location 
unrelated to /
- call kernel-install in the chroot that it should make bootable. That 
may however would require overlays for /etc and /var and what not.

cu
Ludwig

-- 
  (o_   Ludwig Nussel
  //\
  V_/_  http://www.suse.com/
SUSE Software Solutions Germany GmbH, GF: Ivo Totev
HRB 36809 (AG Nürnberg)

**Comment by lnussel** [comment]
> kernel-install is also the entrypoint for people who build a kernel via "make" from upstream sources. Ripping out depmod and moving it to RPM is hence pretty pointless, it just makes life harder for everyone.

`make modules_install` already calls depmod itself. Just like with rpm the only job of kernel-install would be the bootloader integration. If kernel-install would also install the modules, then I'd agree calling depmod would make sense too.  Right now kernel-install does not install modules so not it's job to call depmod either IMO.

> > Similarly, depmod files should be removed when the last package that provides modules under `/lib/modules/<uname>` is removed. This should be totally independent of `kernel remove`.
> 
> hmm? a rpm that provides kmods for some kernel should be installed _after_ that kernel and be removed _before_ that kernel. hence the correct way should be if each involved RPM would run `kernel-install add` on install. The kmod rpms should also call `kernel-install add` on removal. The kernel main rpm should call `kernel-install remove`.

That can be done totally independent of depmod.

**Comment by poettering** [comment]
so i am still not convinced that just dropping the depmod script is a good idea. while i can see it is not useful in some scenarios, ultimately kernel-install is just a plugin framework where people can drop in stuff whenever a kernel is installed or some other event happens that makes people want to register/rebuild/resign/… a kernel. Those other events could be:

1. a snapshot is made
2. a secondary kmod package is installed
3. a configuration change is made that must propagate into the initrd and beyond
4. a crucial software package has been update which should propagate into the initrd and beyond
5. …

In some of these cases we might need to do some things and others other things. I think we should keep things generic and basically "rebuild the world" if in doubt. At the same time we should of course support setups where specific steps are not desirable because rootfs is read-only or similar.

So for the 2nd item in the list above I am pretty sure we should keep the depmod stuff, because it's essential then.

Hence I think some tweaks to make the plugin become a true NOP in all necessary cases I'd very welcome, but dropping it altogether sounds wrong to me.

**Pull request closed without merging**
