### PR TITLE
Introduce $LISTEN_NAMES (v2)

### PR DESCRIPTION
**Pull request by maciejaszek**

### CODE REVIEW

**Comment by poettering** [comment]
As already indicated I think we can simplify the way how we collect the names for the sockets. I think we should not turn the single name into a list in socket.c, but only in service.c when we start merging everything we got.

**Comment by grooverdan** [comment]
Is asking for an interface in systemd.so like the following possible? Otherwise every user of the interface is going to be writing this function anyway.

<pre>const char *sd_listen_name(int fd);</pre>

**Comment by poettering** [comment]
@grooverdan sure, we can add that, but should be a separate patch i figure...

Also, i doubt we can make this a `const char*`. We probably have to allocate it so it will be `char*` and you have to `free()` it.

**Comment by grooverdan** [comment]
Was thinking it might be possible to overwrite an separator with \0 in the env but whatever you think is best.

**Comment by poettering** [comment]
@maciejaszek heya, I now posted a reworked version of this, fixing everything I saw, and changing a few other things (including that i named it LISTEN_FDNAMES now, to that we can keep the "fdname" word in all places), in #1468. Closing this one hence!

Thank you very much for your work!

**Pull request closed without merging**
