### PR TITLE
ci: pin mkosi to SHAs as well

### PR DESCRIPTION
**Pull request by evverx**
I somehow overlooked it. @mrc0mmand could you take look?

### CODE REVIEW

**Review by mrc0mmand — APPROVED** [review]
LGTM!

**Comment by mrc0mmand** [comment]
All mkosi CIs are green, so let's ship it!

**Comment by Werkov** [comment]
@evverx What is the motivation behind pointing to commit hashes instead of tags?

**Comment by evverx** [comment]
@Werkov it was https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
> Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release

**Comment by evverx** [comment]
It would be great if they implemented https://github.com/dependabot/dependabot-core/issues/2835#issuecomment-902136798 though

**Comment by Werkov** [comment]
Thanks. That makes some sense.

**Comment by evverx** [comment]
Just to clarify, even though that page is focused on security I'm more interested in the ability to jump from one version to another to catch issues like https://github.com/systemd/systemd/pull/21505 and https://github.com/systemd/systemd/pull/21340 before they affect the CI globally. If the workflows pointed to tags it wouldn't be possible.

**Pull request merged**
