### PR TITLE
io-util: actually retry on failure

### LINKED ISSUE #30152: Assertion failure in `loop_write_full`
```
[   36.321469] systemd-logind[546]: Assertion '(size_t) k <= nbytes' failed at src/basic/io-util.c:171, function loop_write_full(). Aborting.
```

I think it's failing to handle EAGAIN properly,
since the alternative is that the write succeeded and k returned more than nbytes
which should not be possible.

`k = write(fd, p, nbytes);` returns some k < 0 if it fails
and `if (errno != EAGAIN || timeout == 0) return -errno`
means the assert is only reachable on EAGAIN on a non-zero and non-infinite timeout.

The `fd_wait_for_event` is supposed to block until writable
and should return `r == POLLOUT` since it returns .revents
on success, which is a mask of the passed events.

However, instead of trying again it falls-through to the assert
because it only retries when the poll returns a transient error or the timeout was infinite.

This appears to have been added in https://github.com/systemd/systemd/pull/29071 by @YHNdnzj 

The test where I encountered this failure can be run by `mkosi --image=system '--kernel-command-line-extra=SYSTEMD_UNIT_PATH=/usr/lib/systemd/tests/testdata/testsuite-23.units:/usr/lib/systemd/tests/testdata/units: systemd.unit=testsuite.target systemd.wants=testsuite-23.service noresume oops=panic panic=1 systemd.wants=end.service' qemu` but it doesn't reliably happen.

### PR DESCRIPTION
**Pull request by yuwata**
Follow-up for e22c60a9d5dfc5f0b260c7906f3546aef2925998.

Fixes #30152.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
I have a _sneaking_ suspicion that the Packit stuff is being affected by similar networking issues like CentOS CI. I shouldn't have said _things_ in https://github.com/systemd/systemd/pull/30153#issuecomment-1823285840. But the last testing-farm job passed with one unrelated test fail (which I'll look into shortly), so I'd go ahead and merge this, especially given it's a trivial change.

**Comment by bluca** [comment]
Are you saying you _jinxed it_? You know that's the first rule of the cloud

**Review by bluca — APPROVED** [review]

**Comment by poettering** [comment]
ouch

**Comment by YHNdnzj** [comment]
Oops. Thank you for the fix

**Pull request merged**
