### PR TITLE
ethtool: Fix speed in 593022fa377d40d9a645919759b04c53cf4eace8

### PR DESCRIPTION
**Pull request by ssahani**
We should use the DIV_ROUND_UP missed in the commit 593022fa377d40d9a645919759b04c53cf4eace8

### CODE REVIEW

**Comment by poettering** [comment]
lgtm

**Comment by benjarobin** [comment]
A minor style fix in link_config_apply of link-config.c
Could you move the line :  `speed = DIV_ROUND_UP(config->speed, 1000000);`
just after `ethtool_set_glinksettings`  inside the `if`

**Comment by keszybz** [comment]
Hm, ethtool_set_speed does not set `port`. So `port` will be silently ignored if `ethtool_set_glinksettings` is not supported. It should either be changed to do that, if possible, or a warning should be emitted that `port` is being ignored.

**Comment by ssahani** [comment]
updated

**Pull request merged**
