### PR TITLE
time-util.c: get_timezone: Follow nested /etc/localtime links

### PR DESCRIPTION
**Pull request by martin-flaska**
When `/etc/localtime` is a symbolic link pointing to another symbolic link, `get_timezone` will return `-EINVAL` instead of the timezone. This issue can cause systemd-networkd DHCPServer to fail.

This should also help to fix any other problems with any part of the systemd checking the current local time - e.g. `timedatectl status`, where "Timezone=..." part is missing in this case.

The max. number of nested symbolic links is 10, just for simplicity sake and also to prevent circular links.

```
# ln -sf /data/etc/localtime /etc/localtime
# ls -l /etc/localtime
lrwxrwxrwx 1 root root 19 Sep 20 15:58 /etc/localtime -> /data/etc/localtime
# ls -l /data/etc/localtime
lrwxrwxrwx 1 root root 33 Sep 20 15:52 /data/etc/localtime -> /usr/share/zoneinfo/Europe/Vienna
#
# date
Fri Sep 20 15:58:58 CEST 2024
# timedatectl show
LocalRTC=no
CanNTP=yes
NTP=yes
NTPSynchronized=yes
TimeUSec=Fri 2024-09-20 15:59:14 CEST
RTCTimeUSec=Fri 2024-09-20 15:59:15 CEST
```

With this fix:
```
# timedatectl show
Timezone=Europe/Vienna
LocalRTC=no
CanNTP=yes
NTP=yes
NTPSynchronized=yes
TimeUSec=Mon 2024-09-23 17:14:46 CEST
RTCTimeUSec=Mon 2024-09-23 17:14:47 CEST
```

Note: I did not implement `timedatectl set-time` part yet - to update the last symbolic link.

### CODE REVIEW

**Review by yuwata — CHANGES_REQUESTED** [review]
Please use `chase()` instead of using the custom loop.

**Comment by martin-flaska** [comment]
@yuwata 
> Please use `chase()` instead of using the custom loop.

Thank you for the suggestion, I did not know this function exists. Do you suggest specifically `chase()` or is there some its better alternative, I mean `chase_...(`, for this need ? For instance `chase_extract_filename` which sounds equivalent to `chase()` with `CHASE_EXTRACT_FILENAME` flag. Checking the comment next to it: `Only return the last component of the resolved path`, which sounds exactly what is needed here, probably :). I am little bit lost in that `chase.h` code - no brief description for those helper functions. Any detailed suggestion would be really appreciated.

Also, does the `chase()` aproach limits the max symlink nesting level or prevents endless recursion for circular symlinks?

**Comment by yuwata** [comment]
> > Please use `chase()` instead of using the custom loop.
> 
> Thank you for the suggestion, I did not know this function exists. Do you suggest specifically `chase()` or is there some its better alternative, I mean `chase_...(`, for this need ? For instance `chase_extract_filename` which sounds equivalent to `chase()` with `CHASE_EXTRACT_FILENAME` flag. Checking the comment next to it: `Only return the last component of the resolved path`, which sounds exactly what is needed here, probably :). I am little bit lost in that `chase.h` code - no brief description for those helper functions. Any detailed suggestion would be really appreciated.

The current code checks if the resolved path points to under /usr/share/zoneinfo/. So, I think pure `chase()` should be better, unless if you want to drop the check about /usr/share/zoneinfo/.
So, chase() + path_startswith("/usr/share/zoneinfo/") + timezone_is_valid() should be the way to go, I think.

> Also, does the `chase()` aproach limit the max symlink nesting level or prevents endless recursion for circular symlinks?

Yes. IIRC.

**Comment by poettering** [comment]
No. /etc/localtime is API you cannot just redefine it like this. Moreover, timedated modify the thing, but that's never going to work like this.

Sorry, but I guess this is yet another attempt to invent a read-only /etc/ that isn't actually read-only. But I am really not convinced about that model. If you want to have an immutable /etc/, then good, go for it, but /etc/localtime is part of it. If you want a mutable /etc/localtime then make /etc/ mutable. 

I am vehemently agains any changes that move files like this, because that means we cannot update them atomically via create/rename anymore.

sorry, but no.

**Pull request closed without merging**
