### PR TITLE
tests: fuzz dns resource records

### PR DESCRIPTION
**Pull request by evverx**
It should help to catch issues like https://github.com/systemd/systemd/issues/19584 and https://github.com/systemd/systemd/issues/25449

### CODE REVIEW

**Comment by keszybz** [comment]
LGTM.

**Comment by evverx** [comment]
It fails under UBSan in four different places almost as soon as it starts. `dns_resource_record_to_string` and `dns_resource_record_to_json` need some tweaking to withstand at least 15 seconds of fuzzing to make the CI happy. I'll try to take a look next week.

**Comment by keszybz** [comment]
@evverx ?

**Comment by evverx** [comment]
I haven't fixed `dns_resource_record_to_string` and `dns_resource_record_to_json` yet. I ended up looking for other places that aren't covered by the fuzz target where those null pointers are passed around and how they are handled. in the case of `nsec3.salt` at least the latest versions of openssl and gcrypt seem to handle them fine.

I think the fastest way to start running this fuzz target on OSS-Fuzz would be to merge it and wait for about 6 hours until it gets picked up by OSS-Fuzz. Once it's there OSS-Fuzz should report those issues and CIFuzz should stop failing. To avoid breaking the CI another option would be to turn off the pointer overflow check temporarily to make the CI green, merge the PR and bring the check back in about 6 hours.

**Comment by evverx** [comment]
Before I forget while I was going through `dns_resource_record_to_string` and `dns_resource_record_to_json` I noticed that `dns_resource_record_to_json` rejects `DNS_TYPE_OPENPGPKEY` along with unparsable records. It has nothing to do with fuzzing but looks like a bug to me.

**Comment by keszybz** [comment]
This still LGTM. When oss-fuzz starts reporting issues, we'll deal with them.

**Pull request merged**
