### PR TITLE
tmpfiles: split out config for systemd-resolve

### PR DESCRIPTION
**Pull request by keszybz**
This mirrors what was done in 564761fcaeda8c013210f7c6934847a6d0228ec9
for sysusers.d. If we allow separating resolved sysusers config
in a subpackage, we should do the same for the symlink that is
only useful when resolved is installed.

Related to #21317.

### CODE REVIEW

**Review by yuwata — APPROVED** [review]
LGTM.

**Comment by poettering** [comment]
lgtm

**Comment by poettering** [comment]
maybe prep a NEWS file entry for this right-away, since it's a weak compat break since people might order their own tmpfiles.d snippets against systemd.conf

**Comment by keszybz** [comment]
I think it's easier to prepare NEWS entries while right before the release, except maybe for some complicated stuff. Someone needs to walk over all the commits anyway.

**Comment by keszybz** [comment]
build (gcc):  322/1232 test-repart                             TIMEOUT 30.01 s , looks unrelated.

**Comment by mbiebl** [comment]
I guess it makes sense to split the tmpfiles as was done for the sysusers file.

My only remark is, that we do have a bit of any inconsisteny regarding our naming. Sometimes we use systemd-foo, sometimes only foo

Example:
timesyncd
```
/etc/systemd/timesyncd.conf (no systemd prefix)
/lib/systemd/ntp-units.d/80-systemd-timesync.list
/usr/lib/sysusers.d/systemd-timesync.conf
```
coredump
```
/etc/systemd/coredump.conf (no systemd prefix)
/usr/lib/sysctl.d/50-coredump.conf (no systemd prefix)
/usr/lib/sysusers.d/systemd-coredump.conf
```
and so on.

**Comment by keszybz** [comment]
No need for the prefix when it's already in the directory name: /etc/systemd/foo. For the other ones, true, there can be some inconsistencies, but at least the examples you showed don't show this. 50-coredump.conf has no "systemd" prefix because it configures other coredump-related settings, not just the core pattern.

**Comment by mbiebl** [comment]
> 50-coredump.conf has no "systemd" prefix because it configures other coredump-related settings, not just the core pattern.

well, but `kernel.core_pattern=|/lib/systemd/systemd-coredump` pretty much makes it systemd-coredump specific and it's not a generally usable sysctl file

**Comment by pemensik** [comment]
This change improves situation a bit, because the /etc/resolv.conf would not be created if systemd-resolved is uninstalled. It would still create the file in case systemd-resolved is just disabled, but present on the system. Which still leads to disabled service by default and should be done different way, just as I proposed in PR #21317.

Please note Ubuntu and Debian already change it by downstream file and have this file creation missing. I think I have idea why downstream patch was chosen.

**Comment by pemensik** [comment]
No, they don't. They have limited variant in *debian.conf*, which seems like minimalistic *etc.conf*.

**Comment by pemensik** [comment]
It was originally related to MR #21257, where I thought less conflicting proposal including removal of /etc/resolv.conf spawning originated. It seems even that is too radical for systemd. MR #21317 just introduced alternative way to ensure /etc/resolv.conf exists, but without issues left on systemd-resolved stop or disablement.

**Comment by pemensik** [comment]
> To be more specific, in Debian/Ubuntu we don't install etc.conf at all.

Oh, you said we. Do you know the reason for that? Can you comment, why is upstream file replaced with a distribution specific one?

**Comment by keszybz** [comment]
focal-amd64: TEST-50-DISSECT:                    FAIL     (313 s)
focal-ppc64el: test-json
packit: 467/957 test-json                                                                 FAIL              0.28s   killed by signal 6 SIGABRT

The second and third are interesting, but all seem unrelated. 

The failure is the same in both cases on ppc64el:
```
/* test_float */
Assertion 'json_variant_is_real(json_variant_by_index(v, 7)) && json_variant_is_integer(json_variant_by_index(v, 7)) && json_variant_integer(json_variant_by_index(v, 7)) == 10' failed at src/test/test-json.c:540, function test_float_match(). Aborting.
```
@poettering, is this related to c79aaff9d53c992ef0f2d6a24163c9972819df24?

**Comment by bluca** [comment]
> focal-amd64: TEST-50-DISSECT: FAIL (313 s) focal-ppc64el: test-json packit: 467/957 test-json FAIL 0.28s killed by signal 6 SIGABRT
> 
> The second and third are interesting, but all seem unrelated.
> 
> The failure is the same in both cases on ppc64el:
> 
> ```
> /* test_float */
> Assertion 'json_variant_is_real(json_variant_by_index(v, 7)) && json_variant_is_integer(json_variant_by_index(v, 7)) && json_variant_integer(json_variant_by_index(v, 7)) == 10' failed at src/test/test-json.c:540, function test_float_match(). Aborting.
> ```
> 
> @poettering, is this related to [c79aaff](https://github.com/systemd/systemd/commit/c79aaff9d53c992ef0f2d6a24163c9972819df24)?

It's https://github.com/systemd/systemd/issues/21390

**Comment by mbiebl** [comment]
> No, they don't. They have limited variant in _debian.conf_, which seems like minimalistic _etc.conf_.

Well, I should know. I'm the maintainer :-)

**Comment by mbiebl** [comment]
> Oh, you said we. Do you know the reason for that? Can you comment, why is upstream file replaced with a distribution specific one? 

debian.conf is not really a replacemt for etc.conf.

It's quite simple: We don't install/support factory-reset.

**Pull request merged**
