### PR TITLE
core: fix D-Bus API

### LINKED ISSUE #7129: systemd-run does not support SystemCallFilter and SystemCallErrorNumber
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> Debian

### In case of bug report: Expected behaviour you didn't see

> The output of ls in the directory I ran the command in

### In case of bug report: Unexpected behaviour you saw

> Unknown assignment SystemCallFilter=~fsync sync syncfs fdatasync msync sync_file_range.
> Failed to create bus message: Invalid argument

### In case of bug report: Steps to reproduce the problem

> `systemd-run --user --wait --tty -p SystemCallFilter="~fsync sync syncfs fdatasync msync sync_file_range" -p SystemCallErrorNumber=0 -- ls`

### PR DESCRIPTION
**Pull request by yuwata**
This fixes bugs introduced by cffaed83e87bde81378b2be74192193850d0e03a.

Closes #7129.

### CODE REVIEW

**Comment by poettering** [comment]
ouch. lgtm

**Comment by poettering** [comment]
hmm, any chance you can rebase this PR on current git and force push? The CI was broken with git until just now, and this was fixed a few moments ago with another commit. To make sure we don't break it right-away again, it would be great if you could rebase this PR and force push so that the CI runs over this again?

**Comment by yuwata** [comment]
Sure, rebased.

**Comment by poettering** [comment]
excellent! thanks!

**Comment by yuwata** [comment]
BTW, it seems no test for D-Bus API especially `bus_append_unit_property_assignment()` in bus-unit-util.c. Since D-Bus API is a kind of API, then its behavior should not be changed so frequently. So, I think we should prepare test for it. Are there any plan?

**Comment by yuwata** [comment]
The CI failure in xenial-s390x is related to avahi-daemon and seems not related to this PR.
```
Errors were encountered while processing:
 avahi-daemon
 avahi-utils
 libnss-mdns:s390x
E: Sub-process /usr/bin/dpkg returned an error code (1)
blame: https://git.launchpad.net/~pitti/systemd/+git/debian
autopkgtest [08:46:55]: ERROR: erroneous package: Test dependencies are unsatisfiable. A common reason is that your testbed is out of date with respect to the archive, and you need to use a current testbed or run apt-get update or use -U.
badpkg: Test dependencies are unsatisfiable. A common reason is that your testbed is out of date with respect to the archive, and you need to use a current testbed or run apt-get update or use -U.
```

**Comment by poettering** [comment]
> BTW, it seems no test for D-Bus API especially bus_append_unit_property_assignment() in bus-unit-util.c. Since D-Bus API is a kind of API, then its behavior should not be changed so frequently. So, I think we should prepare test for it. Are there any plan?

Yes, this definitely should have some automated testing. A new test case for the CI would be very very welcome!

**Pull request merged**
