### PR TITLE
Implement boot counting scheme in systemd-boot

### PR DESCRIPTION
**Pull request by msekletar**
This PR implements (roughly) scheme as proposed by Kay here

https://github.com/systemd/systemd/issues/909#issuecomment-128789172

### CODE REVIEW

**Comment by msekletar** [comment]
Closing until I figure out what Semaphore doesn't like. Will post v2, soon. Sorry for the noise.

**Comment by msekletar** [comment]
Hmm, Semaphore already deleted build logs. Before I was able to figure out what's going on. Since build passes Just Fine (tm) on my machine, I am reopening this PR to re-trigger the Semaphore build.

**Comment by zonque** [comment]
Re-opening the PR apparently doesn't trigger a rebuild. Just close the PR and open a new one I guess.

**Comment by msekletar** [comment]
v2 -> #1894

**Pull request closed without merging**
