### PR TITLE
Fail RequisiteOf units with oneshots

### PR DESCRIPTION
**Pull request by bl33pbl0p**
Fixes: #11422

Oneshots going to inactive directly without ever entering UNIT_ACTIVE is
considered success. This however means that if something both Requires=
and Requisites= a unit of such nature, the verify-active job getting
merged into the start job makes it lose this property of failing the
depending jobs, as there, the start job has the result JOB_DONE on
success, so we never walk over RequisiteOf units.

This change makes sure that such unit's job always fails. It is also only
meaningful with After=, but so is Requisite= itself. Also, we also catch
cases like a oneshot having RemainAfterExit= true making us start up
properly in such a setting, but then removing it, reloading the unit,
and restarting it. In such a case, we go down due to restart propagation
before them, and our start job waits on theirs, properly failing with
the JOB_DEPENDENCY result.

### CODE REVIEW

**Comment by bl33pbl0p** [comment]
The problem isn't limited to local merging in transaction (before it gets activated), merging across transaction (say in an installed job) can have an equal effect that

**Comment by bl33pbl0p** [comment]
This is not limited to just in-transaction merging.

For instance, if you have a oneshot unit you Requisite= + After= from another unit, and then enqueue a start job for first one, and then start your unit, its verify-active job merges into the installed one, and it starts up successfully instead of failing.

I did it at that point in the code because I think invalidation here should work wrt job processing (and unlike on state change with BindsTo=).

**Comment by poettering** [comment]
hmm, the condition thin is actually a major point. I think this convinces me that your patch is actually indeed the way to go.

Hmm, but let's wait for v242 for this, given this has the chance to break stuff.

(I think complaining with a warning if people use Requisite= on a oneshot service actually would still be great, but i guess this can be handled separate from this PR. Patch very welcome for that too, hint hint ;-))

**Comment by poettering** [comment]
hmm, can you mention the condition thing in the comment in your patch, too, btw?

**Comment by bl33pbl0p** [comment]
Does it look okay now?

**Comment by poettering** [comment]
yes

**Comment by poettering** [comment]
thanks!

**Pull request merged**
