### PR TITLE
Add croatian translation

### PR DESCRIPTION
**Pull request by muzena**

### CODE REVIEW

**Comment by martinpitt** [comment]
Can you please squash the second and third commit into the first, and prefix the commit log with "po:"?

**Comment by zonque** [comment]
> Can you please squash the second and third commit into the first, and prefix the commit log with "po:"?

GitHub can squash commits now, and for once, we can use that feature on purpose ;)

**Comment by zonque** [comment]
> GitHub can squash commits now

Eh, on this PR again, it doesn't work. I'm puzzled. Will do it manually.

**Comment by zonque** [comment]
Merged, thanks!

**Pull request closed without merging**
