### PR TITLE
Script indentation cleanups

### PR DESCRIPTION
**Pull request by keszybz**
Things were mostly random, and this was annoying me when copying stuff between different files.
Let's standarize on the most common indentation.

### CODE REVIEW

**Comment by yuwata** [comment]
I'd like shell completions to be also re-indented.

**Comment by poettering** [comment]
i must say i would have standardized on 8ch everywhere. but i guess this works too

**Comment by keszybz** [comment]
shell-completion now done too.

**Comment by poettering** [comment]
please also update the first rule in CODING_STYLE

**Comment by keszybz** [comment]
> please also update the first rule in CODING_STYLE

Adjusted.

**Comment by poettering** [comment]
needs a rebase!

**Comment by keszybz** [comment]
Updated.

**Pull request merged**
