### PR TITLE
journal: Add journal sync

### PR DESCRIPTION
**Pull request by anoo1**
Replicate the functionality provided by 'journalctl --sync'
in the journal library.
Reference: systemd/systemd#5602

### CODE REVIEW

**Comment by poettering** [comment]
I really don't like synchronous calls exposed by libraries like this I must say. I'd much prefer if we could find a different solution to this. One option would be if journald would offer a bus call for this. Now that's quite problematic IRL, as dbus-daemon is a client journald (as it logs via syslog), and if journald would offer APIs on the bus, and the bus uses the journal, then we'd have a cyclic dependencies possibly resulting in a deadlock. One option out of that would be if we'd do this via a tiny auxiliary service that does little more than just offering a bus API for the journal and then forwards it to the journal via signals and stuff. 

With that, we'd then make that bus API the official API for accessing journal functionality such as syncing, and people can call that synchronously or async, the way they prefer, and they way dbussupports it anyway.

Does that make sense?

**Comment by anoo1** [comment]
@poettering Thanks for the feedback. What do you think about the proposal to add a new:

dbus method - sync_journal() -> uint64_t token
dbus signal - sync_complete -> uint64_t token

From a journald perspective this would be adding a message / token onto the queue and broadcasting the signal when all previous work is complete.

**Comment by poettering** [comment]
@anoo1 I'd probably just make this a simple asynchronous method call: "Synchronize()", that will issue the sync operation, and only send the "method return" message when that's complete.

**Comment by anoo1** [comment]
New commit uploaded to create a journal dbus object and expose a Synchronize method.

**Comment by anoo1** [comment]
hi @poettering , I added an optional journal dbus interface because wasn't sure that systemd would want to offer one as a default, but re-reading your initial comment, maybe that's what you were looking for (to have journald add the dbus interface). I can make an additional pull request (or commit) to have journald add the dbus interface, have the dbus method Synchronize do the sync logic, and change journalctl --sync to call the Synchronize dbus method.

**Pull request closed without merging**
