### PR TITLE
boot: allow wrapping around in entry selection

### PR DESCRIPTION
**Pull request by lheckemann**

### CODE REVIEW

**Comment by medhefgo** [comment]
I'm not really convinced: In general, lists (in any app) don't wrap around, why should we? And if you really need to get to the other side of a long list one can use the `Start/End` keys.

**Comment by lheckemann** [comment]
_Menus_ usually do wrap around when navigated with a keyboard, and the wrapping behaviour is a lot more obvious to me personally than the use of Home/End -- to the point that trying Home/End didn't actually occur to me until I was reading the code! That said, I won't fight for this if nobody else thinks it's a good idea.

**Comment by poettering** [comment]
I am not convined either. I often keep hitting pageup continously to make sure i get the first entry. with this you break that.

we should consider making ctrl-a and ctrl-end alternatives to home/end, i.e. following god's own keybindings: emacs.

**Comment by poettering** [comment]
anyway, let's close this, given the lukwarm response so far, and @lheckemann apparently being fine if we don't merge this.

**Pull request closed without merging**
