### PR TITLE
Drop pointless goto

### PR DESCRIPTION
**Pull request by dtardon**

### CODE REVIEW

**Review by YHNdnzj — APPROVED** [review]
Since the two commits change the same part of the file, I'd like them to be squashed

**Comment by poettering** [comment]
yeah, please squahs.

but frankly i always though that loops whose main codepath ends in a return or break is a bit weird. the return/break should be the exceptional case (and hence the one indented via if or similar), not the default case. or in other words, a loop where you never can reach the closing bracket `}`  and the only way to actually loop is an early `continue` is strange.

Weird:
```c
for (;;) {
        …
        if (x) {
                …  
                continue;
        }
        …
        break; 
}
```
Not weird:
```c
for (;;) { 
        …
        if (!x) { 
                …
                break;
        }
        …
}
```

**Comment by keszybz** [comment]
I agree. We can have the form suggested by @poettering without any `goto` and it'll be clearer than the complicated loop in the current patch version.

**Comment by dtardon** [comment]
All right, I've dropped the second commit.

**Review by yuwata — APPROVED** [review]

**Pull request merged**
