### PR TITLE
CD cannot be mounted automatically (The cd was burned twice in Windows)

### PR DESCRIPTION
**Pull request by HeroesLoveToRoujiamo**
When udev calls the blkid_do_safeprobe function, if you assign a value to the pr->offset attribute, it will cause a disc (udf) that has been burned more than twice under windows to fail to mount and display. At first I thought this was a problem with the blkid code of util linux, and communicated with the upstream developers of blkid. For a description of the issue, see karelzak/util-linux#1161. Finally found that this was a problem with udev, and modified its code. Regarding the normal call of the blkid_do_safeprobe function, you can refer to the util-linux code: https://github.com/karelzak/util-linux/blob/master/libblkid/src/verify.c (The blkid_do_safeprobe function is called here because the blkid command is executed in the terminal, such as "blkid /dev/sr0").

### CODE REVIEW

**Comment by karelzak** [comment]
I'm not sure if I understand the issue. The default probing offset in udev-builtin-blkid is zero, and if you want something else you need explicit -o <offset> in udev rules. So, it sounds that the probem is somewhere in the rules than in the udev-blkid code.

**Comment by HeroesLoveToRoujiamo** [comment]
> 我不确定是否了解此问题。udev-builtin-blkid中的默认探测偏移为零，如果您需要其他设置，则需要在udev规则中使用显式-o。因此，听起来探针在规则中比在udev-blkid代码中更重要。

**Comment by HeroesLoveToRoujiamo** [comment]
> 我不确定是否了解此问题。udev-builtin-blkid中的默认探测偏移为零，如果您需要其他设置，则需要在udev规则中使用显式-o。因此，听起来探针在规则中比在udev-blkid代码中更重要。

**Comment by HeroesLoveToRoujiamo** [comment]
> I'm not sure if I understand the issue. The default probing offset in udev-builtin-blkid is zero, and if you want something else you need explicit -o in udev rules. So, it sounds that the probem is somewhere in the rules than in the udev-blkid code.

You are right, I need to test it again. Thank you very much

**Comment by HeroesLoveToRoujiamo** [comment]
Thanks for @karelzak ’s advice. I adore you! I need to retest!

**Pull request closed without merging**
