### PR TITLE
manager: put bin before sbin for user instances

### LINKED ISSUE #733: Put $x/bin before $x/sbin in --user sessions' PATH
I've converted my user session to using `systemd --user`, but now I'm getting `/usr/sbin` before `/usr/bin` in the path. This causes problems with `mock` which has `/usr/sbin/mock` and `/usr/bin/mock` and the latter is the one meant to be run by a user.

This occurs within `tmux` from the shell because `tmux` was started with a user-level `tmux.service`. Also occurs in `urxvt` because I'm use the server/client mode via a `urxvt256cd.service`.

Would it be possible to place `/usr/bin` before `/usr/sbin` (and similar for `/usr/local`) for `--user` service files?

See https://bugzilla.redhat.com/show_bug.cgi?id=1246810

### PR DESCRIPTION
**Pull request by keszybz**
Traditionally, user logins had a $PATH in which /bin was before /sbin, while
root logins had a $PATH with /sbin first. This allows the tricks that
consolehelper is doing to work. But even if we ignore consolehelper, having the
path in this order might have been used by admins for other purposes, and
keeping the order in user sessions will make it easier the adoption of systemd
user sessions a bit easier.

Fixes #733.
https://bugzilla.redhat.com/show_bug.cgi?id=1744059

OOM handling in manager_default_environment wasn't really correct.
Now the (theorertical) malloc failure in strv_new() is handled.

Please note that this has no effect on:
- systems with merged /bin-/sbin (e.g. arch)

- when there are no binaries that differ between the two locations.

  E.g. on my F30 laptop there is exactly one program that is affected:
  /usr/bin/setup -> consolehelper.

  There is less and less stuff that relies on consolehelper, but there's still
  some.

So for "clean" systems this makes no difference, but helps with legacy setups.

$ dnf repoquery --releasever=31 --qf %{name} --whatrequires usermode
anaconda-live
audit-viewer
beesu
chkrootkit
driftnet
drobo-utils-gui
hddtemp
mate-system-log
mock
pure-ftpd
setuptool
subscription-manager
system-config-httpd
system-config-rootpassword
system-switch-java
system-switch-mail
usermode-gtk
vpnc-consoleuser
wifi-radar
xawtv

### CODE REVIEW

**Comment by mrc0mmand** [comment]
The Travis CI (Fuzzit) error is not related (cc @evverx)
```
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/xenial-pgdg/main/binary-i386/Packages  Writing more data than expected (788347 > 787357)
```

**Comment by evverx** [comment]
I've opened https://github.com/systemd/systemd/pull/13407 but it seems the issue is gone.

**Comment by poettering** [comment]
I really don't like this, but OK.

**Comment by xnox** [comment]
Strong -1.

In Ubuntu, we have always included `sbin` in all users path, and it has always came first. I would want to revert this, or have a config option to disable this.

We have the PATH documented at https://wiki.ubuntu.com/PATH and we do enforce

> Reordering PATH components is not allowed - sbin leads, and bin follows.

**Comment by cgwalters** [comment]
Yeah, Ubuntu/Debian never used consolehelper, rather pre-polkit I think it was more "let's add Unix groups for everything".

This probably does need to be easily configurable by the distribution.

(Personally I think the right fix is to unify them, but there's a lot of legacy consolehelper in Fedora/RHEL still today sadly)

**Comment by keszybz** [comment]
But that makes even less sense: the only reason not to unify bin-sbin is to have different programs there and to use different `$PATH` orderings. If you don't satifsfy *either* of those, the split has no effect. While I'd like to see the unification in Fedora, at least the current sad state is that the split is used for something, and cannot be removed without other changes. But once `$PATH` is fixed, you might just as well: 1. forbid to package anything that lands in lower-priority path if the same name exists in higher-priority path. Once that's done, just 2. make sbin→bin symlink.

**Comment by xnox** [comment]
> But that makes even less sense: the only reason not to unify bin-sbin is to have different programs there and to use different `$PATH` orderings. If you don't satifsfy _either_ of those, the split has no effect. While I'd like to see the unification in Fedora, at least the current sad state is that the split is used for something, and cannot be removed without other changes. But once `$PATH` is fixed, you might just as well: 1. forbid to package anything that lands in lower-priority path if the same name exists in higher-priority path. Once that's done, just 2. make sbin→bin symlink.

Debian usually allows both root login and regular user login. The expectation on Debian, is that regular user logins do not have sbin in path. When root user logs into a graphical session, sbin is expected in the path and should come first. In both cases, user-level systemd will be running.

On Ubuntu the default has been to not allow root logins, but instead rely on sudo. Thus sbin is always expected to be in PATH. There are packages in Ubuntu that do ship binaries in sbin that take priority over binaries shipped in bin, although it is considered to be against the policy.

In either case, making bin to be ahead of sbin is a change that might break things in Debian/Ubuntu especially for the root-account user manager.

**Comment by keszybz** [comment]
Do you think this should be reverted upstream and only applied in Fedora/RHEL?

**Comment by xnox** [comment]
> Do you think this should be reverted upstream and only applied in Fedora/RHEL?

Revert to the previous default => yes, and like make it a compile-time option which Fedora/RHEL can then turn on. If half of the installs will use the option, imho it should be integrated as a config option upstream, rather than distro-patched. Should I write that patch given that it's my objection?

**Comment by keszybz** [comment]
> Should I write that patch given that it's my objection?

Yes, please.

**Comment by mbiebl** [comment]
@xnox I wonder if the correct change for Ubuntu/Debian would be to not add sbin to `PATH` for user instances at all.

**Comment by mbiebl** [comment]
After all, if we add sbin to PATH (before bin) and do not actually have root privileges. I assume there could be binaries in sbin which actually require root privileges to function properly.

**Comment by poettering** [comment]
Can we revert this altogether maybe? I think this was a bad idea. I am not sure "legacy setups" is a good reason for doing this at all. I mean, we broke this 7 years ago, and so far noone cared, why hence fix this now? Apparently those "legacy setups" don't matter too much, otherwise people would have been noisier about this.

REally, I hate adding compat kludges for stuff without perspective to ever get fixed.

**Pull request merged**
