### PR TITLE
Link local no default route

### PR DESCRIPTION
**Pull request by keszybz**
Potential replacement for #13420.

### CODE REVIEW

**Comment by ssahani** [comment]
```
2.6.2.  Forwarding Rules

 many network stacks, achieving this functionality may be as simple
   as adding a routing table entry indicating that 169.254/16 is
   directly reachable on the local link.  This approach will not work
   for routers or multi-homed hosts.  Refer to section 3 for more
   discussion of multi-homed hosts.
```

Here is the testing with the old code .

HOST
```
░▒▓ ~ ▓▒░ ip route                                                                                                                                         ░▒▓ ✔ | with sus at esx-fedora ▓▒░
default via xxxxx dev ens192 proto dhcp metric 100 
default via xxxxx dev ens224 proto dhcp metric 101 
default via xxxxx dev ens256 proto dhcp src xxxx metric 1024 
default dev ve-f30 proto static scope link metric 2048 <=========here
 
xxxx dev ens256 proto kernel scope link src 10.112.195.149 
xxxx dev ens192 proto kernel scope link src 10.112.195.203 metric 100 
xxxx dev ens224 proto kernel scope link src 10.112.195.48 metric 101 
xxxx dev ens256 proto dhcp scope link src 10.112.195.149 metric 1024 
169.254.0.0/16 dev ve-f30 proto kernel scope link src 169.254.166.109 
```

container
```

Fedora 30 (Thirty)
Kernel 5.3.0-0.rc8.git0.1.fc32.x86_64 on an x86_64 (console)

f30 login: root
Password: 
Last login: Fri Sep 13 23:58:55 on pts/0
[root@f30 ~]# ip route
default via xxxx dev host0 proto dhcp src xxxs  metric 1024 
default dev host0 proto static scope link metric 2048 
Fedora 30 (Thirty)
Kernel 5.3.0-0.rc8.git0.1.fc32.x86_64 on an x86_64 (console)

f30 login: root
Password: 
Last login: Fri Sep 13 23:58:55 on pts/0
[root@f30 ~]# ip route
default via 192.168.180.241 dev host0 proto dhcp src 192.168.180.253 metric 1024 
default dev host0 proto static scope link metric 2048  <=========here 
169.254.0.0/16 dev host0 proto kernel scope link src 169.254.58.164 
xxxx dev host0 proto dhcp scope link src xxxx metric 1024 
```

If I delete the route(default dev host0 proto static scope link metric 2048 )  on the host it just works fine but if I delete on the container it does not work any more. 

```
f30 login: root
Password: 
Last login: Sat Sep 14 00:05:21 on pts/0
[root@f30 ~]# ip route
default via 192.168.61.17 dev host0 proto dhcp src 192.168.61.29 metric 1024 
default dev host0 proto static scope link metric 2048 
169.254.0.0/16 dev host0 proto kernel scope link src 169.254.58.164 
192.168.61.16/28 dev host0 proto kernel scope link src 192.168.61.29 
192.168.61.17 dev host0 proto dhcp scope link src 192.168.61.29 metric 1024 
[root@f30 ~]# ip route del default dev host0 
[root@f30 ~]# ping google.com
�
[1]+  Stopped                 ping google.com
[root@f30 ~]# ping xxxx
PING xxxx (xxxxx) 56(84) bytes of data.
�
[2]+  Stopped                 ping 192.168.94.136
````

With the new patches will this work it will preserve the route in container but not in the host ?

**Comment by keszybz** [comment]
> default via 192.168.61.17 dev host0 proto dhcp src 192.168.61.29 metric 1024 

You have this route. It is enough to communicate with the outside world.

> ip route del default dev host0 

Oh, that's where the misunderstanding comes from. This removes all matching routes, so in effect you removed both routes, including the one via `192.168.61.17`. Please try something like `ip route del default dev host0 metric 2048`.

**Comment by yuwata** [comment]
@keszybz I've fixed the test failure.

**Comment by yuwata** [comment]
@keszybz What do you think about the backward compatibility? Is it enough to announce in the NEWS? If it is enough, then this PR is simpler and I prefer this :-)

**Comment by keszybz** [comment]
Yes, I think NEWS is appropriate. I understand previous behaviour to be an error, and the normal policy for error fixes should apply. It *is* a user-visible change though, so we should note this prominently in NEWS.

**Comment by keszybz** [comment]
@ssahani are you on-board with this?

**Comment by ssahani** [comment]
> @ssahani are you on-board with this?

Yes that works thanks ! LGTM

**Comment by keszybz** [comment]
Let's merge.

**Pull request merged**
