### PR TITLE
meson: Disable dmi_memory_id on arches without DMI

### PR DESCRIPTION
**Pull request by hadess**

### CODE REVIEW

**Comment by yuwata** [comment]
Please also drop the test and rule file for non-supported host.

**Comment by hadess** [comment]
> Please also drop the test and rule file for non-supported host.

The test I forgot about. The rule I don't really see the point...

**Comment by hadess** [comment]
> The test I forgot about. The rule I don't really see the point...

Done anyway, wasn't enough code to warrant always installing it.

**Comment by yuwata** [comment]
LGTM.

**Pull request merged**
