### PR TITLE
libsystemd: Use getrlimit() to check for max LISTEN_FDS value

### PR DESCRIPTION
**Pull request by lpereira**
If the call to getrlimit() fails for some reason, the previous value (INT_MAX) will be used instead.

### CODE REVIEW

**Comment by vcaputo** [comment]
Not to be pedantic but isn't it possible for the rlimit to be lowered after fd values exceeding the current rlimit had been opened?

Linux really needs a syscall for returning the current highest fd number for a process, the rlimit is not a suitable substitute.

**Comment by evverx** [comment]
> isn't it possible for the rlimit to be lowered after fd values exceeding the current rlimit had been opened?

Yes, it's possible:

``` sh
getrlimit(RLIMIT_NOFILE, {rlim_cur=1024, rlim_max=4*1024}) = 0
setrlimit(RLIMIT_NOFILE, {rlim_cur=1, rlim_max=4*1024}) = 0
fstat(2, {st_dev=makedev(0, 14), st_ino=3, st_mode=S_IFCHR|0620, st_nlink=1, st_uid=1001, st_gid=5, st_blksize=1024, st_blocks=0, st_rdev=makedev(136, 0), st_atime=2016/07/22-06:41:21.813000000, st_mtime=2016/07/22-06:41:21.813000000, st_ctime=2016/07/22-04:54:46.815000000}) = 0
write(2, "hm\n", 3hm
)                     = 3
open("/etc/passwd", O_RDONLY)           = -1 EMFILE (Too many open files)
```

> the rlimit is not a suitable substitute.

Agreed

@lpereira , which problem are you trying to fix?

**Comment by poettering** [comment]
Hmm, not grokking this patch. The INT_MAX check is only there to ensure the addition that follows doesn't overflow. Why would we want to check RLIMIT_NOFILE here at all?

Note that LISTEN_FDS should exactly match the number of fds passed, and we validate eahc of the fds anyway via the fd_cloexec() call, hence why would we consult RLIMIT_NOFILE here?

(@vcaputo: in order to close all fds it is usually nicer to explicitly enumerate them, via iteratring through /proc/self/fd/. That's what our close_all_fds() call does.)

**Comment by lpereira** [comment]
@evverx I was using an older version of `sd-daemon.c` on a project of mine, and Coverity warned that the loop to set the cloexec flag was essentially unbounded (not really true, as it'll end after `fd_cloexec()` returns error). I've changed my copy to use a similar approach, then decided to take a look if this was already fixed upstream.

The idea is that, instead of looping through all possible integers until fd_cloexec() fails, use a more controlled upper bound by using the maximum possible file descriptor using a call to getrlimit(). If the call to getrlimit() fails for some reason, or if the limit is unlimited, just use INT_MAX as before.

I've updated the patch to use `rlim_max` instead of `rlim_cur`.

**Comment by evverx** [comment]
> Coverity warned that the loop to set the cloexec flag was essentially unbounded (not really true, as it'll end after fd_cloexec() returns error)

Well, this is a false positive. Why not ignore this?

**Comment by lpereira** [comment]
Alright.

**Pull request closed without merging**
