### PR TITLE
network: Use TAKE_PTR

### PR DESCRIPTION
**Pull request by ssahani**

### CODE REVIEW

**Review by bluca — APPROVED** [review]
lgtm

**Comment by ssahani** [comment]
Thanks for the review

**Comment by bluca** [comment]
actually same comment as the other PR, please squash the commits that do the exact same thing for the same file, no need to have such granularity

**Comment by ssahani** [comment]
> actually same comment as the other PR, please squash the commits that do the exact same thing for the same file, no need to have such granularity

These are logically separated commits per function.

**Comment by bluca** [comment]
> > actually same comment as the other PR, please squash the commits that do the exact same thing for the same file, no need to have such granularity
> 
> These are logically separated commits per function.

Well yes, but it's the same change everywhere, and we usually do these kind of fixups/refactors in a single commit with the suffix "treewide: do x"

**Comment by ssahani** [comment]
> > > actually same comment as the other PR, please squash the commits that do the exact same thing for the same file, no need to have such granularity
> > 
> > 
> > These are logically separated commits per function.
> 
> Well yes, but it's the same change everywhere, and we usually do these kind of fixups/refactors in a single commit with the suffix "treewide: do x"

haha just because it's in a same PR. Ok will squash.

**Pull request merged**
