### PR TITLE
hostname-setup: support kernel with empty CONFIG_DEFAULT_HOSTNAME

### LINKED ISSUE #21896: "Failed to set hostname" if CONFIG_DEFAULT_HOSTNAME is empty
**systemd version the issue has been seen with**
 > 250

**Used distribution**
 > Linux From Scratch

**Linux kernel version used** (`uname -a`)

 > `5.16.0-rc6+`

**CPU architecture issue was seen on**
 > mips64

**Expected behaviour you didn't see**
 > systemd should update hostname to the content of /etc/hostname

**Unexpected behaviour you saw**
 > "Failed to set hostname to \<xry111-A1901\>: No such device or address"

**Steps to reproduce the problem**
 > Build a kernel with empty CONFIG_DEFAULT_HOSTNAME, and boot it.

### PR DESCRIPTION
**Pull request by yuwata**
Fixes #21896.

### CODE REVIEW

**Comment by yuwata** [comment]
This needs to be backported to v250-stable.

**Comment by bluca** [comment]
what about adding something like `GET_HOSTNAME_ALLOW_EMPTY` instead, so that we can keep using the same internal helpers everywhere?

**Comment by yuwata** [comment]
> what about adding something like `GET_HOSTNAME_ALLOW_EMPTY` instead, so that we can keep using the same internal helpers everywhere?

In `sethostname_idempotent_full()`, not only empty string, any hostname currently configured should be accepted. So, it is better to just call `uname()` there.

**Comment by keszybz** [comment]
Yeah, this seems to DTRT in a simpler way.

**Pull request merged**
