### PR TITLE
build-sys: allow wheel group name to be specified

### PR DESCRIPTION
**Pull request by keszybz**
https://github.com/systemd/systemd/issues/2492

### CODE REVIEW

**Comment by martinpitt** [comment]
Thanks @keszybz! I nDebian we could use this to specify `--with-admin-group=root` to drop the current seddery. LGTM, but I don't merge yet in case @poettering or others want to review this first.

**Comment by johannbg** [comment]
If you are heading down this path you need to allow every group name to be specified to adhere to all the other distributions that might deviate from the standard...

**Comment by poettering** [comment]
I am really not sure how I feel about this one. The point of the sysusers.d/basic.conf file is among others to define a basic set of groups available everywhere. If we make this configurable, then we might not want to ship this at all. It's a pity the distros can't agree on some common ground here...

I think the logic of using "adm" as a "see what root can see" and "wheel" as "do what root can do" makes a ton of sense and it fits into the Fedora user database. Debian has an "admin" and an "adm" group for this apparently (?), but quite frankly that's really stupidly called (i.e. two different abbreviations of the same word "administrator", really???). Not that "wheel" was really that well named, but at least the history is pretty clear on it.

Not sure what to do about this. ideally one of the two big distros would just adopt the scheme of the other here...

I think the worst option is too make this configurable in systemd. This is really not supposed to be configurable, it should be the most basic of the basic.

I think an alternative is to make tmpfiles be permissive on this (i.e. skip the wheel thing with a warning, if the wheel group doesn't exist), but I am not sure the ACL libs permit for that...

**Comment by poettering** [comment]
I am also strictly against the name "--with-admin-group" for this, because we already reference an "admin" group everywhere, via "adm"...

**Comment by martinpitt** [comment]
> Debian has an "admin" and an "adm" group for this apparently (?)

To clarify, the "what root can do" group is `sudo`, but it only exists if you actually install the `sudo` package. Otherwise there is no out-of-the-box group for that concept.

Aat the moment we just sed this away completely. I don't actually need this configurable, we just need to ensure that we don't specify groups that don't exist, as otherwise systemd-tmpfiles fails.

> I think an alternative is to make tmpfiles be permissive on this

TBH I wouldn't like that. It's too easy to silently hide typos or intended configuration particularly for files provided by the admin.

**Comment by keszybz** [comment]
FTR, I think `wheel` isn't such a bad name, but `adm` meaning "can see logs" is pretty bad.

So... what about simply something like `--disable-wheel-group`, which would simply remove all mentions of `wheel` from installed files?

**Comment by johannbg** [comment]
@poettering it's more like every distribution and *nix based OS except Debian based once in this case ( it's not just Fedora vs Debian defined as big distro's ) but otherwise it's correct that it's better to just stop shipping basic sysusers.d/basic.conf and ship instead sysusers.d/systemd.conf which defines the systemd users,groups and not deviate from those instead of making make this configurable in systemd ( which you would need to do for every of those defined users/groups since downstreams cannot agree to what those should be ). 

In the end either you set the base line in the core/baseOS as the building block, which is always dictated by the lowest common denominator between the target audience, which in the case for systemd would be embedded since it's lowest common denominators of the target audience hence the rest can always extend on top of that, the further up that stack you go containers/servers/desktop ( you get the worst result if upstream defaults are targeted at desktop since it's highest up that stack which requires most downstream patches from the others ) and those that follow that reap the benefits and those that deviate from that base line will have to carry their own downstream patches against that ( regardless for what they are for ) or you only limit the upstream defaults to it's own minimum and or recommended requirements for the lowest common denominator right? 

Everything becomes clear once either of those path's have been chosen ( set the baseline or not ) and then the upstream defaults can be made that reflect that choice.

**Comment by poettering** [comment]
@keszybz that sounds more acceptable indeed.

**Comment by poettering** [comment]
@martinpitt hmm, one more question: which group is used for polkit's "admin role" stuff on debian? on fedora that's "wheel", but on debian?

**Comment by martinpitt** [comment]
> which group is used for polkit's "admin role" stuff on debian

Same really -- `AdminIdentities=unix-user:0` and `AdminIdentities=unix-group:sudo`.

**Comment by poettering** [comment]
@martinpitt but how does that work? does polkit pull in the sudo pkg?

**Comment by poettering** [comment]
oops, accidentally closed, sorry.

**Comment by martinpitt** [comment]
> does polkit pull in the sudo pkg?

No, if sudo is not installed, the `AdminIdentities=unix-group:sudo` bit is simply ignored and the only user that can access admin stuff is `root`.

**Comment by poettering** [comment]
lgtm. CI still outstanding though.

**Comment by martinpitt** [comment]
Both CI tests green now, merging. Thanks @keszybz!

**Pull request merged**
