### PR TITLE
test-proc-cmdline: run tests only with efi

### PR DESCRIPTION
**Pull request by eworm-de**
Run these tests only with efi enabled.

### CODE REVIEW

**Comment by eworm-de** [comment]
For me this fails in a multilib build where EFI is disabled (`-Defi=false`).

**Comment by bluca** [comment]
What's the error you are getting?

**Comment by eworm-de** [comment]
```
Assertion 'proc_cmdline_get_key("foo_bar", 0, &value) > 0 && streq_ptr(value, "quux")' failed at src/test/test-proc-cmdline.c:66, function test_proc_cmdline_override(). Aborting.
```

Not really sure the fix is correct, but it works for my use case. 😜

**Comment by bluca** [comment]
Parsing the command line needs to work without efi obviously, can you run with debug logs and see if there's anything useful?

**Comment by eworm-de** [comment]
Parsing `SYSTEMD_EFI_OPTIONS` should work as well?

Will test later today...

**Comment by eworm-de** [comment]
I tried a build with `-Defi=true`, as expected that succeeded.

Will try to dig in deeper later in the evening.

**Review by YHNdnzj — APPROVED** [review]
LGTM. We return `-ENODATA` for `systemd_efi_options_variable()` directly if `!ENABLE_EFI` in `basic/efivars.h`. Seems to be a regression introduced by a3cb11f84.

**Review by yuwata — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
