### PR TITLE
Remove POINTINGSTICK_CONST_ACCEL

### PR DESCRIPTION
**Pull request by whot**
The only known consumer of this property was libinput but it stopped using
this property since libinput 1.9 (released Oct 2017). This property is
arguably not one that should be in systemd anyway - it's not a
hardware-specific property but rather a factor of the acceleration method
employed by whatever userspace handles the events.

Drop it, libinput 1.9.x through to 1.11.x doesn't use it, libinput 1.12 has
copied the values over and has its own quirks database for this now.

### CODE REVIEW

**Comment by keszybz** [comment]
Hmm, Oct 2017 is not that long ago. I think we should keep the entries for compatibility for a while yet. It's OK to drop the documentation. Would it be a problem for *newer* libinput if those entries stay?

**Comment by whot** [comment]
We never look at it, so leaving them in forever doesn't matter other than potentially confusing users. Want me to instead just update the blurb at the top with a "Don't bother with this property" message?

**Comment by keszybz** [comment]
Yes, please. (People do install newer systemd on older systems for various reasons, and the horizon where backwards compatibility matters seems to be at least 2 or 3 years.)

**Comment by whot** [comment]
Force-pushed a different patch that just updates the comment to deprecate the property

**Comment by poettering** [comment]
We should probably start maintaining some calendar somewhere that lists stuff to remove and when to do so, so that we don't forget

**Comment by keszybz** [comment]
I think it works pretty well to put a note above the part to be removed, directly in the file. Then when somebody is looking at the code for unrelated reason, they'll see it. I think a centralized list will be harder to maintain.

**Comment by poettering** [comment]
This was finally dropped in #28360

**Pull request merged**
