### PR TITLE
units: use NoExecPaths= ExecPaths=

### PR DESCRIPTION
**Pull request by topimiettinen**
Install a simple allow-list for executable paths for main services.

### CODE REVIEW

**Comment by topimiettinen** [comment]
This will not work for NixOS, but they can add `/nix/store` to the list. Maybe it's even covered by `@rootlibexecdir@`.

**Comment by topimiettinen** [comment]
All CIs seem to be happy. @poettering ptal

**Comment by poettering** [comment]
hmm, i am not a fan of this. We generally avoided listing myriad of dirs in unit files w eship this way, but instead added ProtectSystem= and similar which hid this all away under a simple setting. Thus maybe add ProtectSytem=extra-strict or so, which is like protectSystem=strict, but adds both MS_RDONLY + MS_NOEXEC to all dirs outside of /usr

**Comment by poettering** [comment]
Also, I am not convinced that it even makes sense to make this more finegrained than considering /usr as a whole. i.e. trying to distinguish subdirs below /usr doesn't make much sense to me: the data in /usr should be considered vendor-supplied as a whole, and how the vendor splits up their data shouldn#t matter

**Comment by topimiettinen** [comment]
With /usr-merged systems, leaving only `ExecPaths=/usr` would be enough but for split systems, the dynamic loader may be found in either of /lib or /lib64. So minimal allow-list would be `ExecPaths=-/lib -/lib64 /usr`. Would that be OK? Perhaps meson option `split-usr` could be consulted to remove also /lib and /lib64 if possible?

**Comment by poettering** [comment]
> With /usr-merged systems, leaving only `ExecPaths=/usr` would be enough but for split systems, the dynamic loader may be found in either of /lib or /lib64. So minimal allow-list would be `ExecPaths=-/lib -/lib64 /usr`. Would that be OK? Perhaps meson option `split-usr` could be consulted to remove also /lib and /lib64 if possible?

All this complexity should not leak into the unit files. That's why I think ProtectSystem=extra-strict makes a lot more sense: it hides away what kind of `#ifdeffery` we do internally...

That said, I'd maybe not support split usr systems for this, it's a dying breed. i.e. i'd just say that ProtectSystem=extra-strict is identical to ProtectedSystem=strict except that on split-usr systems / is mounted MS_NOEXEC and /usr is the only thing excluded from that.

**Comment by topimiettinen** [comment]
So, `ExecPaths=/usr` only, no meson or m4 ifdeffery?

**Comment by poettering** [comment]
> So, `ExecPaths=/usr` only, no meson or m4 ifdeffery?

As mentioned, the unit files should *not* carry ExecPaths= or NoExecPaths= by default, but only a new ProtectSystem=extra-strict, and that should hide the logic internally.

if there's ifdeffery to cover for split usr systems then it should be in C code, in the implementation of ProtectSystem=extra-strict

**Comment by topimiettinen** [comment]
OK, closing this then.

**Pull request closed without merging**
