### PR TITLE
Fixes for test 58 repart

### PR DESCRIPTION
**Pull request by fbuihuu**

### CODE REVIEW

**Review by yuwata — APPROVED** [review]
LGTM.

**Comment by yuwata** [comment]
@mrc0mmand @DaanDeMeyer mksquashfs in CentOS 8 is old and not support options that repart uses?
```
/usr/sbin/mksquashfs: invalid option
```

**Comment by DaanDeMeyer** [comment]
Fixed by #26810

**Comment by yuwata** [comment]
@DaanDeMeyer Thank you. Let's merge #26810 first, then restart the CentOS CI.

**Comment by bluca** [comment]
@mrc0mmand could you please restart (I think CentOS tests the merge to main right?)

**Review by bluca — APPROVED** [review]

**Pull request merged**
