### PR TITLE
networkd: rename CheckSum → Checksum

### LINKED ISSUE #4307: Rename CheckSum → Checksum in new networkd options
Follow-up for #4110, see discussion in that bug.

### PR DESCRIPTION
**Pull request by ssahani**
fixes #4307

### CODE REVIEW

**Comment by martinpitt** [comment]
This already was in 231, shouldn't this keep the old spelling for backwards compatibility?

**Comment by tixxdz** [comment]
@martinpitt I agree.

**Comment by poettering** [comment]
@martinpitt were they? #4110 added them, no? which was just merged the other day?

**Comment by martinpitt** [comment]
`RemoteCheckSum` was indeed only introduced in #4110, but `UDPCheckSum` and `UDP6ZeroChecksumRx/Tx` were introduced in v220 in https://github.com/systemd/systemd/commit/cffacc741cb7 . These three should stay backwards compatible IMHO.

**Comment by poettering** [comment]
> RemoteCheckSum was indeed only introduced in #4110, but UDPCheckSum and UDP6ZeroChecksumRx/Tx were introduced in v220 in cffacc7 . These three should stay backwards compatible IMHO.

Ah, I see.

@ssahani can you rework the patch to keep the old names for the old options as compat alias? the docs should only list the new names for them, but the old names should stay available, though we only advertise the new names. Thanks!

**Comment by ssahani** [comment]
@poettering kept the old one also alias for the same . I guess this is what you meant.

**Comment by martinpitt** [comment]
@ssahani : No need to keep the old name for `RemoteCheckSum` as that has never been released. But in general, yes, that's what I meant. Thanks!

**Comment by poettering** [comment]
lgtm

**Comment by poettering** [comment]
@martinpitt hmm, @ssahani's current patch drops the RemoteCheckSum name actually, so the patch is inline with what you suggest already? /me is confused?

**Comment by martinpitt** [comment]
Sorry, misread, indeed. :+1:

**Pull request merged**
