### PR TITLE
Several man fixes

### PR DESCRIPTION
**Pull request by yuwata**
Related to the discussion in #7875.
Also several follow-ups for #7890 and #7684.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @olafhering @shawnl @reverendhomer @nuxwin.

**Comment by olafhering** [comment]
ack for sscanf.

**Comment by yuwata** [comment]
@olafhering Thank you. Updated.

**Comment by nuxwin** [comment]
@yuwata 

Typo there: https://github.com/systemd/systemd/pull/7897/files#diff-7a3aa382affc9b9d042a71a58abdfe7fR881

**Comment by yuwata** [comment]
@nuxwin Thanks. Updated.

**Pull request merged**
