### PR TITLE
loop-util: several cleanups

### PR DESCRIPTION
**Pull request by yuwata**
Mostly refactoring, should not change functionality.

### CODE REVIEW

**Comment by poettering** [comment]
hmm, CI failure does look a bit suspicious

**Comment by yuwata** [comment]
Hm, that looks not related. The error is caused after loopback block device is allocated. See [TEST-29-PORTABLE.journal.tar.gz](https://github.com/systemd/systemd/files/9535214/TEST-29-PORTABLE.journal.tar.gz)

The issue seems triggered when multiple services with a same image are starting. Two folked systemd processes setting up their namespace acquire their own loopback block device, but verity devices seems shared, maybe... If one process deactivates the dm-verity partition, then the other fails to mount it.

**Comment by yuwata** [comment]
@mrc0mmand Have you seen the failure on other invocations?

**Comment by yuwata** [comment]
```
Sep 09 07:33:18 systemd[452]: Opened '/usr/share/minimal_1.raw' in O_RDONLY access mode, with O_DIRECT enabled.
Sep 09 07:33:18 systemd[452]: Successfully acquired /dev/loop0, devno=7:0, nr=0, diskseq=0
Sep 09 07:33:18 systemd[452]: Allocating context for crypt device /usr/share/minimal_1.verity.
Sep 09 07:33:18 systemd[452]: Trying to open and read device /usr/share/minimal_1.verity with direct-io.
Sep 09 07:33:18 systemd[452]: Crypto backend (OpenSSL 1.1.1f  31 Mar 2020) initialized in cryptsetup library version 2.2.2.
Sep 09 07:33:18 systemd[452]: Detected kernel Linux 5.4.0-125-generic x86_64.
Sep 09 07:33:18 systemd[452]: Reading VERITY header of size 512 on device /usr/share/minimal_1.verity, offset 0.
Sep 09 07:33:18 systemd[454]: Opened '/usr/share/minimal_1.raw' in O_RDONLY access mode, with O_DIRECT enabled.
Sep 09 07:33:18 systemd[452]: Setting ciphertext data device to /dev/loop0.
Sep 09 07:33:18 systemd[452]: Trying to open and read device /dev/loop0 with direct-io.
Sep 09 07:33:18 systemd[452]: Activating volume dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity by volume key.
Sep 09 07:33:18 systemd[452]: Trying to activate VERITY device dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity using hash sha256.
Sep 09 07:33:18 systemd[452]: Allocating a free loop device.
Sep 09 07:33:18 systemd[454]: Successfully acquired /dev/loop1, devno=7:1, nr=1, diskseq=0
Sep 09 07:33:18 systemd[452]: Trying to open and read device /dev/loop5 with direct-io.
Sep 09 07:33:18 systemd[454]: Allocating context for crypt device /usr/share/minimal_1.verity.
Sep 09 07:33:18 systemd[454]: Trying to open and read device /usr/share/minimal_1.verity with direct-io.
Sep 09 07:33:18 systemd[454]: Trying to load VERITY crypt type from device /usr/share/minimal_1.verity.
Sep 09 07:33:18 systemd[454]: Reading VERITY header of size 512 on device /usr/share/minimal_1.verity, offset 0.
Sep 09 07:33:18 systemd[454]: Setting ciphertext data device to /dev/loop1.
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop1 with direct-io.
Sep 09 07:33:18 systemd[454]: Activating volume dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity by volume key.
Sep 09 07:33:18 systemd[454]: Device dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity already exists. <-- in LOG_ERR
Sep 09 07:33:18 systemd[454]: Allocating crypt device context by device dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity.
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop0 with direct-io. <-- What??
Sep 09 07:33:18 systemd[454]: Allocating context for crypt device /dev/loop0. <-- Hm??
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop0 with direct-io. <-- Huh??
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop0 with direct-io. <-- again??
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop5 with direct-io.
Sep 09 07:33:18 systemd[454]: Error opening verity device, crypt_volume_key_get failed: Invalid argument
Sep 09 07:33:18 systemd[454]: Releasing crypt device /dev/loop5 context.
Sep 09 07:33:18 systemd[454]: Allocating context for crypt device /usr/share/minimal_1.verity.
Sep 09 07:33:18 systemd[454]: Trying to open and read device /usr/share/minimal_1.verity with direct-io.
Sep 09 07:33:18 systemd[454]: Trying to load VERITY crypt type from device /usr/share/minimal_1.verity.
Sep 09 07:33:18 systemd[454]: Reading VERITY header of size 512 on device /usr/share/minimal_1.verity, offset 0.
Sep 09 07:33:18 systemd[454]: Setting ciphertext data device to /dev/loop1.
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop1 with direct-io.
Sep 09 07:33:18 systemd[454]: Activating volume loop1-verity by volume key.
Sep 09 07:33:18 systemd[454]: Trying to activate VERITY device loop1-verity using hash sha256.
Sep 09 07:33:18 systemd[454]: Allocating a free loop device.
Sep 09 07:33:18 systemd[454]: Trying to open and read device /dev/loop6 with direct-io.
Sep 09 07:33:18 systemd[454]: Calculated device size is 5928 sectors (RO), offset 0.
(udev processing many events)
Sep 09 07:33:21 kernel: /dev/mapper/dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity: Can't open blockdev <-- LOG_ERR
(snip)
Sep 09 07:33:21 systemd[452]: Udev cookie 0xd4dedbd (semid 10) destroyed
Sep 09 07:33:21 systemd[452]: Verity volume dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity status is V.
Sep 09 07:33:21 systemd[454]: Udev cookie 0xd4d0212 (semid 11) destroyed
Sep 09 07:33:21 systemd[454]: Verity volume loop1-verity status is V.
Sep 09 07:33:21 systemd[454]: Deactivating volume dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity. <-- ??
Sep 09 07:33:21 systemd[454]: Allocating crypt device context by device dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity.
Sep 09 07:33:21 systemd[452]: Probed fstype 'squashfs' on partition /dev/mapper/dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity.
Sep 09 07:33:21 systemd[454]: Trying to open and read device /dev/loop0 with direct-io. <-- Oh, again??
Sep 09 07:33:21 systemd[454]: Allocating context for crypt device /dev/loop0.
Sep 09 07:33:21 systemd[454]: Trying to open and read device /dev/loop0 with direct-io.
Sep 09 07:33:21 systemd[454]: Trying to open and read device /dev/loop0 with direct-io.
Sep 09 07:33:21 systemd[454]: Trying to open and read device /dev/loop5 with direct-io.
Sep 09 07:33:21 systemd[454]: Trying to open and read device /dev/loop0 with direct-io.
Sep 09 07:33:21 systemd[454]: Verity volume dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity status is V.
Sep 09 07:33:21 systemd[454]: dm remove dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity  [ opencount flush retryremove deferredremove ]   [16384] (*1) <-- Wait, wait, it is still used by PID=452...
Sep 09 07:33:21 systemd[452]: Mounting /dev/mapper/dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity (squashfs) on /run/systemd/unit-root (MS_RDONLY|MS_NODEV "")...
Sep 09 07:33:21 systemd-udevd[281]: dm-0: Device is queued (SEQNUM=3921, ACTION=remove)
Sep 09 07:33:21 systemd[452]: Failed to mount /dev/mapper/dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity (type squashfs) on /run/systemd/unit-root (MS_RDONLY|MS_NODEV ""): No such file or directory
Sep 09 07:33:21 systemd[452]: Failed to mount root image: No such file or directory
Sep 09 07:33:21 systemd[452]: Deactivating volume dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity.
Sep 09 07:33:21 systemd[452]: Device dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity is not active.
Sep 09 07:33:21 systemd[452]: Failed to deactivate encrypted partition dfbc0b7c6019e90420b41209c8f54b867537b6cbf64de5e7fafa098947484c90-verity <-- yeah, it is already removed by PID=454...
Sep 09 07:33:21 systemd[452]: Releasing crypt device /usr/share/minimal_1.verity context.
Sep 09 07:33:21 systemd[452]: Releasing device-mapper backend.
Sep 09 07:33:21 systemd[452]: Closing read only fd for /usr/share/minimal_1.verity.
Sep 09 07:33:21 systemd[452]: Closed loop /dev/loop5 (/usr/share/minimal_1.verity).
Sep 09 07:33:21 systemd[452]: minimal-app0-bar.service: Failed to set up mount namespacing: No such file or directory
Sep 09 07:33:21 systemd[452]: minimal-app0-bar.service: Failed at step NAMESPACE spawning cat: No such file or directory
Sep 09 07:33:21 systemd[1]: Received SIGCHLD from PID 452 ((cat)).
Sep 09 07:33:21 systemd[1]: Child 452 ((cat)) died (code=exited, status=226/NAMESPACE)
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Child 452 belongs to minimal-app0-bar.service.
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Control process exited, code=exited, status=226/NAMESPACE
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Got final SIGCHLD for state start-pre.
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Failed with result 'exit-code'.
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Service will not restart (restart setting)
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Changed start-pre -> failed
Sep 09 07:33:21 systemd[1]: minimal-app0-bar.service: Job 486 minimal-app0-bar.service/start finished, result=failed
Sep 09 07:33:21 systemd[1]: Failed to start minimal-app0-bar.service.
```

**Comment by yuwata** [comment]
Relevant logs are picked from the journal. The failure is not in loopback block device allocation, hence, unrelated.
But, the failure sounds horrible...

**Comment by mrc0mmand** [comment]
I can't say I've seen this before, but it sounds like something we should look into.

**Comment by yuwata** [comment]
Filed as #24617. Merging.

**Pull request merged**
