### PR TITLE
change "journalctl -M" honour file system namespace setups by transitioning into the container's namespace to get journal access

### PR DESCRIPTION
**Pull request by krnowak**
Hi,

When having a container that keeps its journal inside overlayfs,
journalctl from host can't access them anymore. The way to fix, as
proposed by Lennart, was basically journalctl to get file descriptor
of journal directory from machined and go from there. This situation
happens inside rkt containers - currently to get logs from them, we
need to link the journal to host and call journalctl with merge flag,
journalctl -m _HOSTNAME=<machine id>

So, first three commits are some fixes for minor bugs I noticed or
small refactorings I made during this work.

Fourth patch adds a GetJournal() method to machine1.Manager which
takes a machine name and returns a file descriptor. It works by
entering a mount namespace of machine's leader and getting a
descriptor of /var/log/journal.

Fifth and sixth patches convert the JournalFile from being open()ed
with a path to being openat()ed with dirfd and filename. The fifth
patch wraps the directory fd and path into a refcounted struct, so
many JournalFiles actually hold a ref to JournalDirectory instead of
holding a descriptor. The sixth patch changes the JournalFile to use
JournalDirectory and all the other sources that were using
JournalFile. The patch is quite big because of that, sorry about
that. Maybe you will want to minimize the changes (by preserving
JournalFile's path member).

Seventh patch hooks journalctl to machine1.Manager's GetJournal.

### CODE REVIEW

**Comment by alban** [comment]
@mezcalero all your comments will disappear when this PR gets updated because the comments are on specific commits ids rather than on the PR itself (in the "Files changed" tab). Commenting on specific lines in the "Files chaned" tab would also be better because we would see the context of the comments in the conversation...

**Comment by daurnimator** [comment]
> @mezcalero all your comments will disappear when this PR gets updated because the comments are on specific commits ids rather than on the PR itself (in the "Files changed" tab). Commenting on specific lines in the "Files chaned" tab would also be better because we would see the context of the comments in the conversation...

That makes sense, as most of the comments were about coding style; which are likely to not be relevant once the pull request is updated.

**Comment by dvdhrm** [comment]
I picked up the first 3 cleanup-patches from this PR.

**Comment by zonque** [comment]
What about the rest of this PR? The branch can't be merged anymore. If nobody cares, I'd like to close it.

**Comment by krnowak** [comment]
Yes, I guess it can be closed for now. Not sure when I can find time to address this. We made some change in rkt, so `journal -M` works again (I don't remember exactly what, probably we are now storing container's journal on host instead of in guest, probably to be able to read logs even after the container quits).

I have the code stowed somewhere on my computer, so it will not be lost (for now). I would need to rebase it on top of ~4k new commits. Sounds like fun.

**Comment by zonque** [comment]
Ok, thanks for the update. I'll close this now, please feel free to come back with a new version.

**Pull request closed without merging**
