### PR TITLE
test: fix memleak and fd leak

### PR DESCRIPTION
**Pull request by yuwata**
Fixes issue reported at #22576.

### CODE REVIEW

**Comment by yuwata** [comment]
cc @evverx

**Comment by evverx** [comment]
@yuwata thanks! I don't think any memory leaks were reported there though. The only memory leak in the unit tests I can see right now is
```
==286764==
==286764== 7 bytes in 1 blocks are definitely lost in loss record 1 of 1
==286764==    at 0x484586F: malloc (vg_replace_malloc.c:381)
==286764==    by 0x502D4FD: strdup (in /usr/lib64/libc.so.6)
==286764==    by 0x4D3D072: _set_put_strndup_full (hashmap.c:1861)
==286764==    by 0x497EFB5: config_parse_log_filter_patterns (load-fragment.c:6526)
==286764==    by 0x40EE98: test_config_parse_log_filter_patterns (test-load-fragment.c:1036)
==286764==    by 0x402C92: run_test_table (tests.h:106)
==286764==    by 0x40F66B: main (test-load-fragment.c:1104)
==286764==
```
but it could be that I disabled `networkd` during that build. Let me double-check.

**Comment by evverx** [comment]
Just to make it easier to figure out what's going on here I'll attach the backtraces Valgrind shows without this PR:
```sh
==297828==
==297828== FILE DESCRIPTORS: 5 open (3 std) at exit.
==297828== Open AF_UNIX socket 7: <unknown>
==297828==    at 0x4DFD67E: socketpair (in /usr/lib64/libc.so.6)
==297828==    by 0x403B52: icmp6_bind_router_solicitation (test-ndisc-rs.c:168)
==297828==    by 0x40AE46: sd_ndisc_start (sd-ndisc.c:346)
==297828==    by 0x4047C7: test_timeout (test-ndisc-rs.c:366)
==297828==    by 0x40289B: run_test_table (tests.h:106)
==297828==    by 0x4048AA: main (test-ndisc-rs.c:375)
==297828==
==297828== Open AF_UNIX socket 6: <unknown>
==297828==    at 0x4DFD67E: socketpair (in /usr/lib64/libc.so.6)
==297828==    by 0x403B52: icmp6_bind_router_solicitation (test-ndisc-rs.c:168)
==297828==    by 0x40AE46: sd_ndisc_start (sd-ndisc.c:346)
==297828==    by 0x404103: test_rs (test-ndisc-rs.c:279)
==297828==    by 0x40289B: run_test_table (tests.h:106)
==297828==    by 0x4048AA: main (test-ndisc-rs.c:375)
==297828==
==297828==
==297828== HEAP SUMMARY:
==297828==     in use at exit: 0 bytes in 0 blocks
==297828==   total heap usage: 106 allocs, 106 frees, 29,427 bytes allocated
```
```sh
==297829==
==297829== FILE DESCRIPTORS: 5 open (3 std) at exit.
==297829== Open file descriptor 6:
==297829==    at 0x4DFC99B: timerfd_create (in /usr/lib64/libc.so.6)
==297829==    by 0x4BC99ED: event_setup_timer_fd (sd-event.c:1185)
==297829==    by 0x4BC9B78: setup_clock_data (sd-event.c:1215)
==297829==    by 0x4BCA049: sd_event_add_time (sd-event.c:1288)
==297829==    by 0x4BCA21F: sd_event_add_time_relative (sd-event.c:1336)
==297829==    by 0x4041E8: test_ra (test-ndisc-ra.c:330)
==297829==    by 0x402781: run_test_table (tests.h:106)
==297829==    by 0x404337: main (test-ndisc-ra.c:346)
==297829==
==297829== Open file descriptor 5:
==297829==    at 0x4DFC66B: epoll_create1 (in /usr/lib64/libc.so.6)
==297829==    by 0x4BC6742: sd_event_new (sd-event.c:406)
==297829==    by 0x403C9D: test_ra (test-ndisc-ra.c:290)
==297829==    by 0x402781: run_test_table (tests.h:106)
==297829==    by 0x404337: main (test-ndisc-ra.c:346)
==297829==
==297829==
==297829== HEAP SUMMARY:
==297829==     in use at exit: 2,232 bytes in 10 blocks
==297829==   total heap usage: 71 allocs, 61 frees, 17,323 bytes allocated
==297829==
==297829== LEAK SUMMARY:
==297829==    definitely lost: 0 bytes in 0 blocks
==297829==    indirectly lost: 0 bytes in 0 blocks
==297829==      possibly lost: 0 bytes in 0 blocks
==297829==    still reachable: 2,232 bytes in 10 blocks
==297829==         suppressed: 0 bytes in 0 blocks
```

**Comment by evverx** [comment]
Got it. This PR addresses the "still reachable bytes" issue by turning `recv_router_advertisement` into a local variable. I usually look at stuff that gets definitely lost so I didn't notice that one.

**Review by bluca — APPROVED** [review]

**Pull request merged**
