### PR TITLE
hwdb: add bluetooth entry for Logitech MX Anywhere 2S

### PR DESCRIPTION
**Pull request by hexchain**

### CODE REVIEW

**Comment by hexchain** [comment]
Not sure if `MOUSE_WHEEL_TILT_HORIZONTAL` should also be added too, but AFAICS that breaks horizontal scrolling in Chromium and Firefox.

**Comment by keszybz** [comment]
LGTM.

> Not sure if MOUSE_WHEEL_TILT_HORIZONTAL should also be added too, but AFAICS that breaks horizontal scrolling in Chromium and Firefox.

Hmmm.

**Comment by whot** [comment]
> Not sure if MOUSE_WHEEL_TILT_HORIZONTAL should also be added too, but AFAICS that breaks horizontal scrolling in Chromium and Firefox.

huh, I wonder why. I do have this thing (non-BT) around though so I can put this on my todo list.

**Pull request merged**
