### PR TITLE
Adding IFLA_BR_MCAST_IGMP_VERSION

### PR DESCRIPTION
**Pull request by shreyasbe**
Adding IFLA_BR_MCAST_IGMP_VERSION in file src/libsystemd/sd-netlink/netlink-types.c

### CODE REVIEW

**Comment by yuwata** [comment]
What is the use case? We usually do not add all attributes, but only used ones. Adding this is ok, but why?

**Comment by ssahani** [comment]
LGTM

**Comment by shreyasbe** [comment]
Hi Yu Watanabe,
                        I want to contribute & follow-up with patches.

Regards,
Shreyas

**Comment by yuwata** [comment]
So, you have some follow-up works. Then, please submit this commit with the follow-ups.

**Comment by ssahani** [comment]
We already have such patches added. I don't find any harm adding these.
````
      [IFLA_BR_FDB_FLUSH]                  = { .type = NETLINK_TYPE_U16 },
        [IFLA_BR_MCAST_ROUTER]               = { .type = NETLINK_TYPE_U8 },
        [IFLA_BR_MCAST_SNOOPING]             = { .type = NETLINK_TYPE_U8 },
        [IFLA_BR_MCAST_QUERY_USE_IFADDR]     = { .type = NETLINK_TYPE_U8 },
        [IFLA_BR_MCAST_QUERIER]              = { .type = NETLINK_TYPE_U8 },
        [IFLA_BR_MCAST_HASH_ELASTICITY]      = { .type = NETLINK_TYPE_U32 },
        [IFLA_BR_MCAST_HASH_MAX]             = { .type = NETLINK_TYPE_U16 },
        [IFLA_BR_MCAST_LAST_MEMBER_CNT]      = { .type = NETLINK_TYPE_U32 },
        [IFLA_BR_MCAST_STARTUP_QUERY_CNT]    = { .type = NETLINK_TYPE_U16 },
        [IFLA_BR_MCAST_LAST_MEMBER_INTVL]    = { .type = NETLINK_TYPE_U64 },
        [IFLA_BR_MCAST_MEMBERSHIP_INTVL]     = { .type = NETLINK_TYPE_U64 },
        [IFLA_BR_MCAST_QUERIER_INTVL]        = { .type = NETLINK_TYPE_U64 },
        [IFLA_BR_MCAST_QUERY_INTVL]          = { .type = NETLINK_TYPE_U64 },
        [IFLA_BR_MCAST_QUERY_RESPONSE_INTVL] = { .type = NETLINK_TYPE_U64 },
```

**Comment by ssahani** [comment]
@shreyasbe could you please see how we add other properties and configure them. For a start this is OK.

**Comment by shreyasbe** [comment]
Sure .. I will check other properties.

**Comment by shreyasbe** [comment]
Sure. I will do.

**Comment by yuwata** [comment]
Replaced by #13169. Closing.

**Pull request closed without merging**
