### PR TITLE
test: suppress logs generated by journal tests

### LINKED ISSUE #33035: TEST-02-UNITTESTS: test-journal-flush spams journal with debug messages
### systemd version the issue has been seen with

main

### Used distribution

_No response_

### Linux kernel version used

_No response_

### CPU architectures issue was seen on

None

### Component

_No response_

### Expected behaviour you didn't see

_No response_

### Unexpected behaviour you saw

https://github.com/systemd/systemd/actions/runs/9244662593/job/25430224712?pr=32866

```
gh run download 9244662593 --name ci-mkosi-9244662593-1-arch-rolling-failed-test-journals -D ci/ci-mkosi-9244662593-1-arch-rolling-failed-test-journals && journalctl --file ci/ci-mkosi-9244662593-1-arch-rolling-failed-test-journals/test/journal/TEST-64-UDEV-STORAGE-multipath_basic_failover.journal --no-hostname -o short-monotonic -u test-journal-flush
```

### Steps to reproduce the problem

_No response_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
...
[  405.825807] test-journal-flush[2717]: Attempt to move to uninitialized object: 482176
[  405.826026] test-journal-flush[2717]: Attempt to move to uninitialized object: 482184
[  405.826240] test-journal-flush[2717]: Attempt to move to uninitialized object: 482192
[  405.826450] test-journal-flush[2717]: Attempt to move to uninitialized object: 482200
[  405.826698] test-journal-flush[2717]: Attempt to move to uninitialized object: 482208
[  405.826942] test-journal-flush[2717]: Attempt to move to uninitialized object: 482216
[  405.827152] test-journal-flush[2717]: Attempt to move to uninitialized object: 482224
[  405.827361] test-journal-flush[2717]: Attempt to move to uninitialized object: 482232
[  405.827585] test-journal-flush[2717]: Attempt to move to uninitialized object: 482240
[  405.827794] test-journal-flush[2717]: Attempt to move to uninitialized object: 482248
[  405.828001] test-journal-flush[2717]: Attempt to move to uninitialized object: 482256
[  405.828207] test-journal-flush[2717]: Attempt to move to uninitialized object: 482264
[  405.828414] test-journal-flush[2717]: Attempt to move to uninitialized object: 482272
[  405.828636] test-journal-flush[2717]: Attempt to move to uninitialized object: 482280
[  405.828850] test-journal-flush[2717]: Attempt to move to uninitialized object: 482288
[  405.829085] test-journal-flush[2717]: Attempt to move to uninitialized object: 482296
[  405.829296] test-journal-flush[2717]: Attempt to move to uninitialized object: 482304
[  405.829503] test-journal-flush[2717]: Attempt to move to uninitialized object: 482312
[  405.829726] test-journal-flush[2717]: Attempt to move to uninitialized object: 482320
[  405.829940] test-journal-flush[2717]: Attempt to move to uninitialized object: 482328
[  405.830210] test-journal-flush[2717]: Attempt to move to uninitialized object: 482336
[  405.830421] test-journal-flush[2717]: Attempt to move to uninitialized object: 482344
[  405.830630] test-journal-flush[2717]: Attempt to move to uninitialized object: 482352
...
```

### PR DESCRIPTION
**Pull request by yuwata**
Note, journal_file_dump() is only used by tests.

Closes #33035.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
I'm OK with this especially since we're close to release but aren't we hiding a real issue like this?

**Comment by yuwata** [comment]
> I'm OK with this especially since we're close to release but aren't we hiding a real issue like this?

This just suppresses logs, and still the tests can fail e.g. by assertion or so. So, at least, we can detect failures.
Of course, this may make it harder to debug failures. But, that should not be a problem, as we can anytime increase log level when necessary.

**Comment by DaanDeMeyer** [comment]
> > I'm OK with this especially since we're close to release but aren't we hiding a real issue like this?
> 
> This just suppresses logs, and still the tests can fail e.g. by assertion or so. So, at least, we can detect failures. Of course, this may make it harder to debug failures. But, that should not be a problem, as we can anytime increase log level when necessary.

Yes but isn't the fact that SD_JOURNAL_FOREACH() doesn't exit early here a bug? From what I can see from the logs, it tries to read thousands of invalid objects. I feel like we should probably stop earlier in that case. I'm not sure why it's doing that though, I assume rotation is somehow causing this

**Comment by yuwata** [comment]
The test intentionally tries to read invalid objects. So, the debug logs about the failure are expected. Though the test may torture too much, but the test itself is not too slow. I think it is not necessary to reduce the number of trials.

**Review by DaanDeMeyer — APPROVED** [review]

**Pull request merged**
