### PR TITLE
test: hopefully fixes race in TEST-35-LOGIN

### PR DESCRIPTION
**Pull request by yuwata**

### CODE REVIEW

**Comment by yuwata** [comment]
Ugh, still in red...

**Comment by yuwata** [comment]
@mrc0mmand If CIs are green, then could you run a stress test for TEST-35?

**Comment by mrc0mmand** [comment]
> @mrc0mmand If CIs are green, then could you run a stress test for TEST-35?

Definitely. I'll prep a PR in the systemd-centos-ci repo for this.

**Comment by mrc0mmand** [comment]
@yuwata https://jenkins-systemd.apps.ocp.ci.centos.org/job/ci-build/1132/artifact//index.html

**Review by mrc0mmand — APPROVED** [review]
LGTM, thanks a bunch! I unleashed [the stress test](https://github.com/systemd/systemd-centos-ci/pull/514) on this PR (where CI runs the test 100 times in a row), and so far it got past the first fifth without a fail (previously it would fail within the first ten iterations), so it looks promising.

**Pull request merged**
