### PR TITLE
rules: whitelist nbd* devices

### PR DESCRIPTION
**Pull request by keszybz**
https://bugzilla.redhat.com/show_bug.cgi?id=1226311

### CODE REVIEW

**Comment by kaysievers** [comment]
No. Network devices do not send notifications when the they are set up or change. How is that supposed to work?

These devices have even been explicitly been blacklisted before we turned that into a whitelist.

**Comment by keszybz** [comment]
On Thu, Jun 11, 2015 at 05:39:15PM -0700, Kay Sievers wrote:

> No. Network devices do not send notifications when the they set up or change. How is that supposed to work? These devices have even been explicitly been blacklisted before we turned that into a whitelist.

They do send notifications when they are set up:

$ qemu-nbd -c /dev/nbd0 /var/tmp/img
KERNEL[41301.117067] change   /devices/virtual/block/nbd0 (block)
KERNEL[41301.117185] add      /devices/virtual/block/nbd0/nbd0p1 (block)
UDEV  [41301.125496] change   /devices/virtual/block/nbd0 (block)
UDEV  [41301.134050] add      /devices/virtual/block/nbd0/nbd0p1 (block)

or changed (on the host side)
$ fdisk /dev/nbd0
KERNEL[41331.425191] remove   /devices/virtual/block/nbd0/nbd0p1 (block)
KERNEL[41331.431724] change   /devices/virtual/block/nbd0 (block)
KERNEL[41331.431976] add      /devices/virtual/block/nbd0/nbd0p1 (block)
UDEV  [41331.432917] remove   /devices/virtual/block/nbd0/nbd0p1 (block)
UDEV  [41331.436996] change   /devices/virtual/block/nbd0 (block)
UDEV  [41331.445659] add      /devices/virtual/block/nbd0/nbd0p1 (block)

but not when changed on the remote side:
$ fdisk /var/tmp/img
(nada)

But I think that this is fine. When I mount an device using nbd, I don't
expect any changes to be done directly to the underlying block storage,
since there's no protocol to "push" those changes to the local side.

Is this what you had in mind?

**Comment by kaysievers** [comment]
Just loading the nbd module will create 16 "dead" nbd devices before they attach a backing file to it.

**Comment by poettering** [comment]
@keszybz for the nbd stuff to be nicely exposable in udev we'd need it to work like /dev/loop and /dev/loop-control work these days: i.e. only create the nbd devices when they are needed and have a sane API in /sys to detect if there's something connected to an nbd device or not.

**Comment by kaysievers** [comment]
Also, these devices are created by userspace tools and not discovered like hardware. They are private to the tool which creates them and the tool does not need udev to find it again.

In general, we would not add loop to the list today, and we will only add new devices to the udev link logic when there is absolute need for it. Not all devices are expected to have them, the links are mostly for legacy tools to find probed hardware, not to support tools which create their own devices for themselves.

**Pull request closed without merging**
