### PR TITLE
Add support for /boot/efi

### PR DESCRIPTION
**Pull request by kreijack**
bootctl assumes that the ESP partition is mounted on /boot.
However some distributions mount the ESP partition on /boot/efi.
Add a check to detect the mountpoint used for the ESP partition.

### CODE REVIEW

**Comment by teg** [comment]
I don't think we should introduce support for this unless there is a good reason for people to actually have these setups. If this is just an arbitrary choice I'd say we should stay with one supported setup upstream and let downstream patch it if they really insist on doing things differently.

**Comment by martinpitt** [comment]
This would indeed avoid having to patch it for the majority of distros out there. But if this gets accepted in principle it would be good to also adjust the manpage accordingly, for the `--path` option.

**Comment by microcai** [comment]
It is really stupid to have ESP mounted on /boot/efi, if so, what's the point to have /boot anyway?

**Comment by johannbg** [comment]
Agree with @teg here + @poettering  gave all installer maintainers heads up sometime in 2013 as well as providing patch for grub2 if memory serves me correct so deviation now from the bootloader spec ( which intent is to simplify and unify ) after all this time does not make much sense so distribution a) need do carry a downstream patch or b) simply jump on the /boot bandwagon.

**Comment by martinpitt** [comment]
> b) simply jump on the /boot bandwagon

So I suppose the "Fedora" comment in this PR is wrong, and Fedora actually mounts the ESP onto `/boot`?

If that's really "simple", how do you handle existing systems on upgrade? If there's a reasonably safe way to do that this would be a good thing to do indeed. Thanks for any pointers!

**Comment by johannbg** [comment]
@martinpitt the comment is right however is said in no relation to fedora ( where this quickly got requested and rejected due to the same reasons  ) and as far as I know this has not been implemented in Fedora since nobody drove that "feature" ( and the feature process is arguably obsoleted since the introduction of products ) but I think @wgwoods was discussing this with the Anaconda team at that time so he might have some insight what came out of those discussion or why it has not been implemented ( if it has not been implemented already ) he could even share some some light on potential "upgrade" issues since he is re-implementing the upgrade tool in fedora for what 3rd or fourth time..

**Comment by johannbg** [comment]
@martinpitt  the grub2 patch is being carried in Fedora which you can find here http://pkgs.fedoraproject.org/cgit/grub2.git/plain/0460-blscfg-add-blscfg-module-to-parse-Boot-Loader-Specif.patch?h=f20

Here is also Magiea feature page conforming to the bootloader spec process ( and how they implemented it or indented to implement it, most notably drop all other bootloaders with exception of grub2 for bios boot and Gummiboot/systemd-boot For UEFI boots. This approach in Debian or Debian based distribution most likely will park some passionate debates but it is precisely how I would do it as a feature in Fedora since it should fly in Fedora/OpenSuse/Arch and other distribution that dont need gazillion bootloaders to support ).

You should be able to ping Colin if they went through with this or stopped for some reason or another  ( the % of completion means nothing in Fedora )
https://wiki.mageia.org/en/Feature:BootPartitionShakeup

**Comment by kreijack** [comment]
Hi,
the goal of this patch is not related where ESP _will_ be placed; is related to the ESP _is_ placed now. 

Despite the free-desktop specification:
- fedora mount ESP in /boot/efi [https://fedoraproject.org/wiki/Unified_Extensible_Firmware_Interface,
  https://docs.fedoraproject.org/en-US/Fedora/22/pdf/Multiboot_Guide/Fedora-22-Multiboot_Guide-en-US.pdf],
- debian mount ESP in /boot/efi [https://wiki.debian.org/GrubEFIReinstall]
- ubuntu mount ESP in /boot/efi [https://help.ubuntu.com/community/UEFI]
- suse mount ESP in /boot/efi [https://en.opensuse.org/openSUSE:UEFI]

(please correct me if I am wrong, because it is not easy to find the rules used by each distribution)

So I think that even this is not the best which we can do, we have to face this fact. The aim of this patch is not to support /boot/efi more than is needed, is only to allow bootctl to work on this kind of reality.

**Comment by kaysievers** [comment]
Stacking arbitrary filesystems are a just too broken concept for the systemd-boot tools. This is all too complicated for no sensible reason. Upstream systemd-boot supports only the minimal setup of /boot as the ESP.

**Comment by kaysievers** [comment]
systemd could mound the ESP to /efi and ignore /boot entirely. But that would need to be carefully decided, and in the end might not worth the trouble. We have no intention to support the stacking of several "boot partitions" with the systemd-boot tools.

**Comment by poettering** [comment]
The essence is really that we suggest people to mount the ESP to /boot. And if they don't then they can use `--path=`. Consider it a gentle push towards making /boot the ESP, while supporting other setups. Hence I don't think we should start searching for the ESP at other places automatically, and quite honestly /boot/efi is the poorest choice of all, and hence should be something we should explicitly not make easiest to use by default. As Kay said, /efi might be an alternative to /boot, but playing matroshka dolls with ESP and /boot and stacking them into each other is just wrong...

**Pull request closed without merging**
