### PR TITLE
hwdb.d/60-keyboard.hwdb: add Clevo mic mute quirk for V5x iGPU, NV41PZ

### PR DESCRIPTION
**Pull request by filipleple**

### CODE REVIEW

**Comment by poettering** [comment]
any reason for this to be marked as "draft"? did you verify this works? to me this looks ok the way it is. if you tested this sounds good to merge?

**Comment by filipleple** [comment]
@poettering I still need to verify it on each HW model once I get access to them, it should be ready for merge by Tuesday

**Comment by filipleple** [comment]
Alright, I've managed to test the solution and confirm it works

```
Event: time 1725892608.653838, -------------- SYN_REPORT ------------
Event: time 1725892608.737872, type 4 (EV_MSC), code 4 (MSC_SCAN), value 81
Event: time 1725892608.737872, type 1 (EV_KEY), code 190 (KEY_F20), value 0
Event: time 1725892608.737872, -------------- SYN_REPORT ------------
```

and it does mute the mic as expected.

**Comment by poettering** [comment]
CI doesn't like it:

```
Match 'evdev:atkbd:dmi:bvn*:bvr*:svnNotebook:pnNV4xPZ:*' is duplicated
Match 'evdev:atkbd:dmi:bvn*:bvr*:svnNotebook:pnV54x_6x_TU:*' is duplicated
```

**Comment by filipleple** [comment]
I've reworked it into a CI-compliant version that covers the laptops properly.

**Pull request merged**
