### PR TITLE
pid1/nspawn: raise RLIMIT_MEMLOCK to 8M matching kernel 5.16's new default

### PR DESCRIPTION
**Pull request by poettering**

### CODE REVIEW

**Review by yuwata — APPROVED** [review]
LGTM.

**Comment by Geass-LL** [comment]
Maybe also change /etc/systemd/system.conf:
#DefaultLimitMEMLOCK=8M

**Comment by poettering** [comment]
good point. added. also updated the man page, to mention this.

**Comment by bluca** [comment]
Uhm the last commit is the same as https://github.com/systemd/systemd/pull/22707 was that an unintentional push?

**Comment by bluca** [comment]
> Uhm the last commit is the same as #22707 was that an unintentional push?

I've removed the commit given the other PR is merged. There's no code change, so no need to wait for another round of CI.

**Comment by poettering** [comment]
> Uhm the last commit is the same as #22707 was that an unintentional push?

oops, yes, seems i accidently pulled that into the wrong branch. sorry for the confusion

**Pull request merged**
