### PR TITLE
udevadm: ignoring request when run in chroot

### LINKED ISSUE #11333: changed behaviour of "udevadm trigger" with missing /sys
**systemd version the issue has been seen with**

v240

**Used distribution**
 
Debian sid
Related downstream bug report
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917633

Inside a chroot, /sys is usually not mounted.
Running "udevadm trigger" inside such a chroot yields the following error with v240:
```
# udevadm trigger
Failed to scan devices: No such file or directory
# echo $?
1
```

In comparsion, older udev versions handled this differently:
```
# udevadm trigger
# echo $?
0
```
This is a change in behaviour caused by https://github.com/systemd/systemd/commit/13aca847695#diff-e3e322f67caf1b94a0008af64eadfaf5R303

In Debian we have quite a few package which run `udevadm trigger` in their maintainer scripts and now fail to install unless they ignore errors via `|| true`
Possibly affected packages: https://codesearch.debian.net/search?q=udevadm+trigger

Before I start filing bug reports to get every affected package updated to use `udevadm trigger || true` I wanted to ask if this change in behaviour was intentional.
@yuwata your input would be welcome.

### PR DESCRIPTION
**Pull request by yuwata**
Closes #11333.

### CODE REVIEW

**Comment by yuwata** [comment]
@mbiebl PTAL.

**Comment by keszybz** [comment]
Yep, look good. I'll wait for @mbiebl to comment though.

**Comment by mbiebl** [comment]
I think we should allow `udevadm help` inside a chroot.
Other then that, looks fine to me. Thanks!

**Comment by yuwata** [comment]
`udevadm help` is not documented. And `udevadm --help` works in chroot.

**Comment by poettering** [comment]
lgtm

**Comment by keszybz** [comment]
We've been waiting 16h for the CI. This looks pretty safe, let's merge.

**Comment by Jeansen** [comment]
What should I do if I have /sys mounted and want to use udevadm from withing chroot?

**Comment by Low-power** [comment]
This change makes some rescue operations impossible. So bad.

**Pull request merged**
