### PR TITLE
cgroup handling fixes

### PR DESCRIPTION
**Pull request by htejun**
Hello,

I've encountered a couple bugs in cgroup handling. Here are the fixes.

Thanks.

### CODE REVIEW

**Comment by keszybz** [comment]
Build fails with

```
../src/shared/bus-unit-util.c: In function ‘bus_append_unit_property_assignment’:
../src/shared/bus-unit-util.c:213:17: error: implicit declaration of function ‘cg_blkio_shares_parse’ [-Werror=implicit-function-declaration]
                 r = cg_blkio_shares_parse(eq, &u);
                 ^
../src/shared/bus-unit-util.c:213:17: warning: nested extern declaration of ‘cg_blkio_shares_parse’ [-Wnested-externs]
```

**Comment by htejun** [comment]
Oops, sorry about that. That was me being stupid while rebasing. Will resend after running check.

**Comment by keszybz** [comment]
No need to close. Just force push when you're ready.

**Comment by htejun** [comment]
Oops, didn't know that's how it's supposed to be done. Just sent out a new pull request.

**Comment by keszybz** [comment]
Yeah, we used to do that, but github is now better and doesn't lose comments when commits are replaced, so we prefer to force-push.

Closing in favour of #3160.

**Comment by htejun** [comment]
I see. Will do forced updates from now on. Thanks!

**Pull request closed without merging**
