### PR TITLE
Revert "Implement DNS notifications from systemd-resolved using varlink"

### PR DESCRIPTION
**Pull request by poettering**
This will become API, and I think we need an iteration or two more before this is ready to be that. Please see my (admittedly late, soryy) review comments on #22845.

Reverts systemd/systemd#22845

### CODE REVIEW

**Comment by bluca** [comment]
Can't it just be fixed up? That PR has been open with back and forth for half a year...

**Comment by poettering** [comment]
Well, sure, but it's a lot to fix. If a patch is quickly prepared to fix the points I raised, we could merge that instead of this.

**Comment by yuwata** [comment]
Please also revert PR #24637 if this is going to be merged instead of fixing the original PR.

**Comment by poettering** [comment]
Let's close this one in favour of the already commited #24823 and #24853 that i just posted.

**Pull request closed without merging**
