### PR TITLE
man: systemd.exec: add missing variables

### PR DESCRIPTION
**Pull request by evverx**

### CODE REVIEW

**Comment by evverx** [comment]
Hm

```
FAIL: test-ndisc-rs
```

See https://github.com/systemd/systemd/issues/1952

**Comment by zonque** [comment]
Yes, this also fails in master now. Meh. @teg?

**Comment by zonque** [comment]
This should be fixed now with #1958. Care to rebase to current master?

**Comment by evverx** [comment]
Rebased.

**Pull request merged**
