### PR TITLE
schedule sending Subscribe messages to avoid systemd releasing  Subscribe flags

### PR DESCRIPTION
**Pull request by yangmingtai**
systemd-logind sends a Subscribe message during startup, and systemd sets m->subscribe accordingly. When the connection between systemd and dbus-daemon is interrupted, m->subscribe is released, but systemd-logind does not perceive this change and m->subscribe is not restored. A simple solution is to periodically send a Subscribe message.

https://github.com/systemd/systemd/issues/27667

### CODE REVIEW

**Comment by bluca** [comment]
Isn't the subscribe client list refcounted?

**Comment by yangmingtai** [comment]
> Isn't the subscribe client list refcounted?

not refcounted
image

**Comment by yuwata** [comment]
> When the connection between systemd and dbus-daemon is interrupted, m->subscribe is released,

If your analysis is correct, then please fix this point. And please do not introduce any workaround.

**Comment by poettering** [comment]
pid1 should serialize its list of subscribers during daemon reexec, so the list of subscribers should not get lost when it disconnects from the bus due to reexec.

And so far dbus-daemon is generally assumed to never die during runtime of userspace, programs are not assumed to generally have mechanisms to recover from that.

Hence, what kind of disconnection between logind and pid 1 do you have in mind?

**Comment by yangmingtai** [comment]
> pid1 should serialize its list of subscribers during daemon reexec, so the list of subscribers should not get lost when it disconnects from the bus due to reexec.
> 
> And so far dbus-daemon is generally assumed to never die during runtime of userspace, programs are not assumed to generally have mechanisms to recover from that.
> 
> Hence, what kind of disconnection between logind and pid 1 do you have in mind?

systemd will send a Disconnected message to itself when there is a dbus communication exception, such as a timeout. Upon receiving this message, it will call destroy_bus, which will uref m->subscribed. In this case, recovery is not possible. However, you assume that this situation will not occur.^^

**Comment by poettering** [comment]
> systemd will send a Disconnected message to itself when there is a dbus communication exception, such as a timeout. Upon receiving this message, it will call destroy_bus, which will uref m->subscribed. In this case, recovery is not possible. However, you assume that this situation will not occur.^^

Yeah, if dbus is down the system is generally assumed to be fucked. there's now sensible way to recover from dbus dying, it's simply not a case people generally assume is relevant. It's like saying userspace should stay running if the kernel dies completely... noone expects userspace to just continue running.

Hence, I am not convinced we need to deal with this. D-Bus should really be one of the last things to die, and we already bump its oom adjust to make sure it gets preferential treatment to just continue working.

what scenario do you actually have in mind here you are trying to improve? a system where dbus' timeouts are all hit is a broken system, and the way to ensure this doesn#t happen is really mostly about resource mgmt in the sense of assuring it gets preferential scheduling for IO, memory + CPU. i.e. focus on ensuring the system never enters the state rather than trying to recover from something so substantially fucked...

**Comment by YHNdnzj** [comment]
Let's just close this here. The original problem is fixed by https://github.com/systemd/systemd/pull/27968 according to https://github.com/systemd/systemd/issues/26744#issuecomment-1628240782, and on modern systems dbus is simply considered never going down.

**Pull request closed without merging**
