### PR TITLE
Journal fixes

### PR DESCRIPTION
**Pull request by keszybz**
v2 of #2088 

All changes implemented as suggested and a hack for semaphore added. Let's see if this passes.

### CODE REVIEW

**Comment by poettering** [comment]
Patches look good to merge to me, but Semaphore still disagrees!

**Comment by keszybz** [comment]
Yeah, I needed to set up my own semaphore instance to debug this. Whom should I ask for access to the systemd one?

**Comment by teg** [comment]
All looks good to me (and semaphore is now happy).

**Comment by poettering** [comment]
@keszybz i think that would be @zonque. You need some account there and he'll add you iirc. @zonque?

**Comment by keszybz** [comment]
@zonque I'd like to move python-systemd semaphore stuff from under my own account to systemd semaphore account so other people can adjust it if needed.

**Comment by zonque** [comment]
@keszybz sorry for the delay, I've been on PTO.

So the Semaphore settings for user access and for build receipts are per project, so I don't see a point for merging the systemd and python-systemd projects here.

I can of course add you to the list of collaborators in Semapore though. You just need to create an account there and give me your username.

**Pull request merged**
