### PR TITLE
journald: make sure we retain all stream fds across restarts

### PR DESCRIPTION
**Pull request by msekletar**
Currently we set 4096 as maximum for number of stream connections that
we accept. However maximum number of file descriptors that systemd is
willing to accept from us is just 1024. This means we can't retain all
stream connections that we accepted. Hence bump the limit of fds in a
unit file so that systemd holds open all stream fds while we are
restarted.

New limit is set to 4224 (4096 + 128).

### CODE REVIEW

**Comment by poettering** [comment]
lgtm

**Comment by msekletar** [comment]
Hmm, this is weird. Tests seem to fail because access to ```/run/log/journal``` was denied. Also I see weird timeouts in two ninja tests. I tried running ninja tests locally and they all pass fine.

@martinpitt any idea what is going on?

**Comment by martinpitt** [comment]
I retried the s390x test yesterday, that's fine now. The amd64 test is now looping eternally, victim of switching over from autotools to meson. This is tricky to investigate, this will need some time. So I disabled the i386/amd64 webhooks for now and asked the autopkgtest infra maintainer to kill the running jobs. @msekletar, if you still have the link to the old log where this happened, please put it here, then I can have a look.

**Comment by msekletar** [comment]
Unfortunately I no longer have the log file.

**Pull request merged**
