### PR TITLE
networkd: fix commit a9381b7

### PR DESCRIPTION
**Pull request by ssahani**
If classless route not provided configure default routes.
Something went wrong in the rebase.

### CODE REVIEW

**Comment by keszybz** [comment]
Commit a9381b7 doesn't seem to be in the history of master.

**Comment by ssahani** [comment]
Sorry not sure but it show the commit 
```commit 5f04a209eae0a2a04eb60fd7235b3fcdf3cc81ba
Author: Susant Sahani <145210+ssahani@users.noreply.github.com>
Date:   Wed Nov 22 12:13:55 2017 +0530

    networkd:DHCP-client ignore default route if classless static route is set (#6885)
    
    According to RFC 3442:
    
    If the DHCP server returns both a Classless Static Routes option and
    a Router option, the DHCP client MUST ignore the Router option.
    
    fixes #5695.


```

**Comment by keszybz** [comment]
Try `git log -1 ':/networkd:DHCP-client ignore default'` on the master branch.

**Comment by ssahani** [comment]
I tried that first it says pattern not found. But of you just click enter then it shows.

**Comment by keszybz** [comment]
It shows *something*, but the point of a commit number is not to show *something*, but to show a commit number that is a part of that branch. In other words, it is not useful to say "this fixes a" on a commit for some branch, when "a" is not in the history of _that_ branch.

Try, 'git fetch origin && git log -1 ':/networkd:DHCP-client ignore default' origin/master`. If that doesn't work, something is seriously broken.

**Comment by yuwata** [comment]
5f04a209eae0a2a04eb60fd7235b3fcdf3cc81ba is the right commit hash.

**Comment by yuwata** [comment]
lgtm.

**Pull request merged**
