### PR TITLE
added systemd-echo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by vcaputo** [comment]
Useful.

**Comment by ghost** [comment]
Indeed, that's what systemd is all about

**Comment by nmiell** [comment]
```
   text    data     bss     dec     hex filename
   1607     564       4    2175     87f systemd-echo
  25550    1200     352   27102    69de /usr/bin/echo

-rwxrwx---. 1 nicholas nicholas 6.2K Aug 25 14:45 systemd-echo
-rwxrwx---. 1 nicholas nicholas 9.8K Aug 25 14:44 systemd-echo.debug
-rwxr-xr-x. 1 root     root      32K Jul 12 07:08 /usr/bin/echo
-r--r--r--. 1 root     root      96K Jul 12 07:08 /usr/lib/debug/usr/bin/echo.debug
```

**Comment by vcaputo** [comment]
@R41z You seem interested in optimization and performance in your published personal code, and willing and able to contribute to the systemd project.  Might I direct your attention to an opportunity to ply your skills and implement a sick fast index to make searching this linked list more efficient in journald?
https://github.com/systemd/systemd/blob/master/src/journal/mmap-cache.c#L452

**Comment by ghost** [comment]
may I introduce you to my clean up patch that will solve all those issues?

**Pull request closed without merging**
