### PR TITLE
logind: fix `loginctl enable-linger`

### PR DESCRIPTION
**Pull request by sourcejedi**
`man systemd-run`: "In the default configuration, users can enable
lingering for themselves".

But when I sshed in and tried it, I was prompted for the password of the
first user with `sudo` access (`wheel` group) or `root`.  Even though we
seemed to explicitly allow all uses in #3373.

After some code analysis: `XDG_SESSION_ID= loginctl enable-linger` worked
fine.

I don't know exactly why loginctl uses XDG_SESSION_ID.  But it is more
friendly anyway, if logind allows it when the value for UID is passed
explicitly, given that it would allow if it detected the same UID
implicitly after being passed UID_INVALID.

### CODE REVIEW

**Comment by poettering** [comment]
lgtm

**Comment by keszybz** [comment]
Please don't merge. I think there's other issues at play here.

**Comment by sourcejedi** [comment]
Sorry, this was the branch I hadn't tested yet, not the one where I'd tested the code but had other stuff to fix.

After the commit, `loginctl enable-linger $USER` seems to work, but it doesn't fix `loginctl enable-linger`.

It looks like it's passing UID 2, for XDG_SESSION_ID=2.

**Comment by keszybz** [comment]
Yeah, something is messed up in loginctl itself. Are you going to provide patches?

**Comment by sourcejedi** [comment]
I think I got it.  logind was also using OWNER_UID (of the system bus), when it meant effective uid.  Patches following testing.  (I say patches plural, but at least right now the _fixes_ are all smushed into one commit with a correspondingly tedious description).

**Comment by sourcejedi** [comment]
> patches follow testing

and docs, and...

It would be easier to write a less misleading message for BUS_ERROR_NO_USER_FOR_PID, if we didn't "abandon" users which have "abandoned" sessions.  It would avoid inconsistent behaviour of `loginctl kill-user` too...  <del>I think that change can be split out nicely.</del>

**Comment by sourcejedi** [comment]
ugh, now re-open is greyed out and I can't get it back, I guess I have to open a new PR.

**Comment by sourcejedi** [comment]
To be clear, the revised PR does not try to change the handling of abandoned sessions.

Retaining the ability to kill abadoned sessions of logged out users would need some way to detect when the sessions eventually stop despite that we abandoned them :).  I'm not sure you'd want logind to keep Session objects around in some form after they've been abandoned, without some more justification.

**Pull request closed without merging**
