### PR TITLE
network: wait until the underlying interface becomes up

### LINKED ISSUE #7478: systemd-networkd support for DSA ("Distributed Switch Architecture")
### Submission type

 - Bug report

### systemd version the issue has been seen with

235

### Used distribution

> Debian

### In case of bug report: Expected behaviour you didn't see

> Interface `wan` (which is linked to `eth0`) comes up

### In case of bug report: Unexpected behaviour you saw

> well, it doesn't

### In case of bug report: Steps to reproduce the problem

Networking on the EspressoBin is special: there's an internal switch. The kernel comes up with this setup:

```
# ip link
[…]
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 532
    link/ether 00:00:00:00:51:81 brd ff:ff:ff:ff:ff:ff
5: wan@eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:51:81 brd ff:ff:ff:ff:ff:ff
6: lan0@eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:51:81 brd ff:ff:ff:ff:ff:ff
7: lan1@eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:00:51:81 brd ff:ff:ff:ff:ff:ff
```
(except that initially eth0 is down)

I have two `systemd.network` files for `eth0` and `wan`:
```
# cd /etc/systemd/network; grep . *
49-switch.network:[Match]
49-switch.network:Name=eth0
49-switch.network:[Network]
49-switch.network:DHCP=no
50-main.network:[Match]
50-main.network:Name=wan
50-main.network:[Network]
50-main.network:DHCP=no
50-main.network:[Address]
50-main.network:Address=10.107.0.1/24
```
However, depending on the Gods of Random Chance, I need to restart `systemd-networkd` in order to bring up the `wan` interface. The first start only enables `eth0`.

Workaround:
```
# cat /etc/systemd/system/systemd-networkd.service.d/after-udev.conf 
[Service]
ExecStartPre=/sbin/ip link set dev eth0 up
```

### PR DESCRIPTION
**Pull request by yuwata**
This is for DSA interface, which has several stacked interfaces on the
'master' interface. To bring up a stacked interface, it is necessary
that the master is already up. See
https://github.com/systemd/systemd/issues/7478#issuecomment-348508263.

Note that a .network file for the master is still required, otherwise,
networkd does not bring up the master. Or it is necessary to bring up
the master manually.

Fixes #7478.

### CODE REVIEW

**Comment by vladimiroltean** [comment]
Note that since kernel 5.12, according to the documentation this isn't necessary any longer:
https://www.kernel.org/doc/html/latest/networking/dsa/configuration.html#configuration-showcases

**Comment by yuwata** [comment]
> Note that since kernel 5.12, according to the documentation this isn't necessary any longer: https://www.kernel.org/doc/html/latest/networking/dsa/configuration.html#configuration-showcases

> The slave interfaces depend on the master interface being up in order for them to send or receive traffic. Prior to kernel v5.12, the state of the master interface had to be managed explicitly by the user. Starting with kernel v5.12, the behavior is as follows:
> - when a DSA slave interface is brought up, the master interface is automatically brought up.
> - when the master interface is brought down, all DSA slave interfaces are automatically brought down.

Oh, nice! Thank you! Then, my PR is even not necessary, but makes the situation worse...

**Comment by yuwata** [comment]
(Note: https://github.com/torvalds/linux/commit/9d5ef190e5615a7b63af89f88c4106a5bc127974)

**Comment by yuwata** [comment]
Sorry, I mistakenly closed this when force-push. new version is #21737.

**Pull request closed without merging**
