### PR TITLE
core: add '-' prefix to AmbientCapabilities=

### PR DESCRIPTION
**Pull request by yuwata**
If AmbientCapabilities= is prefixed by '-' and the ambient capability is not supported by the kernel, then the listed ambient capabilities are ignored and the commands are executed by root.
On top of the options, networkd, resolved, and timesyncd drop the capabilities in the following commits, which are inspired by the commits in PR #6393 by @Siosm.

### CODE REVIEW

**Comment by boucman** [comment]
would a ConditionKernelFeature and multiple service files work ? (just a thought, another approch to the same problem...)

That might cause an unwanted multiplication of service files, though which might be worse...

**Comment by yuwata** [comment]
Yes, if it is implemented.

**Comment by tixxdz** [comment]
Hey @yuwata thanks for the patch, the `AmbientFallbackBoundingSet=` name is a bit strange, I don't get the full context, is the https://github.com/systemd/systemd/pull/6393 only one or there is some other links ? will review, thank you!

**Comment by yuwata** [comment]
@tixxdz Thanks. The discussion in #6421 may be helpful to understand why I add this option.

> the `AmbientFallbackBoundingSet=` name is a bit strange

Do you have any suggestion?

**Comment by yuwata** [comment]
Please do not merge this PR in this form, it is necessary to add entries in `bus_exec_context_set_transient_property()` and `bus_append_unit_property_assignment()`.

**Comment by yuwata** [comment]
The D-Bus API will be added after #6497 is merged.

**Pull request closed without merging**
