### PR TITLE
network: drop noisy log message

### LINKED ISSUE #13595: systemd-networkd writes to the log "Configured" each time, when it gets RA message
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > 5.2.14-arch2-1-ARCH

**Expected behaviour you didn't see**
 > systemd-networkd should write once "Configured" to the log.

**Unexpected behaviour you saw**
 > systemd-networkd writes "Configured" each time to the log, when it gets RA message.

**Steps to reproduce the problem**

Configure a network interface with the same address and the same gateway, which the interface gets via RA:
```
[Match]
Name=wan

[Network]
DHCP=yes
Address=2a00:1838:aaaa:2037:7285:c2ff:fe25:bc62/64
IPForward=yes
IPv6AcceptRA=true

[Route]
Gateway=fe80::204:4eff:fe87:f000
PreferredSource=2a00:1838:aaaa:2037:7285:c2ff:fe25:bc62

[DHCP]
UseDNS=false
UseNTP=false
UseMTU=true

[IPv6AcceptRA]
UseDNS=false
```

The log in debug mode:
```
сен 18 13:25:19 server systemd-networkd[10705]: NDISC: Received Router Advertisement: flags none preference medium lifetime 1800 sec
сен 18 13:25:19 server systemd-networkd[10705]: NDISC: Invoking callback for 'router' event.
сен 18 13:25:19 server systemd-networkd[10705]: wan: Configuring route: dst: n/a, src: n/a, gw: fe80::204:4eff:fe87:f000, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
сен 18 13:25:19 server systemd-networkd[10705]: wan: Configuring route: dst: 2a00:1838:aaaa:2037::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
сен 18 13:25:19 server systemd-networkd[10705]: wan: Remembering updated address: 2a00:1838:aaaa:2037:7285:c2ff:fe25:bc62/64 (valid for 4w 2d)
сен 18 13:25:19 server systemd-networkd[10705]: wan: Configuring route: dst: n/a, src: n/a, gw: fe80::204:4eff:fe87:f000, prefsrc: n/a, scope: global, table: main, proto: static, type: unicast
сен 18 13:25:19 server systemd-networkd[10705]: wan: Setting routes
сен 18 13:25:19 server systemd-networkd[10705]: wan: State changed: configured -> configuring
сен 18 13:25:19 server systemd-networkd[10705]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=27 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
сен 18 13:25:19 server systemd-networkd[10705]: wan: Routes set
сен 18 13:25:19 server systemd-networkd[10705]: wan: Configured
сен 18 13:25:19 server systemd-networkd[10705]: wan: State changed: configuring -> configured
сен 18 13:25:19 server systemd-networkd[10705]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=28 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
```

### PR DESCRIPTION
**Pull request by yuwata**
Closes #13595.

### CODE REVIEW

**Comment by ssahani** [comment]
Please put in debug mode so that we can debug.

**Comment by yuwata** [comment]
`link_set_state()` logs similar and more informative message in debugging log.

**Comment by yuwata** [comment]
Hmm, cannot connect to salsa.debian.org.

**Comment by ssahani** [comment]
Does it print configured then we can ignore else we will be guessing

**Comment by yuwata** [comment]
It certainly shows 'configured'.

**Comment by ssahani** [comment]
Then LGTM. Please merge

**Pull request merged**
