### PR TITLE
resolved: log when a bus client changes per-link DNS info

### PR DESCRIPTION
**Pull request by poettering**
Fixes: #16298

Split out of #17535

### CODE REVIEW

**Comment by yuwata** [comment]
Please use `log_link_info()`.

**Comment by yuwata** [comment]
Then, "Interface %s: " are redundant. Please drop them.

**Comment by poettering** [comment]
Ah, yes, just noticed that too. Force pushed a new version now. PTAL!

**Comment by yuwata** [comment]
LGTM.

**Pull request merged**
