### PR TITLE
resolved: Check for non-NULL before setting GNUTLS credentials

### PR DESCRIPTION
**Pull request by filbranden**
Uncovered by Coverity. Fixes CID 1393390.

cc @irtimmer 
code was introduced in #8849

### CODE REVIEW

**Comment by irtimmer** [comment]
Setting credentials for GnuTLS is required as otherwise the connection will fail. Beside theoretically t->server should always be available when using TLS, as only DNS_PROTOCOL_DNS is using TLS. And in the beginning of the function it is already accessing t->server without checks when using the DNS protocol. So it rather seems the non-NULL check for gnutls_session_set_data is unnecessary or the code is unexpectedly trying to use TLS for LLMNR.

**Comment by filbranden** [comment]
In that case, I suggest adding an `assert(t->server);` to the top of the function and changing the check `if (t->server && t->server->tls_session_data.size > 0)` below not to check for `t->server`. I'll update the PR to do that instead.

**Comment by filbranden** [comment]
Please take another look...

**Comment by irtimmer** [comment]
Maybe I wasn't completely clear, but t->server is only set if t->scope->protocol == DNS_PROTOCOL_DNS and DNS_SERVER_FEATURE_LEVEL_IS_TLS(t->current_feature_level) should only be true, if t->scope->protocol == DNS_PROTOCOL_DNS. So the assert at the current location would break LLMNR support.

**Comment by filbranden** [comment]
Ah makes sense... Sorry, I'm not familiar with the code, just trying to silence the static analysis check, since `t->server` has been dereferenced before, so that check for it does nothing...

Moved the assert down to that block, please take a look.

**Pull request merged**
