### PR TITLE
hwdb: Add sensitivity for Dell Precision pointingstick

### PR DESCRIPTION
**Pull request by khfeng**
BugLink: https://bugs.launchpad.net/bugs/1657553

### CODE REVIEW

**Comment by keszybz** [comment]
@khfeng https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1657553/comments/10 says that 0.**0**25 works better. Did you see that comment?

**Comment by khfeng** [comment]
I can burrow a Precision 7510 to do some test.
Is there any definitive way to determine what this value should be? Something like `touchpad-edge-detector`?

**Comment by whot** [comment]
sorry, this one slipped through.

there's no tool to determine the value because finger pressure on the pointing stick isn't something we can compare on an objective basis, at least not without a specialised tool that every reporter would have to have.

**Comment by khfeng** [comment]
@whot, thanks for your explanation.

So I guess it's better to let real user to decide the best value.
Update to 0.025 accordingly.

**Comment by poettering** [comment]
@whot did you see the new iteration @khfeng posted?

**Comment by whot** [comment]
@khfeng are you still setting libinput's accel speed to 1 as well? because if you do, the CONST_ACCEL factor is wrong. libinput's accel of 1 is the maximum acceleration, so if you have to set that on top of const accel (which is supposed to de/accelerate trackpoints severely off normal motion), then the CONST_ACCEL is wrong. libinput's accel factor should only cater for user-specific preferencess, and generally if you have to set it to 1 something is wrong

**Comment by khfeng** [comment]
@whot Ok, I'll grab the machine and test it again.
So what value should I use for libinput's accel? Leave it as a default?

**Comment by whot** [comment]
leave it at 0 (the default), but also have a look at https://bugs.freedesktop.org/show_bug.cgi?id=91369 first

**Comment by poettering** [comment]
@khfeng any update on this one?

**Comment by poettering** [comment]
Closing due to lack of response.

**Comment by moapwr** [comment]
something somewhere broke a lot of pointing stick acceleration stuff
the freedesktop bugreport was abandoned
still not fixed

... for me on xubuntu 18.04 on dell e7470

- xinput nows nothing about 'Device Accel Constant Deceleration'
- changing xinput 'Accel Speed' does noting
- hwdb entry does nothing

**Comment by Jeffset** [comment]
I have dell E7470, this behavior also annoys me, so I'm ready to test solutions, and respond quickly.

**Comment by whot** [comment]
Don't merge it, there's no real point. libinput 1.8  and later stopped parsing that property and there is nothing else that uses it. This is a libinput bug that will be fixed with libinput 1.12 (yes, one after next release) but I need some time to actually grasp all the various details.

Meanwhile - as said, the property does exactly nothing with anything libinput 1.8 and above (or any other driver).

**Comment by whot** [comment]
All of those should eventually go away, I'll send a PR out for that once I'm done with the libinput changes.

**Comment by poettering** [comment]
@whot any update?

**Comment by whot** [comment]
sorry, forgot about this one. TLDR: libinput 1.12 now has a magic multiplier, effectively  the same as the `CONST_ACCEL` property. See the [libinput docs](https://wayland.freedesktop.org/libinput/doc/latest/trackpoint-configuration.html).

This means that we should **not** merge any further `CONST_ACCEL` properties into systemd - libinput was the only user of it and it hasn't for quite a while now.

This also means we should, **generally**, not merge any `POINTINGSTICK_SENSITIVITY` properties into systemd. These are for exceptions where the OOTB setting is completely broken and increasing the magic multiplier in libinput leads to jaggy movement.

**Comment by moapwr** [comment]
tyvm!
trackpoint finally useable on ubuntu

**Pull request closed without merging**
